### ISSUE TITLE
update "ref" syntax to use arrows, as string refs are being deprecated

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#1000]
The React team has taken the position that string refs are bad and are going to be removed in a future version of React, so we start updating all refs in code that we're touching from things like `<element ref="thing">` (that we then reference as `this.refs.thing`) to the preferred form `<thing ref={ e => this.thatSpecificThing = e}>` (that we then access as `this.thatSpecificThing`).

**Comment by anweshknayak** [comment]
Hey I can take this up?

**Comment by Pomax** [comment]
Hi @anweshknayak, sorry for the delay: absolutely, let me know if you're still interested!

**Comment by irrationalRock** [comment]
Hi, I'm interested in this issue.
Can I take a stab at it?

**Comment by Pomax** [comment]
Closing this for now, due to tech stack updates
