### ISSUE TITLE
[PNI Regression on Staging] Speech bubble and sticky nav not working properly

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#10059]
### Describe the bug
PNI regression bugs are found on staging. Prod is working fine.

When viewing PNI homepage on small screens,
1. Speech bubble and creep-o-meter are pushed out of the viewport (further down and right) which creates x-scrollbar and extra space on the right.
2. Sticky nav is no longer sticky

### To Reproduce
1. View PNI staging on a smaller screen
2. Select a non-English locale. e.g., https://foundation.mofostaging.net/de/privacynotincluded
3. Scroll left and right. Notice where the speech bubble and creep-o-meter are. You might need to scroll down first to see them.
4. Scroll down. Notice the sticky nav is no longer sticky.

### Expected behavior
- No regression with the positions of the speech bubble and creep-o-meter.
- Page should not have x-scrollbar

### Staging Regression
https://user-images.githubusercontent.com/2896608/214968590-b130a72a-26c2-424a-b58f-a37a4e831431.mov

### Prod 

https://user-images.githubusercontent.com/2896608/214970355-63a34c88-acea-424d-9c1c-e6052be495fb.mov

**Comment by mmmavis** [comment]
Regressions on staging have been resolved by pulling the affecting code commits out from `main`.
Closing.

**Comment by tbrlpld** [comment]
@mmmavis This has been QAed on staging?
