### ISSUE TITLE
[Research Hub] Library shows protected pages

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#10081]
### Describe the bug

When visiting the research hub library page (https://foundation.mofostaging.net/en/research/library/) and there a non-public / protected page exists (https://foundation.mofostaging.net/en/research/library/alternative-data-governance-playbook/) then that page is listed. 

### To Reproduce

1. Go to the research hub library page: https://foundation.mofostaging.net/en/research/library/
2. In the admin, make one child page of the library page protected (e.g. password protected)
3. Refresh the library page
4. See see that the protected page is listed.

### Expected behavior

Needs discussion: *We should only show protected pages to logged-in users.*

**Comment by kevinhowbrook** [comment]
> We should only show protected pages to logged-in users.

I've dealt with something similar recently, and really we deemed that 'teasers' were ok to be 'non-protected' as they advertise the content and the user is prompted to login.

A fix for this won't be as simple as modifying a queryset to add `.public()`, if we are definitely sure of the expected behaviour then we will need to offer different querysets depending on the `reuest.user` (one filtered by public() and the other not)

**Comment by tbrlpld** [comment]
Good points @kevinhowbrook I agree, we need to define what the desired behavior should be.

I wonder how much we want to show protected pages in public. Not sure who to ask, but I would be confused as a user visiting the research hub and then find a page I can not access. Most users/visitors won't be editors as well. 

Outside of the check for the request user, what other considerations do you have in mind?

**Comment by kevinhowbrook** [comment]
Other considerations, only that any public API was being filtered too... e.g search results. The two querysets would be fine, just raising it so we don't create further edge cases or create unreachable content

**Comment by tbrlpld** [comment]
Staff are reporting this on production: https://mozilla.slack.com/archives/C98GW3P7X/p1675101252839289

**Comment by tbrlpld** [comment]
@kristinashu I agree, I think the most expected would be to hide protected pages in the public library. 

If we later discover we want to show it to logged in users, we can to that then. To keep it simple, we could hide all non-public pages from the library for now. 

Can you explain what "in the thumbnails" means?

**Comment by kristinashu** [comment]
Oh sorry, I mean the thumbnails on the library page. 

Yes, hiding all non-public pages from the library and search results sounds good like the right scope for this ticket.

**Comment by tbrlpld** [comment]
@kristinashu Would you mind testing this on staging? https://foundation.mofostaging.net/en/research/library/

**Comment by kristinashu** [comment]
Good, I no longer see protected pages on the library page!
