### ISSUE TITLE
Password Protected pages should be styled

### ISSUE THREAD

**Issue by kevinhowbrook** [mozilla/foundation.mozilla.org#10082]
### Describe the feature request
I think it would be nicer for editors if we styled the password-protected page here https://foundation.mofostaging.net/en/research/library/alternative-data-governance-playbook/

This was picked from https://github.com/mozilla/foundation.mozilla.org/issues/10081

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-117)

**Comment by mmmavis** [comment]
This is how the password protected page look like:

![Image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/84558ce8-c954-4bb1-9438-30d92a76f5b1)

It's a good idea that we style this page so visitors don't feel like they just landed on a random page.

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Tyler Denton Considering that this ticket has been around since Jan 2023, we could remove for the time being until we have an actual request on this matter.
