### ISSUE TITLE
React Google Analytics are not being initialized

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1012]
STR: 
1. Visit https://foundation.mozilla.org/sign-up/
2. Click on form field
3. Observe warning in browser console.

Expected behavior: It should log the GA event. This is the same problem on Petition components (https://foundation.mozilla.org/campaigns/aadhaar/take-action)

Remember to keep Do not track in mind, I'm not sure if initializing the react GA component respects the normal GA DNT functionality baked in elsewhere.

**Comment by ScottDowne** [comment]
An error happens on page load too.

"Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”."

I think that's likely our issue.

**Comment by ScottDowne** [comment]
Yeah something's not making sense. The error I pasted above doesn't fire in chrome, but nothing still seems to work. On donate, I get the pasted error in Firefox, yet things still seemingly work. So I'm probably wrong about the pasted error having anything to do with things, but still kinda curious as to what it is.

**Comment by ScottDowne** [comment]
I also don't see donate being initialized. But it's likely the way we manually load GA might be how we solved that. Still digging.

**Comment by ScottDowne** [comment]
Turns out it was super simple, just needed to update react-ga version: https://github.com/mozilla/foundation.mozilla.org/pull/1078

**Comment by alanmoo** [comment]
Looks like this has been addressed on production by Scott's PR.
