### ISSUE TITLE
Video embeds not rendering on mozillafestival

### ISSUE THREAD

**Issue by kevinhowbrook** [mozilla/foundation.mozilla.org#10133]
### Describe the bug
Vimeo embeds are not working here:
https://mozillafestival.mofostaging.net/en/
https://mozillafestival.mofostaging.net/en/issues-and-spaces/

This _may_ have been buggy before the wagtail upgrade as a video here is fine https://foundation.mofostaging.net/en/blog/

### To Reproduce
1. Go to 'https://mozillafestival.mofostaging.net/en/'
2. Click on a video
4. Video fails to load
5. Debug console shows CSP error

**Comment by kristinashu** [comment]
The video works for me on production https://www.mozillafestival.org/en/ so it seems like it's a new issue

**Comment by mtdenton** [comment]
This seems like a staging issue, it may have never worked on staging. Dev tools:
![csp](https://user-images.githubusercontent.com/41487159/218155935-d837f1c0-89c1-486f-a435-a5f44c9f14f6.JPG)

CSP directives are stored in environment variables in Heroku.

**Comment by danielfmiranda** [comment]
Hi @kevinhowbrook!

Tyler appears to be correct that this was a CSP issue. I have updated the `CSP_FRAME_SRC` env variable in staging to now include vimeo and it seems to be working for me.

Can you please take another look at the page and let me know if everything is working as expected? Thanks!

**Comment by kristinashu** [comment]
The videos work for me now too!
