### ISSUE TITLE
Remove `ul` css reset

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1014]
In `resets.scss` we're resetting the styles of `ul` elements so they don't have a bullet. This makes the Wysiwyg editor confused, as it expects lists to have bullets. Can we remove the reset?

**Comment by alanmoo** [comment]
(I just did a test, straight up removing this causes bullets to appear in the mobile navigation, so we probably need to comb the site a bit to figure out how to best accomplish the goal of "make the wysiwyg editor indicative of what the user will see on the final page")

**Comment by alanmoo** [comment]
Partial fix was landed in #1058. Gavin, I'll let you make the call if this should stay open or not.

**Comment by gvn** [comment]
What you did with adding back the bullets for CMS added/wrapped LIs is what I intended to do, so I'm fine with closing this.
