### ISSUE TITLE
[Fellowship Pages] FAQ

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1015]
**Context:**
Currently, our individual fellowship pages (all 4 of them) mention an FAQ - for what I remember, we decided (Alan, Matthew and I) to go for a simple FAQ page (reusing the template of 1 column of our "Opportunity" pages). 

@auremoser I am wondering if you see the need for an FAQ page and if so, @alanmoo do we need a mockup for this page (since it is based on an existing template, I was not sure if it is necessary)?

_Comment from Amy (from [this doc](https://docs.google.com/document/d/1iiQ5lTFpAbEvRMYcNx9DqvaTmVjCE-AHwYh4PMtvveg/edit?usp=sharing)): "I wonder if an FAQ page should be for version 2 as we get a better idea of what questions people still have after reading the website. I'd say probably 1 faq page for all fellowships since we're not sure how much more we'll need to share at this point. Thoughts?"_

Screenshot for reference:

![faq](https://user-images.githubusercontent.com/22157921/35525971-ea9b126c-04da-11e8-9ec5-9207b93f071c.jpg)

**Comment by alanmoo** [comment]
The cynical view on an FAQ page is that if it needs to exist, the content strategy isn't tight enough. So unless we actually have a set of FAQs that aren't just "content that we can't figure out where else to put it", it would be great if we could just not build it for now.

**Comment by auremoser** [comment]
I think we can make that work (delaying the creation of an FAQ).

We've had them in the past on the Advocacy and Science sites and I do think they were helpful, but we always recieve many questions anyway, and I develop some templates for how to respond to typical ones. We could try going FAQ-less this year, and treat it as a lesson-learned for next year if that doesn't pan out.

Science: https://science.mozilla.org/programs/fellowships/faq
Advocacy (this page is currently "hidden" on the site though): https://github.com/mozilla/advocacy.mozilla.org/blob/master/src/pages/open-web-fellows/info.js

For now, we can direct folks to fellowships@mozillafoundation.org with questions, and the Fellowships team can triage thereafter.

**Comment by taisdesouzalessa** [comment]
Okay, thanks for the input here, Aurelia and Alan. I removed the FAQ link from the pages' comps and used only a "contact us" link, that will point to the email "fellowships@mozillafoundation.org"

<img width="842" alt="image" src="https://user-images.githubusercontent.com/22157921/35586420-a6774a8a-05af-11e8-95d5-316f8e1a954b.png">

I think this solves this ticket so I am closing it. Feel free to reopen it if you think there are things left to be discussed.
