### ISSUE TITLE
Write tests for campaigns and petitions

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1016]
In our rush to get petitions working, we didn't add proper tests. Let's do that.

**Comment by Pomax** [comment]
Do we want to create a general testing issue to keep track of "what needs tests still"?

**Comment by gideonthomas** [comment]
@Pomax good idea, can we just morph this ticket into that? If you know what needs tests, can you edit @alanmoo's comment above to reflect that?

**Comment by alanmoo** [comment]
I created #2539 to contain everything. Let's keep this one to campaigns/petitions

**Comment by Sharma-palak** [comment]
Hi @alanmoo,I want to work on this issue.Since I am new to open source I may need your help.

**Comment by alanmoo** [comment]
Unfortunately we don’t have the capacity to support someone new to open source on a ticket like this, which requires deep understanding of the project.

@pomax based on our conversation last week, should we close this and open a few more specific testing issues?

**Comment by Pomax** [comment]
This is probably related to https://github.com/mozilla/foundation.mozilla.org/issues/2786 in the sense that we need to figure out whether or not we want "tests" or whether we want an actual real world bannered campaign page to act as our test case.

Either way, this feels like an issue we should close, as it will pop up naturally in the course of figuring out a new/improved test approach
