### ISSUE TITLE
Responsive fellowships nav

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#1019]
Make sure the nav we have for fellowships site works and is responsive. 

@taisdesouzalessa can you give me a ping once the comps are finalized? Thanks! 😄

**Comment by taisdesouzalessa** [comment]
Hey @mmmavis they are ready to go: https://drive.google.com/file/d/1ZqIVpHwzx9AWk9Ef4l22VD82FK4yYWoi/view?usp=sharing

This to consider: content still not 100% yet, we may have some few feedback pieces here and there - but styling and structure seems ok, I'll let you know if anything changes as soon as I know.

Next step: working on assets

**Comment by mmmavis** [comment]
For more details about how the nav should work see

- https://github.com/mozilla/foundation.mozilla.org/issues/977#issuecomment-360321769
- https://invis.io/Z4FGLVDEP3W#/275358045_TEST2-MOBILE_-_FellowshipsUI_-_Overview_Copy

**Comment by mmmavis** [comment]
Closing!
Work has been merged into the main `fellowships` branch.
