### ISSUE TITLE
[Fellowship site] Full email displayed on the site

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1023]
Currently in our site we have some situations in which the full email is displayed (like "fellowships@moz..."):
<img width="758" alt="image" src="https://user-images.githubusercontent.com/22157921/35711741-48525844-0773-11e8-9d33-d07adabdc7ea.png">

I find it is a big address to have there but I think it is necessary, right @mmmavis and @alanmoo? I am curious about your thoughts or any past experiences you may have in displaying full emails on pages.

**Comment by mmmavis** [comment]
That's a long email address. Not sure if it can fit in one line on mobile 👀

**Comment by alanmoo** [comment]
My 2¢: It's useful to actually see the address you're emailing (as it is here), so you can copy/paste if necessary. I don't think it's too long if the mobile view is just text from left to right (as presumably the image would be above/below the text block?).

I give less than one 🥄 though; do whatever you think works.

**Comment by taisdesouzalessa** [comment]
Thanks for your feedback here, Mavis and Alan.

I used the browser inspect tool and placed it in a similar component of the current site just to have a more realistic view of this issue. It fits okay in a small viewport (320px). So that addresses one of the concerns we had about being long. I like the idea of allowing users to copy and paste the email address since this page if for host orgs and funders (the easy we can make for them to contact us, the better) so I'll keep the full address on this page. 

<img width="397" alt="image" src="https://user-images.githubusercontent.com/22157921/35746887-3f80b8ca-07fd-11e8-8158-51228e2fc797.png">
