### ISSUE TITLE
Opportunity Page - move navigation up

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1028]
From https://github.com/mozilla/foundation.mozilla.org/issues/1013

Move the side nav up on desktop view so the top to the nav lines up with the top of the title (so the order on desktop is main nav, dropdown, title, then content).. 

Please keep mobile as it is now (so the order on mobile is main nav, title, dropdown, then content).

Example: there is a faint blue guideline to show how they should line up

<img width="822" alt="screen shot 2018-02-02 at 11 09 00 am" src="https://user-images.githubusercontent.com/1068783/35750411-bf10c18c-0809-11e8-9b41-ebb245b7156b.png">

Notes from @alanmoo:

@anweshknayak the opportunity pages are based on opportunity.pug as a template, which gets generated into landingpage.html which is used as a django template.

This seems like it should require only markup changes in 2 files: opportunity.pug and campaign.html. (It's a bit confusing the way it runs right now, and we do need to clean that up so they're using a similar template. But that's a separate issue)

**Comment by anweshknayak** [comment]
@kristinashu thanks 😃 On this.

**Comment by alanmoo** [comment]
@anweshknayak I'm in the middle of doing something that actually takes care of this for Campaign pages. Hold off on those for now, and maybe on Opportunity pages until my commit lands

**Comment by kristinashu** [comment]
@alanmoo now that https://github.com/mozilla/foundation.mozilla.org/issues/977 is done, can @anweshknayak work on this?

**Comment by alanmoo** [comment]
Yes! @anweshknayak if you rebase off master, you'll see that there's been some updates to campaign and landing pages. They both need this update applied.

**Comment by anweshknayak** [comment]
@alanmoo @kristinashu will look into it 😃 thanks

**Comment by kristinashu** [comment]
Any updates or problems here?

**Comment by anweshknayak** [comment]
@kristinashu Sorry. haven't had the time to look into this :smiley: . I will try to fix this asap.

**Comment by gvn** [comment]
@anweshknayak Are you still planning on doing this?

**Comment by kristinashu** [comment]
@gvn Anwesh is busy with GSOC now and won't be able to do this, will you be able to?

**Comment by gvn** [comment]
Sure

**Comment by gvn** [comment]
@kristinashu This is on staging now if you want to take a look

**Comment by kristinashu** [comment]
Looks good!
