### ISSUE TITLE
CMS pages - List styles don't work

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1035]
### I've added bulleted list in the CMS:
<img width="1008" alt="screen shot 2018-02-06 at 5 16 31 pm" src="https://user-images.githubusercontent.com/1068783/35893166-a40b8d76-0b61-11e8-9438-cf81f87dc227.png">

### But it don't show up on production:
<img width="1274" alt="screen shot 2018-02-06 at 5 16 40 pm" src="https://user-images.githubusercontent.com/1068783/35893167-a431f894-0b61-11e8-95f5-9846c6f5a418.png">

### Is there a way to have the bullets show up?

cc @gvn

**Comment by mmmavis** [comment]
Related: https://github.com/mozilla/foundation.mozilla.org/issues/1014

**Comment by kristinashu** [comment]
[Global Sprint site](https://foundation.mozilla.org/opportunity/global-sprint/for-site-hosts/) is heavily reliant on bulleted lists and option-8 isn't cutting it!  
<img width="952" alt="image" src="https://user-images.githubusercontent.com/1068783/36175575-d294ad86-10c4-11e8-9c5a-fd1a877a89cd.png">

cc @alanmoo @gvn
