### ISSUE TITLE
Detail page - Limit child page types to article and publication

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#10361]
## Description

Currently, research detail pages can have any page as a child page. This does not make much sense and can make it hard for editors to select the correct type. 

We might want to limit this to a few sensible options. E.g. publication page and article page. 

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Designs](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?t=zoMb9zxg25R0T6yt-6)

## Acceptance criteria

- [x] As an editor, when adding a child page to a research detail page, I can add an article page or a publication page. 
- [x] As an editor, when adding a child page to a research detail page, I don't see any other options except the one listed above.

**Comment by tbrlpld** [comment]
@kristinashu Does this sound sensible to you?

**Comment by danielfmiranda** [comment]
Hi @kristinashu! This is now on staging and ready for QA. I was wondering if you could please take a look whenever you find a free moment? Thanks in advance!


## Steps to test:

1. Visit any detail page, for example, "[Shifting power through data governance](https://foundation.mofostaging.net/cms/pages/18276/edit/)"
2. Click "Add Child Page"
3. There should now be 2 options, "Article Page" and "Publication Page"
![image.png](https://images.zenhubusercontent.com/6046b7f1bc36adc9ce95a16a/f535b954-08e5-42f1-a1da-dbe0ee2962cb)
4. If everything looks as expected, testing is complete!

**Comment by kristinashu** [comment]
This is working well, thank you!
