### ISSUE TITLE
Design a loading icon / animation

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#1045]
On Fellowships minisite's Directory page, we get fellow profile data from Pulse API client-side.

### Problem

When you visit the Directory page, you see a blank page with only the page header "Fellows Directory". There's no loading indication while data from Pulse API is being retrieved. Retrieval time can take a few seconds depends on the connection. 

/cc @taisdesouzalessa

**Comment by taisdesouzalessa** [comment]
@xmatthewx you okay if I assign myself this task? I would love to work on it.

**Comment by taisdesouzalessa** [comment]
After @mmmavis  and I did some brainstorming, it seems we were leaning more on what's presented on slides 5 and 6. 
https://docs.google.com/presentation/d/13dl3c8Ar2lHf15gmI6lXtSNV0i9L8JI6qUQpI6M1ETw/edit?usp=sharing

**Comment by xmatthewx** [comment]
I should have thought of this before, but we have a loading icon on Pulse already. It works well and I think it'll get the job done for this. Any reason to not use that?

**Comment by taisdesouzalessa** [comment]
I think we did that to align with the foundation site aesthetics (green, with the dots). It was just a touch to make it a little bit more aligned with the visual of the site. Does that sound right to you @mmmavis?

If we don't have the time for this now, could we add the "enhancement" label to it so we tackle this later on?

**Comment by xmatthewx** [comment]
We do need some kind of indicator so users aren't confused now. I would just keep the task as simple as possible.

**Comment by taisdesouzalessa** [comment]
Are you suggesting we use the same as Pulse for now? If so, I am cool with that.

**Comment by xmatthewx** [comment]
You two can decide if that keeps it simple and it does the job.

**Comment by mmmavis** [comment]
Done! Fix has been merged into the main fellowships work branch "`fellowships`". See loading icon in action: https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/directory/
