### ISSUE TITLE
Bring clarity to campaign and opportunity page navigation

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1047]
In order to make it clearer where a user is on the site, we want to do two things:

1.) On opportunity and campaign pages (if a page level is > 2) the parent's title should be visible at the top of the main content (as a heading). Below it, the page heading should appear (larger).
  1b.) On mobile, the page heading is hidden because the navigation has it.
2.) In the side navigation menu, we should remove parent pages, so that only siblings of the current page show up. (This is accomplished by changing some logic in lines 4-6 of `side-menu-items.html`) 

With this change, we are going to need to copy the content of existing top-level opportunity and campaign pages into their own mini-site:

* for each top-level campaign/opportunity page without children, we do nothing.
* for each top-level campaign/opportunity main page with child pages, create a new page called "overview" as child page, and copy the content from the main page over into the overview page,
* set the Meta Data "URL" field for overview pages to `opportunity/{main-page-url}`, so they will act as mini-site entry point
* set the Meta Data "URL" field for the parent to blank, but leave them published,
* change the Meta Data "URL" field of the rest of the sub-pages to `opportunity/{parent-page}/{sub-page-name}`

**Comment by kristinashu** [comment]
Here's some background, based on design in https://github.com/mozilla/foundation.mozilla.org/issues/1029

## Navigation problems on Productions right now:
1) When I user lands on a subpage they have no way to orientate themselves (i.e. on a site about Aadhaar, Global Sprint, or Web Lit), particularly on mobile.
2) On mobile, the subpage title is doubled up.

![global sprint home copy 6](https://user-images.githubusercontent.com/1068783/36054012-0a587eec-0da9-11e8-8174-224d1d47f8fd.jpg)

## Solution:
1) Add a persistent "mini-site" title to every page.
2) On mobile, hide subpage title.

[Redpen comps](https://redpen.io/p/myec85141a1f7a03a5)

![global sprint home copy 4](https://user-images.githubusercontent.com/1068783/36053869-62f88278-0da8-11e8-9278-c9c86c15babe.jpg)
![global sprint home copy 5](https://user-images.githubusercontent.com/1068783/36053870-6310c7de-0da8-11e8-93f2-3d692086ca35.jpg)

**Comment by kristinashu** [comment]
@gvn let me know if you have any questions!

**Comment by kristinashu** [comment]
So nice to see this! https://foundation.mofostaging.net/opportunity/web-literacy/

We will have to updated all the CMS pages on Production when this gets pushed. @alanmoo @gvn can you teach the designers what we will need to do? 

### Here's an WIP list of todos for creating/updating CMS pages:
(No clue if what I'm saying is correct so please review and update this list)

#### For Parent page (i.e. Web Literacy, Aadhaar, Global Sprint):
- Make sure both the Title and Header are the same (the name of the mini-site that will appear at the top of every page)
- Update page to Draft
- Delete URL name

#### For all Sub pages (i.e. Core Curriculum, Take Action, Register):
- Create a new subpage:
  - Move all the content currently on the Parent page to this new page
  - Call this new page something like "Overview" or "About"
  - Update the URL to the Parent page name???
- For all other Subpages: Make sure both the Title and Header are the same (one appears nav while another appears in dropdown nav and heading on page)
- Make sure all subpages are Published

**Comment by alanmoo** [comment]
This has been promoted to production and the database updated appropriately.

**Comment by xmatthewx** [comment]
There are a couple differences between the design and the build that hamper usability. 

Should we open a new ticket @kristinashu with a checklist to update? Related to this, we should look at how we are using this subnav on the fellowship pages, and decide on how it is similar / different. Is it above or below the header? 

<img width="711" alt="image" src="https://user-images.githubusercontent.com/53411/36555568-6c2ffba0-17d0-11e8-870f-0cd495683b16.png">

**Comment by gvn** [comment]
This is getting a little long, so if you want to open a QA ticket that'd be rad!

**Comment by kristinashu** [comment]
I have opened a new ticket https://github.com/mozilla/foundation.mozilla.org/issues/1090.
I will add comps and context to that ticket then assign to engineering.
