### ISSUE TITLE
Create Web Literacy Curriculum Landing Page (on Production)

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#1048]
### Description

The design and planning ticket is here: https://github.com/mozilla/foundation.mozilla.org/issues/985
We need to implement the Web Literacy Curriculum landing page and subpages on the CMS on Production. Pages need to be copy and pasted over. It is currently on staging https://foundation.mofostaging.net/opportunity/web-literacy/ and we will need to move it to https://foundation.mozilla.org/opportunity/

Alan mentioned:

> If something’s set to “published”, it can be viewed by anyone on the web (on both staging and production, just at different URLs). If something’s ‘draft’, you can only view it if you’re logged in to the CMS. Pages that are on Staging can’t be immediately copied to production, they need to be manually copied over using the web interface. So if you’re building something that’s more than a test page, you should be building it on production, set as a draft. *We don’t back up the staging server, so work in-progress there isn’t securely stored, and there’s always a chance we could need to wipe the staging database if something gets there with a bug.*

**Comment by sabrinang** [comment]
cc/ @xmatthewx @zee-moz

**Comment by sabrinang** [comment]
@anmechung Just following up on this, is the copy for Web Literacy Landing complete on the staging site? Let me know if you help by copying/pasting it over to production. I just want to make sure the content is complete so I can help refine any layout/graphics.

**Comment by anmechung** [comment]
@sabrinang per slack convo I added clipart images to each of the activities.  Feel free to substitute other images, especially for all the stickerz - there is probably a better graphic than a suitcase with stickers.  Maybe laptop with Mozilla stickers? We are missing description for one activity that will be added tomorrow (Safety First).  Graphics/layout definitely need your refining touch!  Copy/past over to production first before this? or after?

**Comment by anmechung** [comment]
@sabrinang How does one navigate to the core curriculum page from the main web literacy page?

**Comment by xmatthewx** [comment]
Hi. We've made slight change in how parent/child pages are arranged. 

I recommend you move this content over to the production site now instead of on staging ... they can remain as drafts. There's no need to use staging. 

When you move things over, @alanmoo can describe to do it for new set up.

**Comment by sabrinang** [comment]
@anmechung I moved the content to https://foundation.mozilla.org/opportunity/web-literacy/ and included classes to style all headings and reformatted the alignment of the curriculum image sections. This took longer than I anticipated so I'll be refining the imagery tomorrow but feel free to go in and fill in the rest of the placeholder copy on production.

**Comment by xmatthewx** [comment]
@alanmoo - can you check these new parent-child pages for sub nav? 

@sabrinang - i believe we now use an empty parent page, and put parent content in a new child page sorted to the top.

**Comment by alanmoo** [comment]
@sabrinang A side effect of the recent parent-child page structure is that you have to go into the meta data of each of the subpages and remove the `-1` from the URL.

**Comment by sabrinang** [comment]
Thanks for the feedback @xmatthewx @alanmoo I have cleared the parent page and removed the -1 suffix from the subpages

**Comment by anmechung** [comment]
@sabrinang I added new activity to Read - Get Friendly with your Browser. Could you add a pic?  Thx

**Comment by anmechung** [comment]
@sabrinang I replaced placeholder copy in Additional Resources.  A few things:
- Do you have art/design/expression/ activities that could be added?
- This is where I think we should make a link to the videos https://www.kollaborate.tv/link?id=5970c622a244d unless you have other ideas.  I believe that Jesse was looking for the credentials to Youtube site, but not sure if he located them yet. 
- Tips: text heavy.  I could do more editing, but not sure how much that helps.  Any suggestions for how to make it less text heavy looking?

**Comment by anmechung** [comment]
@sabrinang A thought on the tips: I could turn into a blog and link to it?

**Comment by sabrinang** [comment]
@anmechung For copy, I think it’s a good suggestion to move the long tips list to a blog post and link it below the title **Tips from Web Literacy Leaders**. I also suggest that we link https://medium.com/read-write-participate/introducing-mozillas-web-literacy-leaders-c7f230d0e4dd below the title as well instead of part of the title (it’s a bit unconventional and not obvious that there is a link in the heading). I also updated the heading styles on this additional resources page.

Another feedback for copy is on the **Core Curriculum** page, there is another Additional Resources section that mentions “You can browse these here” but it doesn’t link to anything. Unsure if it is suppose to link to the Additional Resources page or not.

For the videos, it would be great to host this where a password isn’t needed each time but I still don’t think we have found the credentials for Youtube yet. I’m not sure how I can further help in terms of video.
