### ISSUE TITLE
Spin up new petition for baby monitors

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1050]
Create a standard petition form (like equifax) and associated single page campaign on production pointing at the petition.

@gideonthomas and @ScottDowne can you coordinate to make sure you're both familiar with how to do this from start to finish? Ping me if you need help with creating the campaign page itself.

I believe the aim is for this campaign to go live in the first half of this week.

**Comment by ScottDowne** [comment]
I added a petition form to the page we have in the foundation site.
