### ISSUE TITLE
Remove "Sign up" from site header

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1051]
The master "Sign up" in the global site header is confusing on opportunity pages, and hasn't been a major factor in list signups. Let's remove it for now, and we can revisit how we use it as we rework the site.

**Comment by taisdesouzalessa** [comment]
I like this idea! Interesting to learn it hasn't been a major factor in signups too.

**Comment by kristinashu** [comment]
Thanks for doing this! Global Sprint peeps just flagged this again today.
