### ISSUE TITLE
Update Profile card to separate type from program

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1054]
Each profile will have two types of info that connect a person with Mozilla. This was previously one field. 

@taisdesouzalessa @kristinashu - We need to separate this in UI for profile cards on both Pulse and Foundation site.

Let's assume that some fields can be blank. Examples: 

Name: Aurelia
Type: Staff
Program: _________

Name: Maya
Type: Fellow
Program: Open Web

Name: Katherine
Type: _________
Program: MozFest Speaker

Notes: there is no need to label this info on the cards. Type will be fixed and highly controlled by us. (staff, board, fellow, ...). Program will be loose, with staff adding new ones as needed.

**Comment by kristinashu** [comment]
Talked with @taisdesouzalessa about this and if we understand you correctly, we think the best way to display this is to separate Type and Program with a `,`  . Keeping them in that order and using the m icon. 

Examples:

Aurelia
Staff

Maya
Fellow, Open Web

Katherine
MozFest Speaker

Are we still planning to show the Fellowship year?

Here's a quick mockup for Pulse:
<img width="1015" alt="screen shot 2018-02-16 at 9 42 58 am" src="https://user-images.githubusercontent.com/1068783/36321185-cf6b229e-12fd-11e8-9571-2d7e020a5cc7.png">

**Comment by taisdesouzalessa** [comment]
I will work on this today, probably in the afternoon. I think showing Fellowship year is important so users can easily find their cohort (one of the goals of the site was to facilitate connections and exchange of info between them).

**Comment by xmatthewx** [comment]
This is weirdly complicated. 

 1) Year: There's a weird thing with how years are engineered. I can't remember why, but it's not attach to the program name. Until that changes, if a person has more than program (Tech policy, MozFest Speaker) we can't know which happened when. (@alanmoo I know we said this won't matter until 2019, but I think we should expect to fix this before MozFest) We should probably skip displaying years for now. (the directory can still group and filter by year)

 2) Type fail: Another scenario.... `Sally K, Fellow, MozFest Speaker, Science`. We can't force an order on programs. I wonder if we should not display type and be more verbose with programs. i.e. `Sally K, MozFest Speaker, Fellow in Science`. We will still use type to group and filter in the directory, but should maybe not display it. 

I wish this were less weird. I don't know the best solution. I'm open to any suggestions on how we can simplify. We could enforce 1 and only 1 program per person. Too limiting? Or, have a field just to identify fellowship program, and a separate field for all other programs. That might be the best solution given the unique nature of fellowships.

**Comment by alanmoo** [comment]
+1 for leaving the display complexity out of this. Assume one "categorization" per person; when we add support for multiple, you can just show the most recent/top one on the admin list.

**Comment by taisdesouzalessa** [comment]
After meeting today (Alan, Matthew, Kristina, Taís) we decided to keep the UI as per Kristina's mockup from above, adding the year. Example: Fellow, Open Web 2017 - [Program], [Area] [Year] - feel free to edit this comment if you think something is missing.

**Comment by taisdesouzalessa** [comment]
Here is a mockup for Fellows, with the data applied:
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/22157921/36498820-5f14e3f4-16f4-11e8-8bbe-de5623692aef.png">

The Fellowship pages prototype was updated to reflect this decision:
https://invis.io/ZJ9YTAGEA#/276734820_v2-FellowshipsUI_-_Fellows_Directory

**Comment by kristinashu** [comment]
Looks good @taisdesouzalessa!

Here's the Pulse version with the year added:
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/1068783/36510504-13119190-1718-11e8-920c-62bfb8d9fc08.png">

@xmatthewx is this all you need from us? Could you open the implementation tickets? I'm not sure of all the nuances involve.

**Comment by xmatthewx** [comment]
I started a ticket for frontend. It'll need some attention before we begin, but we're not ready to implement this just yet. https://github.com/mozilla/network-pulse/issues/929
