### ISSUE TITLE
Figure out where to store assets for Fellowships minisite

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#1056]
### Context
Fellowships work is built using Django templates. There are image assets that we need to add to the pages and we are wondering where to store them. In the [repo](https://github.com/mozilla/foundation.mozilla.org/tree/master/source/images)? Or S3 bucket?

Would love to know what you think @cadecairos @gideonthomas @alanmoo @gvn

**Comment by gvn** [comment]
So far all non-CMS managed images are added to the repo and statically served from Django:

See: https://github.com/mozilla/foundation.mozilla.org/tree/master/source/images

**Comment by mmmavis** [comment]
Talked to @alanmoo on stand today, and we decided to put assets on the repo for now (like what we've been doing)
