### ISSUE TITLE
Wagtail migration plan

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1065]
We've started to evaluate Wagtail as a replacement for Mezzanine. Let's figure out how we can do that. More items will be added along the way, but let's agree that this is the basic approach we're taking

- [x] Create branch of foundation site with Wagtail installed, standing next to Mezzanine at different URLs
- [x] Confirm this branch works in production, make changes if necessary (no custom wagtail models necessary yet)
- [x]  Merge this into master, so that we don't end up with a massive merge later on
- [x] Start adding Wagtail apps to the project with new page models, so that we can eventually stand up a parallel set of pages to the existing ones
- [ ] Add S3 support for Wagtail uploaded images
- [x] ¿Copy existing S3 images to the right spot for Wagtail to use them?
- [x] Ensure the wagtail admin login is wired up to support Google Auth login
- [x] Identify how we'll migrate pages during an admin shutdown (manually? A script? I'm feeling like a divide and conquer manual approach might be quicker than debugging a migration script)
- [x] Do that migration
- [ ] Remove mezzanine

Output from this ticket: Once we have agreement, we can convert these to issues and close this ticket.

**Comment by gideonthomas** [comment]
just mentioning again here, we shouldn't just add wagtail page models. We should create new apps that will contain new wagtail page models.

**Comment by alanmoo** [comment]
Yes! I clarified the original post

**Comment by Pomax** [comment]
We can nest apps, correct? So we could do something like:
```
-- network_api
 |-- campaigns
 |-- cms
 | |--capaigns
 | |--highlights
 | |-- landingpages
 |-- highlights
 |-- langindpages
 |
```

**Comment by alanmoo** [comment]
Highlights are a django model, so they can stay in the same spot, no?

To potentially be phone-call discussed and then reshaped when it has more coherence:
This makes some sense, but I also wonder if we really need to create a new app for every page template within Wagtail, or if we should have a "generic pages" app that houses campaigns and landing pages. Or maybe we create that next to these others (which are themselves effectively clones of the Mezzanine models), with the "generic pages" using Streamfield

**Comment by Pomax** [comment]
let's not forget s3 images~

**Comment by gvn** [comment]
> let's not forget s3 images~

Can you say more?

**Comment by Pomax** [comment]
there is no checkbox for making sure image updates and asset hosting through S3 works with wagtail, the way it currently works with mezzanine. We had to write [our own](https://github.com/Pomax/filebrowser_s3) library to make that work, but I've seen some articles that suggests we won't have to do that again for Wagtail, so making sure we capture it as an essential step's a good idea.

**Comment by alanmoo** [comment]
Updated

**Comment by Pomax** [comment]
On the google login front, things turned out to be incredibly simple. thanks to wagtail's very sensible way of dealing with page templates. All I had to do was create an override on the login.html file that extends `wagtailadmin/login.html` with an `<a href="{% url "social:begin" "google-oauth2" %}?next=/cms">`, similar to what we already have for Mezzanine. As long as the google clientid+secret are set correctly, things just work.

**Comment by Pomax** [comment]
Official docs on wagtailin' with S3: https://wagtail.io/blog/amazon-s3-for-media-files/

**Comment by Pomax** [comment]
I've filed https://github.com/mozilla/foundation.mozilla.org/pull/1071 so we can do a review-app review, although @cadecairos or @gideonthomas may need to set that review app environment to match what we use in production, and hook up a google+ api enabled credential set for gauth (clientid/secret/callbackurl)

**Comment by kristinashu** [comment]
Migration ✅

Can we close this?
