### ISSUE TITLE
Add event tracking to petition page template

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1066]
We're now directing campaign traffic to pages like [/campaigns/equifax-breach/](https://foundation.mozilla.org/campaigns/equifax-breach/). We need to add analytics tracking to better understand conversion, bounces, and traffic that continues onto the site. 

We have event tracking set up already on our sign up form, so this can follow that pattern.

Element | Category | Action | Label
-- | -- | -- | --
petition send button | petition | form submit tap | [page title] - pettion submit
petition share button | petition | share tap | [page title] - share tap

cc @alanmoo to triage

[spreadsheet](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=779058050) of other events on pulse and site for reference.

**Comment by vojtechmzl** [comment]
Just flagging that there is an existing issue #1012  form with the sign up form events, which are currently not firing

**Comment by alanmoo** [comment]
The form sign up events appear to now work properly, so we can add this tracking.

**Comment by gvn** [comment]
I'm seeing an event wired for form submit already:

```js
    ReactGA.event({
      category: `petition`,
      action: `form submit tap`,
      label: `Petition form submitted`
    });
```

I think it only fires when the form is successfully validated...do you want it to always fire when a user clicks on the button even if the form is invalid?

Also...I don't see any social share buttons. Should I?

**Comment by alanmoo** [comment]
There should be one social share button right now in `petition.jsx`, and the rest are coming as part of #1038

**Comment by xmatthewx** [comment]
the social buttons appear after submitting the petition. @ScottDowne is revising that now. 

good question. i think that's okay. this will fire if it passes validation, but server fails? later, we should consider events for validation failure and server failure, because we currently depend on a human to notice and report it.

**Comment by ScottDowne** [comment]
@gvn to answer your first question, I think sending the event on success is probably more useful, so if that's already there this is probably now a super low priority.

However, in the past, I have sent events if the form fails and with the type of validation error they got, but I don't think it's ever been useful? I normally would just consult vojtech on what events he wants.
