### ISSUE TITLE
SPIKE - Explore AI Intersections Database Information Architecture & Salesforce Integration

### ISSUE THREAD

**Issue by Gbaldassano** [mozilla/foundation.mozilla.org#10739]
### **Context:**
The insights team is interested in turning the Ai Intersections Database into a user-facing tool. More info here: [PROJECT PLAN: AI Intersections Database Build](https://docs.google.com/document/d/1tDiSgskpD_2NUDHMLgwoah2QjPRyeeQH-YLf5uiaDzo/edit#)

This project is divided up in two phases.

Phase 1 |  Quick Win
What: Make the current database easy to update, get permission from current actors to appear in database
Why: Fast, relatively inexpensive, upgrades experience, prepares for Phase 2
This phase is in progress and falls mostly to the Insights and CRM team to implement.

Phase 2 | Long-term Success 
What: Develop full update with automated workflows that’s integrated into the forthcoming CRM with a user-friendly, external-facing frontend
This phase needs more discovery/scoping to determine a solution and involves design/engineering. 

### Request:

**The goal of this ticket is to:**

- Explore how to best to represent the information architecture of the database in Salesforce and the website. Right now, it seems that the Information Architecture of the database is an open question. This needs more investigation as that will inform any front end changes.

- Provide guidance (i.e., design/engineering best practices) on what a user-friendly, external-facing frontend would look like to help scope and inform the timeline for Phase 2.

### Acceptance Criteria
There are no hard and fast acceptance criteria for this issue because it is a spike issue.

The goal would be to have to have follow-up tickets created that handle the actual work to implement Phase 2 or clear next steps on contacting third-party web developer to build.

**Comment by Gbaldassano** [comment]
As discussed in sprint planning  - First step should be to diagram/lay out how things are

**Comment by Gbaldassano** [comment]
@mtdenton think we can close this?

**Comment by mtdenton** [comment]
@Gbaldassano yep I think we're good to go here, will follow up as needed
