### ISSUE TITLE
Fellowships - Fellow Profiles

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#1074]
Two main questions...

## Which fellows do we want to feature on certain pages on the Fellowships minisite?

Pages we want to feature fellows on...

### 4 on `/fellowships`

e.g., (staging link) https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/

### 1 on `/fellowships/science`

e.g., (staging link) https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/science/

### 1 on `/fellowships/open-web`

e.g., (staging link) https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/open-web/

### 1 on `/fellowships/tech-policy`

e.g., (staging link) https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/tech-policy/

### 1 on `/fellowships/media`

e.g., (staging link) https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/media/

### 1 on `/fellowships/support`

e.g., (staging link) https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/support/

### List of [fellow profiles](https://github.com/mozilla/foundation.mozilla.org/issues/955#issuecomment-357941019)

Make sure all the meta are filled out on Pulse backend

- `profile type` set to `fellow`
- `program type` needs to be specified (e.g., senior fellow, science fellow, etc)
- `program year` needs to be specified (e.g., 2016, 2017, etc)
- `location`
- `bio`
- `profile photo` (needs to be cropped into square)
- (optional) Twitter, LinkedIn links
- (optional) what internet health issues fellow is interested in

/cc @alanmoo

**Comment by annmarie123** [comment]
4 fellow front page: An Me, Amba, Linet, Orlando. 
1 science - Chris
Open Web - Freddy
1 media - Hang
1 tech policy - Gigi Sohn
Support - Host Org Photo

**Comment by annmarie123** [comment]
Also, all film footage links, photo content, and mozfellow bios can be found in this drive: https://drive.google.com/drive/folders/0B6_ZVUFx2WHHMFEwSlRCZDZIZjg

I am currently updating the Mozilla Bios with their project updates from a couple weeks ago (can comment when finally updated: https://docs.google.com/document/d/1_NUF0dMWsgvsPuOLCA1qFnYANadKaiO6123_suTjfYU/edit

Social Media + Linkedin Links for all fellows (including alumni) can be found here: https://docs.google.com/spreadsheets/d/1y_J9EI_Grxd9omK-HivMZErixPaEvia7frHiOJ25zTY/edit#gid=0

**Comment by annmarie123** [comment]
@mmmavis 
All the info you requested including pictures of the fellows for the fellows spotlight can be found here: https://docs.google.com/document/d/1a2eS4UZxq-_0b06VlTpj9y_8eTORwFl9-uJgn3qiE3o/edit?usp=sharing

**Comment by taisdesouzalessa** [comment]
@annmarie123 - is it okay if we replace some of those pictures, using the ones from this folder instead? https://drive.google.com/open?id=11Tr-49LVoZrzPkFhrMQQEfgWskIRrpiI

**Comment by annmarie123** [comment]
@taisdesouzalessa YES PLEASE REPLACE THEM!

**Comment by alanmoo** [comment]
I believe we can close this since we've ditched those other pages. Re-open if you disagree.
