### ISSUE TITLE
Opportunity/Campaign pages: heading inconsistencies

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1083]
Pulling this out of the bigger ticket from @sabrinang https://github.com/mozilla/foundation.mozilla.org/issues/1021

Heading styles on Opportunity/Campaign pages need to match the rest of the site. For example, h3 on these Opportunity/Campaign pages should be the same as h3 on the main site (i.e. be Zilla rather than Nunito).

The spacing on Opportunity/Campaign also makes it hard to read and scan content.

[Example: About page is great how there is a larger vertical space above the title than below (helps group the title with the content below)](https://foundation.mozilla.org/about) 

<img width="844" alt="screen shot 2018-02-01 at 10 23 52 am" src="https://user-images.githubusercontent.com/1068783/35695669-172cf53c-073a-11e8-80ef-4a7ed096afda.png">

[Compared with the CMS pages where the spacing is the same and it takes more mental effort to group the content](https://foundation.mozilla.org/campaigns/aadhaar/aadhaar-challenges-and-the-path-forward/)

<img width="844" alt="screen shot 2018-02-01 at 10 24 13 am" src="https://user-images.githubusercontent.com/1068783/35695670-1748f53e-073a-11e8-8dad-71df2759fdf9.png">

Designers have been able to force some of the styles by editing in the Mezzanine code editor https://foundation.mofostaging.net/opportunity/cms-styles/ but it is very time consuming and the spacing is still off, forcing us to use lots of `<p>&nbsp;</p>`

cc @gvn @Pomax @alanmoo not too sure who would be able to work on this?

**Comment by alanmoo** [comment]
This might be work that has to be re-done once we move to Wagtail, so we probably shouldn't sink too much time into it unless there's big wins that can be made with low effort. This feels like something for @gvn's plate, with @Pomax on support with respect to what approach we might take with Wagtail/Streamfield

**Comment by kristinashu** [comment]
I'm going to close this since Pomax will be doing this in Wagtail.
