### ISSUE TITLE
Generate sitemap for SEO

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1088]
Once we've got wagtail up and running, we should generate a sitemap so pages not in the navigation have better visibility on search engines.

**Comment by Pomax** [comment]
This isn't too hard, but does raise the question "if we don't want to expose them on the site, why should they show up in search engines"? Ideally any page we care to have show up in search results is a page that you can reach by navigating the site itself.

**Comment by Pomax** [comment]
turns out we also have https://github.com/mozilla/foundation.mozilla.org/issues/1696 open to cover (part of) this work.

**Comment by alanmoo** [comment]
Seems like they're complete duplicates- what's different?

**Comment by Pomax** [comment]
This one is for a solution for SEO purposes, the other issue was for making a sidemap available for dev/stage only, because we want a way to find out which routes the CMS thinks exists, so we can do dev testing based on those.

**Comment by Pomax** [comment]
@alanmoo we should probably revisit this, especially in terms of how we want to mark pages as "don't show up in the sitemap that external parties get to see"

**Comment by alanmoo** [comment]
I'm ok with us leaning more on private pages for that kind of thing.

**Comment by xmatthewx** [comment]
Our site is pretty well crawled. Google knows about 358 pages. A few thoughts: 

 - As @alanmoo noted when he opened this issue, a sitemap might help with staff pages that aren't promoted well, particularly getting them known and accessible by search more quickly. 
 - I've been reading up on "site links" (other pages suggested be google  - see image below). I wonder if a sitemap can help google's opaque sauce to optimize those.  
 - Sort of related to sitemaps, there's a way to [provide search with breachcrumbs via json](https://developers.google.com/search/docs/data-types/breadcrumb). 
 - Lastly, digging through web master tools, I'm glad to see that google understands our localization and that /about is the canonical url for /en/about.  

<img width="676" alt="image" src="https://user-images.githubusercontent.com/53411/57941730-b433c100-789d-11e9-9fdf-2becc6df47ad.png">

**Comment by cadecairos** [comment]
I'm not sure we need a sitemap, given the potential gain.

**Comment by xmatthewx** [comment]
@cadecairos - This has value for SEO. I've added it to a list of small projects that we could potentially add on to a larger contracted project.
