### ISSUE TITLE
Subnav UI fixes on Opportunity/Campaign

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1090]
Follow up from: Bring clarity to campaign and opportunity page navigation #1047

There are a couple differences between the design and the build that hamper usability. 

#### Subnav on opportunity/campaign pages, please:
- [x] Reduce vertical space around the mini-site title
- [x] Reduce width of dropdown box

<img width="711" alt="image" src="https://user-images.githubusercontent.com/53411/36555568-6c2ffba0-17d0-11e8-870f-0cd495683b16.png">

**Comment by gvn** [comment]
@kristinashu This is on staging now if you want to take a look

**Comment by kristinashu** [comment]
This first part is done. The second is better at medium widths but on mobile the dropdown is still full width. 

Screen cap on iPhone:
<img width="427" alt="screen shot 2018-03-08 at 10 37 26 am" src="https://user-images.githubusercontent.com/1068783/37169455-c4c8660c-22bc-11e8-8c7a-ca4173d95cd6.png">

**Comment by gvn** [comment]
@kristinashu Should be fixed now on staging. Can you verify?

**Comment by kristinashu** [comment]
@gvn looks good!
