### ISSUE TITLE
[QA Fellowship mini-site] missing icon on mobile view

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1092]
Issue:
In mobile view (iPhone7, Safari) the "info icon" is not displayed in the [Fellowship homepage](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/):
![image](https://user-images.githubusercontent.com/22157921/36622433-f62cdd64-18b1-11e8-92dd-cf3517bc3736.png)

**Comment by mmmavis** [comment]
@gvn the missing icon is from font-awesome. Do you think it's worth loading the entire font-awesome CSS given that this is the ONLY font-awesome icon we use on the foundation site? If not I guess we can just export that icon into SVG.

**Comment by taisdesouzalessa** [comment]
I am on it! Will do that today and post the svg here :). Thanks, team.

**Comment by taisdesouzalessa** [comment]
@mmmavis here is the svg for this icon:
<img width="86" alt="image" src="https://user-images.githubusercontent.com/22157921/36702569-827bf6cc-1b0c-11e8-9e05-a18146873d30.png">

[info-icon.svg.zip](https://github.com/mozilla/foundation.mozilla.org/files/1760681/info-icon.svg.zip)

**Comment by mmmavis** [comment]
Done!
