### ISSUE TITLE
[QA Fellowship mini-site] testimonial bottom spacing + lines

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1095]
Issue:

On the pages we have testimonials, is it possible to remove the grey line and margin-bottom of the element (mb-5) so we decrease the size of the spacing and remove the unnecessary line?

It happens on: Science and Open Web pages

<img width="497" alt="image" src="https://user-images.githubusercontent.com/22157921/36623136-f411fb86-18b6-11e8-99de-650ef6beff7f.png">

<img width="338" alt="image" src="https://user-images.githubusercontent.com/22157921/36623148-203e682a-18b7-11e8-8023-259392b788c4.png">

**Comment by mmmavis** [comment]
As per discussion with @xmatthewx and @taisdesouzalessa yesterday - we have decided to remove  testimonial section from pages. We'll add them back once we have all the content we need for that section (fellow meta + quote).
