### ISSUE TITLE
[QA Fellowship mini-site] Testimonial is narrower in mobile than expected in Support Page

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1097]
Issue: for some reason, the testimonial card doesn't go all the way to the side margins ([Support the Program](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/support/) page):

<img width="322" alt="image" src="https://user-images.githubusercontent.com/22157921/36623418-71b2717c-18b9-11e8-915f-758f0bb5c3e4.png">

**Comment by mmmavis** [comment]
As per discussion with Matthew and Tais yesterday - we have decided to remove this section from page. We'll add it back once we have all the content we need for that section (fellow meta + quote).
