### ISSUE TITLE
Add share buttons to petitions admin page

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/foundation.mozilla.org#1098]
With https://github.com/mozilla/foundation.mozilla.org/pull/1038 landing, we need to add fields for links to share buttons in the petitions model.

@alanmoo how do we want to deal with the existing share link field in the admin? We can leave it as it is (might be confusing if others use it) or we can disable the field so that no new share links can be added but existing ones will work.

**Comment by alanmoo** [comment]
Disable it in the admin

**Comment by alanmoo** [comment]
Test test. Ignore me.

**Comment by gideonthomas** [comment]
This is done
