### ISSUE TITLE
Figure out how to remove the `unsafe-inline` CSP rule for scripts

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/foundation.mozilla.org#1099]
We either set it for django admin or for mezzanine, not sure. But this CSP rule is also being set for user facing pages (e.g. petitions, opportunities, etc.) which isn't great. Let's try to figure out if we can remove it entirely or at least isolate them to the features that actually need it.

**Deliverable 1**: Research output of what happens when we remove it and list of pages that it is required for.
**Deliverable 2**: Implementation - Either we can't do this or we remove it entirely or we isolate it to pages that need it.

**Comment by Pomax** [comment]
This still seems relevant - wagtail needed it for a while because of its image browser, but as far as I know that got fixed, so we should revisit this and see if we can remove these CSP rules now.

**Comment by harshs14** [comment]
hi @Pomax, I am new here, can I take this up if no one is working on it and can u explain me on how to solve this

**Comment by gideonthomas** [comment]
@Pomax is this still something that's worth pursuing or give up on this?

**Comment by Pomax** [comment]
Wagtail apparently still relies on this, so.... closing with a sigh.
