### ISSUE TITLE
Fallback style for news with no image

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1100]
On the homepage, if the left news item has no image, it looks a bit broken. It would be good to have a fallback background color or gradient. 

@gvn will take a look for requirements. 

@sabrinang or @kristinashu can help with design of asset.

**Comment by gvn** [comment]
There currently is no thumbnail specified for the featured news item on the homepage, thus the missing image.

For a default we can use any image format, but I'd recommend SVG if it's vector based or JPG if it's a photo.

**Comment by kristinashu** [comment]
We could use the blue to green gradient. This should be the fallback for News and also Happening Now section.

**Comment by kristinashu** [comment]
Opened a bigger ticket to create fallbacks for all cms images https://github.com/mozilla/foundation.mozilla.org/issues/2416
