### ISSUE TITLE
Add featured fellows to fellowship homepage

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1109]
From https://docs.google.com/document/d/1a2eS4UZxq-_0b06VlTpj9y_8eTORwFl9-uJgn3qiE3o/edit#heading=h.c3j8ww1sgwj8.

This involves creating Pulse profiles for them if necessary, adding the content from the doc, and then pulling that content into the foundation site (even if it's a static import of the copy/pasted JSON to start)

**Comment by mmmavis** [comment]
Done. I decided to just hardcode all 4 profiles content in because currently only one of these four featured fellows have profile on Pulse... and we aren't able to create profiles for the other 3 due to tech difficulties (in Pulse API context: they are "creators" that don't have a profile)
