### ISSUE TITLE
[Fellowship Mini Site] Placeholder Image

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1114]
### Issue
Some of our Fellows don't have a profile picture and the site looks broken when all the Fellows are seen side by side in the directory page:
<img width="815" alt="image" src="https://user-images.githubusercontent.com/22157921/36759376-023f944e-1bcc-11e8-8c18-1899843f2aa2.png">

### Solution
To have a placeholder image to accommodate those cases, so we give all Fellows the opportunity to stand out in our interface, no matter if they chose to have a profile picture or not.

**Comment by taisdesouzalessa** [comment]
Here is the proposed placeholder:

Fellowship Mini Site:
<img width="865" alt="image" src="https://user-images.githubusercontent.com/22157921/36760319-30775d08-1bcf-11e8-9b0b-9835c2d96911.png">

Pulse:
<img width="834" alt="image" src="https://user-images.githubusercontent.com/22157921/36760376-6c046636-1bcf-11e8-8e05-bf7d3b966bcb.png">

This is just a quick design fix, for now, we could do studies and tweaks if we desire, in the future. @xmatthewx @kristinashu you comfortable with this solution?

**Comment by kristinashu** [comment]
Perfect @taisdesouzalessa!

**Comment by xmatthewx** [comment]
😀

**Comment by mmmavis** [comment]
Looks great!

**Comment by xmatthewx** [comment]
@taisdesouzalessa when you have the asset ready, please share in pulse repo as well: https://github.com/mozilla/network-pulse/issues/881

**Comment by taisdesouzalessa** [comment]
@mmmavis here is the asset to be used as a placeholder for those who don't have a profile picture:

![profile-placeholder](https://user-images.githubusercontent.com/22157921/36802673-6ea7b366-1c6a-11e8-9e4d-e00a840c9f66.jpg)

**Comment by mmmavis** [comment]
Done! https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/directory/
