### ISSUE TITLE
[Fellowship mini site] Replace content

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1115]
@mmmavis @jessevondoom here is the mockup with the new content from [this doc](https://docs.google.com/document/d/1irQDK5IrRRuBa_Bq4sVOkaD9iHIYxD-cPyUGY_UOuY8/edit?usp=sharing)

https://invis.io/ZJ9YTAGEA#/281947967_v2-FellowshipsUI_-_Overview

I have some questions related to that:
1. Are we keeping the box for applications open/closed? If not, let me know and I will remove from the comp.
<img width="505" alt="image" src="https://user-images.githubusercontent.com/22157921/36766184-9f2aa998-1be9-11e8-9452-2553f8ad2419.png">
<img width="479" alt="image" src="https://user-images.githubusercontent.com/22157921/36766190-a8874082-1be9-11e8-926a-6317cbd76905.png">

2. In the section "Why become a Fellow", first bullet point, the CTA says: "Meet the Mozilla Fellows, current and emeritus."
<img width="485" alt="image" src="https://user-images.githubusercontent.com/22157921/36766232-d5f7ee72-1be9-11e8-9058-e2e79c16729e.png">
However, it will take the user to a page that has only 2017 Fellows (https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/directory/) - Could we change the copy to reflect the right expectation for the users? The past Fellows page will exist. However, it is accessible after user hits "See all [area] Fellows". Does that make sense? @KevZawacki I am adding you here to get your opinion on this copy :).

Once we have answers on those items, I can send assets to Mavis to build the page. Also, please let me know if you have any feeback on the page.

**Comment by KevZawacki** [comment]
Hi @taisdesouzalessa, 

The page looks fantastic! Re: 2) Agreed. Let's change the copy to simply "Meet the Mozilla Fellows."

And, one small tweak to the copy beneath the header "Fellows keep artificial intelligence accountable": Can you remove the word "Conducted" in the last sentence? Thanks!

**Comment by jessevondoom** [comment]
How do you feel about keeping the "Applications are open" box and just changing the copy to say "Ready to become a Mozilla fellow? Apply today." — let's us keep the call-out but not worry about the close date.

**Comment by taisdesouzalessa** [comment]
Implementation ticket:  #1120
