### ISSUE TITLE
[Fellowship mini site] New "Apply Now" Page

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1116]
As per talk with @jessevondoom and @mmmavis, we are removing the "Learn More" from the apply page.

Here is the comp:
https://invis.io/ZJ9YTAGEA#/276734812_v2-FellowshipsUI_-_Apply-Applications_Open

 Jesse, please let us know if you are okay with this page as is now or if you need any changes :).

**Comment by mmmavis** [comment]
I'm trying to remove any section that has broken links or placeholder (lorem) copy so we can ship this soon - I've already made some changes to fellowships pages right after our call today: https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/apply/

I removed "learn more" links as well as the bottom 2 CTA blocks

- "Apply Here" - I'm not sure where we are linking users to
- "Contact Us" - no copy was provided + not sure where to link users to after they click "contact us"

I can add these back if we have copy / info in hand already.

**Comment by taisdesouzalessa** [comment]
Hey @mmmavis the "Apply Here" button is important because it takes users to the Fluxx form. Currently, it is the only place that takes users to the application form so I would keep it in the interface (even if we don't have a link yet) so we won't forget about this important detail.

Also, I think we should keep the "contact us" - if I am not mistaken it will take users to send an email to fellowships@mozillafoundation.org - is that correct @jessevondoom @alanmoo @auremoser?

**Comment by auremoser** [comment]
I'm o.k. with contact us --> fellowships@mozillafoundation.org

+1 that'll probably be the link, thanks Tais.

**Comment by mmmavis** [comment]
@jessevondoom can you help provide copy for the intro paragraph? Or should we just remove it for now?

**Comment by jessevondoom** [comment]
It's not the best bit of copy I've ever written, but here's a rough stab at copy for the top of the application page. @KevZawacki do you have some suggestions/clean up?

> Becoming a Mozilla Fellow will give you access to resources and people, amplifying your work and centering you in the movement for a healthy Internet. Fellows are based all around the globe and work on specific focus areas to build a more open and inclusive Internet for all. If you're passionate about one of these focus areas we want to hear from you.

**Comment by KevZawacki** [comment]
@jessevondoom This is copy that appears on the fluxx page and provides context?

We could re-purpose copy from the Fellowship site. So:

_Mozilla Fellowships provide resources, tools, community and amplification to those building a more ​humane​ ​digital​ ​world. During their tenure, Fellows use their skill sets — in technology, in advocacy, in law — to design products, run campaigns, influence policy and ultimately lay the groundwork for a more open and inclusive internet. 

Mozilla Fellows hail from a range of disciplines and geographies: They are policymakers in Kenya, journalists in Brazil, engineers in Germany, privacy activists in the United States, and data scientists in the Netherlands. Fellows work on individual projects, but also collaborate on cross-disciplinary solutions to the internet’s biggest challenges. Fellows are awarded competitive compensation and benefits._ 

If that's too long:

_Mozilla Fellowships provide resources, tools, community and amplification to those building a more ​humane​ ​digital​ ​world. During their tenure, Fellows use their skill sets to design products, run campaigns, influence policy and ultimately lay the groundwork for a more open and inclusive internet. Mozilla Fellows hail from a range of disciplines and geographies and are awarded competitive compensation and benefits._

**Comment by mmmavis** [comment]
@KevZawacki the placeholder content we would like to replace is on the Apply page of the Fellowships minisite. I've attached a screen cap and color the placeholder in red.

<img width="1127" alt="screen shot 2018-03-01 at 2 39 18 pm" src="https://user-images.githubusercontent.com/2896608/36873785-6125dbd8-1d5e-11e8-9f5e-015a8fc2a3fd.png">

**Comment by KevZawacki** [comment]
@mmmavis Ah, gotcha. Thanks! In that case, I propose:

Mozilla Fellowships provide resources, tools, community and amplification to those building a more ​humane​ ​digital​ ​world. During their tenure, Fellows use their skill sets — in technology, in advocacy, in law — to lay the groundwork for a more open and inclusive internet. Mozilla Fellows hail from a range of disciplines and geographies, and are awarded competitive compensation and benefits.

**Comment by taisdesouzalessa** [comment]
@mmmavis could we add the yellow button back and the "Contact Us" link (that will link to fellowships@mozillafoundation.org)?

**Comment by mmmavis** [comment]
@taisdesouzalessa yup I got a PR up for you to review! https://github.com/mozilla/foundation.mozilla.org/pull/1127

**Comment by taisdesouzalessa** [comment]
Issue has been addressed. Closing this ticket. Feel free to reopen it if needed.
