### ISSUE TITLE
[Fellowship mini site] "Applications Closed" Page

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1117]
### Issue
If applications are closed, users were supposed to see the page below. However, we don't have copy for that. @jessevondoom do you think we could have some copy for this section? Should I ask Amy?

cc: @mmmavis 

https://invis.io/ZJ9YTAGEA#/276734813_v2-FellowshipsUI_-_Apply-Applications_Closed

<img width="666" alt="image" src="https://user-images.githubusercontent.com/22157921/36766584-5eacccaa-1beb-11e8-89e6-a8472527d55b.png">

**Comment by mmmavis** [comment]
Ummm... I wouldn't worry about content for the "application closed" version of this page yet since it will probably be weeks or months until we show this version of page to public. True?

**Comment by jessevondoom** [comment]
Yeah this is far off. Let's make a note that we'll need copy but I wouldn't even think about this right now.

**Comment by taisdesouzalessa** [comment]
We already found a solution for this one. Closing the issue.
