### ISSUE TITLE
Twitter share for campaign pages does not have a lot of context

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/foundation.mozilla.org#1118]
If you share a campaign page on twitter, you see this:

![twitter-share](https://user-images.githubusercontent.com/197334/36802577-4f812300-1c83-11e8-8ff9-ea8f02afdd4d.png)

We need to figure out what we're missing here. Maybe a description? I dunno.

@xmatthewx

**Comment by xmatthewx** [comment]
So page template needs another OG tag?

CMS generates a description meta field that authors can edit. We could use that, though it will probably rarely be useful text. We should consider a specific share field for authors, maybe using meta description as fallback.

**Comment by ScottDowne** [comment]
@xmatthewx So I'm not exactly sure how we want to make the share better, or what's even possible, but yeah, I'm guessing OG tags are part of this.

I don't use Twitter ever, so not sure what people normally expect to see in a twitter share.

**Comment by kristinashu** [comment]
Looks like this has been updated?!
<img width="620" alt="image" src="https://user-images.githubusercontent.com/1068783/39020937-80fab91e-43e3-11e8-8763-57e886012413.png">
