### ISSUE TITLE
[Fellowship mini site] new 'homepage' content implementation

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1120]
@mmmavis - this page is ready to ship! 

InVision file: https://invis.io/ZJ9YTAGEA#/281947967_v2-FellowshipsUI_-_Overview
Doc file: [this doc](https://docs.google.com/document/d/1irQDK5IrRRuBa_Bq4sVOkaD9iHIYxD-cPyUGY_UOuY8/edit?usp=sharing)

here are the assets:
1. Group picture has changed dimensions "Why become a Fellow" (it was a square, now it is a rectangle to accommodate new content). [Link to the asset](https://drive.google.com/open?id=1KzgPJDJoAYnDvkd7KhB0Qqz85q3dvvAJ)
2. All svgs used in this page [are here](https://drive.google.com/open?id=178x7FtDEX3y_plm2irftituGaQTfdbGS). Names of the files: "illustration-personal-data.svg", "illustration-open-scientific-research.svg", "illustration-connect-unconnected.svg" and "illustration-artificial-intelligence.svg"
3. [Sketch file](https://drive.google.com/open?id=15st_Yd-GS4nAFgqqp-ci8QU1g4pWLdWr): please notice that the copy of the grey box "Applications are open" changed (as per Jesse's suggestion)
 
NOTE: for mobile view, let's keep as we have it in the live version: illustration on top of copy.
Also please notice the titles follow the pattern of the "[Support the Program](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/support/)" page

<img width="894" alt="image" src="https://user-images.githubusercontent.com/22157921/36807124-ec6875cc-1c76-11e8-8659-90cf5c588ba9.png">

**Comment by mmmavis** [comment]
Updated.
