### ISSUE TITLE
[Fellowship mini site] Cropped hero image (responsive view)

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1124]
### Issue
In some views of the site, the hero image is cropped:
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/22157921/36862255-1f56f8e0-1d3b-11e8-9155-3ad32940b522.png">

@mmmavis I wonder if we could have a fix for that. It is not urgent, you and I could work together to figure out viable alternatives to this issue later on, what do you think? 

@xmatthewx tagging you here to capture your thoughts on it as well :)

**Comment by mmmavis** [comment]
I can write some custom CSS to make this look better.

It's very hard to have this gradient + line art + photo hero banner look good on *all* screen sizes without adding a ton of dirty CSS code. The horizontal lines and photo combo is making this troublesome to implementation. (just a note for future reference)

**Comment by mmmavis** [comment]
Fixed.
