### ISSUE TITLE
Web Literacy - Interactive Web Lit Map 

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#1130]
We previously have the interactive web literacy map on https://learning.mozilla.org/en-US/web-literacy. @anmechung is inquiring if this can be added to https://foundation.mozilla.org/opportunity/web-literacy/

This is outside the scope of the CMS capabilities and filing this ticket for discussion as I am unsure how it was built and if it is compatible to be moved to the foundation site or when we have resources to do so.

cc/ @xmatthewx

**Comment by xmatthewx** [comment]
This will have to be considered along with all the other migration that Sydette is leading, and that's going to take time. I'm guessing it's unlikely that we will have the engineering resources to rebuild and maintain this, but maybe there's a way we can archive it.

**Comment by Pomax** [comment]
It feels like this issue can be closed due to our use of foundation.moz having changed, but I'll leave this up to @xmatthewx to decide on.

**Comment by kristinashu** [comment]
Because this doesn't line up with our new priorities I think it is unlikely we will be able to do this. I'm going to close but please reopen if needed.
