### ISSUE TITLE
Where to upload videos for web literacy core curriculum

### ISSUE THREAD

**Issue by anmechung** [mozilla/foundation.mozilla.org#1131]
@jessevondoom What's the status of the Youtube channel to upload the videos that accompany the web literacy core curriculum? I know you've been on the lookout for this for awhile - thus, what alternatives would you suggest if  credentials for the Youtube channel can't be located? @zee-moz @sabrinang @xmatthewx

**Comment by sabrinang** [comment]
The how-to curriculum videos are linked on the Web Lit resources page: https://foundation.mozilla.org/en/opportunity/web-literacy/additional-resources/

The videos have been uploaded to the main Mozilla youtube channel on March 15, 2018 so the playlist is here: https://www.youtube.com/playlist?list=PLYiaJo7rYNXL_tVqcZnMJealHjuTjTVma

I'm unsure who uploaded it though and which credentials were used though. Closing issue.
