### ISSUE TITLE
[Fellowship Mini Site] Remove "Senior Fellow" as filter item in directory

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1133]
### Issue:
We currently have "Senior Fellow" as an area in the directory filter but no "Senior Fellow" category below.
<img width="745" alt="image" src="https://user-images.githubusercontent.com/22157921/36920461-97f23e74-1e15-11e8-803c-ae731ac8fafb.png">

### Solution:
The team decided to remove the "Senior Fellow" label for now. 

cc: @jessevondoom

**Comment by mmmavis** [comment]
@taisdesouzalessa 

This is because we have no pulse profiles marked as "senior fellows" on the backend. Do you know if we are planning to enter any on Pulse backend? If not, I'll remove the filter from the Fellowship page so it doesn't attempt to fetch senior fellow profiles from Pulse API.

**Comment by taisdesouzalessa** [comment]
@jessevondoom's suggestion was to remove the filter for the soft launch. So I guess we could do that.
Any concerns here, Jesse?
Also are the "Senior Fellows" labeled as something else as well (like Science, Open Web...)? Just to make sure we are capturing them on the page.

**Comment by xmatthewx** [comment]
@mmmavis Let's remove "senior fellow" as option in pulse admin https://api.mozillapulse.org/admin/profiles/programtype/1/change/

**Comment by mmmavis** [comment]
kk gotcha, I'll have a PR up for this soon!

**Comment by mmmavis** [comment]
Fixed!
