### ISSUE TITLE
[Fellowship Mini Site] Add link to Fluxx application

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1134]
### Issue
In our "[Apply to Be a Fellow](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/apply/)" page we have a button ("Apply to Be a Fellow Today") that is currently not working as expected because we need the Fluxx link
<img width="861" alt="image" src="https://user-images.githubusercontent.com/22157921/36920601-038d2842-1e16-11e8-8faf-48c3a983c7ee.png">

### Solution
Add the Fluxx link as soon as we have it. This is **very important** since this is the only place that will take users to applications.

Please @auremoser and @annmarie123 let us know when this link is ready? I'll leave this ticket open to make sure we don't forget :) Feel free to reassign this to other people or remove yourself if it makes more sense.

**Comment by auremoser** [comment]
I've asked Kalpana to make the application link the following: https://mozilla.fluxx.io/apply/2018fellows

I'll have more details next week when we have a draft of the fluxx site. Will update when I know.

**Comment by taisdesouzalessa** [comment]
@xmatthewx recommended we change the copy of this button for now until we have the link:
"Application Coming Soon"

@mmmavis I can take care of it, okay? Will create a PR tomorrow.

**Comment by auremoser** [comment]
Update here: just confirmed with Kalpana that this will be the link for the Fluxx application: https://mozilla.fluxx.io/user_sessions/new

It looks bland, but that's because they'll need to register in Fluxx before they select which grant application they're applying to, we'll provide them with a link to an application guide (a doc with instructions about how to apply in Fluxx in our blog posts.

**Comment by xmatthewx** [comment]
That URL is fine for the button. For emails @auremoser, you can now use https://mzl.la/fellowship-application.

**Comment by taisdesouzalessa** [comment]
Based on the conversation we had here #964 - this page has now a new content:
[landing page content](https://docs.google.com/document/d/13QFhketbtk2oJAwJdFrNj4GDvdIltN_1OtiWcsQqg2c/edit) 

This is the agreed flow:
`"Apply to Be a fellow:"` button--> `Intermediary Page on Foundation site`: with [landing page content](https://docs.google.com/document/d/13QFhketbtk2oJAwJdFrNj4GDvdIltN_1OtiWcsQqg2c/edit) --> `Application:` [Fluxx application](https://mozilla.fluxx.io/user_sessions/new)

The new content required some changes in the layout. Aurelia mentioned that there are still some edits to be made to the copy, here is the comp I have on this page so far. 

https://invis.io/ZJ9YTAGEA#/276734812_v2-FellowshipsUI_-_Apply-Applications_Open

Feel free to give your feedback on InVision @auremoser @xmatthewx @jessevondoom  - and add more stakeholders as needed. 

**Aurelia, could you please let me know once all adjustments on copy are made so I can transfer them to the comp?**

Some recommendations and questions:
- I would suggest we link the Funding Partners to their sites. Aurelia, could you (or somebody from your team) please provide the links for the excerpts highlighted in blue? If you disagree, let me know and I will remove the text links.
<img width="964" alt="image" src="https://user-images.githubusercontent.com/22157921/37234857-1bda0ef8-23af-11e8-9443-683a321c3a3d.png">
- I feel it is a good idea to provide a link to Contact Us on this page, since it is the page the audience is deciding to apply. Aurelia if you agree, could you (or somebody from your team) please provide a copy for this text blurb? I feel the current copy doens't fit into the new page model anymore.
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/22157921/37234904-6ce9930e-23af-11e8-97f3-bbc4949e4c03.png">

**Comment by auremoser** [comment]
Yes, I will most def let you know about copy changes. 

For the funding partners, here are the URLs, we can also include logos if you think those are appropriate? I've put together all the [logos here](https://drive.google.com/drive/folders/1626JMdhQmAEXRFOygTlO0RYezaZjQLPi?usp=sharing) and it might be nice to feature them as "grey-ed out" logos
* Mozilla Foundation - https://foundation.mozilla.org/
* Ford Foundation - https://www.fordfoundation.org/
* Siegel Family Endowment - http://www.siegelendowment.org/
* Helmsley Charitable Trust - http://helmsleytrust.org/
* Netgain Partnership - https://www.netgainpartnership.org/

How about?
"Any further questions about fellowships at Mozilla? [Contact us](mailto:fellowships@mozillafoundation.org). `<- link to fellowships@mozillafoundation.org.`"

**Comment by taisdesouzalessa** [comment]
Hey @auremoser it seems this page has a new copy now, I created a new clean ticket for it okay?  #1193
I'll add the Fluxx link there and your suggested "Contact Us" message
Closing this ticket, feel free to reopen if needed.

**Comment by auremoser** [comment]
O.k. @taisdesouzalessa , thanks for letting me know. Hopefully the funder refs will still be useful to you somewhere!
