### ISSUE TITLE
[Fellowships Mini Site] Draft and plan "Application closed content"

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1135]
### Issue
Once our applications close, we should have a plan in place to:
1. Replace the banner on the Fellowships home page
2. Have a new content on "fellowships/apply" page

<img width="967" alt="image" src="https://user-images.githubusercontent.com/22157921/36921140-187f01ec-1e18-11e8-85e5-a23896d86d1e.png">

InVision mockups for those stages:
[Item 1](https://invis.io/ZJ9YTAGEA#/276734811_v2-FellowshipsUI_-_Overview_Applications_Closed)
[Item 2](https://invis.io/ZJ9YTAGEA#/276734813_v2-FellowshipsUI_-_Apply-Applications_Closed)

@jessevondoom @xmatthewx @community-impact - I am keeping this issue open as a reminder for us :)

**Comment by alanmoo** [comment]
This is happening soon. Do we have a plan yet?

**Comment by community-impact** [comment]
We touched base with @jessevondoom earlier this week. He was going to check to see if we could replace the "apply" button with an email capture. The plan is not to change any of the main body text (except to take out the call for applications reminder in the middle of the page).

Can we:
1) Change the text on the bottom to to "Applications for 2018-2019  Please input your email and we will send you info when applications are open" and then
2) Change the yellow button to "input your email here" (If embedding an email capture is not possible, can we link to a Google form to capture that info?)

**Comment by community-impact** [comment]
I think we should keep "Be a Fellow" as that encourages folks to read the
rest of the page (or else they may not see the opportunity at the end to
show their interest

**Comment by community-impact** [comment]
Even if we can't get the email grab embed up, can we flip the button to
unlink from the application and to say "applications are closed" by Mon
please? Thank you.

**Comment by alanmoo** [comment]
#1441 Will unlink the application.

**Comment by taisdesouzalessa** [comment]
@community-impact and @alanmoo: considering conversation I had with Alan today on what's possible for this page and also what I read on this thread, here are my suggestions.

We could either add the e-mail address or a button that links to a Google Form, as proposed by Amy. I feel the button to Google form is a better option because the data can then be stored in a spreadsheet for the Fellowships team rather then spread in emails (up to Amy to decide, though). Here is the user flow for the 2 options - scroll to see option 2: [InVision link](https://mozilla.invisionapp.com/share/BAGJFYP3CN5#/293064829_User-Flow-Applications-Closed)

**Screens for option 1:** [Overview Page](https://mozilla.invisionapp.com/share/BAGJFYP3CN5#/293064310_Applications_CLOSED_-_V3-FellowshipsUI_-_Overviewv1) + [Apply Page](https://mozilla.invisionapp.com/share/BAGJFYP3CN5#/293064309_Applications_CLOSED_-_V3-FellowshipsUI_-_Be_A_Fellowv1)

**Screens for option 2:** [Overview Page](https://mozilla.invisionapp.com/share/BAGJFYP3CN5#/293064311_Applications_CLOSED_-_V3-FellowshipsUI_-_Overviewv2) + [Apply Page](https://mozilla.invisionapp.com/share/BAGJFYP3CN5#/293064308_Applications_CLOSED_-_V3-FellowshipsUI_-_Be_A_Fellow-V2)

**Questions**
**For Alan:** are those implementation options okay and fairly easy to implement? Any thoughts?
**For Amy:** if both options are feasible (to be confirmed with Alan), please let me know which one do you prefer and also could you please take a look at the copy and do some tweaks? I added a few words on your suggested copy to adjust it to the contexts of email and button, please take a look and feel free to make improvements (copy is not my strength). 
Here is the copy I am talking about:
<img width="341" alt="image" src="https://user-images.githubusercontent.com/22157921/39153592-73d6a354-4700-11e8-93f7-d47239ade79f.png">
<img width="348" alt="image" src="https://user-images.githubusercontent.com/22157921/39153600-7b15b3f8-4700-11e8-9002-df1b7c0909b3.png">

@auremoser any thoughts here are welcomed! adding you to the loop :).

**Comment by community-impact** [comment]
Thanks Tais. I'd prefer option #2. I'd recommend changing "be in the loop"
to "Get more info" to reduce any possible confusion for international
candidates with what be "in the loop" means.

If you do approve the button option, please let me know and I can send you
a form

**Comment by auremoser** [comment]
👍 I like the option 2 version for the [Apply Page](https://mozilla.invisionapp.com/share/BAGJFYP3CN5#/screens/293064308_Applications_CLOSED_-_V3-FellowshipsUI_-_Be_A_Fellow-V2).

I worry that giving people dates will restrict us or might be another thing we could forget to update next year.

Currently, text is: 
> Applications are currently closed. Applications for the 2018-2019 cycle: click on the button and fill in the form. We will send you info when applications are open `<button>`Be in the Loop`</button>`

I might edit the text to say something like the following: 
> Applications are currently closed. Interested in the subsequent application cycle? Please click the button at right, and fill out the form. We will send you info when applications re-open! `<button>`Stay in the Loop`</button>`

"Sign up" or "Get more info" are fine too. I like the jazziness fo "stay in the loop" but understand that it might not be intuitive.

**Comment by community-impact** [comment]
I like Aurelia's recommendation, with the button saying "Get more info"

**Comment by alanmoo** [comment]
Either of those items are pretty straightforward, but I’m curious if dumping visitors to a google form is the best way of getting them into the funnel for next year- seems like that’s the kind of thing the CRM is perfectly designed for. @stephaniemcv @desiree-mofo might have thoughts

**Comment by stephaniemcv** [comment]
Yes, the long-term vision is to get these interested folks into the CRM. This type of email capture is an interesting challenge as it's very specific to limited messaging about application cycle notification and not a mass marketing/promotional email relationship. This is an issue on docket to address when we begin the Fluxx+Salesforce integration and Fellowship program implementation into Salesforce.

In the short-term the google form is probably going to be the best bet.

**Comment by auremoser** [comment]
Looks good to me, and good catch on the "at right" deletion!

**Comment by community-impact** [comment]
Looks good, thought we should change the "apply to be a fellow" menu label as well until applications are open again - @KevZawacki what do you think? Perhaps "How to get involved?"

**Comment by community-impact** [comment]
Also here is the link to the form I just created https://docs.google.com/forms/d/e/1FAIpQLSdTUqJ9Z4xdcVr4IMzd9UESqm7XwcpVdrIXDeeFNIHUc_vhvQ/viewform

**Comment by KevZawacki** [comment]
@community-impact 👍 Or simply "Get Involved"

**Comment by taisdesouzalessa** [comment]
@community-impact here is the mockup with "Get Involved" as a menu label:

[Overview Page](https://mozilla.invisionapp.com/share/BAGJFYP3CN5#/293064311_FINAL_VERSION-_Applications_CLOSED_-_V3-FellowshipsUI_-_Overviewv2)
[Get Involved Page](https://mozilla.invisionapp.com/share/BAGJFYP3CN5#/293064308_FINAL_VERSION-_Applications_CLOSED_-_V3-FellowshipsUI_-_Be_A_Fellow-V2) - we will need to change the URL from `/fellowships/apply/` to `/fellowships/get-involved/` - is that okay? Also, I kept the title "Be a Fellow" because I think it is a compelling title and the audience is interested in being a fellow, even though the cycle may no be currently opened. Let me know if that makes sense to you or if you need any changes.

**Comment by taisdesouzalessa** [comment]
@community-impact I added some custom images to the form. In this way, the transition between site and form is smoother and the visual identity is preserved.

**Comment by community-impact** [comment]
I think the "Get Involved" menu and URL changes looks good, as do the
changes you made to the form.

**Comment by taisdesouzalessa** [comment]
Cool! Here is the implementation ticket, to be done by engineers:  #1457. Closing this ticket. Thanks all!
