### ISSUE TITLE
Design landing pages for Participate & Initiatives

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1137]
Consider phased enhancement on current Get Involved and Upcoming pages and Get Involved homepage content. Consider real existing content vs ideal future content.

Include design for super-MVP List view for “more” participate & “more” initiatives [/participate/archive]

Note: initially, items on landing and archive pages will link to CMS authored pages, like what we have for Global sprint. 

Note: some things will appear on both of these pages, framed differently. MozFest is a initiative. It will also have granular ways to participate (submit a session).

**Comment by kristinashu** [comment]
Interim pages are built and I've opened a new ticket for wireframing future work https://github.com/mozilla/foundation.mozilla.org/issues/1547
