### ISSUE TITLE
Plan IA. Design nav UI.

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1139]
Focus on MVP, phased approach starting with top-level pages.

Remember that most visitors will find content via incoming links and google search. Nav doesn't need to be a sitemap to all the things, just the primary things.

**Comment by kristinashu** [comment]
This [alignment ticket](https://github.com/MozillaFoundation/Design/issues/241) has some background how we got to the main nav that we have. 

For sub-pages we have two different styles:
#### 1) Custom pages like Fellowships where the nav is on top and has a few different states.

[Landing page](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/)
<img width="1294" alt="screen shot 2018-03-06 at 8 46 16 am" src="https://user-images.githubusercontent.com/1068783/37045559-135aa170-211b-11e8-9556-1247e00cc393.png">

<img width="293" alt="image" src="https://user-images.githubusercontent.com/1068783/37046120-6a61349c-211c-11e8-9d32-01e04c41c6e0.png">

[Other pages](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/directory/) (this example has filters too)
<img width="1251" alt="screen shot 2018-03-06 at 8 50 39 am" src="https://user-images.githubusercontent.com/1068783/37045855-be97f286-211b-11e8-9ea1-7229dbde24ba.png">

#### 2) CMS pages like [Web Literacy](https://foundation.mozilla.org/opportunity/web-literacy/) and [Aadhaar](https://foundation.mozilla.org/campaigns/aadhaar/) where the nav is on the side (to accommodate long titles and longer lists):
Here's how it should look once engineers finish QA tickets.

<img width="1097" alt="screen shot 2018-03-06 at 8 29 13 am" src="https://user-images.githubusercontent.com/1068783/37045241-57514c04-211a-11e8-9483-24b176a0b26e.png">

<img width="325" alt="screen shot 2018-03-06 at 8 30 57 am" src="https://user-images.githubusercontent.com/1068783/37045202-4067b186-211a-11e8-9ac6-b7787b1860f2.png">

**Comment by xmatthewx** [comment]
For CMS pages, is the arrow a hack for sub-pages? Or do we actually have two levels in that sidebar?

**Comment by kristinashu** [comment]
Arrows are a hack, if you look at the admin view the arrows are just pasted into the text field.

**Comment by kristinashu** [comment]
Separated this into two tickets:
- Plan IA #1155 (Becca will work on this)
- Design nav UI #1156 (Nat will start on this and then Becca will join)
