### ISSUE TITLE
[Fellowship Mini Site] Update "Meet Some of the Mozilla Fellows" content

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1141]
### Issue:
In our [Fellowship Home Page](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/), make sure the copy in the section "Meet Some of the Mozilla Fellows"  represents the Fellows the way we want (would we like emphasize what their fellowship focus are?). Ideally they would also have the same number of lines so it looks more organized, visually.

<img width="932" alt="image" src="https://user-images.githubusercontent.com/22157921/36921545-92bf9c5e-1e19-11e8-8e2b-96a9457d3f30.png">

@jessevondoom @community-impact tagging you here so you can decide how important you think this issue is.

cc: @xmatthewx

**Comment by xmatthewx** [comment]
this also doesn't seem like a launch blocker to me, but i leave it to @jessevondoom and @community-impact to decide.

**Comment by annmarie123** [comment]
@taisdesouzalessa Here are some condensed copy for that section: Orlando - software engineer, interested in projects that impact the lives of underrepresented communities. Currently, working on Ahwaa.org, a discussion platform for the LGBT community in the Middle East.

Amba - a researcher and policy consultant, Amba is studying how India’s experience with Aadhaar and other tech/government issues can inform global debates about privacy, digital identity, net-neutrality and other critical issues.

Linet - Founder and CEO of DataScience LTD, Linet works on understanding the policies that guide data collection and dissemination in East Africa. She plans to publish a report outlining her findings with policy recommendations on existing policies and proposed amendments.
 

An Me - former Director of Strategic Partnerships at the Mozilla Foundation, An Me is currently a Resident Fellow focused on equipping people with core web literacy skills needed to read, write, and participate on the internet.

**Comment by taisdesouzalessa** [comment]
This is done! Thanks all!
