### ISSUE TITLE
[Fellowship Mini Site] "Host a Fellow" content update

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1142]
### Issue
In the "[Support the Program](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/support/)" page, we have a section "Learn more about how to get involved" that may need some update since the applications are now closed. Also the "here" link is not working (we don't know which url we should add there)

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/22157921/36921783-6f93a5da-1e1a-11e8-82b9-6c88ffe16962.png">

@jessevondoom @community-impact tagging you here so you can decide how important you think this issue is.

@xmatthewx

**Comment by xmatthewx** [comment]
this doesn't seem like a launch blocker to me, but i leave it to @jessevondoom and @community-impact to decide.

**Comment by jessevondoom** [comment]
Maybe just change the copy from:

> Applications are due February 16th, 2018. When applications are closed, you can reach out to fellowships@mozillafoundation.org with any inquiries.

to:

Applications are currently closed, but reach out to fellowships@mozillafoundation.org with any inquiries.

**Comment by mmmavis** [comment]
<img width="739" alt="screen shot 2018-03-07 at 7 25 15 pm" src="https://user-images.githubusercontent.com/2896608/37131455-5b4c87e6-223d-11e8-9a69-b9e449d5c22e.png">

@jessevondoom @taisdesouzalessa  
"this link" in the first sentence just links to the page where user is currently on (the Support page)... which isn't very helpful. Should we just remove the entire sentence `You can apply to be a host organization via this link.` ?

**Comment by taisdesouzalessa** [comment]
Yep, it makes sense to me to remove the first sentence. @jessevondoom you okay with that?

**Comment by jessevondoom** [comment]
Yeah that seems wise.

**Comment by taisdesouzalessa** [comment]
Thanks for the contributions here. Changes were applied.
