### ISSUE TITLE
[Fellowship Mini Site] Update Linet Kwamboka's social link

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1144]
### Issue
In the current version of the site, Linet Kwamboka's LinkedIn link is taking users to a non-existent page.
<img width="638" alt="image" src="https://user-images.githubusercontent.com/22157921/36926884-f3d55b9a-1e2e-11e8-8f97-6a58816dc2c9.png">

### Solution
Aurelia suggested in [this doc](https://docs.google.com/spreadsheets/d/1y_J9EI_Grxd9omK-HivMZErixPaEvia7frHiOJ25zTY/edit?usp=sharing) that we use her twitter profile instead. Her Twitter link is on line 46, column G of [this other doc](https://docs.google.com/spreadsheets/d/1OPxMysNE789MurFGHao_JepDPfNI4JDYXdDtEh8kSds/edit?usp=sharing)

**Comment by auremoser** [comment]
Yes, maybe just use her twitter and not include linked in: https://twitter.com/linetdata?lang=en

I think @mmmavis is on it though, based on the above comments/commits

**Comment by taisdesouzalessa** [comment]
Yay! This is done now - thanks for the work here Aurelia and Mavis! You rock! We just solved this issue.
