### ISSUE TITLE
[Mar 15] Update existing links from old fellowship page to new page

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1147]
The site has a few links that currently point to /opportunity/fellowships. We need to update these links during launch to new root /fellowship page. We don't need a redirect. 
  
 - homepage - Get Involved item
 - /get-involved/ page - fellowship description links to 

We do this _after_ we ship pages to production, a few days _before_ we send out announcement. 

cc @taisdesouzalessa - to look for other links

**Comment by xmatthewx** [comment]
Comms announcement will be early on Monday, March 19th. Let's push this change by Wednesday or Thursday March 15th. cc @alanmoo

**Comment by mmmavis** [comment]
I'm gonna be on PTO during that time - assigning this ticket to @alanmoo so he can reassign it to someone else.
