### ISSUE TITLE
Decide a date to merge 'fellowships` branch into `master`

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#1148]
Fellowships MVP work is almost done (except some small content updates here and there). It seems like we are hoping to launch the mini site in mid-March so at some point this week we should merge the main `fellowships` branch into `master` so people can start QA'ing it on staging. There's no content on the fellowships work that needs to be hidden from users until the official launch... and the minisite currently is not discoverable (e.g., not linked anywhere from the main foundation site). @xmatthewx and I thought it shouldn't be any harm to get this fellowships site work into the deploy pipeline (i.e., `master` branch) but I'd like to check with you all to make sure we didn't miss anything.

/cc @cadecairos @Pomax @gideonthomas

**Comment by mmmavis** [comment]
@cadecairos I'll have a PR up for https://github.com/mozilla/foundation.mozilla.org/pull/996/files/f81827b8c50a1b9d96fdac4d38b9b9e25a834862#diff-ad6df14ef7827e3cd7bc18506dbbf5f1 before the merge happens!

**Comment by mmmavis** [comment]
Ah darn, just thought about this - one thing that might be troublesome/confusing...

... real fellow profiles are on Pulse API PRODUCTION, so once we merge the `fellowships` branch into `master` , on foundation staging site it will pull fellow profiles from PULSE API STAGING instead (which only contains some fake cats and dogs profiles lol). This will def confuse stakeholders. 😬 @xmatthewx thoughts?

**Comment by xmatthewx** [comment]
Can we always have Site Staging pull from Pulse Production? It's best to use real data when we build and test that site. I don't see a need for staging data. Is there a reason we can't?

**Comment by cadecairos** [comment]
I'd prefer not to mess with the staging setup if at all possible. Perhaps we should have two apps in our staging pipeline, one that consumes staging resources, another that consumes production?

**Comment by xmatthewx** [comment]
I understand that staging site frontend should always talk to staging site backend, and that pulse staging frontend should look to pulse staging backend. Is pulse in the same environment as the site? As a resource external to the site, can't the site just always point to Pulse production?

If not, I see two options: 
 1. we pulse production db to staging db, just once. 
 2. after a quick check on staging, we push fellow pages to production for sharing with staff.

I think we go with option 2.

**Comment by mmmavis** [comment]
@xmatthewx yea I vote for option 2 as well

**Comment by gideonthomas** [comment]
This is done @mmmavis?

**Comment by mmmavis** [comment]
Yup, fellowships work has been merged into `master` and pushed to staging: https://foundation.mofostaging.net/fellowships/ 🎉
