### ISSUE TITLE
Plan IA

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1155]
Based on #1139 

Focus on MVP, phased approach starting with top-level pages.

Remember that most visitors will find content via incoming links and google search. Nav doesn't need to be a sitemap to all the things, just the primary things.

#### To dos: 
- [x] layout current IA based on http://foundation.mozilla.org/
- [x] layout proposed IA based on [Jesse's wireframes](https://docs.google.com/presentation/d/1Hl5Etpl-iTOCoJJ66ilszGLYFS2k-LqTRk7_fCTmySc/edit#slide=id.g2e15d82b60_0_64)
- [x] prototype suggested IAs

cc @natalieworth @beccaklam

**Comment by beccaklam** [comment]
![current ia](https://user-images.githubusercontent.com/20977376/37307335-fd6ff9c8-2610-11e8-9d54-9a51f7049e90.jpg)
![jesse s wireframes](https://user-images.githubusercontent.com/20977376/37307336-fd861622-2610-11e8-825b-6aa631970ba8.jpg)

**Comment by beccaklam** [comment]
@natalieworth See above ^ for IA work. Did you want to meet today to talk about next steps for nav design?

**Comment by kristinashu** [comment]
I think this is done, we're going with https://redpen.io/tz04b23ee0dfa52dda
