### ISSUE TITLE
Design nav UI

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1156]
Based on #1139 

Focus on MVP, phased approach starting with top-level pages.

Remember that most visitors will find content via incoming links and google search. Nav doesn't need to be a sitemap to all the things, just the primary things.

### To dos
- [x] Asses current nav (some context below)
- [x] Benchmark other navs (lightly consider mozilla.org)
- [x] Mockup proposed nav updates 
  - based on IA from https://github.com/mozilla/foundation.mozilla.org/issues/1155
  - few things to consider: responsive states, hover and selected states, breadcrumbs...
- [ ] Write a requirement list for engineers 
- [ ] Test it

### Background

This [alignment ticket](https://github.com/MozillaFoundation/Design/issues/241) has some background how we got to the main nav that we have. 

For sub-pages we have two different styles:
#### 1) Custom pages like Fellowships where the nav is on top and has a few different states.

[Landing page](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/)
<img width="1294" alt="screen shot 2018-03-06 at 8 46 16 am" src="https://user-images.githubusercontent.com/1068783/37045559-135aa170-211b-11e8-9556-1247e00cc393.png">
<img width="293" alt="image" src="https://user-images.githubusercontent.com/1068783/37046120-6a61349c-211c-11e8-9d32-01e04c41c6e0.png">

[Other pages](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/directory/) (this example has filters too)
<img width="1251" alt="screen shot 2018-03-06 at 8 50 39 am" src="https://user-images.githubusercontent.com/1068783/37045855-be97f286-211b-11e8-9ea1-7229dbde24ba.png">

[Third level](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/directory/science/) (with breadcrumb)
<img width="1299" alt="screen shot 2018-03-06 at 9 07 54 am" src="https://user-images.githubusercontent.com/1068783/37046747-e643c362-211d-11e8-9a29-4b1e557842a0.png">

#### 2) CMS pages like [Web Literacy](https://foundation.mozilla.org/opportunity/web-literacy/) and [Aadhaar](https://foundation.mozilla.org/campaigns/aadhaar/) where the nav is on the side (to accommodate long titles and longer lists):
Here's how it should look once engineers finish QA tickets.

<img width="1097" alt="screen shot 2018-03-06 at 8 29 13 am" src="https://user-images.githubusercontent.com/1068783/37045241-57514c04-211a-11e8-9483-24b176a0b26e.png">

<img width="325" alt="screen shot 2018-03-06 at 8 30 57 am" src="https://user-images.githubusercontent.com/1068783/37045202-4067b186-211a-11e8-9ac6-b7787b1860f2.png">

cc @natalieworth @beccaklam

**Comment by kristinashu** [comment]
Any progress on this? I'm curious to see how it's coming along!

**Comment by beccaklam** [comment]
@kristinashu Nat and I should be showing some mock ups at crit today! cc: @natalieworth

**Comment by natalieworth** [comment]
I've added benchmarks to a doc here https://docs.google.com/presentation/d/198Sk4LZVe5MBBv0d4RcumiYN9EzusZVOFymJHMOZbcg/edit?usp=sharing . I'm updating my nav designs based on meeting with Becca about IA and nav function during meeting I missed while sick.

**Comment by kristinashu** [comment]
Interim design is being built in https://github.com/mozilla/foundation.mozilla.org/issues/1288 but we're still exploring designs for the future design.

**Comment by kristinashu** [comment]
@natalieworth @beccaklam please keep exploring nav/banner options! Jesse is keen to have a white nav (like mozilla.org) and probably a different style of Donate button. 

He also shared a nav he did previously https://cashmusic.org/ It's a little odd how it has different functionality depending on if you're at the top of the page or scrolled down but would be nice to have one iteration with a better version of that.

Sketch file is in Abstract!

**Comment by kristinashu** [comment]
Putting everyone's WIP comps in redpen for easier feedback https://redpen.io/p/bk3ac2ba96e659d333

I think @natalieworth has done more exploration since this, please add them when you can.

@xmatthewx @taisdesouzalessa @sabrinang please add any thoughts, feedback and examples.

**Comment by natalieworth** [comment]
Added some more nav options to a redpen doc here https://redpen.io/p/xsf546746ceb717376 (with rough gif options for V1 and V2 functionality—so will need to view in Chrome 😫). 

cc @kristinashu @xmatthewx @jessevondoom @taisdesouzalessa @sabrinang @beccaklam

**Comment by natalieworth** [comment]
Nav update:
There's consensus that V1 is the best option. I've updated that based on the redpen feedback:
-  The 'return to top/ arrow' need to be more prominent
- Users need some way to access the menu when the sub nav becomes sticky
- Since our pages won't be that long content-wise, when a menu item is clicked, it will redirect to that page instead of having the automatic scroll

These changes are in the Nav 1 (updated) version of the redpen along with another gif:
https://redpen.io/p/xsf546746ceb717376

cc @xmatthewx @jessevondoom @alanmoo @kristinashu

**Comment by natalieworth** [comment]
Nat update (Version 4 in the redpen) https://redpen.io/p/xsf546746ceb717376
- I got rid of the weird left menu and instead added a hamburger icon that appears when the subnav becomes sticky on scroll
- Hamburger reveals the top level nav. Top level nav is also accessible by scrolling back to top
- I eliminated the 'Return to top' (arrow) since our pages aren't that long (but I can add back if you think it's a necessary feature). I think with the hamburger we solve the issue of having to return to the top of the page to access the main menu.
- Is this technically viable now? @alanmoo (mobile will function different/ I will mock that up once the desktop is in a good spot)

cc @xmatthewx @jessevondoom @alanmoo @kristinashu @taisdesouzalessa @sabrinang  @beccaklam

**Comment by alanmoo** [comment]
Two (minor?) technical concerns from me:

When clicking on an anchor link, the brower's default behavior is to scroll that target element to the top of the browser window. (Looking at what happens when clicking on the "participate" item in the nav.) It's possible to override this, but it potentially starts you down a bad path of breaking other default browser behaviors, especially when it comes to URL routing.

Secondly, having the later sections "push" the top nav out of the way might be tricky, though I'll let someone closer to the code (@gvn) comment on the feasibility of that.

My broader non-technical concern is that I'm unclear as to what pages this will be used on- do we have pages that have multiple sections like this? Is this for mini sites like the Aadhaar campaign?

**Comment by natalieworth** [comment]
@kristinashu This site does it nice https://www.sfmoma.org/
I think the thing I'm wondering is if being able to access the main menu is necessary. The SF one just allows you to return to the top to access the main menu again (which I feel is pretty normal ux).

**Comment by kristinashu** [comment]
Here's an audit of our current nav types and why we have them https://redpen.io/ym4ce635f63eee1ebb 
As you work on the UI please keep these different cases in mind. How they look will change but we will probably need to keep the different types. But if you find ways to simply, please do!

**Comment by natalieworth** [comment]
@kristinashu I narrowed it down to 2 options that I think will work best for mobile nav in doc here (these are just the wireframe version) https://redpen.io/p/th17ea7bf1ea8e704b
Option 1 is my preference. Let me know if you need these mocked up as a gif too! I can defs do, but I thought they were easier to understand than the desktop nav.
cc @xmatthewx

**Comment by kristinashu** [comment]
So far our IA is more straightforward than we thought it would be. The only non-typical behavior will be on Initiatives pages where we will show a secondary nav that then disappears once a user clicks through to one of its "sub-page" (user can always click Back in their browser or click Initiatives in the main nav to return).

![visual ia 2x](https://user-images.githubusercontent.com/1068783/42399274-09aed972-8122-11e8-8e19-b86ab22a0464.jpg)

Sticking with the simpler versions of Nat's designs since I don't think we need to do anything too unique, here is the nav that most of us seem to be gravitating towards and have generally been using in our comps.

https://redpen.io/p/avd5fc0b3db14a7883

![single page 2x](https://user-images.githubusercontent.com/1068783/42399438-a724b910-8122-11e8-996c-faa827e3a989.jpg)

<img width="325" alt="image" src="https://user-images.githubusercontent.com/1068783/42399605-55aa5292-8123-11e8-8b6f-724a54472b02.png">

<img width="326" alt="image" src="https://user-images.githubusercontent.com/1068783/42399598-4a678eae-8123-11e8-9875-f8c5c291a0a2.png">

<img width="325" alt="image" src="https://user-images.githubusercontent.com/1068783/42399613-5f6ab1d2-8123-11e8-9663-b7fecf322707.png">

Please add in your final thoughts/feedback in [Redpen](https://redpen.io/p/avd5fc0b3db14a7883). 

I have one question about the functionality of the secondary nav on mobile. If anyone has benchmarks or dev feedback/constrains please add it as well.

<img width="858" alt="image" src="https://user-images.githubusercontent.com/1068783/42399684-b4854e16-8123-11e8-8570-d5ab4f057efb.png">

**Comment by kristinashu** [comment]
One additional outstanding question is when a user scrolls down, should the secondary nav replace the main nav and stick to the top of the page?

**Comment by beccaklam** [comment]
Hmm, tough question, I would say yes if the secondary nav held anchors on the page but since it's external links I wonder if people would get confused/annoyed. In general I think we still should solve the secondary nav with external links issue ...

**Comment by kristinashu** [comment]
Okay here are the _final_ specs for all the nav updates https://redpen.io/vp5721a2a03e94bf21
Let me know if you have any _final_ feedback or concerns! Does actually seem like there are any big changes...

Note: 
- Tackling the button style in a separate ticket since Nat is still experimenting with diff colors and things
- Keep the dropdown functionality as is (selected menu item disappears when open the dropdown - see bottom of [comment above](https://github.com/mozilla/foundation.mozilla.org/issues/1156#issuecomment-403144169)) until we have a better suggestion
- I'll put this into one implementation ticket and devs can split it up as they see fit

![nav new 2x](https://user-images.githubusercontent.com/1068783/43663943-fd893246-971f-11e8-8b1b-9a0643cbad01.jpg)

**Comment by kristinashu** [comment]
Opened implementation ticket and closing this one but ping me if you think it needs updates!

https://github.com/mozilla/foundation.mozilla.org/issues/1721
