### ISSUE TITLE
[QA Fellowship Mini Site] Grammatical error in header

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/foundation.mozilla.org#1159]
<img width="1440" alt="screen shot 2018-03-06 at 5 42 11 pm" src="https://user-images.githubusercontent.com/5816130/37062921-d17b1f5a-2165-11e8-9b0e-ed0707c5d3c3.png">

The header should either read:
"What is a Mozilla Fellowship?"
or
"What are the Mozilla Fellowships?"

cc @taisdesouzalessa to verify

**Comment by taisdesouzalessa** [comment]
Good catch! It is "What are Mozilla Fellowships" according to [the copy document](https://docs.google.com/document/d/1irQDK5IrRRuBa_Bq4sVOkaD9iHIYxD-cPyUGY_UOuY8/edit).

I can do that PR and ask @mmmavis for review.
