### ISSUE TITLE
[QA Fellowships Mini Site] Missing name next to fellow

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/foundation.mozilla.org#1161]
<img width="1440" alt="screen shot 2018-03-06 at 5 45 26 pm" src="https://user-images.githubusercontent.com/5816130/37063344-19f633e0-2167-11e8-9c1f-6a49283e60f3.png">
Cori's name is missing in the directory next to her pic.

cc @mmmavis

**Comment by mmmavis** [comment]
Info updated it on Pulse backend.
