### ISSUE TITLE
[QA Fellowships Mini Site] Redundant CTA in support fellows page

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/foundation.mozilla.org#1162]
<img width="1436" alt="screen shot 2018-03-06 at 5 58 10 pm" src="https://user-images.githubusercontent.com/5816130/37063662-141f50f4-2168-11e8-92af-3d9ba921843b.png">
The CTA at the bottom of the `/fellowships/support/` page contains a past application deadline and the link redirects to the same page you are on. Seems a bit redundant to have that text although the inquiry text seems useful.

cc @taisdesouzalessa for verification

**Comment by taisdesouzalessa** [comment]
Yeah, you are right, it is very redundant :). We already have a ticket filed here for this issue: #1142

**Comment by gideonthomas** [comment]
Awesome! Thanks @taisdesouzalessa, closing!
