### ISSUE TITLE
[QA Fellowships Mini Site] Missing profile in directory

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/foundation.mozilla.org#1163]
<img width="1201" alt="screen shot 2018-03-06 at 6 03 27 pm" src="https://user-images.githubusercontent.com/5816130/37063834-c1ec75fe-2168-11e8-87d2-bfa4b989471e.png">
An-Me is shown in the main `/fellowships/` page under "Meet Some of the Mozilla Fellows" but when you actually go to the fellowships directory, I can't seem to find her in any of the categories (or maybe I missed it). Don't know if this is intentional or not.

cc @taisdesouzalessa to verify.

**Comment by taisdesouzalessa** [comment]
An-Me should be in the directory, not sure why she is not showing there. @xmatthewx @mmmavis do you know why this is happening? Let me know if I can help with anything here!

**Comment by mmmavis** [comment]
Just a note that currently featured fellows on fellowships pages are hardcoded. Only the profiles we see are Fellowships Directory are pulled directly from Pulse API.

An-me's profile IS on Pulse backend: https://api.mozillapulse.org/api/pulse/profiles/77/ We just need to label it with the right `profile_type`, `program_type`, and `program_year` for it to show on the directory. I can help update it if the above metas are provided.

**Comment by annmarie123** [comment]
I have updated An Me's profile to put her in the Fellows in Residence program (i.e. what senior fellows used to be). I will make sure other staff who are now fellows in residence are accommodated for.

**Comment by xmatthewx** [comment]
We might have a little collision here. I believe "fellow in residence" is different than other types, so a person can be a Tech Policy Fellow, or a Fellow in Residence (like An-Me), or both (like Cori).

Correct me if I'm wrong @annmarie123. But, if I'm right, our model is not designed to handle this. 

Let's _not_ try and solve this right now. Let's just confirm that things are not totally broken. 


 - [x] If the directory's drop-down filter includes `science, tech policy, in residence`, some people will appear twice. That's probably okay.
 - [ ] More importantly, the profile card may or may not include both labels. 
    - Ideal would be: `Cori, Fellow, Tech Policy In Residence 2017`
    - Okay would be: `Cori, Fellow, Tech Policy 2017` or `Cori, Fellow, In Residence 2017` 
    - Is this acceptable?: `Cori, Fellow, In Residence Tech Policy 2017`
 - [ ] Note! The program should be labeled "In Residence" without the word fellow to avoid redundancy. 

The proper fix is to create a separate field for in residence. I think it would be a mistake to try and build and ship that in a hurry.

**Comment by annmarie123** [comment]
Thank you for the details! Cori is just a "In Residence" fellow. She created the tech policy team, but is not herself a tech policy fellow. Therefore, she could just be "In Residence", i.e. no need to change your system.

**Comment by xmatthewx** [comment]
Hmmm. So no Fellow in Residence also has a focus area? Does Cori deal with anything other than Tech Policy? Wouldn't it be weird to not list her with the cohort she oversees?

Thinking again, I think it makes more sense to create a Web Lit focus area to match other types, rather than using a label that won't have much meaning to an external audience. What about Phillip Smith. Is he a fellow? In Residence? Open Web?

**Comment by xmatthewx** [comment]
Awesome. Thanks for the clarity @annmarie123. 

@taisdesouzalessa - can you file a new ticket to add "In Residence"  to the filter on the directory?

**Comment by taisdesouzalessa** [comment]
This issue will be fixed once we add the "In Residence" category: #1174
I will leave this ticket open so we don't lose track of it and once it is fixed, I'll update here okay?

**Comment by taisdesouzalessa** [comment]
Issue is solved :) Closing this ticket. Thanks for the contributions here, team!

**Comment by alanmoo** [comment]
Things have changed significantly since this ticket was filed. An-me does show up on the directory now, but there's no more categories. So I think this can safely be closed.
