### ISSUE TITLE
Update Homepage Features for Global Sprint, Fellowship, & Internet Health

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1168]
The foundation homepage includes a few opportunities for people to get involved. Below news, leaders, the get involved box currently includes: leadership training, fellowship, and Internet Health. 

All three should be updated soon @Sydette.  

 - **Global Sprint** [Launched already]
   - [ ] Craft blurb. @kristinashu can help with an image if needed. cc @zee-moz
   - [ ] Add [Global Sprint](https://foundation.mozilla.org/opportunity/global-sprint/). I think we can do this now. Just needs a blurb. 
   - [ ] Remove Leadership training
 - **Internet Health Report** [Launches Apr 10]. 
    - [ ] Update blurb? 
    - [ ] Update link. @kristinashu I assume transition page is not still useful UX-wise, now that we have landing site and higher quality report? Should we point to main IH site now?
 - **Fellowship** [Launches Mar 15]
    - [ ] Update blurb?
    - [ ] Point to new /fellowships URL

![image](https://user-images.githubusercontent.com/53411/37120772-5346d0ce-2229-11e8-8778-b2053f3d2b6d.png)

**Comment by kristinashu** [comment]
Here are two Fellowship images options and one for Global Sprint:
![fellows1](https://user-images.githubusercontent.com/1068783/37491934-9b18e0fc-285c-11e8-9d3c-9bc829edece9.jpg)
![fellows2](https://user-images.githubusercontent.com/1068783/37491935-9b2c953e-285c-11e8-9ed7-c0987db374e7.jpg)
![globalsprint](https://user-images.githubusercontent.com/1068783/37491936-9b415be0-285c-11e8-9551-a2b4a3eea483.jpg)

**Comment by xmatthewx** [comment]
- I will go ahead and point the IH Report item to internethealthreport.org. 
 - Alan updated the fellow item to the new pages

**Comment by xmatthewx** [comment]
@zee-moz - I'd like to replace the leadership training item for the Global Sprint. Do you have some all purpose copy we could use? Roughly 140-240 characters.

**Comment by zee-moz** [comment]
@xmatthewx sorry, I'm confused-- you want leadership training copy, or global sprint copy?

**Comment by xmatthewx** [comment]
I'd like to remove the current leadership copy and replace it with a big shoutout to the Global Sprint. So promotional language you maybe drafted with Kevin, something to pull people from the homepage into your new landing page.

**Comment by zee-moz** [comment]
How's this? 

**Mozilla’s Global Sprint brings together coders, scientists, artists, students, educators and activists to collaborate on open-source projects that make the internet a better, healthier place.**

**Comment by xmatthewx** [comment]
Here is a test on staging. Look good to you @kristinashu @zee-moz? Any typos?

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/53411/37736877-7cfe9500-2d28-11e8-9724-b8009570e554.png">

**Comment by zee-moz** [comment]
Looks great to me! :)

**Comment by kristinashu** [comment]
Global Sprint feature is live! https://foundation.mozilla.org/

URL links for IHR and Fellows have also been updated so the only outstanding items is to update the IHR and Fellows blubs (but I'm not sure they're needed).

**Comment by xmatthewx** [comment]
Great. Closing this. Filed follow up for other initiatives. 
 - Global sprint: done
 - Fellowship: tracking here https://github.com/mozilla/foundation.mozilla.org/issues/1211
 - Internet health report: tracking here https://github.com/mozilla/foundation.mozilla.org/issues/1212
