### ISSUE TITLE
[QA Fellowship Mini Site] Inconsistencies in data entries

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1170]
### Issue
On the [Directory Page](https://foundation.mofostaging.net/fellowships/directory/) we have some inconsistencies in data entries. Example below (“New York, New York” / “New York, NY”, “Brooklyn  [no comma] New York”):
<img width="325" alt="image" src="https://user-images.githubusercontent.com/22157921/37127876-853b0caa-222c-11e8-9ec8-6e96880d101b.png">

### Solution
Create rules for this field and make users aware of it. Maybe in the CMS?

@xmatthewx's comment: 

> "I'd advocate for an international solution. Avoid abbreviations? Always name country including United States?"

**Comment by xmatthewx** [comment]
@annmarie123 we should make locations a bit more consistent on profiles. cc @community-impact 

I propose: 
 - City, State, Country (no abbreviations)
 - Everyone should have a single primary location, not something like "Washington DC and New York City". Because, we will eventually make this an actual location via the google maps api.  
 - For the U.S., we could omit country if you feel like it'll appear too much on the page.

**Comment by mmmavis** [comment]
@xmatthewx 

> For the U.S., we could omit country if you feel like it'll appear too much on the page.

I'd suggest keeping U.S. in the data entry so that it'll be a lot easier for us to massage the data when the time comes. If we wanna hide `U.S.` from the website we can do it via front end code magic. We should make sure we use the same term though - US? U.S.? United States? or?

**Comment by xmatthewx** [comment]
I leave it to @annmarie123 to decide how to format the content. 

I feel like hiding on front end adds extra work and risk, since user inconsistency might not get captured. The google api will assume United States (for better and worse).

**Comment by mmmavis** [comment]
> For the U.S., we could omit country if you feel like it'll appear too much on the page.

From a dev's perspective...

I'm not sure how we are going to map our manually entered location string to Google API in the future. If we leave "U.S." out, will it become a problem if Google API can't find the location? I'm just worried it might result in us going through each entry one by one to massage the location meta manually again. I don't know Google API enough... so it's likely there's some magic behind it that I'm not aware of.

From a site visitor's perspective...

I'd like to see "U.S." show up as the location meta. We shouldn't assume visitors can always recognize any city in the U.S.. Leaving out country meta just when it's US seems odd to me. Also a note that this `location` meta on Pulse backend is not only used/read by Fellowships' Directory page but also on Pulse website. If we really don't want "U.S." to appear too much on Fellowships' Directory, we should do it on Foudation's site's front end so it won't affect any other site/platform that's consuming the same Pulse profile data.

**Comment by taisdesouzalessa** [comment]
From the user perspective, I think we shouldn't hide the country. I think it is important we treat all data equally and from a usability perspective, it can cause confusion if a country is hidden and others not. I would strongly recommend to keep all the countries (it is more likely a user recognizes a country than not a city). If in the future we are going to use an API or something the shows the country, we can then figure out how to display the data then. In my opinion, we should design for the present and make sure the context is clear enough to make users' lives easier in the present.

Abbreviations or full country names would work. Abbreviations would look cleaner, the downside is that not everybody gets it :).

**Comment by Pomax** [comment]
Are there still steps we want to take here, or should we close this issue? @xmatthewx

**Comment by kristinashu** [comment]
We will align with in our new fellowship cms work.
