### ISSUE TITLE
[Fellowship Mini Site] Add "In Residence" category to Directory pages

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1174]
### Issue: We need a space for our "In Residence" fellows category in our Directory Pages.

**List of requirements:**  - Thanks @xmatthewx for suggesting it.
- [ ] Add new label `In Residence` (to the filter, to profiles)
- [ ] put in alphabetical order (issue #1175)
- [ ] link to section below with title `Fellows in Residence`
- [ ] include button to `See all Fellows in Residence`
- [ ] link button to page at `/fellowships/directory/in-residence/`
- [ ] page should include all profiles in this category
- [ ] **In Pulse:** Change program type on Pulse backend to `In Residence` (it's currently set to `Fellow in Residence`)

---------------------------
**Visual walkthrough:**

We should add "In Residence" to the filter: 

<img width="774" alt="image" src="https://user-images.githubusercontent.com/22157921/37169629-45a1f09a-22bd-11e8-8ed5-99dcf6f5d533.png">

---------------------------

Also, to this page (as an area by itself):

<img width="725" alt="image" src="https://user-images.githubusercontent.com/22157921/37169665-601afd72-22bd-11e8-8795-48619d3ff39f.png">

------------------------

And also to its own page, like we have for other areas such as "Science":

<img width="619" alt="image" src="https://user-images.githubusercontent.com/22157921/37169697-796131c0-22bd-11e8-95ab-26f85afe46ed.png">
----------------------

Here is the list of fellows in Residence for context (extracted from [here](https://github.com/mozilla/foundation.mozilla.org/issues/1163#issuecomment-371321049)):
Philip Smith - Misinformation + Fake News
Cori Zarek - Tech Policy
An-Me Chung - Web Literacy
Jon Rogers - IoT
Peter Bihr - IoT
Julia Kloiber - IoT
Steve Song - Access and Digital Inclusion
Renee DiResta (coming soon) - Misinformation
Thomas Lohninger- TBD (focus on enforcing Net Neutrality in the EU, but may be titled something else)

@mmmavis let me know if this is clear. In can you need a comp, I can quickly provide one.

cc: @xmatthewx - feel free to edit this issue to add more details if you want :)

**Comment by mmmavis** [comment]
- URL should be `/fellowships/directory/in-residence/` and page title should be `Fellows in Residence`

**Comment by alanmoo** [comment]
Correct me if I'm wrong, but I believe we can close this since we've moved away from the sub-page style.
