### ISSUE TITLE
[QA Fellowship Mini Site] Directory in Alphabetical Order

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1175]
### Issue
**Attention:** this issue is related to #1174.

In our [Directory Page](https://foundation.mofostaging.net/fellowships/directory/) we should organize items in alphabetical order:

in residence > media > open web > science > tech policy

That should be applied both to the filter:
<img width="392" alt="image" src="https://user-images.githubusercontent.com/22157921/37170062-a6132470-22be-11e8-892b-c9f485f6373f.png">

And the page:
<img width="383" alt="image" src="https://user-images.githubusercontent.com/22157921/37170077-b6098cca-22be-11e8-8b6e-6aa5f0f539c6.png">

cc: @xmatthewx @jessevondoom

**Comment by alanmoo** [comment]
Fellows are in alphabetical order now, though no longer in groups by type.
