### ISSUE TITLE
[Fellowship Mini Site] Change labels on the directory page

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1183]
### Issue
Amy's team requested some [wording changes ](https://docs.google.com/document/d/143kk5m-rEJGr1ZUTgdg0ARCpX4DssQz_6rLojL85ZSI/edit?usp=sharing) for the fellows directory.

### Solution
- [ ] Taís will work on the comps for those changes and send to Amy's team for approval.
- [ ] After approval, Taís will create an implementation ticket so Mavis can work on the changes.

@xmatthewx @jessevondoom tagging you here so you are aware of this work in progress

**Comment by xmatthewx** [comment]
note: these labels will need to be changed in the directory and in the pulse admin

**Comment by taisdesouzalessa** [comment]
Here are the changes applied:
https://projects.invisionapp.com/share/ZJ9YTAGEA#/screens/276734820_v2-FellowshipsUI_-_Fellows_Directory

**Status:** waiting on Amy's team approval

**Comment by mmmavis** [comment]
@xmatthewx @taisdesouzalessa 

These directory pages are built dynamically based on the data we get from Pulse API. Just a reminder that changing the names of those `program_type` labels on Pulse admin will affect things __ hugely __ on the directory pages (e.g., name of each program section will change, filter name will change, some URLs are likely to change because of that... etc).

Things broke last time when the labels on Pulse admin got changed from `<program> fellow` to just `<program>`. Please give dev team a ping **before** we decide to make changes to that field again so we can get the patch in first. 👍

**Comment by mmmavis** [comment]
related question:

does this affect URLs under `/fellowships/directory/` too?
e.g., does https://foundation.mozilla.org/fellowships/directory/science/ become https://foundation.mozilla.org/fellowships/directory/scientists/

**Comment by taisdesouzalessa** [comment]
@xmatthewx @mmmavis in my understanding the changes were more related to title (like in the example below we changed the title from "Media Fellows" to "Media Makers". But the label inside the card remained the same "Fellow, Media, 2017". 
<img width="495" alt="image" src="https://user-images.githubusercontent.com/22157921/37315873-294cc014-2619-11e8-8ca2-ef57ee33514c.png">

Matthew, let me know if I misunderstood it? My comp doens't change labels, just the titles (which I assume are hard coded, correct?).

**Comment by taisdesouzalessa** [comment]
@mmmavis, good point on the URL. I asked Amy via email about a similar issue (changing the button copy will likely change the title of individual pages). If she agrees with the change, I think it makes sense to change the URL as well, what do you think @xmatthewx?

![directory-demo](https://user-images.githubusercontent.com/22157921/37315965-acdd1f46-2619-11e8-9478-d6448617e52d.gif)

**Comment by mmmavis** [comment]
@taisdesouzalessa on directory pages, only the big heading "Fellows Directory" and the word "Area" in the filter bar are hardcoded 😉 Everything else is built based on the data we get from Pulse API.

**Comment by taisdesouzalessa** [comment]
@mmmavis So the areas highlighted in green come from Pulse as well? That is a good info to have, I didn't know it :).  Thanks for the clarity here. 
<img width="525" alt="image" src="https://user-images.githubusercontent.com/22157921/37316134-98ca073e-261a-11e8-833e-aa21f1ff13b5.png">

**Comment by mmmavis** [comment]
@taisdesouzalessa yea those titles are generated **"based on"** data from Pulse API.

e.g., 

if program type is "in residence", display title as "Fellows in Residence"
otherwise display title as "_program name_ Fellows"

**Comment by taisdesouzalessa** [comment]
thank you so much for your explanation @mmmavis! Now it is clear to me and it makes sense :).

**Comment by taisdesouzalessa** [comment]
This is solved, we don't have areas anymore, we added years instead. Closing this issue.
