### ISSUE TITLE
Make nav at narrow widths more consistant

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1186]
### Desktop looks good:
<img width="1156" alt="screen shot 2018-03-13 at 12 22 30 pm" src="https://user-images.githubusercontent.com/1068783/37364991-53d8d598-26b9-11e8-8ec2-adaf58b28c4d.png">

### But at narrow widths:
- [x] Hover state is yellow when it should be white with underline (like at desktop width)
- [ ] Social icons are hidden or cut off when they should be visible

<img width="723" alt="screen shot 2018-03-13 at 12 22 05 pm" src="https://user-images.githubusercontent.com/1068783/37364988-50f972d8-26b9-11e8-873f-0bcc324244f5.png">

**Comment by kristinashu** [comment]
Social icons cut off can be done here https://github.com/mozilla/foundation.mozilla.org/issues/1247

**Comment by mmmavis** [comment]
Done!

> Per discussion with designers - we decided to remove this section from mobile nav altogether for cleaner, more streamline design.
