### ISSUE TITLE
Get Connected icon is squished 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1187]
### Icon at bottom of home page looks good at width browser widths:
<img width="1129" alt="screen shot 2018-03-13 at 12 28 14 pm" src="https://user-images.githubusercontent.com/1068783/37365263-368c25fc-26ba-11e8-91de-e876860ed170.png">

### But is squished at narrower widths, it shouldn'd be squshied:
<img width="793" alt="screen shot 2018-03-13 at 12 28 02 pm" src="https://user-images.githubusercontent.com/1068783/37365262-367549d6-26ba-11e8-84bd-708ae0cec0c6.png">

**Comment by kristinashu** [comment]
Same as on https://foundation.mozilla.org/sign-up/ but even at full browser width:
<img width="1008" alt="screen shot 2018-03-13 at 12 32 36 pm" src="https://user-images.githubusercontent.com/1068783/37365413-a956d7bc-26ba-11e8-95e1-023500c4e20a.png">

This must be a new thing?

**Comment by taisdesouzalessa** [comment]
it is a bug not a feature :(
