### ISSUE TITLE
Add colors to Style Guide

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1188]
These are the only colors that should appear on the site. Please:
- [x] add them to the [Style Guide](https://foundation.mozilla.org/style-guide/) so everyone knows
- [x] make sure there are no other colors hard coded into the site

<img width="628" alt="screen shot 2018-03-13 at 1 39 35 pm" src="https://user-images.githubusercontent.com/1068783/37369071-40692b78-26c5-11e8-924f-b7ddd84288fd.png">

**Comment by kristinashu** [comment]
Nice! Colors have been added https://foundation.mozilla.org/style-guide/

@mmmavis should I open a new ticket for fixing hard coded colors?

**Comment by mmmavis** [comment]
@kristinashu it's okay we can just use this ticket. Can you update colour names in the design file so they are the same as what we have on our style guide page?

**Comment by kristinashu** [comment]
w00t this is done!
