### ISSUE TITLE
Pull Pulse Projects for Global Sprint 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1191]
For the Global Sprint, we want to pull projects from Pulse that are tagged mozsprint. 

Goals: 
 - Long term: enable CMS page authors to specify parameters e.g. (issue, tag, featured). 
 - Short term: a solution we can land in advance of global sprint. 

Solution in order of preference: 
 1. cms authored page has projects at bottom
 1. an engineered page included on the sprints sidebar nav
 1. an engineered page linked prominently from a sprint page
 1. a prominent link to tag view on pulse

We can leverage the current card style on the [project page](https://foundation.mozilla.org/projects/), though an update might be nice.

@kristinashu @acabunoc @zee-moz - add your thoughts and then I'll explore an approach with the engineers.

**Comment by kristinashu** [comment]
I think it would look something like this, where the [Projects page on the site](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/) shows a feed of projects pulled from Pulse. Projects would be styled as they are on Pulse (but without the fav icon). Each individual project would link out to the detail view on Pulse.

<img width="939" alt="screen shot 2018-03-14 at 11 56 20 am" src="https://user-images.githubusercontent.com/1068783/37424851-c1842b4a-277e-11e8-9909-58fb2ef17e87.png">

**Comment by xmatthewx** [comment]
@alanmoo - let's put our heads together soon and talk about how to approach project feeds on the site. We have most of the building blocks in place.

**Comment by zee-moz** [comment]
@alanmoo @xmatthewx  we have lots of projects registered, and this is the perfect time to begin to highlight them-- our list of awesome projects on the site is central to our comms strategy and is the main driver of registration. is there any way this feature could be ready end of the week, or early next week? the sprint is fast approaching!

**Comment by kristinashu** [comment]
@zee-moz I'm assuming we only want to show featured Global Sprint projects from this year. What hashtag should we use to pull in projects? 

#globalsprint vs #globalsprint2018

Should we pull any projects that have that hashtag or only ones that have that hashtag and are set as "Featured" on Pulse?

**Comment by gvn** [comment]
My proposal is that for now we can move ahead and build the React component and inject it via a bespoke HTML target wherever it needs to go. A fast follow would be to create a Wagtail component for easy embedding without the need to write any HTML.

The HTML would be something like:

`<div class="pulse-project-list" data-tags="mozsprint,2018"></div>`

@xmatthewx @kristinashu – Is the design above ready for me to implement like this?

**Comment by kristinashu** [comment]
I'm good with the design above.

**Comment by gvn** [comment]
FYI: Currently the Pulse API only supports single tag searches.

Is there a cap for how many projects we want to show for this list?

**Comment by acabunoc** [comment]
@gvn  last year I filtered for two tags using https://api.mozillapulse.org/api/pulse/entries/?search=mozsprint+2017

Can you use https://api.mozillapulse.org/api/pulse/entries/?search=mozsprint+2018 ?

**Comment by zee-moz** [comment]
I'm hoping @kristinashu can help us put up a temporary, static project page so we can begin to do comms around projects on Monday-- unless @gvn you think this will be up and running by Monday?

Here's the issue for the temporary page: https://github.com/mozilla/2018-global-sprint-planning/issues/33

Thanks everyone for your help on this 😺

**Comment by gvn** [comment]
- Capped at 6 items since that's what I'm seeing in the design.
- Switched over to a general search query instead of a tag based query. We should probably file follow-on tickets to move back to tags and refactor the API for multi-tag searches.
- Not sure how long this will take to land on prod...that will depend on how long reviews take.

The target markup that will go into Mezzanine pages once this is on prod will be:

`<div class="pulse-project-list" for="mozsprint+2018"></div>`

**Comment by acabunoc** [comment]
@gvn please show all projects with the tag!

**Comment by gvn** [comment]
Ok, this should work now for pages on prod or staging. Just add this snippet through the code editor in Mezzanine wherever you want the component:

`<div class="pulse-project-list" for="mozsprint+2018"></div>`

(FYI: "mozsprint+2018" isn't returning any results right now, but just "mozsprint" will.)

**Comment by acabunoc** [comment]
I'll be approved a few of the submission later today -- test data coming soon!

**Comment by xmatthewx** [comment]
This is amazing! So powerful and simple. Thanks @gvn

Below is a screenshot of a [draft page you can view on production](https://foundation.mozilla.org/opportunity/iot-projects/) (requires site login). 

A few things we should fix: 
 - [ ] reverse order of results. currently displays oldest items first. 
 - [ ] increase spacing between rows. they currently mash together. 
 - [ ] add fallback for missing thumbs. ideally [gradient used on pulse](https://www.mozillapulse.org/entry/598).
 - [ ] line height on long titles should be reduced.  
 - [ ] [for wagtail] we should limit to 6 by default. include parameter for more. 

Anything else you notice @kristinashu ? 
 
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/53411/37933897-a8c2c40e-311a-11e8-9d2a-52b169ac2f63.png">

**Comment by kristinashu** [comment]
@xmatthewx can we do these as a followup ticket? This is going out today and I believe all the Global Sprint projects will have an image and will all be published at the same time.

I see `increase spacing between rows. they currently mash together` as important but feel the others are slightly less pressing.

**Comment by alanmoo** [comment]
I'll update the API to return results in reverse order by default

**Comment by xmatthewx** [comment]
> can we do these as a followup ticket?

Yep, yep. This is all live on production already too. So, it can be added to the page now.

**Comment by kristinashu** [comment]
Cool cool, I've opened a ticket https://github.com/mozilla/foundation.mozilla.org/issues/1223

The Div class has been added it to the [site](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/), just can't tell because projects with that hashtag haven't been published yet.

**Comment by gvn** [comment]
Since we have a new QA ticket I'm going to close this one...
