### ISSUE TITLE
[Fellowhip Mini Site] Apply to be a Fellow page: copy change

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1193]
### Issue
Change the current copy of our https://foundation.mofostaging.net/fellowships/apply/ page

[Here](https://docs.google.com/document/d/1ZRMFoPl0aNiu1ya-ldJJKnZIOhZfp6OZCVZThwL-b8g/edit?usp=sharing) is the new copy.

- [x] Taís will apply copy to comp and do the necessary adjustments.
- [x] Fellowship team will approve the comp
- [x] An implementation ticket will be created and sent to @alanmoo to triage on this team (since Mavis will be in PTO) #1195

Here is a note from Amy: once the applications close, she would like to have an email field that captures possible future applicants (so they can be notified once applications open). @community-impact this issue is captured in this GitHub ticket:  #1135 - please add any thoughts or comments to that issue and let us know if that works for you. Please note that we are not working on that for the launch stage (it is an "up next" feature) :).

**Comment by taisdesouzalessa** [comment]
From this previous ticket (#1134) we have the link to Fluxx application: https://mozilla.fluxx.io/user_sessions/new + @auremoser suggestion of "Contact Us" copy: "Any further questions about fellowships at Mozilla? Contact us. <- link to fellowships@mozillafoundation.org."

**Comment by community-impact** [comment]
Yes, ticket #1135 reflects the thought about the email capture, thank you.

And yes, that will be the correct app link as far as I know in #1134

**Comment by taisdesouzalessa** [comment]
Here is the comp for this page 
https://invis.io/ZJ9YTAGEA#/276734812_v2-FellowshipsUI_-_Apply-Applications_Open

After @community-impact  and her team approve this comp, we can send it to @alanmoo's team for implementation.

**Comment by auremoser** [comment]
@taisdesouzalessa the comp doesn't load for me but thank you for sharing and so much for putting this together.

**Comment by taisdesouzalessa** [comment]
Oh sorry for that, @auremoser - here is a redpen link: https://redpen.io/jp21f74016b6ee4c71

Rizwan approved this page by email. @alanmoo this page is ready to be built. I'll open an implementation ticket.

**Comment by auremoser** [comment]
Looks great, thank you for sharing!

**Comment by taisdesouzalessa** [comment]
Implementation ticket here: #1195
