### ISSUE TITLE
Investigate makes.org

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#11938]
The team has reviewed this [list](https://docs.google.com/document/d/17ByHIC_vo_WK7j48x3VauW5LMO_yDK6qvrCE0uQ4IL8/edit) to evaluate AWS resources for potential decommissioning or removal. In the process, we've identified `makes.org` requires further examination. (Marked with a yellow dot on the google doc)

The purpose of this task is to look into `makes.org` and confirm whether it can be approved for decommissioning.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-35)

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Based on the site no longer active and the files being more than 5 years old, this is safe to remove from AWS.
