### ISSUE TITLE
[Fellowship Mini Site QA] Fellowship Directory

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1199]
### Issue
Currently, in our [Directory Page](https://foundation.mozilla.org/fellowships/directory/), once users click on the button "See Fellows for Previous Years" they are taken to [a page](https://foundation.mozilla.org/fellowships/directory/archive/) that has all Fellows, from all years, including 2018. The problem is that this behavior doesn't match the expectation of the title "See Fellows from Previous Years"

### Solution
Change the [archive page](https://foundation.mozilla.org/fellowships/directory/archive/) to display Fellows from 2017 and before that, as proposed in [the comp](https://invis.io/ZJ9YTAGEA#/276734822_v2-FellowshipsUI_-_Fellows_Directory_Specific_Program_Page).

cc: @alanmoo @community-impact for visibility

**Comment by gvn** [comment]
This is on prod now if you want to verify, @taisdesouzalessa !

**Comment by taisdesouzalessa** [comment]
It looks great!! Yay, thank you so much @gvn :)
