### ISSUE TITLE
[Fellowship Mini Site] Change button copy on lauch + helper text

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1202]
Once the applications launch, do the following changes on this page:
https://foundation.mozilla.org/fellowships/apply/

- [x] change button copy to "Apply to be a fellow today" 
- [x] button linking to Fluxx: https://mozilla.fluxx.io/user_sessions/new)  
- [x] add this helper copy: "Applications are due by 5 pm Eastern Time on April 20th, 2018. `<strong>` Make sure to register by April 18th `</strong>`."

@alanmoo adding you here to triage this issue. If needed, I can do those changes. I have the bandwidth.

@community-impact and @auremoser could you let us know here when this copy should change? 

cc: @xmatthewx adding you to the loop

**Comment by auremoser** [comment]
Looks great, thank you @taisdesouzalessa , if we can bold the April 18th date that would be great. I just don't want people to miss it!

**Comment by taisdesouzalessa** [comment]
good point, Aurelia :). Added this note to the original ticket :)

**Comment by alanmoo** [comment]
@taisdesouzalessa If you want to open a PR labeled "Do not merge yet" you're welcome to take it on. If you can't assign it to Gavin.

**Comment by taisdesouzalessa** [comment]
Sure, I can do it @alanmoo between today and tomorrow.

**Comment by taisdesouzalessa** [comment]
@auremoser @community_impact here is how the button with the helper text will look like. I think having 2 dates there may be a bit confusing from the user's perspective. With the current copy, I made the whole "April 18th" line bold to try to alleviate that. Do we need to have those 2 dates?

<img width="822" alt="image" src="https://user-images.githubusercontent.com/22157921/37673783-5c4a0cfe-2c2e-11e8-9ac4-eed3a5ccb049.png">

**Comment by annmarie123** [comment]
@taisdesouzalessa Yes we do as applicants who are registering for the first time, need to be approved by staff, thus we do not want last minute "help" emails about their application at 11pm Friday April 20th.

**Comment by taisdesouzalessa** [comment]
Thanks for the context @annmarie123 - leaving it as is then :).

**Comment by taisdesouzalessa** [comment]
@alanmoo PR is ready, assigned Gavin for review.

**Comment by auremoser** [comment]
+1 to Ann Marie, it is confusing, but the reality is that if they don’t register by the 18th we probably won’t invite them to Fluxx in time to submit by the 20th. I’ve prepped a canned email to respond to any confusion!

**Comment by taisdesouzalessa** [comment]
https://foundation.mozilla.org/fellowships/directory/
