### ISSUE TITLE
[Campaigns Page Template] title misalignment

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1204]
### Issue:

Currently, in our [campaigns pages template](https://foundation.mozilla.org/campaigns/baby-monitor/), the title is not aligned with the body copy, which makes the layout a bit weird.
DESKTOP:
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/22157921/37668546-054e4ba6-2c22-11e8-913b-d2786fd689f8.png">

MOBILE:
<img width="323" alt="image" src="https://user-images.githubusercontent.com/22157921/37668737-6a4abc60-2c22-11e8-9d7e-f8867001dc2a.png">

### Solution:
Either make the columns larger or the title narrower to it aligns with the body copy.

@alanmoo @xmatthewx assigning you for triage :).

**Comment by xmatthewx** [comment]
I agree that this should be fixed. Seems like a new CSS bug recently introduced. Leaving this to @alanmoo to triage.

**Comment by alanmoo** [comment]
See also https://github.com/mozilla/foundation.mozilla.org/issues/1037
