### ISSUE TITLE
Discuss thank you text that appears after supporter signs up

### ISSUE THREAD

**Issue by vojtechsedlak** [mozilla/foundation.mozilla.org#1209]
We did a recent evaluation of the rate of new subscribers that end up confirming their subscription through the double opt-in process. Currently only about 42% of people who subscribe on the site end up confirming their subscription. In contrast, on [developer.mozilla.org](developer.mozilla.org) site that percentage is >90%. 

Ideally we would be able to test the impact of different messages on the double opt-in rate, but given that the content on developer.mozilla.org seems to be performing well, could we change the thank you message content to be the following?

"
Thanks! Please check your inbox to confirm your subscription.

If you haven’t previously confirmed a subscription to a Mozilla-related newsletter you may have to do so. Please check your inbox or your spam filter for an email from us.
"

**Comment by alanmoo** [comment]
Is this referring to the main signup component or petitions?

**Comment by vojtechsedlak** [comment]
Primarily the signup components, though we should talk about the messaging after petition signups as well. It just gets a bit more complicated there with the share buttons.

**Comment by alanmoo** [comment]
To clarify then, you're looking to replace the existing message of `Thanks for joining. The Internet already feels a bit more vibrant (^_^). We will email you soon to confirm.`?

**Comment by vojtechsedlak** [comment]
Indeed, the main point is to emphasize that they need to confirm their subscription. Thanks!

**Comment by kristinashu** [comment]
Updated for main foundation site email signup and in the works for campaigns https://github.com/mozilla/foundation.mozilla.org/issues/1366

<img width="695" alt="image" src="https://user-images.githubusercontent.com/1068783/39020803-f07b1dc0-43e2-11e8-819e-f94da0abcc36.png">
