### ISSUE TITLE
Update IH Report feature on homepage

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1212]
The IH Report is featured on the foundation site homepage. In prep for launch, we should review the copy and update it if needed. 

@Solanasaurus – does the copy need a refresh?

> Is the Internet getting healthier? Is it under threat? Do we all have a voice on the web? Mozilla’s Internet Health Report is an open source initiative that combines research from multiple sources to document what’s healthy and unhealthy.
Read the report --> 

@kristinashu – we should prep an image so we can move this to the lead spot when the report launches. 

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/53411/37792934-977c24a4-2de3-11e8-9696-7a957837cdf4.png">

**Comment by Solanasaurus** [comment]
Good call! 

How about:

2018 Internet Health Report

How healthy is the Internet? You may know other reports that look at industry trends and technologies. The Internet Health Report is about the human experience of the Internet - an independent, open source compilation of data, research and stories that show how the Internet evolving.

You could recycle image we used on pre-launch post: https://internethealthreport.org/get-ready-the-2018-internet-health-report-will-be-released-on-april-10/

Is there an additional page or will it link directly to the report?

Solana

**Comment by kristinashu** [comment]
We can link directly to http://mzl.la/ihr 

Should we update the body copy now or wait until the report launches? If we update it now then we should change "Read the report" text as well.

**Comment by xmatthewx** [comment]
>  Is there an additional page or will it link directly to the report?

We used an [interstitial page](https://foundation.mozilla.org/opportunity/internet-health-report/) last year, but it feels superfluous now that the report has a parent site and more synchronized branding.  

Thanks @Solanasaurus! Thanks @kristinashu!

**Comment by kristinashu** [comment]
@alanmoo can you update the lead feature banner?

### Copy:

2018 Internet Health Report 

How healthy is the Internet? You may know other reports that look at industry trends and technologies. The Internet Health Report is about the human experience of the Internet - an independent, open source compilation of data, research and stories that show how the Internet evolving.

Link: http://mzl.la/ihr

### Image

![ihr](https://user-images.githubusercontent.com/1068783/38568628-f77d6dc2-3c9d-11e8-9a28-7a8be2134e9c.jpg)

### How it will look on the site
<img width="1201" alt="screen shot 2018-04-10 at 9 01 38 am" src="https://user-images.githubusercontent.com/1068783/38568718-31b23a04-3c9e-11e8-9590-f61a405e1dcd.png">

**Comment by xmatthewx** [comment]
This looks done to me. Closing. Thanks all!!
