### ISSUE TITLE
Fellowship year in directory

### ISSUE THREAD

**Issue by community-impact** [mozilla/foundation.mozilla.org#1213]
@taisdesouzalessa @xmatthewx - On the directory page, given that the convention we are working with is that the year we show is the year in which the fellowship cohort ended, can we have the 2016-2017 fellows in the Open Web and Science space show up in 2017 please? 

cc @rtufail @annmarie123

**Comment by annmarie123** [comment]
@community-impact @taisdesouzalessa I'm currently updating the directory per your specifications.

**Comment by taisdesouzalessa** [comment]
Thanks, @annmarie123 - let me know if there is any help you need.

**Comment by taisdesouzalessa** [comment]
I guess this is solved by now? @annmarie123 feel free to reopen this ticket if necessary.
