### ISSUE TITLE
[Fellowship Mini Site] Directory takes a while to load

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1214]
### Issue
The directory is taking a bit to load (at least using my connection here at Mozilla Vancouver)
![fellowships-directory-loading](https://user-images.githubusercontent.com/22157921/37799848-334d6272-2dde-11e8-959b-d4f9fc5b1d0d.gif)

@cadecairos @alanmoo @mmmavis is there anything we could do to make this loading faster? Also, please let me know if you experience delays as well.

**Comment by alanmoo** [comment]
I think this is blocked by https://github.com/mozilla/network-pulse-api/pull/320

**Comment by taisdesouzalessa** [comment]
Solved! Directory is much faster now! Closing this issue, thanks, team :)
