### ISSUE TITLE
[Fellowships Mini Site] Add filters to Directory Page

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1215]
### Issue:
Now that we have the MVP of our [Directory Page](https://foundation.mozilla.org/fellowships/directory/) it is time to add filters as per wireframes:

<img width="414" alt="image" src="https://user-images.githubusercontent.com/22157921/37802722-d9552b5a-2de8-11e8-8cbf-03d840bf7d3a.png">

**Comment by taisdesouzalessa** [comment]
Here are the comps and Filter behaviors. I have 2 options for that:

OPTION 1:
**Gif Files** - I made some Gif because they are easy to walkthrough:
[Gif (adding filters - DESKTOP)](https://drive.google.com/open?id=1w13fEz9Tvlr2VsWUmBEeJYx2Sn264Tn2)
[Gif (deleting filter - DESKTOP) ](https://drive.google.com/open?id=13lTRSjI81S5EstuO08Efr3eyQdwDxAzz)
[Gif (MOBILE)](https://drive.google.com/open?id=1b5_mohSKs6cvp7ypGY-2mKY3GQpPS3ZW)
**InVision File** (interactive prototype):
[Desktop](https://mozilla.invisionapp.com/share/BAGJFYP3CN5#/287147562_v2-FellowshipsUI_-_Fellows_Directory_Dropdown_Closed)
[Mobile](https://mozilla.invisionapp.com/share/FCGIKIDHGSK#/287185541_step1-V3-MOBILE_-_FellowshipsUI_-_Directory)


OPTION 2:
**Gif Files**
[Gif (DESKTOP)](https://drive.google.com/open?id=1jH9ulVBhpgc-YEdMP5v99g0psHw80Djh)
[Gif (MOBILE)](https://drive.google.com/open?id=1DYX6I2pur1uVx6ehIYzY-5PTkV92uTg5)

**InVision File** (interactive prototype):
[Desktop](https://mozilla.invisionapp.com/share/BAGJFYP3CN5#/287187550_OPT2-Step1-V3-FellowshipsUI_-_Fellows_Directory_Dropdown_Closed_Copy)
[Mobile](https://mozilla.invisionapp.com/share/FCGIKIDHGSK#/287188976_OPT2-Step1-V3-MOBILE_-_FellowshipsUI_-_Directory_Copy)

@alanmoo @xmatthewx @mmmavis - please take a look and give your feedback. I'll also request feedback from other designers as well.

**Comment by xmatthewx** [comment]
Thanks @taisdesouzalessa. I'd like to team up on this, sort through the ux and technical challenges.  Let's find some time to whiteboard together.

**Comment by sabrinang** [comment]
@taisdesouzalessa 
I think Opt 2 was more obvious multiple filters could be made and it may be more commonly experienced (like on shopping sites etc.) I think for Opt 1 it wasn’t immediately obvious multiple could be chosen and I was wondering what would appear in the dropbox itself when 2+ filters are selected? The gifs are great 👍

**Comment by taisdesouzalessa** [comment]
adding @natalieworth's feedback from Slack:

>  I think if stakeholders need only the 1 filter option, then I'd prefer the 1st option with the deselect. Feels more modern and easier to switch between single filter selections. If more category selections are necessary/ possible though I think the 2nd would work better since it's easier to clear multiple filters.

**Comment by kristinashu** [comment]
I like the simplicity of Option 1. Option 2 feels like it would be better if there were lots of possible items to filter by, but seems overkill for us. I also like how both options show the number of results next to the name.

For comparison, it would be nice to see a non-dropdown version of filtering. Because there are two fields, dropdowns might be our only option here but if we can [avoid them](https://www.lukew.com/ff/entry.asp?1950) then we should.

**Comment by beccaklam** [comment]
@kristinashu nice article!
@taisdesouzalessa I agree with the feedback given so far that option #1 is good if the user can only select one filter at a time and option #2 is good if we can select multiple. I also agree with Kristina that it would be good to explore another input form besides dropdown menu (i.e. one that shows all the filter options straight away -- just to see what that would be like, not saying that's the solution).

**Comment by taisdesouzalessa** [comment]
Yay! Thank you so much for all this good feedback, friends :). @kristinashu nice article! Bookmarking it.

**Comment by mmmavis** [comment]
Hey @taisdesouzalessa ,

Thanks for the gifs. They were super helpful!

As what I mentioned to you yesterday on Slack I found option 2 less intuitive as "tags" usually imply we can allow multiple tags at the same time -- in this case we don't.

**Comment by taisdesouzalessa** [comment]
@xmatthewx and I discussed this Filter and we will go with a very simple filter by now (just Year). We will probably use more complex filtering site wide in the future so the discussions we had here are super valid for when we work on it. Thanks for the feedback, team!

**Comment by taisdesouzalessa** [comment]
Here are the options with just the year:

### **With Dropdown**
![filter-opt3](https://user-images.githubusercontent.com/22157921/38001453-c0a42050-31e1-11e8-8069-153e49ac95eb.gif)
[InVision (DESKTOP) - interactive](https://mozilla.invisionapp.com/share/BAGJFYP3CN5#/287806803_OPT3-Step1-V3-FellowshipsUI_-_Fellows_Directory_Dropdown_Closed_Copy)
[InVision (MOBILE) - one screen only](https://mozilla.invisionapp.com/share/FCGIKIDHGSK#/287808460_OPT3-V3-MOBILE_-_FellowshipsUI_-_Directory_Copy)

### **Without Dropdown**
I found the filter a little lost there, since there is only one. And considering the article @kristinashu posted, this option seems to make sense to me:
![filter-opt4](https://user-images.githubusercontent.com/22157921/38001795-ac3d036e-31e3-11e8-889b-cf5fd113809d.gif)

[InVision (DESKTOP) - interactive](https://mozilla.invisionapp.com/share/BAGJFYP3CN5#/287806807_OPT4-Step1-V3-FellowshipsUI_-_Fellows_Directory_No_Dropdown)
[InVision (MOBILE) - one screen only](https://mozilla.invisionapp.com/share/FCGIKIDHGSK#/287808461_OPT4-V3-MOBILE_-_FellowshipsUI_-_Directory_Copy_2)

@xmatthewx could you let me know which option you prefer?

**Comment by xmatthewx** [comment]
Hmmm. Interesting. 
 - I can see the advantages of option without drop-down. Glad to pursue that, change it later only if it proves necessary. 
 - I definitely like not having 'filter' as a label
 - Can we try a treatment without greybox as background? I am not opposed, but I've always felt it feels drab here and behind the Join CTA. This is not critical if there isn't an easy alternative.

**Comment by taisdesouzalessa** [comment]
> Can we try a treatment without greybox as background? I am not opposed, but I've always felt it feels drab here and behind the Join CTA. This is not critical if there isn't an easy alternative.

@xmatthewx I tried a treatment without the background and it seems it is floating there. Both Mavis and I agree that the background helps to anchor the content. I am leaving it for now and once we have more filter options we can reevaluate this issue. Does that work for you?

**Comment by xmatthewx** [comment]
sure thing. this is definitely not a blocker.

i like your style used for application date CTA. maybe there's some variation on that to anchor it with lines. but again, let's ship this!!! we can always change the style later.

**Comment by xmatthewx** [comment]
❗️ 👍 💯 💥 🛥

**Comment by mmmavis** [comment]
This is now on [staging](https://foundation.mofostaging.net/fellowships/directory/). Will go live in the next production push (tomorrow most likely).

**Comment by taisdesouzalessa** [comment]
This feature is now implemented! Thanks all for the feedback :)
