### ISSUE TITLE
QA Updates for Pulling Pulse Projects into CMS pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1223]
Based on - Pull Pulse Projects for Global Sprint #1191 

A few things we should fix: 
 - [x] reverse order of results. currently displays oldest items first. (confirmed fixed by API patch). Note: Global Sprint wants oldest first, but this should not be the default behavior. 
 - [x] increase spacing between rows. they currently mash together. 
 - [x] add fallback for missing thumbs. ideally [gradient used on pulse](https://www.mozillapulse.org/entry/598).
 - [x] line height on long titles should be reduced.  
 - [ ] [for wagtail] we should limit to 6 by default. include parameter for more.

**Comment by acabunoc** [comment]
Hello! @zee-moz and I have discussed this a bit and we would like the oldest item displayed first (otherwise we see the last minute rushed projects at the top during the sprint).

**Comment by kristinashu** [comment]
Ok Abby! @gvn @alanmoo ^

**Comment by zee-moz** [comment]
@kristinashu is this ready to go yet? I'd like to start promoting tomorrow!

**Comment by kristinashu** [comment]
@zee-moz yes! It's here https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/ 

@acabunoc looks like there are only 3 projects showing up, should there be more?

**Comment by alanmoo** [comment]
The page is still in draft mode- see the banner at the top.

**Comment by kristinashu** [comment]
Sorry @zee-moz, was that what you were asking? Yeah, whenever you are ready to launch registration, just make sure you update the Register and Projects pages from Draft to Published in the CMS.

<img width="650" alt="screen_shot_2018-03-26_at_4 34 05_pm" src="https://user-images.githubusercontent.com/1068783/38055842-b2603b6a-328f-11e8-90d4-08eef01eca26.png">

**Comment by acabunoc** [comment]
Yes, only 3 right now! I originally went and approved all the project @zee-moz listed for the temp page, but then their coaches started reviewing and I thought they should be the ones to approve the listing.

Anyways, coaches have started so more should be coming!

**Comment by kristinashu** [comment]
Ok cool! Zannah thought there was a bug and that's why so few projects were showing up.

She gave me to go ahead to publish the Register page but will hold off on Projects page till tomorrow.

**Comment by zee-moz** [comment]
@acabunoc I approved all the mentored projects I could find that had the correct mozsprint and 2018 tags, but we still only have 8 projects appearing. There are more to approve but they need the correct tags! Can you change in the Pulse backend so we can get more projects showing up before we turn the project page on, on Monday? 

Random design suggestion: do we have any mechanism to vary the placeholder pink image, for projects that don't have their own graphics? if we could color code these to IH issue or something that would at least create some visual variation so we don't end up with tons of generic pink (there's lots of non-image projects coming our way)-- @xmatthewx ?

thanks!

**Comment by xmatthewx** [comment]
that's an interesting idea @zee-moz, color by issues. I don't think we can tackle this now, but it could be a fun project during mozfest.
