### ISSUE TITLE
Wagtail Design Help

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1225]
### Context:
It would be nice for the design team to get to know Wagtail by building things with it. Gavin suggested we reached out to Pomax and see if he needs help moving pages from Mezzanine to Wagtail - so we can learn by using real projects.

[UPDATED Google Doc here](https://docs.google.com/document/d/1Rbbkh4x5hnY6TgJiWJXiCJF0MzD-cb6FR6fQI9cWlK0/edit?usp=sharing)

~~@Pomax mentioned he will first power through the pages and then we can look at each page after that in collaboration to figure out tweaks and improvements~~

**Comment by kristinashu** [comment]
I've update the [doc link](https://docs.google.com/document/d/1Rbbkh4x5hnY6TgJiWJXiCJF0MzD-cb6FR6fQI9cWlK0/edit#heading=h.l1gy3apa6i3k) above to Pomax's.

It would be great if everyone could port over one set of pages so they can become familiar with Wagtail. Just add your name in the doc and list any problems you may come across.
