### ISSUE TITLE
Design page feature callout component

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1245]
## summary

Our content-rich pages could benefit from a callout box to hold an image and text. 

 - A first use case of this: as we simplify nav and header, we'll need to move the fellow featured in the header of the fellowship page. 
 - This component could be similar to a card from the home page: image with whitebox of text overlaps from below. It could float to the right, break across the main column to mix things up a bit. 

@jessevondoom – is this clear? Feel free to revise. 

## notes

When we simplify nav and header, we'll need to move this content:

![image](https://user-images.githubusercontent.com/53411/38259643-8a976dd0-3733-11e8-85fa-0398a026cbfa.png)

Into some sort of card in the body of the page. How can we do this as a component useful on other pages? It probably should NOT include a title and tag like the screenshot below. But image + textbox could be super cool. 

![image](https://user-images.githubusercontent.com/53411/38259954-5bae48f8-3734-11e8-8866-96a180a796b4.png)

**Comment by kristinashu** [comment]
We are removing this feature in the new design to make things more streamlined https://redpen.io/hx70e9eb24e0534b72
