### ISSUE TITLE
Design potential lead features

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1246]
As we ramp up traffic, and run lead features at the top of the site's homepage, we will likely want a few different templates to make the most of that space.

Think about current and future features for this space (facebook petition, year end fundraising, mozfest, IH report). How can we push this space to the max? Bold images. Full bleed. Inline form field. Fundraising amount button.

**Comment by kristinashu** [comment]
@beccaklam made these lovely designs https://redpen.io/p/cs7e31adca809cb337 

Becca, can you please give everyone upload powers to that redpen so we can all add our designs to the same place?

**Comment by xmatthewx** [comment]
This will be great. Next time we have an urgent need for a quick feature, we'll have a library of options to help choose a direction.
