### ISSUE TITLE
Fix nav overlay icons

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1247]
Something funky is happening with our icons on the popover nav. I see it on android chrome and desktop firefox. See screenshots below. 

@alanmoo to triage

## android chrome 

<img width="471" alt="image" src="https://user-images.githubusercontent.com/53411/38260651-32e1e4f0-3736-11e8-9928-ddb6640144b5.png">

## firefox nightly desktop 

<img width="626" alt="image" src="https://user-images.githubusercontent.com/53411/38260665-3d0fdacc-3736-11e8-9bb1-9e44992b5fad.png">

**Comment by kristinashu** [comment]
Also in https://github.com/mozilla/foundation.mozilla.org/issues/1186

**Comment by mmmavis** [comment]
Fixed!

> Per discussion with designers - we decided to remove this section from mobile nav altogether for cleaner, more streamline design.
