### ISSUE TITLE
Add Donate button to header

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1250]
As we update nav we will remove the signup button. Let's add a donate button in its place.

Requirements
 - [x] design button
 - [x] add button
 - [ ] ship it with analytics event wired up
 - [ ] bonus: add analytics to footer donate link

### analytics

  | Category | Action | Label
-- | -- | -- | --
Header | donate | donate button tap | [page title] header
Footer | donate | donate button tap | [page title] footer

also captured in [ga events](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=779058050) spreadsheet

**Comment by vojtechsedlak** [comment]
It would be great if we could add the following to the URL, to help with tracking on the donate site: ?utm_source=foundation.mozilla.org&utm_medium=referral&utm_content=header

**Comment by kristinashu** [comment]
Also from Vojtech: 
The footer one should include ?utm_source=foundation.mozilla.org&utm_medium=referral&utm_content=footer
