### ISSUE TITLE
Delete "upcoming.jsx" if it doesn't get used by July 1

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#1260]
`source/js/components/upcoming/upcoming.jsx` is not being used anywhere (related: PR https://github.com/mozilla/foundation.mozilla.org/pull/1256). We want to keep this file in the repo for now in case we decide to use it again in the near future. This ticket is just a reminder for us to delete that file if it doesn't get used again by July 1.

**Comment by gvn** [comment]
![0397c08cc2cabf8d6e1f1402f00a7bc3](https://user-images.githubusercontent.com/206379/38324983-99789a2c-37f6-11e8-9a7b-11e83820f3d7.gif)

**Comment by mmmavis** [comment]
😂

**Comment by Pomax** [comment]
@mmmavis I'm guessing we can remove this now =D

**Comment by mmmavis** [comment]
Yes, it's been almost a year passed our "July 1" last call. 😂 😂 😂 😂 😂 😂 😂
