### ISSUE TITLE
Wagtail User Documentation

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#1266]
The guide will be located here: https://foundation.mozilla.org/wagtail/docs/how-do-i-wagtail/

This will be where we can work on documenting useful notes, tips and tricks for people using Wagtail. 

@Pomax @xmatthewx

**Comment by sabrinang** [comment]
@xmatthewx The user doc on https://foundation.mozilla.org/wagtail/docs/how-do-i-wagtail/ is ready for review or feedback.

- sections are split up as child pages for easy navigation
- screenshots of UI are incorporated for reference
- sample page is used to demo the body content in context

**Comment by taisdesouzalessa** [comment]
Updates link: https://foundation.mozilla.org/docs/how-do-i-wagtail/

**Comment by taisdesouzalessa** [comment]
This is implemented now! Closing this ticket. Feel free to reopen if needed.
