### ISSUE TITLE
port foundation campaigns/opportunities

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#1271]
The CMS is landed enough on foundation.moz.org at this point to do a serious content-port pass

#### Opportunities
- [x] Fellowships FAQ
- [x] Leadership Training
- [x] Internet Health Report
- [x] Network Feedback - DRAFT ON MEZZANINE
- [x] Network 50
- [x] Tech Policy Fellows
  - [x] Advisory Board
- [x] Mozilla Information Trust Initiative
  - [x] Manifestions and Visualisation Challenge
- [x] Mozilla's Open IoT Studio [DRAFT IN MEZZANINE]
- [x] NSF Showcases
- [x] Design [DRAFT IN MEZZANINE]
- [x] Global Sprint
  - [x] Register
  - [x] 2018 Projects
  - [x] Participate
  - [x] Lead a Project
  - [x] Host a Site
  - [x] Tools & Working Open
- [ ] Web Literacy
  - [ ] Core Curriculum
    - [ ] Frame
    - [ ] Read
    - [ ] Write
    - [ ] Participate
  - [ ] Additional Resources
- [ ] Open Leadership Framework
  - [ ] Mozilla's Open Story
  - [ ] About the Open Leadership Framework
  - [ ] Personas & Use-cases
  - [ ] How to Contribute
- [ ] IoT Projects

#### Campaigns
- [ ] Aadhaar
  - [ ] Key challenges and the way forward
  - [ ] Take Action
  - [ ] Blogs and press
- [ ] Equifax breach
- [ ] Dear Target: Please help make baby monitors safer
- [ ] Facebook
  - [ ] FR
  - [ ] ES
  - [ ] PT
  - [ ] DE
  - [ ] PL
- [ ] India needs a strong privacy and data protection law
- [ ] Facebook update

**Comment by Pomax** [comment]
# tech policy fellows and advisory board

images cannot be sized properly in the rich text editor, so some images ARE HUGE while others ᵃʳᵉ ᵗᶦᶰʸ

**Comment by Pomax** [comment]
# Mozilla's Open IoT Studio

The heading looks very off

**Comment by Pomax** [comment]
# Global Sprint

partner logo is too large (image size issue)

**Comment by kristinashu** [comment]
W00t this is all done!
