### ISSUE TITLE
Build new email signup component

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1272]
Based on - Build updated home page #1234 

We're updating the email signup on the home page to look like [this comp](https://redpen.io/fnbf9b42fd34a2cf61).

We would like to streamline our signup so we only have one component. But looking at the [style guide](https://foundation.mozilla.org/style-guide/), there are several different components.

Can we streamline these to just the one new component?

It is hard to figure out where the signup is actually being used, so far I've found:
- http://foundation.mozilla.org/ (want to redesign)
- https://foundation.mozilla.org/sign-up/ (no longer link to so we should archive this)
- CMS
 - https://foundation.mozilla.org/opportunity/training/ (new design would work here)
 - https://foundation.mozilla.org/opportunity/miti/ (new design would work here)
 - https://foundation.mozilla.org/opportunity/internet-health-report/ (no longer link to so we should archive this and redirect it)

cc @xmatthewx

**Comment by jessevondoom** [comment]
I think your list looks right and we should go ahead and make it a single component. Good call!
