### ISSUE TITLE
Figure out where to put people/highlights/news (menu vs. snippets)

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#1273]
These three models are currently "real models" with sidebar menu entries that offers a different UI compared to the "snippet -> [that model]" UI. 

Where do we want to surface these data models?

/cc @alanmoo

**Comment by alanmoo** [comment]
People are going to go away eventually (as we pull them from Pulse) so let's just leave that for now.
News should be accessible and searchable as easy as possible. Not sure what the two options here mean for that.
Highlights should be addable/sortable (of the ones that are currently on the page) in the homepage, but don't need to be as accessible throughout the rest of the site.

**Comment by Pomax** [comment]
I'm closing this in lieu of us filing a new issue if and when we're ready to actually do this. The site's changed too much since this got filed.
