### ISSUE TITLE
put the template <title> inside a block for wagtail overriding

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/foundation.mozilla.org#1294]
This is about to land: https://github.com/mozilla/foundation.mozilla.org/pull/1281

Which puts some of the meta data into the CMS (mostly just share image)

This makes the `<title>`,  which is defined in pug, not quite match up with the title coming from the CMS.

We should update it so these are the same, and one possible solution is move the `<title>` into a block, and allow the modular_page to change it to be what was from the CMS.

**Comment by Pomax** [comment]
We should be able to do this by making the pug template generate a `<title>{% block pageTitle %}default content{% endblock %}</title>`
