### ISSUE TITLE
Foundation Site: Storytelling and Narratives

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1297]
Ticked based on meeting with Sydette on April 6th, 2018. 

**Think about ways to create narrative on the site.** 

If users are in a story, what are the different ways to add tracks for people to navigate on the site? Once they do an action on the site, how can we display other actions that can be taken? What are they ways to navigate site and content? For instance: signing up and learning more about an initiative / sign up and attend a meeting?

**Goal/ Metric:** time spent on the site, time enjoyed. Engagement. 

**[Notes from the meeting →](https://docs.google.com/document/d/1u5GYTGWgcYbaLfgyfJCWDbF7DebGnDUh7tKU8Uk6d-E/edit?usp=sharing)** 

NEXT STEPS:

- Brainstorm ideas, add benchmarks to InVision Board / add how we see those examples being applied at Mozilla. **[Board for Brainstorming →](https://mozilla.invisionapp.com/boards/DK3LFFTE6RA/)** 
- Sydette to share some examples
http://tow.cjr.org/platform-timeline/

@kristinashu @Sydette @jessevondoom @beccaklam - feel free to edit this issue/the doc as you see fit.

**Comment by kristinashu** [comment]
Adding notes from something Jesse mentioned which feels related:
I think two of our biggest problems might be solutions for each other. There's the future nav design and the narrative context. Given that the nav is ever present just like the idea of an Internet Health context, I think there are ways to give wayfinding tools for that IH context in the nav, and use it to help people see the connections between an announcement about Facebook at the work someone like Amba is doing on Aadhaar.

**Comment by beccaklam** [comment]
@taisdesouzalessa Can you invite me to collaborate on the board? Can't seem to add to it?

**Comment by taisdesouzalessa** [comment]
@beccaklam done, let me know if it works! Sorry for that :).

**Comment by kristinashu** [comment]
We will be working out of the doc @taisdesouzalessa started https://docs.google.com/document/d/1CE_vy2ecTWndzzsE_TyW8LT77c3H662uEUnaA-zCjrM/edit?usp=sharing

**Comment by kristinashu** [comment]
We're working out of the doc and slack channel.

Deck is [here](https://docs.google.com/presentation/d/1PfQkuyJWgYK2OyZyqPUOQn20FeqKnaL4An8l3wQRpCU/edit?usp=sharing) and Sydette is working with Jesse on [this doc](https://docs.google.com/document/d/18zu0gBUZXadTfJ4FCB2s2SU5wxsctXuEmrNhWiZDZlM/edit?ts=5ae77397#heading=h.awikj1axy4gu).

I think we can close this ticket!
