### ISSUE TITLE
News Page Updates

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1304]
### Issue:
Since we made some changes in the "Latest News" section in our Foundation site, we also need to update the "News" page to reflect that.

Here is a list of suggested changes:
- [x] the “mb-3” should become “mb2”, so it matches the style of the home page.
<img width="629" alt="image" src="https://user-images.githubusercontent.com/22157921/38448030-2e026270-39b6-11e8-9519-05692d319aff.png">

- [x] We should use the same text format that the home page has (1 line instead of 2)
<img width="632" alt="image" src="https://user-images.githubusercontent.com/22157921/38448047-4c346842-39b6-11e8-898e-e887f28b985c.png">

@alanmoo assigning to you for triage. I am assuming we can skip design because the requirements seem clear. Let me know if I am wrong, though :)

**Comment by coderpen-me** [comment]
How can i contribute by making these changes?

**Comment by alanmoo** [comment]
@coderpen-me you're welcome to clone the repo, load fake data (see the readme) and open a PR with the changes needed, referencing this ticket in the PR.

**Comment by Pomax** [comment]
@kristinashu is this work that we still need to do, or did the code and content updates since initial filing obviate this issue?

**Comment by mmmavis** [comment]
Just assigned myself this ticket as I'm doing some styling cleanup for the site and this is part of it. 👍
