### ISSUE TITLE
Create fake data for Wagtail pages

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1308]
As we're building out the site in Wagtail, we should be able to spin up a build of the site that resembles the production structure somewhat easily. 

Can the `load_fake_data` script be augmented to support building a fake homepage and choosing options in the fields for it?

Secondarily, can `load_fake_data` generate content for a page with StreamFields?

Once those two items are in place, developers building other pages should be able to easily generate whatever other fake page structures they need.

**Comment by cadecairos** [comment]
This was completed in #1509
