### ISSUE TITLE
Implement Campaign Landing Page 

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#1311]
### Checklist:
- [x] Desktop: Form is sticky and always present
- [x] Mobile: CTA button is always present at bottom 
- [x] Form filed inputs are similar to http://bradfrost.com/blog/post/float-label-pattern/ 
- [x] Include form error states [[bug](https://github.com/mozilla/foundation.mozilla.org/issues/1311#issuecomment-387580009)]
- [x] Form title (ex "Add your name", Empty form field text, and checkbox text are from our [Style Guide ](https://foundation.mozilla.org/style-guide/))
- [x] Content on left side will reflect Wagtail rich text editor (so image is optional and font styles are based on the editor)
- [x] Follow bootstrap grid

### Comp
Initial "basic" template page https://redpen.io/gf9574a99f7765a29a and grid

<img width="983" alt="image" src="https://user-images.githubusercontent.com/1068783/39936954-189a2400-5503-11e8-819a-c380165ccebb.png">

### Mobile
<img width="319" alt="image" src="https://user-images.githubusercontent.com/1068783/40207689-b2aa8738-59ea-11e8-9bbe-53f7b2983093.png">

**Comment by kristinashu** [comment]
### Comp
- starting with our initial "basic" template page https://redpen.io/gf9574a99f7765a29a

![red-pen-57207e7a-c287-4135-8c53-3fce523b51d7](https://user-images.githubusercontent.com/1068783/38707391-0ac31f16-3e66-11e8-811b-e59b9356d7cc.jpg)

### Existing components
- Use nav that is currently on production
- Callout above the CTA already exists https://foundation.mozilla.org/campaigns/equifax-breach/

### Content
- Content on left side will reflect Wagtail rich text editor (so image is optional and font styles are based on the editor)

### Form 
- Updated our form style to something like http://bradfrost.com/blog/post/float-label-pattern/ 
- Form title (ex "Add your name", Empty form field text, and checkbox text are from our [Style Guide ](https://foundation.mozilla.org/style-guide/))
- Orange #FF5C00 button and text is a new color not in our style guide
- @ScottDowne and @beccaklam to work out details for the best form UX!

### Desktop bootstrap grid
<img width="970" alt="screen shot 2018-04-12 at 3 30 55 pm" src="https://user-images.githubusercontent.com/1068783/38707539-8ef8f814-3e66-11e8-93a5-2c05e7d6ae66.png">

### Mobile
- form drops below content 
- CTA button is fixed to the bottom of broswer. Clicking on scrolls (not jump!) the user down the page to the form anchor 

[I will add mobile comp shortly]

**Comment by kristinashu** [comment]
@ScottDowne @alanmoo @beccaklam sorry there has been some stop and go on this. 

I've updated the above comment to reflect the approved design. Please re-read and let me know if there are any questions/comments.

**Comment by kristinashu** [comment]
Note for QA: the CTA button on iOS will take 2 taps to activate, since the browser UI pops up and moves it on the first tap. This happens on [change.org campaigns](https://www.change.org/p/join-me-in-asking-l-macaulay-to-end-food-waste-in-canada-whywastefood?source_location=discover_feed) and [airbnb posts](https://www.airbnb.ca/rooms/1012597?s=99qPY-_q) and is _normal_.

cc @alanmoo

**Comment by kristinashu** [comment]
Form is now sticky! https://foundation.mozilla.org/campaigns/equifax-breach/

@ScottDowne I noticed two sides of the error are cutoff or something 
<img width="494" alt="screen shot 2018-05-07 at 3 24 47 pm" src="https://user-images.githubusercontent.com/1068783/39789022-26aa44f8-52e2-11e8-94de-25e861a08056.png">

**Comment by xmatthewx** [comment]
Nice progress everyone. 

Can we update the checklist at the top? Mark what's done, and maybe add new items that have emerged?

For example... there's a top-alignment issue across the columns. Maybe we can tackle that as we do other layout adjustments. 

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/53411/39937206-fe39ed6a-551c-11e8-9824-8665fd9dfde2.png">

**Comment by kristinashu** [comment]
Yeah, I can update the checklist!

That alignment issue will be solved by the new layout and titles so we don't need to fix it, but it would be good to get the new layout and styling done soon. I think it's next in Scott's to do list.

**Comment by alanmoo** [comment]
I'd like to get more details on the "Follow Bootstrap Grid" Item, as it's way too vague to be able to check off. Technically the site follows it now, but it may not be to the column amounts that are desired at various screen sizes. If you inspect the markup on pages like [the facebook campaign](https://foundation.mozilla.org/campaigns/facebook/), you'll notice the main content has ` py-5 col-md-8 offset-md-2 col-lg-10 offset-lg-1`, which makes it narrower than the nav content (for reasons that date back to preventing templates with a single column from having lines with too many words). **Should that container be full width on all campaign pages?**

From there, the 2 columns are split evenly starting at medium browser widths. If this is not correct, **at what breakpoints should the left and right column be what size?** 

Breakpoint sizes are [here](https://github.com/mozilla/foundation.mozilla.org/blob/master/source/sass/main.scss#L10-L14), please define sizes for each breakpoint, going up.

For example:
```
12 columns to start
Medium: 6/6
Large and up: content 7, gap of 1, petition 4
```

**Comment by kristinashu** [comment]
@alanmoo I don't think Scott has worked on this yet so it isn't ready to be checked off. Here's a screen cap from the first comment that showed the bootstrap columns. On desktop they are: 7 body content  | 1 gap | 4 form
I can mock up medium screen widths tomorrow if needed or we can have a quick vidyo call?

<img width="735" alt="image" src="https://user-images.githubusercontent.com/1068783/40339453-63ba2190-5d2f-11e8-97b3-eca1c6544d17.png">

**Comment by kristinashu** [comment]
Scott has followed this grid, just hasn't been pushed to staging yet.

**Comment by kristinashu** [comment]
The only thing left are the titles. So "Aadhaar" should be contained within the left side content (not across the entire page like it is on prod). And the "Take Action" and "Add you name" have different font styling that now.

Take Action" and "Add you name"  are from the [style guide](https://foundation.mozilla.org/style-guide/):
.h5-heading
.h6-heading-uppercase

<img width="1238" alt="screen shot 2018-05-28 at 10 12 18 am" src="https://user-images.githubusercontent.com/1068783/40624157-af596eb4-625f-11e8-94f6-e54591fea0c3.png">

**Comment by kristinashu** [comment]
W00t! This is all on staging!
