### ISSUE TITLE
Confirm Heading Streamfield element markup

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1315]
Take a look at https://foundation.mozilla.org/wagtail/opportunity/global-sprint/tools-working-open/, the in-progress page for Wagtail. It uses the "heading" component a bunch, and it's just too big. I'm guessing text like "Collaboration tools for the sprint" should be `h3` elements, @taisdesouzalessa can you confirm?

**Comment by taisdesouzalessa** [comment]
Definitely @alanmoo, good catch :) - h3 is the way to go so hierarchy of content is preserved (h1 makes the secondary titles bigger than the main title). Screenshot for h3.

<img width="991" alt="image" src="https://user-images.githubusercontent.com/22157921/38630441-cb2479f4-3d6b-11e8-8d47-2ade8e02b2a7.png">

**Comment by alanmoo** [comment]
So should we be using a paragraph element heading and leaving the "heading" component at that font, or change it so that all "Heading" streamfield components are h3?

**Comment by taisdesouzalessa** [comment]
Sorry, I think I misunderstood your question @alanmoo - I talked to @kristinashu and were wondering why we need the heading component if we can can have headings by using the paragraph tool (which provided more flexibility - from h2 to h5):

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/22157921/38632995-2aac8a0e-3d73-11e8-97a5-3ecd53bf1198.png">

Please let me know if I am missing something here...

**Comment by alanmoo** [comment]
Theoretical data clarity, but honestly I'd be fine ditching it and putting `h1` back in the paragraph editor. @Pomax @gvn any thoughts?

**Comment by alanmoo** [comment]
Great, then this is CMS content that needs to be changed and not in the code, so I'm gonna close this.

**Comment by kristinashu** [comment]
Oh I was thinking we remove the Heading block as an option completely. Avoid this problem in the future.
