### ISSUE TITLE
Update heading class names on primary wagtail pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1321]
This is a blocker for launch.

Need to update heading class names on primary wagtail pages. 

Headings should match our [style guide](https://foundation.mozilla.org/style-guide/).

Example: wagtail looks like https://foundation.mozilla.org/wagtail/participate/
<img width="1205" alt="screen shot 2018-04-12 at 9 12 14 am" src="https://user-images.githubusercontent.com/1068783/38693158-f72caeac-3e3a-11e8-9039-6e855c86d8dd.png">

Should look like original pages https://foundation.mozilla.org/participate/
<img width="1265" alt="screen shot 2018-04-12 at 10 19 38 am" src="https://user-images.githubusercontent.com/1068783/38693183-0e3fe032-3e3b-11e8-9809-227d00e34f71.png">

cc @alanmoo @taisdesouzalessa

**Comment by alanmoo** [comment]
I believe I just addressed this in #1346
