### ISSUE TITLE
Design QA of primary wagtail pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1325]
### Secondary nav
Currently https://foundation.mozilla.org/wagtail/about/
- space between banner and secondary nav items is too large
- add gradient divider bar
<img width="1091" alt="screen shot 2018-04-12 at 12 24 53 pm" src="https://user-images.githubusercontent.com/1068783/38699394-bbca2d96-3e4c-11e8-94aa-83cf5ae58ba6.png">

It should at least look like https://foundation.mozilla.org/fellowships/

<img width="1091" alt="screen shot 2018-04-12 at 12 25 36 pm" src="https://user-images.githubusercontent.com/1068783/38699385-b52ccbe2-3e4c-11e8-8a4d-10621fe22397.png">

Bonus is it looks like (black underline like main nav, instead of yellow bar)

<img width="1128" alt="screen shot 2018-04-12 at 12 28 10 pm" src="https://user-images.githubusercontent.com/1068783/38699482-01b5867a-3e4d-11e8-8a6e-6f4e5560bf17.png">

### Banner height
- Increase banner height by about 20px on all pages with the banner

### Content width of copy
- copy width on Overview should be narrower (like on https://foundation.mozilla.org/fellowships/apply/)
- on [Overview](https://foundation.mozilla.org/wagtail/about/), [Trademarks](https://foundation.mozilla.org/wagtail/about/trademarks/), [Public Records](https://foundation.mozilla.org/wagtail/about/public-records/), and any future pages that are paragraphs of copy

### Heading styles
- will [this](https://github.com/mozilla/foundation.mozilla.org/pull/1324#issuecomment-380906497
) fix the heading styles here too?

### [Leadership grid](https://foundation.mozilla.org/wagtail/about/leadership/)
- Is there a reason why "Emeritus Board Members" looks different than "Management"? They're both 3 across. 
<img width="712" alt="image" src="https://user-images.githubusercontent.com/1068783/38700009-8f09a73a-3e4e-11e8-9a0c-4cb47b3f49d4.png">

- Would be nicer if there was more padding around image like the comp https://redpen.io/ug4d381110a992b4de (this way it will match the bootstrap grid)

- Would also be nice to eventually have the different type styling for name and job title, as in the comp

### Bullet points
- Spacing after bullet points should be the same or larger than before them (ex https://foundation.mozilla.org/wagtail/about/public-records/)
Screen cap from production looks confusing because bullets look grouped with content bellow, not above
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/1068783/38700407-ce8e518e-3e4f-11e8-8281-3eca8e79f76f.png">

**Comment by kristinashu** [comment]
cc @taisdesouzalessa

**Comment by alanmoo** [comment]
Let's break these out into separate tickets, as it's hard to track what needs to be done in an issue like this.
