### ISSUE TITLE
Wagtail QA: Banner height

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1328]
From @kristinashu  in #1325 

### Banner height
- Increase banner height by about 20px

**Comment by alanmoo** [comment]
We could do this, but that tall banner looks kind of weird on mobile devices, and it gets messy to try and shrink that conditionally. I'd strongly suggest we land on one size that works everywhere (and honestly I think what we currently have is that)

**Comment by kristinashu** [comment]
Mobile was designed to be much smaller https://github.com/mozilla/foundation.mozilla.org/issues/1288

<img width="997" alt="image" src="https://user-images.githubusercontent.com/1068783/38701548-0620200c-3e53-11e8-9a45-3b4788b9bc31.png">

**Comment by kristinashu** [comment]
We can address this later
