### ISSUE TITLE
Wagtail QA: Heading Styles

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1329]
From @kristinashu  in #1325 

- will [this](https://github.com/mozilla/foundation.mozilla.org/pull/1324#issuecomment-380906497
) fix the heading styles here too?

**Comment by alanmoo** [comment]
@kristinashu Can you clarify? What other styles need fixing?

**Comment by kristinashu** [comment]
## For pages primary pages I can edit like About Us:

**In the editor for this page https://foundation.mozilla.org/wagtail/about/public-records/ I have selected H3**

<img width="392" alt="screen shot 2018-04-12 at 1 18 17 pm" src="https://user-images.githubusercontent.com/1068783/38701966-29f6e46a-3e54-11e8-9eac-18721f39ded4.png">

**The H3 ends up looking like this**

<img width="461" alt="screen shot 2018-04-12 at 1 18 28 pm" src="https://user-images.githubusercontent.com/1068783/38701982-372816f4-3e54-11e8-9d81-0ea232eb6d5a.png">

**But it should look like the style guide https://foundation.mozilla.org/style-guide/**

<img width="595" alt="image" src="https://user-images.githubusercontent.com/1068783/38702302-1dd853b6-3e55-11e8-8c63-72c9d443294b.png">


## For primary pages I can't edit like Initiatives, Participate, People

**On https://foundation.mozilla.org/wagtail/people/ "Member Spotlight" looks like this** 

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/1068783/38702228-e9e0eb36-3e54-11e8-8c04-7cd1a5b9ab37.png">

**It should look like it does on the live site https://foundation.mozilla.org/people/**

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/1068783/38702190-cd81c938-3e54-11e8-9ab8-43579aaf0e7d.png">

**Comment by alanmoo** [comment]
Ah. So we need to add the heading element selectors to the CSS where we've got the `.hx-heading` classes.
