### ISSUE TITLE
Wagtail QA: Bullet points

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1331]
From @kristinashu  in #1325 

- Spacing after bullet points should be the same or larger than before them
Screen cap from production looks confusing because bullets look grouped with content bellow, not above
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/1068783/38700407-ce8e518e-3e4f-11e8-8281-3eca8e79f76f.png">

**Comment by Pomax** [comment]
The reason this is going wrong is because the structure her is:
```
<p> Bylaws [...]</p>
<ul>
   [ list elements]
</ul>
<p>Conflict [...] </p>
```
and paragraphs have uneven margins. Our CSS sets this:
```
p {
  margin-top: 0;
  margin-bottom: 1rem; }
```
and so the real problem is the paragraph below the `ul` "glueing" itself to the content above it.
