### ISSUE TITLE
Signup confirmation message bug

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1339]
We got an email:

Hi, I observed  <br/> tags together with the text on the confirmation
page(I attached a screenshot) after a user signs up for updates

**Comment by taisdesouzalessa** [comment]
I guess this is the screenshot (`<br/>` tags):

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/22157921/38746984-30e66a84-3efe-11e8-9cbf-a6178e80eba3.png">

**Comment by gvn** [comment]
Did they happen to give us a URL?

**Comment by taisdesouzalessa** [comment]
To reproduce the screen above: 1. go to: https://foundation.mozilla.org/ - 2. fill in the box with your info / 3. You will then see the screenshot above.
