### ISSUE TITLE
Heading styles broke 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1344]
Multiple headings are broken on production 

https://foundation.mozilla.org/initiatives/
https://foundation.mozilla.org/participate/
https://foundation.mozilla.org/people/

<img width="1142" alt="image-1" src="https://user-images.githubusercontent.com/1068783/38752680-f3f556c2-3f10-11e8-81e9-28b5ab1f89b5.png">
<img width="295" alt="image" src="https://user-images.githubusercontent.com/1068783/38752681-f40f3af6-3f10-11e8-879d-af21390b55bd.png">

**Comment by kristinashu** [comment]
Assigned to @gvn and @alanmoo but not sure who is doing this.

**Comment by alanmoo** [comment]
I've got this one

**Comment by kristinashu** [comment]
https://foundation.mozilla.org/initiatives/ should be h3
<img width="707" alt="image" src="https://user-images.githubusercontent.com/1068783/38754632-7fed922e-3f17-11e8-857d-2feb87e7c600.png">

https://foundation.mozilla.org/participate/ should be h4
<img width="902" alt="image" src="https://user-images.githubusercontent.com/1068783/38754651-8eb11dc6-3f17-11e8-9c27-b3ecb2bd947d.png">

https://foundation.mozilla.org/people/ should be h3
<img width="772" alt="image" src="https://user-images.githubusercontent.com/1068783/38754667-9da836d4-3f17-11e8-9730-f4095f726c82.png">

**Comment by kristinashu** [comment]
Just noticed news page as well https://foundation.mozilla.org/news/ 

<img width="1200" alt="screen shot 2018-04-13 at 4 11 18 pm" src="https://user-images.githubusercontent.com/1068783/38761160-74ed41bc-3f35-11e8-9102-f9e4c0452961.png">

**Comment by kristinashu** [comment]
Opened News page as a separate ticket https://github.com/mozilla/foundation.mozilla.org/issues/1360
