### ISSUE TITLE
[QA: primary wagtail pages] About Us should show selected state

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1353]
### "About Us" in main nav should show select state. black underline.

https://foundation.mozilla.org/wagtail/about/ (missing underline)
<img width="1420" alt="screen shot 2018-04-13 at 2 58 45 pm" src="https://user-images.githubusercontent.com/1068783/38759590-788545d6-3f2b-11e8-9d45-add7d89538f7.png">

https://foundation.mozilla.org/about/ (good underline)
<img width="1423" alt="screen shot 2018-04-13 at 3 02 37 pm" src="https://user-images.githubusercontent.com/1068783/38759645-bb6d39b2-3f2b-11e8-93bd-bdbad0ab8f7c.png">

**Comment by alanmoo** [comment]
This should automatically be fixed once we switch the wagtail pages to the long-term routes. It's technically not broken now, since you're not actively on that page.
