### ISSUE TITLE
[QA Primary Pages] Sub nav styling

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1354]
Type and underline in the subnav should look the same as the main nav. Intended as per [comp](https://redpen.io/rn6bd6ea7068af8f53).

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/1068783/39316910-2e308a28-492f-11e8-8952-d2bf0160fa9a.png">

But on prod: https://foundation.mozilla.org/wagtail/about/ 
- subnav font is too large 
- underline in subnav is too thick 
- underline in subnav too far below the nav text

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/1068783/39316928-3a203342-492f-11e8-91f6-33c3d32a5016.png">

**Comment by Pomax** [comment]
@kristina image for the "real" look was missing the actual nav elements so I tried to do a new screenshot, but of course the site switched over so there is nothing to compare now. Do we still have a comp that we include a comparison shot based off of?

**Comment by kristinashu** [comment]
Yes, here's the comp https://redpen.io/rn6bd6ea7068af8f53

You can reference the main nav as much as possible.

**Comment by kristinashu** [comment]
Follow up would be that this style should then be applied to the subnav on the [Fellowship pages](https://foundation.mozilla.org/fellowships/).

**Comment by kristinashu** [comment]
Closing this ticket and opened broader ticket to make all sub navs more consistent https://github.com/mozilla/foundation.mozilla.org/issues/1465
