### ISSUE TITLE
[QA: primary wagtail pages] Add more paragraph styles to Rich Text editor

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1356]
Please add `.body-large` and `.quote-feature` as paragraph styles to the text editor.

These styles are from our main style guide https://foundation.mozilla.org/style-guide/

This will give us more flexibility to style text and make intro paragraphs stand out more over normal body text.

**Comment by alanmoo** [comment]
I'm not sure this is going to be directly customizable using the text editor, it may be another streamfield content type. Can you point to examples of where/how that gets used to make sure we address the needs properly?

**Comment by kristinashu** [comment]
Would be nice for things like this but we can hold off on it for now.

<img width="772" alt="screen shot 2018-04-16 at 9 16 30 am" src="https://user-images.githubusercontent.com/1068783/38886158-fe767e5c-4229-11e8-91fb-cf8aa6ce89cf.png">
<img width="976" alt="screen shot 2018-04-16 at 9 18 16 am" src="https://user-images.githubusercontent.com/1068783/38886159-fe8cd558-4229-11e8-93f8-e4c3879b4bdc.png">

**Comment by kristinashu** [comment]
I take that back, having the .body-large class would be useful.

**Comment by alanmoo** [comment]
From this I can see how large body text might be used as part of the template for various CTA components, but not something that should be tied into the rich text editor as an additional option. Does that make sense? This is the kind of thing the zen of wagtail article was talking about- separating design and content.

**Comment by kristinashu** [comment]
Ok I'll put this on designers until we have done a full audit of what components we need the most.
