### ISSUE TITLE
Helper copy: Foundation site

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1357]
In our Foundation site, we always have some helper copy that gives the audience some context on what they will see on the page:
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/22157921/38760732-57033268-3f32-11e8-9c56-921a317eb77e.png">
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/22157921/38760737-6514801e-3f32-11e8-943e-906d107ded14.png">

This context doesn't exist on the new wagtail pages at the moment:
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/22157921/38760756-89e428cc-3f32-11e8-9be7-d9a14f4cbc2a.png">

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/22157921/38760776-bf996194-3f32-11e8-9985-f5d93c208146.png">

I think having the context really help the audience to understand our organization, particularly if they are new to the site. I was wondering if we are moving away from that style of header and also to collect your thoughts on this topic: @kristinashu @xmatthewx

**Comment by kristinashu** [comment]
This was a request from Jesse. Something along the lines of not want to have to write the copy! But I agree, we should work in some intro text below the banner.

**Comment by xmatthewx** [comment]
Adding to this... a goal is to move content out of the header and into the body. New content will have good intros. If any interim page seems totally broken without, we could look to add some temp words at the top of the body copy, but only if it seems totally broken.

**Comment by kristinashu** [comment]
This is coming with the new design.
