### ISSUE TITLE
[QA: primary wagtail pages] Home page Happening Now is missing dividing lines

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1358]
Home page Happening Now is missing dividing lines.

https://foundation.mozilla.org/wagtail/ (no lines)
- Note: prod doesn't have a dividing line above the first post, I think it is ok if it does. In other words, it can be a rule that all the posts have a line, not just the 2nd and 3rd one.
<img width="1093" alt="screen shot 2018-04-13 at 3 59 35 pm" src="https://user-images.githubusercontent.com/1068783/38760935-d18d9c52-3f33-11e8-87ab-3f049c1bfc42.png">

https://foundation.mozilla.org/ (with lines)
<img width="1127" alt="screen shot 2018-04-13 at 3 59 01 pm" src="https://user-images.githubusercontent.com/1068783/38760909-a0b2b130-3f33-11e8-8611-2df9181a16c8.png">

**Comment by alanmoo** [comment]
Fixed on production.
