### ISSUE TITLE
[QA] News page headings should not be highlighted

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1360]
From https://github.com/mozilla/foundation.mozilla.org/issues/1344#issuecomment-381281772

Headings on News page still look broken  https://foundation.mozilla.org/news/

<img width="1200" alt="screen shot 2018-04-13 at 4 11 18 pm" src="https://user-images.githubusercontent.com/1068783/38761160-74ed41bc-3f35-11e8-9102-f9e4c0452961.png">

**Comment by alanmoo** [comment]
Are they the correct typeface and the only problem is the background color stretching down?

**Comment by kristinashu** [comment]
Years seem to be fine (should be Zilla Slab 72 in light gray). There should be no black background at all. Just gray text on white background.

**Comment by alanmoo** [comment]
Got it.  Seems like my solution for fixing the headings last week was a little over-zealous. The PR that's open dials it back a bit.

**Comment by kristinashu** [comment]
Ok good. Will it fix these as well? https://foundation.mozilla.org/fellowships/

<img width="1148" alt="screen shot 2018-04-16 at 9 01 45 am" src="https://user-images.githubusercontent.com/1068783/38821230-d16e942e-4154-11e8-9378-250d44bb211b.png">

**Comment by alanmoo** [comment]
Yes.
