### ISSUE TITLE
Implement Nav 'zen mode'

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1363]
### Comps: https://redpen.io/p/bk3ac2ba96e659d333

- mini (zen mode) nav for all primary pages not in the main nav + all Opportunity/Campaign pages
- note: at narrow widths, mobile nav and zen mode nav look and act the same way
- home page nav and Opportunity/Campaign pages nav have white background with black dividing line

### Page types:
![screen-shot-2018-04-16-at-8 17 21-pm](https://user-images.githubusercontent.com/1068783/38846987-188cbba6-41b4-11e8-8ca7-1dc7d97193e0.jpg)

**Comment by alanmoo** [comment]
@ScottDowne This may be for you.

@kristinashu Do you have comps of what it looks like when the menu is clicked? Does Zen mode just look like regular mode then? And are we indeed using the kebab instead of the hamburger? I'm pretty sure @jessevondoom said something about using the burger.

**Comment by kristinashu** [comment]
Yes, when Zen mode menu is open it looks the same as the regular menu but with a close icon. Yes, the latest [comps in redpen](https://redpen.io/p/bk3ac2ba96e659d333) have the burger instead of the kebab.

Here are a couple animation examples of the Zen mode opening and closing:
- https://cashmusic.org/
- https://blog.intercom.com/ (need to scroll down)

**Comment by kristinashu** [comment]
@ScottDowne Mavis just made font updates to the nav on staging so please use those styles. I.e. should be Nunito Sans (not Open Sans) and please also keep her font sizes and line heights.

**Comment by kristinashu** [comment]
This is done and it's awesome! 

Some follow up in https://github.com/mozilla/foundation.mozilla.org/issues/1473 but closing this ticket.
