### ISSUE TITLE
Improve UX on campaign pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1366]
Continuation of https://github.com/MozillaFoundation/Design/issues/271

Create wireframes to explore ways we can enhance our campaign pages. This could be new features like recommending similar campaigns, better social share options, better thank you and confirmation when signing a petition, better mobile options...

Could also update old [benchmarking deck](https://docs.google.com/presentation/d/1X31GHF9SclchaMY-K4Lo2XvUEAmmGrUjGHht-IHt0Q4/edit#slide=id.g15c71e0009_0_139).

**Comment by kristinashu** [comment]
Oh adding localization to this. Currently there is this [hack](https://foundation.mozilla.org/campaigns/facebook-update/). Our solution will also probably have to be a bit of a hack but I'm sure we can do something better.

**Comment by kristinashu** [comment]
cc @vojtechsedlak

**Comment by vojtechsedlak** [comment]
Just to flesh out some of the desired user flow, when someone submits the form and has checked the checkbox for newsletter signup, we should give them the following message above the share buttons: 

"Thanks! Please check your inbox to confirm your subscription.

If you haven’t previously confirmed a subscription to a Mozilla-related newsletter you may have to do so. Please check your inbox or your spam filter for an email from us."

If they haven't checked the subscription checkbox, they can just get a regular thank you message and the share buttons.

Please let me know if there is anything else I can help with on this. Thanks!

**Comment by xmatthewx** [comment]
As we work on this, let's consider easy incremental improvements (like better thanks/confirmation and a language picker), along side ambitions for the future (like suggested campaigns/projects from a pulse tag). After a bit of design we can organize phased implementation.

**Comment by kristinashu** [comment]
Yeah there are some awesome ideas in there @beccaklam! 

I think it'd be useful to see a high-level flow diagram of possibilities. So less about what the page looks like and more about when and what we prompt users with.

**Comment by vojtechsedlak** [comment]
These look amazing! I'd suggest looping in Jon, Will and Sara, who have a lot of knowledge about improving conversion rates on action pages. Ideally we would want to test the impact of individual elements on conversion and action rates, so a modular design, where elements such as counters, recent signers etc. can be added and removed would be best.

**Comment by sabrinang** [comment]
+1 to vojtech's comment above - I like the idea of displaying a countdown or deadline that helps communicate a sense of urgency to signers too for campaign pages

**Comment by beccaklam** [comment]
@vojtechsedlak I mocked up some tests we could do in the redpen (the wireframe flows near the end): https://redpen.io/p/gz26fa3bd26ec0cb81. Not sure what next steps would be to refine these and get some testing implemented?

**Comment by vojtechsedlak** [comment]
I will pull some metrics together today @kristinashu. Will update the ticket.

**Comment by vojtechsedlak** [comment]
Here is a rundown of some of the metrics, I will keep adding to this doc: https://docs.google.com/document/d/1W2mTcYlQbhbHexAwWH16r1phq8LBfF-myqEm4WlthAQ/edit# 

Let me know if there are any specific questions to focus on that would help with the design process.

**Comment by kristinashu** [comment]
Super interesting! Thank you Vojtech. I'm going to share this with the rest of the design team since I think they'll also find it interesting.

Otherwise, I'm going to close this ticket and continue UI design in https://github.com/mozilla/foundation.mozilla.org/issues/1459
