### ISSUE TITLE
About page active state in navigation doesn't work

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1367]
STR:

Visit https://foundation.mozilla.org/about/
Notice "About" in nav isn't underlined

**Comment by Pomax** [comment]
visual details"

![image](https://user-images.githubusercontent.com/177243/38839590-3531b49c-4190-11e8-9ebb-716002350ef7.png)

vs.

![image](https://user-images.githubusercontent.com/177243/38839592-3e407924-4190-11e8-8a15-e422fd17d425.png)
