### ISSUE TITLE
[QA: primary wagtail pages] Admin - Up/Down arrows in Home Page Highlights don't work

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1371]
I'm updating posts so they reflect what was in Mezzanine. This is the order post should be in (Global Sprint and Dear Facebook as main features):

<img width="387" alt="screen shot 2018-04-16 at 4 33 46 pm" src="https://user-images.githubusercontent.com/1068783/38840345-f7b3cd4a-4193-11e8-9127-010cd3a3b6e7.png">

When I try to reorder the posts in Wagtail using the up/down arrow it looks good in the admin but then the order isn't actually reflected on prod when I publish it: 
<img width="706" alt="screen shot 2018-04-16 at 4 29 49 pm" src="https://user-images.githubusercontent.com/1068783/38840341-f62ad5a4-4193-11e8-970f-aa25b12adb7e.png">

Prod even after the update (shows Global Sprint and Facebook Container):
<img width="979" alt="image" src="https://user-images.githubusercontent.com/1068783/38840415-5ea60518-4194-11e8-9fb4-1dd866275b1d.png">

**Comment by kristinashu** [comment]
I just clicked "Submit for Moderation" thinking that might fix it but I'm not sure.

<img width="476" alt="image" src="https://user-images.githubusercontent.com/1068783/38840767-18512adc-4196-11e8-9ddd-1cdd491326f5.png">

**Comment by Pomax** [comment]
I've run into this as well, I've filed https://github.com/wagtail/wagtail/issues/4477 because this seems a wagtail bug, but I'm not sure.
