### ISSUE TITLE
Optimize vertical space in CMS componemts

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1379]
Currently, wagtail components mash against the content above. They could use some better default vertical margins. See screenshot below. This happens whether a heading is in the same component, or in a subsequent component. While manual vertical space components are useful, a better default margin for staff would help prevent lots of trouble. 

I think we should prioritize this over some other style improvements. Changing this default later would require updating lots of manual space components added by authors.

Manual "triple" space component would be good as a default

## Current

![image](https://user-images.githubusercontent.com/53411/38886528-393229be-4244-11e8-839e-af7ede82e438.png)
.
.
.

## Manual "triple" space

![image](https://user-images.githubusercontent.com/53411/38886512-2b5cba0c-4244-11e8-9166-0811aeef6b35.png)

**Comment by kristinashu** [comment]
@taisdesouzalessa @gvn are looking into spacing

**Comment by taisdesouzalessa** [comment]
Ticket on spacing (on a system level) is opened and being tracked here: #1404 - I referred to this ticket there as well.

**Comment by kristinashu** [comment]
I'm going to close this ticket since we're looking at it more holistically in #1404
