### ISSUE TITLE
[QA] Missing style guide

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1387]
Something change yesterday or so.
https://foundation.mozilla.org/style-guide/ 
- this is what I used to go to
- it used to reflect the latest [type updates ](https://docs.google.com/spreadsheets/d/1Z1oScv_5NfhGGkFg6nH-_16dKWSyPcNhrKdA5E_QwIk/edit#gid=0)
- now the page is missing and I see a 404 page

https://foundation.mozilla.org/styleguide/
- this seems to load but shows old/wrong type styles

**Comment by alanmoo** [comment]
URL's been reverted- that was just a change in the CMS. Unsure what's different about the type styles. Can you point out a specific one and what it should be instead?

**Comment by kristinashu** [comment]
None of the work Mavis during the sprint is reflect now. Although it was fine a couple days ago. Most of the headings are wrong (name and style). This is what it should be:
![typography](https://user-images.githubusercontent.com/1068783/38903239-cfc34b56-4258-11e8-8b09-a5d90310bcf2.jpg)
