### ISSUE TITLE
[Fellowships Mini Site] Make deadline for Application more prominent - implementation ticket

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1396]
Related to  #1228

## 1) update fellowship overview page
 
 - [ ] add new date+button. (
 - [ ] place this higher on the page
      - place the call out after the 2nd paragraph. Above "More than ever, we need a movement..."
      <img width="500" alt="image" src="https://user-images.githubusercontent.com/53411/38103516-81a992e4-3354-11e8-86fa-817038cf9ddb.png">

## 2) update the apply page
 
 - [ ] update style on due date next to button at bottom <img width="400" alt="image" src="https://user-images.githubusercontent.com/53411/38104002-f2da5d9e-3355-11e8-9f56-208f30e32ae1.png">
 - [ ] after the first paragraph, add a new element with date. it should look exactly like component on the homepage. But don't include the button. <img width="400" alt="image" src="https://user-images.githubusercontent.com/53411/38104134-494f19ee-3356-11e8-8c89-463f22fff230.png">

Sketch file: https://drive.google.com/open?id=15st_Yd-GS4nAFgqqp-ci8QU1g4pWLdWr

**Comment by mmmavis** [comment]
Hey @taisdesouzalessa the Sketch file doesn't really match the specs so I wasn't sure what to follow. Could you head to https://github.com/mozilla/foundation.mozilla.org/pull/1406 and let me know what needs fixing in that PR?

**Comment by taisdesouzalessa** [comment]
oh shoot, really? Sorry for that, I though they matched. I will check and make a list of fixes. Thanks @mmmavis

**Comment by mmmavis** [comment]
@taisdesouzalessa no worries & thanks!

**Comment by kristinashu** [comment]
Is this done? @taisdesouzalessa can you please QA and close if it's all good?

**Comment by taisdesouzalessa** [comment]
QAd, done and now closed! Yay.
