### ISSUE TITLE
[QA Wagtail] Issue uploading image with the same name

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1400]
_Assigning Alan for triage_

### Issue
I was trying to upload an image that has the same name as an existing image with the hope I could replace it. However when I do it, what happens is that the previous image stays there and the new image is not uploaded. Example below:

![wagtail-bug](https://user-images.githubusercontent.com/22157921/38900679-001207d2-4251-11e8-90ab-da76fb3c135a.gif)

Maybe this is intentional so users won't overwrite existing images by accident? If so, is there any way we could tell users something like "an image with this name already exists, please try another name" or something like that? So we can give them clear instructions on what to do to fix it.

**Comment by alanmoo** [comment]
What are you clicking to get the initial dialog box to open in the gif?

**Comment by taisdesouzalessa** [comment]
I am clicking on "Change Image". Sorry, I think LiceCap took a while to start recording... 
<img width="732" alt="image" src="https://user-images.githubusercontent.com/22157921/38904195-e08455f2-425d-11e8-8922-5b1ee33145b8.png">

**Comment by alanmoo** [comment]
Honestly, the easiest solution for this seems like it might be "don't do that". I suspect it's something deep in the way Wagtail is built and won't be worth our energy to try and fix it when we have other things to do. Do note that you could click "edit this image" to swap out the image (I believe that would change it anywhere it's used across the site).

I'm not sure how many times you tried it, but this image has now been uploaded a bunch of times to production:
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/1682681/38934915-f7b845b6-42ea-11e8-981e-4229dd1c72f0.png">

**Comment by taisdesouzalessa** [comment]
@alanmoo Yeah I tried many times as you can see...sorry. I am trying to delete copies of this image (and of Alan Davidson's copies) but in some cases I am receiving an error message like that:

![images-wagtail](https://user-images.githubusercontent.com/22157921/38946367-16a7d510-42ee-11e8-8bff-964a1f98bae7.gif)

Given we won't be working on a solution for that in the near future, I will close this ticket and open a new one for the error message problem.
