### ISSUE TITLE
campaigns don't seem to render quite the same if there's (unlisted) children

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#1401]
compare https://foundation.mozilla.org/wagtail/campaigns/india-needs-strong-privacy-and-data-protection-law/ (no children) to https://foundation.mozilla.org/wagtail/campaigns/facebook-and-european-parliament/ (unlisted children)

**Comment by Pomax** [comment]
first link:
![image](https://user-images.githubusercontent.com/177243/38902257-9cfa74b4-4254-11e8-840b-6ec58f3e5a10.png)

**Comment by Pomax** [comment]
second link:
![image](https://user-images.githubusercontent.com/177243/38902261-a3a55e5a-4254-11e8-9ec6-67bdf47b3357.png)

**Comment by Pomax** [comment]
This looks like a missing `offset-md-2` from the `py-5 col-12 col-md-9` rule

**Comment by kristinashu** [comment]
@Pomax did #1568 fix this?

**Comment by Pomax** [comment]
fixed in the past.
