### ISSUE TITLE
[QA Opportunity] Figure Grid isn't working

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1407]
Figure Grid component isn't working on Wagtail:
https://foundation.mozilla.org/wagtail/opportunity/global-sprint/
<img width="431" alt="image" src="https://user-images.githubusercontent.com/1068783/38907068-d8d78278-426e-11e8-9cd6-c5b8611d5809.png">

It should look like it does on Mezzanine:
https://foundation.mozilla.org/opportunity/global-sprint/
<img width="882" alt="image" src="https://user-images.githubusercontent.com/1068783/38907076-e4ce9fc6-426e-11e8-9da1-6d0863fcbd11.png">

Slack convo:
P:
that's actually a good case of "We have mutually exclusive needs"
you landed a PR that allows the flexbox to wrap, but that means with images set to original size, it wraps immediately
so it might be wise to undo that wrap, and say "don't use more than x figures. If you need more, use another grid"
A:
Mmm. Yeah I was landing for about page, recognized that need may be different elsewhere
P:
or use more if you need like 10 icons next to each other of course
is the about page use-case fixable by "using another flexgrid" instead?
A:
This is something gvn should run
Note that specific use of flex grid on the leadership page will eventually go away as we move to better profile cards. Not sure about that need for flexgrid elsewhere

**Comment by kristinashu** [comment]
Updated it to 200x200. It's ok but not great ...

<img width="934" alt="image" src="https://user-images.githubusercontent.com/1068783/38963940-3766f840-4329-11e8-91cd-ad1989edbd09.png">

**Comment by gvn** [comment]
This should be good to go now, but we should close this after it's switched over to the new component on prod.

**Comment by kristinashu** [comment]
It's live and it looks great! https://foundation.mozilla.org/opportunity/global-sprint/
