### ISSUE TITLE
Broken Links on Foundation Site

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#1413]
Some incorrect URLs leading to 404 page
<img width="780" alt="image" src="https://user-images.githubusercontent.com/2492510/38950437-61871a12-42fa-11e8-8653-35cba8a87204.png">
 
____________
**Home page on Latest News section - main news item**
<img width="711" alt="image" src="https://user-images.githubusercontent.com/2492510/38949918-cac451cc-42f8-11e8-912b-604574572797.png">
 
____________
**Initiatives on Events section - Upcoming Events**
<img width="549" alt="image" src="https://user-images.githubusercontent.com/2492510/38949999-03fef9ec-42f9-11e8-94da-2e548de9cf96.png">
 
____________
**About Us section - Mozfest, Internet health report, advocacy are all 404:**
<img width="388" alt="image" src="https://user-images.githubusercontent.com/2492510/38950147-73da1bd4-42f9-11e8-9313-d377d28d944e.png">

**Comment by kristinashu** [comment]
These are all fixed except for Upcoming Events on https://foundation.mozilla.org/initiatives/
@gvn can you please remove that link?

**Comment by alanmoo** [comment]
Assigning to you too @mmmavis in case you can get to it first.

**Comment by mmmavis** [comment]
sure @alanmoo @kristinashu so where should the "Upcoming Events" link go?

**Comment by kristinashu** [comment]
Please remove that link/text entirely.

**Comment by kristinashu** [comment]
Done! Thanks!
