### ISSUE TITLE
IHR graphic for consumer press

### ISSUE THREAD

**Issue by KevZawacki** [mozilla/foundation.mozilla.org#1414]
Phase II of IHR press pitching focuses on consumer press: USA Today, Mashable, Teen Vogue, etc. 

We need a simple graphic highlighting the ways the IHR empowers readers. Text would be something like:

Three ways to make your personal internet experience healthier:

- Protect yourself and your devices with strong passwords and two-factor authentication

- Always update your computer and phone software as soon as a security update is available

- Take an 8-day data detox at https://datadetox.myshadow.org/detox

Find more tips at https://internethealthreport.org/2018/participate/

**Comment by KevZawacki** [comment]
(@xmatthewx realizing this is the wrong repo -- is there a general design repo?)

**Comment by xmatthewx** [comment]
thanks @KevZawacki - https://github.com/mozillafoundation/design/issues and https://mzl.la/project-brief
