### ISSUE TITLE
Fix column layout for "true single page" vs. "looks like single page, has children" campaigns

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#1420]
There are a few quirks that need to be addressed around the column layout (both in terms of _being_ column layout, as well as offset classes) in campaign pages.

### true single page campaigns
- the CTA should be a right column, not below the content (e.g. equifax)

### "looks like single page" campaigns
- the content does not have the correct offset class applied, making it present way too much to the left of the viewport (e.g. facebook campaign pages)

**Comment by kristinashu** [comment]
@Pomax did #1568 fix this?

**Comment by Pomax** [comment]
fixed in the past.
