### ISSUE TITLE
Default URL given doesn't work

### ISSUE THREAD

**Issue by irrationalRock** [mozilla/foundation.mozilla.org#1424]
Hi, I have been reading the documentation for the last couple of days and noticed that it mentions `https://localhost:8000` to go to the website.

However, this didn't work for me and I needed to use `http://127.0.0.1:8000/`.

I think it would be better to change the url to point to `http://127.0.0.1:8000/` or say the user should look at the result of `python manage.py runserver` and go to whatever it's pointing to.

**Comment by aryanc403** [comment]
@irrationalRock I think issue is already fixed with removal of s from https://localhost:8000 in readme.

**Comment by irrationalRock** [comment]
@aryanc403  thanks, it must of been updated since posting this issue.
