### ISSUE TITLE
[Wagtail UX] Campaign page localization

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1426]
I believe @TheoChevalier came up with this cleaver hack for localizing campaigns.

<img width="1418" alt="screen shot 2018-04-19 at 9 01 06 am" src="https://user-images.githubusercontent.com/1068783/39004066-2e37ba56-43b1-11e8-8d6f-b3e5452d87fb.png">

@TheoChevalier @sabrinang I'm wondering if you have any examples or suggestions for a better long-term solution to show localization? Would a drop-down menu be better? Any examples you have would be great.

@alanmoo @Pomax what are our constraints? 

Is it possible to localize the form? What are the alternatives to creating new sub pages for each language?

**Comment by alanmoo** [comment]
Wagtail does offer some support for internationalization of sites: http://docs.wagtail.io/en/latest/advanced_topics/i18n/index.html#creating-sites-with-multiple-languages

I'd like to look into that once campaigns are live on wagtail.

**Comment by TheoChevalier** [comment]
Thanks for starting this discussion, @kristinashu !

I will take a stab at listing some localization needs for the campaign pages. 

**Displaying the most relevant content**
A drop-down like in the footer of www.mozilla.org or the header of www.changecopyright.org would definitely be a good improvement, and would help us scale a little bit.

Another one is coupling this drop-down to some language negotiation from a canonical URL: reading the user’s browser language preferences and making a decision to redirect based on this). The drop-down would then be used only to override the choice we made. Similar behavior to the websites listed above.
This boils down to what’s doable on Watgail side. If we can’t add/enable this feature yet, I would advocate for the language switcher to remain prominent if possible, to avoid lower engagement numbers.

**Petition form & subscriptions**
The petition form would need some fixes too, besides localizing the fields. If the user’s language is included in this list `de, es-*, fr, it, pl, pt-*` we should send his locale to Basket. In all other cases, we would default to en-US. Currently, everyone is subscribed to en-US, which is of course not ideal.

For localizing the form itself, I don’t know the current implementation. However if it’s already a Jinja2 template, it should be possible to extract the strings into a gettext-like file format. And then localize those files with Pontoon following our usual process.

Hope this helps, but happy to clarify any of the above if needed!

**Comment by TheoChevalier** [comment]
> So to clarify, it seems like the current approach is tolerable for the time being, and we should focus on localizing the petition form itself first?

Yes, I think that’s a higher priority

**Comment by alanmoo** [comment]
I believe the original needs of this have been met, if more l10n work is needed on the site let's create a new issue describing the latest situation.
