### ISSUE TITLE
search on the CMS "people" page errors out

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#1430]
example: https://foundation.mozilla.org/cms/people/person/?q=cake

**Comment by kristinashu** [comment]
This seems to work now but please re-open if it isn't.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1068783/50936992-be910a80-1426-11e9-8b52-81c677db95eb.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1068783/50936977-b638cf80-1426-11e9-9427-12c4a647687f.png">
