### ISSUE TITLE
[Wagtail Component] Remove Heading Component

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1437]
~If we add H1 to the Paragraph styles #1389 then should we remove the Heading component since a Paragraph component can do everything it can do and more!~

Having fewer components will be easier for people to use and as is Heading component only allows for H1 which isn't useful.

Updated: Only things this ticket needs to do is remove the 'Heading' component.

**Comment by gvn** [comment]
I'm fine either way. If we keep the heading we should probably allow people to choose the heading level, otherwise it's not that useful.

**Comment by kristinashu** [comment]
For simplicity, I think we should remove it. We could always rename `Paragraph` to `Text` to make it more generic.

**Comment by Pomax** [comment]
@kristina this kind of fell off the roadmap, do we still want to remove this?

**Comment by youriwims** [comment]
@kristinashu have we settled on renaming the `Paragraph` component? If so, I'll open a separate issue for that.

**Comment by youriwims** [comment]
What's the best way to do a block inventory search for `Heading`?

/cc: @mmmavis @Pomax

**Comment by kristinashu** [comment]
I don't think renaming it will be necessary, let's just keep the name `Paragraph`. Also don't think we need to add H1 to the Paragraph component since the Title/Header field using H1 and we should restrict it's use.

So the only things this ticket needs to do is remove the 'Heading' component. I don't see any instances of this in the Block Inventory search but let me know if you see any and I'll update them to Paragraphs.

Thank you!

**Comment by youriwims** [comment]
From what I can tell, it looks like `Heading` is still active on these pages:

- [ ] https://foundation.mozilla.org/en/news/
- [ ] https://foundation.mozilla.org/en/style-guide/
- [ ] https://foundation.mozilla.org/cms/pages/169/view_draft/ (Draft page...may not be important)

I'm going to do a bit more digging to make sure there's no more instances of this component.

**Comment by kristinashu** [comment]
I've just deleted that old draft page. The first two on your list aren't cms pages so I don't think they are relevant, but @mmmavis any thoughts?

**Comment by mmmavis** [comment]
> https://foundation.mozilla.org/en/news/
Headings in the article list shouldn't be affected as the list is generated via JS.

> https://foundation.mozilla.org/en/style-guide/
This is a hardcoded static page. Things here shouldn't be affected.

I'm not sure what the proper way is to remove a component on CMS without breaking pages that are already using them. @Pomax can you chime in here?

**Comment by youriwims** [comment]
@Pomax just removed the `Heading` component from those two pages—going to go ahead and remove the component now. Btw @mmmavis [this guide](https://github.com/mozilla/foundation.mozilla.org/blob/master/docs/workflow.md) helped me understand the component removal process pretty well.
