### ISSUE TITLE
[Wagtail Component] Figure, Image, Image text, Figure Grid

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1438]
@taisdesouzalessa @gvn we should look at these 4 components more holistically and see how we can make them easier to use and better looking.

### Image
- Image (size + alignment) 
<img width="1238" alt="screen shot 2018-04-20 at 1 13 57 pm" src="https://user-images.githubusercontent.com/1068783/39072923-ea73c7b0-44a0-11e8-84cd-dae760595788.png">
<img width="780" alt="image" src="https://user-images.githubusercontent.com/1068783/39072929-ef3b0344-44a0-11e8-815d-251acec41d2f.png">

### Figure
- Image (size + alignment) 
- Caption (paragraph text style)
- URL (turns paragraph into link)
- (result = image on top of text)
<img width="1240" alt="screen shot 2018-04-20 at 1 13 43 pm" src="https://user-images.githubusercontent.com/1068783/39071828-53b2347c-449d-11e8-9193-fd707f386700.png">
<img width="901" alt="image" src="https://user-images.githubusercontent.com/1068783/39072634-fd81218c-449f-11e8-934e-c00e11de66e6.png">

### Image text
- Text (paragraph text style)
- Image (size + ordering (similar to alignment))
- (result = image left of text)
<img width="1242" alt="screen shot 2018-04-20 at 1 14 39 pm" src="https://user-images.githubusercontent.com/1068783/39071830-53d960a6-449d-11e8-8b29-9fd50c804731.png">
<img width="939" alt="image" src="https://user-images.githubusercontent.com/1068783/39072659-0da507b8-44a0-11e8-86a4-48f3dd5a64ef.png">

### Figure Grid
- Multiple Figures
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/1068783/39072843-a841880a-44a0-11e8-8183-75f75f436876.png">
<img width="981" alt="image" src="https://user-images.githubusercontent.com/1068783/39072858-b80f0014-44a0-11e8-9a42-6a0e43d543fd.png">

**Comment by kristinashu** [comment]
I need to think through this more but I think using the Paragraph component would help streamline the `Caption`, `URL`, and `Text` fields into one consistent and flexible field/options. Then it's a matter of the text being below or beside the image.

**Comment by taisdesouzalessa** [comment]
@kristinashu is this issue related to the discussion we had today with the figure grid or is it bigger than that?

**Comment by kristinashu** [comment]
We talked about the Figure Grid component but not really the other components how they all fit together.

**Comment by gvn** [comment]
I'd like to get rid of the "size" options entirely since Wagtail can handle image sizing for us.

It'd be nice to drop the alignment options too as much as possible. I feel like a broken record, but we want to keep users focused on content and not layout.

**Comment by taisdesouzalessa** [comment]
Agree with the mantra "keep users focused on content not layout"  💯 .

About the image sizes, I think for the "figure grid" it should adjust to the page's grid as we discussed yesterday.

For image + copy (side by side), I think it would be cool if the system could accommodate at least 2 scenarios:

**1. Image on the left + body copy on the right**
<img width="834" alt="image" src="https://user-images.githubusercontent.com/22157921/39203392-7b28fe5a-47a9-11e8-8d58-78e57b5c64a0.png">

**2. Image on the left (small) + title on the right (h2-h6)**
Offer the option to add icons to titles.
<img width="780" alt="image" src="https://user-images.githubusercontent.com/22157921/39203678-52b09630-47aa-11e8-9772-403e40f84bc0.png">

**Comment by kristinashu** [comment]
I'm all for removing options but just want to make sure things will look good.

### Listing a few use cases as a starting point:

- **icon**
  - 1 column width
  - always left aligned
  - 1:1 aspect ratio
  - heading + paragraph text could wrap it?
- **small image**
  - 2-3 columns (would need to test to decide)
  - always left aligned
  - 1:1 aspect ratio
  - example: profile pic
- **large image**
  - 6-8 columns (8=full width)
  - if 6 columns then center aligned
  - 16:9 aspect ratio

**Comment by kristinashu** [comment]
@taisdesouzalessa will mock-up the best case scenario of how the components should look (using content from our existing opportunity pages as use cases). Then we can see what patterns arise and how we can streamline them. 

I was looking at what we [currently have](https://docs.google.com/spreadsheets/d/1Z1oScv_5NfhGGkFg6nH-_16dKWSyPcNhrKdA5E_QwIk/edit?usp=sharing) but realize maybe we should ignore this for now and just focus on what we want!

**Comment by taisdesouzalessa** [comment]
@kristinashu @gvn I created a doc that contains links to comps and also recommendations. Some files look big in the screen because I wanted to keep the comps in their real size.

I think it is better if we keep all the comments in the doc, so they are all in a central place. Please let me know your thoughts on the recommendations and if anything seems confusing or not feasible:

https://docs.google.com/document/d/1nsu6k-MdJ1yL9myRgVg8im6Uc0wH_RwSa52Ul4yFfyo/edit?usp=sharing

**Comment by kristinashu** [comment]
Nice @taisdesouzalessa! I left a few comments. Noting the [campaign comps](https://redpen.io/p/gz26fa3bd26ec0cb81) show the new grid I'm trying to enforce! They are generally narrower than what we have now so that should help with the full width images and videos.

**Comment by taisdesouzalessa** [comment]
@kristinashu I updated the comps to reflect the new grid and addressed your feedback. Please let me know if all looks good to you then I can create an implementation ticket.

**Comment by kristinashu** [comment]
Comps look good! I've added some clarifying questions about requirements and move some text around but I think we're close. 

@gvn when you can, please take a look at the [doc](https://docs.google.com/document/d/1nsu6k-MdJ1yL9myRgVg8im6Uc0wH_RwSa52Ul4yFfyo/edit?usp=sharing) and let us know if we're missing anything.

**Comment by kristinashu** [comment]
I've cleaned up and updated the doc based on our chat. Tomorrow, Taís will mockup these components all together on one page. This will help us visualize the final results, check spacing, and make it easier to add them to our style guide. Once comps are finalized, we will open separate implementation tickets for each component.

**Comment by taisdesouzalessa** [comment]
Here are the unified comp of all those components. I added the optional caption as noted in the doc. Check it out and let me know your thoughts: https://mozilla.invisionapp.com/share/CPIAF8M4FBK#/296012268_All_Image_Components_in_1_page - I really like we could narrow down to this set, it seems versatile enough for the scenarios we encountered so far. Go team!

**Comment by kristinashu** [comment]
Woohoo this is excellent @tais! Do you think they're ready for implementation? I think so!

**Comment by taisdesouzalessa** [comment]
Cool! I'll file individual implementation tickets then. I'll create a master ticket so we can have an overview of how individual tickets are progressing. Will close this issue as soon as I have them all written.

**Comment by taisdesouzalessa** [comment]
Master Implementation ticket: #1516 - closing the issue. Feel free to reopen it if necessary.
