### ISSUE TITLE
[QA Wagtail] Global Sprint registration script 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1439]
While registration for Global Sprint is open, Zannah receives a bunch of submissions which goes into [this spreadsheet](https://docs.google.com/spreadsheets/d/1-JyApZ-AyBd9XX9vRoqX-zP_XHM-nRa-onWqhgtWcRU/edit?usp=sharing). Every few days she runs a script from the doc to generate the code below v. She would then go into Mezzanine and paste this code into the HTML editor to display the list seen on the [Registration](https://foundation.mozilla.org/opportunity/global-sprint/register/) page.

Now that there is no code editor, do you @alanmoo have any suggestions on how she could do this? They will probably close submission at the end of next week but expects there to be about 10-20 more locations to add.

`<div class="row map-sites"><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">Argentina</h4><div><a href="https://ti.to/Mozilla/global-sprint-buenos-aires18" target="_blank">Buenos Aires, Buenos Aires</a></div></div><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">Bangladesh</h4><div><a href="https://ti.to/Mozilla/global-sprint-dhaka18" target="_blank">Dhaka, Dhaka</a></div></div><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">Bolivia</h4><div><a href="https://ti.to/Mozilla/global-sprint-santacruzdelasierra18" target="_blank">Santa Cruz de la Sierra, Santa Cruz</a></div></div><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">Brazil</h4><div><a href="https://ti.to/Mozilla/global-sprint-sao-paulo18" target="_blank">São Paulo, São Paulo</a></div><div><a href="https://ti.to/Mozilla/global-sprint-Taquaritinga" target="_blank">Taquaritinga, São Paulo</a></div><div><a href="https://ti.to/Mozilla/global-sprint-maceio18 " target="_blank">Maceió, Alagoas</a></div><div><a href="https://ti.to/Mozilla/global-sprint-goiania" target="_blank">Goiânia, Goiás</a></div></div><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">Cameroon</h4><div><a href="https://ti.to/Mozilla/global-sprint-yaounde18" target="_blank">Yaounde, Center-Cameroon</a></div></div><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">Canada</h4><div><a href="https://ti.to/Mozilla/global-sprint-vancouver18" target="_blank">Vancouver, BC</a></div></div><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">Colombia</h4><div><a href="https://ti.to/Mozilla/global-sprint-medellin18" target="_blank">Medellín, Antioquia</a></div></div><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">Côte d'Ivoire</h4><div><a href="https://ti.to/Mozilla/global-sprint-abidjan" target="_blank">Abidjan, Region des lagunes</a></div></div><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">France</h4><div><a href="https://ti.to/Mozilla/global-sprint-paris18" target="_blank">Paris,  Île-de-France</a></div></div><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">Germany</h4><div><a href="https://ti.to/Mozilla/global-sprint-mannheim18" target="_blank">Mannheim, Baden-Württemberg</a></div></div><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">Ghana</h4><div><a href="https://ti.to/Mozilla/global-sprint-accra18" target="_blank">Accra, Accra</a></div></div><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">India</h4><div><a href="https://ti.to/Mozilla/global-sprint-amalapuram18" target="_blank">Amalapuram, Andhra Pradesh</a></div><div><a href="https://ti.to/Mozilla/global-sprint-Indore18" target="_blank">Indore, Madhya Pradesh</a></div><div><a href="https://ti.to/Mozilla/global-sprint-mozilla-hyderabad" target="_blank">Hyderabad, Telangana</a></div><div><a href="https://ti.to/Mozilla/global-sprint-mozilla-delhi" target="_blank">Mozilla Dehli , Delhi</a></div><div><a href="https://ti.to/Mozilla/global-sprint-mozilla-kerala18" target="_blank">Kochi, Kerala</a></div><div><a href="https://ti.to/Mozilla/global-sprint-goa18" target="_blank">Panaji, Goa</a></div><div><a href="https://ti.to/Mozilla/global-sprint-salem" target="_blank">Salem, Tamil Nadu</a></div><div><a href="https://ti.to/Mozilla/global-sprint-combinatore18" target="_blank">Coimbatore, TamilNadu</a></div></div><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">Indonesia</h4><div><a href="https://ti.to/Mozilla/global-sprint-jakarta18" target="_blank">Jakarta, DKI Jakarta</a></div></div><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">Japan</h4><div><a href="https://ti.to/Mozilla/global-sprint-yokosuka18" target="_blank">Yokosuka-shi, Kanagawa-ken</a></div></div><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">Kenya</h4><div><a href="https://ti.to/Mozilla/global-sprint-swahilipothub18" target="_blank">Mombasa, Coast</a></div></div><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">Nigeria</h4><div><a href="https://ti.to/Mozilla/global-sprint-lagos18" target="_blank">Yaba, Lagos</a></div></div><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">Pakistan</h4><div><a href="https://ti.to/Mozilla/global-sprint-Sialkot18 " target="_blank">Sialkot, Punjab</a></div></div><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">Portugal</h4><div><a href="https://ti.to/Mozilla/global-sprint-lisboa18" target="_blank">Lisboa, Lisboa</a></div></div><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">South Africa</h4><div><a href="https://ti.to/Mozilla/global-sprint-cape-town-18" target="_blank">Cape Town, Western Cape</a></div></div><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">Sri Lanka</h4><div><a href="https://ti.to/Mozilla/global-sprint-colombo18" target="_blank">Colombo, Western Province</a></div></div><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">Tunisia</h4><div><a href="https://ti.to/Mozilla/global-sprint-tunis18" target="_blank">Tunis, Tunis</a></div></div><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">USA</h4><div><a href="https://ti.to/Mozilla/global-sprint-worcester18" target="_blank">Worcester, MA</a></div><div><a href="https://ti.to/Mozilla/global-sprint-portland18" target="_blank">Portland, OR</a></div><div><a href="https://ti.to/Mozilla/global-sprint-StPaul18" target="_blank">St Paul, MN</a></div><div><a href="https://ti.to/Mozilla/global-sprint-caltech-library" target="_blank">Pasadena, CA</a></div><div><a href="https://ti.to/Mozilla/global-sprint-LosAltosHills18" target="_blank">Los Altos Hills, CA</a></div><div><a href="https://ti.to/Mozilla/global-sprint-data-science-seattle" target="_blank">Seattle, WA</a></div><div><a href="https://ti.to/Mozilla/global-sprint-trust-for-public-land-new-york18" target="_blank">New York, NY</a></div><div><a href="https://ti.to/Mozilla/global-sprint-santa-barbara18" target="_blank">Santa Barbara, CA</a></div><div><a href="https://ti.to/Mozilla/global-sprint-boston18" target="_blank">Chestnut Hill, MA</a></div><div><a href="https://ti.to/Mozilla/global-sprint-omaha18" target="_blank">Omaha, NE</a></div><div><a href="https://ti.to/Mozilla/global-sprint-michigan-state" target="_blank">East Lansing, MI</a></div><div><a href="https://ti.to/Mozilla/global-sprint-mountain-view18" target="_blank">Mountain View, CA</a></div><div><a href="https://ti.to/Mozilla/global-sprint-gainesville18" target="_blank">Gainesville, FL</a></div><div><a href="https://ti.to/Mozilla/global-sprint-template-houston18" target="_blank">Houston, TX</a></div><div><a href="https://ti.to/Mozilla/global-sprint-template-chicago18" target="_blank">Chicago, IL</a></div></div><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">United Kingdom</h4><div><a href="https://ti.to/Mozilla/global-sprint-london18" target="_blank">Southwark, London</a></div><div><a href="https://ti.to/Mozilla/global-sprint-sheffield18" target="_blank">Sheffield, South Yorkshire</a></div><div><a href="https://ti.to/Mozilla/global-sprint-manchester18" target="_blank">Manchester, Greater Manchester</a></div></div><div class="col-lg-4 col-sm-4 col-xs-6"><hr/><h4 class="h4-medium-black">Virtual</h4><div><a href="https://ti.to/Mozilla/global-sprint-virtual18" target="_blank">Virtual Participant</a></div></div></div>`

**Comment by alanmoo** [comment]
I pasted that link into a new pen on codepen.io, then copied the rendered markup and pasted it into Wagtail. I had to enter line breaks again, but if this only has to happen a few more times, it may be easiest to continue doing that/it might take us longer to figure out a long term solution than this week. (It's still something we need to figure out though)

**Comment by alanmoo** [comment]
Assigned to Gavin for visibility/consideration about future components.

**Comment by gvn** [comment]
So, this is just a bunch of headers with lists of links underneath that needs to be maintained, right?

For now it's probably easiest to hand update things in Wagtail when they change now that it's in there. I think there's a ticket regarding a multi-column list component that would probably make sense to use once it's created.

**Comment by kristinashu** [comment]
@alanmoo does your codepen suggestion show the list in 3 column? If it does then that's a great short term solution. If it doesn't then I can just add them new locations manually and @gvn can explore how to display the list in 3 columns in https://github.com/mozilla/foundation.mozilla.org/issues/1421.

**Comment by alanmoo** [comment]
No, it's still single column.

**Comment by kristinashu** [comment]
Ok, I'll close this and just do manual updates.
