### ISSUE TITLE
Some petitions can’t be signed

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#1446]
Looks like the last two Facebook petitions can’t be signed, and are displaying “Something went wrong while trying to sign the petition. Please try again later.”

Those don’t work anymore:
https://foundation.mozilla.org/campaigns/facebook-update/
https://foundation.mozilla.org/campaigns/facebook-and-european-parliament/

But I can sign this one without any issue https://foundation.mozilla.org/campaigns/facebook/

@gideonthomas @ScottDowne any idea what’s going on?

**Comment by ScottDowne** [comment]
Confirmed.

**Comment by ScottDowne** [comment]
I wonder if it's related to wagtail migration? Or related to google sheets somehow?
