### ISSUE TITLE
[Fellowships Mini Site] link to FAQ is not working

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1450]
_Assigning Alan for triage_

### Issue
We currently have 3 links in the mini site that point to the Fellowship Page FAQ. The current links point to:
https://foundation.mozilla.org/opportunity/fellowships/ - which returns a 404 page.

We should point the links to the new Wagtail page: 
https://foundation.mozilla.org/opportunity/fellowships-faq/

### Link locations:
https://foundation.mozilla.org/fellowships/ 

1. 
<img width="795" alt="image" src="https://user-images.githubusercontent.com/22157921/39154637-d7b05bf6-4703-11e8-9934-a29025deb021.png">

2. 
<img width="608" alt="image" src="https://user-images.githubusercontent.com/22157921/39154668-ef4b8e5c-4703-11e8-8fad-b969d6be75e5.png">

https://foundation.mozilla.org/fellowships/apply/
3. 
<img width="719" alt="image" src="https://user-images.githubusercontent.com/22157921/39154701-05e451c6-4704-11e8-8f4e-9e7ebfe04623.png">

**Comment by alanmoo** [comment]
Mavis, can you change this in the fellowships markup and then when it lands set up a redirect in the wagtail admin for `/opportunity/fellowships/` to go to `/fellowships`?

**Comment by alanmoo** [comment]
Fixed
