### ISSUE TITLE
Add Open Graph / Twitter Card metadata to Sprint registration page

### ISSUE THREAD

**Issue by acabunoc** [mozilla/foundation.mozilla.org#1454]
Hello hello!

Just got some feedback from @kademorton on the registration page for the Sprint:

> Just a bit of feedback around communication for the Sprint. The registration page of the website, when linked on social media, doesn't pull through any nice graphics or anything. The main overview page does, but if we want to direct social media followers straight to the registration page it looks a bit drab on Twitter/LinkedIn/Facebook.
> 
> Just a note on optimising the visual appeal of calls for contribution. The overview page pulls through fine and looks great!

I assume this is a wagtail / old cms issue. Let me know if I can help migrate things at all!

**Comment by alanmoo** [comment]
You can edit the search description and search image under the promote tag on most pages to add that content. (I added an image to the register page so it should show up now). That being said, if nothing's added for a specific page it should inherit the parent, so I'll file a ticket for that.

**Comment by acabunoc** [comment]
<img width="587" alt="screen shot 2018-04-26 at 12 30 21 pm" src="https://user-images.githubusercontent.com/617994/39318990-a84f2530-494d-11e8-8777-a580b40e3ae9.png">

Thanks!
