### ISSUE TITLE
[Fellowships Mini Site] "Applications Closed" Implementation

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1457]
### To Do list
Based on what was discussed on #1135, here is the to do list:

- [x] 1. In the Fellowships page main menu, replace label `Apply to be a Fellow` for `Get Involved`
<img width="506" alt="image" src="https://user-images.githubusercontent.com/22157921/39275948-18837a7a-489c-11e8-9a4e-95d3fe291278.png">

- [ ] 2. The change above will require an URL change (and a change in all the other places that point to this URL):  from `/fellowships/apply/` to `/fellowships/get-involved/` or whatever URL the engineers think it makes sense

- [x] 3. Change "[Fellowships page](https://foundation.mozilla.org/fellowships/)", adding a block of copy saying applications are closed. Comp [here](https://mozilla.invisionapp.com/share/BAGJFYP3CN5#/293064311_FINAL_VERSION-_Applications_CLOSED_-_V3-FellowshipsUI_-_Overviewv2)
<img width="730" alt="image" src="https://user-images.githubusercontent.com/22157921/39276109-a197256e-489c-11e8-9f3f-1bd64ad15104.png">

- [x] 4. Change "[Apply to Be a  Fellow](https://foundation.mozilla.org/fellowships/apply/)" page. Now it will be called "Get Involved". Add the block of copy saying applications are closed and remove the yellow button. Comp [here](https://mozilla.invisionapp.com/share/BAGJFYP3CN5#/293064308_FINAL_VERSION-_Applications_CLOSED_-_V3-FellowshipsUI_-_Be_A_Fellow-V2)

--------------------------

### Sketch File
[LINK HERE](https://drive.google.com/open?id=15st_Yd-GS4nAFgqqp-ci8QU1g4pWLdWr)

In the file, look for "•••Comps" page, they are labeled as "applications closed options"
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/22157921/39276429-c96df846-489d-11e8-9123-0f64c54a2dd9.png">

**Comment by alanmoo** [comment]
Mavis will hopefully get to this later this week.

**Comment by mmmavis** [comment]
@taisdesouzalessa @community-impact what do we want users to see when they visit `/fellowships/apply/`? 404? redirect to `/fellowships/get-involved/`? or?

**Comment by community-impact** [comment]
I'd suggest redirecting to fellowships/get-involved

**Comment by alanmoo** [comment]
Will this be a permanent change or are you looking to change this back and forth? I'd recommend sticking with one.

**Comment by community-impact** [comment]
At most we'd think about switching it back when applications open again,
but I also think it could be entirely appropriate to leave it as
/get-involved

**Comment by taisdesouzalessa** [comment]
UPDATE:Button "Get More Info" takes users to this form once clicked: https://docs.google.com/forms/d/e/1FAIpQLSdTUqJ9Z4xdcVr4IMzd9UESqm7XwcpVdrIXDeeFNIHUc_vhvQ/viewform - @mmmavis

**Comment by mmmavis** [comment]
Cool I'd vote for just using `/get-involved` from now on. If that sounds good I'll redirect `/fellowships/apply` to `/fellowships/get-involved`

**Comment by community-impact** [comment]
Sounds good

**Comment by mmmavis** [comment]
Updates are live https://foundation.mozilla.org/fellowships 🎉 

and https://foundation.mozilla.org/fellowships/apply now gets redirected to https://foundation.mozilla.org/fellowships/get-involved/
