### ISSUE TITLE
Improve UI on campaign pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1459]
Based on - Improve UX on campaign pages #1366 

Updates based on feedback in this [deck](https://docs.google.com/presentation/d/146UzqSH6q2YE426gMZbQ86pupYKoAfNACmc7tBgmAk0/edit?usp=sharing). 

Also prioritizing and estimating on which features/modules to build first.

**Comment by beccaklam** [comment]
Looks good to me @kristinashu !

**Comment by taisdesouzalessa** [comment]
Looks great! I really like the persistent take action button on mobile <3.

**Comment by kristinashu** [comment]
Thanks you two! 

Yeah the persistent take action button was from Becca's UX work!
