### ISSUE TITLE
Discuss enhancements to Pulse component on Wagtail

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1460]
Currently, wagtail allows us to pull projects from Pulse to site pages with a search query. Let's discuss refinements and enhancements. @gvn @kristinashu @mmmavis For example, we could add option to filter by one or more issues. Also, we'd like to enable authors to pull People (such as mozfest speakers).

<img width="824" alt="image" src="https://user-images.githubusercontent.com/53411/39321103-0abafd06-4954-11e8-8294-308bb45b5089.png">

cc @gideonthomas @alanmoo

**Comment by xmatthewx** [comment]
Currently, it allows for "no maximum" in number of results. That seems dangerous. Is it still limited by API? Paginated? I'd cap it at 48 and maybe insert a button to "more" if the limit is reached. 

People
 - 5 issues
 - program type / year
 - latest?? 
 - location (not truly useful until we advance that field)
 - language (does not exist yet)
 - help offered (field doesn't exist yet, but will be awesome)

Projects
 - search (as built)
 - tags (one or more)
 - issues
 - help categories

Anything missing?

**Comment by gvn** [comment]
We probably shouldn't require search terms. Currently the homepage is searching with an empty query to show all the featured projects. This is only working because it's not a Wagtail-created instance of the component.

**Comment by gvn** [comment]
We can sort what we get back by date, but I'm not sure if we can fetch in particular date ranges.

Also, the max is now completely up to the user but if it isn't set it defaults to 48. I definitely think we should add pagination to the component. I'm happy to work on that if you want to file it.

**Comment by gvn** [comment]
Let's create implementation tickets for each component with requirements inside. I think both will require design as well.

**Comment by alanmoo** [comment]
Based on the features Matthew is requesting, @gvn why don't you create the tickets with proposed technical changes that would best meet the needs? Put in the things that are most reasonable to do (lowest effort/biggest reward) so that we can continue the conversation from there. Designers need more information on what's possible so that we can move forward on this in a sensible way.

**Comment by gvn** [comment]
Honestly that seems a little backward to me. Most things are technically possible. I'd like to see what Design would like to do even if it's just wireframes and then I can always give feedback on that. @xmatthewx does that sound reasonable?

**Comment by xmatthewx** [comment]
For Projects, I don't think need to change anything on the frontend. So, we'll just need to mock-up admin for the component, which should be quick and easy based on the list above. Let's start there. After we land that, we can move onto a People component.

**Comment by gvn** [comment]
We should really add pagination to the projects component though, right? Can we have a designer comp that?

**Comment by gideonthomas** [comment]
+1 to adding pagination. Chatting with Abby, it's a pretty core requirement to events such as the global sprint. I don't think there are any performance considerations if we're paginating the entries.

**Comment by taisdesouzalessa** [comment]
Here is the comp for the Projects component. 
I have a question related to tags, help needed and issues: will we display them in the front end as well? 
If we are showing them in the front end we may consider limit the number of tags? Otherwise it can become very long! See example here (scroll to the side to see the front-end view)

https://redpen.io/gxfb04f53533453cdd

**Comment by taisdesouzalessa** [comment]
@xmatthewx for the People component, we currently don't display `year` on the Pulse profile. However, we do that for Fellows. We display different things for people depending on the context (if Fellows, Pulse or People Page). I made a of things we display for each scenario:
https://redpen.io/gyc6c2712cd59f290e

Here is in a [spreadsheet format](https://docs.google.com/spreadsheets/d/1HAlPqVV8y_oQ7b8YXLhQiSZoVCeFrInG_-a00NQXnwQ/edit?usp=sharing)

I feel we should define what we want to display first so I can mockup the CMS component, does that make sense? Maybe I should open a new ticket just for this discussion?

**Comment by taisdesouzalessa** [comment]
Tickets are here: 

1.     implement project component admin  #1542
2.     discuss people card frontend #1543
3.     plan people component admin #1544

Closing this ticket.
