### ISSUE TITLE
[QA] Make sub nav styling consistent 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1465]
Note that main nav is good at Nunito 700, 16px.

### Sub Nav on Primary pages:
- Horizontal nav = sub menu items + gradient divider (select and hover state is yellow underline)
- [Fellowships main page](https://foundation.mozilla.org/fellowships/) is good at Nunito 700, 16px
- [x] Add gradient divider to all fellowships sub pages (directory, support, apply)
- [x] Update all the [About pages](https://foundation.mozilla.org/about/) to match sub nav on fellowships page

### Sub Nav on [Opportunity](https://foundation.mozilla.org/opportunity/global-sprint/) pages:
- Vertical = sub nav items (select and hover state is yellow underline)
- [x] please update from Nunito 700, 20px to 17px, increase line height to 1.6

**Comment by mmmavis** [comment]
@kristinashu 

> please update from Nunito 700, 20px to 17px, increase line height to 1.6

Is this for both mobile and desktop?

**Comment by kristinashu** [comment]
> please update from Nunito 700, 20px to 17px, increase line height to 1.6

I was only thinking desktop but yes, please do for both mobile and desktop! 

> should we use 16px so it's the same as the horizontal secondary nav?

No, unfortunately the text in the vertical nav needs to be a little bigger than horizontal. It gets a little lost on the side if the text is too small.

**Comment by mmmavis** [comment]
@kristinashu 

> I was only thinking desktop but yes, please do for both mobile and desktop!

Ah I just realized on mobile the vertical side nav changes to a collapsible dropdown which the desktop horizontal secondary nav also uses (design-wise). I'm gonna stick with whatever stylings we already have but when you review my PR feel free to suggestion any changes if needed.

**Comment by kristinashu** [comment]
Yeah, don't worry about the drop down right now.

**Comment by kristinashu** [comment]
This is done and it looks great!
