### ISSUE TITLE
[Wagtail QA] Figure Grid 2 isn't displaying images

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1469]
New Figure Grid component is doing something cra cra.

Content in staging CMS looks good:
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/1068783/39376800-c7c2ddfc-4a07-11e8-8709-dd147221a85e.png">

But images aren't showing up on [staging](https://foundation.mofostaging.net/opportunity/global-sprint/). Instead we see the image name as a link?

<img width="873" alt="image" src="https://user-images.githubusercontent.com/1068783/39376808-cf9a62f2-4a07-11e8-8218-9c4b7d5f76aa.png">

Note that the image name is what is showing up:

<img width="831" alt="image" src="https://user-images.githubusercontent.com/1068783/39376924-3673e9f8-4a08-11e8-9c0c-13f9809c9e79.png">

https://foundation.mofostaging.net/opportunity/global-sprint/

**Comment by gvn** [comment]
You're seeing alt text for a broken image tag wrapped in a link. Basically the problem is that the source of the image is a broken URL. I'm not sure why that would be the case though...seems like a Wagtail config thing?

**Comment by gvn** [comment]
Are these newly added images or pre-existing? Not sure why/if that would make a difference, but curious anyway...

**Comment by kristinashu** [comment]
Heyo! I think you just solved it. They were old images but I just reloaded one of them and it worked!

**Comment by kristinashu** [comment]
So FigureGrid2 is looking good! But not sure if the missing image thing is part of a bigger issue? Where did the images go?? Should there be some sort of warning that there is a missing image???

**Comment by alanmoo** [comment]
Sorry, in what case are images missing?

**Comment by kristinashu** [comment]
Images that were uploaded a while ago appear to be broken.

This might be related to https://github.com/mozilla/foundation.mozilla.org/issues/1470

If it's just a staging issue then we can close these but just want to make sure.

**Comment by alanmoo** [comment]
I'm not completely following- the images were uploaded previously, but when pulling them into FigureGrid2 they only work if they're re-uploaded?

**Comment by kristinashu** [comment]
Yes. 

Not a big deal if it's just this one instance on staging but I just want to make sure it isn't a systemic issue and we loose all our images when we push to prod. Probably won't happen, but just wanted to flag.

**Comment by alanmoo** [comment]
This was just an issue with staging
