### ISSUE TITLE
[Home page QA] Hero image is missing at narrow widths

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1470]
Hero image disappears at narrow width on staging but is good on prod.

<img width="332" alt="image" src="https://user-images.githubusercontent.com/1068783/39377934-bd7211ca-4a0b-11e8-9145-0d2ee97d219b.png">

**Comment by ScottDowne** [comment]
Havn't figured this out yet, but it does look like the url to the image seems to be "https://assets.mofostaging.net/network/not-found" which def wouldn't work.

**Comment by ScottDowne** [comment]
Looks like it's a simple matter of that image not existing on staging maybe?

**Comment by alanmoo** [comment]
Seems like it's related to us using two different ways of calling the image- see the first and last lines [here](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templates/wagtailpages/homepage.html#L16-L24)

@gvn Can't we use one of the bootstrap push/pull classes to simplify this so we don't have to load the image twice? And then while we're at it, only use the python image tag for the one that works?

**Comment by kristinashu** [comment]
This ticket is resolved but should we open a new ticket for the comment above? https://github.com/mozilla/foundation.mozilla.org/issues/1470#issuecomment-385493664

**Comment by alanmoo** [comment]
Good call. Filed #1482.
