### ISSUE TITLE
[Components] Spacings Implementation ticket

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1474]
Based on discussion on #1404, here is the implementation ticket.

- [x] Add margin top and bottom of 16px by default on all components (expected behavior is to have a margin collapse as per [Gavin's comment](https://github.com/mozilla/foundation.mozilla.org/issues/1404#issuecomment-383751450)). Here is a [list of the components](https://docs.google.com/document/d/1zpw8Kn9NQEkUCAlzeh_VIvUFXEKdWRc8oskoVrd0a1Y/edit?usp=sharing) that need to be updated  (I don't have full knowledge of the items that are also components, so please correct me if something seems off/is missing there @gvn) 

- [x] Keep the line break available to users <img width="30" alt="image" src="https://user-images.githubusercontent.com/22157921/39158149-3e0ccb50-4713-11e8-9648-1a69e0acf032.png"> 

- [x] "Healthy Internet" component should have a bigger margin-top. Margin bottom is 8px+48px so margin-top should be the same (8px+48px)
<img width="581" alt="image" src="https://user-images.githubusercontent.com/22157921/39388940-b55398e2-4a38-11e8-9723-927ea878f399.png">

cc: @kristinashu @xmatthewx @gvn let me know if this makes sense to you. Assigning this task to Gavin

**Comment by gvn** [comment]
I think we should also change the "Spacer" component to be optionless and just be 16px tall.

@taisdesouzalessa @kristinashu thoughts?

**Comment by taisdesouzalessa** [comment]
I think the "Spacer" component can be useful because there are scenarios (like "Example B" [here](https://mozilla.invisionapp.com/share/H4HRH4BKMQW#/293086382_Desktop)) in which the layout would benefit if different blocks of text have more spacing between them instead of the constant 16px.

That being said, I do think our spacer has an overwhelming amount of options (@sabrinang and I talked about it in the past and we have some opinions about it - feel free to add your comments here, Sabrina):
<img width="973" alt="image" src="https://user-images.githubusercontent.com/22157921/39443154-8d9ec632-4c68-11e8-986c-b422b335d213.png">

Maybe just 3 would be enough? And named: **small** (equivalent to my-2 which is equal to 8px)/**medium** (equivalent to my-4 which is equal 24px)  / **large** (equivalent to my-5 which is equal 48px)

I even wonder if the "medium" is necessary since it is so close to 16px...what do you think?

**Comment by gvn** [comment]
Keep in mind if it's fixed you could still add multiple spacers in a row...

**Comment by taisdesouzalessa** [comment]
The only scenario I thought that a 8px vertical space would be useful was for captions - but I think we can make this standard for this type of component (so users don't have a choice?). If spacing is built in the component then 8px isolated spacing may not be necessary...
<img width="608" alt="image" src="https://user-images.githubusercontent.com/22157921/39449340-9efc7aaa-4c7c-11e8-8236-3593f6940ed0.png">

@gvn for the scenario you pointed out `adding multiple spacers in a row` you meant something like that (imagine there is no dropdown menu, so if I want a spacing of 32px, I would have to stack 2 spaces of the default 16px):
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/22157921/39449645-7510324e-4c7d-11e8-8064-8f895bc2685e.png">

**Comment by gvn** [comment]
>The only scenario I thought that a 8px vertical space would be useful was for captions - but I think we can make this standard for this type of component (so users don't have a choice?). If spacing is built in the component then 8px isolated spacing may not be necessary...

Those caption margins are built into the component itself so will remain the same.

>@gvn for the scenario you pointed out adding multiple spacers in a row you meant something like that (imagine there is no dropdown menu, so if I want a spacing of 32px, I would have to stack 2 spaces of the default 16px):

Yes. :)

**Comment by kristinashu** [comment]
Excellent, sounds like we can just have the one spacer size!

**Comment by taisdesouzalessa** [comment]
Yep, I think we can give this a try and see how staff build their pages. We can always increase complexity if the need arises but I am cool with starting simple first!

**Comment by taisdesouzalessa** [comment]
Made an audit of the implemented spacings. There are still a few issues to solve: https://redpen.io/ye8382707324177761

The 3 of us should chat to see what's worth it to solve and what's not :) - @gvn @kristinashu
