### ISSUE TITLE
[Wagtail] Narrow grid width when no side nav or petition form by default

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1476]
CMS pages have a "Narrowed page content" checkbox. 

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/1068783/39449431-dc97e0e8-4c7c-11e8-844b-118575e7338f.png">

Problem is that users won't know when to check or uncheck this box. User generated pages should always be narrow when there is no side nav or side petition. And should be otherwise always be full-width. 

All our Opportunity/Campaign pages without nav or petition should be narrow:
- https://foundation.mozilla.org/opportunity/leadership-training/
- https://foundation.mozilla.org/opportunity/network-50/
- https://foundation.mozilla.org/opportunity/fellowships-faq/
- https://foundation.mozilla.org/opportunity/fellowships-research/
- we don't have any Campaign pages like this yet, but we will

All our Primary pages that are CMS generated should be narrow:
- https://foundation.mozilla.org/about/
- https://foundation.mozilla.org/about/leadership/ 
- https://foundation.mozilla.org/about/public-records/
- https://foundation.mozilla.org/about/trademarks/

**Comment by kristinashu** [comment]
cc @Pomax (and @ScottDowne)

This https://github.com/mozilla/foundation.mozilla.org/pull/1568 was a short term fix to make sure petition pages look good regardless if "make narrow" check box is selected or not. 

This ticket is a more long term solution to put the onus on the template rather than the user to determine the page width.

**Comment by kristinashu** [comment]
From #1405 

https://redpen.io/gnce740629099e94c7

![template 2x](https://user-images.githubusercontent.com/1068783/40739611-835da756-63fb-11e8-92d8-4d0115740623.jpg)

**Comment by Pomax** [comment]
this got implemented quite a while back.
