### ISSUE TITLE
[Wagtail Component] Figure Grid on About Us Leadership page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1479]
Now that we have lovely FigureGrid2 that fits the bootstrap grid nicely. 

The [Leadership page ](https://foundation.mozilla.org/about/leadership/)currently uses the the original Figure Grid but we should update this so it too will fit the bootstrap grid.

The twist: all images need to be the same size (as in, an images that are 3 images across needs to be the same dimensions as the 4 across). 

I think @gvn mentioned this page would be a custom exception? It is a primary page after all!

**Comment by gvn** [comment]
@alanmoo had a good idea here since it's the only exception to the default layout: just upload a white image for the 4th spot in the grid. That way you'll see the same width for the 3 images as the 4+ layouts.

**Comment by kristinashu** [comment]
Really, so on mobile it will have a big white gap?

**Comment by gvn** [comment]
Unfortunately, yes it would. We didn't consider that case.

**Comment by kristinashu** [comment]
Maybe it is ok if some of the image are bigger?!? I'm ok to try that and see if anyone complains...

**Comment by gvn** [comment]
Yeah, can we try it as-is with FigureGrid2 and see if it's an issue?

**Comment by kristinashu** [comment]
kk
