### ISSUE TITLE
[Wagtail QA] Can't add News Glyphs in CMS

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1482]
News items on the [home page](https://foundation.mozilla.org/) should show the news sources logo as a Glyphs:
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/1068783/39497680-5229f116-4d59-11e8-8393-aa5d7a3ca394.png">

But I can't add them in the Wagtail admin:
<img width="916" alt="image" src="https://user-images.githubusercontent.com/1068783/39497723-78a03d3c-4d59-11e8-9985-a10e28d59012.png">

@alanmoo is this a permissions thing or something else?

**Comment by alanmoo** [comment]
Doesn't seem to be permissions related, I can't see it either.

**Comment by alanmoo** [comment]
Seems like it's a bug with that field that the production system is handling so it doesn't completely fall over, but needs some attention. Might have to wait till Pomax is back though.

(Unless @gideonthomas you have any quick idea why https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/news/models.py#L73 might be broken)

**Comment by gideonthomas** [comment]
Is `FileBrowseField` still a thing? I thought that was meant for mezzanine and wagtail has its own field for that

**Comment by alanmoo** [comment]
That sounds right, it's probably something we need to rip out and replace still.

**Comment by kristinashu** [comment]
@Pomax just giving this one a nudge...

**Comment by alanmoo** [comment]
Glyphs were removed completely at some point because they were problematic. Let's file another ticket if we want them back (though as I recall they were hard to manage too...)
