### ISSUE TITLE
[Home Page QA] Reduce image requests required on homepage

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1485]
Right now the homepage has 2 image requests for the hero image- one for mobile and one for desktop. Let's consolidate those and use proper [responsive techniques](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images) so there's only one request.

**Comment by youriwims** [comment]
This was fixed in #2425 and is being optimized in #2632.
