### ISSUE TITLE
[Wagtail Component] Remove old Figure Grid component

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1486]
Figure Grid 2 was add in https://github.com/mozilla/foundation.mozilla.org/issues/1407

I have replaced the old Figure Grid with the new one (yay so much better!):
http://foundation.mozilla.org/opportunity/global-sprint/
https://foundation.mozilla.org/about/leadership/

I believe these are the only instances of it but @alanmoo will install a plugin to check https://github.com/mozilla/foundation.mozilla.org/issues/1445

Once confirmed, please remove the old Figure Grid component.

**Comment by kristinashu** [comment]
@gvn as discussed as stand, you can probably remove the old Figure Grid as an option

**Comment by gvn** [comment]
I did a local test to see what happens when components are removed from `models.py` and existing instances of them just disappear. So, we need to make super extra double sure that no instances remain before we fully deprecate.

I have seen some instances of what look like the Figure component on prod FWIW.

@alanmoo any traction on the plugin?

**Comment by kristinashu** [comment]
I still see it under deprecated. It think it should be completely removed.

<img width="715" alt="image" src="https://user-images.githubusercontent.com/1068783/51873314-90119b80-2311-11e9-8c4d-7d9440032511.png">

**Comment by Pomax** [comment]
Ah, well-spotted. Interestingly, unless I'm even blinder, I don't see it listed as possible filter on our ["block inventory" page](https://foundation.mozilla.org/cms/inventory/). I don't know if that means there's something wrong with the block inventory, or whether it means there are zero pages that use it and so it's not even offering the option to filter based on it.

**Comment by alanmoo** [comment]
I believe it means it's not in use- I added it to a (private) page temporarily, and it was suddenly an option in the inventory list.

**Comment by Pomax** [comment]
thanks, I think that means we should be able to impactlessly remove it.
