### ISSUE TITLE
Remove Facebook from footer

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1508]
Mozilla is no longer active on Facebook b/c of recent events. We should remove the Facebook icon and link from the footer of our active properties. I don't think we need to stop using share on facebook buttons, people can make that choice for themselves. 

cc @alanmoo to triage
cc @kristinashu for any design considerations that pop up

Footers:
 - [x] foundation site
 - [ ] pulse
 - [ ] donate
 - [ ] mozfest

Anywhere else critical?

**Comment by alanmoo** [comment]
@mmmavis This might be a good "when you have a few minutes" ticket. Maybe just comment it out so that if we do come back it's easy to revert?

**Comment by mmmavis** [comment]
@alanmoo yea i can take this on if we do wanna remove facebook link/icon from our site footer.

**Comment by alanmoo** [comment]
Yeah do it. Just confirmed with Matthew.

**Comment by mmmavis** [comment]
It seems like Foundation site is the only site out of the 4 listed that shows Facebook on the site footer. I've filed a PR to remove it.
