### ISSUE TITLE
`inv runserver` gobbles console output on windows

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#1529]
Running `inv runserver` starts up the server, but gobbles the console output on windows (using cmd). The console output does not actually show until you ctrl-c the `inv` process, at which point _all_ the console output shows up =)

Invoking `runserver:
![image](https://user-images.githubusercontent.com/177243/40085679-28e4b3d4-5850-11e8-9517-e9178c8fa857.png)

After hitting ctrl-c:
![image](https://user-images.githubusercontent.com/177243/40085687-3112f9ee-5850-11e8-9727-63eba579a816.png)

**Comment by patjouk** [comment]
It's not only linked to windows: same issue on my Mac too and already working on it.

**Comment by patjouk** [comment]
For some reason, it works with pipenv 11.10.0, even on Windows, but it's probably a weird coincidence. [Invoke FAQ](http://www.pyinvoke.org/faq.html#calling-python-or-python-scripts-prints-all-the-output-at-the-end-of-the-run) gives more details on what is happening and what to do to fix it. The solution would be to use `pty=True`, which fix the issue for Linux and MacOS, but not Windows. The long-term solution would be to rewrite the tasks.py, but I don't have time for that this week and will do it the next one.
