### ISSUE TITLE
Make document uploads work

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1533]
It seems like you can upload documents through the admin and it recognizes them as having been uploaded, but it seems like they're not actually findable later on. Let's make it so we can upload a PDF and link to it.

**Comment by kristinashu** [comment]
This is what I see when I try to upload a pdf in the image up-loader:

<img width="1264" alt="screen shot 2018-05-22 at 2 26 16 pm" src="https://user-images.githubusercontent.com/1068783/40391123-29cad28e-5dcc-11e8-94fd-582b205cadbc.png">

Once this is fix, please ping me and I will upload this [PDF](https://drive.google.com/file/d/1Bl-h9d1IrhBXOskacm8eYkPteNMdxlN2/view) and replace the Strategy link on About page.

**Comment by kristinashu** [comment]
Nvm, it was a permissions things. I think this is fixed.
