### ISSUE TITLE
Redesign Donate page UI

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1534]
Re-skin https://donate.mozilla.org/en-US/ to look more like foundation site.

- Now that we have a prominent link to the donate page from the foundation site we need to align the two so the experience is less jarring and more coherent
- Add link on donate page to link to the foundation site
- Out of scope: we do not want to introduce new elements (we can start to test different images, copy and styles after this basic re-skin is done)

### Steps:
- [x] initial desktop design
- [x] feedback at design crit tomorrow
- [x] share with Will for feedback
- [x] design hover and active states
- [x] design mobile and tablet view
- [ ] check for post sign screens (confirmation, email signup, share) ("no thanks" link in email signup) https://github.com/mozilla/donate.mozilla.org/issues/1998
- [x] continue to discuss implementation (html vs css in Traffic Cop)
- [x] discuss how we should A/B
- [ ] write/design tests

**Comment by kristinashu** [comment]
It's been tricky to just _re-skin_ this page but I've tried to refrain myself! Here's the WIP https://redpen.io/p/thbfb2535f83162d2d

cc @sabrinang @taisdesouzalessa @natalieworth @beccaklam @xmatthewx @ScottDowne @alanmoo for feedback

**Comment by alanmoo** [comment]
@ScottDowne Do you think this is something that could happen with just CSS changes that we load using Traffic Cop?

@xmatthewx I think this might be a great project for usertesting.com. You?

**Comment by alanmoo** [comment]
It would effectively need to swap out the HTML after the page loads, correct?

**Comment by kristinashu** [comment]
Thank you everyone for the feedback! I've updated the comps with v5. I like this version because it's actually quiet similar to our current donate page, just a little slicker. 

#### Next steps
- feedback at design crit tomorrow
- share with Will for feedback
- design hover and active states
- design mobile and tablet view
- continue to discuss implementation 
- write/design possible A/B tests

#### Comp

![donate 2x](https://user-images.githubusercontent.com/1068783/40746744-1395f31e-6410-11e8-8591-572d88665c8d.jpg)

**Comment by WesleyBranton** [comment]
I do like the latest design change proposal, but I added a few suggestions to the RedPen page.

**Comment by kristinashu** [comment]
Excellent, thanks @WesleyBranton!

**Comment by kristinashu** [comment]
Follow up tickets:
- Implement modern reskin https://github.com/mozilla/donate.mozilla.org/issues/2008
- [Donate] Re-skin post donate screens https://github.com/mozilla/donate.mozilla.org/issues/2009
- [Donate] Explore other designs to test https://github.com/mozilla/donate.mozilla.org/issues/2010
