### ISSUE TITLE
Switch to plain S3boto3

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#1536]
We used a custom wrapper around s3boto3 to make thumbnails work with Mezzanine, but since we're ripping out mezzanine, we should be able to revert to plain s3boto3 as per https://wagtail.io/blog/amazon-s3-for-media-files/ and not have that additional step to have to worry about anymore.

**Comment by alanmoo** [comment]
Is this still relevant?

**Comment by Pomax** [comment]
nope
