### ISSUE TITLE
[Pulse component on Wagtail] Implement project component admin

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1542]
Based on discussion started here: #1460

After getting feedback from Matthew and Kristina, here is the new version of the component:

https://redpen.io/fwa962f8cef5bb1388 

[Clickable Prototype here](https://taisdesouzalessa.github.io/cms-pulse-projects-prototype/index.html) (click on the filter arrow to expand its view).

2 things:
1. I propose we change the default number for the "Max. number of results box". If the default is 48, I think this is the number that should be displayed. "0" is confusing
<img width="599" alt="image" src="https://user-images.githubusercontent.com/22157921/40207592-233fdd32-59ea-11e8-8116-3dffe9948e61.png">
2. If staff chooses tags or issues or "Help needed" boxes, we could display them, as in Pulse. Please notice that "Help Needed" has its own section of tags (B) so there is a clear distinction between those and the other tags, like we have on Pulse:
<img width="599" alt="image" src="https://user-images.githubusercontent.com/22157921/40207735-ebe0f618-59ea-11e8-964e-54a7d1c9bfa1.png">
I am not sure if we should show:

a) all the tags (it has potential to be super busy)

b) only the selected tags (pro: it is clear to users the filter applied - for instance - those projects need help on coding or those projects are related to decentralization / con: it can be repetitive) 

c) no tags (pro: interface is cleaner / con: staff may be confused if their filter was applied AND staff has to make sure to write on the copy why those specific projects were displayed since there is no indication on design what's tying the projects together)

Any thought on that @xmatthewx @kristinashu ?

**Comment by taisdesouzalessa** [comment]
Design updated as per @xmatthewx's comments on RedPen:
[Prototype](https://taisdesouzalessa.github.io/cms-pulse-projects-prototype/index.html)
[RedPen (v3)](https://redpen.io/po1dac786f32dfef25)

IMPORTANT: the front-end view was removed form the scope of this project. So it will stay as currently is.

**Comment by xmatthewx** [comment]
Great. Let's file a new clean ticket for implementation or delete the frontend stuff from this thread. 

Let's make a checklist of requirements for implementation, and include "admin should default to sort by latest"

**Comment by taisdesouzalessa** [comment]
Implementation ticket here:  #1559. Closing this issue.
