### ISSUE TITLE
[Pulse component on Wagtail] Plan people component admin

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1544]
Discussion started here: #1460

**Dependent on #1543.**

Once we decide which features we want displayed, we have to plan how the admin interface will look like.

**Comment by xmatthewx** [comment]
@taisdesouzalessa - now that the project component is nearly done, let's start thinking about the people component when you have some bandwidth.

**Comment by xmatthewx** [comment]
I think we can thinking about admin query without worrying about the frontend card.

**Comment by taisdesouzalessa** [comment]
I need to visualize what we expect from the frontend card so I know which fields to ask for in the CMS. 
Here are the minimal requiremens for this component, based on conversation from #1460:

1.	Name
2.	5 issues (checkboxes)
3.	program type (text input)
4.	year (text input)
5.	Picture
6.	sort by latest by default (checkbox to reverse) - _CMS view only_
7.	number results (number input)  - _CMS view only_

I imagine that in the frontend the card will look like the existing model we already have, correct me if I am wrong: 
<img width="594" alt="image" src="https://user-images.githubusercontent.com/22157921/42719100-7eecae00-86c5-11e8-9025-38a8c7495df1.png">

The data will come from what we have available on Pulse, correct? If so, numbers 1, 2 and 5 seem straightforward since we have those fields on Pulse. I am not sure on numbers 3 and 4, though.

Here is a diagram that shows the correlation between the card and the info we have in Pulse:
<img width="966" alt="image" src="https://user-images.githubusercontent.com/22157921/42719153-49031f12-86c6-11e8-8ad5-e840fef97a3b.png">
[Full chart on Redpen](https://redpen.io/ynd05237e83b3f9f29) for comments

**Comment by xmatthewx** [comment]
This is all great, but just so you know ... the admin component just needs to identify which people to grab, it won't affect which fields we can show/hide on frontend. It will just give the frontend a list of profile IDs, the frontend can then decide independently what to do with that list.

**Comment by alanmoo** [comment]
It's more a UX question- What groups of people are going to be displayed using this component? Do they have common properties in their profiles? Will we need to be able to hand-pick certain profiles, or do we work around that by being more flexible about the types of Profile types and Program types we create?

Once we've answered those questions, we can decide which query params to allow Wagtail page creators to use. (Possible query params are at the top of [this page](https://api.mozillapulse.org/api/pulse/profiles/?profile_type=fellow)

**Comment by taisdesouzalessa** [comment]
Thanks for the explanation, @alanmoo :). 
I also chatted with Matthew so now I am ready to work on the next steps for this component. I'll update it here once I have the final version.

**Comment by taisdesouzalessa** [comment]
Here are the proposals:
### 1. Profile by ID Component
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/22157921/43280800-c2978b7e-90c6-11e8-8cef-30241ca4e8ae.png">

[RedPen here](https://redpen.io/dc9f2dff1c286e5c0d)

**Name of the component:** "Profile by ID"
**Icon in the CMS:** I am not sure if we can use our own icons or if we have a library to choose from. Please let me know @alanmoo so I can prepare the icon if customization is allowed. 
**Rough idea for icon (modified from Font Awesome):** 
<img width="36" alt="image" src="https://user-images.githubusercontent.com/22157921/43281178-ddbd647c-90c7-11e8-915a-4a405d0f84f6.png">
 


### 2. Latest Profiles Component
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/22157921/43280879-f411ee2e-90c6-11e8-9da1-068db57f90c4.png">

[RedPen here](https://redpen.io/bsb834f94cafe4b895)

**Name of the component:** "Latest Profiles"
**Icon in the CMS:** I am not sure if we can use our own icons or if we have a library to choose from. 
**Rough idea for icon (Font Awesome):** 
<img width="34" alt="image" src="https://user-images.githubusercontent.com/22157921/43281333-44080af2-90c8-11e8-9fc6-bbb253c1e8d8.png">

@xmatthewx and Alan: let me know who will build this component so we can review it with the responsible Engineer and I can create the implementation ticket.

**Comment by xmatthewx** [comment]
Perfect. Thanks @taisdesouzalessa!

**Comment by xmatthewx** [comment]
I'm intrigued by the idea of doing a review on vidyo to build the implementation ticket and checklist of requirements.

**Comment by taisdesouzalessa** [comment]
Yep, I can schedule a meeting. Let me know who you would you like to be in the meeting and I will send an invite.

**Comment by taisdesouzalessa** [comment]
Closing this ticket. Implementation ticket is here: #1719.
