### ISSUE TITLE
Non-deprecated components showing in deprecated group

### ISSUE THREAD

**Issue by gvn** [mozilla/foundation.mozilla.org#1549]
Repro:

- Create a new page
- Add a component (note that `Figuregrid` is "Deprecated")
- Add another component (note that now lots of other components are now in the "Deprecated" group)

Expected:

- Only `Figuregrid` should show up as "Deprecated"

**Comment by alanmoo** [comment]
I'm seeing "Image text" and "Figure" as deprecated currently. Is that correct or should they not be deprecated?
