### ISSUE TITLE
[Wagtail: vertical spacing] Misalignment between image and text in Image Text component

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1551]
### Issue
Currently, the images in the `Image Text` component have a default margin top and bottom of 16px, which causes a misalignment between the image and the text beside it.

<img width="719" alt="image" src="https://user-images.githubusercontent.com/22157921/40390777-2831d7ca-5dcb-11e8-991c-a157be17a48a.png">

**Comment by alanmoo** [comment]
Tell me if I'm understanding this correctly: Images within this component need no margin top/bottom? This should be pretty straightforward, if so.

**Comment by Pomax** [comment]
@kristinashu would you happen to know if this is still the case?

**Comment by kristinashu** [comment]
Yes that is correct but might change based on https://redpen.io/tuab5adf37d05d0414. Let's hold off for now.

**Comment by youriwims** [comment]
Closing this ticket since the new `Image Text` component should have fixed any vertical alignment issues. See #2693 , #2732 & #2783.
