### ISSUE TITLE
[Wagtail: vertical spacing] Spacing between components = 32px

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1552]
### Issue
For our `h1 - h6` components and `p` we should keep the margin as is (16px) because this is the standard being used in the Foundation site pages. However, when we stack components on top of each other (for instance, an iframe, a button and a figure grid), it would be nice if the default spacing was 32px (16 of one element + 16 of the other), so the components don't get too close to each other.

<img width="791" alt="image" src="https://user-images.githubusercontent.com/22157921/40391292-98221580-5dcc-11e8-8e73-4ff613fd72c0.png">

**Comment by kristinashu** [comment]
We've made a lot of improvements to the components lately so I'm not sure this is still an issue. Going to close and we can open a new ticket if it's still needed.
