### ISSUE TITLE
[Wagtail: vertical spacing] Big gap on the bottom of pages

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1553]
### Issue
Currently, our main content container has the class `py-5`, which adds a padding bottom of 48px to the main container.  

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/22157921/40391841-7d4b766e-5dce-11e8-8db7-76eeba7c0fbb.png">

This padding, combined with the one from the next element of the page (in this example, the email sign up box), creates a big gap between elements:

<img width="678" alt="image" src="https://user-images.githubusercontent.com/22157921/40391940-dbaf6bca-5dce-11e8-8a70-e93297be9eeb.png">

@gvn I am not sure about how to solve this one...I think you may have some ideas. I am afraid that removing the margin-bottom from this py-5 may makes the whole block of the content too close to the footer in instances in which we don't have an email sign up of a "This is part of a broader movement..." component.

**Comment by kristinashu** [comment]
I don't really notice this gap anywhere? Will close for now.
