### ISSUE TITLE
Determine whether we can serve specific mime-types for wagtail documents

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#1554]
wagtail documents don't seem to do proper mime-types, so a pdf file becomes a download instead of a preview.

**Comment by Pomax** [comment]
based on https://stackoverflow.com/questions/50494170/getting-wagtail-to-use-correct-mime-types-for-documents it appears this is not possible out of the box, so we may need to see if we can write some code that does know how to do this, or not use Documents

/cc @kristinashu @alanmoo

**Comment by kristinashu** [comment]
Is there an alternative to Google drive we could use? Something opensource or that better aligns with our values that could host and preview our docs?

I don't think we should invest too much time on building something.

**Comment by alanmoo** [comment]
If it's not easy to do in Wagtail, I don't think it's worth it to try and do this in a 3rd place.

Flagging as "Help Wanted" in case anyone wants to take this on but I don't think we should spend time on it.

**Comment by Pomax** [comment]
Maybe, if the PDF gets generated off of a document, it would probably be worth asking whoever generates that PDF to also generate an .html export for transclusion on our webproperties, too. That way we can drop it into the static asset directory, replacing it whenever the original document updates, and then that way  people can access it the same way they access any other static content page.

**Comment by Pomax** [comment]
Do we still want to keep this open? @kristinashu @alanmoo
