### ISSUE TITLE
Show Campaign heading at narrow widths

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1557]
Headings are good at width widths: https://foundation.mozilla.org/campaigns/facebook-update/

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/1068783/40442950-b5e9b462-5e79-11e8-8559-62625a6aa80b.png">

But disappear at narrow widths (it should always be visible): 

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/1068783/40443092-0eee0784-5e7a-11e8-8c1c-435e78de2d77.png">

**Comment by ScottDowne** [comment]
This should do it: https://github.com/mozilla/foundation.mozilla.org/pull/1558
