### ISSUE TITLE
[Pulse component on Wagtail] Implementation ticket: project component admin

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1559]
Implementation ticket for:  #1542 - _assigning Alan for triage_

[Prototype - click on the arrow to see expanded view of Advanced filters](https://taisdesouzalessa.github.io/cms-pulse-projects-prototype/index.html)
[RedPen (v3)](https://redpen.io/po1dac786f32dfef25)
_Styling should match the current CMS  so I am not attaching the Sketch file._

- [ ] Search section: add label `Search terms:`, placeholder copy `Search Terms` and helper text `Test your search at mozillapulse.org/search` - the link should be clickable if possible.

- [ ] Add `OR` between Search section and Pick tags section

- [ ] Pick tags section: add label `Pick tags:`, placeholder copy `Data detox, iot` and helper text `Comma separated. Spaces are ok.` 

- [ ] Number of results section: add label `Max number of results:`, default number `24` and helper text `The maximum number of results to fetch. Choose 1-24.` 

- [ ] Featured section: add label `Featured:`, checkbox (default empty)`Display only featured entries` and helper text `Featured items are selected by Pulse moderators.` 

- [ ] Advanced filters section: default collapsed view. Label `Advanced filters:` Copy: `Options to display fewer, more targeted results.`. Once users click the arrow, the expanded view is displayed with the following options:

- [ ] `Issues:` Checkboxes (empty by default, alphabetical order): `Decentralization`, `Digital Inclusion`, `Online Privacy & Security`, `Open Innovation` and `Web Literacy`

- [ ] `Type of help needed:`  Checkboxes (empty by default, alphabetical order): `Attend`, `Create content`, `Code`, `Design`, `Fundraise`, `Join community`, `Localize & translate`, `Mentor`, `Plan & organize`, `Promote`, `Take Action`, `Test & feedback`, `Write documentation`

- [ ] `Sort:`  Radio button `Find and show the most recent` **(selected by default)** and `Find and show the oldest`

**Comment by alanmoo** [comment]
@gideonthomas Can you take a look through this and identify what the API can do presently? I think there are a few items in here for which it needs some additional filtering functionality.

**Comment by gideonthomas** [comment]
Pretty sure pulse already has all of this

**Comment by alanmoo** [comment]
> Add OR between Search section and Pick tags section

What happens if someone puts data in both fields?

> Pick tags section: add label Pick tags:, placeholder copy Data detox, iot and helper text Comma separated. Spaces are ok.

@gideonthomas What happens for multiple tags? Are they passed in the search by using `?tag=data detox&tag=iot`? This will be an `OR` tag search, is that right?

@taisdesouzalessa FYI it's probably an `OR` search.

>Advanced filters section: default collapsed view. Label Advanced filters: Copy: Options to display fewer, more targeted results.. Once users click the arrow, the expanded view is displayed with the following options:

I'm not sure collapsable sections are a reasonable option here. If Wagtail doesn't offer it with basically one line of code, I would push to not try and build it in.

>Issues: Checkboxes (empty by default, alphabetical order): Decentralization, Digital Inclusion, Online Privacy & Security, Open Innovation and Web Literacy

> Type of help needed: Checkboxes (empty by default, alphabetical order): Attend, Create content, Code, Design, Fundraise, Join community, Localize & translate, Mentor, Plan & organize, Promote, Take Action, Test & feedback, Write documentation

Similar question as tags @gideonthomas and @taisdesouzalessa: Syntax and `OR`?

**Comment by taisdesouzalessa** [comment]
Talked to Alan, waiting for Gideon input to see if using `OR` is the standard behavior for those features. If so, we should change the helper text to make clear for staff what's the expected result is.

**Comment by gideonthomas** [comment]
Ah good catch! Yeah I think its current behavior is AND not OR. Can you file a ticket in network-pulse-api for the fields you need it for? I can fix accordingly.

**Comment by taisdesouzalessa** [comment]
@xmatthewx, do you have any thoughts on the "AND" or the "OR" behavior for this feature? I feel that "OR" is the behavior users most expect but I could be wrong. We have:
1. To decide if we want "AND" or "OR" behavior.
2. File a ticket to Gideon (see comment above).
3. Adjust the copy accordingly so users know what to expect.

**Comment by xmatthewx** [comment]
Hi team. 

1) **API** – Let's avoid changing the API right now. I don't think we need to do that.
2) **Tags** - As an Author, if I request `tags: mozsprint, 2018`, I expect to only see items with mozsprint AND 2018, which is what @gideonthomas says the API already offers. 
1) **Help and Issues** – these could make sense to authors as OR, but again, let's not change the API. If needed @taisdesouzalessa, we could make these radio options, so an author can choose one or none, not multiple. What do you think?

@gideonthomas - two questions:
 - if someone hits the API for two issues categories, is it AND or OR?
 - if someone hits the API fro two help categories, is it AND or OR?

@taisdesouzalessa - 
 - thank you for absolutely amazingly thorough requirements checklist. it's help us catch important things before engineering started
 - Ping Pomax. Let's find out if a wagtail component could easily have a collapsing section. Otherwise I guess we'll use an `<hr>`

**Comment by gideonthomas** [comment]
Both issue categories and help categories are filtered using AND.

**Comment by xmatthewx** [comment]
Thanks @gideonthomas.
 
@alanmoo - sanity check: if we set up the admin to only allow one help category with radio option, we could later enhance it to allow more than one, without breaking old data. correct?

**Comment by taisdesouzalessa** [comment]
@xmatthewx should I change "Help and Issues" to radio then, as suggested? If we can choose one OR other option, it makes sense.

I'll ping Pomax about the collapsing section.

**Comment by taisdesouzalessa** [comment]
Talked to @Pomax and it seems it is a bunch of work to do the collapsing section at the moment. So let's go with Matthew's suggestion of displaying it all for now (with the hr dividing it). In the future, Pomax can investigate options for components customization in the CMS. The "advanced filter" could be a good option for some future components but we should be sure/have a list of it before investing time on that.

After I get Matthew's reply on "Help" and "Issues", I'll update the mockup accordingly.

**Comment by xmatthewx** [comment]
@alanmoo - sanity check: if we set up the admin to only allow one help category with radio option, we could later enhance it to allow more than one, without breaking old data. correct?

**Comment by Pomax** [comment]
This should probably be checkboxes if only because it looks like that's what wagtail has built in:

- search for `CheckboxSelectMultiple` in http://docs.wagtail.io/en/v2.1/getting_started/tutorial.html where they use this for "which categories is this blog post for"

**Comment by taisdesouzalessa** [comment]
so @Pomax does that mean, considering the image below, that the user can check `Decentralization` and `Digital Inclusion` for instance then the Pulse component will display results with the issues `Decentralization`, `Digital Inclusion` and `Decentralization and Digital Inclusion` combined? If so, the checkboxes make sense as we have now. Is there a limit of checkboxes users can check?

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/22157921/41613862-b342d51c-73ab-11e8-9d03-4b5587ffa8f2.png">

**Comment by xmatthewx** [comment]
@taisdesouzalessa - I believe that @Pomax is just saying wagtail makes it easy to implement checkboxes. But this won't work for us now, since A) the pulse api can't handle multiple categories and B) we'd have to get more explicit with the user about whether their query is `AND` (not so useful) or `OR` (useful but complicated and confusing when mixed with all the other options). 

I'd strongly prefer to limit choice with the radio selectors in the UI and keep everything simpler with queries. The scope of this will grow a ton otherwise. @Pomax @alanmoo can we do radio selectors?

**Comment by gideonthomas** [comment]
Don't want to cause extra noise here, but once we decide on scope for this specific ticket, can we file (or discuss) follow up tickets for the things that are out of scope that depend on other services, especially like pulse? There are some tasks such as supporting AND and OR queries that we'll need to add to pulse at some point anyway for org profiles and our dashboard view. Once we are able to decide on that, we can probably figure out a timeline for when we get to implement those out-of-scope issues and we might be able to adequately set ourselves up for scoping out a v2 of this issue.

**Comment by taisdesouzalessa** [comment]
After talking to Pomax and Alan today in stand, we decided to use the select box instead of the radio, since users can choose just one option and it looks less overwhelming than a bunch of radio buttons. I'll do the comp, post here and create a new clean implementation ticket. Does that make sense to you @xmatthewx?

+1 to @gideonthomas comment about adding follow up tickets. I feel we have many interesting points here for V2 that shouldn't be forgotten: like having a collapsible component or adding the option in Pulse for more than one "issue" or "help" category. Gideon, would you like to put a list together and I can file the tickets? Or you can file as well if you prefer?

**Comment by xmatthewx** [comment]
Drop-down selector is a solid compromise.

**Comment by taisdesouzalessa** [comment]
here is the component, revised. I am not sure about the styling of the drop down component on Wagtail but I imagine it is something similar to that.

Interaction demo:
![interaction-demo](https://user-images.githubusercontent.com/22157921/41745333-730ad074-755b-11e8-9b6a-cde52fb17024.gif)

InVision:
https://mozilla.invisionapp.com/share/H7LK885483V#/304643566_Panel_-_Collapsed

@alanmoo @Pomax @xmatthewx - let me know if this solution works (you can just give a thumbs up in this comment) then I can create a new clean implementation ticket.

**Comment by alanmoo** [comment]
This seems like a good set of guidance for what functionality this component should have, though I want to point out that we only have so much control over the admin within a reasonable amount of effort. This is one of those cases where the final product may not look extremely close to the comp, but as long as the general functionality is there I think we're good.

**Comment by taisdesouzalessa** [comment]
Yep, agree with you @alanmoo. I don't think the styling is super important here since it is not a component that will be seen by our audience. I am okay with the style being what's possible within Wagtail, as long as the functionality is there and easy to use by staff.

**Comment by taisdesouzalessa** [comment]
Clean ticket filed here: #1617. Closing this issue. We can create follow up tickets as proposed by @gideonthomas.
