### ISSUE TITLE
[Campaigns] Multi-page petition page layout

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1560]
We need our [multi-page petition pages](http://foundation.mozilla.org/campaigns/aadhaar/) to align with our single-page petition pages where the form is nice and prominent.

#### Steps include:
- [x] Move sub-nav from side to top below the title and style (see below for style details)
- [x] Use the same layout grid as single-page petitions (7 body content | 1 gap | 4 form)
- [x] Mobile: sub-nav turns into a dropdown like we have now on [see Aadhaar](http://foundation.mozilla.org/campaigns/aadhaar/)

#### Follow up tickets:
- Add "next section" wayfinding #1561
- Style all our dropdowns [need ticket]

#### Sub-nav styling:
- 15px 
- #000
- 24px gap between menu items
- Inactive
  - Nunito Sans Regular 
  - Line: 1px | #CCCCCC
- Selected/Hover
  - Nunito Sans Bold
  - Line: 3px | #000 | length of the word

#### [Extra Large:](https://redpen.io/pg11648642fd877912)
![multipage copy 2x](https://user-images.githubusercontent.com/1068783/40510255-f0d8fb78-5f50-11e8-93a2-294a671054f9.jpg)

#### [Medium:](https://redpen.io/zy0a3e69d2aaef09dc)
<img width="654" alt="image" src="https://user-images.githubusercontent.com/1068783/40499082-b28515f2-5f35-11e8-9940-2856e145e41a.png">

#### [Small and Extra Small:](https://redpen.io/hx831a776ac7d00a3f)
<img width="318" alt="image" src="https://user-images.githubusercontent.com/1068783/40499062-a9569e42-5f35-11e8-908a-5ff9bb62dda1.png">

**Comment by beccaklam** [comment]
@kristinashu Looks good to me! Only thing is I think stylistically Nat's subnav on the nav UI's she's developing uses a thicker line for selected items that's aligned in the middle of a thinner grey line ... should we make them the same? I'm fine with adapting Nat's style for the campaign pages if so. CC: @natalieworth

**Comment by kristinashu** [comment]
@beccaklam @natalieworth I would like to get them as similar as possible. I've mocked up a quick comparison https://redpen.io/mz3c1d83d188065adf

**Comment by kristinashu** [comment]
I went with something in between, specs [above](https://github.com/mozilla/foundation.mozilla.org/issues/1560#issue-326180443) have been updated. Thanks!

**Comment by kristinashu** [comment]
There's a PR open for this and a follow up ticket https://github.com/mozilla/foundation.mozilla.org/issues/1587

**Comment by kristinashu** [comment]
Note to @beccaklam @natalieworth: Scott wasn't able to make the selected nav item bolder than the non-selected nav items. Changing the font weight caused all the letters to shift so even with some tweeks, I think it will always seem a little off.

Gif from PR:

![nav](https://user-images.githubusercontent.com/1068783/41001730-a1bf1872-68c6-11e8-8899-d509321702ad.gif)
