### ISSUE TITLE
[Campaigns] Multi-page petition: add "next section" wayfinding

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1561]
Follow up from #1560 

At the bottom of a multi-page petition, there is a link to the next section. 

It should say `Next: [name of the next sub-page]`

[Comp:](https://redpen.io/pg11648642fd877912)

![multipage 2x](https://user-images.githubusercontent.com/1068783/40499938-3eca0660-5f38-11e8-90cf-7a1c48616e6d.jpg)

**Comment by kristinashu** [comment]
@beccaklam @ScottDowne do you have any thoughts on what we should do on the last page?

A) Link back to 'Overview' (might need to update 'Next' to 'Back to')
B) Hide this feature
C) Something else?

**Comment by beccaklam** [comment]
My quick two cents: I think the next action we would want them to take is to complete the CTA, right? In that case it makes sense to hide the feature and direct attention back to taking action. We just don't want to direct the user away before they've completed the action.

**Comment by kristinashu** [comment]
Good point! Let's hide the 'Next" link on the last page.

**Comment by Pomax** [comment]
If I'm not mistaken, the site does not show a "next" and so this issue can be closed. /cc @kristinashu

**Comment by kristinashu** [comment]
This was to add a "next" feature but we're going to re-asses campaign pages soon anyways so let's close!
