### ISSUE TITLE
[Campaigns] Layout is offset and broken

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1564]
On staging, if "Narrowed page content" is checked on a petition page then everything is offset.

<img width="1394" alt="image" src="https://user-images.githubusercontent.com/1068783/40511597-0fec8d96-5f55-11e8-9f43-bc05195cc88d.png">

This should not be checked on these pages but if it is then we should have a backup that doesn't look broken.

**Comment by ScottDowne** [comment]
Fixed in https://github.com/mozilla/foundation.mozilla.org/pull/1568
