### ISSUE TITLE
[Wagtail Component] Tweak in margin-top for captions

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1567]
For our image, iframe and video components (every element that has a caption, let me know if I am forgetting something), please make the caption closer to the image. Margin-top=8px (0.5 rem) instead of 16px (1rem).

Ex:
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/22157921/40559648-51a46f30-600c-11e8-8c5b-49d09204b2c4.png">

**Comment by Stark-Pramod** [comment]
@taisdesouzalessa  I would like to do this. Since I a newbie to  Open source world I may need some guidance.

**Comment by taisdesouzalessa** [comment]
Hi @Stark-Pramod, thanks for your interest on this issue :). I am currently on mat leave so I'll put you in touch with somebody from my team and you can take it from there okay? @kristinashu could you please check with our team about this issue? Thanks!!

**Comment by Stark-Pramod** [comment]
@taisdesouzalessa No problem, and thanks.
@kristinashu, Can you help me over this?

**Comment by youriwims** [comment]
[should've been] Closed via #3574
