### ISSUE TITLE
[Wagtail QA] Image component

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1572]
@taisdesouzalessa the latest push https://github.com/mozilla/foundation.mozilla.org/issues/1513 seems to have turned a lot of the images to full width. This is great for the big images but the icons are now huge and look broken. As a quick fix I deleted all the icons which looked too big.

- [x] Could you please re-add those icons? Not sure if you need to wait until @gvn has done another component for that? I've attached screen caps so you know which icons go where.

- [x] Images on https://foundation.mozilla.org/opportunity/tech-policy-fellows/ are a little big but I've left them as is for now. Could you please fix them however you see fit?

Screen caps from https://foundation.mozilla.org/opportunity/mozilla-information-trust-initiative/
![screenshot-2018-5-29 mozilla information trust initiative](https://user-images.githubusercontent.com/1068783/40675067-7ee7b584-632b-11e8-9801-435be6f806e1.png)

Screen caps from https://foundation.mozilla.org/opportunity/web-literacy/
![screenshot-2018-5-29 frame](https://user-images.githubusercontent.com/1068783/40675066-7ecc2468-632b-11e8-8976-e8c0d3101aac.png)
![screenshot-2018-5-29 participate](https://user-images.githubusercontent.com/1068783/40675068-7f032ada-632b-11e8-9f35-c908626a72e5.png)
![screenshot-2018-5-29 read](https://user-images.githubusercontent.com/1068783/40675069-7f21dd86-632b-11e8-9256-081ea3f67782.png)
![screenshot-2018-5-29 web literacy](https://user-images.githubusercontent.com/1068783/40675070-7f407638-632b-11e8-9fe4-cbed2ee80ba9.png)
![screenshot-2018-5-29 write](https://user-images.githubusercontent.com/1068783/40675072-7f617108-632b-11e8-9053-6d54248bb85d.png)

**Comment by taisdesouzalessa** [comment]
Taís to:
- take a look at existing pages and do the temporary fixes if necessary;
- once Image + Text component is in place, take re-add the icons

**Comment by taisdesouzalessa** [comment]
> Images on https://foundation.mozilla.org/opportunity/tech-policy-fellows/ are a little big but I've left them as is for now. Could you please fix them however you see fit?

**Fixed!**

TO DO: Once Gavin works in the icon+text component (small icon size image - #1514), I can add them back to the page - item 1 from this check list.

**Comment by gvn** [comment]
This should be unblocked now!

**Comment by taisdesouzalessa** [comment]
Tks @gvn :). I'll add those images back!

**Comment by taisdesouzalessa** [comment]
@gvn I filed a but here related to this issue:  #1618 - let me know if this is an issue or maybe I am doing something wrong? I uploaded the image then checked the box for "small" images.

**Comment by taisdesouzalessa** [comment]
MITI page icons readded and page republished: https://foundation.mozilla.org/opportunity/mozilla-information-trust-initiative/

Next step: Wed Lit page

**Comment by taisdesouzalessa** [comment]
Web Lit page icons readded and page republished: https://foundation.mozilla.org/opportunity/web-literacy/

Closing this ticket.
