### ISSUE TITLE
[Fellowship Mini Site] Take down Open Application Banners on Science + Open Web sites

### ISSUE THREAD

**Issue by annmarie123** [mozilla/foundation.mozilla.org#1573]
On the [open science website](https://science.mozilla.org/programs/fellowships) and [open web fellowship site](https://advocacy.mozilla.org/en-US/open-web-fellows/overview), there are still banners up promoting the fellowship application and saying it is open. Can we please take those down ASAP?

Let me know if I can help in any way.

**Comment by taisdesouzalessa** [comment]
Assigned Alan for triage.
