### ISSUE TITLE
[Waigtail QA] Draft mode warning is missing

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1574]
<img width="1306" alt="screen shot 2018-05-30 at 8 50 44 am" src="https://user-images.githubusercontent.com/1068783/40734784-404e53c8-63ee-11e8-9a60-e3231a850306.png">

Looks like we lost the warning banner that let users know their page is in draft mode. Please bring this back!

**Comment by kristinashu** [comment]
Here's the original ticket https://github.com/mozilla/foundation.mozilla.org/issues/1055

**Comment by Pomax** [comment]
closed by https://github.com/mozilla/foundation.mozilla.org/pull/1577
