### ISSUE TITLE
Inherit OG tags from parent

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1582]
Following up on #1455 and unmerged #1497

A page should inherit the "search description" and "search image" in the promote tab from its parent, but be able to override it.

Affects all pages/templates across the site.

**Comment by alanmoo** [comment]
(@Pomax)

**Comment by kristinashu** [comment]
Is this right?

If https://foundation.mozilla.org/en/initiatives/responsible-cs/ does not have OG tags then we show the one from https://foundation.mozilla.org/ 

AND if https://foundation.mozilla.org/en/initiatives/responsible-cs/ does have a unique tag then it will show for that and also https://foundation.mozilla.org/en/initiatives/responsible-cs/challenge/?

**Comment by alanmoo** [comment]
Correct, unless 
https://foundation.mozilla.org/en/initiatives/responsible-cs/challenge/ has its own tags set then we'd show those.

**Comment by Pomax** [comment]
Hm, looking at view-source:http://foundation.mozilla.org/en/initiatives/ it seems we don't even have OG tags in the template for that page? So @cadecairos's PR is quite nice for inheritance, but we'll still need to make sure all our page templates actually _have_ `<meta name="og:...` code in place

**Comment by Pomax** [comment]
see https://github.com/mozilla/foundation.mozilla.org/issues/2357
