### ISSUE TITLE
Participate page: Replace Global Sprint with MozFest

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1586]
Now that Global Sprint has ended we should replace that block with MozFest https://foundation.mozilla.org/participate/

@sabrinang do you have a graphic we can use?

@Sydette do you have any copy suggestions?

**Comment by kristinashu** [comment]
Copy from Sydette:

[Title] Mozfest 2018 is open for proposals!

This years theme "Data and You" takes the large concepts of data: collection, surveillance, policy, it’s currency and its future and center it around the most important of all its parts: people. How does and will data affect people’s lives? How can we share best practices, innovative tools and grow connections that allow data to serve people instead of people serving data. The deadline for proposals is August 31st.

[Link] Apply now [https://mozillafestival.org/proposals]

**Comment by kristinashu** [comment]
Here's a graphic. @sabrinang is this ok to use?

![mozfest-promo](https://user-images.githubusercontent.com/1068783/41620035-4d41d9a4-73bd-11e8-9717-577de665aaa9.jpg)

**Comment by sabrinang** [comment]
@kristinashu Yes that's the CFP social background 👍
