### ISSUE TITLE
Hide "subscribe" option on petitions if user came from an email

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1588]
MVP (as there are probably a bunch of ways this will not be effective)
If the URL contains a query parameter `subscribed=1`, we should not show the "sign up for the newsletter" checkbox on petitions

**Comment by taisdesouzalessa** [comment]
Really like this idea, such a good way to remove unnecessary info for specific users.

**Comment by desiree-mofo** [comment]
@Pomax  and @ScottDowne  - I think this is what we were discussing last week in our petition meeting? Wanted to make sure y'all were aware of this issue. I was going to enter something similar, but think we can work from this one...

**Comment by ScottDowne** [comment]
@desiree-mofo Question on this, if the signup is removed, does that mean the country list should go first?

I guess it comes down to if the country is used for the signature or the signup or both. If it's only used for signup, we should probably remove it too.

**Comment by ScottDowne** [comment]
It looks like the only thing we're removing is the checkbox that says "Yes, I want to receive email updates about Mozilla’s campaigns." and everything else stays the same.
