### ISSUE TITLE
[Campaigns QA] spacing and color on multipage petition

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1594]
Overall it looks great, just some small spacing improvements and @ScottDowne solution of making non-selected state gray.

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/1068783/41113651-1641c732-6a37-11e8-88bb-08dc94d30019.png">

**Comment by kristinashu** [comment]
Oh and mobile... please move the content (i.e. the image) up. 
(ignore the dropdown styling)

<img width="685" alt="image" src="https://user-images.githubusercontent.com/1068783/41115960-ddb3c04e-6a3d-11e8-8d75-3f3b818420b4.png">

**Comment by kristinashu** [comment]
Relevant updates should also be applied to Opportunity pages.

**Comment by ScottDowne** [comment]
This got merged.
