### ISSUE TITLE
[Campaign UX] Explore UX around country selector 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1597]
Integrating our petitions with Sales Force means that some of our campaigns will have a Country selector. Let's make sure what we have is the best approach. 
<img width="440" alt="image" src="https://user-images.githubusercontent.com/1068783/41118365-9612bf68-6a44-11e8-9f52-2fb6feb78eaa.png">

### Couple examples:
https://www.change.org/p/save-b-c-wolves
<img width="364" alt="screen shot 2018-06-07 at 11 16 59 am" src="https://user-images.githubusercontent.com/1068783/41118347-887fedb2-6a44-11e8-9adf-958132d3a830.png">
https://actions.sumofus.org/a/show-your-support-for-nationalising-britain-s-water-industry
<img width="357" alt="screen shot 2018-06-07 at 11 17 33 am" src="https://user-images.githubusercontent.com/1068783/41118348-889bc10e-6a44-11e8-954a-9635c4b1780f.png">

**Comment by ScottDowne** [comment]
I like the second one sumofus.org. I think that's in line with what we already got and I think the transition for the placeholder to label is going to be a nice touch.

The first one from change.org with the pencil in the dotted box looks confusing to me, and I'm not sure what the bottom box signifies. I initially think it implies a bit more freedom to edit above and beyond a normal text box.

**Comment by ScottDowne** [comment]
@kristinashu I can try some things based on the examples you provided and have you take a look, or did you want to comp up stuff first?

**Comment by kristinashu** [comment]
Yeah, I'd would like to do a little more benchmarking first. Let me know if you find any good examples!
