### ISSUE TITLE
Finalize wireframes for Participate

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1604]
Follow up from https://github.com/mozilla/foundation.mozilla.org/issues/1547 and based on @taisdesouzalessa lovely [wireframes](https://mozilla.invisionapp.com/share/GHL7FLR8R73#/screens/302107241_Proposal_3_-part-_-_Revised_-_Full_Hero).

### Next steps 

**Determine and Gather Content:** #1607
- Create spreadsheet template for content 
  - include columns for category, length of time, intro text, cta link...
  - possible features and charts...
- Share with Sydette to add content

**InVision prototype with links to Sub-pages:** 
- Link up Participate, Initiative and some of the CTA links (internal + external) to test how the flow feels  #1620

**Requirements list for devs:** #1648
- what content needs to be updateable and how
- make sure everything is doable

**Basic UI:** Mockup UI that aligns with Initiatives page and the rest of the site #1605

**UI Interactions:** [need ticket] benchmark and explore delightful enchantments

**Page future updates and maintenance:** [need ticket]
- Sync with Sydette (and other necessary teams) to make sure we have an editorial calendar with dates of events and when the page needs update. This item is to make sure we constantly update this page to keep it fresh and accurate,

cc @xmatthewx @jessevondoom @taisdesouzalessa @beccaklam please update this list as you see fit!

**Comment by taisdesouzalessa** [comment]
@kristinashu I added the last item to the list. It is something Ashley brought up during the All Hands and I think it's an important piece to keep this page fresh and useful to our audience.

**Comment by kristinashu** [comment]
Closing this ticket! Any followup can be done in the UI ticket #1605
