### ISSUE TITLE
[Participate Page] Spreadsheet template for Content

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1607]
Here is the link to the spreadsheet: 
https://docs.google.com/spreadsheets/d/1wAt7_FqVc-Dw_Eqrsqbt1m5ervLZIBb3BLWvDe7UCJ4/edit?usp=sharing

It is still incomplete and the copy is just a placeholder.

@kristinashu @xmatthewx @jessevondoom @Sydette  @beccaklam I'll need your help here to make this spreadsheet as complete as possible with all the opportunities of participation we may have in a given year. Let me know if I should loop more people in and if the spreadsheet is clear. Feedback is welcomed to make it easier to understand/complete :).

**Comment by xmatthewx** [comment]
We should probably distribute this task to program teams. Maybe setup a google form and @jessevondoom can ask all Directors to submit their opportunities. Or informally slack each program lead. If you do pursue either option, I recommend you just ask for brief general info. Make it quick and easy to submit essential data. Later, we can seek out nitty gritty details if needed.

**Comment by taisdesouzalessa** [comment]
I really like the first option, @xmatthewx - having a Google form helps us on documentation and quickly gets us all on the same page. I think if we do that informally we run the risk of having some lose ends and forgotten pieces. I can work on a draft of the form and submit for you and Jesse to review it.

**Comment by taisdesouzalessa** [comment]
Not sure this spreadsheet is relevant anymore. Have you been using it to organize content with Sydette, @kristinashu? If not, let me know and I can close this ticket...it seems we are using another method for organizing content in this page.

**Comment by kristinashu** [comment]
Sydette is using a google doc for writing the content. Spreadsheet probably isn't as useful now that that we've decided to not use categories.
