### ISSUE TITLE
Create staging database update process

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1609]
It would be great if the staging database closely resembled the production database. IMO, the ideal situation would be production database gets copied to staging weekly, stripping out whatever sensitive data shouldn't be on staging, if any (I believe there may be some concern with user accounts). There should also be a relatively easy way to do it manually.

Implementing this would be a big improvement to the team's testing procedures.

**Comment by cadecairos** [comment]
Had a conversation with @patjouk, realized copying data from production to staging is not going to work, and if it did it would break constantly. so here's the new plan:

1. load production pages into a local database, to generate a bunch of meaningful data.
2. dump pages/campaigns/petitions into a fixture, that's guaranteed :tm:  to load for that specific commit.
3. write a management command that dumps the data exactly as described in 2
4. write a post-deploy command for staging that loads the fixture (after flushing the models)
5. Document that any schema changes require re-generating the fixtures from a local database.

This should result in a setup where staging always has useful data to test with, and ensures we can update the fixtures as needed when the schemas change.

**Comment by alanmoo** [comment]
Can you explain step 5 a bit more? I'm concerned about the overhead it seems is required to "make it work again" when we make schema changes.

**Comment by Pomax** [comment]
Having copied the production database many times, can you expand on why it would break constantly? As long as `inv migrate` runs after a copy, there should be no real issues beyond "who has access" and "making sure the site settings are correct" (which are a trivial secondary pg import as far as I can tell).

**Comment by cadecairos** [comment]
This was resolved via https://github.com/MozillaFoundation/mofo-cron/tree/master/tasks/clone_foundation_site
