### ISSUE TITLE
[Fellowships Mini Site] iPhone 5 Directory page issue

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1612]
_Assigning to Alan for triage_

### Problem: 
In the [Directory Page](https://foundation.mozilla.org/fellowships/directory/), the Social media links overlap with "see work" link, which makes them all super hard to click on. _This bug happens in iPhone 5 (just a small part of our audience sees this bug so it is non-critical)._ Browser: Safari.

<img width="380" alt="image" src="https://user-images.githubusercontent.com/22157921/41678485-089e68da-7480-11e8-9df0-15bc247a5be1.png">

<img width="388" alt="image" src="https://user-images.githubusercontent.com/22157921/41678598-513530a6-7480-11e8-8cd8-1715e1135d4b.png">

**Comment by alanmoo** [comment]
This appears to work in the iOS 11 simulator for an iPhone 5S, so I suspect that it's a bug related to iOS 10 (as the iPhone 5 can't run iOS 11). If a contributor can replicate this and wants to pick it up, they're welcome to, but the team isn't going to try and fix this.

**Comment by taisdesouzalessa** [comment]
Yep, the version was iOS 10.3.3 (it is Becca's phone). To reproduce it, you can use the settings below in [this simulator](https://appetize.io/demo?device=iphone5s&scale=75&orientation=portrait&osVersion=10.3&deviceColor=white):

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/22157921/41732545-2891c964-7536-11e8-8416-eb63abdf645e.png">

URL for testing: https://foundation.mozilla.org/fellowships/directory/

**Comment by kristinashu** [comment]
Let's do this when we CMS-ify the Fellowship pages #2282
