### ISSUE TITLE
Promote MozFest

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1616]
@Saallen @KevZawacki @caltrider @sabrinang @Sydette please add images, copy, and suggested post dates.

A few ideas from Sarah:

**Happening now section** (need: title, body, cta text and url link):
- Call for proposals
- Tickets sales mid July 

**News section** (need: url to article, very short intro text):
- Blogs posts by wranglers

We already have this image and text on the [Participate page](https://foundation.mozilla.org/participate/) but please add any other content you have.

**Comment by kristinashu** [comment]
Updated! Mark's blog is now featured in news.

**Comment by Saallen** [comment]
Hey- looping in @kristinag here too

Suggestion under for happening right now section

MozFest Call for Proposals

The ninth annual MozFest will be held in London Friday October 26 - Sunday October 28. We want you to join us where the web meets world. Come with an idea, leave with a community. 

Will you consider submitting a session idea to be a facilitator at MozFest, sharing your work with other advocates for a healthy internet? Your creativity, expertise and contribution to the open web will not only benefit the MozFest community, but also enhance your leadership skills and allow you to contribute to a growing global network.

**Comment by Saallen** [comment]
Pull graphic from here
https://drive.google.com/drive/folders/0B4Q8pzCpDS_eLURVNVEtNVhGQ3M

**Comment by kristinashu** [comment]
Added! https://foundation.mozilla.org/ 

I had to shorten the copy a little and the https://github.com/mozilla/foundation.mozilla.org/issues/www.mozfest.org/proposals url wasn't working so I used https://mozillafestival.org/proposals instead. Hope that's ok.
