### ISSUE TITLE
[Pulse component on Wagtail] Implementation ticket

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1617]
Here is the component. I am not sure about the styling of the drop down component on Wagtail but I imagine it is something similar to that. If not, the default style of Wagtail is okay as long as functionality is preserved.

### Interaction demo:
![interaction-demo](https://user-images.githubusercontent.com/22157921/41745333-730ad074-755b-11e8-9b6a-cde52fb17024.gif)

### InVision:
https://mozilla.invisionapp.com/share/H7LK885483V#/304643566_Panel_-_Collapsed

### Checklist:
_Styling should match the current CMS  so I am not attaching the Sketch file._

- [ ] Search section: add label `Search terms:`, placeholder copy `Search terms` and helper text `Test your search at mozillapulse.org/search` - the link should be clickable if possible.

- [ ] Add `- OR -` between Search section and Pick tags section

- [ ] Pick tags section: add label `Pick tags:`, placeholder copy `Data detox, iot` and helper text `Comma separated. Spaces are ok.` 

- [ ] Number of results section: add label `Max number of results:`, default number `24` and helper text `The maximum number of results to fetch. Choose 1-24.` 

- [ ] Featured section: add label `Featured:`, checkbox (default empty)`Display only featured entries` and helper text `Featured items are selected by Pulse moderators.` 

- [ ] Horizontal hairline

- [ ] Advanced filters section: Label `ADVANCED FILTERS:` Copy: `Options to display fewer, more targeted results.`. 

- [ ] `Issues:` Dropdown box with `All` chosen by default (if users don't choose an option, all will apply). Once the dropdown arrow is clicked, the full list is displayed in alphabetical order: `All` (in light grey, since it is the selected option), `Decentralization`, `Digital Inclusion`, `Online Privacy & Security`, `Open Innovation` and `Web Literacy` - If users choose another option, the list remains the same and the chosen option is displayed in the box and it is light grey in the expanded view of the list.

- [ ] `Type of help needed:`  Dropdown box with `All` chosen by default (if users don't choose an option, all will apply). Once the dropdown arrow is clicked, the full list is displayed in alphabetical order: `All` (in light grey, since it is the selected option), `Attend`, `Create content`, `Code`, `Design`, `Fundraise`, `Join community`, `Localize & translate`, `Mentor`, `Plan & organize`, `Promote`, `Take Action`, `Test & feedback`, `Write documentation`- If users choose another option, the list remains the same and the chosen option is displayed in the box and it is light grey in the expanded view of the list.

- [ ] `Sort:`  Radio button `Find and show the most recent` **(selected by default)** and `Find and show the oldest`

- [ ] Horizontal hairline

**Comment by gvn** [comment]
I don't seem to be able to add a clean looking "OR" separator without a colon following it (IE: `-OR-:`). Also, "search terms" currently also includes tags. @taisdesouzalessa how would you feel about keeping the "Search terms" UI the same (as one field), but updating the help text to explain that tags work too?

**Comment by xmatthewx** [comment]
@taisdesouzalessa and I discussed this. One input is fine, using search to also query tags. The original thinking was that an author might want things explicitly tagged `this, that`, skipping stuff that mentioned those terms. But it's not critical and we can tackle that later _if_ we surface a significant need.

**Comment by taisdesouzalessa** [comment]
After talking to Matthew and Gavin today, here is the component, updated. I highlighted the changes:
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/22157921/41941692-983cc89e-7951-11e8-84cc-de396d0609b3.png">

1. In the "Search terms" box we state that both description and tags are accepted.
2. Updated helper copy to add more clarity on what staff could do to test their search term. Excluded link sicne it's not possible on Wagtail.
3. Decreased the default max number for results to 6 (staff can still add 24 as max). But default is 6 because it looks good.
4. Added "If you want unlimited results, please check “show all results” below." to the helper text.
5. Added a "show all results" box for cases in which staff would like to display all projects (e.g. Global Sprint). Also added a helper text explaining the risks on slow page loading if all results are displayed. Talked to Gavin about it and this was his suggestion until we do a definitive fix by implementing a lazy loading or pagination solution.

@xmatthewx @gvn please take a look at those and let me know if you agree (give the thumbs up if yes). Once the comp is approved by you both, I'll either update this ticket or create a clean one.

**Comment by xmatthewx** [comment]
- Search
   - Label: "Search"
   - Placeholder: "Search across title, description, and tags"
 - Limit
   - Let's not do the checkbox. It's confusing, requires a lot of help text. We could instead just remove the limit above. 
   - Option A: State a limit of 24 in the help text. But don't actually code a limit. Staff who know can cheat. 
   - Option B: Keep the limit. Add a toggle to include a "Load More" button.

I am against making an exception for a single user/use case when it makes the utility less good for everyone else.

Let's chat after stand with @alanmoo to bring some closure to this.

**Comment by taisdesouzalessa** [comment]
Let's chat tomorrow after the stand then, @xmatthewx? Gavin will be in :).

**Comment by taisdesouzalessa** [comment]
Here is the tweaked component, based on conversation we had today:
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/22157921/42050576-35c827ee-7abe-11e8-9d45-2cc0efee685b.png">

All comps are in InVision:
https://mozilla.invisionapp.com/share/XTM3O1I42MY#/305933243_-CMS_-_Projects_-_V6_-v4_Updated-__Copy

I will create a new clean ticket again for you @gvn :). @xmatthewx could you please take a look at the new copy and see if you are ok with it?

**Comment by gvn** [comment]
That looks great. One other thing: I haven't been able to find a radio button for Wagtail, so it may need to stay similar to how it is now, like:

- [ ] Show most recent entries first

**Comment by xmatthewx** [comment]
For `Button`, let's adjust the help text @taisdesouzalessa. 
 - "Only displayed if there are more results to load." 
 - My thinking: people can select any limit 1-12, and toggle the button on for any mount. The frontend should look at the total count, and only display the button if it's more than the results displayed.  

For `Sort`, can we use a select box with the copy in the comp @gvn?

**Comment by taisdesouzalessa** [comment]
Hey @xmatthewx here is the updated comp. One question I have, though: wouldn't be better if we say "Only displayed if there are more results **than 12** to load". I feel it is clearer since this button will only show up if there are more than 12 entries, correct? Less than 12 we will be displaying them all, in my understanding. Let me know if it makes sense?

<img width="1287" alt="image" src="https://user-images.githubusercontent.com/22157921/42059820-8847bdd4-7ad9-11e8-9c3d-745aecd6049a.png">

**Comment by gvn** [comment]
> For Sort, can we use a select box with the copy in the comp @gvn?

Yeah, that should work too.

**Comment by xmatthewx** [comment]
@taisdesouzalessa - i fear that authors will be confused if they set 6, check the box for the button, and then see no button. we're asking them to set one limit and then think about another limit. help text is a band-aid. also, why not give them a button? they might be prefer a short list of 6 with load more. that's not bad for users. 

i also fear that we are splitting hairs to create a solution for an edge case problem, instead of building the best solution to solve 80% of the most common and useful use cases. 

i'd like to ship this and then come back to the original idea and figure out how to give authors a button that takes visitors to view their search on pulse.

**Comment by gvn** [comment]
I vote Option A, which is what I thought we had consensus on in our meeting earlier.

**Comment by gvn** [comment]
@xmatthewx What is this blocked by?

**Comment by xmatthewx** [comment]
Hi team. I've done a poor job of managing this. We have concluded [several times](https://github.com/mozilla/foundation.mozilla.org/issues/1535) to not offer pagination, to limit number of projects to benefit visitors. And somehow, we keep backpedaling to accommodate a single use case that is outside the intentions of this component or the site. 3 days ago, it happened again. I think it was my fault. 

Here are pageviews for global sprint project page: 

<img width="957" alt="image" src="https://user-images.githubusercontent.com/53411/42103394-ecb192be-7b96-11e8-8244-40e2550d12ec.png">

Views dropped to 20 views on Saturday _during_ the sprint. Today, a month later, it receives 0-3 visits. The job of that page is done. It no longer needs to be part of this discussion.   

Let's pause development and async discussion. We need to make final decisions based on future [strategic](https://docs.google.com/document/d/15ibu9poy88lljiRWD8xqUDx0NHvq69ySdPkhvRSyHBk/edit?usp=sharing) use of the component. Today, @taisdesouzalessa and I will discuss and deliver a clean set of requirements to put a bow on this.

**Comment by taisdesouzalessa** [comment]
Based on conversation with Matthew, here is the new clean ticket:  #1639 - unblocking and closing this ticket.
