### ISSUE TITLE
[Wagtail QA] Image component bug

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1618]
Issue: the images get cut in the final view of the site (here in draft mode):

<img width="909" alt="image" src="https://user-images.githubusercontent.com/22157921/41792253-0bb5da42-760d-11e8-800f-77845c7bc250.png">

To see it, please go to "Mozilla Information Trust Initiative" in Wagtail - Draft Mode (I didn't publish the page live).

**Comment by gvn** [comment]
I'm not seeing that in Firefox at least. Here's a screenshot:

<img width="834" alt="screen shot 2018-06-22 at 1 35 06 pm" src="https://user-images.githubusercontent.com/206379/41798070-229467e2-7621-11e8-8806-174b941dcbc4.png">

**Comment by gvn** [comment]
That would be because we're enforcing a 1:1 aspect ratio on the images. If they are wider than that they will be cropped. 

So, this is currently by design and not a bug.

**Comment by taisdesouzalessa** [comment]
Oh cool, so I should export them as squares. I'll do that and upload them again. Thanks, Gavin!

**Comment by gvn** [comment]
Yeah, that would work. I think we could also change it to not force a square aspect ratio, but that's up to you. There's pros/cons of both approaches.
