### ISSUE TITLE
Link up Participate, Initiative and some of the CTA links (internal + external) to test how the flow feels

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1620]
**Participate Page:** UX Flow here (clickable prototype) - https://mozilla.invisionapp.com/share/SELSJQL2WGF#/304403200_Proposal_3_-_Ux_Flow_-_Main

Please note I added some feedback pieces form our crit session (added issues to the cards and Pulse categories on the bottom of the page, for instance) 

I find it easier to navigate and feel the flow if you have some scenarios in a script to follow. Here is the script: https://docs.google.com/document/d/1BiFWWJCB0mCV7MraGpHi3nC5RmvKGFprgndY_ny8HqI/edit?usp=sharing

@kristinashu @xmatthewx @natalieworth @beccaklam @sabrinang  if you have some time available, would you mind going over that script, see how it feels and give me feedback? Feedback can be given in the doc or via InVision. I would love some fresh perspective since I've been looking at those for a while... thanks!

**NOTE:** we may not have the "buckets" such as "Get Informed", "Meet and collaborate with our network" - it will depend on how we decide to organize the content. If we don't have those buckets, the flow would be simpler, since users would go from the cards straight to individual pages (here is the [single screen](https://mozilla.invisionapp.com/share/WQLSKJLXRK6#/302107240_Proposal_3_-part-_-_Revised_-_Full_Hero_-_V2_Copy) that was presented at all hands for this scenario).

**Comment by kristinashu** [comment]
Thank you for putting this together @taisdesouzalessa! It's super useful to see. I think all the external links feel fine, especially with the icon in the button. 

I just added one note in InVision about the Reports or Opportunity type pages. Since these are essentially third level pages, maybe they should be quite simple and basic (more content, less design). Maybe it just needs a grid of cards and no hero banner? As is, I worry this starts to look too much like the primary pages.

**Comment by taisdesouzalessa** [comment]
Yep, that's a good point. I'll do the changes :)

**Comment by beccaklam** [comment]
@taisdesouzalessa Added some feedback in the doc. But overall, great work, loved the script. +1 to Kristina's comments about removing the hero banner from sub pages and making it more content than design. I think we need to think more about how to direct users back to the main participate page and I think there's more UX thinking that could be done to link to Pulse and on the Pulse site itself for when users get there.

**Comment by beccaklam** [comment]
@taisdesouzalessa One more thing, can we do a flow without the categories? I'm wondering how that would feel.

**Comment by beccaklam** [comment]
Linked up Initiatives Page Invision prototype here: https://mozilla.invisionapp.com/share/W4MFKDA5D2A
 Some external links are working better than others. Also I think Advocacy may be the only external site that needs the interim 'landing page'? Will discuss in meeting with Jesse, Kristina, Tais and Nat today.

**Comment by kristinashu** [comment]
Once @beccaklam has updated the UI based on our meeting with Jesse, then @taisdesouzalessa can update the InVision prototype (mostly removing the sub-pages).

**Comment by kristinashu** [comment]
Added visual IA to this ticket https://redpen.io/nwef7202a9fbd86f1a since it helps to look at the overall flow.

**Comment by kristinashu** [comment]
Do you think this is good to close? Although things have been updated, I think it gave us a good idea or what to expect.
