### ISSUE TITLE
add email validation to the petition email field

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#1629]
Right now, "cake" is an acceptable email address. And that doesn't even make sense!

**Comment by desiree-mofo** [comment]
Has this fix been applied to staging? I tested this today (Jul 01) and it's still accepting invalid email addresses

**Comment by desiree-mofo** [comment]
@alanmoo  - do you know what the hold up is on getting this issue resolved? I believe the code fix was being worked on by @Pomax as of Tues, but he's out today and I need some progress on this as it's the final issue holding up Flash at the moment.
