### ISSUE TITLE
Design pass of migrated campaign

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1635]
I moved https://www.iheartopendata.org/ to a Foundation site campaign page (only visible when logged in) at https://foundation.mozilla.org/campaigns/i-heart-open-data/. Can a designer give it a pass and maybe put in a better graphic cropping than the one that I used? Not a huge rush, this is waiting on some other work to be wrapped up before we move it over and probably getting very little (if any) traffic these days.

**Comment by kristinashu** [comment]
Love the consolidating and unifying! I've updated the image and clicked "save draft" but it don't look updated. Is this the image you see now?

<img width="900" alt="open-data" src="https://user-images.githubusercontent.com/1068783/42062314-142f75dc-7ae2-11e8-9458-f70f2eb05edd.png">

**Comment by alanmoo** [comment]
Nope, I had to click "publish". Now it's there.
