### ISSUE TITLE
Implement Initiatives page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1648]
Based on design in https://github.com/mozilla/foundation.mozilla.org/issues/1605
Comps https://redpen.io/p/er1b89aec9ac7facb2

Hero banner
- image, title, body
- rarely edited

Sub nav
- use [current style](https://foundation.mozilla.org/about/) for now (update can be done later https://github.com/mozilla/foundation.mozilla.org/issues/1156)
- add external link icon
- links: [MozFest](https://mozillafestival.org/), [Fellowship](http://foundation.mozilla.org/fellowships/), [Internet Health Report](https://mzl.la/ihr), [Advocacy](https://advocacy.mozilla.org/)

4 themes
- each has image, title, body, button with external link icon 
- rarely edited
- [animated transition similar to this example](http://werkstatt.fuelthemes.net/werkstatt-fullscreen-split/)

Featured programs
- title + intro text (sometime edited)
- 3-6 cards (sometimes edited) (same as home page Happening Now cards but 3-up instead of 2-up)
- 3-6 mini cards (sometimes edited)

### Comps
![initiatives ui 2x](https://user-images.githubusercontent.com/20977376/42648876-127d5606-85d6-11e8-821e-213d45b7eef7.jpg)

**Comment by kristinashu** [comment]
Gavin has done all the P1's for Initiatives.

Opened up a new ticket for P2's https://github.com/mozilla/foundation.mozilla.org/issues/1718 and a separate ticket for Participate page https://github.com/mozilla/foundation.mozilla.org/issues/1717

**Comment by kristinashu** [comment]
@gvn please close this ticket if that all sounds good to you

**Comment by gvn** [comment]
I'm going to leave it open until we get it landed, but yeah...should be soon 🤞

**Comment by gvn** [comment]
Landed! https://foundation.mozilla.org/initiatives/

![jenga](https://user-images.githubusercontent.com/206379/43728817-16c9e826-995b-11e8-9c94-27a21b336d4d.gif)
