### ISSUE TITLE
Emojis are italicized in 'Quote' component

### ISSUE THREAD

**Issue by acabunoc** [mozilla/foundation.mozilla.org#1657]
<img width="706" alt="screen shot 2018-07-05 at 3 55 33 pm" src="https://user-images.githubusercontent.com/617994/42344952-eab0ce56-806b-11e8-8932-9535580c6af8.png">

If I put an emoji in a Quote component in Wagtail, the emoji is italicized. Current workaround is deleting the emoji.

**Comment by Rupeshiya** [comment]
Hi @acabunoc  I new to mozilla but wants to contribute .I would love to give it a try.
should I delete this emoji ??

**Comment by kristinashu** [comment]
I think this is because we aren't using the true italic, we should use the real zilla italics.

**Comment by mmmavis** [comment]
Verified on Google Font.

<img width="675" alt="image" src="https://user-images.githubusercontent.com/2896608/57048723-02a05900-6c2a-11e9-8dff-3d70ef2132bd.png">

Looks like emojis do get italicized by default. I know there are ways we can alter this behaviour just for emojis but it's probably not gonna be a clean fix. 😬

**Comment by kristinashu** [comment]
Thanks for looking into it Mavis! Given that we have 117 issues in this repo I don't think we'll ever get to prioritize this one. Closing as a "won't fix", sorry!
