### ISSUE TITLE
Footer updates from legal

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1662]
Abigail has reviewed our footer and has requested we update:
- "Legal" link should point to https://www.mozilla.org/en-US/about/legal/terms/mozilla/
- fix the CC license; it needs some additional language [need final copy from Abigail but something like "Portions of this content are ©1998–2018 by individual mozilla.org contributors. Content available under a [Creative Commons license](https://www.mozilla.org/en-US/foundation/licensing/website-content/)."]

**Comment by kristinashu** [comment]
Matthew to update and assign ticket once we get final copy from Abigail.

**Comment by kristinashu** [comment]
Abigail says MoCo is planning some changes to how they describe CC in their footer. She's hoping to make this consistent and will keep us posted.

**Comment by kristinashu** [comment]
MoCo is taking too long so Abigail has recommended"

1) Create a new page that will say (this will be a cms page)

<<
Unless otherwise indicated, Mozilla owns the copyright to the original text content on this site and makes that available to you under a Creative Commons Attribution 4.0 license, or any later version. If you are unsure whether certain content on the site is included in this license, please write us and ask.

For more information about Mozilla licensing policies, including code licenses, visit our [Licensing Policies](https://www.mozilla.org/en-US/foundation/licensing/) page.
>>

2) Update the "License" link in the footer so it links to that new page

**Comment by mmmavis** [comment]
@kristinashu new footer is live now! Is the todo here just to update the **legal** link to https://www.mozilla.org/en-US/about/legal/terms/mozilla/ ?

**Comment by kristinashu** [comment]
Nothing for dev to do right now. I should follow up with Abigail again first.
