### ISSUE TITLE
Design banner section to replace green/blue gradient

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1663]
Now that Initiatives and About Us pages have a new look and feel, we need to update all the green/blue gradient banners to match (Internet Health, People, News, Fellowships). 

See visual IA for reference https://redpen.io/nwef7202a9fbd86f1a

**Comment by kristinashu** [comment]
@natalieworth do you have any thoughts for this? Nothing final just a general approach. I've updated the visual IA so you can see all the pages together https://redpen.io/nwef7202a9fbd86f1a

![visual-ia2 2x](https://user-images.githubusercontent.com/1068783/43666126-66c68d7e-9727-11e8-9f72-1515b34469e6.jpg)

**Comment by natalieworth** [comment]
@kristinashu Yep! Working on header options to replace what we have right now. I'll post in redpen on Monday.

**Comment by kristinashu** [comment]
We would also like an "interim" solution where we can just swap out all the gradients (Internet Health, People, About Us, News, Fellowships), with one new illustration.

**Comment by kristinashu** [comment]
These are for Jesse's interim updates https://github.com/mozilla/foundation.mozilla.org/issues/1727 to make the rest of the site fit in with the new Initiatives pages.

Just updating the banner doesn't work because the gradient in the sub nav clashes.

![single page copy](https://user-images.githubusercontent.com/1068783/43985093-a5eb5dda-9cb9-11e8-87b2-46bdf468a9ca.jpg)

So we recommend the primary and secondary nav updates get done at the same time as the banner updates. 

![single page copy 2](https://user-images.githubusercontent.com/1068783/43985092-a5d47980-9cb9-11e8-81fb-b8e30cb7aea0.jpg)

**Comment by kristinashu** [comment]
Implementation of this is happening here now - Banner Update: Replace green/blue banner #2298 
and design to - Integrate black/white banner onto Participate page #2275
