### ISSUE TITLE
[Optimization Opportunity] Donors (who can't donate anymore) e-mail

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1665]
Description: after All Hands (June 2018), Stephanie L. and I met to discuss cross team collaboration opportunities. The donors email was one of the topics of our chat and I think there is a nice opportunity for collaboration here once we have the new Participate page up.

Here is the opportunity in details: https://docs.google.com/presentation/d/1kGpdQnoFv6KabZscm7-lxMoJbE7os9wp_j5JWPl8Ae8/edit?usp=sharing

@xmatthewx @jessevondoom let me know your thoughts on it? We could team up with Stephanie and her team on this task and measure results.

**Comment by xmatthewx** [comment]
Perfect. Thanks @taisdesouzalessa. It does seem like there's an easy boost we can do by swapping out youtube and swapping in the foundation site in the body of the message. 

It would be good to know the scale and timing of those messages. If the group is big enough (it might not be) we could test a generic message (follow our work at fo.mo.org) vs a get involved message (linking to participate).

**Comment by taisdesouzalessa** [comment]
Yep, good idea on splitting the message. I'll ask Stephanie about the scale and timing of them. 

I agree with you that it seems like a low hanging fruit, we have to make sure our analytics are in place to track this test.

**Comment by taisdesouzalessa** [comment]
Asked Stephanie via e-mail, she shared my e-mail with Will, since he may ave the numbers. Didn't hear back from him yet.

**Comment by taisdesouzalessa** [comment]
@WillatMozFdn we were wondering about the scale and timing of emails your team receives, more specifically, when a donor can no longer donate and when we have a fundraising appeal email and they say they can't donate. 

The reason why we're asking this is if the volume is big enough, we could do a test and send different links to each group (to invite them to participate in non-monetary ways). If the volume is small, this type of test isn't possible. 

Would you have those numbers, by any chance? It would be good to see them separated so we know which one occurs more frequently.

**Comment by WillatMozFdn** [comment]
Hey Tais, thanks for re-pinging me, as I'm still digging out from PTO.  :-)  So ... ballpark estimate, scale is probably around 30-40 per campaign, and we usually run one fundraising campaign per month, so call it 400 to 500 annually.  That's a pretty small number to run a test and hope for any real significance ... and also unfortunately we have zero capabilities for testing in the platform we use, which is desk.com. 

HOWEVER, I would be more than happy to edit that macro (the stock template we use to reply to those cases, with the twitter & youtube links) and add whatever you want!  Pretty easy to do from my end and will make that response a lot better.

Maybe add something like, "There are also a lot of ways you can participate in Mozilla's programs here on our website -- <link> -- so we hope you'll get involved!"

That's just off the top of my head but I think you get the general direction I'm going with that?  Let me know, and have a good weekend!!

**Comment by taisdesouzalessa** [comment]
Hey @WillatMozFdn, thank you so much for your feedback and suggestion. Super valuable to us! I'll bring the macro update idea to Matthew and Jesse to gather their views, since they are the ones who hold the long term strategy vision for the site. Then I'll get back to you with some suggestions, does that work?

I think editing the macro would be a great way to bring some of this traffic to our site. I'll connect with them and keep you posted.

**Comment by taisdesouzalessa** [comment]
After talking to @Sydette, she wrote a copy for this email and it can be found here: https://docs.google.com/document/d/1f-ZFUCZaIGepCcbFIx_sRPAT2mUuiTToO8Ufsbw1gcw/edit?usp=sharing - it would be good to get feedback from you all: @xmatthewx @WillatMozFdn @jessevondoom and probably Stephanie L. as well? I don't know her GitHub handle... You can tag Sydette on Google Doc to ask for tweaks. Thanks, team! We are almost there :).

**Comment by Pomax** [comment]
@alanmoo @xmatthewx what would be the next steps for this issue to move forward (or get closed?)

**Comment by xmatthewx** [comment]
I think it's @WillatMozFdn's call on if and how to move forward. Glad to lend a hand if needed, but otherwise work on our end is done as far as I can tell.
