### ISSUE TITLE
mozillafoundation.org forwards to mozilla.org subpage

### ISSUE THREAD

**Issue by gvn** [mozilla/foundation.mozilla.org#1667]
Right now https://www.mozillafoundation.org/ forwards to https://www.mozilla.org/en-US/foundation/

That seems odd. Shouldn't it forward to https://foundation.mozilla.org ?

CC: @jessevondoom

**Comment by alanmoo** [comment]
It should indeed. If we forward mozilla.org/foundation, it should take care of this in one fell swoop. I think we're ready to do this, @jessevondoom?

**Comment by kristinashu** [comment]
Yay! Now everything forwards to https://foundation.mozilla.org/
