### ISSUE TITLE
[Wagtail] Checkbox too close to helper text

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1670]
_Assigning @alanmoo for triage._

### Issue:
The checkbox in Wagtail has little vertical distance from the text below it, making it hard to read the helper text.

<img width="478" alt="image" src="https://user-images.githubusercontent.com/22157921/42540716-7cbaf2a4-8454-11e8-94da-828e5a5ab80c.png">
<img width="555" alt="image" src="https://user-images.githubusercontent.com/22157921/42540757-91ff7914-8454-11e8-8853-769be3b9430c.png">

**Comment by alanmoo** [comment]
Can you share a link to where the screenshot is from?

**Comment by taisdesouzalessa** [comment]
That would be useful, hey? Sorry for not posting it before. Here it is:

CMS view link: https://foundation.mozilla.org/cms/pages/33/edit/
Live page: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/

The same problem happens in the updated Pulse component that will be implemented (screenshot number 1 in the ticket). I am not sure the updated component has been pushed to prod yet.

**Comment by alanmoo** [comment]
This is only visible in Firefox (not Safari or Chrome), and it's not code that is written by us. See if it's still present once we upgrade to Wagtail 2.1; if so then it might be worth filing a bug in the Wagtail repo, though it could also be a Firefox bug. But as it stands, this isn't a thing we should be tracking down.
