### ISSUE TITLE
Share Progress setup info and transition to how-to page

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/foundation.mozilla.org#1671]
We use share progress for social content management and AB testing share messages.

1. Go to https://www.shareprogress.org/
2. Go auth credentials from one password.
3. Click "Share Buttons". These are all the buttons we've created, three for each campaign, 1 for facebook, twitter and email.
4. You need to either create a new one, or copy existing ones and change it.
5. Click edit on the buttons and update the fields for the button or clear them in the case of a copy and content to be added later.
6. There should be a six digit id for each button preceded with "sp_". You can get it from the info button for each button, but also get it from the url while editing the button, just make sure if you get it from the url add "sp_" to it, example "sp_189307"
7. Added these buttons to the wagtail edit page for the petition widget.

**Comment by alanmoo** [comment]
Moved to [documentation](https://foundation.mozilla.org/docs/how-do-i-wagtail/petitions/)
