### ISSUE TITLE
Populate staging (and review apps) with test Salesforce campaigns

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1684]
We need to be able to easily test functionality for petitions, so having a sandbox Salesforce campaign ID automatically populated for staging and review apps would be exceptionally helpful.

(We may be able to get around this for review apps if it's a problem with an environmental variable and some logic to automatically accept form submissions in development environments)

**Comment by alanmoo** [comment]
I'm not sure. @stephaniemcv @desiree-mofo?

**Comment by cadecairos** [comment]
@stephaniemcv / @desiree-mofo does that campaign ID need to be kept secret?

**Comment by cadecairos** [comment]
@stephaniemcv ping?

**Comment by desiree-mofo** [comment]
@cadecairos  - I don't think it does b/c no one can see any details unless they authenticate via Salesforce.com. I'll double check with Andrew, but my thought is no b/c it doesn't reveal PII (It's a campaign, not a person), even if they were to get that ID - there's no Personally Identifiable info there - they'd have to get to another object to get any PII

**Comment by desiree-mofo** [comment]
....and if this is just a Campaign ID for a Salesforce sandbox, I really don't think it's an issue. However, that ID will change / get erased when a Sandbox is refreshed (all data is wiped on a refresh), so it would need to be set up after every Salesforce sandbox refresh, but we can account for that in the refresh process

**Comment by desiree-mofo** [comment]
Spoke to Andrew, if it's not too much trouble to mask the value, please do. Also, would the value be de-crypted (unmasked) in Basket (before it gets to SFDC?

**Comment by cadecairos** [comment]
@desiree-mofo we'll be able to add the campaign ID to the servers without committing it to code. When sending to basket, the ID will be enctrypted at the transport layer ( SSL/TLS)

**Comment by cadecairos** [comment]
@alanmoo correct me if I'm wrong, but it sounds like we need to do this:

1. Add the campaign ID as and environment variable
2. when generating petitions, use that variable as the campaign ID when creating petition instances.

**Comment by alanmoo** [comment]
Assuming you're talking about for fake data generation, yes. And we'll need to update that campaign ID at the same frequency as the Sandbox refresh?

**Comment by alanmoo** [comment]
@cadecairos Is this actually the right approach to test petitions?

**Comment by cadecairos** [comment]
If we can throw together a test for this that doesn't require manual work that would be great. I'm not sure that we really need to test the full integration with basket and SF, just that a given input on our end produces an expected output to SQS. 

If we could mock an SQS endpoint and just check the payload it gets that would be cool, however I'm not sure how simple that would be with boto3. (A simple search should reveal if boto3 can be tested)

**Comment by alanmoo** [comment]
I think the right approach here to move towards directly posting to basket and then monitoring responses with Sentry.
