### ISSUE TITLE
Consider a /resources/ route for CMS authored pages

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1686]
In NYC, MoFo did a project with the Mayor's Office and [RAD](https://rad.cat/) that produced a bunch of resources on security and data practices for organizations working with immigrants in sanctuary cities.  Good stuff. 

The group will add their resources to Pulse and author a few pages to introduce them on the site. We _could_ put these pages under /opportunities/ but I think /resources/ makes more sense for durable assets like these.  

Can we set up that route? Any reason to not do that @alanmoo?

cc @kristinashu @jessevondoom

**Comment by alanmoo** [comment]
Jesse says let's do this under "initiatives"

**Comment by xmatthewx** [comment]
👍 okay dokes. closing.
