### ISSUE TITLE
Local python linting is too broad

### ISSUE THREAD

**Issue by gvn** [mozilla/foundation.mozilla.org#1688]
When I run `inv test` locally it's also linting all the libraries as well, which is very slow and returns tons of unfixable issues.

We should exclude 3rd party libs and only lint our own python code.

**Comment by prabhupant** [comment]
@gvn I'd like to work on this. Please assign it to me

**Comment by gvn** [comment]
@prabhupant I can't assign to you but I can label this to indicate you're working on it. Thanks!

**Comment by Pomax** [comment]
at some point this got fixed and we forgot to close this
