### ISSUE TITLE
Get a copy of all the news-model associated "glyph" images

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#1693]
We're going to try to reboot the "glyph" functionality, which is currently broke, for which it would be good to not have to reinvent graphics for everything we've already glyph'd in the past - @cadecairos. would you be able to pack up all the glyphs associated with the `news` model from S3 so we can figure out a good place to put them? Most of these I would imagine could simply be static assets, but if not, having them available for "reuploading" will be super useful.

**Comment by cadecairos** [comment]
> pack up all the glyphs

Did you mean backup?

**Comment by cadecairos** [comment]
@Pomax did we still need something here?

**Comment by kristinashu** [comment]
News glyphs have proven to be unrealistic to maintain and so we are no longer using them. Closing this ticket but please re-open if needed.
