### ISSUE TITLE
[Design QA] Fundraising modal after petition signing

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1694]
- [x] 1. **Importance: high** - please increase size of the "X" button. I tried it using the inspector and the following works well (`font size: 2.5rem`; `font-weight:normal` - important: this style should apply for this modal only, if there is any other existent modal we should take a look at it first to make sure it doesn't break past modals):
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/22157921/43228857-a5b95fbe-9017-11e8-980f-e28d3d1050ed.png">

- [x] 2. **Importance: high** -  if the screen is smaller than the size of the modal, the background content is scrolling instead of the modal, which doesn't allow users to access the CTA. Tested on iPhone 6 (landscape) and on desktop (responsive design mode):
![pop-up-issue](https://user-images.githubusercontent.com/22157921/43229123-85f9a49e-9018-11e8-8544-0621e8609a5e.gif)

- [x] 3. **Importance: high** - when screen is bigger than modal and we scroll, the modal scrolls as expected but once it reaches the end of it, the background keeps scrolling and the white overlay behind the modal gets cut (tested on iPhone 6 - portrait):
![pop-up-issue-2](https://user-images.githubusercontent.com/22157921/43229415-844e864a-9019-11e8-8424-a95a4a44a101.gif)

- [ ] ~~4. **Importance: high** - if I click on "No, I'll share instead", I go back to the form view instead of seeing "share" buttons.~~
UPDATE: those will be seen once page is out of herokuapp

![share-issue](https://user-images.githubusercontent.com/22157921/43291933-3dffe042-90e8-11e8-9917-701865d7abb0.gif)

- [ ] 5. **Importance: medium** - could we make the tap area on mobile at least 44x44px?  The "X" has the same specs as on desktop in terms of dimensions but it would be good to have the tap area bigger so people have an easier time closing the modal if desired.
<img width="68" alt="image" src="https://user-images.githubusercontent.com/22157921/43229021-302d0984-9018-11e8-980a-9901011bdafd.png">

- [ ] 6. **Importance: medium** - please make the "X" closer to the right border (use the same distance as it has from the top border).
<img width="360" alt="image" src="https://user-images.githubusercontent.com/22157921/43229665-74a2f86a-901a-11e8-8e90-88c2904914a0.png">

**Comment by Pomax** [comment]
@alanmoo @taisdesouzalessa is this still a thing we want to focus on?

**Comment by Pomax** [comment]
correction: this landed =)
