### ISSUE TITLE
[Wagtail] User Documentation Updates

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1698]
The [Wagtail User Documentation](https://foundation.mozilla.org/docs/how-do-i-wagtail/petitions/) needs to be updated once in a while to reflect changes we do in the platform.

In order to make it easier for us, I created a [spreasheet](https://docs.google.com/spreadsheets/d/1Ur-yCNkblxAuK9p5NjfITHbd1HxFvAKYL0dZ-qQymOE/edit?usp=sharing) where you can see the name of the different sections and the date they were last updated.

Also, there is [a doc](https://docs.google.com/document/d/1s1hO1e0uYKTv4x-n1U7i6koMc_etRvGHDACIGF9Tmm8/edit?usp=sharing) with all content in one place in case you need to do a quick scan of the posted info without having to click on individual pages. You can quickly search a keyword to see if the section you are about to create already exists in some part of the current page. Besides that, you can propose changes to the copy and tag people to discuss it before publishing the changes live in the public facing page.

Please update those 2 docs once you update the "How do I Wagtail" page so we have living docs that can grow with our live page. Also, let me know if you have any suggestions to make those updates easy to do :). 

cc: @alanmoo @xmatthewx @sabrinang @Pomax

**Comment by cadecairos** [comment]
@taisdesouzalessa this feels like more of a process, since issues are meant to be closed. Would addressing this during sprint retros/planning be better?

**Comment by taisdesouzalessa** [comment]
Agree, those sessions seem a better place to discuss this topic. Thanks, Cade! 
Closing.

**Comment by xmatthewx** [comment]
I'd also add... if we duplicate content on the site in separate docs, there's extra work to keep them in sync. If wagtail doesn't make it easy enough to organize and maintain the content, then we should talk about why. For example, if we need a spreadsheet to see it all, maybe we need a better table of contents or search feature for users. If we need a spreadsheet to track status of each page, maybe we need a way to show status or last updated at the top of each page.

**Comment by xmatthewx** [comment]
And yes. I'd like to approach this as a process connected to office hours to support staff, rather than periodically as a project that fells like a p.i.t.a. or falls by the wayside.
