### ISSUE TITLE
Add Events to better understand post campaign actions

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1700]
The foundation site receives huge bursts of traffic around our campaigns. Following a campaign, a small percentage of visitors continues their visit on other parts of the site. 

This fall, we aim to increase the percent of people who are activated beyond the campaign to engage with our news and other programs. One way to achieve this is to optimize the page footer below the campaign:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/53411/43414351-7f6f8012-9400-11e8-8884-eeacbd847b55.png">

This link goes to the homepage, but we don't have an event attached, so we can distinguish it from the logo link in the header or footer. Let's add an event here. 

@alanmoo can you help triage? cc @taisdesouzalessa

**Comment by xmatthewx** [comment]
I've proposed strings for category, action, and label on line 24 of this [spreadsheet](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=779058050).

**Comment by alanmoo** [comment]
@mmmavis This would probably be good for you when you have a break from Mozfest stuff.

**Comment by mmmavis** [comment]
@xmatthewx by "event" did you mean GA event?

**Comment by gvn** [comment]
Isn't this functionality already in stock GA? EG: seeing what links are clicked and referring pages for page views? I don't think this should require custom events...

**Comment by mmmavis** [comment]
I don't know much about GA and how Foundation site is set up with GA. @xmatthewx can you advice? Is a custom event needed or the GA dashboard has features for us to explore that information already?

**Comment by xmatthewx** [comment]
GA only tracks URL flow by default. Using a query parameter would add info on a user's pathway, but it would clutter our dashboards and complicate all our other views, by splitting aggregate activity and behavior. GA use to have an overlay view, but that still didn't distinguish links to the same URL. 

This event will help us understand visits to our most highly trafficked pages.  We can test copy/image changes and learn how to better engage and retain visitors. It'll be very valuable to have a window it this.

**Comment by mmmavis** [comment]
Pushed live and verified it's working.
