### ISSUE TITLE
Move Mozilla Awards Web Page from Opportunity to Initiatives

### ISSUE THREAD

**Issue by annmarie123** [mozilla/foundation.mozilla.org#1702]
Hi there,

Is someone able to move the Mozilla Awards page to the Initiatives page?

https://foundation.mofostaging.net/opportunity/awards/

**Comment by taisdesouzalessa** [comment]
^ @xmatthewx @alanmoo

**Comment by alanmoo** [comment]
You want this to be a child of the Initiatives page? So it's at https://foundation.mozilla.org/initiatives/awards?

**Comment by alanmoo** [comment]
Also: Staging is a test database and gets reset every Monday. If you're building a page that's intended to go live, it should happen on the live site, foundation.mozilla.org/cms. You can set the visibility of pages to be only available to logged in users if it's not ready to go live yet.

**Comment by xmatthewx** [comment]
cc @kristinashu for IA awareness

**Comment by kristinashu** [comment]
It is now a primary page http://foundation.mozilla.org/awards/ 🎉
