### ISSUE TITLE
Improve dev workflow for fake data generation

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1708]
Right now the fake data script needs to be edited each time a new model needs to be mocked. It feels a bit clunky. It would be great if there was a way of doing this automatically if a certain file exists in an app's directory or something like that.

**Comment by cadecairos** [comment]
I'm waiting on some ongoing work that Gavin is doing to land so I can refactor the wagtailpages models file. Doing that will make refactoring the load_fake_data logic actually worthwhile.

**Comment by Pomax** [comment]
We landed this. It's pretty great!

**Comment by cadecairos** [comment]
> We landed this. It's pretty great!

actually, we did not! 

https://github.com/mozilla/foundation.mozilla.org/pull/2376

I have some outstanding work to do, and probably a painful rebase. but that's my fault.
