### ISSUE TITLE
Update secondary nav on foundation.mozilla.org

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#1710]
Starting this ticket here for the work of updating the secondary nav across foundation.mozilla.org.
We will need to affirm what style we are evolving to across the entire site and what are its use cases.
## Current sub nav:
<img width="1143" alt="screen shot 2018-08-02 at 10 14 52 am" src="https://user-images.githubusercontent.com/20977376/43589551-f93bf842-963c-11e8-9c42-816c107e99b6.png">

## Proposed evolved sub nav:

![screen shot 2018-08-02 at 10 17 04 am](https://user-images.githubusercontent.com/20977376/43589689-3d9650a0-963d-11e8-9d33-d1d92f63ed7a.png)

We also want to add an external link icon when the link leads to an external site:
<img width="754" alt="screen shot 2018-08-02 at 12 08 21 pm" src="https://user-images.githubusercontent.com/20977376/43596270-d205692e-964c-11e8-9601-0bf37d68b8a2.png">

## Sidebar sub nav:

Also we should clarify the use case for this side bar sub nav and should we align it more to the evolved sub nav:
![screen shot 2018-08-02 at 10 28 39 am](https://user-images.githubusercontent.com/20977376/43590377-db1f1266-963e-11e8-8552-ef5709b88dac.png)
CC: @kristinashu @natalieworth @gvn @jessevondoom

**Comment by kristinashu** [comment]
This is followup from design work done in https://github.com/mozilla/foundation.mozilla.org/issues/1156

I'm going to un-assign Gvn for now while designers finalize specs and while he finished off Initiatives, Participate, and About Us pages...

**Comment by kristinashu** [comment]
@beccaklam can we close this ticket and use https://github.com/mozilla/foundation.mozilla.org/issues/1721 for implementing the nav updates?

**Comment by beccaklam** [comment]
@kristinashu Yup, no problem at all!
