### ISSUE TITLE
Initiatives page QA: Secondary nav

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1714]
I noticed on staging that the initiatives page navigation made it look like the user is on a page for Mozfest:

<img width="852" alt="image" src="https://user-images.githubusercontent.com/1682681/43592331-51a9d840-9643-11e8-89d8-e56942ee0cd8.png">

I'm not sure what the right styling is here, but I'm sure this can't be it.

@beccaklam @taisdesouzalessa @kristinashu can one of you clarify what's expected?

**Comment by kristinashu** [comment]
Good catch, I think this is a vestigial structure from when we were going to have one long scrolling page with a sticky nav.

For this functionality, we should add a link before MozFest that says "Overview" (Overview should have the selected when a user is on /initiatives).

**Comment by beccaklam** [comment]
Correct, sorry for missing this @gvn 
All the links should be greyed out or better yet they should be all black. But I know there's some type of bug right now with the nav where unselected links are greyed out, correct?
<img width="695" alt="screen shot 2018-08-02 at 12 37 42 pm" src="https://user-images.githubusercontent.com/20977376/43597705-e3a44a5c-9650-11e8-80fb-9ee59a1ad443.png">
We also don't want an empty drop down box when we view the site on mobile. The first selection should be a greyed out link or black link, consistent with what we've chosen for desktop:
<img width="306" alt="screen shot 2018-08-02 at 12 36 20 pm" src="https://user-images.githubusercontent.com/20977376/43597648-b27a535e-9650-11e8-8074-59ade5014b9a.png">

**Comment by kristinashu** [comment]
I'm definitely probably missing something but for now, styling for this nav can probably be the same as our current [About Us](https://foundation.mozilla.org/about/) pages?

**Comment by gvn** [comment]
Yes, I'm using that existing nav style and we'll do a follow up to unify all the secondary navs to a single style once Design has determined what that is.

**Comment by gvn** [comment]
@kristinashu I think adding "Overview" is a little odd because it breaks the convention of the nav. What would it link to? The current page that you're already on?

**Comment by kristinashu** [comment]
It would be like on the About Us http://foundation.mozilla.org/about/ page or the Opportunity pages https://foundation.mozilla.org/opportunity/global-sprint/ Is that weird? I think it's useful to see a selected state to help indicate to users that they can click a different one.

**Comment by kristinashu** [comment]
Sorry, scratch that. It's good as is!

**Comment by kristinashu** [comment]
@gvn the only issue with doing it this way will be on mobile. It looks like "Advocacy" is selected when a user is on /initiatives

<img width="430" alt="image" src="https://user-images.githubusercontent.com/1068783/43607820-35d99626-9654-11e8-9760-63d5bdd14479.png">

So for mobile only, could we show "Initiatives" or "Overview" as the selected state in the dropdown? Or do you have any other recommendations?

**Comment by gvn** [comment]
I started with an empty nav, but I believe that got flagged in design review. That's what I'd suggest going with though until we settle on a new unified secondary nav component/style.

Putting a placeholder selected state is going to take some hacking of the current component. It's possible, but if we can avoid it that'd be nice.

**Comment by gvn** [comment]
Based on Slack convo: We'll go with https://github.com/mozilla/foundation.mozilla.org/issues/1714#issuecomment-409989862

**Comment by gvn** [comment]
All fixes in #1712
