### ISSUE TITLE
Initiatives page: Design Tweaks

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#1715]
Hi @gvn 

## Spacing
Since there's time and space, could we change the initiatives paragraph div styling to:

- [x] div class="col-12 col-md-5 col-lg-4 px-3 py-3 px-md-0 ml-lg-4 align-self-center"

and the image div to:

- [x] div class="col-12 col-md-5 offset-md-1"

## Resolution

- [x] resolution also looks a bit low with nat's new image, we should test to see if it's the images or the resolution on the site itself

~~## Header

- [ ] Is there a way we can get the header not to crop?

We can also chat about this over vidyo just to make sure it looks right before pushing the commit.~~

**Comment by gvn** [comment]
> resolution also looks a bit low with nat's new image, we should test to see if it's the images or the resolution on the site itself

Resolution for the header hero is 2400x700 and initiatives are 1600x1600. Sounds like an issue with the image itself.

> Is there a way we can get the header not to crop?

I went through a bunch of options and the way I have it set up felt best. If we don't want a vertical crop then we will either have whitespace on the sides or need to add repeating patterns to the sides, which is pretty complex (exacerbated by the fact that it's managed via CMS).

**Comment by beccaklam** [comment]
@gvn Actually on staging the resolution appears fixed now. So whatever you did worked. 
As for the header that was the lowest priority so we can ship what we have for now.

**Comment by beccaklam** [comment]
Moved the header issue to #1718 as P2. Marking this ticket as done and closing.
