### ISSUE TITLE
Remove staging info from wagtail author documentation

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1716]
Our current wagtail docs on the foundation site invite authors to play around with the cms on staging. while that seemed like a good idea initially, it has proven to be confusing and not very valuable. it's easy to test drafts on the production site, with very little risk. content on staging vanishes every week - authors risk loosing drafts thinking they can promote them from staging to production. 

Let's remove the staging info from our user docs.

**Comment by taisdesouzalessa** [comment]
That is a good idea. I wonder if currently the value of staging is for prod team only? So we can see changes and catch bugs before they go to production site. I wonder if there are any value to staff in staging that I am not seeing...just curious so I could add it to the doc as well if there is any.

**Comment by xmatthewx** [comment]
Perfect. Thanks!
