### ISSUE TITLE
Implement Participate page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1717]
Based on design in https://github.com/mozilla/foundation.mozilla.org/issues/1605
Comps https://redpen.io/p/er1b89aec9ac7facb2

Hero banner 
- image, title, body, time, button url
- often edited

Featured 
- title + intro text (sometimes edited)
- 3 cards (often edited) (same as home page Happening Now cards but 3-up instead of 2-up and with a time note)
- share feature to be done later

Full width CTA
- sometimes edited
- image, title, body, time, button CTA
- exception: in the share CTA has the ghost button is replaced with share buttons

Large feature card
- sometimes edited
- 1-4 cards (ex mozfest, fellowships)
- each card: image, title, body, time, button url

Pulse participate component (P2)
- separate design ticket #1641
- implementation ticket  #1731 <- _edit made by Taís_

Participation Wins (P2)
- separate ticket #1722
- implementation ticket #1732 <- _edit made by Taís_

### Participate UI Large

![participate large 2x](https://user-images.githubusercontent.com/20977376/43802466-dac3f556-9a63-11e8-8aee-2c7b5e11d06f.jpg)

### Participate UI Medium

![participate medium 2x](https://user-images.githubusercontent.com/20977376/43802460-d6c8cb98-9a63-11e8-8848-23e6f0c96089.jpg)

### Participate UI Small

![paritcipate small 2x](https://user-images.githubusercontent.com/20977376/43802474-e1a1e9a0-9a63-11e8-8e7e-9cde4d1e7fa5.jpg)

cc @beccaklam

**Comment by taisdesouzalessa** [comment]
Just a heads up here: Pulse + Participation Wins layout will change on mobile. We had decided to replace the image squares (keeping the Pulse Cards proportions instead, so there won't be a need to crop in mobile). Also, the items in the list on Pulse will need more space in between them for mobile since tapping area requires at least 44px height. I am currently working on those changes for those 2 sections and after I am done, I'll send it to @beccaklam to double check it since she worked on the rest of the UI.

**Comment by taisdesouzalessa** [comment]
@kristinashu I edited the original ticket here, adding "- ticket #1722" on the Participation Wins section okay? There was a change I did that for the mobile mode to replace the square pictures with our default 16:9.

**Comment by beccaklam** [comment]
@kristinashu @gvn @taisdesouzalessa Just realized I need to update the spacing to reflect bootstrap's system. I've already done mobile, just need to update tablet and desktop. I should have that done by end of my day today.

**Comment by gvn** [comment]
> exception: in the share CTA has the ghost button is replaced with share buttons

@kristinashu Is this P1? What do the buttons do exactly? Also, why is there a Facebook share if we're not supporting Facebook at this time?

**Comment by beccaklam** [comment]
@kristinashu @gvn @taisdesouzalessa spacing issues fixed and updated in abstract

**Comment by kristinashu** [comment]
Checked in with Nat and decided on these specs for the banner cta illustrations:

<img width="1234" alt="screen shot 2018-08-07 at 2 33 32 pm" src="https://user-images.githubusercontent.com/1068783/43803905-05d71a76-9a4f-11e8-8f63-01b95455bb40.png">

So using this placeholder image, it would look like this:

<img width="1218" alt="screen shot 2018-08-07 at 2 30 22 pm" src="https://user-images.githubusercontent.com/1068783/43803904-05c3f310-9a4f-11e8-8ae7-2354448c372f.png">

I will update Abstract and the other screen widths.

**Comment by kristinashu** [comment]
I've uploaded all the images for the cards and hero banner to the prod cms so they should be on both prod and staging on Monday.

**Comment by gvn** [comment]
Closing with #1766 and #1749 as follow up tickets.
