### ISSUE TITLE
Initiatives page: animate transition

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1718]
Follow up from https://github.com/mozilla/foundation.mozilla.org/issues/1648
Based on design in https://github.com/mozilla/foundation.mozilla.org/issues/1605
Old comps https://redpen.io/p/er1b89aec9ac7facb2
Page: https://foundation.mozilla.org/en/initiatives/

- [ ] Animated transition similar to [this example](http://werkstatt.fuelthemes.net/werkstatt-fullscreen-split/) for the 4 themes

**Comment by cadecairos** [comment]
Closing this issue due to its age, if this is work that we still want to do, please refile this with up to date information so that it can be put in the correct milestone with up to date estimates.
