### ISSUE TITLE
[Pulse component on Wagtail] People component (Latest profiles + Profile by ID) implementation ticket

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1719]
_Tagging @alanmoo for triage_

Based on discussions from #1544 and #1543, here is the implementation list for the People Component:

### 1. Latest profiles component:
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/22157921/43610391-cf2ef09a-965a-11e8-8b76-8d3e31250224.png">

RedPen: https://redpen.io/bsb834f94cafe4b895

- [ ] Name of the component: `Latest Profiles`
- [ ] Icon of the component: 
<img width="426" alt="image" src="https://user-images.githubusercontent.com/22157921/43610611-75806168-965b-11e8-9c5b-0cb16bba39d7.png">

- [ ] Number of results section - Label: `Max number of results:`, default number: `12`, helper text: `Choose 1-48.`
- [ ] Add `-------- ADVANCED FILTERS: OPTIONS TO DISPLAY FEWER, MORE TARGETED RESULTS. -------- `
- [ ] Profile type section - Label: `Profile type:`,  UPDATE (Aug 21): free text field   ~~Dropdown box with `--` by default, Extended dropdown has the following options, in alphabetical order: `--` (in light grey, since it is the selected option), `Board Member`, `Fellow`, `Grantee`, `Staff`, helper text: `Select an option to list a specific group. Leave blank to not restrict by type.`~~
- [ ] Program type section - Label: `Program type:`, UPDATE (Aug 21): free text field   ~~Dropdown box with `--` by default, Extended dropdown has the following options, in alphabetical order: `--` (in light grey, since it is the selected option), `Media`, `Mozilla Fellow`, `Open News `, `Open Science`, `Open Web`, `Tech Policy`,  helper text: `Select an option to list a specific program. Leave blank to not filter by program.`~~
- [ ] Year section - Label: `Year:`, UPDATE (Aug 21): free text field   ~~Dropdown box with `--` by default, Extended dropdown starts with `--` (in light grey, since it is the selected option) and has all the years available in the Pulse database (currently from 2012-2019, from most recent to oldest)~~

### 2. Profile by ID component:
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/22157921/43610722-cbd25288-965b-11e8-8dd6-0783057e65ff.png">

RedPen: https://redpen.io/dc9f2dff1c286e5c0d

- [ ] Name of the component: `Profile by ID`
- [ ]  Icon of the component:
<img width="401" alt="image" src="https://user-images.githubusercontent.com/22157921/43610829-22b8d27a-965c-11e8-8619-8be868953e3d.png">

- [ ] Label: `Profile by ID:`, Placeholder copy: `Example: 85,405`, helper text: `Find the profile ID at the end of the profile URL: mozillapulse.org/profile/[##]. Add multiple IDs separated by commas.`

### Front end view of the component example:
<img width="635" alt="image" src="https://user-images.githubusercontent.com/22157921/43610975-9f671192-965c-11e8-800a-d9e6bbcf8a78.png">

- [ ]  Same model as in our current “Fellowships Directory” cards. CTA should be `see full profile` and take users to individual Pulse Profiles.

**Comment by alanmoo** [comment]
I just talked to Jesse/Matthew: We're going to keep the Profile Type/Program Type/Year fields as free text fields for now because it's only a few people using it, and not very often. It's not quite worth the probably effort to get that working right.

**Comment by taisdesouzalessa** [comment]
Thanks for the heads up here, Alan! Do you want me to change the comp based on that? or is this in motion already and we don't need it?

**Comment by alanmoo** [comment]
I don't think it needs a comp update.

**Comment by taisdesouzalessa** [comment]
Updated the specs list to reflect comment above.

**Comment by Pomax** [comment]
What is "See full profile" supposed to do?

**Comment by taisdesouzalessa** [comment]
@Pomax "See Full Profile" takes users to the individual Pages on Pulse, so your guess is correct :). For instance, if the person clicks on "See Full Profile" for Alan Davidson, they would see [this page](https://www.mozillapulse.org/profile/335)

**Comment by Pomax** [comment]
Presentation question: what should we show when someone's profile type is "plain"? For example, in the test data that gets generated in my network-pulse-api, not all of the following users have a special role:

![image](https://user-images.githubusercontent.com/177243/45390792-598eea80-b5d5-11e8-9294-7b95981e1162.png)

Should we just show "nothing" where others will have the moz icon and their role/year?

**Comment by alanmoo** [comment]
I would assume so. We should probably have more categories in pulse that get brought in here as ways to describe how people are affiliated with Mozilla, but that's a separate issue.
