### ISSUE TITLE
Initiatives page: header styling fixes

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#1720]
- [ ] Fix header image cropping based on conversation in #1715 The cropping is making the image look too 'blown up'. Possible solution is designers supplying a pattern that can repeat as opposed to a large image.

- [ ] Fix header spacing. The margin around the white box should be equal all around and remain the same on larger screen sizes. Designers to determine what the exact offset width should be. Example of what it should look like on a larger screen size:
<img width="1018" alt="screen shot 2018-08-03 at 7 56 14 am" src="https://user-images.githubusercontent.com/20977376/43641887-51578c24-96f3-11e8-8529-cedf62a833c6.png">

**Comment by kristinashu** [comment]
Closing since design for this is going to change #2275
