### ISSUE TITLE
Implement iterations on nav

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1721]
Based on design in https://github.com/mozilla/foundation.mozilla.org/issues/1156

Comp overview and notes https://redpen.io/vp5721a2a03e94bf21

### Main Nav
- [x] Put nav on white background everywhere: already have this on Home, new Initiatives, Opportunity/Campaign pages but need to add this to the rest of pages (Participate, Internet Health, People, About Us, News, Fellowships) - in #1727
- [x] Update all selected states: increase thickness of the black line to 6px and move it lower down so it is on top of the grey line
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/1068783/43664420-c15a3214-9721-11e8-8e93-b9587dbbec56.png">

### Main Nav Mobile (on hold)
- Update background to white  (alpha .9) and text to black (P2)
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/1068783/43664566-2f0b0874-9722-11e8-987a-3a7446d92518.png">

### Horizontal Sub Nav (primary pages)  - **now in #2297**
- Remove gradient line
- Add light grey line: full width of the page and 16px below text
- Update selected state bar: update yellow bar to a 3px black bar and move bar down so it is vertically centered on grey line
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/1068783/43664619-611c0502-9722-11e8-8b0a-dd733f826516.png">

### Vertical Sub Nav (opportunity pages)  - **now in #2299**
- Update yellow bar to black bar
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/1068783/43664652-7edab598-9722-11e8-8ebf-52e5f082a12a.png">

### Sub Nav on Mobile  - **now in #2297**
- Update dropdown background from solid grey box to grey outline
- Selected state: remove yellow selected state bar (just show text in box)
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/1068783/43665386-ce31aec4-9724-11e8-8d9a-05dc6d66b0dc.png">
- Selected state: update yellow bar to black bar
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/1068783/43664747-ca586f7e-9722-11e8-8916-1796a1289529.png">

_Note: keep the dropdown functionality as is (selected menu item disappears when open the dropdown - see bottom of [comment](https://github.com/mozilla/foundation.mozilla.org/issues/1156#issuecomment-403144169)) until we have a better suggestion.)_

### Overview
![nav new 2x](https://user-images.githubusercontent.com/1068783/43663943-fd893246-971f-11e8-8b1b-9a0643cbad01.jpg)

cc @gvn @alanmoo

**Comment by alanmoo** [comment]
Are the primary page nav and campaign page nav actually any different? Without inspecting closely, it looks like they could be identical, and that the only difference is the distance the grey bar goes (which would just be the container div).

**Comment by kristinashu** [comment]
The secondary nav on primary pages is the same as multi-page campaign pages. Only difference is the grey line fill the entire width of the page on primary pages.  

The main primary nav is also similar but the font size is larger (17px instead of 15px) and all items are black. Synergy! 

Linking this ticket to: Multipage campaigns with long page titles look...weird #1660

**Comment by kristinashu** [comment]
Moved to new individual tickets
