### ISSUE TITLE
[Participate Page] Wins Section

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1722]
@beccaklam I made some changes on the design of the section "Participation Wins". Could you please take a look at the file in Abstract and make sure the UI and spacings are correct (branch: "Pulse-Participate Page Mobile", section "Pulse section iterations + Wins")? 

The only change here was on mobile: I removed the square treatment for pictures and used the default Pulse style treatment so it is consistent with the desktop version and the same as we have in "Trending Projects" section of our home page.

Please let me know if you have any questions and happy to chat at anytime.

**Comment by taisdesouzalessa** [comment]
Hey @beccaklam in our Abstract, Style Guide doc, there is an artboard called "Spacing" - it should have the bootstrap spacing equivalent there. I should have pointed you to that doc before, sorry :(.

<img width="888" alt="image" src="https://user-images.githubusercontent.com/22157921/43792406-680180d2-9a2d-11e8-82c9-5530795b6f99.png">

**Comment by beccaklam** [comment]
@taisdesouzalessa Component is reviewed 👍 I updated the pacing to match bootstrap and merged your branch. You can check out the changes on Master's Initiatives and Participate file :)

**Comment by taisdesouzalessa** [comment]
Implementation ticket is here: #1732 - please take a look there and let me know if anything is missing.
