### ISSUE TITLE
Enable scheduled publishing

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1723]
[According to the Wagtail documentation](http://docs.wagtail.io/en/v2.1.2/reference/pages/theory.html?highlight=publish%20time#scheduled-publishing), we can schedule page publishes/updates. We need to enable a command to run hourly though to publish those. In addition it seems something isn't happening to allow successful queuing of those updates (though the two may be tied together).

Let's make this a thing we can do.

**Comment by cadecairos** [comment]
@alanmoo what's the priority on this?

**Comment by alanmoo** [comment]
Normal. Not a burning need, but something that will help Sydette and others using the site.

**Comment by patjouk** [comment]
@alanmoo I did some testing locally and found a few things:
- Timezone for publishing is in UTC (cf `settings.py`), but it's not communicated to the user. I'll take a look to see if we can add this info in the admin section dedicated to scheduling,
- We can add a scheduled script to Heroku every hour or every 10 min. Either way, we should ask people to set up a scheduled time earlier that when it should be up (2:50pm for 3pm for example). That way, we make sure they never "miss a publish" window. We could also do a check every minute but it means a dedicated dyno, which is definitely overkill.
- That feature can also be used to put an expiration date on pages and unpublished them automatically.

Would it be useful to have a slack bot that says that the scheduled page got published/unpublished?

**Comment by alanmoo** [comment]
Hourly is good. Any chance we can make it happen 1 minute after the hour so, for example, a user can say "publish at 9:00" and it happens at 9:01?

**Comment by patjouk** [comment]
Sadly no, it's 00, 10, 20, 30 or 50. Ex: 09:00, 09:10, etc

**Comment by alanmoo** [comment]
Make it 10 after.

**Comment by patjouk** [comment]
I've added a new job for Heroku scheduler running every hour at 10.
Keep in mind that for now, people need to schedule their page in UTC, not in their timezones.

**Comment by cadecairos** [comment]
@gideonthomas This is done, but be aware that there's some issues regarding timezones. @patjouk understands this far better so if you need more info get in touch on Slack.
