### ISSUE TITLE
Unpublished pages show up in nav

### ISSUE THREAD

**Issue by acabunoc** [mozilla/foundation.mozilla.org#1724]
I unpublished the page https://foundation.mozilla.org/opportunity/mozilla-open-leaders/apply/ in wagtail, but it still shows up in the secondary nav in the parent page

<img width="390" alt="screen shot 2018-08-07 at 10 54 58 am" src="https://user-images.githubusercontent.com/617994/43783724-69bdd044-9a30-11e8-93b2-554417ae741a.png">

When you click it, it 404's
cc: @alanmoo

**Comment by alanmoo** [comment]
Only because you're logged in. The chick means it's in "draft". You could also change the permissions on the page to be private so only logged in users see it (and it would have a lock icon)

**Comment by acabunoc** [comment]
Ah, thank you!
