### ISSUE TITLE
Illustrations for Participate page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1729]
We need an illustration for the Donate CTA and the Share CTA.

#### Copy for Donate is:
If you can, will you give today?
People like you help us stand for a healthy accessible web for all. Donate to keep the web open and free.

#### Copy for Sharing is:
Spread the word
A healthy internet needs people. Share Mozilla’s work with your people to grow 

#### Dimensions are:

<img width="1266" alt="screen shot 2018-08-07 at 2 45 41 pm" src="https://user-images.githubusercontent.com/1068783/43804420-cee87530-9a50-11e8-8d5c-36b5967c1a6e.png">

#### Hacky but there's an example of those dimensions using this placeholder image:

<img width="1218" alt="screen shot 2018-08-07 at 2 30 22 pm" src="https://user-images.githubusercontent.com/1068783/43803904-05c3f310-9a4f-11e8-8ae7-2354448c372f.png">

**Comment by kristinashu** [comment]
I've updated the comp with real content from Sydette https://redpen.io/kc4146d61ae4776b8c
It's in Abstract if you want to test out your illustrations, or I can.

**Comment by kristinashu** [comment]
Nice! You have access now and I've updated it with what you have in Abstract.

**Comment by natalieworth** [comment]
Uploaded the image files to production here https://foundation.mozilla.org/cms/images/

**Comment by kristinashu** [comment]
Live! http://foundation.mozilla.org/participate/
