### ISSUE TITLE
[Participate Page] Pulse section (Collaborate with us) - Implementation ticket

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1731]
Section Preview: 
Desktop:
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/22157921/44051720-7d13bc26-9eef-11e8-8747-2f76872e28c0.png">
Tablet:
<img width="767" alt="image" src="https://user-images.githubusercontent.com/22157921/44051742-8e8eee58-9eef-11e8-881e-21875e8a0061.png">
Mobile:
<img width="160" alt="image" src="https://user-images.githubusercontent.com/22157921/44051789-a2e5c48a-9eef-11e8-8590-9ea9d764601d.png">

- [ ] Title: `Collaborate with us`
- [ ] Intro copy: `Help Mozilla with your time and expertise by contributing to Pulse, where we capture and broadcast projects in pursuit of a healthy internet.`
- [ ] Types of help list: all the [help types we have in Pulse](https://api.mozillapulse.org/admin/helptypes/helptype/), in Alphabetical order: `Attend`, `Create Content`, `Code`, `Design`, `Fundraise`, `Join community`, `Localize & translate`, `Mentor`, `Plan & organize`, `Promote`, `Take Action`, `Test & feedback`, `Write documentation`. All items on this list are links and each one link to a `https://www.mozillapulse.org/help/[LABEL]` url link. E.g.: `https://www.mozillapulse.org/help/attend`, `https://www.mozillapulse.org/help/create-content`
- [ ] Pulse cards: for desktop, 4 Pulse cards will be displayed
   - display latest entries `has_help_types=True`. More info: https://github.com/mozilla/foundation.mozilla.org/issues/1650#issuecomment-410033031
   - each one contains `Title` and the `Type of help needed` label. If there are more than 2 lines of type of help needed (~54 characters), add ellipsis (...). 
- [ ] CTA section: `There is a total of [total number of projects in Pulse, dynamic field] projects in Pulse and counting!`. If this is not possible, please use the fallback `There are nearly 1000 projects in Pulse!`
- [ ] CTA button: `check them out` + external link icon. Link to: `https://www.mozillapulse.org/featured`

**Please note that for tablet and mobile the height of the "Types of help" list items is higher (48px). This is to accommodate the tapping on those devices (if items are too close it will be very difficult to tap).**

**Spacing Specs are on Abstract: Master/Participate and Initiatives. - please let us know if you need this document somewhere else more accessible and we make a copy.**

@kristinashu - this is the implementation ticket but before we assign it to Engineers it would be good to have @xmatthewx eyes on it since he collaborated with Gideon on parts of this ticket, regarding the API (I don't have knowledge of it, so it would be better they review it before we move it forward).

**Comment by xmatthewx** [comment]
Looks great! Excellent work on the checklist details.

**Comment by taisdesouzalessa** [comment]
Updated comp as per conversation with Kristina and Matthew. Abstract updated as well. @beccaklam please note we removed the horizontal lines that were in between the links to make the layout less busy. I updated it in Abstract as well.

**Comment by kristinashu** [comment]
I honestly don't see this getting built anytime soon as we now have different priorities. @xmatthewx I'm going to close but feel free to re-open.
