### ISSUE TITLE
[Participate Page] Participation Wins section (pull from blog/stories)

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1732]
Section preview:
Desktop:
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/22157921/43863811-b63e1cf2-9b12-11e8-9bf1-c2fc4218f76f.png">

Tablet:
<img width="766" alt="image" src="https://user-images.githubusercontent.com/22157921/43863859-cfc13254-9b12-11e8-8aec-669314344e04.png">

Mobile:
<img width="320" alt="image" src="https://user-images.githubusercontent.com/22157921/43863878-db49b5ba-9b12-11e8-8660-a23533ae1d6b.png">

- [ ] Cards have the same style as "Trending Projects" section on the [Foundation site](https://foundation.mozilla.org/). The only difference is that there are 4 of them instead of 3 for desktop view.
- [ ] Cards have `Title` + `Author` of the article
- [ ] Content: I imagined the content of those cards being pulled from a variety of sources. Like, our [Medium blog](https://medium.com/read-write-participate/fellowships-graduations-and-growing-the-movement-a7fba5de44ad) or when we have a victory and update a page with the win, such as the [Change Copyright](https://changecopyright.org/en-US/) or maybe even an article from an external source about the work we do. The only rule here is that the theme of this section has to be a win that was consequence of participation. @kristinashu could you work with Sydette (maybe Kevin too?) to figure out examples of content they think it would be good to have in this section? The reason I ask is because you've been gathering the content of the Initiatives page. Let me know if you would prefer if I talk to them and I can move this forward :). 

**Spacing Specs are on Abstract: Master/Participate and Initiatives. - please let us know if you need this document somewhere else more accessible and we make a copy.**

@jessevondoom @xmatthewx let us know if you have thoughts on types of content for this section.

**Comment by kristinashu** [comment]
This will work well once we have the blog/stories component but blocked until then.

**Comment by kristinashu** [comment]
Soon we will have a blog component https://github.com/mozilla/foundation.mozilla.org/issues/3564 so now we are only blocked by content.
