### ISSUE TITLE
Create OG content for sharing site

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1735]
Need to make an image and write copy that will appear on FB & Twitter when someone shares foundation.mozilla.org

**Comment by kristinashu** [comment]
This is what we have right now:
<img width="539" alt="image" src="https://user-images.githubusercontent.com/1068783/50704579-be4ed480-100c-11e9-9ce1-831bdd884f02.png">

@natalieworth no rush but would you be able to create a better graphic for this?

**Comment by kristinashu** [comment]
I've updated the homepage 'promote' copy with Sydette's recommendation:
> Mozilla is a global non profit dedicated to keeping the Internet global public resource that is open and accessible to all.

**Comment by kristinashu** [comment]
@natalieworth let's go with V1! 

Can you please scale it to the recommend dimensions (i.e. whatever google search says) and then upload it to the CMS (in the promote tab of the Homepage)? 

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/1068783/50937733-d4ec9580-1429-11e9-91d8-4a8aa79559d1.png">

**Comment by natalieworth** [comment]
Updated this today in wagtail (but it's still displaying the old one when I try the link on facebook). I'll try again tomorrow to make sure that it's working:

<img width="1675" alt="screen shot 2019-01-10 at 2 15 35 pm" src="https://user-images.githubusercontent.com/14876567/51000641-90710080-14e2-11e9-9f72-114fc6bef5fa.png">

**Comment by natalieworth** [comment]
Also should the copy have an 'a' before the 'global public...'?

cc @kristinashu

**Comment by kristinashu** [comment]
Sweet! All good now 

<img width="544" alt="image" src="https://user-images.githubusercontent.com/1068783/51001466-06766700-14e5-11e9-8e00-45102be9bc2d.png">
