### ISSUE TITLE
Redesign Buyers Guide

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1739]
Work can be gathered in this deck https://docs.google.com/presentation/d/1EjdExJaq9AYlu5Zf2Z7KReTJe_MTSGnkO53BjIO9lDM/edit?usp=sharing

### Buckets of work
- Assess site UX
- Add a Matrix
  - Product page: Sliders
  - Home page: Matrix Overview
- Product page updates
  - New and improved criteria
  - Add Updates & Opinions feed
- Create Holiday Themed images and crop product images

### Each of these need
- Benchmarking
- Wireframe
- Content
- Comp
- Dev requirements

### UX Research Materials
1. [Comment Analysis](https://docs.google.com/document/d/1755uLhrffsq3VaUUpORkdjh72y0DOMoG-7PM-5j1f6Y/edit?usp=sharing)
2. [Google Analytics Analysis (Data Studio)](https://docs.google.com/document/d/1755uLhrffsq3VaUUpORkdjh72y0DOMoG-7PM-5j1f6Y/edit#bookmark=id.3emc0m37818e)

**Comment by kristinashu** [comment]
@beccaklam @natalieworth please add any benchmarks or feedback/ideas you have to improve the site to the [deck](https://docs.google.com/presentation/d/1EjdExJaq9AYlu5Zf2Z7KReTJe_MTSGnkO53BjIO9lDM/edit?usp=sharing)!

**Comment by kristinashu** [comment]
Yeah the old one will be replaced. I'm guessing a lot of the content will be copied over tho.

**Comment by taisdesouzalessa** [comment]
@kristinashu @beccaklam I am looking into the analytics to get some guidance on the questions you both asked during our meeting (I am putting together a Data Studio panel so we can take a look at it). In the meantime, I looked at the comments (there were just 6 of them) and added some notes on [Google Docs ](https://docs.google.com/document/d/1755uLhrffsq3VaUUpORkdjh72y0DOMoG-7PM-5j1f6Y/edit?usp=sharing)(see section 1: "Comment Analysis"). Becca, that doc may help you to guide some decisions while you work on the interface. Let me know if you have any questions!

**Comment by taisdesouzalessa** [comment]
@kristinashu @beccaklam - Data Studio step completed as well. The insights are all under "UX Research Materials" in the main ticket. Hope that helps to guide your decisions and let me know if you have any questions or if you feel that any information is missing.

**Comment by kristinashu** [comment]
Haven't updates this in a while so here we go...

## Product page 
@kristinashu cleaning up the sketch file and finalizing spacing and icons
@taisdesouzalessa is working on all the different states for the creep-o-meter
@natalieworth will work on animating the creep-o-meter faces (just a placeholder for now until @gvn confirms if it is possible)

https://redpen.io/p/qz6bdb2811e058ffb1

![red-pen-67b3f5d6-4348-461b-993e-8e288163d24a](https://user-images.githubusercontent.com/1068783/45125287-a9c40380-b122-11e8-8f96-e2b279a6fa01.jpg)

## Home page 
https://redpen.io/p/oz80db51ee0e81c38f

@beccaklam brainstormed concepts and is now refining and narrowing it down to 3-4 directions which we will present to Jen
- Matrix
- Quiz
- Layers of purgatory (could be vertical scroll or horizontal slider)
- Simple list

## About the Guide 
Just a plain text page

https://redpen.io/pf7d0c9c8559e1d79f

![red-pen-b010c501-e282-4390-cab0-0f4bbb67055d](https://user-images.githubusercontent.com/1068783/45125300-b5afc580-b122-11e8-9af8-1d632c9c8526.jpg)

## Donate popup
Either a popup like last year (but delayed) or a [1/3 popup](https://redpen.io/wr89a2ff232aa90157)

![red-pen-5ba94251-de5c-4483-bad0-b95b609285cd](https://user-images.githubusercontent.com/1068783/45125523-b006af80-b123-11e8-9169-7c94a6d41284.jpg)

cc @alanmoo

**Comment by natalieworth** [comment]
I've got a really rough animated version of the PNI face (9 frames total). Frames 1,3,5,7, and 9 are the "key face frames." I can add additional frames to tween between the faces for a more seamless look when I return from PTO (and if the test goes okay).

There are png, svg, gif, and mov versions of the face to test.

[I've uploaded everything to the drive here.](https://drive.google.com/drive/folders/1-7zCpdI8gCMnd7qfaMIzhVMgc9D3kf8x?usp=sharing)

cc @gvn and @beccaklam @kristinashu I also included my working illustrator and after effects files.

**Comment by kristinashu** [comment]
This is all done and is amazing! We just need to finalize the home page in https://github.com/mozilla/foundation.mozilla.org/issues/1869 and creepy face animation in https://github.com/mozilla/foundation.mozilla.org/issues/1859. Closing this ticket!
