### ISSUE TITLE
Custom Heroku error page

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#1742]
If there's ever a platform outage or database outage, we can serve a static page of our own design, that's hosted on a highly reliable service (in our case, S3). Lets create a stand alone error page for the foundation site.

Ideally, the page can be a part of this project, and one of the build steps on staging and production is to sync it to a pre-configured place on S3.

I can set things up, but I'm pretty sure we'll need some design + front end skills so that the page is consistent with the rest of the site, and that messaging is good.

**Comment by kristinashu** [comment]
@cadecairos just let me know if you want a design for this and what type of content would be on the page. It could maybe look something like our 404 page?

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/1068783/51939005-5a2cef80-23c3-11e9-802d-2d39b60297cf.png">

**Comment by cadecairos** [comment]
If we're okay with the same design, then I can just take care of the copy - although, not the 404 image with the happy face. Is there another graphic we could use?

**Comment by kristinashu** [comment]
To keep it simple, let's just not have an image. Hopefully not many people will see this...

![untitled-1](https://user-images.githubusercontent.com/1068783/51947351-6ae86000-23d9-11e9-94e0-aefabbddf721.jpg)

**Comment by cadecairos** [comment]
@alanmoo @kristinashu: I made a fully stand-alone maintenance page. 100% open to copy changes. 
![](https://screenshotscdn.firefoxusercontent.com/images/8bbef0e3-168e-45d6-a7aa-826c0e85214f.png)

@alanmoo any preferences around versioning/deployment here? I can commit this to the repo and have it auto-upload to S3 on a `master` travis-ci run - that way we can change it and have those changes ship automatically. A second option is having it live on a separate branch in the repo, with all other content removed, and have it deployed on branch merges. Lastly, we could just chuck it into S3.

**Comment by cadecairos** [comment]
missing a mozilla logo in the header. will fix that

**Comment by alanmoo** [comment]
S3 auto-upload sounds best so it doesn't end up being out-of-sync with our styles. We can even throw a Percy test on it so we don't forget about it.

**Comment by cadecairos** [comment]
Well it's a bit trickier than you might think. I have to rewrite a path in the styles, as well as several in the markup. It's also not going to be testable, unless we also expose it as static route on the site. I think there needs to be a bit of a tradeoff here between having the page and keeping it in parity with site styles. I'm not convinced it's worth engineering something to automatically create modified html and styles for this page. Luckily, it was quite easy to save as a standalone page and make the necessary edits. If I document the process, would you be okay with that?

**Comment by alanmoo** [comment]
Sounds good.

**Comment by cadecairos** [comment]
one last thing to land and this can be closed

**Comment by cadecairos** [comment]
https://github.com/mozilla/foundation.mozilla.org/pull/2902
