### ISSUE TITLE
Content change requests to https://foundation.mozilla.org/about/trademarks/

### ISSUE THREAD

**Issue by ejregithub** [mozilla/foundation.mozilla.org#1743]
Mozilla Legal is requesting the following changes to https://foundation.mozilla.org/about/trademarks/ 

Change requests:

Change page heading and title from '"About us" to “Licensing”

Under the content section “Trademarks”, please edit the copy and links to read:

Although our code is free, it is very important that we strictly enforce our trademark rights, in order to be able to protect our users against people who use the marks to commit fraud. This means that, while you have considerable freedom to redistribute and modify our software, there are tight restrictions on your ability to use the Mozilla names and logos in ways which fall in the domain of trademark law, even when built into binaries that we provide.

For more detail on our trademark licensing, see our <a href="https://www.mozilla.org/en-US/foundation/trademarks/policy/">Mozilla Trademark Guidelines</a>. If you still have questions after reading the policy, please contact <a href="mailto:trademark-permissions@mozilla.org">trademark-permissions@mozilla.org</a>.

(end changes)

-------------------
For reference, I consulted w. @alanmoo about how best to make these requests, resulting in the filing of this issue. Please let me know of any questions.

Many thanks,

Eric

**Comment by alanmoo** [comment]
I've changed the body content, but I'm not entirely clear on what you're looking for from the heading. "About Us" is the heading across all pages in that section of the site, so it's not logical to change that. Can you clarify? We could easily change the "Trademarks" item in the navigation if that addresses the concerns at hand.

cc @jessevondoom

**Comment by ejregithub** [comment]
Apologies for the lack of clarity.  Yes, the request is to change 'Trademarks' in the nav to 'Licensing', as will as the corresponding change to the URL from https://foundation.mozilla.org/about/trademarks/  to  https://foundation.mozilla.org/about/licensing/


<img width="347" alt="screen shot 2018-08-12 at 10 03 53 am" src="https://user-images.githubusercontent.com/20547886/44004423-62e4e7fe-9e17-11e8-95ee-2defcbd7b88c.png">

**Comment by alanmoo** [comment]
Done!

**Comment by ejregithub** [comment]
Thanks @alanmoo !!
