### ISSUE TITLE
remove `filebrowser-safe` dependency

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#1759]
We should investigate whether we're still using this library at all, and if so, if we're using it "correctly" or whether there's a better solution to tie wagtail into s3

**Comment by Pomax** [comment]
I might need your help in figuring this one out, @cadecairos, @patjouk - we added this a loooong time ago in order for image uploads via the CMS to make it onto S3, but I have no idea whether that's still necessary or not.

**Comment by patjouk** [comment]
I'm not sure either. I'm adding the devops label so we can triage this and take a look soon.

**Comment by cadecairos** [comment]
@patjouk can you investigate this and report here what we're dealing with regarding filebrowser_safe?

**Comment by patjouk** [comment]
Yeah, but like I said, this is very low in my priorities list 😞

**Comment by KalobTaulien** [comment]
@cadecairos as far as I can tell it's not being used. We're using S3 with an in-house app but the filebrowser-safe package continued to work for me on staging. Is there a way we can test this on a staging/review app? 

[According to the docs it's for Mezzanine](https://github.com/stephenmcd/filebrowser-safe#overview) as well. My thinking is it's safe to remove this, but let's test this out just in case there are some old Mezzanine hooks in the db that requires this.

The diff can be found here https://github.com/mozilla/foundation.mozilla.org/compare/master...1759-remove-filebrowser-safe-dependency 
The branch I've built is `1759-remove-filebrowser-safe-dependency `

**Comment by Pomax** [comment]
closing in favour of https://github.com/mozilla/foundation.mozilla.org/issues/8500
