### ISSUE TITLE
Add Awards to Initiatives landing page

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1762]
We have a new page about our [Awards programs](https://foundation.mozilla.org/initiatives/awards/).

@Sydette - can you work with @jenntbeard to add an intro and link? It would be in the featured programs on the [Initiatives landing page](https://foundation.mozilla.org/initiatives/).

@jenntbeard drafted this to get things rolling: 

> Awards at Mozilla are designed to support diverse approaches to addressing the most pressing threats to Internet Health. Awards celebrate a variety of targeted solutions, not a one-size-fits-all silver bullet. They spotlight the technologies, art, and other work being done by leaders across the globe in order to amplify these promising approaches and to help make the internet healthier for all.

via https://github.com/mozilla/foundation.mozilla.org/issues/1760

**Comment by kristinashu** [comment]
This is almost all done here https://github.com/mozilla/foundation.mozilla.org/issues/2366
