### ISSUE TITLE
Plan a test of Donate button style

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1764]
Team! We have a few different donate button styles floating around. Let's plan a test to pick the best. This ticket is to kickoff the conversation and get organized. 

In order to do an A/B test, we need a steady stream of traffic. We will run this after we redirect traffic from mozilla.org/foundation to foundation.mozilla.org/about. We can test the button on all pages, but this will give us the flow needed for a reliable test, independent of campaign spikes. 

I don't expect wildly different results like we see with donate campaign CTAs. But, it's an opportunity to choose a style AND set up the infrastructure to run non-campaign tests like this. We can flex our testing muscle and look for other site optimizations.  

Tasks
 - [ ] Prep artwork and CSS
 - [ ] Prep server-side tooling to serve options (#1844)
 - [ ] Add testing parameter to GA event tracking label
 - [ ] What else???

Proposed roles
 - Driver: @taisdesouzalessa
 - Accountable: @jessevondoom and/or @xmatthewx
 - Responsible
   - @alanmoo to triage requirements and approach
   - @kristinashu and/or @natalieworth to gather UI options
 - Consulted: Steph McV after we get rolling 
 - Informed: Shhhh. Nobody needs to know.

Next step:
 1. discuss
 2. give @alanmoo time to assess the scope of work on his end _before_ we do any other significant work

**Comment by alanmoo** [comment]
#1844 is filed, I'd like to see if we can get to take a look at that next week.

**Comment by kristinashu** [comment]
@alanmoo is dev almost ready to test this kind of thing?

**Comment by alanmoo** [comment]
This would be a good first implementation of our A/B testing, which is technically live.

**Comment by kristinashu** [comment]
Ok awesome!

**Comment by kristinashu** [comment]
We plan to test the new email signup and donate buttons so I'll close this ticket and focus on https://github.com/mozilla/foundation.mozilla.org/issues/2757
