### ISSUE TITLE
Design for new Awards Challenge

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1765]
We are gearing up for a new Awards Challenge, similar to NSF Wins. It will live on the foundation at [/initiatives/responsible-cs/](https://foundation.mozilla.org/en/initiatives/responsible-cs/).

This will require graphics for us at the top page, email, and social. We should think of this as a title with tagline, not as a logo brand. It will be associated with Mozilla and another funder or two. Requirements for those brand relationships will be sorted out starting this friday. 

@kristinashu let's discuss.

Program launches 9/24. A good deadline for design could be 9/14. 

More info in [this doc](https://docs.google.com/document/d/1YuabSiuOqqDj-QA_u8RHtkL0jQEmZezf6ItgIOP9_7g/edit).

**Comment by kristinashu** [comment]
### To do:
- [ ] Meet with Jen
- [ ] Put [content](https://docs.google.com/document/d/1YuabSiuOqqDj-QA_u8RHtkL0jQEmZezf6ItgIOP9_7g/edit) in to [multi-page site with zen mode nav](https://foundation.mozilla.org/en/initiatives/responsible-cs/)
- [ ] Create images: banner for wagtail pages, email and social
- [ ] Add logos: example of equal hierarchy of logos (but lets do logos in gray scale)
<img width="751" alt="image" src="https://user-images.githubusercontent.com/1068783/45124763-67012c00-b120-11e8-85f2-8acdf39e4913.png">

**Comment by kristinashu** [comment]
I see Natalie's images test working well for this! We could find computery images and apply the gradients and patterns to it.
<img width="679" alt="screen shot 2018-09-06 at 12 32 26 pm" src="https://user-images.githubusercontent.com/1068783/45240598-17486f00-b29e-11e8-9f73-f17a39f46b3d.png">

**Comment by kristinashu** [comment]
@taisdesouzalessa the partners Jenn is working with are very keen to see the graphic (they were expecting to see it Monday) so the sooner the better! I think they want to see some progress, no matter how small!

**Comment by jenntbeard** [comment]
Hello! I am taking a look at the docs/wagtail now. As per our timeline with the Funder, we would like to be able to share a draft of the site by Friday this week, if at all possible. If we have the rough mockup and the header, I think we'd be in good shape - I can always talk them through the remaining work to be done but would like them to at least get a solid idea of our direction.

**Comment by taisdesouzalessa** [comment]
**Status:** shared 4 concepts of header with Jenn + updated the icons via **email**. 
**Next:** update the "Judges" section with pictures, copy updates as per document and wait for Jenn's feedback (once we have it, I can do any necessary adjustments/tweaks). @jenntbeard please let me know if anything is missing here that you would like to get done by Friday.

cc: @kristinashu

**Comment by jenntbeard** [comment]
Ohh, those are looking slick! I really like 2a. We are going to send them over to the funder and I have a few slight changes to the timeline (mostly just capital letters), I will ping you in the website copy doc.

**Comment by kristinashu** [comment]
Yea I'm really liking both 2a & 2b!

**Comment by jenntbeard** [comment]
Yeah, sorry, I misspoke, I really like 1a and 1b - I have sent both of those to the funder for feedback and for their preference on placement of the Omidyar Network logo (I know they will care about that most). I think the site is really coming along. I just reached out to the judges that we haven't received bios/headshots from (and we still have a couple of outstanding invites, just so you know). Also, we will need the one-pager (like we had for WINS) designed to match the theme/website. You can find an almost final version of that here: https://docs.google.com/document/d/1XsDBEK2r5AYlmFOHLuh5c4ByFIWevtKBybdyx06G8oY/edit?ts=5b9bace3

**Comment by taisdesouzalessa** [comment]
Email sent with project's status. Copy of the email below:

1. SITE: Put content in to multi-page site with zen mode nav and create banner.
STATUS: incomplete
• missing picture of Joy Buolamwini (Judges' page)
• missing [All signatories names/affiliations listed in responsive columns here] (Industry Support Page)
• missing link to one pager - Q: Is there a one-pager?  (FAQ Page)
• need links for "Letter of Intent" and "Apply Now" - we just have placeholder links for now.
• once all above is done, we can do the QA

2. ONE-PAGER: Done
STATUS: Design done. Waiting on feedback.
• once stakeholders' feedback is complete, I can export the PDF for print.
• this is the link with the latest PDF (based on Jenn's comment in InVision). Here is the JPGs: page 1 - page 2

3. EMAIL AND SOCIAL: Create images.
STATUS: Not done, dependencies to be solved first. Are we okay with the image on the site (banner)? Is it possible we will have any change related to that? If the banner is approved, that will be the format we will follow for social media and email. In order to create those images, I need to know the content of the social media message and email.

**Comment by taisdesouzalessa** [comment]
STATUS UPDATE:
1. SITE:
    STATUS: incomplete
    • missing picture of Joy Buolamwini (Judges' page)
    • need links for "Apply Now" - we just have placeholder links for now.
    • once all above is done, we can do the QA

2. ONE-PAGER: Done
    STATUS: Design done. After some changing on the number, we have a final version.
    • this is the link with the [latest PDF](https://drive.google.com/open?id=12MBS91NDQMjYS0gno2U-x32duyKUwGMk)(based on Jenn's comment in InVision). 

3. EMAIL AND SOCIAL: Create images.
    STATUS: Facebook template was sent via email. Need the final content to finalize this work or to send the editable file to them if they will place their own content. **LinkedIn and Twitter banners will be done once Facebook template is approved.**

cc: @xmatthewx @kristinashu

**Comment by jenntbeard** [comment]
Hi, the Apply Now button should just be linked to Fluxx: https://mozilla.fluxx.io/. The photo of Joy, along with her bio are now up as well!

**Comment by taisdesouzalessa** [comment]
STATUS UPDATE:
- Design QA done (site, one-pager and social media).
- password protection removed.
- email sent to Jenn, Matthew and Kristina with project status.

One thing I just noticed @kristinashu @jenntbeard there is an email image on the list...do we need that still?

Waiting to see if there is anything missing and if not, will close this issue.

**Comment by jenntbeard** [comment]
Hmm, I think we can get by without the email image - thanks!!
