### ISSUE TITLE
Go live with new Participate page

### ISSUE THREAD

**Issue by gvn** [mozilla/foundation.mozilla.org#1766]
The new participate page has soft launched at https://foundation.mozilla.org/en/participate2

To go "fully" live and replace the existing page, we need to:

- [x] Put final content in CMS (https://foundation.mozilla.org/cms/pages/168/edit/)
- [x] Delete old Participate page on production
- [x] Change Participate 2 page slug to `/participate`

CC @alanmoo @kristinashu

**Comment by kristinashu** [comment]
We have the go ahead from Jesse to launch this!

**Comment by gvn** [comment]
Cool! It's alive!

https://foundation.mozilla.org/en/participate/
