### ISSUE TITLE
Design postcard for copyright campaign - due Aug 30

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1769]
Launch a postcard campaign before a critical EU copyright vote on. Users will land on an updated changecopyright.org and will be asked to send a postcard to MEPs. Users will type in their name and a message that will then be printed and physically mailed.

They need a postcard that will be somewhat art-y – nice enough that MEPs will want to put it up on their walls and not just dump them out in the trash.

Here are some of Jon's concepts:
- Something focused on competition or taking on corporate power (like those old Mozilla vs corporations comic-style posters)
- Something based on pop-art – warhol-style/cut and paste kinda thing, the idea being that the internet right now breeds creativity
- Something based on censorship – that censoring the internet is bad for all of us

If we can use pre-existing art that would be great.

I will get copy from Jon. Note: cards will need to be translated in to six languages. 

cc @xmatthewx

**Comment by natalieworth** [comment]
I've put some options for possible directions in the redpen here https://redpen.io/p/zxbe27071f4ae2480d

I'm going to be out on PTO til the 28th. I'll send an email with the design file if these are needed sooner.

cc @kristinashu @xmatthewx

**Comment by kristinashu** [comment]
Campaign is cancelled 👎 

Thanks anyways Nat for the sweet illustrations!
