### ISSUE TITLE
Update Mozilla Fellows Image

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1800]
Do a quick update on the Mozilla Fellows Image based on the new visual direction we are adopting in our site.

**Current image:**
<img width="699" alt="image" src="https://user-images.githubusercontent.com/22157921/45048786-a270fd00-b031-11e8-9691-5a18300b1751.png">

**Places the image should be updated:**
After talking to Kevin, these are the places this image currently shows up:
1. https://medium.com/read-write-participate/my-year-being-a-ford-mozilla-open-web-fellow-5d88fd4cc5b9
2. https://www.mozillapulse.org/entry/913
3. https://blog.mozilla.org/blog/2018/03/21/seeking-fellows-better-internet-apply/ - I think this one doesn't need update because the blog post is from a time in which the visual direction was the green/blue gradient. We could replace it for one of those other options from InVision: https://mozilla.invisionapp.com/boards/TD3LINZHG8X/ - let me know what you think @xmatthewx. 

@natalieworth will work in a set of guidelines for images, considering our new visual direction. In the meantime, I can work in a quick fix to send to Kevin.

**Comment by kristinashu** [comment]
Let's just leave these and use the new style moving forward.
