### ISSUE TITLE
refactor wagtailpages blocks

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#1801]
they're currently all in one big file; it would be much nicer to have then housed in their own files inside a `blocks` dir.

**Comment by HSR05** [comment]
I'd work on this. Can you guide me a little @kristinashu  @Pomax

**Comment by Pomax** [comment]
Absolutely: do you have any experience with Python and Django?

**Comment by HSR05** [comment]
> 
> 
> Absolutely: do you have any experience with Python and Django?

Yeah, i am familiar with python and django. I have done a few projects in django.
Can you guide me a little so that i can resolve this issue.
i would be more than thankful. 👍

**Comment by Pomax** [comment]
We currently have a huge single file called `customblocks.py` in the `network-api/networkapi/wagtailpages` dir, and it would be good if we could split that up into individual files for each component, while still being able to say `from networkapi.wagtailpages.customblocks import ( ........)` in the `models.py` file that is in the same directory at the moment. So customblocks probably needs to become a directory, with individual files.

(note: this is a python 3.x project so solutions that use also take python 2.7 into account are not necessary)

**Comment by Pomax** [comment]
The refactor part of this work has been resolved, however there is still the question around testing left, for which https://github.com/mozilla/foundation.mozilla.org/issues/3428 has been filed
