### ISSUE TITLE
Copy/Paste in Wagtail - links dissapear

### ISSUE THREAD

**Issue by acabunoc** [mozilla/foundation.mozilla.org#1815]
If I copy & paste from one wagtail component to another, it strips away the links
![sep-11-2018 16-04-14](https://user-images.githubusercontent.com/617994/45384579-6531df80-b5dc-11e8-90b6-7de1bdf45b29.gif)

**Comment by acabunoc** [comment]
workaround: copy/paste from the preview instead

**Comment by Pomax** [comment]
yeah, this is an outstanding issue in wagtail itself, there's been some movement on it but they're reworking the WYSIWYG box atm because links (and some other markup) disappears when you copy =(

**Comment by kristinashu** [comment]
Yes! This drives me crazy! But I'm going to close this ticket since it's a Wagtail issue.
