### ISSUE TITLE
Buyers Guide: product page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1819]
Based on design in https://github.com/mozilla/foundation.mozilla.org/issues/1739

Comps https://redpen.io/p/qz6bdb2811e058ffb1

### Header section
- [x] large image on light gray background
- [x] company name, price, product name, intro text
- [x] copy link with same functionality as [live site](https://advocacy.mozilla.org/en-US/privacynotincluded)

### Criteria
- [x] Final copy in [doc](https://docs.google.com/document/d/1jtWOVqH20qMYRSwvb2rHzPNTrWIoPs8EbWR25r9iyi4/edit) with details
- [x] all sad faces have red highlight
- [x] optional expandable/collapsible accordion for any criteria on any product page
- [x] *NEW: add seal for 'meets minimum security standards': Yes, No, Can't determine (will design three badges, each product will display on of them)

### Updates
- [ ] optional section
- [ ] 0-6 updates per product
- [ ] source, title (opens link in new tab, hover state is underlined), author, intro text

### Related products
- [x] 4 products from the same category (either selected my user or random - need to discuss) 

### Comps

![](https://s3.amazonaws.com/redpen-prod/red-pen-73332979-3492-4c03-9d95-1a62709c51c8.jpg)

![](https://s3.amazonaws.com/redpen-prod/red-pen-caee1abf-9798-4ecd-e445-e1f33021aa5d.jpg)

**Comment by gvn** [comment]
@kristinashu Can you attach a ZIP with SVGs of the various glyphs throughout this comp?

**Comment by kristinashu** [comment]
Here are all the icons for criteria: [icons.zip](https://github.com/mozilla/foundation.mozilla.org/files/2402989/icons.zip)

#### I still need to add
- thumbs up/down icons
- dot pattern
- +/- icon for accordion

**Comment by gvn** [comment]
@kristinashu I did the accordion as a + which rotates to an X if that works.

**Comment by kristinashu** [comment]
👍

**Comment by kristinashu** [comment]
Here's the dot pattern stuff:
- should be a black square 3x3px centered in a 9x9px white square
- jpg and svg of the repeatable pattern [dot.zip](https://github.com/mozilla/foundation.mozilla.org/files/2412860/dot.zip)

- once repeated, it should look like this
<img width="1269" alt="screen shot 2018-09-24 at 2 02 21 pm" src="https://user-images.githubusercontent.com/1068783/45979063-b9888680-c002-11e8-9701-359e7a9f2726.png">

Let me know if you need a different format or scale.

**Comment by kristinashu** [comment]
Since work will now be divided up between @gvn and @Pomax I've split this into slightly smaller tickets:
- Buyers Guide: QA product detail page #1860
- Buyers Guide: build creep-o-meter #1888 
- Buyers Guide: comments #1889

Can we close this one? Still some work to be done on Updates section but maybe that can be part of QA ticket?

**Comment by kristinashu** [comment]
Opened new QA ticket that has Updates section in it so closing this one https://github.com/mozilla/foundation.mozilla.org/issues/1892
