### ISSUE TITLE
Buyers Guide: About page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1822]
Based on design in #1739

Comps https://redpen.io/p/qz6bdb2811e058ffb1

Text page similar to [live site](https://advocacy.mozilla.org/en-US/privacynotincluded)

![](https://s3.amazonaws.com/redpen-prod/red-pen-b010c501-e282-4390-cab0-0f4bbb67055d.jpg)

**Comment by alanmoo** [comment]
Are these heading styles used elsewhere in the site? I'd like to use the same classes if possible.

**Comment by kristinashu** [comment]
Yes, from https://foundation.mozilla.org/en/style-guide/ they are:
- .h3-heading
- .h4-heading
- .normal

**Comment by shaghdoosti** [comment]
@alanmoo @kristinashu 

Can we please change the text about the minimum standards? Here's what it is now: 

 Our Minimum Security Standards

We developed a set of minimum security standards we think all connected products should meet at the very least. Think of it as a “you must be this tall to ride” set of standards. These include five basic things: The product must use encryption, the company must provide automatic security updates, if a product uses a password, it must require a strong password, the company must have a way to manage security vulnerabilities found in their products, and the company must have an accessible privacy policy. If you would like to learn more about our minimum security standards go here. 

Here's what I'd like to change it to: 

 Our Minimum Security Standards

We developed a set of minimum security standards we think all connected products should meet at the very least. Think of it as a “you must be this tall to ride” set of standards. These include five basic things: The product must use encryption, the company must provide automatic security updates, if a product uses a password, it must require a strong password, the company must have a way to manage security vulnerabilities found in their products, and the company must have an accessible privacy policy. **In the guide we've ticked the products that from our research appear to meet the guidelines, this tick is not an endorsement of the product on the behalf of Mozilla, Consumers International or the Internet Society.** If you would like to learn more about our minimum security standards go here.
