### ISSUE TITLE
Buyers Guide: donate popup

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1823]
Based on design in #1739

Comps https://redpen.io/p/qz6bdb2811e058ffb1

### Functionality
- slides up from the bottom of the page
- user must be on the site for 10 second [need to discuss] before it slides up
- clicking close icon, donate, or outside of the popup will close it

### Copy
- `We made this guide with support from people like you`
   Zilla Slab Light 34px with 42px line height
- `Our supporters told us they are uncertain about how to be safer online. We listened. This guide is a result.` 
  .normal paragraph but white
- `Help us keep this work going` 
  Zilla Slab Regular 22px with 28px line height
- `Support Mozilla`

### Styling
- donate button similar to header but bigger 48px height
- background color of #333333 
- earth image

![earth 2x](https://user-images.githubusercontent.com/1068783/47503952-348fc780-d863-11e8-8df2-6c45aca69920.jpg)

### Comps

![donate copy 2x](https://user-images.githubusercontent.com/1068783/47504431-268e7680-d864-11e8-91a8-eb41b98717b8.jpg)

<img width="319" alt="image" src="https://user-images.githubusercontent.com/1068783/47504704-b2080780-d864-11e8-99f5-376d2c6d1b47.png">

**Comment by Pomax** [comment]
Do we have a higher quality version of that earth image? (there's a lot of jpg artifacting in the one linked)

**Comment by WillatMozFdn** [comment]
Copy & overall design look fine to me.  Thanks!!!
