### ISSUE TITLE
Remove the "font-family-no-missing-generic-family-keyword" null from stylelint rc

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#1839]
Stylelint 9 + standard config 18 put in changes that means we have 19 `font-family-no-missing-generic-family-keyword` errors that will need to be resolved before we can take out the bypass for it.

**Comment by HSR05** [comment]
I'd like to work on it. Can you guide me a little. Thankyou 👍

**Comment by kristinashu** [comment]
@HSR05 are you still interested in helping out with this? 

If so, @Pomax please add some guidance!

**Comment by HSR05** [comment]
Yes, I am interested.

**Comment by Pomax** [comment]
this issue should actually have been closed, we switched to `prettier` which obviated the need for this a while back.
