### ISSUE TITLE
Remove the "no-descending-specificity" null from stylelint rc

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#1840]
Stylelint 9 + standard config 18 put in changes that means we have 160 `no-descending-specificity` errors that will need to be resolved before we can take out the bypass for it.

**Comment by mmmavis** [comment]
No longer applicable! We don't have `.stylelintrc` file anymore! 

Closing!

**Comment by mmmavis** [comment]
Sorry I was wrong 😂 . `.stylelintrc` file is still in the repo.

**Comment by mmmavis** [comment]
`no-descending-specificity: null` was removed as part of PR https://github.com/mozilla/foundation.mozilla.org/pull/2807/files#diff-ab1d354bf78d8f05312122983731ff51L6.

Closing this ticket for real this timeee! 😂
