### ISSUE TITLE
[Responsible CS Challenge] Pre-launch and Post-launch punchlist

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1857]
### Pre-launch
- [ ] Proofread copy to make sure there are no typos or wrong info. **Responsible: Jenn** 

- [ ] Make sure there is no info missing or placeholder copy or picture. **Responsible: Taís for checking placeholder pictures/Jenn for checking the info** 
_STATUS: Taís checked and confirm that there is no placeholder pictures._

- [ ] Make sure all links work and take users to the right places. **Responsible: Taís** 
_STATUS: Taís checked and there are a few fixes to do. See comments below on this thread (QA - fixes to do)_

- [ ] Make sure design is consistent across pages. **Responsible: Taís** 
_STATUS: Taís checked and there is one recommendation. See comments below on this thread (QA - fixes to do)_

- [ ] Make sure all the systems are capturing the info we need (Google form, Fluxx). **Responsible: Jenn** 

- [ ] Check all links in one-pager to see if they are working correctly.  **Responsible: Taís and Jenn** 

### Post-launch
- [ ] Take down the LOI/Apply button on December 14, 2018. **Responsible: ???** 

@jenntbeard please edit this list as you see fit and add more items. We should have those checked pre-launch to make sure everything is in place for a smooth site launch! I added my name as "responsible" in the items I can help with.

cc: @xmatthewx @kristinashu

**Comment by jenntbeard** [comment]
I realize this is the pre-launch punchlist but just wanted to flag that we'll need to take down the LOI/Apply button on December 14, 2018.

**Comment by taisdesouzalessa** [comment]
@jenntbeard good point! I edit the name of the ticked and added your item there under "Post-launch". Feel free to add/remove items form the main list as you see fit. Thanks :).

**Comment by taisdesouzalessa** [comment]
### QA - fixes to do:
1. [Judges page](https://foundation.mozilla.org/en/initiatives/responsible-cs/judges/) - Edward W. Felten section - "Public Affairs " link doesn't work
<img width="600" alt="image" src="https://user-images.githubusercontent.com/22157921/46687286-62acb080-cbaf-11e8-9c53-4299ac19665e.png">

2.  [Industry support page](https://foundation.mozilla.org/en/initiatives/responsible-cs/industry-support/) - recommendation: make the names in bold for better hierarchy. Example:
<img width="346" alt="image" src="https://user-images.githubusercontent.com/22157921/46687775-87edee80-cbb0-11e8-9dca-3fa5ba3fc646.png">

3. [FAQ page](https://foundation.mozilla.org/en/initiatives/responsible-cs/faq/)
"Is there a one-pager?" question is not there anymore. Just double checking if it was intentional.

cc: @jenntbeard @kristinashu

**Comment by jenntbeard** [comment]
Hi - funny, I hadn't even noticed things were hyperlinked in the bios - feel free to disable if the link isn't working. I love the recommendation to bold the names in the Letter to Industry. That item was removed from the Q&A (it was a weird reminder to myself mostly to create that collateral for sharing externally). Finally, Fluxx isn't meant for mobile - in the application guide it advises people not to use it in mobile. Let me know if you need anything else!

**Comment by jenntbeard** [comment]
Hi - funny, I hadn't even noticed things were hyperlinked in the bios - feel free to disable if the link isn't working. I love the recommendation to bold the names in the Letter to Industry. That item was removed from the Q&A (it was a weird reminder to myself mostly to create that collateral for sharing externally). Finally, Fluxx isn't meant for mobile - in the application guide it advises people not to use it in mobile. Let me know if you need anything else!

**Comment by jenntbeard** [comment]
Ack sorry, not sure what happened there - didn't mean to close!! I fixed the link for Ed Felton's profile - there was just an extra www. that wasn't necessary.
