### ISSUE TITLE
Buyers Guide: Creep-O-Meter animation

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1859]
Feedback from Tais' usertesting found that users felt the current simple face animation didn't really represent their feelings of being creeped out. Would be good to draw out more creeped out keyframes and uplevel animation to something a little more rich.

Examples of richness, not creepiness:
- https://dribbble.com/shots/3039000-Hello-Dribbble 
- https://dribbble.com/shots/3025343-Animatiki-Animated-iOs-Stickers

Please do it in your own style, these are just examples.

**Comment by natalieworth** [comment]
<img width="1222" alt="screen shot 2018-09-26 at 4 09 27 pm" src="https://user-images.githubusercontent.com/14876567/46114275-bdeda480-c1a6-11e8-837d-323939043179.png">
@beccaklam @kristinashu before I start animating anything—do you think these 5 'key' faces convey better emotion/ understanding of creepiness? I'll also put them on r[edpen if you want to leave comment in there.](https://redpen.io/p/wfa33bfccd9fe4f98e)

**Comment by natalieworth** [comment]
[faces_v-3.ai.zip](https://github.com/mozilla/foundation.mozilla.org/files/2421867/faces_v-3.ai.zip)
@beccaklam There is the .ai file too for the faces (if you want to mock them up to see how they look in your comps).

**Comment by kristinashu** [comment]
This is gonna be amazing! 

Some notes from convo with @gvn:
- he needs one svg face to test with
- we will have about 30-40ish faces in total (but will have some back and forth to figure out how to balance smooth animation with load-time and effort)

**Comment by natalieworth** [comment]
Added 2 other more subtle options of the emoji styles in redpen. https://redpen.io/p/wfa33bfccd9fe4f98e

cc @kristinashu @beccaklam

**Comment by natalieworth** [comment]
Creep-o-meter draft!!! AH! It's been tricky to get the transitions to not look weird, but hopefully if it's sliding it'll be less weird:
![face-test-02](https://user-images.githubusercontent.com/14876567/46434842-ac0d8380-c709-11e8-80e9-ce02f0dd30fe.gif)
cc @kristinashu @beccaklam

**Comment by beccaklam** [comment]
whooaaa @natalieworth so cool and smooth :)
Yeah the only weird thing is the teeth that come out from the creeped out face to the happy face. but does it even need to transition between the two? wouldn't it just go backwards?

**Comment by natalieworth** [comment]
@beccaklam Yah! It could essentially only go back and forth, so it wouldn't have to loop seamlessly.

**Comment by kristinashu** [comment]
Soo cute and expressive!

**Comment by natalieworth** [comment]
[5-faces.zip](https://github.com/mozilla/foundation.mozilla.org/files/2448519/5-faces.zip)
[face-png-animation.zip](https://github.com/mozilla/foundation.mozilla.org/files/2448520/face-png-animation.zip)

**Comment by kristinashu** [comment]
Sweet! I think this is all done and amazing. 

Please reopen if you still need it tho!
