### ISSUE TITLE
Buyers Guide: QA product detail page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1860]
From ticket https://github.com/mozilla/foundation.mozilla.org/issues/1819 and [doc](https://docs.google.com/document/d/14wTXrEmYmQFWYlmkwFXJtHJZPiseXTgAokJq7_BHx28/edit#heading=h.725dh6j4j01a).

### Images
- [x] hero image is broken **_(high priority)_**
- [x] Related Product images are broken **_(high priority)_**

### Categories Nav
- [ ] should be sticky _(low priority)_
- [ ] font weight 700 instead of 900 _(low priority)_
- [ ] font size from 17px to 15px (new update so that it fits better on all screen widths)  _(medium priority)_
- [ ] Nav container should be consistent height (right now it changes depending if selected state bar is there or not) _(low priority)_

### Grid
- [x] grid is generally too narrow (update from 8 to 10 columns) _(medium priority)_

### Intro
- [ ] copy link functionality isn't working in Safari on iPhone _(medium priority)_
- [ ] needs some sort of feedback so the user knows that the link has been copied **_[need to mock up]_** _(medium priority)_
- [ ] narrow layout: copy link should be moved lower down _(medium priority)_

### Criteria
- [x] need to add link to Privacy Policy **_(high priority)_**
- [ ] accordions work well but should [style text in italics and 14px](https://redpen.io/we4fedfbca381f4804) _(medium priority)_
- [ ] undetermined face has been updated from green to gray _(low priority)_
- [x] grades should be individual and add "can't determine :|" **_(high priority)_**
- [x] update password question and answer: "If a password is required, you must change the default password"  Yes :) or No :( or Not required :|  **_(high priority)_**
- [ ] add "Customer support" text above list of ways to contact them _(medium priority)_ 
- [x] remove "Customer support" field from CMS (we don't show the answer) **_(high priority)_**
- [ ] medium layout: phone icon disappears _(medium priority)_
- [ ] medium layout for both 3 icons sections: list should stack and go into mobile view layout sooner _(medium priority)_
- [ ] narrow layout for both 3 icons sections: icon centering and spacing is off _(medium priority)_
- [ ] narrow layout: smile/frown faces shouldn't change size _(medium priority)_
- [x] add Twitter as a contact **_(high priority)_** (this is a new feature, sorry)

**Comment by gvn** [comment]
That sounds do-able to me.

**Comment by gvn** [comment]
@alanmoo @cadecairos – Any idea why images would be working locally but not showing up in the staged PR?

**Comment by alanmoo** [comment]
This goes back to something I didn’t get to when setting up the scaffolding. There’s a media directory env var or something like that which needs to be added to the image URLs in the template.

**Comment by gvn** [comment]
@alanmoo Currently I have images set up like this, which works locally:

`<img src="{{mediaUrl}}{{product.image}}" />`

Do you know what I'd need to use instead?

**Comment by alanmoo** [comment]
Looks like you need to add `{{AWS_LOCATION}}` between the two, as uploaded images on staging are in the `network` directory (`https://assets.mofostaging.net/network/images/buyersguide/nintendo-switch_1538423164.jpg` for example).

@Pomax may be able to shed some more light on this for the proper way to do it.

**Comment by gvn** [comment]
Got it working. 🎉

**Comment by kristinashu** [comment]
👀

**Comment by kristinashu** [comment]
All the P1s are done so I'm going to close this and have open a new one for P2s:
- Buyers Guide: nav QA #1893
- Buyers Guide: QA product detail page P2

Closing!
