### ISSUE TITLE
Buyers Guide: crop product images

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1866]
- Full product list is [here](https://docs.google.com/spreadsheets/d/1zfwxGCc7dIF7ubO4Pqw6m-ZAevU05CaQ_jUzQPz3ZxM/edit#gid=115469060)
- Let's gather the best image for each product (must be on white background and high res)
- Put on light grey background
- Crop them to 800x800px or 1000x1000px
- Upload to CMS

**Comment by kristinashu** [comment]
Slowly starting to put images into [Drive](https://drive.google.com/drive/folders/1IxnifzMqYwCVzmhwQZG-2v3qhm_a6XgW?usp=sharing) and put into one Photoshop file. Updating the [content sheet](https://docs.google.com/spreadsheets/d/1zfwxGCc7dIF7ubO4Pqw6m-ZAevU05CaQ_jUzQPz3ZxM/edit#gid=115469060) as I go.

Once image upload is working in the CMS we can test out different dimensions. For now, I'm using last years dimensions for the Photoshop file but I think we'll be able to just to a non-full width image?

**Comment by kristinashu** [comment]
@gvn @beccaklam I'm having an issue with the images. Even though Photoshop and the site are using #f4f4f4 as a background color. They are slightly different so I can see a faint square background around the bear.

Using transparent png for the bear isn't possible because we won't be able to get it on a clear background and the file size will be too big.

Should we do it like the [old site](https://advocacy.mozilla.org/en-US/privacynotincluded/category/toys/edwintheduck)? Where we upload the full banner? Any other ideas?

Screen cap from https://foundation.mozilla.org/privacynotincluded/product/Parker%20Teddy%20Bear/
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/1068783/46379850-06004180-c655-11e8-9670-d8e465622c84.png">

**Comment by gvn** [comment]
Is there a color profile getting attached to the JPEG? Are you using export to web?

**Comment by kristinashu** [comment]
Yea using Save for Web with sRGB

**Comment by kristinashu** [comment]
Ok so I ink dropped a screen cap of the code generated side banner and got #f1f1f1. I put that as the bear's background in Photoshop and it seems to work. 

Can you test on your screens to see if you can see a border?
https://foundation.mozilla.org/privacynotincluded/product/Parker%20Teddy%20Bear/

**Comment by beccaklam** [comment]
Looks good to me @kristinashu! No border.

**Comment by kristinashu** [comment]
@gvn I've added 10 products to the CMS! But I'm finding it hard to crop a photo in a way that works for both the product hero banner and the thumbnail (product hero banner has too much grey around it and thumbnail doesn't have enough). Do you think this would work:
- I crop the images they are as big as possible in the square so they work in the hero image
- Dev adds a grey border around each thumbnail image (~28px all around)

Screen cap from prod:
Too much space 
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/1068783/46548323-9b811880-c883-11e8-8c9a-0710cef95bec.png">

Not enough space
<img width="699" alt="image" src="https://user-images.githubusercontent.com/1068783/46548492-0f232580-c884-11e8-83da-341edf0b1ad8.png">

I also think the making the hero image 400x400 instead of 500x500 will help. Seems like the hero banner is taking up too much vertical space.
![image](https://user-images.githubusercontent.com/1068783/46548606-6f19cc00-c884-11e8-9fe6-d28802079861.png)

If this makes sense to you then I'll add it to the QA ticket and get cropping on the images.

**Comment by gvn** [comment]
As long as the cropping is consistent we can easily add padding around the thumbnails to expand the grey border!

**Comment by kristinashu** [comment]
Cool, thanks! I've re-cropped all the images so they fill the square better and added the padding note to the QA ticket.
