### ISSUE TITLE
Buyers Guide: add content to cms

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1867]
CMS should be ready for content as early as next week.

Dev wise we will need all _high priority_ QA done https://github.com/mozilla/foundation.mozilla.org/issues/1860, categories done, and pushed live by Oct 4.

### To do
- [ ] Jen to finalize content Oct 5
- [x] Kristina to upload content
- [ ] Jen to QA all content once it's all in
- [ ] Design to QA all content layout once it's all in

**Comment by kristinashu** [comment]
@beccaklam live site is ready for content entry! Let's add a few to test it out https://foundation.mozilla.org/cms/buyersguide/product/

**Comment by kristinashu** [comment]
@xmatthewx @beccaklam I've updated the [doc](https://docs.google.com/document/d/1iSHloKSuhJONihayIv12b2Ll7zNcGbBjkwXR7hk_Wk0/edit?usp=sharing) asking people to help add content (along with some basic instructions). Can you please take a look at it and then I'll give it to Ashley to share out and ask for volunteers.

**Comment by beccaklam** [comment]
@kristinashu Doc looks good, just added a note that for price the input doesn't need a dollar sign. Played with the nintendo switch content. Just thinking that when we give them the content we should format it so that it matches the cms inputs.

**Comment by kristinashu** [comment]
Yea good call! We can delete the $ from the spreadsheet field and make sure all the working matches up before people start importing.

**Comment by kristinashu** [comment]
Categories are added! 

It's all on Jen now to add any missing content and to QA it. She will do that this weekend. Closing this ticket.
