### ISSUE TITLE
Buyers Guide: user testing & feedback at MozFest

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1868]
While we're promoting the guide at MozFest https://github.com/MozillaFoundation/Design/issues/281 we should take this opportunity to also get some casual user feedback.

Let's make sure whoever is at the Buyers Guide booth is logging comments and feedback from users. 

To do:
- get advice from @taisdesouzalessa 
- have a few casual user testing questions (mostly just watch and hear what people say while they use it)
- we could:
  - make a sign: users can write feedback themselves and designers/staff can write users thoughts
  - have a physical notebook or google doc for designers/staff to write notes in
- find out who will be running the booth and onboard them

cc @beccaklam

**Comment by xmatthewx** [comment]
I've started [a doc](https://docs.google.com/document/d/1NxJUSMjgcjdkaorXko7a9Rm_9h3TZge7p5pCUeeUqO0/edit#) to gather ideas on buyer's guide things we might test at mozfest. Drop in your thoughts @kristinashu @beccaklam @natalieworth

**Comment by kristinashu** [comment]
We can merge with staff feedback in the QA doc https://docs.google.com/document/d/13C0gMgLM9nwhcU1C31dNpQiegbsWzylYESVRLGLa-jM/edit?usp=sharing

**Comment by xmatthewx** [comment]
Yep, good thinking, there might be some feedback worth adding to these testing prompts.

**Comment by kristinashu** [comment]
w00t got some great feedback, follow up in https://github.com/mozilla/foundation.mozilla.org/issues/2072
