### ISSUE TITLE
Buyers Guide: holiday style banner

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1870]
The top banner needs to have more of a holiday feel https://redpen.io/p/qz6bdb2811e058ffb1
- copy: a holiday guide to put your safety first
- image must work on narrow and wide screens
- set's stay away from full-on Christmas look but it is a gift guide so maybe wrapped packages or winter theme could work??
- this look and feel could be applied to some of the promo material (at mozfest and beyond!)

**Comment by kristinashu** [comment]
w00t @natalieworth is gonna help out with this! 

@beccaklam can you add any other thoughts/guidance you have? Is that ^ the copy Jen said?

**Comment by beccaklam** [comment]
@kristinashu @natalieworth yup that's the copy! yaaay collaboration!

**Comment by natalieworth** [comment]
Updated the banner mockups here: 
https://redpen.io/p/wec2dd550a2a545c06
cc @kristinashu @beccaklam

**Comment by natalieworth** [comment]
![06_pni-splash](https://user-images.githubusercontent.com/14876567/46509559-46e48b80-c7f8-11e8-9712-fd0a765b70b0.jpg)

**Comment by natalieworth** [comment]
Blender illustration file for reference:
[blender-illustration-file.zip](https://github.com/mozilla/foundation.mozilla.org/files/2448529/blender-illustration-file.zip)

**Comment by beccaklam** [comment]
@natalieworth So beautiful Nat! Love the snowflakes! Just left a little comment: wondering if we can make one of the snowflakes bigger/overlap with the Nintendo switch so when it crops on the desktop/tablet views we get more snowflakes. The mobile is perfect.

**Comment by kristinashu** [comment]
Let's run with this! I've attached the jpeg to the implementation ticket.
