### ISSUE TITLE
Buyers Guide: Add seal of approval 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1873]
We have to go ahead on this so we will need to design three seals. Each product will feature one of the three seals.

WIP copy is:
- Meets Mozilla’s minimum security standards
- Warning: does not meet Mozilla’s minimum security standards
- Can’t determine if it meets meets Mozilla’s minimum security standards

Matthew's sugestion:
- `Secure`, `Not Secure`, `Unsure`
- each label could have that text large and then a small `Tested by Mozilla` underneath

cc @beccaklam

**Comment by kristinashu** [comment]
<img width="204" alt="screen shot 2018-09-28 at 1 46 28 pm" src="https://user-images.githubusercontent.com/1068783/46487785-c13fec00-c7b5-11e8-8be6-79e9953d1c0f.png">
<img width="185" alt="image" src="https://user-images.githubusercontent.com/1068783/46487870-ef253080-c7b5-11e8-94e2-3b7a69ec31cc.png">
<img width="313" alt="image" src="https://user-images.githubusercontent.com/1068783/46487948-2b589100-c7b6-11e8-89f2-8114e842cebc.png">
@beccaklam  what was the one you had at the start?

**Comment by kristinashu** [comment]
@xmatthewx I've added your copy suggestion above. Let us know if you think of anything else!

**Comment by kristinashu** [comment]
Rebecca designed some seals. I've placed my favorite version into the comps.

There are quite a lot of products that are "secure" and quite a lot that we "can't determine" and just a few that are "not secure". I am going to recommend to Jen that we just don't show any badge for product we can't determine. Do you for see any issues with that? I think users will understand that if there is no seal of approval on a product then we either haven't gotten to reviewing it yet or we just can't determine. 

@xmatthewx do you have any thoughts here?

https://redpen.io/we4fedfbca381f4804
https://redpen.io/fk5813dda329fda302
![product wide copy 2x](https://user-images.githubusercontent.com/1068783/47313460-d8733c00-d5f3-11e8-8b8e-1e150b254163.jpg)
![product small copy 2x](https://user-images.githubusercontent.com/1068783/47313459-d8733c00-d5f3-11e8-92c4-dec31b6f3711.jpg)

**Comment by xmatthewx** [comment]
These look fantastic: bold, easy to read, instill confidence. 

Will we use "Unsure" and a question mark for the 3rd badge?

**Comment by kristinashu** [comment]
There are quite a lot of products that we are "unsure" about. I am going to recommend to Jen that we just not show any badge for product we can't determine. Do you for see any issues with that? I think users will understand that if there is no seal of approval on a product then we either haven't gotten to reviewing it yet or we just can't determine.

**Comment by kristinashu** [comment]
Yay Jen is cool with not showing a badge for `unsure`

Just running language past the rest of the team.
