### ISSUE TITLE
Buyers Guide: Integrate How To Use This Guide text on Product page (and maybe add accordions to Can It Spy On Me section)

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1874]
Also,

Think through how to incorporate 'How To Use This Guide' content. Having an accordion at every section seems excessive. 

- Main thing people asked about at MozFest was what the unexpected reasons were in "Shares your information with 3rd parties for **unexpected reasons**" Could mainly just highlight that?

- Add link to About page?

**Comment by beccaklam** [comment]
Round 1 ideas: https://redpen.io/to0653be7377b7ef63

**Comment by beccaklam** [comment]
We also dropped in the 'unexpected reasons' explanation from the 'How To Use This Guide' content into an accordion on every product page.

**Comment by beccaklam** [comment]
@kristinashu Do you think adding the link solves the need to add an accordion to the 'Can it spy on me' section? Or do we need further exploration?

**Comment by kristinashu** [comment]
I think it's good! We can keep an ear out to see if anyone complains about it...
