### ISSUE TITLE
Buyers Guide: Identify GA Events to track

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1887]
The Buyer's Guide is awesome and will soon land some fab new features. Let's make sure we've got robust event tracking in place. 

I've started a new tab in our spreadsheet with a few things we might track, but I leave it to designers to identify all the important things to track. Let's chat after stand one day this week if anyone needs help getting oriented on this stuff.

Next steps
 - [x] add events to [spreadsheet of events](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=980429434)
 - [x] mw to review labels to align with other properties
 - [x] file ticket for engineering

**Comment by kristinashu** [comment]
@xmatthewx I've added all the possible clickable things. Can you please review and let me know if any of them aren't possible or not necessary? I'm not sure about the CMS generated things like accordions and customer support links.

**Comment by xmatthewx** [comment]
Thanks. Very helpful. I've adjusted things and prioritized most important things to count.

@alanmoo - I think this is ready for a technical review. The goal is to capture key events that won't show up otherwise, to understand if, when, and where people are taking meaningful actions.

**Comment by xmatthewx** [comment]
done! yay! filed implementation ticket #1925

**Comment by kristinashu** [comment]
w00t! thank you!
