### ISSUE TITLE
Buyers Guide: comments

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1889]
Based on design in #1739
Comps https://redpen.io/p/qz6bdb2811e058ffb1
Follow up from larger product page #1819

### Comments
- same functionality as [live site](https://advocacy.mozilla.org/en-US/privacynotincluded) (except without any localization)
- each product has its own comment thread
- put Jen Caltrider and Kristina as moderators 

### Comp
![red-pen-bcdf377a-2c12-459d-f032-139264485f47](https://user-images.githubusercontent.com/1068783/46363898-25817500-c629-11e8-9b3d-3994dc652637.jpg)

**Comment by kristinashu** [comment]
PR https://github.com/mozilla/foundation.mozilla.org/pull/1948

**Comment by alanmoo** [comment]
@cadecairos I think moderators just need to be added and then we can close this.

**Comment by cadecairos** [comment]
Folks will need to create accounts, then we can promote them to moderator.

**Comment by kristinashu** [comment]
Do moderators need to create a general Talk account or specific to this instance? Jen and I both have accounts [firstname]@mozillafoundation.org, will that work?

**Comment by kristinashu** [comment]
Ok Jen and I have both login on prod

**Comment by alanmoo** [comment]
Me too

**Comment by cadecairos** [comment]
You've all been granted permissions
