### ISSUE TITLE
Buyers Guide QA: P1 product detail page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1892]
Follow up from https://github.com/mozilla/foundation.mozilla.org/issues/1860
Comps https://redpen.io/p/qz6bdb2811e058ffb1

### Images
- [x] hero: banner is taking up too much vertical space, update image size from 500x500 to 400x400

### Intro
- [x] narrow layouts: copy link should be moved lower down ([see comps](https://redpen.io/fk5813dda329fda302))

### Criteria
- [x] P1: make product title link through to buy product (url is already in cms)
- [x] P1: undetermined face has been updated from green to gray [icon-face-neutral.svg.zip](https://github.com/mozilla/foundation.mozilla.org/files/2480810/icon-face-neutral.svg.zip)
- [x] P1: update "Shares your information with third parties" to "Shares your information with 3rd parties for unexpected reasons" (from Abigail)
- [x] add "Customer support" text above list of ways to contact them ([see comp](https://redpen.io/we4fedfbca381f4804))
- [x] P1: remove mailto for email (usually just a url to contact page)
- [x] **P1: make the Grade text linkable (most products will link to a unique external url)**
- [x] **P1: completely remove "Requires an account" question**

### Related Products
- [x] P1: mobile: image needs vertical spacing
- [x] mobile: images should be two across, not just one large one https://redpen.io/fk5813dda329fda302
Screen cap from staging: 
<img width="507" alt="image" src="https://user-images.githubusercontent.com/1068783/46364552-fc61e400-c62a-11e8-9d6a-e580b8d7c64d.png">

### Updates
- [x] **P1: if no updates are in this section, then the entire section should be hidden from users**

**Comment by mmmavis** [comment]
@kristinashu 

> P1: make the Grade text linkable (most products will link to a unique external url)

Where can I find the external url you mentioned?

**Comment by kristinashu** [comment]
Each product will link to a different url, so this should be added as a field in the cms.

Does that make sense? Happy to hop on a call and chat through all of these if you like.

**Comment by kristinashu** [comment]
This is a big ticket so I've moved all those P2's the a new ticket. 

The only remaining things for this one is - P1: completely remove "Requires an account" question. 

After that, please close!

**Comment by kristinashu** [comment]
🎉 yay thank you @mmmavis!
