### ISSUE TITLE
Buyers Guide: nav QA

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1893]
Follow up from https://github.com/mozilla/foundation.mozilla.org/issues/1818
comps https://redpen.io/p/qz6bdb2811e058ffb1

Link icon svg [icon-link.svg.zip](https://github.com/mozilla/foundation.mozilla.org/files/2448497/icon-link.svg.zip)
Share icon svg [icon-share.svg.zip](https://github.com/mozilla/foundation.mozilla.org/files/2448498/icon-share.svg.zip)

### Main Nav
- [ ] share icons with the same functionality as [live site](https://advocacy.mozilla.org/en-US/privacynotincluded) - will be done in #1899
- [x] update style of Donate button - hover state color #FF0000
- [x] Main nav is not sticky
- [x] Mobile Only: Share + donate options overlay when user clicks share icon. Behavior similar to foundation site's hamburger menu on mobile.

### Categories Nav
- [x] should be sticky
- [x] font weight 700 instead of 900
- [x] font size from 17px to 15px (new update so that it fits better on all screen widths)
- [x] Nav container should be consistent height (right now it changes depending if selected state bar is there or not)

![red-pen-22532bcd-7d56-415a-b8a8-f02377b4aa09](https://user-images.githubusercontent.com/1068783/46685910-7bb36280-cbab-11e8-988c-08dedcfa4e0b.jpg)
![red-pen-b853baf2-10c7-4bc7-a491-0530187c4509](https://user-images.githubusercontent.com/1068783/46685916-8110ad00-cbab-11e8-93e3-f65de1c158d7.jpg)
![red-pen-afd8173c-dd75-4f3a-b6ac-4816a95e10b0](https://user-images.githubusercontent.com/1068783/46685919-82da7080-cbab-11e8-809b-0a86a5396d0f.png)

**Comment by mmmavis** [comment]
@kristinashu not sure if I got the right version of Sketch file from Abstract - but the mobile share overlay I saw in the Sketch is like below. Can you let me know which design I should go with?

<img width="360" alt="image" src="https://user-images.githubusercontent.com/2896608/46997257-1f34d380-d0d4-11e8-8720-b6d04790f037.png">

**Comment by kristinashu** [comment]
Oh weird! Do you have the latest version of Sketch or did you accidentally delete something? Please go with the version at the [top of this ticket](https://github.com/mozilla/foundation.mozilla.org/issues/1893#issue-366010329) and what is in [Redpen](https://redpen.io/ef43c1d04260c0b688).

I've also attached the Sketch file, in case it's an Abstract issue [Buyers Guide copy.zip](https://github.com/mozilla/foundation.mozilla.org/files/2483693/Buyers.Guide.copy.zip)
