### ISSUE TITLE
Buyers Guide: OG Tags for shares (required for MozFest) 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1899]
At MozFest, we will have a raffle to incentive people sharing and commenting on products in the buyer's guide. To do this well, we'll need OG Tags in place for nice tweets with good description and images. 

 - [ ] Step 1: engineer with logo and basic description (fail proof fallback)
 - [ ] Step 2: gather ideal description and image (this will take a minute)
 - [ ] Step 3: build out with optimized content

cc @alanmoo @caltrider @beccaklam to make it so

**Comment by alanmoo** [comment]
@mmmavis This is something you have experience with, let's talk soon about if you can help out with this.

**Comment by mmmavis** [comment]
@alanmoo we will have to make sure `og` tags related code is generated on server side in order for this to work. I think Pulse still has issues around this due to the same reason + getting it to work with `react-router`'s routes with params.

**Comment by kristinashu** [comment]
I'll get copy from Jen for this and then add it here.

**Comment by kristinashu** [comment]
Adding a note from @Pomax that we will need both OG _and_ a Twitter share card.

**Comment by beccaklam** [comment]
@kristinashu @mmmavis @alanmoo  Sorry for the late notice on this but for tracking engagements at MozFest (with a goal of 5000 in mind), Jen and I were wondering if it would be possible to set up unique social shares on each product page. This would increase the ways people could engage with the guide in a manner we could count. We know it's late in the game though, so if it's not feasible within the timeline, that's fine.  
![share-question](https://user-images.githubusercontent.com/20977376/46805367-d9be8200-cd32-11e8-8546-710bf50ddfad.jpg) cc: @caltrider

**Comment by kristinashu** [comment]
### Here's a summary

#### For general share:
- user clicks a share icon in the header
- user copy and pastes one of these urls
  - http://foundation.mozilla.org/privacynotincluded/
  - http://foundation.mozilla.org/privacynotincluded/[category]
  - http://foundation.mozilla.org/privacynotincluded/[about]
- share copy: "I found this really useful website and wanted to share. It’s @Mozilla’s holiday buyer’s guide to help understand what connected products are safe and which ones aren’t. So you don’t give someone a gift that could spy on them this holiday. It’s at PrivacyNotIncluded.org"
- image [kristina to attach]

#### For product page share:
- user copy and pastes url for a product detail page http://foundation.mozilla.org/privacynotincluded/[product]
- we do not provide copy
- image is the product page's hero image

#### For product page creep-o-meter:
- after voting a user clicks s share icon in the creep-o-meter section
- copy: "I think this product is CREEPY. What do you think? Check out the Creep-O-Meter over on @Mozilla’s PrivacyNotINcluded.org holiday buyer’s guide.
[version depending on a users vote: CREEPY, NOT CREEPY, NOT REALLY ALL THAT CREEPY, KINDA CREEPY]
- image is the product page's hero image

cc @gvn

**Comment by kristinashu** [comment]
@alanmoo @mmmavis just to make sure we're on the same page from our meeting...
- P1: Nav share as recommended above 
- P1: for now, Product creep-o-meter shares will just do the same as Nav share
- P2: later, make it so Product creep-o-meter share product url and custom message as recommended above
  - we will won't use Share Progress 
  - will use FB API

**Comment by kristinashu** [comment]
Update: 

Yay @mmmavis is done with the shares in the nav https://github.com/mozilla/foundation.mozilla.org/pull/1926

Now that Alan has finished with creep-o-meter, Mavis can set those up too.

Product page shares should:
- FB, Twitter, Email will link to product page
- Tweet + Email will give pre-populated text (editable by user): "I think this product is CREEPY. What do you think? Check out the Creep-O-Meter over on @mozilla’s PrivacyNotINcluded.org holiday buyer’s guide."
[version depending on a users vote: "CREEPY" (first two bars), "NOT REALLY CREEPY" (middle), "NOT CREEPY" (last two bars)]
- FB won't have any pre-populated text
