### ISSUE TITLE
Add filter to wagtail profile component

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1900]
For listing people it would be helpful to have a filter that tests whether a profile has an image or bio. 

Profiles with one of those are useful, profiles with none much less so. This would help program staff launch a page (e.g. new cohort in mentor program), knowing that some participants still need to fill out their info. 

For authors, this could be one checkbox for has_content (image or bio), or checkbox for each. More simplicity vs more control. 

@Pomax does this makes sense? What's the tech lift to land an enhancement like this? (assume I give you admin comp with copy)

Here's a demo list view: https://foundation.mozilla.org/cms/pages/221/edit/preview/

**Comment by Pomax** [comment]
This feels like we might be trying to solve a problem for program staff by fixing the content for all users. I think if we still want to do this, we probably need to figure out who this is a solution for, and whether there is a more appropriate place to solve this (like the admin interface)

**Comment by kristinashu** [comment]
This component is currently only used on Fellowship page and one mentorship page (which is going away) and might eventually be used for mozfest staff, wrangler, and maybe speakers. All these are fairly thoughtful and controlled so I think we should put the onus on staff to unsure profiles are filled out sufficiently and not on tech.

I'm going to close, but please re-open if you still see the need for this.
