### ISSUE TITLE
Remove deprecated Figure component

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1902]
This requires access to the production environment, but we should remove all instances of deprecated components using the Block Inventory feature to find them, and then remove those components from the codebase.

**Comment by kristinashu** [comment]
I will go review https://foundation.mozilla.org/cms/inventory/ and make sure no deprecated components are in use.

cc @Pomax

**Comment by alanmoo** [comment]
Once you've confirmed, this is probably something @youriwims could take care of.

**Comment by kristinashu** [comment]
These are the deprecated components and all instances of them have been removed on prod so they are ready to be removed.

- [ ] Image text (related to - Updates to Image Text2 component #2693)
- [ ] Figure
- [ ] Figuregrid (can be done in #1486)

<img width="398" alt="image" src="https://user-images.githubusercontent.com/1068783/53747874-12cdcf00-3e59-11e9-8f89-520a97972dde.png">
