### ISSUE TITLE
Add some details about l10n to README

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1903]
I was hitting a wall until I realized a new model that I created needed to be added to `translation.py`. Let's update the README to point this out somewhere- I was searching through it for any mention of "translate" or "localization" to see if it could help me but nothing was there.

cc @Pomax in case you have any useful thoughts.

**Comment by Pomax** [comment]
yeah: maybe we should mention what we're using, because the `wagtail-modeltranslations` readme tells you to do this already

**Comment by SunveerSingh** [comment]
Hello, I would like to work on this! please let me know in Readme where should it be added. and some details that needs to be added

**Comment by alanmoo** [comment]
At the very least, we need a reference to `wagtail-modeltranslations`, as Pomax noted. To be clear about what else is needed, I would suggest spinning up the repo and attempting to add a new Wagtail page type model, and documenting where code needs to be put in to enable translations.

**Comment by Pomax** [comment]
we added this a while ago without closing this issue
