### ISSUE TITLE
Update Participate factory

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1906]
The ParticipatePage factory is still generating the original page. It needs to generate a ParticipatePage2 instead.

While we're at it, we should entirely remove the original Participate model.

**Comment by mmmavis** [comment]
It turns out that we can't just simply rename the model. 

I've filed a question on [Stackoverflow](https://stackoverflow.com/questions/54318017/wagtial-how-to-properly-rename-a-wagtail-page-model).

**Comment by Pomax** [comment]
It looks like wagtail-modeltranslations is getting in the way of removing models, where removing it from `translations.py` breaks the `makemigrations`/`migrate` commands, so I've filed an issue over on https://github.com/infoportugal/wagtail-modeltranslation/issues/226 and hopefully there's a clean and simple way to _remove_ a model (and equally hopefully, rename a model)

**Comment by alanmoo** [comment]
Closed by #2826
