### ISSUE TITLE
Buyers Guide: launch Oct 22

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1916]
### Launch dates
- [x] Launch the new guide Oct 18 
  - https://foundation.mozilla.org/privacynotincluded/

Update url redirects Oct 22
- [x] Redirect https://privacynotincluded.org (and www.privacynotincluded.org) to https://foundation.mozilla.org/privacynotincluded
- [x] Redirect https://advocacy.mozilla.org/privacynotincluded to https://privacynotincluded.org
- [x] make sure with/without www work
- [x] redirect the old subpages to https://foundation.mozilla.org/privacynotincluded/
- [x] ~take down the old site~ - Nothing to remove. The domains were redirecting, and the advocacy site hosts other content still.
- [x] [check google indexing](https://github.com/mozilla/foundation.mozilla.org/issues/2000)
- [x] review [check list](https://github.com/mozilla/foundation.mozilla.org/issues/1940)

@alanmoo can you please add relevant context and assign to the ticket?

**Comment by xmatthewx** [comment]
Be sure to avoid a loop. We should probably let privacynotincluded.org propagate for 24 hours before we do the advocacy redirect.

**Comment by xmatthewx** [comment]
Advocacy redirect should use a wildcard to redirect all product urls

**Comment by cadecairos** [comment]
I've redirected `privacynotincluded.org`, `www.privacynotincluded.org`, `privacynotincluded.com`, `www.privacynotincluded.com`, `advocacy.mozilla.org/*/privacynotincluded/*` to `foundation.mozilla.org/privacynotincluded`.

There's no site to take down, since the privacynotincluded.org (and .com) redirected to the advocacy domain, and the PNI site there is part of the advocacy.mozilla.org code repo.

**Comment by kristinashu** [comment]
Can you also please redirect https://foundation.mozilla.org/en/privacynotincluded/ (or https://foundation.mozilla.org/*/privacynotincluded/) to https://foundation.mozilla.org/privacynotincluded/

**Comment by alanmoo** [comment]
Lets do that last set as a temporary in case we localize this next year.

**Comment by xmatthewx** [comment]
Good catch @kristinashu!

**Comment by alanmoo** [comment]
@kristinashu Is that because of the 404 pages? We don't link to a localized version of the site anywhere else.

**Comment by kristinashu** [comment]
Opened https://github.com/mozilla/foundation.mozilla.org/issues/2023 so we can close this and deal with https://foundation.mozilla.org/en/privacynotincluded/ separately.
