### ISSUE TITLE
Buyers Guide: QA category page 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1923]
Follow up from https://github.com/mozilla/foundation.mozilla.org/issues/1821

### Font styling
- [x] Category title .h3-heading
- [x] Disclaimer .normal with italic 
- [x] Disclaimer should be moved to the bottom of the page
- [x] Product company .h6-heading-uppercase
- [x] Product name .h5-heading

![category 2x](https://user-images.githubusercontent.com/1068783/46822544-a2ef6880-cd40-11e8-8014-3038bf5a8d22.jpg)

**Comment by Pomax** [comment]
addressed in the same PR
