### ISSUE TITLE
Buyers Guide: refactor categories page to use bootstrap layout

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#1924]
Right now it uses the old site's flex solution and that should be bootstrappable, cleaning up/tightening both the scss and template html

**Comment by kristinashu** [comment]
I'm going to add: remove stroke (and shadow?) that is around each image.

**Comment by Pomax** [comment]
I'll file that as separate issue, since that's not refactoring but actual styling changes.
