### ISSUE TITLE
Buyers Guide: Add GA Event tracking

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1925]
As discussed in https://github.com/mozilla/foundation.mozilla.org/issues/1887, we want to add GA Event tracking to the guide. 

The goal is to capture key events that won't show up in analytics otherwise, to understand if, when, and where people are taking meaningful actions.

The events and labels are listed and prioritized in [this spreadsheet](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=980429434).

**A note on tracking filtering**
-----------------------
Most of the events are simple and ordinary. The filter stuff (line 5) could be tracked in a few different ways. Let's try and keep the filter event simple and free of noise. The goal is to understand if people are using the filter feature at all, and when they do it. 

Problem: We could track open, close, and change on slider and radio button. That's probably more data than we need.

Proposal:  
 - trigger the event when filter modal is _closed_ IF any change has been made on any filter
 - do it when the function is called, in case we enable people to close with a tap out side the modal
 - after modal is closed and event is triggered, clear the var that tracks if filters were changed

Make sense?

**Comment by kristinashu** [comment]
cc @arlissc

**Comment by kristinashu** [comment]
Note: for OKRs, we need to distinguish "engagements" for the soft launch (MozFest) vs the full launch

**Comment by xmatthewx** [comment]
We can filter reports by date, location, and incoming link to distinguish soft launch vs full launch. But, we won't modify the tracking itself in any other way.

**Comment by kristinashu** [comment]
Right! Thanks for clarifying. No, don't need modify tracking.

**Comment by Pomax** [comment]
Product GA tracking landed in the codebase, so if you agree @xmatthewx @kristinashu it would be nice to close this and then file follow-ups for the GA events that we still need.

**Comment by kristinashu** [comment]
I'm good to close and do the rest in a new ticket.

@xmatthewx @cadecairos do you know where these will show up? Is it under foundation site or separate. If it's separate than can you please give me access?

**Comment by kristinashu** [comment]
Ok, I don't see them but as long as someone can!
