### ISSUE TITLE
Buyers Guide: Create Launch Checklist

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1940]
Let's avoid snafus and create a launch checklist for the buyer's guide. Let's take this as an opportunity to create a stand list we can use when launching any significant page, site, or tool. 

I've started [a doc](https://docs.google.com/document/d/1cCuILd6Dwcr0uSSH69qFkeKDNiV_i50fBg0vH6R8nNQ/edit#heading=h.5uajtx709lys).

**Comment by cadecairos** [comment]
This might help: https://github.com/MozillaFoundation/mofo-devops/blob/master/docs/go-live.md

**Comment by xmatthewx** [comment]
We walked through the list as a group. I've assigned issues to file via comments in the [doc](https://docs.google.com/document/d/1cCuILd6Dwcr0uSSH69qFkeKDNiV_i50fBg0vH6R8nNQ/edit#heading=h.5uajtx709lys). After that's done, @kristinashu can sort the board and close this.

**Comment by alanmoo** [comment]
I created one last issue for performance, as that was the only thing left on the doc.
