### ISSUE TITLE
Buyers Guide: improve the product model API for creepiness/confidence

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#1941]
We currently aggregate votes into a `product.votes` property, which is an unordered set of untyped objects that must be inspected before values can be retrieved. It would probably be better if we come up with a way to aggregate the data such that `product.creepiness` and `procuct.confidence` are (`@property` decorated?) props that can be used directly in templates and template logic.

**Comment by cadecairos** [comment]
Does this seem more usable:

```
>>> p = Product.objects.get(id=5)
>>> p.confidence
{'0': 9, '1': 6}
>>> p.creepiness['average']
57
>>> p.creepiness['vote_breakdown']
{'0': 4, '1': 0, '2': 2, '3': 0, '4': 5}
```
