### ISSUE TITLE
Buyers Guide: clean up urls

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1951]
From @alanmoo: 

We should make sure our product urls are clean before launch. I think they have spaces in them right now, which feels...weird.

**Comment by alanmoo** [comment]
Thanks for creating this. I realized product names might cause a problem, and it looks like they do- https://foundation.mozilla.org/privacynotincluded/products/Harry%20Potter%20Coding%20Kit%20%E2%80%93%20Build%20a%20Wand for example.

@cadecairos or @patjouk can you help us sanitize these URLs?

**Comment by cadecairos** [comment]
Do we still want URLs to use product names? using ID numbers makes more sense, and will prevent weird decisions being made, like "do we use underscores and substitute them for names when looking up a product?" and "Don't include URL unsafe text in your product names!"

**Comment by alanmoo** [comment]
Goooooood question. I don't particularly care. @kristinashu?

**Comment by cadecairos** [comment]
Another option would be to have a slug field generated on save from the title value, which can be used in lookups

**Comment by kristinashu** [comment]
Is this settled? The URL should be the product name, makes it much easier to revisit and/or share a page. But what to do with spaces I don't know! Can it just remove them for the URL? Example https://foundation.mozilla.org/privacynotincluded/products/HarryPotterCodingKitBuildaWand or dashes https://foundation.mozilla.org/privacynotincluded/products/Harry-Potter-Coding-Kit-Build-a-Wand

**Comment by cadecairos** [comment]
I'm sorry, I was typing on my cell phone while walking, fat fingered the close and comment button.

**Comment by cadecairos** [comment]
I think I can solve this by slugifying the title and saving it along with the model.

**Comment by kristinashu** [comment]
Lol ok cool. Yeah I guess we should follow what rest of site does and use dashes https://foundation.mozilla.org/en/opportunity/tech-policy-fellows/

**Comment by kristinashu** [comment]
Not sure if it's related but when I go to https://foundation.mozilla.org/privacynotincluded/ and click on the following product links, I get a 404:
- https://foundation.mozilla.org/privacynotincluded/products/BB-8%20Robot
- https://foundation.mozilla.org/privacynotincluded/products/Amazon%20Echo%20%26%20Dot
- https://foundation.mozilla.org/privacynotincluded/products/Harry%20Potter%20Coding%20Kit%20%E2%80%93%20Build%20a%20Wand
- https://foundation.mozilla.org/privacynotincluded/products/Precision%20Cooker%20Sous%20Vida%20Wifi%20%2B%20Bluetooth
- https://foundation.mozilla.org/privacynotincluded/products/Amazon%20Echo%20Show%20%26%20Spot
- https://foundation.mozilla.org/privacynotincluded/products/Bose%20QuietComfort%2035%20II%20%28w/Alexa%20or%20Google%20Assistant%29
- https://foundation.mozilla.org/privacynotincluded/products/Quell%202.0%20Wearable%20Pain%20Relief
- https://foundation.mozilla.org/privacynotincluded/products/2.0%20Smart%20Water%20Bottle
- https://foundation.mozilla.org/privacynotincluded/products/Withings%20Body%20Wi-Fi%20Scale

**Comment by cadecairos** [comment]
Update: I've got a working implementation of automatically slugify-ing the title field. I'm just working on adding it in where product name was used before, and I also need to update the admin form for products to not show the slug field, since it's auto generated.
