### ISSUE TITLE
Buyers Guide: Add filters to home page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1958]
Based on design in https://github.com/mozilla/foundation.mozilla.org/issues/1739

Comps https://redpen.io/p/qz6bdb2811e058ffb1

Follow up from https://github.com/mozilla/foundation.mozilla.org/issues/1820

Filter svg icon [icon-filter.svg.zip](https://github.com/mozilla/foundation.mozilla.org/files/2448495/icon-filter.svg.zip)

- [x] Filter 'bubble' that expands (animation opportunity!) upon click into a larger bubble containing filtering options based on 'creepiness' and 'likelihood to buy' example: https://teatrlalka.pl/en/kalendarz

- [x] User is able to filter products according to aggregated scores of creepiness (creep-o-meter slider with range) and likelihood to buy (radio buttons)

- [ ] Empty state for filters shows text and reset link https://redpen.io/bsc0229990715a84c8

- [ ] Tapping close icon or anywhere outside of the bubble closes it

**Comment by kristinashu** [comment]
@Pomax this is ready to be implemented. I know we talked about holding off on it but after some feedback at mozfest, we think this is a valuable feature to have.

**Comment by Pomax** [comment]
Are there also comps that make it clear how all these filters relate back to the products that are being shown? (E.g. just seeing images getting shuffled around leaves no clues for the user to determine what the actual ordering is, or what the jumps in filtered value are from one product to the next?)

**Comment by kristinashu** [comment]
I'm not completely sure what you mean but hopefully this helps... the likelihood to buy filter should be obvious since if a user selects thumbs up in the filters then that they will only thumbs up. Creepiness range is trickier since they will have to scroll to see it but pretty sure users understand the general concept of using filters. We are working on designs for adding in text next to the face to better articulate what the facial expression is. Also, we had mocked up tags https://redpen.io/apca47a1799345281b but figured this would be more work to implement so thought it should just be a "nice-to-have" or future feature depending on what feedback we get.

**Comment by Pomax** [comment]
Usually when you have a filter, the "thing you filtered on" is visible in the results, too. So for instance, if we're filtering on creepiness, then the results would have some kind of incidation of what their creepiness is, if we're filtering on likely/not likely, the results would have an indication of what that value is, to explain what they user's seeing, Basically the "ordered set" may be ordered, but not _look_ ordered unless there's something that you can see that explains why things are ordered the way they are.

**Comment by Pomax** [comment]
Do we have a graphic for the wide-eyed face that'll sit on the right of the filter slider?

**Comment by kristinashu** [comment]
Lol you mean the super creeped out face? It should actually be the same as the last face on the homepage when you scroll down. Sorry, I think that wide-eyed one is from an older comp. 

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/1068783/47886529-dc733b00-ddf7-11e8-8cac-5926fe89fc09.png">

**Comment by Pomax** [comment]
no worries, that's what I used in the mean time =D
