### ISSUE TITLE
Buyers Guide: determine if the donate button needs utm arguments

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#1959]
For metrics purposes we might need `utm` arguments on the donate button, so that the donate site understands that a donation is coming in because someone visited the buyers guide rather than any of the other sites/campaigns

**Comment by Pomax** [comment]
Who should be looking at this? @xmatthewx? @WillatMozFdn?

**Comment by WillatMozFdn** [comment]
Oh yes, please, let's track this URL.  Correct URL will be:

https://donate.mozilla.org/?utm_source=foundation.mozilla.org&utm_medium=buyersguide&utm_campaign=buyersguide2018&utm_content=modal

If we're doing it in ES as well as EN, we should probably use for "buyersguide2018ES" and "buyersguide2018EN" for the UTM_campaign tag, respectively.

**Can someone please loop me in on the verbage being used to ask for the donation?**  I have some recent learnings from the October email campaign that could give us a 10-20% lift on donations....thanks!

**Comment by kristinashu** [comment]
So should we do the same utm for both the header donate button and the popup donate button?

https://donate.mozilla.org/?utm_source=foundation.mozilla.org&utm_medium=buyersguide&utm_campaign=buyersguide2018&utm_content=button

**Comment by WillatMozFdn** [comment]
ah, well if we have two buttons, let's vary the utm_content tag, and use "headerbutton" and "popupbutton" if possible .... would that work?  We might be gettin a little over-granular with that, but I actually am curious to see which one works better....

**Comment by kristinashu** [comment]
Ok cool, opened an implementation ticket https://github.com/mozilla/foundation.mozilla.org/issues/2063
