### ISSUE TITLE
Buyers Guide: Updates and Related Products stoped working

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1960]
These two sections used to work but now they don't. In the cms, I have selected the items but then they don't show up on the live page.
<img width="893" alt="screen shot 2018-10-17 at 3 32 42 pm" src="https://user-images.githubusercontent.com/1068783/47120004-0e927380-d222-11e8-9640-7d8fc9b89815.png">
<img width="970" alt="screen shot 2018-10-17 at 3 32 48 pm" src="https://user-images.githubusercontent.com/1068783/47120005-0f2b0a00-d222-11e8-8ea4-d8ab5918e0a3.png">
cc @alanmoo @Pomax

**Comment by kristinashu** [comment]
Heyo this looks related https://github.com/mozilla/foundation.mozilla.org/issues/1913

**Comment by kristinashu** [comment]
cc @cadecairos

**Comment by cadecairos** [comment]
This issue isn't related to the warning in #1913
