### ISSUE TITLE
Accessibility review

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#197]
Let's make sure we're following best practices for accessibility while we iterate during member preview.

**Comment by alanmoo** [comment]
As we get closer to public launch we should do an audit. At the very least that would include running this through some sort of test suite that gives advice on what needs to be done to improve accessibility.

**Comment by alanmoo** [comment]
Let's find someone who can give us some guidance on accessibility at Mozilla and possibly audit this. @xmatthewx @hannahkane any ideas?

**Comment by alanmoo** [comment]
Let's make sure key things like navigation and footer are accessible, images have alt tags, links are links, things have focus states.

**Comment by alanmoo** [comment]
Some other things we can do: https://developers.google.com/web/fundamentals/accessibility/how-to-review

**Comment by hannahkane** [comment]
On @alanmoo's todo list to find someone to consult with us on this, with goal of increasing in-house knowledge.

**Comment by xmatthewx** [comment]
@alanmoo is on it! planning a brownbag.

**Comment by alanmoo** [comment]
This is a bit broad for a ticket in this repo. Reconsidering our approach to this.
