### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#198]
Let's chat with MoCo person who can help with some SEO.

**Comment by alanmoo** [comment]
@xmatthewx What's the specific ask on this?

**Comment by xmatthewx** [comment]
Reach out to Peter German for a review of the site and recommendations. I believe he can advice on keywords, marketing not technical recommendations. 

I think we can wait until we're gearing up for a broader public push.

**Comment by Pomax** [comment]
closing this for now - SEO's not been a real concern given the effectiveness of PNI
