### ISSUE TITLE
Buyers Guide QA: improve styling of intro at narrow widths

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1981]
On the homepage:
- [x] improve how the hero image is cropped (show more of the image - maybe crop left side?)
- [x] make intro text wider

Prod
<img width="352" alt="screen shot 2018-10-18 at 7 28 05 pm" src="https://user-images.githubusercontent.com/1068783/47226479-7d341600-d375-11e8-9fa9-0a1256cc7506.png">

Comp
<img width="318" alt="image" src="https://user-images.githubusercontent.com/1068783/47226541-aa80c400-d375-11e8-851a-9ae6740b9c9a.png">

**Comment by alanmoo** [comment]
I'm opening a PR that does what you're actually asking for, but in the process of building it I found myself looking at this which, IMO, might be a better solution for mobile (with a little adjustment- when you scroll down, the face isn't on a background anymore with this design). I'm not saying we should go with this, but wanted to throw it out there as a thing we can do.

![image](https://user-images.githubusercontent.com/1682681/47360508-9a474c80-d6c7-11e8-914b-7c84d3de4ac3.png)

**Comment by kristinashu** [comment]
Your PR looks good! I still prefer to keep the text separate. It's more legible for users and keeps us flexible for a "non-holiday" version of the graphic.
