### ISSUE TITLE
Redirect old buyer's guide links

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1983]
Tuesday October 22:

- [ ] Redirect https://privacynotincluded.org (and www.privacynotincluded.org) to https://foundation.mozilla.org/privacynotincluded
- [ ] Redirect https://advocacy.mozilla.org/privacynotincluded to https://privacynotincluded.org

**Comment by kristinashu** [comment]
Related to https://github.com/mozilla/foundation.mozilla.org/issues/1916
