### ISSUE TITLE
Landscape mode on iPhone X looks odd

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1987]
The background doesn’t span the entire page or something.

https://foundation.mozilla.org

**Comment by alanmoo** [comment]
![2472b46c-aed6-4846-9eb0-d7c536cbe965](https://user-images.githubusercontent.com/1682681/47254726-058de600-d45e-11e8-89a4-6801cb8bf002.png)

**Comment by tristandenyer** [comment]
I noticed this happens in Firefox app on iOS, but works fine in Safari iOS (haven't checked other browsers.)

I was looking into this and trying to set up 'Debugging Firefox OS over WiFi' ( https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_OS_over_Wifi ).  This page seems out of date, and settings panel in neither the Firefox iOS app or the desktop app show anything about debugging over wifi. Am I missing it? Anyone know of another way to debug this in Firefox iOS?

**Comment by alanmoo** [comment]
It also looks weird in Chrome iOS, so perhaps it's a bug in iOS's rendering? Apparently you can't debug a WKWebView page unless you've built the app (Firefox) yourself in Xcode. See [this ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1131671) and I confirmed in Mozilla's Slack.

**Comment by alanmoo** [comment]
Part of this is probably that the `html` element background is `black`, but I'm not sure about the extra horizontal scrolling.

**Comment by tristandenyer** [comment]
(If I assume this correctly) I think the horizontal scrolling you are seeing in the screenshot is the persistent iPhone X grab bar thing at the bottom of the screen. Mine on iPhone X does not scroll horizontally.

**Comment by Pomax** [comment]
This got resolved recently through various PRs that solved issues that had aspects of this showing up even in portrait mode.

**Comment by alanmoo** [comment]
Nope, still there. I think this is something related to the iOS web-view implementation that 3rd party browsers use, so the end result of this may be an Apple bug report, but I want to leave it open for now.

**Comment by Pomax** [comment]
can you check what these three tests do?

1. https://pomax.github.io/nightly-is-upgrading-an-insecure-display-request/ios-scroll-x-test.html
2. https://pomax.github.io/nightly-is-upgrading-an-insecure-display-request/ios-scroll-y-test.html
3. https://pomax.github.io/nightly-is-upgrading-an-insecure-display-request/ios-no-scroll-test.html

**Comment by alanmoo** [comment]
All 3 seem to have y scroll in Firefox on an iPhone XS. (Can you change the background color on them in the future? I think that might make it easier to see)

**Comment by Pomax** [comment]
More tests:

1. https://pomax.github.io/nightly-is-upgrading-an-insecure-display-request/ios-pos-rel-scroll-x.html
2. https://pomax.github.io/nightly-is-upgrading-an-insecure-display-request/ios-pos-rel-scroll-y.html
3. https://pomax.github.io/nightly-is-upgrading-an-insecure-display-request/ios-pos-rel-no-scroll.html

**Comment by alanmoo** [comment]
![unadjustednonraw_thumb_9d5e](https://user-images.githubusercontent.com/1682681/49168840-67b3f380-f306-11e8-81fa-a382f992afd1.jpg)
![unadjustednonraw_thumb_9d5f](https://user-images.githubusercontent.com/1682681/49168841-67b3f380-f306-11e8-8232-21f82249939d.jpg)
![unadjustednonraw_thumb_9d60](https://user-images.githubusercontent.com/1682681/49168842-684c8a00-f306-11e8-9b8f-80b3f08227bb.jpg)
![unadjustednonraw_thumb_9d61](https://user-images.githubusercontent.com/1682681/49168843-684c8a00-f306-11e8-92f9-2cf218206895.jpg)

**Comment by Pomax** [comment]
dafuq. Okay, let's try this on body...

**Comment by Pomax** [comment]
Three more:

1. https://pomax.github.io/nightly-is-upgrading-an-insecure-display-request/ios-rel-body-scroll-x.html
2. https://pomax.github.io/nightly-is-upgrading-an-insecure-display-request/ios-rel-body-scroll-y.html
3. https://pomax.github.io/nightly-is-upgrading-an-insecure-display-request/ios-rel-body-no-scroll.html

**Comment by alanmoo** [comment]
Looks identical to the previous set, by my eye.

**Comment by Pomax** [comment]
I guess that blows a stackoverflow claim that position:relative on the body should make ios fall in line out of the water then.

**Comment by Pomax** [comment]
Once again!

1. https://pomax.github.io/nightly-is-upgrading-an-insecure-display-request/ios-rel-div-no-scroll.html
2. https://pomax.github.io/nightly-is-upgrading-an-insecure-display-request/ios-rel-div-x-scroll.html
3. https://pomax.github.io/nightly-is-upgrading-an-insecure-display-request/ios-rel-div-y-scroll.html

**Comment by alanmoo** [comment]
This is interesting. Seems to work (and this is what I get on iOS Firefox when scrolling the last one to the side) ![image](https://user-images.githubusercontent.com/1682681/49177235-ace22080-f31a-11e8-87a7-cec3b3f1c01c.png)

**Comment by alanmoo** [comment]
Notice the white space, which is visible in all cases. It's matching what's described in the 3rd image of https://webkit.org/blog/7929/designing-websites-for-iphone-x/

**Comment by Pomax** [comment]
Let's solve this in stages. First let's get the overflow fixed for most devices, and then worry about whether we want to spend time fixing a problem only people with a $1200 phone run into.

**Comment by alanmoo** [comment]
Yeah, this ticket is certainly lower priority than #2292. I'm fine leaving this as something a contributor or new hire can pick up on if they have interest.

**Comment by Pomax** [comment]
Is this still affecting us, @alanmoo? (I think we fixed this, but I need your device to confirm =)

**Comment by alanmoo** [comment]
Still wonky.

**Comment by kristinashu** [comment]
@alanmoo is it stillll wonky?

**Comment by alanmoo** [comment]
No, it got fixed somehow! Huzzah!
