### ISSUE TITLE
Buyer's Guide: Updating product names breaks url

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1988]
From Slack:

>Jen Caltrider [7:07 PM]
Heya, just flagging things as I update and review product content this weekend.
The link to the Beeline Smart Bike Compass seems to be broken.
https://foundation.mozilla.org/en/privacynotincluded/products/smart-compass-for-bike/

>Jen Caltrider [7:16 PM]
Ah, apparently if I edit the name of the product, it breaks the product page link. Not sure what to do about that?
I broke the Withings Body Scale too (what’s currently in the CMS is the correct info..it just broke the page link from the category page)

**Comment by cadecairos** [comment]
@caltrider so the url of the product is tied directly to the product name. If name is changed, the URL will change too because it runs it through a process to make it URL safe. 

A refresh of the products/category pages should update links properly. Does the URL rendered on the page not update properly after a refresh?

**Comment by alanmoo** [comment]
The logic behind this being: we probably aren't changing the product name after it's gone live, so it shouldn't be that big of an issue. Does that sound reasonable, @caltrider?

**Comment by caltrider** [comment]
@alanmoo Yes, after I get done reviewing all the products today (I've got about 14 more to go) the product names should be final and not change any more. 

@cadecairos Yesterday it didn't seem the products were coming up after a refresh but today it looks like the products that were broken are working again. The Athena wearable, the Ticwatch Pro, and the FREDI baby monitor are still missing some content, but that is from a different issue that I think @Pomax was working on.
