### ISSUE TITLE
Buyers Guide QA: some products are missing content

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1989]
@caltrider noticed that content for some products just isn't showing up even when all the info has been entered in the cms.

Happening on these pages and possibly others:
https://foundation.mozilla.org/privacynotincluded/products/athena-safety-wearable/
https://foundation.mozilla.org/privacynotincluded/products/ticwatch-pro/
https://foundation.mozilla.org/privacynotincluded/products/fredi-baby-monitor/

Screen caps from prod:

<img width="923" alt="screen shot 2018-10-22 at 9 25 45 am" src="https://user-images.githubusercontent.com/1068783/47304799-7a872a00-d5dc-11e8-95ac-9073a171480d.png">

and:

<img width="949" alt="screen shot 2018-10-22 at 9 25 34 am" src="https://user-images.githubusercontent.com/1068783/47304803-7ce98400-d5dc-11e8-8a93-96bc81ffe8b4.png">

**Comment by Pomax** [comment]
I've filed https://github.com/mozilla/foundation.mozilla.org/pull/1999 to see if that fixes it, but there is an odd difference where foundation.moz seems to use data not found in local dev.
