### ISSUE TITLE
Bust the Google search cache for "privacynotincluded"

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#2000]
Related: #1916 

Searches on Google for "privacynotincluded" show links to `advocacy.mozilla.org`. They redirect properly to the new guide, but we might want to have Google learn they're redirecting to the foundation site-based guide now.

In order to do that we'll need to either wait for it to organically update, or verify the `advocacy.mozilla.org` domain for use on the Google search console. The trouble with that is the quickest way should be to add a meta tag in the homepage, but the site is on very old versions of React and React-Router. An initial investigation left me knowing nothing more about how to inject meta tags into a site using those frameworks.

**Comment by kristinashu** [comment]
Google hasn't figure this out yet... @alanmoo @cadecairos (the right Cade!) what do you think? Time to force it?

<img width="833" alt="image" src="https://user-images.githubusercontent.com/1068783/48156375-289ffe80-e282-11e8-8528-e0a832964939.png">

**Comment by alanmoo** [comment]
Given that this is a combination of the Google algorithm doing its magic and a pain to update, I'm not sure it's worth the effort to validate since it redirects to the right URL once you hit the link. I suspect as the new guide gets shared more, it'll rise to the top of results.

**Comment by kristinashu** [comment]
Ok, works for me. Close this ticket?
