### ISSUE TITLE
remove dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2006]
We have `dangerouslySetInnerHTML` in a few places in our site JS (specifically, jsx) and we _really_ shouldn't be injecting raw HTML.

**Comment by kristinashu** [comment]
@Pomax is the Buyer's Guide related or general foundation site?

**Comment by Pomax** [comment]
General site maintenance: it's something that's affecting our React code rather than anything Wagtail or PNI specific.

**Comment by alanmoo** [comment]
The areas in which we use this [appear](https://github.com/mozilla/foundation.mozilla.org/search?utf8=%E2%9C%93&q=dangerouslySetInnerHTML&type=) to be fields that are not rich-text, but which need a link when rendered on the page. Is the solution to this making those Rich Text Fields?

**Comment by cadecairos** [comment]
if we want CMS content to display as HTML, we need to do this. closing.
