### ISSUE TITLE
Buyers Guide QA: field is blank 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2007]
@caltrider notices: the field under “what does it know about me?” is blank for some products. It should say "Product uses encryption".

Examples:
https://foundation.mozilla.org/privacynotincluded/products/sphero-mini
https://foundation.mozilla.org/privacynotincluded/products/sphero-bb-8-robot/
https://foundation.mozilla.org/privacynotincluded/products/cognitoys-dino/

Screen cap on prod:
<img width="937" alt="screen shot 2018-10-22 at 6 34 36 pm" src="https://user-images.githubusercontent.com/1068783/47329365-3d955480-d629-11e8-9b56-ec58b28c7209.png">

**Comment by alanmoo** [comment]
It looks like this is a text encoding issue. I swapped the regular quotes (`"`) for smart quotes (`“`) and (`”`) and that fixes it. That being said, this should still work so I'll take a look and see if there's a way for us to handle those.

**Comment by kristinashu** [comment]
Cool, thanks for fixing!
