### ISSUE TITLE
Document package-lock.json

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2012]
I can never tell when I'm supposed to commit package-lock.json or how to update it. Let's add this to our documentation. @patjouk when you have a chance perhaps?

**Comment by Pomax** [comment]
Good candidate for adding to an attempt at documenting "universal" things over on https://github.com/mozillafoundation/production ?

**Comment by patjouk** [comment]
That's the plan.

**Comment by cadecairos** [comment]
the plan: Update the production repo explaining the process (Ship updates to package-lock.json, provide link to npm documentation on package-lock)
