### ISSUE TITLE
Buyers Guide: add copy to home page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2021]
If we don't add filters https://github.com/mozilla/foundation.mozilla.org/issues/1958 then we at least need to add copy saying that this is user generated (request from legal).

- [x] Add copy to intro "Products below are rated by users. Click on a product to rate it."
- [x] Zilla Slab, Italic, 18/24, #9B9B9B

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/1068783/47397277-61b56c00-d6e3-11e8-8813-4da5681f22fc.png">

**Comment by Pomax** [comment]
What is the 18/24 intended for? font-size 24, with 18 on mobile, or font-size 18 with 24 lineheight?
