### ISSUE TITLE
Buyers Guide: GA con't

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2024]
Key events have been done https://github.com/mozilla/foundation.mozilla.org/issues/1925 but still a few more in the doc https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=980429434

**Comment by xmatthewx** [comment]
I set up a segment so you can filter most analytics views just for users who hit at least one `/privacynotincluded/` page in their session. 

To view segment (see screenshot)
 1. Tap All Users
 2. Uncheck All Users from list
 2. Search privacy
 3. Select Privacy Not Included
 4. Hit Apply

<img width="986" alt="image" src="https://user-images.githubusercontent.com/53411/47392466-b3adc000-d6ea-11e8-9ae0-596b0da09246.png">

<img width="734" alt="image" src="https://user-images.githubusercontent.com/53411/47392674-43536e80-d6eb-11e8-9eed-68494c73b044.png">

....I believe segments are shared between users, but let me know if that doesn't seem work.

**Comment by xmatthewx** [comment]
Of all these, the site-wide share button will be most important to add, since these shares are part of the key engagement metric we're tracking.

Assigning @alanmoo to triage 😉

**Comment by Pomax** [comment]
@xmatthewx hm, we added event for those already though, are they not showing up? (the primary nav has GA hooked up for both the desktop and mobile views as far as I can see)

**Comment by kristinashu** [comment]
The header shares always share the homepage. But it doesn't look like they are showing up in GA.

**Comment by xmatthewx** [comment]
There were no events for this yesterday. I now see 2 events from today. I think we're good for GA on site wide shares and all the events critical launch. 

Events > Action: Share tap > Category: Site

<img width="321" alt="image" src="https://user-images.githubusercontent.com/53411/47514877-6b5be280-d84f-11e8-80a1-e17641dbbe72.png">

**Comment by kristinashu** [comment]
Ok awesome!

**Comment by xmatthewx** [comment]
@Pomax - are you able to [re-name the site category](https://github.com/mozilla/foundation.mozilla.org/issues/2024#issuecomment-432425945) on a few of the already implemented events? From `site` to `buyersguide` as listed in [column E of the spreadsheet](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=980429434). 

Why? When I originally labeled this I failed to realize these analytics will be mixed with foundation site analytics.

**Comment by Pomax** [comment]
@xmatthewx  Certainly, but that will touch already landed code so if we can file a new issue specifically for that rename I can whip up the PR that addresses it.

**Comment by kristinashu** [comment]
Issue for re-naming is here https://github.com/mozilla/foundation.mozilla.org/issues/2087

Just a _few_ more left to do in the spreadsheet https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=980429434

**Comment by Pomax** [comment]
I've split up the filter one into separate entries for homepage and categories, since we never implemented the filter for category pages and so that'd be new work rather than adding events to existing code.

**Comment by Pomax** [comment]
The only event left is the filter event, which has open questions - can we resolve those? From the sheet:

> let's discuss best way to wire this. on any change? on closing modal if there was a change? we just want to know if people are using this feature a lot, a little, never. questio: will we have filter params in the URL? doesn't matter much, just curious.

**Comment by kristinashu** [comment]
Ok nice. For that question, Matthew is wondering if there is a way to track if people are using the filters once they open it. So not only tracking when someone opens/closes the filter bubble but also if they are adjusting the creepiness or likelihood of buying. Is something like that doable?

**Comment by Pomax** [comment]
Getting the events isn't hard (all the filter things are clicks), the hard part is understanding what the events mean in a dashboard: it won't tell us much about whether the filter does what the user wants out of it, since it's so playful =)

That said, if we want to add events to filtering, given how many events this will be, can we start a new issue specifically for those and close this one out?

**Comment by kristinashu** [comment]
Sounds good! I've opened a new ticket https://github.com/mozilla/foundation.mozilla.org/issues/2263
