### ISSUE TITLE
GA isn't showing buyer's guide visits

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2033]
I can't quite tell if this is a GA filtering or implementation issue but when I visit https://analytics.google.com/analytics/web/#/realtime/rt-overview/a87658599w138395144p162890438/ I don't see any hits from the guide, despite seeing myself visiting the main site.

(Firefox also seems to not be reporting on the main site for me despite DNT being disabled. I can't tell if that's a separate issue.)

**Comment by cadecairos** [comment]
I've set up a filtered view for PNI: https://analytics.google.com/analytics/web/#/realtime/rt-overview/a87658599w138395144p183946777/ And I can confirm I'm seeing realtime hits there, but only for events we've wired up.

I think we need to manually trigger page views: https://github.com/react-ga/react-ga#reactgapageviewpath

**Comment by kristinashu** [comment]
@cade are you able to give me access to that? It says I'm missing permissions.

**Comment by cadecairos** [comment]
@kristinashu done!

**Comment by cade** [comment]
It's less fun when @cadecairos beats me to responding... I am in Montreal at the moment though, so I have a Canadian-themed joke for y'all:

> **How many people in Toronto does it take to change a light bulb?**
> 
> One. They hold the bulb in the socket and wait while the world revolves around them.

🇨🇦 🍁 🏒

**Comment by kristinashu** [comment]
😂
