### ISSUE TITLE
Fix remaining Buyer's Guide criteria issues.

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2044]
Follow up on #2036 

- [x] Reading levels 13 or greater are "bad"
- [x] All products should be "Can't determine" rather than "Not required". The only exception is "If a password is required, you must change the default password" should be "Not required".

**Comment by Pomax** [comment]
I've updated both, but I've left out the exception. as "should you change your password?" is still the same "yes/no/unknown" value in the model. If you don't need to change the password, then we should save that product with value `no`. If we save `unknown` then we're saying we literally don't know, and then showing "not required" would be bad.
