### ISSUE TITLE
Buyers Guide: open vote share in new tab

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2046]
Sorry Pomax I know you hate opening links in new tabs but I think we need to for this. Because if a user: Votes on a product, clicks share on Twitter, then wants to share on FB so they click the back button, but they can't share on FB now because they are back at the pre-voting screen. 

Would be better if the share screens like FB and Twitter opens in a new tab so users can close it and return to the post voting screen.

**Comment by Pomax** [comment]
That's an interesting use-case: I agree, in this case a new tab makes a lot of sense.
