### ISSUE TITLE
Social graphics to promote Buyers Guide

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2090]
Few images and gifs for social, email, blog posts on both the Mozilla blog and Medium, some for press releases for media to use.

Some possible [copy](https://docs.google.com/document/d/1hRYn2EFAJxGjikeQqsXeeiaPOdJy37dzwi10PJTl_EA/edit#heading=h.j8n12cvme0nu).

**Comment by natalieworth** [comment]
Got a start on some [social graphics here.](https://redpen.io/p/dud88d7ca8c480714a)

cc @kristinashu @caltrider @beccaklam

**Comment by natalieworth** [comment]
Updated social [graphics here](https://redpen.io/p/dud88d7ca8c480714a)

Maybe could meet on Tuesday when we are back to go over them? And I can create and export finals for instagram/ twitter?

**Comment by kristinashu** [comment]
Yeah sounds good Nat! We can go through the tough process of trying to choose just a few!

**Comment by caltrider** [comment]
Love them. I'm around on Tuesday if you'd like me to join.

**Comment by natalieworth** [comment]
Have uploaded Twitter/ Instagram versions of buyers guide social (and some press options if needed):
[Twitter](https://drive.google.com/open?id=138X2tFcbum-uFfaTdjQoMDjcl9nhlDsi&authuser=natalie@mozillafoundation.org)
[Instagram](https://drive.google.com/open?id=138Z10W5-Pc29FiqEE6r9MesknsXtIFNY&authuser=natalie@mozillafoundation.org)
[Press](https://drive.google.com/open?id=13_NXQn5GY3xhsP4ZxsPKcZHOfCNSW9p8&authuser=natalie@mozillafoundation.org)

**Comment by kristinashu** [comment]
Sweet! I've shared all of these with Lotta. @caltrider can you please share with whoever else might need them?

**Comment by caltrider** [comment]
Will do. Thank you all!

**Comment by natalieworth** [comment]
Documenting the updated social graphics to remove the 'mozilla' logo:
![07-pni-logo-insta](https://user-images.githubusercontent.com/14876567/48872409-cd9bfa80-ed9d-11e8-8f56-d8be8a6e5257.jpg)
![07-pni-logo-twitter](https://user-images.githubusercontent.com/14876567/48872410-cd9bfa80-ed9d-11e8-9d0a-59a9d7535ba7.jpg)
