### ISSUE TITLE
Update seal of approval

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2091]
Based on design in https://github.com/mozilla/foundation.mozilla.org/issues/1873

Update: 
- we will now only have one badge
- copy will be "Meets Our Minimum Security Standards"
- from the comps, I think 140x140px is a good size for [desktop](https://redpen.io/bcd47ecb6d670654da) but keep in mind it will be smaller on [mobile](https://redpen.io/fk5813dda329fda302)
- [working file in drive](https://drive.google.com/file/d/18EZJW-W6KO-c0rqA9XS-Iy2JdWl_RoS0/view?usp=sharing)

**Comment by natalieworth** [comment]
Updated some seal options here! Trying to focus on legibility as the page is pretty busy (V6-V10)! :D 
https://redpen.io/p/sj23e52061227d6ca8

cc @kristinashu @beccaklam

**Comment by natalieworth** [comment]
Final seal of approval svg [is here](https://drive.google.com/drive/folders/1W9w0kVbvloZZ16ApcPpr40OR9SnloCEp?usp=sharing)

[PNI-Seal-of-Approval.svg.zip](https://github.com/mozilla/foundation.mozilla.org/files/2555047/PNI-Seal-of-Approval.svg.zip)

![artboard 6 copy 1x](https://user-images.githubusercontent.com/14876567/48093980-b833a780-e1c5-11e8-83a2-92ffc1bb0906.png)

cc @kristinashu @mmmavis @beccaklam

**Comment by kristinashu** [comment]
w00t thanks Nat! I've updated the implementation ticket.
