### ISSUE TITLE
Nov 12 launch dates & checks

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2096]
### Dates 
- Let's push everything we got to prod Thur Nov 8 💪
- Re-review @xmatthewx's [check list](https://docs.google.com/document/d/1cCuILd6Dwcr0uSSH69qFkeKDNiV_i50fBg0vH6R8nNQ/edit) after stand on Wed Nov 7
- Final final QA Fri Nov 9
- Any pushes after that will need to be **heavily** tested on staging

### Promo Detail
- Official launch date is Mon Nov 12 🚀 
- Email will be sent Tue Nov 13
- Press event Wed Nov 14
- Articles & press throughout both the weeks of Nov 12 + 19
- Not sure when snippet will be approved?

cc @alanmoo @cade @Pomax @patjouk @xmatthewx

**Comment by cade** [comment]
![huzzah](https://user-images.githubusercontent.com/3403/47888020-4a2b6100-de10-11e8-833a-5d3dea61aa6e.gif)

Great work everyone! Shipping's the best. I couldn't be more proud of y'all. 👏 👏 

Backpats all around. (Especially for @cadecairos. He's endured _all_ of my shenanigans along the way.)

**Comment by kristinashu** [comment]
Nooooo I can't believe I did it again! Sorry!

**Comment by alanmoo** [comment]
Github really needs to add autocomplete on mobile...that's where I make that mistake half the time. @kristinashu let's pretend you were working really hard on your phone? ;)
