### ISSUE TITLE
Copy updates on Product page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2097]
Based on user testing & feedback at MozFest https://github.com/mozilla/foundation.mozilla.org/issues/2072 and the [comp](https://redpen.io/bcd47ecb6d670654da).

### Update Customer Support copy 
- [x] New copy: `Company makes it easy to contact customer support`

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/1068783/47881635-ec811f80-dde3-11e8-9c54-b77ffc871a8f.png">

### Remove question marks
- [x] Delete question marks from criteria titles
  - `Can it spy on me`
  - `What does it know about me`
  - `Can I control it`
  - `Company shows it cares about its customers`
  - `What could happen if something goes wrong`

### Privacy policy lowercase
- [x] Update `Reading level for Privacy policy` to`Reading level for privacy policy`

### Update copy of related products 
- [x] New copy: `Compare products`

### Product page comp:
![product wide copy 2x](https://user-images.githubusercontent.com/1068783/47880208-dcffd780-dddf-11e8-8dd8-f8932ba8e97f.jpg)

**Comment by Pomax** [comment]
The "Company shows it cares about its customers" line seems very different from the other lines, which start with interrogative "what/can [...]". It makes the "company shows" start feel out of place. Is there some phrasing we can think of that brings it a bit more in line with the other three?

**Comment by Pomax** [comment]
:flamethrower: very well
