### ISSUE TITLE
Remove link icon from header

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2118]
Based on user testing & feedback at MozFest https://github.com/mozilla/foundation.mozilla.org/issues/2072 and the [comp](https://redpen.io/bcd47ecb6d670654da).

- [ ] Remove link icon from top nav (on desktop and mobile menu)

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/1068783/48022600-6e2cc200-e0f0-11e8-8a8b-842e317ec24c.png">

<img width="319" alt="image" src="https://user-images.githubusercontent.com/1068783/48022577-5e14e280-e0f0-11e8-86ea-36defae4eb62.png">

**Comment by mmmavis** [comment]
Need clarification @kristinashu , by removing "link icon", did you mean remove all those social links for good on both mobile and desktop?

**Comment by kristinashu** [comment]
Only remove the copy link icon and functionality. Facebook, Twitter and Email should remain (like in the comp). 

Yes, for both mobile and desktop.

**Comment by mmmavis** [comment]
ahhh okay, I misunderstood. Thought you meant those 3 "linked icons" 😂

**Comment by kristinashu** [comment]
Glad you asked!
