### ISSUE TITLE
Filters QA

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2123]
Here's a list of all the things. Not saying there all need to be done... 

### Add filter label
- [x] Add the word `Filter` on left side of bubble
- [x] Nunito sans bold 12px #666666

### Bubble size and shadow
- [x] reduce icon size to ~30px~ 24px wide
- [x] slightly reduce the amount of drop shadow
<img width="425" alt="image" src="https://user-images.githubusercontent.com/1068783/48096792-08623800-e1cd-11e8-8ef5-712ad994b983.png">

### Bubble over top of nav and product
- [x] bubble should overlap both nav and products
<img width="428" alt="image" src="https://user-images.githubusercontent.com/1068783/48096828-229c1600-e1cd-11e8-80ee-b746255a9cf9.png">

### Bubble location at narrow widths
Is there a reason the bubble is on the left instead of the right side?
- [x] bubble should be on right side of the screen so it's consistent with wider screens and with close icon
<img width="770" alt="image" src="https://user-images.githubusercontent.com/1068783/48096952-7ad31800-e1cd-11e8-8626-9b6be1ac38b6.png">

### Filters should fill screen at narrow widths - can be done in #2183
- ~Filters at narrow widths fill the screen~

### Empty set - can be done in #2179
- ~if there are no products then we should say `No results.  Clear filters and try again.`~
- ~clicking `Clear filters and try again.` should clear the filters and show all the products~
- ~link is black with underline with hovers state #3302FF~

### Tags - can be done in #2180
- ~if a filter has been used, the a tag should appear~
- ~click to delete the tag should reset that filter~

**Comment by beccaklam** [comment]
Looks great and @kristinashu covered most of the QA I have. The one thing I caught is when the bubble expands it's cut off at the nav:
![screenshot_2018-11-07 privacy not included 1](https://user-images.githubusercontent.com/20977376/48153692-dcaa8500-e294-11e8-9dc4-89856be9e0b1.png)
It the mock ups we had the filter expand and move down a but to avoid that:
![image](https://user-images.githubusercontent.com/20977376/48153730-f4820900-e294-11e8-8a76-686d92e44071.png)
Not a big bug but would be nice to have!

**Comment by mmmavis** [comment]
Assuming this ticket is ready for implementation... I'm gonna self assign.

**Comment by kristinashu** [comment]
Sweet! I say start with the quick wins. Can always to the bigger things separately.

**Comment by kristinashu** [comment]
Slightly related https://github.com/mozilla/foundation.mozilla.org/issues/2153

**Comment by kristinashu** [comment]
Yay done! Everything else is in separate individual tickets.
