### ISSUE TITLE
Homepage product thumbnails should fill the screen width

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2124]
In the comps, the homepage products are full width but this was never implemented. I think the desktop layout is ok on the live site but all the medium widths should be full width to maximize the space. 

Note:
- the mini seal is should be made small, like in the comps
- light gray padding around each product image should be good but might need to be adjusted
- This ticket sets us up for adding the product titles

Comps: https://redpen.io/p/qz6bdb2811e058ffb1

![red-pen-dfeeef57-446d-46b1-f151-13508e67836c](https://user-images.githubusercontent.com/1068783/48727836-2d50a500-ebe8-11e8-941f-1ea86a127161.png)

![red-pen-4a7b925a-9a9d-43bc-efe3-85f5750f7960](https://user-images.githubusercontent.com/1068783/48727834-2cb80e80-ebe8-11e8-81da-b51d1288d382.png)

<img width="186" alt="image" src="https://user-images.githubusercontent.com/1068783/48727894-5709cc00-ebe8-11e8-9375-a171378a9911.png">

**Comment by mmmavis** [comment]
Fixed in PR #2232
