### ISSUE TITLE
Generate fake data for Initiatives page

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2127]
When running `load_fake_data`, the initiatives page is empty. Let's fix that.

**Comment by Pranay144** [comment]
@alanmoo  I am new to open source.I would like to work on this issue #2127.

**Comment by alanmoo** [comment]
Sure, is the descript (paired with the readme) clear enough for you to get started @Pranay144?

**Comment by Pranay144** [comment]
yes, the description is clear enough for me to get started with the issue.
I'll work on it.

**Comment by Pomax** [comment]
@alanmoo is this still required? if so, @Pranay144 are you still interested in working on this?

**Comment by alanmoo** [comment]
I don't believe anything significant has changed since December, so yes, it would still be useful.

**Comment by Pomax** [comment]
ping @cadecairos, where would someone start looking to get that added?

**Comment by cadecairos** [comment]
we'll need to customize the `InitiativesPageFactory` class in `network-api/networkapi/wagtailpages/factory.py` so that it generates values for all the attributes defined on the `InitiativesPage` class in `network-api/networkapi/wagtailpages/models.py`

**Comment by harshs14** [comment]
hi @alanmoo, I am new here, can I take this up if no one is working on it and can u explain me on how to solve this

**Comment by alanmoo** [comment]
Based on conversations we had last week, I’m not sure we are going to continue generating fake data, so this might not be a useful ticket to work on.

**Comment by harshs14** [comment]
@alanmoo, i wanted to work on a issue based on django as i have some knowledge about it but i am unable to find any appropriate issue related to it in the good first section, can i look for any other issue other than good first section which i can solve?
