### ISSUE TITLE
Design About This Guide page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2129]
Jen has the almost final drafts done for the About page. Let's see if we can add some images and possible some section anchors to the page so it doesn't feel so long.

Copy for [How To Use This Guide](https://docs.google.com/document/d/1U0ccj1E5JM6wQNh7OR9uraRKDu-OnFYiZC6DAtKYPyo/edit?ts=5be360ec) and [Why We Made This Guide ](https://docs.google.com/document/d/16cUpqZz0K43G4wuxfymqVM_F8c9rMrKV5imuhCcCvQk/edit#).

**Comment by kristinashu** [comment]
@alanmoo on Monday, can you please update the copy on the [About This Guide](https://foundation.mozilla.org/en/privacynotincluded/about/) page?

@caltrider please ping Alan once the blog posts are up and you have added the links to the doc.

Final copy is here [How To Use This Guide](https://docs.google.com/document/d/1U0ccj1E5JM6wQNh7OR9uraRKDu-OnFYiZC6DAtKYPyo/edit?ts=5be360ec) and [Why We Made This Guide ](https://docs.google.com/document/d/16cUpqZz0K43G4wuxfymqVM_F8c9rMrKV5imuhCcCvQk/edit#).

#### Comp for Phase 1 (for Monday): https://redpen.io/dx13ae7f4a60908343
![about copy 2x](https://user-images.githubusercontent.com/1068783/48281323-12717a00-e40b-11e8-9006-ba87939f5c78.jpg)

#### Comp for Phase 2: https://redpen.io/fcdadf5d950054eb7b
![about copy 2 2x](https://user-images.githubusercontent.com/1068783/48281322-12717a00-e40b-11e8-949c-7271dc18eb7e.jpg)

### #Comp for Phase 3: maybe something like this but still exploring https://redpen.io/cxc1bcdeaca3949a2f
![about copy 5 2x](https://user-images.githubusercontent.com/1068783/48281337-1dc4a580-e40b-11e8-8575-958c828e9639.jpg)

**Comment by alanmoo** [comment]
@kristinashu @beccaklam What style are the sub-headings supposed to be using? ("Creep-O-Meter", "Our Minimum Security Standards", etc)

Also, I need access to the "How to use this guide" doc.

**Comment by beccaklam** [comment]
Hey @alanmoo the style for the sub headings is based off the 'normal body' style, it's just bolded.
<img width="242" alt="screen shot 2018-11-12 at 10 04 36 am" src="https://user-images.githubusercontent.com/20977376/48355639-76da4680-e662-11e8-8980-9261d038aea1.png">
