### ISSUE TITLE
Further User Testing for Buyer's Guide

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#2130]
Post launch we should do some more user testing for the Buyer's Guide product and homepage. Specifically:

- [x] Design a test to see what is the most effective format for the engagement survey

- [x] Design a test to see whether users need to read the review before voting

*if there's time:

- [x] Design a test to see if users understand correlation between creepy face on home page and product scroll

Buyer's Guide Feedback doc: https://docs.google.com/document/d/1NxJUSMjgcjdkaorXko7a9Rm_9h3TZge7p5pCUeeUqO0/edit#heading=h.qkrcs2d8sfgd

Working Doc: https://docs.google.com/document/d/1utoeB5wzVnyeQHt5051sxC2pzPuXPHttuYcK6CXtBmA/edit#

**Comment by beccaklam** [comment]
### Prototypes:
**Variant A:** https://mozilla.invisionapp.com/share/BCP664UE6TS
**Variant B:** https://mozilla.invisionapp.com/share/DSP6ZHUCN7F
### Script doc:
 https://docs.google.com/document/d/1lab8BdPibdeQEg5wtBFsWZnMTbZgyoBPl07i525Oe9w/edit

**Comment by natalieworth** [comment]
### Prototypes (for user testing to complete 2 step voting system):
**Variant A:** https://mozilla.invisionapp.com/share/M7P74VTW8CE
**Variant B:** https://mozilla.invisionapp.com/share/93P75DQRE2Z
### Script doc (2nd page, Part 2):
https://docs.google.com/document/d/1lab8BdPibdeQEg5wtBFsWZnMTbZgyoBPl07i525Oe9w/edit?usp=sharing

**Comment by beccaklam** [comment]
## Vote Section Outcomes
**Variant A** [Video 1](https://www.usertesting.com/v/b6ed8dae-56a1-4735-8139-3f1b08b01c1b?encrypted_video_handle=eMrUuwB_KpXIZ3XueXPelw&shared=Ffk1LoCm) | [Video 2](https://www.usertesting.com/v/6ecbceea-a6b8-48dc-93d2-8799ce2c2172?encrypted_video_handle=CorUpwBzODZPJFcs-c2GGg&shared=adn4U2wO)
- Users need to be directed to the research before engaging with the creep-o-meter not only for the information but to draw a correlation between the two (Video 1)

- Even after scrolling through the page and seeing the research after the creep-o-meter, users choose to interact with the creep-o-meter first. Users follow the hierarchy of the page unless told to break it (Video 2)

- Users feel there is enough information to engage with the creep-o-meter after reviewing the research section but not before (Video 1)

- Users want more information on things labeled 'Can't Determine' and 'unexpected reasons'. Confirms our assumption that linking to the 'How to use this guide' content will be helpful (Video 2)
- User liked the purpose of our page, especially for tech toys she might buy for her niece or nephew, confirms we are speaking to the needs of our target audience

**Variant B** [Video 1](https://www.usertesting.com/v/f32a53dd-c314-47ab-9efd-270b375166e3?encrypted_video_handle=pUAynnWsebye3YWiHfLj_A&shared=JgNVOlSF) | [Video 2](https://www.usertesting.com/v/6061bf6c-cef5-419b-a4b8-5a7cd8a886a3?encrypted_video_handle=miF__dCn6Jc75j2a3AcTxw&shared=hAAXL3O-)

### Testing Notes:

- Be more specific about where you want the user to browse unless you truly want them to browse the page generally. E.g. in this case we could have said, 'Read the review' since they should be in that mindset when clicking into this page.

- Don't ask the user to 'interact' with a mostly unresponsive demo. Ask them to browse with their eyes first then be guided when asking them to click if only a small portion of the page works.

**Comment by beccaklam** [comment]
@natalieworth Would you be able to write up a report for your test? After we can close this ticket I think!

**Comment by kristinashu** [comment]
Nat has opened an implementation ticket for some small updates to the vote section! 

I think we can push for these updates when we do the Valentines Day push 💖
<img width="382" alt="image" src="https://user-images.githubusercontent.com/1068783/50789266-a24b6d00-1270-11e9-9c4b-18d0b4e1bcc9.png">
