### ISSUE TITLE
Error while refreshing the homepage cache

### ISSUE THREAD

**Issue by patjouk** [mozilla/foundation.mozilla.org#2136]
When I try to invalidate the BuyersGuide homepage cache (prod/staging/local dev) I get this error:

```
HTTP 405 Method Not Allowed
Allow: POST, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "detail": "Method \"GET\" not allowed."
}
```
URL is: http://localhost:8000/en/privacynotincluded/refresh-cache

**Comment by cadecairos** [comment]
fixed in https://github.com/mozilla/foundation.mozilla.org/pull/2148
