### ISSUE TITLE
Hide Customer Support links inside accordion

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2137]
Add + icon where the Yes/No Face would be. Hide contact info inside. Clicking on + shows the contact info as it is now.

<img width="816" alt="screen shot 2018-11-08 at 8 30 04 am" src="https://user-images.githubusercontent.com/1068783/48212502-9440a500-e330-11e8-8fdd-76d8f268137d.png">

**Comment by mmmavis** [comment]
Has the filed for "company makes it easy to contact customer support" been added to CMS yet? I can't seem to find it on the interface.

**Comment by mmmavis** [comment]
Does it appear based on if any of the phone number / live chat / email / twitter fields is filled?

**Comment by kristinashu** [comment]
Oh it's because on prod the copy says "Customer support" but Pomax has a PR for the copy update to go from "Customer support"  to "Company makes it easy to contact customer support" https://github.com/mozilla/foundation.mozilla.org/issues/2097

Right now on prod it looks like this:
<img width="917" alt="image" src="https://user-images.githubusercontent.com/1068783/48510749-9f507500-e809-11e8-8756-3ed271b9be9d.png">

**Comment by Pomax** [comment]
(note that PR has now landed)
