### ISSUE TITLE
Fix emoji sprite offset in Firefox and Chrome

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2143]
On desktop, the super creepy face disappears at the very bottom, you should still be able to see it.
<img width="1159" alt="screen shot 2018-11-08 at 4 33 44 pm" src="https://user-images.githubusercontent.com/1068783/48236060-75183680-e375-11e8-9663-e5762ef3ab42.png">

On mobile, I see the happy face at the very very bottom of scrolling, should see the super creepy face.

<img width="324" alt="image" src="https://user-images.githubusercontent.com/1068783/48236128-b577b480-e375-11e8-8be7-2d5ab4e030de.png">

**Comment by kristinashu** [comment]
Doesn't look fixed on staging or prod.

**Comment by Pomax** [comment]
It would appear that this is a mismatch between Chrome and Firefox, where:
- chrome: keeps the face, does not seem to compute the sprite offset correctly
- firefox: computes the sprite offset correctly, but is off by one for the most-creepy frame it looks like
