### ISSUE TITLE
Fix small filter glitch

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#2153]
The filter is looking awesome, but I see a small glitch in the animation. It stutters, and the content appears full size through a small window. 

Might be good to hide content until circle is mostly open. 

Browser: FF Nightly 65.0a1 on Mac

![filter-animation](https://user-images.githubusercontent.com/53411/48287374-b02e6e80-e436-11e8-8573-d25a11e77bbf.gif)

Unlike other recent Gifs recently tweeted, this one isn't manipulated for fake news. 

cc @kristinashu @alanmoo to triage

**Comment by alanmoo** [comment]
Ah, yes, I saw this too. I was thinking we might be able to use `transform:scale(x)` and a transition to make it work nicer. Definitely some polish I'd like to get on there.

**Comment by Pomax** [comment]
@alanmoo we're already using scale transforms =(

https://github.com/mozilla/foundation.mozilla.org/blob/master/source/js/buyers-guide/components/filter/filter.scss#L81

**Comment by alanmoo** [comment]
It's janky in Safari too. I played with it a little bit in the inspector, and it feels like removing the `.d-none` class on the element targeted by `.filter-content.collapsed > .content` would make it look smoother. The flip from hiding/showing content is what seems to make things flicker.
