### ISSUE TITLE
CMS updates disappear!

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2156]
Ok I have confirmed with certainty multiple times. I update the Related Products in the cms, look at the page and it looks correct, but then refresh the page a couple hours later and it is back to how it was before the update.

**Comment by Pomax** [comment]
To confirm, is this on the production server? /cc @cadecairos

**Comment by kristinashu** [comment]
Yes, on production.

**Comment by cadecairos** [comment]
This is a strange bug, I'm not sure how it's even possible, unless there's a problem with wagtail.

**Comment by kristinashu** [comment]
@beccaklam is updating the all Related Products now to see it's just me loosing my mind or not. So far it's just me but give it time! If it isn't me then I hypothesis it's something to do with updating one Related Products affects a different product page? Or maybe something happens when we push to prod?? Anyways, let's see what happens with Rebecca's updates... 

Because it's only this one component and not any of the important info, I don't think it's super important to fix asap.
