### ISSUE TITLE
Donate modal button appears prematurely

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2170]
STR:

1. In a new/private tab (so that your sessionStorage is clear), open a product page [like this one](https://foundation.mofostaging.net/en/privacynotincluded/products/parker-teddy-bear/)
2. Scroll down quickly (before the modal appears), and you'll see the pink "Support Mozilla" button stuck in the middle of the page somewhere. It jumps to the donate modal once that appears.

(I still landed this because it has the potential to have an impact on our donations if it's live when the blast goes out. Most people will also likely hit the homepage first, and it doesn't happen there.)

**Comment by Pomax** [comment]
After various modal rewrites, at some point this got fixed
