### ISSUE TITLE
Clicking outside the donate modal should not close it

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2171]
Opinion bug here, @kristinashu what do you think? I think the donate modal should be a bit more permanent- we don't want it going away when someone clicks to vote, for example. Usually, I'm all about giving options to get rid of modals, but this one doesn't block the entire page and we really want to encourage people to donate.

**Comment by kristinashu** [comment]
Sure, that makes sense to me.

@mmmavis sorry but could you please remove the feature that allows people to dismiss the popup my clicking anywhere outside of the model. So modal will only close if: user clicks close button or donate button.

**Comment by mmmavis** [comment]
yup i can do that!
