### ISSUE TITLE
Add favicon metatag

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#2173]
I'm seeing hundreds of 404s in the logs for failed requests for `favicon.ico`

Lets add a meta tag to fix this (and a favicon if needed)

`<link rel="icon" href="path_to_favicon.png">`

we might even want to go a step further with different size icons.

**Comment by cadecairos** [comment]
This might just be a buyer's guide thing?

https://github.com/mozilla/foundation.mozilla.org/commit/8fff1fe0a1c32439c3e0b0a581149fadbd46e10c

**Comment by Pomax** [comment]
It looks like this got fixed, can you confirm and close (if fixed of course)?

**Comment by Pomax** [comment]
fixed
