### ISSUE TITLE
Update OG image and copy

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2184]
#### Current OG copy and image:
<img width="496" alt="image" src="https://user-images.githubusercontent.com/1068783/48506200-c4d78180-e7fd-11e8-8414-228f970070ab.png">

#### Please update copy to:

Title: *Privacy Not Included: A Holiday Buyer’s Guide for Connected Products
Intro: 70 connected products rated on their safety and security

#### And update image to:

![09-og](https://user-images.githubusercontent.com/1068783/48505776-b2107d00-e7fc-11e8-919f-3cdb7be04a7a.jpg)

**Comment by mmmavis** [comment]
> Intro: 70 connected products rated on their safety and security

@kristinashu I'm not sure what intro you were referring to. Do you know what current intro copy is?

**Comment by mmmavis** [comment]
nvm. I got it!

**Comment by kristinashu** [comment]
Yeah it replaces the "This year, learn what tech..." text.
