### ISSUE TITLE
Add mechanism to control which average creepiness is "happy"

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2196]
Right now frame 0 is reserved for creepiness values 0-2.5 which means there is effectively no way for people to ever see the happy face.

Adding a step that remaps creepiness at the time of reading-in would allow us to control at which creepiness we "start" moving off of the happiest-face towards. Might even give us some A/B testing opportunities?

**Comment by kristinashu** [comment]
Yes! Jen just mentioned she would love for the first few products to be "not creepy". So we're not so ominous.

**Comment by Pomax** [comment]
I've set up a PR for this, on https://foundation-mofostaging-pr-2198.herokuapp.com/privacynotincluded, with the range for cosmetic purposes changed to 25-80, so the emoji will change as:

- any creepiness < 25 is considered not creepy, super happy
- any creepiness in the range 25-80 maps the the emoji transitions if it's the range 0-100
- any creepiness > 80 is considered super creepy recoily face.
