### ISSUE TITLE
Remove thumbs from homepage

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2197]
So everyone is confused by the thumbs on the homepage. They think they can click it to up/down vote, they think it's mozilla rating the products... We should remove them since the cost of the majority of users being confused by the thumbs is more than the cost of the few people who use the filters to filter by likelihood to buy and could be confused by not seeing the thumbs on the product.

- [ ] Remove thumbs from products on homepage (but keep them as a filter)

We are thinking of add product titles as a hover states so could maybe show the thumbs there too, but need to mock it up first.

**Comment by Pomax** [comment]
Removing any indication of what those icons stood for makes it unclear what the filter does, filtering on a secret property. Can we instead replace the thumbs with something that is perceived as an informative element rather than an interactive one? E.g. replace them with the phrase "A likely purchase" or "An unlikely purchase" or something?

**Comment by kristinashu** [comment]
Do you mean show that text over top every image, always? I think that would work well on hover (with the product titles when we do that - working on design now).

**Comment by Pomax** [comment]
Ah, putting that in the hover is a good idea - shall we block this issue on the hover title etc. then?

**Comment by kristinashu** [comment]
It's tough because right now everyone is confused by having the thumbs there so we're keen to remove it asap. Some people will be confused by not seeing the thumbs when they use the filters, but since fewer people use the filter so seems like an ok trade off.

**Comment by Pomax** [comment]
kk, PR incoming.

**Comment by kristinashu** [comment]
One thought... would it be possible to not show the thumbs. But then if a user filters so they only see "Likely to buy" then they would see those thumbs over the product. And vise versa for "Not likely to buy". But then if they click "Both" then they don't see any thumbs?

**Comment by Pomax** [comment]
it's a little more work, but certainly possible.

**Comment by kristinashu** [comment]
This is done and it's great 🎉
