### ISSUE TITLE
About This Guide layout enhancements

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2211]
Currently the page about page is a wall of text. How To Use https://redpen.io/cxc1bcdeaca3949a2f and Why We Made https://redpen.io/scc5487f6071e8ce0d

- [x] Add side nav (similar to our opportunity pages) 
- [x] Add accordions (+ is the same as on product pages but at 50% opacity) 

Note: we will be linking the badge on a product page to "minimum security requirements" on this page. Is it possible to make the accordion open?

![about 2 2x](https://user-images.githubusercontent.com/1068783/48961405-00262e80-ef29-11e8-91fa-7844011d9e1b.jpg)

![red-pen-ef00f842-f9cb-4e67-a612-a5915a241c65](https://user-images.githubusercontent.com/1068783/49041004-e1b67200-f178-11e8-97db-3fade8362ba1.jpg)

**Comment by Pomax** [comment]
Not that this is not CMS-managed content, so if we want a side nav, we're faking one from scratch =)

Would adding a few headings to break up the wall into a few manageable sections make sense, too?

**Comment by kristinashu** [comment]
I realize it's not as easy as pulling from the cms but hopefully some of the css can be re-used??

Yes, that's a good suggestions! We could definitely be some grouping to break it up a little. I'll assign this to myself to update with some section headings.

**Comment by kristinashu** [comment]
@Pomax I've created a bit more hierarchy but not sure it's really helping. It's still just really long!

![about 2 2x](https://user-images.githubusercontent.com/1068783/48807460-6cf3bb80-ecd2-11e8-8efa-998ddb50f0a6.jpg)

**Comment by Pomax** [comment]
What if we go the "FAQ" way that a lot of sites these days use, with accordions next to each criterion?

![image](https://user-images.githubusercontent.com/177243/48959991-59d52b80-ef1e-11e8-9692-8dcc52cdd5a0.png)

(pay no attention to the repeated text, I photoshopped this together from your comp rather than actually implementing it =)

**Comment by kristinashu** [comment]
Oooh I like that! I had mocked it up with accordions for everything but I prefer it the way you did it. Will mock it up!

**Comment by kristinashu** [comment]
Here it is https://redpen.io/cxc1bcdeaca3949a2f

I'll just run this past Jen on Monday.

![about 2 2x](https://user-images.githubusercontent.com/1068783/48961405-00262e80-ef29-11e8-91fa-7844011d9e1b.jpg)

**Comment by Pomax** [comment]
It's probably worth putting a two sentence "paragraph" below the `Criteria` header, along the lines of "We currently rate products on the following criteria. Click on any criterion to see what we look for and how we rate them, or click here to expand all:" with a small button that just opens all of them up at the same time.

**Comment by kristinashu** [comment]
Jen is happy with this and doesn't think we Criteria needs any intro text.

I've update the first comment in the ticket to reflect the changes.

Note copy update in https://github.com/mozilla/foundation.mozilla.org/issues/2272

**Comment by Pomax** [comment]
I take it "how to use" will be the page you land on when you click "about" in the top nav?
