### ISSUE TITLE
Add 'creepy face' beside 'What could happen if something goes wrong' header

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#2231]
- [ ] Add the creepy face beside the 'What could happen if something goes wrong' header to give it more emphasis. SVG is [here](https://drive.google.com/open?id=1HzVsb2fdlRPVfVnvmrQoU3hYmmcu-Tzh).
![what-could-go-wrong 2x](https://user-images.githubusercontent.com/20977376/48731500-08612f80-ebf2-11e8-810e-a088b4e7f966.jpg)

**Comment by Pomax** [comment]
This feels like this forces the emoji into the page a little - do we need this emphasis? If so, would it make sense to only show it if the product is creepy enough (e.g. not have our seal of approval), so as not to introduce bias into the product's perception?

**Comment by beccaklam** [comment]
Hey @Pomax there was a request from @caltrider to add emphasis to the 'What could happen if something goes wrong' section. There's a concern it's getting passed over and it contains important information. We would prefer to keep the face consistent across the pages so people know what to look for. The choice to use the emoji is to, again, stay consistent with highlighting creepiness with the emoji face. cc: @kristinashu

**Comment by Pomax** [comment]
Alright, I'll add the emoji in, but I'd like to also pitch the idea that right now it just looks like detached text  due to there only being a header and a single sentence, and adding an emoji won't affect that too much. It might be worth turning that into a kind of "alert box" (similar to how textbooks deal with conclusions or break-outs) and style it so it can't be ignored but instead draws eyes to itself.

**Comment by caltrider** [comment]
I like that idea @Pomax .

**Comment by Pomax** [comment]
silly mock-up, but something that pops out like this?

![image](https://user-images.githubusercontent.com/177243/49108111-2eaf4c80-f23c-11e8-959e-14fd964abdbb.png)

**Comment by kristinashu** [comment]
I don't think it needs to stand out **that** much!

**Comment by Pomax** [comment]
I wasn't sure about the bold, but I kind of liked having the emoji on both sides =P

**Comment by Pomax** [comment]
Is it worth waiting for a new design before implementing this, or do we want the intermediary "just the emoji" first and file a followup for more emphasis?

**Comment by kristinashu** [comment]
I think _just the emoji_ and then see if it still comes up as an issue in user testing.
