### ISSUE TITLE
Add mini seal to categories 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2234]
Similar to https://github.com/mozilla/foundation.mozilla.org/issues/2236

- [x] Add mini seal to categories - 40px wide
- [x] Update company name from .h6-heading-uppercase to .h6-heading
- [x] Add gray padding around image 

<img width="394" alt="image" src="https://user-images.githubusercontent.com/1068783/48739093-bb885380-ec07-11e8-9805-d04c8ca6d452.png">

Comp https://redpen.io/mb5979d9d3273ab852

![category copy 2 2x](https://user-images.githubusercontent.com/1068783/48738708-af4fc680-ec06-11e8-8801-315b60dd7437.jpg)

**Comment by Pomax** [comment]
Would these effectively be the same panels we use on the homepage? (if so, we might be able to turn them into a template fragment and have the homepage and category views both use the same thing, just with an argument to show/hide the title)

**Comment by kristinashu** [comment]
Not too sure what you mean my panels. It is the same content as home page (image, mini seal, company name title, product name title, and gray padding). Differences are that thumbs, the product title, and the white space between products on the Category pages is larger. Another small difference is that titles on the homepage will be hidden at narrow mobile widths, where as they must always be shown on the Category pages.

**Comment by Pomax** [comment]
That's effectively what I was looking for as answer - I'll investigate if we can do some unification there, so we can take advantage of the code we already wrote for showing seals-of-approval without repeating code/scss!

**Comment by Pomax** [comment]
Hm, pulling things apart turned out not to be a real option, so adding things specifically to the category page.
