### ISSUE TITLE
Buyers Guide: Add product names to page titles 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#2246]
Currently, all buyer's guide pages have the same generic title in html head. Let's add product names to the title tag. This will help with SEO and user navigating their bookmarks and history.

**Comment by Pomax** [comment]
What title format would you like? `*privacy not included - {company} {productname}`?

**Comment by Pomax** [comment]
As we use it, the company name is already in the product name, so I'll use that instead.
