### ISSUE TITLE
Foundation site: Add page title to html head

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#2247]
Currently, all foundation site pages just have "Mozilla Foundation - " in the html head. Let's add page title to the title tag. This will help with SEO and user navigating their bookmarks and history.

**Comment by Pomax** [comment]
Hm, does it even make sense to keep `Mozilla Foundation` in the title at all, when the "Privacy Not Included" part is the actual "site" title?

**Comment by kristinashu** [comment]
There's another ticket for this https://github.com/mozilla/foundation.mozilla.org/issues/2367
