### ISSUE TITLE
Update the default share image for the Buyer's Guide

### ISSUE THREAD

**Issue by natalieworth** [mozilla/foundation.mozilla.org#2255]
We received feedback from the brand team that we are unable to use the 'mozilla' logo next to the '_a buyer's guide by_.' I've updated the social files and the logo file, but we will also have to update the image that is shown on share.

Currently, the social sharing is displaying this image:
<img width="613" alt="screen shot 2018-11-21 at 3 14 25 pm" src="https://user-images.githubusercontent.com/14876567/48872981-7f3c2b00-eda0-11e8-9d8c-fdeddc58ddd5.png">

@mmmavis could we please change to [this image](https://drive.google.com/file/d/15fCo3UrYdy3_aEvSaxp8ThgZIa0C6sPR/view?usp=sharing):
![default-link-share](https://user-images.githubusercontent.com/14876567/48872989-87946600-eda0-11e8-8662-75a4dd403b36.jpg)

cc @kristinashu feel free to change/ update if I missed anything in this ticket.

**Comment by natalieworth** [comment]
and also on twitter too:
<img width="540" alt="screen shot 2018-11-21 at 3 21 20 pm" src="https://user-images.githubusercontent.com/14876567/48873111-27ea8a80-eda1-11e8-8cac-d7e81c4f2655.png">

**Comment by mmmavis** [comment]
@natalieworth can we crop the image so it has less padding at top and bottom? Facebook recommends the following ratio for OG image 

> Images appear in a rectangular format. You should use a 1.91:1 image ratio, such as 600 x 314 px.

If we could make ours from `2400px * 1350px` to roughly `2400px * 1260px` (or 2400px * 1256px if you want a precise 1.91:1 ratio)

(Other platforms have looser ratio recommendation compared to Facebook.)

**Comment by kristinashu** [comment]
Here's the cropped image @mmmavis! 

![privacynotincluded](https://user-images.githubusercontent.com/1068783/49169334-65459f80-f2ee-11e8-8768-4cc412355423.jpg)
