### ISSUE TITLE
resolve the eslint "ecmafeatures" deprecation

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2257]
mofo-style uses an obsolete format for eslint.
```
[ESLINT_LEGACY_ECMAFEATURES] DeprecationWarning: The 'ecmaFeatures' config file property is deprecated, and has no effect. (found in "node_modules\mofo-style\.eslintrc.yaml")
```

**Comment by Pomax** [comment]
@alanmoo should we start planning for moving off of mofo-style? Or is that still our authoritative style guide, and should we put some cycles into making it use the most recent eslint?

**Comment by alanmoo** [comment]
I'm fine with us moving to a standard JS syntax linter, similar to Flake8 on Python. Zero opinions on which one, as long as it's easy to turn on in VSCode :)

@youriwims @mmmavis Any thoughts for JS linting?

**Comment by Pomax** [comment]
Then let's use Prettier. It's insanely widely used, it's opinionated, and it has excellent integration with basically everything.

**Comment by youriwims** [comment]
> Then let's use Prettier. It's insanely widely used, it's zero-conf, opinionated based on basically buy-in from every sane JS dev you may have heard of, and it has excellent integration with basically everything.

I vote for Prettier!

**Comment by Pomax** [comment]
filed https://github.com/mozilla/foundation.mozilla.org/issues/2538 to do said replacement.
