### ISSUE TITLE
Add GA events to filter

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2263]
Follow up from https://github.com/mozilla/foundation.mozilla.org/issues/2024. These are also listed in the [spreadsheet](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=980429434).

- [x] Add events: checks or unchecks Meets Minimum Security Standards 

Note: track every time an event happens, even if it is the same user doing it multiple times.

<img width="444" alt="image" src="https://user-images.githubusercontent.com/1068783/48960854-02868980-ef25-11e8-977b-b58a93c96ae2.png">

@xmatthewx assigning to you to review

**Comment by Pomax** [comment]
Before we put these in, can we figure out what we're hoping to get out of these events? Just tracking clicks doesn't mean those numbers are useful unless there's a question that we want to answer based on concrete metrics.

**Comment by kristinashu** [comment]
I've update the first comment and the spreadsheet. @xmatthewx can you please double check? I've made it more general but still tracking each way of filtering.

**Comment by xmatthewx** [comment]
Looks like the main `filter set` event is already wired up, and people are using the feature. So... this issue is really about whether we want a specific event to see if people use the filter by `meets standards`.

<img width="514" alt="image" src="https://user-images.githubusercontent.com/53411/49095042-9ca44580-f235-11e8-9726-3806c02eb5dd.png">

**Comment by kristinashu** [comment]
Yes, I think we should track `meets standards` separately. So in summary, I think this is what Matthew wants to track:
- clicks open filter bubble (done)
- checks or unchecks Meets Minimum Security Standards

Events he does not want to track:
- adjusts creepiness slider
- clicks on any of the Likelihood to buy
- clicks close filter

**Comment by Pomax** [comment]
To double check: is this "check or uncheck standards and then close the filter", or simply "check or uncheck" irrespective of whether the filter is then closed again?

**Comment by kristinashu** [comment]
Just "check or uncheck". We aren't tracking anything to do with closing the filter.

**Comment by xmatthewx** [comment]
Cool. We can just trigger the event when they check it. The other event (already wired up) can alert us if people abandon the filter. This will let us spot check against that, whether a high or low percent of filter users use this toggle. 

```
Category: buyersguide
Action: Filter by standards
Label: filter by standards on buyersguide homepage
```
