### ISSUE TITLE
Create a downloadable pdf

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2271]
There are been several requests for a downloadable PDF.

Requirements:
- devs will generate a PDF once (might need to be update every few months if our content changes)
- add a "Download PDF" link on the site (either homepage or About page)
- PDF included: cover page and then one product per page 
- only show relevant info (don't show vote section, updates, comments, related products)
- designers will mock-up an example page

cc @Pomax @beccaklam @caltrider

**Comment by Pomax** [comment]
I wonder if we can achieve this using a `/printable` URL that generates a special page with print media CSS so that people can print directly to paper form or to a pdf using whatever built-in pdf writer they have.

I also wonder how big of a pdf/page that would end up generating and what the right way would be for us to host/cache that.

/cc @alanmoo @cadecairos

**Comment by alanmoo** [comment]
This seems like an odd way to spend our time unless the request is coming from leadership...What's the reasoning behind wanting this?

**Comment by caltrider** [comment]
This is a request we received a number of times last year and I've also received from at least four people this year. Not a huge number, but it does keep coming up. It does feel a bit like an accessibility thing. I know my public library would likely print something like this out and leave it around for people to more easily access. I don't think we need to rush on this, but it would be a good feature to include in the guide as we move forward to make the guide as accessible and shareable as possible.

**Comment by kristinashu** [comment]
Unfortunately with our limited resources and other higher priority tickets for Buyers Guide features, we won't be able to do this. Please reopen if there is a sudden influx of requests for this!
