### ISSUE TITLE
Update color on Initiatives illustration 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2274]
@natalieworth please update the 4 illustrations so each one uses a different color. Still only one color per illustration, but 4 colors in total. Then replace the image in the CMS.

**Comment by natalieworth** [comment]
Updated the colors of each illustration: https://foundation.mozilla.org/en/initiatives/
I used 3 brand colours from the mozilla.ninja guidelines and a color from this years MozFest branding.

**Comment by kristinashu** [comment]
w00t! They pop!
