### ISSUE TITLE
Integrate black/white banner onto Participate page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2275]
Currently the Participate page hero banner style is quite different than the rest of the site. Explore ways to make it more like the Initiatives page but still work for features/content that is always changing.

**Comment by kristinashu** [comment]
Slightly related to 'Initiatives page: header styling fixes #1720' so let's link them together once design is done and there is an implementation ticket.

**Comment by kristinashu** [comment]
I kinda think these could be the same layout as the other primary pages but with a unique background pattern. Using dots here but could be anything! What do you think @sabrinang @beccaklam @natalieworth? Overview https://redpen.io/hx70e9eb24e0534b72 

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/1068783/52434581-87b12180-2ac4-11e9-9f9c-ae0118d8d18b.png">

**Comment by sabrinang** [comment]
cc/ @natalieworth may be related to the revisions of participate illustrations for brand standards too https://github.com/MozillaFoundation/Design/issues/386 if you want to think about the banner as well

**Comment by kristinashu** [comment]
We might be removing this page so let's no invested in it now. Closing!
