### ISSUE TITLE
Hero image isn't scaling

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2279]
Related to https://github.com/mozilla/foundation.mozilla.org/issues/2261

@Pomax can you please recap what you think the problem here is?

Desktop looks good:
<img width="1176" alt="screen shot 2018-11-27 at 10 39 33 am" src="https://user-images.githubusercontent.com/1068783/49103996-b3e13400-f231-11e8-8c7f-a148e1ad74e0.png">

But mobile is cut off:
<img width="331" alt="image" src="https://user-images.githubusercontent.com/1068783/49104024-c6f40400-f231-11e8-95ac-85fd802219ab.png">

**Comment by alanmoo** [comment]
It seems like this is a template issue, where a different version of the image is being fetched for mobile.

**Comment by mmmavis** [comment]
@kristinashu how should the banner image look like on mobile? Full width with no left/right margin?

**Comment by kristinashu** [comment]
Right, it should be full width with no side margin.

**Comment by kristinashu** [comment]
So the same margin as we have on the live site, just without cropping the image:

<img width="318" alt="image" src="https://user-images.githubusercontent.com/1068783/50863349-37bf2d80-1353-11e9-849a-d971f29851ab.png">

**Comment by mmmavis** [comment]
Thanks! 

@youriwims refer to the comp above ^ for now. We will get you set up with Abstract and Sketch tomorrow.

**Comment by youriwims** [comment]
Thanks @mmmavis & @kristinashu—I was able to fix it.

**Comment by kristinashu** [comment]
Oooh is this ticket possibly related to this one #1485?? Is #1485 still relevant?

**Comment by youriwims** [comment]
Yes, it's definitely related. For this image , I'm fixing the scaling/cropping issue, consolidating the code, and using best practice responsiveness.

**Comment by youriwims** [comment]
This has been fixed. See #2425 & #2632.
