### ISSUE TITLE
Design blog/stories pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2281]
@alanmoo has started this but we should mock it up and give some design recommendations: https://foundation-mofostaging-pr-1905.herokuapp.com/en/stories/

[Alan & Jesse] what is the purpose of this? Is it to tell people stories or to replace our external blogs?

**Comment by jessevondoom** [comment]
The answer to your question on purpose is: both. We want to start using the Foundation site as the primary destination for announcements, etc — with Medium serving as a secondary platform for additional amplification. But we also want a place where we can start to tell deeper/richer stories, specifically about fellows, awardees, and the people in our network. 

So we'd promote this to a top-level /stories URL with a featured story, etc. For all intents and purposes it's a blog, but it'll have fewer posts so the lack of publishing management is probably okay for the foreseeable future.

**Comment by kristinashu** [comment]
@alanmoo @anilkanji few notes from our kick-off meeting https://docs.google.com/document/d/1VboTE2WhLIrX1Vix7yY854X3mya9l2gyAQSeW-SGC0w/edit?usp=sharing

**Comment by kristinashu** [comment]
Moved to https://github.com/mozilla/foundation.mozilla.org/issues/2797
