### ISSUE TITLE
Fellowships: Re-design pages to fit CMS

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2282]
We will be moving all of the [Fellowship](https://foundation.mozilla.org/fellowships/) pages into the CMS. 

### Recommend steps:
- mock-up all the pages in Sketch, using our latest designs and sticking to existing CMS components when possible
- identify sections that might need a new component (ex. cta callouts?)
- open tickets for new components if needed
- start creating pages in the cms
- try improving upon current components -- expanding current configurations

Note: 
- design for Directory page is happening here #2502
- should move this general [FAQ](https://foundation.mozilla.org/en/opportunity/fellowships-faq/) tab over
- working on Support page here #2473 https://redpen.io/yk2753d793670c6ae5

**Comment by kristinashu** [comment]
@Pomax I was taking with @alanmoo the other day and we were thinking the best way to go about this is for me to start re-building the fellowship pages using existing CMS components and then opening tickets if new additional components need to be designed and build.

Would it be possible for you to help me get started? I think I need a primary page, like About Us, with a temporary name like `fellowshipsWIP` (I think you can add a primary page in the cms but I don't have permissions). I will put the content in and then when we're ready, someone can take down the existing hard coded Fellowship page, update the name of the new CMS page from `fellowshipsWIP` to just`fellowships` and then we'll have seamless swap out of https://foundation.mozilla.org/fellowships/ Does that sound right?

**Comment by kristinashu** [comment]
For the record, because Wagtail adds the `/en/` we decided go straight to [/en/fellowships](https://foundation.mozilla.org/en/fellowships/). Pomax create the primary sub page and I now have permissions to edit and add sub pages!

**Comment by kristinashu** [comment]
@beccaklam designs are coming along nicely here https://redpen.io/p/mga45e3eeaaf9bc071

### Next steps:
- update comps based on feedback from designs
- for completeness, add mockup simple FAQ page ([content here](https://redpen.io/p/mga45e3eeaaf9bc071))
- I will email Anil and Amy for feedback from them
- meet with devs to discuss components and possibilities
- clearly define which components are new and which existing ones need updates

**Comment by beccaklam** [comment]
Updates and FAQ page updated in redpen: https://redpen.io/p/mga45e3eeaaf9bc071 @kristinashu

**Comment by kristinashu** [comment]
Awesome! I made a few more updates to the file. Put real placeholder images into the overview page and updated the banner background to the arrow pattern so we aren't so repetitive with the marble pattern. 

Will share with stakeholders tomorrow and if PNI stuff has calmed down then we can meet with devs too!

**Comment by kristinashu** [comment]
Feedback from stakeholders in [redpen](https://redpen.io/p/mga45e3eeaaf9bc071), sofar it's only copy related!

Meeting with devs Monday to talk about new/updated components.

**Comment by kristinashu** [comment]
@beccaklam when you have time, you could start adding content into the [CMS](https://foundation.mozilla.org/cms/pages/265/). This should help point out to us which components need the most attention and fixing up.

**Comment by kristinashu** [comment]
[Notes](https://docs.google.com/document/d/1c9pprS5amWhZbmeS0vy-IJ9adhZc45tmhAbc2r2A6Rw/edit?usp=sharing) from our meeting with devs.

Next steps:
- Rebecca to start adding content into the CMS
- Kristina to compile use case for each component 
- discus and open implementation tickets

**Comment by kristinashu** [comment]
I've updated the component enhancement and new component comps https://redpen.io/p/sj497b7b3aff054ec9

@beccaklam @alanmoo @youriwims @mmmavis please add thoughts/feedback/concerns when you can!

**Comment by kristinashu** [comment]
Becca, I'm going to unassign you since you're wrapped up in the land of misinfo!

My next steps will be:
- Open implementation tickets for the `Image Text` component updates and the new `Image Text Mini` component
- Clean up Sketch file and components\
- Re-crop logos

I've also email stakeholders asking for a decision on the nav item names.

**Comment by kristinashu** [comment]
Cleaned up the pages as much as I could https://foundation.mozilla.org/en/fellowships/, opened tickets for component updates, and cropped the logos.

Still need to clean up the sketch file now.

They have two new types of fellows so will need to create icons for the Get Involved page:
- `open internet engineers` (that track is focused on building internet connectivity in low penetration environments)
- one for `fellows in residence` (these are more senior level fellows)

Also need to update styles on [this google form](https://docs.google.com/forms/d/e/1FAIpQLSdTUqJ9Z4xdcVr4IMzd9UESqm7XwcpVdrIXDeeFNIHUc_vhvQ/viewform).

I'll open new ticket for those ^

**Comment by kristinashu** [comment]
Tickets filed:
- New icons for fellowship types https://github.com/MozillaFoundation/Design/issues/328
- Generic MoFo google form style https://github.com/MozillaFoundation/Design/issues/329

I'm going to close this one! Still need to clean up sketch but that's kinda an on going thing...
