### ISSUE TITLE
Move advocacy pages to foundation site

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2285]
### Goal
Sunset https://advocacy.mozilla.org/ 
(https://github.com/mozilla/advocacy.mozilla.org)

### To do

@alanmoo @cadecairos I've started a [spreadsheet](https://docs.google.com/spreadsheets/d/1ugrj8iFfQS-lcMcj5Rxwx26TTsuo25Yyz048I2R_AZ4/edit?usp=sharing) to try and compile a list of Advocacy pages we would need to move over to the foundation site in order to sunset the Advocacy site. Please add to the list and add any additional columns you think would be useful steps to track. My list is very much overly simplified so please edit it! If this list already exist then please point me to it!

**Comment by alanmoo** [comment]
I pulled in the other subsections on the site by parsing [this file](https://github.com/mozilla/advocacy.mozilla.org/blob/master/src/routes.js)

**Comment by cadecairos** [comment]
We stand ready to shit doewn the servers and redirect requests whenever the content is finished being migrated.

**Comment by kristinashu** [comment]
@alanmoo is this ticket useful or do you want to track this work another way?

**Comment by alanmoo** [comment]
It doesn't look like we're actually going to do this work, instead tracking our solution is happening in https://github.com/MozillaFoundation/mofo-devops/issues/657
