### ISSUE TITLE
Homepage hero gets cropped poorly on mobile

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2289]
<img width="461" alt="screen shot 2018-11-27 at 4 40 03 pm" src="https://user-images.githubusercontent.com/1682681/49113308-36ceb280-f263-11e8-97d9-6cd406e6de80.png">

That's not right. The entire image width should render on mobile.

**Comment by kristinashu** [comment]
Duplicate of https://github.com/mozilla/foundation.mozilla.org/issues/2279
