### ISSUE TITLE
Dot background breaking page on iOS browsers + desktop Chrome/Safari

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2292]
On production, pages that have the dot background ex https://foundation.mozilla.org/en/privacynotincluded/products/apple-watch-4/ have black space to the right of the page (this makes voting on the slider hard).

Screen cap from iPhone:
<img width="287" alt="image" src="https://user-images.githubusercontent.com/1068783/49164712-81dcda00-f2e4-11e8-9ebd-15e7a4667e8a.png">

Also noticing Related Products on these pages (pages with dot background) it much narrower than ones that don't.

With dot background:
<img width="291" alt="image" src="https://user-images.githubusercontent.com/1068783/49164726-87d2bb00-f2e4-11e8-9379-3368e36462e0.png">

Without dot background:
<img width="287" alt="image" src="https://user-images.githubusercontent.com/1068783/49164744-8d300580-f2e4-11e8-90f8-75a8e1b0078b.png">

cc @Pomax @mmmavis

**Comment by Pomax** [comment]
wait, so: even though the html document has `overflow-x: hidden` set, the iphone goes "actually no, I will let you scroll horizontally"?

**Comment by mmmavis** [comment]
We could fix it by adding 
```css
body {
  overflow-x: hidden;
}
```

but adding `overflow: hidden` to high hierarchy containers is usually not the best practice unless we can be 100% certain that we'll never need a horizontal bar at page level for Buyer's Guide. If we aren't certain, we should probably think of another way to implement this.

**Comment by Pomax** [comment]
I can't think of a reason why the buyers guide would ever have a document-level horizontal scrollbar, though. That would just make for a horrible page experience.

**Comment by mmmavis** [comment]
Related to https://github.com/mozilla/foundation.mozilla.org/issues/2120

**Comment by mmmavis** [comment]
> I can't think of a reason why the buyers guide would ever have a document-level horizontal scrollbar, though. That would just make for a horrible page experience.

> (overflow-hiding on the body won't prevent scrollbars for any swipe-bars mid-document, if we ever add those)

Agreed that there's super tiny chance that we'll want a page level horizontal scrollbar. But I really wanna avoid adding `overflow-x: hidden;` to `body` unless that's absolutely the only solution. Having that rule for `body` will make debugging CSS code for its children DOM elements hard. I'd like to be able to tell whether or not my future CSS code for other implementation is creating unnecessary horizontal space outside of the viewport instead of relying on `overflow-x: hidden` to hide any overflow issue for me.

I'll try to get a more proper patch in as soon as I can. If this needs to be fixed urgently, for now let's add 
```css
body {
  overflow-x: hidden;
}
```

**Comment by alanmoo** [comment]
Possible solution: change the `-100%` for left/right 0, and use the following markup (`.container` becomes `.container-fluid` and I added another `.container` inside the product updates row)

```
<div class="container-fluid">
  
  <div class="row with-product-updates">
  
    
    <div class="container">
      <div class="px-5 mt-5 col-12 col-md-10 offset-md-1 bg-white">
```
