### ISSUE TITLE
Add 'Read our research first' jump link and styling to engagement section

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#2293]
We've done some user testing and have noticed that users engage with the creep-o-meter and likely to buy/not buy section before reading our research. Some users have even complained about not being able to change their votes after reading the review. Others say the research is why they're here in the first place and would like to access that first. Since we can't move the engagement section down (per @caltrider's request) we will add a jump link that anchors to the research when a user clicks on it. 

- [x] Add styling to engagement section

- [x] Add jump link that anchors to the beginning of our research (clicking should smoothly scroll the user down the page)

- [x] Hover state #3302FF

**Assets:**
Pink information circle icon: [pink information circle.svg.zip](https://github.com/mozilla/foundation.mozilla.org/files/2625796/pink.information.circle.svg.zip)

**Comp:** https://redpen.io/zr97c45f097ffe0ff4
<img width="897" alt="image" src="https://user-images.githubusercontent.com/1068783/49192950-2cc7b500-f332-11e8-9c65-388f060f10e4.png">

**Comment by caltrider** [comment]
I love it! I'm glad you did that users testing too to see what people like best. Thank you for doing all this.

Only one tiny little word tweak suggestion. I would suggest we say "Learn how to use this guide" rather than "Learn how to use our guide".   
cc: @beccaklam

**Comment by beccaklam** [comment]
@caltrider I actually just changed it to 'How to use this guide', that okay? That way it matches the title of the page they're going to.

**Comment by caltrider** [comment]
Perfect! Thank you @beccaklam

**Comment by beccaklam** [comment]
@mmmavis 
Re: increase padding in the big white box, I think doubling the padding would be a good thing. @kristinashu any thoughts?
Re: styling changes to mobile view, that's a good call. I'll need to make the comp, will post here once it's done. Thanks Mavis!

**Comment by kristinashu** [comment]
> do we also want to increase padding in the big white box? In the comp left padding (or left margin of "Edwin the duck") is 94px whereas on production it's only 48px.

Does this mean all the page content will be narrower? If so I'm good with that but let's just make sure we QA it well.

> Do we want to apply styling changes to mobile view as well?

Good call! I left a couple comments in redpen.

**Comment by beccaklam** [comment]
> do we also want to increase padding in the big white box? In the comp left padding (or left margin of "Edwin the duck") is 94px whereas on production it's only 48px.

> Does this mean all the page content will be narrower? If so I'm good with that but let's just make sure we QA it well.

Oh, I was thinking the box would just increase outward, so the width of the content wouldn't change. Would that affect anything else @mmmavis ? cc: @kristinashu

**Comment by mmmavis** [comment]
@beccaklam did you mean keeping the big white container the same while making the "Read our research first" box wider? It could work but we just need to be careful for mobile as the box might extend outside of the viewport/cut off (if we are using the same design treatment).

**Comment by beccaklam** [comment]
@mmmavis No, I meant keep the content the same but making the big white container wider. Let me know if that makes sense, if not happy to jump on a call!

**Comment by beccaklam** [comment]
Hi @mmmavis , thanks for your patience. Here's the comp for mobile:
https://redpen.io/mge4da91661e19eed3
![screen shot 2019-01-10 at 4 51 33 pm](https://user-images.githubusercontent.com/20977376/50999374-02077980-14f8-11e9-8f21-2e0c1ed079bf.png)
You can find the sketch file in the Buyer's Guide file on the 'Jump Link' page:
![screen shot 2019-01-10 at 4 48 25 pm](https://user-images.githubusercontent.com/20977376/50999410-13e91c80-14f8-11e9-80a4-565589c3777a.png)
Let me know if you have any questions!
CC: @kristinashu

**Comment by Pomax** [comment]
At wide views (desktop etc) does it make sense to also lower the vote buttons, so they line up with the slider? atm it looks like this:

![image](https://user-images.githubusercontent.com/177243/51134146-91a87300-17eb-11e9-844b-94f9d9130587.png)

which feels like a little margin-top would give a more uniform UI:

![image](https://user-images.githubusercontent.com/177243/51134200-bb619a00-17eb-11e9-897f-ca713bc06d34.png)

**Comment by beccaklam** [comment]
@Pomax That's an interesting suggestion, I think though that having the likely/not likely buttons closer to the question makes more sense. It is nice to have the slider and the buttons lined up but for usability have the buttons closer to the question makes more sense than having a giant space there.
