### ISSUE TITLE
Add 'How to use this guide' link

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#2294]
Users are asking for more information regarding our research (why our categories are important, why they should care, etc) and the 'How to use this guide' content answers those questions. Since it's too much to fit into the product page itself without making the page too busy we're going to include a link to the About page that already has the 'How to use this guide' content.

- [x] Add 'Our Research' title

- [x] Add 'How to use this guide' link, and link to About page

- [x] Hover state #3302FF

**Assets:**
Grey information button: [grey-information-icon.svg.zip](https://github.com/mozilla/foundation.mozilla.org/files/2625912/grey-information-icon.svg.zip)

![test b screen 1 copy 11 2x](https://user-images.githubusercontent.com/20977376/49186959-00ad3380-f334-11e8-8810-1bf78206b16a.jpg)

**Comment by Pomax** [comment]
`Add 'How to use this guide' link, and link to About page` is being done as part of the about page layout redesign in https://github.com/mozilla/foundation.mozilla.org/issues/2211

**Comment by mmmavis** [comment]
@beccaklam I realized there are 2 versions of "i" icon - one pink one grey. Is it intentional or should we make them both grey (or pink)?

**Comment by beccaklam** [comment]
It was intentional ... for the top one we really wanted people to notice 'Read our research first' because users were getting confused why they were being asked to vote with so little information. I understand it's kind of strange. Perhaps it wouldn't be a bad thing if both were pink since having users read the 'How to use this guide' info is useful too. Thoughts, @kristinashu ?

**Comment by kristinashu** [comment]
I like the idea of making both of them pink! It helps set a pattern for users. 

Also, please use the same pink and pink hover state color as the header Donate button.

**Comment by beccaklam** [comment]
@mmmavis let's make both the icons pink then :)
