### ISSUE TITLE
Add accordion that explains what unexpected reasons means

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#2295]
Users keep asking what 'unexpected reasons' means.

- [x] Add accordion to 'unexpected reasons' section that has this explanation when expanded: 

>  Nearly every company collects some kind of information on its users. That’s how the internet works. It’s how they use and care for this information that matters. You should know whether a company shares or sells your personal information to others and for what reasons.

>  For the purpose of this report Mozilla determined that if according to a company’s privacy policy, it appeared to share data with third parties that could then use that information to market or advertise to customers, then we labeled it as “Shares information with third parties for unexpected reasons."

>  This does not mean your information is definitely used for these purposes. Simply that the policy leaves the possibility open your information could be used in this way.

![test b screen 1 copy 11 2x](https://user-images.githubusercontent.com/20977376/49186978-16baf400-f334-11e8-8f17-907410101f06.jpg)

**Comment by kristinashu** [comment]
Thank you to Jen for doing most of this!
