### ISSUE TITLE
Banner Update: Replace green/blue banner 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2298]
Followup from https://github.com/mozilla/foundation.mozilla.org/issues/1727 and https://github.com/mozilla/foundation.mozilla.org/issues/1721 and comps https://redpen.io/p/avd5fc0b3db14a7883

### Replace green/blue banner and add call out box

Needed on primary pages like Internet Health, People (although I think this page will be archived soon), About Us, News, Fellowships. Not needed on special primary pages like Home, Initiatives, Participate, or other pages like Campaign and Opportunity pages.

- [x] Swap out the old graphic (gradient and white line art) for one of the new b&w patterns (black/white marble header in https://foundation.mozilla.org/cms/images/)
- [x] Add white cutout box
- [x] Move title off of image and into box (update to h1-heading)
- [x] Add intro text (large-body)

Note: right now banner is all the same but we might make it different on each page https://github.com/mozilla/foundation.mozilla.org/issues/1663

###  Desktop

<img width="1239" alt="screen shot 2018-12-18 at 10 08 02 am" src="https://user-images.githubusercontent.com/1068783/50173802-5464ca00-02ad-11e9-85c5-4ac98a5064a8.png">

### Mobile

<img width="320" alt="screen shot 2018-12-18 at 10 07 43 am" src="https://user-images.githubusercontent.com/1068783/50173800-53339d00-02ad-11e9-91b7-d4ecc6e7aaa4.png">

### Overview
![nav new 2x](https://user-images.githubusercontent.com/1068783/43663943-fd893246-971f-11e8-8b1b-9a0643cbad01.jpg)

**Comment by kristinashu** [comment]
Sorry @mmmavis, @beccaklam is going to look at the dimensions for the white cut out box and text. So maybe hold off on that for now?

**Comment by beccaklam** [comment]
Hey @mmmavis so here are the updated designs. They're not too different, we just lessened the size of the banner and made the heading larger to be more consistent with the rest of the site.
## Desktop:
<img width="1244" alt="screen shot 2018-12-19 at 3 50 43 pm" src="https://user-images.githubusercontent.com/20977376/50255223-df28f000-03a5-11e9-8ee7-88b21b6e0b01.png">

## Mobile
<img width="323" alt="screen shot 2018-12-19 at 3 49 43 pm" src="https://user-images.githubusercontent.com/20977376/50255196-c02a5e00-03a5-11e9-9fa1-01e2557611ac.png">

You can find the design in 'Foundation Site' Sketch file on the 'Header Template' page:
<img width="245" alt="screen shot 2018-12-19 at 3 53 10 pm" src="https://user-images.githubusercontent.com/20977376/50255375-7130f880-03a6-11e9-8ae5-eebf690fd37b.png">

**Comment by kristinashu** [comment]
@beccaklam did you merge this? I don't see "Header Template".

**Comment by kristinashu** [comment]
Never mind, I think there was a merge problem in Abstract. You can see the file by going back in history but let's sort it out tomorrow. Also please note, the desktop header should be the marble black and white graphic, not the arrows.

**Comment by mmmavis** [comment]
So

desktop header: marble black and white graphic
mobile header: arrows

?

**Comment by kristinashu** [comment]
Both marble. The mobile looks right but desktop is wrong.

**Comment by beccaklam** [comment]
Hi @kristinashu and @mmmavis, 

Hmm. Not sure what happened! Sorry about that.
I merged my current branch and I can see the file here:
![screen shot 2019-01-08 at 11 03 31 am](https://user-images.githubusercontent.com/20977376/50842611-12232b80-1335-11e9-865e-f65c0429f235.png)
I've also attached the header image and have updated the comps above to the correct image. [header-img.jpg.zip](https://github.com/mozilla/foundation.mozilla.org/files/2737527/header-img.jpg.zip) Let me know if you need anything else!
