### ISSUE TITLE
Nav Update: Vertical Sub Nav

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2299]
Followup from https://github.com/mozilla/foundation.mozilla.org/issues/1727 and https://github.com/mozilla/foundation.mozilla.org/issues/1721 and comps https://redpen.io/p/avd5fc0b3db14a7883

### Vertical Sub Nav 

On opportunity and campaign pages

- [x] Update yellow bar to black bar
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/1068783/43664652-7edab598-9722-11e8-8ebf-52e5f082a12a.png">

### Sub Nav on Mobile  
- [x] same as horizontal sub nav https://github.com/mozilla/foundation.mozilla.org/issues/2297

### Overview
![nav new 2x](https://user-images.githubusercontent.com/1068783/43663943-fd893246-971f-11e8-8b1b-9a0643cbad01.jpg)

**Comment by mmmavis** [comment]
Done. PR has been merged!
