### ISSUE TITLE
Nav Update: Primary Nav on white

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2300]
Followup from #1727 and #1721 and comps https://redpen.io/p/avd5fc0b3db14a7883

### Main Nav
- [ ] Put nav on white background everywhere (already have this on Home, Initiatives, Opportunity/Campaign, Participate, Fellowships pages but need to add this to the rest of pages **Internet Health, People, About Us, News**)

- [ ] Update all primary nav selected state: increase thickness of the black line to 6px and move it lower down so it is on top of the grey line

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/1068783/43664420-c15a3214-9721-11e8-8e93-b9587dbbec56.png">

### Overview
![nav new 2x](https://user-images.githubusercontent.com/1068783/43663943-fd893246-971f-11e8-8b1b-9a0643cbad01.jpg)

**Comment by alanmoo** [comment]
What's next on this line of updates? The "primary page" template seems like a likely candidate? (See the "about" page for an example)

**Comment by alanmoo** [comment]
It already is - https://foundation.mozilla.org/cms/pages/47/edit/

Based on the comps, it seems the banner area needs some attention, which will cascade a bit into other areas of the site templates. I'm asking if that banner area is the next thing to focus on after this ticket lands.
