### ISSUE TITLE
Buyers Guide pre-launch DB Stats

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#2301]
To report pre- and post-launch stats, @caltrider would like a count of opinions submitted before our launch date (Nov 13th). @cadecairos - can you grab this?

We can view total opinions in data studio and use analytics to gather other pre-launch stats.

**Comment by caltrider** [comment]
Heya quick question, will this include all types of engagements?
creepometer, link shares, comments, social shares, social mentions

**Comment by xmatthewx** [comment]
Let's make a list. Better yet, a spreadsheet! 

We need @cadecairos to get stuff from DB on creepometer and comments. Other stuff we can get from analytics. For social, I wonder if kevin has a way to count stuff on social that will be more accurate than my count of taps.

**Comment by cadecairos** [comment]
The number of creepiness rating and would/would not buy ratings before Nov 13 is 4916

**Comment by xmatthewx** [comment]
Closing. Thanks @cadecairos. Dropping this into a [spreadsheet](https://docs.google.com/spreadsheets/d/1TlriNwIPT5jmpcfpW8CJWHdik0eei02510xZv9vna9g/edit?usp=sharing )

**Comment by xmatthewx** [comment]
@cadecairos - can you give us one more count of ratings? today's is fine. any recent day. this will give me a better sense of GA numbers, and what % of traffic appears in there.

**Comment by xmatthewx** [comment]
Nevermind. Got 51,030 from the dashboard.
