### ISSUE TITLE
Buyer's Guide - Bad "id" primary_nav.html

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#2304]
In line 27 in [`network-api/networkapi/buyersguide/templates/primary_nav.html`](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/buyersguide/templates/primary_nav.html#L27)

```html
id="primary-nav-links d-flex align-items-center flex-wrap"
```

We should remove `d-flex align-items-center flex-wrap` from `id`.

**Comment by Pomax** [comment]
yeah that looks like a bunch of classes accidentally ending up in an id
