### ISSUE TITLE
Randomised Buyer's Guide Products Votes generation takes forever.

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2320]
We should look at whether we can speed up the "Randomised Buyer's Guide Products Votes" generation task in the data faker, as it takes a considerable amount of time to just run that task at the moment (probably due to me not realising there was a more efficient way of writing it!)

**Comment by kristinashu** [comment]
Closing this since buyers guide is no longer an active project and won't be for a while and who knows what we will be doing for it!
