### ISSUE TITLE
[Fellowship mini site] Broken Link fix for Sarah Kiden

### ISSUE THREAD

**Issue by annmarie123** [mozilla/foundation.mozilla.org#2337]
I found a broken link on the front page of the fellowship website (https://foundation.mozilla.org/fellowships/). Sarak Kiden's name link should lead to her pulse profile here: https://www.mozillapulse.org/profile/491.

Thanks in advance!

**Comment by SukhnandanMalhotra** [comment]
Hey, I'd like to work on this, could I take this one?

**Comment by SukhnandanMalhotra** [comment]
**Fix broken link for a fellow profile** #2390

**Comment by SukhnandanMalhotra** [comment]
#2390

**Comment by kristinashu** [comment]
Looks like this is done https://foundation.mozilla.org/fellowships/directory/! Thank you for the help!!
