### ISSUE TITLE
Simple column component for CMS pages

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#2339]
Staff authored pages often present a lot of info. Some of it would benefit from a simple table or card component. 

Let's explore design before we commit to implementation. 
 - Let's keep it super simple, something that can give staff 2 or 3 side by side boxes that collapse nicely on mobile. 
 - Give author option to include borders or not. 
 - If we give author option to add a header to each box, we could limit contents otherwise to just plain text. 

Here's a quick example on codepen (first one, not second) https://codepen.io/team/css-tricks/full/KzWORB

cc @kristinashu

**Comment by kristinashu** [comment]
Closing this ticket since Rebecca will be working on this here https://github.com/mozilla/foundation.mozilla.org/issues/2643
