### ISSUE TITLE
Add some code that lets us curate our domain whitelist from inside Wagtail

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2342]
We're using an `env` at the moment to curate the whitelist of allowed embeddable domains and it's kind of a pain? We should totes fix that to become CMS-list-enrichable, where we can do something like "go to /cms, open settings, open whitelist, add domain, good to go".

And then have that kick in _in addition to_ what we preclear in the env, so that we can ensure there are a few domains that are always allowe, with the wagtail page showing those as non-editable entries or something

/cc @alanmoo @cadecairos

**Comment by alanmoo** [comment]
Sure, this seems like it would be nice but I don't think it's particularly worth spending time on. More like a thing that might be nice to add upstream to Wagtail itself

**Comment by cadecairos** [comment]
Yeah I'd love to be able to update the CSP via the admin interface (this is how we do it on the internet health report).

That said, I'm not really willing at the moment to maintain that project. might be nice to have it as an upstream feature.

**Comment by Pomax** [comment]
assigning myself so I remember to file a feature request on the wagtail repo.

**Comment by kristinashu** [comment]
@Pomax did you file it with wagtail? If so then it sounds like we won't be taking this any further.

**Comment by gideonthomas** [comment]
Closing as this should be done upstream in wagtail. @Pomax just a reminder in case you haven't filed it yet.

**Comment by Pomax** [comment]
That's the wrong order in which to do things. File first, then close.
