### ISSUE TITLE
Make buyers guide stats more accessible

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#2343]
Buyer's guide has collected a bunch of awesome stats on public opinion. 

They could be more accessible to researchers, journalists, and return visitors. Currently, these users need to revote to view a breakdown on opinions. 

One option - make the vote count below the vote button a link to display stats on that product. 

![image](https://user-images.githubusercontent.com/53411/49955757-a2ef1e80-fed1-11e8-9f53-412d7d2ab072.png)

Another option - build a `/stats` page that displays a list view of stats for the site and products. 

![image](https://user-images.githubusercontent.com/53411/49955701-7cc97e80-fed1-11e8-89f6-469eef523403.png)

cc @alanmoo for a quick guess on effort required before we invest in design

**Comment by kristinashu** [comment]
This feature isn't a priority so closing and we can re-asses at the end of the year when we relaunch.
