### ISSUE TITLE
Default OG image/text

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2346]
Until 30 seconds ago, links across the web to foundation.mozilla.org had no OG image. They still have no description. I added the Mozilla logo (using the promote tab on the CMS) though it could probably use a better formatted/higher res image. We also need some text.

@jessevondoom @xmatthewx @kristinashu @Sydette

**Comment by xmatthewx** [comment]
Strange. Thanks for catching. This is definitely a thing we had in place before, though probably with old Networky language.

**Comment by kristinashu** [comment]
yea, there's a ticket for that!
