### ISSUE TITLE
Fix how-to-use accordion hardcoded h2+p expectation

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2356]
The how-to-use page currently has some rules in place that assume an `h2` is only ever followed by a single `p` for accordion folding. We have at least one entry for which we really want three paragraphs, so let's fix the code to understand how much it needs to fold instead of assuming there's only one paragraph.

(see https://github.com/mozilla/foundation.mozilla.org/pull/2288#discussion_r240902509)

**Comment by alanmoo** [comment]
This isn't worth the effort given.
