### ISSUE TITLE
base.html for non-PNI pages lacks any sort of meta/og tags

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2357]
Related to https://github.com/mozilla/foundation.mozilla.org/issues/1582, it turns out that our `base.html` that is used as basis for all standard foundation.mozilla.org pages has no meta tags at all, meaning any page that extends it gets zero OG, twitter-card, etc. data for search engines and social media to tap into O_O

The base template is located [here](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/templates/pages/base.html), with an example of how we deal with OG tags in PNI [over here](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/buyersguide/templates/bg_base.html)

**Comment by HSR05** [comment]
@kristinashu @Pomax  I've looked at the template and the base.html too. Can you just guide me a little so that i can work on it? Thankyou 👍

**Comment by Pomax** [comment]
certainly: if you look at https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/buyersguide/templates/bg_base.html#L9-L17 you can see that there is a block of OpenGraph metadata that allows search engines, twitter, etc. to pick up on "what the page is". However, if you look at https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/templates/pages/base.html, there is no opengraph data at all, so we would like to add an opengraph block to the latter such that it has general information where needed, and page-specific information where appropriate.

**Comment by HSR05** [comment]
So what general information should i add as meta data. I saw the https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/buyersguide/templates/bg_base.html#L9-L17  which states that this page is "A buyer's guide for connected products" and similarly in description.
Now i know what to do. Can you tell me what general info should be added to the base.html as meta data. Like the content of title, description and other meta tags.

**Comment by alanmoo** [comment]
@youriwims Is this related to what you're working on?

**Comment by youriwims** [comment]
@alanmoo , I was mainly working on fixing the logic so that our page titles appear in the `<title>`, but I can take a look at this as well.

**Comment by alanmoo** [comment]
@alanmoo to check if this is still true

**Comment by alanmoo** [comment]
I believe this is addressed now- I see OG data on the homepage and other pages, so it's making its way in somehow.
