### ISSUE TITLE
Donate modal can't be closed on iPhone landscape mode

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2359]
Probably other devices too- the combination of the fixed nav and fixed modal conflict. 
![image](https://user-images.githubusercontent.com/1682681/50121921-6b150d80-0228-11e9-8788-49c6373e9629.png)

@kristinashu Possible solution: How would you feel if the nav wasn't sticky on mobile?

**Comment by kristinashu** [comment]
Could the popup go over top of the nav? And maybe fill the entire screen?
