### ISSUE TITLE
Templatize nav related code as much as we can

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#2364]
Follow-up for [Updated multipage nav styling & code refactor/cleanup](https://github.com/mozilla/foundation.mozilla.org/pull/2348)

- templatize nav related code
- utilize Bootstrap classes where appropriate

---

Note to self:

- campaign page's multipage nav looks slightly different than primary page's multipage nav

**Comment by kristinashu** [comment]
@alanmoo is there some high level template thinking that needs to happen before this happens?

**Comment by alanmoo** [comment]
I think there's a conversation that needs to happen around when pages show up in the navigation of their parent page which will influence a bit of the approach we take to this work.  Probably worth setting up a call about; let's confirm that thought in stand today.

**Comment by alanmoo** [comment]
Related to #2877

**Comment by alanmoo** [comment]
@mmmavis What's the goal for this issue? To use a singular set of code for all navigation instances?

**Comment by mmmavis** [comment]
Ideally having a singular set of code for all navigation instances would be awesome but I don't know if it's technically doable (or worth doing) given that we have so many variations of nav in the codebase. I haven't touched nav related code for a while so maybe it's now easier to achieve this than half year ago when this ticket was first created.

**Comment by alanmoo** [comment]
Agreed, but this ticket feels a bit too nebulous to be useful. I'm gonna close it and if we see tangible cases where we can improve things, let's file new tickets then.
