### ISSUE TITLE
New Fellowship and Awards pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2366]
@jessevondoom @jenntbeard @mehan based on the [copy doc](https://docs.google.com/document/d/1vrHAKGi-vzJAB8V3GVZJigRC41fecdj-2wz-Pk7AFrU/edit) and our chat I think this is what we need. If this doesn't make sense, no worries! @beccaklam is going to do a quick mockup tomorrow to help us visualize our options.

## Initiatives Page (blocked by creating the Awards page)
URL: https://foundation.mozilla.org/en/initiatives/ 

Update Fellowships & Awards cta button:
- have two separate buttons "Fellowships" (links directly to https://foundation.mozilla.org/fellowships) and "Awards" (links directly to https://foundation.mozilla.org/awards)

## Awards Landing Page
URL will be: https://foundation.mozilla.org/awards/

This will have two pages:
- Intro page with copy from [this doc](https://docs.google.com/document/d/1vrHAKGi-vzJAB8V3GVZJigRC41fecdj-2wz-Pk7AFrU/edit?usp=sharing)
- Directory page with about 110 projects pulled from Pulse (will need separate categories for `creative media` `NSF WINS` and  `Gigabit`)

I think we should try to make these pages as [CMS pages](https://foundation.mozilla.org/en/initiatives/awards/) (still needs to be styled) but with the 'Primary page' black & white header and horizontal nav like the /fellowship page will have: cc @alanmoo

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/1068783/50188858-e1bd1400-02d7-11e9-839f-5ff5cf22f3b3.png">

**Comment by mehan** [comment]
Sounds like an accurate summary to me--thanks, @kristinashu!

**Comment by jenntbeard** [comment]
Images for use are here: https://drive.google.com/open?id=1dgHbTSO3cw4WZZbiOvjt3n5hyuW2-cMg

**Comment by jenntbeard** [comment]
Also, here is the Awards Portfolio page Ann Marie has created - https://foundation.mozilla.org/en/initiatives/mozilla-gigabit/mozilla-gigabit/ (it will cover more than just Gigabit projects, but it's a start).

**Comment by xmatthewx** [comment]
Exciting to see this coming together!

To me, it seems like the combined fellowship and awards page speaks more to us and funders, and doesn't feel optimized for our audiences. My instinct is that we serve them better with two buttons that lead to two landing pages. Each landing page could have a small box that says "hey, we also have awards that might help your work. take a look →". In our About section on the site, we could use the combined language as it provides a birds-eye view on why we do both these things in tandem. 

Regarding Pulse projects, I will huddle up with @gideonthomas  and @alanmoo  to figure this out. I will likely advocate for a few featured projects and button to view 'em all on Pulse. Pulse provides search, favs, sharing, tags ... features that make 100+ projects easier to navigate.  We're working on program view for Pulse so Awards could have it's own landing and search. 

Hope this is helpful!

**Comment by xmatthewx** [comment]
> Also, here is the Awards Portfolio page Ann Marie has created - https://foundation.mozilla.org/en/initiatives/mozilla-gigabit/mozilla-gigabit/ (it will cover more than just Gigabit projects, but it's a start).

Oooooo - look at that awesome page!

**Comment by jenntbeard** [comment]
That sounds great @xmatthewx - our biggest hope with the Awards page (at least) is to help prospective applicants understand our opportunities and where we might be able to support their work.  Ann Marie is adding projects to Pulse - given what you've said Matthew - should I just have her continue to work on that and you all will take care of the tagging, sorting, layout?? Thanks!

**Comment by kristinashu** [comment]
@jenntbeard I think Ann Marie should continue what she is doing and Matthew can just go in and clean up the tags if needed.

Am I correct in assuming that the Gigabit page https://foundation.mozilla.org/en/initiatives/mozilla-gigabit/mozilla-gigabit/ should be incorporated into this new Awards page so that everything is streamlined and in one place?

**Comment by jenntbeard** [comment]
The Gigabit Page is really meant to be the Awards Directory, covering all of them. Ann Marie is working on that now. Thanks!!

**Comment by kristinashu** [comment]
I've quickly mocked up what I mentioned yesterday.

A) This is what was is in the copy doc(initiatives -> landing page -> fellowships page OR awards page): 
<img width="360" alt="screen shot 2018-12-19 at 2 23 49 pm" src="https://user-images.githubusercontent.com/1068783/50252631-66716600-039c-11e9-96e1-51d32ed5d612.png">

B) This is what we are recommending for a simpler and better user experience (initiatives -> fellowships page OR awards page): 
<img width="360" alt="screen shot 2018-12-19 at 2 49 22 pm" src="https://user-images.githubusercontent.com/1068783/50252896-5908ab80-039d-11e9-990d-aec0682208b2.png">


If we go with B but you feel we would sometimes need to link people to a combined landing page, we could still have one that you could link out to (but we wouldn't link to it from the /initiatives page).
<img width="360" alt="screen shot 2018-12-19 at 2 24 20 pm" src="https://user-images.githubusercontent.com/1068783/50252633-66716600-039c-11e9-9cea-3e7c51a155a7.png">

Rough comps: https://redpen.io/p/prf05ef30aeb8c698f

![initiatives 2x](https://user-images.githubusercontent.com/1068783/50252625-62454880-039c-11e9-8854-abdddfc2b577.jpg)

![awards 2x](https://user-images.githubusercontent.com/1068783/50252623-61acb200-039c-11e9-9129-0dbadb7a440b.jpg)

![fellowships 2x](https://user-images.githubusercontent.com/1068783/50252624-61acb200-039c-11e9-8c08-a8c26ea8bedc.jpg)

**Comment by mehan** [comment]
These mockups look amazing! Personally, I am all for option B--I don't see why we would insert yet another landing page to click through unless we absolutely have to. Thanks, @kristinashu!

**Comment by jenntbeard** [comment]
WOW! This is so beautiful! (And so amazing to see this all coming to life!) I think Option B is great - I always like streamlining where possible - not sure we would need a combined landing page at all with this. Thank you!

**Comment by kristinashu** [comment]
Yay amazing! 

I will touch base with Alan tomorrow about the small bits of dev work that will need to be done and I will continue to mockup the directory page and images.

**Comment by kristinashu** [comment]
Alan has set up the Awards page so the url is now https://foundation.mozilla.org/en/awards/! The nav and banner still have the old styling but Mavis should have that updated early in the new year. 

I have also moved Ann Marie's work over to final url https://foundation.mozilla.org/en/awards/directory/. 

## Edit content

@jenntbeard @mehan @annmarie123 please make any cms edits to these new pages. They are at the primary level so click on `Homepage` and then `Awards` to edit the landing page or click on the arrow on the right side to edit the Directory page. 

To edit Awards page:
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/1068783/50304834-e43d7c00-0445-11e9-937b-3535d26262e9.png">

To edit Directory page:
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/1068783/50304910-236bcd00-0446-11e9-8153-a686df7209d6.png">

## Delete old pages

If everything it ok with these pages then we should delete the other versions under Initiatives and Opportunities to avoid any confusion.

## Add CTA button

Once we are happy with these, Alan can add Awards button to the [/initiatives](https://foundation.mozilla.org/en/initiatives/) page:
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/1068783/50304988-675ed200-0446-11e9-82ae-44a165bd32b9.png">

**Comment by mehan** [comment]
Ditto what Jenn said--thank you all so much for pushing this through so quickly! It will be great to start the new year having a page on the website for our work. 🙂 

I think we should be good to go with regard to deleting the old pages and adding the nav button.

**Comment by jenntbeard** [comment]
YES!!

**Comment by kristinashu** [comment]
Ok they're all deleted!

But unfortunately we won't be able to add the button to /initiatives page until just after the holiday break.

**Comment by jenntbeard** [comment]
As sad, we were soclose!! :)

**Comment by kristinashu** [comment]
I know Sorry! It's more than just a cms update so it's a little more involved and we don't want to rush it then have something broken on the site over the holidays when everyone is off.

I guess we could have that intermediary landing page in the meantime? That can be done just through the cms.

<img width="360" alt="screen shot 2018-12-19 at 2 23 49 pm" src="https://user-images.githubusercontent.com/1068783/50252631-66716600-039c-11e9-96e1-51d32ed5d612.png">

**Comment by jenntbeard** [comment]
I'm just being a pain - it's totally fine to wait.

**Comment by kristinashu** [comment]
And it's live! https://foundation.mozilla.org/en/initiatives/
