### ISSUE TITLE
Fix language in newsletter CTA

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/foundation.mozilla.org#2375]
<img width="1440" alt="screen shot 2018-12-19 at 12 43 14 pm" src="https://user-images.githubusercontent.com/5816130/50305109-f1676480-045f-11e9-8eca-33f5308c27e7.png">

At the bottom where we have our newsletter CTA, the text looks really weird. Neither "Network", "Movement", or "Internet" should be capitalized.

**Comment by SukhnandanMalhotra** [comment]
Hey, I am new to open source world, I'd like to work on this. Can I take this up?

**Comment by gideonthomas** [comment]
Hi @SukhnandanMalhotra! I just realized that this isn't an engineering issue (or a good first issue). It's something that needs to be changed in the system itself so I'm going to make the change. Sorry about that!

**Comment by gideonthomas** [comment]
Edited via CMS (can be seen live in the fellowships FAQ)

Note from @Sydette - there's a question about stylizing "Internet health" as title case or not. I have changed it to all lowercase for now. Let's file a new ticket if it needs to change.
