### ISSUE TITLE
Buyers Guide About page nav is broken looking

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2377]
https://foundation.mozilla.org/en/privacynotincluded/about/

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/1068783/50307789-2ff42380-044e-11e9-8ec8-ca35da1bfeca.png">

**Comment by mmmavis** [comment]
@kristinashu Is this side nav's styling supposed to be the same as what we have on the main site? e.g., https://foundation.mozilla.org/en/opportunity/artists-open-web/

**Comment by kristinashu** [comment]
Yes! Should be the same.
