### ISSUE TITLE
Add Awards link to Initiatives page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2379]
Based on https://github.com/mozilla/foundation.mozilla.org/issues/2366

### Add new Awards page link http://foundation.mozilla.org/awards/ to:
- [x] sub nav (after Fellowships)
- [x] Fellowships & Awards section

https://redpen.io/qo2596f105b2a24626

![red-pen-c8a5e13f-344b-4c3e-cc52-ba89d9a5eab3](https://user-images.githubusercontent.com/1068783/50308033-fbcd3280-044e-11e9-9067-269b0c825902.jpg)

**Comment by alanmoo** [comment]
Because this page is baked into the CMS, adding a change like this is more involved than just adding some markup, and it's not going to happen this week. However, if Awards is its own section (like IHR, Mozfest, etc), everything can be done in the CMS.

Is it a hard requirement that they're tied together?

**Comment by alanmoo** [comment]
In fact, I'd like to state my *strong* opposition to doing it the way this ticket is proposing; It introduces a lot of opportunities for bugs to creep in. This is one of those cases where the power of the CMS in one spot comes at a cost of being in a CMS in another spot- we were able to get those pages going quickly, but we shouldn't try to push against what we've previously built here.

**Comment by kristinashu** [comment]
Fellowships and Awards definitely want to be seen as one unit. They talked about having the one button but and then going to a landing page than then goes to the two separate pages but that would be terrible ux.

**Comment by alanmoo** [comment]
Ok, how about this?

* Hardcode the page navigation instead of iterating over the set of `initiative sections` on the page
* Add an optional second button to the `InitiativeSection` model so that we can add one for Initiatives and Awards

**Comment by kristinashu** [comment]
Yes that sounds good!

**Comment by alanmoo** [comment]
Alright. I'm gonna pop this on the board for an "ease-in-to-the-year" ticket

**Comment by kristinashu** [comment]
Looks good on staging! https://foundation.mofostaging.net/en/initiatives/

Assigning to myself to update cms once pushed to prod.

**Comment by kristinashu** [comment]
Live! https://foundation.mozilla.org/en/initiatives/
