### ISSUE TITLE
Auto crop cms images

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2402]
Designers to provide a list of image dimensions for all cms image types so devs can make the cms crop the images. 

We should try to be consistent with our ratios as possible so  staff can easily use one image in multiple places and not have to crop it to a bunch of different sizes.

### Home
- hero image (desktop & mobile - 4:3 ratio)
- featured news image (desktop & mobile - 16:9 ratio)
- both happening now sections (card desktop & mobile, and wide version - 16:9 ratio) 

### Initiatives
- Feature program (desktop & mobile - 16:9 ratio) 

### Participate
- hero image - WIP (pending header template)
- small feature cards - 16:9 ratio
- larger features - 16:9 ratio

### Future
- Make sure we do this for upcoming Fellowship and Blog pages.
- Design fallback images for cms images #2416

**Comment by kristinashu** [comment]
Based on our from slack convo: 

@natalieworth @sabrinang do you have any recommendations for image ratios?

Our Abstract Sketch file should already have some ratio recommendations so maybe start with those, adjust them if needed, and then run them past the brand guideline work.

**Comment by beccaklam** [comment]
@kristinashu I added the image ratios to your list above. Only one missing is the Participate hero image that's pending the header template I'm working on.

**Comment by kristinashu** [comment]
@beccaklam do you think hero image could work at 16:9 to really make things consistent?

**Comment by beccaklam** [comment]
@kristinashu you mean for the home page? Yeah I think it would work.

**Comment by kristinashu** [comment]
Nice! I've opened an implementation ticket #2426
