### ISSUE TITLE
CMS Component Bug: spacer isn't working

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2403]
Adding a spacer component doesn't add any space.

**Comment by mmmavis** [comment]
Might be margin collapsing related.

@kristinashu where were you trying to add spacer component to? I just wanna crosscheck to see if my guess is right.

**Comment by mmmavis** [comment]
@alanmoo potential good first bug - probably only have to change the bootstrap class we used from margin class to padding class.

**Comment by kristinashu** [comment]
@mmmavis did you do something? Looks like it's working now!?

**Comment by mmmavis** [comment]
Ummm no I didn't do anything. 🤔

**Comment by kristinashu** [comment]
Lol ok well I guess it's good to close 🙃
