### ISSUE TITLE
Fallback images for cms images

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2416]
Once auto crop cms images #2402 is done, we designers should create fallback for each image type in case staff don't upload an image.

**Comment by kristinashu** [comment]
Since everything is 16:9 we could probably just use one placeholder everywhere with the exception of people in the Fellowship directory which would be 1:1.

Tais made this but we are moving away from the gradient. But I do like the idea of doing something slightly different for people.

<img width="815" alt="image" src="https://user-images.githubusercontent.com/1068783/50919491-cb4a3a00-13f7-11e9-94fd-b0195e6cc0c1.png">

**Comment by kristinashu** [comment]
Sorry what line design? It will replace the image under Science Fellows in the above comment and then a new image for regular (non-profile) images.

**Comment by gideonthomas** [comment]
ah ok sorry I wasn't clear. I meant the image under Science Fellows - it's not ideal at the moment :P

**Comment by youriwims** [comment]
@kristinashu, the progress on this will be affected by #2687 .

**Comment by kristinashu** [comment]
I idea was that designers would create one image at 16:9 and one at 1:1 for devs to use. Are you saying that is no longer possible?

**Comment by youriwims** [comment]
No, that's exactly what I was suggesting. So that's perfect that you
already had that planned.

>

**Comment by kristinashu** [comment]
@sabrinang gave these examples in slack:

mozilla.org blog has pattern fallbacks you can put on our blue-purple colour, can prob make some similar
- https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/wp-content/themes/frontierline/img/fallbacks/pattern-1.png
- https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/wp-content/themes/frontierline/img/fallbacks/pattern-2.png
- https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/wp-content/themes/frontierline/img/fallbacks/pattern-3.png
- https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/wp-content/themes/frontierline/img/fallbacks/pattern-4.png
- https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/wp-content/themes/frontierline/img/fallbacks/pattern-5.png
- https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/wp-content/themes/frontierline/img/fallbacks/pattern-6.pngwe 


@beccaklam has also pointed out that the misinfo campaign could use some placeholders for resource links. Matthew suggests some generic icons/thumbnails that can be used for links and call out text.

**Comment by beccaklam** [comment]
Some ideas for the 16:9 design: https://redpen.io/p/bufe0d8e87faf7a719 @kristinashu @sabrinang @natalieworth @taisdesouzalessa

**Comment by Pomax** [comment]
I'm closing this as a stale issue, given that both our content and the CMS itself is several years newer at this point. If there are still places where we need fallbacks, let's file those as needed.
