### ISSUE TITLE
Update cms auth due to Google+ API getting shut down

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2417]
We need to update the auth solution due to Google shutting down Google Plus  - the immediate option is to use Google's newer Google Sign-In (https://developers.google.com/identity/sign-in/web/), and then with that in place, add oidc support (https://mozilla-django-oidc.readthedocs.io/en/stable/installation.html) and opening things up to mozillian accounts.

/cc @alanmoo @gideonthomas @cadecairos

**Comment by Pomax** [comment]
Hm, so looking at our code, we're currently using oauth2 rather than google+ sign in, so it looks like we can skip the "moving to google sign-in" step?

**Comment by Pomax** [comment]
@alanmoo @gideonthomas @cadecairos it looks like G+ won't affect us, let's re-evaluate whether we want to do any auth changeovers or leave things as they are for now.

**Comment by Pomax** [comment]
Note: there is some g+ reliance under the hood in python-social-auth but they're working on getting that fixed in https://github.com/python-social-auth/social-core/pull/301 before G+ is shut down, so we should be able to just wait for them to clean that up and then bump the version.

**Comment by alanmoo** [comment]
Sounds good, let's not spin our wheels unnecessarily. (That being said, I am still a bit curious as to the cost/benefit of switching to IAM for authentication.)

**Comment by Pomax** [comment]
And done.
