### ISSUE TITLE
[CMS] Update help text for 'title' and header' fields

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#2419]
In various page template files (primary, opportunity, campaign and maybe more) we have logic like the following

```
if title
   show title
else if header
   show header
```

or 

```
if root.title
   show root.title
else if page.header
   show page.header
else
   show page.title
```

I wanted to clean up the code but couldn't do so as I couldn't figure out what `title` and `header` are and how they are being used. 

### On Wagtail
- Help text for `title`: is currently `The page title as you'd like it to be seen by the public` (which is vague and not meaningful)
- Help text for `header`: we don't have one

We should update the help text so it's clearly to users what each field is for and where on the site/page they will show up.

**Comment by Pomax** [comment]
Both title and header come from the page as it exists in the CMS. `page.title` / `page.header` is the current page's title and header field, `root.title/root.header` are relevant only to "mini sites" (opportunity/campaigns) and are the title and header for whatever is the "main page" of those mini sites.

**Comment by Pomax** [comment]
Making this clearer is a good idea, let's start by finding all the places we reference them and seeing "how we use them" to see if we can come up with a description for title and header that makes more sense.

**Comment by youriwims** [comment]
Here are the instances I've found: 
 1. https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/primary_heroguts.html
  2. https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templates/wagtailpages/campaign_page.html#L33
3. https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templates/wagtailpages/opportunity_page.html#L23
4. https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templates/wagtailpages/static/initiatives_page.html#L13

**Comment by cadecairos** [comment]
Closing this issue due to its age, if this is work that we still want to do, please refile this with up to date information so that it can be put in the correct milestone with up to date estimates.
