### ISSUE TITLE
Add a few CMS pages to review app (faker?)

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#2427]
Make sure review apps have the following pages set up 

- [Awards](http://foundation.mozilla.org/awards/)
- [IH](https://foundation.mozilla.org/en/internet-health/)

so we don't have to manually create these pages every time for testing

/cc @cadecairos (not sure who to assign this ticket to)
/cc @kristinashu as FYI

**Comment by patjouk** [comment]
What do you have in mind for the IH page?

**Comment by mmmavis** [comment]
Maybe just a `primary page` set for `/internet-health` so that route is not 404 on review apps?

**Comment by cadecairos** [comment]
@mmmavis does the content of this page need to look similar to production or is it more important to have it exist in the first place?

**Comment by kristinashu** [comment]
Mavis is out on PTO for a while. It would be deal if it had similar content as prod so we can see if a component was effected. But content for those IH and Awards pages don't change very often so it ok if the review app doesn't get constantly updated.

**Comment by mmmavis** [comment]
Agreed!

> It would be deal if it had similar content as prod so we can see if a component was effected. But content for those IH and Awards pages don't change very often so it ok if the review app doesn't get constantly updated.

**Comment by cadecairos** [comment]
There doesn't appear to be any unique features on these pages so lets close this.
