### ISSUE TITLE
Add wagtail-experiments to our setup for A/B testing

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2428]
Now that https://github.com/torchbox/wagtail-experiments is effectively out of beta, and is compatible with our setup, it's probably a good time to add it in.

It introduces a new settings option called (surprise!) "experiments", which lets you A/B(/C/D/E/...) test page conversion in the sense that you can set up a set of pages, pegged to a "control page", and users hitting the control page's URL will be served either the control page, or any of the alternate pages you specified. Metrics are gathered for the purpose of determining conversion rates, either based on a target CMS-managed URL that acts as "goal", or custom JS that tells wagtail-experiments there has been a completion (e.g. signalling completion if a user clicks "donate", as part of the click handler).

The reporting interface also comes with a way to not just look at the conversions, but also peg which of the various test cases should replace the original page handling, if it turns out the control page does not perform as well as one of the alternative test cases.

It's all pretty sleek!

/cc @alanmoo

**Comment by Pomax** [comment]
How much detail do we want to add to our own README.md when it comes to explaining A/B testing?

**Comment by alanmoo** [comment]
At least a heading and a link to Wagtail Experiments documentation.
