### ISSUE TITLE
Copy for new banner

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2429]
https://docs.google.com/document/d/1c-nwpxS06CnoqO3--qLUT0pkWaECSgUpq9Saic_5MuQ/edit?usp=sharing

**Comment by Pomax** [comment]
Is this related to any specific other issue?

**Comment by kristinashu** [comment]
I'll close it. Sydette says she'll do this tomorrow but doesn't really work from github anyways.
