### ISSUE TITLE
Design audit to make sure design follows site's style guide

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#2440]
https://foundation.mozilla.org/style-guide/

Foundation site's style guide was pretty up to date at one point. However, it seems like overtime we have been adding too many variations of the existing styles to the design/codebase without reflecting them on the style guide. Two things I spotted the most is **the number of shades of the gray** and **different type styles** (e.g., use `.h5-heading` but change the color to x, font weight to y, and make the font size smaller <--- this is not `.h5-heading` anymore).

Before things have gone tooooooooo far, I would advocate for doing a site audit soon so we can decide if we should update the style guide so it includes all the new things we have added to the site design/codebase OR clean up our site design/codebase to make sure we are really following our style guide.

/cc @kristinashu 
/cc @sabrinang (I think this sort of relates to your ongoing branding work?)

**Comment by kristinashu** [comment]
Yes thank you @mmmavis! Maybe it's something we can review together at the office.

**Comment by kristinashu** [comment]
@mmmavis @sabrinang is this ticket useful? Design audit and style updates to the site have come a long way!

Have you two decided if we'll maintain both https://foundation.mozilla.org/style-guide/ and https://foundation.mozilla.org/en/docs/brand/?

What would be the next steps for this ticket?

**Comment by mmmavis** [comment]
We can try maintaining `/style-guide` but I'd like to remove the component portion of it since it's hard to keep that portion always up-to-date.

Not sure what needs to be done in the design end though. Do we need to update https://foundation.mozilla.org/en/docs/brand/ as well as the master Sketch file???

**Comment by kristinashu** [comment]
There are design tickets for updating /docs/brand/ and the master Sketch file https://github.com/mozilla/foundation.mozilla.org/issues/2548. 

So should we close this ticket and open a new one to update /style-guide and remove the component portion?

**Comment by kristinashu** [comment]
Opened a followup ticket https://github.com/mozilla/foundation.mozilla.org/issues/2903 and closing this one, please feel free to reopen if needed.
