### ISSUE TITLE
Evaluate if we can remove "takeover" component and "upcoming" component

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#2442]
... since it's an oooooolllllldddddd component.

This includes `takeover.jsx`, `upcoming.jsx`, related SCSS, and some portions of `main.js`

**Comment by Pomax** [comment]
It might make sense to do this at the same time we're removing `upcoming.jsx`

**Comment by mmmavis** [comment]
Good call. That component isn't being used anymore either.

**Comment by mmmavis** [comment]
@kristinashu 

Do you know if we wanna keep this takeover component? It was initially built two years ago (related ticket [here](https://github.com/mozilla/foundation.mozilla.org/issues/288)) and it's not being used for the site currently.

**Comment by kristinashu** [comment]
Please remove it!!!

**Comment by mmmavis** [comment]
Whooohooooo 🗑
