### ISSUE TITLE
Buyers Guide: design V-Day hero banner

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2444]
Based on https://github.com/mozilla/foundation.mozilla.org/issues/2438

Design a V-Day themed banner to replace holiday themed banner.

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/1068783/51061104-e5764a80-15a6-11e9-975a-09e353687847.png">

Bonus: Design a generic post V-Day themed banner while you're at it!

**Comment by natalieworth** [comment]
Have a couple options for the header in Redpen here. I am trying to keep it not too busy since the other content on the page feels a bit busy too. [Let me know what you think](https://redpen.io/p/mg0194f75b80b2008e)

cc @kristinashu @beccaklam @caltrider @sabrinang

**Comment by caltrider** [comment]
Love these! Left a few comments. My favs are the hearts with the "don't spy" and "hey siri" 
Good work @natalieworth

**Comment by kristinashu** [comment]
Nice! We're gonna go with V1. @natalieworth can you please share the final background image jpg here and then I'll open an implementation ticket.

**Comment by natalieworth** [comment]
Buyer's Guide header image for Valentine's [is here](https://drive.google.com/file/d/1KAN2RMdN9OvjQ8BlmgTRobd_oqyk4HVU/view?usp=sharing).

Original illustrator file is [here](https://drive.google.com/drive/folders/1JuFZFdY-BV5wrCon1rQLAWGiOUEaTNom?usp=sharing) (if designers need).

**Comment by natalieworth** [comment]
[Updated the banner](https://drive.google.com/file/d/1KEAmnSm-UqwwEs22X6YxLfqKZ8sPyskp/view?usp=sharing) @kristinashu to have same dimensions as previous. :D

**Comment by kristinashu** [comment]
w00t thanks!
