### ISSUE TITLE
Buyers Guide: crop new product images & NSFW treatment 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2445]
Based on #2438 

[Product list](https://docs.google.com/spreadsheets/d/1hm7LliaSu3ypNFlp5oj8CKTRu4Q46nbjTBw-nXR3oDE/edit?usp=sharing) should be finalized Jan 14.

Then we will need to source images and crop them.

_Note: some might need special nsfw treatment?_

**Comment by beccaklam** [comment]
@xmatthewx @kristinashu For nsfw treatment I'm not exactly sure what this would look like. What about a special overlay on the homepage that slightly blurs the image with a nsfw warning? Thoughts?

**Comment by kristinashu** [comment]
Our lawyer Abigail thinks we need to do something to the thumbnail images but doesn't want us to "overdo it". So as we chatted about at crit, @natalieworth can you work with Rebecca to figure out some sort of either overlay or pixelation and also possibly a little NSFW sort of badge?

**Comment by kristinashu** [comment]
Asking devs about possibly of having one modified image for thumbnails and then a separate one for the product page https://github.com/mozilla/foundation.mozilla.org/issues/2518

**Comment by beccaklam** [comment]
@kristinashu @natalieworth What if we just took one of the social images Nat's already made, crop it and tweak the words to a nsfw warning? And this could just be the image for all the nsfw thumbnails? It relates to the Vday update and even long term the heart will give people get an indication of why it might not be safe for work.
![image](https://user-images.githubusercontent.com/20977376/51762885-f93da880-209e-11e9-9197-476a16bb3117.png)

**Comment by kristinashu** [comment]
Yeah that would be cute!

Jen is working on the copy with Abigail. She's trying to keep it was short as possible but ideas have been ranging from:
- “The linked content may not be appropriate for all audiences.”
- “Content may not be appropriate for all audiences” 
- “Slightly NSFW”

So if it's the short version then this could work!

Also, cross-linking some from Nat https://redpen.io/p/yg5faa4931a3fe3418

**Comment by xmatthewx** [comment]
Nice!! On the product page, if we want it, engineers could use a blur filter that disappears on hover.

**Comment by natalieworth** [comment]
I like "Slightly NSFW" for content length!

**Comment by kristinashu** [comment]
Final copy decision from Abigail is `18+` for all the sex toy images. Nice & short!

So we could try an option with the candy heart like Becca suggested, one with a blurred or pixelated image with copy over top, and then what ever other ideas you might have.

As you design these, can you also please place them up in the context of the homepage so we can see them in-situ to help decided?

**Comment by natalieworth** [comment]
Design options for 18+ tag are here: https://redpen.io/p/nzfa8afdb875caa41e
Just waiting for final approval/ feedback from Abigail and Ashley.

**Comment by kristinashu** [comment]
Based on message from Jen, this has been approved! 

@natalieworth can you please export an svg of the heart (make sure it's a gray from the style guide) and provide some guidance for blur in the implementation ticket https://github.com/mozilla/foundation.mozilla.org/issues/2518

**Comment by beccaklam** [comment]
Awesome! I think everything in this ticket is done then :)
