### ISSUE TITLE
Increase shares after voting

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2446]
A lot of people are voting but very few are sharing. 

Currently we have about 29k creepiness votes in analytics and only about 29 vote shares, that’s 0.1%. Let’s try and get 5 out of 100 voters to share!

We might be able to test different options if Pomax is done setting that up in time.

#### Ideas 
- remove link to comments 
- make share title larger and say something like `Share!` or `Invite your friends to vote!`
- make icons bigger??
- 

#### Current state
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/1068783/51061604-acd77080-15a8-11e9-929c-ee13519aa7ee.png">

cc @xmatthewx

**Comment by xmatthewx** [comment]
Excellent. Design-wise, let's try and land on 2 options: one bolder, one super bold. Will be fun to test!

**Comment by beccaklam** [comment]
@kristinashu @xmatthewx Here are two quick ideas: https://redpen.io/p/utee9e897aa82628cd
Let me know what you think!

**Comment by beccaklam** [comment]
@xmatthewx 
### Bold Option:
![screen shot 2019-01-15 at 3 37 40 pm](https://user-images.githubusercontent.com/20977376/51208401-94829100-18db-11e9-859f-e55dc12c0156.png)


### Bolder Option 
Kristina already pointed out this is probably too much and the UX for this coupled with the donation ask would be a bad experience. Probably going to nix it, was just trying out ideas

Post-vote pop-up:
![screen shot 2019-01-15 at 3 37 48 pm](https://user-images.githubusercontent.com/20977376/51208406-99474500-18db-11e9-8775-38ed866ec15b.png)

After user closes pop up:
![screen shot 2019-01-15 at 3 37 54 pm](https://user-images.githubusercontent.com/20977376/51208412-9cdacc00-18db-11e9-9f03-c1c9977cb021.png)

**Comment by xmatthewx** [comment]
Cool, cool. Looking great! Yep, pop up is probably too much to tackle. 

One idea: move 367 votes from the top to your new heading: `367 Votes. Invite your friends!` I'm thinking that people like to share stuff that's validated by other people's engagement.

**Comment by xmatthewx** [comment]
Excellent. 
 - The top headline in option 2 (bolder) is very effective. Great idea. We could remove the line of text "Thanks for ... results" and make this box all very clean and simple. I think results infographic speaks for itself. If you disagree we could just label it "results". 
 - I'll step back now and let you and Kristina decide button color and make the final call on all of this. 
 - I'm very _very_ curious to see if we this helps dial up engagement!

**Comment by beccaklam** [comment]
@kristinashu @xmatthewx 
Feedback based on crit and matthew's comments -- Bold option remains the same, some updates to Bolder option:
- eliminated sub header line
- changed colour of buttons to reflect social platform brand (when applicable)

https://redpen.io/gs490ea2b6eb47dbb7
<img width="869" alt="screen shot 2019-01-17 at 3 57 37 pm" src="https://user-images.githubusercontent.com/20977376/51348495-e4df2780-1a70-11e9-8155-e2e9cbd5642e.png">

**Comment by kristinashu** [comment]
I think you could group the titles in the bold option, like you had on the bolder option. It makes for better hierarchy and feels less clustered.

<img width="940" alt="image" src="https://user-images.githubusercontent.com/1068783/51355775-fd4d4300-1a6c-11e9-988b-8cb50e64daf4.png">

**Comment by xmatthewx** [comment]
I really like it with no subhead. If you make them both the same with button color as the only variable, then an A/B test will give us unambiguous info on why one performs better than the other.

**Comment by kristinashu** [comment]
May be one could have the number of votes in the large text and the other with the smaller text?

**Comment by xmatthewx** [comment]
I worry a little about 2 things: 

 1. info overload - this little space has so much text, numbers, buttons competing for attention. I think it's better without subhead. 
 1. test results - if test A does better than test B, we won't know if it's because of button color or the headline. 

Implementation
 - When you file implementation, please ask dev to make sure we keep GA Event on share buttons. 
 - If we do A/B test, ask dev to  "prepend `GA Event Label` with `test A:` and `test B:`"
 - I'm super excited!

(I'm going to unsubscribe from this thread now 😉 )

**Comment by kristinashu** [comment]
Oh sorry, I misunderstood! I thought you **didn't** want buttons to be the only variable between A and B. But yes, I think they should be the same (except for buttons)!

**Comment by beccaklam** [comment]
Edits after above feedback, I think we're close!

## Variant A (Black and white buttons)
![screen shot 2019-01-21 at 11 09 30 am](https://user-images.githubusercontent.com/20977376/51485845-13108000-1d6d-11e9-8cf4-e1c4d5a7f94e.png)

## Variant B (Colourful buttons)
![screen shot 2019-01-21 at 11 07 38 am](https://user-images.githubusercontent.com/20977376/51485867-202d6f00-1d6d-11e9-987d-dda9970e64e0.png)

@kristinashu @xmatthewx

**Comment by kristinashu** [comment]
Looks good to me! 

@xmatthewx is the idea that once pomax has implemented A/B testing on the site, will can test these live?!

**Comment by xmatthewx** [comment]
I think we should go ahead and implement one of them for v-day. you pick. we should have enough traffic to compare new version against holiday version. If a/b testing does land, we can go further and test color vs b&w buttons, but let's not wait for that.

**Comment by beccaklam** [comment]
That sounds good to me. My vote would be Variant A, it follows button styles we've already introduced on the page and the colour combination is the most accessible.

**Comment by kristinashu** [comment]
Yes, Variant A please!

**Comment by beccaklam** [comment]
Here's the mobile version for Variant A. Closing this ticket for now, implementation opened: #2510 
![screen shot 2019-01-23 at 2 45 20 pm](https://user-images.githubusercontent.com/20977376/51634430-392b5100-1f22-11e9-86f8-9177806ff072.png)
@kristinashu @xmatthewx
