### ISSUE TITLE
Remove the donate banner when in local dev

### ISSUE THREAD

**Issue by patjouk** [mozilla/foundation.mozilla.org#2451]
The banner is quite big and frequently in the way when you're doing some local dev. It would be great to have a flag to hide it.

**Comment by kristinashu** [comment]
There is talk of removing the banner https://github.com/mozilla/foundation.mozilla.org/issues/2481

I'll assign this to myself until we decide.

**Comment by Pomax** [comment]
I think in the mean time we can probably update `main.js` by replacing ` if (donationModal ) {` with something like  `if (donationModal && !env.DEBUG) {`?

**Comment by kristinashu** [comment]
We will be removing the popup but only once we have a permanent cta in the footer, so maybe in a month from now. Up to you if you want to do the quick fix in the meantime.

**Comment by Pomax** [comment]
for developers (who need to load localhost:8000 a lot) it's probably worth disabling the popup in the mean time.

**Comment by kristinashu** [comment]
Banner has been turned off so this is not longer a priority.
