### ISSUE TITLE
Follow up ticket for Engagement Section on Product Page

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#2461]
Follow up ticket from #2447

## Issue One

- [ ] Make sure padding between 'Tell us what you think banner' and the paragraph above is 48px

_Context:_
There's supposed to be 48px padding between the 'Tell us what you think' banner and the paragraph above, but it doesn't look like the comp has that? cc: @mmmavis 
### Deployment:
<img width="1440" alt="screen shot 2019-01-15 at 8 54 57 am" src="https://user-images.githubusercontent.com/20977376/51193122-1cee3b00-18b6-11e9-95e4-0bf042547b89.png">

### Comp:
<img width="981" alt="screen shot 2019-01-15 at 9 11 59 am" src="https://user-images.githubusercontent.com/20977376/51193153-2d9eb100-18b6-11e9-94c8-6f771ca5175b.png">

## Issue Two

- [ ] Change mb-5 on the charts div to mb-4

_Context:_
I think because of a bunch of margins + padding, the space below the charts looks a bit large:
![screen shot 2019-01-15 at 11 05 43 am](https://user-images.githubusercontent.com/20977376/51192911-989bb800-18b5-11e9-891c-a2e2d5e318cc.png)

If we change the bottom margin to mb-4 that seems to be better:
<img width="1440" alt="screen shot 2019-01-15 at 8 54 57 am" src="https://user-images.githubusercontent.com/20977376/51192810-5f634800-18b5-11e9-98a4-62c78b46326f.png">

**Comment by mmmavis** [comment]
this is a follow-up ticket for https://github.com/mozilla/foundation.mozilla.org/pull/2447

**Comment by mmmavis** [comment]
I'll take a look soon.
