### ISSUE TITLE
V-Day: update Buyers Guide hero image

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2464]
Based on design in #2444 & parent ticket #2438.

**_Do not push live until around Feb 5._**

Update white holiday banner with this new V-Day one. [JPG is here](https://drive.google.com/file/d/1KEAmnSm-UqwwEs22X6YxLfqKZ8sPyskp/view?usp=sharing).

![pni-valentines-header- 2x](https://user-images.githubusercontent.com/1068783/51283589-8eed7f80-199d-11e9-9a9a-34c3c22ea803.jpg)

And should look like:

![red-pen-635a139b-2efd-40b9-9e77-70b324078dc6](https://user-images.githubusercontent.com/1068783/51218729-86843e80-18e2-11e9-87f4-da90be7fe634.jpg)

**Comment by kristinashu** [comment]
Bonus might be to make this image update-able in the cms.

cc @alanmoo

**Comment by alanmoo** [comment]
Unlikely before next week, unfortunately, but there's definitely opportunity to make the guide a bit less hard-coded outside of products.

**Comment by kristinashu** [comment]
Soft launching Feb 5!

**Comment by mmmavis** [comment]
k I'll work on the PR now.

@kristinashu 

Question: is it intentional that we are removing the grey thin border in between nav and banner (it's not on mockup)?

**Comment by kristinashu** [comment]
Eagle eyes! The line should be there.

We need it more for when users scroll down.

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/1068783/52095703-e0d6fd80-2578-11e9-9908-85bef792d7d6.png">

**Comment by mmmavis** [comment]
Cool that makes the update a lot more easier to implement lol
