### ISSUE TITLE
Fellowships: host org updates

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2473]
Fellowships team will requesting host org applications so we need to update [Support the Program](https://foundation.mozilla.org/fellowships/support/) content with content found at the bottom of [this doc](https://docs.google.com/document/d/1ke01ZGzdktlDkBb_GVbF-fuA47jLHx8ksDGAC6vfrHw/edit#).

- hard launch on Mon Feb 4 but lets have it live by Thurs Jan 30 
- content is not yet final
- they will create an FAQ for Host Orgs (once they have it, we should update the url to something like https://foundation.mozilla.org/en/fellowships/support-faq or https://foundation.mozilla.org/en/opportunity/fellowship-support-faq
- Email Amy for approval

cc @xmatthewx @alanmoo @gideonthomas

**Comment by gideonthomas** [comment]
Marking this as blocked on https://github.com/mozilla/foundation.mozilla.org/issues/2282 based on my understanding. Feel free to remove the label if I'm wrong.

**Comment by kristinashu** [comment]
@gideonthomas this isn't blocked. This needs to go live at the end of this month and CMS-ify work will not be done by then so this will be hard coded. 

I'm working on the design for it now. Copy isn't completely final but it is enough for me to start with and the program staff are award they need to finalize copy asap.

**Comment by kristinashu** [comment]
Shared this comp https://redpen.io/eh8702bc7fda6e22d5 with Amy for some feedback.

**Comment by kristinashu** [comment]
Approved and opened: Fellowships: implement updates to Support page - launch Feb 1 #2530
