### ISSUE TITLE
Fellowships: backend for directory component

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2474]
Based on https://github.com/mozilla/foundation.mozilla.org/issues/2282

**Goal:** allow staff to update & add new fellows to the [Directory page](https://foundation.mozilla.org/fellowships/directory/).

We want to keep the same content and also add in a short bio for each Fellow (will mock this up).

@alanmoo @xmatthewx @gideonthomas @Pomax this will probably require a new CMS component, can you please add your thoughts on how to go about this?

**Comment by xmatthewx** [comment]
Great. Thanks. A few things to discuss... 

 - **Summary**: "directory" component would allow author to pick filters much like our "profile listing" component, but include tabs for navigation. 
 - **Tabs**: It _could_ automatically use the year field to create tabs, or allow author to pick a field for tabs. Use case: mozilla directory filters to show everyone with "program type: mozfest; year: 2019", but includes "profile_type" for show tabs for staff, wrangler, speaker.  
 - **Model**: Now is probably terrible time to bring up a concern of mine and Abby's: people can only be associated with one program in pulse model. And year is a field unattached to programs. Out of scope?

<img width="787" alt="image" src="https://user-images.githubusercontent.com/53411/51342225-4f886700-1a61-11e9-9529-22ae49010354.png">

---

Here's our existing "profile listing" component

<img width="608" alt="image" src="https://user-images.githubusercontent.com/53411/51342189-37b0e300-1a61-11e9-98a4-4f46bbb79dee.png">

**Comment by alanmoo** [comment]
I knew you'd be able to give a good overview of this, thank you 😄

There's a balance to be had here of flexibility and complexity, I think you're pretty much at the sweet spot, @xmatthewx.

>- **Summary**: "directory" component would allow author to pick filters much like our "profile listing" component, but include tabs for navigation. 

Sounds good. I see this new component as, functionally, a wrapper around the "profile listing" component. (Engineering note: In terms of code we should be able to share it, but nesting wagtail blocks can be a bit gross. Though I'm not sure we'd need to, this may be a matter of nested JSX components.)

> - **Tabs**: It _could_ automatically use the year field to create tabs, or allow author to pick a field for tabs. Use case: mozilla directory filters to show everyone with "program type: mozfest; year: 2019", but includes "profile_type" for show tabs for staff, wrangler, speaker.  

This is basically a "specify a query param and the (site-visitor) clickable arguments. The query param could be a fixed list, but it would probably be significantly more complicated to make the arguments anything more than a comma separated list.

> - **Model**: Now is probably terrible time to bring up a concern of mine and Abby's: people can only be associated with one program in pulse model. And year is a field unattached to programs. Out of scope?

Out of scope, but fixing that shouldn't require us to double back on this in the future.

**Comment by gideonthomas** [comment]
> Out of scope, but fixing that shouldn't require us to double back on this in the future.

Let's file a ticket for this and work on it sooner rather than later -- it is one of the "medium priority" items for our team but I anticipate this becoming an issue for a couple of things we'll be working on in the near future.

**Comment by xmatthewx** [comment]
> Let's file a ticket for this [profile categories and years]

ticket filed here: https://github.com/mozilla/network-pulse-api/issues/445

> This is basically a "specify a query param and the (site-visitor) clickable arguments. The query param could be a fixed list, but it would probably be significantly more complicated to make the arguments anything more than a comma separated list.

What would this look like as form inputs? I don't totally understand.

**Comment by alanmoo** [comment]
Something like this? 
<img width="985" alt="image" src="https://user-images.githubusercontent.com/1682681/51400105-8b7d0400-1b15-11e9-9b6d-c48ef1f4551e.png">

**Comment by alanmoo** [comment]
> I would maybe label this Tab category and Tab items. Not sure. I see the fields above as filters.

Sure, no strong opinions there.

> For Tab options/items, is author naming values in the Tab category? So, they can basically include some, ignore others? That seems reasonable. Obviously there's risk of author error, but we can deal with that. This is definitely a power user component.

Yes, because it would be way too hard to pull all the possible options for different categories, or fix them and remain up to date with the ones in Pulse. Fixing the categories themselves feels reasonable though. And yes, it's a little bit of rope but not too much that it's dangerous.

> I'm guessing search is an aspiration, but it would be insanely powerful to make a directory of people with "fake news" in their bio.

Good point, we don't have searching of profiles in the API yet. I was thinking entries. If that was something we got to, implementing the functionality I describe shouldn't be too hard as it's all query params on the back end.

**Comment by kristinashu** [comment]
Opened up frontend ticket for @youriwims to get started on.

@alanmoo @Pomax @youriwims I'll set up a time for us to chat over the backend component. (Note: similar existing Pulse Profile listing components https://foundation.mozilla.org/en/opportunity/mozilla-open-leaders/round-7/mentors/)

Design won't be changing too much. Year filter and the general layout will stay the same. Here's a list of updates to the cards:

### Updates to Fields
- remove `Fellow, 2019` since it's very repetitive
- replace issue tags with short bio (also pulled from their Pulse profile)

### Updates to Design
- reduce black stroke to 1px
- make location icon and text `Medium Gray ($medium-gray) #909090` from [Style Guide](https://foundation.mozilla.org/en/style-guide/)
- reduce size of share icons and make them black (but make sure they have a large enough hit area on mobile)
- remove `See work` link
- remove light gray line

<img width="773" alt="image" src="https://user-images.githubusercontent.com/1068783/51630407-f0ae6c00-1efe-11e9-8ffe-bf822c1e8641.png">

### Full designs https://redpen.io/p/mga45e3eeaaf9bc071

![red-pen-337c7faa-acfa-4aed-e165-c9578764c2c1](https://user-images.githubusercontent.com/1068783/51629846-78937680-1efd-11e9-9af8-1f32e2fd227d.jpg)

**Comment by alanmoo** [comment]
Based on our convo yesterday, @Pomax will identify the technical approach we can take to ensure this component is flexible and performant.

**Comment by youriwims** [comment]
Closing this ticket since the component is complete. (Ref #2701)

cc: @Pomax @kristinashu
