### ISSUE TITLE
Horizontal Sub Nav should only show "primary" pages

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2477]
Host FAQ is a child page of Support the Program, but it shouldn't show up in the navigation.
<img width="787" alt="image" src="https://user-images.githubusercontent.com/1682681/51353564-fdeed500-1a7e-11e9-9bbf-babfb05ed824.png">

**Comment by mmmavis** [comment]
@alanmoo by "primary nav" I assume you didn't mean the nav that's shared Foundation site-wide? Did you mean the the horizontal nav that appears on "multipage" primary page and its children? 

(fyi, I just created a [ticket](https://github.com/mozilla/foundation.mozilla.org/issues/2478) for us to streamline terminology we use to refer to different types of navs on the site.)

**Comment by kristinashu** [comment]
Yes, he means the horizontal sub nav that appears on primary pages and opportunity/campaign type pages.

<img width="840" alt="image" src="https://user-images.githubusercontent.com/1068783/51354494-a6456f00-1a68-11e9-84a2-8f4629840b7d.png">

i.e `Host FAQ` should not show up like this
<img width="684" alt="image" src="https://user-images.githubusercontent.com/1068783/51354653-2075f380-1a69-11e9-9fae-5629486f4ede.png">


Note: Vertical sub nav that appears on opportunity/campaign type pages should continue to show tertiary pages.

**Comment by mmmavis** [comment]
Cool. Sounds good. Let me know if this still needs more discussion / or is ready for a fix.

**Comment by alanmoo** [comment]
I think we need to determine the rules for this a bit more clearly. Questions that come to mind:

* These are a shared navigation component, with different CSS for horizontal/vertical, is that correct @mmmavis?
* If so, do we simply hide tertiary* pages on the horizontal nav? Or do we always hide/show based on the tertiary page template type (for example, create a new page type to be used as children of "primary" pages, whic will _never_ show in that navigation)


*In the above example, Host FAQ is a tertiary page

**Comment by mmmavis** [comment]
> These are a shared navigation component, with different CSS for horizontal/vertical, is that correct @mmmavis?

Not yet. That work was delayed a bit. I was waiting for my previous nav related PRs to be reviewed so I jumped to work on other non-nav tickets in the meanwhile. I should be able to continue the nav work soon.

> If so, do we simply hide tertiary* pages on the horizontal nav? Or do we always hide/show based on the tertiary page template type (for example, create a new page type to be used as children of "primary" pages, whic will never show in that navigation)

I think this is more of a design question for @kristinashu ? Right now there are around 6 versions of nav code snippets in the codebase. I cleaned up the styling to make sure navs have consistent look but I still need to take care of the logic part as they all seem to have their own nav display logic.

**Comment by kristinashu** [comment]
Not too sure what the design question is? Horizontal navs should never show tertiary pages while vertical navs should always show tertiary pages.
