### ISSUE TITLE
Streamline terminology for different types of navs

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#2478]
There are many different types of navs on Foundation site. We should streamline the terminology we use to refer them to avoid confusion.

Some examples I've seen people using

- main nav
- primary nav
- secondary nav
- multipage nav
- side nav
- horizontal nav
- ... etc

/cc @kristinashu to triage

**Comment by kristinashu** [comment]
Do these work for you? https://redpen.io/vp5721a2a03e94bf21

**Comment by kristinashu** [comment]
@sabrinang do you think these should go into the style guide?

**Comment by sabrinang** [comment]
@kristinashu Yes I think we should, in the brand standards planning outline it'll be noted under Design / Website / UI Elements / Navigation

**Comment by kristinashu** [comment]
Ok excellent! I think this is good to close but please reopen if I'm wrong.
