### ISSUE TITLE
Keep Donate closed for return visitors over x-time period 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#2481]
Return visitors are likely to be annoyed by the donate modal, especially if they have donated. (On both buyers guide and foundation site.) Return visitors are awesome people, so that's not ideal.

Let's consider keeping it closed for a week or month. First from a UX perspective. Then tech. 

Keep in mind that we have flexibility to do something like ... keep closed after a single donate tap, or two x-close taps. Or using an explicit "don't show again" link at bottom.

**Comment by kristinashu** [comment]
Lol YESSSS!

**Comment by kristinashu** [comment]
Currently it tracks by tab only so we would need to change that.

I'd say the ideal scenario is: show it the first two times a user visits the site and then once a month after that.

cc @alanmoo

**Comment by alanmoo** [comment]
We can do that, but I'm curious as to when we start getting into GDPR "Hey we use cookies on this site" territory.

**Comment by xmatthewx** [comment]
You're right, but dang that feels like an unfortunate consequence given our intentions. Does the letter of the law go into things like what's stored, why it's accessed, and whether it's stored in a cookie or localstorage? 

If we don't want to go that route, we should consider designing something less disruptive (and possibly less effective).

**Comment by alanmoo** [comment]
Looks like it brought in just under $1100 in [December](https://analytics.google.com/analytics/web/#/report/trafficsources-campaigns/a49796218w101806119p105783219/_u.date00=20181201&_u.date01=20190124&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.adContent&_r.drilldown=analytics.campaign:mainsite)

**Comment by kristinashu** [comment]
I like the idea of building it into the footer, like a call-out just above it, so it's permanent and on every page. Only potential issue would be if we then also want to add an email signup above the footer and it started getting busy with too many CTAs.

If everyone is cool with this approach, I can open a design ticket to play around with a few layouts then share them with Anil?

**Comment by xmatthewx** [comment]
Yes let's mock up some options. I think we probably choose either sign up or donate, but good to explore various directions. And, we can still use the pop over for peak campaigns.

**Comment by kristinashu** [comment]
Cool, Nat will mock up a few options here #2546 and then we can open an implementation ticket to build it and disable the popup.
