### ISSUE TITLE
Spacing and order is wrong on product page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2501]
@mmmavis any idea what happened here? Looks like Updates, Related Products, and Comments are in a different order than before and Related Products & Comments are way too close to each other now?

Screen cap from prod:
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/1068783/51489734-05073300-1d5e-11e9-8d1e-b701586242ed.png">

Comp: 
https://redpen.io/bcd47ecb6d670654da
![red-pen-4490dc46-2483-4f6f-b619-2dcd752949d2](https://user-images.githubusercontent.com/1068783/51489864-63ccac80-1d5e-11e9-9783-abccee2551c2.jpg)

**Comment by mmmavis** [comment]
@kristinashu do you remember which URL that was from? I just tested it on production. Spacing needs fixing but order seems right to me.

**Comment by mmmavis** [comment]
Ah, nvm. Found it: https://foundation.mozilla.org/en/privacynotincluded/products/fitbit-versa-watch/ .

**Comment by kristinashu** [comment]
And https://foundation.mozilla.org/en/privacynotincluded/products/jabra-elite-65t-earbuds/

**Comment by mmmavis** [comment]
Ah okay. I am able to reproduce the issue now. 

I wonder if we ever got the ordering and spacing implemented right. It seems like we didn't touch that part of code in the past 2-3 months 👀 .

**Comment by kristinashu** [comment]
🤔
