### ISSUE TITLE
Fellowships: Re-design Directory

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2502]
Re-asses the directory pages before we turn to CMS.

Notes:
- we would like to add short bios for individual fellows in the directory
- reference blue-sky people page designs
- review Tais' blue-sky design for Directory filters
- dev ticket for this #2474
- design for other CMS pages #2282

**Comment by kristinashu** [comment]
I'm recommending some subtle updates to the [Fellowship Directory cards](https://foundation.mozilla.org/fellowships/directory/).

Since we've moving away from different types of fellowships and since staff regularly specifically  reference current fellows, continuing to filter by year seems to make the most sense. 

### Updates to Fields
- remove `Fellow, 2019` since it's very repetitive
- replace issue tags with short bio (also pulled from their Pulse profile) - bio feels more meaningful to the average user than our issues

### Updates to Design
- reduce black stroke
- reduce size of share icons (also aligns better with Pulse profile)
- reduce CTA link since there are so many with in on one page
- remove light gray line for cleaner design

![fellowcard](https://user-images.githubusercontent.com/1068783/51500448-d3ed2980-1d82-11e9-8a51-4068ff371d0e.jpg)

### Full comp
https://redpen.io/me6c690075cd81cd6f

![directory 2x](https://user-images.githubusercontent.com/1068783/51500259-47db0200-1d82-11e9-811c-5c46c2cd3680.jpg)

cc @xmatthewx @alanmoo @Pomax @beccaklam

**Comment by alanmoo** [comment]
This seems reasonable. Is this ticket ready to be handed over to dev? Feels like a good one for @youriwims to work on.

**Comment by kristinashu** [comment]
@xmatthewx what do you think?

**Comment by xmatthewx** [comment]
Excellent. Your adjustments are all great. One thing:
 - What if link text was "Profile & Projects"? I think work or projects is important. Not sure we need _see_ or _view_.

**Comment by kristinashu** [comment]
Noting that we should also update the other Pulse Profile listing components to align with the new layout/styles https://foundation.mozilla.org/en/opportunity/mozilla-open-leaders/round-7/mentors/

**Comment by kristinashu** [comment]
Done! 

Fellowships: frontend for directory component #2511 
Fellowships: backend for directory component #2474
