### ISSUE TITLE
IHR research page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2508]
IHR team has created a new page for research https://foundation.mozilla.org/en/initiatives/internet-health-research-archive/.

### To do:
- [x] Link do this research page from the [/internet-health](https://foundation.mozilla.org/en/internet-health/)

- [x] Improve the design on the research page

@xmatthewx @gideonthomas @alanmoo is this right?

**Comment by kristinashu** [comment]
I've added a button to the research page at the bottom of [/internet-health](https://foundation.mozilla.org/en/internet-health/). Let me know if that's what y'all had in mind.

**Comment by xmatthewx** [comment]
Yes. 
 - I think the button makes sense. Share that with Sam after we spruce up the page.
 - Short-term, we can clean up design in wagtail. Thumbnails for the first few reports would be nice. 
 - Long-term: I filed a brief to enhance pulse wagtail component to serve this use case. Take a look. As you design for short-term, keep long-term in mind.

**Comment by kristinashu** [comment]
Here's the spruced up page https://foundation.mozilla.org/en/initiatives/internet-health-research-archive/

**Comment by xmatthewx** [comment]
Excellent. So much easier on my eyes. Do you want to share with Sam? Or should I follow up? Either is fine. If you, cc me so I can restart the thread with her about promoting this stuff.

**Comment by kristinashu** [comment]
Ok I've emailed Sam!
