### ISSUE TITLE
[Wagtail] Image Resolution 

### ISSUE THREAD

**Issue by youriwims** [mozilla/foundation.mozilla.org#2509]
Follow-up to PR #2425 : 

Although we're able to manipulate the image quality of uploaded wagtail images, the solution in using jpeg-quality may not be the best option. For some reason, when using this feature the image produced is quite pixelated at an unacceptable level. Maybe we could look into using .webp formatted images since they tend create a more optimized image.

cc: @Pomax @mmmavis

**Comment by mmmavis** [comment]
Question - What image optimization tool are we using?

**Comment by youriwims** [comment]
Currently, just the available options in the [Wagtail documentation](https://docs.wagtail.io/en/v2.1/topics/images.html) and then I go and check the image analysis on [webpagetest.org](http://webpagetest.org/).
