### ISSUE TITLE
Increase shares after voting implementation 

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#2510]
This is the implementation ticket for issue #2446 

- [x] Change header to h3, [M]h3 for mobile, however, since things are centered in this section of the page can we change the text-align also to center?
- [x] Add vote count to above header
- [x] Delete 'View comments or share your results'
- [x] Change social icon button styles (follows the would buy/wouldn't buy button styling, except only one option per button)

## Desktop:
![screen shot 2019-01-23 at 2 44 52 pm](https://user-images.githubusercontent.com/20977376/51634170-92df4b80-1f21-11e9-849b-0268ed848773.png)

## Mobile:
![screen shot 2019-01-23 at 2 45 20 pm](https://user-images.githubusercontent.com/20977376/51634191-9d014a00-1f21-11e9-80db-8a66ca141327.png)

You can find the file in abstract here:
<img width="343" alt="screen shot 2019-01-23 at 3 15 53 pm" src="https://user-images.githubusercontent.com/20977376/51634254-cd48e880-1f21-11e9-9874-41a3b00fa7f7.png">

**Assets:** Wasn't sure if any new assets were needed let me (@beccaklam) know if anything is needed.

**Comment by kristinashu** [comment]
@Pomax are you working on this? We're aiming to have it done for launch early this week.

**Comment by Pomax** [comment]
Ah! I read this issue wrong, but I can definitely take this one.

**Comment by kristinashu** [comment]
Lol thank you!

**Comment by Pomax** [comment]
Where might I find the "link" icon? (we have the fb, twitter, and email already)

**Comment by kristinashu** [comment]
Could you use the one at the top of each product page (but make it black)? 
<img width="943" alt="image" src="https://user-images.githubusercontent.com/1068783/52245517-c497d100-2896-11e9-8fb9-c070dc5ecc10.png">

**Comment by Pomax** [comment]
That should work - I'll make it a different file though, so it can sit alongside the other social media icons in the social media icon dir.

**Comment by Pomax** [comment]
PR up - I added several breakpoints to keep things from looking weird at intermediate sizes, each size documented in the PR with a screenshot.
