### ISSUE TITLE
Fellowships: frontend for directory component

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2511]
Based on design in #2502. I believe @youriwims will be doing the frontend (this ticket) while @Pomax will be doing the backend in #2425. Let's kick this off with a quick call to make sure we're on the same page. 

**Goal:** turn this existing page https://foundation.mozilla.org/fellowships/directory/ into a CMS component that staff can edit/add themselves. 

(Note: the current design has a loading icon, can we keep that?)

Design won't be changing too much. Year filter and the general layout will stay the same. Here's a list of updates to the cards:

### Updates to Fields
- remove `Fellow, 2019` since it's very repetitive
- replace issue tags with short bio (also pulled from their Pulse profile)

### Updates to Design
- show images at 1:1 ratio
- have a fallback image [design to add image here]
- reduce black stroke to 1px
- make location icon Medium Gray ($medium-gray) #909090` from [Style Guide](https://foundation.mozilla.org/en/style-guide/)
- make location text `.h6-heading` from [Style Guide](https://foundation.mozilla.org/en/style-guide/)
- reduce size of share icons and make them black (but make sure they have a large enough hit area on mobile) - hovers state `Dark Blue ($dark-blue)` from [Style Guide](https://foundation.mozilla.org/en/style-guide/)
- remove `See work` link
- remove light gray line

<img width="773" alt="image" src="https://user-images.githubusercontent.com/1068783/51630407-f0ae6c00-1efe-11e9-8ffe-bf822c1e8641.png">

### Full designs https://redpen.io/p/mga45e3eeaaf9bc071 
(please note hove states and edge cases pointed out in redpen).

![red-pen-337c7faa-acfa-4aed-e165-c9578764c2c1](https://user-images.githubusercontent.com/1068783/51629846-78937680-1efd-11e9-9af8-1f32e2fd227d.jpg)

![red-pen-cdfb0cc0-061b-408c-a6f4-a3383bb47654](https://user-images.githubusercontent.com/1068783/51629847-78937680-1efd-11e9-8175-22a2f06560f8.jpg)

cc @alanmoo

**Comment by kristinashu** [comment]
@xmatthewx can you please add any analytic requests you may have?

**Comment by youriwims** [comment]
>     * make location icon and text `Medium Gray ($medium-gray) #909090` from [Style Guide](https://foundation.mozilla.org/en/style-guide/)

On the live site, it appears as though the location is bolder than the redesigned mock. As part of the redesign, do you want the font-weight decreased? Depending on your choice, $medium-gray could have a positive or negative impact on accessibility (see color contrast analysis below).

![screen shot 2019-01-25 at 2 26 57 pm](https://user-images.githubusercontent.com/36484608/51768103-52143d80-20ad-11e9-9f2a-a043d26e562b.png)

**Comment by kristinashu** [comment]
Thank you so much for flagging this! The text should actually be just be `.h6-heading` from the [style guide](https://foundation.mozilla.org/en/style-guide/). But unfortunately it is still #909090 which as you pointed out has accessibility problems. 

I think for now, let's just use it as but then we should assets `.h6-heading` and any other fonts that use that gray as part of a bigger ticket. @sabrinang is doing a bunch of work on this!

Does that that work for you @youriwims!

**Comment by xmatthewx** [comment]
In addition to "remove See work link" in description above, we need to put that link on the person's name and photo.

**Comment by mmmavis** [comment]
@kristinashu does clicking on a filter update the page url? (so it includes the filter as a query param like `/?profile_type=fellow` etc?)

**Comment by kristinashu** [comment]
It doesn't do this right now so it's ok if it still doesn't.

**Comment by mmmavis** [comment]
@kristinashu kk it was working at some point 😂 guess we accidentally broke that functionality

**Comment by youriwims** [comment]
Completed in #2669 , #2685 & #2701.
