### ISSUE TITLE
Write visual regression tests

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2516]
Right now we have four visual regression test, which simply loads up some URLs and take a full page screenshot. Now it's time to start adding more visual regression tests for pages that update more frequently, so that unintentional content structure and/or CSS changes can surface  immediately.

**Comment by mmmavis** [comment]
### Main Site Page (Types)

- [ ] BanneredCampaignPage
- [ ] BlogPage
- [ ] CampaignPage
- [ ] Homepage
- [ ] IndexPage
- [ ] InitiativesPage
- [ ] NewsPage
- [ ] OpportunityPage
- [ ] ParticipatePage
- [ ] ParticipatePage2
- [ ] PeoplePage 
- [ ] PrimaryPage
- [ ] Styleguide
- [ ] YoutubeRegretsPage

### MozFest Page (Types)

- [ ] MozfestHomepage
- [ ] MozfestPrimaryPage

### PNI Page (Types)

- [ ]

**Comment by mmmavis** [comment]
@Pomax I did an audit and marked items that I think are worth adding to our Percy tests. Can you take a look at the above list and see if it makes sense?

**Comment by Pomax** [comment]
I think it's probably worth adding everything you flagged, and fixing the test cases with warning lights.

As for the youtube page, we definitely want a test there, but we don't want to test "the youtube regrets page" so much as make sure that we test with a page that is representative enough of the data that we'd catch CSS errors etc. So we might need to create a load_fake_data step for that page type.

**Comment by mmmavis** [comment]
Done! Look for **FIXED/ADDED** items on this list for Percy tests that have been added.

https://github.com/mozilla/foundation.mozilla.org/issues/2516#issuecomment-557714474
