### ISSUE TITLE
Category descriptions

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2520]
As noted in #2519 we're going to add a description field to categories to set a bit more context when looking at the category. @kristinashu @beccaklam I did a quick HTML mockup, using a simple paragraph tag to embed the description. Does this need any work or is that good as it is?

![image-1](https://user-images.githubusercontent.com/1682681/51760635-d9a38180-2098-11e9-9da3-605383337696.png)

**Comment by kristinashu** [comment]
No! Please use .body-large from the style guide.

Do we have copy for this?

**Comment by alanmoo** [comment]
I figured I'd get a quick response if you didn't like it ;)

It's going to be CMS editable copy.

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/1682681/51761779-fee5bf00-209b-11e9-8fb4-1d93924ca5e9.png">

**Comment by kristinashu** [comment]
Here's the comp https://redpen.io/mb5979d9d3273ab852

In order to not push the main content down too much, I recommend copy should be less than 240 characters.
 
![category copy 2x](https://user-images.githubusercontent.com/1068783/51766035-5bda7880-208e-11e9-9a15-658932e0adfa.jpg)
