### ISSUE TITLE
Add Contact page to Buyers Guide

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2521]
### Add a dedicated contact page:

- [x] Add new tab to About page `Contact us`
- [x] Have the copy: 
`Contact Us`
`For any questions about the guide or to recommend a product for review or offer constructive feedback, please email Jen Caltrider jen@mozillafoundation.org`
`For members of the press with questions about this guide, please email Kevin Zawacki kevin@mozillafoundation.org`
- [x] Remove existing contact info that is currently at the bottom of the two other About pages

### Comps: https://redpen.io/decce024f058fb8e20
![contact 2x](https://user-images.githubusercontent.com/1068783/51765659-3bf68500-208d-11e9-971d-314468de7ff3.jpg)

**Comment by mmmavis** [comment]
@kristinashu what do you want the url to be? `/privacynotincluded/about/contact`? `/privacynotincluded/about/contact-s`?

**Comment by kristinashu** [comment]
Either would work but how about we go with `/privacynotincluded/about/contact`
