### ISSUE TITLE
Fellowships: implement updates to Support page - launch Feb 1

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2530]
Based on #2473

Fellowships team will requesting host org applications so we need to update [Support the Program](https://foundation.mozilla.org/fellowships/support/) content with content found at the bottom of [this doc](https://docs.google.com/document/d/1ke01ZGzdktlDkBb_GVbF-fuA47jLHx8ksDGAC6vfrHw/edit#) (while keeping the existing Fund the Fellows, please note order of content that is in the comp).

Live Feb 1 (hard launch Feb 4)

Assets can be pulled from live site and type, color, button should only use styles from our [style guide](https://foundation.mozilla.org/en/style-guide/).

Comp https://redpen.io/vu7a6a1366f7a38449
![support 2x](https://user-images.githubusercontent.com/1068783/51857838-1d3ffa80-22e8-11e9-9a78-be156b5a333f.jpg)

Note grid:
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/1068783/51857861-2af58000-22e8-11e9-9487-e8d3b7be5541.png">

**Comment by kristinashu** [comment]
cc @mmmavis for any tips or guidance

**Comment by mmmavis** [comment]
Implementation should be fairly straightforward.

- Grid changes can be easily changed by applying different Bootstrap's `col-*` classes.
- @kristinashu What would you like the `Apply to Host a Fellow` and `Supported By` sections to look on mobile?

**Comment by kristinashu** [comment]
Great Q! They will be similar to the live site. Here's a comp: https://redpen.io/nfaed8b7fdf8191ea1

![support copy](https://user-images.githubusercontent.com/1068783/51871316-e5967a00-230a-11e9-8221-fcc65e491f1b.jpg)
