### ISSUE TITLE
Add a cache-clear instruction for PNI products to the `release-steps.sh`

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2532]
If we deploy prod it's possible that the PNI product cache becomes invalid due to migrations to the product model, so it would be a good idea to add a cache-invalidation to our `release-steps.sh` script to make sure that prod doesn't start up a dyno with an update to date codebase, up to date database, but and outdated cache.

**Comment by patjouk** [comment]
I thought we were already clearing the cache on redeploy: https://github.com/mozilla/foundation.mozilla.org/blob/master/release-steps.sh#L16 ?

**Comment by Pomax** [comment]
Hmmm, then this mystery deepens: clearing the cache totally fixed the problem we were seeing, so maybe there's a subtle difference in how `clear_cache` runs vs. how it runs when invoked through the CMS itself?

**Comment by cadecairos** [comment]
If there is a difference, it's a bug in django's cache interface, because the `clear_cache` command just calls `django.core.cache.clear()`, which should do exactly what you think: https://docs.djangoproject.com/en/2.1/topics/cache/#django.core.caches.cache.clear

**Comment by gideonthomas** [comment]
@cadecairos is there anything actionable here? If not, can we close and re-file if we run into this again?

**Comment by cadecairos** [comment]
As it is, I'm not seeing anything actionable. I don't believe cache was the whole issue, I think we're missing another piece of the puzzle.

**Comment by gideonthomas** [comment]
Ok, I think we should monitor and re-evaluate on our next prod push and re-open or re-file this ticket then.
