### ISSUE TITLE
Fellowships: Add analytics to directory and profile component

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#2533]
We will soon build a new directory component that leverages an update pulse profile component. Let's wire it up for GA to measure our success with engaging visitors and extending fellow promotion.

We will want to attach this to:
 - profile
   - tap on photo or name --> pulse profile
   - tap on social icon --> linkedin or twitter
 - directory
   - tap on directory tab/filter --> year by year view

Component | Category | Action | Label
:-- | :-- | :-- | :--
Profile | profiles | profile tap | [page title] - [name of person] - [destination]
Directory | profiles | directory filter | [page title] - [filter value]

Example | GA Event
:-- | :-- 
2015 | label: "profiles", action: "directory filter", label: "fellowship directory - 2015"
Renee twitter | label: "profiles", action: "profile tap", label: "fellowship directory - renee - twitter"
Meghan pulse | label: "profiles", action: "profile tap", label: "fellowship directory - meghan - pulse profile"

**Comment by youriwims** [comment]
Any suggestions for a good place to start on this? Here's a [link](https://developers.google.com/analytics/devguides/collection/analyticsjs/events) I found...let me know if I'm headed in the right direction.

cc: @alanmoo @Pomax

**Comment by xmatthewx** [comment]
Take a look at [reactga](https://github.com/mozilla/foundation.mozilla.org/search?q=reactga&unscoped_q=reactga) in our source. You'll see a few places where similar things have been implemented.

**Comment by youriwims** [comment]
Nice, thanks @xmatthewx !
