### ISSUE TITLE
Improve testing across the site

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2539]
Master ticket for all the testing that we should improve

- [ ] Petition submissions (#1016)
- [ ] Sitemap
- [ ] Spider sitemap and check for 200's
- [x] Visual regression tests (fixed data generation seeds?)

@Pomax @mmmavis @youriwims @patjouk @cadecairos feel free to edit this comment and add to the list if there's something obviously missing, or have a conversation below if you're unsure.

Decisions:
We should determine for each test if it needs to run for PRs or just for staging, to keep us from being unnecessarily blocked on landing PRs.

**Comment by patjouk** [comment]
I want to add a [status check](https://help.github.com/articles/about-required-status-checks/) that if the review app deployment failed, it's considered a failure (blocking merge or not is open to discussion).
We might also want to discuss if we want to run all those tests at every PR or some only on staging, etc: I know that wait time before being able to merge a PR was a problem at some point.

**Comment by alanmoo** [comment]
This is covered by sub-tickets, and we can have convos in those.
