### ISSUE TITLE
Design graphics for EU MisInfo Campaign

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#2545]
Campaign will be coming soon. It's safe to assume we'll need a basic graphic to use on campaign page, email, twitter. 

Campaign info: https://docs.google.com/document/d/1U7olKcSsXZ7Y66mC_gHH_miLfBgUmZf8OuyBiviI33A/edit?ts=5c4f5f6e

More details coming soon...

cc @kristinashu

**Comment by kristinashu** [comment]
Cross-linking with landing page design #2542

**Comment by kristinashu** [comment]
Assigning to @beccaklam to gather more info but @natalieworth might help out with actual graphics.

**Comment by beccaklam** [comment]
Waiting on Jon L to let me know what he's thinking in terms of graphics. Briefed @natalieworth on what's coming though so hopefully she can get started tomorrow.

**Comment by beccaklam** [comment]
Comment from Jon regarding graphics @natalieworth 

> this campaign needs to be on the more professional end given that both facebook and EU commissioners are likely to see it

**Comment by beccaklam** [comment]
@natalieworth From Misinfo Working Group Meetings:
Something that targets 'social platforms', 'misinfo', and 'elections'. 
Since the campaign is about calling social platforms (e.g. Facebook, Twitter, etc) to be accountable for the APIs and how they effect elections, esp in terms of the upcoming EU elections.

**Comment by beccaklam** [comment]
'Disinformation erodes discourse' not 'Disinformation determines elections'

**Comment by xmatthewx** [comment]
I do think an election related icon can help our audience understand what this is about. And can be presented without suggesting too much.

**Comment by natalieworth** [comment]
https://redpen.io/p/cw88c87ca1cbf04bc0

**Comment by beccaklam** [comment]
@natalieworth Like Jon and Brandi said in the email they prefer 1 and 6 from these concepts: https://redpen.io/p/ua6f0325eddafc6b21. I'll let you choose which one you want to push forward and ask them to get sign off from Raegan.

**Comment by xmatthewx** [comment]
Thanks Becca. Unless I missing something in option 1, I think 6 is more accessible for a broad audience.

**Comment by beccaklam** [comment]
Talked to Nat and we are pushing forward with concept 6. Emailed Brandi and co. to ask them to get sign off from Raegan.

**Comment by beccaklam** [comment]
@natalieworth Can you also send the graphic to @KevZawacki when it's ready so he can add it to a blog? And to alexander on slack so he can put it in all our share progress tags.

**Comment by natalieworth** [comment]
Final graphic [assets are in here.](https://drive.google.com/drive/folders/1Lq5uZeU6QXe8X6y7LCA5hd7Wn6mH7L_J)
