### ISSUE TITLE
Footer: Donate and email signup

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2546]
We're going to disable the current donate popup and only use it during our end-of-year donation push. But we would like to try adding it to the footer, like a call-out just above it, so it's permanent and on every page (both foundation site and PNI). 

Because we sometimes have an email signup in this location, let's mockup a few options:
- signup + footer
- donate + footer
- signup + donate + footer

Once this is build, let's open an implementation ticket to remove the pop up and add this.

**Comment by natalieworth** [comment]
Drafts/ options for these are [up on Redpen here](https://redpen.io/p/nr17f804a498f8d46c).

I'm just waiting for my new Sketch license to get updated from Service Now, then can merge changes to Abstract.

cc @kristinashu @sabrinang @beccaklam

**Comment by natalieworth** [comment]
Updated the footer based on feedback in the redpen here:
https://redpen.io/p/nr17f804a498f8d46c

I've also messaged Will with [some of the options](https://redpen.io/p/ore7d534a7ecf1cd2c) and he said he's going to get back to me tomorrow morning.

cc @kristinashu @sabrinang @beccaklam @xmatthewx

**Comment by natalieworth** [comment]
Hey, so for the footer donation ask, I spoke with Will and he liked option 2 (if it's possible) https://redpen.io/av8c7786e5982c5947 but he suggested it would have to be localized for people outside of USA/ Canada (but I think we can use the same UX that is on the mozilla.org site, which allows donors to select their currency on the [actual donate page](https://donate.mozilla.org/en-US/?utm_source=foundation.mozilla.org&utm_medium=referral&utm_content=header&test=ost&test=htl)). 

We could also test 2 options if we have bandwith to do that too?
My preferences right now are:
1. **[Simplified version with text and link](https://redpen.io/ha814366dcb02a7691)**
2. **[More robust button options with dollar amount choice](https://redpen.io/yof8d4ea09a1e66953)** 

I also prefer the email signup in the footer, but would we have dev time to implement that?

cc @kristinashu @xmatthewx @beccaklam @gideonthomas

**Comment by kristinashu** [comment]
Awesome Nat! Yeah let's start with the simplified version. Maybe we could build/test the more robust version during key fundraising times like at the end of the year. 

For the footer update, we need to do something to our current email signup because it has the old gradient and I think adding it to the footer so it's on every pages is a good strategic move since we will be sprucing up our email newsletters too. @gideonthomas do you think we have the bandwidth for this?

@natalieworth can you please mock-up the mobile version for the simpler donate ask and newsletter footer?

**Comment by gideonthomas** [comment]
implementation is probably best left till the end of the month since engineers are busy with other elevated priority projects at the moment.

**Comment by natalieworth** [comment]
For reference, I've narrowed down the 2 options in [redpen here](https://redpen.io/p/nr17f804a498f8d46c) and made updates based on previous feedback. Files have also updated in Abstract.

Option 1
[Option 1 desktop](https://redpen.io/uab58cb13ae2244084)
[Option 1 mobile](https://redpen.io/uqdb9c45cc88eb0c6d)

Option 2 (can implement in future when we do a larger fundraising ask/ test)
[Option 2 desktop](https://redpen.io/bh7cc5a1a1090a31e8) 
[Option 2 mobile](https://redpen.io/su0f0dddb0cc12a088)

cc @kristinashu @gideonthomas I'll show these in crit tomorrow and once option 1 is finalized, I can create a dev ticket for end of month/ when devs get time to update this.

**Comment by natalieworth** [comment]
A note too from @WillatMozFdn to use https://donate.mozilla.org/en-US/?utm_source=foundation.mozilla.org&utm_medium=referral&utm_content=header&test=ost&test=htl

If we have donate ask banner at the bottom, we can track that differently with the campaign tag.

**Comment by natalieworth** [comment]
Have added the error states for [Option 1 of desktop and mobile (of the email sign up in the footer) here](https://redpen.io/p/nr17f804a498f8d46c).

**Comment by kristinashu** [comment]
These are looking awesome! 

@alanmoo please review these comps to flag any concerns and let us know what size of project this will be for devs (aka needs it's own brief or not).

**Comment by WillatMozFdn** [comment]
Two quick comments:  
A) newsletter signup text right next to the box ... best email strategy practices here tell us we need to communicate the value, and set frequency expectations, for someone to let us into their inbox.  Suggested copy: "Want to get smarter about your online life?  Sign up for our Mozilla newsletter! (Delivered 1-2 times per week.)"  (We've done some testing on this in the snippet channel, and a version of that ^^^ was a very clear winner.
B) Noticing that Facebook is still in the footer ... should that be commented out, as we're still on pause with FB?  If we want to be really snarky and make a point, we could replace their logo with a pause symbol, and have it link to https://blog.mozilla.org/blog/2018/03/21/mozilla-presses-pause-facebook-advertising/ . :-)

**Comment by alanmoo** [comment]
Since this is new functionality and my team is stretched so thin right now, this warrants a new brief for prioritization.

**Comment by kristinashu** [comment]
Ok, I'll open one.

**Comment by natalieworth** [comment]
Added the copy updates [to the footer](https://redpen.io/zf88636d2af35edf72) along with the github icon from Friday.

cc @WillatMozFdn @kristinashu @beccaklam @sabrinang

**Comment by kristinashu** [comment]
This is part of our broader newsletter work so @natalieworth, when you get the chance, please open an implementation ticket and close this one!

**Comment by sabrinang** [comment]
@natalieworth Can you check if typography aligns with dark theme styles in https://github.com/MozillaFoundation/Design/issues/319 and if not note what exceptions are made or if we can align etc.

**Comment by natalieworth** [comment]
I moved the most recent versions of this to a [Redpen here.](https://redpen.io/p/bp40e77cb408ac932a) I've updated it to include type and colors from the brand updates that Sabs worked on.

For reference, the old versions of the designs and process are on the previous [Redpen here.](https://redpen.io/p/nr17f804a498f8d46c)

**Comment by natalieworth** [comment]
Final designs for this are in here https://redpen.io/p/bp40e77cb408ac932a

Annotations are also documented in the Sketch file (Redpen was down)

Implementation tickets are #2833 (add donation ask) and #2834 (add email to footer)
