### ISSUE TITLE
Update Sketch library components to reflect design changes from brand work

### ISSUE THREAD

**Issue by natalieworth** [mozilla/foundation.mozilla.org#2548]
This ticket is to document the 2019 changes based on the brand work our team has been doing. For design, we can keep the Sketch updates in this master file—then create new implementation tickets based on changes that have been updated.

Sketch Library updates: 
P1's 
- [x] Change rules from the gradient to black #000000
- [x] Update link colors
- [x] Update greys based on Sabrina's color updates
- [x] Update link text to sentence case
- [x] Update 'document' color swatches with new colors

P2's
- [x] Add new ghost button style
- [x] Update button colors and hover states
- [ ] Implement banner pattern background
- [ ] Update Promotion components

P3's
- [ ] Edit and upload brighter photographs/ review illustrations and images of each page and curate based on updated branding work
- [ ] Evaluate static/ evergreen illustrations and adjust to fit within the growing brand direction
- [ ] Document visual changes (after implementation) on the Foundation brand site
- [ ] Updates to typography (if needed)
- [ ] Design/ illustration template for quick image creation
- [ ] Other templates? (maybe a downloadable template section on the Brand Guide page would be useful? Social templates, patterns, etc.?)

P4's
- [x] Footer orientation and layout
- [ ] Card styles and layout
- [ ] Increase spacing
- [ ] Review UX language on site

cc @kristinashu @sabrinang @beccaklam @xmatthewx   Started this rough ticket to document all upcoming Sketch library changes (and potential future changes if we get time) to work on. Thinking once something is updated in the Sketch file, we can create a ticket for dev implementation? Feel free to make any changes to this ticket or suggest any process that could work better.

**Comment by kristinashu** [comment]
Sorry, closing this but please continue this work over in our design repo https://github.com/MozillaFoundation/Design/issues/338!

**Comment by natalieworth** [comment]
All P1's are done for this, but is it okay to keep ticket open @kristinashu Or I could also make the P2/ smaller individual tickets when I get time later this week. And then close this giant ticket (since they will have different/ longer timeline based on when we get downtime)

**Comment by kristinashu** [comment]
I just wanted to move this from Foundation site repo to our design repo so I close this one but opened the exact same on in our design repo. Is that okay? Sorry if it's confusing, just seemed like since this is related to our sketch file and won't be dev tickets that it should be over there.
