### ISSUE TITLE
Split up the README.md

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2552]
There's a _lot_ of information in the README.md at this point, much of which is not immediately necessary to get up and running, and constitutes enough text to be place in separate .md files, so: let's create a `docs` dir, move most of the README.md into that dir as separate dedicated files, leave the README.md as lean as possible to run you through the process of going from "cloning" to "successfully having a fake-data-loaded instance running on localhost:8000" with a secondary section that links to each file in the `docs` dir.

**Comment by devbihari** [comment]
lemme handle this one for you :fire:

**Comment by Pomax** [comment]
all yours!

**Comment by mmmavis** [comment]
Looks like we forgot to mark this done!
