### ISSUE TITLE
Uses Encryption criteria when unknown should be sad face ☹️

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2578]
If `Uses encryption` is `unknown` then the site should show the red sad face (and red highlight) instead of the gray neutral face.

<img width="1074" alt="screen shot 2019-02-04 at 10 57 41 am" src="https://user-images.githubusercontent.com/1068783/52230314-f3e51880-286b-11e9-941a-0b01e884556a.png">

**Comment by mmmavis** [comment]
So it should display `Can't determine` [red face]?

**Comment by kristinashu** [comment]
Yes, but only for this particular criteria. 

@caltrider

**Comment by caltrider** [comment]
Yes
