### ISSUE TITLE
Buyer's Guide: reduce padding after coral embed

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#2579]
Screencap taken from [staging](https://foundation.mofostaging.net/en/privacynotincluded/products/google-home/):

![screenshot_2019-02-04 privacy not included - google home](https://user-images.githubusercontent.com/2896608/52231341-87b7e400-286e-11e9-87ac-b51f2da41330.png)

**Comment by mmmavis** [comment]
It seems like the height of the embed is being dynamically set. But we can at least remove bottom padding and margin to reduce the extra space after the embed so it can look like:

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/2896608/52231488-f72dd380-286e-11e9-85ce-34532d07f308.png">

**Comment by kristinashu** [comment]
Please always show the "Updates" title.

![red-pen-4490dc46-2483-4f6f-b619-2dcd752949d2](https://user-images.githubusercontent.com/1068783/52232422-5b519700-2871-11e9-9041-136bc024a581.jpg)
