### ISSUE TITLE
Remove fira.css from base templates

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#2582]
It doesn't seem like we are using Fira for the foundation site. True? If so we should stop loading `fira.css`.

Base templates to look at

- `/network-api/networkapi/buyersguide/templates/bg_base.html`
- `/network-api/networkapi/templates/pages/base.html`
- `/network-api/networkapi/wagtailcustomization/templates/wagtailadmin/404.html`

**Comment by Pomax** [comment]
from what I can tell, we're not, no. Good catch. @kristinashu is Fire part of any of our designs?

**Comment by kristinashu** [comment]
No, we should **not** be using Fira anywhere on our site.

**Comment by devbihari** [comment]
may I handle this?

**Comment by Pomax** [comment]
certainly, have at it.
