### ISSUE TITLE
Create ISSUE TEMPLATES for Foundation site

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#2586]
GitHub now supports multiple issue templates on repos. We can simply set them up by going to `Settings > Options > Features section > Issues > Set up templates`

I'm thinking we can start with the following

- bug report
- feature request (anything code or design related and is not a bug)
- discussion
- code improvement

Thoughts?

---

See this "new issue" page on my test repo: https://github.com/mmmavis/test-issue-templates/issues/new/choose (ignore the the actual template content though... I was too lazy to change GitHub's default content)

![image](https://user-images.githubusercontent.com/2896608/52248668-5823ce80-28a4-11e9-97a3-00e70200acc4.png)

**Comment by Pomax** [comment]
We can give this a try, although it'd be worth keeping track of how many external issues even get filed, since it's far more of an internal project than an external product.

**Comment by mmmavis** [comment]
Fields available in an issue template

<img width="630" alt="image" src="https://user-images.githubusercontent.com/2896608/54716618-5ab84b80-4b13-11e9-8b8d-58a45d8e10f0.png">

**Comment by mmmavis** [comment]
Hi @Pomax @youriwims I'm adding two issue templates to this repo and I'd like both of you to chime in as the custom template I wrote is related to front-end implementation.

Try it on my test repo https://github.com/mmmavis/test-issue-templates/issues/new/choose

1. Bug report - this is GitHub's default bug report template. I found it useful so I decided to include it
2. Design to Dev Handoff - this is the one I wrote from scratch. Please let me know if there's anything missing. We can always revise the content. I just wanted to get the checklist in sooner to reduce the back and forth convos between designers and devs.

**Comment by mmmavis** [comment]
@Pomax @youriwims thoughts? 👀

**Comment by youriwims** [comment]
Sorry for the delay—not sure why I didn't see this earlier. @mmmavis love this idea!...especially the design to dev handoff template. Just off the top of my head, the only thing I can think to add to that specific checklist would be 'related issues/comments'. Sometimes it helps to be able to follow those digital breadcrumbs of info to avoid unnecessary pinging 😄 I'll try to think of more today, if any.

**Comment by Pomax** [comment]
This feels like something we should _not_ think about. @mmmavis just add one, turn it on, and then we can iterate on the text but let's just get this in and then move from there.

**Comment by mmmavis** [comment]
Yay merged!
