### ISSUE TITLE
🌡 URL encoding funkiness for buyer's guide

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2587]
I copied a URL from my browser and pasted it into Slack, only to discover it wasn't working:

https://foundation.mofostaging.net/en/privacynotincluded/categories/Valentine%E2%80%99s%20Day/

The correct link is 
https://foundation.mofostaging.net/en/privacynotincluded/categories/Valentine's%20Day/

The trick here is that somewhere along the way, the apostrophe got converted into a "smart apostrophe" (That's probably the wrong word. It's the curly kind.)

Given that this is going to start being shared narrowly tomorrow and broadly in the following few days, what's the best thing we can do to make sure we don't have users stumbling on this and getting 404's? Can we easily sanitize the string that generates the category URL to strip that character altogether (thus making the url `/categories/Valentines%20Day`)? Or should we simply catch it with a redirect in the CMS admin for now?

@patjouk @cadecairos @Pomax @mmmavis

**Comment by Pomax** [comment]
This isn't CMS-managed, so we're currently beholden to whatever Django does. We're creating the actual link over in https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/buyersguide/templates/category_nav_links.html#L5-L6, so one thing we can probably do here is use a sluggifying tag, with an unsluggifier on the views.py side.

**Comment by Pomax** [comment]
Yeah, I just added that.
