### ISSUE TITLE
Update buyer's guide share text

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2589]
"I think Harry Potter Kano Coding Kit is NOT CREEPY. What do you think? Check out the Creep-O-Meter over on @mozilla’s privacynotincluded.org holiday buyer’s guide."

I assume we want to generalize this a bit?

While we're at it, should we do a search of the repo for "holiday" and update/file tickets for any other references?

**Comment by kristinashu** [comment]
Good catch! There's also the share messaging in the nav:

"Shop safe this holiday season using @mozilla’s PrivacyNotIncluded.org buyer’s guide. 70 popular connected products rated to help understand if they are likely to spy on you. Find out which are creepy and which aren’t."

@caltrider any suggestions for what we could say year round?

@alanmoo yeah a search would be great!

**Comment by alanmoo** [comment]
Kudos to @cadecairos for noticing it.

**Comment by caltrider** [comment]
Took @kristinashu 's recommendation and just made small tweaks. Here's the updated text:

1. Copy if a user shares a product after voting:
I think this Harry Potter Kano Coding Kit is NOT CREEPY. What do you think? Check out the Creep-O-Meter over on @mozilla’s PrivacyNotIncluded.org  buyer’s guide.

2. Message if a users shares the landing page:
Be smart. Shop safe using @mozilla’s PrivacyNotIncluded.org buyer’s guide. 89 popular connected products rated to help understand if they are likely to spy on you. Find out which are creepy and which aren’t.

cc: @alanmoo  @cadecairos

**Comment by kristinashu** [comment]
Thanks! Opened https://github.com/mozilla/foundation.mozilla.org/issues/2599
