### ISSUE TITLE
Remove People page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2591]
We have the go ahead to completely remove the [/people](http://foundation.mozilla.org/people) page from our site.

Here's a screen cap for our record.
![screenshot_2019-02-05 people](https://user-images.githubusercontent.com/1068783/52289614-3d446f00-2923-11e9-9c9d-7025025d1fa8.jpg)

cc @alanmoo

**Comment by Pomax** [comment]
page itself removed from the CMS, filing a PR to remove the orphaned static template for that page.

**Comment by Pomax** [comment]
closing as resolved, with https://github.com/mozilla/foundation.mozilla.org/issues/2686 to track the code cleanup aspects.
