### ISSUE TITLE
Remove "Email" from site footer

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#2596]
We've decided to deprecate the icon and link to Email in our footer. We have better utilized and better monitored channels for specific programs. 

![0edb6ddf-c457-401f-aef3-e8ad4aede670](https://user-images.githubusercontent.com/53411/52299818-64fffb00-2954-11e9-941f-47add8983578.jpeg)

**Comment by kristinashu** [comment]
We also have it on our [404 page](https://foundation.mozilla.org/en/404/). Should we remove it there too?

Also maybe search the site for any addition instances.

**Comment by alanmoo** [comment]
It should be one reference used everywhere. But worth doing a search.

**Comment by youriwims** [comment]
Just double checked the files and it's only in the two base files, which are now removed.
