### ISSUE TITLE
Update Buyer's Guide share copy

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2599]
From https://github.com/mozilla/foundation.mozilla.org/issues/2589, need to de-holiday our share messages.

1. Copy if a user shares a product after voting:
I think this Harry Potter Kano Coding Kit is NOT CREEPY. What do you think? Check out the Creep-O-Meter over on @mozilla’s PrivacyNotIncluded.org buyer’s guide.

2. Message if a users shares the landing page:
Be smart. Shop safe using @mozilla’s PrivacyNotIncluded.org buyer’s guide. 89 popular connected products rated to help understand if they are likely to spy on you. Find out which are creepy and which aren’t.

**Comment by mmmavis** [comment]
> 2. Message if a users shares the landing page:
Be smart. Shop safe using @mozilla’s PrivacyNotIncluded.org buyer’s guide. 89 popular connected products rated to help understand if they are likely to spy on you. Find out which are creepy and which aren’t.

@kristinashu which share icons are you referring to?

**Comment by kristinashu** [comment]
Sorry, I mean if a users shares from the top nav.
