### ISSUE TITLE
[18+ Content] Overlapping content on mobile

### ISSUE THREAD

**Issue by youriwims** [mozilla/foundation.mozilla.org#2613]
I'm not sure where else this appears on the live site, but the 18+ symbol in the V-day category is overlapping the 'draft' content on mobile. It would be worth a second look to see where else this issue is present. 

![screen shot 2019-02-06 at 3 00 46 pm](https://user-images.githubusercontent.com/36484608/52370185-449d7280-2a20-11e9-8698-f29186efb9f9.png)

**Comment by mmmavis** [comment]
@youriwims thanks for filing ticket!

`This is a draft` is only visible for people who have logged into CMS. Though this is an issue it only affects a small portion of site visitors. I would see this as a minor bug.

**Comment by kristinashu** [comment]
I think it's ok if this happens since it's only staff who see that draft message but if you notice this anywhere else please let us know!

**Comment by youriwims** [comment]
Oh, okay. Thanks for letting me know!
