### ISSUE TITLE
Update existing colors to standardized colors

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#2636]
### Foundation Palette
By referring to Foundation Palette colors determined in the brand standards colour issue: https://github.com/MozillaFoundation/Design/issues/312#issuecomment-458746752, let's clean up and update current colors on the site.

![image](https://user-images.githubusercontent.com/2492510/52447239-09b14280-2ae5-11e9-9b35-d66a8f01ba45.png)

You can refer to the Foundation Site color audit slide 12: https://goo.gl/jwnocf to see all the different colors that currently exist and to help locate where they appear on the site.

### Grays
On slide 13, I have made recommendations to simplify our grays, to avoid using opacity and to replace gradient with black.
![image](https://user-images.githubusercontent.com/2492510/52447143-c7880100-2ae4-11e9-9f22-451b510ee3ef.png)

### Colors
 On slide 13, I have made recommendations on hover shades and to simplify to a blue. 
![image](https://user-images.githubusercontent.com/2492510/52447353-58f77300-2ae5-11e9-98b0-35ec777c9931.png)

**Note:** For text links, we will want to use the dark blue (for optimal color contrast and accessibility) and the hover state will be an underline not a darker shade but this will be part of the links/button standardization update.
__________________________
If you have any feedback on variable names as well, let me know. 
Additional brand color documentation on: https://foundation.mozilla.org/en/docs/brand/design/color/

**Comment by Pomax** [comment]
I've also filed https://github.com/mozilla/foundation.mozilla.org/issues/2663 to make sure we update our linter so that we can't land code with "raw CSS colors" in the future. Right now any SCSS we write that uses css colors rather than sass variables doesn't get flagged as bad... and they should be =D

**Comment by kristinashu** [comment]
@sabrinang do you know what is left for Mavis to do to close this ticket?

**Comment by sabrinang** [comment]
@kristinashu Yes, when we updated the Foundation site palette it affected colours in Privacy Not Included so to finish color standardizing it is in issue #2665

**Comment by kristinashu** [comment]
Ok awesome!
