### ISSUE TITLE
Scorecard for Misinfo Campaign

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#2643]
The Campaigns team is asking for the creation of a 'Scorecard' they can direct tech companies, EU/UK commissioners, partners and our email list to. The purpose is to put pressure on tech companies to improve their platform APIs and for partners to see where are the areas they can campaign on.

**Examples of Scorecards:** [here](https://www.macrumors.com/2015/05/12/apple-tops-2015-greenpeace-clean-energy-index/), [here](https://www.forestandbird.org.nz/resources/five-out-seven-political-parties-want-end-irrigation-subsidies) and [here (page four)](https://www.greenpeace.org.uk/wp-content/uploads/2017/05/9fb0ba4a-palm-oil-scorecard-final.pdf)

**More info/context about the Scorecard:** [here](https://docs.google.com/document/d/1MrZ8CLF0BrO_7PoRsjw0BryAtMNrnW7FipGPKI-uXEY/edit)

**Larger context about the Misinfo campaign:** [here](https://docs.google.com/document/d/1RS6sD4UB-8NEtsoiL11hesp8y9dzkBfDZ5a_GldVeyw/edit)

This will also be a good opportunity for the engagement team to build out a table cms component for the foundation site.

**Comment by beccaklam** [comment]
Emailed Rebecca Ricks to get dummy/rough content to begin this work.

**Comment by kristinashu** [comment]
Here's another user case for a table https://foundation.mozilla.org/en/initiatives/mozfestsponsorship/

<img width="746" alt="image" src="https://user-images.githubusercontent.com/1068783/52504942-d501c180-2b9e-11e9-8cfc-c0ec60d2d4df.png">

And also a older request ticket for this component here https://github.com/mozilla/foundation.mozilla.org/issues/2339

cc @sabrinang because she was looking at branding for gdoc tables

**Comment by beccaklam** [comment]
Becca Ricks said that content should be ready by this Friday, Feb 15 (pending approval from various domain experts).

**Comment by beccaklam** [comment]
Another table example for the Scorecard:
![image](https://user-images.githubusercontent.com/20977376/52746311-38309100-2faf-11e9-9fcd-557b99a9bf49.png)

**Comment by kristinashu** [comment]
@beccaklam you can see @alanmoo [PR here](https://foundation-mofostaging-pr-2662.herokuapp.com/en/about/of-station-year/title/). Login to the CMS for this PR [here](https://foundation-mofostaging-pr-2662.herokuapp.com/cms) using the username and password in the [#mofo-review-apps](https://mozilla.slack.com/archives/GBKP2SG94/p1550168052000500) channel.

**Comment by beccaklam** [comment]
We are currently on track to use airtable pro for this and will embed onto the campaign page.

**Comment by beccaklam** [comment]
We may want short links for the methodology or take action urls if we want them to look less terrible in the air table grid.

**Comment by beccaklam** [comment]
So where we are now: We tried out airtable, but the Campaigns team wants something more impactful. Kristina did a mockup using the Figuregrid component that we're hoping will do the trick:
![misinfo 2 2x](https://user-images.githubusercontent.com/20977376/53426253-a49a8f80-39b4-11e9-8b5c-a27af50b648f.jpg)
 
Bringing in @natalieworth  to make some awesome graphics to further elevate the Scorecard.

**Comment by beccaklam** [comment]
@natalieworth One thing to note, like I mentioned in our call yesterday, is to think of ways to make the standards (i.e. Make Ads Transparent) more prominent. Or just someway the user can more quickly visually gauge what these Platforms are being graded upon.

**Comment by beccaklam** [comment]
After a week of iterating we have our final design! We are waiting on final content to export all the necessary assets. The due date for this is March 11. For a complete overview of the design: https://redpen.io/p/tafd9bccd2cd92a146
![misinfo-desktop 2x](https://user-images.githubusercontent.com/20977376/53741682-e7e97800-3e64-11e9-94c5-c3a4210887a6.jpg)

**Comment by beccaklam** [comment]
**Things left to do:**

- [ ] Export logos for overall Scores

- [ ] Export all scores (overall and standards)

**Comment by beccaklam** [comment]
Asking for feedback on what combination works better for logo and icon integration:
![scorecard-logo-and-icons 2x](https://user-images.githubusercontent.com/20977376/53764590-bb048780-3e9b-11e9-96ce-f2326388ed15.jpg)

**Comment by beccaklam** [comment]
This work is paused indefinitely due to reasons relating to the Campaigns team not being able to move forward with this work.
