### ISSUE TITLE
Design "petition is closed" view

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2644]
We've got some old petitions that are still using Google forms. Rather than moving them over to Salesforce, let's just "close" them. That being said, we need a design to show in place of the petition form on pages like https://foundation.mozilla.org/en/campaigns/facebook/

When this is done, please file a ticket for developer implementation and tag me.

**Comment by kristinashu** [comment]
A few benchmarks: 

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/1068783/54164245-2a88f280-4419-11e9-8267-3ddc1790ad75.png">

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/1068783/54164152-d716a480-4418-11e9-9b26-d314c70fd7f3.png">

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/1068783/54164196-f281af80-4418-11e9-834a-c0c9a4855596.png">

And quick comps https://redpen.io/p/gz26fa3bd26ec0cb81

MVP
![advocacy copy 5@2x](https://user-images.githubusercontent.com/1068783/54164930-d6cbd880-441b-11e9-8f16-361ace2465a6.jpg)

Closed 
![advocacy copy 4@2x](https://user-images.githubusercontent.com/1068783/54164929-d6cbd880-441b-11e9-8a8f-b036ccf4b97f.jpg)

Victory 
![advocacy copy 3@2x](https://user-images.githubusercontent.com/1068783/54164928-d6cbd880-441b-11e9-99d3-78c79c6a7006.jpg)

**Comment by alanmoo** [comment]
Let's try and keep it to a single closed state/message for now, to make l10n and implementation as simple as possible. Numbers are maybe reasonable though? If we as an org want to share those for every campaign...

**Comment by xmatthewx** [comment]
A count of signatures would be great if feasible. 

Let's include a link to _something_. Even if it's generic. Maybe...
 - Text: "View our latest campaigns" 
 - Link: `/advocacy`.

**Comment by kristinashu** [comment]
So like this? Do we need approval from someone on campaigns team? 

![campaign - closed copy@2x](https://user-images.githubusercontent.com/1068783/54237942-69c84980-44d4-11e9-8373-7c7bd77be429.jpg)

**Comment by alanmoo** [comment]
I'm coordinating with Jon. In doing that, I discovered that it appears all our old campaigns _were_ migrated. I still think there's value in this though.

**Comment by kristinashu** [comment]
Ok, I've assigned to you to open an implementation ticket when ready!
