### ISSUE TITLE
Reorganize our dev documentation

### ISSUE THREAD

**Issue by patjouk** [mozilla/foundation.mozilla.org#2659]
related #2658 and #2552

The README got gigantic and was split into multiple files. It's a great start but the fact that some parts should be duplicated in the dev or deploy file is a sign that our docs need a more serious reorganization.
I've started a workflow file in [this PR](#2658), but it could use another section dedicated to "What happens when you open a PR", which would include info on CI and review apps. Deployment could be changed to infrastructure, etc.

**Comment by gideonthomas** [comment]
Closing in favor of #2552
