### ISSUE TITLE
Make header image on primary pages cms editable

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2661]
We would like to be able to update the background image on individual primary pages. 

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/1068783/52802652-3ad5c980-3035-11e9-94c6-cff63450a5bb.png">

**Comment by mmmavis** [comment]
I think we can keep the existing banner (like the one in the screecap above) as fallback image and add an optional banner image field to CMS so people can override default with the image they want.

**Comment by alanmoo** [comment]
Suggestion: for the template implementation, use a `<style>` tag to override the CSS applied to `#hero::before`'s background.

**Comment by kristinashu** [comment]
Not sure if this is helpful but it is currently possible to update the hero on [/initiatives ](https://foundation.mozilla.org/en/initiatives/) in the cms.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/1068783/53269339-7576dc00-369d-11e9-97ac-e8755e2020ed.png">

**Comment by alanmoo** [comment]
Only kind of. They use different markup to achieve the same effect. I'd like to avoid rewriting markup just for this ticket because that could be a rabbit hole.
