### ISSUE TITLE
Update PNI override colors to standardized colors

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#2665]
Related to Foundation Palette updates in https://github.com/mozilla/foundation.mozilla.org/issues/2636, we should also clean up the Privacy Not Included site as the colours are affected. 

**Foundation Palette**
<img width="594" alt="image" src="https://user-images.githubusercontent.com/2492510/52447239-09b14280-2ae5-11e9-9b35-d66a8f01ba45.png">

**PNI Palette**
<img width="594" alt="image" src="https://user-images.githubusercontent.com/2492510/52816267-c2333500-3055-11e9-95de-ae2330e4b1f1.png">

You can refer to the Privacy Not Included Site color audit slide 16: https://goo.gl/jwnocf to see all the different colors that currently exist and to help locate where they appear on the site.

### Grays & Colors
I have made recommendations to simplify our grays and to avoid using opacity.
<img width="955" alt="image" src="https://user-images.githubusercontent.com/2492510/52816504-41c10400-3056-11e9-92e3-726b0402cc7b.png">

### Coral used on PNI
If we can align the colors in the comments section here are the recommendations:
<img width="629" alt="image" src="https://user-images.githubusercontent.com/2492510/52816525-4d142f80-3056-11e9-854a-c638daa33245.png">

**Comment by mmmavis** [comment]
@sabrinang should `$pni-gradient` (`#0000ff` to `#ff506f`) be using the standardized `$pni-blue` (`#1808f2`) and `$pni-pink` (`#e4487d`) instead?

**Comment by mmmavis** [comment]
@sabrinang should `$pni-gradient` (`#0000ff` to `#ff506f`) be using the standardized `$pni-blue` (`#1808f2`) and `$pni-pink` (`#e4487d`) instead?

Note that I couldn't find where this gradient is being used on PNI production site.

**Comment by sabrinang** [comment]
Thanks for pointing that out! yes we should align the gradient with `$pni-blue` and `$pni-pink`

The gradient bar is an svg: 
https://foundation.mozilla.org/_images/buyers-guide/gradient-bar.svg
<img width="376" alt="image" src="https://user-images.githubusercontent.com/2492510/56157556-ad4f2100-5f74-11e9-9591-bdb0c035d594.png">
<img width="409" alt="image" src="https://user-images.githubusercontent.com/2492510/56157574-b3450200-5f74-11e9-9385-ef194e7ee512.png">
<img width="370" alt="image" src="https://user-images.githubusercontent.com/2492510/56157604-bfc95a80-5f74-11e9-8f34-4a90e647e522.png">
