### ISSUE TITLE
Add tests for all pages that use things that tap into people.scss

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2667]
Removing people.jsx revealed that people.scss is actually being used for roles other than just the people page. We should make sure to add visual regression tests for all pages that use styling from that file, but aren't the people page.

**Comment by mmmavis** [comment]
`people.scss` was [removed](https://github.com/mozilla/foundation.mozilla.org/pull/2870/files#diff-71b38340a1c9110a9c9fc5f8935d9ad9) in March. So yay no action needed to this ticket!
