### ISSUE TITLE
Design a language switcher

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#2681]
Filing this bug to keep this under our radar since we’re launching campaigns where numbers indicate that English is not the main driver.

We control where we send people from our list, but there are a number of cases out of our control and a language switcher would help people get in front of a page that speaks their language. And in the end, improved engagement and better accessibility.

When third parties promote our content, they are failing to link to the language that would make the most sense for their audience. That’s because they have no way of finding that link or even just knowing that the page is available in other languages. Here’s a couple example:

Member of French Parliament tweeting the English page: https://twitter.com/PaulaForteza/status/1097480557699760128

Or worse, the Turkish account of Reporters Without Borders tweeting the French page because they likely found the link on the French RWB account: https://twitter.com/RSF_tr/status/1095197722079039488

Even with partners that got communicated the language agnostic link, most of them would still click the link then share the /en/ English page rather than sharing the original link.

A great (and obvious) implementation example is the one in the footer of https://www.mozilla.org
We also have one on https://www.changecopyright.org but the actual implementation is quite hacky.

**Comment by sabrinang** [comment]
Iterated a few options: https://redpen.io/p/vu6e9b5fe5236d10f8
- header option (full-wdith dropdown or landing variations)
- footer option (list drop down - field styling, icon only or default select element) the heading could also link to the landing option similar to how https://www.mozilla.org/en-US/ links to https://www.mozilla.org/locales/

Mozilla examples for reference or to be aware of: 
<img width="500" alt="image" src="https://user-images.githubusercontent.com/2492510/63982488-90c10a80-ca77-11e9-8c61-e6d8bd3b974e.png">

@TheoChevalier @alanmoo @kristinashu Would like to hear your thoughts and feedback so far andyou can leave your feedback here or on [redpen](https://redpen.io/p/vu6e9b5fe5236d10f8)

**Comment by kristinashu** [comment]
Looks good @sabrinang! I like all the footer versions. I don't think we can do a nav version because it competes too much with our main CTAs and also feels too prominent considering most of our pages aren't translated.

**Comment by alanmoo** [comment]
I mentioned in the Red Pen, but I know comments can get lost there. I feel pretty strongly that we need _some sort_ of icon in the footer version to demonstrate that it's a language switcher. When you land on a page in a language you don't speak, it can be very hard to find the word "language" in that language.

**Comment by sabrinang** [comment]
Thanks for the feedback @alanmoo @kristinashu I refined the footer field option in the redpen: https://redpen.io/p/vu6e9b5fe5236d10f8
- aligned field height to match form styles
- use 2 columns to accommodate lengthy language labels
- included language speech bubble icon, world icon or no icon options
- drop down style and mouseover style
- mobile version

I avoided using flag icons as they represent locations like country/nations than languages themselves - reference http://www.flagsarenotlanguages.com/blog/why-flags-do-not-represent-language/

**Comment by kristinashu** [comment]
Awesome, I like the one with the globe icon! 

Maybe just check-in with @mmmavis since I think she might be implementing this. I'm not sure how much work it will be to customize the drop down?

**Comment by mmmavis** [comment]
If we wanna stick with standard HTML `<select>` (dropdown) without any hacks/JavaScript then there are restrictions on the things we are able to style using CSS.

@youriwims , I know you have experience styling a standard dropdown on Pulse. Can you correct me if I say anything wrong or if you have anything to add?

## Default/Closed State

<img width="397" alt="image" src="https://user-images.githubusercontent.com/2896608/64287593-f64c4580-cf14-11e9-997d-73e39b470d02.png">

We should be able to make it appear as expected.

## Open State

<img width="392" alt="image" src="https://user-images.githubusercontent.com/2896608/64287936-c6517200-cf15-11e9-9bc7-cd7ac4565d5a.png">

### Things all desktop browsers don't respect

- change the arrow icon depending on dropdown list's open state
- add divider/line in between different options
- customize background color of the selected option
- remove or customize the default check ✔️ mark from the selected option. e.g., 
<img width="231" alt="image" src="https://user-images.githubusercontent.com/2896608/64289874-de2af500-cf19-11e9-85da-065b17c87bb5.png">


### Things desktop WebKit browsers don't respect (Chrome, Safari)

- font color, background color or font weight for the options

### Mobile browsers

We can't customize the dropdown list at all.

**Comment by kristinashu** [comment]
Let's see what Youri says but most likely we will have to do something like what Pulse has (custom closed state but default open state).

Once that is decided, Sabrina, please update the implementation ticket https://github.com/mozilla/foundation.mozilla.org/issues/3580.

**Comment by youriwims** [comment]
Yep, you've covered everything @mmmavis and are absolutely correct. Like @kristinashu said, something similar to the Pulse dropdown is the extent of what can be done with `<select>`.

**Comment by sabrinang** [comment]
Keeping default/closed state design and updated using default style similar to what could be done in pulse dropdown. Got R+ from design crit and final updates on redpen here: https://redpen.io/p/vu6e9b5fe5236d10f8

Sketch style guide footer has been updated in abstract. White globe icon found in sketch style guide or download svg here: https://drive.google.com/open?id=1VwaGtRuGmhKPiRFiiPJ5Sy8FvqAFjg0L&authuser=sabrina@mozillafoundation.org&usp=drive_fs

**Comment by sabrinang** [comment]
Note: I made spacing updates to the mobile/desktop symbols in style guide.sketch file to reflect design review adjustments in https://github.com/mozilla/foundation.mozilla.org/pull/3613#pullrequestreview-286990027

<img width="919" alt="Screen Shot 2019-09-11 at 11 27 12 AM" src="https://user-images.githubusercontent.com/2492510/64724848-1be2cd00-d488-11e9-941e-b3b88931719e.png">
(tablet symbol isn't reflective of what is live, so I did not update the language picker there as the whole symbol needs an update)
