### ISSUE TITLE
Testing python 3.7 on windows

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2682]
- [x] remove old python version(s)
- [x] install python 3.7.2
- [x] install pip 19
- [x] install invoke
- [x] install pipenv
- [x] fresh clone of the repo
- [x] remove any pre-existing venvs
- [x] updated Pipfile to read `python_version = "3.7"`
- [x] `inv setup` runs to completion
- [x] `pipenv run python network-api\manage.py createsuperuser` works.
- [x] `npm start` runs to completion

**Comment by Pomax** [comment]
`inv setup` does not seem to report what it's doing while install python dependencies, so we probably need to change the inv reporting during that step because right now it takes 5+ minutes to install everything, and during that time the console shows nothing happening.

**Comment by Pomax** [comment]
@cadecairos @patjouk it looks like there's no pathing induced errors anymore on a clean python 3.7 install \o/

**Comment by patjouk** [comment]
🎉 I will check if all parts of our infrastructure support 3.7 and move the project to this version if it's the case.

**Comment by Pomax** [comment]
Closing - 3.7 will probably happen at the same time as the django/wagtail uplift?
