### ISSUE TITLE
remove people.jsx, refactor people.scss

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2686]
We're no longer using the people page, but some of its SCSS is used by other pages/components, so we should pull those two things apart, remove the people page code itself, and make sure we relocate the still-used styling.

**Comment by HSR05** [comment]
Is this still open?

**Comment by Pomax** [comment]
It is, but this one is not actual as easy as the original comment makes it sound, so we'll be tackling this one internally.

**Comment by mmmavis** [comment]
Just a note that `/source/sass/views/fellowships/people.scss` (which its code is identical to `/source/js/components/people/people.scss`) is not being imported and used. We should decide which file we wanna keep and remove the unused one.

/cc @youriwims

**Comment by youriwims** [comment]
I'm not sure if `/source/js/components/people/people.scss` is still being used...would have to look more into that. But, we can remove `/source/js/components/people/people.scss`. I think I was going to update that one, but then found `/source/sass/wagtail/profiles.scss` and settled on updating that file and forgot to remove the other. Feel free to create a ticket for it and assign me 😄

**Comment by youriwims** [comment]
_Update_: Looks like the entire `source/js/components/people` directory which includes`people.jsx`, `people.scss`, and `person.jsx` can safely be removed. Styles in `people.scss` are no longer in use since the new Fellowship Directory was built ( Ref #2511, #2685, #2474   ). Lastly, the `Person` module will be obsolete once all of the fellowship related files and `people.jsx` are removed.

**Comment by mmmavis** [comment]
Awesome. Don't forget to remove `people_page.html` and other related bits! 👍

**Comment by youriwims** [comment]
Thanks!

**Comment by youriwims** [comment]
[Temporarily blocked](https://github.com/mozilla/foundation.mozilla.org/pull/2870#issuecomment-475403284)
