### ISSUE TITLE
Pulse images unable to be rendered at different dimensions

### ISSUE THREAD

**Issue by youriwims** [mozilla/foundation.mozilla.org#2687]
The Pulse API isn't currently capable of serving optimized, uploaded images to specific aspect ratios/dimensions.

Use-case: Currently in #2511 , I am trying to render Fellow images from Pulse at a 1:1 aspect ratio, but the Wagtail image tag doesn't allow me to do that solely with the URL that is being served. In order to use the Pulse images with consistent aspect ratio results and an `<img>`, I would need pre-cropped images available via URL.

@kristinashu , currently I can't ensure that the remaining uploaded images stated in #2426 will be cropped at the specified aspect ratio. For now, whichever images that are uploaded will appear at their original dimensions. If possible, uploaded images should already be cropped as per the design specs  until this gets sorted out.

cc: @Pomax @patjouk

**Comment by alanmoo** [comment]
@gideonthomas Do you have any thoughts on this?

**Comment by gideonthomas** [comment]
I think it's worth doing what @youriwims suggests. I can try to tackle this on next week. Don't have any different thoughts than [what's mentioned here](https://github.com/MozillaFoundation/mofo-devops/issues/636#issue-383491873). I think we def should use Celery or some kind of task processor. Personally I would lean towards using https://github.com/jazzband/sorl-thumbnail coz it seems like the easiest lift (no difficult model changes)

**Comment by cadecairos** [comment]
Closing this issue due to its age, if this is work that we still want to do, please refile this with up to date information so that it can be put in the correct milestone with up to date estimates.
