### ISSUE TITLE
Updates to Image Text2 component

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2693]
This is probably blocked by - Remove deprecated components #1902 and Updates Figuregrid2 component #2696

Related to - New Image Text Mini component #2694

Based on design in https://github.com/mozilla/foundation.mozilla.org/issues/2282, component comps https://redpen.io/tuab5adf37d05d0414 and Fellowship comps https://redpen.io/p/mga45e3eeaaf9bc071.

### Styling and CMS form fields
- [x] Keep image at 1:1 ratio
- [x] Add styles to `Test` so they match our style guide (H2-H6, normal body + large body, bold, italic, list, url link)
- [x] Add optional top divider and separate optional bottom divider (1px black)
- [x] Vertically center the image with the content
- [x] Mobile: halve the size of the image and left align it
- [x] Update component name from `Image Text2 ` to `Image Text` [blocked by deprecating old component #2739] - ok to hold off on name change
- [x] Remove `Small` checkbox (this is now `Image text mini`)

@alanmoo or @Pomax can you please either add to this ticket or open a separate one that includes additional steps for determining where this component is used and how we can make sure we don't break anything while doing these updates?

### Component comp
![image text 2x](https://user-images.githubusercontent.com/1068783/53360531-98e29680-38ea-11e9-8b15-66e173f5505c.jpg)

**Comment by Pomax** [comment]
It looks like we're still using ImageTextBlock [on nine pages](https://foundation.mozilla.org/cms/inventory/?form-TOTAL_FORMS=3&form-INITIAL_FORMS=0&form-MIN_NUM_FORMS=0&form-MAX_NUM_FORMS=3&form-0-has=includes&form-0-block=networkapi.wagtailpages.customblocks.ImageTextBlock&form-1-has=includes&form-1-block=&form-2-has=includes&form-2-block=) so we'll have to switch those over to ImageTextBlock2 first before we can remove the original ImageTextBlock (which is a necessary step before we can start renaming things relating to ImageBlock2. Streamfield migrations are unfortunately even more complex than standard django model renames)

**Comment by kristinashu** [comment]
Amazing that you can tell which pages are using it! I will update those tomorrow.

**Comment by kristinashu** [comment]
Ok that was painfully tedious but they're all gone now!

**Comment by Pomax** [comment]
Super! On a CMS permissions note, can you see the "settings -> block inventory" option? I don't recall it being an explicit permission in the user group policies, but I also don't think we ever checked that everyone with CMS access can see it, even though it'd be super useful if everyone could.

**Comment by kristinashu** [comment]
Yes, I see it!

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/1068783/53257415-e6f36200-367e-11e9-9d2c-aefa64320bfa.png">

**Comment by Pomax** [comment]
ah, perfect. Thanks for checking!

**Comment by kristinashu** [comment]
I guess, feel free to do the renaming later if deleted the deprecated component is a blocker.

**Comment by alanmoo** [comment]
Removing the "small" checkbox is going to impact at least one page on the existing site: https://foundation.mozilla.org/en/initiatives/responsible-cs/challenge/.

Has an audit been done to understand the effects of this (and the URL removal)?

I wonder if it might be better to rebuild this as a separate component called Image Text and deprecate ImageText2

**Comment by kristinashu** [comment]
ImageText2 (without the checkbox) has been used extensively on the site so replacing it would be a nightmare. 

I can certainly do an audit of where the "small" checkbox has been used and then replace those with `Image Text Mini` when we have it (that's why I put mini as a higher priority to this one).

**Comment by youriwims** [comment]
@kristinashu, any updates on the 'small' checkbox audit?

**Comment by kristinashu** [comment]
From an [inventory search](https://foundation.mozilla.org/cms/inventory/?form-TOTAL_FORMS=3&form-INITIAL_FORMS=0&form-MIN_NUM_FORMS=0&form-MAX_NUM_FORMS=3&form-0-has=includes&form-0-block=networkapi.wagtailpages.customblocks.ImageTextBlock2&form-1-has=includes&form-2-has=includes&p=2) and looking at the page, here are the instances:

- [ ] https://foundation.mozilla.org/en/fellowships/
- [ ] https://foundation.mozilla.org/en/fellowships/apply/ (2 places)
- [ ] https://foundation.mozilla.org/en/initiatives/responsible-cs/
- [ ] https://foundation.mozilla.org/en/initiatives/responsible-cs/faq/
- [ ] https://foundation.mozilla.org/en/initiatives/responsible-cs/industry-support/
- [ ] https://foundation.mozilla.org/en/initiatives/responsible-cs/judges/
- [ ] https://foundation.mozilla.org/en/initiatives/responsible-cs/challenge/ (multiple in a row)
- [ ] https://foundation.mozilla.org/en/opportunity/mozilla-information-trust-initiative/
- [ ] https://foundation.mozilla.org/en/docs/how-do-i-wagtail/sample-page/
- [ ] https://foundation.mozilla.org/en/docs/brand/design/Typography/
- [ ] https://foundation.mozilla.org/en/docs/brand/design/color/

As soon as https://github.com/mozilla/foundation.mozilla.org/pull/2722 is pushed live I will go in an update these with the new component!

**Comment by youriwims** [comment]
> Add styles to `Test` so they match our style guide (H2-H6, normal body + large body, bold, italic, **list**, url link)

@kristinashu, what type of list(i.e. ordered/bulleted or unordered/no-bullets) did you want here?

**Comment by kristinashu** [comment]
All those text styles should be the same as the `Paragraph` component.

**Comment by Pomax** [comment]
marking as blocked until https://github.com/mozilla/foundation.mozilla.org/pull/2763 is on production (not just staging)

**Comment by Pomax** [comment]
#2763 got deployed to production, marking as unblocked again.

**Comment by kristinashu** [comment]
w00t Youri! Looks like this is all done and working great! 

The final step is represented in - [Wagtail Component] Remove Image Text 2 Component #2793
