### ISSUE TITLE
New Image Text Mini component

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2694]
Related to - Updates to Image Text2 component #2693

Based on design in #2282, component comps https://redpen.io/pk88a3dce26ec3fe58 and Fellowship comps https://redpen.io/p/mga45e3eeaaf9bc071.

### Styling and CMS form fields
- [x] Image 1:1 ratio
- [x] Name component `Image Text Mini`
- [x] `Test` to have restricted paragraph styles (normal body, bold, italic, link)
- [x] Automatically add top divider and  bottom divider (1px black)
- [x] Vertically center the image with the content

-  [ ] Note: this is similar to our IH snippet which is automatically added to the bottom of all opportunity/campaign pages and will also need to update it's style to align with this one.

### Component comp
![image text mini 2x](https://user-images.githubusercontent.com/1068783/53360461-705a9c80-38ea-11e9-94f3-4980eb2f6a13.jpg)

cc @alanmoo @Pomax

**Comment by youriwims** [comment]
@kristinashu, as soon as I have the build and design approved for the image text mini component, I'll open a separate pr and make the updates to the IH snippet.
