### ISSUE TITLE
Updates Figuregrid2 component

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2696]
Related to - Updates to Image Text2 component #2693 & New Image Text Mini component #2694

Based on design in #2282, component comps https://redpen.io/kg4b8b684f624bf84c and Fellowship comps https://redpen.io/p/mga45e3eeaaf9bc071.

### Styling and CMS form fields
- [x] Update mobile to show two-up instead of just one-up
- [x] Add `Square image` checkbox 
  - Selected by default - crops images as they are on prod 1:1 ratio
  - If unselected - show image at uploaded ratio
- [x] Rename from `Figuregrid2` to `Image Grid`

### Component comp
![image text grid 2x](https://user-images.githubusercontent.com/1068783/53122508-9d363a80-350b-11e9-93aa-8f8eb800d046.jpg)

cc @alanmoo @Pomax

**Comment by alanmoo** [comment]
Since these images are being stored as part of Wagtail, the square image functionality should leverage the "focal area" feature that Wagtail offers. See [this page](http://docs.wagtail.io/en/v2.0/topics/images.html?highlight=focal) for details.

**Comment by HSR05** [comment]
Is this issue open? @kristinashu Can you guide me? I'd like to work on this.

**Comment by alanmoo** [comment]
Thanks for your interest, @HSR05. We're on a bit of a deadline with this, so someone on staff is going to be taking this on today or tomorrow. Can I recommend one of our issues tagged ["good first issue"](https://github.com/mozilla/foundation.mozilla.org/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)?

**Comment by kristinashu** [comment]
Ok, all the instances of FigureGrid2 have been updated to Image Grid.
