### ISSUE TITLE
Initiatives page content & features

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2699]
At the bottom of our [/initiatives](http://foundation.mozilla.org/initiatives) page we have a section where we could feature a lot more of our work. 
@anilkanji @Sydette should we?

Here's some possible work we could feature:
- https://foundation.mozilla.org/en/initiatives/responsible-cs/
- https://foundation.mozilla.org/en/initiatives/trustable-technology-mark/
- https://foundation.mozilla.org/en/opportunity/leadership-training/
- https://foundation.mozilla.org/en/opportunity/artists-open-web/
- https://foundation.mozilla.org/en/opportunity/mozilla-information-trust-initiative/
- https://foundation.mozilla.org/en/initiatives/stronger-nyc-communities/

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/1068783/53131119-c57c6400-3520-11e9-9834-2fa6f0dca2f8.png">

@alanmoo it would be amazing to be able to see a list of all Initiative and Opportunity pages and then we could just check off which ones we want to see at the bottom of the /initiatives page (and the image and copy is pulled from OG content). Something like this could also be used on /participate and also /advocacy could pull from our Campaign pages.

**Comment by alanmoo** [comment]
I agree; This concept of grabbing the 'promote' tab content for elsewhere in the site is functionality I'd love to add- it would be useful for index pages of campaigns and for situations like this. If it's something enough of us agree on, perhaps we should add it as a brief and prioritize it.

**Comment by anilkanji** [comment]
@kristinashu I'm struggling with this one a bit. I think we need to be clear and concise in sharing what we work on, we don't want to overwhelm the visitor or give them a fragmented picture of what we do. After coming to the page the visitor should feel like they have a handle on what we do. That said, I think there's probably a way to accomplish both the a) clear positioning of our core programs and b) depicting the diversity of what we do  - in a way that doesn't overwhelm. Let's talk!

**Comment by cadecairos** [comment]
@kristinashu is this work still relevant or should we close it?

**Comment by kristinashu** [comment]
Thank for the nudge Cade! I'll close it in-lieu of our new IA work.
