### ISSUE TITLE
Consider creating Percy tests for the fellowship pages

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2703]
Given our intent to migrate the fellowship pages, it might be worth making tests for the current pages, so that work we do in the porting comes with tests that ensure we don't accidentally remove styling that's still supposed to apply to the old pages during the porting effort. 

Of course, adding tests would cut into our allotted screenshots per month, but that might be worth it. Or not! Let's figure out if we want to do this, or no.

/cc @alanmoo @kristinashu

**Comment by kristinashu** [comment]
Thanks for opening this Pomax, I didn't realize it would take extra work to do. Since it's only a few pages and will be short lived it probably isn't worth the effort.

**Comment by alanmoo** [comment]
+1, especially since this isn't meant to be a 1:1 conversion.
