### ISSUE TITLE
remove ENABLE_PROFILE_DIRECTORY_BLOCK feature flag

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2706]
Once the profile directory component has landed, we'll need to remove the dependency on, and need for, the `ENABLE_PROFILE_DIRECTORY_BLOCK` flag

**Comment by youriwims** [comment]
@Pomax, this was updated already right?

**Comment by Pomax** [comment]
what do you mean with updated? The code still depends on the ENABLE_PROFILE_DIRECTORY_BLOCK flag.

**Comment by youriwims** [comment]
Okay, I'll put this on my to-do list for today.
