### ISSUE TITLE
When can the "old page" rules in fellows.scss be removed?

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2718]
ref: https://github.com/mozilla/foundation.mozilla.org/pull/2701/files#r259854771

**Comment by Pomax** [comment]
After we finish porting fellows pages. The old rules in there only for as long as the old (e.g. current until we port?) pages exist.

**Comment by alanmoo** [comment]
Sorry, I meant "add a comment to the codebase stating when these can be removed"

**Comment by kristinashu** [comment]
Guessing this can now be removed?

**Comment by alanmoo** [comment]
Most likely.

To close this ticket:
- [ ] Remove the styles [here](https://github.com/mozilla/foundation.mozilla.org/blob/master/source/js/components/fellow-list/directory-filter-bar.scss#L33)
- [ ] Confirm the filter component still looks as expected.
