### ISSUE TITLE
Prevent dependabot updates from triggering Percy

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2719]
These updates are going to kill our monthly quota for (mostly) no reason. I know Travis has a way to prevent it from being run, does Percy?

(I'd still want to see it run, but only for the coalesced updates we manually create based on dependabot.)

@Pomax @patjouk @cadecairos

**Comment by Pomax** [comment]
From talking to the Percy folks:

>we're noticing that we're burning through screenshots thanks to a security service that files PRs whenever there are dependency updates to any of our million dependencies - is there a way to tag a PR such that percy ignores the associated CI's trigger for visual testing?

>> It's possible, you'll want to use the PERCY_ENABLE env variable to disable Percy in CI for those PRs

>Ah, thanks. I guess we'll be looking into figuring out how to make Travis set that variable for dependency PRs then.

>>I wonder how hard it would be to have check the git user info in TravisCI and disable percy based on the dependabot user? Yeah, I'd be curious. We've seen some customers do the inverse where they only enable Percy when there's something like [visual] in the commit message 

>oh interesting. It would be cool if those customers could report back how they did that to see if it might be an approach worth putting in the official "how to" docs =)

>>Yeah that would be interesting. It looks like dependabot uses the same branching convention. It might be easier to disable percy for branches that start with `dependabot/ `

>ah, good observation. we'll see if we can easily tap into that.

**Comment by patjouk** [comment]
It's worth trying :) @Pomax Want to do it since you're in contact with the folks at Percy? It will be easier to report to them if that worked.

**Comment by patjouk** [comment]
Decided to [give it a try](https://github.com/mozilla/foundation.mozilla.org/pull/2730/commits/4f7774e1275941074c803872d17e273e01bf7fdd#diff-354f30a63fb0907d4ad57269548329e3R55) since I'm working on a new Travis config file.

**Comment by Pomax** [comment]
I recall seeing you comment on conditionals in Travis being not super great, did that try work out?

**Comment by patjouk** [comment]
I'm going for something different. If I can't make it work, conditional on dependabot branch name will work.

**Comment by patjouk** [comment]
It's done!
