### ISSUE TITLE
Pre-checks for launching fellowships 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2723]
### Soft launch Feb 28.

- [x] review [checklist](https://docs.google.com/document/d/1Raa5uZTmTyeUMZ6nRzMRJM6TG4J8SdSceB5AUl_0aJE/edit)

- [x] redirects (with and without `en`):
  - [x] https://foundation.mozilla.org/fellowships/directory/ to https://foundation.mozilla.org/en/fellowships/meet-our-fellows/
  - [x] https://foundation.mozilla.org/fellowships/support/ to https://foundation.mozilla.org/en/fellowships/partner-with-us/
  - [x] https://foundation.mozilla.org/fellowships/get-involved/ to https://foundation.mozilla.org/en/fellowships/apply/
  - [x] https://foundation.mozilla.org/en/opportunity/fellowships-faq/ to https://foundation.mozilla.org/en/fellowships/faq/

- [ ] remove old fellowship pages (#2737) 

- [x] remove old CMS FAQ page

- [x] check both links on [/initiative](http://foundation.mozilla.org/initiatives) (probably don't need to update)

**Comment by alanmoo** [comment]
Any link that simply adds a locale shouldn't need an update. Once `/fellowships` is gone, Wagtail will automatically try to add the locale, and it will find the new pages.

**Comment by kristinashu** [comment]
Oh yeah, ok I'll remove that one.

**Comment by alanmoo** [comment]
Ok, I've done everything except removing the old pages, which has been filed as #2737. Closing in favor of that.
