### ISSUE TITLE
Create new template: Primary Page banner, campaign page below

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#2725]
For the Misinfo campaign we need an intermediate solution for its campaign landing page. We need a Primary Page that will have the option of adding a petition. The URL for this page should be the same as what we currently have for the landing page: https://foundation.mozilla.org/campaigns/eu-misinformation/

**List of requirements:**
- [x] Primary Page look and functionality
- [x] Can add a petition
~~- [ ] Can change banner image (related to #2661)~~

Redpen (first three designs):
https://redpen.io/tb154f87eb91f8fb07

Mobile:
![image](https://user-images.githubusercontent.com/20977376/53437254-11208900-39cb-11e9-9fe9-822848ea6468.png)

Desktop:
![image](https://user-images.githubusercontent.com/20977376/53437301-272e4980-39cb-11e9-91d2-e753491a1cca.png)

cc: @xmatthewx

**Comment by kristinashu** [comment]
Assigned to @alanmoo to triage.

So basically we need a new template where the banner and subnav look like a primary page and below the subnav will look like campaign pages.

**Comment by alanmoo** [comment]
I've updated the title of this to be more clear that it's a new template type entirely.

@kristinashu @beccaklam: Where else do you anticipate this template being used in the future (once it evolves)?

**Comment by beccaklam** [comment]
I think the campaigns team would use it again, so in campaigns for sure. @kristinashu mentioned something about MozFest?

**Comment by Pomax** [comment]
I assume that this is "not a primary page" for the purposes of being part of the main site navigation (like the intiatives/participate/etc primary pages)?

**Comment by alanmoo** [comment]
Right, this is more along the lines of a sibling to the existing campaign/opportunity pages.

**Comment by xmatthewx** [comment]
I see it as landing page for long-term initiatives that warrant a home. I could see it used for Machine Decision Making as we build up content and perspective in that space. I could see it replacing the internet health report parent site (while keeping reports themselves elsewhere). It could be used to establish the new home for mozfest.

**Comment by kristinashu** [comment]
Naming could be something along the lines of "special landing page"? 

Yes to what Matthew said, I think something like CS Challenge using this too.

**Comment by kristinashu** [comment]
This might be helpful https://redpen.io/hx70e9eb24e0534b72

**Comment by xmatthewx** [comment]
Litmus test: could our team _and_ stakeholders imagine buying a vanity url to redirect to this page? If yes, then this template is the right choice. 

Also worth noting: we don't want anyone and everyone using this template. They should have design support for IA and banner graphic.

**Comment by alanmoo** [comment]
Unfortunately, we can't constrain use of a specific template by user permissions, but we can constrain where it gets used and where they can create pages. That being said, it seems like this shouldn't have restrictions because we want it under `/campaigns` and possibly under the homepage (`/mozfest`, for example).

**Comment by Pomax** [comment]
For the `primary page look and function` does that include the options for "narrowed page content" and "zen nav"?

**Comment by alanmoo** [comment]
We should talk about removing the zen-mode option (forcing it on everything except primary pages, I believe?).

As for the narrowed page content- I believe we should be ignoring it. As in, don't make it affect anything in the template's rendering.

**Comment by Pomax** [comment]
I'm trying to touch as little as possible by extending and overwriting the bare minimum, so code that already checks for narrow content will keep doing that, and new code will too if it's role is to "shim" a bit of code that's missing due to partial template inheritance (yay, tech jargon!). Any bits that end up duplicating zen/narrow checks can be part of a cleanup pass once we do one.

**Comment by beccaklam** [comment]
This is pretty much done. Just following up with some QA in #2661
