### ISSUE TITLE
Image Text Mini should be full width

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2726]
Sorry I didn't catch this during QA but looks like this component isn't filling the container width. It looks good a narrower widths but isn't quite wide enough at the widest one.

Example https://foundation.mozilla.org/en/fellowships/apply/

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/1068783/53445183-d582c080-39c4-11e9-9638-a18a092cf013.png">

cc @youriwims @Pomax @alanmoo

**Comment by kristinashu** [comment]
Also wondering if this is way the icons are so small now? I swear they were bigger in the PR.

<img width="982" alt="image" src="https://user-images.githubusercontent.com/1068783/53445735-16c7a000-39c6-11e9-94c3-076f791e8c84.png">

**Comment by youriwims** [comment]
Okay, so you always want this component to span the full width of whatever container it's in? Also, checking out the icon size now. Thanks!

**Comment by youriwims** [comment]
Are these correct?

**Component View**
<img width="624" alt="screen shot 2019-02-26 at 4 55 10 pm" src="https://user-images.githubusercontent.com/36484608/53449239-64083980-39e7-11e9-8710-b075806f436e.png">
<img width="619" alt="screen shot 2019-02-26 at 4 55 36 pm" src="https://user-images.githubusercontent.com/36484608/53449242-65396680-39e7-11e9-8c20-cdd31b5b98ad.png">

**Page View**
<img width="1013" alt="screen shot 2019-02-26 at 4 57 05 pm" src="https://user-images.githubusercontent.com/36484608/53449353-9ca81300-39e7-11e9-9e59-822219b56ea3.png">
<img width="1059" alt="screen shot 2019-02-26 at 4 57 18 pm" src="https://user-images.githubusercontent.com/36484608/53449355-9dd94000-39e7-11e9-8760-4436aa42780a.png">

**Comment by kristinashu** [comment]
Yes exactly, component should span the full width of whatever container it's in.

And yes, icons size looks correct!
