### ISSUE TITLE
remove ENABLE_PROFILE_DIRECTORY_BLOCK from staging and production

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2731]
we should remove ENABLE_PROFILE_DIRECTORY_BLOCK from the staging environment once master redeploys, and remove ENABLE_PROFILE_DIRECTORY_BLOCK from the production environment once we promote staging.

- [x] master deployed to staging
- [x] staging environment cleaned up
- [x] staging promoted to production
- [x] production environment cleaned up

**Comment by youriwims** [comment]
This is done ✅
