### ISSUE TITLE
Make wagtail page sections collapsable

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2735]
Only if this is a thing Wagtail can do very easily, though I ask because I'm pretty positive it can:
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/1682681/53530135-f0d0f700-3abc-11e9-9d22-90df4c593cbd.png">
I'm pretty sure the white triangles on pink backgrounds exist because they're "expanded" sections. It would be nice to enable the collapsability of them if we can with a simple option.

**Comment by Pomax** [comment]
From [the docs](https://docs.wagtail.io/en/v2.1.3/reference/pages/panels.html):
---

### Collapsing MultiFieldPanels to save space

By default, MultiFieldPanel s are expanded and not collapsible. Adding collapsible to classname will enable the collapse control. Adding both collapsible and collapsed to the classname parameter will load the editor page with the MultiFieldPanel collapsed under its heading.

```
content_panels = [
    MultiFieldPanel(
        [
            ImageChooserPanel('cover'),
            DocumentChooserPanel('book_file'),
            PageChooserPanel('publisher'),
        ],
        heading="Collection of Book Fields",
        classname="collapsible collapsed"
    ),
]
```

**Comment by HSR05** [comment]
Is anybody working on this?

**Comment by alanmoo** [comment]
Feel free to open a PR! I'd err on the side of "don't collapse things by default" but do make most panels collapsable.

**Comment by HSR05** [comment]
@alanmoo the collapsing of multifields is making sense to me. As i am new to this code base, can you just help me walkthrough and reach the wagtail pages section. I would be more than thankful. Cheers 👍

**Comment by alanmoo** [comment]
I'm just referring to page models inside the wagtailpages app.

**Comment by kristinashu** [comment]
@HSR05 was that helpful? Are you still interested in working on this?

**Comment by HSR05** [comment]
Yes, I will give it a try. 👍
