### ISSUE TITLE
Directory component improvement: hold past height while fetching new list

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2738]
When switching from one year in the filter component to the next, the page "jumps" because the div is suddenly emptied out while fetching the next group of profiles. Can we reduce the visual impact of this? Perhaps by grabbing the height of the div when switching, manually setting it with an inline style, then removing it once the new data has loaded. (Feel free to go about it another way, I just wanted to explain the steps as I see them for functional clarity.)

![jumpy-filter](https://user-images.githubusercontent.com/1682681/53578469-c2e3c500-3b45-11e9-9ba9-9f33f3fd65d3.gif)

**Comment by Pomax** [comment]
An alternative is to not clear out the results until we _have_ new results, and show the load indicator in some other fashion.

**Comment by alanmoo** [comment]
Good point. @kristinashu any thoughts on this?

**Comment by HSR05** [comment]
I'd like to take this up. Can you guide me on this @alanmoo ? Thankyou.

**Comment by alanmoo** [comment]
Thanks for the interest, but this still needs some design guidance.

**Comment by kristinashu** [comment]
> An alternative is to not clear out the results until we have new results, and show the load indicator in some other fashion.

This might not give users enough feedback that content is updating.

The white space with loading icon is fine. I think all it needs is to make it so the footer doesn't jump up (I think what you where saying Alan).
 
Although I think a bigger ux issue is how the page jumps sometimes [probably a new ticket]. 
Step to repeat:
- load the page
- scroll down past the secondary nav
- click on a year
You will see how the page scrolls up a little. It should remain in the same scroll position.

![ezgif-5-306c747a6497](https://user-images.githubusercontent.com/1068783/54319950-a5344800-45a8-11e9-905e-759072f16a66.gif)

**Comment by alanmoo** [comment]
Same issue. Since the content is temporarily "empty", you're moved to the bottom of the page, and the top might actually need to scroll up. When the content re-fills, it does so from wherever the top of the page currently is.

**Comment by HSR05** [comment]
@alanmoo Can we use an anchor in that place so that when we jump to next year and the content re-fills, it does so from wherever the top of page currently is but jumps the the anchor which is at the height of the previous click?

**Comment by alanmoo** [comment]
I don't think that would work- the anchor jump happens instantly. And we'd still have the height shrinking while the new content is loading. Keeping the height of the directory will solve both problems.

**Comment by HSR05** [comment]
I would like to implement it. Can you guide me ? I'd be very thankful. 👍

**Comment by alanmoo** [comment]
Off the top of my head:
Spin up the repo and create a primary page that has a profile listing component, with a profile type of "fellow" ("fellows"?) and filters of 2019, 2018, 2017.

Add some code [to this function](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/static/js/directory-listing-filters.js#L86) that preserves the height of the profileContainer before replacing the content of it with a spinner.

Make sure that when the content loads, that fixed height is removed.

**Comment by HSR05** [comment]
I'll give it a go!! Thankyou for the guidance. 👍

**Comment by Pomax** [comment]
@HSR05 just to check, are you looking at this? (if not, that's fine, just making sure our issues are tagged correctly)

**Comment by HSR05** [comment]
@Pomax I have exams going on!! I'll be working on it side by side!!

**Comment by Pomax** [comment]
In that case I would rather unassign it and have someone on staff work on it, mostly because we're trying to clean up some issues and if you're splitting time between exams and this, our issue list should not interfere with your education.
