### ISSUE TITLE
add test and fake_data for BanneredCampaign

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2742]
follow-up to https://github.com/mozilla/foundation.mozilla.org/pull/2733, to add coverage testing and a load_fake_data entry for BanneredCampaigns

**Comment by Pomax** [comment]
This is probably related to https://github.com/mozilla/foundation.mozilla.org/issues/2786 in the sense that we need to figure out whether or not we want "tests" or whether we want an actual real world bannered campaign page to act as our test case.

**Comment by cadecairos** [comment]
already done!
