### ISSUE TITLE
Generate id attribute for headings in streamfields (anchor links)

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2743]
Problem: In order to be able to link directly to sections of our pages, we need headings to have an ID attribute.

Suggested solution: Use JS to create IDs based on the text of `h1` and `h2` elements (at least) of streamfield content.

This will be used for the EU-misinfo campaign

cc @beccaklam

**Comment by Pomax** [comment]
After trying a few things, the JS solution probably isn't the right one, as it will have to force in `id` attributes and then also do fragment-id detection on the URL, with a forced navigation to scroll to that fragment, which it won't do "in sync" with the page, so it might kick in when the user's already started scrolling...

It might be possible to wrap the `richtext` wagtail tag with our own tag that drops ids into the HTML code that gets generated server side, instead.

**Comment by alanmoo** [comment]
Ah, that makes a lot of sense. I should have thought of that being a problem. 🙃
