### ISSUE TITLE
Campaign banner template needs banner image to be editable

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2744]
Editors should be able to choose the image that appears across the top of bannered campaign pages.

**Comment by Pomax** [comment]
This feels like something we might actually want to put on the primary page itself. There's no good reason I can think of that would require that image to be a hardcoded asset.

**Comment by alanmoo** [comment]
@beccaklam Any objections to this? Default image as it exists, but with the ability to override on all pages with banners if desired? (Assuming it's the same amount of work or less)

**Comment by kristinashu** [comment]
Is this the same as - Make header image on primary pages cms editable #2661 ?

**Comment by beccaklam** [comment]
No objections from me! Same bird, one stone.

**Comment by Pomax** [comment]
given https://github.com/mozilla/foundation.mozilla.org/issues/2661, I'm going to mark this a duplicate, get 2261 sorted out, and as the BanneredCampaign extends the PrimaryPage, it'll get the banner "for free"
