### ISSUE TITLE
Create Special Landing Page Pt 2: The 'Editorial Banner' (or w/e we decide to name it)

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#2756]
When design is finalized and there's time/resources we want to build out this design for larger, more long term campaigns:
![image](https://user-images.githubusercontent.com/20977376/53742968-ce95fb00-3e67-11e9-8c3b-f665edf2f2b6.png)

Things to do:

- [ ] Finalize design (responsive widths)

- [ ] Build it

**Comment by kristinashu** [comment]
Sounds like the design we want for this will also need to work for MozFest. Once you're up to speed with MozFest stuff you might want to close this ticket and open a more holistic one!

**Comment by kristinashu** [comment]
@beccaklam can this be close, focus efforts on the mozfest landing page and go from there? I don't feel like there is anything we can do for this ticket right now.

**Comment by beccaklam** [comment]
Agreed!
