### ISSUE TITLE
Design newsletter signup in nav

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2757]
Launch mid-late April 2019

Product Owner: Anil
Project Manager: Kristina
Consultant: Will, Jen
Design & UX: Natalie or Rebecca
Dev: Mavis or Youri

We would like to add signup ‘above the fold’, most likely in the nav next to donate. This will link to a new signup page [link to ticket].

Goal from Anil: Make signup form more prominent on our site with compelling, tested, signup language that reinforces the value proposition of the Foundation.

We should look a how many/much donations are coming in via the nav donate button so we know how effect/important it is.

Steps:
- [x] benchmark
- [x] decide what text should say (join, signup, newsletter...)
- [x] mockup different 3 options
- [x] get feedback from design team
- [ ] A/B test two options

Requirements:
- [x] hover state & selected state
- [x] desktop & mobile layout

See footer sign up https://redpen.io/p/nr17f804a498f8d46c https://github.com/mozilla/foundation.mozilla.org/issues/2546

**Comment by kristinashu** [comment]
Copy note from Anil:

One thing the team that is working on the welcome series should be aware of is the value prop stated in this sign up form though. For an example of an abbreviated value prop, check out the signup form on https://www.wcs.org/. As someone who signs up to that list for example, my expectation is that what I receive after will be congruent with the promise implied by the copy on the signup form.

**Comment by kristinashu** [comment]
A few examples:
<img width="1438" alt="Screen Shot 2019-03-17 at 3 18 40 PM" src="https://user-images.githubusercontent.com/1068783/54542825-bc34ba80-4959-11e9-896c-975d30f9f73c.png">

<img width="1379" alt="Screen Shot 2019-03-17 at 8 39 52 PM" src="https://user-images.githubusercontent.com/1068783/54542827-bc34ba80-4959-11e9-837e-afadf1df5b8b.png">

<img width="1185" alt="Screen Shot 2019-03-17 at 8 40 38 PM" src="https://user-images.githubusercontent.com/1068783/54542829-bccd5100-4959-11e9-8cc1-16bebce41402.png">

**Comment by kristinashu** [comment]
Designs are coming along here https://redpen.io/p/uvd561910fde4f4bc9

Couple options to test:
<img width="842" alt="image" src="https://user-images.githubusercontent.com/1068783/54859421-2cc93780-4cca-11e9-9a12-a993acdaea48.png">

Still exploring but clicking of "Stay in touch" could open drawer just below with form.
<img width="973" alt="image" src="https://user-images.githubusercontent.com/1068783/54859414-191dd100-4cca-11e9-8b7f-8ff9451fee4f.png">

**Comment by kristinashu** [comment]
@beccaklam can you also please help out this ideas for this?

**Comment by kristinashu** [comment]
I've updated redpen but an feeling a little stuck on this https://redpen.io/p/uvd561910fde4f4bc9
@beccaklam if you have any ideas, please test 'em out!

Possible Test Variant A:
<img width="891" alt="image" src="https://user-images.githubusercontent.com/1068783/55357892-f9816800-5482-11e9-81a8-1605c7a8b491.png">

Possible Test Variant B:
<img width="881" alt="image" src="https://user-images.githubusercontent.com/1068783/55357927-0e5dfb80-5483-11e9-910c-a82effde65df.png">

Form if user clicks on Subscribe (all success and errors would be the same as footer signup):
<img width="648" alt="image" src="https://user-images.githubusercontent.com/1068783/55357950-17e76380-5483-11e9-8357-6af428da9c10.png">

@alanmoo @Pomax is this the type of thing we can set up to A/B test?

**Comment by alanmoo** [comment]
I believe the A/B framework we put in was more about page content variations, but there might have been hooks for this kind of thing.

A thought about the slide-out: isn't this form going to be in the footer of every page too? Any reason we wouldn't just make it a jump/smooth scroll down to that?

**Comment by kristinashu** [comment]
Yeah scroll down could be a nice MVP! Doesn't feel as focused as the slide-out form tho since there are a bunch of additional links in and around the footer.

**Comment by alanmoo** [comment]
Ah, wait: if it's super close to the bottom of the page, the page won't scroll up enough to bring the sign-up to the top, especially on desktop.

**Comment by beccaklam** [comment]
Some ideas based on http://time.com/, https://www.charitywater.org/, https://www.worldwildlife.org/, and https://www.timeout.com/ where they weight two things equally in the top left hand corner.

## Button Version:
![Home Copy 7@2x](https://user-images.githubusercontent.com/20977376/55430225-8ac40d80-555b-11e9-87a4-13a09d9dcf77.jpg)

On hover:
![Home Copy 10@2x](https://user-images.githubusercontent.com/20977376/55430236-8ef02b00-555b-11e9-846f-d5347d777746.jpg)

## Just Links Version:
![Home Copy 11@2x](https://user-images.githubusercontent.com/20977376/55430239-9283b200-555b-11e9-8707-473aca8d5012.jpg)

On hover:
![Home Copy 12@2x](https://user-images.githubusercontent.com/20977376/55430254-97486600-555b-11e9-9baa-414d685aa82b.jpg)
@kristinashu

**Comment by kristinashu** [comment]
Thanks Rebecca! The design team has decided on these for the final comps:

![Home Nav@2x](https://user-images.githubusercontent.com/1068783/55438762-65cd9b80-5557-11e9-9d2e-9b4db6f3ce11.jpg)

Newsletter opens on click:
![Nav Open@2x](https://user-images.githubusercontent.com/1068783/55438763-66663200-5557-11e9-82c1-59a913771732.jpg)

Buttons prioritized on mobile:
<img width="317" alt="image" src="https://user-images.githubusercontent.com/1068783/55438787-767e1180-5557-11e9-8d57-e85aa8cacec6.png">

Newsletter opens on tab (closing by clicking on anywhere in nav bar or clicking Sign up button):
<img width="319" alt="image" src="https://user-images.githubusercontent.com/1068783/55438771-6cf4a980-5557-11e9-8876-66e148901c11.png">

Implementation ticket is here https://github.com/mozilla/foundation.mozilla.org/issues/2948
