### ISSUE TITLE
CMS images caching

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2761]
From @sabrinang:

Regarding images in the CMS / thumbnail issue:

I see the same image for all the images but in the editing view I have uploaded different PNGs but the live link is displaying one thumbnail or multiples

See pages: https://foundation.mozilla.org/en/docs/brand/design/templates/ or https://foundation.mozilla.org/en/docs/brand/design/logos/ 

Image is wrong on prod:
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/1068783/53835250-d88c2c80-3f41-11e9-9592-bc6d0040e989.png">

Image is correct in editor:
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/1068783/53835304-01acbd00-3f42-11e9-9afe-8f930ee4ca4f.png">

cc @beccaklam because she was having similar issue on staging

**Comment by cadecairos** [comment]
Possibly related: https://github.com/wagtail/wagtail/issues/3883 (need to look a bit closer...)

**Comment by cadecairos** [comment]
https://github.com/wagtail/wagtail/issues/3206 seems to actually be our issue.

@kristinashu @sabrinang short term, you can unblock yourselves by uploading images which have unique file names *in the first 17 characters*

I'm going to see how to mitigate this long-term.

**Comment by cadecairos** [comment]
Possible Work-Around is `AWS_S3_FILE_OVERWRITE = False` in settings.py
