### ISSUE TITLE
remove some mention of mezzanine from our docs

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2762]
based on https://github.com/mozilla/foundation.mozilla.org/pull/2746, it turns out we actually still mention mezzanine in a few places, and those should get removed =)

**Comment by SimiCode** [comment]
@alanmoo @Pomax 
Great! I'll take this on :)

**Comment by SimiCode** [comment]
@alanmoo @Pomax
I created a PR for this. Please review and advise.
