### ISSUE TITLE
Fix up the banneredcampaign page template

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2769]
it looks like there's a bit too much spacing between its banner and the main content: 

![image](https://user-images.githubusercontent.com/177243/53910786-8f071480-4009-11e9-98c2-28491812dc29.png)

**Comment by Pomax** [comment]
compare this to primaries:

![image](https://user-images.githubusercontent.com/177243/53910817-a2b27b00-4009-11e9-9c0f-80cf9953069f.png)

**Comment by kristinashu** [comment]
Looks like this has been fixed https://foundation.mozilla.org/en/campaigns/eu-misinformation/
<img width="1374" alt="image" src="https://user-images.githubusercontent.com/1068783/55442238-a979d280-5562-11e9-8395-7d5ca73f482b.png">
