### ISSUE TITLE
Fix banner image 'cutout' on Landing Page Template

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#2784]
Just some QA on the new 'Bannered Campaign Template':

When adding a new image for the header, depending on the aspect ratio of the image loaded the white 'cut out' box disappears:

**Original:**
![image](https://user-images.githubusercontent.com/20977376/54152919-be0bf480-4414-11e9-9640-26cd75c43d93.png)

**New Header**
![image](https://user-images.githubusercontent.com/20977376/54152969-d67c0f00-4414-11e9-8a0d-15727c60e2d9.png)

Let's discuss what the best option is for making sure the white cut out remains constant responsively. If we decide to go the aspect ratio route, @kristinashu do you have an opinion of whether or not we should tie it to the 16:9 ratio we have more most images on the site. Or are we ok with creating a new aspect ratio for this use case?

**Comment by kristinashu** [comment]
I'm ok with creating a new aspect ratio for this use case since it's quite different than our other images.

**Comment by beccaklam** [comment]
@mmmavis just a note, the bannered campaign template inherits its header code from the primary page header. so if we are making changes in the code we would need to do it in the primary page code.

**Comment by xmatthewx** [comment]
Good catch @beccaklam! I'd like to flag this as very important to fix even if it might seem like a little visual thing. This landing page template will likely account for 90% of all traffic to the site this year.

**Comment by mmmavis** [comment]
@beccaklam 

> the bannered campaign template inherits its header code from the primary page header. so if we are making changes in the code we would need to do it in the primary page code.

So primary page (and hence campaign template) will have its own aspect ratio for the banner? If so, what aspect ratio do we want it to be?

**Comment by beccaklam** [comment]
@mmmavis Well we could make it whatever aspect the current default image is since the header was built around that. Was just wondering if that's the best solution or if there's a solution in code?

**Comment by xmatthewx** [comment]
Ah, I see. If I'm understanding this correctly (which I might now)...

It does seem like we _should_ have standard image dimensions for adding those banners. And it should inform the user in the cms next to the upload button. 

To fix this with code, I'm guessing that there are a few options, but I'd also wager than none of them are great. We don't want to stretch images to fit. We don't want to add a default background color to fill extra space. We _could_ set it to repeat horz or vert if the image isn't big enough or the right proportions, but that feels very risky – it could breakdown in several different ways, especially with a user image that doesn't repeat well. 

I leave to you all to decide what's best, but my instinct is that the best solution is with a standard size image and good user instructions in the CMS.

**Comment by mmmavis** [comment]
I'd like to avoid writing custom code to fix design issue just for a particular page. 

In terms of technical solution, it's pretty versatile so don't worry about how things are implemented currently. I just need to understand the design specs better before I can come up with a new technical solution:

1. Currently the banner section is set to be fixed height, 144px, on both mobile and desktop. Is fixed height still something we wanna keep?
2. Is there a dimension restriction for the banner image?
  - If so, how do we wanna enforce it? Is simply having a note as help text in Wagtail sufficient enough?
  - If not, what image treatment do we prefer to have for images smaller or bigger than the banner section, respectively?
3. Do we always want to have cutout treatment?

**Comment by Pomax** [comment]
to be clear: the primary page is currently set to min-width 100% for the banner, but not min-height: 100%, so if the banner is "less high than the actual block it's sitting in", it won't look like there's a cutout. There is one, but the banner CSS is set not to repeat vertically, so you won't see it as it'll be white on white.

**Comment by Pomax** [comment]
To illustrate, I'm pretty sure we're running into this:

![image](https://user-images.githubusercontent.com/177243/54233360-09340f00-44ca-11e9-9428-4000133d1690.png)

I've made the banner have a not-white background to show off the cutout's happening, but the banner image isn't tall enough to cover the banner's vertical space.

**Comment by beccaklam** [comment]
> I'd like to avoid writing custom code to fix design issue just for a particular page.
> 
> In terms of technical solution, it's pretty versatile so don't worry about how things are implemented currently. I just need to understand the design specs better before I can come up with a new technical solution:
> 
>     1. Currently the banner section is set to be fixed height, 144px, on both mobile and desktop. Is fixed height still something we wanna keep?
In reading Pomax's comments, I'm assuming the answer is yes? It would be good to have the height consistent across pages/sizes.
>     2. Is there a dimension restriction for the banner image?
Currently, no, but I think there might need to be.
> 
>     * If so, how do we wanna enforce it? Is simply having a note as help text in Wagtail sufficient enough?
Maybe not, if these pages are going to be staff authored/edited it might be best to give them hard and fast rules. So, like an error message and the image not uploading if it doesn't meet our requirements.
>     * If not, what image treatment do we prefer to have for images smaller or bigger than the banner section, respectively?
See response above ...
> 
>     1. Do we always want to have cutout treatment?
Yes

**Comment by xmatthewx** [comment]
I don't think we can feasibly make this fool-proof for staff users. 
 - Best we can do is probably add a tip to the author component UI. These images will almost always be created by design staff. 
 - If staff mess it up often, we could hide the upload button in the settings tab. 

I have no idea what the requirements are for the image. Please don't copy the text in my mockup. 



<img width="599" alt="image" src="https://user-images.githubusercontent.com/53411/54237209-d13dc380-44eb-11e9-8e6b-055371dbe2c9.png">

**Comment by mmmavis** [comment]
Cool. If we are settled on having fixed height then this should be simple fix. I'll have a PR up first. @beccaklam let's sync up tomorrow after stand.
