### ISSUE TITLE
Update middleware to support multiple domains

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2790]
We want to allow Wagtail to determine which domain a request is coming in for so that it can serve the appropriate page. I've set up a new site on staging with a url of https://mozillafestival.mofostaging.net yet foundation.mofostaging.net is being served up. 

In Slack, @cadecairos mentioned this needs to be updated: https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/utility/middleware.py#L11

**Comment by cadecairos** [comment]
I can work on this today
