### ISSUE TITLE
[Wagtail Component]Find Image Text 2 & Replace with Image Text Component in CMS

### ISSUE THREAD

**Issue by youriwims** [mozilla/foundation.mozilla.org#2792]
This the second step in completing the renaming process of Image Text 2 [Old Component] to Image Text [New Component]. Image Text has been created and is ready to replace Image Text 2. Once this is done, we can officially [remove the Image Text 2 Component](https://github.com/mozilla/foundation.mozilla.org/issues/2793).

The Block Inventory [list](https://foundation.mozilla.org/cms/inventory/?form-TOTAL_FORMS=3&form-INITIAL_FORMS=0&form-MIN_NUM_FORMS=0&form-MAX_NUM_FORMS=3&form-0-has=includes&form-0-block=networkapi.wagtailpages.customblocks.ImageTextBlock2&form-1-has=includes&form-1-block=&form-2-has=includes&form-2-block=) shows ~18 pages where there are instances of the old component.

Part 1: #2783
Part 3: #2793
OG Ticket #2693

**Comment by kristinashu** [comment]
Ok these are ALL DONE!!!
