### ISSUE TITLE
[Wagtail Component] Remove Image Text 2 Component

### ISSUE THREAD

**Issue by youriwims** [mozilla/foundation.mozilla.org#2793]
This the last step in completing the renaming process of Image Text 2 [Old Component] to Image Text [New Component].

Part 1: #2783 
Part 2: #2792 
OG Ticket: #2693

**Comment by youriwims** [comment]
This is blocked until Part 2 is complete.

**Comment by kristinashu** [comment]
Part 2 is complete!
