### ISSUE TITLE
People Name Links on People Cards (Fellowships)

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#2798]
On the fellowships page, https://foundation.mozilla.org/en/fellowships/meet-our-fellows/, when you click into another cohort year and click on the name of the fellow the URL `https://www.mozillapulse.org/profile/{{ profile.profile_id }}` leads me to a _profile not found_
![image](https://user-images.githubusercontent.com/2492510/54244062-1cee6e00-44e8-11e9-8717-feb4151852dc.png)

When I first go into the fellowships page the 2019 cohort name links work for me, it is when I click into another year and go back it becomes broken.

/cc @youriwims @pomax @kristinashu

**Comment by Pomax** [comment]
ah, those `{{` and `}}` should not be there, they're templating instructions, so let's see what's up with that.
