### ISSUE TITLE
Update existing heading/paragraph styles to standardized type

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#2806]
By referring to the brand standards typography issue: https://github.com/MozillaFoundation/Design/issues/319, let's clean up and update current type on the site.

This focuses on heading, copy/paragraph and introducing a dark theme. Any typography in UI components & other elements (form, nav etc.) will be dealt with in different issues.

**Comment by mmmavis** [comment]
@sabrinang for headings https://foundation.mozilla.org/en/docs/brand/design/Typography/ , does each class have the same font size and line height on both mobile and desktop?

**Comment by sabrinang** [comment]
No mobile is different than desktop, I have only documented desktop on the brand page. Please preserve scaling for screen sizes as we do.

**Comment by mmmavis** [comment]
@sabrinang what's the hover colour for anchor on dark theme? Is it `#a0a1f8`? If so can we name this new colour since it's not currently on our colour variable list?
