### ISSUE TITLE
Figure out how to make the nav "not need a scrollbar"

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2823]
From https://github.com/mozilla/foundation.mozilla.org/pull/2788#discussion_r264869974, 

>Two things to consider:
>
>1.) The DEV HELP item makes this worse at more resolutions than it is in reality
>2.) The fact that the nav needs to wrap in the first place seems like a bug, possibly a result of a switch to the items in the nav that we made a few months(?) ago.
>
>Between those two, I'd argue that this isn't an issue to solve here, and we should instead file a follow up about the banner itself looking wonky at just above 768px. Thoughts?

Let's find out how to fix our nav bar, because it should probably never trigger a scroll bar in the first place.

**Comment by alanmoo** [comment]
It triggers a scrollbar for you? It just wraps for me...

**Comment by Pomax** [comment]
![image](https://user-images.githubusercontent.com/177243/55428273-999bc780-553d-11e9-92b0-07df854c0e7c.png)

**Comment by cadecairos** [comment]
Closing this issue due to its age, if this is work that we still want to do, please refile this with up to date information so that it can be put in the correct milestone with up to date estimates.
