### ISSUE TITLE
Simplify homepage and participate page

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2824]
right now these pages are using tons of duplicated fields, where they should really be using a "1 or more" snippet chooser, with a normal Django model that capture those fieldsets as a single thing.

**Comment by abhinavsagar** [comment]
Can I work on this?

**Comment by Pomax** [comment]
Thank you for the offer, but model updating is fairly complex at the moment due to our deployment setup, so this is not a good bug for contributors.

**Comment by cadecairos** [comment]
Closing this issue due to its age, if this is work that we still want to do, please refile this with up to date information so that it can be put in the correct milestone with up to date estimates.
