### ISSUE TITLE
Quote CMS component 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2845]
Currently, the cms allows users to add multiple quotes:

<img width="1271" alt="Screen Shot 2019-03-13 at 3 24 26 PM" src="https://user-images.githubusercontent.com/1068783/54551612-aa5c1300-496b-11e9-816d-fcd510eabee5.png">

But only the first one shows up on the site:
<img width="803" alt="Screen Shot 2019-03-13 at 3 24 34 PM" src="https://user-images.githubusercontent.com/1068783/54551613-aa5c1300-496b-11e9-8eb6-710284056bc3.png">

The intention was to put them into a static carousel so users could swipe through to see different ones. Similar to this:
<img width="618" alt="Screen Shot 2019-03-18 at 10 49 09 AM" src="https://user-images.githubusercontent.com/1068783/54551711-d5defd80-496b-11e9-98ff-17392f00bb65.png">

Need to mock this up then open implementation ticket.

**Comment by kristinashu** [comment]
Here's the comp: dots are 14x14px and the distance between then is 14px

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/1068783/58918197-213cb880-86de-11e9-8bb8-4aae277f04f6.png">

**Comment by kristinashu** [comment]
Update: let's just remove the ability to have multiple quotes in one component.

**Comment by cadecairos** [comment]
Closing this issue due to its age, if this is work that we still want to do, please refile this with up to date information so that it can be put in the correct milestone with up to date estimates.
