### ISSUE TITLE
"harden" load_fake_data wrt changes in models and streamfield blocks

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2846]
Every time we add/remove models, or model fields, or streamfield blocks, load_faka_data in its current form will change all the random numbers and effective generate completely new data "downstream" from a change. That means that if we, for example, deprecate and remove a custom streamfield block used in modular pages, then all the Buyers Guide pages will suddenly have different content, too, which makes visual CI throw a bit of a fit (it'll flag a ton of diffs. All of them correct! But many of them not undesired)

Let's update load_fake_data so that we "reseed" the base python random number generator at each step, and at least ensure that changes to models in one place don't affect random data for another.

**Comment by cadecairos** [comment]
This was done already
