### ISSUE TITLE
Social sharing: facebook?

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#2850]
If we have paused using facebook, should we consider removing facebook from share options to be consistent? I'm unsure where this is at but I noticed we removed it from our footer so these may be other areas as well

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/2492510/54565561-dedfc700-498b-11e9-8f21-a6792669e9e5.png">
<img width="450" alt="image" src="https://user-images.githubusercontent.com/2492510/54565579-ebfcb600-498b-11e9-8c6c-afeb93be790d.png">
<img width="478" alt="image" src="https://user-images.githubusercontent.com/2492510/54566015-f1a6cb80-498c-11e9-92f3-6cdc005f45ef.png">

I noticed these during brand button audit

**Comment by kristinashu** [comment]
I think we're still ok with people sharing on Facebook (this is important for campaigns) but we are not directly posting to it or linking to our Facebook page.

So I think we can/should keep these instances of it.
