### ISSUE TITLE
Enable wildcard checkbox for Salesforce petitions

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2853]
Following up on some work we started last year, we have the ability to add custom checkbox fields to our petitions, but once the petition gets submitted to the backend, they get dropped. Let's make them get passed along to Salesforce fully.

@stephaniemcv @pmac, where did we net out on this? I believe the plan was to pass the extra checkbox states from Basket as JSON into some "extra" field on the campaign object. However, I don't recall how far we got before this work dropped off. What I need to know to push this ticket forward is the structure of what we need to pass to Basket. Right not it looks like

```
'data': {
  'json': True,
  'form': data,
  'event_type': 'crm_petition_data'
}
```

and the data looks something like

```
data = {
     "campaign_id": cid,
      "first_name": request.data['givenNames'],
      "last_name": request.data['surname'],
      "email": request.data['email'],
      "email_subscription": request.data['newsletterSignup'],
      "source_url": request.data['source'],
}
```

Do we need to simply tack on

`data.checkbox1=BOOL` before sending? Or does work need to be done on the Basket/Salesforce side?

[Relevant code](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/campaign/views.py#L103)

**Comment by pmac** [comment]
basket will look for a `metadata` field in the `data` and will write that to the `Petition_Flex__c` field in Salesforce as JSON encoded data. So borrowing your example you'd do something like:

```js
data = {
     "campaign_id": cid,
      "first_name": request.data['givenNames'],
      "last_name": request.data['surname'],
      "email": request.data['email'],
      "email_subscription": request.data['newsletterSignup'],
      "source_url": request.data['source'],
      "metadata": {
          "my-special-checkbox": true,
      }
}
```

And just FYI basket also looks for a `comments` field in the `data` as well and will put that into `Petition_Comments__c`.

**Comment by stephaniemcv** [comment]
Petition_Flex__c was added to the SFDC Advo sandbox. We need to sync up and test passing data to it before I can push to production.

**Comment by alanmoo** [comment]
Wait, @stephaniemcv you're saying we never landed comments for petitions on Salesforce either?

**Comment by stephaniemcv** [comment]
No, comments are completed, Petition_Comments__c is in Production and working. 

Petition_Flex__c only got as far as the sandbox. And yes, prep the data as Pmac described and we 3 should schedule a testing time to pass the data through the system to make sure it lands in Advo sandbox.

**Comment by cadecairos** [comment]
Closing this issue due to its age, if this is work that we still want to do, please refile this with up to date information so that it can be put in the correct milestone with up to date estimates.
