### ISSUE TITLE
Update hover state for links

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#2854]
Follow-up for https://github.com/mozilla/foundation.mozilla.org/issues/2806

Update hover state for links so the underline appears further away from the text (like links on mozilla.org)

/cc @sabrinang

**Comment by mmmavis** [comment]
@sabrinang can you provide specs and assign me this ticket when it's ready for implementation? I did a quick check on mozilla.org. It seems like 
- for headings/bold links , mozilla.org is using `border-bottom` to achieve the underline effect. Widths seem all to be `2px` and the underline colours seem to be **inconsistent**... the underline colour is usually the text colour with some opacity
- body size links seem to just use the default `text-decoration: underline`

**Comment by sabrinang** [comment]
**Heading Links**
border-bottom: 2px solid
(I liked how the default underline width proportionate to the font weight but by using border-bottom I’m assuming we have to set this width)
color: $black (for .h1-heading to .h5-heading)
color: $gray-40 (for .h6-heading)
hover transition: .1s ease-in-out
margin-bottom: 14px (.h1-heading), 12px (.h2-heading), 8px (.h3-heading, .h4-heading), 6px (.h5-heading), 4px (.h6-heading)

**Body Links** 
border-bottom: 1px solid
color: $dark-blue
hover transition: .1s ease-in-out
margin-bottom: 4px  (.body-small, .body and .cta-link )
margin-bottom: 6px (.body-large)

**Dark Theme**
color: $light-blue

I'm assuming margin-bottom is from the baseline of the text and not line height but let me know how I can provide the distance better (when I was inspecting the mozilla.org site it was in ems)

**Comment by mmmavis** [comment]
This ticket requires @sabrinang and I to block probably half a day or longer to work and test things side by side. Currently we don't have the capacity to do so. I'm gonna move this ticket to Backlog.
