### ISSUE TITLE
Sunset old email lists

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2857]
Not sure who to ping about this but @stephaniemcv seems like a good start! We have some inactive email lists like Webmaker, Mozilla Leadership Network, Mozilla Labs... Would it be possible to remove them completely so this list isn't so daunting for users? Perhaps email these inactive lists to let them know and encourage them to signup to the general list? 

![Screenshot_2019-03-19 Newsletter Subscriptions](https://user-images.githubusercontent.com/1068783/54649617-38b5bf00-4a68-11e9-9286-a61cb6567c9e.png)

**Comment by stephaniemcv** [comment]
Yeah...that is something I want to do, however that project lives in the LCM backlog and I don't see us or MoCo prioritizing it anytime soon. :(

**Comment by Pomax** [comment]
also pinging @cadecairos

**Comment by anilkanji** [comment]
> Yeah...that is something I want to do, however that project lives in the LCM backlog and I don't see us or MoCo prioritizing it anytime soon. :(

Even the ones we "own" like webmaker? @stephaniemcv

**Comment by stephaniemcv** [comment]
Yes, even the MoFo ones are included in the LCM project, trapped in the backlog. The only thing preventing us from trimming our own dead wood is and has been the prioritization of this work.

**Comment by kristinashu** [comment]
Sounds like some work has been done here. Non-key list only appear if someone signs up so for new signups, the list page is pretty clean looking:
<img width="779" alt="Screen Shot 2019-06-03 at 9 36 01 AM" src="https://user-images.githubusercontent.com/1068783/58911751-5ee51580-86cd-11e9-8662-055a671de094.png">
