### ISSUE TITLE
Add new "nav root page" setting to Wagtail pages

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2877]
Based on the output of a meeting, we should add a new checkbox setting to all Wagtail pages. Let's call it something like "Navigation root page". When true, the page will act as a root for all children below it, making them show up in programmatically generated menus on that page. 

### Successful implementation
We can remove the mini-site namespace template
We can place campaign/opportunity/primary pages at any point in the hierarchy and have their children show up in menus as if they're a mini-site.

### Use case

We'll be leveraging the BanneredCampaignPage in multiple spots around the site and for Mozfest, so we want to make sure secondary navs function properly.

I believe this is all back-end work that doesn't require any template modification, is that correct @Pomax?

cc @mmmavis @kristinashu

**Comment by kristinashu** [comment]
cc @xmatthewx

**Comment by Pomax** [comment]
This should still be something we can do, although how much work is required to make the menu system recognise the correct root page if there's more than one page with that checkbox set is an unknown right now.

**Comment by cadecairos** [comment]
@xmatthewx Is there a current use case that makes doing this work worth the time investment?

**Comment by xmatthewx** [comment]
I'll talk through the problem and use cases with Kristina at our next 1-1 and follow up here soon.

**Comment by xmatthewx** [comment]
@kristinashu did discover another case where this creates a limitation. I say we table this until the IA work is done. then we can evaluate if it's critical for primary pages, or a nice-to-have for program use cases.

**Comment by cadecairos** [comment]
Closing this issue due to its age, if this is work that we still want to do, please refile this with up to date information so that it can be put in the correct milestone with up to date estimates.
