### ISSUE TITLE
Automate the detection of "not following the style guide" where possible

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2888]
As an engineering follow-up on #2440, we should see if there are any things that we can think of that lets us detect "not style-guide compliancy". An easy one would be "CSS uses raw color instead of variable name", but there are no doubt many others that we can think of.

**Comment by cadecairos** [comment]
Closing this issue due to its age, if this is work that we still want to do, please refile this with up to date information so that it can be put in the correct milestone with up to date estimates.
