### ISSUE TITLE
Update PNI's link colours

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#2889]
@beccaklam @natalieworth 

We currently have overrides for PNI links to force them use the **old** link blues. Is it okay if we remove the overrides and make them use colours from our new set?

**Currently on PNI**
default: `#3bb7ef` (old blue) 
hover/focus/active state: `#4383bf` (old dark blue)

For reference,
<img width="583" alt="image" src="https://user-images.githubusercontent.com/2896608/54939713-7d1ce100-4ee6-11e9-96ae-35de96ac405a.png">

**Comment by beccaklam** [comment]
Yeah I think we can go for it. Did you actually already do it? When I look at the site, it looks like the new colours? @mmmavis

**Comment by mmmavis** [comment]
@beccaklam they are weird overrides everywhere but I'm planning to clean them up 😂
