### ISSUE TITLE
Create a Join page 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#2890]
Create a page to more seamlessly onboard professionals in our network to our mailing list and Pulse. This could be used with the public, but will be optimized for newly engaged professionals such as applicants to fellow, awards, and mozfest.

This will need to navigate some tech realities to smoothly submit stuff to both salesforce and Pulse. 

Next steps: 
 - compose a brief in [this doc](https://docs.google.com/document/d/1l5iD1Pcp4xxbwJdLk4f3uORbopTnHWXA4mbuOhP2a84/edit#)
 - develop simple wireframes to inform a discussion on requirements and limits with engineering

**Comment by Pomax** [comment]
Just out of practical curiosity: do professionals in our network rely on our site/use it to find their way through our material? Or do they instead interact with staff directly and rely on other (web)resources?

**Comment by xmatthewx** [comment]
Some no, some yes. Different programs have leveraged the site for program materials to varying degrees. Doing that for high level materials can simplify things. And... program applicants and participants have not been onboarded in a consistent manner, or at all. Here's brief context: [gdoc](https://docs.google.com/document/d/1Yw9zsHz0jOe_q97ydfBF17ZxI3PSFn1jiZ9O_PDIsIc)

**Comment by natalieworth** [comment]
Update: working on the UI for the option 4 version in the redpen https://redpen.io/p/ng0850c024851f8ce2

cc @gideonthomas

**Comment by natalieworth** [comment]
I've updated the desktop and mobile UI based on doc comments/ feedback etc. https://redpen.io/p/jx6c0e576743fd5de0

I had a couple of questions/ discussions that I posted in the [redpen ](https://redpen.io/p/jx6c0e576743fd5de0)

**Comment by natalieworth** [comment]
Updated desktop and mobile: https://redpen.io/p/jx6c0e576743fd5de0
Need to refine the 4 'why join' icon illustrations.

**Comment by natalieworth** [comment]
Most recent Join pages for mobile/ desktop are in here for reference: https://redpen.io/p/wp17e9f94b044da4a0

**Comment by natalieworth** [comment]
Created dev tic for this here https://github.com/mozilla/foundation.mozilla.org/issues/3145
[Redpen doc is updated here ](https://redpen.io/zgec7048af617e6e44)

**Comment by natalieworth** [comment]
Added a join us page[ draft in CMS](https://foundation.mozilla.org/cms/pages/395/edit/)

We moved the 'Sign up' button further up the page (since it can't be center aligned at the bottom and it looked odd left aligned).

![Screenshot_2019-05-15 Join Us](https://user-images.githubusercontent.com/14876567/57816945-18d20d00-7732-11e9-9616-e54c71f91151.png)

**Comment by natalieworth** [comment]
Added the Join Us page to the foundation site: #3147
