### ISSUE TITLE
squash our django migrations

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2893]
Especially the wagtailpages migrations take up a fair bit of time to run one after another, we should be able to squash them into a single thing rather than some 50+ steps =)

**Comment by Stark-Pramod** [comment]
@Pomax I want to work on this issue. Since I am a newbie to Open Source world I may need some guidance and help.

**Comment by Patil2099** [comment]
@Pomax  If this is still open can I work on this?
