### ISSUE TITLE
Create a safety first page

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#2896]
The [Safety first](https://advocacy-mozilla-org-prod.herokuapp.com/en-US/safety) campaign produced some excellent videos. With minimal work, we could get those videos onto a foundation site page. It'd also be nice to have them as pulse entries for discoverability. 

This is _not_ urgent, but a good quiet day activity. 

 - [ ] When it's done, we could change the old redirect to point to this #3260
 - [x] update link from pulse.

**Comment by kristinashu** [comment]
@natalieworth @beccaklam I've copied everything over https://foundation.mozilla.org/en/campaigns/safety-first/. Let me know if you have any other ideas of feedback and if not then can one of you give it an R+?

Then I'll run it past Brett and then get a dev to setup the redirect.

**Comment by natalieworth** [comment]
R+ ! Yeah! Cool to have it on the Foundation site now!

**Comment by beccaklam** [comment]
R+! Thanks for doing this @kristinashu !

**Comment by xmatthewx** [comment]
I wonder: is there a permanent path to a page like this? From IH page, privacy section?

**Comment by kristinashu** [comment]
Or maybe a card on /participate and /advocacy (feels a little out of place for IH page since we don't really link to anything else)?

**Comment by alanmoo** [comment]
Submit it to Pulse, tag it with `mozilla, campaign, advocacy` and it should pop up on https://foundation.mozilla.org/advocacy

**Comment by kristinashu** [comment]
I've opened a ticket for the redirects https://github.com/mozilla/foundation.mozilla.org/issues/3260

Updated the url link and the tag in Pulse, it now shows up on /advocacy.
