### ISSUE TITLE
Remove email cta snippet

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2899]
To streamline and grow our main email list, we'll no longer encourage individual/independent email lists. Soon we will have email signup in the footer and a link in the nav so we don't need any in-body within a cms page. Although mozfest will be an exception https://github.com/mozilla/foundation.mozilla.org/issues/2874.

Please determine if and where the following email cta snippet are being used, delete those instances, and then completely remove them as an option.
- Internet Health basic form
- MITI
- Fellowship basic form
- Default Form

<img width="632" alt="image" src="https://user-images.githubusercontent.com/1068783/54969602-ff83c000-4f3b-11e9-81d4-2eeadbfcab61.png">

<img width="434" alt="image" src="https://user-images.githubusercontent.com/1068783/54969595-f72b8500-4f3b-11e9-8b64-81fa91a87b17.png">

<img width="961" alt="image" src="https://user-images.githubusercontent.com/1068783/54969461-6b195d80-4f3b-11e9-85a4-66d163b9d812.png">

cc @alanmoo please update this ticket as you see fit.

**Comment by alanmoo** [comment]
Does this mean the opportunity page template will become a single column, plus navigation if present?

**Comment by kristinashu** [comment]
Not sure I understand what you mean, but yes it should be single column, plus nav if present. 

Example (all content should be same width as paragraph text, signup and IH cta at the bottom shouldn't be full-width like that https://github.com/mozilla/foundation.mozilla.org/issues/2900) https://foundation.mofostaging.net/en/opportunity/mozilla-information-trust-initiative/

**Comment by youriwims** [comment]
Let me know when this is good to go 👍

**Comment by alanmoo** [comment]
@youriwims Go ahead and remove the signup form from the opportunity template and model (probably in 2 different PRs), but don't delete the snippet itself. We'll re-use/adapt that soon for the banneredCampaignPage.
