### ISSUE TITLE
Unify button styles

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2905]
Based on @sabrinang @natalieworth's amazing work in https://github.com/MozillaFoundation/Design/issues/317

- [x] Design has been finalized
- [x] Link to original design ticket
- [x] Link to related ticket [n/a]
- [x] Link to Redpen [screen caps below]
- [x] Design changes been merged into the master Sketch file [see Style Guide file]
- [x] Desktop and mobile mockups are included 
- [x] Assets are included [n/a]
- [x] Hover state for elements are designed
- [x] Other states for elements are designed (e.g., error state for form) [n/a]

### Button class names
- [x] `.btn-normal` to ~~`.button-primary`~~ (`.btn-primary`)
- [x] `.btn-ghost` to ~~`.button-secondary`~~ (`.btn-secondary`)
- [x] `.btn-pop` to ~~`.button-pop`~~ (keep the name)

### Button Labels
- [x] text-transform: remove uppercase (we can't enforce sentence case in code and there will be exceptions like capitalizing names etc.)
- [x] letter-spacing: 0px (remove)

### Button Styles
![](https://assets.mofoprod.net/network/images/Screen_Shot_2019-03-26_at_3.44.40_PM.original.png)
- [x] **Button Primary Updates:**
color: $white
background: $blue
hover background: $dark-blue

- [x] **Button Secondary Updates:**
color: $black
background: none (transparent)
border: 2px solid $black
hover background: $black 
hover color: $white

- [x] **Button Pop Updates:**
background: none (can this be transparent with the shadow?)
hover: instead of it popping out, it presses in ([example](https://projects.invisionapp.com/share/8QR4EO1E5TG#/screens/353450240_Button_Test))

### Dark Theme Button Styles
![](https://assets.mofoprod.net/network/images/Screen_Shot_2019-03-26_at_3.42.27_PM.original.png)

- [x] **Button Primary Dark Theme Updates:**
color: $white
background: $blue
hover background: $light-blue
hover color: $black

- [x] **Button Secondary Dark Theme Updates:**
color: $white
background: none (transparent)
border: 2px solid $white
hover background: $white 
hover color: $black

- [x] **Button Pop Dark Theme Updates:**
background: none (can this be transparent with the shadow?)
border: 2px solid $white
hover: instead of it popping out, it presses in ([example](https://projects.invisionapp.com/share/8QR4EO1E5TG#/screens/353450240_Button_Test))

### Button Arrangement
- [ ] Alignment: all left-aligned (exceptions support navigation or UI like .button-pop)
- [ ] Spacing: margin/padding unchanged and only primary button is full-width on mobile
- [ ] Order: if there are multiple buttons order by importance left to right

- [ ] Multiple buttons: always have them on separate lines with margin-bottom 8px spacing
![image](https://user-images.githubusercontent.com/2492510/55044632-5058ee80-4ff8-11e9-8a2c-90faa45415e0.png)

Buttons are also documented in UI components in wagtail: https://foundation.mozilla.org/en/docs/brand/design/ui-components/

**Comment by mmmavis** [comment]
Note:

1) after chatted with @sabrinang we have decided to keep the button class name prefix `btn-` (instead of `button-`) to align with Twitter Bootstrap's naming convention.

2) PR will not address things mentioned in "Button Arrangement" as they are more best practices for designer and content writers to follow.

**Comment by mmmavis** [comment]
Done! Follow-up ticket filed here: https://github.com/mozilla/foundation.mozilla.org/issues/2936
