### ISSUE TITLE
Update IH CTA Snippet to span width of body content

### ISSUE THREAD

**Issue by youriwims** [mozilla/foundation.mozilla.org#2909]
**Bug Description** 🐛 
Currently, the IH CTA Snippet doesn't line up with the primary body content and instead spans the full width of the page's parent container. So, we want to fix that.

**To Reproduce** 🌱 
1. Follow this [link](https://foundation.mozilla.org/en/opportunity/web-literacy/)
2. Scroll down to the bottom of the page.
3. Error: There you will see that the snippet spans the full width of the navigation and body content.

**Expected behavior** 🌟 
Fix: The snippet should only span the main body content. Per the example ⬆️, the snippet should always be the same width as the `Web Literacy - Overview` section.

_To-Do Checklist_ ✔️ 

- [x] Add field to `ModularPage` model
- [x] Update `settings_panel`
- [x] Include snippet template in `primary_page.html`
- [x] Test feature (If successful, add to all templates)

**Additional context** 📖 

Related Issue #2900 
[Reference Comment](https://github.com/mozilla/foundation.mozilla.org/issues/2900#issuecomment-476908641) ⬇️ 
> The IH Snippet should continue to appear on all the same pages it does now (all the /opportunity, /initiative, and /campaign pages) which means it would need to fit the width on pages that have nav and ones that don't, and pages with the "make narrow" checkbox checked or not checked. 
cc: @kristinashu

**Comment by kristinashu** [comment]
Beautifully detailed ticket!
