### ISSUE TITLE
Design search feature for fellow directory

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#2915]
The Pulse API can now handle search of profiles! Yay. It would great to add this feature to the fellow directory. 

 - Use case: Moz or a partner wants to find experts in topic-X to join a research project or present at a conference or comment on an article. Search includes all text in name, bio, location, affiliation.
 - MVP could be a search box that opens results over in pulse. Ideally though, we'd serve results directly on this page if it's not a big lift. 
 - If we can keep it simple, this would be a great feature to ship and share at all hands.  

Step 1: wireframe frontend (timebox to a day?)
Step 2: discuss requirements and constraints with Alan

cc @kristinashu to triage

**Comment by gideonthomas** [comment]
closing, no one has asked for this. can re-open when there is a need.
