### ISSUE TITLE
Bannered campaign page sub nav width

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2916]
Checking off "Narrowed page content:" checkbox should not change the width of the subnav.

Screen cap from prod:
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/1068783/55191193-bcedfd80-515e-11e9-8af2-f3449a9f544d.png">

It should be like the about page.
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/1068783/55191269-f6bf0400-515e-11e9-8e4f-39be89abcbcb.png">

Can be grouped with https://github.com/mozilla/foundation.mozilla.org/issues/2769

cc @alanmoo @Pomax

**Comment by alanmoo** [comment]
Isn't the plan to get rid of the "narrowed page content" functionality altogether?

**Comment by alanmoo** [comment]
@mmmavis This is a little gross because the initial stab at this page was a pure Frankensteining of Primary and Campaign pages. Let's make this a priority today/tomorrow.

@kristinashu is it safe to say all BanneredCampaignPages should have content at the same width as the primary pages, unless there's a petition? Is the content still the same width, just with the petition added?

**Comment by kristinashu** [comment]
Just to be clear, it's only the subnav that isn't right. The main page is acting as expected.

**Comment by kristinashu** [comment]
> Isn't the plan to get rid of the "narrowed page content" functionality altogether?

That's part of a conversation we haven't really had yet... we would like to take the option away from users but that would be complicated. Content on these types of pages should always be narrow (except for the pulse directory page).

> Is it safe to say all BanneredCampaignPages should have content at the same width as the primary pages, unless there's a petition? 

Yes, content should be the same with as primary pages when there's a petition (these have the "Narrowed page content:").

> Is the content still the same width, just with the petition added?

Content with a petition should behave the same as on a petition page:
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/1068783/55195492-efe9be80-5169-11e9-9926-9613266c49f1.png">

**Comment by alanmoo** [comment]
Ah, I missed that. Thanks. Then we probably need to abstract out the nav so it's not wrapped up in the body container. I'll let Mavis make that call though.
