### ISSUE TITLE
🌡 Bannered campaign page should have donation modal functionality

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2917]
**Describe the bug**
The BanneredCampaignPage should support donation modals just like the regular campaign page

**To Reproduce**
1. Sign a petition on a bannered campaign page
2. Observe there's no modal asking for a donation.
3. Observe there's no option to add that modal in the admin

**Expected behavior**
Visit a regular campaign page (like [this one](https://foundation.mozilla.org/cms/pages/315/edit/)) and notice that Donation Modal is a possible snippet, and it appears after signing the public petition.

**Comment by kristinashu** [comment]
Is this still missing? I see this after signing https://foundation.mozilla.org/en/campaigns/eu-misinformation-facebook/ Should there be something else?

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/1068783/56152481-a3272580-5f68-11e9-99a6-862e5aae54e5.png">

**Comment by alanmoo** [comment]
That’s not a bannered campaign page, it’s a regular campaign page

**Comment by kristinashu** [comment]
Ha right, woops!

**Comment by alanmoo** [comment]
I got confirmation from Will that we can attach the donation modals to the petition model, there's no concern about using the same petition in multiple places with different donation modals.

As part of this work, I'll first land a commit on production that allows me to manually re-link the donation modal used on a page directly to the petition itself (since there aren't that many, it's easiest to just do this manually). Then I'll follow up with a commit that removes the link from campaignPage to donationModal, and instruct the petition snippet to show the modal on submission, if present.

Sound reasonable @Pomax?

**Comment by Pomax** [comment]
@alanmoo as the last comment was from May 10th, how much has the work here changed (if it's still relevant at all?)

**Comment by alanmoo** [comment]
Still relevant, no change.

**Comment by alanmoo** [comment]
@Pomax Rather than taking this on, would it be efficient for you to identify what needs to be done so that someone else may be able to try it?

**Comment by Pomax** [comment]
This involves adding a donation chooser panel to the bannered campaign model (similar to the campaign model) and then making sure the template for the bannered campaign picks up on that (which might already be the case)

**Comment by alanmoo** [comment]
One of the things we've been talking about has been making the "thanks for signing" text a separate page. That may change how this gets executed, but I also don't know how long it's going to be until we get there. If it's as straightforward as adding that donation chooser, great, let's get this moving forward when we next work on this ticket. But if it ends up being more work than that, we might want to revisit the approach.

**Comment by alanmoo** [comment]
I'm going to close this and say that the path to this is making "thank you" page a separate URL. This helps us in many more ways than just using a modal.
