### ISSUE TITLE
Unnecessary margin below single-page campaign page header

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#2920]
Follow-up for https://github.com/mozilla/foundation.mozilla.org/pull/2919

Some unnecessary margin has been added to single page campaign page as side effect of [this](https://github.com/mozilla/foundation.mozilla.org/pull/2919/files#diff-e898d74f7a453781bf6b77c5a4fd1d01R41) (thanks for Percy for catching it). `mb-4` should only be there when menu is present.

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/2896608/55256320-094a4380-521a-11e9-94ec-ec5917ecbafd.png">

**Comment by mmmavis** [comment]
Since many components are shared between multiple page types (e.g., mini site menu, campaign, bannered campaign page, primary page... etc) there's no simple way to get rid of the extra margin without introducing changes to other pages. Gonna mark this "won't fix". /cc @kristinashu

**Comment by mmmavis** [comment]
@kristinashu Just realized we no longer have "won't fix" label. I'll just close this ticket then.

**Comment by kristinashu** [comment]
👍
