### ISSUE TITLE
Remove {% block html_content_classes %} from mini_site_name_space.html

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#2921]
https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templates/wagtailpages/mini_site_name_space.html#L20

It seems like `{% block html_content_classes %}` is not doing anything. I did a search through codebase for `html_content_classes` and this is the only result found.

/cc @Pomax to help verify

**Comment by Pomax** [comment]
yep, this should be entirely removable
