### ISSUE TITLE
Organize {% block content %} in modular_page.html

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#2922]
Two templates are currently extending `modular_page.html`
- [primary_page.html](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templates/wagtailpages/primary_page.html)
- [mini_site_name_space.html](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templates/wagtailpages/modular_page.html)

As [primary_page.html](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templates/wagtailpages/primary_page.html#L14-L36) rewrites `{% block content %}` entirely, this means default content in `modular_page.html`'s `{% block content %}` is purely for `mini_site_name_space.html`. Can we move this code from `modular_page.html` to `mini_site_name_space.html` & let `modular_page.html` just have an empty `{% block content %}{% endblock %}` to avoid confusion?

**Comment by alanmoo** [comment]
I think we should look at this a bit more holistically; I'm not sure `mini_site_name_space` needs to have any content at this point. I was talking to @Pomax about this a little while ago; I think he's going to set up a meeting next week.

**Comment by cadecairos** [comment]
Closing this issue due to its age, if this is work that we still want to do, please refile this with up to date information so that it can be put in the correct milestone with up to date estimates.
