### ISSUE TITLE
CODE_OF_CONDUCT.md isn't correct

### ISSUE THREAD

**Issue by Mozilla-GitHub-Standards** [mozilla/foundation.mozilla.org#2925]
**Your required text does not appear to be correct**

As of January 1 2019, Mozilla requires that all GitHub projects include this [CODE_OF_CONDUCT.md](https://github.com/mozilla/repo-templates/blob/master/templates/CODE_OF_CONDUCT.md) file in the project root. The file has two parts:

1. Required Text - All text under the headings *Community Participation Guidelines and How to Report*, are required, and should not be altered.
2. Optional Text - The Project Specific Etiquette heading provides a space to speak more specifically about ways people can work effectively and inclusively together. Some examples of those can be found on the [Firefox Debugger](https://github.com/devtools-html/debugger.html/blob/master/CODE_OF_CONDUCT.md) project, and [Common Voice](https://github.com/mozilla/voice-web/blob/master/CODE_OF_CONDUCT.md). (The optional part is commented out in the [raw template file](https://raw.githubusercontent.com/mozilla/repo-templates/blob/master/templates/CODE_OF_CONDUCT.md), and will not be visible until you modify and uncomment that part.)

If you have any questions about this file, or Code of Conduct policies and procedures, please reach out to Mozilla-GitHub-Standards+CoC@mozilla.com.

_(Message COC003)_

**Comment by Pomax** [comment]
@Mozilla-GitHub-Standards the "raw template file" link is a 404

**Comment by Pomax** [comment]
I'm also confused how https://github.com/mozilla/foundation.mozilla.org/blob/master/CODE_OF_CONDUCT.md and https://github.com/mozilla/repo-templates/blob/master/templates/CODE_OF_CONDUCT.md differ, given that they are literally the same text.

**Comment by hwine** [comment]
1) Sorry about the 404
2) The two CoC files are actually different, but you have to look at the raw text to see it. Your reporting link specifies a locale ``en-US``, the updated master one leaves the locale up to the user's browser to select.

**Comment by Pomax** [comment]
Ah, thanks.

It would be useful to update the bot to point out what the difference is (or, since including diffs in comments is more of a bugzilla than a github thing, have the bot also file a PR with a "fixes #...", which would make the diff more obvious?)

**Comment by hwine** [comment]
The challenge with that modified PR is that it is completely legit for folks to have modified the PR to add project specific information. I've opened mozilla/Mozilla-GitHub-Standards#8 to sort out a better approach. Please add any additional concerns you have there. Thanks!
