### ISSUE TITLE
Enable localization of "Intro" field on BanneredCampaignPages

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2941]
**Describe the bug**
The field labeled "Intro" on BanneredCampaignPage can't be localized. Let's make that possible.
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/1682681/55406561-508e4800-552a-11e9-9c1a-cea4489bd961.png">

**Comment by Pomax** [comment]
This is an inherited field from PrimaryPage, so we'd have to enable it for all primary pages. If that's fine then this should be a quick thing to do.

**Comment by alanmoo** [comment]
Yeah, that's good.

**Comment by Pomax** [comment]
accidentally landed the wrong code.
