### ISSUE TITLE
Add newsletter sign up button and form to nav

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2948]
## HOLD UNTIL DESIGN IS FINAL

Add newsletter sign up button to nav, update donate button, and add form.

- [ ] Add `Newsletter` button
- [ ] Update style of `Donate` button
- [ ] Mobile: `Newsletter` stays put while `Donate` button moves down below nav items
- [ ] Clicking on `Newsletter` button animates sign up form to open and page content slides down
- [ ] Clicking anywhere outside of the black form box animates the form to close
- [ ] Error/success/hover states should follow footer styles

**🗒  Design -> Dev Handoff Checklist**

- [ ] Design has been finalized
- [x] Link to original design ticket https://github.com/mozilla/foundation.mozilla.org/issues/2757
- [x] Link to related ticket _[n/a]_
- [x] Link to Redpen https://redpen.io/p/uvd561910fde4f4bc9
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Assets are included _[n/a]_
- [x] Hover state for elements are designed
- [x] Other states for elements are designed (e.g., error state for form)

Final comps:

![Home Nav@2x](https://user-images.githubusercontent.com/1068783/55438762-65cd9b80-5557-11e9-9d2e-9b4db6f3ce11.jpg)

Newsletter opens on click:
![Nav Open@2x](https://user-images.githubusercontent.com/1068783/55438763-66663200-5557-11e9-82c1-59a913771732.jpg)

Buttons prioritized on mobile:
<img width="317" alt="image" src="https://user-images.githubusercontent.com/1068783/55438787-767e1180-5557-11e9-8d57-e85aa8cacec6.png">

Newsletter opens on tab (closing by clicking on anywhere in nav bar or clicking Sign up button):
<img width="319" alt="image" src="https://user-images.githubusercontent.com/1068783/55438771-6cf4a980-5557-11e9-8876-66e148901c11.png">

**Comment by mmmavis** [comment]
@youriwims please don't work on this until the sign up component work that Pomax and I are working on is merged first.

**Comment by kristinashu** [comment]
Also please wait for design to be finalized!

**Comment by kristinashu** [comment]
Sorry but it's looking like this ticket was premature! Anil wants to look into the working a little more. @youriwims I'm going to unassign you and turn this into a design ticket, sorry.

### Things for design to do:
- get analytics from Will so we know how much the current donate button is bringing in [Kristina to do]
- benchmark site that have more movement orientated copy [Kristina & Rebecca to do]

**Comment by kristinashu** [comment]
Numbers from Will for the last year: 688 donations for $19,525
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/1068783/55584663-99383380-56d9-11e9-93da-d1c4b7b85622.png">

Compared to visits: 
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/1068783/55584731-cdabef80-56d9-11e9-8f73-577010902a31.png">

**Comment by kristinashu** [comment]
@beccaklam I've added some benchmarks [here](https://docs.google.com/presentation/d/1Yppt2ZUK3NVXhQ5OtB2vNctQl3uPo80bIYAtF5D3MlE/edit?usp=sharing), please add your thoughts or more examples!

**Comment by kristinashu** [comment]
Opened up dev implementation ticket https://github.com/mozilla/foundation.mozilla.org/issues/2994 and tracking/testing ticket https://github.com/mozilla/foundation.mozilla.org/issues/2995 (@beccaklam if interested, maybe you could take the lead on the tracking/testing one?).
