### ISSUE TITLE
Content and design review of wagtail pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2949]
We need a way to review pages that have been created or updated by staff to review content for typos, broken links... and to make sure it follows our brand standards and best practices.

Comms team has also flagged a similar need for our blog posts. Note from Anil:
> I spoke with Lotta and Juan about blogs today, and they’re generally aligned with us moving forward. They were cautious about turning the feature on for everyone without a strategy/process in place. Perhaps more so process - how would we ensure every blog posted is copyedited? How would we ensure blogs were on theme? I tried to emphasize at least initially we wouldn’t be opening it up to everyone.

I wouldn't want to block staff from updating or creating pages but at the very least we need a way to see what pages have recently been updated or created so we can flag them for review. Although perhaps blog posts would need more moderation, if possible.

@alanmoo @xmatthewx thoughts?

**Comment by alanmoo** [comment]
I believe we would be able to require moderation for blog posts. For other pages, There should be a way to tap into the Wagtail API to expose "recently updated pages by anyone" on the admin homepage. @Pomax Does that sound right?

**Comment by Pomax** [comment]
There is moderation built into wagtail, it's probably just a matter of learning to use that.

**Comment by cadecairos** [comment]
This doesn't seem engineering related.

@kristinashu @anilkanji : this needs triage.

**Comment by xmatthewx** [comment]
To use moderation, we'd need to make sure we're using author roles properly, so not everyone could hit publish. Beyond that, yes, it's likely a roles and process question for Lotta and Anil. 

And... in our last meeting with Torchbox, I believe they mentioned a publishing workflow they're developing with a client that may make it into the core build. If so, that would be more feature reach than simple moderation.

**Comment by cadecairos** [comment]
Closing this issue due to its age, if this is work that we still want to do, please refile this with up to date information so that it can be put in the correct milestone with up to date estimates.
