### ISSUE TITLE
Our page spawns an hscrollbar on Windows at <=768px widths

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2952]
Chrome: 

![image](https://user-images.githubusercontent.com/177243/55490365-83971100-55e8-11e9-875b-2332a295d6c4.png)

Firefox:

![image](https://user-images.githubusercontent.com/177243/55490409-8e51a600-55e8-11e9-9d9b-046e0a2ac1d1.png)

**Comment by cadecairos** [comment]
Closing this issue due to its age, if this is work that we still want to do, please refile this with up to date information so that it can be put in the correct milestone with up to date estimates.
