### ISSUE TITLE
Make location display conditional on profile cards

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#2958]
Profiles include an icon even when location is empty (profile by id  streamfield component). 
 

**To Reproduce**

1. Go to https://foundation.mozilla.org/en/docs/how-do-i-wagtail/profiles-from-pulse/
1. Scroll down and compare Peter and Luca
4. See placemarker by Luca's empty location field. 

**Expected behavior**
When profile has no location, there should be no icon and no extraneous space. 

**Screenshots**

<img width="861" alt="image" src="https://user-images.githubusercontent.com/53411/55513184-1e1c4200-5633-11e9-8b63-8b32d5140a04.png">

**Comment by youriwims** [comment]
Should the bio text be moved up and fill that space if no location is present? @xmatthewx @kristinashu

**Comment by kristinashu** [comment]
Yes please! There's an example in the comp (Brett) https://redpen.io/me6c690075cd81cd6f
