### ISSUE TITLE
Change how we turn button and text into dark theme version

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#2959]
Related to the recent button standardization PR that I landed.

Currently to make a dark themed button or text we simply apply `dark-theme` to the element. e.g., 

```html
<h6>regular theme heading</h6>
<h6 class="dark-theme">dark theme heading</h6>
```

If we have a section with dark background and we want to make every element in that block to be on dark theme, we will have to apply `dark-theme` class to every single element. Imagine doing that for 20 elements 🙈 ...

I want to propose that we change the way we create dark theme elements. Instead of adding `dark-theme` class to individual elements, we should have a wrapper with class `dark-theme` and have SCSS to make everything in that wrapper become their dark theme version (e.g., text should be white instead of black etc)

```html
<h6>regular theme heading</h6>

<div class="dark-theme">
  <h6>dark theme heading</h6>
  <a>dark theme anchor</a>
</div>
```

This way we can simply toggle regular mode and dark theme mode of a section by toggling `dark-theme` class on the wrapper element. 

@Pomax @youriwims @sabrinang I would love to hear your thoughts.

**Comment by sabrinang** [comment]
Sounds good Mavis so it's less redundant using dark-theme for each separate element 👍  I will defer to you devs for your expertise here

**Comment by youriwims** [comment]
I think this is a great idea and makes for much more efficient code that won't need to be refactored in the near future.

**Comment by mmmavis** [comment]
Blocked by #2998 

To reduce code merging complexity with the already gigantic PR #2998, let's wait for that to merge first before tackling this ticket.
