### ISSUE TITLE
Enable localization of “Overview” navigation tab in campaign pages

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#2960]
It looks like the “Overview” tab label can’t be localized (or I can’t find it in Wagtail) on https://foundation.mozilla.org/en/campaigns/eu-misinformation/ it would be great to add a field for this

![image](https://user-images.githubusercontent.com/1294206/55548036-8702c900-56ca-11e9-8634-afd1127d5459.png)

**Comment by mmmavis** [comment]
@Pomax @alanmoo The word `Overview` is currently hardcoded in `utils.py` Is our approach for this ticket to first have a map of localized `Overview` strings, and render the matching string according to the locale?

**Comment by alanmoo** [comment]
That's probably the most straightforward way to do this and I'm fine with it, though I could see it evolving in the future.

**Comment by mmmavis** [comment]
@TheoChevalier since we have to hardcode this for now, do you mind providing me with the list of localized strings for "Overview" so I can add it to the codebase?

**Comment by TheoChevalier** [comment]
Hey @mmmavis, this page was only translated in de, es, fr, so let’s proceed with this for now:

de: "Übersicht"
es: "Síntesis"
fr: "Vue d’ensemble"

I’m tracking the need for pl & pt, and will update the file directly once it’s ready.

**Comment by alanmoo** [comment]
This is part of the broader structure of our pages, so we should likely have the pl & pt strings even if they're not in use on this particular campaign.

**Comment by TheoChevalier** [comment]
Of course! I’m just saying I don’t have those translations yet, since this string was exposed as part of the misinfo hub.

**Comment by TheoChevalier** [comment]
And let’s not block on those missing translations, if you need a value for pt/pl, let’s use the English string for now, and I’ll replace it with translations later

**Comment by mmmavis** [comment]
Talked with @TheoChevalier (see https://github.com/mozilla/foundation.mozilla.org/pull/3666#discussion_r325936276) about the required work... and it turned out that Pomax and Theo's [template localization PR](https://github.com/mozilla/foundation.mozilla.org/pull/3529) actually has this ticket covered as well.

@TheoChevalier I'm going to set you as ticket assignee since you were the one added the fix to the template localization PR. 👍

**Comment by alanmoo** [comment]
Since this is covered by the other PR, let's close this.
