### ISSUE TITLE
Brainstorm: Show different Favicons for Staging and Prod

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2961]
I feel like it might be useful if the tab icon for staging and production (maybe review apps too?) was different somehow. That way we can take a glance at our open tabs and know where staging is to test some data changes vs "don't break this" in production. Am I alone on this or do others agree? 

@mozilla/mofo-eng @mozilla/mofo-design

**Comment by alanmoo** [comment]
@kristinashu Should we just use the Mozilla logo with a different color or something?

**Comment by kristinashu** [comment]
Yeah maybe we could do the inverse.

**Comment by sabrinang** [comment]
Here are ideas to help distinguish the tabs: 
![favicon-ideas@2x](https://user-images.githubusercontent.com/2492510/149404990-015be68b-5931-4066-bd68-2644c032731e.jpg)

- icon color: change favicon so it's distinguishable at a glance _(it'll be for internal use only so less concerned about if color is improper application use of the logo)_
- title: adding short prefix such as [S] for staging and [RA] for review app
- production would be left as is

@kristinashu R?

**Comment by kristinashu** [comment]
Love this R+

I like how all three are different in both color and text.

**Comment by kristinashu** [comment]
😂

**Comment by sabrinang** [comment]
Thank you all for your enthusiasm on this classic ticket lol! 🥲
I exported favicons as SVGs [here](https://drive.google.com/open?id=1aJFhen5r-3dWCDoefysvbCtzVDAAbR8K&authuser=sabrina%40mozillafoundation.org&usp=drive_fs) and filed the implementation ticket here: https://github.com/mozilla/foundation.mozilla.org/issues/8109 — closing!
