### ISSUE TITLE
Enhance landing page inheritance for easier author experience

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#2964]
In authoring a campaign that uses the new landing page template, it's a wee bit of a pain to select the banner image on every single child page. Would it possible for child pages to inherit their parents banner image if nothing is specified for that specific page? And only fall back to generic b&w if neither have an image?

Let's discuss and then file a real ticket @alanmoo @kristinashu

**Comment by kristinashu** [comment]
Yes, this would be amazing!

I've also wondered if the child pages could inherit the OG content from parent page too?

**Comment by alanmoo** [comment]
The original request should be possible. 

@kristinashu - It looks like OG Text does inherit currently, but not images. I'm not sure if that's an oversight in the implementation of #2347 or a bug. @cadecairos Can you comment on that part?

**Comment by kristinashu** [comment]
@Pomax any thoughts/insights on this?

**Comment by Pomax** [comment]
It should be possible to fall back to the parent page's data in absence of "local" data. I would estimate a 2 for figuring out how much work the implementation would be, and then have a separate issue to do the implementation work? I recall we already had fallthrough for _something_ in our existing models, but I can't remember where off the top of my head.

**Comment by Pomax** [comment]
@kristinashu is this something we still want to do?

**Comment by kristinashu** [comment]
@Pomax yes, this would still be a very valuable feature to have!
