### ISSUE TITLE
[planning] a cleaner inheritance model for django models/templates and CMS page types

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2965]
This is a long-term tracking/planning issue around "what the ideal model/template situation for our page types would be", and how we can work towards realising that particular information architecture.

Let's start with a graph of an initial "this feels reasonable" pass:

[Proposed Foundation Site Template April 2019.pdf](https://github.com/mozilla/foundation.mozilla.org/files/3048164/Proposed.Foundation.Site.Template.April.2019.pdf)

/cc @alanmoo @pomax @mmmavis @youriwims

**Comment by cadecairos** [comment]
Closing this issue due to its age
