### ISSUE TITLE
Add "edit this page" functionality for logged in users

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2967]
When I'm looking at a published page and I want to edit it, there are way too many steps involved. Can we add a link/route/keyboard shortcut to allow logged in users to jump directly to editing that page?

@Pomax what's possible?

@kristinashu any preference?

**Comment by kristinashu** [comment]
This would be great to have! Could do a bar across the top similar to the Draft Page but with a message (linked text) to Edit Page.
