### ISSUE TITLE
percy seems to load images and webfonts unreliably

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2988]
immediate fix: longer wait before taking the snapshot

long term fix: figure out how to actually know that all images and webfonts have (1) downloaded and are (2) correcetlydisplayed, before taking a screenshot, even if the _content_ may not be "correct"

**Comment by mmmavis** [comment]
Worth checking this again as Percy recently made huge improvement around loading fonts and images.

**Comment by mmmavis** [comment]
Closing. This seems to be resolved as I haven't seen any false postive flags for webfont in past few weeks.
