### ISSUE TITLE
consider adding more information to the newsletter signup 

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2991]
in order to better serve users who want to be signed up to our newsletters, https://github.com/mozmeao/basket/issues/152 points out that we can add additional information to make sure newsletters are "tailored" - the main fields for this are `language` and `format`, as well as possible `country`

Of course, getting this information would require some thinking about whether that is information that can be gathered by our signup components without becoming a full form, so our initial pass will simply pass in the email address as currently designed for, but we can think about what we want to know, given that "custom tailoring" is something we can do.

**Comment by Pomax** [comment]
example of mozilla's form: https://www.mozilla.org/en-US/newsletter/

![image](https://user-images.githubusercontent.com/177243/55837150-5a3d2000-5ad5-11e9-85db-36fc8d89ec50.png)

**Comment by kristinashu** [comment]
@Pomax is this still relevant now that we've added Country and Language drop downs to the form?
