### ISSUE TITLE
Add newsletter sign up button and form to nav

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2994]
### Add newsletter sign up button to nav, update donate button, and add form.

- [x] Add `Newsletter` button
- [x] Update style of `Donate` button ([icon-heart.svg.zip](https://github.com/mozilla/foundation.mozilla.org/files/3064965/icon-heart.svg.zip)) (hover: dark blue #0d10bf)
- [x] Mobile: `Donate` stays put while `Newsletter` button moves down below nav items
- [x] Clicking on `Newsletter` button animates sign up form to open and page content slides down
- [x] Clicking anywhere outside of the black form box animates the form to close
- [x] Form error/success/hover states should follow footer styles
- [x] Keep Donate UTM
- [ ] Add google event to Newsletter button (clicks and actual signups)
- [ ] Add source tag to Newsletter button for filtering purposes so Will can look up how many signups came from that button (@WillatMozFdn @Pomax please check if I worded this correctly ...)

**🗒  Design -> Dev Handoff Checklist**

- [x] Design has been finalized
- [x] Link to original design ticket #2757 #2948 
- [x] Link to related ticket https://github.com/mozilla/foundation.mozilla.org/pull/2956
- [x] Link to Redpen https://redpen.io/p/uvd561910fde4f4bc9
- [x] Design changes been merged into the master Sketch file _(Home page in Foundation site file)_
- [x] Desktop and mobile mockups are included
- [x] Assets are included _(heart icon above)_
- [x] Hover state for elements are designed
- [x] Other states for elements are designed (e.g., error state for form)

Final comps:
![Home Nav Copy@2x](https://user-images.githubusercontent.com/1068783/55899124-ebb19e00-5b78-11e9-8499-7d8772f7117a.jpg)

Hovers:
![Home Nav Hovers@2x](https://user-images.githubusercontent.com/1068783/55899140-f409d900-5b78-11e9-9ca9-da85b88047bc.jpg)

Newsletter opens on click:
![Nav Open Copy@2x](https://user-images.githubusercontent.com/1068783/55899157-fc621400-5b78-11e9-9333-5f5fbebc27e7.jpg)

Buttons prioritized on mobile & Newsletter opens on tap (closing by clicking on anywhere in nav bar or clicking Sign up button):
<img width="746" alt="Screen Shot 2019-04-10 at 10 10 42 AM" src="https://user-images.githubusercontent.com/1068783/55899187-0d128a00-5b79-11e9-891f-fe1595f6cd2e.png">

cc @mmmavis @youriwims @beccaklam

**Comment by beccaklam** [comment]
Also not sure about the use of usertesting.com. The UX/UI seems straightforward enough, and the above tests may be able to tell us enough about whether the design is effective. I can do some quick in person tests though and see how people do. 
Possible scenarios:

- "You sign a campaign and want to learn more about the company behind the petition. Where do you go? Peruse their site. Now you want to stay up to date with what this company does. What do you do?"
-
-

**Comment by kristinashu** [comment]
@beccaklam I think that comment was meant for https://github.com/mozilla/foundation.mozilla.org/issues/2995?

**Comment by mmmavis** [comment]
@youriwims reminder: you might wanna wait till PR https://github.com/mozilla/foundation.mozilla.org/pull/2998 is merged first 👍 .

**Comment by youriwims** [comment]
Sounds good =)

**Comment by youriwims** [comment]
@kristinashu what did you mean by 'UTM' in 'keep Donate UTM'?

**Comment by kristinashu** [comment]
@beccaklam will be adding more info about the UTMs and tracking. We need to carefully track how many clicks/donations/signups we're getting.

**Comment by beccaklam** [comment]
@youriwims I added it to the checklist!

**Comment by youriwims** [comment]
@kristinashu how should I handle the nav/form layout at medium screen sizes? Should it remain like mobile?

**Comment by kristinashu** [comment]
@youriwims thanks for asking! I did a quick mockup and looks like it still fits nicely at >768px wide (see comp below) but will probably have to match mobile for anything narrower than that.

<img width="768" alt="image" src="https://user-images.githubusercontent.com/1068783/56386479-b7705a00-61d6-11e9-9d5b-94c8e531adb9.png">

**Comment by youriwims** [comment]
Awesome, thanks!...I don't foresee any issues with this. I'll let you know if anything 👍

**Comment by youriwims** [comment]
![Screen Shot 2019-04-18 at 4 06 56 PM](https://user-images.githubusercontent.com/36484608/56388054-05e02180-61f4-11e9-9611-aab2f4d98fa0.png)

Just checked prod and at 576px, the logo changes to the large Moz logo. Should I keep that or follow your comp above and keep the small logo?

**Comment by kristinashu** [comment]
Oh sure, large logo works!

**Comment by youriwims** [comment]
@kristinashu is it possible we can add some way to exit i.e. an 'x' to this form?...or there's really no way for the user to exit the form, especially at mobile.

**Comment by kristinashu** [comment]
Users can click anywhere outside of the black form box (logo, hamburger, white bar...) to close it. I don't think anything extra is need to desktop or tablet since it isn't very intrusive but we could add something to mobile. An 'x' at the top left or right feels busy like there is an overwhelming amount of options but we could add a `No thanks` below the Sign up button. Clicking it should return the user to the screen they were previously on. 

<img width="319" alt="image" src="https://user-images.githubusercontent.com/1068783/56839666-714f7200-6838-11e9-94de-786a7c0ee127.png">

**Comment by kristinashu** [comment]
Via user testing we can decided to use new copy #3161:
- [ ] Button text: `Join us`
- [ ] Body text: 
`Protect the internet as a global public resource.`
`Join our email list to take action and stay updated!`

**Comment by gideonthomas** [comment]
@mmmavis is this still in progress (are you actively working on it)? If not, can you move it to Up Next?

**Comment by mmmavis** [comment]
This is on staging now! 

From the ticket description looks like there are still two todos left:

> - [ ] Add google event to Newsletter button (clicks and actual signups)
> - [ ] Add source tag to Newsletter button for filtering purposes so Will can look up how many signups came from that button (@WillatMozFdn @Pomax please check if I worded this correctly ...)

---

Form on nav uses the same "sign up" component that we use for other places on the site (e.g., footer, bannered campaign page). There are two GA event associated with this "sign up" component

```js
ReactGA.event({
      category: `signup`,
      action: `form focus`,
      label: `Signup form input focused`
    });
```
What else do we need to do to mark this done? 👀 

```js
ReactGA.event({
      category: `signup`,
      action: `form submit tap`,
      label: `Signup submitted`
    });
```

1. 
2.

**Comment by gideonthomas** [comment]
@xmatthewx ^

**Comment by xmatthewx** [comment]
I'm guessing this is about source on button action getting passed to Salesforce. Not a GA thing. Ask @alanmoo?

**Comment by alanmoo** [comment]
From a convo with Will and Steph: For newsletter signups, we should send along the source URL as the base URL without all the query params, as having more data in Salesforce makes things harder to parse.

**Comment by xmatthewx** [comment]
@mmmavis - do you need any further info on this? if so, let's chat on slack in mofo-production.

**Comment by xmatthewx** [comment]
Those GA categories and action look good. If we could add position to the Label to identify where it shows up, that would be great.  For example `Signup submitted from Footer` OR form `from Header`. If it's not possible, we will survive without it!

**Comment by mmmavis** [comment]
I'm gonna mark this done and open two separate tickets instead as they affect to the shared sign up component on the site and not just the form on the nav.

1. GA Event (based on this [comment](https://github.com/mozilla/foundation.mozilla.org/issues/2994#issuecomment-517395655)): (if possible) add position to the Label to identify where it shows up.  For example `Signup submitted from Footer` OR form `from Header`.
2. Source URL sent to Salesforce (based on this [comment](https://github.com/mozilla/foundation.mozilla.org/issues/2994#issuecomment-516997473)):  For newsletter signups, we should send along the source URL as the base URL without all the query params, as having more data in Salesforce makes things harder to parse.
