### ISSUE TITLE
Fellowships Directory layout at tablet width

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3001]
@sabrinang has suggested a better card layout for the browser width of around 760-980px. Instead of the bio copy being really narrow, the copy should go below the pic (like on mobile).

Comp: https://redpen.io/ge7f4beac4f1723042

![Medium (≥768px) @2x](https://user-images.githubusercontent.com/1068783/55919691-cbe79d80-5bab-11e9-816c-d15ca4856e34.jpg)

Screen cap from prod:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/1068783/55919733-eb7ec600-5bab-11e9-936e-dea07c3ee92f.png">

cc @youriwims

**Comment by youriwims** [comment]
I can definitely do this but, all of the images have to be cropped to a square and some of the images haven't been cropped yet. When do you think this can be done @kristinashu  😸 ?

**Comment by kristinashu** [comment]
Ooooh right that! Which ones aren't square? I just had a quick look at it seemed like they were all miraculously square.

**Comment by youriwims** [comment]
I'm look at them at the given tablet widths, 760-980px:

_2019_
Caroline Sinders , Danae Valentina , Daniela Saderi,  Kadija Ferryman , Renee DiResta, 
Stefania Koskova 

_2018_
An-Me Chung, Julia Kloiber , Peter Bihr , Sarah Kiden

**Comment by kristinashu** [comment]
Ok I've copped all of those!

Few notes:
- @sabrinang to make sure all MozFest profiles are square
- there is a long term fix chat happening here https://github.com/mozilla/network-pulse-api/issues/458
- but maybe @mmmavis has some other short term fix ideas
