### ISSUE TITLE
Remove FigureBlock2

### ISSUE THREAD

**Issue by youriwims** [mozilla/foundation.mozilla.org#3003]
**Describe the bug**
It doesn't appear that `FigureBlock2` is currently in use on staging or prod and therefore, should be removed. This is a follow-up to #2999.

**To Reproduce**
1. Go to `/network-api/networkapi/wagtailpages/customblocks.py`
2. Line 106 still has unused `FigureBlock2` class.
3. Verify that it is not in use by:
- Searching the block inventory on staging and production
- Searching the codebase for the class

**Additional context**
Related PRs/Issues #2696 , #2760 , #2773 , #2782 , #1902

**Comment by harshs14** [comment]
@alanmoo can I take this as it seems no one is working on it?

**Comment by alanmoo** [comment]
Sure. I checked production, it's not in the block inventory list, so it should be safe to remove.
