### ISSUE TITLE
Fellowship directory - use flexbox instead of CSS grid

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#3004]
Upcoming directory related tickets: #2958 #3001 

(It'd better if we tackle this ticket first.)

---

There are quite a bit of arbitrary / magic numbers in `profiles.scss` ([existing code](https://github.com/mozilla/foundation.mozilla.org/blob/master/source/sass/wagtail/profiles.scss#L18-L29) & [in PR](https://github.com/mozilla/foundation.mozilla.org/pull/2997/files#diff-a7e457c11566b243d750e6a6acd87ad7)). It also seems like new sets of magic numbers have been added to the codebase every time we introduce minor design adjustment. This makes me wonder if CSS grid is the most suitable system to use here. From the [mockups](https://redpen.io/me6c690075cd81cd6f) it seems like design could most likely be easily implemented using flexbox without much mental math calculation involved. @Pomax @youriwims I don't know a lot about CSS grid so I'm curious if there's something specific about CSS grid that we wanna use and cannot be achieved using flexbox?

Content in each card is different so forcing the same grid cell height and width across all cards doesn't seem like the right solution (e.g., let the `bio` section always take x% of the card's height). This results in unpredictable sizing & spacing for sections in each card. 

### Few examples (screencap taken on production):

1. The two name sections have different width, height, and spacing to top border of the card. (**Expected: name section should have same width and spacing/margin across all cards.**)
2. The two social media sections have different width and height. (**Expected: dimension of this section should stay the same across all cards**)

<img width="1083" alt="Screen Shot 2019-04-11 at 1 27 10 AM" src="https://user-images.githubusercontent.com/2896608/55972366-39411000-5c38-11e9-9825-d86229bf15ce.png">

**Comment by youriwims** [comment]
This specific container you're mentioning _is_ using Flexbox. CSS Grid is only being used here to compartmentalize each card which you'll see is basically equal on each card depending on the content that's within it. In addition, the primary reason I went with the grid is because it allowed us to easily move the bio content below the image at mobile which couldn't easily be done with flexbox. Off the top of my head, the best solution here could be to set a min-width for the social media container, to avoid this issue with longer names between 991px - 1200px.

Below, you'll see the the dashed lines that represent where the grid is actually being used:
![Screen Shot 2019-04-11 at 3 39 32 PM](https://user-images.githubusercontent.com/36484608/55987751-3104c700-5c70-11e9-86cc-2c0f50e39ff6.png)

Whereas, here you'll see where flexbox is being used
![Screen Shot 2019-04-11 at 3 41 55 PM](https://user-images.githubusercontent.com/36484608/55987822-5e517500-5c70-11e9-948a-c1bd3a56824d.png)
![Screen Shot 2019-04-11 at 3 42 06 PM](https://user-images.githubusercontent.com/36484608/55987840-63162900-5c70-11e9-9938-b6cf0c847df8.png)

I'm open to other suggestions including how to better implement flexbox here to fix the issue—let me know.

**Comment by mmmavis** [comment]
Thanks for the detailed explanation and screencaps. Those were very helpful! @youriwims 👍 

I don't wanna propose for huge implementation changes. So I guess my main questions are - with the current CSS grid + Flexbox implementation that we have in place, is it possible that we can polish things up so that

1. width and spacing of each mini section in each card is consistent across all cards (height should grow to fit content)
2. we can avoid using arbitrary numbers in the `profiles.scss` file, especially

```SCSS
// is this equivalent to allocating 40% of the free space to first row and 60% to the last row?
grid-template-rows: 0.5fr 0.75fr;

// is this equivalent to allocating 31.03448276% of the free space to first column and 68.96551724% to the last column?
grid-template-columns: 0.9fr 2fr;

...

// is this equivalent to allocating 25.92592593% of the free space to first row and 74.07407407% to the last row?
grid-template-rows: 0.35fr 1fr;

// is this equivalent to allocating 31.0344827586% of the free space to first column and 68.9655172414% to the last column?
grid-template-columns: 0.9fr 2fr;

**Comment by mmmavis** [comment]
For the wrapping social icons issue, you can probably fix it by simply adding `flex: 1;` to `.meta-block`. Ideally we want to **avoid setting min/max width/height** where we can as it will require us to manually update that value when content in that section changes (e.g., if we decide to change the size of the icons or if we decide to add another icon to it)

Disclaimer: I didn't test my code suggestion locally so I could be wrong. 😂

**Comment by youriwims** [comment]
> I don't wanna propose for huge implementation changes. So I guess my main questions are - with the current CSS grid + Flexbox implementation that we have in place, is it possible that we can polish things up so that
> 
>  1. width and spacing of each mini section in each card are consistent across all cards (height should grow to fit content)

The width and spacing of each mini section _is_ currently consistent and grows to fit the content. (See my [initial example](https://github.com/mozilla/foundation.mozilla.org/issues/3004#issuecomment-482280947) displaying the grid expanding to fit Caroline's longer bio content in comparison to  Chukwuyere's bio that's visibly shorter). It's doing this all while maintaining the overall layout specified by Bootstrap.
>  2. we can avoid using arbitrary numbers in the `profiles.scss` file, especially

I don't want to get cheesy 🧀 , but this this is literally the magic ✨ of css grid and why it's so useful in creating and achieving very specific and/or complex layouts. The `fr` unit means a fraction or part of the available space, but also takes into account many other things that you can read more about [here](https://css-tricks.com/introduction-fr-css-unit/) 😊 . For generally simpler layouts, most use values like `0.5fr`,`1fr`, and`2fr` but the more comfortable you get with css grid, you can start using more unique/exact `fr` values like the ones I've used. [Here](https://labs.jensimmons.com/2017/01-011B.html) you can inspect the grid in the dev tools and see how they've used unique values to create this complex grid layout which in a sense is how I looked at creating the directory cards to compartmentalize the content within it.

I definitely recommend checking out Jen Simmons' [website](https://labs.jensimmons.com/); she has a lot of cool examples and approaches to using the grid to your advantage for creating layouts or doing things that may be out of the scope of flexbox and bootstrap. [This](https://css-tricks.com/snippets/css/complete-guide-grid/) helped me understand css grid when i first started learning it 👍 .

_Btw_ `flex:1` on `.meta-block` worked great—thanks!

**Comment by mmmavis** [comment]
@youriwims I know just the basics of CSS grid. Thanks for the links though - they are helpful! I noticed there were/are some small bugs here and there so I thought they might be CSS grid related. To be honest I'm a little lost now but if everything works as expected design wise let's just stick with the existing system. 

I know with CSS grid we will have to deal with interesting numbers. Would it be possible if we can change the numbers used for fellowship directory to something easier for other devs to follow? Or at least come up with a convention so in the future we can ensure numbers used in CSS don't seem as magic and arbitrary?

I'm curious how the number were picked in `profiles.scss `, for example

- `grid-template-rows: 0.5fr 0.75fr` is essentially the same as `50fr 75fr`, `2fr 3fr`, `1fr 1.5fr`, ... etc. Is fraction number representation more conventional?

- `grid-template-rows: 0.35fr 1fr;` and `grid-template-columns: 0.9fr 2fr;`... Was there a particular reason why we used `0.35fr 1fr`(and not its equivalent `0.7fr 2fr`) and `0.9fr 2fr`(and not its equivalent `0.45fr 1fr`)?

- Were these number chosen based on design specs? e.g., for `grid-template-columns: 0.9fr 2fr;` -- we specifically want the first column have 9/29 of the free space and the 2nd column have 20/29 of the free space?

**Comment by youriwims** [comment]
> grid-template-rows: 0.5fr 0.75fr is essentially the same as 50fr 75fr, 2fr 3fr, 1fr 1.5fr, ... etc. Is fraction number representation more conventional?

not sure what you mean by that question, but yes those are all equivalent 😸 However, it tends to be the norm in CSS Grid to use smaller `fr` units i.e. `4fr` and below. (note: you can also use percentages and pixels with `fr` units).

>grid-template-rows: 0.35fr 1fr; and grid-template-columns: 0.9fr 2fr;... Was there a particular reason why we used 0.35fr 1fr(and not its equivalent 0.7fr 2fr) and 0.9fr 2fr(and not its equivalent 0.45fr 1fr)?

there's no particular reason why I picked  0.35fr vs 0.7fr as in this case, they're exactly the same. like i said previously ☝️, css grid tends to use smaller numbers, so I always go with the fraction reduced to its lowest terms _in a sense_ without making the number too ridiculous...tbh this sort of thing is devs' preference...truthfully, there's nothing wrong with either option,again, it just comes down to preference.

>Were these numbers chosen based on design specs? e.g., for grid-template-columns: 0.9fr 2fr; -- we specifically want the first column to always have 9/29 of the free space and the 2nd column have 20/29 of the free space?

Not too sure how you came up with these fractions, but if I'm understanding correctly yes, I built the grid according to the design specs and explicitly told element each element which cells I want it occupy and when.

**Comment by mmmavis** [comment]
Here's my lengthy reply 😅 . We can chat on Vidyo if you have more questions.

---


> there's no particular reason why I picked 0.35fr vs 0.7fr as in this case, they're exactly the same. like i said previously ☝️, css grid tends to use smaller numbers, so I always go with the fraction reduced to its lowest terms in a sense without making the number too ridiculous...tbh this sort of thing is devs' preference...truthfully, there's nothing wrong with either option,again, it just comes down to preference.

I understand devs have their own preference. But since we are working on a collaborative project we would want to prioritize "making the code easier for other people to understand" than personal preference. Reducing numbers to their lowest terms is cool but there are already inconsistency happening in your code. Like what I pointed out in my previous comment - in one line you used `0.35fr 1fr` and another you used `0.9fr 2fr` (which should've been reduced to `0.45fr 1fr` to avoid inconsistency). That's why in my previous comment I suggested setting up a "convention/system" that everyone **can and should** follow, rather than making numbers look pretty for the sake of making them pretty.

> Not too sure how you came up with these fractions

These numbers came from [your Profile card updates sans location PR](https://github.com/mozilla/foundation.mozilla.org/pull/2997/files). The reason why I keep mentioning numbers being **magical/arbitrary** is because these number combos generate odd ratios that are unlikely "by design".

Taking `grid-template-columns: 0.9fr 2fr;` from the PR as one example, this means
- dividing all the available space by (0.9+2=2.9) fractions
- making the 1st column take 0.9/2.9 = 31.03448276% (which is the same as 9/29, as noted in my previous comment) of the available space
- and making the 2nd column take 2/2.9 = 68.96551724% (which is the same as 20/29, as noted in my previous comment) of the available space

It's almost impossible that designers would want a 31.03448276-to-68.96551724 2-column layout. That's why I was curious to know how you chose these numbers. If these numbers were not chosen based on design specs, then we are doing something wrong here as _we are just picking random numbers that seem to work_. This results unexpected things like the following

<img width="1280" alt="Screen Shot 2019-04-17 at 9 28 35 PM" src="https://user-images.githubusercontent.com/2896608/56337423-19d74500-615a-11e9-87f6-e0386281bba9.png">

<img width="1262" alt="Screen Shot 2019-04-17 at 9 37 21 PM" src="https://user-images.githubusercontent.com/2896608/56337429-1ba10880-615a-11e9-9db2-065c60f49f27.png">

<img width="1272" alt="Screen Shot 2019-04-17 at 9 48 17 PM -2" src="https://user-images.githubusercontent.com/2896608/56337787-d41b7c00-615b-11e9-976d-4f6c89587afc.png">

As screen is shrinking from desktop to mobile, profile layout jumps from **desktop layout -> tablet/mobile layout -> desktop layout -> tablet/mobile layout**.
![profile-layout](https://user-images.githubusercontent.com/2896608/56337595-eea12580-615a-11e9-8c44-7a2307050866.gif)






For MoFo websites, it's very unlikely that designers would design layout in percentage (for page layout maybe, but for anything else it's very very unlikely). If you aren't sure how to get design specs from Sketch file, I can give you a walk through and hopefully that can resolve some misunderstanding there might have been.




---

Back to my original CSS grid vs flexbox question.

I gave a few CSS grid articles a thorough read last week so I think I know the gists of it. After taking a closer look of the mockups today I think neither is a good solution for building our profile card layout.

I would suggest using a cleaner solution as the following

- mobile and tablet: use `float` for headshot (this is the classic legit use case for using float)
- desktop: use `absolute` positioning for headshot and social media block

You can check out my approach here: https://github.com/mozilla/foundation.mozilla.org/pull/3034

**Comment by Pomax** [comment]
As a small note on `fr`, you generally don't want to work with "Fractional fractions", so the smallest value you want to see is just `1fr` - the `0.9fr 2fr` dimensions are a bit odd, 1:2 would certainly feel more in line with what a designer would request. The `fr` units are great for expressing the whole "multiples of one" ratio that makes grid design pleasant =)

**Comment by youriwims** [comment]
⬆️ Moved to enhancement ✨ implementation ticket ⬆️ .
