### ISSUE TITLE
Fine tune footer styling 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#3007]
Follow-up for PR https://github.com/mozilla/foundation.mozilla.org/pull/2998

To make sure things match what we have on the mockups. 

- hover state
- ~form error state~ for form related stuff we'll revisit when form standardization work is done.

**Comment by kristinashu** [comment]
Please have @natalieworth and @sabrinang review the PR!

**Comment by sabrinang** [comment]
@mmmavis for the "Mozilla is a global non-profit ..." text please change this to `.body-small`.
For dark theme .body-small links and other paragraph links, let's change the links to be in `$light-blue`.

**Comment by kristinashu** [comment]
@mmmavis can I add one more update to this ticket (if not I can open a separate one). Please update the two mozilla.org links (logo & "Visit us at mozilla.org") to go to foundation.mozilla.org instead. Abigail from legal says if we're talking about the not for profit then we shouldn't be linking to moz.org.

**Comment by mmmavis** [comment]
@kristinashu sounds good!
