### ISSUE TITLE
Remove AlignedImageBlock from customblocks

### ISSUE THREAD

**Issue by youriwims** [mozilla/foundation.mozilla.org#3008]
**Describe the bug**
The class `AlignedImageBlock` is still in `customblocks.py` but doesn't appear to be in use. This is a follow up to #2999.

**To Reproduce**
1. Go to `/network-api/networkapi/wagtailpages/customblocks.py`
2. Line 73 still has unused `AlignedImageBlock` class.

**Comment by Sharma-palak** [comment]
@youriwims  ,Is this issue still open? can i take this issue ??

**Comment by Pomax** [comment]
@kristinashu can you confirm our content no longer requires this block to exist?

**Comment by kristinashu** [comment]
I checked with Youri and she has confirmed that we should remove this block.

I also checked our inventory and it isn't showing up so guess it isn't in use anywhere: 
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/1068783/63110631-c4ad1380-bf40-11e9-99b3-732039ccea8e.png">

**Comment by mmmavis** [comment]
![image](https://user-images.githubusercontent.com/2896608/74556120-252e0500-4f12-11ea-8a09-b6ab66963711.png)

Confirmed that we can remove the block.
