### ISSUE TITLE
Blog MVP

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#3029]
Create a Blog MVP for staff to use.

- [x] Design has been finalized
- [x] Link to original design ticket:  #2911
- [x] Link to related ticket: #3030 (Post MVP blog)
- [x] Link to Redpen: https://redpen.io/p/bha12cf7387de4f7e7
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Hover state for elements are designed

## Requirements Checklist
- [ ] Title field
- [ ] Author field
- [ ] Stream field to include
- paragraph component (but that uses the .body-large style instead of the .body style)
- Image
- Image text
- Image text mini 
- Video
- Link button
- Spacer
- Quote
- [ ] always Narrow width 
- [ ] always Zen mode
- [ ] always has IH cta at bottom

## Desktop:
![MVP-blog-detail@2x](https://user-images.githubusercontent.com/20977376/56389903-b94b1500-61f8-11e9-8354-60e087ca0330.jpg)

## Tablet:
![MVP-tablet](https://user-images.githubusercontent.com/20977376/56389907-be0fc900-61f8-11e9-92bd-a86b0df1c20b.jpg)

## Mobile:
![MVP-mobile](https://user-images.githubusercontent.com/20977376/56389916-c1a35000-61f8-11e9-9bae-501b54a9b1a5.jpg)

**Comment by kristinashu** [comment]
@alanmoo we have sign off from Anil to build this under `blog`

**Comment by alanmoo** [comment]
How does the date get set? Is it automatically the publish date? (I'm not sure if that gets updated when we, say, fix a typo or something)

**Comment by kristinashu** [comment]
Date should be the publish date (editing the post should not update the date).

**Comment by mmmavis** [comment]
Not sure how much we care about this -

To avoid seeing posts being published 'in the future', when displaying published date do we wanna include timezone info as well?

**Comment by mmmavis** [comment]
Curious about what the user flow on Wagtail is to create a blog post? Do we plan to add anything to the sidebar?

<img width="171" alt="image" src="https://user-images.githubusercontent.com/2896608/56627756-03b70200-65fc-11e9-8ab8-dbcd5d25671c.png">

**Comment by alanmoo** [comment]
Nope, they’re just a page with a new template under a parent “blog” index page (which can be a ghost namespace to start).

As for time zones: I wouldn’t worry about it- we’re so North American centric chances are the day has already started everywhere by the time a post goes live.

**Comment by mmmavis** [comment]
@alanmoo how should we implement the "author" field? Is it a simple text field or person/user object field?

**Comment by alanmoo** [comment]
I don’t have strong opinions about that other than that whatever we do shouldn’t be too restricted, because you know at some point a post will go up where Mark is the author but he didn’t actually log in and post it.

**Comment by mmmavis** [comment]
k, let's go with text field for now then to avoid blocker.
