### ISSUE TITLE
Blog: Post MVP P2's

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#3030]
Build on the Blog MVP work to fully flesh out capabilities.

- [x] Design has been finalized
- [x] Link to original design ticket: #2911 (original design ticket)
- [x] Link to related ticket: #3029 (MVP ticket)
- [x] Link to Redpen: https://redpen.io/p/bha12cf7387de4f7e7
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Hover state for elements are designed

### P1
- Sticky Side Share buttons, disappears on mobile (need to ask devs if this is possible) https://github.com/mozilla/foundation.mozilla.org/issues/3157
- Share buttons after the blog post https://github.com/mozilla/foundation.mozilla.org/issues/3157

### P2
- Tags (though, building this into the cms earlier may be helpful so we don't have to go back in and add tags later) https://github.com/mozilla/foundation.mozilla.org/issues/3165
- Related Content Section https://github.com/mozilla/foundation.mozilla.org/issues/3162
- Clickable Author name that leads to page of all the articles the author has written/their pulse profile? https://github.com/mozilla/foundation.mozilla.org/issues/3165 

## Desktop (with hover states):
![Post-MVP-hover-states@2x](https://user-images.githubusercontent.com/20977376/56389974-d97ad400-61f8-11e9-93f0-f3e6c8477616.jpg)

## Tablet:
![Post-MVP-tablet](https://user-images.githubusercontent.com/20977376/56389980-dc75c480-61f8-11e9-9efa-30e117e369c0.jpg)

## Mobile:
![Post-MVP-mobile](https://user-images.githubusercontent.com/20977376/56389986-df70b500-61f8-11e9-8f8f-f7af6bd351f3.jpg)

**Comment by kristinashu** [comment]
Turned these into individual tickets so closing this one.
