### ISSUE TITLE
CMS: group the buyers guide data

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#3042]
There are three buyers guide "interfaces" available in the CMS at the moment (bg products, bg product categories, and bg product updates) but they all live at the same root level in the nav menu... they should get grouped under some "buyers guide" heading so that they take up less space, and more obviously belong together.

ref:

![screenshot 706](https://user-images.githubusercontent.com/177243/56504645-0d424c00-64ce-11e9-9a0c-c6cc53925ed9.png)

**Comment by Stark-Pramod** [comment]
Hii @Pomax can I take this issue. can you please elaborate what exactly want, so that I may have a more clear idea?
