### ISSUE TITLE
Add 'Line' to Primary/Bannered Campaign Pages with no sub-nav

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#3045]
We want to add a line for a visual break/centering purposes on both full width and narrow templates of the Primary/Bannered Campaign pages with no sub nav. Currently it looks a bit awkward without it.

Related tickets: #3022 
Redpen is here: https://redpen.io/p/ys4594fedace293c98

## Current:
<img width="736" alt="Screen Shot 2019-04-22 at 11 57 33 AM" src="https://user-images.githubusercontent.com/20977376/56509781-dda73a00-64f5-11e9-8390-304be9646431.png">
<img width="742" alt="Screen Shot 2019-04-22 at 11 57 25 AM" src="https://user-images.githubusercontent.com/20977376/56509782-dda73a00-64f5-11e9-8638-6b181fbd1e4c.png">

## Mobile:
Spacing is 24px above and below line
<img width="354" alt="Screen Shot 2019-04-22 at 11 55 22 AM" src="https://user-images.githubusercontent.com/20977376/56509636-8903bf00-64f5-11e9-9001-4c88fefd5c38.png">

## Tablet:
Spacing is 48px above and below line
<img width="807" alt="Screen Shot 2019-04-22 at 11 55 52 AM" src="https://user-images.githubusercontent.com/20977376/56509665-991b9e80-64f5-11e9-86b5-4bf1f9af17e4.png">

## Desktop:
Spacing is 48px above and below the line
<img width="1268" alt="Screen Shot 2019-04-22 at 11 56 22 AM" src="https://user-images.githubusercontent.com/20977376/56509691-aafd4180-64f5-11e9-9492-ec8093bc7d98.png">

---

**Comment by mmmavis** [comment]
Blocked by PR #3025 #3049

**Comment by mmmavis** [comment]
@beccaklam since the gap in between the heading section and main content is kinda huge, I'm wondering if we should add divider line to both wide & narrow templates?

**Comment by beccaklam** [comment]
@mmmavis yes we want the line on both wide and narrow templates. Sorry just reworded my ask!

**Comment by mmmavis** [comment]
Fixed as part of PR https://github.com/mozilla/foundation.mozilla.org/pull/3025.
