### ISSUE TITLE
Sign-up component bug - email validation error for invalid email should be inline

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#3051]
**Describe the bug**
According to design - email validation error should be inline and not appear in a browser default error bubble.

**To Reproduce**
1. Go to https://foundation.mozilla.org
2. Scroll down to the footer section
3. Type something random in email field

**Expected behavior**
Error message for invalid email should be inline.

**Screenshots**
![sign up error bubble](https://user-images.githubusercontent.com/2896608/56600623-fb37da80-65ad-11e9-8e38-ab961300c938.gif)

**Comment by mmmavis** [comment]
Related to #3005 (this bug can be fixed if #3005 gets tackled first)

**Comment by alanmoo** [comment]
Would adding `novalidate` to the `<form>` element be sufficient here? Or is this a broader issue?

**Comment by mmmavis** [comment]
Yea I think `novalidate` + some small code changes will fix this issue. @alanmoo if you haven't started working on this I'm gonna re-assign this ticket to myself since I just fixed the same issue on Pulse.

**Comment by alanmoo** [comment]
Go for it
