### ISSUE TITLE
mismatch between PULSE_API_DOMAIN and PULSE_DOMAIN

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#3057]
Our environment.json (i.e. https://foundation.mozilla.org/environment.json) returns the following JSON:

```
{
  "PULSE_API_DOMAIN": "https://api.mozillapulse.org",
  "PULSE_DOMAIN": "www.mozillapulse.org",
  "NETWORK_SITE_URL": "https://foundation.mozilla.org",
  "TARGET_DOMAINS": ["foundation.mozilla.org"]
}
```

Which seems odd: either the `X_DOMAIN` vars should both have a protocol, or neither should have one... let's see whether we can homogenise that.

/cc @cadecairos @mmmavis

**Comment by mmmavis** [comment]
What would our preference be? With or without protocol?

**Comment by Pomax** [comment]
I would prefer "with".
