### ISSUE TITLE
Wagtail 2.5

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#3062]
[Wagtail 2.5 is out](https://docs.wagtail.io/en/v2.5/releases/2.5.html), lets update sooner rather than later.

Unfortunately, we're currently blocked on this by wagtail-inventory: https://github.com/cfpb/wagtail-inventory/issues/20

**Comment by Pomax** [comment]
wagtail-inventory now has a Wagtail 2.5 + Django 2.2 compatible 0.7 release, we should be good to go~
