### ISSUE TITLE
Remove 'image_text2' from streamfield_provider.py and factory.py

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#3065]
Remove `image_text2` related code from `streamfield_provider.py` and `factory.py` as it seems to be a custom block that no longer exists.

---

Updates: I see that `image_text2` is now used in `abstract.py`. To whoever is going to work on this ticket - please check with the team to see if `image_text2` is still something can be safely removed.

**Comment by harshs14** [comment]
hi @mmmavis , I am new here, can I take this up?

**Comment by Pomax** [comment]
This is not a good first bug, I would recommend having a look at [the list of good first bugs](https://github.com/mozilla/foundation.mozilla.org/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) instead

**Comment by Sharma-palak** [comment]
Hi @mmmavis  ,can I take this issue?

**Comment by mmmavis** [comment]
Hi @Sharma-palak thanks for offering help but I think for this ticket it's less complicated for our team to handle it.

**Comment by youriwims** [comment]
[should've been] Closed via #3575
