### ISSUE TITLE
Image text mini layout bug

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3076]
**Describe the bug**
- Icon and layout in image text mini component changes depending on copy on right side. 

**To Reproduce**
- I've made this test page to show the three different possible text variations https://foundation.mofostaging.net/en/initiatives/image-text-mini-test/.
- Component looks good in version 1 when text wraps but icon looks stretched (and ratio of icon to text is different) if text doesn't warp (is only on one line or has returns to break lines).

**Expected behavior**
- Icon and layout should look the same regardless of how much text there is and how text is formatted.

**Screenshots**
<img width="796" alt="image" src="https://user-images.githubusercontent.com/1068783/56921545-e6aa8500-6a7a-11e9-9e54-c37b9d4032e4.png">

This is happening on prod here https://foundation.mozilla.org/en/fellowships/apply/ (correct) vs https://foundation.mozilla.org/en/fellowships/partner-with-us/ (icon is too large).

cc @youriwims @mmmavis

**Comment by mmmavis** [comment]
@kristinashu how big should the image section be? e.g., as wide as the original image dimension? certain % of the total width of the "image text mini" component? fixed width?

**Comment by kristinashu** [comment]
The image should be fixed at 50x50px (image should crop if something larger or non-square is uploaded).

**Comment by mmmavis** [comment]
@kristinashu does the 50*50px dimension apply to image on all screen sizes?

**Comment by kristinashu** [comment]
Yes please. The way it's mocked up kinda breaks the grid but I've added a light gray bounding box to help convey with the idea.

<img width="973" alt="image" src="https://user-images.githubusercontent.com/1068783/56981211-20d75d80-6b33-11e9-8426-480e31cde6ba.png">

**Comment by mmmavis** [comment]
@kristinashu thank you! That screencap is very helpful!
