### ISSUE TITLE
Rename "img-txt-mini" to "image-text-mini" so it matches its corresponding component name

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#3079]
To follow our existing convention and to make sure things can be easily looked up, let's rename `img-txt-mini` to `image-text-mini` so it matches its corresponding component name.

- selector names in [foundation.mozilla.org/network-api/networkapi/wagtailpages/templates/wagtailpages/blocks/image_text_mini.html](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templates/wagtailpages/blocks/image_text_mini.html)
- file name and selector names in [foundation.mozilla.org/source/sass/components/img-txt-mini.scss](https://github.com/mozilla/foundation.mozilla.org/blob/master/source/sass/components/img-txt-mini.scss)
- other `img-txt-mini` instances in the codebase

**Comment by Sharma-palak** [comment]
@mmmavis  ,can I take this issue

**Comment by mmmavis** [comment]
Hi @Sharma-palak thanks for offering help! If you already know how to spin up the project locally and you think this ticket description provides enough instructions, feel free to take this on!

**Comment by Sharma-palak** [comment]
@mmmavis  plzz review pull request

**Comment by Sharma-palak** [comment]
@mmmavis  plzz review the pr

**Comment by alanmoo** [comment]
@youriwims Can you take the code review over the finish line?

**Comment by youriwims** [comment]
Sure can 👍

**Comment by youriwims** [comment]
Closed via #3438
