### ISSUE TITLE
Bump up line height for .body-large to 1.5

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#3081]
We've decided to bump up line height for `.body-large` to `1.5`.

/cc @sabrinang @beccaklam

**Comment by sabrinang** [comment]
I updated https://foundation.mozilla.org/en/docs/brand/design/Typography/ `.body-large` documentation (20px/30px) to match

@beccaklam Can you update the sketch style guide text style to reflect this line height update?

**Comment by beccaklam** [comment]
Yup I did that, also updated the mobile .body-large from 18/24 to 18/27 @sabrinang
