### ISSUE TITLE
Design related content cards and functionality

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3086]
**Goal**

Engage visitors to venture across site content.

**Solution**

Integrate related, dynamic content on various pages. This could be: 
- blog items
  - blog section of MozFest site
  - homepage news section
  - Participation wins at bottom of participate page
  - Fellowship success stories
  - related posts at the bottom of a blog post
- News 
- Campaigns on homepage, /participate, /advocacy
- Profiles and projects

**Automation**

Talk to devs about how this can be automated.
- can we pull content from the pages' promote tab
- show recent posts with a particular tag could appear in a certain section of a page

**Comment by beccaklam** [comment]
Started a deck here: https://docs.google.com/presentation/d/1FX12yqJy4VVSwzujEB-CtJt6FVWPhB60yvd-MAOQZCw/edit?usp=sharing
Redpen here: https://redpen.io/p/gbd1513a10bf8e9a3b

**Comment by kristinashu** [comment]
Cards look good but I'm curious about how you see this being implemented? Is it a component that can be added to any page or is it built into a template? Maybe it's automatic for blog posts and campaigns but not for other pages? Where does the image, title, secondary text come from and how would it differ depending on the page type? Once you have the ideal user flow then it's probably worth chatting to Alan about to see what is possible. I'll put this into the ticket...

**Comment by beccaklam** [comment]
So I agree that it should built into the template for blogs and campaigns. The image and header will be drawn from the page's first image and title (or just from its OG tag information if a page has one?). I'm not sure if we need a secondary heading anymore ... unless we want to surface author or date, but I don't know how important that is on our site. Scheduling a meeting with Alan tomorrow! @kristinashu

**Comment by beccaklam** [comment]
Opened implementation ticket here: #3162
