### ISSUE TITLE
Add a newsletter sign-up landing page

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#3089]
We're currently building a new sign-up drop-down that's super sweet. There are some instances, when we'll want to link to a sign-up page. For example, a google ads campaign. 

This page should leverage all the same copy as the drop-down. Might benefit from a nice image for visual balance, but otherwise the task boils down to:

 - choose URL (/newsletter, /signup, ~/join~)
 - configure page
 - add content
 - launch it

Long-term, we might want a way to manage the copy for both page and drop-down together, but it's probably best to launch it first and confirm the need. 

I believe drop-down is still better UX for typical site visitor, so I don't think this page changes anything there. 

cc @kristinashu @alanmoo

**Comment by alanmoo** [comment]
I'm not sure I understand this. What about the current opportunity page with signup form wouldn't address this?

**Comment by alanmoo** [comment]
Is this still relevant?

**Comment by xmatthewx** [comment]
Yes. We can try it as just an authored page, but put at /newsletter. See if it's good enough. We discovered a new for a blog post making a call to sign up.

**Comment by alanmoo** [comment]
https://foundation.mozilla.org/cms/pages/457/edit/

**Comment by kristinashu** [comment]
I think this is done https://foundation.mozilla.org/en/newsletter/ so I'm gonna close.
