### ISSUE TITLE
Update mozfest link on /initiatives 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3094]
Update MozFest link in sub nav on https://foundation.mozilla.org/en/initiatives/
- [ ] update copy from `MozFest` to `Festival`
- [ ] update link from https://mozillafestival.org/ to https://foundation.mozilla.org/en/mozfest/

**Comment by alanmoo** [comment]
Considering the URL will eventually go back to Mozillafestival.org and it redirects presently, should we actually change it?

**Comment by kristinashu** [comment]
Yeah works for me!
