### ISSUE TITLE
Add optional first/last name capture to signup snippet

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#3106]
I can't find the issue right now (@kristinashu can you maybe help?) but there's a request for specific newsletter signups to collect first/last names. We should add that to the "signup" snippet in Wagtail.

One question:
**If a user turns on "ask for name", should it be required? Always, or sometimes?**

@xmatthewx @stephaniemcv any opinions?

As per above, I can't find a comp right now, but the quick in-browser mockup means it'll by default look like this:
<img width="381" alt="image" src="https://user-images.githubusercontent.com/1682681/57233451-a7d17d80-6fec-11e9-957a-27f5a00bfea9.png">

**Comment by kristinashu** [comment]
Thanks Alan, yes those styles work!

I don't think we should make names a required field since as far as I know we have no huge need to know their names and I wouldn't want to block people from signup just because they don't want to share their name (or for them to use a fake name). @annmarie123 you ok with that?

**Comment by stephaniemcv** [comment]
In my opinion, I agree with @kristinashu. Name should be optional not required. I can't think of a current Mozilla subscription only form that requires name.

**Comment by kristinashu** [comment]
Sounds like @stephaniemcv is getting close to setting this up on her endhttps://github.com/MozillaFoundation/Design/issues/348#issuecomment-493304220, @alanmoo would you be able to add these fields?

**Comment by kristinashu** [comment]
Oh and can you also add the ability to have a Bannered Campaign Page under /fellowships?
