### ISSUE TITLE
Fix margin of "IH CTA" on blog pages

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#3111]
(Blocked until PR #3066 is merged)

Follow-up for PR https://github.com/mozilla/foundation.mozilla.org/pull/3066. For original discussion see this [thread](https://github.com/mozilla/foundation.mozilla.org/pull/3066#discussion_r280888321).

Currently IH CTA section(`ih_cta.html`) comes with default margin class `my-5` (48px top and bottom margins). On blog pages we want IH CTA to have top margin 95px and no bottom margin. We decided to separate this work from the [blog PR](https://github.com/mozilla/foundation.mozilla.org/pull/3066) to keep things less complicated.

@alanmoo you mentioned the approach I had in the PR wasn't ideal (removing `my-5` as default wrapper class and making `ih_cta.html` take an optional var `wrapper_class`). Can you provide suggestions here? Are you thinking about creating a templatetag(? or tag?) and letting it figure out what wrapper class we should assign `ih_cta.html` based on the page type it's on?

/cc @alanmoo @Pomax

**Comment by alanmoo** [comment]
I was thinking a sensible default (`my-2`) would be useful, and then simply wrap it in more HTML with margin classes if necessary wherever it's used. Building the ability to capture a wrapping class into the tag feels excessive.

(I'm only at like 2/5 💩 given about this though)

**Comment by mmmavis** [comment]
Um I'm opposed to making things more nested just for margin's sake. I'm gonna close this ticket but if you think this is still worth doing please re-open it.
