### ISSUE TITLE
Update buyer's guide fake data

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#3113]
**Describe the bug**
Percy flagged a real change, but the resulting screenshot looks wrong because of our fake data setup. Notice the bottom of the image, with the donate graphic overlapping product comparison.

**To Reproduce**
I'm not positive, but presumably run the mock data generation and check out a buyer's guide product page.

**Expected behavior**
Some comparison products show up in Percy so we understand what the page will look like.

**Screenshots**
![image](https://user-images.githubusercontent.com/1682681/57388328-f5cdb900-7185-11e9-83da-18699a6bb45c.png)

**Comment by alanmoo** [comment]
@Pomax @mmmavis How was this during development this year? Do you think this ticket still needs to exist?

**Comment by mmmavis** [comment]
I didn't work on PNI that much this year but I don't recall seeing any issues like the one mentioned above.

**Comment by cadecairos** [comment]
Closing this issue due to its age, if this is work that we still want to do, please refile this with up to date information so that it can be put in the correct milestone with up to date estimates.
