### ISSUE TITLE
MozFest: Unique Landing Page

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#3116]
### Description
For Mozilla Festival 2019, it'll have it's own landing page.

**Navigation**
It'll have its own navigation with festival logo, nav items and cta button and it will be match the style of the current https://foundation.mozilla.org/ site.

**Full Hero Banner**
This landing page will feature a large hero to feature an image, heading, description and cta button. Could this area feature a video background? Note that all other subpages on the festival site will be using the primary template style.

_Related Issue: This may also be used to update the current participate and initiative page styles on the foundation site to align those styles. https://github.com/mozilla/foundation.mozilla.org/issues/2275_

**Pulse component**
We will pull blog post using our existing Pulse component.

**Twitter feed**
https://github.com/mozilla/foundation.mozilla.org/issues/3118

**Wireframe on redpen here** https://redpen.io/smaff9809d00feddb3
<img width="942" alt="image" src="https://user-images.githubusercontent.com/2492510/57412679-52d96700-71a6-11e9-973e-2f6bf7f3b516.png">

**Comment by Pomax** [comment]
This might also include a video in the banner as "background" so we probably want to look at making sure the template supports `<video>` in addition to `<img>`

**Comment by sabrinang** [comment]
redpen mockup here: https://redpen.io/vuefbd37973f0c2a38
<img width="307" alt="image" src="https://user-images.githubusercontent.com/2492510/57659143-218ddc00-7596-11e9-98bc-705f61079dde.png">

**Navigation**
- logo is mozilla festival
- features one button on upper right nav

**Full Hero Banner**
- features heading, description and button
- video background under dark gradient overlay for contrast
- text uses dark theme

**Potential Editable Areas TBD**
- hero banner text/button
- text after hero 
- text beside social feed near footer

**Comment by sabrinang** [comment]
https://github.com/MozillaFoundation/mozfest-website-2019/issues/1#issuecomment-492421308
- another area of editable text would be after pulse feed (Zannah wants to keep Mark's note from current April version)

**Comment by kristinashu** [comment]
I think everything here is either done or represented in a different ticket so I'm going to close!
