### ISSUE TITLE
MozFest: Unique Footer

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#3117]
### Description
For Mozilla Festival 2019, it'll have unique content for the footer that is specific to the festival but will be styled to match the current https://foundation.mozilla.org/ site.

**Email Signup**
After April, the email sign up will live in this footer area.

**Social (More about us section)**
This will link to the festival's social links: [twitter](https://twitter.com/mozillafestival), [medium](https://medium.com/mozilla-festival), [youtube playlist](https://www.youtube.com/playlist?list=PLnRGhgZaGeBt11miYYvKSSgbxkkbKKT7p), [email](festival@mozilla.org)

I believe the MozFest team would like to hide the donate cta above the footer as they will be focusing on ticket sales.

Wireframe on redpen here: https://redpen.io/smaff9809d00feddb3
<img width="900" alt="image" src="https://user-images.githubusercontent.com/2492510/57413083-ca5bc600-71a7-11e9-8dba-c161325ae1e6.png">

**Comment by kristinashu** [comment]
This signup should add people to both `mozilla-foundation,mozilla-festival` lists (same as what is currently on https://foundation.mozilla.org/en/mozfest/).

**Comment by sabrinang** [comment]
Will the participation guidelines be an unique MozFest page or use same link as other footers https://www.mozilla.org/about/governance/policies/participation/ ?

**Comment by sabrinang** [comment]
![image](https://user-images.githubusercontent.com/2492510/57658979-8268e480-7595-11e9-89bd-8c842c62e039.png)
footer seen on redpen mockups here: https://redpen.io/p/nt88aa617b390e8eb0
- used sign up language from current [April version](https://foundation.mozilla.org/en/mozfest/)
- included icons for medium, twitter, youtube playlist, email

**Comment by mmmavis** [comment]
@sabrinang can you link us to the social icon files? 👀

**Comment by sabrinang** [comment]
@mmmavis svgs exported here: https://drive.google.com/open?id=1sc9am1e190ICxW2MbcWgvVoB95gtrXDy

**Comment by kristinashu** [comment]
@sabrinang @gideonthomas will find out which icons and links to include later today.

**Comment by Pomax** [comment]
Turns out it's too easy to delete something off of a google drive, and that "undo delete" can crash gsuite. @sabrinang can you add the youtube icon to gdrive again? Also, the site CSS expects a different file for "hover" so if we have the same icons but coloured appropriately for hover state, I can drop those into the glyph directory as well and things should "just work(tm)".

**Comment by sabrinang** [comment]
@Pomax I updated the gdrive folder with hover icons (light blue) too: https://drive.google.com/open?id=1sc9am1e190ICxW2MbcWgvVoB95gtrXDy

They can be the same icon size as what is live (16px)

Twitter - https://twitter.com/mozillafestival
Medium - https://medium.com/mozilla-festival

To be confirmed:
Youtube - TBD link
Mail - TBD link

**Comment by sabrinang** [comment]
For the footer links, we got additional info from @zee-moz:

- for Participation Guidelines, link to a new CMS page
- add an additional link, Media Center, below Participation Guidelines that also link to another new CMS page 

<img width="826" alt="Screen Shot 2019-05-22 at 12 42 09 PM" src="https://user-images.githubusercontent.com/2492510/58203537-29810680-7c8f-11e9-8b85-233313cb81c0.png">

**Comment by Pomax** [comment]
what will the URLs for those two pages be?

**Comment by sabrinang** [comment]
The previous URLs were http://mozillafestival.org/guidelines and http://mozillafestival.org/media, so I assume we are going with /guidelines /media @gideonthomas can you confirm?

**Comment by Pomax** [comment]
I've filed the PR with `#tobedetermined`, so it should be easy to update.

**Comment by gideonthomas** [comment]
I don't think it matters. We can keep it the same.

**Comment by Pomax** [comment]
Note that this does require someone _make_ those pages of course =D

**Comment by gideonthomas** [comment]
Yep I will do that asap
