### ISSUE TITLE
MozFest: Social Media Feed

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#3118]
### Description
For Mozilla Festival 2019, it'd be great to feature more social activity and stories by including a social feed. Specifically, twitter #mozfest hashtag or @mozillafestival handle.

**Feed**
This can be featured above the footer area on the landing page. TBD how it is styled because it may just use twitter's styles.

Wireframe on redpen here: https://redpen.io/smaff9809d00feddb3
<img width="948" alt="image" src="https://user-images.githubusercontent.com/2492510/57413384-ca0ffa80-71a8-11e9-8a67-58e8a6c9745b.png">

**Comment by alanmoo** [comment]
I envision this as a streamfield component, which would be useful across the site. Keep in mind that streamfield components are separate from the template, which defines how they get laid out on a page. So if you're looking for a 2 column page layout, that's a different topic.

**Comment by Pomax** [comment]
this might not be shared, but just something that only lives on the homepage, which means we can probably just "do this in the template" rather than trying to make wagtail slip this into a streamfield

**Comment by sabrinang** [comment]
![image](https://user-images.githubusercontent.com/2492510/57659865-c5788700-7598-11e9-8bc6-98d109eb6810.png)
social feed mockup in landing page on redpen here: https://redpen.io/vuefbd37973f0c2a38
- 2 column since it is only on the homepage
- can the text left of it be editable?
- how does the embed look like? I'm not sure if my screenshot is accurate in the mockup and if it needs any additional styling

**Comment by kristinashu** [comment]
@alanmoo can you please provide some guidance on implementing this?

**Comment by kristinashu** [comment]
On slack @alanmoo said:

> My understanding is we can _just_ embed this in the template and be good

<a class="twitter-timeline" href="https://twitter.com/mozillafestival?ref_src=twsrc%5Etfw">Tweets by mozillafestival</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 

@Pomax is skeptical and reminded us that CSP clearance will be necessary because that's a third part embed.

Maybe @mmmavis could take a look???

**Comment by Pomax** [comment]
@sabrinang @kristinashu  Styling wise, what is the max-height this embed block should be?

**Comment by kristinashu** [comment]
We might need to adjust it once we see it at all screen widths but could you please start with 336px (this is based on using multiples of 8 so 8x42=336px which is pretty close to what Sabrina mocked up)?

**Comment by kristinashu** [comment]
nvm the 360px you have is probably good and wouldn't want to go any less than that.
