### ISSUE TITLE
MozFest: Blog Post Feature

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#3119]
### Description
For Mozilla Festival 2019, the landing page will have a storytelling focus to feature blog posts from medium.

**Blog feature**
This could look similar to the latest news section on the foundation site to feature festival specific content or it could be a pulse feed that links directly to festival blog posts. It will feature content from https://medium.com/mozilla-festival/tagged/mozfest2019

**Related Issue**
This work is also referenced in adding cards the site to engage visitors https://github.com/mozilla/foundation.mozilla.org/issues/3086

Wireframe on redpen here: https://redpen.io/smaff9809d00feddb3
<img width="694" alt="image" src="https://user-images.githubusercontent.com/2492510/57413765-3f2fff80-71aa-11e9-87c4-fca2bf7b580b.png">

**Comment by alanmoo** [comment]
If we're going to with Pulse as the tracker for Medium stories, it's probably best to stick with the card component that we've used elsewhere, and then have conversations about how we might want to enhance that component in the future.

**Comment by sabrinang** [comment]
Note: We will be using the pulse feed component to feature blogs, the other option won't be ready

**Comment by sabrinang** [comment]
<img width="874" alt="image" src="https://user-images.githubusercontent.com/2492510/57645855-0e6a1480-7574-11e9-98ce-44499b7ab8fd.png">
We are sticking with the pulse feed card component that pulls in medium blog posts from https://medium.com/mozilla-festival

**Comment by sabrinang** [comment]
Redpen mockup of feed in context on landing page: https://redpen.io/vuefbd37973f0c2a38

**Comment by kristinashu** [comment]
I'm going to close this ticket since we will be using the Pulse component therefore there is no dev work to be done here. 

There is however the question about if we should be posting to Medium or our own blog on fo'mo. Since that is more of a content question with Zannah, @gideonthomas can you please open a ticket in your repo for that https://github.com/MozillaFoundation/mozfest-website-2019/issues?
