### ISSUE TITLE
MozFest: People Card Format

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#3120]
### Description
For Mozilla Festival 2019, it will feature people from staff, wranglers, volunteers etc.

**People Cards**
We'll use the current people cards powered by pulse. The bios for the festival can be lengthy so I was wondering if we can have a full width style for narrow view to balance out the copy and image? Another feature I'd like to consider is that if we can hide location subheading to feature a role subheading instead? 

(See below example of previous years: Sarah Allen _Executive Festival Director_ etc.)
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/2492510/57414281-52dc6580-71ac-11e9-8d92-ff00f6600c92.png">
Wireframe on redpen here: https://redpen.io/hv7a834d9950715a48

**Comment by alanmoo** [comment]
This is probably possible, though perhaps not right for launch depending on what we need to prioritize. Any changes we make supporting wider cards would be applied across the entire "directory", not on a per-tab basis.

**Comment by sabrinang** [comment]
Note: if production team has different role and bio format, we can use image + text components for that page instead of using people cart format

**Comment by kristinashu** [comment]
So I think there actually isn't anything for devs to do here?

**Comment by sabrinang** [comment]
Confirm with Zannah/Gideon that production team bios are using image + text component (we collect these) and for wrangler/volunteers etc. we are pulling in from pulse (they enter it themselves)

**Comment by kristinashu** [comment]
Styling the cards in https://github.com/mozilla/foundation.mozilla.org/issues/3237
