### ISSUE TITLE
Add more context to homepage

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3142]
Concerns that our homepage doesn't give new users enough context about who we are and why they should care has surfaced in two different ways recently.

#### From @beccaklam's users testing https://github.com/mozilla/foundation.mozilla.org/issues/2995#issuecomment-491035740:
- We should consider users who don't know our issues/Mozilla well and think about how to onboard them on our homepage if we ever want to grow our audience
- We should be aware of two types of audience -- those who know our cause or are internet-savvy and those who don't know us or are not internet-savvy. We don't want to talk down to people who feel that they already know their stuff.

#### From Juan and Lotta around fundraising [(doc from meeting)](https://docs.google.com/document/d/1txC3guawnjoeXUvFbFABhR32kPNDtx2O0MKGP8OzTJs/edit#):
  - Going to the site it’s hard to say “What Mozilla does”. This should frame the rest of the content about projects, news, etc.
  - What is a short pithy way to describe what we do that is engaging and captivating? This should be a big piece of the landing page
  - Everything we present should be about the “bigger plan”
  - Needs to make donors be a part of the work we do so that they don’t feel like they’re just giving us money to do work but they’re giving us money to do work that they care about and are contributing to
  - Landing page doesn’t talk about why they should participate - only how to participate (e.g. Apply to be a Fellow).  We need to be able to tell our broader story better on this page.
  - Where do we talk about what our plan is for a healthier internet? We should be selling that plan/vision. I.e. resonating with audiences with emotion, a story, rather than specific programs we run out of context. Answering “what is Mozilla about” should be the first touchpoint for people
  - Juan just links people to the fo’mo website so the first touchpoint is the landing page.
  - News should tell the story of our impact
  - Projects need more context so that the broader picture is still described using it

#### We should:
- benchmark similar sites: a few examples but should gather more
  - https://colorofchange.org/
  - https://rebellion.earth/
  - https://www.astraeafoundation.org/global-reach/
  - http://www.freedomforall.org
  - http://sfaf.org/
  - https://www.fordfoundation.org/
  - https://www.shuttleworthfoundation.org/
- write up a few recommendations (some quick fixes some long-term) 
  - one of those recommendations should be to add an intro sentence (who should write this?)
- mock-up a few options
- get feedback from staff
- test with different audiences

cc: @sabrinang @natalieworth @beccaklam @xmatthewx @anilkanji

**Comment by natalieworth** [comment]
I found this example too a while ago that I liked: https://www.thebureauinvestigates.com/stories
<img width="1680" alt="Screen Shot 2019-05-13 at 3 10 35 PM" src="https://user-images.githubusercontent.com/14876567/57657804-6105f980-7591-11e9-9a27-ffe4e3a6a185.png">

**Comment by kristinashu** [comment]
I've added a bunch of benchmarks to redpen for discussion https://redpen.io/p/fm1aa86db66594fc47

**Comment by kristinashu** [comment]
Initial homepage comp https://redpen.io/vye279eb57db215c4d. I'd like to simplify our homepage to be less overwhelming to users and help them quickly understand what we do. 
- added a placeholder cause sentence
- reduced the amount of content, images, and number of different styles
- incorporated some design elements from Natalie's blue sky explorations https://redpen.io/p/rja784df428a8af4e5 but made them less _blue sky_ aka quicker for devs to do
- hoping to add ways of automatically updating content rather than Sydette needing to do it manually

**Comment by anilkanji** [comment]
Digging this thinking/conversation. Based on these mocks this feels like it's evolving from adding context to thinking about home page UX/IA, and potentially rethinking some of our content strategy. We should connect to align on what level this project is at - it's all positive stuff, and want to be sure we set the process up to succeed.

**Comment by kristinashu** [comment]
Makes sense! I've added one more comp https://redpen.io/qr7e80679a5c55f97f that keeps everything from our current site the same and only added in the cause sentence. We can use this to start finalizing a sentence and then explore other homepage updates in the future.

**Comment by anilkanji** [comment]
Thanks! I think the exploration is good though, and don't want to lose
that. We should be thinking about this stuff, and need to loop in the right
people on our team.

**Comment by kristinashu** [comment]
Focusing on the cause sentence here https://github.com/MozillaFoundation/Design/issues/377 and will close this one since is out of scope.
