### ISSUE TITLE
Create a 'Join Us' landing page on the foundation site

### ISSUE THREAD

**Issue by natalieworth** [mozilla/foundation.mozilla.org#3145]
We will be creating a 'Join Us' landing page with a 'sign up' button that will link to the Pulse sign-up for new users/ fellows/ potential fellows.
https://redpen.io/zgec7048af617e6e44

Image assets are in here:
[Join Us Image Assets.zip](https://github.com/mozilla/foundation.mozilla.org/files/3175334/Join.Us.Image.Assets.zip)

cc @mmmavis @youriwims Do you need the header exported or are you able to pull it from one of the other pages? I think it is already on the site but I don't know if you need it exported again?

@xmatthewx @gideonthomas @alanmoo

**Comment by natalieworth** [comment]
Going to block this until I have final design feedback on images/ design from design team.

**Comment by mmmavis** [comment]
Hey @natalieworth once design is final do you mind updating the ticket description to follow the "design to dev" handoff template? You can copy the template here: https://github.com/mozilla/foundation.mozilla.org/issues/new?assignees=&labels=&template=design-to-dev-handoff.md&title= 👍 👍 👍 Thank you!

**Comment by mmmavis** [comment]
> Do you need the header exported or are you able to pull it from one of the other pages? I think it is already on the site but I don't know if you need it exported again?

If it's an image being used live we can pull it. Just show us an example on prod then we should be able to reuse the image.

**Comment by natalieworth** [comment]
Closing this one @mmmavis and opened one with the hand off template :)

**Comment by mmmavis** [comment]
Thank you! @natalieworth
