### ISSUE TITLE
Create a 'Join Us' landing page on the mozilla foundation site

### ISSUE THREAD

**Issue by natalieworth** [mozilla/foundation.mozilla.org#3147]
We will be creating a 'Join Us' landing page with a 'sign up' button that will link to the Pulse sign-up for new users/ fellows/ potential fellows.
https://redpen.io/zgec7048af617e6e44

Image assets are in here:
[Join Us Image Assets.zip](https://github.com/mozilla/foundation.mozilla.org/files/3175402/Join.Us.Image.Assets.zip)

cc @mmmavis @youriwims I'll find the header example to pull. Everything's still blocked for this ticket. Just setting it up but design isn't quite ready yet :D 

@xmatthewx @gideonthomas @alanmoo
---

**🗒  Design -> Dev Handoff Checklist**
(Feel free to remove items that are not applicable.)

- [x] Design has been finalized
- [x] Link to original design ticket
- [x] Link to related ticket
- [x] Link to Redpen
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Assets are included
- [x] Hover state for elements are designed
- [x] Other states for elements are designed (e.g., error state for form)

**Comment by natalieworth** [comment]
Final design is here (and updated in the Sketch file):
https://redpen.io/p/wp17e9f94b044da4a0

<img width="1242" alt="Screen Shot 2019-05-14 at 5 47 25 PM" src="https://user-images.githubusercontent.com/14876567/57741176-5b331580-7670-11e9-9ed2-a4d48fbfdd38.png">

`<hr>`

**Comment by kristinashu** [comment]
From what I understand @natalieworth can just make this page in the cms. Nat, let me know if you need help doing that.

@xmatthewx what should the url be?

**Comment by kristinashu** [comment]
P.S. Based on Rebecca's user testing we're update the `Newsletter` signup button to `Join us` so that might be confusing (but we also hope to test out `Subscribe`) https://github.com/mozilla/foundation.mozilla.org/issues/3161?

**Comment by kristinashu** [comment]
@xmatthewx says we should go with /joinus so @alanmoo can you please create a `Primary` page template at http://foundation.mozilla.org/en/join-us? And then @natalieworth can add the content!

**Comment by alanmoo** [comment]
https://foundation.mozilla.org/cms/pages/396/edit/

**Comment by natalieworth** [comment]
Created join us page at Alan's link above https://foundation.mozilla.org/cms/pages/396/edit/
cc @kristinashu @xmatthewx @alanmoo

**Comment by kristinashu** [comment]
w00t w00t @natalieworth! I think you just need to:
- check the "Narrowed page content" box under Settings tab. 
<img width="800" alt="image" src="https://user-images.githubusercontent.com/1068783/58122967-9cbb4780-7bbf-11e9-8d94-aed39ebb1b3c.png">

- delete the test page under Initiatives
- and then I think you can publish it

cc @xmatthewx

**Comment by natalieworth** [comment]
Deleted old page and published here (but it's still on 'private' view for now): 
https://foundation.mozilla.org/cms/pages/396/edit/

cc @kristinashu @xmatthewx

**Comment by kristinashu** [comment]
Looks great! I don't see any harm in publishing it so it's live now https://foundation.mozilla.org/en/join/

Closing!!!
