### ISSUE TITLE
Prep post and form for Fundraising MisInfo Campaign

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#3149]
We're launching a fundraising campaign around misinfo soon. It requires a couple of things: 

 - [x] Blog post by @caltrider with dataviz by @beccaklam https://github.com/MozillaFoundation/Design/issues/361
 - [ ] Google form by @caltrider and @beccaklam to gather questions from audience
 - [ ] NIce to have: a page to embed the google form (tested by @alanmoo & @beccaklam) 
    - Could be placed as hidden child page of /campaign/eu-misinfo
    - **Note:** I think this might be overkill. Google form with good info at the top might be plenty for this campaign. 

@beccaklam - can you facilitate all of this? full license to nudge Alan and others as needed.

**Comment by beccaklam** [comment]
Yep, I can do this. This launches on this Thursday, right? @xmatthewx

**Comment by caltrider** [comment]
Hey @beccaklam, blog post we've already talked about is for this week. We'll pretty much all good to go there once you have the data viz done.  The other stuff is actually for the next email set to go next Wednesday, not the one that launches this week on Thursday. @xmatthewx , I know Rebecca heads out on vacation for a couple weeks after tomorrow so we might need to find someone else to help with the google form stuff for next week?

**Comment by beccaklam** [comment]
Oh I see, in that case I can't do this since I'll be on vacation like Jen said. Sorry @xmatthewx ! Talked to Kristina and she said she can cover it. Thanks @kristinashu !

**Comment by xmatthewx** [comment]
Link to form will go out in email on May 22nd. So, form should be ready before. Maybe Monday the 20th?

**Comment by xmatthewx** [comment]
@caltrider - when you create your form, you can grab one of these theme headers: https://drive.google.com/drive/folders/10Qs8u-55IH5Ih89igzNBG0yFysxrpqzb

**Comment by kristinashu** [comment]
Or the full form template here https://foundation.mozilla.org/en/docs/brand/design/templates/
