### ISSUE TITLE
Add field to upload OG image to Blog page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3156]
Promote tab for blog should have a place to add an OG image (like our other CMS pages).

Screen cap of blog promote tab: missing image field
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/1068783/57729400-edc0be00-764a-11e9-82ba-305ce99a9158.png">

Screen cap from another cms page: with image field
<img width="1245" alt="Screen Shot 2019-05-14 at 1 17 13 PM" src="https://user-images.githubusercontent.com/1068783/57729602-6d4e8d00-764b-11e9-8500-0ca9a7220e19.png">

cc @mmmavis @beccaklam

**Comment by mmmavis** [comment]
@Pomax I think it's this part in `class BlogPage(FoundationMetadataPageMixin, Page)` in `models.py` that's causing the issue here.

```py
promote_panels = Page.promote_panels + [
    FieldPanel('tags'),
]
```

It seems like [`Page.promote_panels`](https://github.com/wagtail/wagtail/blob/4891db0d89d99529b222a97ccb00e10a51e51230/wagtail/admin/edit_handlers.py#L784-L791)  doesn't include the `search_image` field. I can't figure out why all other page types have `search_image` field in Promote tab by default. Can you suggest what the best way is to enable that field for Blog Page?

**Comment by Pomax** [comment]
Metadata fields in the "promote" tab are supplied by both the `Page` and `MetadataPageMixin`, so rather than use this code, which fully overwrites `promot_panels`, it's probably better to say:
```
class BlogPage(FoundationMetadataPageMixin, Page):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.promote_panels.append(
          FieldPanel('tags')
        )
```
Or, create an extension on the FoudationMetadataMixin and inherit from that:
```
class FoundationMetadataMixinWithTags(FoundationMetadataMixin):
  promote_panels = FoundationMetadataMixin.promot_panels + [
    FieldPanel('tags');
  ]

...

class BlogPage(FoundationMetadataMixinWithTags, Page):
  ......
```

**Comment by mmmavis** [comment]
Went with the 2nd approach and got the following errors 👀 

```bash
SystemCheckError: System check identified some issues:

ERRORS:
wagtailpages.BlogPage: (models.E005) The field 'id' from parent model 'wagtailpages.foundationmetadatamixinwithtags' clashes with the field 'id' from parent model 'wagtailcore.page'.
wagtailpages.BlogPage: (wagtailcore.E002) Manager does not inherit from PageManager
	HINT: Ensure that custom Page managers inherit from wagtail.core.models.PageManager
```

**Comment by Pomax** [comment]
Having a look at the underlying code, I'm not sure why Blog pages don't show the image field - it's part of the metadata, and the inheritance chain for BlogPage, which is lacking that image field, is the same as for PrimaryPage, which _does_ have that image field...

**Comment by kristinashu** [comment]
@Pomax can you please ping me once this has landed on prod? Then I'll go in and add images.
