### ISSUE TITLE
Implement new mozfest app

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#3160]
Implement a new mozfest app with a homepage and "other" page model, with associated templates.

Closes: https://github.com/mozilla/foundation.mozilla.org/issues/3170
Related: https://github.com/MozillaFoundation/mozfest-website-2019/issues/1 (includes comps)

**Comment by Pomax** [comment]
Tasks left to do:
- [ ] clean up the footer (does it need a refinement to `<JoinUs>` based on being on the mozfest site?)
- [ ] clean up the nav (make the links includable fragments to DRY out that part of the template)
- [ ] add SCSS for narrow content on all pages, while making the homepage the only page with wide content.
- [ ] make sure GA kicks in for mozfest rather than for the foundation site (this probably involved `main.js` work, probably with a new `MOZFEST_ANALYTICS_ID` or somesuch env var)

**Comment by mmmavis** [comment]
Re-opening to track leftover todos.

**Comment by Pomax** [comment]
Solved the footer by making them always pull the signup details from the `Mozfest` signup snippet.

**Comment by Pomax** [comment]
All caught up!
