### ISSUE TITLE
Update email sign up copy

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#3161]
Related ticket: #2995 

After conducting some testing on usertesting.com (see related ticket) we've decided to update the email sign up button text to:

### Header
- [ ] Update button text: `Join us`
- [ ] Update body text: 
`Protect the internet as a global public resource.`
`Join our email list to take action and stay updated!`

### Footer
- [ ] Update body text:
`Protect the internet as a global public resource.`
`Join our email list to take action and stay updated!`

## A/B Test?
If possible it would nice to A/B test the button text. One version would be 'Join Us', the other would be 'Subscribe'
- [ ] Open ticket to test button language

## Desktop:
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/1068783/57813722-0356e600-7726-11e9-904e-99b17268f329.png">

## Tablet:
<img width="766" alt="image" src="https://user-images.githubusercontent.com/1068783/57813781-339e8480-7726-11e9-977b-335a5d2e60ec.png">

## Mobile:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/1068783/57813817-5335ad00-7726-11e9-9c57-086c8c11d4d3.png">

## Footer:
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/1068783/57813414-e1a92f00-7724-11e9-8f90-695651f3e1e1.png">

**Comment by alanmoo** [comment]
I'll see if this is managed by a snippet under the hood.

**Comment by alanmoo** [comment]
It seems like the header signup is no longer a thing. Does this just apply to the footer now?

**Comment by alanmoo** [comment]
Also, when simply changing the text strings, this highlights a potential design discrepancy on desktop: 
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/1682681/60134611-e45c6280-976d-11e9-8d62-9395b7be6bab.png">

I'm generally cautious of going down a rabbit hole of design tied to content in places like this, but it does feel like the kind of thing we should make look really nice on every page. Should I land the string change and open an issue to discuss the spacing, or should this all happen together? (The latter of which would be easiest to do with some pairing time over Zoom.)

**Comment by beccaklam** [comment]
> It seems like the header signup is no longer a thing. Does this just apply to the footer now?

@kristinashu @anilkanji Is the header signup no longer a thing or was it never implemented? From my knowledge it was a new initiative that had been designed but not put on the site yet. I could be wrong though 🤷‍♀

**Comment by beccaklam** [comment]
> Also, when simply changing the text strings, this highlights a potential design discrepancy on desktop:
> <img alt="image" width="1118" src="https://user-images.githubusercontent.com/1682681/60134611-e45c6280-976d-11e9-8d62-9395b7be6bab.png">
> 
> I'm generally cautious of going down a rabbit hole of design tied to content in places like this, but it does feel like the kind of thing we should make look really nice on every page. Should I land the string change and open an issue to discuss the spacing, or should this all happen together? (The latter of which would be easiest to do with some pairing time over Zoom.)

@alanmoo Do you mean hard-coding it so it always breaks a certain way? I'd be okay with doing that over Zoom so we could check different screen widths.

**Comment by kristinashu** [comment]
Nav signup is happening here https://github.com/mozilla/foundation.mozilla.org/issues/2994 but was put on hold for Pulse work. I'll update that ticket with this new copy.
