### ISSUE TITLE
Investigate adding .body-large style to Paragraph component

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3163]
Can we add [.body-large](https://foundation.mozilla.org/en/style-guide/) as an option to the Paragraph component? It would be quite useful sometimes.

cc @mmmavis @Pomax

**Comment by mmmavis** [comment]
The Paragraph component auto wraps any non-block level elements in `<p>`. e.g., (bold text, anchor, etc). So adding a new ["feature" (option)](http://docs.wagtail.io/en/v2.0/advanced_topics/customisation/page_editing_interface.html#limiting-features-in-a-rich-text-field) for `.body-large` text to the list below doesn't seem to be a good way to achieve what we want.
<img width="856" alt="image" src="https://user-images.githubusercontent.com/2896608/57954411-b26efb00-78a7-11e9-9ecb-5a4755010197.png">

@Pomax correct me if I'm wrong - I think it's cleaner and easier if we create a new Wagtail component  (call it Large Paragraph???) that does basically the same thing as Paragraph component except by default has `.body-large` assigned to the wrapper `<p>` so everything in that component is in `.body-large` style without the need of extra SCSS overrides like [what we added for the blog page](https://github.com/mozilla/foundation.mozilla.org/blob/d5c61fa37e6e4be2ab3f40812839674256001561/source/sass/wagtail.scss#L78).

**Comment by kristinashu** [comment]
This is a P2 for *Privacy Included piece https://github.com/mozilla/foundation.mozilla.org/issues/3801

**Comment by Pomax** [comment]
creating a new component that does the exact same thing as paragraph but adds a `body-large` is not going to be something that people will remember to use, and will probably cause more confusion in the CMS view than it lets us solve. 

This might be one of those things that we can't really solve without hacks that work short term, but make things much larger long term, because "adding classes to only certain freeform paragraphs" is not a thing that fit in the the wagtail way of streamfield content editing.

We should investigate if there's something we can do here, which I would estimate as a 3, but note that only covers the investigation, not the implementation yet.

**Comment by kristinashu** [comment]
Hmm ok, I'll put this on design. Maybe we need to increase the size of our regular body text... will explore.

**Comment by kristinashu** [comment]
Maybe loosely related https://github.com/mozilla/foundation.mozilla.org/issues/3847?

**Comment by Pomax** [comment]
After further investigation, we can use a wagtail_hook to extend the rich text editor to do _almost_ what we want here, except it won't apply to paragraphs, but rather to `<span>`s of text.

E.g. with a new button "L" (for "large") added, you can select a stretch of text and click that the same way you would bold or italic:

![image](https://user-images.githubusercontent.com/177243/69180388-1629e900-0ac2-11ea-819a-37cf1a333496.png)

Which results in the following code:

![image](https://user-images.githubusercontent.com/177243/69180480-39ed2f00-0ac2-11ea-87d0-f370ebac90e5.png)

Which then looks like this:

![image](https://user-images.githubusercontent.com/177243/69180461-29d54f80-0ac2-11ea-9bb7-3bcb2ef741b1.png)

**Comment by Pomax** [comment]
I've filed https://github.com/mozilla/foundation.mozilla.org/pull/3937 to see if this is good enough for what we want.
