### ISSUE TITLE
MozFest: homepage banner

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#3172]
Since the design for MozFest homepage banner section is new, I'll need the following before I can go ahead and fix what's currently on staging 🔨 

- mobile mockup (and tablet mockup, if possible)
- default banner image

/cc @sabrinang

**Comment by kristinashu** [comment]
1) First I tried keeping the aspect ratio the same for all screen sizes and that doesn't work for tablet or mobile...
<img width="970" alt="image" src="https://user-images.githubusercontent.com/1068783/57896717-f2ca6c80-7806-11e9-8ac0-527a39749d70.png">

2) Then I tried keeping the same height which works well for tablet and kinda works for mobile...
<img width="969" alt="image" src="https://user-images.githubusercontent.com/1068783/57896736-05dd3c80-7807-11e9-8879-64724675c65f.png">

3) So then I kept the same height for desktop and tablet but adjusted it for mobile. 
<img width="968" alt="image" src="https://user-images.githubusercontent.com/1068783/57896829-800dc100-7807-11e9-88fa-89e80bd4734d.png">

I think 3 is best but 2 could work. What do you think @mmmavis @sabrinang? 

Note for mobile: white cutout box disappears and video is just a static image.

**Comment by kristinashu** [comment]
@sabrinang can you give me upload access to https://redpen.io/p/nt88aa617b390e8eb0? Then I'll add the comps there too.

**Comment by kristinashu** [comment]
Oh nvm, I think I found a banner height that will work at all screen widths:

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/1068783/57939815-f817cd80-787f-11e9-8593-4366b3e32a15.png">

I also looked at the old site and it seems like the overlay is done in css over top of the video https://mozillafestival-org-production.herokuapp.com/. Do we want to do keep doing that?

**Comment by mmmavis** [comment]
Can we leave the gradient overlay as P2 for now. It's trickier to implement that here than on the old MozFest site.

**Comment by kristinashu** [comment]
@sabrinang @mmmavis can we start with this image and then update it with the video or a different image with the same dimensions later?
![homepage-banner@2x](https://user-images.githubusercontent.com/1068783/57953457-f4e30880-78a4-11e9-9623-2f7a5a8c2b1e.jpg)

**Comment by sabrinang** [comment]
Yup 👍 I was thinking that could be placeholder before we have video ready

**Comment by mmmavis** [comment]
@kristinashu yea that works! Let me know the height specs for each breakpoint then I should be able to get this implementation ticket going!

**Comment by kristinashu** [comment]
Opened a new ticket for implementation, let me know if you need anything else https://github.com/mozilla/foundation.mozilla.org/issues/3178!

**Comment by mmmavis** [comment]
Thanks!
