### ISSUE TITLE
Add tagging to more page types

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#3173]
Right now, Blog pages support tags. Let's add that functionality to Campaign, BanneredCampaign, and Opportunity pages as well.

This furthers the work to be done in #3362

**Comment by kristinashu** [comment]
IHR team is asking for something related to this https://github.com/mozilla/foundation.mozilla.org/issues/3801... they have a series of 3 stories which we've posted as blog posts (ex https://foundation.mozilla.org/en/blog/how-smart-homes-could-be-wiser/). They also have a landing page introducing these stories https://foundation.mozilla.org/privacy-included/. They would like the Related Blog posts at the bottom of a post to show the 2 related stories and also the landing page. So ideally, we tag the 3 blog posts and the landing page with 'Privacy Included' and then 3 of those things show up a the bottom of those 3 blog posts.

**Comment by alanmoo** [comment]
@Pomax You wanna take the lead on this? Let's figure out what the right solution is before building anything.

**Comment by Pomax** [comment]
Can we clarify what the initial work here is to be? The original comment and what the IHR team would like to do sound like two fairly different issues - the original comment is about adding tags to more page  types, while the IHR team wants the related content block on blog pages changed to do something it currently doesn't do.

**Comment by alanmoo** [comment]
IIRC, the idea with the IHR team is to leverage tagging with some unique tags to force specific items to appear on those pages.

This is a bit of a drive-by comment though, part of the work I'd like you to do is to actually dig in and figure out what they're looking for/how we can achieve it without overextending ourselves/writing in super specific logic for this page.

**Comment by kristinashu** [comment]
Also related to https://github.com/mozilla/foundation.mozilla.org/issues/3362

**Comment by Pomax** [comment]
Do we envision us wanting to do related content cross-content-type? E.g. a campaign with tag "X" showing related content that is a blog post that also uses tag "X"? Or do we want related content to be "the same type" so that campaigns only show related campaigns, blog posts only show related blog posts, etc?

**Comment by Pomax** [comment]
I've filed a PR based on some investigatory work on adding tagging to bannered campaign pages, implementing what I think is a reasonable way to make all of this happen, but it might be good to see if this feels right, or whether it feels wrong, before I build it out further.

(It take the "only show related same-page-types" which might be too restrictive... for example, should bannered campaigns not show "regular" campaigns if we add tagging?)

**Comment by alanmoo** [comment]
>(It take the "only show related same-page-types" which might be too restrictive... for example, should bannered campaigns not show "regular" campaigns if we add tagging?)

My guess is that related pages should show all page types, not just "of the same type", since the goal is to show people everything Mozilla is doing/drive engagement.

**Comment by alanmoo** [comment]
This needs a list of what page types need tagging added to them.

**Comment by Pomax** [comment]
closing as old work, let's file a new issue for this, with fresh investigation of the work involved, if we want to surface tags in the future.
