### ISSUE TITLE
Add logo for search results

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#3174]
Currently, a search for mozilla foundation yields the awesome but extinct dinosaur. 

Seems like we can update this via meta info on our site. Info here: https://developers.google.com/search/docs/data-types/logo

cc @kristinashu @alanmoo 

<img width="505" alt="image" src="https://user-images.githubusercontent.com/53411/57940677-00c9cd00-789b-11e9-8346-b60cbce4edf4.png">

**Comment by alanmoo** [comment]
Labeling this Good First Issue because it's not blocking anything else and if anyone feels like figuring it out, a PR would be welcome. @kristinashu is this a good image?

![](https://assets.mofoprod.net/network/images/mozilla-og-image-min.original.jpg)

**Comment by kristinashu** [comment]
Yup!

**Comment by Stark-Pramod** [comment]
@alanmoo I figured it out but I am not sure it will work as I can't test that. So if you allow me  to do some changes I can figure it out.

**Comment by alanmoo** [comment]
I’m happy to take a look at a pull request if you open one. I know it’s near impossible to test, but if you can show me why it has a chance at being successful, I’ll merge it.

**Comment by Stark-Pramod** [comment]
@alanmoo Done. please review the PR.

**Comment by rraue** [comment]
There is a typo in the code, so I see a error in the search console and therefore it won't show up in search. The last element must not end with a ,

**Comment by alanmoo** [comment]
Ah, thank you! @rraue It looks like you're opening a PR for that? I saw the error come through my inbox but haven't had a chance to investigate yet, so this is super helpful!

**Comment by rraue** [comment]
Yes, but I just have the rights to suggest changes, but you took it from there, right? I could work on some extended definitions, as I am dealing with this right now in bedrock anyways: https://github.com/mozilla/bedrock/pull/7364

But one suggestion up front: This piece of code should be just on the homepage, not in the base template. It is not necessary to define it in more than one place, if defined right, its for the whole domain anyways. See https://www.searchenginejournal.com/google-do-not-put-organization-schema-markup-on-every-page/289981/#close

**Comment by alanmoo** [comment]
Great, thanks! I filed #3369, and if you have more to suggest around extended definitions, we'd be open to reviewing PRs- no one on the team has super extensive knowledge in this space, so it would be great to have a conversation.
