### ISSUE TITLE
SEO Improvements to Title & Descriptions

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#3175]
There's some low hanging fruit to improve our SEO. I believe this will improve click thru to our homepage, rank of primary pages, and "site links" when we are a featured result.  

 - root
   - [ ] change title tag from "... - Homepage" to "... - Protect the internet!"
 - descriptions tags
   - [ ] prep unique descriptions for key pages (home, about, initiatives...). 
   - [ ] make fallback description different from homepage
 
cc @alanmoo

**Comment by alanmoo** [comment]
All of these things are achievable in the CMS- just change the Title field on the homepage, and promote fields on the other pages.

**Comment by xmatthewx** [comment]
Yep. Most of the work is in writing the copy. Might want to change fallback description, but that's TBD.

**Comment by jamilasnell** [comment]
@benhohner do you want to talk this one through? Why was this moved out of Icebox?

**Comment by benhohner** [comment]
T'was my accidental clicking. See MELT for more discussion!

**Comment by Pomax** [comment]
can we close this issue and file a new one when there is an SEO strategy that we want to action on?

**Comment by kristinashu** [comment]
Yup, I'll close this. Anil has re-surfaced a request in [Airtable](https://airtable.com/tbljPmOCkK9JShaTS/viwpFvt3FxiVannif/recX3Vd146Z116a1W?blocks=hide) which we can use for the high-level planning of this work.
