### ISSUE TITLE
MozFest: homepage hero banner

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3178]
Styling for the mozfest landing page banner.

**🗒  Design -> Dev Handoff Checklist**

- [x] Design has been finalized
- [x] Link to original design ticket https://github.com/mozilla/foundation.mozilla.org/issues/3172
- [x] Link to Redpen https://redpen.io/p/nt88aa617b390e8eb0
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Assets are included 
- [x] Hover state for elements are designed [n/a]

#### Notes:
- [x] height of the banner can remain at 464px for all screen widths
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/1068783/57939815-f817cd80-787f-11e9-8593-4366b3e32a15.png">

- [x] please mask from center when resizing
- [x] mobile: white cutout box disappears
- [x] image (note that this will be replace with a video later but we will keep the same dimensions)  ![homepage-banner@2x](https://user-images.githubusercontent.com/1068783/57953457-f4e30880-78a4-11e9-9623-2f7a5a8c2b1e.jpg)

**Comment by mmmavis** [comment]
@kristinashu sorry for being back and forth about this - I happened to get the gradient overlay working in CSS 😂 Can you attach the untreated banner image so I can use it as default image?

**Comment by kristinashu** [comment]
Ooooh yes here you go! I might need to adjust the saturation tho once we see it with the CSS gradient.

![no-gradient@2x](https://user-images.githubusercontent.com/1068783/58121701-dc346480-7bbc-11e9-9869-88e4db61f184.jpg)

cc @sabrinang
