### ISSUE TITLE
MozFest: Color palette

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#3179]
@sabrinang anything color variables we should add to the style guide?

**Comment by sabrinang** [comment]
@mmmavis Yes:
![](https://assets.mofoprod.net/network/images/Screen_Shot_2019-04-09_at_5.03.02_PM.original.png)
As seen on https://foundation.mozilla.org/en/docs/brand/design/color/

**Comment by sabrinang** [comment]
add $dark-festival-blue `#0e11bf`

**Comment by mmmavis** [comment]
The three MozFest colour related variables that are currently being used in the codebase have been documented on the [style guide](https://foundation.mozilla.org/en/style-guide/). Closing this ticket now.

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/2896608/58729205-a0a85000-839d-11e9-9b13-9fc5a9f93df5.png">
