### ISSUE TITLE
MozFest: Mobile view sub nav

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/foundation.mozilla.org#3193]
**Describe the bug**
- Sub nav disappears in mobile

**To Reproduce**
Page: https://mozillafestival.mofoprod.net/en/spaces/

**Expected behavior**
Sub nav should show up in a similar way as the foundation.mozilla.org/en/about/ page

**Screenshots**
<img width="785" alt="Screen Shot 2019-05-21 at 4 13 11 PM" src="https://user-images.githubusercontent.com/5816130/58127473-74454480-7be3-11e9-8e8b-78a0c8cef397.png">

**Smartphone (please complete the following information):**
 - Device: any

Page: https://mozillafestival.mofoprod.net/en/spaces/

cc @Pomax

**Comment by Pomax** [comment]
As two different issues, can we split this so that we can write one PR for one issue?
