### ISSUE TITLE
Sub nav at medium widths

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3201]
Sub nav gets a little odd a medium widths (example https://mozillafestival.mofoprod.net/en/spaces/).

Screen cap from prod:
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/1068783/58134730-8e2f5900-7bdc-11e9-9993-b077b3f23f4e.png">

@mmmavis is it feasible to make the nav go onto a new line, something like this? 
<img width="867" alt="image" src="https://user-images.githubusercontent.com/1068783/58134685-70fa8a80-7bdc-11e9-9bd7-943f1f3dcd3d.png">

cc @sabrinang

**Comment by mmmavis** [comment]
> is it feasible to make the nav go onto a new line

I would say no and deprioritize this 😬.

We could simply make the sub nav auto wrap like
![Screen Shot 2019-05-21 at 17 28 24](https://user-images.githubusercontent.com/2896608/58139131-487b8c00-7bee-11e9-963c-892b5a43ec9a.png)

But to achieve the following design it will be a huge lift 
1. each "line" comes with a bottom grey border (we have rewrite the HTML/DOM implementation of the sub nav quite a bit for or this)
2. to make sure there's gap between each line, we have to add padding/spacing to the top of each nav link. This will end up creating extra space in between the intro and sub nav.

Plus we have to QA all the pages that have sub nav to make sure things still look good.

I did a quick test. It seems it's only on 770px-994px wide screen the sub nav looks squishy. So if I could choose I would not bother fixing the nav 😬😬😬

**Comment by kristinashu** [comment]
Okay okay thank you Mavis! I'll close this and reopen it if it becomes worse...

**Comment by kristinashu** [comment]
@mmmavis @sabrinang I think roughly this spacing would work:

<img width="868" alt="image" src="https://user-images.githubusercontent.com/1068783/58216090-bccb3380-7cb1-11e9-94f0-f70b72488054.png">
