### ISSUE TITLE
Add the mozfest-specific GA identifier

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#3203]
Our `analytics.js` currently has a hardcoded UA for the foundation site, which will have to be made a little more modular if we want to support multiple "sites" that all use the same main.js functionality

**Comment by Pomax** [comment]
@alanmoo @cadecairos do we want to introduce a new environment variable here, to be read in during build, or are we cool with simply hardcoding another UA key in main.js and simply looking at whether the content templates say "this is mozfest" vs. not saying anything about which site is being rendered at all?

**Comment by Pomax** [comment]
("wait, hardcoded?" why yes: https://github.com/mozilla/foundation.mozilla.org/blob/master/source/js/analytics.js#L22)

**Comment by alanmoo** [comment]
Env var doesn't feel right, since it's only one build/environment. I think the UA key needs to be embedded in the base template used for the domain, maybe as a new block. If that means GA init code needs to be pulled into the template, so be it?

**Comment by Pomax** [comment]
I can certainly make it a `meta` value in the mozfest base template so that `main.js` can look for it, and if it sees one, use that instead of the foundation identifier to initialize react-ga
