### ISSUE TITLE
Image Text component on mozfest homepage

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3204]
Homepage for mozfest site looked like [this](https://redpen.io/vuefbd37973f0c2a38) because it was based on the main site homepage:
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/1068783/58137051-727c8080-7be5-11e9-8988-b2b42bb9ac2a.png">

But because we decided use the Image Text streamfield component instead the design is a little off (this component was designed for narrow width, not full width):
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/1068783/58137067-7c05e880-7be5-11e9-8c11-9bcff06f4b9d.png">

### Solution?

@youriwims added this very handy checkbox to the Image Grid component that allows images to be square or not: 
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/1068783/58136972-04d05480-7be5-11e9-9c30-584c89f3c28e.png">

Could we do something similar to the Image Text component where there's a check box to determine if the image is 1:1 or 16:9? Or is it more complicated because of the text?
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/1068783/58137557-87f2aa00-7be7-11e9-81d4-89c68334920f.png">

cc @sabrinang @mmmavis @Pomax @alanmoo

**Comment by alanmoo** [comment]
I either don't understand the question or I have no opinions about it. But I'm not sure which. Let's mention this in stand?

**Comment by mmmavis** [comment]
@kristinashu can you make sure this gets mentioned during tmr's MozFest chat after stand? (I don't quite understand this ticket either)

**Comment by kristinashu** [comment]
Yup, let's chat after stand but here's another attempt at explaining it:

Can we add a checkbox to the Image Text component
<img width="574" alt="image" src="https://user-images.githubusercontent.com/1068783/58489323-e1933100-811f-11e9-957d-c7fff61e6a72.png">

So image would be 1:1 or 16:9, so the component would look like

1:1 (default)
<img width="873" alt="image" src="https://user-images.githubusercontent.com/1068783/58489698-a2191480-8120-11e9-9024-a49dec2d18f8.png">

or 16:9 (if unchecked)
<img width="893" alt="image" src="https://user-images.githubusercontent.com/1068783/58489661-9299cb80-8120-11e9-8066-caedd322d9f4.png">
