### ISSUE TITLE
Add external link icon to nav button

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3219]
Add external link icon to nav button when the link is external.

@sabrinang can you please provide an svg of the icon?

Comp:
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/1068783/58217618-6a414580-7cb8-11e9-82a0-4c3dcb079ca7.png">

Prod:
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/1068783/58217625-71685380-7cb8-11e9-875e-7c596c49dae3.png">

**Comment by sabrinang** [comment]
Let's go with external icon with full square (looks better at small size too) and use at 16px inline with buttons. 

Comparison with alternative icon:
<img width="1017" alt="Screen Shot 2019-05-23 at 1 50 07 PM" src="https://user-images.githubusercontent.com/2492510/58287316-9797fd00-7d65-11e9-80a2-bce944969c3c.png">


Exported Black/White svgs here: 
https://drive.google.com/open?id=1sc9am1e190ICxW2MbcWgvVoB95gtrXDy

**Comment by kristinashu** [comment]
"Submit Proposal" is now an internal page so we won't need the icon. But let's keep this open in case we need it for a different CTA. @sabrinang can you think of a future CTA button that would need it?

**Comment by sabrinang** [comment]
I'm assuming tickets will stay internal and schedule, speakers pages have yet to be created but hoping they are internal as well! Not quite sure where the schedule will live

**Comment by kristinashu** [comment]
Ok awesome, let's close this then!
