### ISSUE TITLE
MozFest: Twitter icon in the footer is not quite aligned correctly

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#3227]
Discovered during mozfest review, but also affects the master foundation footer, so this is a cross "site" issue:

![image](https://user-images.githubusercontent.com/177243/58278187-4b8e8d80-7d50-11e9-8735-5edf05d6b389.png)

**Comment by mmmavis** [comment]
Let's chat when you are back from PTO @sabrinang . I highlighted the icon container box in red but I don't know how we wanna fix the alignment with the new icon set.

<img width="169" alt="image" src="https://user-images.githubusercontent.com/2896608/58440461-07bcc080-808f-11e9-9d10-63cfd9945dcf.png">

**Comment by mmmavis** [comment]
Ah I guess I know why - Twitter icon hasn't been updated yet. @sabrinang we should update this icon with the new icon you designed? This will affect Twitter icons on the main Foundation site as well.

<img width="457" alt="Screen Shot 2019-05-28 at 10 26 05 AM" src="https://user-images.githubusercontent.com/2896608/58498516-0f35a580-8133-11e9-9468-96dfc8c9932e.png">

**Comment by sabrinang** [comment]
mentioned in https://github.com/mozilla/foundation.mozilla.org/issues/3117#issuecomment-494934750 this is the folder with the new svg icons: https://drive.google.com/open?id=1sc9am1e190ICxW2MbcWgvVoB95gtrXDy
