### ISSUE TITLE
Remove "mofo-style" from package.json 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#3248]
Seems like we no longer uses `mofo-style`.  Let's remove it from `package.json`.

**Comment by Stark-Pramod** [comment]
Hii @mmmavis I am a newbie in open source. Is this issue is all about removing a single line from package.json ?

**Comment by mmmavis** [comment]
Hi @Stark-Pramod I would run `npm uninstall mofo-style --save` so `package-lock.json` reflects the module changes as well.

https://docs.npmjs.com/cli/uninstall

**Comment by Stark-Pramod** [comment]
@mmmavis Is it done? if not can I do this?

**Comment by mmmavis** [comment]
@Stark-Pramod for sure, feel free to tackle this :)

**Comment by Stark-Pramod** [comment]
@mmmavis Done. Please Review the PR.
