### ISSUE TITLE
MozFest: fav icon and title

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3249]
Please update the fav icon from the m to the mozfest specific one:
[fav icon.zip](https://github.com/mozilla/foundation.mozilla.org/files/3224678/fav.icon.zip)

Is it possible to update the site name from `Mozfest` to `Mozilla Festival`

<img width="392" alt="image" src="https://user-images.githubusercontent.com/1068783/58434415-63c41c80-8070-11e9-86ed-bf2e4ad5a531.png">

**Comment by mmmavis** [comment]
@kristinashu @sabrinang I just checked the main Foundation site, PNI, and mozilla.org... they all use an `.ico` file as the default icon file. To make things consistent I'm guessing we should also include an `.ico` file as well. Can you help me generate the file? Not sure what's the proper way to generating it but I do see a few converters available online.

**Comment by kristinashu** [comment]
Sure, I'll make a higher res png and then try this generator https://www.favicon-generator.org/

It's been so long since we've needed to make a fav icon!

**Comment by kristinashu** [comment]
Hmm ok this site seemed to do a better job https://realfavicongenerator.net/. The .ico might be kinda pixely because it's so tiny but could you try this?

[favicon_package_v0.16.zip](https://github.com/mozilla/foundation.mozilla.org/files/3229879/favicon_package_v0.16.zip)

**Comment by mmmavis** [comment]
[mozilla.org's one](view-source:https://www.mozilla.org/media/img/favicon.d4f1f46b91f4.ico) looks kinda pixelated too so I guess we are good here :satisfied:

**Comment by kristinashu** [comment]
Now that P1's are all done, yay, we can tackle this again... 

For reference, here's the old one https://mozillafestival-org-production.herokuapp.com/ and also how a black icon looks on the dark grey tab:

<img width="314" alt="image" src="https://user-images.githubusercontent.com/1068783/58829960-ff6c0480-85fd-11e9-8eff-f7ef301381f9.png">

@sabrinang I'm thinking maybe we should just use the standard mozilla m. I think us and staff are the only ones who have lots of mozilla tabs open at once so I think it's ok for the average user to see the m. And I don't think we can get the gear icon to look non-pixelated. What do you think?

**Comment by sabrinang** [comment]
Let's stick to m then to align and for simplicity in keeping the contrast too. 
For the title, let's use `Mozilla Festival - MozFest 2019`

**Comment by mmmavis** [comment]
cool I'll update my PR accordingly

**Comment by mmmavis** [comment]
@sabrinang The current pattern of the `title` meta is `Mozfest - <title of the page>`. Just to confirm that we want to replace the beginning `Mozfest` with `Mozilla Festival - MozFest 2019` so it reads `Mozilla Festival - MozFest 2019 - <title of the page>`?

**Comment by sabrinang** [comment]
I was thinking we can follow the convention that Mozilla Foundation site has and have Mozilla name appear in full and not abbreviated for consistency so for the festival the other pages will appear:

`Mozilla Festival - Spaces`
`Mozilla Festival - Team`
`Mozilla Festival - MozFest 2019` I was thinking this only appears on the homepage we previously had it in brackets () but I think it is nice to have the abbreviation/year introduced just here to keep the names clean and short

similar to how we have:

`Mozilla Foundation - Participate`
`Mozilla Foundation - Initiatives`

**Comment by mmmavis** [comment]
kk if that's the case I'll just update the `Mozfest - ` portion to `Mozilla Foundation - `.  Text after the hyphen is not hardcoded and can be customized via the CMS.

**Comment by gideonthomas** [comment]
@sabrinang I'm going to change it to `Mozilla Festival 2019` instead of `Mozilla Festival` as that is what appears in a Google search.
