### ISSUE TITLE
Mismatched configs on Heroku and on env.default

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#3250]
Found a few mismatched configs on Heroku and on [env.default](https://github.com/mozilla/foundation.mozilla.org/blob/master/env.default). There might be more... but I'm just gonna list the ones I discovered:

- `CSP_CHILD_SRC`
- `CSP_FRAME_SRC`

/cc @cadecairos @patjouk

**Comment by cadecairos** [comment]
We can pull in the production CSP Rules and apply them to the default env so things are in sync.
