### ISSUE TITLE
MozFest: Update Submit proposal link

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/foundation.mozilla.org#3256]
The submit proposal button at the top should link to the `/proposals` page (we can probably directly use `https://mozillafestival.org/en/proposals` instead of the mofoprod url.

cc @kristinashu to triage

**Comment by mmmavis** [comment]
@gideonthomas should it link to `/proposals` or `https://mozillafestival.org/en/proposals`???

**Comment by kristinashu** [comment]
Probably safest to link to `/proposals`?

**Comment by gideonthomas** [comment]
@mmmavis this doesn't seem to be in prod...can we do a prod push soon?

**Comment by mmmavis** [comment]
We did a prod push yesterday afternoon so prod should have it now. Let me know if it isn't working for you.
