### ISSUE TITLE
Update Instagram and GitHub icons on main Foundation site's footer.

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#3258]
Related to PR https://github.com/mozilla/foundation.mozilla.org/pull/3257

Now that the Twitter icons (regular / regular on hover / dark theme / dark them on hover) have been updated, we should also replace Instagram and GitHub icons on main Foundation site's footer with the newly designed ones.

/cc @sabrinang to provide link to assets

**Comment by sabrinang** [comment]
Instagram and Github icons in various colours svgs exported here: https://drive.google.com/open?id=14wlqmaJ4rh_ByjPuZo6dqwdK39Akg_cl

**Comment by harshs14** [comment]
@mmmavis can i work on this?

**Comment by mmmavis** [comment]
@harshs14 thanks for offering help! Feel free to take this on if you are already familiar with the codebase and know how to get the site up and running locally :)

**Comment by harshs14** [comment]
@mmmavis I will try to solve it, I need access to the drive to start working on it

**Comment by sabrinang** [comment]
@harshs14 I shared the file with you, let me know if you need anything else or if it doesn't work

**Comment by mmmavis** [comment]
Hi @harshs14 since we haven't heard back from your for two weeks, we are going to take over this ticket :)

**Comment by mmmavis** [comment]
@sabrinang are we supposed to use the 16x16px icons for footer? The ones you included in Google Drive are 24x24. If it's simply scaling the icons down I can just modify the SVG source code so they are set to `<svg width="16" height="16" ...>`. Let me know!
