### ISSUE TITLE
MozFest: video background on homepage

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3259]
From what I understand, the mozfest team would like to have the similar looping video background like last year: https://mozillafestival-org-production.herokuapp.com/

@gideonthomas @sabrinang is this still the case?

If so, we could use last year's video until they make a new one. @mmmavis do you see any issues in replacing the static image background with a video backgroud? The aspect ratio is slightly different than the current image but it's pretty similar. 

My only concern is that the video is 14.8 MB which seems unfair to make people download?

Note: mobile would show a static image.

[mozilla-festival_home-page-video-cut.mp4.zip](https://github.com/mozilla/foundation.mozilla.org/files/3229467/mozilla-festival_home-page-video-cut.mp4.zip)

**Comment by gideonthomas** [comment]
Just want to clarify that even if we want to do this, def not for June and it's a lower priority.

@sabrinang can make the call here if it makes sense and is the best UX.

**Comment by kristinashu** [comment]
Closing as "won't fix"
