### ISSUE TITLE
Old Safety First campaign

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3260]
We've made a page on the [Foundation site for the old Safety First campaign](https://foundation.mozilla.org/en/campaigns/safety-first/). 

@cade @patjouk could you please redirect the relevant urls there (sorry, I'm not sure what the original url was)?

But Brett would still like to keep https://advocacy-mozilla-org-prod.herokuapp.com/en-US/safety? Is that ok or is that what you're trying to avoid?

cc @xmatthewx

**Comment by cade** [comment]
> sorry, I'm not sure what the original url was

I think the original url is [here](https://www.youtube.com/watch?v=dQw4w9WgXcQ). Is that right, @cadecairos?

**Comment by cadecairos** [comment]
wow, it's been a while @cade! That's definitely the right link.

**Comment by kristinashu** [comment]
Nooooo! How do I keep doing that!

**Comment by cadecairos** [comment]
I'm going to listen to the whole song 🎵

**Comment by cadecairos** [comment]
regarding the redirects, we'll need to look into how we're handling the redirect for `advocacy.mozilla.org` and whether or not it's a simple task to special case redirect specific urls.

@patjouk when you get online can you check if we're using mofo-redirector for this or if it's a CloudFront/S3 redirection setup?

**Comment by patjouk** [comment]
It's a cloudfront/s3 redirect.

About keeping advocacy up: every website that we keep online needs to have a maintenance/support plan. We need dev time to go and update dependencies from time to time to avoid security issues (which doesn't seem to be happening right now), and ops time for when the site goes down. Keeping something up cost money, which is not really a problem here (7$ per month for Heroku).
Do we have a plan and time to maintain it @alanmoo ?

**Comment by alanmoo** [comment]
Once we've got the content moved over for all the sections of the advocacy site that we plan to move and redirects are doone, we should take the old domain down. It'll still be in github if somoeone else wanted to spin it up somewhere. One of our OKRs is about spinning down old sites, so we have no reason to keep this running.

**Comment by xmatthewx** [comment]
Feel free to ignore me: If Brett has a heroku account, is it trivial to push a button a transfer the app to him?

**Comment by patjouk** [comment]
@alanmoo Do we keep track somewhere of the campaigns that still need to be moved?

**Comment by patjouk** [comment]
Redirect is done :) http://advocacy.mozilla.org/en-US/safety => https://foundation.mozilla.org/en/campaigns/safety-first/
