### ISSUE TITLE
Make Mozfest template pull in meta content from Promote tag

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#3261]
It looks like the OG tags aren't rendering in the Mozfest template from the Promote tab like they do for the Foundation site. Let's make that happen.

**Comment by mmmavis** [comment]
MozFest pages ["inherit"](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/mozfest/models.py#L15) (not sure what the proper tech term is to use here) [`FoundationMetadataPageMixin`](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/models.py#L61-L108) and hence _should_ be pulling Promote tab stuff and render them as `og` tags... I don't know Django enough to tell what's missing here and why it's not working 😬 . Thoughts @alanmoo ?
