### ISSUE TITLE
Adjust h4 line-height style for desktop/mobile

### ISSUE THREAD

**Issue by natalieworth** [mozilla/foundation.mozilla.org#3270]
We need to update the h4 line-height for [brand standards](https://foundation.mozilla.org/en/style-guide/). These updates will be applied to both the Foundation site and the Pulse site (and any future h4 uses). 

Currently our Sketch library is updated and has h4 set to desktop 24px/30px and mobile at 22px/28px. **So could we update the line-height of desktop h4 to 1.25 and mobile to 1.28?** This would apply across all our brand standards (both the Foundation and Pulse site).

- [ ] Update the code of [Mozilla Style Guide](https://foundation.mozilla.org/en/style-guide/)
- [ ] Update line-heights on the Foundation Site (if needed)
 
------

[Design/ original ticket is here.](https://github.com/MozillaFoundation/Design/issues/357)

---

Redpen document/ examples are here: https://redpen.io/p/gk2682339c5647f381

---

**🗒  Design -> Dev Handoff Checklist**
(Feel free to remove items that are not applicable.)

- [x] Design has been finalized
- [x] Link to original design ticket
- [x] Link to related ticket
- [x] Link to Redpen
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included

**Comment by natalieworth** [comment]
cc @mmmavis @youriwims @alanmoo

**Comment by mmmavis** [comment]
@natalieworth I'm removing the `Update line-heights in Pulse (if needed)` checkbox from this ticket as there's a ticket on Pulse repo for it.
