### ISSUE TITLE
Create Mozfest 404 page

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#3275]
If someone hits a 404 on Mozfest, they should see the error message in a Mozfest header/footer instead of the foundation site's.

**Comment by alanmoo** [comment]
@Pomax Any thoughts on how this might work? I couldn't figure out how we can change the template based on the request domain.

**Comment by Pomax** [comment]
I can't see to find any documentation on how to achieve this, so I've posed https://stackoverflow.com/questions/56449188/having-a-404-for-each-site-in-a-wagtail-multisite-setup and hopefully there is a way to easily achieve this, I just can't find what it is.

**Comment by Pomax** [comment]
unblocked by https://github.com/wagtail/wagtail/pull/5375/files
