### ISSUE TITLE
signup_submission has issues

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#3279]
Issue 1: Payload not verified

Steps to reproduce the behaviour:
1. `curl -X POST https://foundation.mozilla.org/api/campaign/signups/1/`

Generates a 500 internal server error because the payload is not checked: https://github.com/mozilla/foundation.mozilla.org/blob/1e460eb24f8d011941791f835e3d2b6cd3f0a19b/network-api/networkapi/campaign/views.py#L86-L93
 
Issue 2: CSRF token not required

Steps to reproduce the bahaviour:
1. `curl --request POST --header 'content-type: application/json' --data '{"email": "test@example.com","source": "Curl test"}' https://foundation.mozilla.org/api/campaign/signups/1/`

The post request succeeds, yet it should fail. we need to render the CSRF token in the form and subit it, as well as verify it in the view.

**Comment by kristinashu** [comment]
cc @alanmoo @Pomax

**Comment by alanmoo** [comment]
Neat bot!

**Comment by kristinashu** [comment]
🤣
