### ISSUE TITLE
Dynamic Mozfest header nav

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#3289]
The nav on the mozfest site is static, but thinking ahead, we want to make it dynamic to support adding and removing sections without the need for a code change.

**Comment by alanmoo** [comment]
This will be useful once the inevitable "tickets are no longer available, let's take that page off the nav" or "add this other page to the nav!" asks come in.

**Comment by Pomax** [comment]
This is relatively easy to do (we didn't do it earlier mostly due to time constraints)
