### ISSUE TITLE
Confirm deadness of and remove vestigial file

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#3296]
**Describe the bug**
The [signup component](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templates/wagtailpages/tags/cta/signup.html) previously used in the Opportunity page templates appears to be vestigial. This needs to be confirmed and any dead code around it should be shaken out.

**Comment by Sharma-palak** [comment]
Hi @alanmoo ,i am new to open source ,can I take this issue??

**Comment by alanmoo** [comment]
You're welcome to open a PR if the description is clear enough, but I don't have capacity to support figuring out what needs to happen right now.

**Comment by Sharma-palak** [comment]
ok @alanmoo , I want to give it a try.

**Comment by youriwims** [comment]
@alanmoo as far as I can tell, it looks like this is currently in use on two bannered campaign pages:

1. https://foundation.mozilla.org/en/fellowships/newsletter/
2. https://foundation.mozilla.org/en/newsletter/

But they don't appear to be _real_ pages...or are they?

**Comment by alanmoo** [comment]
Those are very real, but are you sure that code is used? I thought they're using [this code](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templates/wagtailpages/bannered_campaign_page.html#L64-L71) to render the div that React hooks into (notice the extra data attributes.)

In addition, (this file)[https://github.com/mozilla/foundation.mozilla.org/blob/master/source/js/basket-signup.js] is another one I'm suspect of its actual use these days (and the one I was thinking might actually be useful in Pulse, @mmmavis )

**Comment by youriwims** [comment]
Okay, makes more sense. Yeah, it doesn't look like basket is being used anymore either.

**Comment by alanmoo** [comment]
![](https://media.giphy.com/media/65NO1TrKrJUT6/giphy.gif)
