### ISSUE TITLE
MozFest twitter feed doesn't show up

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/foundation.mozilla.org#3297]
**Describe the bug**
The twitter feed on the mozfest homepage doesn't show up. Error in the console is: "The resource at “https://platform.twitter.com/widgets.js” was blocked because content blocking is enabled." THis happens only in firefox from what I can tell

**To Reproduce**
1. Go to https://mozillafestival.org
2. Scroll down to the end of the page
3. See error

**Screenshots**
![Screen Shot 2019-06-05 at 3 50 44 PM](https://user-images.githubusercontent.com/5816130/58985801-28c99380-87aa-11e9-94b0-e28b0ce6714d.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version 67.0

cc @alanmoo

**Comment by alanmoo** [comment]
I see it on FF 67, macOS...

**Comment by gideonthomas** [comment]
Do you have tracking protection on?

I'm also not sure if there is anything that can be done about it fyi

**Comment by alanmoo** [comment]
I can replicate when I turn on strict content blocking. This is expected behavior unless we rewrite a twitter feed component ourselves.

**Comment by gideonthomas** [comment]
cc @zee-moz doesn't look like we can do anything about it. However, the link that you see will take you to twitter, so it isn't completely broken.

**Comment by alanmoo** [comment]
(When you turn on  content blocking Firefox, there’s a big warning that parts of some websites may not work.  This is exactly the type of thing  it was referring to.)
