### ISSUE TITLE
Mobile version primary nav - active link treatment

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#3298]
Not sure if this is a bug. @kristinashu do you know what the expected on hover treatment is for `active page link` on mobile version of primary nav (e.g, "Home" in the attached gif below)? Currently we add a black underline to it on hover which doesn't make any visual difference since the whole nav section on black background.

![mobile-nav-active-hover](https://user-images.githubusercontent.com/2896608/58992362-7a205580-879f-11e9-908e-dd96091b363f.gif)

**Comment by kristinashu** [comment]
Thanks Mavis, yeah we should add a selected state.

I've also noticed the gaps are a little big at medium widths:

<img width="984" alt="image" src="https://user-images.githubusercontent.com/1068783/58993155-86a5ad80-87a1-11e9-8d2a-aece894407a9.png">

**Comment by kristinashu** [comment]
Sorry, I don't think I really answered your question. To close this ticket please:
- [ ] Add a Selected state that looks like the Hover state
- [ ] Update the bar to be white
- [ ] Update the bar to be 3 px
- [ ] Update the bar to be closer to the text

But let me know if any of this would be tough to do!

<img width="398" alt="image" src="https://user-images.githubusercontent.com/1068783/61891546-bd08ca80-aebe-11e9-8153-8f47578ad6e2.png">
