### ISSUE TITLE
Add Bold Styles to Style Guide

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#3303]
After deciding on how we want to handle bold styles in this ticket: https://github.com/MozillaFoundation/Design/issues/353 we need to add them to the style guide.

Redpen here: https://redpen.io/kd3d58a3e4da0a839c

---

**🗒  Design -> Dev Handoff Checklist**
(Feel free to remove items that are not applicable.)

- [x] Design has been finalized
- [x] Link to original design ticket
- [x] Link to related ticket
- [x] Link to Redpen
- [x] Design changes been merged into the master Sketch file

**Comment by mmmavis** [comment]
@beccaklam what kind of bold text examples do you think we should add to this [style guide](https://foundation.mozilla.org/en/style-guide/)?

**Comment by beccaklam** [comment]
We could just add an example of what the bold styling would look like if the base paragraph text was .body and .body-large

**Comment by youriwims** [comment]
@mmmavis So, I shouldn't add an example of all the updated bold typography? Also, what do you think would be the best way to implement this?

**Comment by mmmavis** [comment]
@youriwims 

what do you mean by
> an example of all the updated bold typography

**Comment by youriwims** [comment]
Based on the links in the initial comment, I saw that we have bold styles for all type in our style guide now. So, I wanted to clarify that I'm _only_ supposed to update the style guide to include `.body.bold` and `.body-large.bold` based on the [comment](https://github.com/mozilla/foundation.mozilla.org/issues/3303#issuecomment-519187914) above.

**Comment by mmmavis** [comment]
I'm thinking if we can just update the Paragraph section in `styleguide.html` to

```html
<h3 class="h2-heading mt-5">Paragraphs</h3>
  <hr />
  <div class="py-2">
    <p class="body-large">.body-large with <b>bold</b> text</p>
  </div>
  <div class="py-2">
    <p class="body">.body with <b>bold</b> text</p>
  </div>
  <div class="py-2">
    <p class="body-small">.body-small <b>bold</b> text</p>
  </div>
  ...
  ...
```
Then we should be good

<img width="362" alt="image" src="https://user-images.githubusercontent.com/2896608/62664303-f1a16b00-b92f-11e9-832a-f880a9d52a05.png">

**Comment by mmmavis** [comment]
We might wanna wait till @beccaklam is back to review the PR though as I'm not 100% sure what reference would be useful for designers.

**Comment by mmmavis** [comment]
@beccaklam let's chat when you are back before we implement this. @youriwims and I are confused by the annotation on Redpen. For example, what are the use case of a bolder version of `h1-heading`?

**Comment by beccaklam** [comment]
@mmmavis I'm back! Feel free to schedule a meeting, my calendar is up to date :)

**Comment by mmmavis** [comment]
@beccaklam oops I'm having hard time remembering who's on PTO or not 😂 Will send invite.

**Comment by mmmavis** [comment]
@youriwims @beccaklam - sorry for being back and forth on this. I re-read this ticket again and am now wondering if we really should add bold examples to the site's [style guide](https://foundation.mozilla.org/style-guide/) (since we are just using the default bolding behaviour)

To make things less confusing and to discourage bolding heading, I think we should **not** add bold text examples for heading classes.

If it's useful, we can add bold text examples for `.body-large`,`.body`, and `.body-small` like below.

<img width="353" alt="image" src="https://user-images.githubusercontent.com/2896608/62896725-7ad8e900-bd06-11e9-8f2e-139889e713ae.png">

Let me know what you think! 😉

**Comment by youriwims** [comment]
I agree with you @mmmavis. This may be slightly outside the scope of this ticket, but how are we going to discourage or prevent Wagtail users from bold-ing headings?

**Comment by mmmavis** [comment]
@youriwims 

> how are we going to discourage or prevent Wagtail users from bold-ing headings

I don't think we can prevent Wagtail users from doing it 😬 I just thought we shouldn't set an example in style guide as it could encourage people to use it.

**Comment by youriwims** [comment]
Ah ok, gotcha 👍

**Comment by beccaklam** [comment]
@mmmavis and @youriwims Yeah that's fine!

**Comment by youriwims** [comment]
@mmmavis I just realized that you may have made the updates in the example [here](https://github.com/mozilla/foundation.mozilla.org/issues/3303#issuecomment-520588417) in the devtools and not in the codebase 🙈. If so, let me know, and I can open a pr to push up the changes we talked about :) 👍

**Comment by mmmavis** [comment]
@youriwims I just opened up a PR for you to review!
