### ISSUE TITLE
Update Dev Style Guide with new button styles

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#3311]
We have some new button styles that have been added to the brand and it would be good to have then reflected in the Dev style guide too!

Related ticket: https://github.com/MozillaFoundation/Design/issues/371
Brand Documentation: https://foundation.mozilla.org/en/docs/brand/
Redpen: https://redpen.io/p/knefb82f90a4716342 (though, Brand documentation is probably the most up to date)

---

**🗒  Design -> Dev Handoff Checklist**
(Feel free to remove items that are not applicable.)

- [x] Design has been finalized
- [x] Link to original design ticket
- [x] Link to related ticket
- [x] Link to Redpen
- [x] Design changes been merged into the master Sketch file
- [x] Assets are included
- [x] Hover state for elements are designed

**Comment by beccaklam** [comment]
Assets here: [social-button-icons.zip](https://github.com/mozilla/foundation.mozilla.org/files/3273188/social-button-icons.zip)

**Comment by mmmavis** [comment]
@beccaklam for "dev style guide" did you mean https://foundation.mozilla.org/en/style-guide/? If so we should create a new ticket for designers to update this page: https://foundation.mozilla.org/en/docs/brand/ (currently empty)

**Comment by mmmavis** [comment]
@beccaklam ^

**Comment by mmmavis** [comment]
Closing this ticket.

"Share Button Group" has been added to "dev style guide" (https://foundation.mozilla.org/en/style-guide/). For design details like margin in between two buttons should be x pixels etc I think we should mention them on the brand doc instead (https://foundation.mozilla.org/en/docs/brand/) as they are more of general design guidelines.
