### ISSUE TITLE
Implement In-line Icon Button Style

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#3321]
We have defined some new button styles (more like filling in gaps we had before in our style guide) and they need to be implemented!

## In-line Icon Button

- [x] Icon should be 16px in height, width can vary (with 16px of spacing between the grouped icon and label and the right/left edges of the button, see grouped buttons ticket for reference: #3322)

- [x] Icon should be spaced 8px from the label

- [x] Label and Icon should then be grouped and centered in button
![in-line-icon-button](https://user-images.githubusercontent.com/20977376/59221305-f3032100-8b94-11e9-9e57-f21dede3f71b.jpg)

Related ticket: MozillaFoundation/Design#371
Redpen: https://redpen.io/p/knefb82f90a4716342

---

**🗒  Design -> Dev Handoff Checklist**
(Feel free to remove items that are not applicable.)

- [x] Design has been finalized
- [x] Link to original design ticket
- [x] Link to related ticket
- [x] Link to Redpen
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Hover state for elements are designed

**Comment by mmmavis** [comment]
@beccaklam other than social share buttons, are there any existing "inline button" on the site that need to be updated for this ticket?

**Comment by beccaklam** [comment]
@mmmavis The only other button that has an inline icon I can think of is the button for external links but there's some conversation going around that right now here in this ticket: https://github.com/MozillaFoundation/Design/issues/372 Is it a blocker for you to land the social buttons first?

**Comment by mmmavis** [comment]
> Is it a blocker for you to land the social buttons first?

@beccaklam not at all. I prefer having these button tickets to focus on just the 'share buttons'.

**Comment by beccaklam** [comment]
Yes, let's land those first then since we use them quite a lot 👍

**Comment by mmmavis** [comment]
Re-opening as there might be more in line buttons on the site that we need to update style for.

**Comment by kristinashu** [comment]
@mmmavis is there more to do for this ticket?

**Comment by mmmavis** [comment]
Just did a quick audit and things all look fine. Gonna close this ticket!
