### ISSUE TITLE
Reactivate donate popup

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3324]
Reactivate the donate popup the same as it was before but will new copy.

### Copy (WAITING FOR APPROVAL)
> Big corporations try to restrict how we access the web. 

> Misinformation makes it harder for us to find the truth. Web-connected devices go to market without basic security standards. 

> The non-profit Mozilla Foundation fights for a healthier internet. Will you donate today?

Where "Will you donate today?" is in bold.

### Comp
https://redpen.io/ps2f6569e046e136bf

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/1068783/59299243-08358980-8c41-11e9-9b18-5e81c8247530.png">

**Comment by Pomax** [comment]
I also remember @xmatthewx saying we wanted to have it be dismissable for at most a week, so I will change the session storage approach to a localstorage approach instead, and then if people dismiss the banner, they will see it again one week later (if they happen to load up the site again =)

**Comment by kristinashu** [comment]
Yes! That would be much less annoying.

**Comment by Pomax** [comment]
Do we still want a 10 second timeout, or do we want to "tighten that up"?

**Comment by kristinashu** [comment]
10 sec is good! Want them to spend some time on the site before we ask them for money.
