### ISSUE TITLE
Foundation website uses non-brand body font

### ISSUE THREAD

**Issue by fitojb** [mozilla/foundation.mozilla.org#3326]
The Foundation website uses Nunito Sans as body font, which has never been prescribed as part of the brand narrative for Mozilla (neither as part of Quantum nor as part of Trailhead).

The body font should be replaced with _Inter_ [(reference)](https://github.com/mozilla/protocol/issues/342#issuecomment-475324102).

**Comment by kristinashu** [comment]
Thank you @fitojb for raising this but [Mozilla Foundation branding](https://foundation.mozilla.org/en/docs/brand/design/Typography/) is different and independent than Mozilla Corporation, Quantum, and Trailhead since we have a different audience and needs.
