### ISSUE TITLE
Related blog posts image is cropped poorly

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#3349]
**Describe the bug**
[Related posts on a blog page](https://foundation.mozilla.org/en/blog/7-interesting-things-we-learned-when-we-ask-world-about-misinformation-online/) crop the promotional image poorly

**Expected behavior**
The cropping should not interfere with the Mozilla logo

**Screenshots**
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/1682681/60119174-ced64100-974b-11e9-895a-8b70e3b064ff.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Browser: Safari
 - Version 12.1.1

**Comment by Pomax** [comment]
No code required: remember to set a focal point on images. I've added one for the image we were using and it now looks perfectly fine:

<img width="1191" alt="Screen Shot 2019-07-09 at 1 43 31 PM" src="https://user-images.githubusercontent.com/177243/60921524-95272f00-a24f-11e9-8981-55136c3a1171.png">
