### ISSUE TITLE
clean up <a href="#">

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#3366]
Under HTML5 rules, the `<a>` element is a purely navigational element, and adding `href="#"` tells the browser to navigatet to the top of the document, which is almost never the intended behaviour when `<a href="#">` is used, so let's find all instances of `<a href="#" ...>` and make sure we replace them with correctly semantically marked up code instead (which will almost always be `<button>`)

Marked as small effort, but this might turn out to be an invalid assessment.

**Comment by aayushbisen** [comment]
Hey @Pomax 👋 Can I work on this issue?

**Comment by Patil2099** [comment]
Can I work on this if it is still open? @Pomax

**Comment by Patil2099** [comment]
@Pomax  I found all <a href="#">
First in product_page.html(Line 43)
Second in blog_card.html(Line 8)
Third in styleguide.html (Line 153)
Forth in Share-button-group.jsx (Line 114)
Can you Help me in Getting the correct links ? So that I can place them ?

**Comment by Pomax** [comment]
The idea is to replace them with "not `<a>` elements" since they're not navigations anchors - semantically anything that is a clickable and doesn't navigate is a button, so every link that's just `#` should be evaluated on a case-by-case basis. This might not be a very good contributor issue, given that our team is very small and there isn't enough free time to make contributors familiar enough with how we combined django/wagtail and React to make a well informed decision on what to replace each `<a>` with.

**Comment by snowmanstark** [comment]
@Pomax @alanmoo is anyone assigned to work on this issue?

**Comment by Pomax** [comment]
No one is assigned this issue at the moment, but we do not have the capacity to walk you through the codebase, and replacing these links with the correct semantic equivalent and the correct classes such that it conforms to the styleguide without breaking functionality means this is not "just replacing `<a>` with `<button>`". There's a lot more work that would have to go into this, which is why the "contributors welcome" label was removed.
