### ISSUE TITLE
Decide active button's hover state

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#3367]
When we implemented our button styles I think we only covered "normal" button's hover state.

Using `btn-secondary` as an example, because we didn't override the styling ourselves an "active" `btn-secondary` button's hover state is purple... which is probably not something we want

<img width="272" alt="image" src="https://user-images.githubusercontent.com/2896608/60619792-43cdfa00-9d8e-11e9-8a74-cb04faeb3b70.png">

---

Some context...

Q: When does a button become "active"?
A: 
> The `:active` CSS pseudo-class represents an element (such as a button) that is being activated by the user. When using a mouse, "activation" typically starts when the user presses down the primary mouse button.

More details on [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:active).

**Comment by kristinashu** [comment]
For simplicity I'd recommend we use the same style for "active" state as we do for a button's "hover" state. @mmmavis @sabrinang @natalieworth you ok with that or have another idea?

**Comment by sabrinang** [comment]
Hmm, there won't be much visual difference then if _active_ is the same as _hover_  though?
To keep it with the limited color scheme for light theme, we can consider using $light-blue and for dark theme, we can consider $dark-blue for active states since it's the only other blue that's not being used in each theme. That's the only other idea I have without introducing new colours or shade/tints to the button set.

**Comment by kristinashu** [comment]
That sounds good for blue buttons but any suggestions for the black/white buttons? Maybe the fill turns `Gray 60` for regular and then `Gray 20` for dark theme? I think we can exclude the pop button since I don't _think_ we're using it anywhere right now.

**Comment by sabrinang** [comment]
I cleaned up doc so all button states are adjacent to compare:
<img width="705" alt="Screen Shot 2019-09-04 at 12 45 44 PM" src="https://user-images.githubusercontent.com/2492510/64286420-47a70580-cf12-11e9-8c1d-bd5ea75b06b6.png">

Ready for review and give feedback redpen here: https://redpen.io/ru6635ba6cf3bd6e12

**Comment by sabrinang** [comment]
@kristinashu 
Design R?

**Comment by kristinashu** [comment]
R+

Note the dev that social share buttons would follow the secondary button styles.

**Comment by sabrinang** [comment]
Great, added implementation issue #3608 – closing this design issue.
