### ISSUE TITLE
Ensure Organization Schema markup is only on homepage

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#3369]
**Describe the bug**
From [this comment](https://github.com/mozilla/foundation.mozilla.org/issues/3174#issuecomment-508458669), we should only have the organization schema JSON on the homepage, not every page on the Foundation site. So, we should move that block from the base template to the homepage template.

**Comment by Stark-Pramod** [comment]
@alanmoo ok, I was on this issue better I should complete this.

**Comment by alanmoo** [comment]
You're welcome to open a PR

**Comment by Shubhamchinda** [comment]
Hey @alanmoo , Can I take this ?

**Comment by alanmoo** [comment]
You're free to open a PR if you have enough information, but I don't have bandwidth to assist other than reviewing it.

**Comment by Stark-Pramod** [comment]
@alanmoo sorry, Actually I got some stuff to do that's why I got busy, otherwise, I would have done it for sure.
