### ISSUE TITLE
/blog page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3370]
Related design ticket https://github.com/mozilla/foundation.mozilla.org/issues/3165
Related implementation ticket for /blog?tag=[name] #3371
Related blog epic ticket https://github.com/mozilla/foundation.mozilla.org/issues/2797

### The following should follow the same rules as our existing related posts
- image pulled from "promote" tab, if no image than it's the generic m image
- hover states
- font styles
- responsive states
- grid

### Other notes
- blue text is the first tag listed for that post
- "see more" button loads another 9 posts below (example https://thewirecutter.com/blog/)
- Blog will not appear in the main nav until we have more posts (people will only discover /blog if they type it in) 

### Note from @alanmoo (please edit as you see fit): 
My instinct is to make the "blog" page a generic page type that shows the preview of all its children pages, so that we can use it for other page types like an Advocacy campaigns index. But because pages would have different types (example: blog cards show a tag and advocacy _might_ not), I believe we could embed a check in the page where, if the card is a blog, we show some extra information.

### Comp
https://redpen.io/mo33ed7416a225ea57
![](https://s3.amazonaws.com/redpen-prod/red-pen-f9907975-3d42-4650-d6f5-40bed074e08c.jpg)

**Comment by alanmoo** [comment]
See also [this issue] for some more functionality that will likely need to get built into this page template.
