### ISSUE TITLE
Page for /blog?tag=[name]

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3371]
Blocked by related implementation ticket for /blog page #3370

Related design ticket https://github.com/mozilla/foundation.mozilla.org/issues/3165
Related blog epic ticket https://github.com/mozilla/foundation.mozilla.org/issues/2797

- styles should follow the /blog page
- should show the number of results and the selected tag (should match the same style as on pulse)
- clicking `clear filter tag` should show users /blog

### Comp
https://redpen.io/ztf6d6d69bc4aa274f

![](https://s3.amazonaws.com/redpen-prod/red-pen-40388170-6400-40e5-cd45-dfbad50c1f1b.jpg)

cc @alanmoo

**Comment by alanmoo** [comment]
This will likely be a part of the same template as the main blog page, as some extra functionality supported by query parameters or something like that.

**Comment by Pomax** [comment]
Given that results will be paginated, how do we want to indicate this? E.g. "Showing 12 of 50 results found", and updating that value as the user clicks "load more results"?

**Comment by Pomax** [comment]
Also, given that the tag filtering is now a properly different URL, `clear filters` is probably either no longer necessary, or needs a design tweak. The base page is still `/en/blog` but the filtered pages now (necessarily) live on `/en/blog/tags/(tags)`, so "clearing" is actually a navigation to `/en/blog`
