### ISSUE TITLE
Add localization support for ShareProgress buttons in petition snippets

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#3377]
**Describe the bug**
We need to be able to add a different URL for each shareProgress button in different languages.

**To Reproduce**
1. Edit a petition
2. Note the Share link fields aren't localized
<img width="929" alt="image" src="https://user-images.githubusercontent.com/1682681/60828352-2c24b600-a180-11e9-82d4-34a3fae9bfb2.png">

**Expected behavior**
When toggling languages, a URL field for the share link should exist for each supported language

**Comment by alanmoo** [comment]
@TheoChevalier This has landed on master, will be live by Monday morning EDT, maybe earlier.

**Comment by TheoChevalier** [comment]
> @TheoChevalier This has landed on master, will be live by Monday morning EDT, maybe earlier.

Yay! Thanks so much folks!
