### ISSUE TITLE
Remove `featured` property from News model

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#3379]
Do-over of https://github.com/mozilla/foundation.mozilla.org/issues/721, which ran into enough problems that it's far easier to retry this "fresh" than it is to continue adding to that issue.

**Comment by Pomax** [comment]
as far as I can tell we already removed all use of the news.featured flag, so the only work left here is a PR that removes the field itself.

**Comment by alanmoo** [comment]
![dragons](https://user-images.githubusercontent.com/1682681/60987370-74bea980-a30f-11e9-9756-9787eb815b19.jpg)

**Comment by Pomax** [comment]
estimated 1 because the work's technically already done...

**Comment by alanmoo** [comment]
![image](https://user-images.githubusercontent.com/1682681/62656711-d2f0a380-b932-11e9-96ef-3bb112cb0932.png)
