### ISSUE TITLE
Make the main CTA button for MozFest CMS editable

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/foundation.mozilla.org#3424]
<img width="1438" alt="Screen Shot 2019-07-16 at 2 55 15 PM" src="https://user-images.githubusercontent.com/5816130/61321604-e0a28580-a7d9-11e9-9a30-c039165b87e1.png">

We will need to update the text and link of the button on the top-right when ticket sales open up, the schedule goes live, and after the festival.

Alan mentioned that it would be useful to make it CMS editable so that we don't have to change it every time (including next year).

cc @alanmoo and @kristinashu to triage. The first update needs to happen by the first week of August.

**Comment by alanmoo** [comment]
@kristinashu Any design requirements for this other than "be able to update the text and the URL"?

**Comment by kristinashu** [comment]
Nope but I would like to clarify that this is only for the MozFest site. Buttons on the main foundation site are much more fixed and the average Wagtail staff should not be able to update them.

**Comment by alanmoo** [comment]
I'd guess we probably want to use [Site settings](https://docs.wagtail.io/en/v2.5.1/reference/contrib/settings.html) for this.

**Comment by Pomax** [comment]
I'd like to clarify: does the _text_ change, or does the _button_ change? Because if the text changes from "submit proposal" to "buy tickets", then really that's a different button, and it might make more sense to define a collection of buttons of which only one can be picked to show up on the homepage at a time, similar to "news items" or "campaign CTAs" on the foundation site.

**Comment by alanmoo** [comment]
Good point. The button changes.

**Comment by Pomax** [comment]
sounds good

**Comment by Pomax** [comment]
Do we want it to point to "any URL", or should it point to a specific mozfest app page? (e.g. should people type the URL and hope it's right, or should they be able to pick a page in the CMS and the button will point to that page, whatever its URL happens to be?)

**Comment by alanmoo** [comment]
I imagine it could be external links, so url string

**Comment by mmmavis** [comment]
A design question for you @sabrinang : do we want the nav CTA button (text + link) to stay the same across the site? Or allow each MozFest page to configure the button so it can link to different URL?

**Comment by sabrinang** [comment]
@mmmavis Keep the same nav CTA button to be consistent across the site.
