### ISSUE TITLE
Fade in/out effect for sticky share buttons on blog page

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#3425]
Follow-up from PR https://github.com/mozilla/foundation.mozilla.org/pull/3383

Currently we hide sticky buttons on the side when the bottom share buttons are scrolled into the viewport.

From Pomax's [comment](https://github.com/mozilla/foundation.mozilla.org/pull/3383#issuecomment-511958894) in the PR

> do we want to make the buttons fade out/in rather than abruptly existing, though? It might be jarring to readers to have them suddenly exist or be gone?

@beccaklam thoughts?

**Comment by beccaklam** [comment]
@Pomax @mmmavis I can't see staging anymore but fade in/out sounds good 👍 Thanks for catching that Pomax.

**Comment by mmmavis** [comment]
hey @beccaklam by "staging" you mean "review app"? Review app is the app that's generated with every PR and self destruct when the PR gets merged 😉

Changes have been pushed to **staging** (https://foundation.mofostaging.net). Blog example on staging can be found [here](https://foundation.mofostaging.net/en/blog/amazon-require-privacy-policies-internet-connected-devices/)

**Comment by beccaklam** [comment]
@mmmavis Oh I see ... thanks :) Just checked it out. I think fading in/out would be a nice transition effect!

**Comment by mmmavis** [comment]
I'm gonna move this ticket to this sprint 'cuz I've got a PR up for this already 😉
