### ISSUE TITLE
MozFest 404 page doesn't work

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/foundation.mozilla.org#3433]
**Describe the bug**
We landed a new 404 for the MozFest site (https://github.com/mozilla/foundation.mozilla.org/issues/3275). But, it doesn't seem to work

**To Reproduce**
1. Go to https://www.mozillafestival.org/en/sdasdada/
2. See the fo'mo 404 page

cc @patjouk who reported it for any more relevant details that I might have missed. and @Pomax

**Comment by patjouk** [comment]
I took a quick look at it and I'm wondering if the site hostname isn't `www.mozillafestival.org` instead of `mozillafestival.org` 🤔
