### ISSUE TITLE
Explore next steps for blog

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3434]
Create some exploratory mock-ups to help visualize possible new blog features and next steps. This will also to help guide @anilkanji on conversations with program staff.

### Ideas to explore
- Post detail page: add comments
- Featured post thumbnails for: 
  - homepage news section
  - /blog featured posts
  - MozFest minsite integration
  - PNI minsite integration
  - OLE page
  - Participation wins on /participate
  - Campaign wins on /advocacy
  - Fellowship success stories on /fellowships

cc @alanmoo 

Related to Epic Blog ticket https://github.com/mozilla/foundation.mozilla.org/issues/2797

**Comment by alanmoo** [comment]
Is the goal of this to end up with engineering tickets for the sprint ending August 19?

**Comment by kristinashu** [comment]
I'm working on a deck exploring the designs and functionally [here](https://docs.google.com/presentation/d/1NWfOotxMRcfE78CehF2uqZefEWEUm5siwrgOXzmbM_8/edit?usp=sharing) but I will be on PTO July 31 - Aug 15 so I'm not sure how much will get approved/finalized before I go since I'm not sure if I'll get to talk to Anil.

**Comment by kristinashu** [comment]
I've updated the [deck](https://docs.google.com/presentation/d/1NWfOotxMRcfE78CehF2uqZefEWEUm5siwrgOXzmbM_8/edit?usp=sharing) based on feedback and added in some notes for devs. I think the next step would be to add in categories but let's chat next week. In the meantime please add any thoughts to the deck or in [redpen](https://redpen.io/p/bha12cf7387de4f7e7). 

@anilkanji @xmatthewx @alanmoo @Pomax @mmmavis @sabrinang @natalieworth @beccaklam

**Comment by gideonthomas** [comment]
@kristinashu to file implementation tickets and put them into Aug 26 milestone.

**Comment by Pomax** [comment]
thing that feels import we add earlier than later: RSS/Atom feed so people can follow us.

**Comment by kristinashu** [comment]
Meet with Alan and Pomax to review the deck and next steps.
- Pomax will start add the ability to tag a post in a categories this week #3560
- next week he will build the category landing pages #3562
- after that he will update /blog tags to categories #3563

And I have updated the Blog Epic ticket with all the remaining work needed https://github.com/mozilla/foundation.mozilla.org/issues/2797 so I will close this ticket and work off of the epic!
