### ISSUE TITLE
Shape plan for interactive campaigns

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#3446]
There are some plans on the horizon for more interactive, slightly more bespoke campaigns than current petitions or pages. Think: interactive components on pages or uniquely designed pages that parody other sites/web apps. We should have an engineering strategy for building these. Obviously we want to host them on the foundation site Wagtail instance, but some things to think about:

* Do we create a separate site in Wagtail?
* Same domain with a vanity URL (like PNI) or just a completely different domain with links back to foundation.mozilla.org?
* What's the Django App setup look like for these?

@kristinashu and @gideonthomas have some more context for this, but to close this ticket I'd like to have a plan in place so that when the first one is ready (potentially a Youtube campaign), we know how to start.

**Comment by xmatthewx** [comment]
Maybe stating the obvious, but if we want to do these things periodically, we should aim for cheap and repeatable structures so we can focus energy on the content and substance. Also, vanity URLs are a black hole for tracking campaign performance. We should avoid them until we have solution for that.

**Comment by Pomax** [comment]
We can technically do the same thing we did before with things like buyers guide and fellowships: as long as we create things that are Django apps, we can borrow as much from wagtail as we want/need, and have the ability to host them under the same URL routeset. The one big issue I can foresee is localized content, which wagtail manages in one way, but Django manages in a related, but other way.

**Comment by alanmoo** [comment]
Thinking about this more, we'll probably still want to create Wagtail pages in the future, though there's a chance they'll end up being single-use. Can we create Wagtail pages in a separate Django app and still use all the nice things?

**Comment by alanmoo** [comment]
This isn't well formed enough/needs a proper example to be useful.
