### ISSUE TITLE
Update NPM watch tasks

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#3451]
It seems like `chokidar-cli` is no longer maintained and becoming a security concern. Can we use something else for our `npm watch` tasks?

**Comment by Pomax** [comment]
https://paulmillr.com/posts/chokidar-3-save-32tb-of-traffic/ is from June 2019, and talks about security concerns... food for digging.

**Comment by Pomax** [comment]
on that note, it would certainly be easy enough to write a node script that just does the watching we need and then running that, rather than chokidar-cli, https://github.com/paulmillr/chokidar#api

**Comment by mmmavis** [comment]
`chokidar-cli` just published a new version v2.0.0. Do we care to upgrade it or we should just get rid of it for good?

https://github.com/mozilla/foundation.mozilla.org/pull/3491

**Comment by alanmoo** [comment]
Yeah, landing that can close this.

**Comment by alanmoo** [comment]
(That being said, I wouldn't mind reducing our dependencies, but that seems to be more of an ongoing task rather than something we need to do right now)
