### ISSUE TITLE
Home is missing from mobile nav

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3452]
<img width="686" alt="image" src="https://user-images.githubusercontent.com/1068783/61891395-6b604000-aebe-11e9-9d28-1bddda9a3b13.png">

<img width="422" alt="image" src="https://user-images.githubusercontent.com/1068783/61891421-7b781f80-aebe-11e9-856a-76bbe3c1ebd7.png">

**Comment by Pomax** [comment]
the narrow screen container uses `<a class="{% primary_active_nav request menu_root.full_url menu_root.full_url %}" href="{{ menu_root.url }}">{{ root_name }}</a` so it's possible that `root_name` just isn't set

**Comment by alanmoo** [comment]
Doesn't the "Mozilla" logo at the top link to `/`? I can't remember when we'd have had this.

**Comment by kristinashu** [comment]
Yes but for usability we should still have the word Home in the mobile nav. It is still on https://www.mozillafestival.org/en/.
