### ISSUE TITLE
Generate unique filenames for static resources on build+deploy

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#347]
If we do this we can avoid caching issues after deploying fixes. I'm confident that webpack should be able to do this automatically, but we would need to inject the filenames into HTML.

**Comment by hannahkane** [comment]
Iceboxing, wait and see if this is an issue for people

**Comment by kristinashu** [comment]
@cadecairos is this still relevant?

**Comment by cadecairos** [comment]
I don't think so. we can refile if it ever becomes relevant again.
