### ISSUE TITLE
Enable heading ID attributes on Mozfest Primary Page templates

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#3471]
So that editors can create anchor links to headings in their streamfields, we should enable the same functionality that's on pages in the Foundation site templates (and ensure it's actually in all Foundation site page types while we're at it). That is, when a user creates a heading (H1-H3, I believe?) they get an ID attribute that's a slugified version of the content.

**Comment by Pomax** [comment]
This will involve making sure that the tag used to inject `id` attibutes to streamfield h1/2/3 gets used on Mozfest templates in addition to the current Foundation templates.

**Comment by Pomax** [comment]
this should, actually, already be happening. The way it works if that we change the way wagtail's own StreamField render function works, so any Streamfield on a mozfest page should already have h1/2/3 get auto-anchored.

**Comment by Pomax** [comment]
e.g https://www.mozillafestival.org/en/#bring-your-work-to-mozfest

**Comment by alanmoo** [comment]
It's not working on this page though- I believe the need is for the top text to be links to the different sections below. Is this a technical issue or a usability one? https://www.mozillafestival.org/en/event-terms-and-conditions/

**Comment by Pomax** [comment]
It turns out the headings had their text bolded - this has been fixed, and https://foundation.mozilla.org/en/docs/how-do-i-wagtail/creating-anchor-links/ has been updated to explain exactly what's going on (and what to do).
