### ISSUE TITLE
Remove CircleCI integration for now

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#3497]
Since Lucie's out, let's make this not fail for now.

**Comment by Pomax** [comment]
https://mozilla.slack.com/archives/C4M19QU2Z/p1565083520001100?thread_ts=1565082922.001000&cid=C4M19QU2Z

**Comment by alanmoo** [comment]
I've spent more than 5 minutes trying to do this and when rebasing a PR, CircleCI keeps coming back. @Pomax any idea how to kill it?

**Comment by alanmoo** [comment]
Yay, done (there was a lingering webhook)
