### ISSUE TITLE
Django site dependency updates

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#3498]
Foundation site, pulse api, wagtail-donate

**Comment by Pomax** [comment]
See https://mozilla.slack.com/archives/C4M19QU2Z/p1565083520001100?thread_ts=1565082922.001000&cid=C4M19QU2Z

**Comment by alanmoo** [comment]
@youriwims  This is basically a placeholder for handling the dependency updates; there seem to be a whole bunch.

**Comment by Pomax** [comment]
Is this just "running through the dependendabot PRs", or is this more than running down the PR list?

**Comment by youriwims** [comment]
@alanmoo was there something specific that you saw needed to be updated in the donate-wagtail repo? I don't see any `dependabot` updates, but when I run `npm outdated` I can see quite a few packages marked as 'missing'.

**Comment by alanmoo** [comment]
Don’t worry about that repo.

-Alan Mooiman,
Mozilla Foundation Engineering Manager
Eastern Daylight Time (USA) UTC-4
