### ISSUE TITLE
"has-danger" class for the footer newsletter signup is invisible.

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#3508]
When the footer's newsletter signup input field has the `has-danger` class, which is supposed to highlight an error with a red border, there does not appear to be a visual cue:

![image](https://user-images.githubusercontent.com/177243/62728693-3d582100-b9d1-11e9-9af1-e7345e0155c4.png)

As a design question: does this need a visual cue at all?
As dev question: if yes, what's the best SCSS to use here? If no, is it more work to remove the code that adds `has-danger` than it is to just leave it as is? (with a code comment that points to this issue)

**Comment by natalieworth** [comment]
@youriwims Added error states for the footer back in the Foundation Site abstract file under 'Footer WIP' section:

<img width="1323" alt="Screen Shot 2019-08-28 at 10 29 04 PM" src="https://user-images.githubusercontent.com/14876567/63913049-a1c03c00-c9e3-11e9-80b7-f9e6b65e186d.png">

cc @mmmavis
