### ISSUE TITLE
use uniform block naming for django templates

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#3531]
We're mixing camelCase and snake_case and kebab-case (omg these names...) and we should probably just stick with "not camel case" (to follow Python's conventions), and then either use underscores or hyphens...

And preference? I'd say "keep underscores for code, and use hyphens in templates" but the choice is 100% arbitrary and we really just need to pick one and then stick with it =)

Leave a vote and unassign yourself after you do:
- 👎  for `snake_case` (because the hyphen's at the bottom!)
- 👍 for `kebab-case` (because .... it's the opposite emoji?)

And you don't get to go "this is not my decision". Just pick one because there is no right choice.

**Comment by youriwims** [comment]
🌮 taco it is lol

**Comment by Pomax** [comment]
🐍 WINS!
