### ISSUE TITLE
Make env.default point to localhost?

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#3537]
Currently the `env.default` says this:
```
NETWORK_SITE_URL=https://foundation.mozilla.org
DOMAIN_REDIRECT_MIDDLEWARE_ENABLED=False
TARGET_DOMAINS=foundation.mozilla.org
```
which means that without overriding this for local dev, all run instructions build a `main.js` that will completely bypass the local instance and instead call the production site for all its API needs.

It feels like we probably want to change this so that env.default reads:
```
NETWORK_SITE_URL=http://localhost:8000
DOMAIN_REDIRECT_MIDDLEWARE_ENABLED=False
TARGET_DOMAINS=localhost:8000
```

instead.

Changing this shouldn't affect staging and production, but might affect review apps?

**Comment by Pomax** [comment]
(this took us way too long to spot when trying to figure out why localhost petition posting was going super wrong =D)

**Comment by patjouk** [comment]
We don't use the `env.default` for review apps: they have their own settings in the `app.json` (either custom env or inherited from staging).

**Comment by alanmoo** [comment]
Ah, so in addition to this for local work, we probably need to change the setting in app.json?

**Comment by Pomax** [comment]
if review apps are unaffected then the only change necessary should be to the env.default - does docker have a preferred format (`localhost` vs `127.0.0.1` vs `0.0.0.0` etc?) or will it work fine with `localhost`?

**Comment by Pomax** [comment]
@cadecairos would you happen to know?

**Comment by cadecairos** [comment]
[We made this change](https://github.com/mozilla/foundation.mozilla.org/pull/849) to ensure that devs saw data locally. If we revert this, do we need to also update the fake data scripts?

**Comment by Pomax** [comment]
That issue was filed when there was still a separate "network site" and "network-API" - once we went the Wagtail route and merged network-api app into the larger Django setup, the need to point to something else kind of disappeared.

**Comment by alanmoo** [comment]
Makes sense to me, I guess?

**Comment by cadecairos** [comment]
let's give it a shot
