### ISSUE TITLE
Set up home for Youtube Campaign

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#3547]
The design team is finalizing designs for a youtube campaign. It's going to be a one-off page in a visual style dramatically different from the rest of the site. It'll probably pull in some JS library that we don't use elsewhere, but we do want to ensure we can still make it have all the nice things we usually do by making it a part of the Wagtail tree. The content itself might not have to be editable in Wagtail, but the metadata and the like should be, for consistency and future maintenance.

**Comment by Pomax** [comment]
Will this live under `/campaigns/` or the homepage?

**Comment by Pomax** [comment]
Also, when we say "dramatically different", are we talking independent HTML and CSS code?

**Comment by alanmoo** [comment]
Yes. Think PNI compared to the rest of the site. Probably some shared metadata and _maybe_ a header nav.

**Comment by Pomax** [comment]
Currently leaning towards:

- a "one off" page model that allows us to specify
  - which template that page should render with, and
  - a streamfield of "translation key/value pairs" so that we can specify text blocks in the CMS, with the translation fields that offers

- a filter for fetching textblocks given keys so that the template ends up being something like `{{ intro_text | gettext }}` and have that yield the correct (localized) string

**Comment by Pomax** [comment]
Note that this means localization would be done through the CMS, _not_ through pontoon (until we can figure out an external localization strategy for CMS content)

**Comment by Pomax** [comment]
On a testing note: without comps, it's effectively impossible to write an adequate data-faking + percy test to go with the code that we land for this issue

**Comment by kristinashu** [comment]
cc @mmmavis since she will be starting to build the YouTube campaign page next week.

**Comment by mmmavis** [comment]
@Pomax @alanmoo this site will likely to be multi-page (one main page + one for FAQ. See [Invision](https://mozilla.invisionapp.com/share/THU06X9A53M#/384781753_Homepage)). Just wanna make sure the PR allows the site to be multi-page.

**Comment by Pomax** [comment]
That would definitely make it _not_ a one-off page, but effectively an independent website like PNI. @alanmoo this might need more planning and architecting.

**Comment by kristinashu** [comment]
I'm not sure if _multi-page_ is right? It be considered just _tabs_ (it shouldn't reload the page)? But if this is a problem, I'm happy to talk about design workarounds to avoid this.

**Comment by alanmoo** [comment]
Doing this with in-page tabs is probably more error-prone than doing it as separate pages would be. Besides, we've already got most of the infrastructure in place for separate pages if we make this based off the BanneredCampaignPage type.

**Comment by kristinashu** [comment]
Ok but if people scroll _go down the rabbit hole_ then click on FAQ, we don't want the page to reload and then they to have to go back _go down the rabbit hole_ to see the FAQ content.

**Comment by alanmoo** [comment]
This has been superseded by more detailed tickets for tracking this project
