### ISSUE TITLE
Fix production

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#3557]
It seems like [this](https://github.com/mozilla/foundation.mozilla.org/compare/73641efa...fc0c3d21#diff-8adf98446ee6773369e46c907ec7db75R3) is the cause of the production incident last week. Filing this ticket to be clear that we need to spend some time rolling back commits and re-deploying.

**Comment by Pomax** [comment]
fied by backing out the "og-locale" PR (and subsequent "hardcoded /en/" PR)
