### ISSUE TITLE
Blog: Add categories field

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3560]
Add the ability to assign a blog post to a category. 

Categories are:
- Mozilla Festival
- Open Leadership & Events
- Internet Health
- Fellowships & Awards
- Advocacy

Can a post be in more than one category? Hmmmm yes, I _think_ a post should be able to be in multiple categories but if that is complicated then just one is fine.

cc @alanmoo

**Comment by Pomax** [comment]
Do we want these in the Promote tab, like tags, or (because it's fixed content) part of the blog page?

**Comment by kristinashu** [comment]
Good question... since it's pretty important and we don't want people to miss it, I think it should go with the main content. Perhaps below the Author field. But for now at least, let's not make it a required field.

**Comment by Pomax** [comment]
can do - I assume these categories are not going to get expanded on very much/very often? (if they are, that changes how best to implement them)

**Comment by kristinashu** [comment]
Right, these should be set. Staff should not be allowed to create new ones or edit existing ones.

**Comment by mmmavis** [comment]
From Pomax:


> [...] after once again running into the fact that Django doesn’t have a simple array type, it will involve making a BlogPageCategory class, with a migration that sets up the 5 categories we need, and giving the BlogPage a many-to-many relation to BlogPageCategory.
Then we can create a subroute for `/category/...`  that works similarly to tags, except using the BlogPageCategory relation
