### ISSUE TITLE
Blog: Build category overview page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3562]
Blocked by - Add categories field https://github.com/mozilla/foundation.mozilla.org/issues/3560

We need one overview page for each of the ~6~ 5 categories

URL: foundation.mozilla.org/blog/[category-name]

### Page content: 
- title of category
- unique editable intro text 
- intro text can have url link in the copy
- most recent posts
- “See more” button
- future feature: ability to have featured posts at the top of the page

### Thumbnail content: 
- OG image
- category is hidden
- author
- date posted
- OG title

### Comp
https://redpen.io/bkd71cb03a53bdf596

![](https://s3.amazonaws.com/redpen-prod/red-pen-24dd6d42-9b68-49d3-e9ed-f44115a59231.jpg)

cc @alanmoo @Pomax

**Comment by Pomax** [comment]
I see only fix categories in the codebase:

- Mozilla Festival
- Open Leadership & Events
- Internet Health
- Fellowships & Awards
- Advocacy

Which one are we missing?

**Comment by Pomax** [comment]
Will categories only ever apply to Blog pages, or are the same categories going to end up getting used for things like campaigns and/or one-off pages?

**Comment by kristinashu** [comment]
Oops only 5 categories, I've updated the first comment!

**Comment by kristinashu** [comment]
There will be a Wagtail component https://github.com/mozilla/foundation.mozilla.org/issues/3564 that will pull post based on the category but I don't foresee using categories anywhere else.

**Comment by Pomax** [comment]
Due to wagtail's routing model, category URLs will need to be `/blog/category/(catname)`. Hopefully that's not a problem?

**Comment by kristinashu** [comment]
Yeah that url structure is ok with me.

**Comment by Pomax** [comment]
In the comp, is the "Mozilla Festival Blog" heading a custom heading, or a compound of `{category name}` + `Blog`?

**Comment by kristinashu** [comment]
I like the consistency of making it a compound `{category name}` + `Blog` (in Title Case).

**Comment by Pomax** [comment]
Also, is the thumbnail content the standard blog card content that we also see on `/blog` and `/blog/tags/...` ? (or, even if not the same as exists right now, is it _supposed_ to all be the same cards, or do these somehow differ?)

**Comment by kristinashu** [comment]
Right, it should be the same image, title, author, date as on `/blog`. Only difference is that the tag/category is hidden since they will all be the same (related: Blog: update tags to categories on /blog #3563).

**Comment by Pomax** [comment]
title case question: right now we're using code that effects title casing for the compound `(category) Blog`, but that would look strange if we have categories with prepositions/articles in it - just to confirm, that's not going to occur, right? They're just "bare" noun phrases?

**Comment by kristinashu** [comment]
Title case works for our current list but two of the have ampersands, is that ok? Because if we didn't have ampersands then it yes it would be weird to have `Open Leadership And Events`. 
- Mozilla Festival
- Open Leadership & Events
- Internet Health
- Fellowships & Awards
- Advocacy

If you think this might be an issue then I guess we could make the title it an editable field. Especially since we have since to decided to make the snippets only editable by a few staff.

**Comment by Pomax** [comment]
yep, ampersands don't cause any problems (at least, I don't _think_ there's an uppercase ampersand!). The only problem with title case is that it's fairly indiscriminate, so it will happily turn "this is a title in plain text" into "This Is A Title In Plain Text", which doesn't really follow conventional title case rules. Symbols are left untouched, so we should be good then!

**Comment by kristinashu** [comment]
Ok awesome, thanks for checking!

**Comment by Pomax** [comment]
And with that, PR landed
