### ISSUE TITLE
Blog: update tags to categories on /blog

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3563]
Update the purple link text from the first tag to category. 

Comp: https://redpen.io/gaebe8a528c73afec4
![](https://s3.amazonaws.com/redpen-prod/red-pen-79d7ed7e-e098-44ec-a943-328da15be42b.jpg)

cc @Pomax

**Comment by youriwims** [comment]
@kristinashu should the font-size for the category (and tags on other blog cards like on [this page](https://foundation-mofostaging-pr-3637.herokuapp.com/en/blog/resource-gas-improve-future-section-late/)) be 12px or 16px? On prod, I noticed the tags are 16px, but in Abstract, they're 12px.

**Comment by kristinashu** [comment]
Oh thanks for catching that! It should be like `.body-small` from the [style guide](https://foundation.mozilla.org/en/style-guide/) so it should be 12px. But can it be uppercase like in the Abstract?
