### ISSUE TITLE
Blog: build Wagtail component

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3564]
Create a component (similar to the Pulse component) that can be embedded on any wagtail page to show recent blog posts within a category or a tag.

### Shows most recent posts from either
  - a category
  - or a tag

### Component content
- section title
- 6 most recent posts
- “More from our blog” button

### Thumbnail content
- OG image
- category (hidden if filtered by category since they will all be the same)
- author
- date posted
- OG title
- ~OG description~

### Comp
https://redpen.io/p/bha12cf7387de4f7e7

![image](https://user-images.githubusercontent.com/1068783/63386326-a5a2ed00-c357-11e9-84a7-f40531b606a8.png)

![](https://s3.amazonaws.com/redpen-prod/red-pen-fd362191-9a70-4af9-f876-c58b9ba183d4.jpg)

cc @Pomax

**Comment by youriwims** [comment]
@kristinashu can you confirm if these will be the only tags for this component? 
- tags
  - 'mozilla'
  - 'privacy'
  - 'security'
  - 'internet health'
  - 'digital inclusion' 
  - 'advocacy'
  - 'policy' 

I took the list of tags from Pomax's blog-tag PRs. If not, can you send the list of pre-defined tags our users should be able to choose from?

**Comment by kristinashu** [comment]
Categories are set to only 5 different ones https://github.com/mozilla/foundation.mozilla.org/issues/3560#issue-482979249 but tags could be anything. Staff can type anything into the tag field on a blog post detail page:
<img width="498" alt="image" src="https://user-images.githubusercontent.com/1068783/64054409-b1eb2f00-cb3b-11e9-8680-d76269d607ac.png">

I assumed filtering by a tag would be similar to the Pulse component where users could put in anything:
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/1068783/64054564-65ecba00-cb3c-11e9-9b68-f8219a0f9f39.png">

**Comment by youriwims** [comment]
Sure, I could do the tag filtering by search similar to the _Pulse Listing_ component. A few other questions:

1. I just want to confirm that we're not letting users choose how many entries to display? It will always be 6, right?
2. Will the “More from our blog” button take them to the tag-filtered blog page or should that component expand and continue loading results?
3. Will the title always be _Latest News_ or should that be editable?
4. What did you mean by OG **description** for the thumbnail?

Thank you! 😄

**Comment by kristinashu** [comment]
Thank you for the questions!

1. I just want to confirm that we're not letting users choose how many entries to display? It will always be 6, right?

> Yes, always 6 please.

2. Will the “More from our blog” button take them to the tag-filtered blog page or should that component expand and continue loading results?

> It should take them to the page (either the tag-filtered one or the category page).

3. Will the title always be _Latest News_ or should that be editable?

> Please make it editable.

4. What did you mean by OG **description** for the thumbnail?

> Oops **description** shouldn't be there! I've crossed it out.

5. Are the top + bottom black dividers optional parts of the component? (or are those from other components?)

> Please make them optional as part of this component.

**Comment by youriwims** [comment]
Awesome—thank you!

**Comment by youriwims** [comment]
Closed via #3597
