### ISSUE TITLE
Design /advoacy page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3568]
Our [Advoacy](https://foundation.mozilla.org/advocacy/) page was put up as a quick fix but now we should take some time to think it through and actually design it.

Make sure to create a brief to establish the goal and audience for the page.

## Proposed content

**Intro text** 
- We do advocacy! He's why and how in 280 characters or so.

**Advocacy campaigns** 
- Our top active campaigns
- Proposed solution: Wagtail component to pull the most recent /campaign pages (as we can see from the current /advoacy page which uses the Pulse component, we do not have the time or people to make manual updates)

**Advocacy wins**
- Our most compelling wins
- Proposed solution: Wagtail component to pull key advocacy blog posts (with a link to see all advocacy blog posts) (dev ticket for this work #3564)

**Comment by kristinashu** [comment]
Notes from Anil:

1) I'd like to check in with Ashley to see if there's any concerted efforts to talk more about our work as advocacy OR campaigns - that's a data point that should be considered.

2) If we're a movement building organization, there's a slight nuance that can be surfaced in the copy (as part of the three bullet points Matthew shared): We campaign (or do advocacy) but our role is to facilitate the internet health movement. So I'd like to see wording like "here are some of the things that you've made possible through mozilla campaigns" (vs framing them as mozilla wins). And I really feel there should be a strong CTA around joining us so you can take action alongside us on this page.

**Comment by kristinashu** [comment]
Reviving this! Note we also not have this index page [/campaigns](https://foundation.mozilla.org/en/campaigns/).

Got some clarity from Ashely on this. Campaigns are a subset of Advocacy work. Campaigns have a clear CTA ask.

### Content structure for our Advocacy home could be something like: 
- Things we work on and why 
  - Portfolios eg. digital ads
- List of key campaigns (campaigns have a clear CTA)
- List of key work with partners (possible in the form of blog posts)
- Show which staff to contact for partnerships or questions

### Next step
- a design to mock up an layout and share with Jon for feedback and copy

**Comment by kristinashu** [comment]
Started a [copy doc here](https://docs.google.com/document/d/1HOtabCYowg8JmP7_r-WQzR9GAECU6lVoTFBTkVJQ2s0/edit?usp=sharing).

**Comment by Pomax** [comment]
@kristinashu should we keep this open, or close this issue and open a new one once there is new focus on advocacy?

**Comment by kristinashu** [comment]
Good to close!
