### ISSUE TITLE
Implement language switcher

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#3580]
Results of #2681

**Comment by sabrinang** [comment]
Final designs on https://redpen.io/p/vu6e9b5fe5236d10f8 or can be found on abstract sketch style guide file: 
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/2492510/64386937-5c0d0000-cfef-11e9-9ba8-17edbe8e024b.png">

White globe icon found in sketch file or download svg here: https://drive.google.com/open?id=1VwaGtRuGmhKPiRFiiPJ5Sy8FvqAFjg0L&authuser=sabrina@mozillafoundation.org&usp=drive_fs

**Comment by mmmavis** [comment]
@sabrinang for the down caret icon did you want me to use the same icon we use on Pulse? https://www.mozillapulse.org/assets/svg/caret-down.svg

**Comment by sabrinang** [comment]
@mmmavis The pulse icon should be using the icon set (round stroke caps) and it'll be white so no. I've exported the white down chevron icon in the same folder here: https://drive.google.com/open?id=1WgJeiczo6i6KM2l4sBJsFwBw0wLqf8xi&authuser=sabrina@mozillafoundation.org&usp=drive_fs
