### ISSUE TITLE
Blog Index - Tag(Category?) list should always be on it's own line

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#3586]
Not sure about the original design but this looks like a bug to me. /cc @kristinashu 

Test page on staging: https://foundation.mofostaging.net/en/blog/tags/coffee/

<img width="943" alt="image" src="https://user-images.githubusercontent.com/2896608/63900601-d87f5d80-c9b5-11e9-97a7-0ace4c28bd86.png">

**Comment by kristinashu** [comment]
Yes, definitely a bug!

**Comment by mmmavis** [comment]
PR merged!
