### ISSUE TITLE
Blog: display list of tags on blog post page

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#3587]
Currently blog post doesn't display the list of tags it's associated with. Is it about time for us to add it to the page?

For example, this [blog post](https://foundation.mozilla.org/en/blog/what-can-you-trust-internet/) has the tag `YouTube`. Based on the mockup provided in this [ticket](https://github.com/mozilla/foundation.mozilla.org/issues/3030) the page should display ```Tagged: YouTube``` before the share buttons.

/cc @kristinashu to triage

**Comment by kristinashu** [comment]
Design had [originally designed](https://redpen.io/ut7a651b2aa0892ef4) it this way but we have since questioned if this is the best modern practice or not. 

I'll assign this as a design task until we decide, but either way it isn't blog priority right now.

**Comment by kristinashu** [comment]
I'm going to close this ticket. Will open a new ticket if we decide tag need to be displayed.
