### ISSUE TITLE
Blog: add comments to post detail page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3589]
From epic ticket https://github.com/mozilla/foundation.mozilla.org/issues/2797

Add comment feature to individual blog post pages similar to [PNI](https://foundation.mozilla.org/en/privacynotincluded/products/harry-potter-kano-coding-kit/) and [IHR](https://internethealthreport.org/2019/lets-ask-more-of-ai/).

By default comments feature should be off but staff should be able to turn them on for specific posts. 

Jen C and I can moderate. 

@alanmoo should we just Coral Talk for this?

**Comment by alanmoo** [comment]
Yup, absolutely.

**Comment by alanmoo** [comment]
@cadecairos Any reason we shouldn't use the same Talk instance as PNI for blogs?

**Comment by cadecairos** [comment]
> Any reason we shouldn't use the same Talk instance as PNI for blogs?

None that I can think of. We should probably look into upgrading that instance.

**Comment by alanmoo** [comment]
And maybe getting it a proper sub domain?

**Comment by cadecairos** [comment]
got one in mind?

**Comment by alanmoo** [comment]
comments.mozilla.org? (Or comments.mozillafoundation.org)

Kristina, any opinion on that? It really only shows up in the url bar when logging in to comment.

-Alan Mooiman,
Mozilla Foundation Engineering Manager
Eastern Daylight Time (USA) UTC-4

**Comment by kristinashu** [comment]
No real opinion but maybe comments.mozillafoundation.org would be clearer?

**Comment by alanmoo** [comment]
Great. I'll file a separate devops ticket. @youriwims, please work on this when you're back in Canada; Getting the initial implementation working shouldn't take more than a day.
