### ISSUE TITLE
Update Wagtail hint text for video component

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3590]
Update hint text for video cms component.

User feedback has pointed out that it is hard to know what YouTube url to put in 

<img width="998" alt="image" src="https://user-images.githubusercontent.com/1068783/63969556-f0f38480-ca56-11e9-9202-eb1bd756ba2b.png">

Update hint text to say:

> To make sure a video will embed properly, go to your YouTube video and click “Share,” then “Embed,” and then copy and paste the provided URL only. For example: https://www.youtube.com/embed/3FIVXBawyQw

**Comment by Patil2099** [comment]
@alanmoo @Pomax Can you tell me where I have to make changes?

**Comment by alanmoo** [comment]
In the file where the model is defined, and then generate a migration if necessary.
