### ISSUE TITLE
[Enhancement] Allow embedding of YouTube Privacy Enhanced Player

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/foundation.mozilla.org#3592]
_(This is just an enhancement request, rather than a bug)._

When trying to add the URL of a privacy enhanced video on YouTube using a Video block, the player does not show on the Mozilla Festival website.

I have added two embeds on https://mozillafestival.mofostaging.net/en/youtube-live-stream-test/

The first is the standard video and the second is same video with the Privacy Enhanced player. 

The Embed URL for the Privacy Enhanced Player is different than the standard embed URL: https://www.youtube-nocookie.com/embed/[videoID]

**Comment by gideonthomas** [comment]
@marcwalsh can you try to spin up that page on the staging site again and see if it works? If it does, I can fix this on the production site as well

**Comment by marcwalsh** [comment]
Thanks - that works for me! 

Test page is here: https://mozillafestival.mofostaging.net/en/live-stream-test/

🍪🚫

**Comment by gideonthomas** [comment]
Perfect! I'll make the change in production as well
