### ISSUE TITLE
Fix migration numbers so there aren't dupes

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#3606]
In `development` branch: there are two migrations sharing the same number `0074`

https://github.com/mozilla/foundation.mozilla.org/tree/development/network-api/networkapi/wagtailpages/migrations

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/2896608/64213454-e58ec780-ce61-11e9-89d2-cbe9abde0366.png">

From @Pomax: 

> we probably need to make sure that's a single chain again

**Comment by mmmavis** [comment]
@gideonthomas can you help triage this ticket?

**Comment by gideonthomas** [comment]
This should really not be necessary per: https://docs.djangoproject.com/en/2.2/topics/migrations/#version-control.
But if you really want to do this, you can do this at the end of the milestone if you have time after finishing up the Up Next and In Progress tickets assigned to you.

**Comment by Pomax** [comment]
honestly, we should really squash our migrations as much as possible sooner than later. Having almost 100 migration files is completely unnecessary =)

**Comment by Pomax** [comment]
closing as progressive more irrelevant.
