### ISSUE TITLE
Implement Button Active State

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#3608]
Design issue #3367 

**Primary active:** $light-blue with $white text
**Secondary active:** $blue with $white text
**Pop active:** $black with $white text

**Inverse Primary active:** $dark-blue with $black text
**Inverse Secondary active:** $blue with $black text
**Inverse Pop active:** $white with $black text

<img width="705" alt="Screen Shot 2019-09-04 at 12 45 44 PM" src="https://user-images.githubusercontent.com/2492510/64286420-47a70580-cf12-11e9-8c1d-bd5ea75b06b6.png">
on style guide sketch file

**Comment by mmmavis** [comment]
@arjunvijayanathakurup sorry to miss your comment. We are currently doing SCSS cleanup work so I will be taking this ticket on. Thank you for offering help.

@sabrinang is this design still relevant? If it is, I can work on it after the Bootstrap cleanup work is done.

**Comment by sabrinang** [comment]
@mmmavis Yes, design hasn't changed as is relevant
