### ISSUE TITLE
Blog: featured on homepage 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3611]
We would like to update the homepage News feed to a featured Blog feed.

### Layout
- Keep the same layout as we have now but replace the news source with the blog category. The rest should stay the same.

### CMS
- Staff (usually Jen) should be able to go to the homepage in Wagtail and select 4 blog posts to feature.
- Most recent featured post should be on the left with an image. Oldest featured post should be bottom right.
- Thumbnail content should be pulled from the post and it's OG info.

### Comp
<img width="526" alt="image" src="https://user-images.githubusercontent.com/1068783/64387436-d5f1b900-cff0-11e9-8c52-c72fc753f869.png">

**Comment by mmmavis** [comment]
@kristinashu 

- Do you know if we still wanna keep the News Wagtail component/snippet or remove it for good since the news section is going to be replaced by blogs on the homepage.
- Is the new section going to be called "Latest news" or "Latest blogs"?
