### ISSUE TITLE
PNI: Optimize for Signups

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3614]
### Goal
This is our primary goal of PNI: Increase conversion of visitors to subscribers to transform prior marketing and engagement success into more power for mofo and movement.

### Why
- To grow the MoFo email list with new audiences so that we’re in a position to fundraise and engage a broader public.
- KRs that this affects: 1.1 and 1.2

### From Matthew
- My theory is that we do this aggressively after some submits creepy opinion. Show share CTA after. We could also add a slide up from bottom, but i think the other will be more effective b/c of the timing.  
- Note: Will says to avoid annoying pop-overs for visitors who arrived with “subscribed=1” in their URL. 

## To do
- review [brief](https://docs.google.com/document/d/1uYHSB0JvmjzmZc_iYZmoz2ABKJoBrDXSeq_f2Xf3GOU/edit#heading=h.l71oov2wfbfc)
- have project kick-off
- research newsletter signups
- wireframe or sketch out possible interactions
- get feedback from design, dev, stakeholders, legal
- mockup
- open implementation ticket
- possibly some user testings

**Comment by beccaklam** [comment]
@kristinashu @xmatthewx  Mocked up what changing the nav on PNI to match the foundation site would look like below. It would mean removing the shares from the nav, but I don't think we can have everything in there. If we want to prioritize sign ups over shares than it should be fine. I'll took a look at the analytics though and see if I can find how many people were using those to share in case it was significant but from what I remember it wasn't.
![Home@2x](https://user-images.githubusercontent.com/20977376/64874984-19b07800-d61a-11e9-9bc1-95bf8246c351.jpg)

**Comment by beccaklam** [comment]
Actually I don't have access, @xmatthewx would you be able to grant me access?

**Comment by beccaklam** [comment]
UI for email sign up in creep-o-meter flow: https://redpen.io/sh6ecf0f84f26f2694
@kristinashu should we update the buttons on PNI to be square instead of pill shaped? Or should I match the email sign up buttons to the pill shape instead?

**Comment by kristinashu** [comment]
@beccaklam try pinging Cade in slack, he can give you access to analytics. But unless you see significant shares from the nav, I'm ok with removing them to focus users on our signup and donate. I don't seem to see them on very many _modern_ sites. 

Yes to square share buttons now that they're in the [style guide](https://foundation.mozilla.org/en/style-guide/).

**Comment by beccaklam** [comment]
@kristinashu @xmatthewx oh yeah, looks like share tips via the site were very low (@xmatthewx do you know the difference between 'site' and 'Buyersguide'?
![image](https://user-images.githubusercontent.com/20977376/64883505-897c2e00-d62d-11e9-858f-26788d6358af.png)
Looks like Donate was getting _very_ little taps too:

**Comment by beccaklam** [comment]
Updated buttons here: https://redpen.io/sh6ecf0f84f26f2694
Also updated the donate screens but not sure if that's still active on the site:
<img width="894" alt="Screen Shot 2019-09-13 at 3 03 01 PM" src="https://user-images.githubusercontent.com/20977376/64887964-ca794000-d637-11e9-839c-07bab8eaef98.png">
cc: @kristinashu

**Comment by kristinashu** [comment]
Nice, very on brand!

I think we should make the `Buy / Won't Buy` button optional since we really want to reduce barriers to get people to signup (and I don't think it's that important to get that purchasing info).

**Comment by kristinashu** [comment]
So you are aware https://github.com/mozilla/foundation.mozilla.org/issues/3628, we are adding Country and Language drop downs to the newsletter signup (only once a user has clicked into the email form field). The header and footer will have this implemented but I am not sure about adding it to this, after voting, signup. Anyone thoughts/options? I would lean towards leaving it out in order to reduce barriers and prevent this box from getting too busy.

**Comment by beccaklam** [comment]
I think we can incorporate it if it only shows after clicking into the email form field. It would make sense it keep it consistent and in the end it helps the user.

**Comment by alanmoo** [comment]
We're only doing the guide in English, so I don't think we need other languages in that dropdown (unless the component we pull in already has it).

**Comment by beccaklam** [comment]
Made some changes to the signup field height and nav height based on Kristina's comments: https://redpen.io/p/ehb3414f20c4e5e625 Should I open dev implementation tickets @kristinashu and close this one? Is there anything else that needs to be done? 

To recap: We're introducing an email sign up prompt in the middle of the creep-o-meter flow and changing the nav to match the Foundation's so that the newsletter signup button is in the top right corner.

**Comment by xmatthewx** [comment]
Whenever it's ready, file as 2 dev tickets. I think post-creepy CTA should come first.

**Comment by beccaklam** [comment]
Implementation tickets created #3674 and #3675!
