### ISSUE TITLE
PNI 2019 Epic

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#3616]
### Engagement (design/eng) team goals
* Increase sign ups
* Improve experience to increase understanding, engagement and return visits

#### Priorities
* Signups [high value, medium effort]
    * Design TBD
* List views [high value, medium to high effort]
    1. simplify home (bring out filters, remove all the words)
    2. Bring those to categories page
    3. Create hero feature with category dropdown below it (eg. Baby teaser story, defaulted to baby category below)
* Review date field [high value, low effort]
    * Engineering can go
    * Design TBD
* Product page updates [medium-high value, aim to keep low effort]
    * Keep to minimal tech
    * Primarily presentation and copy update

**Comment by kristinashu** [comment]
Here's a WIP design/dev brief https://docs.google.com/document/d/1uYHSB0JvmjzmZc_iYZmoz2ABKJoBrDXSeq_f2Xf3GOU/edit?usp=sharing

**Comment by kristinashu** [comment]
I'm not sure how useful this is, gonna close but please reopen if you think you need it!
