### ISSUE TITLE
PNI: Recommend product for review

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3617]
Talk to Jen and get copy from her.

Design a CTA that links to a Google form, Airtable , or our petition/comment snippet (would be nice to prompt with a newsletter signup).

**Comment by beccaklam** [comment]
Some options here in the redpen: https://redpen.io/p/ur962f62818f0c1ffb
Jen's copy:
>Didn’t see the product you were looking for. Let us know what product you would like reviewed in the guide.

> We don’t want to miss any products that might be important to you. Tell us what connected products you want reviewed in our holiday buyer’s guide and we’ll do our best to include them.

I was thinking we could use both? One for the homepage and one for the about page.
cc: @kristinashu @caltrider

**Comment by kristinashu** [comment]
Nice! I really like the button placements and the idea of using both version of the copy.

**Comment by caltrider** [comment]
Looking good. I just left a comment in the redpen. We could tweak the language to be a bit more active is we went with: "Don't see the product you are looking for?" Either one works fine though. There should be a "?" at the end of the sentence too.

**Comment by beccaklam** [comment]
Updated the copy: https://redpen.io/p/ur962f62818f0c1ffb
What did you mean by the "?" @caltrider ? The sentence already had one? If all looks good I'll create the implementation tickets. cc: @kristinashu

**Comment by kristinashu** [comment]
Any thoughts on where the button will link to? It would be ideal if we could prompt users with a Newsletter signup ask when they submit their idea.

Need this link for the dev ticket but otherwise I think it's ready!

**Comment by beccaklam** [comment]
@kristinashu True, maybe we can spin up a simple wagtail page? Any luck on finding that comment snippet? I feel like that would be the snippet we'd have to use? Any idea how we would set up the backend and where comments would go?

**Comment by kristinashu** [comment]
[This](https://foundation.mozilla.org/en/campaigns/tell-amazon-connected-devices-must-have-privacy-policies/chat-amazon-customer-service/) is the comment snippet. It would need to be set up in Salesfoce. Maybe this is worth a chatting about at stand?

**Comment by beccaklam** [comment]
Re: our stand conversation @caltrider Should we just do a shared email account for this? Kind of sounds like integrating with Salesforce is over-kill? cc: @kristinashu

**Comment by kristinashu** [comment]
True. I guess it depends how many recommendations we expect to get? But yeah, probably not enough to make it worth while.

**Comment by caltrider** [comment]
I would say over the past year I've probably gotten 10-15 product recommendations. I've probably had the same number of people or maybe a few more email me with questions or thoughts on the guide. My email is still listed on the about page for those, which is good. I'd say a shared email would work well. Have it come to me for sure and then I can ask in the buyer's guide slack channel who else might be interested in having that redirect to them too. I'm guessing since we're actually asking folks on the site now for these recommendations we'll get a few more, which is great.

**Comment by kristinashu** [comment]
Ok salesforce is definitely not needed then. So should we just link to a google form then?

**Comment by beccaklam** [comment]
I'm fine with that, that seems like a smaller lift than the shared email? @caltrider

**Comment by caltrider** [comment]
The problem with the Google form is a I won't get a notification when someone submits something.

**Comment by beccaklam** [comment]
Okay, so email it is? Should we just set up a gmail account?

**Comment by kristinashu** [comment]
You can set up email notifications for responses. Just go to response and click the 3 dotes.

<img width="903" alt="image" src="https://user-images.githubusercontent.com/1068783/66520033-4337b480-ea9d-11e9-9c85-6920b4f2d3b0.png">

**Comment by caltrider** [comment]
Sounds like we've got some pros and cons for either option:
Google Form: 
Pros: Simplest, we have all the recs in one doc
Cons: Notifications are doable but not as easy as email, harder to reply directly to someone who ask (we'd have to ask for email address which gets tricky)

Dedicated email address:
Pros: Most personal, immediate notification, easiest to reply
Cons: Not as easy to set up, all the recs wouldn't be in one place as easily

I'm sure I'm missing some things there. Feel free to add your own. Based on this, my thoughts are: It'd be nice to have all the products in one easy to read list AND responding to people to let them know I heard their request and give them so level of expectation is important. 

Also, here's the [google form](https://docs.google.com/forms/d/1IjWbylsFs4eVrGbDjCdFKufht0pO-3smxxcNfhuOUz0/edit) we set up when we emailed our list earlier this year to ask for product recs in case you want to see it.

**Comment by beccaklam** [comment]
@caltrider Why is asking for an email address tricky?

**Comment by caltrider** [comment]
Because of our lean data practices. Collecting personal info like an email through a google form might be doable, but i'm sure the lawyers will have much to say and a long disclaimer we'd need to include.

**Comment by beccaklam** [comment]
A disclaimer feels better than spinning up an email though? I'll ping Abigail.

**Comment by beccaklam** [comment]
Abigail is ok with us collecting emails as long as it's optional! I'll spin up the form and then should I open the implementation tickets? @kristinashu

**Comment by kristinashu** [comment]
Sounds good to me!

**Comment by beccaklam** [comment]
@caltrider Any chance I can just edit the google form you had before? This one: https://docs.google.com/forms/d/1IjWbylsFs4eVrGbDjCdFKufht0pO-3smxxcNfhuOUz0/edit

**Comment by caltrider** [comment]
@beccaklam Yup, that form should work. Feel free move the current recommendations from the email ask to a new tab so the current tab is cleaner for new recs too if you want.

**Comment by beccaklam** [comment]
Okay, it didn't seem possible to create a new tab for the new responses so I just created a new form ... @caltrider can you take a look at it and make sure everything looks good? https://forms.gle/UefDgjEU85Xwcf8C8

**Comment by beccaklam** [comment]
Implementation ticket for this opened #3799
