### ISSUE TITLE
PNI: Refine homepage list views

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3618]
From Matthew:
1.    Refine home filtering and sort (simplify and make more clear).
> My thinking: show Meets Req and creepy range slider. Remove the icon to pop open the bubble. Drop the would buy filter. 
This might require a change to the animated scroll face. But, i believe the slider will more quickly communicate to users what’s happening. Scroll face could be moved to the bottom. 
2.   Bring filters to category views.
3.   Reduce text at top the page.

**Comment by kristinashu** [comment]
Perhaps our goal could be to mock up a few different version and test out the comps at MozFest. If one of them is a hit then devs could build between MozFest launch on Nov 12.

**Comment by beccaklam** [comment]
@kristinashu Started some designs here: https://redpen.io/p/rob82780bb84c2b14a Still pretty rough, but any thoughts/feedback?

**Comment by kristinashu** [comment]
Yeah, I'm not sure about having sticky elements both at the top and bottom of the page. Also think the badge needs more context than just the icon. But I do like how Likely to Buy filter has been removed. To be honest, I'm not really sure why we even need the Creep-O-Meter filter? Seems like the scroll does this just fine. So **maybe** all we need is the animated face and a checkbox for Meets Minimum Security Standards? But happy to talk more about this, with Jen as well, before you spend more time on it.

**Comment by kristinashu** [comment]
Devs won't be implementing this for mozfest or for the main launch. @beccaklam up to you if you want to explore this more so get feedback at mozfest, or not to at all, or to explore more after mozfest. Please update the ticket milestone and status accordingly!

**Comment by beccaklam** [comment]
@taisdesouzalessa and I will be doing some usertesting at MozFest before determining what changes would be best to improve the user experience on the home page. Test script here: https://docs.google.com/document/d/1PuL3W6nfsCCHWW2GHhwEFDEm8EirLBX9lnrwNlyLnZU/edit?usp=sharing I'll close this ticket for now.
