### ISSUE TITLE
PNI: About Page additions

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3619]
Talk to Jen and get copy from her before starting.

Add simple pages to our About section:
- Add minimum security standards explainer section
- Add press section

**Comment by beccaklam** [comment]
@caltrider Do you have content ready for this?

**Comment by caltrider** [comment]
I don't yet. I do have some place holder content that will work for two sections.

Here's the link for the ["Methodology](https://docs.google.com/document/d/1oaPPgFRlA1_zfpd5tPPe8THC20iFnmSYBvSvFppkmjA/edit?userstoinvite=lotta@mozillafoundation.org&ts=5d9caea0&actionButton=1)" section.
Here's the link for the ["Our Minimum Security Standards Explained"](https://docs.google.com/document/d/1Y49QM9Yb-BWI7IhtwQUdXMWS6CQoIy8WN6j8Ox_rZSE/edit#heading=h.25auqwqk2y01) section.

I haven't yet reviewed or edited that content, but it can work as placeholder for now. 

I'll have to find time to go in and edit the existing "How to Use this Guide" and "Why We Made This Guide" but that might not happen before MozFest.

**Comment by beccaklam** [comment]
@caltrider @kristinashu I've mocked up the About Page with the new placeholder content Jen provided. Jen, I assumed that the links you provided ^ were replacing "How to Use this Guide" and "Why We Made This Guide" but I wasn't 100% sure. Let me know how to reorganize things if that's not what you were envisioning. https://redpen.io/p/xed29db03743c5348b

**Comment by caltrider** [comment]
Heya @beccaklam, thanks!
For the About page, these two sections will be new section, in addition to the already existing sections. So, the order of the sections on the left hand side of the About Page should go:

- How to Use This Guide (which I will update, after Mozfest)
- Why We Made This Guide (I'll review and make any needed tweaks after MozFest)
- Our Minimum Security Standards Explained (Becca will finalize after Mozfest)
- Methodology (Becca will finalize after MozFest)
- Contact Us
- Press Kit (this is an optional section we can add if we want to/have time based on Kevin's input)

**Comment by beccaklam** [comment]
Updated redpens to reflect the order of the sections: https://redpen.io/p/xed29db03743c5348b

**Comment by beccaklam** [comment]
@KevZawacki Any thoughts on if we should add the Press section to our About page and if yes, what content we should have there?

**Comment by KevZawacki** [comment]
Hi @beccaklam, good idea! Can we populate a press page with:

If you're a member of the press interested in learning more about *Privacy Not Included, please email Corey Nord at corey@pkpr.com. Below, peruse past coverage of *Privacy Not Included:

2018 | WIRED: [Mozilla Makes a Naughty List of Gifts That Aren't Secure ](https://www.wired.com/story/mozilla-privacy-not-included-internet-connected-toys/)

2018 | NPR: [A Tech Foundation Discusses Security And Privacy When It Comes To Smart Devices](https://www.npr.org/2018/12/01/672511667/a-tech-foundation-discusses-security-and-privacy-when-it-comes-to-smart-devices)

2018 | USA Today: [Looking at top tech toys and tools for the holidays? For many, privacy may not be included](https://eu.usatoday.com/story/tech/columnist/2018/11/23/top-tech-gifts-privacy-may-not-included/2059892002/) 

2018 | [New York Times: Don’t Give Kids Holiday Gifts That Can Spy on Them](https://www.nytimes.com/2017/12/08/opinion/holiday-gifts-toys-spying.html)

2018 | ABC San Francisco: [Your privacy may be at risk with some toys, gadgets](http://abc7news.com/technology/your-privacy-may-be-at-risk-with-some-toys-gadgets/2827339/)

**Comment by KevZawacki** [comment]
@beccaklam If you're able to generate the blank "Press" webpage, I can populate it with the above ☝️

**Comment by kristinashu** [comment]
@caltrider says she will have the final copy for her sections on Monday but Becca R won't have final copy for Methodology and Minimum Security Standards sections until Wednesday.

**Comment by kristinashu** [comment]
@caltrider will have all the copy finalized tomorrow morning:
- [How to Use This Guide](https://docs.google.com/document/d/12QuPQ_RXkmLlAlhCcPTX50-Nup2JskAIwC5ntcn8R4Q/edit)
- [Why We Made This Guide](https://docs.google.com/document/d/1rMo-TNMcHkgYOs2JSP8UxpW6AHdrx3N2odbL-uRP1Xs/edit)
- [Minimum Security Guidelines Explained](https://docs.google.com/document/d/1Y49QM9Yb-BWI7IhtwQUdXMWS6CQoIy8WN6j8Ox_rZSE/edit#)
- [About our Methodology](https://docs.google.com/document/d/1oaPPgFRlA1_zfpd5tPPe8THC20iFnmSYBvSvFppkmjA/edit)

Here are all the comps https://redpen.io/p/ya5efd0a747f33afa8. Copy will be tweaked as Jen finalized but the general structure is there.

I've included a comp of the press page. It isn't a cms page so we won't be able to update it in real time but could ask a dev to update it when needed.

**Comment by kristinashu** [comment]
For devs, I've put the press page content into a [doc](https://docs.google.com/document/d/153YTZ2edXYxMUtFAXyX34d7-WlKCW4xC9mYQd7i36JA/edit?usp=sharing). Please make any updates there!

Youri is going to build all these pages https://github.com/mozilla/foundation.mozilla.org/issues/3800 tomorrow afternoon and the is off Fri and Mon so last call!

**Comment by KevZawacki** [comment]
Thank you, @kristinashu -- the press page looks great.

I made two small changes in the doc (I had accidentally labeled two stories from 2017 as 2018). That's all!

**Comment by kristinashu** [comment]
Excellent, closing this!
