### ISSUE TITLE
Localize main nav

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/foundation.mozilla.org#3631]
This _should_ happen automatically when the Titles of pages get localized. Let's confirm that, and check how the donate/newsletter buttons get localized.

**Comment by TheoChevalier** [comment]
Confirmed for the page titles (see Internet Health and About in French here https://foundation.mozilla.org/fr/ )

Donate and Newsletter will be localized as part of https://github.com/mozilla/foundation.mozilla.org/pull/3529

**Comment by cadecairos** [comment]
@TheoChevalier What's the state of this issue?

**Comment by TheoChevalier** [comment]
We can close this, there’s no engineering work required as this gets localized as we localize all linked pages.
