### ISSUE TITLE
Menu layout broken with long translations for 990px-1200px viewport

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#3638]
Filing this issue early as it’s not YET broken, but these are the translations we will use in French when #3529 gets merged, so this will happen pretty soon.

![Screenshot_2019-09-09 À propos de Mozilla](https://user-images.githubusercontent.com/1294206/64782542-536f7900-d55d-11e9-8aa8-263efd2b6b5a.png)

**Comment by cadecairos** [comment]
@kristinashu this looks like it's currently affecting production: https://foundation.mozilla.org/fr/

Should we prioritize design and engineering on this for this sprint?

**Comment by kristinashu** [comment]
Yes, design can support this! @mmmavis do you have any suggestions on how to fix this? Is it possible to increase the text area length for the Donate button?

**Comment by mmmavis** [comment]
@kristinashu not sure if I get what you suggested about the Donate button area. I think the design issue is more about how we want the layout to look (e.g., text to wrap) when links are long. The following could be an option (though the on hover underline looks kinda floaty)

![Screen Shot 2020-02-25 at 13 45 34](https://user-images.githubusercontent.com/2896608/75290632-95237180-57d5-11ea-8b82-f10b4481af88.png)

**Comment by kristinashu** [comment]
Ok, I think there's a few issues going on... @beccaklam would you be able mock-up a few recommendations at some point this sprint?

**Comment by Pomax** [comment]
@kristinashu @TheoChevalier given when this was filed and we've not run into this in the intervening 2 years, shall we close this issue and instead tackle it if it ever comes up?

**Comment by kristinashu** [comment]
This is still an issue and I would like to fix it!

**Comment by mtdenton** [comment]
Happy early third birthday, #3638. Labeling this for purge. Also not seeing this issue for 990x1200 viewport, screenshot attached.

<img width="1728" alt="Screen Shot 2022-08-31 at 12 15 33 PM" src="https://user-images.githubusercontent.com/41487159/187740469-b1513d7f-120d-4645-a4e1-14e7b86bc43b.png">

**Comment by kristinashu** [comment]
I'm ok with closing this. I do see the issue and although it doesn't look nice, I think it's still legible.

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/1068783/187747358-c0f7bc72-b867-4fc6-9d7c-7a296243a3e9.png">

**Comment by kristinashu** [comment]
Closing this as Won't Fix. Please submit this as a "New Wagtail issue" in slack if needed.
