### ISSUE TITLE
Localize the Participate page

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#3642]
Let’s make this page localizable!

There’s a start here: https://github.com/TheoChevalier/foundation.mozilla.org/commit/c24f1664cee8a2f95b726a804c668dda1155aa69

But it’s missing Highlights, and CTA group 4 (and I don’t know how to tackle that)

**Comment by TheoChevalier** [comment]
I think I figured out how to add CTA 4 fields, and since highlights will be handled in a follow up patch, taking this

**Comment by Pomax** [comment]
Not to throw wrench in the wheel, but this page is a modelling _mess_ and we really should rip out all these -/2/3/4 duplications on duplications. Adding localisation now will make that job a lot harder, @alanmoo is there time for us to first refactor this page to something normal?

**Comment by alanmoo** [comment]
I think it's time to put the brakes on this for now; With the amount of effort, low traffic, and questions about the future nature of these pages I don't want to go down a rabbit hole that we don't need to. Théo, let's sync up on Monday about this.

**Comment by cadecairos** [comment]
Closing this issue due to its age, if this is work that we still want to do, please refile this with up to date information so that it can be put in the correct milestone with up to date estimates.
