### ISSUE TITLE
Localize the Initiatives page

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#3643]
Many fields are currently not localizable in Wagtail for this page, let’s fix that!

**Comment by youriwims** [comment]
@TheoChevalier after speaking with @Pomax , localizing the headers and initiative blocks is the most that can be done right now and we'll need to localize the highlights in a follow-up ticket (ticket will be posted here).

**Comment by TheoChevalier** [comment]
Sounds good @youriwims , thanks! I’ll go ahead and expose the strings in Pontoon, minus highlights. Having the initiative blocks alone should justify deploying translations of the page

**Comment by youriwims** [comment]
Not a problem—sounds great! :)

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
