### ISSUE TITLE
Allow longer strings for homepage hero button

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#3646]
As you can tell from the screenshot, the Portuguese translation needed a few more characters. I expect this issue to happen again, so we should find a way to allow for longer translations.

![Screenshot_2019-09-13 Wagtail - Editing Homepage Homepage](https://user-images.githubusercontent.com/1294206/64882980-2f439300-d656-11e9-87b7-bafc94ac2100.png)

I’m assuming the limit was set to avoid breaking the layout on mobile, but it may be possible to allow buttons to wrap in multiple lines?

FTR, the 50 characters limit is set here https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/factory/homepage.py#L33

**Comment by cadecairos** [comment]
@TheoChevalier is it a fair ask that instead of a 1:1 translation, we get a localized string? A button with that much text in it looks pretty crowded.

**Comment by kristinashu** [comment]
Agree, I don't think button text should be that long (including the English version). @TheoChevalier are you ok to keep this as is but push for shorter button text in general i.e. just "Share your story"

**Comment by TheoChevalier** [comment]
> Agree, I don't think button text should be that long (including the English version). @TheoChevalier are you ok to keep this as is but push for shorter button text in general i.e. just "Share your story"

I think we can do this, yep. If we keep hitting this issue, we can think about making this requirement more prominent, for instance by editing the helptext next to the field.

Thanks all!
