### ISSUE TITLE
YouTube story share out

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3647]
[Lot's of stories are coming in](https://docs.google.com/spreadsheets/d/17kFnZMl4cq3QHAl6qOYwk10yAT90AIkTQd4pyw2Elv0/edit?usp=sharing) and [even some press](https://www.theverge.com/2019/9/12/20862352/youtube-algorithm-recommendation-social-campaign-mozilla-firefox)!

So in addition to some share assets https://github.com/MozillaFoundation/Design/issues/409 we would like to have a page on our site to showcase some of the best stories people have submitted.

Scope for this is _undefined_. At the very least it will be a standard Wagtail page with cool graphics to show a few stories. At the most it will be a sweet _down the rabbit hole_ scrolling experience. 

@beccaklam has already started some rough wireframes https://redpen.io/p/qr39aff3aebcd751ac

If we go the bigger scope, design would need to be done by Fri Sept 20 so dev can spend one sprint on it. Although, if we go with a cool scroll effect, I would recommend a dev tests it out next week so we don't have any janky surprises. 

Design should flow the campaign branding:

![](https://s3.amazonaws.com/redpen-prod/red-pen-abd9cfe7-4a97-4c30-9702-c65ffccc62f8.jpg)

cc @alanmoo

**Comment by alanmoo** [comment]
There's a few technical hurdles to address here:

* Where do we store the stories? I know they're in a google sheet right now, but are we expecting to pull them from that sheet, or store a small subset of them in the CMS? Or just hard code them into the page? How often will these be updated?
* In the ideal setup, are the entire stories featured on the main page, or just headlines? Do we stay in the "single" page experience when opening one if it's just a headline?
* Is there anything associated with stories other than text? (Images with each one?)

**Comment by kristinashu** [comment]
Good flags. Rebecca, please feel free to chime in if you have different thoughts!

> 1. Where do we store the stories? I know they're in a google sheet right now, but are we expecting to pull them from that sheet, or store a small subset of them in the CMS? Or just hard code them into the page? How often will these be updated?

We don't want to show all the stories, just the good ones (people probably don't want to read 100s of repetitive stories). I think Brandi would manually copy & paste select stories from the spreadsheet. It shouldn't need to be updated much after launch. Technically submissions will be before we launch although I don't see any harm in keeping the google submission form around after.

> 2. In the ideal setup, are the entire stories featured on the main page, or just headlines? Do we stay in the "single" page experience when opening one if it's just a headline?

Because some of the stories are quite long, we might need a secondary page or lightbox style overlay. But this is the kind of stuff Nat and Becca are exploring right now.

> 3. Is there anything associated with stories other than text? (Images with each one?)

To avoid a wall of text and to make individual stories more interesting/unique, it would be nice if designers could add an image to some of the stories. But again, this is the kind of stuff Nat and Becca are exploring right now.

**Comment by beccaklam** [comment]
> Good flags. Rebecca, please feel free to chime in if you have different thoughts!
> 
> > 1. Where do we store the stories? I know they're in a google sheet right now, but are we expecting to pull them from that sheet, or store a small subset of them in the CMS? Or just hard code them into the page? How often will these be updated?
> 
> We don't want to show all the stories, just the good ones (people don't want to read 100s of repetitive stories). I think Brandi would manually copy & paste select stories from the spreadsheet. It won't need to be updated much after launch. Technically, submissions will be before we launch although I don't see any harm in keeping the google submission form around after.
> 
Yes, I'm meeting more to talk with Brandi on Monday but it would only be a subset. I don't think it would need to be updated after launch, will confirm with Brandi.
> > 1. In the ideal setup, are the entire stories featured on the main page, or just headlines? Do we stay in the "single" page experience when opening one if it's just a headline?
> 
> Because some of the stories are quite long, we might need a secondary page or lightbox style overlay. But this is the kind of stuff Nat and Becca are exploring right now.
> 
Yeah, it'll probably be a pull quote of some sort to draw a user in to click into the full story.
> > 1. Is there anything associated with stories other than text? (Images with each one?)
> 
> To avoid a wall of text and to make individual stories more interesting/unique, it would be nice if designers could add an image to some of the stories. But again, this is the kind of stuff Nat and Becca are exploring right now.

+1 to what Kristina said.

**Comment by kristinashu** [comment]
Two more follow up questions from Alan:

1. Do we have enough content to actually feature things
> Brandi will have about good 30 stories to share

2. Have we run it by Kevin/Brandi to see if, when paired with the content we have, they think it might be interesting enough to generate a new media cycle?
> Rebecca has had regular check-ins with Brandi and they are on the same page. Rebecca will talk to Kevin but he is impressed with the unsolicited press so far. 
Note there are now 1244 stories submitted and we haven't shared any of the stories out yet so it will be new content for people.

Rebecca and I just chatted, she's leaning towards a [cool scroll effect](https://www.watdoenwevoorhetklimaat.be/) for some intro/context text and then a grid of the stories below it.

**Comment by kristinashu** [comment]
Updated wireframes https://redpen.io/p/qr39aff3aebcd751ac and initial comps https://redpen.io/p/fc1dd017be6f0171be.

If we proceed with this we would have limited dev time so let's try to keep this a simple as possible and try to rely on cool graphics we can make to make the site look good rather than unique styling from devs. Maybe it would help to think about it as:
- what the share graphic for a story would look like in twitter
- what site would look like on mobile

**Comment by kristinashu** [comment]
Yay we get to have one week of @mmmavis on this! This is very exciting! 

Rebecca has also confirmed with Kevin that he believes the stories and the site will go over well with press!

Recap from post-stand chat:
- Rebecca will get intro copy from Brandi/Jen this week
- Rebecca has main YT meeting with advocacy tomorrow and they will highlight the most press-worthy stories
- Rebecca will update wireframes today ("rabbit hole" scroll for intro then static stories below ( exploring two possible layouts for stories - either single page or with click through to read the story))
- Natalie will continue to explore visual designs

Once Rebecca has the wireframes then we will all check-in with Mavis for her input on what is actually doable in one week.

**Comment by beccaklam** [comment]
Example sites @mmmavis:
1) https://everytown.org/momentsthatsurvive/
2) https://www.watdoenwevoorhetklimaat.be/

**Comment by beccaklam** [comment]
Updated wireframes here @mmmavis ! cc: @natalieworth

**Comment by beccaklam** [comment]
Invision Prototype for desktop: https://mozilla.invisionapp.com/share/THU06X9A53M#/384781753_Homepage

**Comment by beccaklam** [comment]
Updated share buttons in the redpen: https://redpen.io/p/qr39aff3aebcd751ac @kristinashu @mmmavis @natalieworth

**Comment by kristinashu** [comment]
Prototype looks great!

I've started a requirements list, please add what you can https://docs.google.com/document/d/1snVqs36jl6yG99EgIRaKDyqYT2znPro4dxhIkcrOAwQ/edit#

Notes from crit:
- Rebecca to get first draft of copy from Jen/Brandi tomorrow
  - Will provide them with a character count but suggestion about 3-5 short sentences
- Jen/Brandi to provide final story selection and final intro text by next Thurs
  - 16 of best are under "[For YouTube meeting](https://docs.google.com/spreadsheets/d/17kFnZMl4cq3QHAl6qOYwk10yAT90AIkTQd4pyw2Elv0/edit#gid=206364035)" tab
- Illustrations are safer probably safer than video screen caps for legal review

From Mavis' comment in slack:
> chatted about infrastructure for the YouTube regrets campaign. To make the site easier to manage and easier to localize, we are planning to create new Wagtail page type and store regrets on CMS

> note that intro z-scroll won’t look as nice if we are localizing things as we can’t predict how long each sentence is going to be etc

**Comment by kristinashu** [comment]
Ok I did this late at night so it might be terrible... https://redpen.io/p/ejbd317099554ec032. I took a stab and the layout and tried to simplify things for dev but everyone people keep exploring!

**Comment by kristinashu** [comment]
w00t some good news via Rebecca/Brandi! 

Deadline is pushed back by a couple days:
- Soft-launching on Monday, Oct. 7 for media
- Publicly launching on Tuesday, Oct. 15

**Comment by kristinashu** [comment]
Separated Redpens so it will be clearer for devs:
- Wireframe explorations https://redpen.io/p/qr39aff3aebcd751ac
- UI explorations https://redpen.io/p/fc1dd017be6f0171be
- Final comps **will go** here https://redpen.io/p/ejbd317099554ec032

**Comment by kristinashu** [comment]
Moving on from this ticket in-lieu of this _next-steps_ ticket https://github.com/mozilla/foundation.mozilla.org/issues/3678
