### ISSUE TITLE
https://foundation.mozilla.org/campaigns/ shouldn’t list private pages

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#3658]
https://foundation.mofostaging.net/campaigns/ currently lists private pages (e.g. the Snapchat one), I think they shouldn’t appear here (or anywhere else). I’ve checked in private mode too, to make sure it was listed even if I’m not signed in.

**Comment by Pomax** [comment]
good point, it looks like we're missing `public()` in addition to `live()`.
