### ISSUE TITLE
investigate whether we hit the get_root_or_page tag at all

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#3664]
In a recent deploy test we forgot to actually load the code that's suppose to run when calling the `get_root_or_page` tag, and bizarrely this did not cause any problems or throw any errors... we should investigate why that is: are we not hitting the template that relies on it for some reason?

**Comment by youriwims** [comment]
Additionally, [evaluate if this tag needs it's own file](https://github.com/mozilla/foundation.mozilla.org/pull/3663#discussion_r325328516).

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
