### ISSUE TITLE
Improve analytics on donate popover

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#3679]
The pop-over is...not great, from the experience of a user visiting the site for the first time. I'm curious what percent of people actually click the donate link vs closing the panel. I think we need some more analytics in [this file](https://github.com/mozilla/foundation.mozilla.org/blob/82e69ab30a050180f601f3cf26dac175284866c1/source/js/donate-modal/donate-modal.jsx)

**Comment by kgeorgiou** [comment]
Is this still applicable? 
The Donate buttons now redirect to https://donate.mozilla.org and the `donate-modal.jsx` was removed in #3696
