### ISSUE TITLE
Remove the timeout-based donate banner

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#3682]
We've gotten a fair bit of backlash against it on popular news sites, and it interferes with local dev work - Can we remove this without significantly impacting donations? (given that it seems to be burning goodwill... =S)

/cc @alanmoo @xmatthewx

**Comment by xmatthewx** [comment]
I'm okay with turning it off. I'll also file a design ticket to come up with something less annoying. Something slim at the bottom of the screen, or a slide down from the top that moves content down rather than covering it up. Modals like these make me cranky.
