### ISSUE TITLE
Set up a "youtube regrets" page in wagtail

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#3683]
See #3547 

# Youtube regrets page dev master issue

- [x] new page type specific for the Youtube Regrets campaign
- [x] new associated template file (probably in `wagtailpages/templates/wagtailpages/pages`?)

In terms of page properties, the page should have:
- [x] a streamfield `intro_text` that only allows picking text components
- [x] a streamfield `intro_image` that only allows picking image components
- [x] a streamfield `regret_stories` that only allows picking "Youtube Regret" components.

In terms of custom blocks/components, we need:
- [x] a "Youtube Regret" streamfield component that allows for an image, heading, and a richtext block for housing a few paragraphs of text.

In terms of templating, the template should have html/blocks for:
- [x] a special header section
- [x] share buttons similar to the blog post social share buttons
- [x] a block for rendering out a streamfield body
- [x] a “Load more” button

Animation
- [x] z-axis scroll animated intro for desktop

**Comment by Pomax** [comment]
all work is pending R+, this issue will close when all outstanding work has been merged into master.

**Comment by kristinashu** [comment]
Landed and it's amazing https://foundation.mozilla.org/en/campaigns/youtube-regrets/!!!
