### ISSUE TITLE
Create new page template for Youtube Regrets page

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#3687]
Create a skeleton template for the Youtube Regrets page, to be created in #3684

This template needs:
- [x] a special header section
- [x] share buttons similar to the blog post social share buttons
- [x] a block for rendering out a streamfield body
- [x] a “Load more” button

**Comment by kristinashu** [comment]
😱 https://foundation.mozilla.org/en/campaigns/youtube-regrets/
