### ISSUE TITLE
Create a "Youtube Regret" component

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#3688]
We need to implement a "Youtube Regret" streamfield component that allows for an image, a heading, and a richtext block for housing a few paragraphs of text.

**Comment by kristinashu** [comment]
Two layouts depending if there is an image or not https://redpen.io/p/ejbd317099554ec032. All elements should follow our style guide.

Desktop:
<img width="783" alt="image" src="https://user-images.githubusercontent.com/1068783/65462942-ab369b80-de0b-11e9-8bd4-f6812d30ebbd.png">

Mobile:
<img width="319" alt="image" src="https://user-images.githubusercontent.com/1068783/65463042-d7eab300-de0b-11e9-9a76-3d4498295427.png">

**Comment by mmmavis** [comment]
@Pomax I'm wondering how users select regrets to feature in the intro animation? Should we add a property `featured` to  "Youtube Regret" streamfield component so users can toggle that checkbox if they want certain regrets to be featured?

**Comment by kristinashu** [comment]
If you need realistic placeholder copy, the stories in the "final list" tab are final https://docs.google.com/spreadsheets/d/17kFnZMl4cq3QHAl6qOYwk10yAT90AIkTQd4pyw2Elv0/edit#gid=229438003

**Comment by mmmavis** [comment]
Design has been changed.
Desktop: https://redpen.io/kz80aa1b9eedc210b4
Mobile: https://redpen.io/wvce47e03aa936efbf
