### ISSUE TITLE
Implement the vortex of regret

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#3690]
Implement the vortex/tunnel or regret, with regret images, icons, and text. We can hopefully use normal HTML+CSS for that, with `<a href="#story-10">` elements so that we don't even need JS for jump-to-story functionality.

**Comment by mmmavis** [comment]
Hey @Pomax did you mean for the regrets in the list below the intro?

**Comment by kristinashu** [comment]
I think this is the same as https://github.com/mozilla/foundation.mozilla.org/issues/3694?

**Comment by mmmavis** [comment]
Seems like a dupe. Closing.
