### ISSUE TITLE
Homepage blog order

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3692]
Right now the blog selection looks like this:
<img width="1042" alt="Screen Shot 2019-09-23 at 3 09 03 PM" src="https://user-images.githubusercontent.com/1068783/65466618-4764a080-de14-11e9-9e44-08001b2ce192.png">

Please add the ability to order things like in highlights:
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/1068783/65466670-66fbc900-de14-11e9-84b7-dedf77b1ba01.png">

**Comment by alanmoo** [comment]
This could be straightforward, but @kristinashu will confirm if this is the right approach.

**Comment by kristinashu** [comment]
@mmmavis pointed out that the blog post are listed with the most recent first. 

Would there be a _straightforward_ way to make the key post not follow that logic? So we can choose the key post (post with the image) and then the rest of the posts would be in chronological order (posts without image on the right side)?

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/1068783/65537791-c3b1bf00-deba-11e9-8300-e15ee982bc2e.png">

**Comment by mmmavis** [comment]
Maybe we can remove the auto sort and just make this component the same as the highlights - let CMS editors have full control over the order of the blogs they want. Since we only have 4 featured blogs in total, I think manually order them won't be a huge pain.

**Comment by kristinashu** [comment]
Ok sounds good!

**Comment by mmmavis** [comment]
k this should be quick to fix. I'll file a PR soon.
