### ISSUE TITLE
Build z-axis scroll animated intro for YouTube Regrets page

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#3694]
Build z-axis scroll animated intro for YouTube Regrets page (desktop only).

@kristinashu in terms of the animation & scroll effect, are we thinking about having something like the first part (purple background part) of this example? https://www.watdoenwevoorhetklimaat.be/ (with color, type, and other design changes of course)

**Comment by kristinashu** [comment]
Yeah something like that. Except we will have about 4 sentences to animate through.

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/1068783/65468454-fc995780-de18-11e9-8974-6f106bf68a2f.png">

cc @natalieworth @beccaklam is that right?

**Comment by mmmavis** [comment]
Content to show in the animation

- 4 sentences of text
- around 10 images pulled for the pool of regrets we have

@Pomax any suggestion on how we can store the above in CMS?

**Comment by Pomax** [comment]
Correct - the page will have all the named fields that represent that text that goes in the intro, and we write the template in a way that lets us work with that data. Any html/svg we need to write can go straight into the template, and any CSS/JS for it can go in .css and .js files that we then load in that template with the usual `<link>` and `<script>` elements.

(I still suspect we don't need any JS whatsoever for the animation, as long as we animate `<a href="#regret-number">...</a>` around the swirling images)

**Comment by mmmavis** [comment]
@Pomax to select the featured regret images to show in the intro, should we

1. (If the order of the images matters) Create another CMS field for the intro section for users to select regrets they wanna pull images from
2. (If the order of the images doesn't matter) In the "YouTube Regret" streamfield component we are going to build and use for list of regrets down the page, we simply add another property `featured`.

**Comment by mmmavis** [comment]
Re: animation

I guess we should be calling it an interactive, animated intro, rather than just animation. 
It's more of a "scroll-to-zoom-in" effect than text and images floating around for users to click on to jump to a specific regret down the page. See example here: https://www.watdoenwevoorhetklimaat.be/  (the blueish purle background part)

**Comment by kristinashu** [comment]
I'm leaning towards keep the top interactive section and the bottom stories section fairly separate to allow for more design flexibility. 

For the intro section could we say:
- user upload 4-4 sentences 
- user uploads 10 (need to confirm the number) images

**Comment by Pomax** [comment]
to clarify: does that mean there will be no correspondence between the images in the intro, and the images in the stories? (e.g. we do not pull images from stories, we have a dedicated 10 images)

**Comment by kristinashu** [comment]
Oh yeah sorry, I should have said _staff_.

Also sorry, I might be complicated things. Ignore my comment about keeping them separate. 

So yes, if 10 of the stories below have images then we should pull those 10 images into the intro animation. Order of the images in the animation can be the same as in the story section below.

**Comment by mmmavis** [comment]
@Pomax , I met with Nat and Kristina just now. Back to your question

> to clarify: does that mean there will be no correspondence between the images in the intro, and the images in the stories? (i.e. we do not pull images from stories, we have a dedicated 10 images)

Scratch what Kristain said above in this [comment](https://github.com/mozilla/foundation.mozilla.org/issues/3694#issuecomment-534726682). The images we are showing in the intro can be *any* images, they could be illustrations, regret images, icons, ... etc.

This is the content we want to include in the interactive intro:

- 5 individual sets of plain text (each is about a setence long)
- 10 images of staff's choice 

@Pomax can you advise what CMS fields/components we should have for this intro section?
