### ISSUE TITLE
Final YouTube updates

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3712]
Home stretch! Comps are looking sweet https://redpen.io/p/fc1dd017be6f0171be and all the files are in [Drive](https://drive.google.com/drive/folders/1oAJEeV8JEC1_K9WhfEFBRfeQmSoxZ1-Z?usp=sharing).

Rebecca to:
- [x] Get share copy from Brandi/Jen and give it to Mavis
- [x] Compile stakeholder feedback
- [ ] Check-in with comms/marketing https://redpen.io/p/vo2ab21e6e17b0c110
- [x] Add content to site when ready

**Comment by beccaklam** [comment]
@kristinashu update from Brandi regarding content:

> hey there! just wanted to flag for you that I've removed one story from the list "we're way past playboy now" because legal wasn't comfortable with it. it was line 26 in the doc. also added 3 more at the bottom yesterday afternoon which were the ones we were waiting for localisatio

n on!

**Comment by beccaklam** [comment]
Share copy here: @mmmavis 

> 28 reasons why YouTube must change: startling stories of YouTube’s recommendations leading people down bizarre and dangerous paths

**Comment by kristinashu** [comment]
Add that to this dev ticket https://github.com/mozilla/foundation.mozilla.org/issues/3718

**Comment by kristinashu** [comment]
@beccaklam [here](https://github.com/mozilla/foundation.mozilla.org#workspaces/mofo-engagement-585335eab729771d0736378d/board?useDefaultFilterLogic=false&repos=50445578,76596293,74170666,28190738,174024666&search=youtube) are the remaining YouTube tickets. Could you please QA [the site](https://foundation.mozilla.org/campaigns/youtube-regrets) as well and open any additional issues?

**Comment by kristinashu** [comment]
I'll send an email EOD today with an update in dev progress, localization, and share the social graphics with Kevin, Brandi, Theo.
