### ISSUE TITLE
Selection order of blog posts on homepage

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3714]
Jen has pointed out that it would be better if the most recent posts were at the top.

Screen cap from prod:
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/1068783/66071078-567bda80-e507-11e9-84cd-84620e0e7595.png">

**Comment by Pomax** [comment]
I've filed a Stackoverflow question to hopefully find out whether this is possible at all - https://stackoverflow.com/questions/61353431/sorting-pages-in-a-wagtail-pagechooserpanel-dialog
