### ISSUE TITLE
YouTube links and share buttons

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3718]
Follow up from https://github.com/mozilla/foundation.mozilla.org/pull/3715#issue-324001057

#### For links
> I need to know what treatments we want to override to each scenario. E.g., link in heading, link in paragraph, hover state, active state etc. Please refer to https://foundation.mozilla.org/en/style-guide/ for all scenarios we have to consider.
- Can all text links be the standard #EA0B12 but with an underline
- Hover/Active/Select state be a lighter shard of #FD6976] with an underline

<img width="389" alt="image" src="https://user-images.githubusercontent.com/1068783/66166452-3bcf6180-e5ec-11e9-9767-92b6f1c32db8.png">

#### Share buttons
> Our default share button is carefully set up so icon can transition smoothly between **black**(default state) and **white**(hover/focus/active state). How we do it is we only include the white version of icon like [this](https://foundation.mozilla.org/_images/glyphs/social-share/facebook-share.svg) and when the button is on hover/focus/active state, we use CSS to add a filter to lower the `brightness` of the icon gradually from full to `0` so it turns black. If we want a red version of share button we'll have to design it in a way so that changing from one button state to another is only a matter of adjusting the brightness factor.
- Ideally the icon color would reverse on hover but please let me know what is possible (I'm not sure I understand the constraints)
<img width="86" alt="image" src="https://user-images.githubusercontent.com/1068783/66166551-7afdb280-e5ec-11e9-84c2-b1700dbae1bd.png">

**Comment by kristinashu** [comment]
Share copy
> 28 reasons why YouTube must change: startling stories of YouTube’s recommendations leading people down bizarre and dangerous paths

**Comment by mmmavis** [comment]
I'll open a new ticket for adding share copy since it requires changing a component that's shared across fo.mo.

**Comment by kristinashu** [comment]
What about the load more button? New ticket or here?

Prod:
<img width="181" alt="image" src="https://user-images.githubusercontent.com/1068783/66243289-e90fab80-e6b8-11e9-8b51-f09fe7d7ef86.png">

Comp:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/1068783/66243404-5a4f5e80-e6b9-11e9-9128-8354a305a364.png">

**Comment by mmmavis** [comment]
I have a PR up for all the style overrides mentioned here!
