### ISSUE TITLE
YouTube: add page anchors

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3719]
Post MVP: create anchors for each story so if a user wanted to share a specific story they could.

From @Pomax:
> Adding ids so that url#story-1 works is trivial, but I assume "something" should be a link to those anchors as well so that people can copy the link somehow. Should that be the regret story's heading?

Design should mock this up first.

**Comment by kristinashu** [comment]
@beccaklam what about something like this? Do you have any other ideas? Clicking it would show a checkmark (like the page share buttons).

<img width="783" alt="image" src="https://user-images.githubusercontent.com/1068783/66228980-a7213e00-e695-11e9-89e2-23eac94cd07a.png">

**Comment by beccaklam** [comment]
I like that! @kristinashu I do think it would be stronger with some text.

**Comment by beccaklam** [comment]
Like 'Share this story' or something?

**Comment by kristinashu** [comment]
Like this? I don't think it needs both text + icon and I can't really find a better spot to put the text.

<img width="847" alt="image" src="https://user-images.githubusercontent.com/1068783/66425846-70b12f00-e9c5-11e9-9d76-dde6f5876d83.png">

**Comment by kristinashu** [comment]
Moving this to be a stretch goal.

**Comment by kristinashu** [comment]
Won't be adding this feature.
