### ISSUE TITLE
YouTube Regrets: turn hardcoded text "scroll" into localizable string

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#3720]
Turn hardcoded text `scroll` into localizable string.

https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templates/wagtailpages/pages/youtube_regrets_page.html#L38

@Pomax can you provide a suggestion on how we should do it?

**Comment by Pomax** [comment]
This is probably a good candidate for adding to our `makemessages` template localisation, which is still slated for the October 7th milestone

**Comment by TheoChevalier** [comment]
Confirming this can be fixed with #3529. 

YT strings are wrapped here: https://github.com/mozilla/foundation.mozilla.org/pull/3529/files#diff-bbf48b8f7902f6ea2ceb6a5b420e2ba2

I try to keep track of strings landing, but if I’m missing something, let me know
