### ISSUE TITLE
YouTube: small style fixes

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3727]
### Main styling fixes:
- [ ] Story title should be 38px instead of 42px
- [x] End the background gradient higher up on the page (so only the first story has some pink background but the rest of the stories are on white background so they're easier to read)
- [ ] Increase spacing between stories to about 80px (see screen cap below)
- [ ] Make the spacing above and below the story title the same (maybe about 24px) (see screen cap below)
- [ ] Decrease the amount of opacity even further for the images that haven't "passed" the text yet. Sometimes the overlap makes it hard to read (see screen cap below).
- [x] Center the scroll icon (see screen cap below)

Screen cap from comp:
<img width="942" alt="Screen Shot 2019-10-04 at 3 37 39 PM" src="https://user-images.githubusercontent.com/1068783/66244469-705f1e00-e6bd-11e9-8f12-a0d1f3dd2a87.png">

Screen cap from comp:
<img width="867" alt="Screen Shot 2019-10-04 at 3 39 15 PM" src="https://user-images.githubusercontent.com/1068783/66244470-705f1e00-e6bd-11e9-8a14-1b875090a6c7.png">

Screen cap from prod:
<img width="332" alt="image" src="https://user-images.githubusercontent.com/1068783/66244704-9df89700-e6be-11e9-889e-4b2b8eb6a715.png">

Screen cap from prod:
![Screen Shot 2019-10-07 at 4 52 42 PM](https://user-images.githubusercontent.com/20977376/66347693-eadca780-e922-11e9-8231-413a991e0367.png)

### Nice-to-have circle updates:
- Would it be possible to increase the size of the photos? Currently they feel a bit small and makes the "tunnel" feel a little sparse
- Concentric circle 1: Can the size of the first circle be smaller, perhaps half the size it is now? 
- Concentric circle 2: The spacing between the concentric circles seem to be different for each circle. Could we make it the same and increase the spacing? I would guess perhaps 2-3x the spacing we have now. What https://www.onfaitquoipourleclimat.be/ has for its circles is a good benchmark?
- Would it also be possible to blur both sides of the circles and increase the blur? Currently it looks like only one side is blurred?

**Comment by ankiiitraj** [comment]
I want to contribute to this fix. Can you assign me this?

**Comment by mmmavis** [comment]
Hey @anilkanji , thanks for offering help! This is not a ticket for contributors to pick up as our team is actively working on tickets related to this YouTube project.

**Comment by mmmavis** [comment]
@kristinashu Can we prioritize items on the above list? Non-animated intro related tweaks should be easy to do but tweaking anything in the intro actually takes more time and effort than they seem. For example, the circles are actually placed in a 3D space and positioned differently along the z-axis (depth). The spacing between each circle is actully exactly the same but 3D perception makes them seem different. https://www.onfaitquoipourleclimat.be/ probably implemented it in a 2D way. So it really depends on how much more time we wanan spend on this projct. As for blurring the rings... this is as much as we can do with using purely CSS to draw the circles, we can try using images with transparent background and see how they turn out.

**Comment by kristinashu** [comment]
Ok @mmmavis, I've prioritized the list. The circle updates can be a _nice-to-have_ or a _maybe-later_ update.
