### ISSUE TITLE
Banner on https://foundation.mozilla.org/en/about requires to be loded faster.

### ISSUE THREAD

**Issue by ankiiitraj** [mozilla/foundation.mozilla.org#3728]
The banner at the top loads very slow and requires lazy load.
![WhatsApp Image 2019-10-07 at 9 38 44 AM](https://user-images.githubusercontent.com/48787278/66284617-4fc5dc80-e8e6-11e9-957b-cae724d7b114.jpeg)

**Comment by ankiiitraj** [comment]
I want to work in this issue. Assign this to me.

**Comment by kristinashu** [comment]
Thank you for pointing this out. I have updated the images on the About pages through the CMS so it should load faster now.
