### ISSUE TITLE
Add new CMS fields for PNI products

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#3729]
master issue: https://github.com/mozilla/foundation.mozilla.org/issues/3716

ref: https://docs.google.com/spreadsheets/d/1tcFlDgrxxo4Mj5QP-pCFyB4QSCuPMi5vumLQu_r5-QI/edit#gid=0

Add the following fields to the PNI product model, so that these fields can be given content in parallel with the rest of the product page update work.

- [x] Review Date https://github.com/mozilla/foundation.mozilla.org/issues/3572
- [x] Privacy policy
- [x] Privacy policy helptext (**note** this needs to be "cleared" before it truly applies to its new role)
- [x] How does it [this product] share data?
- [x] Collects biometric data?
- [x] Collects biometric data helptext 

In order to facilitate the new 4-state fields we'll also need a new type for "yes/no/unknown/NA" (we currently use the nullboolean, which has been deprecated)

- [x] Privacy policy: 4state (**note** new field type: `ExtendedYesNoField`)
- [x] Privacy Policy helptext: 5000 charlimit
- [x] "How does it share data?": 5000 charlimit
- [x] helptext for "Collects biometric data": 5000 charlimit

**Comment by Pomax** [comment]
@beccaklam does this over all the new fields or did I miss any?

**Comment by Pomax** [comment]
@kristinashu @beccaklam for the new text fields, are there any charlimits? We're using a 5000 charlimit for most of our help texts at the moment, so I'm thinking we just use the same limit?

**Comment by kristinashu** [comment]
@Pomax note that the Review Date has already been added to the CMS, I've added a link to the ticket in your comment. 

Sticking with the same character limit sounds good (we have a lot of control over the copy so doesn't really matter).

**Comment by beccaklam** [comment]
> @beccaklam does this cover all the new fields or did I miss any?

Looks good to me. I think the only field missing is the "User friendly privacy info" field and its equivalent help text field. cc: @kristinashu

**Comment by kristinashu** [comment]
Yea I had that as a _shift_ in the [spreadsheet](https://docs.google.com/spreadsheets/d/1tcFlDgrxxo4Mj5QP-pCFyB4QSCuPMi5vumLQu_r5-QI/edit#gid=0). I was thinking we could turn "Privacy Policy Reading Level" into "User friendly privacy info" (happy face = `Yes` and the sad = `No`). But that's probably tricky to do, so if that's the case then Pomax please just remove "Privacy Policy Reading Level" and add "User friendly privacy info".

**Comment by Pomax** [comment]
I've made a new field for `user_friendly_privacy_policy` but we can probably do a migration that takes the data currently encoded in `privacy_policy_reading_level` and use that to automatically set the new field.

**Comment by kristinashu** [comment]
That would be super cool!

**Comment by Pomax** [comment]
this all landed
