### ISSUE TITLE
PNI: implement updated homepage banner

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3752]
Update banner header image with this new graphic [here](https://drive.google.com/drive/folders/1CeZ3nTJ3zIyqRSqUtj7r4cjOYvktq3qk?usp=sharing).

**Comment by natalieworth** [comment]
@kristinashu Added the [new badges here](https://drive.google.com/drive/folders/1hQmCYTr7pI16-lGwPKKWLwgDDvaIwLmZ?usp=sharing).

Let me know if I can help the devs with this anymore.
