### ISSUE TITLE
Clean up dropdown code

### ISSUE THREAD

**Issue by youriwims** [mozilla/foundation.mozilla.org#3759]
See #3691 #3628 

[Follow-up clean-up ticket]: Look through updated files in these tickets' associated PRs to see if anything can be refactored and/or cleaned up.

Look into:
- localizing `#nav-newsletter-form-wrapper` `height` value.

**Comment by youriwims** [comment]
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/36484608/66776900-8925bb80-ee95-11e9-8b66-3c3712fb5a6a.png">

Error state spacing fixed in #3771 cc @kristinashu

**Comment by youriwims** [comment]
Dropdown styles component-ized in #3771 and added to buyer's guide.

**Comment by cadecairos** [comment]
Closing this issue due to its age, if this is work that we still want to do, please refile this with up to date information so that it can be put in the correct milestone with up to date estimates.
