### ISSUE TITLE
PNI homepage/categories: only show products with review date within one year

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3760]
We have added a review by date to each PNI product. Can we still show older products on our category product pages but hide them on the homepage?

**Comment by Pomax** [comment]
On @caltrider's request, I'm turning this into hiding both on homepage and category pages

**Comment by Pomax** [comment]
I'll fix the review cutoff date to June 1st 2019. That way we don't run into weird "sliding window" issues (because 1 year ago is a different cutoff date ever day), and should catch anything that's part fo the new batch.
