### ISSUE TITLE
RSS feed unformatted and not full text

### ISSUE THREAD

**Issue by sbaack** [mozilla/foundation.mozilla.org#3763]
**Describe the bug**
Unlike the RSS feed for the Mozilla blog (https://blog.mozilla.org/), the blog of the Foundation (https://foundation.mozilla.org/en/blog/) does not provide a full text RSS feed and the texts provided are not formatted (no line breaks, italics, links etc.)

**To Reproduce**
Subscribe to https://foundation.mozilla.org/en/blog/atom/ or https://foundation.mozilla.org/en/blog/rss/ using Feedly. I haven't tried other RSS services.

**Screenshots**
Here is a comparison of a blog post that appeared both on the [blog of the Foundation](https://foundation.mozilla.org/en/blog/the-next-internet-health-report-will-zoom-in-on-solutions/) and [at internethealthreport.org](https://internethealthreport.org/the-next-internet-health-report-will-zoom-in-on-solutions/), both displayed in Feedly:

<img width="1429" alt="Screenshot 2019-10-10 at 15 34 31" src="https://user-images.githubusercontent.com/8274140/66597328-081daa00-eb9f-11e9-8d61-05bee7623b60.png">

**Additional context**
When you try to add the feed to Feedly by just using https://foundation.mozilla.org/en/blog/, Feedly will fail to find any RSS feed saying "Please contact the website and ask them if they offer a valid RSS feed." Not sure if this is a bug in Feedly or a problem with the Foundation's website. Using https://foundation.mozilla.org/en/blog/atom/ or https://foundation.mozilla.org/en/blog/rss/ works.

**Comment by cadecairos** [comment]
This is caused in https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/rss.py
