### ISSUE TITLE
Add new VP to sites

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3765]
Need to add new VP - Bob Alotta to both:
- https://foundation.mozilla.org/en/about/leadership/
- https://www.mozilla.org/en-US/about/leadership/

@anilkanji to gather content:
 - headshot
 - name and title
 - twitter handle
 - website (optional)
 - link to Mozillians profile
 - bio

Kristina to crop image and add to fo'mo site. 
Once ready, @alanmoo to assign a dev to add to moco site.

**Comment by kristinashu** [comment]
This has been updated on our site. Just info the extra info bio info Bob in order to add it to mozilla.org.

**Comment by alanmoo** [comment]
@anilkanji when you've got the content, drop it in this ticket and assign to me.

**Comment by kristinashu** [comment]
Here's the name, title, and headshot. So just need the bio.

J. Bob Alotta, VP, Global Programs.jpg

![J  Bob Alotta, VP, Global Programs](https://user-images.githubusercontent.com/1068783/67042090-f9258300-f0db-11e9-8e6f-08f49e29445e.jpg)

**Comment by anilkanji** [comment]
Hi @alanmoo - it looks like we're not going to get the bio for a little while. Can we please start the process to getting this up on mozilla.org, and we can add the bio in later?

**Comment by alanmoo** [comment]
My team is pretty light this week and next/focused on PNI so I've submitted this to the Bedrock team intake form.

**Comment by ejregithub** [comment]
The websites team can do this. Ping me when the bio is ready.

**Comment by anilkanji** [comment]
@ejregithub We're still waiting on the bio. Would you please be able to put it up without a bio for now?

**Comment by ejregithub** [comment]
Please push for the bio. Right now the request does not meet the definition of ready (all required components available) for the team to take on a work request.

**Comment by alanmoo** [comment]
@ejregithub Here's the bio. It came with a request to include the photo credit (Photo Credit: Lola Flash) wherever it's used. Is there somewhere it can be attached?

```
J. Bob Alotta is a veteran movement builder and nonprofit executive working at the intersection of technology and communities.
 
Prior to joining Mozilla, Bob led the Astraea Lesbian Foundation for Justice, a global foundation based in New York City that provides critical resources to LGBTQI+ organizations and individuals around the world. Over eight years, Bob quintupled the global footprint of the organization which makes more grants in the global south and east than any other funder in their sector. She built a funding program aimed specifically at strengthening movements by adding extra support for digital security, data use, and internet freedom to otherwise “non-tech” grants. Bob worked with major funders to bring money into Astraea -- and to influence what else these funders invested in worldwide. And, Bob built bridges between the LGBTQI+ and digital rights worlds.
 
It was through this last bit of work that Bob met Mozilla: At MozFest and as a Mozilla fellowship host organization. Now serving as Vice President, Global Programs at Mozilla Foundation, Bob brings their experience both building movements, and building bridges across movements. Bob works with allies across the movement to develop clear goals and real momentum on issues like trustworthy AI; helps Mozilla fellows and awardees become stronger community organizers and leaders; and grows the diversity and geographical scope across our programs, with an emphasis on expanding our work outside North America.
```

**Comment by alanmoo** [comment]
@ejregithub Anything else you need from us for this one?

**Comment by kristinashu** [comment]
Adding to this ticket that Ronald Lemos needs to be removed from our sites. He has resigned from the board and needs to be moved to emeritus ASAP. I have removed him from https://foundation.mozilla.org/about/leadership/ and added a comment to remove him from mozilla.org https://github.com/mozilla/bedrock/issues/8412.

**Comment by kristinashu** [comment]
Thank you all! This is live!
