### ISSUE TITLE
PNI: update badge

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3767]
- [ ] Update large badge on product detail page [@natalieworth to add svg]

- [ ] Update mini badge on homepage [@natalieworth to add svg]

**Comment by natalieworth** [comment]
@kristinashu I have the updated svg badges ([with the stars here](https://drive.google.com/drive/folders/1hQmCYTr7pI16-lGwPKKWLwgDDvaIwLmZ?usp=sharing)).

**Comment by mmmavis** [comment]
@kristinashu is this about replacing existing badges with the files Nat attached?

**Comment by kristinashu** [comment]
Yes that's right, they should be the same size and format (we're just replacing the checkmark with a star).

**Comment by mmmavis** [comment]
@kristinashu @natalieworth new SVGs are in `#909090` vs current ones are in `#000000`. Just wanna confirm we are updating the colour to `#909090` as well.

**Comment by kristinashu** [comment]
Honestly I'm not sure if that was intentional or not but I think #909090 actually looks good so let's go with that!
