### ISSUE TITLE
Add donate footer to YouTube

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3772]
YouTube campaign page is missing the purple donate banner above the footer.

Should look like the rest of our pages:
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/1068783/66774105-99c63980-ee75-11e9-9a5b-599799ec3538.png">

cc @Pomax @mmmavis

**Comment by ShivamRawat0l** [comment]
@kristinashu I would like to work on this issue. Can you post a link to youtube campaign page ?

**Comment by alanmoo** [comment]
It's a specific page type: `Youtube regrets page` that needs this. I think there's a block that just needs to be included in this template.

**Comment by Pomax** [comment]
unassigning due to inactivity.
