### ISSUE TITLE
Update PNI OG copy and image

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3785]
This is an dev ticket to update the OG graphic and copy. Currently blocked by:

@natalieworth to add image here

@caltrider to add copy here

**Comment by natalieworth** [comment]
@kristinashu added the [image and psd file here](https://drive.google.com/open?id=1U_qMMTa9IoL7YPB_4KDKMn9088u30_xt&authuser=natalie@mozillafoundation.org&usp=drive_fs)

**Comment by natalieworth** [comment]
> @kristinashu added the [image and psd file here](https://drive.google.com/open?id=1U_qMMTa9IoL7YPB_4KDKMn9088u30_xt)

It's Christmas themed! Is that okay?

**Comment by kristinashu** [comment]
> It's Christmas themed! Is that okay?

Yeah I think that's the idea!

**Comment by caltrider** [comment]
2019 Holiday Buyer's Guide Social Share Copy options:
Option 1 (new)
Smart speakers, fitness trackers, security cams, & wireless headphones are cool. Are they creepy too? Find out in @Mozilla's PrivacyNotIncluded.org buyer's guide. 76 popular connected products reviewed to help you know if they are likely to spy on you.

Option 2 (more visual)
Creepy (creepy emoji) ---- Not Creepy (not creepy emoji). That is the question when it comes to shopping for connected products. Good thing @Mozilla's PrivacyNotIncluded.org buyer's guide reviewed 76 connected products to help you know what is creepy and what isn't before you buy. 

Option 3 (old)
Be smart. Shop safe using @mozilla’s PrivacyNotIncluded.org buyer’s guide. 76 popular connected products rated to help understand if they are likely to spy on you. Find out which are creepy and which aren’t.

**Comment by kristinashu** [comment]
Would be cool if emoji's could work! @mmmavis can we do this?

> Creepy 😮 — Not Creepy 😀. That is the question when it comes to shopping for connected products. Good thing @mozilla's PrivacyNotIncluded.org buyer's guide reviewed 76 connected products to help you know what is creepy and what isn't before you buy.

If not then let's go with this:

> Smart speakers, fitness trackers, security cams, & wireless headphones are cool. Are they creepy too? Find out in @mozilla's PrivacyNotIncluded.org buyer's guide. 76 popular connected products reviewed to help you know if they are likely to spy on you.

**Comment by youriwims** [comment]
@kristinashu @caltrider should this information be updated too?

![Screen Shot 2019-11-06 at 11 28 30 AM](https://user-images.githubusercontent.com/36484608/68317154-a3178000-0088-11ea-8733-3c44a27ac9c5.png)

**Comment by youriwims** [comment]
Would the only change be the number of products(76)?

**Comment by kristinashu** [comment]
I suspect the "Creepy 😮 — Not Creepy 😀..." might be too long for OG messages. Do you know?

If it is too long, then yeah just update the number. @caltrider unless you have a different suggestion?

But either way, please update the image to the red holiday version.

**Comment by caltrider** [comment]
Let's try this for that copy:
*Privacy Not Included: A Buyer's Guide for Connected Products
Smart home gadgets, fitness trackers, toys and more, rated for their privacy & security
