### ISSUE TITLE
PNI icons sometimes overlap

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3791]
Noticed that if a product is 18+ and filters are being used then the icons overlap. @beccaklam could you please find an alternative spot for the one of the overlapping icons?

<img width="293" alt="Screen Shot 2019-09-04 at 12 22 28 PM" src="https://user-images.githubusercontent.com/1068783/66963326-434d2c80-f028-11e9-9243-f92fe169bb99.png">

**Comment by beccaklam** [comment]
Will something like this work?
<img width="327" alt="Screen Shot 2019-10-17 at 11 39 58 AM" src="https://user-images.githubusercontent.com/20977376/67024720-e0649f80-f0d2-11e9-984d-3d7bb680065d.png">
In situ: https://redpen.io/cy03c326b375db0f8e
@kristinashu

**Comment by kristinashu** [comment]
What would this look like for the other products, like ones that aren't 18+ or don't have the badge?

**Comment by beccaklam** [comment]
@kristinashu It's in the in situ link! But here it is again:
![multi-icon-treatment@2x](https://user-images.githubusercontent.com/20977376/67031236-14de5880-f0df-11e9-98d5-d2076ea39c25.png)

**Comment by kristinashu** [comment]
Ah sorry I missed the link. I think this works well!

@mmmavis would this be pretty straightforward to implement or do you foresee any complications? We wouldn't want this to turn into a big thing.

**Comment by mmmavis** [comment]
This shouldn't be too complicated. I'll let you know if I end up encountering an obstacle.

**Comment by kristinashu** [comment]
Perfect! Can this work as an implementation ticket or should Rebecca open a new one?

**Comment by mmmavis** [comment]
I'll take this from here!
