### ISSUE TITLE
Email preferences don't make sense

### ISSUE THREAD

**Issue by pbbob** [mozilla/foundation.mozilla.org#3792]
Hello friends,
I dunno if this is corretc place to repurt bug, but I am confusion of the email preferences.
Is it yes to subscibe, no to unsubscribe? Please help me lol.

![screenshot](https://user-images.githubusercontent.com/34972102/66964542-f62b8380-f044-11e9-95d5-0e5017718b7e.png)

**Comment by gideonthomas** [comment]
Hi @pbbob, I re-filed your issue here: https://github.com/mozilla/bedrock/issues/8112 which I think might be the right place. Hopefully the bedrock team can provide more information there.
