### ISSUE TITLE
PNI: Emoji face bug on Edge 16

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#3794]
Emoji face bug on Edge 16 (and possibly other versions of Edge as well)

On product page, there's an extra emoji on top

<img width="829" alt="image" src="https://user-images.githubusercontent.com/2896608/67035006-a0e78480-f0cd-11e9-8107-6574a861edcb.png">

Expected:

![image](https://user-images.githubusercontent.com/2896608/67035212-14899180-f0ce-11e9-8037-1f54cd86b4f6.png)

**Comment by kristinashu** [comment]
If it's ok with you @mmmavis, I'm going to close this as "won't fix".
