### ISSUE TITLE
PNI: differences between picture background and css background

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#3795]
**Describe the bug**
There is a small difference of color between the css and the image background on the PNI page, which results in a faint square around the image:
<img width="207" alt="image" src="https://user-images.githubusercontent.com/22157921/67044693-aea70500-f0e1-11e9-9100-c425fd5dfa5a.png">

URL here: https://foundation.mozilla.org/en/privacynotincluded/

**Expected behavior**
To have the same color.

**Additional context**
Changing the class ".bg-gray" to #f5f5f5 solves the issue but I am not sure about how this affects other pages.
<img width="990" alt="image" src="https://user-images.githubusercontent.com/22157921/67045039-60decc80-f0e2-11e9-9475-ca9bcad052c0.png">

**Comment by taisdesouzalessa** [comment]
@kristinashu tagging you for triage. Let me know if I should tag Alan instead?

**Comment by kristinashu** [comment]
Thank you Tais! I've put it in the upcoming milestone.

**Comment by mmmavis** [comment]
The container background colour `#f2f2f2` is a brand color `$gray-05`. It looks like PNI product images were generated with `#f5f5f5` as background. Since regenerating all the images is time-consuming and troublesome, as the simplest solution I can update the container background to `#f5f5f5`.

**Comment by kristinashu** [comment]
Note that the background color used on the product detail page works well with the images
https://foundation.mozilla.org/en/privacynotincluded/products/nintendo-switch/
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/1068783/67119231-98f61600-f19b-11e9-91a2-c68422c7c06c.png">

**Comment by taisdesouzalessa** [comment]
The product detail page bkg color if #f4f4f4 

<img width="635" alt="image" src="https://user-images.githubusercontent.com/22157921/67119409-f5593580-f19b-11e9-917c-a89beabef8d3.png">

I would advocate for the simpler solution Mavis pointed out because it eliminates the issue quickly and the difference between the brand color and the grey we currently have is so small. 
Then update the images next year with the grey on brand. @kristinashu - what do you think?
