### ISSUE TITLE
PNI: it uses section

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3796]
Now that @caltrider has seen this section, she feels it looks empty and uninformative. @beccaklam can you please explore some other possible solutions? Maybe reverting back to have it was before???
 
<img width="850" alt="image" src="https://user-images.githubusercontent.com/1068783/67048735-96d37f00-f0e9-11e9-827c-8775bf8aeb1b.png">

**Comment by beccaklam** [comment]
@kristinashu Should we revert it back to this design:
![Screen Shot 2019-10-18 at 1 02 19 PM](https://user-images.githubusercontent.com/20977376/67113472-9a2d4000-f1a7-11e9-8f41-f79a4a7eea01.png)

So, show _"(device or app)"_ only when answer is _"Yes"_ if the answer is No for both device and app show _"N/A"_

**Comment by beccaklam** [comment]
Revised design (reverting back to what we had last year with some slight styling differences.
Updated redpen: https://redpen.io/p/aj7f2e09f704b2e4ee
### Mobile:
![image](https://user-images.githubusercontent.com/20977376/67126617-809af100-f1c5-11e9-87c1-fc5476b3d6ae.png)
### Desktop: 
![Screen Shot 2019-10-18 at 4 36 52 PM](https://user-images.githubusercontent.com/20977376/67126638-8bee1c80-f1c5-11e9-9fea-eba2925b8ebc.png)
@kristinashu

**Comment by caltrider** [comment]
As I'm going through all these products, it seems we have 4 answers to this question of what it uses:  Yes/No/NA/and ?. Would it be possible to have a ? response for this for ones we were unable to tell (this mostly comes from us not being able to buy the product or tell from the listed specs for the product).

**Comment by kristinashu** [comment]
cc @Pomax @mmmavis unfortunately we will need to update the `It uses` section to make it have 4 possible answers instead of just the 3 and then adjust the product page it to always show all the answers. Will let you know once we've finalized the design.

**Comment by beccaklam** [comment]
Dropped in some more options for the layout of this section: https://redpen.io/p/aj7f2e09f704b2e4ee (last two designs)

**Comment by kristinashu** [comment]
Thanks for mocking those up! I think you had it right with the first one. 

For devs, can you just clarify if you want `Unknown` to be styled (as `Unknown` or as `?`)? And then I think you can open an implementation ticket.

<img width="655" alt="image" src="https://user-images.githubusercontent.com/1068783/67231978-39934280-f3f5-11e9-89d5-26d7f8edf6c1.png">

**Comment by beccaklam** [comment]
Can we do something like this where if both answers are the same the format used is "Device & App" vs "Device: | App:"? This way we can use "Unknown" for consistency instead of "?".
![Screen Shot 2019-10-21 at 3 48 59 PM](https://user-images.githubusercontent.com/20977376/67238067-82112700-f41a-11e9-95d6-8fe924d075e5.png)
@kristinashu @Pomax @mmmavis

**Comment by Pomax** [comment]
we can uplift the "it uses..." fields, is this something we want done over mozfest, or post-mozfest?

**Comment by kristinashu** [comment]
Only 1 products has 'unknown' for both so it's an edge case and probably ok it it ends up going onto two lines.
