### ISSUE TITLE
Bad Request when publishing es/pt YouTube stories

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#3798]
I’m hitting an issue with `es` and `pt` fields for the YouTube Regrets page. When publishing stories for these two locales (even just copying the English ones as in the GIF below), I get a Bad Request error. I managed to successfully publish stories in fr/de

STRs:
- Edit page, show ES fields
- Copy stories from EN
- Publish
![bad-request](https://user-images.githubusercontent.com/1294206/67109337-3404e500-f1c8-11e9-8c66-63456b35bf76.gif)

@cadecairos Are the logs showing anything?

**Comment by TheoChevalier** [comment]
I’ve been able to reproduce locally, it looks like there’s a limit of the number of fields that can be uploaded, and we’re hitting it when publishing a 3rd version of the page

![image](https://user-images.githubusercontent.com/1294206/67204284-18d2e900-f405-11e9-99ea-3ef78ba22b34.png)

**Comment by TheoChevalier** [comment]
Default value is 1000 fields, I guess we would need this to be at least 2500 or 3000
https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-DATA_UPLOAD_MAX_NUMBER_FIELDS

**Comment by Pomax** [comment]
But how we are even getting to 1000+ for a single post? 6 languages for 30 stories, 10 blurps, and <10 additional fields is ~350 fields, even if we fill in every single one?

**Comment by Pomax** [comment]
Filed #3813 as a follow up once we land the PR associated with this issue.
