### ISSUE TITLE
PNI: implement recommend product for review

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3799]
Implement section for users to recommend a product for review.

**🗒  Design -> Dev Handoff Checklist**

- [x] Design has been finalized
- [x] Link to original design ticket: #3617
- [x] Link to Redpen: https://redpen.io/p/ur962f62818f0c1ffb
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included

## List of Requirements
- [x] Add "Recommend product" section to bottom of Homepage after all products and before donate section
    - [x] Copy of this section should read:  "(h3)Don't see the product you're looking for? (body-normal)Let us know what product you would like reviewed in the guide."
     - [x] Button copy is "Submit a product"
- [x] Add "Recommend product" content to About page after Jen and Kevin's emails
    - [x] Copy for this section should read: "We don’t want to miss any products that might be important to you. Tell us what connected products you want reviewed in our holiday buyer’s guide and we’ll do our best to include them." 
      - [x] Button copy is "Submit a product"
- [x] Link both buttons to this google form: https://forms.gle/UefDgjEU85Xwcf8C8

### Homepage:
<img width="229" alt="Screen Shot 2019-10-18 at 2 59 40 PM" src="https://user-images.githubusercontent.com/20977376/67120758-eda78a00-f1b7-11e9-98ad-0ce486bc6f3c.png">

![Home - recommend@2x](https://user-images.githubusercontent.com/20977376/67120819-14fe5700-f1b8-11e9-9bc3-f47a4cabf767.png)

### About page:
<img width="235" alt="Screen Shot 2019-10-18 at 2 59 19 PM" src="https://user-images.githubusercontent.com/20977376/67120770-f6985b80-f1b7-11e9-9dbf-1e78d593bfd3.png">

![about@2x](https://user-images.githubusercontent.com/20977376/67120662-bcc75500-f1b7-11e9-89d7-068f6ef79a30.jpg)

**Comment by kristinashu** [comment]
Nice, thank you for adding all the info @beccaklam!

**Comment by kristinashu** [comment]
Please note this is low priority.

**Comment by youriwims** [comment]
@kristinashu for this new section on the home page, the header is h2 at mobile in abstract and h3 at desktop...just want to clarify if you want h3 for sure?

**Comment by kristinashu** [comment]
Thanks for checking Youri! Please use h3 of desktop and mobile. Only override should be that it's center aligned instead of left aligned. Heavier weight is ok.
