### ISSUE TITLE
PNI: Implement About Page additions 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3800]
Design ticket https://github.com/mozilla/foundation.mozilla.org/issues/3619

## List of Requirements
- Update and add new about pages
- Keep fonts, layout, and general styling the same as our current about pages
- remove accordions (mainly for _How to Use this Guide_)

## Copy

- [x] [How to Use This Guide](https://docs.google.com/document/d/12QuPQ_RXkmLlAlhCcPTX50-Nup2JskAIwC5ntcn8R4Q/edit)
- [x] [Why We Made This Guide](https://docs.google.com/document/d/1rMo-TNMcHkgYOs2JSP8UxpW6AHdrx3N2odbL-uRP1Xs/edit)
- [x] [Minimum Security Guidelines Explained](https://docs.google.com/document/d/1Y49QM9Yb-BWI7IhtwQUdXMWS6CQoIy8WN6j8Ox_rZSE/edit#)
- [x] [About our Methodology](https://docs.google.com/document/d/1oaPPgFRlA1_zfpd5tPPe8THC20iFnmSYBvSvFppkmjA/edit)
- [x] [Press](https://docs.google.com/document/d/153YTZ2edXYxMUtFAXyX34d7-WlKCW4xC9mYQd7i36JA/edit#heading=h.2ws9vo67f5s)

**Comment by kristinashu** [comment]
Might not have final copy until Thursday Nov 7 so might not get this done for launch.

**Comment by kristinashu** [comment]
@Pomax @youriwims Jen is swapped but is trying really hard to finalize the copy for tomorrow morning. If she gets it done by noon do you think this can get done for a prod push on Tuesday Nov 12? I see you estimated it as a 5 but is that still the case with these designs? There are no long any accordions, just copy. Lots and lots of copy.

**Comment by youriwims** [comment]
I can take some time to do this tomorrow once Jen has the copy. Since it's just copy, this is more so a 2-3...I'm just going to put 3 since I skimmed the comps lol

**Comment by kristinashu** [comment]
Note: we won't be using the accordions anymore. We think people who like to read this type of content would prefer to see everything all at once.

**Comment by caltrider** [comment]
Sorry @beccaklam, I haven't had a chance to think on that. We can put a link in anywhere you see fit.

**Comment by beccaklam** [comment]
@kristinashu @youriwims  Can we do this in the cms or is this something a dev has to do?

**Comment by kristinashu** [comment]
It's something devs need to do. I think we should do it as a follow up ticket once Jen has time to write something. We shouldn't block the rest of the about page updates since it's blocking launch, which is about to happen!

**Comment by beccaklam** [comment]
> It's something devs need to do. I think we should do it as a follow up ticket once Jen has time to write something. We shouldn't block the rest of the about page updates since it's blocking launch, which is about to happen!

@kristinashu Yup agreed. @youriwims reached out and we just decided to insert a link at the beginning of the "Why we made this guide" the first instance where Mozilla shows up. It's not much but something for now!
