### ISSUE TITLE
Investigate TooManyFieldsSent error for youtube campaign page.

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#3813]
In order to fix https://github.com/mozilla/foundation.mozilla.org/issues/3798 "for now" we upped the Django field limit, without being absolutely certain that's actually the real problem we were facing.

We should revert that limit-change, and figure out why Django claims we're posting 1001+ fields when the document in question only has ~350 fields even when every single localised field has been assigned content.

**Comment by Pomax** [comment]
Punting on this until I figure out a reliable way to get the staging data loaded locally. I ended up updating the docker definition so that postgres matches the v10.11 that is used on heroku, then checked  `docker container ls` to see which container corresponds to the postgres database container, then for that container ran:
```
> docker exec [containerid] pg_dump postrgres://user@pass:heroku.staging.db/url -F tar -f foundation.psql.tgz`
> docker exec [containerid] dropdb postgres
> docker exec [containerid] createdb postgres
> docker exec [containerid] createuser -U postgres -s <db user name used in the dumped database>
> docker exec [containerid] pg_restore --dbname=postgres --username=postgres foundation.psql.tgz
```
but this doesn't seem quite enough to make the magic happen.

@cadecairos any idea what might still be missing?

**Comment by Pomax** [comment]
https://mozilla.slack.com/archives/C4M19QU2Z/p1574790883002100 has information on how to make this work

**Comment by cadecairos** [comment]
Unless this becomes a serious issue we'll sit on it.

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
