### ISSUE TITLE
Refactor join-us components to use direct basket HTTP request

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#3814]
Inspired by [this comment](https://github.com/mozilla/foundation.mozilla.org/pull/3803#pullrequestreview-304868791), our overloading of the signup endpoint is getting...gross. Let's refactor any signups that aren't actually tied to a signup snippet so that they're POSTing directly to Basket via HTTP. Some signups that come to mind: site header, footer, PNI post-vote, and, I think, somewhere on the MozFest site.

**Comment by Pomax** [comment]
This issue feels like a two-stager: this issue to audit the code and create a list of places where we need to make changes, and then one issue for each place where we can make those changes, so that they can be knocked out one by one rather than in one possibly hard to test PR.

**Comment by Pomax** [comment]
estimating as 3 specifically for the auditing part.

**Comment by alanmoo** [comment]
This will also enable us to leverage Sentry for Basket calls (as failed Basket messages in the SQS fall into the abyss currently)

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
