### ISSUE TITLE
PNI mailto: issue

### ISSUE THREAD

**Issue by natalieworth** [mozilla/foundation.mozilla.org#3816]
**Describe the bug**
On the PNI site, some of the links on the product pages under "How to contact the company: Email section" direct to a mailto: when it should just lead to the company website with their contact information. e.g. The [Nintendo Switch page](https://foundation.mozilla.org/en/privacynotincluded/products/nintendo-switch/). 

**To Reproduce**
1. Go to https://foundation.mozilla.org/en/privacynotincluded/products/nintendo-switch/
2. Scroll to "How to contact the company"
3. Under the Email Section, click the link

**Expected behavior**
A mailto: can happen if we have the company email directly listed on our site, but if it is a site link that directs to a product's company about page, we need it to change to direct to the new site in a new tab.

**Screenshots**
<img width="792" alt="Screen Shot 2019-10-26 at 11 29 01 AM" src="https://user-images.githubusercontent.com/14876567/67618218-70e26480-f7e4-11e9-9062-1853a5cd0ce0.png">

<img width="341" alt="Screen Shot 2019-10-26 at 11 29 09 AM" src="https://user-images.githubusercontent.com/14876567/67618219-76d84580-f7e4-11e9-90d8-b2d402c0a0e7.png">

**Comment by kristinashu** [comment]
Jen can manually add "mailto:" via the CMS for cases were we do have an email address. So for devs, please remove the automatic "mailto:" from the email field.

**Comment by youriwims** [comment]
@kristinashu as an alternative, I've added an email verification check below the email text field. If this box is checked, it will automatically add the `mailto:` to the link without altering the on-screen text :)

![Screen Shot 2019-11-05 at 11 13 59 AM](https://user-images.githubusercontent.com/36484608/68224890-79dded80-ffbd-11e9-8e91-6f8020cb335b.png)

**Comment by kristinashu** [comment]
ah very cool!

**Comment by natalieworth** [comment]
@youriwims @kristinashu So do we have to go back in and fix each mail to? I still get the mail client pop up for the [Switch] even though it's a link.(https://foundation.mozilla.org/en/privacynotincluded/products/nintendo-switch/).

**Comment by youriwims** [comment]
The changes aren't on prod yet, just in the pr that I requested your review on #3845 😜 But, yes, _unfortunately_. The default link is set to 'no email'/no `mailto:`, so once the pr lands, you just have to update the products with actual emails and check the _Email Verification_ box.

**Comment by kristinashu** [comment]
It's good the default is _no email_ since most of them products have a url instead of an actually email address. And Jen is mentally prepared to go through and update these once it is on prod.
