### ISSUE TITLE
Blog category updates aren't reflected in Wagtail component

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3822]
Changes when adding or editing a blog category do not get updated in the Wagtail component list of categories:

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/1068783/67791370-350eff80-fa6f-11e9-9dcd-e00fab441c13.png">

Can Wagtail component list automatically update or should adding/editing a category not be possible in the CMS?

cc @Pomax @youriwims

**Comment by youriwims** [comment]
Sorry, I don't think I understand. @kristinashu can you give more details, pls?...or an example of what you're trying to do here so I can better understand?

**Comment by kristinashu** [comment]
I don't seem to have permissions anymore but I used to be able to add a new blog category in Wagtail. This worked well and would create a new page. For example if I wanted to add a Category `Internet Health Report` then it would create a blog landing page at https://foundation.mozilla.org/blog/category/internet-health-report. The issue is that if I then want to use the `Recent Blog Entries` component, I don't see `Internet Health Report` as an option to filter by.

Can we either?
- give be back permission to add a new Category and update the `Recent Blog Entries` component so new categories show up as a filter option or,
- decided that new categories need to be added manually in which case I am requesting we update `Internet Health` to `Internet Health Report` for both the blog landing page and the `Recent Blog Entries` component 

Does that make sense?

**Comment by youriwims** [comment]
Ah, yes that makes complete sense. As far as I know, the categories are hard coded. So, for now, _I could_ update `Internet Health` to `Internet Health Report`, but if you were previously able to add new categories before, seems like that would probably be a better long-term solution.

Where in the cms were you able to add new categories previously?

**Comment by kristinashu** [comment]
Oh nvm, I can still update the categories (it was hidden in Snippets):
<img width="565" alt="image" src="https://user-images.githubusercontent.com/1068783/68152535-b693e100-fef8-11e9-914a-a4842be95642.png">

So would it be possible for the `Recent Blog Entries` component to reflect changes made to the categories?

**Comment by youriwims** [comment]
I think it may be possible, but let me double check with Pomax on implementation first.

@Pomax what would be the best way to pull dynamic data from the `BlogPageCategory` model to populate the `RecentBlogEntries`(RBE) streamfield dropdown? Currently, the  categories in RBE are hardcoded; however, it looks like there's a way to do this (..._If we haven't done this elsewhere yet_) 👉  [see link](https://stackoverflow.com/questions/38722155/wagtail-how-do-i-populate-the-choices-in-a-choiceblock-from-a-different-model?rq=1).

**Comment by youriwims** [comment]
@kristinashu, it looks like we're going to have to do the automatic updates as a follow-up [follow-up ticket will go here]. For now, I can go ahead and update `Internet Health` to `Internet Health Report` manually.  A few questions though:

1. Are there any other categories that you want to either add or update right now?
2. If not, is renaming `Internet Health` to `Internet Health Report` the only deliverable of this ticket?
> decided that new categories need to be added manually in which case I am requesting we update Internet Health to Internet Health Report for both the blog landing page and the Recent Blog Entries component
3. Do you mean updating `Internet Health` to `Internet Health Report` as the category on the blog cards on the blog landing page?...just want to clarify since that's the only place that I see it.
4. Should these instances be updated to `internet-health-report` and `Internet Health Report Blog` as well?
![Screen Shot 2019-11-05 at 2 04 11 PM](https://user-images.githubusercontent.com/36484608/68237554-532bb100-ffd5-11e9-9eb8-90d17116f0e4.png)

**Comment by kristinashu** [comment]
> Are there any other categories that you want to either add or update right now?

Nothing else right now.

> If not, is renaming Internet Health to Internet Health Report the only deliverable of this ticket?

Yes.

> decided that new categories need to be added manually in which case I am requesting we update Internet Health to Internet Health Report for both the blog landing page and the Recent Blog Entries component
> Do you mean updating Internet Health to Internet Health Report as the category on the blog cards on the blog landing page?...just want to clarify since that's the only place that I see it.

Yes and, just to make sure, updating it in the Recent Posts component. Example https://foundation.mozilla.org/en/internet-health-report/blog/

>  Should these instances be updated to internet-health-report and Internet Health Report Blog as well?

Yes please!
