### ISSUE TITLE
User Testing Findings from MozFest

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#3824]
This is a placeholder ticket for summarizing findings from user testing done at MozFest for both the Buyer's Guide and the Foundation site.

**Comment by taisdesouzalessa** [comment]
Progress done so far:

1. Completed the [Rainbow Spreadsheet ](https://docs.google.com/spreadsheets/d/1QAUZ4KHlygLbz4oLGt1zXoFtyPPEHfdXkfrE3ISwyq8/edit?usp=sharing)for both PNI and Foundation site. Didn't add if positive/negative or neutral (not sure it is necessary) or the possible solution (I would like to team up with Becca so we can explore it together).

2. Started a [document with our Conclusions/Learnings](https://docs.google.com/document/d/1-1AOVPNCB6hSLy8vpDNYj-8tBgRrRJrPMylI4RKqMws/edit?usp=sharing). After we have that full report, we can choose the ones we think are the most important.

IMPORTANT: In progress - project not finalized yet.

**Comment by taisdesouzalessa** [comment]
@beccaklam [here is the report](https://docs.google.com/document/d/1-1AOVPNCB6hSLy8vpDNYj-8tBgRrRJrPMylI4RKqMws/edit?usp=sharing) with learnings from our research. 
Could you take a look at that when you have some time and add your comments? 

Next: we meet to discuss findings and create a list with possible solutions for the problems we think are important to tackle.

**Comment by beccaklam** [comment]
Looks good @taisdesouzalessa ! I added some comments. We can discuss more today during our UX meeting and then we can talk about scope at the Design goals & projects meeting?

**Comment by beccaklam** [comment]
Tickets have been created so closing this ticket! 
Product Page #3904
Homepage #3902
