### ISSUE TITLE
Redirect and archive internethealthreport.org

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3827]
@cadecairos (yes! I got the right one!) @patjouk the IHR team is moving away from https://internethealthreport.org/ to use https://foundation.mozilla.org/en/internet-health-report and https://foundation.mozilla.org/blog/category/internet-health-report _(coming soon)_ instead. 

They plan to move all the content over next week. Once that is done will you be able to redirect the https://internethealthreport.org to https://foundation.mozilla.org/en/internet-health-report by Nov 12? And then I guess eventually archive it?

cc @alanmoo @kaodro

**Comment by cadecairos** [comment]
That's a lot of content and design work to move. What are they doing with the interactive content that goes with the articles and depends on tooling built for WordPress ?

**Comment by kristinashu** [comment]
Are you talking about the reports (example: https://internethealthreport.org/2019/)? Those are staying as is. We're only talking about moving parent site https://internethealthreport.org/

**Comment by cadecairos** [comment]
Well, I'm glad I asked in that case! That makes much more sense.

**Comment by kaodro** [comment]
@cadecairos What happens to links like https://internethealthreport.org/2019/ once you archive the https://internethealthreport.org/? Will they work or do we need sth new?

**Comment by kristinashu** [comment]
Does this sound right to everyone?

All these urls (and their localized equivalents) will redirect to https://foundation.mozilla.org/en/internet-health-report
- https://internethealthreport.org/
- https://internethealthreport.org/blog/
- https://internethealthreport.org/about/
- https://internethealthreport.org/press/

But these will stay the same:
- https://internethealthreport.org/2019/ 
- https://internethealthreport.org/2018/ 

Am I missing any hidden pages?

**Comment by kaodro** [comment]
https://internethealthreport.org/v01/

**Comment by cadecairos** [comment]
@kaodro as @kristinashu said, we plan to only redirect the pages associated with that landing page sub-site on our multi-site Wordpress installation. The other sites (2019, 2018, v01) will remain where they are.

**Comment by kristinashu** [comment]
@kaodro still has a few more blog posts to port over so please hold off on the re-direct until she says she's all done, hopefully just one more day! 

FYI, the site is live https://foundation.mozilla.org/en/internet-health-report/ and most of the blog posts are here https://foundation.mozilla.org/en/blog/category/internet-health-report/.

**Comment by kristinashu** [comment]
@kaodro Tais has noticed some of the press links on the [press page](https://foundation.mozilla.org/en/internet-health-report/press/) aren't working. Could you please check them?

<img width="809" alt="image" src="https://user-images.githubusercontent.com/1068783/68724400-357bc000-0570-11ea-8094-dfd85e831222.png">

**Comment by kaodro** [comment]
Thanks! I fixed the links and I'll ask Kevin if he wants to use another video (one that is available for all)

**Comment by kristinashu** [comment]
Sounds like everything has been moved over https://github.com/mozilla/foundation.mozilla.org/issues/3801#issuecomment-554076218 so this is now ready!

**Comment by cadecairos** [comment]
@kristinashu @kaodro I've set up redirects on WP Engine. Redirects are handled using regular expression rules, so doing a redirect for each blog post, and it's localized variants is not going to be possible.

As of right now 
`https://internethealthreport.org` and its localized versions redirects to the new homepage on the CMS,  `/press/` and its localized versions redirect to the coresponding press page on the CMS, and `/about/` and it's localized pages redirects to the new homepage on the CMS.

All other urls on the domain that **are not** prefixed with: `/v01/`, `/2018/`, `/2019`, `/wp-content/`, and `/wp-admin/` and `/wp-login.php` are redirected to the new homepage on the CMS.

I archived the old homepage on the multisite WP install, and promoted the 2019 site to be the "primary". Please have a look at things to ensure things are all in working order.

**Comment by kristinashu** [comment]
Thank you Cade! Seems to be working well for me!
