### ISSUE TITLE
Product page changes before Nov 12 Launch

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#3828]
Placeholder ticket for tracking the changes that need to be made before the Buyer's Guide's Nov 12 launch.

**Comment by beccaklam** [comment]
Redpen for Product Page comp based on the decisions made at the PNI meeting today: https://redpen.io/p/aj7f2e09f704b2e4ee

To summarize:
1) We are going to expand the Minimum Security Standards section at all times instead of hiding it in an accordion
2) We need to link to an explanation of what the Minimum Security Standards are, or write a short explanation
3) We also decided to add back in the section "Links to privacy information" and add some help text to the "User friendly privacy info" section.

**Comment by kristinashu** [comment]
I've separated this into two implementation tickets:
- Product detail page: style updates Minimum Security Standards #3831
- Product detail page: style updates to Privacy Policy links #3832

@beccaklam when you're back on Monday, please review them and then close this ticket.

**Comment by beccaklam** [comment]
Both tickets look great, thanks @kristinashu ! 👍
