### ISSUE TITLE
Leadership Page - hierarchy fix

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#3830]
### **Issue:**
During user testing at MozFest one user pointed out that was odd that our Former Board Members were more prominent than the current ones. This observation brought the design team to analyze that page and we noticed that the pictures of former board members were larger than the others.

<img width="808" alt="image" src="https://user-images.githubusercontent.com/22157921/67965521-6991d100-fbbf-11e9-888b-8b379a05a50a.png">

### **Fix:**
In order to do a quick fix, I uploaded a transparent gif as a 4th image so the grid of this section is the same as the others, resulting on a uniform looking page and eliminating the issue.

**Comment by taisdesouzalessa** [comment]
### 
QA - changes done on staging: 

DESKTOP

<img width="805" alt="image" src="https://user-images.githubusercontent.com/22157921/67965653-b4134d80-fbbf-11e9-94a6-fd38fb821833.png">
 
MOBILE
Landscape

<img width="400" alt="image" src="https://user-images.githubusercontent.com/22157921/67965861-0f454000-fbc0-11e9-9be9-23127be2bc9a.png">

Portrait

<img width="200" alt="image" src="https://user-images.githubusercontent.com/22157921/67965883-19673e80-fbc0-11e9-80ae-7befdb8a2153.png">

@kristinashu could you please double check the QA and if it is all good, I will push the changes to the live site!

**Comment by kristinashu** [comment]
R+

**Comment by taisdesouzalessa** [comment]
Changes pushed to live page: https://foundation.mozilla.org/en/about/leadership/
