### ISSUE TITLE
Add customization to IHR hub

### ISSUE THREAD

**Issue by kaodro** [mozilla/foundation.mozilla.org#3835]
@kristinashu 
I moved content from https://internethealthreport.org/ to https://foundation.mozilla.org/de/internet-health-report/. The copy will be reviewed or/and added by Solana Tues/Wed (Nov 5, 6) but most of it is already there. 

Can we add:

1) A sign-up box or link that jumps to a sign up for IHR updates mailinglist to the About/Overview page? I'm asking specifically for the sign up that goes to an IHR bucket in salesforce, not the general one for MoFo. For now I added a button but no correct link yet.

2) Can we add a nice timeline for the roadmap on the About/Overview page? For now I just added some milestones and dates. Worst case I can leave it as it is or I can add airtable but it seems like a bit of an overkill.

3) I have some problems with formatting and spacing. Is there a way to view the html/source code page somewhere in wagtail? Also, I trust you will make it look awesome in your final review so I'm not too worried.

Thank you!

**Comment by kristinashu** [comment]
Awesome @kaodro! I like the banner graphic! 

> A sign-up box or link that jumps to a sign up for IHR updates mailinglist to the About/Overview page? I'm asking specifically for the sign up that goes to an IHR bucket in salesforce, not the general one for MoFo. For now I added a button but no correct link yet.

I think we can do something like this https://foundation.mozilla.org/en/initiatives/open-leadership-events/. @stephaniemcv is this correct? Can I add an IHR signup snippet to our site?

> Can we add a nice timeline for the roadmap on the About/Overview page? For now I just added some milestones and dates. Worst case I can leave it as it is or I can add airtable but it seems like a bit of an overkill.

> I have some problems with formatting and spacing. Is there a way to view the html/source code page somewhere in wagtail?

I will do a design pass of the site later this week and see if there are little ways to improve the layout.

**Comment by kaodro** [comment]
Great, thank you!
Question about the language versions: When I change langauge to German (or sometime it changes cause of my location?) it shows me an older version of the English copy. What's the process here?

**Comment by kristinashu** [comment]
You can add localized text in the cms, just click through the languages on top right side.
 
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/1068783/68147519-12596c80-feef-11e9-93c3-40661360475d.png">

But yes, I think there is a bug with it but as long as you check all the pages in the cms then it should be fine.

**Comment by kristinashu** [comment]
@kaodro thanks to the super awesome Steph, the newsletter signup has been added to the site https://foundation.mozilla.org/en/internet-health-report/. This signup functions the same as on https://internethealthreport.org/.

**Comment by kaodro** [comment]
Wonderful, thank you!
