### ISSUE TITLE
Update color of Horizontal line in paragraph component

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3843]
The Paragraph Wagtail component has a `Horizontal line` divider. Currently it appears as light grey on the site but it should be black to match our style guide and the rest of the diving lines on the site.

- [ ] Update color of Horizontal line from grey to black

Screen cap of cms:
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/1068783/68160857-80129200-ff09-11e9-8624-c9cd8ea82a01.png">

Screen cap of prod: (line should be black instead of grey)
<img width="772" alt="image" src="https://user-images.githubusercontent.com/1068783/68160782-5e190f80-ff09-11e9-97ac-cdb483ba2c51.png">

**Comment by Pomax** [comment]
Does the `<hr>` have the right color on the page? Because the style in the CMS admin view and the style on the actual pages are not linked, so changing the color in the admin view will not affect what the line would look like on the actual live site.

**Comment by kristinashu** [comment]
Oh yes, we use it a lot on the blog pages like https://foundation.mozilla.org/en/blog/how-smart-homes-could-be-wiser/

**Comment by kristinashu** [comment]
And I've just tested it on a regular initiatives page https://foundation.mofostaging.net/en/initiatives/stronger-nyc-communities/ where it's also grey and should be black.

<img width="904" alt="image" src="https://user-images.githubusercontent.com/1068783/68321507-af92dd00-0076-11ea-9df1-abc869a485c2.png">

**Comment by kristinashu** [comment]
@youriwims maybe hold off on this? It's a lower priority and totally ok if it doesn't get done this sprint.

**Comment by youriwims** [comment]
sure, np.

**Comment by mmmavis** [comment]
@kristinashu I see on https://foundation.mozilla.org/en/ we have both styles of horizontal line - black and gray. Is the plan to also update all of them to black?

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/2896608/74575330-71416f80-4f3b-11ea-914b-e70430a3eef8.png">

**Comment by kristinashu** [comment]
I believe those grey lines will remain grey because there are multiple of them??? @sabrinang do you remember the rules around this?

**Comment by mmmavis** [comment]
Currently, we have both style defined as

- `hr-emphasis`: 4px thickness, black
- `hr`: 1px thickness, $gray-20 (#cccccc)

**Comment by mmmavis** [comment]
ping @sabrinang 😃

**Comment by kristinashu** [comment]
I found the line design ticket with all the rules https://github.com/MozillaFoundation/Design/issues/314#issuecomment-491999581. But yes, still curious about what Sabs thinks.

**Comment by kristinashu** [comment]
This might just be my preference because I prefer it to be consistent with the dividing lines on the component CTAs but I don't think it's breaking any rules so I'll just close this ticket!
