### ISSUE TITLE
Bold doesn't work for italics in Paragraph component

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3847]
When `Bold` is used in addition to `italics` the text looks italic but not bold. It should be both bold and italic if both are selected.

Screen cap of selections in cms:

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/1068783/68235874-e4405f00-ffb8-11e9-96f6-9b345c050125.png">

But doesn't look bold on prod:

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/1068783/68235891-f02c2100-ffb8-11e9-99b6-55715f766aad.png">

**Comment by Pomax** [comment]
It looks like this was a bug that got fixed in a wagtail update:

![image](https://user-images.githubusercontent.com/177243/69179379-4a9ca580-0ac0-11ea-81ac-df06b67a8402.png)

![image](https://user-images.githubusercontent.com/177243/69179393-4ec8c300-0ac0-11ea-9736-9c764af07f5b.png)

**Comment by kristinashu** [comment]
Sweet! I don't see it effective yet, do you know when we will have the latest Wagtail version?

I'll close this ticket tho.

**Comment by kristinashu** [comment]
Or maybe it is working... I think our bold is just quite subtle on my computer.
