### ISSUE TITLE
Discussion: Header/body newsletter list conflicts

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#3848]
I had a call with Steph W. today and she highlighted a challenge with the current newsletter signup implementation. When a program is trying to get users to sign up for a newsletter by going to a page on the Foundation site, the header/footer CTAs sign visitors up for the main `mozilla-foundation` list, while they're trying to get visitors on a specific list indicated by the body content. This means some people might sign up for the main newsletter, thinking they're getting (in this case) OLE news too.

What can we do to address this? Have an option to (or automatically) hide the header button when there's a signup CTA on the page body? Change the header button to allow customization on a per-page basis? Something else?

@kristinashu any thoughts?

**Comment by kristinashu** [comment]
@taisdesouzalessa will take a look at this and come up with a few options for us to discuss.

**Comment by kristinashu** [comment]
Adding [this doc](https://docs.google.com/document/d/1lj2V7YKWR4zzhFCAdUKP2wPQ1EA9MBiiH49PnLf23CM/edit) since it also explains the issue.

**Comment by taisdesouzalessa** [comment]
@kristinashu and @alanmoo I prepared a doc with 4 options here. I added some of your suggestions there too, Alan:

https://docs.google.com/presentation/d/1VnhbLJ6gFYiF9E-6qe4ToUXDcmR1XCS7Kzvj8TCH1pY/edit?usp=sharing

Please take a look and let me know if it makes sense to you. We can always schedule a meeting if needed.

**Comment by kristinashu** [comment]
This is great! I think we should have a quick chat about it, could even just be 15min after stand one day next week? It would be good to hear your thoughts and then Alan can share his thoughts on expected dev effort.

**Comment by taisdesouzalessa** [comment]
Sure, I'll book a quick conversation with you both so we have it in our calendars.

**Comment by taisdesouzalessa** [comment]
This task is now done. 
Discussion and solution reached. Epic for the task is here: #3924
