### ISSUE TITLE
[Component] Ensure Recent Blog Entries category list automatically updates when adding/editing a category in CMS

### ISSUE THREAD

**Issue by youriwims** [mozilla/foundation.mozilla.org#3851]
We want Recent Blog Entries component's to be dynamically updated by the category object. 

**Issue**: In it's current state, this would create a circular dependency since `models.py` loads `customblocks`> `recent_blog_entries.py` _and_ `customblocks`> `recent_blog_entries.py` would need to load `models.py`. The component and possibly the category object and/or more will need a rewrite to implement this.

Related Issues/PRs: In #3822, [we opted to manually update the component in addition to updating the category in the cms](https://github.com/mozilla/foundation.mozilla.org/issues/3822#issuecomment-549971786).

cc: @Pomax @kristinashu

**Comment by alanmoo** [comment]
To close this issue, we should have an approach in mind and open another issue with the details for that implementation

**Comment by Pomax** [comment]
Blocking on https://stackoverflow.com/questions/60976914/using-a-wagtail-choiceblock-with-dynamic-choices-rather-than-a-hardcoded-list for now - I thought I had a solution here, but the whole "structs get fully unrolled as hardcoded JSON" that happens during migrations is kind of ruining the "we can finally fix this" party.

**Comment by kristinashu** [comment]
Ok, thank you for looking into it!

**Comment by Pomax** [comment]
There's a good answer in the SO post, so this is no longer blocked.
