### ISSUE TITLE
Blog category link on a post page is broken

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3865]
Categories work well on [/blog](https://foundation.mozilla.org/blog/) page but break on [a post detail page](https://foundation.mozilla.org/en/blog/lanet-umoja-using-schools-internet-hub/).

For example, `Fellowships & Awards` goes to https://foundation.mozilla.org/en/opportunity/mozilla-open-leaders/blog/category/fellowships-awards/ when it should go to https://foundation.mozilla.org/en/blog/category/fellowships-awards/.

<img width="1287" alt="image" src="https://user-images.githubusercontent.com/1068783/68419080-6a41de80-014e-11ea-8b0c-64736868bafc.png">

cc @Pomax @youriwims

**Comment by kristinashu** [comment]
Wounder if it's because of this? I'm going to delete the page and see.

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/1068783/68419456-1d123c80-014f-11ea-9be6-e5bb14180805.png">

**Comment by kristinashu** [comment]
Ok deleting that worked 🤷 but still please investigate on how to avoid this in the future!

**Comment by Pomax** [comment]
We're relying on the wagtail `slugurl` template tag to form the link, using:
```html
        {% if category %}
          | <a class="category" href="{% slugurl 'blog' %}category/{{category.slug}}">{{ category }}</a>
        {% endif %}
```
so it feels like the `slugurl` template tag was preferring that deeply nested `blog` page over the _real_ one that lives at the root of the site.

**Comment by acabunoc** [comment]
Added the page back but called it "Open Leaders Blog". Seems to be fine!

**Comment by kristinashu** [comment]
@TheoChevalier has noticed another instance of this...

1. Go to https://foundation.mozilla.org/fr/internet-health-report/
2. Click on 'Blog' in the subnav
3. Result: https://foundation.mozilla.org/fr/internet-health-report/blog/ with a 500 error

**Expected behavior:** Clicking on 'Blog' on the FR page should go to https://foundation.mozilla.org/fr/blog/category/internet-health-report/

**Comment by kristinashu** [comment]
The plot thickens... I've deleted the Blog tab from the sub nav on https://foundation.mozilla.org/en/internet-health-report/ because clicking on it started to show 500 error (only started today, it was fine before).

I think i might be related to the Blog component. I made a page called 'updates' and it was fine until I added the blog component. 

IHR blog has been taken down but you can see the error on staging for now https://foundation.mofostaging.net/en/internet-health-report/
