### ISSUE TITLE
Access to moderate comments on blog page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3873]
Now that we have the option to add comments to a blog post, more people will need access to moderate them.

@cadecairos any hesitation in added several people? Right now this is the list but more teams will want access as they start to use it. If there's any hesitation then please only add Kasia to represent the IHR team and then Jen and Kevin definitely need to be added.

List of people who will _ideally_ have access:
- IHR team: Kasia Odrozek, Solana Larsen, Jairus Khan, and Stefan Baack
- Jen Caltrider
- Kevin Zawacki
- me

**Comment by cadecairos** [comment]
Not a problem updating people to moderators. Just make sure each of them has created an account with their MoFo email address.

**Comment by kristinashu** [comment]
Ok cool, I'll let you know once everyone has logged in.

**Comment by kristinashu** [comment]
@cadecairos ok all the people mentioned above have confirmed that they have logged in!

**Comment by cadecairos** [comment]
@kristinashu I made everyone "Staff" except Kevin, there doesn't appear to be a user account for him.

**Comment by kristinashu** [comment]
Ok thank you, I've pinged Kevin to get him to double check. But IHR team are the more pressing ones so we're good for now!

**Comment by kristinashu** [comment]
Ok Kevin says he's done it for real now. Could you also please add Kristina Gorr while you're at it? She says she's signed in.

**Comment by cadecairos** [comment]
All done!
