### ISSUE TITLE
Update Theory of Change slides

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3875]
Make the ToC slide less overwhelming. Meet with Lainie to kick-off.

https://docs.google.com/presentation/d/1DtD48SqjJLez-TU2jImKPF-5nx3-0YSoU4fNqpjNT-k/edit?usp=sharing

**Comment by alanmoo** [comment]
Sabrina to confirm that this doesn't need anything else

**Comment by sabrinang** [comment]
Lainie will follow up with me next week as they will be talking about prep for the next board meeting then.

**Comment by sabrinang** [comment]
Lainie mentioned no design needs identified for board slides, closing.
