### ISSUE TITLE
Update IHR url on /initiatives subnav

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3889]
Update the 'Internet Health Report' link in the subnav from https://internethealthreport.org/ to https://foundation.mozilla.org/internet-health-report/

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/1068783/68786525-c85e3e00-05f4-11ea-85aa-14de1695893d.png">

**Comment by ragnarokatz** [comment]
@kristinashu Hello, I would like to work on this issue please.

**Comment by ragnarokatz** [comment]
there are two places in total that need to be updated to the latest url: one in initiatives_page.html, one in participate_page.html.

**Comment by kristinashu** [comment]
Hi @ragnarokatz, thank you for pointing out the additional link on [/participate](https://foundation.mozilla.org/en/participate/). That one is editable in the CMS so I have just updated it now. But if you can, please go ahead and update the one on [/initiatives](https://foundation.mozilla.org/en/initiatives/).  

cc @alanmoo
