### ISSUE TITLE
Copy updates to PNI

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3896]
(Old dev ticket for all links https://github.com/mozilla/foundation.mozilla.org/issues/3800)

Copy updates to PNI About pages.

### Add reference to *Privacy Included:

Copy updates are highlighted in yellow:

- [x] [How to Use This Guide](https://docs.google.com/document/d/12QuPQ_RXkmLlAlhCcPTX50-Nup2JskAIwC5ntcn8R4Q/edit): add a paragraph of copy to the bottom of the page

- [x] [Why We Made This Guide](https://docs.google.com/document/d/1rMo-TNMcHkgYOs2JSP8UxpW6AHdrx3N2odbL-uRP1Xs/edit): edit and add a new paragraph towards the bottom of the page

- [x] [Press](https://docs.google.com/document/d/153YTZ2edXYxMUtFAXyX34d7-WlKCW4xC9mYQd7i36JA/edit#heading=h.2ws9vo67f5s): add a sentence to the bottom of the page

### Add reference to Mozilla:

Copy updates are highlighted in blue:

- [x] Update first sentence and add context about Mozilla at the bottom of "Why We Made This Guide"

### Update order of nav items:

- [x] Switch the order of page so "Why we made this guide" is the first subnav item

**Comment by caltrider** [comment]
OK, here's the plan. 
Let's switch the order on the left hand side links and move "Why we made this guide" up to the top so it is the default page people land on when they click on the about page. Then move "How to use this guide" down one below "why we made this guide". I've written the copy about Mozilla in the "[why we made this guide" doc ](https://docs.google.com/document/d/1rMo-TNMcHkgYOs2JSP8UxpW6AHdrx3N2odbL-uRP1Xs/edit)and highlighted it in blue (there's one change at the top and then the blurb at the bottom).

**Comment by kristinashu** [comment]
Sorry @youriwims, but any chance you'd be able to do these updates?

**Comment by youriwims** [comment]
Sure 👍

**Comment by youriwims** [comment]
@kristinashu which subpage should _About the Guide_  in the nav go to?

**Comment by kristinashu** [comment]
Thank you Youri! You didn't have to do it right now, but I do appreciate it!
