### ISSUE TITLE
Remove Watch Video button from mozfest homepage

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/foundation.mozilla.org#3900]
Remove the button at the top of the site. Bonus: make it toggleable via the CMS so that we can easily add it back in later.

**Comment by ragnarokatz** [comment]
@gideonthomas Hello, I would like to work on this issue please.

**Comment by ragnarokatz** [comment]
I'm not sure if this is what you mean by making it toggleable via CMS:
in template file `partials/homepage_banner.html`:
```
      {% if page.banner_video_url %}
      <a class="btn btn-primary" href="{{ page.banner_video_url }}" target="_blank" id="mozfest-home-watch-video-button">Watch Video</a>
      {% endif %}
```

there's a toggle available here, that if page.banner_video_url is passed in, then the watch video button will show up.

It is being passed in `mozfest/models.py`:
```
    banner_video_url = models.URLField(
        max_length=2048,
        blank=True,
        help_text='The video to play when users click "watch video"'
    )

...

    content_panels = parent_panels[:n] + [
        FieldPanel('cta_button_label'),
        FieldPanel('cta_button_destination'),
        FieldPanel('banner_heading'),
        FieldPanel('banner_guide_text'),
        FieldPanel('banner_video_url'),
    ] + parent_panels[n:] + [
        FieldPanel('prefooter_text'),
    ]
```

Should I just remove the `FieldPanel('banner_video_url')` here?

**Comment by gideonthomas** [comment]
@Pomax are you ok with just commenting out that button in the template and adding a comment saying that we will probably add it back next year?

**Comment by ragnarokatz** [comment]
while we're waiting on a response, should I just create a PR with what you have recommended? as in "**just commenting out that button in the template and adding a comment saying that we will probably add it back next year**" @gideonthomas

**Comment by gideonthomas** [comment]
yes please! Thanks @ragnarokatz

**Comment by ragnarokatz** [comment]
@gideonthomas has been created and ready for review.

**Comment by Pomax** [comment]
@ragnarokatz's observation that we have a URL field that we can treat as toggle looks sound to be, I don't see a reason not to just immediately go for "if url is set, show, otherwise, don't".

**Comment by ragnarokatz** [comment]
@gideonthomas Since #3910 has been closed, I believe this ticket can be resolved as well.
