### ISSUE TITLE
PNI Homepage Improvements

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#3902]
Based on [user testing](https://docs.google.com/spreadsheets/d/1QAUZ4KHlygLbz4oLGt1zXoFtyPPEHfdXkfrE3ISwyq8/edit?usp=sharing) conducted at MozFest, @taisdesouzalessa  and I have distilled our [findings](https://docs.google.com/spreadsheets/d/1Si6MnJWz3PZFIKp_pchkATkv50xpNlB_s0VSjcb8ZD0/edit?usp=sharing) into the following issues on PNI's homepage that need attention:

### 1. Highlight and clarify what the "Minimum Security Standards" badge is
- [x] Add Minimum Security Standards explainer text somewhere on the homepage, not hidden in the filter
- [x] Take the Minimum Security Standards filter out of the filter

### 2. Simplify homepage list views 
[Related ticket](https://github.com/mozilla/foundation.mozilla.org/issues/3618)
- [x] If possible, simplify the homepage so a filter is not required. Questions to consider:
   - Does the page need the "Likely" and "Not Likely" to buy filter?
   - Does the page need the creep-o-meter filter?
   - Should the Minimum Security Standards be a filter, or should it always be present?

cc: @taisdesouzalessa @kristinashu

**Comment by beccaklam** [comment]
@taisdesouzalessa Here's a proposal for the homepage design, can I get a design review? It's not a perfect prototype. Please keep in mind that I'm imagining that the MSS checkbox would also be sticky and that the creep-o-meter face would still change as a user scrolls.

[Mobile](https://mozilla.invisionapp.com/share/X4V0LY93JEC#/395226208_-M-_Home_Test)
[Desktop](https://mozilla.invisionapp.com/share/3PV0LWU2E5S#/395240117_Home_Copy_5)

**Comment by beccaklam** [comment]
So, a lot of updates! 
Here's [the second draft of designs](https://docs.google.com/document/d/1x6cNJMMG32ZeMmLn2Y93ibCcYBDecvDqoGo0-e5iuIo/edit?usp=sharing) after getting feedback from the design team.
And here's [the feedback I got from Jen about the draft 2 designs](https://docs.google.com/document/d/1mwPebGK1IhPoEdlmmvNtL5eAJCzhYk1WPu8smSZBBig/edit?usp=sharing).

@taisdesouzalessa @kristinashu

**Comment by kristinashu** [comment]
This is looking awesome and I'm loving the simplified design! Let's see how the user tests go but unless anything crazy comes up, I will turn this into an implementation ticket for Mavis to work on next sprint. 

Assigning to myself. Rebecca, feel free to un-assign yourself.

**Comment by kristinashu** [comment]
Placeholder dev tickets (I need to add content to them):
- PNI home: remove filters #4020
- PNI home: update intro text #4021

**Comment by kristinashu** [comment]
Ok I've added all the context to the dev tickets! Closing...

**Comment by kristinashu** [comment]
Actually... @beccaklam Jen is ok with these changes, right?

**Comment by beccaklam** [comment]
@kristinashu Yeah, she was ok with the homepage changes. She also wanted to add more emphasis to the creep-o-meter face.

**Comment by kristinashu** [comment]
Ok, not noticing the face change came up in some informal user testing at the Vancouver office so I've moved this to a separate ticket for us to decide https://github.com/mozilla/foundation.mozilla.org/issues/4037
