### ISSUE TITLE
Internet Health Report link on /initiatives

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3907]
Follow up from https://github.com/mozilla/foundation.mozilla.org/issues/3889.

The link has been updated which is great but it since it's an internal page it no longer needs to open in a new tab. 

@ragnarokatz please update the ['Internet Health Report' link](https://foundation.mozilla.org/internet-health-report/) in the subnav on [/initiatives](https://foundation.mozilla.org/en/initiatives/) so that it opens in the same tab (similar to the Advocacy link).

cc @alanmoo

**Comment by ragnarokatz** [comment]
@kristinashu I will take a look at this later today when I get home.

**Comment by alanmoo** [comment]
Oops, I should have caught that. That's what I get for reviewing code late at night.

**Comment by ragnarokatz** [comment]
@kristinashu PR has been created to address this issue, it is ready for review.
@alanmoo

**Comment by kristinashu** [comment]
Excellent, thank you!
