### ISSUE TITLE
Change buttons and link leadng to IHR initiative 

### ISSUE THREAD

**Issue by kaodro** [mozilla/foundation.mozilla.org#3909]
@kristinashu 

On the initiative page can we change the buttons under Internet Health Report to:

Replace "Internet Health" with "Learn more" -> link to https://foundation.mozilla.org/en/internet-health-report/
Replace "Read the report" with "Read the 2019 report" -> link to https://internethealthreport.org/2019/

Thank you!

**Comment by kristinashu** [comment]
Thanks for pointing those out! I've updated them.
