### ISSUE TITLE
[Header/body newsletter list conflicts] Hide the “newsletter” top button in pages that have form in their body

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#3925]
### Issue:
If a page has a newsletter form in its body, we should hide the top form button (“newsletter”)so the audience is more focused on the body form, reducing the chances of confusion. 

### Screenshot:
<img width="637" alt="image" src="https://user-images.githubusercontent.com/22157921/69084785-d0a1e900-09f9-11ea-9190-25d69649cf97.png">

### Mockup:
https://mozilla.invisionapp.com/share/8TUW2XEGAF3#/393964297_Final-Proposal-Page

**Comment by mmmavis** [comment]
@alanmoo is this something can be worked on now?

**Comment by alanmoo** [comment]
Should be. Any questions about it?

**Comment by mmmavis** [comment]
Not really a question about the specs but more about what the best way is to have a future-proof way to identify the existence of a newsletter signup form in page "body".  The most straightforward solution I can think of is to wrap the `{% block content %}{% endblock %}` in some named `div` like 

```html
<div class="main-body">
{% block content %}{% endblock %}
</div>
```

And check to see if there's any `.join-us` element in the "body" to decide if we wanna hide the nav button or not.

(if we wanna use `<main>` as the wrapper then we might need to update two templates, bg_about.html and youtube_regrets_page.html, as currently they are using `<main>` already)

Thoughts? @Pomax @youriwims

**Comment by youriwims** [comment]
I think that your idea above for updating `base.html` is a great idea 👍 Tbh, I feel like we should leave `<main>` for use in the individual, specific templates since it can be different template to template.

**Comment by Pomax** [comment]
Yeah, that makes sense. It would allow us to query the document far easier.

**Comment by mmmavis** [comment]
@alanmoo how future-proof do we want the solution for this ticket to be? Asking because I'm deciding if I should have a Django level fix (i.e., render nav newsletter button only if the `page` doesn't have a `signup` snippet) OR a client-side JS "check-and-hide" solution.

**Comment by alanmoo** [comment]
I don't have a strong opinion, but the client-side seems easier to add in or pull out if needed, rather than the Django approach which seems to require a bit more surgery. But keep performance in mind and see if you can prevent the extra nodes from being added to the DOM at all, rather than letting them render then hide (assuming the header form is in the DOM, not just the button).
