### ISSUE TITLE
[Header/body newsletter list conflicts] Make copy more clear inside the form from body

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#3926]
### Issue:
Make copy more clear: user will be signing up for both Open Leadership AND Mozilla News

### Screenshot:
<img width="290" alt="image" src="https://user-images.githubusercontent.com/22157921/69085052-427a3280-09fa-11ea-9a20-58cb90908e3b.png">

### Mockup:
https://mozilla.invisionapp.com/share/8TUW2XEGAF3#/393964297_Final-Proposal-Page

@kristinashu @alanmoo @mmmavis do you think this should be manually updated by every team? Or should design team update it as we see it? Or should we have those fields filled in automatically as teams choose the email lists? 

### IMPORTANT: The copy I currently have in the mockup is just a placeholder.

**Comment by kristinashu** [comment]
@taisdesouzalessa do you see this in the CMS? You should be able to update these yourself byt going to Snippets and then Signup snippets. I think you should go ahead and update them.

<img width="471" alt="image" src="https://user-images.githubusercontent.com/1068783/69091379-03021500-09ff-11ea-8153-be8601c58718.png">

**Comment by taisdesouzalessa** [comment]
@kristinashu I feel the copy could be refined a bit but copy writing is not my strength (I quickly wrote that copy). Maybe I should connect with Jen to give me a hand?
"Join our **Open Leadership** and **Mozilla News** email lists and be the first to know about this project and Mozilla in general"

Also I don't have permission to access the area at the moment - @Pomax or @alanmoo could you give me permission in the CMS to edit the OLE snippet?

**Comment by taisdesouzalessa** [comment]
Blocked by: PTO.

**Comment by kristinashu** [comment]
Tais, Alan says you should have permissions now.

**Comment by taisdesouzalessa** [comment]
@caltrider have 3 options of copy for this section:

**Option #1**
It’s okay to get mad if you don’t like where the internet is going. Now do something about it. Join our Open Leadership and Mozilla News email lists to know what projects, events, and actions you can take to help make the internet better for all. 

**Option #2** 
Get two for the price of one! Join our Open Leadership email list to always know what’s going on with our programs and events. Join our Mozilla News list to stay up-to-date in the fight for a better internet for all. 

**Option #3**
Join our Open Leadership email list to always know what’s going on with our programs and events. Join our Mozilla News list to stay up-to-date in the fight for a better internet for all. 

Once decision is made (discussion happening on [this doc](https://docs.google.com/document/d/1BS493HcyIt34cTRYWGFVbzqZidpaUpCCToDI1XI2nNs/edit?usp=sharing)) we will edit the copy on the site.

**Comment by taisdesouzalessa** [comment]
Implementation ticket here: #4141

Closing this one.
