### ISSUE TITLE
[Header/body newsletter list conflicts] Make copy more clear in footer

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#3927]
### Issue:
Make copy more clear: user will be signing up for ONLY Mozilla News

### Screenshot:
<img width="634" alt="image" src="https://user-images.githubusercontent.com/22157921/69085740-fc719e80-09fa-11ea-986d-7f20b175ff0c.png">

### Mockup:
https://mozilla.invisionapp.com/share/8TUW2XEGAF3#/393964297_Final-Proposal-Page

**IMPORTANT:** @kristinashu @alanmoo copy is just a placeholder

**Comment by alanmoo** [comment]
Who's the decider on copy?

**Comment by kristinashu** [comment]
Let's keep this on `design` until we have final copy. Tais, could you work with Jen (and maybe cc Steph McV) to finalize the copy?

Do you also want to update the message users see after they've submitted their email? Like in https://github.com/mozilla/foundation.mozilla.org/issues/3928.

**Comment by taisdesouzalessa** [comment]
Blocked by: PTO.

**Comment by taisdesouzalessa** [comment]
Jen's comment:

> Tais, the suggested copy you have here works for me for this footer copy. I might change it a little to: “Join our Mozilla News email list to stay informed and take action.”
But it’s also fine as is. 

[Original doc here](https://docs.google.com/document/d/1BS493HcyIt34cTRYWGFVbzqZidpaUpCCToDI1XI2nNs/edit?usp=sharing)

I like Jen's suggestion. The sentence sounds better and follows a more logic path, in my opinion: people get informed and take action after that. 

**Are you okay with this new copy @kristinashu? Anything else needs to approve it before we move on?**

**Comment by kristinashu** [comment]
Yes, the new copy sounds good to me! Please just run it past Steph McV, then update the comps and open an implementation ticket.

**Comment by taisdesouzalessa** [comment]
Implementation ticket here: #4142. Closing this design ticket.
