### ISSUE TITLE
make [1], [2], [3] on the PNI about page link to the notes below?

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#3933]
Looking at https://foundation.mozilla.org/en/privacynotincluded/about/meets-minimum-security-standards, it feels a bit odd to have footnotes to explanations _for_ explanations, without those being links (or have the footnotes just be a second paragraph for each item?).

Would it make sense to tweak those? /cc @kristinashu

**Comment by kristinashu** [comment]
@caltrider do you have any thoughts on this? Could each footnote just go below each relevant paragraph?

**Comment by caltrider** [comment]
Hmmm....I think the text above is the important text and the footnotes are kinda CYA things. I would recommend finding a way to de-emphasize the footnotes. Maybe do an * rather than the number cite at the top and then do the footnotes down below in much smaller text.

**Comment by kristinashu** [comment]
Rebecca reviewed the 10 user testing video and this didn't come up as an issue so I'm going to close this.
