### ISSUE TITLE
Blog page categories can’t be localized

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#3939]
As per Slack convo, it turns out those fields are not enabled for localization

**Comment by TheoChevalier** [comment]
See https://github.com/mozilla/foundation.mozilla.org/pull/3940#pullrequestreview-319452634 for more technical details.

I won’t be able to take care of this one in the near future (not even sure I’ll able to, it looks complicated), so, removing myself

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
