### ISSUE TITLE
Change Newsletter Signup Timing an Frequency

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#3943]
## Problem
Someone contacted Jen and said the email interstitial in the creep-o-meter was annoying them. Jen herself feels that the ask three times in a row is too much. After some discussion among the design and dev team we've decided to change the frequency of the interstitial. The ask will now only show once, occurring after the second time a user has voted on the creep-o-meter. 

## List of requirements
- [x] Change timing of the newsletter signup to after a user has voted twice
- [x] Change frequency of newsletter signup in creep-o-meter to only ~once~ twice

cc: @kristinashu @caltrider

**Comment by caltrider** [comment]
I do know that email sign ups are a priority for us, so I think we could do more than one time, like 2 or 3 would probably be OK, if we spaced them out a little. Maybe let users vote once then see the email ask then not see it until they vote a few more times? I don't want to lose the email ask push, just don't want to alienate users right up front either.

**Comment by beccaklam** [comment]
cc: @kristinashu @youriwims @taisdesouzalessa ☝️ any thoughts? I'm okay with spacing out 2 or 3, but not sure how difficult that is dev wise.

**Comment by youriwims** [comment]
@beccaklam let me follow up with another dev on that and get back to you.

**Comment by kristinashu** [comment]
@beccaklam are there any UX articles about best practices around this?

**Comment by beccaklam** [comment]
I'll have to look into it!

**Comment by kristinashu** [comment]
I couldn't find anything about frequency but in a super quick search it sound like adding a large close "x" is important (like in some of Becca's newer comps). I'll open a separate ticket to add the "x" and will update the requirements in the first comment in this ticket to balance everyone's suggestions... 

Don't show > Show > Show > Don't show > Don't show...

@youriwims I think this ready to go!
