### ISSUE TITLE
Active navitem underline disappears for newsletter subscribed users

### ISSUE THREAD

**Issue by youriwims** [mozilla/foundation.mozilla.org#3949]
**Describe the bug**
#3946 updates a user's newsletter subscription status from the home url install of product page url. The underline of active navitem _Home_ is removed for some reason when a user is coming from a 'subscribed' url.

**To Reproduce**
1. Go to 'https://foundation.mozilla.org/en/privacynotincluded/?subscribed=1'
2. See error

**Expected behavior**
Behavior should be identical to https://foundation.mozilla.org/en/privacynotincluded/

**Additional context**
[This line of code](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/buyersguide/templates/bg_base.html#L81) and [these](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/buyersguide/templatetags/bg_nav_tags.py#L12-L15) may be a good place to start.

**Comment by mmmavis** [comment]
Good catch! Looks like the active nav underline is missing if PNI url contains any query string. I'll file a fix.
