### ISSUE TITLE
[User Testing] Exploration

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#3975]
### Issue:
Explore User Testing topic

**Flow: how to better include user testing in our flow?**

- [ ] talk to MoCo to better understand their flow
- [ ] find benchmarks/research online

**Budget: how much does it cost?**
- [ ] talk to MoCo to better understand their budget
- [x] talk to Usertesting.com to better understand how they charge

**Constraints: do we have any barriers/dependencies?**
  - for instance, do we need to understand our audience better first before investing on it?
  - do we have to sell the value of it?

**Deliverable**
A doc with findings.

@beccaklam and I could work together on it.

cc: @kristinashu for triage

**Comment by taisdesouzalessa** [comment]
Document with WIP [is HERE](https://docs.google.com/document/d/1bYJNkhDWs9ox9oGHwTUrcCg6qm4dyk6xOprG1XNKaX0/edit?usp=sharing)

**Comment by taisdesouzalessa** [comment]
Had a chat with Usertesting.com and updated our WIP doc.

**Comment by kristinashu** [comment]
@taisdesouzalessa is this done? What else is left to do to consider this done?

**Comment by taisdesouzalessa** [comment]
The final goal was to get an estimate for the User Testing budget and we achieved that. We still have to talk to Raja but I feel we can close this ticket. Closing it.
