### ISSUE TITLE
PNI Usertesting of new designs

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#3976]
placeholder ticket for usertesting of new PNI designs

**Comment by taisdesouzalessa** [comment]
Script is in progress but first need to collect Becca's input on what we should test vs what can be left out of the testing.

WIP script + thinking [is here](https://docs.google.com/document/d/1CKiESqpBD69oIyAqFf0DT5yF4n20IGI5l3DyK-y-dck/edit?usp=sharing)

**Comment by taisdesouzalessa** [comment]
Script (pages 1 to 4) [is here](https://docs.google.com/document/d/1CKiESqpBD69oIyAqFf0DT5yF4n20IGI5l3DyK-y-dck/edit?usp=sharing)

**Next steps:** 
- [ ] collect Becca's feedback
- [ ] transfer test to Usertesting.com
- [ ] do a QA of the test with somebody who is not involved on the project (Becca or I) to increase its quality
- [ ] apply changes to Usertesting.com
- [ ] launch test

**Comment by kristinashu** [comment]
I've opened a ticket for reviewing and synthesizing the results https://github.com/mozilla/foundation.mozilla.org/issues/4013

How many test are you planning to do?

**Comment by taisdesouzalessa** [comment]
Thanks for opening that ticket, Kristina.

**The plan is to do 1 test with 15 users:**
- 5 desktop users: sticky creepometer variant
- 5 desktop users: button creepometer variant
- 5 mobile users: there is only one variant so we will be testing that.

**Comment by kristinashu** [comment]
Ah ok thanks, sorry I see your comment in the doc now. So 15 users x 15 min = 3:45 hours to review sounds reasonable.

**Comment by beccaklam** [comment]
Invision prototypes are all ready. [The file is here.](https://mozilla.invisionapp.com/share/V2V3UCEA5RE) I've shared it with @taisdesouzalessa and @kristinashu and Nat, just in case. 
I've also merged all my testing designs into abstract. You can find it in the PNI file and looking for the tab "PNI Test 2019".
<img width="310" alt="Screen Shot 2019-12-05 at 4 48 14 PM" src="https://user-images.githubusercontent.com/20977376/70276788-117e5980-177f-11ea-9171-e79c55ada80a.png">
Tais has written and uploaded the user tests to usertesting.com you can find them here:
[Variant A (Side Bar)](https://www.usertesting.com/st/QnRxCyPXpMpket6sbbXB?shared_via=link)
[Variant B (Sticky Button)](https://www.usertesting.com/st/iysKYergfLeugaNKX8Tc?shared_via=link)

Currently just waiting on feedback from Jen.

**Comment by beccaklam** [comment]
Oh, some more assets in case you need them: https://drive.google.com/drive/folders/1g_UYJ161dnTbev-HONisdJ_E55DIs3tX?usp=sharing cc: @taisdesouzalessa @kristinashu

**Comment by kristinashu** [comment]
Is there a difference in these two home screens?
<img width="613" alt="image" src="https://user-images.githubusercontent.com/1068783/70287912-7a68d000-1785-11ea-965c-eec9b37d9de3.png">

I noticed the About page in the nav looked selected so I updated one but then was worried there's something subtly different about the two that I'm not aware of.

**Comment by taisdesouzalessa** [comment]
Test has been launched:
- 5 users will see Variant A (sticky voting window)
- 5 users will see Variant B (voting button)

Test script [is here](https://docs.google.com/document/d/1CKiESqpBD69oIyAqFf0DT5yF4n20IGI5l3DyK-y-dck/edit?usp=sharing)

User Testing platform:
[Privacy Not Included - variant A](https://www.usertesting.com/dashboard#!/study/2889439/sessions?shared_via=link) 
[Privacy Not Included - variant B](https://www.usertesting.com/dashboard#!/study/2891540/sessions?shared_via=link) 

**NOTE from MoCo:** don’t forget to give star ratings to participants, it helps them, and if you get a really terrible one or a session that doesn’t work, you can let an admin know and we can request a new one.

**Comment by beccaklam** [comment]
> Is there a difference in these two home screens?
> <img alt="image" width="613" src="https://user-images.githubusercontent.com/1068783/70287912-7a68d000-1785-11ea-965c-eec9b37d9de3.png">
> 
> I noticed the About page in the nav looked selected so I updated one but then was worried there's something subtly different about the two that I'm not aware of.

Hmm, is that in Sketch? If yes, there shouldn't be a difference. In InVision there are two different Home screens because they link to different product layouts.

**Comment by kristinashu** [comment]
Oh it was in InVision but test are done now! Gonna close this ticket!

Results will be here https://github.com/mozilla/foundation.mozilla.org/issues/4013.
