### ISSUE TITLE
Images for PNI marketing blog post

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3978]
Copy doc https://docs.google.com/document/d/18YqGZJdHc1ua7oAKQWyFfYCTR1fkzK-6ruUa6ldHsJY/edit?ts=5ddef1e4

**Comment by kristinashu** [comment]
Made some images and created a draft post https://foundation.mozilla.org/cms/pages/671/edit/

Drive files are [here](https://drive.google.com/open?id=17ao3VJFegs-Gr50kpPiAJ2kcmfwRRJif&authuser=kristina@mozillafoundation.org&usp=drive_fs).

cc @natalieworth for edits or R+?

**Comment by natalieworth** [comment]
@kristinashu Yep looks good, I think the only thing is I took away the rounded corners for the Instagram ones—but definitely not a huge deal. Otherwise R+!
