### ISSUE TITLE
Links to 2017 and 2018 public records (990, audited financial statements) missing

### ISSUE THREAD

**Issue by tbm** [mozilla/foundation.mozilla.org#3995]
https://foundation.mozilla.org/en/about/public-records/ is missing links to the 2017 and 2018 public records:

2017:

* Annual report: https://www.mozilla.org/en-US/foundation/annualreport/2017/
* 990:  https://assets.mozilla.net/annualreport/2017/mozilla-2017-form-990.pdf
* Audited financial statements: https://assets.mozilla.net/annualreport/2017/mozilla-fdn-2017-fs-short-form-final-0927.pdf

2018:

* Annual report: https://www.mozilla.org/en-US/foundation/annualreport/2018/
* 990: https://assets.mozilla.net/annualreport/2018/mozilla-2018-form-990.pdf
* Audited financial statements: https://assets.mozilla.net/annualreport/2018/mozilla-fdn-2018-short-form-final-0926.pdf

**Comment by kristinashu** [comment]
Thank you @tbm for pointing this out!

@anilkanji I've updated the page with these links but could you please review it https://foundation.mozilla.org/en/about/public-records/?

**Comment by tbm** [comment]
Thanks, looks good to me!

**Comment by anilkanji** [comment]
Thanks @kristinashu - looks good!
