### ISSUE TITLE
Add close X to PNI newsletter signup

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3996]
Related to https://github.com/mozilla/foundation.mozilla.org/issues/3943

Based on usertesting, some people find the newsletter signup annoying and don't know the creep-o-meter results are just a click away. Consider adding an "X" to the top right corner on desktop and mobile.

Screen shot from prod:
<img width="901" alt="image" src="https://user-images.githubusercontent.com/1068783/69987678-e54fa800-14f4-11ea-923a-56f09e7b080c.png">

cc @beccaklam

**Comment by kristinashu** [comment]
@beccaklam to finalize comp.

**Comment by kristinashu** [comment]
Implementation ticket is here https://github.com/mozilla/foundation.mozilla.org/issues/4043, please update it once design is done.

**Comment by beccaklam** [comment]
Designs for this are done:
![Email-Interstitial-With-Close@2x](https://user-images.githubusercontent.com/20977376/70572383-b1682880-1b6d-11ea-804d-6fe049b39a92.jpg)
![M  Email-Interstitial-Button-With-Close@2x](https://user-images.githubusercontent.com/20977376/70572390-b3ca8280-1b6d-11ea-8014-b416b8f6c413.jpg)
