### ISSUE TITLE
[blog] Blog Home Accessibility Testing

### ISSUE THREAD

**Issue by youriwims** [mozilla/foundation.mozilla.org#4003]
---
## Step 1️ : Automated Testing*

  
- [x] Use `eslint-plugin-jsx-a11y` to fix a11y issues
   > Run  `npm test` and fix any issues related to the blog home template(s)
  

- [ ] Use `pa11y` to fix a11y issues
   > Run  `pa11y ./path/to/your/file.html`against file(s) to fix any issues related to the blog home template(s)
   > **OR**
   > Run `npm start` then `pa11y http://localhost:8000/blog` to fix any issues related to the blog home page

## Step 2️ : Web Testing*

- [ ] Use [axe](https://www.deque.com/axe/axe-for-web/) browser extension to fix any remaining issues related on the blog home page
  > Available for Chrome + Firefox

## Step 3️: Manual Testing

- [ ] Use [Accessibility Insights for Web](https://accessibilityinsights.io/docs/en/web/overview) browser extension _Assessment_ feature to guide you through manual testing issues related to the blog home page
  > *Currently only Available in Chrome + Edge
  > *Assessments 2-23 (_as applicable_)

- [ ] Export + Upload Completed Assessments 
  > `insert blog home assessment here` 👈

  
- [ ] Follow up ticket for further action/discussion (_if applicable_)
  > `insert follow-up ticket here` 👈 

 
---
Related Issue: #3934 
_* Updates should cover the overarching key actions listed at the bottom of the [master a11y ticket](https://github.com/mozilla/foundation.mozilla.org/issues/3934)._

**Comment by mmmavis** [comment]
`axe` extension is giving me a ton of false flags. Will need to look into them more.

**Comment by mmmavis** [comment]
Looks like the extension does have a few [bugs](https://github.com/dequelabs/axe-core/issues) now. Gonna put our a11y tickets on hold until `axe` bugs are resolved.

**Comment by mmmavis** [comment]
Updates: bugs are still there 😬

**Comment by jamilasnell** [comment]
Closing as part of closing #3934
