### ISSUE TITLE
[blog] Blog Post Accessibility Testing

### ISSUE THREAD

**Issue by youriwims** [mozilla/foundation.mozilla.org#4004]
---
## Step 1️ : Automated Testing*

  
- [ ] Use `eslint-plugin-jsx-a11y` to fix a11y issues
   > Run  `npm test` and fix any issues related to the blog post template(s)
  

- [ ] Use `pa11y` to fix a11y issues
   > Run  `pa11y ./path/to/your/file.html`against file(s) to fix any issues related to the blog post template(s)
   > **OR**
   > Run `npm start` then `pa11y http://localhost:8000/blog/eample-blog-post-path` to fix any issues related to a blog post

## Step 2️ : Web Testing*

- [ ] Use [axe](https://www.deque.com/axe/axe-for-web/) browser extension to fix any remaining issues related to a blog post page
  > Available for Chrome + Firefox

## Step 3️: Manual Testing

- [ ] Use [Accessibility Insights for Web](https://accessibilityinsights.io/docs/en/web/overview) browser extension _Assessment_ feature to guide you through manual testing issues related to a blog post page
  > *Currently only Available in Chrome + Edge
  > *Assessments 2-23 (_as applicable_)

- [ ] Export + Upload Completed Assessments 
  > `insert blog post assessment here` 👈

  
- [ ] Follow up ticket for further action/discussion (_if applicable_)
  > `insert follow-up ticket here` 👈 

 
---
Related Issue: #3934 
_* Updates should cover the overarching key actions listed at the bottom of the [master a11y ticket](https://github.com/mozilla/foundation.mozilla.org/issues/3934)._

**Comment by Pomax** [comment]
time passed this work by.
