### ISSUE TITLE
[pni] About Pages Accessibility Testing

### ISSUE THREAD

**Issue by youriwims** [mozilla/foundation.mozilla.org#4007]
---
## Step 1️ : Automated Testing*

  
- [ ] Use `eslint-plugin-jsx-a11y` to fix a11y issues
   > Run  `npm test` and fix any issues related to the about pages
  

- [ ] Use `pa11y` to fix a11y issues
   > Run `npm start` then `pa11y http://localhost:8000/privacynotincluded/about/example-about-path` to fix any issues related to the about pages

## Step 2️ : Web Testing*

- [ ] Use [axe](https://www.deque.com/axe/axe-for-web/) browser extension to fix any remaining issues related to the about pages
  > Available for Chrome + Firefox

## Step 3️: Manual Testing

- [ ] Use [Accessibility Insights for Web](https://accessibilityinsights.io/docs/en/web/overview) browser extension _Assessment_ feature to guide you through manual testing issues related to the about pages
  > *Currently only Available in Chrome + Edge
  > *Assessments 2-23 (_as applicable_)

- [ ] Export + Upload Completed Assessments 
  > `insert about pages assessment here` 👈

  
- [ ] Follow up ticket for further action/discussion (_if applicable_)
  > `insert follow-up ticket here` 👈 

 
---
Related Issue: #3934 , #3864
_* Updates should cover the overarching key actions listed at the bottom of the [master a11y ticket](https://github.com/mozilla/foundation.mozilla.org/issues/3934)._

**Comment by Pomax** [comment]
Solved as part of the PNI a11y epic
