### ISSUE TITLE
Design for surfacing the "related" content on pages beyond Blogs

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#4011]
With the work in https://github.com/mozilla/foundation.mozilla.org/pull/3945 landed, it's worth looking at whether/how we can leverage the existing "related posts" (template fragment) and "recent posts" (component) to add the "related" functionality to pages in addition to Blog.

The immediate candidates based on https://github.com/mozilla/foundation.mozilla.org/issues/3173 would be the Opportunity, Campaign, and BanneredCampaign pages.

**Comment by kristinashu** [comment]
Made some comps to start seeing what would be the ideal user experience https://redpen.io/p/af22f8c37ca4fcecac

**Comment by kristinashu** [comment]
@Pomax @mmmavis @xmatthewx any thoughts/feedback on the above proposal? Should we meet and talk about this?

**Comment by Pomax** [comment]
The proposed approach makes sense, I agree that for campaigns related content might motivate people to nav away from the campaign rather than signing, so let's avoid that =D

I think that it might be worth having a quick chat about this in the sprint that we want to work on this (if that's the coming one, then let's chat this week?)

**Comment by Pomax** [comment]
closing this issue as stale, especially given the new work on research, and the blog redesigns that are in progress.
