### ISSUE TITLE
Review results from user testing

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4013]
Once PNI test have launch https://github.com/mozilla/foundation.mozilla.org/issues/3976 it will take some time to review the results and come up with recommendations.

Tais will be out but Rebecca and I can split them up. Let's see how it goes but let's expect to do this in the first half of next week.

**Comment by kristinashu** [comment]
These are ready for review! 

[Privacy Not Included - variant A](https://www.usertesting.com/dashboard#!/study/2889439/sessions?shared_via=link) 
[Privacy Not Included - variant B](https://www.usertesting.com/dashboard#!/study/2891540/sessions?shared_via=link) 

I watch the first one for both tests and made rough notes in usertesting.com. Let figure out how we should compile the feedback!

**Comment by beccaklam** [comment]
This is done. Rainbow spreadsheet with user feedback is [here](https://docs.google.com/spreadsheets/d/1QAUZ4KHlygLbz4oLGt1zXoFtyPPEHfdXkfrE3ISwyq8/edit?usp=sharing). Tagging @taisdesouzalessa in case she's interested :)
