### ISSUE TITLE
Cypress not able to visit url that redirects

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#4042]
We redirect bad blog category urls back to `/blog`. However, when I asked Cypress to vist a bad category url, Travis gave me the following error.

```bash
http://localhost:8000/en/blog/category/randomnonsensecateogrythatdoesntexist
We attempted to make an http request to this URL but the request failed without a response.
We received this error at the network level:
  > Error: connect ECONNREFUSED 127.0.0.1:80
```

Note running the same Cypress test locally works fine though. 

/cc @Pomax @cadecairos @patjouk

**Comment by cadecairos** [comment]
This might be related to site settings on the test instance.

**Comment by Pomax** [comment]
specifically, it looks like it's trying to redirect to port 80, rather than the port 8000 it's supposed to redirect to.

**Comment by mmmavis** [comment]
Will verify if this still exists.

**Comment by Pomax** [comment]
We now also have a Cypress and CI task that checks whether URLs exist at all, so we can probably add our redirects there: https://github.com/mozilla/foundation.mozilla.org/blob/master/cypress/integration/url-tests.js

**Comment by jamilasnell** [comment]
We fixed this one ages ago!
