### ISSUE TITLE
PNI product page: add a close button to newsletter signup

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4043]
Placeholder dev ticket for https://github.com/mozilla/foundation.mozilla.org/issues/3996.

**List of Requirements**
- [x] Add close button with phrase ' CLOSE ' and the 'x' icon
- [x] Clicking the close button brings the user to the results page, just like the 'No Thanks' button
- [x] Update text to: 
> You Voted! You Rock!
> Now that you’re on a roll, why not join Mozilla? We’re not creepy (we promise). 
> We actually fight back against creepy. And we need more people like you.
> (Your results are under here)
- [x] Hide the "Tell us what you think" ribbon after the first screen (i.e., after the voting section)

Enter actual ticket description here

---

**🗒  Design -> Dev Handoff Checklist**
(Feel free to remove items that are not applicable.)

- [x] Design has been finalized
- [x] Link to original design ticket: #3996
- [x] Link to Redpen: https://redpen.io/p/mn3629c03f84209e3b
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Assets are included: 
![No@2x](https://user-images.githubusercontent.com/20977376/70572862-a82b8b80-1b6e-11ea-8b73-614355f9e9c0.png)

## Desktop design:
![Email-Interstitial-With-Close@2x](https://user-images.githubusercontent.com/20977376/70572569-07d56700-1b6e-11ea-8b35-ea5d82db0d65.jpg)

## Mobile design
![M  Email-Interstitial-Button-With-Close@2x](https://user-images.githubusercontent.com/20977376/70572605-1a4fa080-1b6e-11ea-85db-be04298ef3dc.jpg)

**Comment by alanmoo** [comment]
We may change the estimate once we have a design

**Comment by beccaklam** [comment]
@mmmavis I know that the ribbon thing is missing in these comps and that was intentional. Would it be a lot of extra work to take it out after the initial screen? I want to take it out because it's not necessary after a user votes.

**Comment by mmmavis** [comment]
Should we alright. I'll bump the estimate points from `2` and `3`.

**Comment by mmmavis** [comment]
@beccaklam do we have a svg version of the `x` icon?

**Comment by beccaklam** [comment]
Oops yes I can export that for you!

**Comment by beccaklam** [comment]
@mmmavis here you go! I exported all the icons for you, will also drop in the other ticket ...
[PNI-Dec-2019-assets.zip](https://github.com/mozilla/foundation.mozilla.org/files/3961175/PNI-Dec-2019-assets.zip)

**Comment by mmmavis** [comment]
Thanks!
