### ISSUE TITLE
Homepage blog feed shows the wrong date

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4050]
All posts on our [homepage](https://foundation.mozilla.org/) show April 8, 2018 at the publish date. It should the actual publish date.

Screen cap from prod:

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/1068783/70562360-1a857700-1b41-11ea-8714-88ecbc5c824a.png">

**Comment by Pomax** [comment]
The code for this is in fragments/featured_blogs - relevant except:
```
{% if blog.blog.first_published_at %} {% blocktrans with date=page.first_published_at|date:"DATE_FORMAT" %}on {{date}}{% endblocktrans %}{% else %}not published yet{% endif %}
```

**Comment by Pomax** [comment]
Nope, the error is that `date=page.first_published_at` part. That will be rendering the _homepage_ publish date, so that should be `date=blog.blog.first_published_at`.
