### ISSUE TITLE
Update Homepage fake data

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#4052]
<img width="711" alt="image" src="https://user-images.githubusercontent.com/2896608/70564631-64705c00-1b45-11ea-8da7-2a6ae0132c71.png">

Let's update homepage's fake data so we can make the fake homepage slightly realistic.

1. [ ] add some fake blog posts to blog section
2. [ ] highlights added by factory should be at most 5 (currently factory adds 6 highlights which exceeds the max number of highlights the homepage can have)

**Comment by aryan7778** [comment]
Is this issue is still open or any PR is already there for it.

**Comment by mmmavis** [comment]
Yes @aryan7778 this ticket is still open and I will be working on a PR for it in the next few days.
