### ISSUE TITLE
Reconsider template types

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4064]
Template names
- Reassess our current template names so they are less confusing
- Provide clear descriptions of when to use which type

Template availability 
- Clarify when a template is available under which url

**Comment by kristinashu** [comment]
Linking to this old ticket about our templates https://github.com/mozilla/foundation.mozilla.org/issues/1405

And making a note about Pomax's comment in slack:
> does it make sense to have the "this is part of a broader movement" on artifact pages? e.g. https://foundation.mozilla.org/en/artifacts/x-ray-goggles/

Few thoughts:
- Agree that it doesn't feel right but worry about modifying the template just for this one use case
- That copy is pretty out of date and maybe we can do something that will work on everywhere. 
- I'm also curious about how many people actually click on this. 
- Wonder if showing related content via tagging will be a more effective way to get people to stay and explore the site.

**Comment by kristinashu** [comment]
I would like to talk to everyone about this when there's time but here are my preliminary recommendations.

## Template names
Visual IA https://redpen.io/hx70e9eb24e0534b72 for reference:

### 1) Rename `opportunity` template to `basic`
- notes: this template is used for:
  - _short_ lived info
  - any staff can make anytime
  - allows for a lot of subpages with longer names

### 2) Rename `bannered campaign` template to `banner`
- note: layout is used a lot and not only for campaigns and is used for:
  -  a page is more important and longer lasting
  - receives some design attention
  - sub nav is limited
  - optional petition or newsletter signup snippet

![canvas](https://user-images.githubusercontent.com/1068783/71853081-3a03b700-308f-11ea-9058-2de272f2f8ef.png)

### Reduce then number of template options
Screen caps here https://redpen.io/p/avd5fc0b3db14a7883. To make things easier and clearer for staff, we should limit the types of templates they can use and when. I'm not sure what a lot of the types are so will need to discuss more with @Pomax and @alanmoo. Things to look at:

![image](https://user-images.githubusercontent.com/1068783/71853712-104b8f80-3091-11ea-98a9-319f78906881.png)

### 1) Don't allow users to create pages under `Participate` 
- no one is really doing this anyway so let's simplify it and avoid any future confusion

### 2) Move /opportunity pages to /initiatives
- already have a ticket for this https://github.com/mozilla/foundation.mozilla.org/issues/2971

### 3) Reduce template options under /campaign
- there are so many options and I don't even know what they all do so staff won't know either, let's remove what we can

<img width="492" alt="Screen Shot 2020-01-06 at 2 07 52 PM" src="https://user-images.githubusercontent.com/1068783/71853683-0164dd00-3091-11ea-854d-cac8f93918ce.png">

## IH snippet
- opened a separate ticket https://github.com/mozilla/foundation.mozilla.org/issues/4103

**Comment by alanmoo** [comment]
One open question still: the relationship between pages and their children, and how we indicate what pages show up where.

**Comment by kristinashu** [comment]
Ooooh this seems smart and related https://github.com/mozilla/foundation.mozilla.org/issues/2964

**Comment by kristinashu** [comment]
Alan has added a brain dump of notes here https://docs.google.com/document/d/1ZZtmOTxVMclvwULrG2IJKwO3P7tHCjk2jZb9LVIFZrg/edit?usp=sharing.

And he found this ticket - Add new "nav root page" setting to Wagtail pages #2877.

I will open a brief https://mzl.la/project-brief for this work so it can get prioritized and a facilitator.

**Comment by kristinashu** [comment]
I've opened two new tickets that have come out of this ticket
- Reduce number of template options under campaigns #4221 
- Improve template names #4220 

And here are other tickets this ticket has surfaced
- Move /opportunity pages to /initiatives #2971 
- Add new "nav root page" setting to Wagtail pages #2877 
- Enhance landing page inheritance for easier author experience #2964

Also worth re-linking to [Alan's doc here](https://docs.google.com/document/d/1ZZtmOTxVMclvwULrG2IJKwO3P7tHCjk2jZb9LVIFZrg/edit?usp=sharing). 

Hopefully we can get these into a sprint. But close this ticket!

**Comment by alanmoo** [comment]
Feel free to ping me on this topic if you need anything else; I know site structure/templates was a thing that was mostly just in my head for a long time.
