### ISSUE TITLE
Leadership page content update

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4067]
### Request
https://foundation.mozilla.org/en/about/leadership/
- Put management first
- Include directors as well as VPs

### To do
- gather profile photos
- create a draft page
- get it approved by Anil

**Comment by TheoChevalier** [comment]
Note to self that we will need to update localized pages as well (images, re-arrangement of section and localized titles)

**Comment by sabrinang** [comment]
@kristinashu 
- VPs are already present and added directors below in Management section (currently alphabetically by last name or is there a prefered order?)
- missing photos of Sara and Ethan (none in phonebook)
- currently saved as a draft in wagtail

![Screenshot_2020-01-06 Leadership](https://user-images.githubusercontent.com/2492510/71848113-7d582880-3083-11ea-8055-f35de470aa7c.png)

**Comment by kristinashu** [comment]
Thanks @sabrinang! @anilkanji does this seem like the right order? If so then Sabrina, could you please ping Sara and Ethan for a photo (maybe even ping Lotta and Lindsay to see if they have a more professional photo)?

**Comment by anilkanji** [comment]
Hi @sabrinang, this looks like the right layout - thank you. I think we need to reach out to all of the directors to let them know we'll be adding them to the leadership page, and give them an opportunity to provide a more professional image with a deadline.

**Comment by sabrinang** [comment]
https://foundation.mozilla.org/en/about/leadership/ is published. Sara has a placeholder square but I'm following up and will update it once I receive the image. Lindsey is on mat leave so I won't hear back from her but I've used her photo from mozilla people directory.

**Comment by kristinashu** [comment]
Sweet! Photos are sooo much better! Closing!

**Comment by kristinashu** [comment]
Sweet! Photos are sooo much better! Closing this ticket!

cc @TheoChevalier

**Comment by TheoChevalier** [comment]
Thanks Kristina! 🚀 Off to Pontoon! https://github.com/mozilla-l10n/engagement-l10n/commit/c5017975726a86ced5fb40539bc047db899f0386

@sabrinang Heads up that by the time you update images, you will likely need to update them in other languages too
