### ISSUE TITLE
Add validation to Shareprogress fields on Petition snippet

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#4072]
Shareprogress fields on Petition snippet need to be in the right format (e.g., `sp_12345` and not just `12345`) in order for the inject code to properly kick in and for the share buttons to work.

Let's 
- [ ] update help text and
- [ ] add a custom validator to those fields to ensure value has `sp_` prefix.

**Comment by kristinashu** [comment]
cc @xmatthewx

**Comment by Pomax** [comment]
Is this still work we need to do? If so, who would be the right person to cc?

**Comment by kristinashu** [comment]
@kaili09 would like to be able to use Share Progress.

**Comment by kaili09** [comment]
I used this the other day and thought it could also be solved by sample text -- doesn't necessarily need to be validation.

**Comment by Pomax** [comment]
@kaili09 I'm looking at the model text atm, would this work for you?

> Share Progress id for (facebook/twitter/email) button (including sp_... prefix)

**Comment by kaili09** [comment]
I think that works. Would it be in the box or beside it?

**Comment by Pomax** [comment]
Until wagtail supports manually specifying placeholder text, this is going to necessarily have to be an update to the field help text only =(

**Comment by Pomax** [comment]
note: I will also make the help texts always show, because it's kind of ridiculous that they only show on mouse-over.
