### ISSUE TITLE
MSS badge overlapping products on mobile

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#4081]
The MSS badge is overlapping product images on mobile (see image below). Designers need to identify which products this is happening on and crop the photos slightly smaller and more to the right to accommodate for the badge.

<img width="369" alt="Screen Shot 2019-12-17 at 11 22 05 AM" src="https://user-images.githubusercontent.com/20977376/71014164-7ca12780-20bf-11ea-8218-1544f59d6790.png">

@mmmavis Is there a quick way to fix this or do you think this needs design? cc: @kristinashu

**Comment by mmmavis** [comment]
Any changes we make will be applied to all product pages so I'm not sure how we wanna fix this particular case as it's product image dependent.

**Comment by beccaklam** [comment]
True true. Suggestion from Kristina that I think will work:

> [...] seems like it's only a few images that have this issue? maybe we can just update those graphics so the product is smaller and slightly more to the right if possible.

**Comment by beccaklam** [comment]
I'll change this to a design bug then. cc: @kristinashu

**Comment by beccaklam** [comment]
Went through the 2019 products and updated all the images that were overlapping. 
[Resized photos here on the drive](https://drive.google.com/drive/folders/1z6aLfB4uDEE1B01mVU84pQ5ofdIkAz8Z?usp=sharing)
[PSD file here](https://drive.google.com/file/d/1ptpXhTjlhUZM_TnnU3hTW9JMLVTmo1mb/view?usp=sharing)
This is done!
