### ISSUE TITLE
Design a string management process

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#4100]
We’ve started accepting translations, but we still need to define a process for moving source strings and translations between the `master` and the `l10n` branch back and forth. Let’s start doing this, as the l10n branch already conflicts with master because we created merge commits along the way. Those conflicts are easy to fix, but we should move to a safer process as soon as possible. This process will need to meet some requirements:

# Requirements
- We should never have a conflict between the two branches.
- We should never create a commit when moving strings between branches, and always move existing commits.
- No PR can touch a file in `/network-api/locale` on `master`. I’m not sure we can really enforce this, besides making sure all reviewers are aware and adding a note in a README file.

# Notes on what’s already set up
- Pontoon only touches files in `/network-api/locale` on `l10n` and never use `force-push`.
- PRs landing strings on `l10n` (i.e., the result of `makemessages`) are created or reviewed by a l10n PM. Review requests are automatically triggered by https://github.com/mozilla/foundation.mozilla.org/blob/master/CODEOWNERS

# Process  proposal
We should automate some of the following operations. I’m not sure which infra should run the commands (GitHub actions?), but I’m sure DevOps will have input on that.

## l10n → master merge (automated)
From time to time (daily?), create a PR from `l10n` to `master`. Automatically merge it, always using `Rebase & merge` and NOT `Squash & merge`, nor clicking the `Update branch` button that both create merge commits and would introduce conflicts down the line. Even outside translation files, which would be a total disaster.

All the individual Pontoon commits will show up in master commit history.
If we can’t merge those PRs automatically, I’m happy to be assigned to them and do it.

## master → l10n merge (automated)
Regularly fast-forward the `l10n` branch to `master` tip. Maybe we can even do that every time a PR gets merged to master, using GitHub actions. The frequency shouldn’t have any effect on the proposed solution, but if we set up a staging instance using the l10n branch, it’s good to have the code base as up-to-date as we can.

The commands can be something like this:
`git pull --all` (this should pull both l10n and master)
`git checkout l10n`
`git merge --ff-only origin/master` (--ff-only is an important safeguard here)
`git push origin l10n`

## Landing new strings (must remain manual)
 Create a PR to land the result of `makemessages`. This will expose new (and remove deleted strings) strings to Pontoon.

@patjouk, @cadecairos do you have thoughts/concerns with the proposal above?

**Comment by patjouk** [comment]
Sadly, no GitHub actions since Mozilla is on a legacy account and updating
would cost a ton of money.
We will discuss this with Chris today during our triage.

**Comment by TheoChevalier** [comment]
Sadly, what I had in mind doesn’t work — you can’t replicate the `rebase` behavior with merge without creating merge commits. And we can’t use `rebase`, because it requires to force-push, and the branch protection doesn’t allow that. It’s also scary to build an automation based on something that rewrites history…

I think we should consider moving the `locale` directory into a [Git subtree](https://www.atlassian.com/git/tutorials/git-subtree), and drop the `l10n` branch altogether. Or use Git submodule, but after reading a couple articles, Git subtree seem more appropriate. I don’t have experience with it, though. @patjouk / @cadecairos What do you think? Do you have experience with git subtree?

I think this would be a more robust solution, and would even prevent anyone from creating conflicts by mistake — by touching a .po file on master, by using the `Update branch from master` button on `l10n`, etc. (c.f 3rd requirement above)

**Drawbacks:**
- String export may be _slightly_ more complicated (c.f. “[Contributing back upstream](https://www.atlassian.com/git/tutorials/git-subtree)”), but it looks manageable.
- We will need to stick to bilingual l10n file formats, e.g. `.po` or `.xliff`. If we were to use monolingual files like `.ftl`, source strings wouldn’t be in the code, so devs couldn’t edit strings from this repo. So far, sticking with bilingual files doesn’t look like an issue, as for the remaining react/JS i18n stuff, both proposed approaches are using `.po`. But it would definitely limit our options if we were to go another route. cc @Pomax for this last point.

**Comment by TheoChevalier** [comment]
Did some subtree testing here https://github.com/TheoChevalier/fomo-l10n with my fork https://github.com/TheoChevalier/foundation.mozilla.org

This seem to work, using only pull requests (no direct push to master). Haven’t yet tested to extract strings from the main repo then push upstream

Commands I ran, if you’re curious https://gist.github.com/TheoChevalier/cbdd534295099c1f671932b9b24426af

**Comment by TheoChevalier** [comment]
We had a discussion in Berlin, and the solution we picked is being implemented in https://github.com/MozillaFoundation/mofo-devops/issues/735
