### ISSUE TITLE
Newsletter page doesn't pass on tracking information to SFMC

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/foundation.mozilla.org#4102]
**Describe the bug**
When you try to sign up for the newsletter through https://foundation.mozilla.org/newsletter/, if you landed on it with a query string including utm codes (like https://foundation.mozilla.org/newsletter/?src=acqtestdec2019&utm_source=acqtestdec2019&utm_medium=cpc&utm_campaign=pro&utm_content=daily-kos), none of the querystring is passed on to Salesforce. We should pass this on so that we can properly report in SF.

Not sure if this is also the case with the footer newsletter signup, etc.

**To Reproduce**
Steps to reproduce the behavior (any browser):
1. Go to https://foundation.mozilla.org/en/newsletter/?utm_source=gideon&utm_medium=gideon&utm_campaign=gideon&utm_content=gideon and sign up for the newsletter.
2. Check your customer record's Signup Source URL in SF. It will only show https://foundation.mozilla.org/en/newsletter/ instead of the whole url.

**Expected behavior**
The entire landing page url should be recorded in SalesForce when signing up for the newsletter.

cc @stephaniemcv who can help with verifying + @WillatMozFdn who first discovered this with me.

**Comment by mmmavis** [comment]
@gideonthomas was this request coming from Steph and Will? Wanted to double check because we had the query param stripped on purpose: https://github.com/mozilla/foundation.mozilla.org/issues/2994#issuecomment-516997473

**Comment by gideonthomas** [comment]
It was with @WillatMozFdn that I checked this out. @stephaniemcv is there a reason we want query params stripped out? It makes it nearly impossible to report and evaluate on audiences without them. + the mozilla.org newsletter page does send query params to salesforce, so shouldn't we keep parity with that?

**Comment by stephaniemcv** [comment]
The ideal end state is to strip the query params off of the source url and pass them into their own fields. It'll be easier on the system for reporting than trying to parse a long string of the full url. I pinged you in the requirements doc.

**Comment by gideonthomas** [comment]
@stephaniemcv are these fields already configured in SFMC and does basket already support this? I don't seem to see donate doing this either -- this issue is specifically for newsletters on the foundation site.

**Comment by stephaniemcv** [comment]
The fields are not in SFDC yet and basket does not already support it.

**Comment by gideonthomas** [comment]
Thanks Steph!

@mmmavis I think in the meantime, let's not block on that -- let's pass all the query params like MoCo does.

I'll have a chat with Anil and see how to push forward with separating the fields in SFMC, so there will need to be a follow-up PR later on once that's done.
