### ISSUE TITLE
Remove IH snippet

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4103]
A lot of our CMS templates automatically add this to the bottom of the page. We should take a look at this again, make sure that this is still the best approach and that the copy is still relevant.
<img width="694" alt="image" src="https://user-images.githubusercontent.com/1068783/71853465-6a982080-3090-11ea-93bc-b8d1658fa6b3.png">

Notes:
- The goal for this was to reduce our bounce rate. 
- Copy is pretty out of date and maybe we can do something that will work on everywhere.
- I'm also curious about how many people actually click on this.
- Wonder if showing related content via tagging will be a more effective way to get people to stay and explore the site.

And making a note about Pomax's comment in slack:

> does it make sense to have the "this is part of a broader movement" on artifact pages? e.g. https://foundation.mozilla.org/en/artifacts/x-ray-goggles/

**Comment by kristinashu** [comment]
We have the go-ahead from Anil to remove this snippet from the entire site!

**Comment by Pomax** [comment]
nice! marking this as good first bug, so we can assign it to Daniel as some of his first work.
