### ISSUE TITLE
MozFest 404 Page Top Nav Is Not Up To Date

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/foundation.mozilla.org#4109]
**Describe the bug**
The top nav bar on the 404 page for the MozFest site  (#3275) is not updated with Wagtail / isn't the same as what is currently on the website.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://www.mozillafestival.org/en/askdj'
2. See the nave on 'https://www.mozillafestival.org/en/'

**Comment by mmmavis** [comment]
@marcwalsh the nav for MozFest 404 page is hardcoded (e.g., not controllable by CMS so they won't get dynamically updated). I can update the 404 page so that the nav links and button match what's on https://www.mozillafestival.org/en/.

**Comment by kristinashu** [comment]
@mmmavis do you mean that the nav on the 404 would need to be manually updated every time the cms nav is updated?

I think the nav is going to change several times throughout the year so maybe we should just not show any of the nav items, just encourage people to go to the mozfest homepage.

cc @xmatthewx

**Comment by mmmavis** [comment]
@kristinashu  yes the nav will have to be manually updated. I'm good with not showing any nav items on 404 pages. The main Foundation site does the same thing for same reason as well.

**Comment by xmatthewx** [comment]
Huh. Yes, probably better to remove nav that will break in the future. But, isn't there a way for the 404 template to leverage the primary nav template just like any other view?

**Comment by mmmavis** [comment]
> Isn't there a way for the 404 template to leverage the primary nav template just like any other view?

Ah I wish that's the case. 404 page is static and doesn't get a "page context" like all other CMS page types do.
See https://github.com/mozilla/foundation.mozilla.org/issues/3357 for previous discussion.

I'll update my PR so nav links are removed on MozFest 404 page.

**Comment by kristinashu** [comment]
Sounds good, thank you Mavis!

**Comment by mmmavis** [comment]
Fix for this ticket will go live today as well.
