### ISSUE TITLE
IA: Identify key stakeholders & questions

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4111]
Based on planning in https://github.com/mozilla/foundation.mozilla.org/issues/4090 and [our working doc](https://docs.google.com/document/d/1Co1uocNdhnxmYNBSR9QAg4BQYckTsFYhr1I6vWSCFhY/edit?usp=sharing).

### Identity key stakeholders
- [x] Make a list of potential stakeholders we should interview and consult
- [ ] Get feedback on the list from Anil and the leadership team

### Prepare for interviews
- [x] Prepare a simple introduction to the project and goals. This relates to [project brief](https://docs.google.com/document/d/1IZ8dVsLXrBrge5f7vJ69Gj4mMsIGQ9XlT0VgwuFwfIQ/edit?usp=sharing).
- [x] Prepare a list of key interview question (possibility to also interview about brand https://github.com/MozillaFoundation/Design/issues/450 and audience work as well)

### Interviews 
This will happen here https://github.com/mozilla/foundation.mozilla.org/issues/4112

#### WIP list of key stakeholders
- Leadership (Mark)
- Engagement (Anil, Matthew, Alan, Jen)
- Fundraising (Juan & Jesse)
- Comms (Kevin & Lotta)
- Advocacy (Jon, Sara, Kaili)
- Fellowships & Awards (Amy)
- IHR (Kasia & Solana)
- OLE (?)
 - Mozfest (Sarah)

cc @taisdesouzalessa @beccaklam @sabrinang

**Comment by taisdesouzalessa** [comment]
@kristinashu here is the list and also the detailed plan on this task: https://docs.google.com/document/d/11wys4dpmzQy9iwYoKg17moExGmdOlNhvdX4iH18QuDU/edit?usp=sharing - should I ask for Anil's input on that list?

**Comment by kristinashu** [comment]
How about we wait until we have a few things to share and then share them all at once? This way he doesn't have to multitasks and context shift so many times.

**Comment by taisdesouzalessa** [comment]
It makes sense to me. I'll work on the interview questions as well then in order to collect all the things we could share.

**Comment by taisdesouzalessa** [comment]
Here are the [interview questions](https://docs.google.com/document/d/11wys4dpmzQy9iwYoKg17moExGmdOlNhvdX4iH18QuDU/edit#heading=h.22xkp1o1ozkx)
@kristinashu, @beccaklam: could I get your feedback on them? 
@sabrinang: I tagged the questions that could be potentially useful for brand. Please let me know if they make sense to you. We just have to be mindful of the number of questions, so if you want to add an extra one, I may have to remove an existing one. Also, feel free to give feedback as well :).

**Comment by beccaklam** [comment]
@taisdesouzalessa Questions look great! Just left one grammatical comment but otherwise great job!

**Comment by kristinashu** [comment]
Questions look great! We're just waiting for Anil to give feedback on the list by eod Tuesday. In the meantime, Tais has set up an interview with Alan and will try to set one up with Jen. Those will be documented here https://github.com/mozilla/foundation.mozilla.org/issues/4112.

**Comment by taisdesouzalessa** [comment]
Refined interview template + card sorting script [here](https://docs.google.com/document/d/1S3_77-vi0IFNcRAKt7zpwhUWZtnI_5bzc_FqcgYHKqU/edit?usp=sharing)

**Comment by taisdesouzalessa** [comment]
Waiting on Anil's feedback on stakeholders to interview so I can book the meetings. Interviewing Jen this week.
