### ISSUE TITLE
IA: Interview key stakeholders Part I

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4112]
Based on planning in https://github.com/mozilla/foundation.mozilla.org/issues/4090 and [our working doc](https://docs.google.com/document/d/1Co1uocNdhnxmYNBSR9QAg4BQYckTsFYhr1I6vWSCFhY/edit?usp=sharing).

Related to Identify key stakeholders #4111 

### Interviews Part I
_(Taís' edits from this line on - I'll keep growing the list as I interview people)_ 
- [x] Schedule interview with Alan
- [x] Run interview + card sorting activity with Alan
- [x] Schedule interview with Jen
- [x] Run interview + card sorting activity with Jen
- [x] Schedule interview with Kevin
- [x] Run interview + card sorting activity with Kevin
- [x] Schedule interview with Lotta 
- [x] Run interview + card sorting activity with Lotta 
- [x] Schedule interview with Audrey
- [x] Run interview + card sorting activity with Audrey
- [x] Schedule interview with Becca Ricks
- [x] Run interview + card sorting activity with Becca Ricks
- [x] Schedule interview with Theo 
- [x] Run interview  + card sorting activity with Theo
- [x] Schedule interview with Kaili 
- [x] Run interview  + card sorting activity with Kaili

### Report
- to be done here https://github.com/mozilla/foundation.mozilla.org/issues/4156

**Comment by taisdesouzalessa** [comment]
I am using this ticket to track the interviews + card sorting I am doing. I won't post individual interview documents here. 
I will have a compiled version with the main highlights and commonalities in the final report (#4156)

**Comment by kristinashu** [comment]
This ticket is now "Part I" and then "Part II" can take place in https://github.com/mozilla/foundation.mozilla.org/issues/4228 over next sprint.

@taisdesouzalessa please close this ticket after your last interview this week!

**Comment by taisdesouzalessa** [comment]
all interviews for the Part I done!

**Stats:** 
- 8 interviews done
- around 400 cards sorted
- lots of meaningful conversations

Thanks @sabrinang for being a great thinking partner for this first round.
