### ISSUE TITLE
IA: Identify key audiences 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4114]
Based on planning in https://github.com/mozilla/foundation.mozilla.org/issues/4090 and [our working doc](https://docs.google.com/document/d/1Co1uocNdhnxmYNBSR9QAg4BQYckTsFYhr1I6vWSCFhY/edit?usp=sharing).

### Todo
- [x] Create a prioritized list of key audiences and their breakdown

(Need to talk to key stakeholder we can ask them for a suggestion of a person or 2 of the audience that would be able to talk to us)

#### WIP list of ideas
- New people - define “new audience” for site
- Partner orgs
- Existing people like fellows
- Existing email list

cc @beccaklam

**Comment by taisdesouzalessa** [comment]
Started creating the list. WIP here: https://docs.google.com/document/d/1PRaKKhNT25HRgIEG8kwfDvcFCZAgVDtZ6Cgifqz4NJ0/edit#

**Comment by taisdesouzalessa** [comment]
List is here: https://docs.google.com/document/d/1PRaKKhNT25HRgIEG8kwfDvcFCZAgVDtZ6Cgifqz4NJ0/edit?usp=sharing

The goal is to have in this list all the audiences we can think about so we are aware of the whole ecosystem. We will interview only the ones we prioritize as P1 (and P2 maybe). So the key audience list will be made from this current list.

@kristinashu @beccaklam @sabrinang @natalieworth do you see any missing audience? If so, can you please add there? Thanks!

**Comment by kristinashu** [comment]
Thank you Tais! Sounds like you've started the work on this but that you will shift your focus to the stakeholder interviews and then revisit this ticket after that. So I expect this ticket to carry over into the next sprint and happen after All Hands.

**Comment by taisdesouzalessa** [comment]
In order to advance this work (while I wait on Anil's feedback on stakeholders' interviews) I will map our current audience (existing email list). I will use the info we got from our AI survey so we all can have the same picture of our current audience.  Any objections @kristinashu?

**Comment by taisdesouzalessa** [comment]
Here is the snapshot from our current audience and why I think it is important we have at least this simple snapshot in our team - thanks to @gideonthomas for being my thinking partner on that: https://docs.google.com/presentation/d/1tF9ZGh6UIvP2R5xPKj3vZo8SKogTNWg_L40iXFbFI0s/edit?usp=sharing - let me know if you have any questions/adjustments to make.

**Comment by cadecairos** [comment]
@kristinashu can this be put in a milestone if it's ongoing work?

**Comment by kristinashu** [comment]
This has been on pause but I've put it in our next milestone so we don't forget!

**Comment by kristinashu** [comment]
Moving this into this sprint. @taisdesouzalessa is going to identity a limit few key people to interview and test our prototype with.

**Comment by taisdesouzalessa** [comment]
[Here is the list](https://docs.google.com/spreadsheets/d/1YzBI4JmLgo0HU0FBYR7yIq-oQQBbS7LhlihWrNCVQHU/edit?usp=sharing) I got from talking to internal stakeholders. My suggestion is to interview (and do user testing with) the group marked as P1. 

Based on the first IA drafts I am seeing and the report recommendations, I believe a solid foundation can be built if we focus on the general audience first. Can they get where they want to? Do they understand what we do and why? 

After that we can optimize the paths for the other audiences and test with specific groups. What do others think? @kristinashu @gideonthomas @xmatthewx @beccaklam
