### ISSUE TITLE
Newsletter page throws errors

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/foundation.mozilla.org#4129]
**Describe the bug**
The https://foundation.mozilla.org/newsletter/ page is broken. Here's the error from Sentry:
https://sentry.prod.mozaws.net/share/issue/84cddface079485d89d12ff90a87533f/
Not sure if the subscription is going through or not, but it's definitely throwing errors in the console.

**To Reproduce**
1. Go to https://foundation.mozilla.org/newsletter/
2. As soon as you click on an input box, the error is thrown in the console.

**Screenshots**
<img width="1440" alt="Screen Shot 2020-01-13 at 1 33 22 PM" src="https://user-images.githubusercontent.com/5816130/72281826-4c3ea180-3609-11ea-8560-9165f26c3073.png">

Related to https://github.com/mozilla/foundation.mozilla.org/issues/4102

**Comment by Pomax** [comment]
We can probably do a test for the `data-form-position` attribute, and if it doesn't have an element, simply skip the rest of the code in that handler since it's just for visibility toggling.

https://github.com/mozilla/foundation.mozilla.org/blob/master/source/js/components/join/join.jsx#L207-L216
