### ISSUE TITLE
PNI follow-up: remove unused "CloudinaryImageField" in PNI models.py

### ISSUE THREAD

**Issue by patjouk** [mozilla/foundation.mozilla.org#4135]
Follow up PR of #4126

Cloudinary updates made the `CloudinaryImageField` custom field useless. We can remove it, but it will require some manual work to squash the migrations.

**Comment by patjouk** [comment]
Not adding this to our current milestone for now. I will come back to it when I'm done working on updating donate review apps to the new system. Feel free to grab it in the meantime.

**Comment by Pomax** [comment]
moving this into the PNI followup epic, with the switch to wagtail we can probably close this as part of the "delete old products" step.
