### ISSUE TITLE
Update body-small and H6-heading colour 

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#4136]
Update body-small and H6-heading colour so it has better contrast for reading. From $gray-40 `#999999` to $gray-60 `#666666`

- See design ticket: https://github.com/MozillaFoundation/Design/issues/422#issuecomment-573912124
- Sketch library type styles have been updated and merged in Abstract

**Comment by mmmavis** [comment]
@sabrinang is this ready for implementation or we need to tackle this along with other to-be-created brand related tickets?

**Comment by mmmavis** [comment]
@sabrinang thoughts?

**Comment by sabrinang** [comment]
design issue is closed for this so it is ready for implementation 👍
