### ISSUE TITLE
Grants page layout proposal

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4139]
[Request from Mark](https://docs.google.com/document/d/1HcKBVO85Lv8C2TX7-tq99mdzULQxw0oT-xfE5ytUqfE/edit).

**Create a simple Mozilla Grants foundation page that is holistic and historical.** 

Should consider:
- Fellowships
- Awards
- MOSS
- Mozilla Research Grants

(clarify which are still active and available to seek funding and which are not)
(point to a list of things we’ve supported where they exist and are current)

### For this ticket
- [x] Design to make a proposal _(I recommend we do a mockup with placeholder content that shows at a high-level the structure, order, and type of content the page should have)_
- [ ] recommendations on were the page should live

### To be done later
- Talk to stakeholders (Anil, Mark, Bob, Lotta)
  - Interview
  - Write brief
  - Get feedback on comp
- Update design
- Finalize content
- Create page in Wagtail
- Delete www.mozilla.org/grants/ and redirect to this new page

**Comment by kristinashu** [comment]
@xmatthewx is going to check-in with Bob to see if they have started on something and if she thinks a mock-up would be helpful. @beccaklam could work on this next week if needed.

**Comment by taisdesouzalessa** [comment]
@beccaklam as I promised last week, here is a [quick report based on stakeholders interviews](https://docs.google.com/document/d/1A521soXcO1106NIDDd34GCHElamdKUWAyJgMNQLN4Qk/edit?usp=sharing). Let me know if you have any questions.

**Comment by xmatthewx** [comment]
Great work Taís!

**Comment by beccaklam** [comment]
Started a redpen with three rough high level proposals for the grant page: https://redpen.io/p/ure77a4bf5b093d37b @kristinashu @taisdesouzalessa @xmatthewx Let me know what you think!

**Comment by kristinashu** [comment]
Awesome, thank you @beccaklam! Let's check-in on this next week, we should probably all huddle up on feedback and next steps.

**Comment by kristinashu** [comment]
Follow up work can be done here https://github.com/mozilla/foundation.mozilla.org/issues/4303 so this is good to close!
