### ISSUE TITLE
QA > Link to learning site has a hardcoded locale, we don't need it

### ISSUE THREAD

**Issue by flukeout** [mozilla/foundation.mozilla.org#414]
On the Support Page, under Local Organizing...

![image](https://cloud.githubusercontent.com/assets/25212/26075963/0071dcdc-396c-11e7-8255-671ca0216c68.png)

**Comment by gvn** [comment]
@flukeout if this looks good on https://foundation.mofostaging.net/get-involved/ then feel free to close this ticket! 🎉

**Comment by flukeout** [comment]
👍
