### ISSUE TITLE
[Header/body newsletter list conflicts] Implementation ticket: updated footer copy

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4142]
Implementation ticket for #3927

**Screenshot (mockup):**
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/22157921/72652567-292f2d00-393c-11ea-9bcf-f3612dc1e287.png">

**Copy:**
Join our **Mozilla News** email list to stay informed and take action.

**Comment by mmmavis** [comment]
This wasn't the troublesome ticket I thought it was. Changed estimate from 3 to 1.
