### ISSUE TITLE
[Header/body newsletter list conflicts] Implementation ticket: updated Thank You page copy

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4143]
Implementation ticket for #3928

**[Mockup here](https://mozilla.invisionapp.com/share/8TUW2XEGAF3#/401284807_Screenshot_2020-01-17_Open_Leadership_Events-4-)**

**Copy:**

Thanks!

One more thing. To protect you from unwanted emails, we ask you to confirm your opt-in to our email subscriptions. 

If you haven’t previously confirmed your opt-in to a Mozilla-related email subscription you may have to do so now. **Please check your inbox or spam filter for an email from us to click and confirm your subscription.** 

If you have already confirmed your opt-in to receive Mozilla-related emails, you can now [manage your subscriptions](https://www.mozilla.org/en-US/newsletter/recovery/) and update your email preferences.

**Update:**
We removed the first sentence:  "One more thing. To protect you from unwanted emails, we ask you to confirm your opt-in to our email subscriptions." to: 1. make the copy shorter so it adjusts to the required space and 2. it is easier for users to scan.

**Comment by mmmavis** [comment]
@taisdesouzalessa Can you link me to the Thank You page this ticket refers to?

**Comment by taisdesouzalessa** [comment]
@mmmavis this should apply to all "thank you" pages that ask for newsletter sign up: header of the site, footer of the site and all pages that have our newsletter widget such as "https://foundation.mozilla.org/en/initiatives/open-leadership-events/" - please let me know if you run into any issues as implementing this copy since it is a longer copy than the one we currently have.

**Comment by mmmavis** [comment]
This wasn't the troublesome ticket I thought it was. Changing estimate from 3 to 1.

**Comment by mmmavis** [comment]
PR has been merged!
