### ISSUE TITLE
IA: Report on key stakeholders interviews Part I

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4156]
Create a report and add a summary from each stakeholder interview done in #4112.

**Comment by taisdesouzalessa** [comment]
I will share the insights I had while doing the interviews so the findings can inform Rebecca in her work. As I interview more people, I'll add to those insights and flag if any of them completely changes after interviewing a bigger sample.
[
Insights and Preliminary Recommendations](https://docs.google.com/document/d/1WQgoBs-nUPHiVJwGLhdSr0G6OiYXVHyOe65-d8sXkXg/edit?usp=sharing)

[Card Sorting Activity Results](https://docs.google.com/spreadsheets/d/1iTsvrwzelJuIj0p-3QRT83bRnFKj_qmWp0DRjQrRAyI/edit?usp=sharing): very small sample, only 3 people at the moment

@sabrinang please add any feedback you may have there
@kristinashu @beccaklam it is open for feedback/comments too 

those will inform the next iteration of the report as I expand it

**Comment by kristinashu** [comment]
Super amazing and interesting work Tais! Looking forward to talking through all of it at our IA stand tomorrow!

**Comment by taisdesouzalessa** [comment]
I will keep this issue open so I can keep analyzing the qualitative data as they come. 

### For the final list of recommendations and action items, we should use the Research Report #4201

**Comment by kristinashu** [comment]
This ticket is now only for the first round of interviews. Next sprint please use this ticket - IA: Report on key stakeholders interviews Part II #4229 for the rest of the interviews.

@taisdesouzalessa please close this ticket once you've reported on your final interview this week!

**Comment by taisdesouzalessa** [comment]
I'll close this ticket and add all the insights on the Part II. Since we had many interviews this week + Thimble A/B project, I didn't have the time to think through the data and do the analysis. Next sprint will be focused on that, together with remaining interviews.
