### ISSUE TITLE
[Thimble] Analytics clean up

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4157]
### Issue:
Thimble is bringing lots of traffic to our page. See the chart at the end of the [Brainstorm Doc](https://docs.google.com/document/d/1BeqcElSoPRctQqg6PeIRafk6r8txnAe6aJLnx4EaCdA/edit?usp=sharing), "Update" section. The issue we are having is that this is skewing our Foundation site GA data. After discussion with Gideon we thought that maybe we can have other alternatives to handle this traffic.
**Option 1:** to create a separate page for Thimble in a way that doesn't affect our Foundation site analytics. This solution would generate cleaner data for Foundation site.
**Option 2:** exclude this page/related pages from our GA reports. However, this makes our reporting a little more complicated because we have to constantly use filters to remove the Thimble noise.

Any other ideas, ways to solve this problem are welcomed.

@anilkanji @gideonthomas @cadecairos @kristinashu

**Comment by gideonthomas** [comment]
@xmatthewx deferring to you on this one -- I'm going to take a step back.

**Comment by xmatthewx** [comment]
While this is a legacy project, it is still relevant traffic. The foundation's audience will always include a mix of people from past, present, and future initiatives. It's not viable, nor desirable to remove all of this. Our success will always depend on our ability to see our full audience and direct them to engage with our current strategy.  We can easily set up a segment so we can filter the traffic for research, but we should not remove it from our top level reporting. 

While Thimble traffic is a little noisy right now, over time the traffic will naturally diminish. Ideally, it will settle to a natural, long tail source of new audiences. 

We can discuss this further in person. For now, I'm going to close this.
