### ISSUE TITLE
Update body, body-link/cta-link and btn label font size

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#4158]
Update body, body-link, cta-link and btn labels to be a bit larger on desktop so it is easier to read.

**To update:**
- body was 16/24 and updated to 18/27 / dark mode too
- button labels was 16/20 and updated to 18/22 / dark mode too
- body-links and cta-link was 16/24 and updated to 18/27 / dark mode too
________________________
- See design ticket: MozillaFoundation/Design#429
- Sketch library type styles have been updated and merged in Abstract

**Comment by mmmavis** [comment]
Reminder for Mavis:

- [ ] update things on foundation site and pulse
- [ ] update `.body-small` and `.h6-heading` colours to `$gray-60` on Pulse as I forgot to do it last time

**Comment by mmmavis** [comment]
Done!
