### ISSUE TITLE
Deleting a user returns a 5xx

### ISSUE THREAD

**Issue by patjouk** [mozilla/foundation.mozilla.org#4171]
I tried to delete an account on the foundation site and got this error:

```
IntegrityError

update or delete on table "auth_user" violates foreign key constraint "core_sitepermission_user_id_0a3cbb11_fk_auth_user_id" on table "core_sitepermission"
DETAIL:  Key (id)=(52) is still referenced from table "core_sitepermission".
```

Sentry: https://sentry.prod.mozaws.net/share/issue/a7f799553d1c4e28bfbaf926ed1d4264/

**Comment by Pomax** [comment]
Is this when trying to delete a user through the wagtail CMS `settings` -> `users` option?

**Comment by patjouk** [comment]
Yes

**Comment by Pomax** [comment]
blocked until https://github.com/mozilla/foundation.mozilla.org/issues/4269 is resolved.

**Comment by Pomax** [comment]
https://github.com/python-social-auth/social-app-django/issues/242

**Comment by Pomax** [comment]
blocked by https://github.com/mozilla/foundation.mozilla.org/issues/4341 because it turns out it's legacy tables preventing things from working, thanks to foreign key indexing. Yay!

**Comment by Pomax** [comment]
Tables that are on prod but not actually supposed to be there:
```
conf_setting
core_sitepermission
core_sitepermission_sites
django_comment_flags
django_comments
features_feature
forms_field
forms_fieldentry
forms_form
forms_formentry
generic_assignedkeyword
generic_keyword
generic_rating
generic_threadedcomment
homepage_homepage
homepage_homepagehighlights
homepage_homepageleaders
homepage_homepagenews
issues_issue
landingpage_landingpage
landingpage_signup
opportunities_opportunity
pages_link
pages_page
pages_richtextpage
tags_tag
```

**Comment by Pomax** [comment]
DBs have been cleaned up!
