### ISSUE TITLE
MozFest footer: hide country/language dropdowns until user clicks into the field

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4174]
Based on https://github.com/mozilla/foundation.mozilla.org/issues/4130

Please update the footer on the MozFest site so the country/language is closed until a user clicks into the field.

Problem: currently the MozFest site has the country/language picks open 
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/1068783/72292715-ce799680-3606-11ea-8f8c-d64fe745ef9b.png">
but they should be hidden until a user clicks into the form, like on fo'mo
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/1068783/72292747-e224fd00-3606-11ea-8bec-bbb7777403bd.png">

**Comment by Pomax** [comment]
@kristinashu this feels like independent work, given that the footer is a different template. Are you sure this is blocked?

**Comment by kristinashu** [comment]
Not sure how this happened but it seems like the `Keep me updated` CTA button in the main nav https://mozillafestival.org/ uses the drop downs as a page anchor to the form in the footer. So I think we need to first be able to link to a /newsletter page instead of the footer before we remove the ability to link down to the footer. Super hacky!

**Comment by Pomax** [comment]
I had a look at why, and it looks like our join-us component is generating with `id` attributes, rather than classes, so there are multiple elements with the same id, leading to problematic page behaviour. I've filed https://github.com/mozilla/foundation.mozilla.org/issues/4200 to see if we can't fix that.

**Comment by mmmavis** [comment]
I have a newsletter related PR underway that might ultimately fix the issue here. Assigning myself this ticket so I can update this issue once my PR is ready.

**Comment by mmmavis** [comment]
This was caused by something that's not `id` related. My PR #4202 should fix this.

**Comment by mmmavis** [comment]
Fixed!
