### ISSUE TITLE
GA Event stopped working for Opinion submitted in buyer's guide

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#4182]
**Describe the bug**

Last year, we gathered stats on when users submitted an opinion about a product in the buyers guide. It seems like we lost the trigger on Nov 13th or 14th. 

**Expected behavior**

These stats help us know whether our marketing and UX work is increasing or decreasing user engagement. 

**Screenshots**

[Analytics here](https://analytics.google.com/analytics/web/#/report/content-event-events/a87658599w138395144p142716704/_u.date00=20190101&_u.date01=20200209&explorer-graphOptions.selected=analytics.nthMonth&_r.drilldown=analytics.eventCategory:Product,analytics.eventAction:Opinion%20Submitted&explorer-table.plotKeys=%5B%5D)

<img width="521" alt="image" src="https://user-images.githubusercontent.com/53411/74194005-6da1a600-4c26-11ea-8b40-28895c2e4669.png">

**Comment by mmmavis** [comment]
Looks like the code for initiating all GA tracking on product page was removed (probably accidentally) in mid November last year 😬
