### ISSUE TITLE
Set up simple A/B testing

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4183]
### Background:
In order for us to do more A/B testing in our future pages, we should learn more about how the process work on Wagtail.

### Idea:
Do A/B testing with different types of messaging/quick layout changes 

### Project:
**Learning part**
~~- [ ] learn more about A/B testing on Wagtail by [reading the documentation](https://github.com/torchbox/wagtail-experiments#usage)~~
~~- [ ] implement a quick A/B testing with some draft pages to test if mechanism is working~~
UPDATE: we will launch the new version replacing the older version. Then measure and compare. Not a perfect system but we currently can't do a proper A/B testing on Wagtail for now.

**Implementing part**
- [x] analyze the chosen page using the LIFT model 
- [x] create hypotheses that may improve conversion
- [x] create drafts based on the hypotheses
- [x] present them to Matthew and design team
- [ ] launch A/B testing on Wagtail
- [ ] measure results (use a Data Studio board to track them)

cc: @xmatthewx - feel free to edit this ticket

**Comment by Pomax** [comment]
This is probably blocked on https://github.com/mozilla/foundation.mozilla.org/issues/3573#issuecomment-584412130 for now =(

**Comment by taisdesouzalessa** [comment]
Thanks Pomax. I added a "blocked label". Just so I understand what is going on: for what I understood based on the conversation there, this experiments feature (a/b testing on wagtail) only supports up to a certain wagtail version, is that correct? And it also breaks in Django 3?

My question is: if I were to implement this a/b testing today it wouldn't work? Or are you referring to the chance of this feature breaking in the future as we update our version of wagtail and Django?

**Comment by xmatthewx** [comment]
@Pomax - this test of testing will be low risk, not anything critical. So it only needs to mostly work. My hope is that we'll learn a thing or two and can give torchbox feedback to improve the tool. Or, we'll learn that this is not viable and can look for other options.

**Comment by taisdesouzalessa** [comment]
I'll be doing the design part of this project (creating hypotheses and drafts) - if we can't to the A/B testing, we will launch a new version in a couple of weeks and compare with the previous one. Not a perfect system but at least we exercise our testing skills/measurement.

**Comment by taisdesouzalessa** [comment]
Started doing the lift model exercise and putting it in a doc but still need to think more about it. 
The doc is a **work in progress** and I'll keep working on it next week. 
https://docs.google.com/document/d/1AhHPIfrFaRyAsUnuuCih-89RbS1Wdw6VhdV3dJYt46Q/edit?usp=sharing

**Comment by taisdesouzalessa** [comment]
Lift model exercise plus [sketch here](https://docs.google.com/document/d/1AhHPIfrFaRyAsUnuuCih-89RbS1Wdw6VhdV3dJYt46Q/edit?usp=sharing). @xmatthewx let me know if you have any thoughts on that doc (feel free to comment on there) before I move to draft stage. 

**Next step:** design the page in the browser and screenshot it for design + Matthew's feedback.

**Comment by taisdesouzalessa** [comment]
Based on [the strategy](https://docs.google.com/document/d/1AhHPIfrFaRyAsUnuuCih-89RbS1Wdw6VhdV3dJYt46Q/edit?usp=sharing), here is the [Thimble's proposal screenshot](https://mozilla.invisionapp.com/share/AWW3BL4MNTB#/406116722_Screencap_2). The X-Ray Goggles page will follow the same structure so I am seeking to refine Thimble first and then use the same model for the other pages

@xmatthewx please let me know if you have any feedback on it. Copy is not my strength (I wrote the blurb about visiting our initiatives page) so if you could pay special attention to that and do any refinement that would be great. We may also want to consult Gideon since I think he was the one who wrote the original copy.

I'll post on the Slack channel for design feedback.

**Comment by taisdesouzalessa** [comment]
@beccaklam and @xmatthewx based on your feedback, [here is the new version](https://mozilla.invisionapp.com/share/AWW3BL4MNTB#/407078957_Screencapture-Foundation-Mofostaging-Net-Cms-Pages) of this page. 

Please add any feedback in the InVision doc. Thanks!

**Next step:** create a ticket for Nat so she can work on the illustration for this section.

**Comment by xmatthewx** [comment]
Thanks! Looks good. I dropped in a few small comments. Nothing major.

**Comment by taisdesouzalessa** [comment]
Thanks Matthew, I'll do those changes once I have Nat's illustration so I do all of them in one pass. Ticket for Nat here: #4291 - @kristinashu I didn't assign her because I would rather you triage it first to fit into her schedule. Thanks!

**Comment by kristinashu** [comment]
Thanks @taisdesouzalessa! I've put that ticket in our upcoming sprint.

**Comment by taisdesouzalessa** [comment]
@xmatthewx here is the page on staging. Let me know if it is good to go 👍 
https://foundation.mofostaging.net/en/artifacts/thimble/

**Next steps:** after Matthew's revision, build page on production site.

**Comment by xmatthewx** [comment]
Looks great. Let's test it! 

 - Is there any way to remove the extra spacing above and below the line? I think it can be much tighter. 
 - After you run this, let's consider another layout without the wide graphic, bringing the CTA even higher. 
 
I'm curious to see how it performs!

**Comment by taisdesouzalessa** [comment]
Page is launched: https://foundation.mozilla.org/en/artifacts/thimble/
I'll create a report on how the previous experiment went and track it here:  #4384
