### ISSUE TITLE
Javascript Dependency Updates

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#4189]
- [x] Foundation Site
- [x] Donate
- [x] Network pulse
- [x] Network pulse API

**Comment by Pomax** [comment]
Style lint PR blocked on the minimum Node version (it needs 10+, we're still pegged to 8)

**Comment by Pomax** [comment]
**network pulse**: Style lint and SCSS PRs are blocked on minimum Node version (see above)

**Comment by Pomax** [comment]
**foundation* same same
