### ISSUE TITLE
"Join-us" template causes an error in the React component when missing data-form-position

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#4193]
Join us HTML that does not include a `data-form-position` (e.g. mozfest site footer) runs into a JS error when clicking on the email field, as it tries to resolve the `data-form-position` property, can't find it, and then tries to set a classList value on `undefined` rather than on a real element.

Note: we only just discovered this, but it's been broken for _a while_ now, apparently.

(see https://github.com/mozilla/foundation.mozilla.org/pull/4176#pullrequestreview-357044741)

**Comment by gideonthomas** [comment]
This might be the same as this: https://github.com/mozilla/foundation.mozilla.org/issues/4129

cc @mmmavis

**Comment by Pomax** [comment]
It is: closing this one as duplicate

**Comment by mmmavis** [comment]
@Pomax 

> It is: closing this one as duplicate

Are we closing this ticket? 😄

**Comment by mmmavis** [comment]
Fixed!
