### ISSUE TITLE
Docker may fail on npm install citing ENOENT for node_modules/.staging locations

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#4195]
This looks like a bug youri was running into as, well, and has a "solution" that's a bit hacky but apparently the only option:

- remove `./node_modules`
- remove `package-lock.json`
- rerun `npm install`

@cade and I had this work by running `inv docker-new-env` after updating the dockerfile.node to not copy package-lock.json

Then putting it back after docker finishes the run.

(apparently, package-lock is responsible for the error itself, though there's no clear solution involving npm itself yet?)

**Comment by cade** [comment]
I _knew_ you could fix all your problems by relying on `npm`! Though no one has ever accused me of getting anything to work in Docker... 🤔 What about you, @cadecairos?

**Comment by Pomax** [comment]
Closing, even though it's hard not to keep it open.
