### ISSUE TITLE
IA: Benchmarking

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4198]
Based on our research, let's benchmark some IA's that seem relevant. We can also reference this redpen that has a lot of non-profits https://redpen.io/p/fm1aa86db66594fc47.

Please any some to the redpen https://redpen.io/p/hf62c1a6c9ba6c5262 along with a link to the URL and the reason you think that IA is effective.

We can then pull our favs into the deck https://docs.google.com/presentation/d/11CK6yYXx8iCSsTG3Lc89-2k4Eiuy21zMoJIrmG7vjfY/edit#slide=id.g7db523ff79_0_0

**Comment by beccaklam** [comment]
Dropped in some, I'm not sure if all are great examples will come back next week to purge any I don't think are good. But they're pretty large foundations.

**Comment by beccaklam** [comment]
Based on the benchmarks captured in the redpen, I noticed all these websites follow a similar structure:

1. Who We Are (About Us page)
2. What We Do (The key issues they focus on)
3. How We Work (The programs they support)
4. Where We Work (not applicable to us)
5. Sometimes a site will have a section that talks specifically about their Funding or Grants/Investments

**Comment by taisdesouzalessa** [comment]
Added some benchmarks + reasoning on what I liked about them. Also, added benchmarks from Kaili that relates to IA work. Closing!
