### ISSUE TITLE
join-us component uses `id` attributes, which causes problems with a page has more than one

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#4200]
The join-us component uses an `id`, but we also have multiple join-us components on pages (e.g. nav header + site footer) and this is definitely something we want to fix =)

This will probably require changes to the JS and SCSS due to changes in query selectors.

**Comment by cadecairos** [comment]
This might already be fixed @mmmavis to confirm

**Comment by mmmavis** [comment]
Fixed as part of PR https://github.com/mozilla/foundation.mozilla.org/pull/4348 .

Closing! 🎉
