### ISSUE TITLE
Create Combined Research Report from Foundation Site Analytics and Audience Research

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#4201]
Ticket to track work that @taisdesouzalessa and I are doing to combine our research into a joint report for our IA work.

**Related tickets:**
IA: Current analytics & metrics #4113
IA: audit current site #4110
IA: Report on key stakeholders interviews #4156 

👉 [Link to the joint Research Report ](https://docs.google.com/document/d/1WiImBFgOuNgwf_KVMsowPVX6Bi0gnipqdREtOjZ_2DA/edit?usp=sharing) 🤓 

cc: @kristinashu

**Comment by kristinashu** [comment]
This report is amazing and has turned a new leaf on design at mofo! 

@beccaklam will add one small note to this and then it's good to close!

**Comment by beccaklam** [comment]
Added the note on usage of the "Latest News" section. Will close this now. @taisdesouzalessa feel free to reopen if you need to!
