### ISSUE TITLE
QA > Inconsistent Date formatting

### ISSUE THREAD

**Issue by flukeout** [mozilla/foundation.mozilla.org#423]
On news page articles have date in this format...

![image](https://cloud.githubusercontent.com/assets/25212/26078391/446290c8-3974-11e7-91e7-fe2805828712.png)

On projects...

![image](https://cloud.githubusercontent.com/assets/25212/26078406/4f514740-3974-11e7-85a1-a5ea402d7358.png)

``Apr`` vs ``April`` and one has the year, one doesn't

**Comment by flukeout** [comment]
Also on Upcoming page we have some all caps months...

![image](https://cloud.githubusercontent.com/assets/25212/26078477/8d99d0d0-3974-11e7-8769-c3f966008de2.png)

**Comment by hannahkane** [comment]
estimate is design decision only

**Comment by kristinashu** [comment]
Fixing this in our new library.
