### ISSUE TITLE
Create a campaign index subclass of the IndexPage

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#4234]
Depends on #4233 

With the previous two pieces of work in place, we should duplicate the BlogIndex but then tailored for Campaign pages. This should effectively be a copy-paste job with some string replacements.

**Comment by gabbyprecious** [comment]
Hello, can I claim this as a first contribution

**Comment by Pomax** [comment]
Hi @gabbyprecious, we don't really have any good introductory bugs for contributors to work on for the foundation website, so as much as the gesture is appreciated, we'll be working on this internally.
