### ISSUE TITLE
QA > No "active" state on Get Involved button

### ISSUE THREAD

**Issue by flukeout** [mozilla/foundation.mozilla.org#424]
Feels like we should have one, it's the most prominent button maybe. Other buttons have it.

![image](https://cloud.githubusercontent.com/assets/25212/26079528/efb234e4-3977-11e7-9697-6ade9690ff2c.png)

**Comment by xmatthewx** [comment]
wanna take this @flukeout? for kicks? i also think it could start a little lower and not stretch so high.

**Comment by sabrinang** [comment]
The button can compress a few pixels (perhaps 4px) for its active state

**Comment by kristinashu** [comment]
I think this is done.

**Comment by xmatthewx** [comment]
No, it's still the same. When you hover, button rises. When you click, nothing happens. Feels weird.

**Comment by kristinashu** [comment]
Closing since we will be update this button style.

**Comment by flukeout** [comment]
Oh, fine!!
