### ISSUE TITLE
MozFest: site design updates

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4243]
MozFest team will be making a bunch of content updates and design will help guide the layout of the site. 

### To do
- Mockup homepage with this [WIP content structure](https://docs.google.com/document/d/1Ld-kGSjY3mW0n7eRR-DV9vPImWj1KClPPXzK-8VjUnU/edit) 
- Provide guidelines and suggestions for content
- Find ways to make the site more visually impactful! 
- Will require some back-and-forth between design and copy
- In the meantime, @sabrinang will be working on the Style Guide https://github.com/MozillaFoundation/Design/issues/475 and graphic for city announcement https://github.com/MozillaFoundation/Design/issues/480 which will guide the look of the graphics for the site

### Site changes of note
- Add signup snippet on the right side of page (this is currently possible but the rest of the page might need some styling tweaks to make it look less busy) (see staging https://mozillafestival.mofostaging.net/)
- Main nav will only have two items so we'll need to remove the CTA button - https://github.com/mozilla/foundation.mozilla.org/issues/4249
- Remove Twitter feed and News component
- Might be localized to Dutch 
- Note: [overview of all future website changes](https://docs.google.com/spreadsheets/d/17x3XssyUQpS5gyAVMVIyZCbIrAIZpC6QODVbbz1HbzQ/edit#gid=0)

If any dev work is need it can be added to this ticket https://github.com/mozilla/foundation.mozilla.org/issues/4242.

cc @marcwalsh @mmmavis

**Comment by beccaklam** [comment]
Wants:
- video background
- flashy homepage
- but keep in mind that there multiple changes through out the year: ticket sales, speaker announcements, etc
- MozFest has great photos
- Draft by Tues and get design feedback, show Mavis/Mark Wed to get feedback, Thurs: revise and get feedback again, Friday: final

**Comment by beccaklam** [comment]
First pass at designs in this redpen: https://redpen.io/p/rhbb6e67da007091f2
I'm struggling with this, can I get some feedback? Am trying to make it more 'visually interesting' per the MozFest Team's request but also simple enough for Mavis to build in a week ...

@kristinashu @sabrinang @natalieworth

**Comment by beccaklam** [comment]
So, going off feedback that most of our dev resourcing will go into making a large, video background with maybe some parallax effects, I've laid out the rest of the content using our CMS to keep it simple: https://mozillafestival.mofostaging.net/en/

@kristinashu Can I get some feedback if this is along the right lines of what you were thinking? If so, would my next steps be:
1. Schedule meeting with Mavis to discuss video background + light parallax scroll, as well as removing certain nav items?

2. Set up meeting wit Mark to go over content and layout?

**Comment by kristinashu** [comment]
Thank you all for the quick check-in! Recap of next steps:
- Rebecca update comps with the fancy video top section and simpler wagtail content below
- Share comps with Marc and the mozfest team tomorrow for feedback
- Finalize comps and open dev tickets for Mavis on Friday
- Mavis to start dev on Monday and push to staging early Thursday
- Need to confirm actual launch date with Marc

**Comment by beccaklam** [comment]
Oops forgot to update this ticket yesterday with the latest comps: https://redpen.io/p/rhbb6e67da007091f2

**Comment by beccaklam** [comment]
Updated comps based on feedback from Marc and other designers: https://redpen.io/p/rhbb6e67da007091f2 Waiting for sign off now from Bob and Sarah!

**Comment by kristinashu** [comment]
All the devs tickets are coming along nicely here https://github.com/mozilla/foundation.mozilla.org/issues/4242

@marcwalsh any remaining feedback? If not then @beccaklam, I think this is good to close!
