### ISSUE TITLE
IA: revise IA based on data & interviews

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4244]
Follow up from - IA: Initial draft based on data #4177

**Comment by beccaklam** [comment]
First revised draft here: https://redpen.io/pod54f5e39e4f119a3
cc: @kristinashu @taisdesouzalessa Feedback would be welcomed and appreciated! I'll start adding in more detail too (more third level pages) but here's an initial draft for y'all to look at.

Also, a lot of the recommendations from Tais' staff interviews requires content changes that won't necessarily be reflected in the IA. How should we go about showing these changes? Do we need to in the IA work?

**Comment by kristinashu** [comment]
Nice! Let's discuss at stand tomorrow.

**Comment by beccaklam** [comment]
"Final" revised draft here: https://redpen.io/uwd60d265a2ffbe381 Will start collecting feedback from engagement, content and comms teams. Closing this ticket!
