### ISSUE TITLE
JS bundle contains eval()

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#4245]
The JS bundle now contains multiple `eval()`, probably added by the a11y build
cc @Pomax @mmmavis 

<img width="1050" alt="Capture d’écran 2020-02-22 à 11 04 35" src="https://user-images.githubusercontent.com/1294206/75090488-ae24ec00-5563-11ea-94c5-eb43d6c8d51f.png">

**Comment by Pomax** [comment]
this got fixed by https://github.com/mozilla/foundation.mozilla.org/commit/b42bfd8b34b3aef443faa5bb7b25b8d90cf6fc7e
