### ISSUE TITLE
MozFest: Localized custom Sign Up header/description don’t fallback to English

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#4257]
Text is coming from this snippet: https://foundation.mozilla.org/cms/snippets/wagtailpages/signup/25/

It’s not currently localized, and the localized pages don’t fall back to the English copy as they should.

English page, sign up form in footer:

![Screenshot_2020-02-25 Mozilla Festival](https://user-images.githubusercontent.com/1294206/75260759-5f3cb800-57ea-11ea-93b6-2122f68af01a.png)

French page, sign up form in footer:
![Screenshot_2020-02-25 Mozilla Festival(1)](https://user-images.githubusercontent.com/1294206/75260767-62d03f00-57ea-11ea-8a50-d891ad0544fa.png)

cc @marcwalsh

**Comment by marcwalsh** [comment]
Thanks @TheoChevalier 

I also tried just adding the English version of the snippet into the localised fields, but it is still not displaying.
