### ISSUE TITLE
QA > Line up Menu Icon with X more consistently.

### ISSUE THREAD

**Issue by flukeout** [mozilla/foundation.mozilla.org#426]
It's pretty close, and would be nice if I could always just close the menu by clicking right where I clicked to open it. I feel like WE HAVE THE TECHNOLOGY

![_xicon](https://cloud.githubusercontent.com/assets/25212/26079851/14617ec0-3979-11e7-9646-f55a998d5ebc.gif)

**Comment by hannahkane** [comment]
discussion during backlog grooming: going to file a ticket for allowing users to use Esc key to dismiss the menu <- prioritizing that fix for accessibility reasons

The design aspect of this ticket will be backlogged for now.

**Comment by gvn** [comment]
I don't think this is an issue anymore with the new nav. @flukeout want to close this?
