### ISSUE TITLE
MozFest site: video background

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#4264]
The MozFest site design updates have been finalized in #4243. The main changes will be a video background header with minimal text and a pause button for accessibility purposes. Other smaller updates can be done in https://github.com/mozilla/foundation.mozilla.org/issues/4242. 

cc: @kristinashu 

## List of Requirements
- [ ] Create video background
- [ ] Text on video background should be limited to one line, and preferable up to only 8 columns on desktop/tablet, can be 10 column on mobile
- [ ] Text should be localizable
- [ ] Include pause button, assets here: [pause-circle-assets.zip](https://github.com/mozilla/foundation.mozilla.org/files/4295257/pause-circle-assets.zip)
- [ ] Include play button when video is paused, assets here: [play-circle-assets.zip](https://github.com/mozilla/foundation.mozilla.org/files/4295258/play-circle-assets.zip)

---

**🗒  Design -> Dev Handoff Checklist**
(Feel free to remove items that are not applicable.)

- [x] Design has been finalized
- [x] Link to original design ticket: #4243
- [x] Link to related ticket: #4242
- [x] Link to Redpen: https://redpen.io/p/rhbb6e67da007091f2
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Assets are included
- [x] Hover state for elements are designed

## Desktop
![mozilla-festival v3@1 5x](https://user-images.githubusercontent.com/20977376/76027871-660cae80-5eff-11ea-96ea-713e94eb8e27.jpg)

## Hover State
![mozilla-festival-hover-v3@1 5x](https://user-images.githubusercontent.com/20977376/76027893-6c9b2600-5eff-11ea-97df-a1442179d282.jpg)

## Play Button (when video is paused)
![Group 13](https://user-images.githubusercontent.com/20977376/76027898-71f87080-5eff-11ea-8a5a-4e2823643000.jpg)

## Play Button Hover State
![Group 11](https://user-images.githubusercontent.com/20977376/76027909-7886e800-5eff-11ea-80b3-d77715dc1e3f.jpg)

## Mobile
![mozilla-festival  M  Copy 2@2x](https://user-images.githubusercontent.com/20977376/76027919-7cb30580-5eff-11ea-9f03-bdc4696061f5.jpg)

**Comment by kristinashu** [comment]
Let's coordinate to find a placeholder video Mavis can use while we make the actual video in https://github.com/MozillaFoundation/Design/issues/482.

**Comment by mmmavis** [comment]
@cadecairos will s3 be a good place to host the video file?

**Comment by cadecairos** [comment]
Yeah, in the MoFo-assets bucket so we can use the CDN

**Comment by mmmavis** [comment]
@cadecairos I haven't touched S3 bucket for years. Is it still basically as simple as dropping the file in and grabbing the shareable URL for our site to use?

**Comment by cadecairos** [comment]
Sort of - you upload the file, and should be able to access it via `https://assets.mofoprod.net/{PATH_TO_OBJ_IN_BUCKET}`

**Comment by cadecairos** [comment]
Do you have an active AWS account?

**Comment by mmmavis** [comment]
@cadecairos thanks for the help! I was able to create a new directory `foundation`, a child directory `video` under it, and drop the video file there.

@beccaklam wondering what we wanna do to the `PAUSE` button when the video is already paused?
