### ISSUE TITLE
Overcrawling by Bingbot

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#4283]
A lot of the the traffic we're seeing to the Thimble artifact page is coming from Microsofts Bingbot web crawler (verified with their [Bingbot IP verifier tool](https://www.bing.com/toolbox/verify-bingbot-verdict))

We should be able to stop this with a robots.txt file. 

docs: https://www.bing.com/webmaster/help/how-to-report-an-issue-with-bingbot-25c19802

**Comment by Pomax** [comment]
♫～amazing～♬

**Comment by cadecairos** [comment]
I landed a fix for mofo-redirector that responds to bot requests for robots.txt, and [instructs them to stop crawling](https://github.com/mozilla/mofo-redirector/blob/643b62d310594a16a2d14bb093172bf175b821bf/app.py#L41-L45)
