### ISSUE TITLE
Update Site / Page Title of MozFest Website

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/foundation.mozilla.org#4284]
Currently all page titles start with `Mozilla Festival 2019 -`

As part of the city announcement updates are we able to remove 2019 so page titles start with just `Mozilla Festival -`

**Comment by kristinashu** [comment]
@mmmavis so just to clarify, we don't want to mention a year.

**Comment by imskr** [comment]
Can I work on this?

**Comment by mmmavis** [comment]
Hi @imskr , thanks for offering help 😃 . This ticket is part of the bulk tasks I'm currently working on and I have a fix underway already. Our dev team is quite small now so we don't have the capacity to help contributors get started with the project. If you are familiar with this codebase and would like to contribute your awesome code, I encourage you to look for tickets that have no assignees and are labelled with "enhancement".

**Comment by mmmavis** [comment]
PR merged. Fix will be live today.
