### ISSUE TITLE
Audit object queries and make sure they are language-aware

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#4285]
A follow-up for PR https://github.com/mozilla/foundation.mozilla.org/pull/4266/files

To catch and fix bugs like https://github.com/mozilla/foundation.mozilla.org/issues/4257, we should audit object queries and make sure they are specified language-aware where necessary.

Relevant doc: https://django-modeltranslation.readthedocs.io/en/latest/usage.html#multilingual-manager

**Comment by cadecairos** [comment]
let's revisit this if it becomes a problem
