### ISSUE TITLE
QA > Logo by Karolina is very hard to read...

### ISSUE THREAD

**Issue by flukeout** [mozilla/foundation.mozilla.org#429]
Consider using just the block maybe?

![image](https://cloud.githubusercontent.com/assets/25212/26080251/881fbdc6-397a-11e7-9d53-6ecf5420eb1f.png)

**Comment by xmatthewx** [comment]
We can fix this. And logos will be added by program staff for a growing circle of network people. We won't be able to ensure perfect quality.

**Comment by taisdesouzalessa** [comment]
For this specific case we could use just the symbol (no copy), as they have in [their website](https://www.ifla.org/):
<img width="272" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/26219532/3221ef42-3bc4-11e7-8dd2-20f8392cbd0b.png">
