### ISSUE TITLE
Illustration for CTA (part of A/B testing to better understand our users' motivations to click).

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4291]
Related to this ticket: #4183

### Deliverable:
Illustration to replace the one marked as "Placeholder" on this mockup:
https://mozilla.invisionapp.com/share/AWW3BL4MNTB#/407078957_Screencapture-Foundation-Mofostaging-Net-Cms-Pages

### Goal of the illustration:
To inspire Thimble's page visitors to check out our initiative page, where they can find other ways to get involved with the Foundation.

**Comment by natalieworth** [comment]
I made this version [here in Redpen](https://redpen.io/p/fv667a0bdc180d658d) @taisdesouzalessa Let me know if this is what you're thinking! :)

Final [file is here.](https://drive.google.com/open?id=1ml4m300y4kdbgV3qXNOjs6o9Z907urQT)

**Comment by taisdesouzalessa** [comment]
Great! Thanks Nat :). I used your beautiful illustration on the page and it is in staging here: https://foundation.mofostaging.net/en/artifacts/thimble/ - just submitting to Matthew for approval and we may be good to go. I will leave this ticket open until I get his feedback.

**Comment by kristinashu** [comment]
Illustration looks so good! cc @sabrinang since I think she'll be happy to see another use of this illustration style on the site lol!
