### ISSUE TITLE
MozFest: Link to blog is broken

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4295]
From @marcwalsh's ticket - MozFest: 'More From Our Blog' button linking to Festival domain instead of Foundation domain #4256

On the [/newsletter page](https://www.mozillafestival.org) on the MozFest website, using the Blog Entries block in wagtail adds a 'More From Our Blog' button. 

This button just links to [/blog/category/mozilla-festival/](https://www.mozillafestival.org/blog/category/mozilla-festival/) which isn't available under the Mozilla Festival domain so it 404s.

It should be directing to https://foundation.mozilla.org/blog/category/mozilla-festival/

cc @Pomax @mmmavis

**Comment by xmatthewx** [comment]
I found a roll of duct tape and added a redirect from `/blog/category/mozilla-festival` on the festival domain to right place on the foundation site. 

@kristinashu - please test and confirm that it works as expected. 

Note: this fixes the bug for launch. But, we should still fix the component or change how authors add this button.

**Comment by kristinashu** [comment]
Thanks for the quick fix @xmatthewx!

**Comment by Pomax** [comment]
I did some investigation: if we want to fix this, we will need to ad `sites` awareness to our blog component, so that it can check which site managed by wagtail supports the `/blog` route, and then letting the user pick which site to use for the purpose of blog cards (if there's more than one)

**Comment by kristinashu** [comment]
Ok thanks for looking into this. I think we should close this as "won't fix". It's an edge case and the fix seems like it could cause more problems and make things harder for everyone else using the component. 

Please feel free to re-open if you think it's important.
