### ISSUE TITLE
Fetch Fluent files

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#4297]
This is a piece of work needed for https://github.com/mozilla/foundation.mozilla.org/pull/4181 — feel free to push directly on the `fluent-react` branch

Tasks needed:
- Remove the localized .ftl files form the repo (I included them in the PR for testing/review purposes, actual .ftl files will be stored on  https://github.com/mozilla-l10n/fomo-l10n. The only exception being the English file, that one stays in the repo.
- in l10n.js, don’t import individual files at build time, but use `fetch()` from the client to get the file matching `getCurrentLocale()` instead
- The code must take into account that a requested file might not exist. No need to worry about Fluent, it will gracefully fall back to English, let’s just not fail on fetch().
- Move the PNI strings to a separate .ftl file. When accessing PNI, `getBundles()` will need to add both resource to the bundle.

@Pomax Is that okay if I assign this one to you? I’ve looked into it, but I definitely don’t understand how to correctly handle code with promises 🤷‍♂️

**Comment by jamilasnell** [comment]
This was a thing but not a thing anymore.
