### ISSUE TITLE
IA: finalize report

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4301]
Based on - IA: Report on key stakeholders interviews Part II #4229 

Finalize and consolidate the report. Once it is ready we will share out the report in https://github.com/mozilla/foundation.mozilla.org/issues/4302

**Comment by taisdesouzalessa** [comment]
Checklist from #4229
- [ ] Compile a simple report based on the lastest round of interviews
- [ ] Share report out with engagement team
- [ ] Share report out with key stakeholders. IMPORTANT: Checklist before sharing with broader audience
- [ ] Review IA brief to make sure content still holds true

**Comment by taisdesouzalessa** [comment]
Here is the link for the report: 

**[Report - Stakeholders Interviews + Analytics v 1.0](https://docs.google.com/document/d/16GilewBBqr-sDknD9MroVy4QHR3TmWl4Q_2kGXFDg4A/edit?usp=sharing)** →

@beccaklam please let me know if anything is missing from the Analytics standpoint and any feedback is welcome!
@kristinashu @sabrinang @natalieworth please provide feedback too

**Comment by taisdesouzalessa** [comment]
Report was improved based on staff feedback. @beccaklam also included the card sorting analysis. 
Next steps: add Bob's insights after her interview on Monday + prepare presentation to interviewees. This work will be tracked on this ticket: #4383
