### ISSUE TITLE
Grants page feedback

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4303]
Follow up on - Grants page layout proposal #4139

- [x] Rebecca to write out rational for the page (goals, reasons for the decisions...)
- [ ] Recommendations on were the page should live
- [ ] Get feedback from designers
- [ ] Rebecca and Kristina to meet with J Bob to share the pages and get some feedback

---

From - Grants page layout proposal #4139

[Request from Mark](https://docs.google.com/document/d/1HcKBVO85Lv8C2TX7-tq99mdzULQxw0oT-xfE5ytUqfE/edit).

**Create a simple Mozilla Grants foundation page that is holistic and historical.** 

Should consider:
- Fellowships
- Awards
- MOSS
- Mozilla Research Grants

(clarify which are still active and available to seek funding and which are not)
(point to a list of things we’ve supported where they exist and are current)

### To be done later
- Talk to stakeholders (Anil, Mark, Bob, Lotta)
  - Interview
  - Write brief
  - Get feedback on comp
- Update design
- Finalize content
- Create page in Wagtail
- Delete www.mozilla.org/grants/ and redirect to this new page

cc @TheoChevalier

**Comment by beccaklam** [comment]
[Link to rationales](https://docs.google.com/document/d/1lEBQRk8nyagoJpH084VgoZ_ahaSVBKZDRGRbKTNwaW4/edit?usp=sharing) for designs

**Comment by kristinashu** [comment]
Excellent rational! I left a couple of notes but then I think we should share this with Matthew and Anil and then set something up with Bob.

**Comment by beccaklam** [comment]
@kristinashu added your recommendations: [amended doc here](https://docs.google.com/document/d/1lEBQRk8nyagoJpH084VgoZ_ahaSVBKZDRGRbKTNwaW4/edit?usp=sharing)

Would you like me to share with Matthew and Anil?

**Comment by kristinashu** [comment]
This has been shared with Matthew and Anil and I've opened a ticket for next sprint https://github.com/mozilla/foundation.mozilla.org/issues/4386.

@beccaklam can you just share this with the rest of the designs in Slack and then I think it's good to close!

**Comment by beccaklam** [comment]
Thanks @kristinashu ! Designs have been shared in slack so closing this for now. Anyone feel free to reopen if you need to add any feedback/comments.
