### ISSUE TITLE
IA: summary of card sorting exercise

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4306]
Follow up on - IA: Report on key stakeholders interviews Part II #4229

**Comment by taisdesouzalessa** [comment]
**Important:** as we review the results of this work, include analytics from [this report](https://docs.google.com/document/d/1WiImBFgOuNgwf_KVMsowPVX6Bi0gnipqdREtOjZ_2DA/edit?usp=sharing) (**items 3, 5 and 6**). Also consider sharing highlights/find commonalities with the report #4301

**Comment by beccaklam** [comment]
Excel card sorting analysis sheet [here](https://docs.google.com/spreadsheets/d/1aoz7D_2P-SdUPLSqq0Db3DCF3IWcgM-Cm1cM-lbkC7o/edit?usp=sharing).
Card sorting report started [here](https://docs.google.com/document/d/1AuSpwdK-0OJXdGJdCu-DupJJY1g_YJ7WwuMUrOIWXhU/edit?usp=sharing).
cc: @taisdesouzalessa @kristinashu

**Comment by beccaklam** [comment]
@taisdesouzalessa I dropped in some insights into both reports that you mentioned above. I didn't have a whole lot to add, only two to three points per report. Like I mentioned to you before, I think the card sorting analysis will become more useful once we start drafting the IA. I'm going to close this ticket for now but please feel free to reopen if you see the need to!
