### ISSUE TITLE
Language in the CMS changes

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4308]
**Describe the bug**
Updating the language on the site's footer also updates the language in the cms. However, @Pomax does not have this issue.

**To Reproduce**
1. Go to https://foundation.mozilla.org/en/
2. Click on language dropped in the footer and select Deutsch, url is now https://foundation.mozilla.org/de/
3. In the url, replace `de` with `cms`
4. See error: CMS is now in Deutsh

**Expected behavior**
I'm not actually sure.

**Screenshots**
![image](https://user-images.githubusercontent.com/1068783/76039442-4bd3d000-5f01-11ea-8de4-516384926691.png)

**Desktop:**
 - OS 10.15.3
 - Browser FF
 - Version 73.0.1

**Comment by Pomax** [comment]
As a data point, when I click "Deutsch", the URL does not change for me on Windows in either Firefox or Chrome.

**Comment by TheoChevalier** [comment]
I’m playing very often with the lang switcher, and I never managed to reproduce this bug. But I remember it happened in the past. I wonder if this could be a plain Wagtail bug, not a bug in our code?

Some details:

**CMS locale:**
- stored in the user profile https://github.com/wagtail/wagtail/blob/6ce9f3a717abd3cb7a9ae35364ae274f141c267b/wagtail/admin/auth.py#L160
- Endpoint `https://foundation.mozilla.org/cms/account/language_preferences/`

**Site locale:**
- Stored in the `django_locale` cookie
- Endpoint `https://foundation.mozilla.org/i18n/setlang/`

Managing CMS language preferences: https://foundation.mozilla.org/cms/account/language_preferences/

**Comment by kristinashu** [comment]
@TheoChevalier do you still notice this? I think we can maybe close this ticket.

**Comment by TheoChevalier** [comment]
I think it’s safe to close yes, we can always open a new ticket if staff keep hitting this.
