### ISSUE TITLE
MozFest Homepage - controls for embedded banner video

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#4310]
Currently, we have pause/play button in the banner area as the only video controls.
<img width="309" alt="image" src="https://user-images.githubusercontent.com/2896608/76124653-06baa700-5fb0-11ea-81ff-92aa70e7e707.png">

[Suggestion](https://github.com/mozilla/foundation.mozilla.org/pull/4296#issuecomment-595508470) from @Pomax 

> Is it possible to make the video pause by clicking anywhere on the banner, rather than just the pause button?

**Comment by kristinashu** [comment]
I think this would be very problematic on mobile.
