### ISSUE TITLE
Support ISO 3166 locale codes

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#4314]
Like on donate-wagtail, it would be great to support `ab-CD` locales to be consistent with the format we support at Mozilla.

I’m going to backport here the fix Torchbox made

**Comment by TheoChevalier** [comment]
Hey @cadecairos, would you mind sharing the current status for this? (Or blocker/next steps?)

**Comment by phildexter** [comment]
Iceboxing this for now but @anilkanji will engage with Theo to prioritise this through appropriate channels.

**Comment by anilkanji** [comment]
@TheoChevalier will join our next sprint planning (7/7) to discuss next steps on this.
