### ISSUE TITLE
QA > Creative Commons licensing should be listed in full

### ISSUE THREAD

**Issue by thornet** [mozilla/foundation.mozilla.org#432]
In the footer where it links to the CC license, it's recommended instead to include it as metadata like this: 

<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />Unless otherwise indicated, this website is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

**Comment by thornet** [comment]
See https://creativecommons.org/choose/results-one?license_code=by&amp;jurisdiction=&amp;version=4.0&amp;lang=en

**Comment by kristinashu** [comment]
Updating this in https://github.com/mozilla/foundation.mozilla.org/issues/1662
