### ISSUE TITLE
Add meta tag to remove staging websites from Google search

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/foundation.mozilla.org#4330]
Update from Gideon:
We've noticed that several staging websites popup at some points in Google searches (donate-wagtail, fo'mo, and pulse).

To fix this, let's add `<meta name="robots" content="noindex">` to all pages unless we're in a production environment.
Alternatively, if it is easier to do this with a header (via CDN or code), we can also just set `X-Robots-Tag: noindex` on those pages.

---

I was searching for different MozFest terms on Google this morning and found that some of the top results for some terms were for mozillafestival.mofostaging.net, which is likely because the production site hasn't been re-crawled yet.

**Comment by kristinashu** [comment]
@gideonthomas @xmatthewx d'you know anything about this?

**Comment by gideonthomas** [comment]
@marcwalsh what terms did you search for?

**Comment by marcwalsh** [comment]
@gideonthomas - this seems to have disappeared now, it was when searching for MozFest 2021 and Mozilla Festival 2021 - but it's now totally gone, even searching for the domain doesn't show results.

**Comment by gideonthomas** [comment]
Hmm, that's odd. But if it does come back, please do let us know @marcwalsh.

@xmatthewx something to consider when generating sitemaps for fo'mo and mozillafestival -- it shouldn't be generated on staging.

**Comment by xmatthewx** [comment]
Strange. Let's definitely reopen this if it reappears. cc @cadecairos @mmmavis just so they're aware in case there's an obvious reason.

**Comment by gideonthomas** [comment]
Reopened as this is occurring for other staging sites as well. I've updated the issue and recommended a fix at the top.

cc @xmatthewx and @marcwalsh
