### ISSUE TITLE
Localize country dropdown

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#4332]
https://github.com/mozilla/foundation.mozilla.org/blob/master/source/js/components/petition/salesforce-country-list.js

We should find a way to localize this using an external library.

Donate uses [django_countries](https://pypi.org/project/django-countries/) successfully, but the list is part of the model

**Comment by Pomax** [comment]
Closing this as stale, given that we've not planned this task in for over two years. If we still want to do this, let's file a new issue and get it added to a sprint

**Comment by mtdenton** [comment]
Echoing the above from Pomax, this will be purged. File a new issue if needed.
