### ISSUE TITLE
replace `manage createsuperuser` with a direct python code call?

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#4362]
Docker on windows is great, but the one last thing that doesn't work is `createsuperuser`, due to TTY requirements that don't really work.

However, this does work, creating an admin/admin account:

```
inv docker-manage "shell -c \"from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'admin')\""
```

Would it make sense to update the tasks so that rather than calling `manage createsuperuser`, we simply directly call the django code that builds a superuser?

/cc @patjouk

**Comment by patjouk** [comment]
Wroks for me!
