### ISSUE TITLE
Localized campaign pages are 404

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#4366]
Only English campaign pages are live, all the other languages are 404.
Examples:

202 ✅ https://foundation.mozilla.org/en/campaigns/
202 ✅ https://foundation.mozilla.org/en/campaigns/youtube-regrets/
202 ✅ https://foundation.mozilla.org/en/campaigns/tell-amazon-require-two-factor-authentication-all-ring-accounts/

404 ❌ https://foundation.mozilla.org/fr/campaigns/
404 ❌ https://foundation.mozilla.org/fr/campaigns/youtube-regrets/
404 ❌ https://foundation.mozilla.org/fr/campaigns/tell-amazon-require-two-factor-authentication-all-ring-accounts/

**Comment by TheoChevalier** [comment]
For some reasons, Dutch and Polish pages are still showing up fine, but French, German, Spanish, Portuguese are all broken

**Comment by TheoChevalier** [comment]
This seem related to https://github.com/mozilla/foundation.mozilla.org/pull/4334 and probably to the commands ran on the DB thereafter.
Localized page titles got moved to the localized slug field for some reason, thus breaking language negociation. @Pomax do you have an idea?

**Comment by patjouk** [comment]
Just as an example, those work: https://foundation.mozilla.org/fr/campagnes/ or https://foundation.mozilla.org/fr/campagnes/youtube-regrets-about/

**Comment by Pomax** [comment]
when I moved the campaign page over to the new campaignindexpage type, apparently wagtail decided to create new slugs for every locale, instead of only `en`. Removing all non-`en` slugs got us back to expected behaviour.
