### ISSUE TITLE
Remove "member notice" code that was built for member preview 2 years ago

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#4369]
@kristinashu We turned off the member preview banner [2 years ago](https://github.com/mozilla/foundation.mozilla.org/issues/794) and never used it again since. Is this type of notice bar something we will use in the near future? If not I'd like to remove the code for good 😄 

### default state

![Screenshot_2020-03-18 Homepage](https://user-images.githubusercontent.com/2896608/77024334-7e42eb80-694b-11ea-8094-75b51ee87bbe.png)

### open state

![Screenshot_2020-03-18 Homepage(1)](https://user-images.githubusercontent.com/2896608/77024333-7daa5500-694b-11ea-82f6-c3fa10737533.png)

**Comment by kristinashu** [comment]
Oh my gosh! Yes, please remove this for good!
