### ISSUE TITLE
Increased body size should be applied everywhere

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4373]
We decided to increase the font size of our body text and it looks like it was applied to regular paragraph text but not all the special cases. For example, bullet point text is too small and should match the rest of the text. See https://foundation.mozilla.org/en/docs/process/ 

<img width="863" alt="image" src="https://user-images.githubusercontent.com/1068783/77092447-116d3700-69c7-11ea-86b8-7b622c582e30.png">

I think the "happening now" cards on our homepage should also have the larger text.
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/1068783/77092930-86d90780-69c7-11ea-845a-a3267f4229e8.png">

cc @sabrinang @mmmavis

**Comment by mmmavis** [comment]
> I think the "happening now" cards on our homepage should also have the larger text.

This is being covered in https://github.com/mozilla/foundation.mozilla.org/pull/4360 

I'll take a look into the list item text sizing issue.
