### ISSUE TITLE
Styles for Print [Blog Pages]

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#4378]
Let's discuss whether it's worth putting in a little work to improve these styles. 

One use case: When program staff put out a report, there's often a desire to create a PDF to share with press and policy people, etc. It'd be great if we could just use the browser to print to PDF instead of having a designer to create a new doc to make that so. 

How big of a lift would it be to get things in better shape? Not perfect, but good enough?

cc @kristinashu @cadecairos @mmmavis

**Comment by mmmavis** [comment]
@xmatthewx I wanna test out how Foundation site currently deals with this. Do you have a link to any existing report on the site that I can play around with the print options?

**Comment by kristinashu** [comment]
It will probably be something like this https://foundation.mozilla.org/en/blog/5-key-decisions-every-smart-device/ or a more complicated version would be like this https://foundation.mozilla.org/en/blog/how-smart-homes-could-be-wiser/. 

@xmatthewx I guess the limitation is that it can only be a single page, is that ok?

**Comment by xmatthewx** [comment]
Yes, print to pdf would be a single page at a time. They'd have to be gathered into one doc. A cover could be added. I think it's still easier than producing a separate document.

**Comment by kristinashu** [comment]
cc @sabrinang since this could relate to the "one-pages" for Lotta.

**Comment by cadecairos** [comment]
@kristinashu Would it be just the blog pages needing print styles or have your recieved requests for other page types to get print versions?

**Comment by kristinashu** [comment]
It will be for other templates as well. Example: [Opportunity template pages](https://foundation.mozilla.org/cms/pages/807/view_draft/). But happy to start with just blog pages if that's easier.

**Comment by cadecairos** [comment]
OK, great! I think for a first pass we'll get a feel for print styles using blog pages and then follow up with changes for Opportunity template pages.

**Comment by mmmavis** [comment]
Blocked until #4542 is done so we can utilize Bootstrap's new utility classes for print.
