### ISSUE TITLE
IA: add Bob's insights and prepare report for first broader presentation

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4383]
**Background:** based on  #4301 - the report was finalized and we need to insert Bob's insights after her interview on Monday, 23rd.

Tasks:
- [x] Add Bob's insights to the report.
- [ ] Prepare a presentation with the main highlights to share with stakeholders

Once this task is done, it will unblock the presentation on #4302

**Comment by taisdesouzalessa** [comment]
Bob's insights were included on the report. The report (Google Docs) is finalized and ready to go \0/

**Next step:** to prepare the presentation with highlights.

**Comment by kristinashu** [comment]
Updating this ticket so it's just about interviewing Bob and adding her insights to the report.

Creating a condensed report can be done here https://github.com/mozilla/foundation.mozilla.org/issues/4416!
