### ISSUE TITLE
Generating Pipfile.lock updates without pipenv

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#4405]
@cadecairos @patjouk @mmmavis with everything running in Docker for local dev, there does not appear to be a clean way to generate a fresh `Pipfile.lock` file after you delete your local copy.

One way to do this is to of course run `pipenv lock` in the local file system, outside of docker, but that does mean still needing `pipenv` to be installed, and of course that will create a pretty huge virtualenv diirectory somewhere, just to generate a ~35kb `Pipfile.lock` file, which seems overkill, 

The only other way I've figured out how to do this is to use Docker, but in a fairly unpleasant way: start everything up with `docker-compose up`, then in a second terminal run `docker exec -it foundationmozillaorg_backend_1 /bin/bash` to get into the backend container, run `pipenv lock` to explicitly generate the lock file inside the container, then exiting and running `docker cp foundationmozillaorg_backend_1:/app/Pipfile.lock .` to get the new lock file out.

Is there a way to make all this work without needing to run `pipenv` locally?

**Comment by patjouk** [comment]
The idea is to use pipenv that is inside your backend container. To make easier, you can use `inv docker-pipenv [COMMAND]`. In your case you can run `inv docker-pipenv lock`. In case you don't know,  you can also use `npm` inside the `watch-static-files` container by using `inv docker-npm [COMMAND]`.

**Comment by cadecairos** [comment]
https://github.com/mozilla/foundation.mozilla.org/blob/master/docs/local_development_with_docker.md#python
