### ISSUE TITLE
IA: Create a condensed report

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4416]
Follow up from #4383 and blocking ##4415.

The[ interview report ](https://docs.google.com/document/d/16GilewBBqr-sDknD9MroVy4QHR3TmWl4Q_2kGXFDg4A/edit#heading=h.rrt26f1h8iqp)is done and is amazing!

Now we just need a concise version of the report to share out with stakeholders.

### Todo
- [x] Create a [condense report](https://docs.google.com/presentation/d/19etCN1uGLcLmB50-uV-srsWKEAhlwlR_bc0dLE1uW1g/edit?usp=sharing) that links to the full report

cc @beccaklam

**Comment by taisdesouzalessa** [comment]
Condensed report was merged with Rebecca's condensed report as well as everything is related to the same subject. 
[Here is the final version](https://docs.google.com/presentation/d/19etCN1uGLcLmB50-uV-srsWKEAhlwlR_bc0dLE1uW1g/edit?usp=sharing)

Next step: share with interviewees and Engagement team.

**Comment by kristinashu** [comment]
Awesome Tais! 

The next steps of writing the email and sharing can happen here https://github.com/mozilla/foundation.mozilla.org/issues/4415 so closing this ticket!
