### ISSUE TITLE
Create slack notification for production pushes

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#443]

**Comment by xmatthewx** [comment]
Could be nice to have a changelog from PRs. Alert team to look at risky things in staging.

**Comment by alanmoo** [comment]
@cadecairos What's the lift on something like this?

Also, do we have a bot for setting up reminders based on time of week so we can encourage people to poke at staging one more time before we deploy?

**Comment by cadecairos** [comment]
Do we want production push notifications for the front end and the django app? To which channel?

It is simple to set up hooks for the django app on Heroku. Adding slack notifications for the front end shouldn't be hard either, the jenkins instance has a slack plugin installed.

**Comment by kristinashu** [comment]
Is this done? Looks like these are showing up in [Slack](https://mozilla.slack.com/archives/C4F5NM7C7/p1520016176000269)
<img width="890" alt="screen shot 2018-03-06 at 10 12 00 am" src="https://user-images.githubusercontent.com/1068783/37049803-edbf9e1e-2126-11e8-951b-f070b4f7d44c.png">

**Comment by cadecairos** [comment]
@kristinashu yeah, Lets close this out!
