### ISSUE TITLE
IA: share proposed IA with the team

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4439]
Follow up from - IA: revise IA based on data & interviews #4244

Share the [proposed IA](https://redpen.io/uwd60d265a2ffbe381) with the Anil, Matthew, Engineers, content, and comms and iterate based on feedback.

- [x] Slack Anil and Matthew
- [x] cc devs in ticcket
- [x] Set up meeting with content
- [x] Set up meeting with comms
- [x] Compile feedback
- [ ] Update based on feedback [https://github.com/mozilla/foundation.mozilla.org/issues/4472]

cc @taisdesouzalessa

**Comment by beccaklam** [comment]
Engineering team! I know I shared this during stand but in case you missed it @cadecairos @Pomax @mmmavis @patjouk here is the IA draft: https://redpen.io/p/wd83cac5211b178ff0 Please let me know if you have any questions or concerns, your feedback is welcome as we keep iterating!

**Comment by beccaklam** [comment]
Closing this ticket, will track follow up work in ticket #4472
