### ISSUE TITLE
Top level newsletter form only becomes invisible, not "not in the DOM", so you can tab into it

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#4440]
Because we don't set `display:none` on the top sliding newsletter form, the form and all its elements stay on the page, and tab-navigating through the page means tabbing through a whole bunch of elements that are invisible and don't update the status bar to show what's actually happen.

So that probably needs changing to a two-step "display" + "fade" toggling.

**Comment by mmmavis** [comment]
@Pomax I believe you have fixed this?

**Comment by cadecairos** [comment]
@Pomax to investigate

**Comment by Pomax** [comment]
Totes McFixyboatsed
