### ISSUE TITLE
PNI: localizing Minimum sec standards badge

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#4447]
Hello designers,

I’d like to localize this badge in French and German for PNI, would that be possible?

![image(2)](https://user-images.githubusercontent.com/1294206/78266455-b7f42480-74fd-11ea-9a77-532d51007ada.png)

Note: I’ve put in bold which word should use a larger font size, if possible

FR: RESPECTE NOS / CRITÈRES / ÉLÉMENTAIRES DE / **SÉCURITÉ**
DE: ERFÜLLT UNSERE / MINDEST- / **SICHERHEITS-** / STANDARDS

**Comment by kristinashu** [comment]
Working files and fonts are [here](https://drive.google.com/drive/folders/18CmCFIV28BjKZau-nQqLCXjB0tFnIEWO?usp=sharing).

**Comment by sabrinang** [comment]
@TheoChevalier @kristinashu 

Please review redpen here: https://redpen.io/p/ag12916249ad66953f

- adjusted type size on design to fit longer words

**Comment by TheoChevalier** [comment]
Thanks @sabrinang, it looks great!

**Comment by sabrinang** [comment]
Exported files on gdrive here: https://drive.google.com/open?id=1Ji8H0lxEHMXwopuOYnRlsBLb1OYGcKRa&authuser=sabrina@mozillafoundation.org&usp=drive_fs

**Comment by TheoChevalier** [comment]
Oh wait, I just realized the color is not matching what we have on the site, it should be something like #909090 instead of #000000

**Comment by sabrinang** [comment]
All updated to `#909090` and re-uploaded: https://drive.google.com/open?id=1Ji8H0lxEHMXwopuOYnRlsBLb1OYGcKRa&authuser=sabrina@mozillafoundation.org&usp=drive_fs

**Comment by TheoChevalier** [comment]
Thanks! Adding it to the site here https://github.com/mozilla/foundation.mozilla.org/pull/4531
