### ISSUE TITLE
[Fellows support] RCS Playbook: create and build

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4453]
Epic here (#4451)

THEME: CREATE AND BUILD 
- [x] Mock up a couple options using wagtail 
- [x] Get feedback from design team and Kathy
- [x] Set up the chosen proposal in Wagtail 
- [x] Consider how it fits in with other [Responsible CS Challenge work](https://foundation.mozilla.org/en/initiatives/responsible-cs/) 
- [ ] Train Kathy to add the rest of the content herself

**Comment by taisdesouzalessa** [comment]
Mocked up one option and sent Kathy's way for feedback...it is still rough but wanted to give her a sense of the direction I am envisioning before I go too far in the design process:
https://foundation.mofostaging.net/en/fellowships/responsible-computer-science-playbook/topics/

**Comment by taisdesouzalessa** [comment]
Sent revised proposal to Kathy + built the page on production Wagtail

**Comment by taisdesouzalessa** [comment]
Kathy is okay with new version, will try to populate it herself and I'll be available to answer her questions. 

Need Kathy's feedback (messaged her on Slack) about "Consider how it fits in with other Responsible CS Challenge work" - once I have the answer I can offer some suggestions so this item is likely to move to next sprint.

**Comment by kristinashu** [comment]
How's this going? 

How do you think we should consider thisfits in with other Responsible CS Challenge work? I think this is a design UX question.

I recommend the design should match the main CS Challenge pages https://foundation.mozilla.org/en/initiatives/responsible-cs/. The UI already matches since it's on our site so just the graphics for the new pages should align a little. I would also recommend we link to the Playbook from the main CS Challenge page once it's live. But what do you think @taisdesouzalessa?

**Comment by taisdesouzalessa** [comment]
This project is moving well. 
I had asked Kathy about where this project fits inside the bigger "Responsible CS Challenge" work so I could understand the structure before moving to UX work. She replied on Friday and based on that, here are the options of placement:
1. We could insert its link inside "[Task Forces](https://foundation.mozilla.org/en/initiatives/responsible-cs/community/)" 
<img width="588" alt="image" src="https://user-images.githubusercontent.com/22157921/82355007-7a1c6400-99b6-11ea-9d35-68531fce691f.png">

2. Or we could add an extra menu item labeled "Projects" and add all the winning projects there, including the Playbook (this is my preferred option):
<img width="700" alt="image" src="https://user-images.githubusercontent.com/22157921/82355229-c9629480-99b6-11ea-84cf-7ef747a33e95.png">

Do you have a preference, @kristinashu?

About the design, agree with following the style we already have 👍  

Next step is to connect with Jenn and Kathy to see if it we can have the extra item on the menu.
