### ISSUE TITLE
Wireframe: About Us page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4459]
### Todo
- Create a simple wireframe for our key About Us pages (Overview & Our people) 
- [Based on the proposed IA](https://redpen.io/uwd60d265a2ffbe381)
- Update [this copy doc](https://docs.google.com/document/d/19Y5hNmEU4wix_gCoSvmhMKUk2F1Dht6Nwf1JQAu0lsg/edit) based on recommend page structure 
- Make sure the wireframe style matches the other wireframes

**Comment by taisdesouzalessa** [comment]
Here is the prototype:
https://mozilla.invisionapp.com/share/4SX9I3KGXZT#/417439332_About_Overview

I have 2 versions of "Our People" page:
a) [Version 1: with all staff](https://mozilla.invisionapp.com/share/4SX9I3KGXZT#/417439330_About_Our_People_V1)
b) [Version 2: with only leadership](https://mozilla.invisionapp.com/share/4SX9I3KGXZT#/417439423_About_Our_People_V2_-2-)

The feedback we received from staff was that it would be nice to have all of us so people can see our faces (good for fundraising) and have an idea of the size of the org. However I think having all of us in one page looks too busy and it affects loading times. 

A solution for the problem raised by staff is: to add the number of people who work at Foundation (V2) + to add faces in their context to relevant teams. For instance, Fellowships team already has a "meet the team" tab in their section. In partnerships pages we can have picture of staff they should contact and so on. It makes more sense to me. I wonder what you think.

@kristinashu @beccaklam could you please give me feedback on it?

**Comment by beccaklam** [comment]
@taisdesouzalessa The pages are looking good! I agree that having all staff on one page is too much. I think having teams show up in context is a good idea. The only thing is I remember Bob mentioning it would be nice to have a link to an org chart in the About section (sorry did not include this in the IA notes, this was from the Grants page meeting). I think she said this was helpful for fundraising purposes. I imagine it could be annoying having to click through all the "Meet the Team" pages to show the org. Perhaps we can just have a link to a tertiary page that shows a nicely designed org chart? Otherwise looking great, I like the history infographic :)

**Comment by taisdesouzalessa** [comment]
Thanks for the info and feedback @beccaklam. I'll find a way to include the org chart in the page. I like your idea to have a tertiary page with the org chart - nicely designed (so we don't overwhelm our novices audiences).

**Comment by kristinashu** [comment]
Nice Taís! This is feeling really good. 
- I agree that showing all the staff looks too overwhelming to users. I also worry about maintaining and gathering content for that page if we were to show all staff (the current leadership page is already a pain to maintain). I'd also be curious if from a donor perspective, they would be less likely to donate a few dollars knowing that we are such a big org.
- Org chat is something Bob requested but agree that it isn't relevant to novice uses so it shouldn't be visible on these secondary page and probably not a priority at this stage.
- Only thing I think is missing is more about our mission, Internet Health, and ToC (placeholder space for it until we hear more from Ashley about this). We will touch on it on Our Work page but I think the bulk of the info should be found here. People are very important but what also makes us so unique that we have a meaningful mission and strategy. 
- Could update nav to "Who we are" instead of "About us"
- I like how you've incorporate CTAs into the content!

**Comment by taisdesouzalessa** [comment]
Thank you for taking the time to give feedback, team! I've added the feedback pieces to the new prototype and merged these pages [with the latest prototype](https://mozilla.invisionapp.com/share/ZEWXZW3VXJR): "Who we are" section.

**Comment by taisdesouzalessa** [comment]
2 new feedback pieces from InVision:  
1. "Anil has highlighted that we might miss the our current hero space (accessible project with a clear CTA), should we add that back in? I still think it should be below the value prop and TBD titles but maybe above the blog posts."
2. Titles check (by content team)

**Comment by kristinashu** [comment]
That feedback is for the Homepage not the About page. I've opened a ticket for this Homepage feedback https://github.com/mozilla/foundation.mozilla.org/issues/4666

**Comment by taisdesouzalessa** [comment]
Hahah! yeah, sorry. I'll scratch the comment above! Tks for catching that, Kristina.

**Comment by taisdesouzalessa** [comment]
This page is done! \0/. Closing this ticket, feel free to reopen if needed.
