### ISSUE TITLE
Wireframe: Our Work page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4461]
### Todo
- Create a simple wireframe for our key Our Work pages (Overview, Consumer Ed, MozFest, Research) 
- [Based on the proposed IA](https://redpen.io/uwd60d265a2ffbe381)
- Update [this copy doc](https://docs.google.com/document/d/19Y5hNmEU4wix_gCoSvmhMKUk2F1Dht6Nwf1JQAu0lsg/edit) based on recommend page structure 
- Make sure the wireframe style matches the other wireframes

**Comment by beccaklam** [comment]
Wireframes here, includes Homepage and Grants wireframes too.

## V1
[Mobile](https://mozilla.invisionapp.com/share/TCWX8Z7UQ78)
[Desktop](https://mozilla.invisionapp.com/share/AWWX8UPC6ES)

## V2
[Mobile](https://mozilla.invisionapp.com/share/4TWXWK2NJ3G)
[Desktop](https://mozilla.invisionapp.com/share/ZEWXZW3VXJR)

cc: @taisdesouzalessa @kristinashu
