### ISSUE TITLE
Wireframe: Homepage

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4463]
### Todo
- Create a simple wireframe for our homepage
- [Based on the proposed IA](https://redpen.io/uwd60d265a2ffbe381)
- Update [this copy doc](https://docs.google.com/document/d/19Y5hNmEU4wix_gCoSvmhMKUk2F1Dht6Nwf1JQAu0lsg/edit) based on recommend page structure 
- Make sure the wireframe style matches the other wireframes

**Comment by taisdesouzalessa** [comment]
[Desktop Wireframe here](https://mozilla.invisionapp.com/share/ZPWUGM6FKT2#/414159978_Home_-_Top_Banner)
Mobile Wireframe: in progress
