### ISSUE TITLE
Update IA Proposal Based on Feedback

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#4472]
Follow up from - IA: share proposed IA with the team #4439

Compiled feedback from share out with Comms and Content teams [here](https://docs.google.com/document/d/1cmyQdLIwZwCNLUozvmrNHlGK_RdleNM9rJ2tWzrC9RQ/edit?usp=sharing).

More feedback may be coming, but Rebecca will start to update IA.

cc: @taisdesouzalessa

**Comment by taisdesouzalessa** [comment]
Becca, one thing to consider once we add the value prop on the homepage is the tab name. We should come up with a stronger tab name that reflects the value prop.

**Current:** "Mozilla Foundation-Homepage"
I like MoCo's one: "Internet for people, not profit"

<img width="457" alt="image" src="https://user-images.githubusercontent.com/22157921/78619455-58b24f00-7832-11ea-952a-8ab58836b29f.png">

**Comment by beccaklam** [comment]
Updated IA here: https://redpen.io/ae3dc4024cf2cd9c93

**Comment by kristinashu** [comment]
Sweet I am so excited about this IA! I think this is done. Wanna close it Becca?

@taisdesouzalessa you could put your comment about page titles here https://github.com/mozilla/foundation.mozilla.org/issues/3175
