### ISSUE TITLE
[PNI] Implement a Video Call App Category 

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#4487]
We need a new category for the Video Call products in the special edition.

The category will ideally have a special 'flair' in the nav to highlight it, similar to the Valentine's day category. It should display all `VideoCallProduct` models, exactly like we do in the other categories. We also have a stretch goal to provide an optional space at the top to display an "about the category", or maybe a card to link to a related Blog post?

**Comment by mmmavis** [comment]
My template PR covers the todo for icon 
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/2896608/79503764-965b6880-7fe6-11ea-8f6f-9a7444127f58.png">

@cadecairos 
> We also have a stretch goal to provide an optional space at the top to display an "about the category", or maybe a card to link to a related Blog post?

Can you elaborate more on this?

**Comment by Pomax** [comment]
The idea was to give categories an optional "long form" description (rich text) to be shown as part of the category page. I've filed https://github.com/mozilla/foundation.mozilla.org/issues/4487 for adding the actual field on the backend.

**Comment by mmmavis** [comment]
From this [Slack thread](https://mozilla.slack.com/archives/CBQU5EYN5/p1587070652057400?thread_ts=1587070595.056200&cid=CBQU5EYN5), it seems like long blurb field is no longer needed. 

I'm marking this ticket done! :D
