### ISSUE TITLE
[PNI] Create template[s] for Service review types

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#4488]
Refer to Sketch file for design updates

- [ ] Add icon to "Video Call Apps" on main PNI nav (icon can be found [here](https://github.com/mozilla/foundation.mozilla.org/issues/4456#issuecomment-613702610))
- [ ] Update text, order, and styling for these sections on Software Product

<img width="425" alt="image" src="https://user-images.githubusercontent.com/1068783/79281648-0d1e2780-7e68-11ea-9338-3c0c72db2651.png">

---

**Nice to have**

In voting section, swapping the verb "buy" with "use" if it's a software product. E.g.,

- For general products, show `How likely are you to buy it?`
- For software products, show `How likely are you to use it?`

Voting result screen will need to be updated as well.

**Comment by cadecairos** [comment]
Some [requests from Jen ](https://github.com/mozilla/foundation.mozilla.org/issues/4486#issuecomment-614242701)to consider while implementing:

- Always display "Compliant with US medical privacy laws" 
- Free product handling in the template: https://github.com/mozilla/foundation.mozilla.org/issues/4514

**Comment by natalieworth** [comment]
Adding [updated designs here](https://redpen.io/zq699456aa063e945a).

<img width="873" alt="Screen Shot 2020-04-15 at 3 17 55 PM" src="https://user-images.githubusercontent.com/14876567/79403259-3790e300-7f43-11ea-906b-07d118f7a58a.png">
