### ISSUE TITLE
Wireframe: Grants page prototype 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4497]
We've met with J Bob and received feedback in - Grants page feedback from Bob #4386

### Next steps
- [x] Update wireframes
- [x] Create wireframes for the additional pages
- [x] Update InVision prototype 

### To be done later
- Write a brief
- Create design
- Finalize content
- Create page in Wagtail
- Delete www.mozilla.org/grants/ and redirect to this new page
- (Added by Taís) - once we have a new URL structure to this page, please inform Audrey to contact Torchbox (they will need to update GA ads that are pointing to "en/fellowships" and "en/awards" urls).

cc @beccaklam (putting this a stretch goal but most likely won't work on this until next sprint)

**Comment by beccaklam** [comment]
Started fleshing out the wireframes:
[Desktop](https://mozilla.invisionapp.com/share/AWWX8UPC6ES#/414395792_Grants_Proposal_3)

**Comment by beccaklam** [comment]
@kristinashu @taisdesouzalessa I've made edits to the [invision prototype](https://mozilla.invisionapp.com/share/ZEWXZW3VXJR#/414396501_Grants_Proposal_3) based on your wonderful feedback! Please take a look and let me know what you think. FYI, I've put links to tertiary FAQ pages at the bottom of the Fellowship and Awards pages.

**Comment by kristinashu** [comment]
Looking good! I've moved a couple of the items to this design ticket https://github.com/mozilla/foundation.mozilla.org/issues/4626 so I think you just need to:
- update the main nav with the new names based on today's brainstorm 
- update the InVision

Then this is good to close!
