### ISSUE TITLE
Google Data Studio: Content Board

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4508]
### Background:
The content team wants to know how their articles are performing.

### Requests:
•  5 days performance of blogs/content on our site (recurring report). Also report on what content is converting visitors to subscribers (or donors)
• Performance of content from homepage (Xavier's ask). 
• Share out this on Slack after stand (with Xavier) every week - top 5 or 10 pieces of content (Taís will see if this can be automated via bot)

### Deliverable:
Google Data Studio Dashboard that can be filtered by the Content team so they can have access to stats when needed.

### Notes:
• Board can live in the UX Artifacts page
• Taís will sync with Anil to figure out how to roll out boards to broader team.

**Comment by taisdesouzalessa** [comment]
WIP here: https://datastudio.google.com/open/1Ko34ErDtjqCGZCgQ76xy5VkvE3zL7uRl

**Comment by taisdesouzalessa** [comment]
Started this dashboard (WIP): https://datastudio.google.com/open/1hV3JjKzZvvDV-XbefrqpJMpOvwLlfaMj?usp=sharing

**Comment by taisdesouzalessa** [comment]
• Added benchmark numbers to page 1 of the board and connected with Anil asking for input on what are the best metrics to use as benchmark.

**Comment by kristinashu** [comment]
@taisdesouzalessa what else is needed to complete this ticket?

**Comment by taisdesouzalessa** [comment]
- [ ] making it more on brand
- [ ] adding benchmarks to facilitate comparison

**Comment by taisdesouzalessa** [comment]
this ticket was forgotten. I still think there is value on doing a dashboard so Xavier can see content performance (we are now meeting every 2 weeks instead of weekly). Will try to do an MVP of this. Adding it a stretch goal for this sprint.

**Comment by taisdesouzalessa** [comment]
Dashboard is here and ready to go: https://datastudio.google.com/reporting/1Ko34ErDtjqCGZCgQ76xy5VkvE3zL7uRl

Next step: contact Xavier to see if the need a walkthrough. Closing this ticket.
