### ISSUE TITLE
[PNI] new PNI products start off with `NaN` vote information

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#4511]
This means that before our `aggregate_product_votes` script runs, visitors will see this:

![image](https://user-images.githubusercontent.com/177243/79276780-76e50400-7e5d-11ea-988a-c66a73f21035.png)

So we probably want to make sure that we catch those NaN values and instead show something that suggests vote tallying is pending?

@kristinashu would this need explicit design, or would just some tactical phrasing be enough here?

**Comment by kristinashu** [comment]
I do try to vote at least once on every product for every level of creepiness both for this reason but so people are less likely to notice the delay in their vote counting towards the results. 

If it's straight forward for you to do, you could update the `NaN` to just `0` as a backup tho.

cc @caltrider
