### ISSUE TITLE
[PNI] Remove $ on Free Products

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#4514]
Products provided for free need to be gracefully handled in our template:

![image](https://user-images.githubusercontent.com/438003/79381751-75d0d700-7f30-11ea-9936-14c73ca92fc3.png)

**Comment by mmmavis** [comment]
Current template code:
```html
<a id="product-company-url" class="product-price small-link col-md-8 mb-3" href="{{product.url}}" target="_blank">{{product.company}} ${{product.price}}</a>
```

Before we can remove the hardcoded dollar sign from template, we'll have to update existing product price value in the database to include dollar sign first.

**Comment by Pomax** [comment]
We can do a check on which product type we're dealing with, so that general products only need to specify a number, but software products need to include `$` if that needs to show up on the page.

**Comment by Pomax** [comment]
we're slipping this into the template PR
