### ISSUE TITLE
[PNI] Finalize SoftwareProduct CMS form layout

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#4515]
Let's verfy the layout of our fields for Software Products in the CMS.

- move "share data" fields to the "how does it handle privacy" section
- Can we set the `verbose_name` of `how_does_it_share` to get a better label name?
- hide the "ways to contact the company" fields on software products

**Comment by Pomax** [comment]
Not a fan of just "hiding" those fields: if not all products should have "how to contact" we should move it out of the BaseProduct and into the GeneralProduct instead.

@caltrider do we only want to hide this field for "video call apps", or will software products never have that information?

**Comment by cadecairos** [comment]
This was fixed.
