### ISSUE TITLE
Fix spacing between company and price

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#4541]
The spacing between the company name and the price looks odd without a leading `$`

![image](https://user-images.githubusercontent.com/438003/79905002-92af5380-83e3-11ea-9aa3-f2c0ee354f65.png)

**Comment by mmmavis** [comment]
@kristinashu could you assign a designer to come up with design solution?

Context:
On PNI product page, we show `<company name> <price field value>` as one hyperlink. This works fine for physical products because they only have single fixed price value, whereas for software products the value of the price field could be a list of options and it reads odd for those cases (see screencap above)

**Comment by kristinashu** [comment]
Staff could just add a `|` before the price and try to shorten the copy (cc @caltrider). 
For example:

<img width="579" alt="image" src="https://user-images.githubusercontent.com/1068783/79919593-87f4be80-83e3-11ea-85d1-441fccaf1f03.png">

**Comment by kristinashu** [comment]
Jen is doing this quick fix!

**Comment by Pomax** [comment]
We can add ` | ` through the product template too, so that Jen doesn't have to do this manually. As a small fix, we can push that through to prod pretty easily.

**Comment by kristinashu** [comment]
I'll reopen this for design to look at for a more long term solution. 

The `|` would only appear if there isn't a `$` so it seems like manual is easier for now.

**Comment by natalieworth** [comment]
Have 2 options to deal with the [company/ price in redpen here](https://redpen.io/p/bk0470965b5cde0dc1).

I prefer it with titles and on 2 lines (so it separates and identifies the content better)—but let me know if it's technically possible and design feedback too.

cc @kristinashu @beccaklam @taisdesouzalessa @sabrinang @mmmavis

**Comment by natalieworth** [comment]
I added an example of the product image in redpen. If it's good to go we could make a dev tic. :)
https://redpen.io/p/bk0470965b5cde0dc1

cc @kristinashu For design review and @mmmavis if you want to see it.

**Comment by kristinashu** [comment]
Thanks Nat! I added one more idea to explore. If you think it doesn't work then go with the version with out the "company" and "price" text.

**Comment by mmmavis** [comment]
From looking at the comps it seems like `COMPANY` and `PRICE` are using custom text treatment (all caps with extra letterspacing) Will it be possible to use existing type styles we have on the style guide?
