### ISSUE TITLE
Sunset "mofo-bootstrap" and update "bootstrap" to latest version

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#4542]
Foundation doesn't have many web properties anymore and the only two websites that use [`mofo-bootstrap`](https://github.com/mozilla/mofo-bootstrap) are **Foundation site** and **Network Pulse**. `mofo-bootstrap` was last updated 2 years and our brand style has evolved quite a bit since. Many SCSS overrides have been added to Foundation site & Pulse codebase to achieve the new brand style we want and this has introduced more maintenance overhead. 

## Proposal
Sunset `mofo-bootstrap` and have all custom overrides for our current style guide in Foundation site codebase. We'll have to do the same for Pulse. Note that the overrides we have in Pulse will be somewhat different than the ones we have in the Foundation site because Pulse doesn't follow Foundation style guide 100%.

### Foundation site

1. #4545 Move `mofo-bootstrap`'s [overrides for Bootstrap](https://github.com/mozilla/mofo-bootstrap/tree/master/src/scss) to Foundation site repo & remove `mofo-bootstrap` dependency from Foundation site --> **1 PR**
2. #4546 Clean up overrides from `mofo-bootstrap` and existing overrides for the new brand so there's only one set of overrides in Foundation site repo. --> **1 PR**

### Network Pulse

Similarly,
1. https://github.com/mozilla/network-pulse/issues/1293 Move `mofo-bootstrap`'s [overrides for Bootstrap](https://github.com/mozilla/mofo-bootstrap/tree/master/src/scss) to Pulse repo & remove `mofo-bootstrap` dependency from Network Pulse --> **1 PR**
2. https://github.com/mozilla/network-pulse/issues/1294 Clean up overrides from `mofo-bootstrap`, existing overrides for the new brand, and "Pulse brand"  so there's only one set of overrides in Pulse repo. --> **1 PR**

### Sunset `mofo-bootstrap`

#4547 Once we verify things look good on Foundation site and Network Pulse without having `mofo-bootstrap` as a dependency, we should sunset `mofo-bootstrap`.

### Update `bootstrap` to latest version

Update `bootstrap` dependency to `v4.1` from `v4.0.0-alpha.6` (which is what `mofo-bootstrap` is currently built on)

- #4549 Do this for Foundation site
- https://github.com/mozilla/network-pulse/issues/1295 As well as for Pulse

/cc @Pomax @cadecairos

**Comment by Pomax** [comment]
I love it, let's make it happen.

**Comment by mmmavis** [comment]
DONE! 🎉
