### ISSUE TITLE
Add Pulse profile streamfield to factory

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#4553]
Add Pulse profile streamfield to factory and Percy so we can get Percy to flag any visual regression.
May need to fake the Pulse API

**Comment by mmmavis** [comment]
@danielfmiranda this could be a little tricky compared to your other tickets so I'm leaving it as a stretch goal ticket.

**Comment by Pomax** [comment]
We can close this - this component is covered by the styleguide, and kicks in for review apps, being flagged by percy.
