### ISSUE TITLE
Youtube Regrets: Join Mozilla Button

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#4615]
**Describe the bug**
The Join Mozilla button appears throughout the page and is not clickable. On smaller viewports, two buttons appear at the top, both not clickable.

**To Reproduce**
1. Go to 'https://foundation.mozilla.org/en/campaigns/youtube-regrets/'
2. Scroll down or minimize window (or mobile)

**Expected behavior**
See button after opening message only and is actionable to join Mozilla.

**Screenshots**
![Y0yn5VGrgT](https://user-images.githubusercontent.com/2492510/81596535-1e7c2600-9379-11ea-8844-357316984e40.gif)

**Desktop (please complete the following information):**
 - OS: iOS 10.15.4
 - Browser: Firefox 75 & Chrome 81.0.4044.138

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: android 10
 - Browse: Firefox 68.8.0 & Chrome 81.0.4044.138

**Comment by cadecairos** [comment]
```
TypeError: c.container.style is undefined5 youtube-regrets.compiled.5c13046056b8.js:1:2543
    value https://assets.mofoprod.net/static/_js/youtube-regrets.compiled.5c13046056b8.js:1
    value https://assets.mofoprod.net/static/_js/youtube-regrets.compiled.5c13046056b8.js:1
    value https://assets.mofoprod.net/static/_js/youtube-regrets.compiled.5c13046056b8.js:6
    (Async: EventListener.handleEvent)
    value https://assets.mofoprod.net/static/_js/youtube-regrets.compiled.5c13046056b8.js:6
    e https://assets.mofoprod.net/static/_js/youtube-regrets.compiled.5c13046056b8.js:6
    168 https://assets.mofoprod.net/static/_js/youtube-regrets.compiled.5c13046056b8.js:6
    n https://assets.mofoprod.net/static/_js/youtube-regrets.compiled.5c13046056b8.js:1
    <anonymous> https://assets.mofoprod.net/static/_js/youtube-regrets.compiled.5c13046056b8.js:1
    <anonymous> https://assets.mofoprod.net/static/_js/youtube-regrets.compiled.5c13046056b8.js:1
```
