### ISSUE TITLE
[Fellows support] RCS Playbook: graphics and RCS main page

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4616]
**Epic here (#4451)**

THEME: GRAPHICS AND RCS MAIN PAGE 
**Note: dependence on copy + links for the [RCS main page](https://foundation.mozilla.org/en/initiatives/responsible-cs/)**
- [x] get feedback from Kathy on the [prototype suggested - new page and banner in overview page](https://mozilla.invisionapp.com/share/3KX6DXKF5VM#/screens/421310516) in #4719 (requested by email)
- [x] build it on prod (draft mode)
- [ ] ask Kathy and Jenn to populate the drafts
- [ ] do the illustrations (5 illustrations)

**Note: dependence on Kathy populating the page with content**
- [x] Create a banner graphic that aligns with the existing CS branding
- [x] Create placeholder graphics to individual articles

**DEADLINE:** they plan to have all content ready by end of August.
**DESIGN DEADLINE:** end of this sprint (mid September). I updated Jenn and Kathy via email about it and both are okay with the design deadline.

**Comment by taisdesouzalessa** [comment]
Here are the options of placement:
1. We could insert its link inside "[Task Forces](https://foundation.mozilla.org/en/initiatives/responsible-cs/community/)" 
<img width="588" alt="image" src="https://user-images.githubusercontent.com/22157921/82355007-7a1c6400-99b6-11ea-9d35-68531fce691f.png">

2. Or we could add an extra menu item labeled "Projects" and add all the winning projects there, including the Playbook (this is my preferred option):
<img width="700" alt="image" src="https://user-images.githubusercontent.com/22157921/82355229-c9629480-99b6-11ea-84cf-7ef747a33e95.png">

Do you have a preference, @kristinashu?

About the design, agree with following the style we already have 👍  

Next step is to connect with Jenn and Kathy to see if it we can have the extra item on the menu.

**Comment by kathytpham** [comment]
Love the second one @taisdesouzalessa !

**Comment by taisdesouzalessa** [comment]
Nice @kathytpham I prefer that too! Once we have the winning projects on the side menu we can also add a callout banner to the overview page (with a link to the Projects tab), since "overview" is the page with the most pageviews.

**Comment by taisdesouzalessa** [comment]
build draft on prod + got placeholder content form Kathy

**Comment by kristinashu** [comment]
Yay!

**Comment by taisdesouzalessa** [comment]
Content is being added as it arrives from the Playbook team. 
**Expected deadline for this project: end of August.**

Asked Kathy for a heads up before launch so we can give a design pass. Also, trying to unblock the illustrations for the "Resources" page + 1 for "overview" (the plan is go with more generic illustrations based on current placeholder content).

**Comment by taisdesouzalessa** [comment]
Did the main banner + placeholder image and sent to Kathy and Jenn for review + requests (to populate Wagtail) and questions to them.

**Comment by taisdesouzalessa** [comment]
Closing this ticket because I created an updated one here: #5505
