### ISSUE TITLE
PNI: remove unused "narrow menu" code

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#4619]
Just spotted some [potential dead code](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/buyersguide/templates/primary_nav.html#L5-L24) for PNI's nav. 

I can't recall if PNI ever had a toggleable nav menu for mobile and I can't seem to find it on PNI's Sketch file. (By toggleable mobile nav I mean something like Foundation site's 🍔 button + black overlay mobile nav menu). If the above code is not needed, we should remove it + its related SCSS.

**Comment by Pomax** [comment]
@kristinashu do you recall whether that was ever the case (in my recollection, we never had a hamburger on PNI, only on fomo itself, but my memory is not super reliable here =D)

**Comment by kristinashu** [comment]
Hmmm I can't remember a hamburger menu on PNI either.

**Comment by Pomax** [comment]
@mavis let's remove it~

**Comment by mmmavis** [comment]
Wow just found [this](https://github.com/mozilla/foundation.mozilla.org/issues/1893#issuecomment-430119727). We did have a mobile version nav for PNI roughly 2 years ago 😄 I guess that's what this old code was for. Will remove.
