### ISSUE TITLE
Front-end: Add featured post on /blog

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4624]
Follow up from: Featured post on /blog #3693

Add the ability to feature two blog posts at the top of /blog.

Comp:
![blog w featured copy@2x](https://user-images.githubusercontent.com/1068783/65466960-12a51900-de15-11e9-86ec-22d306e39165.jpg)

Style of the thumbnail should be the same as on https://foundation.mozilla.org/
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/1068783/65467034-4aac5c00-de15-11e9-9f4e-e780c67abaa0.png">

Which blogs to feature should be selected on the /blog cms page:
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/1068783/65467236-d0c8a280-de15-11e9-81bb-5821d6cf1851.png">

**Comment by Pomax** [comment]
Tasks
- [x] add featured blog posts to BlogIndexPage
- [x] extend the indexpage.html template to blogindexpage.html
- [x] set up a two-colum layout above the main content listing
- [x] reuse the homepage "featured blog post" template to show the feature blog posts
- [ ] ensure that featured blog posts are excluded from the general set so there's no duplication?
