### ISSUE TITLE
Grants page design

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4626]
Follow up from - Wireframe: Grants page prototype #4497

- [x] Add design layer
- [x] Create a skeleton copy doc for J Bob to populate
- [x] Review [Mark's note] and make sure we're addressing everything (https://docs.google.com/document/d/1HcKBVO85Lv8C2TX7-tq99mdzULQxw0oT-xfE5ytUqfE/edit)
- [x] Share with Bob
- [ ] Finalize name for the page

**Comment by kristinashu** [comment]
I had started the copy skeleton for grants pages in the [main copy doc](https://docs.google.com/document/d/19Y5hNmEU4wix_gCoSvmhMKUk2F1Dht6Nwf1JQAu0lsg/edit#heading=h.r3ipdfcwlg73).

**Comment by beccaklam** [comment]
@kristinashu here is the [doc](https://docs.google.com/document/d/15KVmaKV85qBVWzPalDwT46ty7f73M2ZcJJJBwXphCXw/edit?usp=sharing) with the skeleton copy template (including suggested rationales) and a draft of my email to Bob. Can you take a look and then I'll send over to Anil to review before sharing with Bob? Thanks!

**Comment by kristinashu** [comment]
Looks good!

**Comment by beccaklam** [comment]
Sent email to Bob today! [Final skeleton doc here](https://docs.google.com/document/d/15KVmaKV85qBVWzPalDwT46ty7f73M2ZcJJJBwXphCXw/edit?usp=sharing).

**Comment by beccaklam** [comment]
@kristinashu Reviewed Mark's doc, some things that we are missing:

- _We should create a simple Foundation page talking about our fellowships and awards plus MOSS and Mozilla Research Grants for now_  **(<-- I'll make a note in the skeleton copy doc asking Bob to put this in somewhere?)**
- _Point to a list of things we’ve supported where they exist and are current_

He also comments on some issues with the Awards directory that should be cleaned up? Though I don't entirely understand the issues, would need a conversation with someone who does.

- _The Mozilla Awards directory is also a problem as it makes it look like that’s the only grant making we’re doing -- need something holistic and historical_
- _Could be that you build on this to get in all grant making and fellowships, depends how things are set up_
- _Also, makes it look like a lot of the awards programs are still active and available to seek funding on_

**Comment by beccaklam** [comment]
I think overall we're going to need to figure out how to incorporate the MoCo funded programs ...

**Comment by beccaklam** [comment]
@kristinashu @taisdesouzalessa I did a [quick design pass](https://mozilla.invisionapp.com/share/7WXCS62FVXH#/418292275_Grants_Proposal_3) on the "what we fund" pages. Just added in the header image and some icons. Let me know what you think? Wondering if we should do solid colour for icons or try gradients?

**Comment by kristinashu** [comment]
@beccaklam did Mehan say who we should talk to about that? I think he said he could talk to the team and compile list, maybe you could ping him to follow-up.

**Comment by taisdesouzalessa** [comment]
@beccaklam I loved the icons you added to "Fellowships" and "Awards". Having them with different colors help to quickly scan which content belongs to what. I would keep them solid because they are easy to scan that way. My only recommendation would maybe change the color of "Fellowships" icon to other than purple because our donate box has a purple background too and people may think they are related (I could totally be overthinking that too...).

**Comment by beccaklam** [comment]
Started a doc here for internal interview signups: https://docs.google.com/spreadsheets/d/1irTuJHqTWTVeJE2KaX1dI0cIKkNdNE_Z1w6W-y9MESk/edit?usp=sharing

**Comment by beccaklam** [comment]
Abigail also said she would schedule a meeting with us but I've yet to see the invite. Will follow up with her by end of today.

**Comment by kristinashu** [comment]
Are those comments meant for this ticket https://github.com/mozilla/foundation.mozilla.org/issues/4649? I think this one is good to close?

**Comment by beccaklam** [comment]
oops yes 😅
