### ISSUE TITLE
[pni] cross page: nav text color is too low contrast

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#4639]
The grey text is not quite high contrast enough: it is currently #999999, which has a contrast ratio of 2.85, so needs to be #707070 or lower to pass web standards.

![](https://user-images.githubusercontent.com/177243/81863049-76ed2800-951f-11ea-81c2-446861c9b12b.png)

**Comment by Pomax** [comment]
@sabrinang would #707070 (~43%, so maybe gray-40?) work?

**Comment by sabrinang** [comment]
@Pomax +1 Yes, if gray-40 (#999999) is too light I'd go with the next darker shade gray-60 (#666666)

**Comment by Pomax** [comment]
oops, got those percentages the wrong way round =P Thanks, I'll put that change in and that's another a11y issue we can knock off the list!
