### ISSUE TITLE
[IA refresh] Homepage design

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4648]
Design three homepage options based on [the benchmarks](https://github.com/MozillaFoundation/Design/issues/559) and [these wireframes](https://mozilla.invisionapp.com/share/7WXCS62FVXH#/screens/418292231).

Designs could range from simple to more complex. One idea is the do something "fancy" (aka more custom and requires more dev time) at the top but then keep the rest of the page simple (aka uses our existing wagtail components).

**Comment by kristinashu** [comment]
@natalieworth created some comps [here](https://redpen.io/p/pnc1a02281d081bfba) and designs gave feedback at crit.

**Comment by natalieworth** [comment]
[V10 and the [M]](https://redpen.io/p/pnc1a02281d081bfba) version are the most recent versions for the homepage designs.

**Comment by natalieworth** [comment]
Final desktop and mobile designs for our meeting on Thursday [are in here](https://redpen.io/p/bn82314af4898269e1).

**Comment by kristinashu** [comment]
Devs seem happy with the designs! Kick-off notes are [here](https://docs.google.com/document/d/1fjehou_PsT9r_DlBkzSGUhBJwpkOUMppZlHKFWJNiqE/edit#heading=h.qlcprtmvr3fd). We are soooo close!

#### Final steps 
- [ ] Decide on some final copy https://docs.google.com/document/d/1cRquctm-6CjI28Odh4y41osXMZpVuzjq538mhNTFlI0/edit#heading=h.tdi7nysnkp5i
- [ ] Areas of focus: add links
- [ ] Blog author photos [Kristina to open a new ticket to finalize this and mock-up blog detail page]
- [ ] Consider restricting length of titles and blurbs [Kristina to open a new ticket for design to explore this]
- [ ] Spotlight: should we add a link to this tag?
- [ ] Take action thumbnails: Mock up what different title lengths looks 
- [ ] Take action signup: Mock up what the signup looks like expanded

**Comment by natalieworth** [comment]
Closing this and moving the final changes to #4869
