### ISSUE TITLE
Typography on Opportunities Pages 

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#465]
**Issue:**
Currently our Opportunities Pages (CMS view) allow editors to choose from a series of heading sizes: h1 to h6
<img width="404" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/26424179/2cfe0f94-4085-11e7-8e77-07a1a73c018b.png">

This is what editors see in the interface (this example is an h2):
<img width="925" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/26424293/8b6ad9d6-4085-11e7-923d-879f966bef77.png">

It looks good in the editors' interface. However, once published, the h2 looks very big, breaking the planned hierarchy of the page. Ideally, titles for this page should be h4.
![hierarchy-opportunities-pages](https://cloud.githubusercontent.com/assets/22157921/26424356/ce754662-4085-11e7-8fdf-56a95cffecfd.jpg)

The issue here is how we balance users' choice and flexibility of the system with predetermined page hierarchy and content flow. Do we see scenarios in which h1, h2 and h3 are necessary for this page? 

@alanmoo @hannahkane @xmatthewx @sabrinang  @gvn

**Comment by alanmoo** [comment]
Because of the way the editor allows custom code, it's probably not wise to attempt to prevent H1-H3 from ending up on the page. One possible solution: Using the same typographic styles inside the editor as the ones in place in the front end. Not quite sure the feasibility of that though.

**Comment by gvn** [comment]
We can do some overrides for CMS managed content so that H1-H3 aren't as large in that context.

**Comment by alanmoo** [comment]
Bringing them closer to the size they appear in the editor?

**Comment by kristinashu** [comment]
Hoping Wagtail will be better at this! But let's open a new Wagtail ticket if it isn't...
