### ISSUE TITLE
User test wireframe prototype - part I

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4650]
Test our [new proposed wireframes](https://mozilla.invisionapp.com/share/ZEWXZW3VXJR#/screens/414389585) using usertesting.com with a focus on novice users.

(edit by Taís): we decided to divide this task in 2 parts, since we see more value on doing the user testing after we have a more defined content + after gathering some structural insights from the treejack test.

### Todo - part I
- [x] Create a Research Plan
- [x] Determine tasks
- [x] Write script

Part II is here:  #4674

**Comment by taisdesouzalessa** [comment]
@taisdesouzalessa is the driver, @beccaklam is the supporter

**Comment by taisdesouzalessa** [comment]
Before I dive into the tasks I want to make sure we are all on the same page in terms of the goals we have with this research and the audience we are targeting.
I put together a [Research Plan here](https://docs.google.com/document/d/1xZqOWY9A6kUbQDm4FZmEs0VEYACwwSI9CGSlUyOxlTM/edit?usp=sharing) - could you please give me some feedback @kristinashu and @beccaklam? Thanks!

**Comment by taisdesouzalessa** [comment]
Here is the script. @kristinashu and @beccaklam could you give me feedback on it? Thank you!

**Comment by taisdesouzalessa** [comment]
Next step: take a look at Jen's feedback and update the test

**Comment by taisdesouzalessa** [comment]
Test updated, closing this ticket.
