### ISSUE TITLE
Wireframes - Exploring Mega Menus

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#4667]
We are exploring mega menus on the foundation site to see if they a) add more context for a user when using our global navigation and b) make organization of our content better.

[Prototype here](https://mozilla.invisionapp.com/d/main?origin=v7#/console/19805706/414389585/preview?scrollOffset=0).

**Comment by Pomax** [comment]
@kristinashu @beccaklam is this something we can close, or is there more work to be done? (if new work, rather than more work, closing and filing a new issue is probably better)

**Comment by kristinashu** [comment]
I still want to do this but yes, let's close it until this work is actually on our roadmap.
