### ISSUE TITLE
Update nav-newsletter.js so DOM nodes for mobile nav can be optional

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#4686]
Follow-up for https://github.com/mozilla/foundation.mozilla.org/issues/4619
Related PR and code: 

In ^ that ticket we remove extra DOM nodes for PNI mobile nav that are hanging around and not being used. More DOM nodes can be removed from `/buyersguide/templates/primary_nav.html` once we have `nav-newsletter.js` updated. 

Setting the estimate to 3 as I remember any nav related front end code is not straightforward to deal with.

**Comment by Pomax** [comment]
@mmmavis to have a quick look to see if this is still applicable

**Comment by Pomax** [comment]
closing this as stale
