### ISSUE TITLE
"Tweet This" page

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4703]
**Background:**
Problem we are trying to solve: how might we make the work of the Engagement team more "shareable" within the company so our teammates can tweet about it?

**Solution:**
Page on wagtail with projects containing a "Tweet This" button, which will give people a per-populated content for easy sharing.
 
**From Audrey:**
- I'd love to have a short "this is the content you can share this week" that I could share with Foundation staff to make it easy for them to post prewritten content highlights on Facebook, LinkedIn and Twitter. It'll raise awareness of things they might not know about, give them a chance to show off how cool the org they work for is, and drive traffic back to our website and engagement with out content. It's also a nice employee engagement piece.
- **It would also be a great way to do social media toolkits for campaigns** that we could share with partner orgs to make it easy for them to share our content.

**Steps:**
- [x] It seems there is a need for this page to be public facing, so we should maybe consider a hub together with [this page (Sabrina's suggestion)?](https://foundation.mozilla.org/en/initiatives/instagram/). Action item: Taís to connect with Sabrina on best way to do that.
- [x] Build the prototype on Wagtail (staging)
- [x] [Prepare a doc with instructions](https://docs.google.com/document/d/1gVnneiISmiT4WfBPQb3KgHutJq6Zlv0O9-lR1BlcOHs/edit?usp=sharing) on how to create the button and update the page. 
- [ ] Get Audrey's and Kevin's feedback
- [x] Move prototype to production environment
- [ ] Hand if off to Audrey and Kevin (page: confirm they have access and also send them the doc with instructions)

@KevZawacki looping you into this project as well as you may have interest on it :). Maybe this page would help you in your work as well? Open to feedback, ping me anytime.

cc: @sabrinang

**Comment by KevZawacki** [comment]
@taisdesouzalessa Smart idea! I can also update the page with recent press coverage that staff could share. Keep me posted & let me know how else I can help.

**Comment by Audreymofo** [comment]
Thanks @taisdesouzalessa ! Is it possible to also have "share this on Facebook" and "share this on LinkedIn" options?

**Comment by taisdesouzalessa** [comment]
Hey @Audreymofo I feel if we are going to make this page more complex we should open a ticket to engineers to allow us to reuse the "share" buttons we already have in our blog. 

Example below:
<img width="787" alt="image" src="https://user-images.githubusercontent.com/22157921/84404109-48fd1100-abbb-11ea-87ef-2ff9f89e1084.png">

I would recommend you test this page first, see if people are using it (you can also create your own links using the tool I shared with you via Slack) and if we have enough use of this page we can then open a ticket for engineers, does that work for you?

**Comment by taisdesouzalessa** [comment]
Closing this ticket, since the goal was to have this page created. If there is need of any tweaks or asset creation for it, I'll open a new one.
