### ISSUE TITLE
Update PNI's methodology.html to improve HTML outline

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#4706]
Update `network-api/networkapi/buyersguide/templates/about/methodology.html` to improve HTML outline.

This requires updating some DOM nodes with the right tag. (Mostly around `<section>` and heading)

Seeing context: https://github.com/mozilla/foundation.mozilla.org/pull/4702#discussion_r431465927

**Comment by Pomax** [comment]
@mmmavis there's a lot of `<p id="product-selection"><b>{% trans "Product Selection" %}</b></p>` in this file, too, do we want to change that to something more sensible, like `<h3 id="product-selection" class="h3-heading">{% trans "Product Selection" %}</h3>`?
