### ISSUE TITLE
[IA refresh] Moving wireframes to new live environment - part II (who we are pages)

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4725]
### Background:

Now that we have a new live environment: https://ia-refresh.mofostaging.net it is time to move the [current wireframes](https://mozilla.invisionapp.com/d/main?origin=v7#/console/19976285/418292231/preview?scrollOffset=0) to it. 

**Note: This is a first draft only. These will not be the final pages. They will be used to help determine what is needed, to get final copy, and approvals.**

Since those pages will be driven by strategy, we will need a stable version of the content before building those.

### Dependency 
- [ ] content finalized and executive approval (ticket here: #4668)

### List of pages:
- [ ] Who we are > Overview
- [ ] Who we are > Theory of Change
- [ ] Who we are > Our People
- [ ] Who we are > Public Records: no changes needed
- [ ] Who we are > Licensing: no changes 

### Current wireframes: 
https://mozilla.invisionapp.com/d/main?origin=v7#/console/19976285/418292231/preview?scrollOffset=0

### Current content: 
https://docs.google.com/document/d/19Y5hNmEU4wix_gCoSvmhMKUk2F1Dht6Nwf1JQAu0lsg/edit?usp=sharing

### Related tickets:
part I: #4724 | part III: #4727

cc: @kristinashu

**Comment by kristinashu** [comment]
@taisdesouzalessa does this still need to be done?

**Comment by taisdesouzalessa** [comment]
Nope, our "who are are" pages are launched and live. Closing this ticket! Thanks for catching this ooooold one floating around there in GH.
