### ISSUE TITLE
Add an npm task for running prettier --write

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#4729]
Whenever the Prettier dependency updates, it's a good bet some linting rules change and we need to run prettier with `--write` to ensure the code passes linting. Having to run that manually is very silly, let's automate that.

**Comment by patjouk** [comment]
As a side note and when the PR is merged here, can you open the same one on pulse front and doante-wagtail? Thanks!

**Comment by Pomax** [comment]
Good call, let me make issues for those so I don't forget!
