### ISSUE TITLE
PNI - Add Webby Award badge to homepage

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#4736]
**🗒  Design -> Dev Handoff Checklist**
(Feel free to remove items that are not applicable.)

- [x] Design has been finalized
- [x] Link to [original design ticket](https://github.com/MozillaFoundation/Design/issues/570)
- [x] Link to [related ticket](https://github.com/MozillaFoundation/Design/issues/570)
- [x] Link to [Redpen](https://redpen.io/p/pf8b9ed17a7d55d6a7) 
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Assets are included:

## Badge
![Site_Badges_2020_bw-webbypv-winner](https://user-images.githubusercontent.com/20977376/84159941-a4a09080-aa3b-11ea-8a79-a4dfb6a01b6d.png)

## Desktop
![Screenshot_2020-06-09 Red Pen](https://user-images.githubusercontent.com/20977376/84160291-019c4680-aa3c-11ea-921c-dcf96b295824.png)

## Mobile
![Screenshot_2020-06-09 Red Pen(1)](https://user-images.githubusercontent.com/20977376/84160306-052fcd80-aa3c-11ea-8e1f-c00c8bd0d2cc.png)

**Comment by beccaklam** [comment]
Updated the design to dev checklist @mmmavis! Let me know if you need anything else :)

**Comment by mmmavis** [comment]
@beccaklam do you have a SVG or png version of the badge? The one included in the ticket is on white background so it's not suitable for our use case.

**Comment by mmmavis** [comment]
@beccaklam yup yup the SVG file you attached works great. Thanks!
