### ISSUE TITLE
Translate “Mozilla Foundation” in page titles

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#4754]
Similarly to #4752, “Mozilla Foundation” appears untranslated in search results (all pages, not only PNI). We should translate this for consistency and SEO purposes.

My first suspect was https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/settings.py#L440 but it’s not appearing anywhere in the generated HTML code, and this string should be only used in the CMS UI.

I’m starting to think this is coming from something else, @cadecairos do you have an idea?

<img width="797" alt="Capture d’écran 2020-06-05 à 13 03 48" src="https://user-images.githubusercontent.com/1294206/83874204-05bf2000-a72d-11ea-8b39-36fe15be6014.png">

**Comment by mmmavis** [comment]
I'm not sure what the standard / best practice is, but I'm wondering if company names and brand names usually get translated?

**Comment by TheoChevalier** [comment]
> I'm not sure what the standard / best practice is, but I'm wondering if company names and brand names usually get translated?

Each org has its own policy on the matter, such that there’s not a standard practice. But here’s our current policy, that l10n-drivers and MoCo Legal came up with last year https://mozilla-l10n.github.io/styleguides/mozilla_general/index.html#brands-copyright-and-trademark

Based on this, what can we do? “Mozilla” can’t be translated, but we can translate “Foundation”.

Should we do it?
I think we would do ourselves a favor yes, as for instance a French-speaking person is much more likely to search for “Fondation Mozilla” than for “Mozilla Foundation”.
And we’re already translating it everywhere else

**Comment by cadecairos** [comment]
We need to run this by Abigail.

**Comment by cadecairos** [comment]
Abigail's recommendation is to not translate "Mozilla Foundation" as it suggests a separate corporate entity such as a local subsidiary.

She also points out that most search engines would be smart enough to know that "Fondation Mozilla" means "Mozilla Foundation" and show relevant results.

**Comment by phildexter** [comment]
Given the legal advice we're going to close this ticket @TheoChevalier. Please reopen if you have any questions.
