### ISSUE TITLE
[IA refresh] Wishlist and requirements

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4768]
**Background:**
As we create the pages in the [new IA refresh environment](https://ia-refresh.mofostaging.net/en/), we have a wishlist of features to request to different teams: design, content and mainly engineers.

**To do:**
- [x] writing the wishlist. **UPDATE:** [list here](https://docs.google.com/document/d/1DpjB_rqJ-Y47UdNFnjKGVAX_e6tuD_fRTSdWl_iRcTU/edit?usp=sharing)
- [ ] during the design team meeting on June 09 we decided to do a deeper design analysis of the components before creating engineer requests.
- [ ] prioritize items on the list 
- [ ] review list with devs, content and design to identify what is possible/what needs agreement
- [ ] modify mockups if necessary to adjust to limitations
- [ ] open dev implementation tickets
- [ ] open content requests

**Comment by kristinashu** [comment]
[Here are the notes](https://docs.google.com/document/d/1fjehou_PsT9r_DlBkzSGUhBJwpkOUMppZlHKFWJNiqE/edit#heading=h.qlcprtmvr3fd) from the Homepage design/dev kick-off.

We will be assessing requirements on a page-by-page basis as part of the design review and the design/dev kick-offs, so closing this one!
