### ISSUE TITLE
[IA refresh] Press Center page

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4777]
### Background:
We want to have a page for press to facilitate their communication with us. This hub will showcase our latest work to press and display Kevin's contact.

### Mockup of the final page:
https://ia-refresh.mofostaging.net/en/press-center/

### Task:
- [ ] To add a child page of "homepage" on production site called "Press Center"
NOTE: This page **won't be displayed on the top menu**. The link for this page will be on the footer. Tickets were filed for the footer task:#4791, https://github.com/mozilla/donate-wagtail/issues/1017 and https://github.com/mozilla/donate-wagtail/issues/1018

<img width="507" alt="image" src="https://user-images.githubusercontent.com/22157921/84287526-dfb2ca80-aaf4-11ea-8193-61907a33565c.png">

**Comment by phildexter** [comment]
@taisdesouzalessa are we happy with just creating this on the live site?

Note: we need to make sure it doesn't appear in the main nav

**Comment by taisdesouzalessa** [comment]
Yep, it is okay to have it only in the live site. We just have to make sure this page keeps existing when we move the content from the "IA refresh environment" to "production" later on.

**Comment by phildexter** [comment]
This ticket is only to create the page - not to do any other work. So all we need is a new page created by an admin.

**Comment by taisdesouzalessa** [comment]
edited the ticket to make the request more clear 😸

**Comment by cadecairos** [comment]
The page is now created under "Homepage" as a draft.
