### ISSUE TITLE
Close button visual regression in donation modal

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#4778]
I’ve noticed a minor visual regression in the donation modal, the close button is probably missing a margin.

![Screenshot_2020-06-10 Tell Zoom end-to-end encryption for everybody](https://user-images.githubusercontent.com/1294206/84301596-fa645e00-ab4b-11ea-8413-2d61ede9a169.png)

Tested on Firefox Nightly 79

**Comment by mmmavis** [comment]
@TheoChevalier can you remind us how to get to this donate modal?

**Comment by TheoChevalier** [comment]
> @TheoChevalier can you remind us how to get to this donate modal?

It’s a “Donation CTA” snippet used on petition pages, and displayed after signing the petition.
You should see it after signing https://foundation.mozilla.org/en/campaigns/tell-zoom-end-end-encryption-everyone/ for instance
