### ISSUE TITLE
Examine Optimizely integration & security

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#478]
@gvn - can you add a summary here? I don't think we need to start this work now, just want to make sure we capture the info. For later this month or next.  cc @alanmoo

**Comment by gvn** [comment]
Fundamentally, Optimizely requires us to weaken our content security policy to allow inline script execution, which opens an attack vector.

Aside from that, it also allows code to be added to our sites (and directly to production) that hasn't been given a review (although, we could set a policy to address that issue).

**Comment by kristinashu** [comment]
I believe we are no longer using Optimizely.

**Comment by gvn** [comment]
Good decision! 👍
