### ISSUE TITLE
No Contact Us option in the foundation.mozilla.org site

### ISSUE THREAD

**Issue by aecarvalho** [mozilla/foundation.mozilla.org#4782]
Hi, I just realized there's no way to contact the Mozilla Foundation specifically on the website, there is a mailing list provided on https://www.mozilla.org/en-US/about/forums but still no direct reference to the Foundation contacts. I needed to report the privacy issue of an app named Hike on play store, wherein there's no end-to-end encryption and most of the media sent on the app is saved on their servers for a very long time.

**Comment by Pomax** [comment]
Thank you for reaching out, and apologies for taking so long to reply.

If you wanted to report this for review as a Privacy Not Included product, then there we have some contact information at the bottom of the PnI about page, specifically at the bottom of https://foundation.mofostaging.net/en/privacynotincluded/about/why
