### ISSUE TITLE
Minify compiled CSS file

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#4784]
Minify compiled CSS file to reduce file size and load time.

We can probably do it via Webpack: https://webpack.js.org/plugins/mini-css-extract-plugin/#minimizing-for-production

**Comment by cadecairos** [comment]
With GZip enabled we might not see huge returns, but lets check.

**Comment by mmmavis** [comment]
According to https://web.dev scan, we could have a potential 70% saving of the CSS file size with CSS minification (though the saving is only 67KB).

<img width="901" alt="image" src="https://user-images.githubusercontent.com/2896608/87467203-6f540900-c5cc-11ea-9de6-ca1f0daca500.png">

I'm gonna remove this ticket back to stretch goal column and tackle this again once I'm done with my other tickets.

**Comment by mmmavis** [comment]
Spent more time than I expected on this. I ended up using `postcss` to minify CSS files because 1) we are already using `postcss` 2) it's troublesome to modify webpack config to make this work. 

One surprising finding - currently our main compiled CSS file on production is ~650KB and ~400KB actually comes from inline source map that **doesn't work** 🤮 . With minification and removal of the broken inline source map code, [we are able to improve](https://github.com/mozilla/foundation.mozilla.org/pull/4899) the CSS file from

<img width="865" alt="image" src="https://user-images.githubusercontent.com/2896608/88016724-ead81d80-cad8-11ea-8cc9-af0a02f5b991.png">

to 

<img width="834" alt="image" src="https://user-images.githubusercontent.com/2896608/88016765-fdeaed80-cad8-11ea-8151-83e9e5482107.png">

😃 

I will chat with the dev team to see if source map is needed. If yes, I will file a separate ticket to add a _working_ source map for CSS.
