### ISSUE TITLE
Placeholders are duplicated when fields are focused

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#4786]
This only occurs in Firefox, I can’t reproduce in Chrome or Safari. I think it happens with all fields, but it’s more visible with longer text.

Here are examples from the petition form:

<img width="367" alt="Capture d’écran 2020-06-11 à 16 12 25" src="https://user-images.githubusercontent.com/1294206/84404305-9058c100-abfe-11ea-8a7f-abfed4aa13d2.png">
<img width="359" alt="Capture d’écran 2020-06-11 à 16 12 32" src="https://user-images.githubusercontent.com/1294206/84404318-9484de80-abfe-11ea-8b9f-a692b8441bca.png">

**Comment by mmmavis** [comment]
Hey @TheoChevalier , thanks for catching this and filing a ticket for it! Would you mind using our [bug report ticket template](https://github.com/mozilla/foundation.mozilla.org/issues/new/choose) next time? Foundation site is growing and it's not always easy for us to reproduce bugs without the specific STR. 😅

**Comment by TheoChevalier** [comment]
> Hey @TheoChevalier , thanks for catching this and filing a ticket for it! Would you mind using our [bug report ticket template](https://github.com/mozilla/foundation.mozilla.org/issues/new/choose) next time? Foundation site is growing and it's not always easy for us to reproduce bugs without the specific STR. 😅

Sure thing!
