### ISSUE TITLE
SEO recommendations for /privacynotincluded/

### ISSUE THREAD

**Issue by rraue** [mozilla/foundation.mozilla.org#4787]
I came across the privacynotincluded several times the last year and today I took some time to see how it does in search engines. And I found a good base of sessions coming from search but as well opportunities to grow with few small changes on the site, I collected in this doc: https://docs.google.com/document/d/1qNv74r0CcGymkLbgrHpBEEXfj4LaG7syxc_Bq1UXdlw/edit?usp=sharing

We could do some changes on titles, meta description, og:tags and the international hreflang setup to increase traffic by getting better snippets and make it easier for users finding us in search to click us.

**Comment by cadecairos** [comment]
Thanks @rraue - it looks like there's lots of opportunities to improve here. We'll have to take the individual suggestions in the doc and break it out into smaller tasks, then link them to this issue.

**Comment by cadecairos** [comment]
@caltrider Do you want to weigh in on the proposed improvements?

**Comment by caltrider** [comment]
@cadecairos I'm no SEO expert so I will defer to you and @rraue here. If the changes look good to you all, I trust you all on that. And yay for better SEO!

**Comment by cadecairos** [comment]
Adding the document content here:

#### Meta title:
Every page must have a unique title and the keyword with the most important and unique information must be in the front. So for Product pages the product name should come first and as *privacy not included isn't a known brand, we should give more information about the url itsel, that it is a Privacy and Security Test of that product. I might have not found every sub page, but the following pattern should help to identify the title changes:
* Product pages:
  * Is: *privacy not included - Productname
  * Should be: Productname | Security & Privacy Test | Mozilla Foundation
* Category pages:
  * Is: Mozilla - *privacy not included
  * Should be: Category name | Security & Privacy Tests | Mozilla Foundation
* Homepage:
  * Is: Mozilla - *privacy not included
  * Should be: *privacy not included | Shop smart and safe | Mozilla Foundation
* About:
  * https://foundation.mozilla.org/en/privacynotincluded/about/why
    * Is: Mozilla - *privacy not included
    * Should be: Why we made the *privacy not included guide
  * https://foundation.mozilla.org/en/privacynotincluded/about/
    * Is: Mozilla - *privacy not included
    * Should be:  How to use *privacy not included 
  * https://foundation.mozilla.org/en/privacynotincluded/about/meets-minimum-security-standards
    * Is: Mozilla - *privacy not included
    * Our minimum security test standards | *privacy not included
  * https://foundation.mozilla.org/en/privacynotincluded/about/methodology
    * Is: Mozilla - *privacy not included
    * Our Methodology  | *privacy not included
  * https://foundation.mozilla.org/en/privacynotincluded/about/contact
    * Is: Mozilla - *privacy not included
    * Should be: Contact us | *privacy not included
  * https://foundation.mozilla.org/en/privacynotincluded/about/press
    * Is: Mozilla - *privacy not included
    * Should be: https://foundation.mozilla.org/en/privacynotincluded/about/press

#### Meta descriptions:
Every url must have a unique meta description, helping users in search to know what the url is about together with the title. Right now most urls do not have any description. We could just set it on the product pages in a schema like this: “We tested *product* if it fits our minimum security standards. Find out if it passes the test and if it respects your privacy”

#### Og:title,  og:description and og:image:
Same like above, we should take the new titles and descriptions and fill them in these tags as well. The og:image should be not generic if possible, at least for the product pages it would be great to have the product images and the passed or not stamp on the sharing image.

#### Hreflang:
The content is available in more languages. We should let crawlers know this by implementing hreflang (via http headers). Then other languages have a way better chance to rank in their language in search engines.

**Comment by rraue** [comment]
With the new bunch of tested products and the organic traffic nearly doubeling I just would like to ask if I can somehow help to get this SEO basics done? We are in reach for pretty big keywords (nintendo switch ranking 14 in the US) and I think with the basics we have a great chance to get on the first page for a lot of these tested products.

**Comment by jamilasnell** [comment]
re-estimating to 0 for Mar 15th sprint as it is just being reviewed
