### ISSUE TITLE
Youtube regrets design checks

### ISSUE THREAD

**Issue by phildexter** [mozilla/foundation.mozilla.org#4799]
Torchbox have been working with Brandi on the UX and design for the Youtube Regrets extension. We felt it would be wise to have someone from the MoFo design team review where we're at with it. The existing Youtube Regrets styling has been used, along with the brand guidelines for Mozilla.

So far we've worked with Brandi and have several rounds of reviews and amends, all of which seem to have helped.

Key points to check:
 - Any views on the icon options for the extension itself
 - Any mis-use of brand guidelines
 - Does it feel understandable and digestable
 - Anything else that sticks out

We are hoping this can be more a sanity check, than something needing a full design review.

Work in progress designs are [here](https://lindsay970727.invisionapp.com/public/share/VC17H3O2PN#/screens).

**Comment by beccaklam** [comment]
Hi @phildexter thanks for going over the designs with @sabrinang and I today. We've both left comments in InVision. Is this ticket good to close?

**Comment by phildexter** [comment]
Yes, that's great thank you!
