### ISSUE TITLE
What we fund: reorder and copy reminder

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4816]
Feedback from execs:

> We like this overall approach a lot and are approving it. However, we want to shift the order of things to: why, what, how, who sections. Bob can help finalize and approve the reordering or work with you directly on it. Mark made the suggestion and she agreed and is ready to partner on finalizing. 

### To do
- [x] Update wireframes with the new order
- [x] [Update copy doc ](https://docs.google.com/document/d/15KVmaKV85qBVWzPalDwT46ty7f73M2ZcJJJBwXphCXw/edit)with the new order
- [x] Follow up with Bob on the copy and new links (slack Amanda to loop her in and see if she can help move things forward with Bob)

**Comment by beccaklam** [comment]
Reordered content in prototype and copy doc and emailed Bob/slacked Amanda. Hoping to hear back by next week!
