### ISSUE TITLE
Don't filter out draft children in the side menu if the top page itself is draft

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#4826]
Right now we don't show any draft pages in the side menu, because those should definitely be hidden on a live site, but we also do that when the parent page itself is in draft, which actually hampers content development. We should update the menu code a little so that if the root is draft, we don't filter out children, and if it's live, we do filter out the things that shouldn't be shown.

**Comment by bheasman** [comment]
Closing until raised as a new issue.
