### ISSUE TITLE
Data stewardship landscape analysis: Create a home

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4830]
We need a place to intro and link to all the PDFs and the AirTable created in https://github.com/mozilla/foundation.mozilla.org/issues/4829 as well as a newsletter signup.

### Deliverables
- [x] Determine a URL.
- [x] Determine the template type (probably Bannered Campaign style)
- [ ] Gather copy for the page
- [ ] Create evergreen graphic style for the banner and possibly social media
- [x] Determine where on fo'mo we will link to this home
- [x] Add newsletter signup (can put IHR snippet for now but final signup is blocked by https://github.com/mozilla/foundation.mozilla.org/issues/4848)

**Comment by taisdesouzalessa** [comment]
Taís to think about the URL - where does it fit considering the current information architecture (under initiatives? on its own?) - explore 3 options or so

**Comment by taisdesouzalessa** [comment]
**Determine a URL. Status: waiting on feedback**
Here is a [doc with 2 suggestions of URL](https://docs.google.com/document/d/1YM5LxEVmcrjWX5ECEFnRxNmNeR-iiGCHqVTp0h7kBAM/edit?usp=sharing). My current recommendation is the proposal #2 but I want to send this to design review before reaching the final decision. @kristinashu is there anybody else that should be involved in this decision besides the Design Team? Please let me know so I can loop them in.

**Comment by taisdesouzalessa** [comment]
**chosen URL:**  `/initiatives/data-stewardship/`

**Site potential entry points for this page:** [Blog](https://foundation.mozilla.org/en/blog/) (if we have a Blog post for this content) and if the content has any participatory element we can also add it as a card in the [Participate](https://foundation.mozilla.org/en/participate/) page - this is a [diagram with the current flow](https://mozilla.invisionapp.com/share/ZFXY0HI5E28#/424658063_System-Data-Stewardship)

**Questions for Insights team:**
1. Will we have a blog post dedicated to this project? If so, the project will be displayed in our [Blog Page](https://foundation.mozilla.org/en/blog/).
2. Will this project have any participatory element? If so, the project will be displayed in our [Participate Page](https://foundation.mozilla.org/en/participate/).

**Mockups:**
• [Proposal V1](https://mozilla.invisionapp.com/share/ZFXY0HI5E28#/424634038_V1-Overview): recommended if 3 PDFs are a collection, meaning they all have to be read to get full understanding of the subject.
• [Proposal V2](https://mozilla.invisionapp.com/share/ZFXY0HI5E28#/424634136_V2-Overview): recommended if the 3 PDFs are independent, meaning people can read 1 of them and get enough information.

**Next steps:**
• Request Insights team to choose between V1 or V2, depending on the connection between PDF docs
• Get answers from questions 1 and 2 from Insights
• Once Insight team chooses the version, Taís will build it in prod and they can start populate the template with content. Currently, [V1 is already built in the live site ](https://foundation.mozilla.org/en/initiatives/data-stewardship/).

**Comment by kristinashu** [comment]
Any update on this? I talked to Kasia this morning and it sounds like they feel a little blocked on the content because the PDFs aren't final yet. For this sprint I would recommend doing everything that we can do but then handing it off to them to populate when they feel ready.

**Comment by taisdesouzalessa** [comment]
I think the only thing we can move forward on this task is doing the evergreen banner graphic during this sprint. That is what is in my queue.

**Comment by taisdesouzalessa** [comment]
Since the PDFs' content is blocked and the team can't make a decision on the version of the page until they decide on the PDFs' content I am closing this ticket and opened a new one to the following sprint - #4915

The 4 items achieved on this sprint are checked on the ticket.
