### ISSUE TITLE
foundation.mozilla revised home page

### ISSUE THREAD

**Issue by phildexter** [mozilla/foundation.mozilla.org#4832]
Final Design: https://redpen.io/mg468ea09fe28062ff
[Kickoff meeting notes](https://docs.google.com/document/d/1fjehou_PsT9r_DlBkzSGUhBJwpkOUMppZlHKFWJNiqE/edit)
Feature branch for this work: https://github.com/mozilla/foundation.mozilla.org/tree/ia-refresh-homepage

**Comment by phildexter** [comment]
Notes from the meeting - https://docs.google.com/document/d/1fjehou_PsT9r_DlBkzSGUhBJwpkOUMppZlHKFWJNiqE/edit?ts=5efdf61b

**Comment by cadecairos** [comment]
Let's create a feature branch `ia-refresh-homepage` and build things out there. It will auto-deploy to the ia-homepage-refresh app on Heroku.
