### ISSUE TITLE
Hero Section

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#4834]
![image](https://user-images.githubusercontent.com/177243/87191328-0ce7c980-c2a9-11ea-9d02-0370897ca91b.png)

**Comment by Pomax** [comment]
Hero fields (not including the cutout statement):
- background image and cutout similar to MozFest 
  - [x] image, already exists as `hero_image`
- [x] header text, already exists as `hero_headline`
- link-as-button:
  - [x] "button label" text, already exists as `hero_button_text`
  - [x] navigational link, already exists as `hero_button_url`

Question: do we still need the current `hero_story_description`? It seems we shouldn't, but we could also use that field as the "statement of intent" inside the cutout  box.

@mmmavis does it make sense to reuse that field so we only need to add some nav-button fields for the cutout?

**Comment by mmmavis** [comment]
> Question: do we still need the current `hero_story_description`? It seems we shouldn't, but we could also use that field as the "statement of intent" inside the cutout box.

I'm not sure what the best practice is for db work. Keeping `hero_story_description` and renaming it OR just creating a new field? Note that the "cause statement" (cutout box section) work is filed under https://github.com/mozilla/foundation.mozilla.org/issues/4836

**Comment by mmmavis** [comment]
I just realize `hero_story_description` is currently a rich text field and for "cause statement" we need a plain text field with character limit. I will add the new field in my PR for #4836 and leave `hero_story_description` untouched (you can remove it in your PR?).

**Comment by Pomax** [comment]
I won't remove it in my PR, but we can remove it as part of the "cleaning up the homepage of all the things we _don't_ need anymore" pass

**Comment by mmmavis** [comment]
This is done. (Front end work is being tracked in a different ticket.)
