### ISSUE TITLE
Cause Statement

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#4836]
Fields: 
- [x] Plain text field 
- [x] Link text and link url (Confirm if internal/external urls are required; if so add validation)

**Comment by mmmavis** [comment]
@natalieworth @taisdesouzalessa is the "cause statement" section the section overlaps with the hero banner? e.g., 

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/2896608/86959964-abdabd00-c113-11ea-92e1-e11448fbbe04.png">

If so, do we wanna set character limit for the plain field and the link text field? Also wondering what kind of link do we wanna allow (e.g., internal? external?)

**Comment by natalieworth** [comment]
@mmmavis Character limit would be great. I also think it should remain an internal link. I think it'll mainly remain the same/ similar content about the Foundation, but I'll defer to @taisdesouzalessa

**Comment by taisdesouzalessa** [comment]
Agree with Natalie that we should limit the characters to force a concise way to state our mission. Also the "Learn more about our work" will always link to an internal page. @beccaklam does the character limit work you've been doing include this section as well? If so, could you give us some guidance on the number of it?

**Comment by beccaklam** [comment]
Hi @taisdesouzalessa! That ticket is a stretch goal in this sprint so I haven't touched it yet. Will update you here if I do. Also let me know what you and Nat decide since it could influence my work on that ticket :)

**Comment by kristinashu** [comment]
Let's 400 for the char limit!

**Comment by mmmavis** [comment]
This is done.
