### ISSUE TITLE
Areas of Focus

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#4837]
![image](https://user-images.githubusercontent.com/177243/87200078-ad8db780-c2b0-11ea-941d-d4124128cc35.png)

**Comment by Pomax** [comment]
Template fragment:
- `Our areas of focus` heading (wrapped in i18n tag)
- "area" cards (`{% for card in areas_of_focus %} ...`):

Card template:
- standard field templating
- nav link to use `Learn more →` wrapped in i18n tag

New model: `AreaOfFocus(Orderable)` registered as snippet, with:
- [ ] icon (image picker)
- [ ] Title
- [ ] Description
- [ ] navigational URL

New field in `HomePage` model:
- `areas_of_focus` with `AreaOfFocus` chooser set to min=3, max=3

**Comment by natalieworth** [comment]
I've exported svg [versions of the 3 icons here](https://drive.google.com/open?id=1i0f-s4Jf8eddKAcmrZuCH4nmjMg2ahdS&authuser=natalie%40mozillafoundation.org&usp=drive_fs)

**Comment by natalieworth** [comment]
Hey @KalobTaulien , I've [updated these as jpgs instead](https://drive.google.com/drive/folders/1nWooXJS-87Z_4gLlFOZgHR3l-KwAC3ba?usp=sharing) here (since we're needing them to be update-able)

**Comment by Pomax** [comment]
@natalieworth is it possible to get them as `png` instead? (jpg is great for photos, but not too good at graphics like these)

**Comment by natalieworth** [comment]
Defs! Just uploaded here: https://drive.google.com/open?id=1jwHIEe3lxqP1p5Iu8EPIQCxz032T-eRE&authuser=natalie%40mozillafoundation.org&usp=drive_fs

**Comment by phildexter** [comment]
Blocked by the URL work that Pomax is going to fix up this sprint.

**Comment by phildexter** [comment]
@Pomax should this be closed now?

**Comment by Pomax** [comment]
It should, why the heck are PRs no longer auto-closing associated issues O_o
