### ISSUE TITLE
News you can use

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#4838]
Fields:
- [x] 1 large feature 
- [x] 3 smaller features 

These should be page choosers and the relevant data for the design cards will be automatically pulled in. Card titles should be shortened to always fit on the same 2 lines. 

Note: We'll also need to decide how many blog author photos to display and attach an image field to blog author profiles.

**Comment by Pomax** [comment]
@beccaklam is this now "News you can use"?

**Comment by beccaklam** [comment]
> @beccaklam is this now "News you can use"?

Yes!

**Comment by Pomax** [comment]
I've stubbed out the backend work for this over in https://github.com/mozilla/foundation.mozilla.org/pull/4903 but there's some work left to do.

**Comment by Pomax** [comment]
weirdly, the PR closing did not close this issue but: this got done.
