### ISSUE TITLE
Quote Section

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#4843]
Fields:
- [x] Image
- [x] Quote text 
- [x] Name (Confirm if this will be linked to another page, if so add another link field)
- [ ] ~~Link (to link the `name` to)~~ no longer needed
- [x] Job Title

**Comment by cadecairos** [comment]
Q: can we use the existing streamfield for quotes
Q: This design differs from the existing brand guidelines for quotes, do we update it elsewhere?

**Comment by mmmavis** [comment]
> Q: can we use the existing streamfield for quotes

The quote we have currently on homepage is hardcoded in the template. We'll have to create new fields for it - quote text, name, title (and maybe a hyperlink field to link the name to? @taisdesouzalessa @natalieworth can you confirm?)

> Q: This design differs from the existing brand guidelines for quotes, do we update it elsewhere?

I asked this question during kick-off and designers confirmed this new style is specific for homepage only. So no need to update brand style guide.

**Comment by natalieworth** [comment]
> > Q: can we use the existing streamfield for quotes
> 
> The quote we have currently on homepage is hardcoded in the template. We'll have to create new fields for it - image, quote text, name, job title (and maybe a hyperlink field to link the name to? @taisdesouzalessa @natalieworth can you confirm?)
> @mmmavis Yes, we'll need all those fields.
> > Q: This design differs from the existing brand guidelines for quotes, do we update it elsewhere?
> 
> I asked this question during kick-off and designers confirmed this new style is specific for homepage only. So no need to update brand style guide. @mmmavis Yep, that's right. :)

**Comment by mmmavis** [comment]
@natalieworth is the image going to be for decorative purpose only (e.g., not relevant to screen readers)?

**Comment by mmmavis** [comment]
@natalieworth ^

**Comment by natalieworth** [comment]
Sorry @mmmavis I missed this!
> 
>     * for the image field - is it going to be for decorative purposes only (e.g., not relevant to screen readers)?
>  Yeah more decorative/ adding to the quote. Are you thinking if it needs accessibility? Cause I feel it would be nice if we could have alt-text still for it. 
>     * for the link field - is it link to learn more about the author? or used as quote citation source?
> Based on designer feedback, I ended up [removing the quote](https://redpen.io/p/bn82314af4898269e1) (since we didn't have a great place to always link it to)
>     * [could you attach the open quote image SVG file here?](https://drive.google.com/open?id=1i0f-s4Jf8eddKAcmrZuCH4nmjMg2ahdS&authuser=natalie%40mozillafoundation.org&usp=drive_fs) :)

**Comment by mmmavis** [comment]
Thanks! I'll update my PR accordingly.

**Comment by natalieworth** [comment]
@mmmavis I updated the location of the [quote icon svg here](https://drive.google.com/file/d/1i0nHKEmrayI4o13mcvQyEltO-5FB3Is2/view?usp=sharing)

**Comment by mmmavis** [comment]
Done!
