### ISSUE TITLE
Partner Section

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#4844]
Everything in this section is editable.

Fields:
- [ ] Image
- [ ] Heading
- [ ] Intro text 
- [ ] Link text
- [ ] Internal/external link. Add validation
- [ ] Multiple logos with optional links

**Comment by KalobTaulien** [comment]
Hey @taisdesouzalessa should these logos all have links to partner sites? And if so would they be optional links? 

![image](https://user-images.githubusercontent.com/4743971/87324857-f1b9cb80-c4ed-11ea-8615-6ada157eed07.png)

**Comment by taisdesouzalessa** [comment]
We should allow people to link to partner sites (and make the links optional, not mandatory).

**Comment by KalobTaulien** [comment]
@taisdesouzalessa Yep, makes perfect sense. Thank you!

**Comment by Pomax** [comment]
@KalobTaulien @taisdesouzalessa as I understand it, partner links are always external? E.g. we're not going to be writing pages _for_ partners that we host and link to?

**Comment by KalobTaulien** [comment]
I wasn't sure about that. I've seen situations like this before where we had to add in extra url fields. But in this case I'd be happy to remove them to keep this components simple

**Comment by Pomax** [comment]
Let's get @taisdesouzalessa to confirm whether we need external, because it'll save us a _bunch_ of code (and bug/maintenance surface =D) if this will always be "our" page.

**Comment by taisdesouzalessa** [comment]
@Pomax @KalobTaulien the intention here was to link "let's work together" to our own page (probably it will be this one: https://foundation.mozilla.org/en/fellowships/partner-with-us/)
Logos would link to external partner sites (we wouldn't host pages on our site) - the links to external sites should be optional if possible. We can choose if we want to link or not, depending on the case. Does this explanation help?

**Comment by Pomax** [comment]
Perfect, that covers both the link aspects, and drastically simplifies the code we'll need for the "Let's work together" link.

**Comment by KalobTaulien** [comment]
@Pomax #4960 is the new PR + Branch for this work. It's a lot cleaner - could you give that a quick review?
