### ISSUE TITLE
Share Treejack results and launch second round of tests

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#4867]
We launched the first set of Treejack tests (#4649) and now it's time to look at the results, see what changes we need to make, and launch the second round of tests! After we launch the second round of tests we can share the results with stakeholders and the engagement team more widely.
- [x] Review results from first test
- [x] Make any needed adjustments to second test
- [x] Launch second test
- [x] Analyze results
- [x] Share with Engagement Team and stakeholders!

cc: @kristinashu @taisdesouzalessa

**Comment by beccaklam** [comment]
Initial overview of benchmark round 2 vs new IA round 2 shows that new IA only performed minimally better (55% success score vs 57% avg success score). But digging into the results more this morning I think the new IA is still performing stronger task for task. I think we also learned a lot about where people are going for certain things and can incorporate those leanings into the new IA. Will share more once I have the chance to really analyze the results! @kristinashu @taisdesouzalessa

**Comment by beccaklam** [comment]
@kristinashu @taisdesouzalessa 

## Analysis
[Treejack Analysis Here](https://docs.google.com/document/d/1BoF6eka5MMgwMpcGmjmxPp0pHLGRxl7RMzoSKkQZVSE/edit?usp=sharing)

## Recommendations
Essentially I think we can move forward with the new navigation names. The two things that stood out were how badly users performed in Question 3 in the New IA Test and how well users performed on Question 5 for the Benchmark Test. I've copied my recommendations here from the analysis doc.

**Re: Paths for Question 3 (New IA Test)**
Looking at the paths most users took that resulted in Direct or Indirect failure shows that the majority of users selected ‘What you can do’ as where they could apply for a grant program. This indicates that the majority of users associate action on their part (applying for a program) with a label that addresses actions they can take. This trend is also observed in the Benchmark test where the majority of users went to ‘Participate’ (see the ‘Participant Destination’ tables section). To improve the chances of a user finding Fellowship and Award application paths we can make sure they are featured prominently on our 'What you can do' page. 

**Re: Success of “Internet Health” when asking users to find where they can educate themselves on latest technology issues**
‘News’ is a decent label for this but compared to the success of ‘Internet Health’ it appears that we can improve by making the label less broad. Specifically if we do want to create a hub for consumer tech education we should create a label more specific to that theme.

@taisdesouzalessa Please let me know if there's anyway I can improve my analysis? Also not sure how we want to share these results with the broader engagement team and stakeholders so open to suggestions!

**Comment by beccaklam** [comment]
Shared doc with Anil who will share with Ashley.

**Comment by kristinashu** [comment]
Awesome! I think this is good to close. Sharing it at our sprint demos is enough to consider it shared with the Engagement team.
