### ISSUE TITLE
Footer: add copy for CC license + create a page with a fuller explanation of it.

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4868]
**Background:**
Follow up on this ticket: #4755
After talking with Abigail it was decided we will have a new page in Wagtail: a Mozilla page with a fuller explanation of the license, instead of linking directly to the CC license webpage.
Pulse will have its own page, since most of the content there is not CC licensed.

**To do:**
- [x] get Abigail's approval on the [new footer copy](https://mozilla.invisionapp.com/share/PJXWEC7BU86#/424185486_Footer-License-Copy-V3)
- [x] add the new copy to all footers (in Abstract)

- [x] get copy from Abigail for this new page - **ESTIMATED DEADLINE for copy, according to Abigail: July 15th (mid next week).**
~~1 copy for Foundation sites in general/1 copy for Pulse site~~
**UPDATE:** Abigail will put all the copy on one page, so the footer can link to the same page regardless of which site it appears on. She will call out Pulse differentiation on that same page.

- [x] once we have the copy, create page on Wagtail (simple page/text only)

- [x] Pulse mockup

- [ ] open implementation ticket for all footers

~~- [ ] open implementation ticket for specific License page on Pulse (ideally a https://www.mozillapulse.org/license) OR we can create an [entry like the "About" page](https://www.mozillapulse.org/entry/120) so there is no need for engineers for this task. - @kristinashu wonder if you have any thoughts on the preferred route here?~~

**Comment by taisdesouzalessa** [comment]
New footer copy was approved by Abigail via email.

**Comment by taisdesouzalessa** [comment]
New copy (Foundation site) added to Abstract:
[Desktop](https://mozilla.invisionapp.com/share/PJXWEC7BU86#/425022979_-Desktop-_Footer)
[Tablet](https://mozilla.invisionapp.com/share/PJXWEC7BU86#/425022978_-Tablet-_Footer)
[Mobile](https://mozilla.invisionapp.com/share/PJXWEC7BU86#/425022977_-M-_Footer)

Changes: 
1. Removed "License" link
2. Added "Most content available under a Creative Commons license."
3. Changed Mozilla logo to the most updated one.
Note: using the version with "Press Center" link since this is the queue for implementation.

Next: get design feedback + apply same changes to other footers

**Comment by kristinashu** [comment]
Looks good to me R+

**Comment by taisdesouzalessa** [comment]
New copy (MozFest Footer) added to Abstract library:
[Desktop](https://mozilla.invisionapp.com/share/PJXWEC7BU86#/425026759_-Desktop-_Footer_Festival_)
[Tablet](https://mozilla.invisionapp.com/share/PJXWEC7BU86#/425026787_-Tablet-_Footer_Festival)
[Mobile](https://mozilla.invisionapp.com/share/PJXWEC7BU86#/425026784_-M-_Footer_Festival)

Changes: 
1. Removed "License" link
2. Added "Most content available under a Creative Commons license."
3. Changed Mozilla logo to the most updated one.
4. Changed from "Media Center" to "Press Center" - already got permission from Marc to do so [ticket here](https://github.com/mozilla/foundation.mozilla.org/issues/4824)
Note: using the version with "Press Center" link since this is in the queue for implementation.

Next: get design feedback + apply same changes to other footers

**Comment by taisdesouzalessa** [comment]
New copy (Donate page footer) added to Abstract library:
[Desktop](https://mozilla.invisionapp.com/share/PJXWEC7BU86#/425161335_-Desktop-_Donate_Footer)
[Tablet](https://mozilla.invisionapp.com/share/PJXWEC7BU86#/425161370_-Tablet-_Donate_Footer)
[Mobile](https://mozilla.invisionapp.com/share/PJXWEC7BU86#/425161389_-M-_Donate_Footer)

Changes:

1.     Removed "License" link
2.     Added "Most content available under a Creative Commons license."
3.     Changed Mozilla logo to the most updated one.
4.     Removed "Donate" since this is the Donate page and link is redundant
    Note: using the version with "Press Center" link since this is in the queue for implementation. / Will already took a look at this version of the footer(sent to him via Slack) and he is okay with that.

**Comment by taisdesouzalessa** [comment]
New copy (Donate page footer: Thunderbird) added to Abstract library
[Desktop](https://mozilla.invisionapp.com/share/PJXWEC7BU86#/425161690_-Desktop-_Thunderbird_Donate_Footer)
[Tablet](https://mozilla.invisionapp.com/share/PJXWEC7BU86#/425161720_-Tablet-_Thunderbird_Donate_Footer)
[Mobile](https://mozilla.invisionapp.com/share/PJXWEC7BU86#/425161729_-M-_Thunderbird_Donate_Footer)

Changes:

1.    Added "Most content available under a Creative Commons license."
2.    Changed Mozilla logo to the most updated one.
3.   Replaced License notice by _"Mozilla is a global non-profit dedicated to putting you in control of your online experience and shaping the future of the web for the public good. Visit us at foundation.mozilla.org. Most content available under a Creative Commons license.  "_
Note: using the version with "Press Center" link since this is in the queue for implementation.

@kristinashu does anybody else need to take a look at this footer besides Abigail?

**Comment by taisdesouzalessa** [comment]
Update: email sent to Abigail seeking approval of the footers above + estimate on copy of the Wagtail page.

**Comment by kristinashu** [comment]
> @kristinashu does anybody else need to take a look at this footer besides Abigail?

Nope!

**Comment by taisdesouzalessa** [comment]
Abigail and I aligned on expectations for this page during a meeting today and this is the plan:
- we will have a copy for this page very soon (Abigail showed me the preview of it and there are just a few tweaks).
- URL proposal: `https://foundation.mozilla.org/en/about/site-licensing-policies` > @kristinashu let me know if this is fine by you - this page won't be visible on the menu and it will be linked on all footers.
- Taís will do a mockup for Pulse footer and since Abigail is good with all the other versions I don't think there is a need for approval on Pulse, we will do the same as we did in the other pages
- **Thunderbird footer will be left as is.** They have their own license and we don't want to change that.

**Comment by kristinashu** [comment]
That urls sounds good. Thank you for sorting all of this out!

**Comment by taisdesouzalessa** [comment]
New copy (Pulse footer) added to Abstract library:
Desktop/Tablet/Mobile [here](https://mozilla.invisionapp.com/share/PJXWEC7BU86#/425806734_Footers-Pulse)

Changes:

    Removed "License" link

    Added "Most content available under a Creative Commons license."

    Note: using the version with "Press Center" link since this is in the queue for implementation.

**Comment by taisdesouzalessa** [comment]
**Implementation tickets:**
Foundation + PNI - #4926
Mozfest - #4927
Donate Page - https://github.com/mozilla/donate-wagtail/issues/1072
Thunderbird Donate Page - https://github.com/mozilla/donate-wagtail/issues/1018
Pulse Page - https://github.com/mozilla/network-pulse/issues/1379
