### ISSUE TITLE
Mozilla Network Launch Dashboard - data highlights

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#487]
**Description:**
Now that we have the [Mozilla Network Launch Dashboard ](https://datastudio.google.com/u/0/org//reporting/0B5UMbl9u1_wQdTlJTDZFUS0wSGs/page/OQ5E) set up it is time to think about which numbers we would like to see there.
What do we want to learn? Which numbers can help us on those learnings? How can we relate the different data points?

**Etherpad:** 
https://public.etherpad-mozilla.org/p/network-metrics

**Comment by xmatthewx** [comment]
Thanks @taisdesouzalessa! 

Remember that we can track many things in analytics and the database. For this dashboard, let's focus on things that feel right for a high level daily weather update. Things, for example, that would be interesting to see before, during, and after a big event or campaign. 

I'm particularly interested in info from the database that we can't see at all in analytics. For example, how many projects are categorized as xyz? How many users have submitted multiple entries?

**Comment by taisdesouzalessa** [comment]
Here is the spreadsheet with the items discussed in our meeting: https://docs.google.com/a/mozilla.com/spreadsheets/d/1k5p3SXfpFEUcoMrZ5YYwbOaCQbql70NxGFYsePbKrkI/edit?usp=sharing

**Comment by xmatthewx** [comment]
I started that spreadsheet, but I honestly think it invites the wrong approach. Instead of being super comprehensive, I think we can keep it simple and additive. 

If you could learn just one thing in June and July given our real traffic, see one fact on a daily basis, what would it be?

**Comment by taisdesouzalessa** [comment]
@xmatthewx ok! So maybe we could include our 1 thing item to this thread? Or would you prefer a doc?

**Comment by xmatthewx** [comment]
here's some info i gathered from the pulse DB and analytics that i think give a useful snapshot on the state of things. 

![pulse facts june 2016](https://user-images.githubusercontent.com/53411/27881778-f357dc82-6197-11e7-8034-bca7e0e1799a.png)

**Comment by taisdesouzalessa** [comment]
This task has been inactive for a while but it is still relevant. The dashboard is not getting the data, though. Maybe @arlissc can help us to fix it?

**Comment by xmatthewx** [comment]
@taisdesouzalessa - if you want to resurrect the dashboard (a good idea), I'd close this and open a new devops ticket for Arliss and Cade and Alan to discuss hooking it up.

**Comment by taisdesouzalessa** [comment]
Thanks for the guidance here, Matthew! I filed a ticket here: https://github.com/MozillaFoundation/mofo-devops/issues/621
