### ISSUE TITLE
Design support for homepage dev

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4870]
General design reviews of PRs, QA, and answering questions from engineers.

**Comment by taisdesouzalessa** [comment]
Moving this to next sprint as it is an ongoing work.

Done during this sprint: design review on quote component, tablet view of homepage, character counting decision for mission statement.

**Comment by kristinashu** [comment]
In order to properly track our sprint story points, can you please close this (in this sprint) on and open a new ticket for next sprint?
