### ISSUE TITLE
Finesse UI Direction for "What we do" pages

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#4872]
We chose a direction for the UI on the "What we do" pages (#4776) but the final assets need creating/finessing.

- [x] Finesse final UI for "What we do" pages
- [x] Create final assets
- [x] Update staging

**Comment by beccaklam** [comment]
MVP: https://redpen.io/p/rp56d7e061f5ec4b65

**Comment by beccaklam** [comment]
Staging MVP: https://ia-refresh.mofostaging.net/en/what-we-do/

**Comment by beccaklam** [comment]
I think this is good to close for now. Will open new tickets once we get more content from the exec team? @kristinashu

**Comment by kristinashu** [comment]
Yup, good to close! I think it looks great (not too busy lol) and this is plenty to work with. We can update content details when we get it from execs.
