### ISSUE TITLE
Working with Fellowship and Awards Team on "What we fund" content

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#4875]
Providing support to Lindsey and Janice as they work on content for "What we fund" overview page.

[Copy doc.](https://docs.google.com/document/d/15KVmaKV85qBVWzPalDwT46ty7f73M2ZcJJJBwXphCXw/edit#heading=h.r3ipdfcwlg73)

**Comment by beccaklam** [comment]
Lindsey and Janice have started populating the doc. I've reached out to Kevin and he has time next week to make edits.

**Comment by beccaklam** [comment]
Update after meeting with Lindsey and Janice. Content is almost ready for staging. Lindsey and Janice asked if we could put the content in staging before they showed Bob for feedback (I said I could do this). Bob is also really busy at the moment and there are some other content changes that the team wants to do before having the revisions go live. Therefore, end of the month may be a more realistic timeline for the new fellowship and awards hub to go live. @kristinashu

**Comment by kristinashu** [comment]
Good!

**Comment by beccaklam** [comment]
Still waiting for content. Once I get it I'll create a ticket to track the work of putting it live on staging.
