### ISSUE TITLE
Quote Attribution Link

### ISSUE THREAD

**Issue by KGorr** [mozilla/foundation.mozilla.org#4877]
It would be really great to be able to add a link to the attribution field of a quote. In [this blog post](https://foundation.mozilla.org/en/blog/everyone-has-internet-health-story-tell/), I had to add a paragraph underneath my quotes in order to point to the full story that I was quoting. Instead of doing this, I was hoping to just link to their name (or add their original blog title after their name and link that text).

**Comment by sabrinang** [comment]
Proposed design updates:
- author text to be larger for more hierarchy above attribution _(18/27px same as body copy size)_
- add attribution line below as body copy small with ability to link text
- iterated if the whole quote block should span 8-col or if the quote text should have the 73px side padding as before _(considering that long quotes take up a bit of vertical space)_
<img width="945" alt="image" src="https://user-images.githubusercontent.com/2492510/148632335-a9dbf14c-0370-4a99-8e6d-79e8cb157243.png">

- link to [figma exploration](https://www.figma.com/file/JT9Dvdyc96AqQ3HJlnA9Qq/?node-id=814%3A259)

**Comment by sabrinang** [comment]
@kristinashu design review?

**Comment by kristinashu** [comment]
R+ this is a great iteration! The attribution line looks good and the longer line length works well for the larger quote text. Curious if the quote text could be wide but then keep the smaller attribution text narrow?

**Comment by sabrinang** [comment]
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/2492510/149592667-8304d547-4782-4cef-a1af-b82c94045810.png">
Thanks for the feedback @kristinashu —  I updated the author/attribution lines to be narrower with padding on desktop. For mobile, they will be both full width. 

- link to component on [figma page](https://www.figma.com/file/JT9Dvdyc96AqQ3HJlnA9Qq/?node-id=814%3A259)

**Comment by kristinashu** [comment]
Looks good R+

**Comment by sabrinang** [comment]
Thanks! Dev issue opened here: https://github.com/mozilla/foundation.mozilla.org/issues/8123 — closing this issue.
