### ISSUE TITLE
Fix alignment on petition confirmation close icon

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4879]
**Describe the bug**
After signing a petition the donate dialogue box appears but the close X icon is misaligned.  

**To Reproduce**
1. Go to https://foundation.mozilla.org/en/campaigns/tell-amazon-ring-stop-sharing-information-police-services/ 
2. Fill in info and click on "Add my name"
3. See light box and the close icon

**Expected behavior**
Icon is touching the side of the outline but it should have equal space around it.

**Screenshots**
Screen cap from prod desktop
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/1068783/86849168-23511380-c064-11ea-8bf0-7e2603b45671.png">

Mobile
<img width="224" alt="image" src="https://user-images.githubusercontent.com/1068783/86850081-83948500-c065-11ea-9627-b13819a9e3e5.png">

**Desktop**
 - OS: iOS 10.15.5
 - Browser: FF 77.0.1 & Chrome 83.0.4103.116

**Smartphone**
 - Device: iPhone 7
 - OS: 13.5.1
 - Browser: Safari 

cc @cadecairos for triage

**Comment by TheoChevalier** [comment]
This has been fixed in https://github.com/mozilla/foundation.mozilla.org/issues/4778, it’s just waiting for a prod deploy.
Closing this one then

**Comment by kristinashu** [comment]
Wonderful! Thank you!
