### ISSUE TITLE
Redirect .../moz-news-beat to .../news-beat

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4884]
Redirect all languages of https://foundation.mozilla.org/blog/category/moz-news-beat/ to just https://foundation.mozilla.org/blog/category/news-beat/

Once this is done then I'll update the snippet in the cms.

cc @cadecairos for triage

**Comment by Pomax** [comment]
It looks like this one fell off our radar: do we still need to do this, @kristinashu?

**Comment by kristinashu** [comment]
Thanks Pomax! I can do this now. But will the Wagtail redirect work? For all languages?

**Comment by kristinashu** [comment]
Closing this since News Beat is on longer publishing new content
