### ISSUE TITLE
Alternate white/grey background for sections on the new homepage

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#4885]
This is blocked until the front end work of the new homepage is done.

---

Alternate white/grey background for sections on the new homepage. See mockup: https://redpen.io/sb271478cae0b6a0f8

**Comment by arps18** [comment]
Hello, @mmmavis I would like to contribute, can you help me with more details?

**Comment by mmmavis** [comment]
Hi @arps18  👋 Thanks for offering help! 

I should've left a descriptive ticket description 😓 . So this is related to the new homepage work that our team is heads down working on currently. This won't be ready for implementation for at least another 2 weeks and it will be taken care of by one of our devs. Thanks for showing interest!

**Comment by arps18** [comment]
Ok @mmmavis Not a problem! Always open to contribute for more!🥳

**Comment by KalobTaulien** [comment]
Merged in #4842 and created #5011 for the FE work — 5011 wont be covered in this ticket, but might get split into its own fragment for cleanliness.

**Comment by mmmavis** [comment]
Done!
