### ISSUE TITLE
Update staging DB clone documentation

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#4898]
There's a much easier process to get a local clone of the staging DB than we have documented [here](https://github.com/mozilla/foundation.mozilla.org/blob/master/docs/local_development.md#using-a-copy-of-the-staging-database-for-critical-testing)

Prerequisites and Considerations:

- Your local installation of postgres client tools must be from a version greater than or equal to the remote postgres server.
  - remote version: `heroku pg:info -a foundation-mofostaging-net | grep "PG Version"`
  - local version `psql --version`
- Images won't work unless you configure your environment to use the staging asset domain. Check the staging configuration settings (assuming you have access)

1. Start your Postgres conainer `docker-compose up postgres`  (add `-d` if you want stdout detatched from your console)
2. Drop the existing DB: `dropdb -h localhost -p 5678 -U foundation wagtail`
3. Use the Heroku CLI tooling to pull the remote DB into your local one: `heroku pg:pull -a foundation-mofostaging-net DATABASE_URL postgresql://foundation@localhost:5678/wagtail`

**Comment by Pomax** [comment]
cross-platform note: there is no `grep` on windows. Let's remember to make sure that the instructions work everywhere =D

**Comment by cadecairos** [comment]
> cross-platform note: there is no `grep` on windows. Let's remember to make sure that the instructions work everywhere =D

There's always `heroku pg:info -a foundation-mofostaging-net | findstr /C:"PG Version"`

But the output of the info command is only 10 or so lines, not a huge amount of data to scan for the right line. 



> Also, the user roles are not going to be the same: does this _actually_ work, or are `CREATE ROLE` instructions for the `datastudio` and heroku-db-username still required?

`pg:pull` takes care of all the role renaming fun for us!
