### ISSUE TITLE
Opportunity pages - anchor 

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#490]
**Issue**
It seems that some of our Opportunities pages are using anchors to connect elements within the same page (more specifically peoples' names to their description).

Because our top nav bar is fixed, it hides the name of the person as a title once users click on the name list.
![anchor](https://cloud.githubusercontent.com/assets/22157921/26806035/b50be5fa-4a03-11e7-945f-05366d2c4b94.gif)

**Fix**
Could we make the anchor a little bit higher in order to consider the presence of the fixed top nav bar?
<img width="738" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/26806081/ded6b7d4-4a03-11e7-9f8c-dc33b389ba7a.png">

**Comment by alanmoo** [comment]
A quick hack for this would be to give the headings a margin-top of 2em. But this is a very slippery slope, as we shouldn't be writing CSS for specific CMS pages. We should instead solve the problem at a systematic level. This seems like something that could happen on other pages that get created, so perhaps we need to reevaluate the fixed header nav.

**Comment by xmatthewx** [comment]
Let's not try and fix this right now. I'm not sure that we'll see a lot of this use case. I did a bit of research and the internet has not solved this problem gracefully – solutions are hacky. 

Since a person's name appears at the beginning of the paragraph, it's not totally broken. I'd rather remove anchor links than spend a bunch of time on this. We have bigger, more tasty fish to fry.

**Comment by taisdesouzalessa** [comment]
Thanks for the insight here @alanmoo. I was wondering if a systematic level approach would be to make all the anchors in the site respect the top nav height. Because the fixed top nav exists everywhere in the site and all anchors would have the same issue as seen in the opportunities pages.

@xmatthewx I agree it is not totally broken. I think the improvement would be worth it in the future, though, since this is an issue that can happen with any anchor we decide to add to the website. Since we have other priorities now, is there any way we could move this task to a future queue to tackle it when we have some time?

I would prefer to leave as is than to remove the anchor links. The anchor helps people to find the name they are looking for right away. Analytics shows clicks on those anchors, which means this feature has been used.

**Comment by xmatthewx** [comment]
We can leave it in the backlog for the future. I'll also mark as `help wanted`.

**Comment by kristinashu** [comment]
We've moved away from anchors in Wagtail but will tackle them if they're needed in the future.
