### ISSUE TITLE
Blog-related functionality dependent on Blog Index Page page title being 'Blog'

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#4905]
**Describe the bug**
If a user decides to change the page title of the blog index page from anything other than 'Blog', blog related functionality stops working. Is there a way to make blog related functionality work without this dependency?

**To Reproduce**
1. Go to https://ia-refresh.mofostaging.net/cms/pages/789/edit/
2. Change TITLE to anything other than Blog, hit publish
3. Go to "What we fund" and select the "News" tab
4. See Server (500) error

**Expected behavior**
You should see a Server (500) error

~**Screenshots**
If applicable, add screenshots to help explain your problem.~

**Desktop (please complete the following information):**
 - macOS Catalina V 10.15.5
 - Nightly
 - Version 80.0a1 (2020-07-09) (64-bit)

cc: @Pomax

**Comment by mmmavis** [comment]
Cross linking with https://github.com/mozilla/foundation.mozilla.org/issues/5085

**Comment by Pomax** [comment]
closing this issue, as #5085 captures the actual engineering work required.
