### ISSUE TITLE
Create a new Wagtail page - child of "About Us"

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4910]
Could we get a new child page under "About Us"?
<img width="481" alt="image" src="https://user-images.githubusercontent.com/22157921/87599124-46a14180-c6a8-11ea-885c-7fffbc1454b7.png">

The page will be called **Website Licensing** and it will be linked from the footer of many properties: foundation, mozfest, pulse and donate. 

More context on this here: #4868

**Comment by cadecairos** [comment]
@taisdesouzalessa https://foundation.mozilla.org/cms/pages/1029/edit/
