### ISSUE TITLE
Use {% with %} template tags 

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#4914]
In homepage.html we're going to have:

```
{% for highlight in page.featured_highlights.all %} {% if forloop.counter > 2 %}
    ...
    <a href="{{highlight.highlight.link_url}}">{{highlight.highlight.title}}</a>
    ...
{% endfor %}
```

It would be more efficient to use the `{% with %}` template tag. Example:

```
{% with highlight=highlight.highlight %}
    .. {{ highlight.link_url }}
{% endwith %}
```

This way we're not traversing data points as often in the template, and it keeps the template cleaner.

**Comment by bhushan-borole** [comment]
Hello @KalobTaulien 
I would like to work on this issue.
Are we talking about all homepage.html files here?

**Comment by KalobTaulien** [comment]
Hey @bhushan-borole 

Ideally, it'd be any template that uses a 2 table reference. 

```
{% for thing in page.things.all %}
    {{ thing.second_table.value }}
{% endfor %}
```
☝️ That could use the `{% with %}` keyword to reduce `{{ thing.second_table.value }}` to `{{ new_thing.value }}`

**Comment by bhushan-borole** [comment]
I understand we need to make as many less traversals as we can right?
