### ISSUE TITLE
Streaming Service Campaign

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#4928]
Placeholder ticket for work on streaming service campaign.
- [x] Complete Stakeholder Interview with Kaili

**Comment by beccaklam** [comment]
Stakeholder Interview completed with Kaili, [link here](https://docs.google.com/document/d/1xDqp1Qblg61a1wAQAp7KRoN4PZmsypOc5FUVQA87UTQ/edit?usp=sharing)

She's fine with seeing how far we can get with the campaign using wagtail components first. 
Some more context:
- Kaili originally thought MoCo could donate some engineering time to this but because of the Misinfo campaign that won't be happening. So something smaller scale is okay. 
- This also won't be the big election campaign Kaili thought it would be a few weeks before (not sure why, possible b/c they're splitting it now with the Misinfo campaign?)

Deliverables she needs from us are:
- Campaign website with visual form of their [comparative analysis](https://docs.google.com/spreadsheets/d/1EQ3zySRx3uw5h3JC7zcRmouHvaACyc1c-t77sBg-12k/edit?usp=sharing)
- The usual suite of graphics: website, social, email, blog

I'll open tickets for the items above.

cc: @kristinashu @phildexter

**Comment by kristinashu** [comment]
Excellent to hear, thank you Becca!
