### ISSUE TITLE
Add Mastodon profile link beside Twitter and co.

### ISSUE THREAD

**Issue by ArcticSnow** [mozilla/foundation.mozilla.org#4933]
**Describe the feature request**
Mozilla foundations does a lot in promoting a new internet with better respect for private life and data, so why not promoting social platform like Mastodon along side Twitter, Instagram and other platform on your webpages.

**Comment by Pomax** [comment]
After talking to some folks on the MoCo side, Mozilla currently has no official Mastodon account that can be pointed to.
