### ISSUE TITLE
[Frontend] Areas of Focus

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#4935]
Desktop:

![Screen Shot 2020-07-29 at 9 50 41 AM](https://user-images.githubusercontent.com/177243/88829131-08fce800-d181-11ea-9e8c-2516ded058b1.png)

Tablet:

![Screen Shot 2020-07-29 at 9 51 40 AM](https://user-images.githubusercontent.com/177243/88829249-36e22c80-d181-11ea-83f7-1b6128628769.png)

Mobile:

![Screen Shot 2020-07-29 at 9 52 07 AM](https://user-images.githubusercontent.com/177243/88829257-39448680-d181-11ea-8fa8-aee8dacccfe3.png)

**Comment by mmmavis** [comment]
@taisdesouzalessa can you attach the three icon files here? 😉

**Comment by taisdesouzalessa** [comment]
Here are the files in Sketch: https://drive.google.com/drive/folders/1kRxpcQhytOJ6Ujnckx-EH5jDQ1GgDA-L?usp=sharing

Let me know if you need them in other format (like svg)?

**Comment by taisdesouzalessa** [comment]
@kristinashu @natalieworth do you remember if this section was supposed to be editable in the CMS? I remember we talked about it in the meeting with Engineers but I don't remember what we decided. Would you help me here? Thanks!

**Comment by kristinashu** [comment]
Yes, it should be editable. That should have been done in the back-end ticket.

**Comment by mmmavis** [comment]
Ah sorry for the confusion. I asked for icon files without checking the backend requirements. If the files are uploaded via CMS, please ignore my comment above.

**Comment by Pomax** [comment]
I'll include the icons in our static dir anyway - mostly because it will let us bootstrap the "load fake data" command with the real images (will be using the .png files for that).

@mmmavis @taisdesouzalessa question about the "Our areas of focus" heading: that does not appear to be using any of our styleguide-indicated headings, is this a new style?

**Comment by Pomax** [comment]
marking as blocked pending refinalization of this new section

**Comment by taisdesouzalessa** [comment]
> "Our areas of focus" heading: that does not appear to be using any of our styleguide-indicated headings, is this a new style?

As per Slack chat, we are doing some custom styles for the homepage - so overrides are okay.

**Comment by Pomax** [comment]
seriously, why does github no longer auto-close issues that use github's syntax for autoclosing issues =(
