### ISSUE TITLE
Create a LinkChooser panel that allows us to define one `url` field, but with UI for internal vs. external

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#4936]
Even if wagtail is going to be working on this, too, we should create a LinkChooser panel (and stick it in the `wagtailcustomization` app, probably?) that lets people define a model as `url = models.URLField(...)` and then  assign it a panel `panels = [ ..., LinkChooser('url'), ... ]` with UI that has a regular URL chooser as well as a page chooser for internal pages, with the "one of these needs to be real" checking before it sends the value through to the associated model field.

And this can even be _the same code_ we already thought of putting in, just wrapped by a LinkChooser so that we can rely on a single real field in our model, rather than having two fields.

/cc @KalobTaulien @cadecairos

**Comment by KalobTaulien** [comment]
Hmm yeah. We could "cheat" and use a URLField for both values. However the internal_url we tend to use (with a PageChooserPanel) will use a pageId so if the slug of a page changes the link won't 404. 

I was thinking of having something like this stored in a textfield (as json)
```
{
    "external": "https://website.com", 
    "internal": 71,
    "url": ... // Checks the values and finds page 71's full url if needed
}
```
With validation to set either one or the other. And a `.url` value to maintain the same way we're already doing this. 

Though this might mean we create a custom Django field as well, much like `StreamField()`.

**Comment by Pomax** [comment]
I was more thinking we define a custom model field that internally holds both a `URLField` and a foreign key to a Page, with a `@property` decorated `def url(self): ...` that lets us ask for its value. Storing JSON is something I'd like to avoid if at all possible because migrations become borderline impossible when you're dealing with having to figure out schema translations for JSON. (which is one of the reasons it would be have great if StreamFields were real models, but that's a decision that was made way too long ago to try to switch to, now).

**Comment by Pomax** [comment]
It might be worth looking at https://pypi.org/project/django-composite-field/ to see if we can wrap a URLField and ForeignKey into a single composite field. We'd still have the same "it's two fields, with custom cleaning", but at least it'd be a single instance of that, which we can reuse in the various models that need it.

**Comment by Pomax** [comment]
As a practical "chooser" side of things, it feels like we might be able to get away with a tailored `class CustomURLChooserPanel(MultieFieldPanel` with a hardcoded list `[FieldPanel('external'), PageChooserPanel('page')]` and then the real work is around making the frontend have something for toggling which of the two fields you need.

**Comment by Pomax** [comment]
Okay, so: worrying aspect about https://github.com/bikeshedder/django-composite-field: it looks like a fresh repo (the code used to live elsewhere, but they clearly didn't care to preserve releases etc. when they moved the code and there are zero issues other than the one I filed to ask whether the project's still maintained)

**Comment by Pomax** [comment]
We'll be rolling with a custom model that wraps the two fields for now, and exposes the resulting URL through a `@property` wrapped `def url(self)`. It's not ideal, but it'll let us write dry code at least.

**Comment by Pomax** [comment]
We're closing this because nothing "simple" we tried actually worked. Breakdown to follow.

**Comment by Pomax** [comment]
Dedicated model, with a ForeignKey in models that require a universal link:

```
from django.db import models

from wagtail.admin.edit_handlers import FieldPanel
from wagtail.admin.edit_handlers import PageChooserPanel


class UniversalLink(models.Model):
    external_link = models.URLField(
        blank=True
    )

    internal_link = models.ForeignKey(
        'wagtailcore.Page',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='+',
    )

    panels = [
        FieldPanel('external_link'),
        PageChooserPanel('internal_link'),
    ]

    @property
    def url(self):
        if self.internal_link:
            return self.internal_link.url
        return self.external_link

    def clean(self):
        """
        Validation to ensure both internal or external links have
        been added to the partners section.
        """
        super().clean()
        if self.internal_link and self.external_link:
            # Both fields are filled out
            message = "Please ensure only one field has a value."
            raise ValidationError({
                'external_link': ValidationError(message),
                'internal_link': ValidationError(message),
            })
        if not self.internal_link and not self.external_link:
            message = "Please pick either a page or specify an external URL"
            raise ValidationError({
                'external_link': ValidationError(message),
                'internal_link': ValidationError(message),
            })

    class Meta:
        verbose_name = 'link'
        verbose_name_plural = 'links'
```

This code, paired with `field_name = models.ForeignKey('wagtailpages.UniversalLink',             null=True, blank=True, on_delete=models.SET_NULL, related_name='+')` causes low level Django errors:

```
AttributeError: 'ForwardManyToOneDescriptor' object has no attribute 'related'
```

**Comment by Pomax** [comment]
Mixin, imparting the fields automatically:
```
class UniversalLinkMixin(models.Model):

    link_to_web = models.URLField(
        blank=True
    )

    link_to_page = models.ForeignKey(
        'wagtailcore.Page',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='link_to_page',
    )

    # similar panels, def url(self) and def clean(self)

    class Meta:
        abstract = True
        verbose_name = 'link'
        verbose_name_plural = 'links'
```

Using this as mixin into the classes such as the blog page, using `class BlogPage(UniversalLinkMixin, FoundationMetadataPageMixin, Page)` causes the most curious of errors:

```
ERRORS:
wagtailpages.BlogPage.link_to_page: (models.E006) The field 'link_to_page' clashes with the field 'link_to_page' from model 'wagtailcore.page'.
```

And this isn't actually a real field error: Page does not _have_ that field, and changing the field name in the mixin simply throws the same error but with the renamed field.

**Comment by Pomax** [comment]
Closing as a time sink, we'll run with the duplicated code for internal+external linking for now, and leave the associated code as tech debt with a comment link to this issue to explain why it's not cleaner.
