### ISSUE TITLE
[Frontend] Blog Author photos

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#4937]

**Comment by mmmavis** [comment]
My work for the [Spotlight ticket](https://github.com/mozilla/foundation.mozilla.org/issues/4941) touches this. I will implement the blog author section as a template fragment and have CSS code in place so they can be reusable for other sections(e.g., the ["News you can use" section](https://github.com/mozilla/foundation.mozilla.org/issues/4940)).

Closing as work is being covered in the [Spotlight ticket](https://github.com/mozilla/foundation.mozilla.org/issues/4941).
