### ISSUE TITLE
[Frontend] Hero section

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#4938]
Final designs: https://redpen.io/p/bn82314af4898269e1

Desktop:

![Screen Shot 2020-07-28 at 10 47 52 AM](https://user-images.githubusercontent.com/177243/88702245-ee166f00-d0bf-11ea-9e56-da2decae1857.png)

Tablet:

![Screen Shot 2020-07-28 at 10 48 00 AM](https://user-images.githubusercontent.com/177243/88702291-fc648b00-d0bf-11ea-8917-7d75288628ef.png)

Mobile:

![Screen Shot 2020-07-28 at 10 48 10 AM](https://user-images.githubusercontent.com/177243/88702256-f078c900-d0bf-11ea-8bb0-020c9d619a0e.png)

**Comment by mmmavis** [comment]
Done!
