### ISSUE TITLE
[Frontend] Take action

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#4942]
Blocked until backend work https://github.com/mozilla/foundation.mozilla.org/issues/4842 is done.

Refer to Sketch file for the final design.

<img width="615" alt="image" src="https://user-images.githubusercontent.com/2896608/88116562-aa76af00-cb6d-11ea-9fed-31b2cfcc351a.png">

**Comment by mmmavis** [comment]
Setting the estimate to 5 as I expect quite a bit of back-and-forth discussion with designers for this one.

**Comment by mmmavis** [comment]
@taisdesouzalessa I have questions regarding how we wanna align each block in this section.

Scenario:

When the title of a card is long, that card will be taller than its neighbour. Do we want cards that are side-by-side always be in the same height?

**Comment by taisdesouzalessa** [comment]
Hey @mmmavis yes, the plan is to make the cards with the same height when side-by-side, like you have above.

About the titles' length, we are exploring options here: #4847 -  @beccaklam looping you here since it is related to the work you've been doing.

**Comment by mmmavis** [comment]
@taisdesouzalessa how do we want content in each card to be linked? (e.g., treat the entire card as one big hyperlinked element? only make the text hyperlinked? etc)

**Comment by taisdesouzalessa** [comment]
Considering the other cards' behaviour we have in the page (in which the all caps text takes users to a different place than the headline - see example below), I feel it makes more sense to just have the text hyperlinked so the behavior of the cards are all the same. What do you think?

<img width="375" alt="image" src="https://user-images.githubusercontent.com/22157921/88979713-16949980-d277-11ea-9ef0-679ee2032d2f.png">

**Comment by taisdesouzalessa** [comment]
It would be good to have images linking to the same place as the headline as well, like we have in our blog: https://foundation.mozilla.org/en/blog/

**Comment by KalobTaulien** [comment]
@taisdesouzalessa / @mmmavis do we have cover states in the design for the cards and form fields?

**Comment by KalobTaulien** [comment]
Tentatively ready for code review @mmmavis — PR is at #5015

**Comment by taisdesouzalessa** [comment]
@KalobTaulien I believe the hover states are the same as we currently have in our live page - @natalieworth could you confirm that, please?

**Comment by KalobTaulien** [comment]
I've set the to be the same as the blog. 

Status: This is awaiting another quick peer review.

**Comment by natalieworth** [comment]
Hover states are same!

**Comment by KalobTaulien** [comment]
Note: Design has feedback, I need to implement it.

**Comment by taisdesouzalessa** [comment]
Design review done, just a few more changes.

**Comment by KalobTaulien** [comment]
@taisdesouzalessa Design updates applied if you want to take one more look. 

@mmmavis Could you give this a code review please?

**Comment by mmmavis** [comment]
PR merged. Closing.
