### ISSUE TITLE
[Frontend] Partners

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#4943]

**Comment by mmmavis** [comment]
@taisdesouzalessa can you export partner logos and attach them here? 😉

**Comment by taisdesouzalessa** [comment]
here they are (they are white with transparent background so it seems empty but I swear they are here...haha)

Color of Change
![color_of_change@2x](https://user-images.githubusercontent.com/22157921/88193699-d0926280-cbf2-11ea-966e-305e439aa2fb.png)
_____
Freedom of the Press Foundation
![freedom_of_the_press_foundation@2x](https://user-images.githubusercontent.com/22157921/88193700-d0926280-cbf2-11ea-9495-6ecc50d8eb63.png)
______
Privacy International
![privacy_international@2x](https://user-images.githubusercontent.com/22157921/88193702-d12af900-cbf2-11ea-8c39-6be97a5a46b1.png)
_____
The Citizen Lab
![the_citizen_lab@2x](https://user-images.githubusercontent.com/22157921/88193703-d12af900-cbf2-11ea-8980-d72d72d5ffcb.png)

Note: this section should be editable in the CMS so we can swap logos and message as needed.

@kristinashu I feel that before launching the site live, we should double check with the Fellowships and Awards team that it is okay to use those logos in our homepage as they are past host organizations (or if they prefer to make other orgs visible). Should I ask it to them now or do we have a plan to show this page to some stakeholders for a final QA before we go live?

**Comment by mmmavis** [comment]
Ah sorry for the confusion. I asked for the file files without checking the backend requirements. If files can be uploaded via CMS, please ignore my comment above.

**Comment by KalobTaulien** [comment]
Frontend is blocked until Backend is done with #4960

**Comment by KalobTaulien** [comment]
PR #5013 

@mmmavis could you review that PR please? It's my first official frontend PR and might require me to do some re-jigging. Happy to accept feedback and make suggested changes!

**Comment by KalobTaulien** [comment]
Status: Awaiting one more small code review.
