### ISSUE TITLE
[Publications] Benchmarks and Best Practices

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#4950]
Gather external examples to benchmark long-form content and reports in a google slide deck for reference. This can give us insight on what best practices are out there and what features we may want to consider.

_Note: we can also ask stakeholders what benchmarks or existing examples they are aware of if any to be included_

**Comment by sabrinang** [comment]
WIP collecting benchmarks in google slide deck here: https://docs.google.com/presentation/d/14YZuDp2865947lBivP8wXo8K8BgVz21xDMK9cjKQP-o/edit?usp=sharing

**Comment by sabrinang** [comment]
Included external _(online/pdf reports, long form articles, vertical nav)_ and internal _(ihr, ai white paper, current vertical nav, legacy templates)_ examples in the benchmark doc. 

I'll document examples from Phil, MozFest/HeyHey and Data Futures as they share them to me.

**Comment by kristinashu** [comment]
Is this good to close?

**Comment by sabrinang** [comment]
Yes good to close (if I get more examples shared with me, I'll capture them in the doc as I go).
