### ISSUE TITLE
Decide if we want to enable source map

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#4956]
Ticket #4784 / PR #4899 removed the never-worked broken inline source map code from our compiled CSS files. Do we still want to add source maps? If so, do we

1. include both JS and CSS source maps?
2. always include them or only on development mode?

**Comment by Pomax** [comment]
Source maps are a useful feature, but raelly only for dev: none of our actual users should ever need to look up where, in our original source, a particular CSS rule came from.
