### ISSUE TITLE
Force-update title/slug fields for all locales when copying a page

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#4959]
- Log into the CMS
- pick a page and initiate its `copy` function
- on the copy page, open dev tools and look at the console
- `Uncaught ReferenceError: createPageChooser is not defined at (index):719`

**Comment by cadecairos** [comment]
This appears to be related to wagtail-modeltranslation?

* https://github.com/wagtail/wagtail/issues/6095
* https://github.com/infoportugal/wagtail-modeltranslation/issues/283

**Comment by cadecairos** [comment]
This bug doesn't appear to be the reason why copy wasn't working. It appears to be a UX problem.

When copying, you must toggle on all the localized fields using the buttons on the top-right: 
![Screenshot from 2020-09-15 10-51-18](https://user-images.githubusercontent.com/438003/93226799-b764e880-f741-11ea-9a4c-fd05a3c0bc11.png)

Without them on you can't see that the localized slugs are failing validation because they're identical to the original page's slug.

**Comment by cadecairos** [comment]
That said, It's not clear whether the page chooser bug is related. It seems to work fine on staging, which is troublesome.

**Comment by Pomax** [comment]
It is. Some options:
- we trigger some JS that reveals all fields, so users can update everything
- we trigger some JS that ensures that updates to the [en] title and slug are copied to the other locales as well

**Comment by Pomax** [comment]
Option 1 would certainly be the least-effort solution:

```
document.querySelectorAll(`.locale-picker .locale-toggle`).forEach(btn => {
  if (!btn.classList.contains(`showing-locale`)) btn.click();
});
```

Although it would be nice if we could request/help the infoportugal folks add a function to the `wagtailModelTranslations` utility so that we could call `wagtailModelTranslations.showAll()` or something.

**Comment by Pomax** [comment]
Although it's probably worth extending the copy template page so that it has a button that gives folks the option to automatically copy the `en` field over to all the other locales.

**Comment by Pomax** [comment]
Approach taken: 

![image](https://user-images.githubusercontent.com/177243/94625221-127ffa80-026d-11eb-86ad-545cf235462c.png)

The first button does what it says on the label, the second copies over the values from the [EN] fields to all other fields.
