### ISSUE TITLE
Streaming Service Campaign Prototype Website

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#4961]
[Campaign Stakeholder Brief](https://docs.google.com/document/d/1xDqp1Qblg61a1wAQAp7KRoN4PZmsypOc5FUVQA87UTQ/edit?usp=sharing)

Create a prototype campaign homepage that will host the Streaming Service Campaign and its [comparative analysis](https://docs.google.com/spreadsheets/d/1EQ3zySRx3uw5h3JC7zcRmouHvaACyc1c-t77sBg-12k/edit?usp=sharing).
- [x] Make bannered campaign page
- [x] Visualize comparative analysis using current wagtail components
- [x] Create graphics for website (draft)
- [x] Share with Kaili and Becca R for feedback

cc: @kristinashu @phildexter

**Comment by beccaklam** [comment]
Two options so far:
[Streaming Campaign V1](https://foundation.mozilla.org/cms/pages/1049/edit/preview/)
[Streaming Campaign V2](https://foundation.mozilla.org/cms/pages/1053/edit/preview/)

Will show Kaili and Becca Ricks tomorrow at our meeting

cc: @kristinashu @phildexter

**Comment by beccaklam** [comment]
[Homepage prototype](https://foundation.mozilla.org/cms/pages/1054/edit/preview/)

**Comment by kristinashu** [comment]
Looking good and thank you for sticking with our existing components!

Did you consider making each services a sub-page of the homepage and have them show up in the sub-nav? I like how you've shown the logos on the landing page but it would be nice to also have an easy way to navigate between the different services.

**Comment by beccaklam** [comment]
> Looking good and thank you for sticking with our existing components!
> 
> Did you consider making each services a sub-page of the homepage and have them show up in the sub-nav? I like how you've shown the logos on the landing page but it would be nice to also have an easy way to navigate between the different services.

No I didn't. There are fourteen services so I think that would be too many items for the sub-nav? We could put another image grid at the bottom of the page to suggest other services to look at though?

**Comment by beccaklam** [comment]
@kristinashu Example of "Compare Services" section: https://foundation.mozilla.org/cms/pages/1055/edit/preview/ Similiar to what we have on PNI.

**Comment by kristinashu** [comment]
> No I didn't. There are fourteen services so I think that would be too many items for the sub-nav? We could put another image grid at the bottom of the page to suggest other services to look at though?

Ah right, 14 would be way too many! Just so we've covered all the options... I guess if they really wanted a nav you could do the [vertical side nav](https://foundation.mozilla.org/en/initiatives/responsible-cs/) but then it doesn't have the nice banner at the top. Let us know what they say! 

> Example of "Compare Services" section: https://foundation.mozilla.org/cms/pages/1055/edit/preview/ Similiar to what we have on PNI.

That sounds good!

**Comment by beccaklam** [comment]
Notes from meeting with Becca and Kaili:
- Audience is more partners so we can "show our work" more

**Comment by beccaklam** [comment]
Will make changes to prototypes based on feedback and then I think this ticket is good to close? It doesn't sound like content will be ready for a while. Perhaps next sprint we can focus on developing visual identity for the campaign? But may want to see how close Kaili and Becca are to fine-tuning the goal of the campaign which is still in flux.

**Comment by kristinashu** [comment]
Sounds perfect! Good call to wait until the campaign is a little more fleshed out. 

I'll let Cade know that there won't be any engineering required for this campaign!

**Comment by beccaklam** [comment]
Vertical nav (Default page) exploration: https://foundation.mozilla.org/en/campaigns/streaming-campaign-v4/
Revised bannered page exploration with 'comparison' page: https://foundation.mozilla.org/en/campaigns/streaming-campaign-homepage/

**Comment by beccaklam** [comment]
Leaning towards the default page template since having the ‘Overview’ label switch around is pretty confusing for a user. Could try to make the default page less overwhelming by taking out the image grid on the homepage. Will wait to decide until advocacy team is more clear on how many services they want to review since that’ll influence the design. Closing this ticket for now!

**Comment by kristinashu** [comment]
Thanks Becca, I'm all for waiting to decide between the two options. 

The "Default" version seems to be working as expect but I think there's something up with the "Bannered" one. I _think_ you could still make Hulu and the other services sub-pages of the Streaming Services homepage (but hide them from the sub-nav). That might make the "Overview" nav item work better. The URLs and CMS also might be cleaner that way.

**Comment by beccaklam** [comment]
Oh interesting, I'll give that a look!

> Thanks Becca, I'm all for waiting to decide between the two options.
> 
> The "Default" version seems to be working as expect but I think there's something up with the "Bannered" one. I _think_ you could still make Hulu and the other services sub-pages of the Streaming Services homepage (but hide them from the sub-nav). That might make the "Overview" nav item work better. The URLs and CMS also might be cleaner that way.

**Comment by beccaklam** [comment]
Oh so @kristinashu you were right you can hide child pages! This makes the bannered campaign page more viable. It'll be up to Kaili and Becca if they want the services listed in the subnav then.
