### ISSUE TITLE
Graphics for Streaming Service Campaign

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#4962]
Timeline:
- Sharing with media Wed Sept 16
- Launching Mon Sept 21

The Streaming Service Campaign will need the usual host of graphics to support it (check-in with Kaili before starting):
- [x] Social. DONE: [graphic here](https://redpen.io/nh46369291eecccad7)
- [x] Email
- [x] Blog
- [x] Snippet Icon for MoCo. Mockup in context [here](https://redpen.io/ky8bb7c0b18f3d48d9)

Graphics will be based off the website graphics we develop for this campaign #4961. Rebecca Ricks has started to populated it here https://foundation.mozilla.org/en/campaigns/paid-programming/. Once she is done, the pages need a design review - specifically, Rebecca Ricks created some of the logo images and some of the grade images so a designer needs to double check those and possibly re-create them.
- [x] Design review of pages. DONE: [page here](https://foundation.mozilla.org/en/campaigns/paid-programming/). Password protected for now.
- [x] Grid overview with all grades (as per chat in Slack with Becca). DONE: [graphic here](https://redpen.io/hs695c30ae2bae008b)
- [x] Image for Kevin: all logos + text " Paid Programming: Investigating streaming ads during the election season". DONE: [mockup here](https://redpen.io/abae1fca0deae260e1)

**Comment by kristinashu** [comment]
Since this is related to elections and tv ads, maybe it could be styled similar to misinfo mondays - which is also election related and has a tv vibe! cc @natalieworth @sabrinang

**Comment by kristinashu** [comment]
Update: 
- Check-in with Kaili and Rebecca R before starting to confirm graphic style direction and dimensions needed
- They plan to use this template version https://foundation.mozilla.org/en/campaigns/streaming-campaign-v4/ (please update the url before launch and delete and the other test pages)
- Rebecca R is adding copy this week
- Ideal deadline is Sept 4 but confirm with Kaili and Rebecca R
- This will appear on the elections hub https://foundation.mozilla.org/campaigns/elections/

**Comment by kristinashu** [comment]
Launch is pushed back to Sept 22

**Comment by taisdesouzalessa** [comment]
- [ ] Check-in with Kaili and Rebecca R before starting to confirm graphic style direction and dimensions needed
**Status:** done. Got the brief of "look and feel" with them both today.

- [ ] Deadline for design review of the page: Sept 16 (EOD)

- [ ] Deadline for the other assets: Sept 18 EOD. Got specs with Kaili today. 
• snippet specs [here](https://docs.google.com/presentation/d/1zhAyQo1kGxywO8KLxh2CGt1meIyP0o8uleaF0fiXs6Q/edit#slide=id.g7824f655ac_0_132) and "Try to keep your images as close to 1.91:1 aspect ratio as possible to display the full image in News Feed without any cropping."
• email specs were sent by email

**Comment by taisdesouzalessa** [comment]
Did illustration and table today. Received new feedback that will be addressed tomorrow.

We may have some leftover Monday work as companies will have time to respond over the weekend, which may affect some of the grades.

**Comment by taisdesouzalessa** [comment]
All promo assets are in [Google Drive](https://drive.google.com/drive/folders/1WUa5BA5BkgjV5o0SKrzFry15_dS9dFfv?usp=sharing)

- Social (Promote tab) 
- Email
- Blog 
- Snippet Icon

**Comment by taisdesouzalessa** [comment]
Did QA of live site today. Closing this ticket. 
Will reopen if any other issues surface but I don't expect that to happen.
