### ISSUE TITLE
Audit which ia-refresh changes to the homepage still require factory code

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#4981]
we skipped the factory code changes for a number of changes to the homepage, leading to review apps having a homepage that requires quite a few things to be updated before you can publish what you _actually_ wanted to change.

@mmmavis @KalobTaulien this is more of an inconvenience than anything, so let's get this done but not necessarily before we finish up the front-end work =)

**Comment by KalobTaulien** [comment]
Updating based on what I just found, there may be more than this:

- [ ] Area of focus orderables (need 3; plus the factory on the snippet itself) 
- [ ] News you can use: needs 4 blog posts. 
- [ ] Take action: Needs 4 orderables with pages

**Comment by KalobTaulien** [comment]
News you can use is being taken care of in #4993  https://github.com/mozilla/foundation.mozilla.org/pull/4993/files#diff-8b27edd0621ac9f63cca1144336e92b9 

Areas of Focus, Spotlight and Take Action are covered in #5024
