### ISSUE TITLE
YouTube Regrets Page - intro images are stuck at top

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#4982]
**Describe the bug**
Images in [YouTube Regrets page](https://foundation.mozilla.org/en/campaigns/youtube-regrets/)'s intro section are stuck at top and no longer move as users scroll the page.

**To Reproduce**
1. Go to https://foundation.mozilla.org/en/campaigns/youtube-regrets/
2. Scroll down to see if the images in intro section move/animated
3. Bug: Images are stuck at top and no longer have the "moving into user's eyes" effect

**Expected behavior**
Images should have the "moving into user's eye" effect as user scrolls down the page

**Screenshots**
![Screenshot_2020-07-28 YouTube Regrets](https://user-images.githubusercontent.com/2896608/88695480-d4bcf500-d0b6-11ea-8801-5e99d8170740.png)

**Desktop (please complete the following information):**
I'm able to reproduce this issues on Firefox, Chrome, and Safari on Mac.

**Additional context**
Percy screenshot for the YouTube Regrets page seems fine though. So worth looking into why.
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/2896608/88695799-3e3d0380-d0b7-11ea-8135-897d5eb294ca.png">

**Comment by Pomax** [comment]
I can't seem to reproduce this locally at all, even with webpack set to build for `production` rather than `development`. What are the steps to reproduce what is happening on the foundation site?

**Comment by mmmavis** [comment]
postcss is triggered by `build:sass` and not by `webpack`. I just temporarily modified https://github.com/mozilla/foundation.mozilla.org/blob/master/postcss.config.js to make it use `cssnano`. Running it with production mode on should work too.
