### ISSUE TITLE
Implement character limit on Blog titles

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#4984]
For the new homepage refresh we've decided to implement a character limit on blog titles (across the whole Foundation site). 

**Reasons:**
- To keep the design clean and easy to read
- Shorter titles are easier to scan and more digestible to novice users

## List of Requirements
- [ ] Come up with strategy for existing blog posts over 80 characters
- [ ] An error is triggered if a user tries to save a blog title with over 80 characters
- [ ] Implement help text that prompts English language authors to keep titles to 60 characters (80 characters is to accommodate for localization). 

**Proposed help text:** 
>For authors posting in English, please keep blog title to 60 characters to accommodate for localization.

**Proposed error text:**
>Please keep blog title to 80 characters

**🗒  Design -> Dev Handoff Checklist**
(Feel free to remove items that are not applicable.)

- [x] Design has been finalized
- [x] Link to original design ticket:  #4847
- [x] Link to related ticket:  #4847
- [x] Link to Redpen: https://redpen.io/p/fhf15adfe8d37eb89a
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Other states for elements are designed (e.g., error state for form)

**Comment by kristinashu** [comment]
cc @cadecairos for triage

**Comment by jamilasnell** [comment]
@kristinashu Would you be able to give guidance around what should happen to current titles with more than 80 characters?

**Comment by kristinashu** [comment]
Existing titles are fine as is. Limit can just be fore new or edited titles.

**Comment by mmmavis** [comment]
@KalobTaulien need some pointers here. `title` is coming from `Page` so I don't know how to properly override it so `title` of `BlogPage` has 80 character limit. Also wondering if enforcing character limit will invalidate existing blog title that are longer than 80 characters? If so, how do we resolve tthis issue?

**Comment by KalobTaulien** [comment]
@mmmavis The easiest way to do this would be to add a new "Bog Title" field (`CharField(max_length=80` for example). Then we can create a custom page property to check if there is a new Blog Title. Something like this:

```python
 class BlogPage(Page):
    blog_title = models.CharField(max_length=80) 

    @property 
    def get_title(self):
        return self.blog_title if elsself.blog_title else self.title 
```

This would prevent pages from being re-saved without a proper blog title, but support older pages that have longer titles. For the longer titles, we probably want to truncate the blog title to something like 14 words (5.5 chars per word, divided by 80 max — I guessed the 5.5 chars per word average) 

Then if we wanted to get a little fancier, we can do two things (but these would be better in separate tickets) 
1. Create a data migration that will copy all title fields into `blog_title` fields and cut it off at 80 characters this way every page has a blog_title moving forward. 
2. Overwrite the `Page.title` help text so it doesn't say something like "This is the title that you will see in your blog post". For that, we can write some crafty Python:
```python
BlogPage._meta.get_field("title").help_text = "The title you will see in your Wagtail page explorer"
```

**Comment by mmmavis** [comment]
@KalobTaulien I have a WIP PR up but after trying it out myself, I think having two title fields (`title` and `blog_title`) will confuse CMS users. Although we have 80-character limit on the `blog_title` field, it is marked as an optional field so I wonder if users will still choose `title` over `blog_title`. Another issue I bumped into is about meta tags. Do we override `wagtailmetadata_tags` somehow so only the BlogPage's meta title is handled differently?

**Comment by benhohner** [comment]
Create List of potential solutions and discuss with a designer
- [ ] @mmmavis 
- [ ] @Pomax 
- [ ] @danielfmiranda 
- [ ] @KalobTaulien 

https://docs.google.com/document/d/15p2r4mKZn76raj8eqv-UadFNFP_6y1jSpscEZtOGWaU/edit?usp=sharing

**Comment by mmmavis** [comment]
@kristinashu could you go over our suggestions in the [doc](https://github.com/mozilla/foundation.mozilla.org/issues/4984#issuecomment-799745882) and let us know if you have any questions?

**Comment by kristinashu** [comment]
I like the first solution "Create a JavaScript snippet that counts down the remaining characters when entering a title. Turns red when its over 60 characters to provide a visual cue that the title is getting too long." This feels like a nice way to make staff aware of the issue but without forcing it and potentially causing Theo headaches.

**Comment by benhohner** [comment]
@benhohner @kristinashu to discuss solution

**Comment by benhohner** [comment]
Create follow up issue after we discuss

**Comment by benhohner** [comment]
The deciding is done! 

"Create a JavaScript snippet that counts down the remaining characters when entering a title. Turns red when its over 60 characters to provide a visual cue that the title is getting too long." (similar to Twitter)
