### ISSUE TITLE
[AI White Paper] - Reader's Digest Blog Post

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#4985]
### Intro
A blog post that is an abridged, executive summary version of the AI white paper. This will link to the upcoming [consider.it platform](https://mozilla-trustworthy-ai.consider.it/?tab=FAQ) to collect feedback from people that will go live end of next week and may also link to the existing [google form](https://docs.google.com/forms/d/e/1FAIpQLSemkMhbjhtugjHUjxVwS0XlAkBlaP-prOm3pUsELPKjkXjupQ/viewform?usp=sf_link) to collect more in-depth feedback.

- Mockup draft in wagtail to preview length, if it is too long consider breaking up length
- Collab with Sarah W and Becca R on format

**Note:** This may be part of a series so we can consider a blog category tag but we can also do this retro actively later too. 

### Links
Content in progress here: https://docs.google.com/document/d/14ZgK8HhBRZYy7RY6v9xCUDUbczDoSdgC37_EWKQAj7U/edit?usp=sharing

cc: @phildexter

**Comment by kristinashu** [comment]
Note: Sarah W and Becca R might need to be on-boarded to wagtail first

**Comment by beccaklam** [comment]
Blog draft: https://foundation.mozilla.org/en/blog/trustworthy-ai-abridged-version/

**Comment by beccaklam** [comment]
On boarded Becca R to wagtail yesterday. Discussed creating graphics for the TOC medium outcomes for the blog post and beyond. First draft of graphics: https://redpen.io/p/db241955dbe19001fa

**Comment by beccaklam** [comment]
Becca R, Sarah W and Abby are good with the graphics above. Will mock up a header image for Abby that can be reused for this blog post.

**Comment by beccaklam** [comment]
Header image here: https://redpen.io/mcd6255e334bdaf5a5

**Comment by kristinashu** [comment]
Looking good!

**Comment by beccaklam** [comment]
Blog post awaiting approval from Sarah and Becca: https://redpen.io/vbb40edd51f8d13275
Once approved I'll make the OG image and ask Audrey what social assets she needs. @kristinashu

**Comment by kristinashu** [comment]
Awesome, illustrations are perfect!

**Comment by beccaklam** [comment]
Sarah and Becca are good with the blog post and I've created the OG image: https://redpen.io/ge5b9154eec78c0317

**Comment by beccaklam** [comment]
Everything has been uploaded to the blog post. This should be done. I've uploaded all my files onto our google drive as well: https://drive.google.com/drive/folders/17sFOrgQHZcADxamSpeEI6wCCJ0Q2rwaj?usp=sharing
