### ISSUE TITLE
[AI White Paper] - Social Outreach

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#4986]
### Intro
Related to #4985, the blog post and consider.it platform would like to be promoted on social media particularly on LinkedIn and Twitter. This is still in planning but may not need design assets if posts are polls/prompts only.

### Links
End of this doc has social ideas: https://docs.google.com/document/d/1c1oMp3l_C2Dmk6t-7bzQulZ9yaN770CvmOdSiBB0wiE/edit

cc: @phildexter @Audreymofo

**Comment by beccaklam** [comment]
Audrey just needs a good preview image for the blog post.

**Comment by beccaklam** [comment]
OG image has been put into the promote page of the AI White Paper blog post. Audrey says that's all she needs. This should be done!
