### ISSUE TITLE
Audit style overrides

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#4988]
Our codebase now has style overrides that we gradually added in over the past few months. The new homepage also introduces many style overrides. Off the top of my head, I think they are mostly font style related. Before our pool of overrides becomes too challenging to maintain again, it would be useful if we can set time to 

1. audit existing style overrides (both in code and Sketch)
2. devs and designers meet to discuss what should stay as bespoke styles and what should be turned into a brand style
3. update codebase / Sketch file to reflect changes

**Comment by Pomax** [comment]
We've done a lot of styleguide and CSS updates since this issue, effectively doing what this issue was hoping to get done.
