### ISSUE TITLE
[Backend] redo the work for "Areas of Focus"

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#4989]
redpen: https://redpen.io/p/bn82314af4898269e1

The areas of focus backend needs to be modified a little bit to match a design change: each area of focus should have an _optional_ link to an internal page, which means we need the following backend changes:

- [x] un-mixin the area of focus because it no longer needs `UniversalLink` functionality
- [x] add a `page` foreignkey to `Wagtail.Page` with a PageChooser, with `null=True`/`blank=True`

And probably:

- [x] rename the `AreaOfFocus` model to `HomepageFocusAreas`
- [x] audit the code to see if we should delete the UniversalLink code again. If nothing else uses it, it might not make sense to keep it around
- [x] add factory code for the homepage that builds the three areas of focus and links them:

#### Empower Action
image: source/images/homepage/area-of-focus/01_empower-action-icon.png
description: Issues like privacy, trustworthy AI, and digital rights impact all of us. Mozilla helps empower meaningful 

#### Connect Leaders
image: source/images/homepage/area-of-focus/02_connect-leaders-icon.png
description: We support activists and thought leaders shaping the future of our online lives.

#### Investigate & Research
image: source/images/homepage/area-of-focus/03_investigate-research-icon.png
description: We publish open source research and host global convenings to make ideas like trustworthy AI mainstream.

**Comment by Pomax** [comment]
Frontend work for this has mostly been done already in https://github.com/mozilla/foundation.mozilla.org/pull/4990, and should work with the changes effected by this issue's work.

**Comment by mmmavis** [comment]
Can this [request](https://github.com/mozilla/foundation.mozilla.org/issues/5025) be addressed as part of this ticket as well? 🥺

**Comment by KalobTaulien** [comment]
We need a new reviewer since Pomax and I have both been working on this PR. @mmmavis any chance you have time to review this? 

Note: I need to rebase this branch again.

**Comment by Pomax** [comment]
https://github.com/mozilla/foundation.mozilla.org/pull/4990 got merged in.
