### ISSUE TITLE
Source non-evergreen homepage content

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5019]
Tais and Xavier to update content before we launch our **new** homepage!

**To do (edited by Taís):**

- [x] decide content for
- Hero CTA
- News you can use section
- Spotlight theme name & posts
- Feature actions

- [x] find images for chosen content
- [x] update staging and final page with content chosen above

**Comment by taisdesouzalessa** [comment]
Yay! Do we have a launch estimate? So I can fit this item into my weekly meeting with Xavier in the week of launch :)

**Comment by taisdesouzalessa** [comment]
Talked to Xavier and he will bring this up to content team to decide what news should be in this launch. He will also connect with Jon to see if there is any upcoming campaign we can highlight in the hero section. 
Estimated time for content to decide what to add there: Aug 18
Estimates time for Taís to make sure we have the images we need to accompany content: Aug 20
Aiming for launch on Aug 24th.

**Comment by taisdesouzalessa** [comment]
Here is the WIP doc with suggestions of content for the launch. It has been seen and updated by Xavier and Anil:
https://docs.google.com/document/d/1JIHSsA7UUWZWjpIFIR9b2XwxLlotC4KUApA-tr0uFo4/edit?usp=sharing

Nat will work on adjusting the hero image (described on this ticket: #5090)

**Comment by taisdesouzalessa** [comment]
The document linked above has been revised and discussed by Taís and Xavier. Xavier touched base with Jon and we all agree the hero image should remain the current main campaign (Nextdoor). 

Tagged Anil to see if he has any feedback on the chosen content and we will adjust it if needed.

**Comment by taisdesouzalessa** [comment]
Anil is okay with suggested content. [Final doc here](https://docs.google.com/document/d/1JIHSsA7UUWZWjpIFIR9b2XwxLlotC4KUApA-tr0uFo4/edit?usp=sharing).
 
Leaving this ticket open as it should also include to update the content on the final page.

**Comment by taisdesouzalessa** [comment]
All done here! \0/
