### ISSUE TITLE
[Bug] Blog author text no longer shows on the page

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5023]
**This is currently happening on the new homepage branch, and not production.**

I'm guessing this is due to the recent blog (author) model change and that we forgot to update the template code to reflect that.

### Case 1. On blog index page. (`/blog`)

<img width="437" alt="image" src="https://user-images.githubusercontent.com/2896608/89442857-5be81980-d704-11ea-97b3-16a9926ff3fa.png">

Author info is missing in the highlighted line. It should read `By [author] on Aug. 4, 2020`

### Case 2. On blog post page.

<img width="610" alt="image" src="https://user-images.githubusercontent.com/2896608/89443254-e466ba00-d704-11ea-878d-17515afa7b20.png">

It should read `By [author] | Aug. 4, 2020 | Advocacy`

**Comment by mmmavis** [comment]
@kristinashu blog author info used to be one text field in CMS (currently on prod). As part of the new homepage work, we now have each author as an object ( each with `name` and `image`). Do you know how we want the blog author info to appear on the two scenarios above?

**Comment by kristinashu** [comment]
Yes! @beccaklam mocked them up here https://redpen.io/p/dn2ff4a99909ffc5b7

**Comment by mmmavis** [comment]
@beccaklam is this the section I should be referring to in the Sketch file?

<img width="195" alt="image" src="https://user-images.githubusercontent.com/2896608/89930574-d068ff80-dbbf-11ea-8530-d044cd22dcff.png">

**Comment by beccaklam** [comment]
@mmmavis yes!

**Comment by mmmavis** [comment]
Done
