### ISSUE TITLE
Consider separating primary_heroguts.html into different fragments

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#5039]
In the `primary_heroguts.html` file there's a check for `{% if homepage %} .. {% else %} .. {% endif %}` 

It'd be nice to see us split this out so we don't need to check the page type in the template. Though I understand this might not be completely possible without running into CI issues (Percy). 

Can we explore this and determine if this is worthwhile, or if we should keep the page type check in the template? 

CC: @Pomax

**Comment by Pomax** [comment]
closing as stale
