### ISSUE TITLE
Address issues with CSS "object-fit" property on IE

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5040]
@KalobTaulien made a [good point](https://github.com/mozilla/foundation.mozilla.org/pull/5021/files#r467913558) that `object-fit` [isn't supported on IE](https://caniuse.com/#search=object-fit). There are a few [`object-fit` instances](https://github.com/mozilla/foundation.mozilla.org/search?q=object-fit&type=Code) in our codebase and I wonder how we want to handle them. 

Some stats: GA shows that 1.2% of our site visitors are on IE.

**Comment by cadecairos** [comment]
Are we committed to supporting old versions of Internet Explorer? According to that caniuse link, we're talking about 1.6% of global internet users on some version of IE that doesn't have `object-fit`.

If it's a lot of work to implement a workaround that supports IE 11 and earlier, then I'm not sure we should bother unless we have data suggesting a significate portion of our traffic is on IE.

**Comment by Pomax** [comment]
We've decided in favour of "we don't support IE" pretty much ever since Edge got hard-pushed by microsoft. As long as it works at all on IE11, we don't want to invest time into making IE11 actually look "the same".

**Comment by Pomax** [comment]
closing, but adding @KalobTaulien just to have it speed by his inbox.
