### ISSUE TITLE
Continue PNI Privacy Criteria Work

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#5043]
Continued from #5014
[Content](https://docs.google.com/document/d/1MYmz5WKfKEG_Rv8G03zc2nMFq57WWHHxiyUZ5Kaoj1E/edit) from Jen
- [x] Make changes based on first draft of feedback from Jen
- [x] Round 2 ~or finalize design~ for product page
- [x] Round 2 ~or finalize design~ for badges on homepage 

cc: @kristinashu

**Comment by beccaklam** [comment]
Feedback to work on this sprint:

**Homepage:**
- Jen is okay with removing MSS badge from homepage
- [ ] Really emphasize "*privacy not included"

**Product Page:**
- [ ] Jen would like “privacy not included ding" to be very boldly and obviously labeled. Goal: User immediately knows this products sucks for privacy
- [ ] Explore if we can add more hierarchy, colour coding, larger text and bolder headers
- [ ] Add back in "Can it snoop" section

**Comment by beccaklam** [comment]
Designs are here: https://redpen.io/p/as0fadff5c9a9d87b1
Sent for review from Jen

**Comment by kristinashu** [comment]
This work can be finalized next sprint in:
- PNI: finalize design of the privacy ding #5151
- PNI: finalize the product detail page design #5152

**Comment by beccaklam** [comment]
Thanks @kristinashu ! Not sure if I should close this so I'll leave it to you but it's good to close form my end :)
