### ISSUE TITLE
Analytic events and baseline tracking for homepage: implementation

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5048]
Design ticket: #5000

**Here are the recommendations for things we should track in our homepage:**
• [GA - Tracking spreadsheet](https://docs.google.com/spreadsheets/d/1GFmZXZu6R9aUygeBLDONODt7-GwwwIz7ioNP70o3mfY/edit?usp=sharing)
• Here are the events we should track for the homepage: [Analytics Site Events spreadsheet ](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit?usp=sharing)(lines 30-35) - I did my best to replicate the model Matthew had

@mmmavis when you have some available time could you please:
1. Give me feedback on the things I plan to track (first bullet point above)? Feel free to comment on the spreadsheets or we can chat if you prefer
2. Add the events to the new homepage buttons and test them (second bullet point above)?

**Comment by cadecairos** [comment]
I doubt we have the time this sprint to work on analytics events. If this can't get picked up this time we'll assign it on the next sprint.

**Comment by taisdesouzalessa** [comment]
Thanks for the heads up here, Cade!

**Comment by cadecairos** [comment]
Targeting second half of Sept 14th sprint.
