### ISSUE TITLE
[Publications] Design Mockups

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#5051]
Create mockups / comps to refine the designs of the publication template and components needed. The mockups can have various screen sizes iterations to work out responsive design considerations as well. This can be accompanied by a clickable prototype to help showcase the interaction and flow between the screens.

### Related Links
#4997 Wireframes 
#4950 Benchmarks

**Comment by sabrinang** [comment]
I separated mockups in this presentation: https://docs.google.com/presentation/d/1fXFcilVTCgp4ngHSOA5Atm31eCQe2ocOkYKsrbkDhUg/edit?usp=sharing

To see the images full size and to leave specific comments, see redpen: https://redpen.io/p/hef0b91baad73367ea

To view mockup specs / sketch design file, view on abstract app: https://app.abstract.com/invitations/3232590ea77576b3eee5d4dd40f3950c6c5a2fab5447b6347c140065f60b6ae8

**Comment by easherma** [comment]
Thanks, @sabrinang ! I would love to view on abstract, but it is saying I need an email address with a mozilla foundation domain.

**Comment by sabrinang** [comment]
@easherma ah I changed permissions you should be able to access from your torchbox email now

**Comment by sabrinang** [comment]
Sketch files are updated, please view via Abstract.

Presentation updated: https://docs.google.com/presentation/d/1fXFcilVTCgp4ngHSOA5Atm31eCQe2ocOkYKsrbkDhUg/edit#slide=id.g25275a8168_0_425

Note: Redpen are NOT updated.

______________

I've updated publication table of contents number only to have colour behind the square when image is not present; this is the same for chapter table of contents as well. I've updated the article summary to be at the top of the body to be seen and when user scrolls pass it, it becomes the sticky nav (it will be seen in full and not squished in side column). Regarding social buttons, the side social buttons will only been seen at the top (not sticky along page scroll) and seen as buttons at the bottom of the page above next/previous buttons.

**Comment by sabrinang** [comment]
@easherma In the [presentation](https://docs.google.com/presentation/d/1fXFcilVTCgp4ngHSOA5Atm31eCQe2ocOkYKsrbkDhUg/present?token=AC4w5VjG-BPVjPyJRA59h1DvUVMMt0pjsQ%3A1598918077211&includes_info_params=1&eisi=CL_xkYDSxusCFdKOIwAd5j4Ebg#slide=id.g938599712a_1_2) I included motion mockup for reference that can help visualize the interactions on the article page to help with https://github.com/mozilla/foundation.mozilla.org/issues/5143#issuecomment-683951835 but the subnav dropdown bar is mvp

![Publications - Sub Nav Mockup](https://user-images.githubusercontent.com/2492510/91779434-66ce8680-ebaa-11ea-9971-9bd20cc76aeb.gif)

**Comment by sabrinang** [comment]
I'll continue dev support on https://github.com/mozilla/foundation.mozilla.org/issues/5159 for the next sprint but mockups are complete afaik — closing.
