### ISSUE TITLE
Create new ticket template for engineers implementation

### ISSUE THREAD

**Issue by phildexter** [mozilla/foundation.mozilla.org#5064]
Often engineers contact the wrong designer for help on a ticket because it's confuisng who work on the designs. 

To make this easier we will create a new template to be used for creating implemation tickets.

**Comment by easherma** [comment]
If it's helpful (and it might not be related or may be overkill), I've written and used this template in the past: 
https://raw.githubusercontent.com/cityofaustin/resource-list/master/.github/ISSUE_TEMPLATE/issue_with_user_story.md
