### ISSUE TITLE
D&I Disclosure Graphics

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5067]
**Background:** 
we will release a blog post with our D&I disclosure and we have some graphics on it that need to be aligned with our brand style.

**To do:**
- [x] update graphics (8 in total so far) with "on brand" style. Sarah Swayze will share a folder with design team with the graphics to be updated
- [x] create a cover image as an intro to the blog post to motivate people to read it.

**Deadline:**
Ideally Thursday (Aug 20, mid-sprint) - let me know if it feels too rushed and I can talk to Sarah about alternatives

**Comment by beccaklam** [comment]
@taisdesouzalessa Talked to Sarah and she's okay with changing the deadline to Monday, August 24 for this.

**Comment by beccaklam** [comment]
Cover image here: https://redpen.io/hs4a8bc46792664669
Not sure if I can share the google sheets doc on github but I've updated the charts and will share with Sarah on Monday for feedback :)

**Comment by beccaklam** [comment]
This is done, graphs are in the excel sheet Sarah shared with me which for privacy reason I don't think I can share here. But here are two screen caps:
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/3bb48701-459d-4ffc-bc20-e88facc702e2)
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/f99f5241-9246-4b5f-a74d-ee2aeb5ff8ff)

**Comment by beccaklam** [comment]
Blog post image, OG image and illustrator file is on the drive here if needed: https://drive.google.com/drive/folders/1CZehE6kplm0O3jXcXIePA4lJcjQEK5pU?usp=sharing

**Comment by beccaklam** [comment]
This should be good to close!
