### ISSUE TITLE
Publications | Publication chapter page template

### ISSUE THREAD

**Issue by phildexter** [mozilla/foundation.mozilla.org#5072]
-   New page template called Publication chapter page
-   Available anywhere
-   Only child page available is Publication article page
- Use blog page header and footer

**Comment by easherma** [comment]
We need to figure out in what ways chapter page differs from publication page, and whether that requires a different model vs template level or other rules. 

i.e. if a publication page is a child of a publication page, is it a chapter page? Or is that too clever.

**Comment by easherma** [comment]
@sabrinang says: 

I'll be exporting and uploading updated ones by noon and link to you.
I don’t think there are many practical differences, the differences I see are:
* Hero Area: includes breadcrumb nav and most likely includes less info than its publication page
* Body: excludes Table of Contents Heading and chapter listing styling is slightly different (smaller numbers/image space) but more or less it's the same

**Comment by easherma** [comment]
@phildexter I think its pretty settled that we don't need another model or template for chapter pages. But we could leave this open until the publication template properly handles chapter pages as well as publication page. 

Best I can tell, current definition of a chapter page is 'publication page that is a child of a publication page'.

**Comment by phildexter** [comment]
I agree exactly. 

This implementation also offers up the ability for going even deeper (Publication > Publication > Publication > Article)

I genuinely think we'll get use cases like this - not for the entire book, but that at some level people will find a need where it makes sense to keep splitting things in this way.

I think we should aim to just make those hero elements optional.

**Comment by easherma** [comment]
Yep, they will be optional and not displayed if empty. At least thats the plan. 

It might make sense to come up with a more intuitive name than Publication page if they are expected to be nested...open to ideas on what the authors would call it.

**Comment by easherma** [comment]
I think this is safe to close now that we've discussed with the whole team + stakeholders. @phildexter feel free to resurrect if you see a  need.
