### ISSUE TITLE
Publications | Make article page model + template exist

### ISSUE THREAD

**Issue by phildexter** [mozilla/foundation.mozilla.org#5073]
- New page template called Publication article page
- Available anywhere
- No child pages available
- Use blog page header and footer

**Comment by easherma** [comment]
@phildexter are we sure we want this content type available anywhere, not just as a child of publication pages/chapters? Are there plans to let people use the content type elsewhere on the site?

**Comment by phildexter** [comment]
I think so, but not 100%. 

In the slides on page 10 the AI whitepaper is coming directly from a different page type (Bannered page).

However on the revised wireflows (slides 4-7) it's not doing that at all. Which makes me think we don't have a use case for it at this point. Which makes me think we shouldn't do it.

@sabrinang can you let us know your thoughts on this?

I feel like a benefit of making it only available as a child of publication pages would be that it would increase consistency across the site. Article pages used for what they are designed for, blog pages used for what they are designed for.

**Comment by easherma** [comment]
I agree with that benefit. The site isn't huge, but in general it could get hard to keep track of or control where else it might get used. 

Also I reckon in the above case you could still link to the page from a bannered page (though wouldn't you link to the root publication page?), I'd imagine there is a page chooser interface on that page but I could be wrong.

**Comment by sabrinang** [comment]
+1 I agree with the points as well, that it should be together to make it consistent and if the content is short enough to be linked directly than that makes sense that blog pages should be used for that purpose.

To clarify, I think in the earlier slides it had the two ways methods described: 
1. linking to article directly from wagtail landing but after we discussed that it was 70+ pages it would make the load/page and summary really long so we should break it up and go with that alternative approach for a better experience
2. breaking up the paper into sections for shorter article pages so then it would need a publication landing to show its contents with ToC overview. Initially I thought of this as a chapter page but in the revised flow it made sense to just be the publication page as it is the only parent page.
