### ISSUE TITLE
Publications | Publication page | FE

### ISSUE THREAD

**Issue by phildexter** [mozilla/foundation.mozilla.org#5075]
Hero section of publication page, including:

- Hero image
- Title
- Sub title
- PDF download
- Secondary subtitle
- Publication date

As per field spec for these fields.

---

###  Design -> Dev Handoff Checklist

- [ ] Design has been finalized
- [ ] Link to original design ticket
- [ ] Link to related ticket
- [ ] Link to Redpen
- [ ] Design changes been merged into the master Sketch file
- [ ] Desktop and mobile mockups are included
- [ ] Assets are included
- [ ] Hover state for elements are designed
- [ ] Other states for elements are designed (e.g., error state for form)

**Comment by easherma** [comment]
We can break this into smaller issues if desired, but at least here's a brain dump of a list for how I'd tackle this. 

- [ ] Make each element of the page exist as part of the template, without worrying about layout or styling. 
- [ ] Get the general containers of each element conforming to spec (brush up on breakpoints for the project, etc)
- [ ] Add styling, following existing page templates and CSS as a guide (if there is a description or contributing guide for frontend stuff let  me know)
- [ ] Make sure image handling is good, with sensible defaults
- [ ] Double-check if there are any client-side interactive bits that need to be created via Javascript
- [ ] Make sure the language, copy confirm to specs or other content guide, and are configurable where it makes sense to (ideally with sensible defaults)

**Comment by phildexter** [comment]
This is now superceeded by Publications | Chapter + Article Pages Template | Frontend #5141
