### ISSUE TITLE
Publications | Publication page | Authors

### ISSUE THREAD

**Issue by phildexter** [mozilla/foundation.mozilla.org#5076]
Front and backend for authors section in the hero as per design and field spec.

###  Design -> Dev Handoff Checklist

- [ ] Design has been finalized
- [ ] Link to original design ticket
- [ ] Link to related ticket
- [ ] Link to Redpen
- [ ] Design changes been merged into the master Sketch file
- [ ] Desktop and mobile mockups are included
- [ ] Assets are included
- [ ] Hover state for elements are designed
- [ ] Other states for elements are designed (e.g., error state for form)

**Comment by phildexter** [comment]
We can take some of the new homepage work for this - suggest Kalob does this one.

**Comment by KalobTaulien** [comment]
Update: Blocked until Homepage work is merged into master. There's Author migration work in there (authors as snippets) we'll want to build off of).

**Comment by KalobTaulien** [comment]
Technically this is blocked, but I'm going to steal some work from the Homepage refresh branch, and delete the stuff I steal before I rebase off master when homepage lands. It'll duplicate work a tiny bit but would help us finish this ticket in this sprint.

**Comment by KalobTaulien** [comment]
Blocked: We need to decide how authors are being pulled into the Publication Page. 

Are they:
* Being pulled in from the Article Pages automatically?
* Manually added to each Publication Page? 
* Manually added, but if not provided then automatically pull in from Article Pages?

@kristinashu or @sabrinang — thoughts?

**Comment by easherma** [comment]
Option two it was.

**Comment by easherma** [comment]
New blocker though, regarding frontend: 
@kristinashu @sabrinang 
The current code is borrowing from blog authors. 

However for publication pages, authors are optional. 
* should we assume authors section just isnt shown at all if there are no authors?
* the blog has hardcoded copy `Written by <authors> with contributing authors`. Just to confirm we'd want this same copy for publications? In which case its up to ya'll if you'd want some sort of fallback of 'Written by contributing authors' if no specific authors are selected.

**Comment by sabrinang** [comment]
> - should we assume authors section just isnt shown at all if there are no authors?

Yes, if there are no authors do not show author section at all.


> - the blog has hardcoded copy Written by <authors> with contributing authors. Just to confirm we'd want this same copy for publications? In which case its up to ya'll if you'd want some sort of fallback of 'Written by contributing authors' if no specific authors are selected vs the above bullet point.

Some publications will not have `with contributing authors` I believe so just having`by <author>` would be the most versatile but could we include an option where where we could include `with contributing authors`?  If left empty, the fallback again would be not to show the author section.

**Comment by easherma** [comment]
OK, in that case IMO it probably makes the most sense to not have that additional hardcoded copy for MVP. It's something we can bring up with stakeholders/if they ask for extra language it wouldn't be too hard for a dev to add, but its something we can go without for now and match the design spec.

**Comment by KalobTaulien** [comment]
Status: Awaiting final re-review.
