### ISSUE TITLE
Publications | Chapter table template

### ISSUE THREAD

**Issue by phildexter** [mozilla/foundation.mozilla.org#5077]
As per designs and as per field spec for chapter table title field.

Note: Designs show the author underneath the title of each chapter. We discussed this and it's actually going to be Chapter title with Article page titles underneath, as that's more interesting to users (we assume).

###  Design -> Dev Handoff Checklist

- [ ] Design has been finalized
- [ ] Link to original design ticket
- [ ] Link to related ticket
- [ ] Link to Redpen
- [ ] Design changes been merged into the master Sketch file
- [ ] Desktop and mobile mockups are included
- [ ] Assets are included
- [ ] Hover state for elements are designed
- [ ] Other states for elements are designed (e.g., error state for form)

**Comment by easherma** [comment]
This is primary going to be done in templates via parent --> child relationships. Querysets FTW

**Comment by KalobTaulien** [comment]
PR is #5131 — does not include polished frontend code. Only includes some basic frontend work.

**Comment by easherma** [comment]
Kalob and I worked out a solution for the backend and template, all that is left is styling.

**Comment by KalobTaulien** [comment]
I'm going to look for (and create, if needed) a ticket for the frontend work. This ticket is complete.
