### ISSUE TITLE
Ensure all the headings on the new homepage use the correct style.

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5083]
We'll want to do a QA pass once the homepage is fully merged, to make sure that things that should have the same style, all have the same style.

**Comment by taisdesouzalessa** [comment]
Thank you for this ticket, it is a good reminder :). Linked this ticket to our master QA list Kristina had written \0/: https://github.com/mozilla/foundation.mozilla.org/issues/5050

**Comment by taisdesouzalessa** [comment]
QA done and notes on #5050. Closing this ticket.
