### ISSUE TITLE
unhardcode the `/blog` route

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5085]
We rely on the blog posts always living on `/blog`, which means that if someone renames that (e.g. to `/news` or the like), everything that relies on the blog route for  streamfield etc. will break =(

Also note that renaming the `/blog` route means that every single link to blog posts in search engines will break, so while it'll be nice to fix this "bug", it's arguably more important to resist the temptation to change the route name. Unless we're somehow losing money by keeping it names "blog", we shouldn't be renaming that route.

**Comment by Pomax** [comment]
still relevant, especially given the upcoming blog redesign.

**Comment by mtdenton** [comment]
If the subdirectory ever changed, we could indicate this change to search engines. That being said, we have no plan to do this now, next, or later, so I'm marking this for purge.
