### ISSUE TITLE
Remove/consolidate dev docs on localization

### ISSUE THREAD

**Issue by easherma** [mozilla/foundation.mozilla.org#5088]
This file: 
https://github.com/mozilla/foundation.mozilla.org/blob/master/README-FOR-WAGTAIL-LOCALISATION.md 

Contains some useful links and info on how localization is handled. 

However, much of it is out of date and no longer accurate. Let's get rid of the file, and see if there's any useful content in it that can be incorporated in the development docs.

**Comment by Pomax** [comment]
PR landed
