### ISSUE TITLE
Hero image: homepage refresh

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5090]
**Background:**
We will feature the "[Nextdoor: Pause Police Partnerships](https://foundation.mozilla.org/en/campaigns/nextdoor-pause-police-partnerships/)" campaign in our homepage refresh launch. This campaign will be placed in our hero section. 
The current image has the following dimensions: 1280 X 720px. The [refreshed version of the homepage](https://redpen.io/pa964c89dd9ed67af9) has a full bleed in the hero section so we need to adjust the proportions to make sure it looks impactful in the new format.

**To do:**
• Modify the image so the final size is 4032 X 480px

**Deadline:**
Aug 20

**Notes:**
• Please timeblock this task, we don't need to put too much effort on it.
• Please consider space for the copy, which is left aligned
• The system already adds a black layer on top of the illustration (55% opacity) to increase legibility
• You can upload the image on the [CMS here](https://homepage-refresh.mofostaging.net/en/) to test how it looks on different screen sizes
• 1920x1080 is a common big screen resolution for our audience, it is a good "average big size" to test.

**Comment by natalieworth** [comment]
I got a [start on this here](https://redpen.io/p/qu9164c16e20cdd9a1) @taisdesouzalessa 

Working [file and export are in here](https://drive.google.com/open?id=1S-dPBWQ7auNqtcoLEvLFoJ3F99oZai2O&authuser=natalie%40mozillafoundation.org&usp=drive_fs)
