### ISSUE TITLE
make create_super_user a @task

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5095]
It's currently not decorated as a `@task` in `tasks.py`, so it can't be run using `inv create-super-user`, which means trying to administer a copy of the staging db is unreasonably involved.

**Comment by mmmavis** [comment]
Closing.

This seems to be done: https://github.com/mozilla/foundation.mozilla.org/blob/master/tasks.py#L72-L77

And `inv -l` gives you

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/2896608/105080980-73168b80-5a46-11eb-9019-cc33807dedca.png">
