### ISSUE TITLE
Consider linting for backend code 

### ISSUE THREAD

**Issue by easherma** [mozilla/foundation.mozilla.org#5099]
See discussion in: https://github.com/mozilla/foundation.mozilla.org/pull/5091
Also welcome to discuss here. Issue size could definitely expand if we want a more complex solution to this issue.

**Comment by Pomax** [comment]
@cadecairos thoughts on this? Was this something that you and Patjouk had considered before already?

**Comment by KalobTaulien** [comment]
@Pomax @easherma I'm wondering with the current work we have if we icebox this one for a bit OR if after the Home Page work lands we quickly autoformat code before we get too deep into additional branches.

Thoughts on either option?

**Comment by easherma** [comment]
I’m thinking the latter
