### ISSUE TITLE
Add tests for blog routes

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5104]
We currently only have percy tests for the blog, which means we're not testing for things like whether or not specific URLs with unexpected arguments lead to server error 500 or not. Let's add some!

Estimated a 3 primarily because of the trickiness of testing "live routes" in Django, rather than "pretend routs" that bypass the actual server mechanism.

**Comment by jamilasnell** [comment]
We added this awhile back so I am closing this!
