### ISSUE TITLE
[Homepage QA Bug] Long text can't fit in fixed height hero

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5107]
Originally mentioned in https://github.com/mozilla/foundation.mozilla.org/issues/5050#issuecomment-679260694

- [ ] MOBILE (iphone 5 viewport) - top of the title gets cut
<img width="468" alt="image" src="https://user-images.githubusercontent.com/22157921/91075862-8df9e680-e5f3-11ea-87ee-b2d15580087c.png">

**Comment by mmmavis** [comment]
Fixed height sections are problem prone especially for localized CMS-controlled site. We should avoid using them in the future.

**Comment by mmmavis** [comment]
Setting the estimate to `3` because we might need to rewrite hero section's DOM and SCSS depending on the kind of fix we want.

**Comment by mmmavis** [comment]
@taisdesouzalessa the simplest fix for this would be reducing font size for mobile and increase the fixed height value. This way we don't have to rewrite a bunch of code to make the section auto expand

**Comment by taisdesouzalessa** [comment]
@mmmavis do you think if we only increase the fixed height value a bit that would work? I would rather do that than reduce font size. Let me know what you think!

**Comment by mmmavis** [comment]
@taisdesouzalessa yes let's try increasing the height. In the future, we should avoid having fixed height section for text as we can't predict how long the text is going to be and how many lines there will be. Can you let me know what tall you want to increase the section height to (mobile? tablet? desktop)?

**Comment by mmmavis** [comment]
@taisdesouzalessa I spent some time adjusting things a bit and I think I have a fix for this (auto height with min height 390px for mobile and 480px for tablet+). Will file a PR.

**Comment by mmmavis** [comment]
PR merged!
