### ISSUE TITLE
[Homepage QA Bug] Re-order CMS panels 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5108]
Originally mentioned in https://github.com/mozilla/foundation.mozilla.org/issues/5050#issuecomment-679260694

- [x] Nice to have: reorder the CMS editing blocks order to follow the live page order.
<img width="664" alt="image" src="https://user-images.githubusercontent.com/22157921/91076051-c4cffc80-e5f3-11ea-8e3b-4186f40b26ff.png">

**Comment by Pomax** [comment]
@tais while I'm doing this, which sections do you think should be collapsed by default?

**Comment by Pomax** [comment]
fun fact: the "areas of focus" isn't collapsible because wagtail doesn't support that. However, it's actively being worked on here: https://github.com/wagtail/wagtail/pull/6342

**Comment by taisdesouzalessa** [comment]
Ahh good point on sections collapsed by default. How about we collapse the more "evergreen" sections (that will be updated once in a while only) and leave the other content expanded (the ones we will likely to update more frequently)?

**Collapse on default:**
• Cause statement
• Area of focus > _if it is tricky to make it collapsed, okay to leave as is_
• Partner
• Quote

**Comment by mmmavis** [comment]
PR merged!
