### ISSUE TITLE
[Homepage QA Bug] Take action cards have different widths

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5123]
- [x] when we adjust the browser window to narrower width, this is what we see:
<img width="455" alt="image" src="https://user-images.githubusercontent.com/22157921/91103385-3aea5880-e620-11ea-8b65-f387aa5507dc.png">

Those cards should have the same behavior that the other mobile cards in the page. 

Mockup:
https://redpen.io/mqd533ac95816f5e14

**Comment by mmmavis** [comment]
PR merged
