### ISSUE TITLE
[Homepage QA Bug] Quote picture should be full width in mobile

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5126]
Current state (screenshot) - **image doesn't go full width**
<img width="300" alt="image" src="https://user-images.githubusercontent.com/22157921/91119739-da234600-e648-11ea-8e36-4004ed4b5acf.png">

Desired state (mockup):
<img width="267" alt="image" src="https://user-images.githubusercontent.com/22157921/91119852-29697680-e649-11ea-8577-17f98d346ba7.png">

**Comment by mmmavis** [comment]
PR merged!
