### ISSUE TITLE
Publications | Chapter + Article Pages Template | Frontend

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#5141]
The ChapterPage (nested PublicationPage) needs frontend styling.

I'm self-assigning this one for the time being, but may get @easherma to pick this up depending on time allocation this week.

**Comment by KalobTaulien** [comment]
@sabrinang Can you share the link to the Abstract design? There's 2 in there, I want to make sure we work on the right one.

**Comment by sabrinang** [comment]
The layout would be the same for the two, one option just shows it has a colour bg if no image is present: 

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/2492510/91749382-3f5dc680-eb76-11ea-8b98-f1ce09c82ead.png">

Chapter page with images and dark overlay: https://share.goabstract.com/4fe9d5af-1378-4a94-9b88-5a66bf1e30c5?mode=design&sha=2d2b262c36eeec4fc35d710862dbed022cc16a0b

Chapter page without images (will have color bg only): https://share.goabstract.com/5dbd3f87-4eea-4626-b19e-120da599e65a?mode=design&sha=2d2b262c36eeec4fc35d710862dbed022cc16a0b

**Comment by easherma** [comment]
This is mostly done, beyond polish + making sure images are handled as expected (i think the above comment is out of date and there is no overlay for images)

**Comment by phildexter** [comment]
This ticket now superceeds tickets:
https://github.com/mozilla/foundation.mozilla.org/issues/5146
https://github.com/mozilla/foundation.mozilla.org/issues/5075
