### ISSUE TITLE
Publication Article Page frontend

### ISSUE THREAD

**Issue by easherma** [mozilla/foundation.mozilla.org#5143]
it exists, make it pretty. there is a lot to check here in terms of the various components as designed and where they should display on a page.

**Comment by easherma** [comment]
@sabrinang for ArticlePage, there is the summary at the top. On some renders it is hidden behind a dropdown. We'll def want to articulate examples when/how we want to make the transition, especially concerned about it being a jerky transition that we might run out of time to finess. 

This isn't an immediate blocker, I will likely focus on making the dropdown first since it will have to exist either way based on the current design.

**Comment by sabrinang** [comment]
Ok sounds good and agree to focus on dropdown bar first. 
Ideally it appears after you scrolled past the summary section at the top but I know we are tight for time.

**Comment by KalobTaulien** [comment]
> Should this be set to closed @KalobTaulien 

Yes! This is old
