### ISSUE TITLE
Make previous and next buttons

### ISSUE THREAD

**Issue by easherma** [mozilla/foundation.mozilla.org#5145]
* might be good to add these to the style guide
* @sabrinang how do previous and next buttons work if there isn't another sibling page to browse to? apologies if this is already noted somewhere else. 
* when @KalobTaulien and I talked about it, he mentioned maybe needing test coverage for

**Comment by sabrinang** [comment]
For buttons I was thinking:
- if it is the first page, the previous button can direct to its parent
- if it is the last page, the next button can direct to its parent
- if it has no siblings, the previous button can direct to its parent (no next button)

I think this would be easier to bring the user back to see the overview of the content again than to leave the button empty

**Comment by phildexter** [comment]
Where is that at also @KalobTaulien ? should this ticket still exist or is this part of the larger PR?
