### ISSUE TITLE
Publications | Generate data for ArticlePage summary

### ISSUE THREAD

**Issue by easherma** [mozilla/foundation.mozilla.org#5147]
Unlike the Publication/Chapter Page summaries, which are generated from the title of each page, for the ArticlePage we need to generate a summary from the body content of the Streamfields itself. 

We'll need some sort of function/class method that loops through all the content in the streamfield and collects heading tags (maybe h2s?) to display on the summary for that page. 

This is def possible, but might need some testing to make sure it works well. People entering the content will need to understand how it works too in order to deliver expected behavior.

**Comment by easherma** [comment]
might be able to use the `expand_db_html` function to some extent, etc.

**Comment by KalobTaulien** [comment]
This is part of #5143
