### ISSUE TITLE
PNI: finalize design of the privacy ding

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5151]
Rebecca started to explore different directions in - Continue PNI Privacy Criteria Work #5043 and in redpen [here](https://redpen.io/p/as0fadff5c9a9d87b1). Product page design will be finalized [here](https://github.com/mozilla/foundation.mozilla.org/issues/5152).

This ticket is to:
- explore a few more options for both the large and small version of the "icon" 
- chose one direction
- export assets for dev

Note, the "icon" should be:
- portray that it is a bad thing 
- be very "branded" (iconic, can be used in marketing the guide...)
- large version should included the name *Privacy Not Included

**Comment by natalieworth** [comment]
Updated designs for these are in the [Redpen](https://redpen.io/p/je5bb4fbd77c5984ca) and Sab's google slide deck

**Comment by natalieworth** [comment]
[Finalized Ding designs are in here](https://docs.google.com/presentation/d/1PPfS0OWruOW6CpoWk3MpBBt6MrcqqVQWR0Qkl0e1CiY/edit#slide=id.g979bbd3815_0_76)

Will double check tomorrow with team for sign-off.
