### ISSUE TITLE
PNI: finalize the product detail page design

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5152]
Rebecca started this work in - Continue PNI Privacy Criteria Work #5043 and in redpen [here](https://redpen.io/p/as0fadff5c9a9d87b1). The privacy ding design will be finalized in - https://github.com/mozilla/foundation.mozilla.org/issues/5151. Content criteria is in [this doc](https://docs.google.com/document/d/1pTxI9jQQjys4svcxScmhKlejisnauxYz1oUlWR1HOJ0/edit).

This ticket is to:
- review content and design
- make any needed updates 
- mock-up tablet and mobile
- prep for devs

**Comment by sabrinang** [comment]
WIP desktop mockups here: https://docs.google.com/presentation/d/1PPfS0OWruOW6CpoWk3MpBBt6MrcqqVQWR0Qkl0e1CiY/edit?usp=sharing

I'll get more feedback from tomorrows shareout and iterate on the mockups to create accompanying tablet/mobile mockups too.

**Comment by sabrinang** [comment]
Updated iterations on slides (21-26): https://docs.google.com/presentation/d/1PPfS0OWruOW6CpoWk3MpBBt6MrcqqVQWR0Qkl0e1CiY/edit#slide=id.g95c4eee9a5_0_0

Includes layout order, symbol/highlight for red flags and what could happen/creep-o-meter being above the fold iterations. I can continue iterating on the symbol based on brand updates https://github.com/mozilla/foundation.mozilla.org/issues/5151

**Comment by sabrinang** [comment]
Updated slides with v3 mockup iterations (slides 33-36): https://docs.google.com/presentation/d/1PPfS0OWruOW6CpoWk3MpBBt6MrcqqVQWR0Qkl0e1CiY/edit#slide=id.g95c4eee9a5_0_64

Merged latest mockups in abstract and moved old mockups into zArchive PNI page

Note: I'll need to create a tablet view and clean up some names/layers on Monday

**Comment by sabrinang** [comment]
Updated slides with v4 mockups changes (slides 44-48): https://docs.google.com/presentation/d/1PPfS0OWruOW6CpoWk3MpBBt6MrcqqVQWR0Qkl0e1CiY/edit#slide=id.g98f1846143_3_9

Uploaded to redpen as well: https://redpen.io/p/yqece0a9215e9c33f1

Merged latest mockups in abstract (all artboards are in Privacy Criteria Updates in Buyers Guide.sketch)

**Comment by sabrinang** [comment]
Updated slides with v5 mockups changes (slide 54): https://docs.google.com/presentation/d/1PPfS0OWruOW6CpoWk3MpBBt6MrcqqVQWR0Qkl0e1CiY/edit#slide=id.g98f1846143_3_75

Uploaded to redpen too: https://redpen.io/p/yqece0a9215e9c33f1

Merged lastest artboards in abstract (Privacy Criteria Updates in Buyers Guide.sketch) and moved old mockups (zArchive.sketch PNI page)

**Comment by sabrinang** [comment]
Updated slide with v6 mockup changes (slide 56): https://docs.google.com/presentation/d/1PPfS0OWruOW6CpoWk3MpBBt6MrcqqVQWR0Qkl0e1CiY/edit#slide=id.g98f1846143_3_90

Uploaded to redpen: https://redpen.io/p/yqece0a9215e9c33f1

Merged latest artboards via abstract (Privacy Criteria Updates in Buyers Guide.sketch)

**Comment by sabrinang** [comment]
@kristinashu R? 
Artboards in Privacy Criteria Updates (Q3 2020) page: https://share.goabstract.com/584e7002-4d07-4ce5-aafe-dc825e076a27?sha=f0b8ca1b588425d1ef83c57a9f4126c8ff97648e

- included creep-o-meter states for desktop 
- cleaned up layer groups/names, nav and aligned spacing for artboards 

I haven't made these artboards with document symbols/text styles though since I didn't clean up Buyers Guide.sketch's document symbols or text styles overall as I think I should do that in a separate ticket as it would require more time for general file clean up.

**Comment by kristinashu** [comment]
It's looking good R+ 

Thanks for cleaning it up. Feel free to open a new ticket and put it in our next sprint if you want to do more clean up.

**Comment by sabrinang** [comment]
Great thanks for the review. I created a clean up issue here https://github.com/MozillaFoundation/Design/issues/660 — closing this issue.
