### ISSUE TITLE
MozFest website Nav Bar glitching with blue pixels

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/foundation.mozilla.org#5169]
### Describe the bug
When using Google Chrome in desktop view, the navigation bar glitches with blue pixels, as shown in the image below.

### To Reproduce
1. Go to 'https://www.mozillafestival.org' in Google Chrome
2. Ensure window width is above 768px

### Expected behavior
There shouldn't be blue pixels across the Nav Bar.

### Screenshots
![Screenshot 2020-09-02 at 20 22 07](https://user-images.githubusercontent.com/30226684/92027835-fadf5000-ed5a-11ea-8627-8cb83a7676a6.png)

### Desktop (please complete the following information):
 - OS: MacOS 10.15.5
 - Browser Chrome
 - Version 85.0.4183.83 (Latest as of Sept 9th 2020)

**Comment by cadecairos** [comment]
I'm testing this with BrowserStack on Catalina with Chrome 85.0.4183.83, can't get the graphical issue. 

Long shot here - can you try rebooting, and, clearing your browser cache?

**Comment by marcwalsh** [comment]
I restarted (and updated to MacOS 10.15.6) - and did not clear the browser cache - but it fixed it. Seems like it's something to do with my Mac rather than the website.

**Comment by Pomax** [comment]
closing as probably an odd glitch
