### ISSUE TITLE
Publications | implement breadcrumbs

### ISSUE THREAD

**Issue by easherma** [mozilla/foundation.mozilla.org#5172]
just a little crumb left for publications..!

**Comment by KalobTaulien** [comment]
We need design guidance on how the breadcrumb should behave. Likely requires input from @sabrinang

**Comment by sabrinang** [comment]
I think it should be styled as dark theme's body-small and on hover it will be the linked hover state.

**Comment by KalobTaulien** [comment]
This was a small task, I put it in #5141. We can review this one in two small commits: https://github.com/mozilla/foundation.mozilla.org/pull/5134/commits/b70a3b99efefc40b90800f8a57822e9ae3faac9a and 
 https://github.com/mozilla/foundation.mozilla.org/pull/5134/commits/e90f37ed2a1a102c317cf0b37f971f985dea9066

@mmmavis 👆 could you review those two commits please?

**Comment by phildexter** [comment]
Closing this as work all being tracked under #5141 issue now.
