### ISSUE TITLE
Add a footer link to our Careers page 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5174]
Link should be called `Careers` and link to the moco page with the foundation filter on `https://careers.mozilla.org/listings/?team=Mozilla%20Foundation`

To keep the footer convention, the link should appear after Donate (so donate is first and the rest are in alphabetical order). 

This should only happen on the main foundation site (not PNI, Pulse, or donate).

cc @TheoChevalier for localization. 

cc @taisdesouzalessa because she is more familiar with our footers!

**Comment by mmmavis** [comment]
@TheoChevalier I'm assuming for localization we just need to put "careers" in the `trans` block? Is there anything else we should be aware of?

**Comment by TheoChevalier** [comment]
> @TheoChevalier I'm assuming for localization we just need to put "careers" in the `trans` block? Is there anything else we should be aware of?

Yup, that’s it!

**Comment by taisdesouzalessa** [comment]
A reminder: the footer patter is Donate first (because it is the most important action) then alphabetical order. So "Careers" (in English) would come before "Cookies"

**Comment by taisdesouzalessa** [comment]
Also, I am curious about what people see if there is no openings on Foundation...the empty state of that page.

**Comment by mmmavis** [comment]
@taisdesouzalessa I did a quick test. The empty state would look 
<img width="776" alt="image" src="https://user-images.githubusercontent.com/2896608/94600323-983c7f80-0246-11eb-882e-f1643c25582f.png">
which I think is fine.

**Comment by taisdesouzalessa** [comment]
Totally fine!! Thanks for doing the test @mmmavis \0/

**Comment by mmmavis** [comment]
@taisdesouzalessa main Foundation site and PNI share the same footer links. So `Careers` will also show up on PNI. For MozFest, do we also wanna add `Careers` in?

**Comment by taisdesouzalessa** [comment]
I think it is okay to add it to MozFest since it is a Foundation initiative and people may get excited to work with us.
