### ISSUE TITLE
Publications | Version/Edition Field

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#5175]
Some publications have a version/edition/draft indicated for the publication. We can include and style this by the date field but in the meantime authors can include this in the secondary subtitle field. Examples: 
![image-1](https://user-images.githubusercontent.com/2492510/92179666-fae25d00-edf9-11ea-9272-6a97a029cff3.png)
![image](https://user-images.githubusercontent.com/2492510/92179674-ff0e7a80-edf9-11ea-81d4-2985431f1c4d.png)

/cc @easherma

**Comment by kristinashu** [comment]
This work was done as part of the broader publications work but @sabrinang, please re-open if it turns out to me missing.
