### ISSUE TITLE
Blog Author random assignment breaks Percy regression tests

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#5186]
We're randomly assigning Blog Authors in our tests in a way that's not reproducible between builds. Let's investigate ways to make it reproducible.

**Comment by Pomax** [comment]
we're generating authors using the following code:
```
def add_authors(post):
    authors = shuffle(list(BlogAuthor.objects.all()))
    count = len(authors)

    for i in range(0, randint(1, min(count, 5))):
        authors = list(BlogAuthor.objects.order_by("?").all())
        post.authors.add(author_orderable)

    post.save()
```
so I suspect what's happening is that the queryset falls through to whatever the database's randmize function is, rather than the python `random` functionality.

**Comment by easherma** [comment]
Although I didn't finish it, I was playing around with authors for Articles and generating those in a more predictable way, so it is possible to do that for both content types.

**Comment by Pomax** [comment]
we wrote everything to rely on python's built in `random`, which we explicit reseed based on a `RANDOM_SEED` env var, so as long as your code didn't rely on the db for randomization, that should already work.
