### ISSUE TITLE
Clean up https://foundation.mozilla.org/en/docs/how-do-i-wagtail/creating-anchor-links/ a bit

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5193]
It's a kind of weird mix of text and well spaced images, and text and no-spaced images, let's clean that up a little.

Also note that the link picker modal now has five options, one of which is called "anchor" and we should probably make it clear _not_ to use that option =P

**Comment by joneskj55** [comment]
Hi @Pomax I'll happily tackle this. I'm looking at the page now, is there anything specific that you'd like to see or should I just generally clean up as I see fit?

**Comment by Pomax** [comment]
Thank you for your interest. However, as documentation for internal tooling, we will not be taking on external contributions.

**Comment by joneskj55** [comment]
@Pomax Got it, thanks!
