### ISSUE TITLE
Create images and finalize What We Fund pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5196]
Pages are built https://foundation.mozilla.org/en/what-we-fund/

### Final design and content steps
- [x] Content edited and approved by F&A team (final copy approved by Bob is [here](https://docs.google.com/document/d/15KVmaKV85qBVWzPalDwT46ty7f73M2ZcJJJBwXphCXw/edit))

**edit by Taís**
- [x] Design to create images and ~add them to the pages (work with Janice and Ann Marie to update photos on [this page](https://foundation.mozilla.org/en/what-we-fund/fellowships/) since they are "repetitive and inaccurate")~ Ann Marie already did that :)

**end of edit by Taís**

- [x] Design to do a final design review of all the pages

~- [ ] Move [CS Playbook](https://foundation.mozilla.org/en/awards/responsible-computer-science-playbook/ ) pages (can do this automatically in Wagtail)~ - moved this to new ticket #5500 < Update by Taís

Launch will happen in https://github.com/mozilla/foundation.mozilla.org/issues/5198

**Comment by kristinashu** [comment]
Ann Marie is updating the wagtail pages with the latest copy right now so hopefully the only real work here will be to create the images.

**Comment by taisdesouzalessa** [comment]
> Move CS Playbook pages (can do this automatically in Wagtail)

Not sure what do you mean by that @kristinashu - is is to change the URL as planned in our [URL structure doc](https://docs.google.com/spreadsheets/d/184z7LnHIghXDp2NIns4T8zlpBDAdaRFuPMUDX7ijHYY/edit?usp=sharing)?
  `/awards/responsible-computer-science-challenge/responsible-computer-science-playbook/`

**Comment by kristinashu** [comment]
That's right, I guess you would also need to move /initiatives/responsible-cs/ to /awards/responsible-computer-science-challenge

**Comment by kristinashu** [comment]
Ok to move that type of work to a separate follow up ticket tho. P1 would be to finish the "What we fund" page!

**Comment by taisdesouzalessa** [comment]
This is done. A new ticket was created to move Awards projects to proper locations. #5500 5500

**Comment by kristinashu** [comment]
cc @TheoChevalier for localization - https://foundation.mozilla.org/en/what-we-fund/ is live! This is the most recent [copy doc](https://docs.google.com/document/d/15KVmaKV85qBVWzPalDwT46ty7f73M2ZcJJJBwXphCXw/edit) in case that's useful.
