### ISSUE TITLE
Re-directs for What We Fund pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5197]
Please redirect all Fellowships and Awards pages to our new What We Fund pages. 

Redirects should include all languages and all sub-pages.

_Edited by Taís on Oct 30th_ > I guess this is not blocked anymore?
~Blocked by design https://github.com/mozilla/foundation.mozilla.org/issues/5196~

_Edited by Taís on Nov 02_

**To Do:** 
- [x] Please redirect the URLs as suggested in [this spreadsheet](https://docs.google.com/spreadsheets/d/1htYOLCDJgEXDmEArg0pliaTTcZY6yFzeSb7Kp6iDKjQ/edit?usp=sharing) - Tab "What We Fund Redirects". There is a note there marked in yellow (not sure why the anchor doesn't work there).
- [x] Once you do the redirects, please ping Taís so she knows the ticket #5555 is unblocked.

**Comment by jamilasnell** [comment]
@kristinashu Is this work still necessary? If so, what is the action item here?

**Comment by kristinashu** [comment]
Yes, this work is still necessary but blocked by https://github.com/mozilla/foundation.mozilla.org/issues/5196.

The work required is the re-direct the urls listed above.

**Comment by taisdesouzalessa** [comment]
@kristinashu @jamilasnell this is ready to go. Redirects described on the spreadsheet (I edited Kristina's ticket)

**Comment by taisdesouzalessa** [comment]
Assigning this to me since I can do redirects in the CMS now and it works!

cc: @Pomax @kristinashu

**Comment by taisdesouzalessa** [comment]
This is done. Closing the ticket.
