### ISSUE TITLE
Launch the new What We Fund pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5198]
Pages are built https://foundation.mozilla.org/en/what-we-fund/

Images and content is being finalized in https://github.com/mozilla/foundation.mozilla.org/issues/5196 

### To launch
- [x] Add What We Fund to the main nav
- [x] Update site links e.g. links on https://foundation.mozilla.org/what-we-do 
- [x] Review redirects in https://github.com/mozilla/foundation.mozilla.org/issues/5197 and then let devs know they can do the re-directs
- [ ] Delete the old pages. Ticket here: #5555

**Comment by taisdesouzalessa** [comment]
> Update site links e.g. links on https://foundation.mozilla.org/what-we-do

Site links were updated. 
Audit tracked on [this spreadsheet](https://docs.google.com/spreadsheets/d/1htYOLCDJgEXDmEArg0pliaTTcZY6yFzeSb7Kp6iDKjQ/edit?usp=sharing). @TheoChevalier this doesn't seem to affect localization (the link updates worked on localized pages - I tested a few) but want to tag you in case there is something I missed.

There are 2 links I couldn't update because it seems I can't do it via CMS and we will need engineer help. Created a ticket for this request here: #5548

**Comment by taisdesouzalessa** [comment]
> Review redirects in #5197 and then let devs know they can do the re-directs

Did a review of them and have some suggestions, questions for @kristinashu (marked in column F, second tab of [this spreadsheet](https://docs.google.com/spreadsheets/d/1htYOLCDJgEXDmEArg0pliaTTcZY6yFzeSb7Kp6iDKjQ/edit?usp=sharing)). I'll wait for those answers before proceeding and requesting redirects from devs.

**Comment by taisdesouzalessa** [comment]
Got answers from Kristina, updated URLs with the new suggested ones from [this spreadsheet](https://docs.google.com/spreadsheets/d/1htYOLCDJgEXDmEArg0pliaTTcZY6yFzeSb7Kp6iDKjQ) - second tab.

Action items before sending those to dev:
- [ ] Build Fellowships Projects page in new URL (cell F27)
- [ ] Ask Ann Marie if we can redirect all updates pages to the ["news" page ](https://foundation.mozilla.org/what-we-fund/fellowships-and-awards-news)
- [ ] [FAQ page](https://foundation.mozilla.org/en/what-we-fund/fellowships/fellowships-faq/) has lots of broken links (linking to "ia-refresh" environment). I'll fix that page and also try to find a tool that can automate the search for broken links to me to make sure that all links on the Fellowships and Awards page have a valid URL.

**Comment by taisdesouzalessa** [comment]
Old pages can only be deleted once Devs do the redirects. A new ticket was created for this work here:  #5555. Closing this one.
