### ISSUE TITLE
Improve checkAndBindDomNodes function in utility.js

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5199]
### File(s) or components

`checkAndBindDomNodes` function in `utility.js`

### Reason for cleanup

https://github.com/mozilla/foundation.mozilla.org/pull/5121#discussion_r485803430 

Update `checkAndBindDomNodes` so the object it returns has a better format.

**Comment by Pomax** [comment]
code passed this by
