### ISSUE TITLE
Implement Adding Project Links to People Card

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#520]
Based on the design ticket https://github.com/mozilla/network/issues/410, we're adding project links (pulse) so we can link from the profile cards to their projects.

![proposed project links](https://user-images.githubusercontent.com/2492510/27110339-744a8f2a-505d-11e7-82f5-4ec353483baf.png)

In the design ticket, engineering discussion started with "...we have to figure out if we want to implement a quick simple feature (type info in CMS), or if we want to wait until the tech can do this stuff more automatically." https://github.com/mozilla/network/issues/410#issuecomment-306944191

**Comment by arush0311** [comment]
Can i take this?

**Comment by xmatthewx** [comment]
thanks @arush0311 - we're putting this feature on hold for right now. we aim to build connections between people and project within Pulse, and then pull that info over to the network site. 

The "Icebox" milestone are things we don't intend to do in the next couple of months.

**Comment by kristinashu** [comment]
Fellowship profiles link to Pulse Profiles.

<img width="582" alt="image" src="https://user-images.githubusercontent.com/1068783/37052091-1b1156e0-212d-11e8-95cf-3ce14d34bce0.png">

And [People page](https://redpen.io/ema74f4b9a0a4e22bf) will be quite different (more about featuring people and then linking out to their profile on Pulse).

@xmatthewx can we close this ticket?
