### ISSUE TITLE
Update maintenance/server error page

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#5210]
Replace maintenance page headers defined in [`maintenance/maintenance.html`](https://github.com/mozilla/foundation.mozilla.org/blob/master/maintenance/maintenance.html) with the latest top-level page names:

* [x] Who we are
* [x] What we do
* [x] What you can do
* [x] Blog

*  [x] Web fonts not loading

The maintenance page at [`maintenance/maintenance.html`](https://github.com/mozilla/foundation.mozilla.org/blob/master/maintenance/maintenance.html)`

Current:
![Screenshot from 2020-09-10 16-15-17](https://user-images.githubusercontent.com/438003/92798430-ed405080-f380-11ea-82f9-3bc63f2f6916.png)

Expected:
![Screenshot from 2020-09-10 16-16-14](https://user-images.githubusercontent.com/438003/92798485-fc270300-f380-11ea-8f35-e40bedf4d2c3.png)

* [x] The link to the status page needs to be removed, we dropped Pingdom
* [x] The page title needs updating, to include the "under maintenance" status

**Comment by cadecairos** [comment]
We'll also need to update the donate button and add a newsletter button:

![Screenshot from 2020-09-10 16-16-14](https://user-images.githubusercontent.com/438003/92798675-2678c080-f381-11ea-97ef-537cc764e239.png)

**Comment by KalobTaulien** [comment]
I've checked the Acceptance Criteria in the first comment. All of them have been updated in PR #5482
