### ISSUE TITLE
Maintenance page not loading web fonts

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#5211]
The maintenance page at [`maintenance/maintenance.html`](https://github.com/mozilla/foundation.mozilla.org/blob/master/maintenance/maintenance.html)`

Current:
![Screenshot from 2020-09-10 16-15-17](https://user-images.githubusercontent.com/438003/92798430-ed405080-f380-11ea-82f9-3bc63f2f6916.png)

Expected:
![Screenshot from 2020-09-10 16-16-14](https://user-images.githubusercontent.com/438003/92798485-fc270300-f380-11ea-8f35-e40bedf4d2c3.png)

**Comment by KalobTaulien** [comment]
`maintenance.html` is a completely static page. For local testing, we'll want to create a URL and serve that template. May be a good idea to keep that URL in urls.py for future work as well.

**Comment by cadecairos** [comment]
Combining with #5210
