### ISSUE TITLE
[Publications] Developer Support 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5216]
Continue to provide design support for developers throughout the collaborative development process. This may include general design reviews of PRs, QA, and answering questions.

Related Links
[Publications] Developer Support #5159
[Publications] Developer Support #5053
[Publications] Design Mockups #5051

**Comment by sabrinang** [comment]
Support happened in zoom check-in with mavis/pomax, slack comments, and pr review comments https://github.com/mozilla/foundation.mozilla.org/pull/5134#pullrequestreview-495207936

Following up this issue  next sprint here https://github.com/mozilla/foundation.mozilla.org/issues/5312
