### ISSUE TITLE
Youtube regrets extension landing page - change images

### ISSUE THREAD

**Issue by phildexter** [mozilla/foundation.mozilla.org#5218]
Brandi has some different images she wants on the regrets landing page.

**Comment by geurkink** [comment]
Could you please swap out the screenshot images under "How it Works" with the three here? The image files are in this folder: https://drive.google.com/drive/folders/1ZRDFwCrfKTOPe-UgHqMZa-DJ7ep-PU90 

<img width="1010" alt="Screenshot 2020-09-14 at 14 44 48" src="https://user-images.githubusercontent.com/47890866/93087634-20dcec80-f699-11ea-921b-619639f88d3f.png">

Thank you!
