### ISSUE TITLE
Update analytics for PNI - Product pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5239]
- [x] define the list of events and which UI elements and user actions they are tied to
- [x] define the list of old events that will need to be removed

**Comment by Pomax** [comment]
temporarily estimating as 3 based on previous PNI work

**Comment by taisdesouzalessa** [comment]
We had a meeting today and defined the items on [this list](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit?usp=sharing)

**Comment by taisdesouzalessa** [comment]
@mmmavis do you think you have all you need to work on this issue after the meeting we had yesterday + notes added to the list? 
The only thing missing seems to have you checking to see if all is working correctly and implement the events/exclude the unused ones. Should I close this ticket and open an implementation one?

**Comment by mmmavis** [comment]
I think I have all I need. Thanks!

**Comment by mmmavis** [comment]
PR merged
