### ISSUE TITLE
Create review/staging style app for the PNI v4 work

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5240]
We have 4 sprints to work on this, having a separate dedicated review app with separate pull request review apps, similar to the homepage, is a great idea.

- [ ] repurpose homepage refresh infra
- [ ] set up a PNI v4 feature branch

**Comment by mmmavis** [comment]
I've created the branch: [`pni-v4-2020`](https://github.com/mozilla/foundation.mozilla.org/tree/pni-v4-2020)

**Comment by cadecairos** [comment]
https://pni-v4-2020.mofostaging.net/en/privacynotincluded/
https://pni-v4-2020.mofostaging.net/cms (uses LDAP)
https://dashboard.heroku.com/apps/pni-v4-2020/ - in pipeline as staging app, autodeploys `pni-v4-2020`
