### ISSUE TITLE
Empty Menu on mobile

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5243]
### Describe the bug
I created a page on the new "Donors" hub and since I don't want it to show up in menus I unchecked the item "Show in menus: Whether a link to this page will appear in automatically generated menus". However when I see this page on mobile, I see an empty menu field, like this page is part of a menu item.

### To Reproduce
1. Go to [this page](https://foundation.mozilla.org/en/giving/mozilla-guardian-giving-program/)
2. See it in "Responsive Design Mode: Mobile"

### Expected behavior
Not have an empty mobile menu (the same way we don't have an empty desktop menu)

### Screenshots
<img width="320" alt="image" src="https://user-images.githubusercontent.com/22157921/93273684-4e936580-f76d-11ea-804e-9c3b3190e46e.png">

**Comment by cadecairos** [comment]
I'll try to reproduce this locally to determine what the issue is.

**Comment by cadecairos** [comment]
I think maybe we want to use a different page type for Giving? Banner Page seems to generate this element because it expects at least one of the children of the parent page to be part of the nav (That said, it does seem odd that it's not displayed on desktop/tablet widths)

@Pomax any thoughts on this issue? Am I right to suggest a different page type or is this truly a bug

**Comment by kristinashu** [comment]
Banner template pages without any sub-pages are common e.g. https://foundation.mozilla.org/en/campaigns/safety-first/ and they work well (never shows a dropdown).

**Comment by cadecairos** [comment]
The main difference between `safety-first` and `mozilla-guardian-giving-program` then, is that the former's parent page is `Campaign Index Page` while the latter's is `Banner Page`.

**Comment by KalobTaulien** [comment]
To add to this: I created a BannerPage as the parent page, and a BannerPage as the child page, and the dropdown works fine on localhost. But it doesn't show the dropdown items in production. 

Working on debugging this now.
