### ISSUE TITLE
PNI: benchmark search and filters for homepage

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5245]
Related to - PNI: homepage sketches #5153

We want to explore adding search and filters. Finding a few relevant benchmarks could be helpful.

**Comment by sabrinang** [comment]
I created a google slide doc where we can capture benchmarks: https://docs.google.com/presentation/d/1bqoa8Gq1vZMwaI_T98qzTfN4kPiCMnB6hAH8h05FWnc/edit?usp=sharing

**Comment by sabrinang** [comment]
website examples of category/search/filter benchmarks in the doc include: 
- consumer/product/tech review
- consumer retail

**Comment by sabrinang** [comment]
@kristinashu for design review? These are pretty high level benchmarks for reference, if I need to be more specific to dive into them, I can continue next sprint.
