### ISSUE TITLE
Move price link below product name

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#5246]
### Move price link below product name

- [x] Move price and company link to below product name (keep existing styles)

### Desktop 
<img width="822" alt="image" src="https://user-images.githubusercontent.com/1068783/93409515-ed8e8f00-f84b-11ea-9ef0-693c09b7566b.png">

### Mobile
<img width="317" alt="image" src="https://user-images.githubusercontent.com/1068783/93532163-4e25d680-f8f5-11ea-8688-5e47876f7fac.png">

**Comment by mmmavis** [comment]
PR merged!
