### ISSUE TITLE
Remove ‘copy & share link’,

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#5247]
### Remove ‘copy & share link’

- [x] Remove ‘copy & share link’

This is the link that should be removed:
<img width="220" alt="image" src="https://user-images.githubusercontent.com/1068783/93532034-0acb6800-f8f5-11ea-89c0-92da6f3178c9.png">

**Comment by mmmavis** [comment]
PR merged!
