### ISSUE TITLE
Update font style for into blurb

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#5248]
@jamilasnell commented on [Wed Sep 16 2020](https://github.com/mozilla/network-pulse/issues/1416)

### Update font style for into blurb

- [x] reduce the font size of the blurb to 18px to match .body from [our style guide](https://foundation.mozilla.org/en/style-guide/)

### Desktop comp
<img width="825" alt="image" src="https://user-images.githubusercontent.com/1068783/93408058-80c5c580-f848-11ea-9e9d-b38891b1d4f2.png">

### Mobile comp
<img width="316" alt="image" src="https://user-images.githubusercontent.com/1068783/93531932-dfe11400-f8f4-11ea-91d3-417054b4dad3.png">

---

**🗒  Design -> Dev Handoff Checklist**

- [x] Design has been finalized
- [x] Link to original design ticket https://github.com/mozilla/foundation.mozilla.org/issues/5152
- [X] Link to related ticket #5234
- [x] Link to [Sketch file](https://share.goabstract.com/584e7002-4d07-4ce5-aafe-dc825e076a27?sha=f0b8ca1b588425d1ef83c57a9f4126c8ff97648e)
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Assets are included - n/a
- [x] Hover state for elements are designed - n/a
- [x] Other states for elements are designed (e.g., error state for form) - n/a

**Comment by mmmavis** [comment]
PR merged!
