### ISSUE TITLE
Investigate: Responsive image solution

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#525]
We need to figure out an approach for responsive images across the site- heros, but also content images. We might need to change the focus point on various images at different breakpoints so certain parts of the image are all visible.

**Comment by taisdesouzalessa** [comment]
Just out of curiosity I took a look at some data related to the current Browser sizes our audience has been using:

<img width="981" alt="image" src="https://user-images.githubusercontent.com/22157921/27887961-4b283312-6198-11e7-9c50-f4e521ecada0.png">

Although we shouldn't extend those numbers to all our audience, I think it is interesting to see that the majority of current mobile users have browser sizes varying from 320-380px. The desktop users are spread thin (there are lots of different browser sizes) and not so many people use a tablet to access our site. I think we should keep monitoring that to have a better picture of the different browser sizes we have and adjust the responsive behavior to make sure they look ok to the majority of users.

**Comment by hannahkane** [comment]
Estimate is for researching and choosing a solution for at least the auto-resizing (image file size) piece. (The curation piece can be a later problem to solve.)

**Comment by taisdesouzalessa** [comment]
Is this still relevant or should I close this issue @alanmoo ?

**Comment by alanmoo** [comment]
I think at this point this is actually a matter of engineering first, something we work into our various templates. If we ever get to a technical solution, I'll create a new ticket with clearer design needs.
