### ISSUE TITLE
Move “creep-o-meter” up

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#5251]
@jamilasnell commented on [Wed Sep 16 2020](https://github.com/mozilla/network-pulse/issues/1419)

### Move “creep-o-meter” up
Related to styling #5236 and Creep-o-meter updates #5236

 - [x] Move “creep-o-meter” up on the page so it's below "What could happen if something goes wrong?" and above "Privacy"

<img width="848" alt="image" src="https://user-images.githubusercontent.com/1068783/93510527-2e32ea80-f8d6-11ea-8d31-0bf9e7f0b8b4.png">

**Comment by mmmavis** [comment]
This can be closed once PR https://github.com/mozilla/foundation.mozilla.org/pull/5269 is merged in.

**Comment by kristinashu** [comment]
Assigned this to you Mavis since you've already done it!

**Comment by mmmavis** [comment]
Done!
