### ISSUE TITLE
Update section titles

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#5252]
@jamilasnell commented on [Wed Sep 16 2020](https://github.com/mozilla/network-pulse/issues/1420)

### Update section titles

Make the following titles the same styling (using the heading style from production).

- [x] "What could happen if something goes wrong?" - #5250
- [x] "Privacy"
- [ ] "Security" will happen in #5237 
- [x] "Artificial Intelligence"
- [x] "Company contact info"

![desktop](https://user-images.githubusercontent.com/1068783/93531664-782ac900-f8f4-11ea-92a1-0ac36863b8a1.jpg)

**Comment by mmmavis** [comment]
This requires new criteria are in place first. Marking it as blocked.

**Comment by mmmavis** [comment]
All big section headings (except "Security") have been added. 

"Security" will be tackled in #5237 and re-styling work of headings and labels will be handled in #5255
