### ISSUE TITLE
Cleanup Tech Debt on ArticlePageFactory

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#5256]
In `publication.py` (from #5075) we see this:

```python
# this is actually just a blog author factory, hello tech debt
class ArticlePageFactory(PageFactory):
    title = Faker('text', max_nb_chars=120)

    class Meta:
        model = ArticlePage
```

Let's remove this tech debt.

**Comment by Pomax** [comment]
As far as I understood it, this was about the fact that Article Author is just a straight up code-copy of Blog Author. However, as a factory, this code is fine, with the bigger question being "Do we need to make unify article and blog authors as some overarching author class instead"...

**Comment by KalobTaulien** [comment]
Riiiiight, that's exactly what it was. Thank you for the reminder! 

We could rename BlogAuthor to Author or GenericAuthor, update the ForeignKeys in models, make migrations, update the factories, run `inv test-python` and 🤞 fingers crossed that's all we'd need to do.

**Comment by Pomax** [comment]
let's file a new issue specifically for unifying BlogAuthor and ArticleAuthor as a single thing, and then close this one.

**Comment by Pomax** [comment]
https://github.com/mozilla/foundation.mozilla.org/issues/5715
