### ISSUE TITLE
RSS feed may be broken

### ISSUE THREAD

**Issue by sbaack** [mozilla/foundation.mozilla.org#5258]
### Describe the bug
It seems that some of the items which are spotlighted in the blog are not appearing in the RSS feed (https://foundation.mozilla.org/en/blog/rss/). At the time of writing, the following post is a spotlight that does not show up in the feed: https://foundation.mozilla.org/en/blog/2-million-award-reimagine-economics-online-journalism/

### Expected behavior
Everything in the blog should show up in the RSS feed as soon as it is published.

**Comment by Pomax** [comment]
Looks like the RSS is completely broken, in fact. https://foundation.mozilla.org/en/blog/rss/ looks like it's been "safified", which smells like a Django minor update not mentioning it changed something fundamental.
