### ISSUE TITLE
PNI: produce localized assets for PNI ding

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#5260]
The Desktop PNI ding image will contain text that needs to be localized, this ticket is about producing those assets.

 ![image](https://user-images.githubusercontent.com/1294206/93504616-a2d74a80-f911-11ea-890f-91d37ee50bc2.png)

Here are the translations:

DE: `* Datenschutz nicht inbegriffen`
ES: `*privacidad no incluida`
FR: `*confidentialité non incluse`
fy-NL: `*privacy net ynbegrepen`
NL: `*privacy niet inbegrepen`
PT: `*privacidade não incluída`

Thanks!

CC @kristinashu

**Comment by natalieworth** [comment]
[Drafts of these are in the Redpen here](https://redpen.io/p/hzbe417b62f629997e)

**Comment by TheoChevalier** [comment]
Thanks @natalieworth ! Just left a comment about the FR one

**Comment by sabrinang** [comment]
👍 localized designs look good @natalieworth just need png/svg exports.

**Comment by natalieworth** [comment]
Thanks for checking Sabs! [Final exports and working file are in here](https://drive.google.com/open?id=13csbKI1lV_Qn2oxfwCy_jquWWiq1vyuW&authuser=natalie%40mozillafoundation.org&usp=drive_fs).
