### ISSUE TITLE
Very small text updates

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5265]
### Lower case `d`
- [ ] Update the `d` in `Review date:` to lower case `d`

Screen cap from comp
<img width="195" alt="image" src="https://user-images.githubusercontent.com/1068783/93532569-2a16c500-f8f6-11ea-8236-f8691fed9c46.png">

### Related products
- [ ] Update `Compare products` to `Related products`

Screen cap from comp
<img width="835" alt="image" src="https://user-images.githubusercontent.com/1068783/93532688-5d595400-f8f6-11ea-81e3-d578aaa18733.png">

**Comment by Pomax** [comment]
PR landed
