### ISSUE TITLE
YouTube recommending different videos

### ISSUE THREAD

**Issue by b1collector** [mozilla/foundation.mozilla.org#5270]
If I enable the regrets report extension, YouTube gives me very different results. Without the extension the recommendations appear to be based on my viewing habits. With the extension, the recommendations appear much more generic.

I can reproduce this behavior by enabled/disabling the extension.

System: Chrome 85.0.4183.102 (64-bit) Windows 10

I am more than happy to share recommendation specifics privately.

**Comment by Pomax** [comment]
This is the repository for the foundation.mozilla.org website, you'll probably want to file this over on https://github.com/mozilla-extensions/regrets-reporter/ instead.

(administered by a completely different group of people, so I can't move this issue for you, unfortunately).
