### ISSUE TITLE
The FTP download link for Firefox Mobile (Android) apk file is not updated

### ISSUE THREAD

**Issue by evan0greenup** [mozilla/foundation.mozilla.org#5271]
### Describe the bug

The FTP download link for Firefox Mobile (Android) apk file is not updated, the download apk file is still for 68.x not for latest Fenix version. 

The problem is appeared in both [https://www.mozilla.org/en-US/firefox/all/#product-android-release](https://www.mozilla.org/en-US/firefox/all/#product-android-release) and [https://wiki.mozilla.org/Mobile/Platforms/Android](https://wiki.mozilla.org/Mobile/Platforms/Android)

### Expected behavior
It should be now for version 80.x.x

**Comment by Pomax** [comment]
This is the issue tracker for the Mozilla Foundation's website https://foundation.mozilla.org website - note that the foundation is a different org from "Mozilla", and we do not make any products, including Firefox. For issues with Firefox on Android, please see https://github.com/mozilla-mobile/fenix
