### ISSUE TITLE
Have an onboarding doc for new dev / designer

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5297]

**Comment by kristinashu** [comment]
OMG we are working on this!!! [Here's Nancy's](https://docs.google.com/document/d/1_WKRD1siHJaw2K0cd8YduGvQb6EZiUW2_3zK3neFJQ4/edit#) and Anil will expand on it for Ben. Is that enough to close this ticket? Or you want to put it in our next sprint for you and Pomax to add more dev specific details?

**Comment by kristinashu** [comment]
@anilkanji 's [doc is here](https://docs.google.com/document/d/1QmQycuJu40qm-rzQdGts_JTxu92VrPR6wpGCiXTuEkk/edit?usp=sharing).

**Comment by kristinashu** [comment]
### To close Kristina will
- [ ] Turn this doc into a template
- [ ] Ping @Pomax add a link to the Handbook and a sentence introducing it
- [ ] Move the template to our shared Engagement team folder

cc @benhohner

**Comment by kristinashu** [comment]
Linking to Handbook ticket https://github.com/MozillaFoundation/MoFo-Engineering-Handbook/issues/51

**Comment by kristinashu** [comment]
Todo's are done so I'll close this ticket. 

@benhohner @jamilasnell @anilkanji when a new hire starts please review and update [the template first](https://docs.google.com/document/d/1vl0cSYISNIVUthrr23Q2eJsjF1pUF5XdT5HG9tG4HwQ/edit), then fork the doc to customize it for the new hire.
