### ISSUE TITLE
Remove 'none' catergory from News you can use on home page

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#5301]
### Describe the bug
For news without categories on home page, it should be empty like on the /blog page. It currently displays _NONE_.

### To Reproduce
1. Go to 'https://foundation.mozilla.org/'
2. Scroll down to 'News you can use'
3. See blogs with no category assigned

### Expected behavior
_NONE_ should not be there

### Screenshots
![image(1)](https://user-images.githubusercontent.com/2492510/94172220-15cb4e80-fe47-11ea-9cd6-a9ec0caff44a.png)

### Desktop + Smartphone 
 - Device: MacBook Pro + Pixel 2
 - OS: Cataline 10.15.6 + Android 10
 - Browser: Firefox 80.0.1 + Firefox for Android 80.1.3

**Comment by Pomax** [comment]
this should be a template update that writes `&nbsp;` if the category evaluates to `None` (non-breaking space to ensure that card content stays aligned)

**Comment by anushri20** [comment]
I would like to work on this issue.
