### ISSUE TITLE
Image Pixelated on Donor Page 

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#5303]
### Describe the bug
Header image on donor page is pixelated. May be due to cropping of the image 

### To Reproduce
1. Go to https://donate.mozilla.org/en-US/guardiangiving/
2. Pixelated image is the header on the page![Screen Shot 2020-09-24 at 11.53.15 AM.png](https://images.zenhubusercontent.com/5f592fe47f30fa8d24d93d20/95712b91-a222-4005-8c25-246ed0d6de5a)

 - Browser FireFox/Safari

**Comment by phildexter** [comment]
Created on wrong repo - now being tracked on donate repo.
