### ISSUE TITLE
RSS feed: Images are not formatted correctly and too big

### ISSUE THREAD

**Issue by sbaack** [mozilla/foundation.mozilla.org#5309]
### Describe the bug
In RSS readers, images in blog posts are always the same size, no matter how they are actually scaled on the homepage. The result is that the images are too big.

### Expected behavior
Retain information about image position and size in the RSS feed, so RSS feed readers can display each blogpost as it is formatted on the Foundation's homepage.

### Screenshots
Here is an example of a recent Mozilla News Beat: https://foundation.mozilla.org/en/blog/weekly-mozilla-news-beat-september-25-2020/

The left site is how it looks on the Foundation's homepage, the right site shows how it is displayed in RSS readers:

<img width="1846" alt="Screenshot 2020-09-25 at 13 57 33" src="https://user-images.githubusercontent.com/8274140/94264614-45598400-ff37-11ea-8a64-ae4bfb5b09ff.png">

In case it's not obvious from the screenshot: In the RSS reader, the image is huge, way bigger than on the homepage.

### Additional context
I tested this with feedly.com and the NetNewsWire app (https://ranchero.com/netnewswire/) to make sure this is not just a bug in the RSS reader I'm using. I should also say that this is not normal: many other RSS feeds I follow display images the same way the homepage is displaying them.

**Comment by Pomax** [comment]
We use 2x images, downscaled in CSS, so that high-dpi devices still get enough image data to render properly. That's not something we can really change on our end just for the RSS feed, so you might need to file an issue with the feed reader(s) that exhibit this problem =(
