### ISSUE TITLE
PNI: Define analytics for PNI

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5310]
**_Edited by Taís on Oct 9_**
- [x] Define what key analytics and events we should track. 
- [x] Find baselines from 2019
- [ ] Start the dashboard (we still have some discussions about metrics happening so dashboard is likely to be finished only on next sprint).

Work with engineers in https://github.com/mozilla/foundation.mozilla.org/issues/5239

**Comment by phildexter** [comment]
Think about data studio too

**Comment by sabrinang** [comment]
2019 link for reference: https://datastudio.google.com/s/h-dwzmjy6a0

**Comment by taisdesouzalessa** [comment]
Note to myself: Research Google Tag Manager

**Comment by taisdesouzalessa** [comment]
Met with Natalie and Sabrina today. Here is the [refined list](https://docs.google.com/document/d/1oWwHlyreicHybrXudDocclclWfef0m1hyUsob6FyL8w/edit?usp=sharing).

@sabrinang @kristinashu @natalieworth please provide feedback/add suggestions. I'll also share this list with Anil and Jen to see if they have recommendations or if they think we are missing something. It would be great if we have this feedback by Wed EOD so we can book meeting with Mavis on Thursday or Monday (before end of sprint).

**Comment by taisdesouzalessa** [comment]
Closing this ticket as we will be working on the continuation of it (#5419) next sprint
