### ISSUE TITLE
[Publications] Design Review

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#5312]
Continue to provide design support for developers as the development process shifts into review. This may include general design reviews of PRs, QA, and answering questions too as we review.

Related Links
[Publications] Developer Support #5216 
[Publications] Developer Support #5159
[Publications] Developer Support #5053
[Publications] Design Mockups #5051

**Comment by kristinashu** [comment]
This is now unblocked! @sabrinang you should be able to create publication pages on staging now!

**Comment by sabrinang** [comment]
I'm going to do a more in depth review with real content on Monday (perhaps starting AI Whitepaper?). So far my initial review notes are:

**Overall**
Things have to be published, not drafts, to be present and not broken (example: draft children pages won’t appear in ToC; draft publication page won’t appear on breadcrumb). Is there a way to preview drafts or show the draft is present (like the emoji status indication so it is viewable for editors logged in)

**Publication Page**
    - Cut out width (align edge of 2nd and 11th columns) should match/be same as summary box width of article pages

**Article Pages**
    - Default body override to Nunito Light? _(italic looks lighter weight and strange)_
    - No tiered numbers list; number list + headings not possible
    - Offset viewport where footnotes jump to _(currently top section hidden behind nav)_
    - Entire footnotes is blue when just a portion is linked (rest of styling should be grey)
    - Create a hover state for previous/next buttons _(not that obvious the whole section is clickable)_
    - Summary box drop down alignment _(text align to the summary title and box width to column edge)_
    - Summary bar not present in mobile
    - Is it possible to make summary bar hidden until user scroll past summary box?

**Wagtail**
Callout box streamfield
        - bottom right stretch doesn’t change anything in appearance (may not be necessary here)
        - can bold, italic, link options be included as well
Table streamfield
        - Column header doesn’t change appearance
        - If row/column header are unchecked, can top hr grey line not appear
        - How do you add more rows or columns? 
        - can bold, italic, link options be included as well

**Comment by sabrinang** [comment]
@kristinashu Please review my review for publications above?

I’ve tested it on staging in a /docs section last week that I can add child pages too. I was wondering if stuff on staging could be imported to production but it seems like it gets wiped weekly. This is because I was thinking if I’d be importing AI whitepaper as a part of the testing but I think I had enough placeholder content to do my review. I wasn't sure if I would do testing/importing with the whitepaper content but I don’t know where the whitepaper would actually live and if I needed to get permissions to add child pages for that section.

**Comment by kristinashu** [comment]
Chatted with devs at stand this morning and here's the plan:
- Publication work will be pushed to prod tomorrow! yay!
- then Sabrina will add the IA Whitepaper on prod to really test out the template with real content https://github.com/mozilla/foundation.mozilla.org/issues/5536
- Once she has tested it out then she will compile any new feedback with the feedback mentioned above
- She can meet with devs and turn the feedback into tickets

So, @sabrinang I think you can close this ticket as long as you don't loose track of your [feedback above](https://github.com/mozilla/foundation.mozilla.org/issues/5312#issuecomment-715640663).

cc @KalobTaulien

**Comment by sabrinang** [comment]
Thanks for going over this with the devs Kristina and will continue reviewing on #5536 — closing this issue.
