### ISSUE TITLE
PNI: Finalize Design Mockups for Dev Handoff

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#5314]
With the chosen homepage direction from findings https://github.com/mozilla/foundation.mozilla.org/issues/5313, finalize the design mockups.

Ensure to go through the "Design -> Dev Handoff Checklist" 

- [x] Desktop and mobile mockups are included
- [x] Hover state and other states for elements are designed (e.g., various search states)
- [x] Assets are exported and link included
- [x] Design has been finalized
- [x] Design has been reviewed
- [x] Design changes been merged into the master Sketch file via Abstract
- [x] Link to original github design ticket (and related tickets)
- [x] Link to Abstract

**Comment by sabrinang** [comment]
**Note:** clean up layers and groups. align type but most type clean up will be done in https://github.com/MozillaFoundation/Design/issues/660

**Comment by sabrinang** [comment]
Desktop and mobile mockups included:
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/2492510/95638725-83cc6400-0a4a-11eb-8557-195424f55780.png">

States have been made into symbols: 
<img width="1545" alt="image" src="https://user-images.githubusercontent.com/2492510/95638689-613a4b00-0a4a-11eb-8e44-bb9c42eb1631.png">

Assets exported here: https://drive.google.com/open?id=19hkTkJghMxtkg2Lwcqgm7bY3OjbZjJYi&authuser=sabrina%40mozillafoundation.org&usp=drive_fs

Other related github issue: https://github.com/mozilla/foundation.mozilla.org/issues/5313

Design changes merged into master Sketch in Abstract: _Master > Buyers Guide.sketch > Home Page Updates (Q4 2020)_
https://share.goabstract.com/8c104ab1-a386-4be2-9e83-746fd45134d5?sha=fdd46b12b5f3968e07f39e6c9b3fd00186b4c317

Abstract Collection: https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb

- I removed hover tooltip and hover creepy state concepts
- I saw that the facebook portal product was center aligned so I also center aligned all products on other screens
- I've decided to make creepy will appear bottom left for both desktop/mobile viewports or bottom of last product row for simplicity (if it does get over looked in testing we can move upper right)
- language for empty state has been updated with *all* clearing filters and an oh no creepy face included
- added neutral smile face for creepy when users are typing in search
- hamburger menu on mobile to align with foundation properties and to reveal 'about the guide' link and newsletter button
- matched typography/spacing as best as I could with what is live on site currently

@kristinashu to finalize and review designs?

**Comment by kristinashu** [comment]
Amazing! It looks wonderful and very thoroughly thought through.

**Comment by sabrinang** [comment]
I checked in with Jen about company name and product name. She wants and plans to keep it separate on product thumbnails so I made the update to abstract to reflect this on the mockups.
