### ISSUE TITLE
PNI: Iterate Design Based on Preliminary Feedback

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#5332]
We got some feedback from Jen and developers on zoom today after [presenting the mockups](https://docs.google.com/presentation/d/1-iaPgIvrXPv-4Qbr9CaAfmoqpJ724vubjJ--EikGV1E/edit?usp=sharing). I got some feedback on slack to from design and devs.

Revise sketch mockups to iterate on the direction based on feedback and share asynchronously in pni4 slack channel for feedback by Thursday. 

Notes here: https://docs.google.com/document/d/13MeQ0F0zlhnRbBgvTiNxS8_hes2u9UZb3e83PxCXEM4/edit#

**Comment by sabrinang** [comment]
I made an iteration based on the feedback earlier this week, homepage C is on abstract: https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb

@kristinashu for design review

**Comment by sabrinang** [comment]
Revised [Homepage C](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb):
- changed “All Products” to “All” 
- Changed “All Stars” to “Best Of”
- changed drop down to be check box with “*privacy not included” filter only

@kristinashu design review?

**Comment by kristinashu** [comment]
Looks great! Can you please share it with Jen and the devs as well? We can do async now and then meeting Mon or Tues for a design -> dev handoff meeting.

**Comment by sabrinang** [comment]
I shared the abstract link on the pni slack channel and mentioned Jen and devs for feedback
