### ISSUE TITLE
Regrets Reporter Twitter Ad (10/4)

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#5334]
### Describe the feature request
If I could please get images similar to the following in 1:1 or 1.91:1 (whichever suits their content best)

https://drive.google.com/file/d/1ll5tXFTiJNMWxZviA12GPT6Otz10rxB0/view?usp=sharing
https://drive.google.com/file/d/1lkq8nwP78BoszfwkCGscuVJZRHvAKj3i/view?usp=sharing
https://drive.google.com/file/d/1lhD90j8jGqvK_fbmrolJuVk-lKz2IcTd/view?usp=sharing

Hopes to have it done by 10/4

**Comment by natalieworth** [comment]
[Redpen drafts are in here](https://redpen.io/p/byd9e3b9bc6346ceb4)

Hey @jamilasnell, is Brandi the reviewer on this?

**Comment by jamilasnell** [comment]
Yes! @Brandi would be the reviewer!

**Comment by natalieworth** [comment]
[Final assets are here](https://drive.google.com/open?id=1xBV24Y7RdIxHopkNdW4XaKCl2Pb74TZQ&authuser=natalie%40mozillafoundation.org&usp=drive_fs) and also sharing with Brandi and Audrey.
