### ISSUE TITLE
Snippet Not Submitting on MozFest Website

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/foundation.mozilla.org#5337]
### Describe the bug
When trying to sign up for the newsletter using a snippet on the MozFest website, the form does not submit. 

The console log shows this:

> [Error] XMLHttpRequest cannot load https://foundation.mozilla.org/api/campaign/signups/73/ due to access control checks.
> [Error] Failed to load resource: Origin https://www.mozillafestival.org is not allowed by Access-Control-Allow-Origin. (73, line 0)

### To Reproduce
1. Go to 'https://www.mozillafestival.org'
2. Click on form, and enter all details and check the checkbox
3. Press the Submit button
4. Form does not submit and the above is shown in the console log

### Expected behavior
The form should submit and a confirmation should be shown

### Desktop (please complete the following information):
 - OS: MacOS 10.15.6
 - Same error on FF, Safari and Chrome

**Comment by marcwalsh** [comment]
I just checked on other pages as well where we use a snippet, and it seems to be a site-wide issue.

**Comment by cadecairos** [comment]
We'll need to dig into this a bit, but at first glance it seems like one of two things:

a) We always submitted forms cross origin (_to_ `foundation.mozilla.org` _from_ `mozillafestival.org`), and the recent Wagtail 2.10 update has changed how CORS is configured, so the server's now rejecting POST requests from `mozillafestival.org` 
b) We are supposed to be getting `mozillafestival.org` as `apiUrl` in our JS, but for some reason we're now getting `foundation.mozilla.org`, and we don't have the server configured for cross domain posts.

**Comment by Pomax** [comment]
We had updated the code to work with the renamed CORS variables from the Django CORS library, but had forgotten to update the corresponding environment variable names on heroku. That's been fixed, and I see the form posting without any errors now.
