### ISSUE TITLE
PNI Product page - design review fixes

### ISSUE THREAD

**Issue by phildexter** [mozilla/foundation.mozilla.org#5341]
Cleanup ticket to represent effort for final changes post design and once everything is merged together.

**Comment by mmmavis** [comment]
Make sure we verify both **general product page** and **software product page**.

**Comment by Pomax** [comment]
far as I can tell, we're good here, but @mavis @KalobTaulien if you spot anything, please tack that onto this issue. The one thing I'm not sure about is the dropdown for Security (@sabrinang) being... too subtle? It doesn't feel like there's anything telling users that they can click it to see more, but that's more of a design consideration than an incompletion in the implementation

**Comment by mmmavis** [comment]
Product page looks good to me as well. One thing we can add is to add `cursor: pointer` to the dropdown arrow so at least visually it looks more like a toggleable control. I will file a PR.

**Comment by KalobTaulien** [comment]
I agree. This arrow is far too subtle. What if we moved it somewhere else? 
![image](https://user-images.githubusercontent.com/4743971/96501271-6434f880-120d-11eb-8152-9db3917ab9bd.png)

Or had the first line of the collapsed area showing with an arrow over it so it visually tells people there's something there and to click it for more (like reading an article from a newspaper these days). 

Or, does the Security section _need_ an accordion? Could it all be visible by default, or is there possibly too much content to show? And if there is too much information for the user to digest, could we use flexbox here to put the items side by side, something like this? 
![image](https://user-images.githubusercontent.com/4743971/96501654-e32a3100-120d-11eb-819e-157677cae287.png)

^ Just ideas, but either way I think its way too subtle

**Comment by jamilasnell** [comment]
@sabrinang Can you take a look at the above comment? If everything is gucci, we can close it!

**Comment by sabrinang** [comment]
I reviewed this section again and I think adding a hr line will help make the arrow less floaty in closed state and help align sections within open state too 
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/2492510/96756304-bfd7c100-1388-11eb-9276-ee241246a7e2.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/2492510/96756436-f6add700-1388-11eb-9f06-2b72227b2e56.png">

artboards updated in abstract (included close state): https://share.goabstract.com/7ef18815-ae8e-4df6-a2e3-ffa1b0f29283?sha=7c0a317ca738f4f1e555b588c109aaab71f32d24

**Comment by KalobTaulien** [comment]
@mmmavis @Pomax which one of us wants to take this on?

**Comment by Pomax** [comment]
@KalobTaulien if you time for this, it's yours now =)

**Comment by KalobTaulien** [comment]
Confirmed, I'm picking this up.

**Comment by KalobTaulien** [comment]
#5542 needs one last review and approval from @mmmavis – then we can merge this in either tonight or tomorrow.

**Comment by mmmavis** [comment]
PR merged! 🎉
