### ISSUE TITLE
Confirm these apps are still being used

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#5351]
I just noticed the comment here. It'd be nice if we could confirm these are being used, and if not then look ingo safely removing them.

https://github.com/mozilla/foundation.mozilla.org/blob/68c503261f5ab8f726b6dfe302e01127480983aa/network-api/networkapi/settings.py#L220-L222

**Comment by Pomax** [comment]
Highlights are 100% still being used. milestones, I don't think we still use. /cc @cadecairos @kristinashu

**Comment by kristinashu** [comment]
Sorry, I have no clue what `milestones` are!

**Comment by Pomax** [comment]
haha, in that case it's probably safe to say we can kill those off!
