### ISSUE TITLE
Video StreamField block needs a factory URL

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#5364]
## Steps to find problem

1. Create a new env or db with `inv new-env` or `inv new-db` 
2. Log into the admin
3. Edit the homepage
4. Publish Homepage
5. Notice the validation error from the missing URL on the `video` block

### The fix requires
The fix requires a URL field for the `video` block. 

### Considerations
Might want to see what platform the URL is looking for, or if its a generic URL, so we don't end up putting a filler/lorem URL when the URL should be a linked to YouTube, for example.

**Comment by mmmavis** [comment]
Also assigning this one to you @danielfmiranda . I think all we need to do is to find a YouTube video under Mozilla account and plug it into the Video StreamField block factory.
