### ISSUE TITLE
Blog page settings bug

### ISSUE THREAD

**Issue by phildexter** [mozilla/foundation.mozilla.org#5367]
First published at is now overlapping the privacy button - this changed in 2.10.

![image.png](https://images.zenhubusercontent.com/5ea300f46a4404fa669bb86d/1383b2fd-d05e-4834-b2f3-d674bf974381)

**Comment by KalobTaulien** [comment]
Looks like this is a bug in Wagtail so I just reordered the list of panels to put the problem panel at the bottom, work is in the PR #5399.

I think it's frontend only, but I opened a ticket with Wagtail anyway. https://github.com/wagtail/wagtail/issues/6449
