### ISSUE TITLE
New criteria should only be available for "general" products

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5371]
Model changes needed!

All new criteria listed in this [sheet](https://docs.google.com/spreadsheets/d/1cOOzLhkoICFIPTUmxQnrH10HZz1qq5eHF51qgj1p8QM/edit#gid=0) should only be added to "general" products. "Software" product fields should stay unchanged.

/cc @kristinashu @Pomax

**Comment by kristinashu** [comment]
Thank you Mavis! Sorry for the misunderstanding.

**Comment by Pomax** [comment]
merged
