### ISSUE TITLE
Update product page template code so criteria show up correctly based on the product type

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5372]
Back-end ticket: https://github.com/mozilla/foundation.mozilla.org/issues/5371

All new criteria listed in this [sheet](https://docs.google.com/spreadsheets/d/1cOOzLhkoICFIPTUmxQnrH10HZz1qq5eHF51qgj1p8QM/edit#gid=0) should only be added to "general" products. "Software" product fields should stay unchanged. Once the model changes are in, we should update the template code so criteria show up correctly based on the product type.

**Comment by Pomax** [comment]
merged
