### ISSUE TITLE
PNI: Improve UX of the Updates and Related Products multi selectors

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5389]
Jen's feedback after our CMS run through on Oct 5.

Selecting multiple items is tricky, problematic, time consuming and frustrating - is there an alternative multi selector option?

**Comment by jamilasnell** [comment]
Estimate is for investigating if this can be added based on what we have in Django and Wagtail.

**Comment by kristinashu** [comment]
@KalobTaulien will this component be user to use once PNI is fully in wagtail? As in, is wagtail's default multi selector better?

**Comment by jamilasnell** [comment]
Because we are switching over to Wagtail pages, the UI is going to change anyway so we are closing this ticket.
