### ISSUE TITLE
Explore a News homepage

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#539]
As we prepare to ramp up editorial for the site, @jessevondoom makes a good case for /news/ as a primary page, acting almost as a second homepage. Let's explore other news/media homepages and see how this might translate for us. 

Gather targeted benchmarks and consider...
 - hero and feature stories
 - mark stories with tags & issues 
 - author avatars and profiles
 - ...?

We can start this design work now, but should expect it to continue a heartbeat beyond All Hands.

**Comment by xmatthewx** [comment]
@jessevondoom – feel free to drop in a couple of links to help calibrate our benchmarking.

**Comment by taisdesouzalessa** [comment]
The benchmarks will be collected in a board in InVision, in case you want to check out the examples being captured: https://projects.invisionapp.com/boards/BQ35I41GZ83VC/ - @jessevondoom I can add the examples you have to that board too. If possible, could you also give a quick summary of 2-3 reasons you think an example is good? That will give me some guidance when I build this page.

**Comment by hannahkane** [comment]
Love the thinking here so far, especially the idea on the InVision board about curated reading lists, and the idea of separating content we produce from content *about* us. 

Have we defined user goals for this page, or do we want to use the design process to drive that conversation?

**Comment by taisdesouzalessa** [comment]
I would love to understand better the user goals for this page. That would allow me to focus on what are the most important needs and do the design around that. Should we use "“As a user I want to … [user goal].”? 
I find the news is a good page to bring returning users since it is understood that news pages would have new content and people would come back to it to read it. Curious of what others think and what success would look like for this page as well, from the business perspective.

**Comment by jessevondoom** [comment]
I'll fill in more details (promise!) but some quick top level-goals, in no particular order, are:
- To have an easily bookmarked "homepage" for return visitors who care about news
- To provide a curated view of news that impacts or features the network 
- To be able to aggregate news stories in a way that puts them in the context of our Internet health movement goals

But you're right, @taisdesouzalessa — user stories would be ideal. Will work with you on those.

**Comment by hannahkane** [comment]
Waiting until week of July 17th to reconvene around this - pulling in insights from user journey conversation + editorial strategy

**Comment by kristinashu** [comment]
Based on the new [wireframe vision](https://docs.google.com/presentation/d/1Hl5Etpl-iTOCoJJ66ilszGLYFS2k-LqTRk7_fCTmySc/edit#slide=id.g2e15d82b60_0_64), this is no longer a primary page candidate.

Can we close?

**Comment by xmatthewx** [comment]
Yep. Closing.
