### ISSUE TITLE
Untrend Twitter Petition Delivery 10/9

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#5394]
### Describe the feature request
Once the xcel file is handed to us, create it into a PDF

### Screenshots / mock-ups
https://docs.google.com/document/d/1u2O9phy5rMkCbFBopohawv0-OUCysgcxJVAHy6FR2Lo/edit

https://mozillasalescloud.lightning.force.com/lightning/r/7014O000001JLQoQAO/related/CampaignMembers/view

**Comment by jamilasnell** [comment]
similar this pdf but with no EFF! [Uploading... Zoom signatures v2.pdf ]

**Comment by jamilasnell** [comment]
https://docs.google.com/spreadsheets/d/1XvUKF628YtUuU-XhSQT83IAy-pYRE4Lh9uPePfO03jE/edit#gid=2145959096 list of names is in this doc!

**Comment by jamilasnell** [comment]
[https://app.zenhub.com/files/76596293/e6c9f688-1ab4-4f37-a66d-5c5892b51bca/download](https://app.zenhub.com/files/76596293/e6c9f688-1ab4-4f37-a66d-5c5892b51bca/download)

**Comment by kristinashu** [comment]
This is done. Working files and the PDF are in Drive [here](https://drive.google.com/drive/folders/1oiQNDNDOy6W9XBhnwpJJTCKh5fFINTyN). This has been shared with Kaili, Ashley, and Jon.
