### ISSUE TITLE
Remove "milestones" app

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5398]
Implementation issue for https://github.com/mozilla/foundation.mozilla.org/issues/5351, nothing uses `milestones`, let's remove it.

**Comment by Sparsh-Bansal** [comment]
Can I take this issue ?

**Comment by Pomax** [comment]
Feel free to.

**Comment by Sparsh-Bansal** [comment]
Query : Should i also make migrations to the database or just change the codebase ?

**Comment by Pomax** [comment]
we'll want to remove the app from the db, as well.

**Comment by Sparsh-Bansal** [comment]
As mentioned [here](https://github.com/mozilla/foundation.mozilla.org/blob/master/docs/workflow.md), I need to land a different PR to generate the migrations. Should i push the migrations in the current PR only ?

**Comment by Pomax** [comment]
I've redone this work as https://github.com/mozilla/foundation.mozilla.org/pull/5722 + https://github.com/mozilla/foundation.mozilla.org/pull/5721, to make sure this removal is a proper removal. In particular, the fact that Django has nothing built in to remove an app from the db means this is not as straight forward as the Django docs claim it is (removing the app from settings leaves everything hanging around in the db).

**Comment by Pomax** [comment]
`manage remove_milestones` issues on staging and production.
