### ISSUE TITLE
Invite visitors to talk with profiled people

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#54]
We should distribute questions, introductions to our core network members (rather than just thru a centralized contact form to us). What are ways we could encourage visitors to reach out to members via twitter or linkedin?

This is a post-launch design task. 

Members could be flagged: talk to me about privacy. talked to me about open source community driven  software.

**Comment by kristinashu** [comment]
@xmatthewx is this still something you want? Seems like we're moving away from showing Twitter/LinkedIn on Foundation site and instead directing them to the Pulse profile.

**Comment by xmatthewx** [comment]
i think it's less relevant now. and way too big lift for now.
