### ISSUE TITLE
PNI - Move “About the guide” from the category nav to the primary_nav

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5409]
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/2896608/95619166-0a6d4b00-0a23-11eb-9895-530a8e2c5301.png">

Move “About the Guide” from the PNI category nav to the primary_nav

We'll have a separate ticket for adding a hamburger menu & mobile primary nav. #5410 

---

Assigning to @sabrinang for now so she can fill out the checklist below.

###  Design -> Dev Handoff Checklist
(Feel free to remove items that are not applicable.)

- [x] Design has been finalized
- [x] Link to original design ticket
- [x] Link to related ticket
- [x] Link to Abstract (make sure it can be viewed by anyone)
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Name of the Sketch file (and specific page/section to look at, if applies)
- [x] Assets are included. Link: 
- [x] Hover state for elements are designed
- [x] Other states for elements are designed (e.g., error state for form)

**Comment by sabrinang** [comment]
Design has been finalized. 
Merged into master Sketch file via Abstract. (_Master > Buyers Guide.sketch > [Home Page Updates (Q4 2020](https://share.goabstract.com/07a9aca5-3903-4f00-828a-6ac8bebb5be3?sha=e49d77cc9da6a70e8c412cd985e28138a3091cd5))_).

Abstract links:
- [[Desktop] Homepage - Index](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=103e293c-16c0-48af-bac2-dc7d7545e5ea&mode=design) 
- [[Mobile] Homepage - Expand Menu](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=6dbd8d6e-f5f9-406e-90ae-719f59298cb2&mode=design)

Hover states:
- Desktop: Match what is currently live _(the same states as 'donate')_
![PNI_about-the-guide-hover-state](https://user-images.githubusercontent.com/2492510/96036148-eb066180-0e18-11eb-8852-088c723dea2e.gif)
- Mobile: Match what is currently live on foundation.mozilla.org _(the same states as 'who we are')_
![PNI_about-the-guide-hover-state-mobile](https://user-images.githubusercontent.com/2492510/96036706-b3e48000-0e19-11eb-970e-85adf677af84.gif)


No exported assets needed.
Related/original github issue: https://github.com/mozilla/foundation.mozilla.org/issues/5314

**Comment by mmmavis** [comment]
PR merged
