### ISSUE TITLE
PNI - add hamburger menu for the primary_nav on mobile

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5410]
Add the delicious, juicy, hamburgery menu for the primary_nav on mobile.

copy/super.block from foundation site? - this would be "home", "about the guide" "newsletter" rather than the options on foundation.moz.org

---

Assigning to @sabrinang for now so she can fill out the checklist below.

###  Design -> Dev Handoff Checklist
(Feel free to remove items that are not applicable.)

- [x] Design has been finalized
- [x] Link to original design ticket
- [x] Link to related ticket
- [x] Link to Abstract (make sure it can be viewed by anyone)
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Name of the Sketch file (and specific page/section to look at, if applies)
- [x] Assets are included. Link: 
- [x] Hover state for elements are designed
- [x] Other states for elements are designed (e.g., error state for form)

**Comment by sabrinang** [comment]
Design has been finalized. 
Merged into master Sketch file via Abstract. (_Master > Buyers Guide.sketch > [Home Page Updates (Q4 2020](https://share.goabstract.com/07a9aca5-3903-4f00-828a-6ac8bebb5be3?sha=e49d77cc9da6a70e8c412cd985e28138a3091cd5))_).

Abstract links:
- [[Mobile] Homepage](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=3f690fff-c322-4f11-8505-04aee49fea04&mode=design)
- [[Mobile] Homepage - Expand Menu](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=6dbd8d6e-f5f9-406e-90ae-719f59298cb2&mode=design)

Hover/other states:
- Match what is currently live on foundation.mozilla.org _(expand animation, hover states and newsletter states)_
![PNI_hamburger-states-mobile](https://user-images.githubusercontent.com/2492510/96039438-7bdf3c00-0e1d-11eb-9e75-295bf2c19ccf.gif)



No exported assets needed.
Related/original github issue: https://github.com/mozilla/foundation.mozilla.org/issues/5314

**Comment by mmmavis** [comment]
This is done!
