### ISSUE TITLE
PNI - update hero banner

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5411]
- [x] move big heading and intro copy to hero
- [x] adjust hero banner height
- [x] adjust alignment

<img width="715" alt="image" src="https://user-images.githubusercontent.com/2896608/95620180-9f247880-0a24-11eb-82f6-ac7d6342c257.png">

---
###  Design -> Dev Handoff Checklist

- [x] Design has been finalized
- [x] Link to related ticket: #5314
- [x] Link to Abstract (make sure it can be viewed by anyone)
- [x] Design changes been merged into the master Sketch file
  - Merged into master Sketch file via Abstract. (_Master > Buyers Guide.sketch > [Home Page Updates (Q4 2020](https://share.goabstract.com/07a9aca5-3903-4f00-828a-6ac8bebb5be3?sha=e49d77cc9da6a70e8c412cd985e28138a3091cd5))_).
- [x] Desktop and mobile mockups are included
  - [[Desktop] Homepage - Index](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=103e293c-16c0-48af-bac2-dc7d7545e5ea&mode=design)
  - [[Mobile] Homepage](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=3f690fff-c322-4f11-8505-04aee49fea04&mode=design)
- [x] Name of the Sketch file (and specific page/section to look at, if applies)
- [x] Assets are included. Link: 
  - background: https://drive.google.com/open?id=1AYYp44yBQ0wY8i57RP3F1fBOmcaqqDSL&authuser=sabrina%40mozillafoundation.org&usp=drive_fs
  - webby award: https://drive.google.com/open?id=14RyywjOt5pBnl_IRg9jCer7hmoCfoC-J&authuser=sabrina%40mozillafoundation.org&usp=drive_fs
- [x] Other states for elements are designed: The background would need to expand to accommodate the text on various screen widths and languages

**Comment by mmmavis** [comment]
@sabrinang from the mockup it seems like we want the hero banner to be at fixed height. We'll need to make some design adjustments because we can't guarantee that all localized content will fit.

**Comment by mmmavis** [comment]
Bumping up the estimate to 2 considering localization and responsiveness.

**Comment by sabrinang** [comment]
@mmmavis Yeah, the background would need to expand to accommodate the text on various screen widths and languages variations so it no I don't believed it is fixed, I can also update mockup to match how the responsive version looks like.

**Comment by mmmavis** [comment]
@sabrinang how do you want text and the badge to align? e.g., do you want them to be always y pixels away from the top and x pixels away from the right edge?

**Comment by sabrinang** [comment]
@mmmavis I think the badge should be by the right side of the container (by the edge of the last column). Desktop it can be 32px from the top; mobile it can be 16px from the top. Desktop text in can span 8-col; mobile text can span full 12-col below badge. Hero height can expand to accommodate longer copy and language variations. 

Rough idea: 
![PNI_hero-resizing-example](https://user-images.githubusercontent.com/2492510/96524342-d7019c00-122c-11eb-9d71-f0243647b179.gif)

**Comment by mmmavis** [comment]
PR merged!
