### ISSUE TITLE
PNI - changes to product card on homepage

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5418]
**This is a placeholder ticket. Pending design decision.**

@sabrinang mentioned we might wanna remove company info from the product cards on homepage? 

Note that this would impact the project detail pages as well.

---

Assigning to @sabrinang for now so she can fill out the checklist below.

###  Design -> Dev Handoff Checklist
(Feel free to remove items that are not applicable.)

- [ ] Design has been finalized
- [ ] Link to original design ticket
- [ ] Link to related ticket
- [ ] Link to Abstract (make sure it can be viewed by anyone)
- [ ] Design changes been merged into the master Sketch file
- [ ] Desktop and mobile mockups are included
- [ ] Name of the Sketch file (and specific page/section to look at, if applies)
- [ ] Assets are included. Link: 
- [ ] Hover state for elements are designed
- [ ] Other states for elements are designed (e.g., error state for form)

**Comment by sabrinang** [comment]
I checked in with Jen about company name and product name. She wants and plans to keep it separate on product thumbnails so I made the update to abstract to reflect this on the mockups. There will be no dev changes since we are keeping what is live currently — closing issue.
