### ISSUE TITLE
PNI: Define analytics for PNI (cont.)

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5419]
Follow up on  #5310

- [x] Finish discussions [from this doc](https://docs.google.com/document/d/1oWwHlyreicHybrXudDocclclWfef0m1hyUsob6FyL8w/edit?usp=sharing) about what key analytics and events we should track.
- [x] Keep adding baselines from 2019
- [x] Start the dashboard. To fully finish it, we depend on the site being implemented and live (so we can add the latest events created by Mavis [here](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit?usp=sharing))

@natalieworth @sabrinang feel free to add things here as you see fit.

**Comment by taisdesouzalessa** [comment]
• Baseline [for 2019 here](https://docs.google.com/spreadsheets/d/1qaafnvkm2cR-UfOvBu21ueJqXNB8QcDHuXPE1lZigNU/edit?usp=sharing)
• [Dashboard started here](https://datastudio.google.com/reporting/3e7cca08-7764-4c6e-835f-6dffeae3df22)

**Comment by taisdesouzalessa** [comment]
Finished first draft of dashboard and asked for feedback [on this doc](https://docs.google.com/document/d/1oWwHlyreicHybrXudDocclclWfef0m1hyUsob6FyL8w/edit?usp=sharing) - by Thursday (Oct 22nd). Will act on feedback after the deadline.

[Dashboard here](https://datastudio.google.com/reporting/3e7cca08-7764-4c6e-835f-6dffeae3df22)

**Comment by taisdesouzalessa** [comment]
Improved the dashboard (WIP, adding 2019 metrics into the dash for comparison) + deciding what elements should fit where in the dash. 

@natalieworth @sabrinang when you have the chance can you please take a look at the WIP dashboard and let me know if you have any feedback on how things can be improved? Also, if you feel any metric is off (like, do the data am I pulling helps to explain the prompts I have? Is there anything that could be done in an better way?).

**Comment by kristinashu** [comment]
This is wonderful Tais! Very interesting to see how much mobile traffic the site gets! Also very interesting to see which platforms people are sharing on and where they're signing up for our newsletter.

**Comment by sabrinang** [comment]
Thanks Tais for presenting the metrics in an accessible manner framed with questions/hypothesis/goals at the top and baselines from 2019, very helpful!

@taisdesouzalessa There's only two parts that are showing up a bit funky for me:

**Site Usage:** has invalid/missing dimensions for 'total events on product pages'
<img width="420" alt="image" src="https://user-images.githubusercontent.com/2492510/97232773-ffdce080-179a-11eb-933f-418b79f9e169.png">

**Devices and Usability:** has cut off, misaligned text in the description
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/2492510/97232910-46323f80-179b-11eb-9936-d932454889e4.png">

**Comment by taisdesouzalessa** [comment]
Thanks @sabrinang - glad the top part with context is helpful. Thank you and Nat for giving feedback in the early stages of it and for giving ideas on how to make the dashboard more accessible!

> Site Usage: has invalid/missing dimensions for 'total events on product pages'
All the data of the dashboard is still not final. We will need the page live so I can grab all the new events we defined + apply all the necessary filters. 

> Devices area
Still fixing this part today \0/ - it is a mess right now but I am organizing the info in my head and adding to there...haha.

**Comment by taisdesouzalessa** [comment]
Dashboard is done and pre-launch list is in a new ticket:  #5530
