### ISSUE TITLE
PNI - define list of fields that should be used in searching

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5421]
Sabrina messaged and confirmed with Jen that the fields that should be included in search are:
- Product names
- Company names
- Product blurb
- What could happen blurb
- Category

**Comment by jamilasnell** [comment]
@kristinashu @sabrinang - Should this actually be a dev ticket?

**Comment by Pomax** [comment]
this was a requirement for #5422, I have folded the information into that issue.
