### ISSUE TITLE
PNI - live search behaviour

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5422]
Show filtered results based on search.

See #5412 for how the emoji face should behave when search is toggled
See #5421 for fields that we should search on.

- [x] write filter JS that hides anything that has no matches for search terms typed by the user in any of the filter attributes:
  - [x] Product name
  - [x] Company name
  - [x] Product blurb
  - [x] What could happen text
  - [ ] Category
- [x] add all filterable content fields to product cards
- [x] hook up search functionality with the search input box
- [x] hook up filtering via the `*privacy not included` checkbox
- [x] reveal "no results" part of the template when there are no search results to show

Note that not all these fields will be visible to the user, but will be visible to the page code via `<input type="hidden">`

Also note that we will have separate tickets for "no result" state and control panel interaction.

---
###  Design -> Dev Handoff Checklist

- [x] Design has been finalized
- [x] Link to related ticket: #5314 #5424 
- [x] Link to Abstract (make sure it can be viewed by anyone)
- [x] Design changes been merged into the master Sketch file
  - Merged into master Sketch file via Abstract. (_Master > Buyers Guide.sketch > [Home Page Updates (Q4 2020](https://share.goabstract.com/07a9aca5-3903-4f00-828a-6ac8bebb5be3?sha=e49d77cc9da6a70e8c412cd985e28138a3091cd5))_).
- [x] other assets linked in https://github.com/mozilla/foundation.mozilla.org/issues/5424
- [x] Other states for elements are designed: the behaviour should be similar to search on https://www.mozillapulse.org/

**Comment by Pomax** [comment]
@sabrinang is this work ready to start?

**Comment by sabrinang** [comment]
@Pomax Yes this is ready to start

**Comment by Pomax** [comment]
@sabrina is category a true search requirement? Given that we already have the nav for that?

**Comment by sabrinang** [comment]
@Pomax True it is repetitive if users have the category options in the nav already, so it isn't really a true search requirement.

**Comment by Pomax** [comment]
this work landed!
