### ISSUE TITLE
PNI - implement "no result" state for search

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5423]
- [x] Implement "no results" state for search
- [x] Hide the "submit a product" block (see linked mockup below) when search is on "no results" state 

---

###  Design -> Dev Handoff Checklist

- [x] Design has been finalized
- [x] Link to related ticket: #5314
- [x] Link to Abstract (make sure it can be viewed by anyone)
- [x] Design changes been merged into the master Sketch file
  - Merged into master Sketch file via Abstract. (_Master > Buyers Guide.sketch > [Home Page Updates (Q4 2020](https://share.goabstract.com/07a9aca5-3903-4f00-828a-6ac8bebb5be3?sha=e49d77cc9da6a70e8c412cd985e28138a3091cd5))_).
- [x] Desktop and mobile mockups are included
  - [[Desktop] Homepage - Category and Search Complete](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=b4beb7d2-7d3e-4c5a-99ba-51530058b813&mode=design) (no results page)
  - [[Mobile] Homepage - Search No Results](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=a2e4e32f-6e2d-452b-9fb3-326c30f282fa&mode=design)
- [x] Name of the Sketch file (and specific page/section to look at, if applies)
- [x] Assets are included. Link: https://drive.google.com/open?id=19j7fCYjv-bRgkUlbTBxi1VEEWtedCMdx&authuser=sabrina%40mozillafoundation.org&usp=drive_fs
- [x] Other states for elements are designed: `All` links back to All cleared of search/checkbox

**Comment by KalobTaulien** [comment]
This is awaiting @Pomax's final blessing before it gets merged into his search branch. If good, we can merge this in today or tomorrow.
