### ISSUE TITLE
PNI - search control panel

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5424]
- [x] implement style and interaction for the search box (mobile & desktop)
- [x] implement style and interaction for the *privacy not included checkbox (mobile & desktop) 
- [ ] update creepy face accordingly (related to #5412) (mobile & desktop)

Note that the actual search functionality will be implemented in #5422

---
###  Design -> Dev Handoff Checklist

- [x] Design has been finalized
- [x] Link to related ticket: #5314
- [x] Link to Abstract (make sure it can be viewed by anyone)
- [x] Design changes been merged into the master Sketch file
  - Merged into master Sketch file via Abstract. (_Master > Buyers Guide.sketch > [Home Page Updates (Q4 2020](https://share.goabstract.com/07a9aca5-3903-4f00-828a-6ac8bebb5be3?sha=e49d77cc9da6a70e8c412cd985e28138a3091cd5))_).
- [x] Desktop and mobile mockups are included
  - [[Desktop] Homepage - Index](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=103e293c-16c0-48af-bac2-dc7d7545e5ea&mode=design) _(search icon not selected / PNI unchecked)_
  - [[Desktop] Homepage - Search](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=6619f77a-a5e3-4019-b224-8adf02478629&mode=design) _(selected)_
  - [[Desktop] Homepage - Search Typing](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=a05bb884-48f2-47d3-b0ea-4ca413cd4212&mode=design)
  - [[Desktop] Homepage - Search Complete](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=bd411525-c773-4653-96b1-eed2b3b917c9&mode=design)
  - [[Desktop] Homepage - Search and Checked PNI](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=2ab96a85-d07b-450e-9d56-f9bdb6bf8b5b&mode=design)
  - [[Desktop] Homepage - PNI Selected](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=7780bf1f-0f85-4eae-a93b-d56c13d0e585&mode=design) _(checked)_
  - [[Mobile] Homepage](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=3f690fff-c322-4f11-8505-04aee49fea04&mode=design) _(search bar exposed on mobile by default)_
  - [[Mobile] Homepage -  Search (sticky)](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=444ea267-9bb3-431d-ac4b-c03e372cdc68&mode=design)
  - [[Mobile] Homepage -  Search Typing](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=8e221879-0554-4930-bfcc-a6e27cccb3de&mode=design)
  - [[Mobile] Homepage -  Search Complete](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=d36d2423-0665-49c1-83c3-897948841596&mode=design)
  - [[Mobile] Homepage -  Search and PNI Checked](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=fbd67b54-88d7-4bec-a03f-cd93cc76d36f&mode=design)
- [x] Name of the Sketch file (and specific page/section to look at, if applies)
- [x] Assets are included. Link: https://drive.google.com/open?id=19hkTkJghMxtkg2Lwcqgm7bY3OjbZjJYi&authuser=sabrina%40mozillafoundation.org&usp=drive_fs
- [x] Other states for elements are designed: _see mockups above for selected, typing, completed, checked states_

**Comment by Pomax** [comment]
adding kalob as the third point is related to #5412

**Comment by Pomax** [comment]
acceptance criterium folded into https://github.com/mozilla/foundation.mozilla.org/issues/5412
