### ISSUE TITLE
PNI - product thumbnails - remove MSS badge and add dings

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5425]
- [x] remove MSS badge from product thumbnails
- [x] show ding on product thumbnails if applicable

---
###  Design -> Dev Handoff Checklist
- [x] Design has been finalized
- [x] Link to related ticket: #5314
- [x] Link to Abstract (make sure it can be viewed by anyone)
- [x] Design changes been merged into the master Sketch file
  - Merged into master Sketch file via Abstract. (_Master > Buyers Guide.sketch > [Home Page Updates (Q4 2020](https://share.goabstract.com/07a9aca5-3903-4f00-828a-6ac8bebb5be3?sha=e49d77cc9da6a70e8c412cd985e28138a3091cd5))_).
- [x] Desktop and mobile mockups are included:
  - [[Desktop] Homepage - Index](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=103e293c-16c0-48af-bac2-dc7d7545e5ea&mode=design) 
  - [[Mobile] Homepage](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=3f690fff-c322-4f11-8505-04aee49fea04&mode=design) 
- [x] Name of the Sketch file (and specific page/section to look at, if applies)
- [x] Assets are included. Link: https://drive.google.com/open?id=1kfrvpO-yguTrPWkOjY3P2yiSvOxeuk1G&authuser=sabrina%40mozillafoundation.org&usp=drive_fs
- [x] Hover state for elements are designed: none

**Comment by mmmavis** [comment]
<img width="573" alt="image" src="https://user-images.githubusercontent.com/2896608/96313031-ba156080-0fc1-11eb-9b14-1e47f7e5bd44.png">

Top right corner of the product thumbnail is currently reserved for the 18+ icon. Where do we wanna position the ding if there's already an 18+ icon?

**Comment by mmmavis** [comment]
@sabrinang ^

**Comment by sabrinang** [comment]
I checked with Jen that we can move ding to upper left where MSS was to replace it, so I'll be updating the mockups.

**Comment by mmmavis** [comment]
Awesome!

**Comment by mmmavis** [comment]
@sabrinang We spoke about keeping the current padding in the product thumbnail box (12px) so the new icons can stay where the existing icons currently are. I'm not sure if that's what you decided to have. Please give me a ping on this ticket when the mockups have been updated. Thanks!

**Comment by sabrinang** [comment]
I've updated the mockups to align with the 12px margins for product cards @mmmavis

**Comment by mmmavis** [comment]
Thanks!

**Comment by mmmavis** [comment]
PR merged!
