### ISSUE TITLE
Change django.conf.urls.url() to django.urls.re_path()

### ISSUE THREAD

**Issue by Sparsh-Bansal** [mozilla/foundation.mozilla.org#5441]
The old `django.conf.urls.url()` function is replaced with new `django.urls.re_path()` function for routing .
This would help : https://docs.djangoproject.com/en/3.1/ref/urls/#url

The `django.conf.urls.url()` function is an alias for `django.urls.re_path()` in 2.2.*, and can be updated in place.

For `Django >= 3.x`,  `django.conf.urls.url()` will be removed. (https://docs.djangoproject.com/en/dev/internals/deprecation/#deprecation-removed-in-4-0)

### To Reproduce
1. Go to all the required urls.py files.
2. Change `django.conf.urls.url` to `django.urls.re_path`.
3. Change all the `url` to `re_path`

**Comment by Pomax** [comment]
We will not be updating Django for probably another few months, but thank you for filing.

**Comment by Sparsh-Bansal** [comment]
Sure, I will land a PR once the Django version will get updated.

**Comment by Sparsh-Bansal** [comment]
Sure , I will land a PR today
