### ISSUE TITLE
PNI Localize Fields (Second Iteration)

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#5442]
This is the second iteration of #5338. 

History: We are running into problems with #5338, namely the `inv test-python` command is not passing and it's hard to debug. This ticket is designed to re-create 5338 (and the relevant PR) in order to have a cleaner commit history so we can bisect the code easier and determine the cause of the failed test. 

#5339 is the original PR, which I'll be re-creating as well with a cleaner commit history for easier bisecting as well. 

From Theo's original comment:
> As part of the revised l10n plan, let’s hook up all CMS fields for localization using the system already in place, wagtail-modeltranslation
> https://docs.google.com/document/d/1RunBlPOJ7m-KfIDwazBHL3EO6Di1MQtj9pqtTDpdZwg/edit?ts=5f7226fd#heading=h.g8i1bgv9jn4e

There is currently a comment/sub-issue surrounding the final work where the `name` and `name_en` fields are both exposed, but only one should be shown. This may or may not be a bug, and if it is a bug it may be something we can live with as it's existence doesn't hurt the editors UX on such a small field (Category snippets, for instance). 

Both #5338 and #5339 will be closed once this ticket and relevant PR are opened.

**Comment by Pomax** [comment]
I think the problem we're running into here is that we're trying to use `wagtail-modeltranslation`, which works with Wagtail's `Page` class, in the context of a plain Django app: none of the PNI models are backed by Wagtail's `Page`, so we see weird side effects.

We may have to start uplifting parts of PNI to "proper" Wagtail models in order for our localization approach to work.

**Comment by Pomax** [comment]
@KalobTaulien @TheoChevalier @caltrider it looks like if we want localization for this iteration, we're going to have to scope some new work to get all the code that should support localization uplifted to "proper Wagtail", and then see how many additional hours of estimated work that requires.

**Comment by KalobTaulien** [comment]
There's an epic created at #5506 for all the "proper Wagtail" work about something like 15 tickets in that epic.
