### ISSUE TITLE
Instagram Petition 10/19

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#5443]
### Describe the feature request
Instagram post and story to support this campaign: https://foundation.mozilla.org/en/campaigns/facebook-stop-group-recommendations/ 

Brief is here: https://docs.google.com/document/d/1GTE7gRndbRhpyOGDE1jwOrYmgxBQKSiFgxMIm3IRuoU/edit

**Related to task on #672**

### Screenshots / mock-ups
If you like, you can copy-paste, or drag-and-drop, a screenshot of the thing you'd like to see improved. Bonus points for faking what you'd like it to look like!

### Additional context
Wants it done by the 19th!

**Comment by jamilasnell** [comment]
Contact person is Audrey (who is on UK time now)

**Comment by natalieworth** [comment]
[Final assets sent to Audrey](https://drive.google.com/drive/folders/1RyXT8O9TFcj53VW6BzI6CFSBgr2vJD7Y?usp=sharing)
