### ISSUE TITLE
PNI Product Images on Product Page

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#5445]
Pulling product images for PNI. Imput line 10--in the spreadsheet product reviews tab where whoever uploads the image to the product page can add a check mark to indicate the image is in. Crop them a bit to fit if necessary. 

[Master Doc](https://docs.google.com/spreadsheets/d/1DXYM8-L2uXcw3M-44ky01yVumkaUqdl-fqm0rpCRWug/edit#gid=0)

**Comment by kristinashu** [comment]
Folders are set up[ in Drive here](https://drive.google.com/drive/folders/1q48nv7emk1cMbGbc-dQ9QCoAnGALpAHs?usp=sharing).

Guidelines:
- Name the images `CompanyName-ProductName`
- Asking devs if we should use JPG or PNG. Save at the lowest file size possible while maintaining good quality.
- Add `Your Initial` + `Original` or `Cropped` to Line 10 of the [Master Doc](https://docs.google.com/spreadsheets/d/1DXYM8-L2uXcw3M-44ky01yVumkaUqdl-fqm0rpCRWug/edit#gid=0) while you're working on it. Update to just `Original` or `Cropped` once you've done.

**Comment by kristinashu** [comment]
I've already done about 1/3 of the images so it shouldn't be a problem to finish this this sprint.

**Comment by kristinashu** [comment]
[Done!](https://drive.google.com/drive/folders/1q7FafC0875QsdJQe2FucF8DqwabGBaSm?usp=sharing)
