### ISSUE TITLE
Design Projects detail view 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#545]
Currently, projects on the project page link to Pulse. We should keep people on the network site for less disruption by showing a detail view on the network site. 

Design for this should be based on new and improved detail view by Kristina. https://github.com/mozilla/network-pulse/issues/527#issuecomment-300548835

**Comment by kristinashu** [comment]
@xmatthewx is this still what you want?

**Comment by xmatthewx** [comment]
This was a request from Jesse. Makes sense. Likely still a thing we'll want to do someday. But obviously not a thing we'll do today. Definitely relates to your work on links between the platforms since this is likely to be a primary path. Feel free to triage this issue however makes sense to you.

**Comment by kristinashu** [comment]
Ok, I've put it under the cross-linking epic to think about.

**Comment by kristinashu** [comment]
We are removing the projects page and highlighting projects on the home page, which will link out to pulse
