### ISSUE TITLE
Possible styling issue on the banner page

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5457]
I was looking at the who we are/what we do pages, and noticed this. On medium size:

![image](https://user-images.githubusercontent.com/177243/96195724-5415d400-0f02-11eb-865b-1226b618c109.png)

But on desktop size:

![image](https://user-images.githubusercontent.com/177243/96195734-5e37d280-0f02-11eb-89c9-e150a29e802d.png)

It looks like the cutout isn't getting sized correctly... is this a bug in our styling, or is that the intended design @kristinashu @sabrinang ?

**Comment by kristinashu** [comment]
I believe that is by design!
