### ISSUE TITLE
Provide content for expanded About page

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#546]
Beyond the 5 issues, we have some Themes worth articulating (aka Hubs, Topics, Priorities, Trends, Focus). issues and themes could also link to related projects in pulse (people and opportunities when that stuff is tagged and ready). Discussion with Jesse started [here](https://docs.google.com/document/d/1DKWHgVKeZi69yvwigK0a-g1J40j6kp4jFeX0hTjqsso/edit).

I think this needs a bit of thought, guidance, and copy from @jessevondoom before design begins.

**Comment by jessevondoom** [comment]
I think there's an organizational hierarchy in the network that maps nicely to Internet Health:

1. Key issues
2. Themes
3. Tags

The key issues are self-evident. We reinforce the IH issues at a top level and use them to navigate projects/people in the network. 

Themes are similar, but less permanent. We can show 10-12 high-level things — hubs, women and the web, fellowship groups, network 50, whatever makes sense. These don't have to be rotated regularly or anything, but they're concepts we can feel free to change as our focus changes over time.

And tags could just be the X most popular tags from Pulse, giving more of a real-time trend kind of view into what's happening in the network. I'm assuming that wouldn't be super useful right now, but as Pulse activity picks up it would be interesting to see things visualized this way. 

I'll work on refining some copy for the page, and throw a document in here. To me the challenge is going to be giving enough "about" information to keep the page informative, but using the issues/themes (and maybe tags) to allow people to explore.

**Comment by hannahkane** [comment]
@jessevondoom - changed the name of this ticket to specifically be about providing content for an expanded About page. Currently assigned to you. OK to have this in the current milestone that ends on the 28th?

**Comment by jessevondoom** [comment]
Yup! I can have something in this heartbeat. Good ticket to bring Sydette in on, too. (Need to figure out her github username...)

**Comment by hannahkane** [comment]
Good progress on the doc, but likely need a bit more time to wrap it up and get ready for production.

**Comment by jessevondoom** [comment]
@hannahkane Yeah I think that's fair. Should land soon, but next heartbeat.

**Comment by alanmoo** [comment]
@jessevondoom any update on this?

**Comment by kristinashu** [comment]
Updated vision for About page based on Jesse's [wireframes](https://docs.google.com/presentation/d/1Hl5Etpl-iTOCoJJ66ilszGLYFS2k-LqTRk7_fCTmySc/edit#slide=id.g3090418ab9_0_58)

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/1068783/37050754-8c4211be-2129-11e8-9ff5-9bf760b047a1.png">

**Comment by kristinashu** [comment]
About page and all content is being rewritten Jesse's [endpoints doc](https://docs.google.com/document/d/1zhOwOET0yH3xQC83tcKmlwGT9s2lLv05wdUqRJsm5MI/edit).
