### ISSUE TITLE
PNI - only show new products on the homepage/category pages - Nov 5

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5463]
We only want new products (products added from Oct 29 onward) to appear on the homepage and category pages. The old products should still be live and discoverable via a google search or a direct url link.

**Comment by kristinashu** [comment]
Note on timing:
- Oct 29: Jen will start with content entry so new product page work will need to be live (her new products will be in draft for a few days)
- Nov 4: soft launch of product pages (not Homepage) - this is when this ticket should be pushed live

**Comment by Pomax** [comment]
This work can move ahead, but should not land until close to release.

**Comment by kristinashu** [comment]
Right, this should be pushed live on Thurs Nov 5.
