### ISSUE TITLE
Make publications and article pages available in staging environment

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#5465]
On the staging environment, an editor can create a new publications page, and new article page

Enable `LOAD_PUBLICATION_MODELS` setting in staging environment on Heroku

**Comment by KalobTaulien** [comment]
`LOAD_PUBLICATION_MODELS` is set to `True` in the environment variables. Cade double checked its enabled in the staging CMS/admin as well.
