### ISSUE TITLE
PNI Homepage Link + Hero Banner for Blogpost

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#5470]
### Describe the feature request
Foundation Homepage link that will be placed in Hero Banner on blogpost and WaPo

**Comment by taisdesouzalessa** [comment]
This took longer than planned so I updated the estimate. Here are the outputs:
1. Blog post image [here](https://redpen.io/otd4da3dccd74ae51d).
2. One extra illustration for the blog post (section "What can you do next"), asking people to sigh the open letter.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/22157921/96523043-948a9000-1229-11eb-96b3-65a9d0e00df7.png">

3. [Social share image](https://redpen.io/uob277dba85ce8b5b6) for the [blog post](https://foundation.mozilla.org/en/blog/mozilla-urges-facebook-and-twitter-halt-dangerous-recommendations/)

4. [Social share image](https://redpen.io/hcb50fe50f2c54ae4a) for the ["Sign the Open Letter" page](https://foundation.mozilla.org/en/campaigns/sign-letter/)

5. [Hero image ](https://redpen.io/eg40321a569b9c2cbc)to be published tomorrow.
