### ISSUE TITLE
PNI - update content on the "About the guide" pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5471]
All content and sub-pages will need to be updated. Design will stay simple and the same as [current pages](https://foundation.mozilla.org/en/privacynotincluded/about/why).

Jen will not have this content ready until just before launch.

Dev ticket is here https://github.com/mozilla/foundation.mozilla.org/issues/5472

**Comment by kristinashu** [comment]
Via Jen: 

Janice is going to work on the methodology section tomorrow and then we both hope to have our about page content to Emily the lawyer for review on Friday. Hopefully it won’t take her long to review it. 

Kevin has this doc ready to go to update the media page in the about section https://docs.google.com/document/d/1ZFZcHfAubnyeXJCpFlA6rJkJKJku4FI6LfFDvRQpTto/edit

Marking this as unblocked since it can get started on even though we done have all the content yet.

cc @jamilasnell

**Comment by sabrinang** [comment]
Jen gave me an update today:

- Why We Made This Guide copy doc:
https://docs.google.com/document/d/1liqlnktlNG5jfi0kcbi3jGXUH6Yh9pWAMCXJ1rVqezs/edit?usp=sharing
- the “how to use this guide” is being sent to lawyer for review (hopefully receive it back no later than tomorrow morning)
- the "methodology" section is being worked on by Janice (should have that done by tomorrow morning and hopefully reviews will have it done by mid-day)
- Only other tweak is to reorder the things on the left and move the "methodology" section up above the “minimum security standards explained” section

**Comment by sabrinang** [comment]
- How to Use This Guide copy doc (approved): https://docs.google.com/document/d/1kj3E7KjJPfqwA9KWU1PD0V4KtiZDAnfoCuyVigG6XKU/edit

**Comment by sabrinang** [comment]
Updated in abstract - collection link here: https://share.goabstract.com/13e6fcf6-1c04-4bdf-9bb1-29cd6ac1f2b6

_note: placeholders for methodology, minimum security standards and contact pages_

**Comment by sabrinang** [comment]
Updates from Jen:

- Methodology copy doc (Jen mentioned it's approved but there is the one outstanding question in there but 99% sure it will be OK with us mentioning them and it might take a bit for us to confirm but doesn't want to hold us back): https://docs.google.com/document/d/1RMBjiVOO4knkpMh3yRT2lF5nxDN8jx66ePNuSuri1dk/edit?usp=sharing
- Contact page: isn’t changing at the moment
- MSS explained page: the only change is to take out this sentence: `Take the FREDI wireless baby camera monitor, for instance, which has been repeatedly hacked.`

**Comment by sabrinang** [comment]
Styling Notes:
- I used existing styles on what is found on PNI prod _(note: these are different heading styles than foundation site)_
- Show current page (black/underline style in side nav)
- Changed light italics to regular italics
- Category nav hidden
- Included alternative press layout with logos (image text style)

Updated via Abstract — @kristinashu ready for review: https://share.goabstract.com/13e6fcf6-1c04-4bdf-9bb1-29cd6ac1f2b6

**Comment by kristinashu** [comment]
+R looks good and is consistent with existing styles!
