### ISSUE TITLE
PNI - implement content on the "About the guide" pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5472]
Based on: PNI - update content on the "About the guide" pages #5471

**Comment by kristinashu** [comment]
Via Jen: 

Janice is going to work on the methodology section tomorrow and then we both hope to have our about page content to Emily the lawyer for review on Friday. Hopefully it won’t take her long to review it. 

Kevin has this doc ready to go to update the media page in the about section https://docs.google.com/document/d/1ZFZcHfAubnyeXJCpFlA6rJkJKJku4FI6LfFDvRQpTto/edit

cc @jamilasnell

**Comment by kristinashu** [comment]
Marking this as unblocked since it can get started on even though we done have all the content yet.

**Comment by kristinashu** [comment]
Shoot, wrong ticket. This should be in https://github.com/mozilla/foundation.mozilla.org/issues/5471

**Comment by kristinashu** [comment]
Assigning to @sabrinang to update with comps and copy doc once it's ready - PNI: update content on the "About the guide" pages #5471

**Comment by sabrinang** [comment]
Copy Documents:
 - Why We Made This Guide: https://docs.google.com/document/d/1liqlnktlNG5jfi0kcbi3jGXUH6Yh9pWAMCXJ1rVqezs/edit?usp=sharing
- How to Use This Guide: https://docs.google.com/document/d/1kj3E7KjJPfqwA9KWU1PD0V4KtiZDAnfoCuyVigG6XKU/edit
- Methodology: https://docs.google.com/document/d/1RMBjiVOO4knkpMh3yRT2lF5nxDN8jx66ePNuSuri1dk/edit?usp=sharing
- Minimum Security Standards Explained: the only change is to take out this sentence: `Take the FREDI wireless baby camera monitor, for instance, which has been repeatedly hacked.` (see [live page](https://foundation.mozilla.org/en/privacynotincluded/about/meets-minimum-security-standards) for copy)   
- Contact Us: No changes at the moment. (see [live page](https://foundation.mozilla.org/en/privacynotincluded/about/contact) for copy)
- Press: https://docs.google.com/document/d/1ZFZcHfAubnyeXJCpFlA6rJkJKJku4FI6LfFDvRQpTto/edit 

Design issue: #5471
Mockups: https://share.goabstract.com/13e6fcf6-1c04-4bdf-9bb1-29cd6ac1f2b6
Assets (press logos): https://drive.google.com/open?id=1CZOSG6PX7ZPiG0ULY8jVDugfXuQ5KyyB&authuser=sabrina%40mozillafoundation.org&usp=drive_fs
