### ISSUE TITLE
[Measuring Design Impact] Create Vision Document

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5486]
**Create a vision doc that outlines:**
- the goals
- the outcomes
- the desired impact of group
Leave space in the doc for a **generative list of things** we can do that advance the goals we want to achieve.

Once we have the items above ready it will help us to shape the RASCI and share responsibilities.

**To do:**
- [x] light research (what's out there, any successful benchmark?)
- [x] write the first draft for review.
- [x] submit for feedback/ask for team's participation on improving it.

**Reference:**
[first meeting notes here](https://docs.google.com/document/d/1AfuHIB1xYbW1_LK8ukqbTGi-6JsKbFo2ZqAAC5STcBE/edit?usp=sharing).

cc: @kristinashu would you like me to create a draft of it and then you and team can review it? Added this ticket to next milestone.

**Comment by kristinashu** [comment]
> @kristinashu would you like me to create a draft of it and then you and team can review it? 

Up to you but that sounds good to me.

**Comment by taisdesouzalessa** [comment]
Still a work in progress and messy but I think it is a perfect opportunity for a team feedback: [doc here](https://docs.google.com/document/d/1y6hcLihiF3LSHd-dt-GroP4a8zaLgoMWIlLdV9Oh1mQ/edit?usp=sharing). @kristinashu @sabrinang @natalieworth would you be able to give some feedback by the end of the week? I intend to clean up this doc by Friday or so - and it will be open to feedback after that too, just wanted to make sure to loop you all in this first draft stage. Feel free to add your thoughts there/edit things. Let's build this together :).

**Comment by taisdesouzalessa** [comment]
Draft: [V0.5 here →](https://docs.google.com/document/d/1y6hcLihiF3LSHd-dt-GroP4a8zaLgoMWIlLdV9Oh1mQ/edit?usp=sharing)

Closing this ticket: email was sent to group team members requesting feedback and next meeting will happen on Nov 18.
