### ISSUE TITLE
[Publications] Design Review + QA

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#5498]
We are able to create publication pages on staging now. 

Get wagtail edit access, test out the pages and continue to provide design support for developers as we QA and review. This may include general design reviews of PRs, QA, and answering questions.

**Related Links**
[Publications] Design Review #5312 
[Publications] Developer Support #5216
[Publications] Developer Support #5159
[Publications] Developer Support #5053
[Publications] Design Mockups #5051

**Comment by kristinashu** [comment]
Looks like the previous one got moved to this sprint so let's just use that one https://github.com/mozilla/foundation.mozilla.org/issues/5312
