### ISSUE TITLE
 PNI - User Test Planning

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#5499]
Create a user testing plan for the revised website. This may be through usertesting.com or with a test group via zoom. Plan what aspects we want to test, potential scripts and ideas for user testing.

**Comment by kristinashu** [comment]
Jonny from Torchbox will be user testing based on our updates so far. Here is the brief https://docs.google.com/document/d/1TRZ-SFNGs1lP532rvrI2Q0PLo-J87ylZ9D_y4eaRD8c/edit#. 

Still going to keep this open for big future test!

**Comment by kristinashu** [comment]
Jonny is doing another round of testing. Closing this issue. We should open a new one when we re-do the homepage.
