### ISSUE TITLE
Move Awards projects to new locations on the site

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5500]
**BLOCKED BY: #5657**

**Background:**
As per our [Proposed URL Structure](https://docs.google.com/spreadsheets/d/184z7LnHIghXDp2NIns4T8zlpBDAdaRFuPMUDX7ijHYY/edit?usp=sharing), we should move the Awards pages to proper new locations:
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/22157921/99715912-4e109700-2a5c-11eb-811c-17c54a44fba0.png">

**To do:**
- [x] Duplicate and move copy of [RCS Challenge page](https://foundation.mozilla.org/en/initiatives/responsible-cs/) inside "Awards" page on Wagtail (and all subpages). New URL: [https://foundation.mozilla.org/en/what-we-fund/awards/responsible-computer-science-challenge/](https://foundation.mozilla.org/what-we-fund/awards/responsible-computer-science-challenge/)
- [x] Move [RCS Playbook page](foundation.mozilla.org/en/awards/responsible-computer-science-playbook) inside "what-we-fund/awards/responsible-computer-science-challenge" page on Wagtail (and all subpages). New URL: [https://foundation.mozilla.org/what-we-fund/awards/responsible-computer-science-challenge-rcs-playbook/](https://foundation.mozilla.org/what-we-fund/awards/responsible-computer-science-challenge-rcs-playbook/)
- [x] Look for any places on the site where we point to those pages (audit link [here](https://docs.google.com/spreadsheets/d/1XSspodNSpdmHJjf91ibx84md-WImoB2JQxwVk2SPe98/edit?usp=sharing)) and change the URL to the new locations.
- [x] Notify Kathy and Jenn of those changes so they start using these new pages on the new location
- [ ] Do the redirects from previous locations to new locations.
- [ ] Once redirects are in place, delete the old pages.

Does this order make sense to you @kristinashu?

**Comment by taisdesouzalessa** [comment]
@mmmavis do you think we will be able to sort this out this sprint? We've discussed this via Slack a while ago (I am not able to move the RCS Challenge page inside the Awards folder in Wagtail because there was a conflict on page types (if I am not mistaken). If you're busy with PNI this sprint we can move it to the next one, just let me know :).

The question was if we want to allow **default page** as child page of **banner page** and I think the answer is yes. I know we won't have the banner on top of the page (as shown below) but this is exactly what I want (no banner). I want the URL inside "Awards" but visually the page should look exactly as the page we have live: https://foundation.mozilla.org/en/initiatives/responsible-cs/

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/22157921/98179005-a8352800-1eb2-11eb-89f1-54172bc8769e.png">

@kristinashu let me know if there is any objections/flags here to consider.

**Comment by mmmavis** [comment]
@taisdesouzalessa yes, please move this to next sprint. 

> The question was if we want to allow default page as child page of banner page and I think the answer is yes. I know we won't have the banner on top of the page (as shown below) but this is exactly what I want (no banner). I want the URL inside "Awards" but visually the page should look exactly as the page we have live: https://foundation.mozilla.org/en/initiatives/responsible-cs/

One note is that all child pages will show up as secondary nav links on /awards. This means RCS Challenge will show up there as well. 

I think this should be fine to do. But let's meet after stand (on next Thursday?) with Kristina and Pomax before we go ahead and make the changes in case I missed anything.

**Comment by taisdesouzalessa** [comment]
Moving this to next sprint as Engineers are busy with PNI. We will need some conversations to happen to move this project forward.

cc: @jamilasnell @kristinashu

**Comment by taisdesouzalessa** [comment]
I'll book a meeting with us all on Thursday: Pomax, Kristina, Mavis and I.

**Comment by taisdesouzalessa** [comment]
Talked to Engineers today, the plan is ti allow Default Pages be the children of Banner pages and test on Staging to see if we get the desired result. Ticket open to Engineers here: #5657

**Comment by taisdesouzalessa** [comment]
Met with Pomax today, we're having some issues related to types of pages. He opened a ticket for Engineers and will ping me when I can try to add this page to staging.

**Comment by taisdesouzalessa** [comment]
changes were pushed to prod. However when trying to add the Playbook pages inside "what-we-do/awards" this is what happens:
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/22157921/99741409-ef601300-2a85-11eb-920c-050cf8af915c.png">

Having this top menu (overview/fellowships/awards...) makes thinks super confusing from a UX perspective. 

What I'll do is to create a "Default Page" hub inside the "Responsible Computer Science Challenge" hub and rebuilt the Playbook page on the "Default Page" mode. This way the interface will be cleaner (like the "[Responsible Computer Science Challenge](https://foundation.mozilla.org/en/what-we-fund/awards/responsible-computer-science-challenge/)" is now).

**Comment by taisdesouzalessa** [comment]
Went as far as I could on this issue. Track the remaining work on #5710.
