### ISSUE TITLE
PNI Product conversion to Wagtail Pages 

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#5506]
We need to convert PNI Product (models) to Wagtail Pages. There's quite a bit of work here, so this is getting filed as an epic. 

I'll make all the relevant tickets as well.

The original spike ticket can be found at #5489 and the roughed out tickets are in [this comment](https://github.com/mozilla/foundation.mozilla.org/issues/5489#issuecomment-713931312) on the same ticket (for future reference)

**Comment by Pomax** [comment]
@KalobTaulien do we have "add tests" in the list of things to do?

**Comment by KalobTaulien** [comment]
Yep!

**Comment by Pomax** [comment]
I filed https://github.com/mozilla/foundation.mozilla.org/issues/5668 to improve how product type is determined.

**Comment by Pomax** [comment]
@KalobTaulien can you check that all the points from https://github.com/mozilla/foundation.mozilla.org/issues/5543 are captured here?
