### ISSUE TITLE
PNI follow-up: delete PNI product models and related code, plus migrations 

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#5521]
> Delete PNI products (in their own ticket) and cleanup the old code 

Criteria:
- [ ] Remove PNI Product models 
  - [ ] base
  - [ ] general
  - [ ] software 
- [ ] Create migrations to remove the models from the database 
- [ ] Remove any related code (ie. factories) surrounding the old product models.

**Comment by Pomax** [comment]
marking as blocked because this is basically the very last step

**Comment by KalobTaulien** [comment]
Afaik there arent any steps remaining before this. I'm going to do some initial work on this today. Moving to In Progress.
