### ISSUE TITLE
PNI - namespace the buyersguide `template` content

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5543]
We currently have all our templating code in `networkapi/buyersguide/templates`, so it will conflict with files found in `networkapi/templates` when there are files with the same name. 

The solution is to make a dir called `networkapi/buyersguide/templates/buyersguide` and then move everything that's in `buyersguide/templates` into that new `buyersguide/templates/buyersguide`. That way, django won't try to merge them with the files found in the base templates dir.

- [ ] create new `networkapi/buyersguide/templates/buyersguide` dir
- [ ] move templates into this new dir
- [ ] update https://github.com/mozilla/foundation.mozilla.org/blob/master/translation-management.sh#L37-L51
- [ ] coordinate a change for https://github.com/mozilla-l10n/fomo-l10n/ with @TheoChevalier / MoCo

**Comment by TheoChevalier** [comment]
@Pomax @mmmavis Heads up that this will completely disrupt localization, as the l10n repository and translation management script are relying on this path.

L10n repo: https://github.com/mozilla-l10n/fomo-l10n/tree/master/foundation/translations/networkapi/buyersguide

Script that will need an update: https://github.com/mozilla/foundation.mozilla.org/blob/master/translation-management.sh#L37-L51

We will need to coordinate that change between both repositories and make sure Pontoon is happy with the resource being moved (it should, but it usually require a hard sync from the Pontoon dev team)

**Comment by Pomax** [comment]
roger - added that as acceptance criteria

**Comment by Pomax** [comment]
I'm closing this as the work that @KalobTaulien is doing on the PNI wagtail uplift includes making sure the new templates are properly namespaced.

#5506
