### ISSUE TITLE
PNI - update page title

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5544]
Currently, all PNI pages have `Mozilla - *privacy not included` as the page title. We want them to be more descriptive (e.g., including category name etc). This should improve our analytics tracking & SEO.

This blocks the analytics implementation ticket #5427 as we need tracking events to include unique page title as part of the data sent to GA.

**Comment by iamraghs** [comment]
i can solve this

**Comment by mmmavis** [comment]
PR merged!
