### ISSUE TITLE
Donor page redirect

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5546]
As per conversation with Jesse, redirect this page: https://foundation.mozilla.org/en/initiatives/leadershipgiving/ to this new page: https://foundation.mozilla.org/en/giving/mozilla-guardian-giving-program/

@kristinashu is there anything I should be aware of (localization needs)? Also [is this the way we do redirects](https://docs.wagtail.io/en/v2.10.2/editor_manual/managing_redirects.html)? Sorry, not very familiar on how to do it in the CMS.

**Comment by kristinashu** [comment]
There is a way to do it, if you don't see it then it's because you don't have the permissions.

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/1068783/97732178-627ff600-1a93-11eb-9547-fd4d08298e72.png">

Note that you should always make it "temporary" not "permanent" because permanent is **very** permanent.

The issue with the wagtail redirect is that you have to do it for every local so for `/` (no language set), `/en`, `/de`.... However for this case, I'm not sure Jesse would have shared the url for different languages.

**Comment by taisdesouzalessa** [comment]
I don't have access to it :(. Will ping engineers and also ask them a walkthrough to teach me these redirect too when PNI is over.

**Comment by mmmavis** [comment]
Hey @taisdesouzalessa , I never did this myself so it's best that we loop Pomax in so he can demo it to both of us. Maybe we can try finding time Thursday this week if we wanna close this ticket by this milestone.

**Comment by mmmavis** [comment]
So we need to first figure out if that page is English-only. If so, we can do the redirect via `Settings > Redirects`. If we need to take localization into account it will require new code set in `redirects.py` to make that happen.

**Comment by taisdesouzalessa** [comment]
I pinged Jesse and I'll get back to you here once I have the answer to the question above. Thanks, Mavis!

**Comment by taisdesouzalessa** [comment]
@mmmavis it is English-only for now. So the easier solution seems to apply. I don't have permissions to do the Redirect via CMS, could you grant me permission so I can do it myself? Tks!

**Comment by mmmavis** [comment]
@taisdesouzalessa Yup! You should have access now!

**Comment by taisdesouzalessa** [comment]
I did the redirects (screenshot below). First one **doesn't work** and the second one **does**. Any thoughts on why the /en/ redirect is not working? Maybe I am missing something here.

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/22157921/98155869-cb98ac80-1e8b-11eb-9188-0fe17f0bc6c8.png">

**Comment by mmmavis** [comment]
@Pomax can you lend a hand here?

**Comment by taisdesouzalessa** [comment]
Opened a new ticket, focused only on this issue (since it has been happening with other pages too). Assigned it to you, Mavis and Pomax. #5634. Closing this one.
