### ISSUE TITLE
[Blog] Fellowships and Awards link updates

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5548]
The [Fellowships & Awards Blog category page](https://foundation.mozilla.org/en/blog/category/fellowships-awards/) has links pointing to old URLs:
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/22157921/97641384-fe602200-19ff-11eb-9511-38cf0049f0ed.png">

**To do:**
- [x] Update Mozilla Fellowships link from `https://foundation.mozilla.org/fellowships/` to `https://foundation.mozilla.org/what-we-fund/fellowships/`
- [x] Update Mozilla Awards link from `https://foundation.mozilla.org/en/awards/` to `https://foundation.mozilla.org/what-we-fund/awards/`
- [x] Once this is done please update [this spreadsheet](https://docs.google.com/spreadsheets/d/1htYOLCDJgEXDmEArg0pliaTTcZY6yFzeSb7Kp6iDKjQ/edit?usp=sharing) marking items as "Done" (cells F13 and F14).

**Related ticket:** #5198

cc: @jamilasnell to assign to engineers

**Comment by kristinashu** [comment]
I was able to do this in the CMS. It's under snippets but you might not have permissions.

<img width="554" alt="image" src="https://user-images.githubusercontent.com/1068783/97731920-fdc49b80-1a92-11eb-9fc7-b247b47581fb.png">
