### ISSUE TITLE
Discuss: CSS vars vs SCSS vars

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5549]
Because we rely on Boostrap so much, I've been using mostly SCSS vars so they align with what Boostrap already uses. However, there are exceptions that I had to use CSS vars because JS needs to access those variables. Since there are already mixed uses of both types of variables in the codebase, I'm wondering going forward if we are okay with "choose your own type of variable" on a case by case basis, or if we wanna stick to either CSS vars or SCSS vars?

Note that whatever we decide, changes will slowly roll out. This ticket is just for settling on an agreement between devs so we know what to do going forward.

**Comment by Pomax** [comment]
I think scss vars are good for "static" values, i.e. things that aren't going to even change. That includes things like styleguide colors, breakpoints, etc.

For more fluid values, e.g. custom front-end work with spacing that is independent of bootstrap, or "cool custom stuff" like the youtube tunnel or creep-o-meter things, having the flexibility of CSS variables feels worth using.

**Comment by mmmavis** [comment]
I'm good with choosing the more suitable type of vars on a case by case basis.

Closing this ticket. 🎉
