### ISSUE TITLE
Conduct web properties audit

### ISSUE THREAD

**Issue by hannahkane** [mozilla/foundation.mozilla.org#555]
This is only tangentially related to the Network site, but I think this is the best repo to file this.

Review all existing web properties and compile a list of recommendations about what to do with various content, functionality, etc.

**Comment by gvn** [comment]
I'm kind of vague on the ask here. Can you clarify this more?

**Comment by hannahkane** [comment]
Sure. We're reviewing all of the various Mofo web properties with an eye towards what content should be pulled into the Network site (perhaps allowing us to sunset some other properties).

No specific ask for engineering right now, but let me know if you'd like to be involved in this early on.

**Comment by hannahkane** [comment]
This work has begun and will continue for awhile, so rolling into next heartbeat.

**Comment by xmatthewx** [comment]
Work is ongoing. Had a good kickoff. Roll ticket over or track in planning docs?

**Comment by hannahkane** [comment]
Will roll over.

**Comment by hannahkane** [comment]
Conversations with several stakeholders have happened, and a few more are scheduled for next week. 

One tangible output will be a plan for how issue-specific content (e.g. web literacy map/curriculum) will show up on the Network site in the future.

**Comment by kristinashu** [comment]
I feel like this work has happened, closing but @xmatthewx please reopen if needed.

**Comment by xmatthewx** [comment]
Sydette is working on content migration plan. I don't think we need to track that here.
