### ISSUE TITLE
PNI launch: ensure we have enough dynos running before mail-out

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5556]
While heroku is set to autoscale based on demand we probably want to make sure that heroku is already scaled up before we send out our emails/notices.

This will require some more work than just prescaling, because the autoscaler will immediately scale back down if it doesn't see the expected load, requiring a temporary bypass. @cadecairos did give us instructions on how to do this, but we'll need to make sure we know how to make things work.

**Comment by tomusher** [comment]
Hirefire is used for autoscaling - to force it to scale up, we can increase the minimum number of dynos it will scale down to.

To do this:

1. Login to https://manager.hirefire.io/ with the HireFire credentials in 1password
2. Find the applicable site in the list and select the 'web' manager in the list.
3. In the manager details page, click the cog to the top right of the Manager pane
4. Increase the Minimum Dyno Quantity, and if necessary, the Maximum Dyno Quantity
5. Save your changes

Of course you can always give me a shout if you need this doing.

**Comment by anilkanji** [comment]
FYI PNI launching November 11, launch email set to go out November 12.

**Comment by kristinashu** [comment]
Via @taisdesouzalessa here are the numbers for PNI 2019. I kept the data range bigger than a few months because we had a very high peak on May 2020. The biggest numbers in a given day were 13,835 (11/27/19) and 16,734 (4/28/20). More details can be seen [here](https://drive.google.com/drive/folders/1322hi_4cxl1FyyPGb3JFU321Zvc4lEpp). 

cc @phildexter @jamilasnell

**Comment by kristinashu** [comment]
Via @anilkanji: emails going out to promote PNI on Nov 12, 27, Dec 9, Dec 17. I think 1.8M is our entire list including inactives - we sent to a smaller list last year - and we're not much that bigger now - here are the results from last year's launch email

![image](https://user-images.githubusercontent.com/1068783/98322377-1d305c80-1f9c-11eb-8cd0-c039cd3d12a4.png)

**Comment by taisdesouzalessa** [comment]
**Do we know if those big spikes correspond with days emails were sent out?**
_We know and the answer is: sometimes. For the second big spike (on April), email was sure a big factor (as it is in the majority of our initiatives). However for the first big spike (Nov, 2019) the main factor seems to be social and direct (we tend to have lots of media coverage for PNI) and also snippet (Lindsay may be the person to connect if you want to learn when we will add PNI to snippets-let me know if you want to connect with her and I can connect you both via Slack). I added all the reports to [our folder](https://drive.google.com/drive/folders/1322hi_4cxl1FyyPGb3JFU321Zvc4lEpp?usp=sharing) so you can see more details (I learned about the snippets by diving deeper into those, so let me know if you need that as well)_

**Do we have concurrent user figures for the same period?**
_Do you mean how many users were in our site? If so, I added a column to our spreadsheet containing users [here](https://docs.google.com/spreadsheets/d/1Ismex3qlLS2w55aBERpRcyamrpiNRfuxUfTbFmweiL4/edit?usp=sharing)

**Comment by kristinashu** [comment]
Via Tom on Slack 
> Foundation site is now set to scale between 10 and 20 dynos - I'll keep an eye on this and drop it back down on Friday if we don't end up using that capacity.
