### ISSUE TITLE
PNI - adjust search bar width

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5559]
Adjust search bar's width so it aligns better with mobile category nav (refer to design on the right and ignore the one on the left)
<img src="https://user-images.githubusercontent.com/2492510/97931152-dd5e4080-1d21-11eb-9954-5974d9961c62.png">

For more context see See https://github.com/mozilla/foundation.mozilla.org/pull/5551#issuecomment-720788496

**Comment by mmmavis** [comment]
I should work on the GA events ticket first. Gonna release this ticket back to the unassigned pool.

**Comment by kristinashu** [comment]
Can I piggyback off this ticket? 

### Search box width should stay the same when a user clicks into it
I noticed that at narrow widths the search box changes width slightly when I click into the it.
- [ ] Search box should stay the same width at narrow widths

**Screen cap from a PR**
<img width="445" alt="image" src="https://user-images.githubusercontent.com/1068783/98275768-e598c480-1f49-11eb-8ce9-e2af80553da5.png">

**Comment by mmmavis** [comment]
@sabrinang does the above apply to tablet and below OR just mobile?

**Comment by sabrinang** [comment]
@mmmavis I'd say tablet and below as it changes to dropdown <768px so adjust it to the exposed search bar style to match the width.
