### ISSUE TITLE
PNI: Comment Tap on Product Pages

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5562]
**Background:**
I forgot to add an extra event in the product page (sorry!), I wanted to know how many people tap the button "sign in to comment" as this may be a form of light engagement (same level as "sharing a page")

<img width="970" alt="image" src="https://user-images.githubusercontent.com/22157921/98143171-9be2a800-1e7d-11eb-88b0-48c7c9a54c97.png">

**To do**
- [ ] Add event as described on [our spreadsheet ](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit?usp=sharing)(row A12) - let me know if you have any suggestions for better naming/labeling or if you think it is clear enough.

**Comment by mmmavis** [comment]
Hey @taisdesouzalessa , unfortunately since this is an iframe from outside of foundation.mozilla.org, we can't access / attach GA event to elements within it. 

I'm gonna close this ticket since it's not possible for us to do.
