### ISSUE TITLE
PNI: search box style improvements

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5571]
Two nice-to-haves for the search box.

### Edge of the search icon is cut off on desktop

- [x] Show the entire icon

Screen cap from PR https://github.com/mozilla/foundation.mozilla.org/pull/5561
<img width="43" alt="Screen Shot 2020-11-04 at 9 12 11 AM" src="https://user-images.githubusercontent.com/1068783/98144300-165ff780-1e7f-11eb-9106-d47244af9d7f.png">

### Expand the hit area for the expanding the search box on desktop

Currently only the search icon will expand the search box. It would make for a better UX if users had a large hit area - maybe a square the same height as the search box (I think that's 62px)

- [x] Expand hit area of the search icon

Screen cap from PR https://github.com/mozilla/foundation.mozilla.org/pull/5561
<img width="294" alt="Screen Shot 2020-11-04 at 9 12 24 AM" src="https://user-images.githubusercontent.com/1068783/98144301-16f88e00-1e7f-11eb-9d69-dff8521c4e2f.png">

**Comment by Pomax** [comment]
technically the hitbox is already huge, it's just missing the `cursor: pointer` part, so both of these should be easy to add
