### ISSUE TITLE
RCS Challenge + Playbook: pre-launch list

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5595]
Update: act on Kathy's feedback - added at the end of the thread. Content not finalized yet.

**[Playbook:](https://foundation.mozilla.org/en/what-we-fund/awards/responsible-computer-science-challenge-rcs-playbook/)**
- [ ] make sure content is finalized 
- [ ] do a last design review (usability issues/formatting issues), all illustrations are done so we shouldn't have any asset to create

**[RCS Challenge:](https://foundation.mozilla.org/en/what-we-fund/awards/responsible-computer-science-challenge)**
- [ ] publish "Resources" page on Wagtail
- [ ] publish "Overview" draft (containing link to "Resources" page)
- [ ] delete "Community" page 
- [ ] make sure everybody who needs to have access to this page have the permission (list will be sent by Kathy) OR confirm with Kathy she will be the central point of contact (discussion happening in the doc highlighted on this ticket)
- [ ] deliver jpgs/png/layered file of the banner so Kathy can use it for different projects

**Relevant document:**
- [ ] [Shared doc](https://docs.google.com/document/d/1bIu5apYyfS8481kDP9_Z327wTLf8DJrvxLSSyfZ8YOo/edit?usp=sharing) between Taís, Kathy and Jenn.

**Comment by taisdesouzalessa** [comment]
@kristinashu @jamilasnell - since this content will be only ready during the week of Dec 14-18th we should probably move it to January sprint, what do you think? We're very close to be done!

**Comment by taisdesouzalessa** [comment]
Moved this to Jan 2021

**Comment by kristinashu** [comment]
@taisdesouzalessa is there an updated eta for this :)

**Comment by taisdesouzalessa** [comment]
Unfortunately not yet. Will ping Kathy and Jenn.

**Comment by taisdesouzalessa** [comment]
@kristinashu will have to bump this to next sprint. Here is the answer from Kathy: 

> "Aim is end of this week and I put it up on wagtail by Friday. I’ll check in with our copy editor Tuesday !"

**Comment by taisdesouzalessa** [comment]
From Kathy:
"There are four sections so far that are fully done in case this is helpful to do a design review. If you prefer to wait for all the sections to be done, that works too. It would be helpful to me to have you take a look though and let me know if there are some design details you should change. A few top of mind:
    

- I took out the "Next Play" section since we now have navigation on the left and the playbook isn't really sequential
- The author section at the bottom looks a little weird. Thoughts on how to make that a little cleaner? Right now, we have one or multiple authors per section. The Accreditation one is a good one to look at: https://foundation.mozilla.org/en/what-we-fund/awards/responsible-computer-science-challenge-rcs-playbook/topics/accreditation-and-ethics/
- Any thoughts on all the text in the example sections? It's a lot of text, which I think is OK, but wanted to ask you.The example section will have examples from multiple universities, and would love thoughts on how to best display this. Right now, the University Name headers are h4, not sure if there's a clearer way to do this"

**Comment by taisdesouzalessa** [comment]
> I took out the "Next Play" section since we now have navigation on the left and the playbook isn't really sequential

1. **Taís:** Agree, I removed the item from all the posts, including the "Draft" ones.

> The author section at the bottom looks a little weird. Thoughts on how to make that a little cleaner? Right now, we have one or multiple authors per section. The Accreditation one is a good one to look at: https://foundation.mozilla.org/en/what-we-fund/awards/responsible-computer-science-challenge-rcs-playbook/topics/accreditation-and-ethics/

2. **How about this?**
<img width="636" alt="image" src="https://user-images.githubusercontent.com/22157921/106333885-70821600-623e-11eb-8ecb-9b8d416b5cbf.png">

> Any thoughts on all the text in the example sections? It's a lot of text, which I think is OK, but wanted to ask you.The example section will have examples from multiple universities, and would love thoughts on how to best display this. Right now, the University Name headers are h4, not sure if there's a clearer way to do this"
3. **Taís:** Let's leave as is for now and if things get too complicated we may think about a solution

**Question for Kathy:** What are the plans of this project once it is launched? Are we thinking about expanding it over time (will more people contribute to it?)

Sent this via email to her. We are already doing a design review by looking into the issues while the content is being populated.

**Comment by taisdesouzalessa** [comment]
Created a new ticket for this issue here: #6129
During this sprint we did this work (partially) - around 2 hours of it. Figuring out how to solve some little issues that popped up from the parts that are ready to go. Closing this one. cc: @kristinashu @jamilasnell
