### ISSUE TITLE
PNI - Wagtilification & Localisation Design QA

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#5596]
Provide any design support to Pomax and Kalob as they will be turning Privacy Not Included into a full wagtail site. In this sprint, it may mostly be backend but provide design support _(general design reviews of PRs, QA, and answering questions) throughout the development process. 

Related epic: https://github.com/mozilla/foundation.mozilla.org/issues/5506

**Comment by kristinashu** [comment]
Sabs, I think you're going to be pretty busy so I can take this ticket on.

**Comment by kristinashu** [comment]
@KalobTaulien please assign this to me once the work is on staging. Jen and I will do some additional QA on it.

**Comment by kristinashu** [comment]
Thank you @sabrinang for your help with QA. Will leave this open to QA the site again once it lands on prod Monday.
