### ISSUE TITLE
PNI: increase hit area of search bar

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5610]
Phil and I both tried to active the search by clicking the right of the search icon. We think it would be better UX if the hit area expanded much more to the right (perhaps all the way to the creep-o-meter face). 

Todo
- [ ] Expand hit area (and cursor state) to the right of the search icon

![Screen-Shot-2020-11-09-at-12 54 48-PM](https://user-images.githubusercontent.com/1068783/98595653-20249900-228b-11eb-9a2a-26edbc243496.jpg)

cc @sabrinang

**Comment by Pomax** [comment]
given how the search bar is currently implement, we can't extend the hit area further right. We can only do this by rewriting the html+css that we're currently using, which we won't be able to do before launch.

**Comment by kristinashu** [comment]
Ok thank you for looking into it Pomax.

**Comment by jamilasnell** [comment]
@kristinashu Should we close this ticket? Or keep it for cleanup stage later?

**Comment by kristinashu** [comment]
Please keep it.

**Comment by Pomax** [comment]
This is an incredibly hard piece of  work given how the search bar was implemented, we can fold this into the work around cleaning that up, but we will not be able to do this for the search bar in its current form. Closing this issue, and will update the code cleanup issue for the search bar.
