### ISSUE TITLE
Intro string on What We Do is too long to be localized

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#5614]
Hey @kristinashu, I published the [German version of What We Do](https://foundation.mozilla.org/de/what-we-do/), but I ran into an issue with the `Intro` field — the translations are well over the 250 characters limit, and the EN copy is 246 characters

Current copy:

`Mozilla invests in bold ideas, global leaders, and the convening and campaign power of people. For more than two decades, we’ve worked across borders, disciplines, and technologies to fuel a movement to realize the full potential of the internet.` 

For reference, the current German translation is 338 characters long

So, I see 3 ways of sorting this one out:
- Significantly shorten the EN copy and get new translations
- Increase the character limit to at least 350 (This will also increase the limit for other pages)
- Do a bit of both

Do you see any other way? What do you suggest?

**Comment by kristinashu** [comment]
Hi @TheoChevalier I think increasing the character count to 350 sounds good. I don't have any design concerns with that.

**Comment by TheoChevalier** [comment]
> Hi @TheoChevalier I think increasing the character count to 350 sounds good. I don't have any design concerns with that.

Thanks! Just filed #5647 for implementation, and closing this ticket
