### ISSUE TITLE
MozFest Dev Specific Landing Page 

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#5615]
Allow the mofest homepage to have additional homepages as children, so that we can make a mozfest landing page that is specifically geared towards devs

Acceptance Criteria
- [x] CMS users can create a homepage as a child of a homepage 
- [x] Nav doesn't change when homepages are created/added 
- [x] Nav on child page keeps working as on the real homepage

**Comment by anilkanji** [comment]
@marcwalsh FYI

**Comment by anilkanji** [comment]
From Marc: 
  *  We're looking for the homepage template to be available as a child page template - mostly so we have the video banner and header style available to use for when we're creating the landing pages for a specific audience. We will likely use this for a couple of audiences like developers and the local Amsterdam community. The pieces Jamila mentioned in the GH issue are exactly right!
 *   For the signup form - our intention was to try and make this as simple as possible. As we've done for the other audiences that we've segmented, we would just be looking to use the Signup Source URL as the way of splitting these out. Having the ability to attach a Campaign ID to existing and new records would be great, but I also imagine this would be a much greater lift to get ready - so maybe it's something we can look at implementing in the future?

**Comment by anilkanji** [comment]
@Pomax StephMcV recommends a quick chat with her and Marc to confirm specifics around the signup form.

**Comment by Pomax** [comment]
Sure - having checked what the code change involved allows, we would literally have "a homepage" that we can do with what we can do for the current homepage too. That includes pointing it to a new signup CTA specific to that second homepage.

**Comment by Pomax** [comment]
folllowup based on requirements by stakeholders: https://github.com/mozilla/foundation.mozilla.org/issues/5712
