### ISSUE TITLE
#DearInternet - Stakeholder Kickoff

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#5618]
Stakeholder Kickoff with Audrey

- [x] schedule kick-off call
- [x] fill out brief and conduct [interview](https://docs.google.com/document/d/1cPPRZBq9LbBbrIYywXTBzWgykVzjDCXuwK4X5D2bT_I/edit)
- [x] ask Audrey about legal review process (sharing story submissions)
- [x] chat about project timeline and milestones

Planning issue: https://github.com/mozilla/foundation.mozilla.org/issues/5598

**Comment by sabrinang** [comment]
Kickoff call scheduled for Thursday Nov 12

**Comment by sabrinang** [comment]
@Audreymofo if you want to fill out any notes for the landing page design brief before our call feel free to do so here: https://www.google.com/url?q=https://docs.google.com/document/d/1amXbYnx3iN6fVDb9SDRIOCwwPStcMKZ90xkgKE2y6ps/edit?usp%3Dsharing&sa=D&source=calendar&ust=1605466268269000&usg=AOvVaw2JRPJPvrllNhqIrxe6Gl3p

**Comment by Audreymofo** [comment]
Hey! Is it possible to do the call Wednesday? I have a volunteer call for the food bank I volunteer at 6pm Thursday

**Comment by sabrinang** [comment]
@Audreymofo It's a Candian holiday tomorrow for us and I'm attending a conference in the morning so Wednesday is unlikely. 

Any other time Thursday? _(gcal was looking occupied so I didn't know what other time block would work)_

**Comment by sabrinang** [comment]
We had our call yesterday and the [brief](https://docs.google.com/document/d/1amXbYnx3iN6fVDb9SDRIOCwwPStcMKZ90xkgKE2y6ps/edit?usp=sharing) has been filled out and contains copy for MVP landing page as well.
