### ISSUE TITLE
clean up the about page nav link CSS override + em dashes

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5627]
@KalobTaulien had to do some rejiggering of the CSS for the about page nav links:

- [ ] we should have a look at to see whether that feels good, or whether we can do that cleaner. See the `network-api/networkapi/buyersguide/templates/about/about_nav.html` file.
- [x] We're also mixing `&mdash;` and `—`, and mixing "em dash with spaces" with "em dash without spaces" so let's clean that up at the same time.
- [ ] some of our links are hardcoded to point to `foundation.mozilla.org` instead of being relative links, which caused some fun misconclusions about the state of things on staging =D
- [x] A link has been removed by mistake
- [x] Typo in Steve Inskeep’s name in Press section (checked with Kevin what was the correct spelling)
- [x] Typo and localization fixes ported over from Théo’s review

**Comment by TheoChevalier** [comment]
@KalobTaulien @mmmavis Whoever is taking this ticket, please add changes on top of this branch — I took a head start https://github.com/mozilla/foundation.mozilla.org/tree/about-pages-copy-fixes

**Comment by mmmavis** [comment]
@TheoChevalier do you wanna start a PR for your branch so we know what have been fixed in your branch? 😉

**Comment by TheoChevalier** [comment]
> @TheoChevalier do you wanna start a PR for your branch so we know what has been fixed in your branch? 😉

Sure, just opened #5666
