### ISSUE TITLE
Redirects issue

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5634]
**Background:**

Recently we did 2 page redirects:

1. From `/initiatives/leadershipgiving` to `/giving/mozilla-guardian-giving-program/`
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/22157921/99101254-2f5c5d00-2591-11eb-94f4-0f06dd07e625.png">

2. From `/blog/category/internet-health-report` to `/blog/category/insights/ `
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/22157921/99101575-a2fe6a00-2591-11eb-9a6c-40cb2f758a94.png">

For each page, we did the 2 redirects (one without the /en/ locale and one with it).  
In both page redirects, **the URL that contains /en/** doesn't work as expected (redirect doesn't function properly). 

**Request:**
Investigate the issue and guide designers on how to fix it (if there is anything we can do on our end).

cc: @jamilasnell

**Comment by Pomax** [comment]
Redirects for localized URLS using the CMS's "redirects" function do not work (and never have). Ideally, we have as few redirects as possible, but for any content that has a locale prefix we need to add a manual rule in our url patterns file (it's a code change, not something that can be done through the CMS).

I see there are many other redirects in the CMS right now with locale codes: _none of those work_ so it feels like we need a better solution here. @kristinashu @KalobTaulien we probably want to brainstorm on what the options are here, given that wagtail's several versions newer compared to when we added our locale solution, and maybe there is a way to finally add locale URL redirects, or even figure out how to make it redirects apply to "any locale as well".

**Comment by Pomax** [comment]
I've done some digging, and I think I have a fix for this issue but it's a fix "at the wagtail level" so I've filed [an issue](https://github.com/wagtail/wagtail/issues/6587) on the wagtail repo as well as [a PR to fix this](https://github.com/wagtail/wagtail/pull/6588) and hopefully with some help from @KalobTaulien we can get this landed so that redirects just... work.

**Comment by Pomax** [comment]
fixed!
