### ISSUE TITLE
Fixing links that include /en in the CMS

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#5646]
### Current issue:

Links to the foundation site (or MozFest, PNI…) that are used in content very often contain `/en`, forcing users that have deliberately switched to a localized version of our site to go back to the English version. Or at the very least, preventing locale negociation to automatically redirect them to the language matching their browser settings.

The English page can then contain autogenerated links that with a dynamic locale code (which is expected), keeping them further away from the localized content. It will remain the case until they click on a locale-neutral link (one without any locale specified).

It makes it very hard to stay on a localized version of our site, and makes localized content even less discoverable.

### This issue needs to be fixed for:
- URL fields where a CMS user manually inputs a link
- Inline links in content, wrongfully used as "External links"

### Solution :
- [ ] Create a one-off DB update to remove links with hard-coded locales
- [ ] Train staff on not using hard coded localized URLs

**Comment by Pomax** [comment]
In terms of the database work, the cleanest option I can come up with is the following:

- [ ] dump the (stage|prod) database to a SQL file
- [ ] `sed -i 's/mozilla.org\/en\//mozilla.org\//g` database_dump.sql`
- [ ] setting (stage|prod) to maintenance mode
- [ ] dropping the (stage|prod) db
- [ ] importing the `database_dump.sql` 
- [ ] turning off maintenance mode for (stage|prod) again

I've tested this locally and it seems to work quite well, and is a relatively fast process too (locally it takes ~1min so running against stage/prod it would probably be more like 5~10min), but we probably want to hold off on actually doing this work until site visits have dropped back down after valentine's day so if something _does_ go wrong, we don't interfere with V-day PNI activity.

**Comment by Pomax** [comment]
@benhohner added you as secondary assignee because we'll want to make sure we time this right. And test it on staging. Maybe twice =)

**Comment by benhohner** [comment]
@Pomax 
Some things to ponder:
1. Are we sure there are no strings that would cause the website to break if they were renamed?
2. How can we verify that everything works after the changes?
3. Do we have DB backups? Can we take one before we do the changes (so as to not lose people's work)? And if so, how long would a backup take to restore?
4. Any way we can just figure out the couple fields and tables that need to be updated and run a SQL replace query?

**Comment by TheoChevalier** [comment]
On the “Train staff on not using hard coded localized URLs”, I’m a bit dubious. I’ve already tried that for a very small subset of staff, and asked people to do it on at least some strategic parts of the content, but even this failed. Trained staff tend to forget half the time.
So training all staff, including people managing content that we rarely or don’t translate at all, that seems ambitious.

Here are additional ideas on what we could do:

1. Finding a way to regularly check /en is no longer hardcoded, so that we can monitor the situation & evaluate with data, and see if additional measures are necessary
2. When saving a page, automatically converting an external link into an internal one when linking to the site’s domain
3. Add an option to copy the neutral URL from this menu? Or somewhere else in the page, displayed to authenticated users?
<img width="245" alt="Capture d’écran 2021-02-11 à 15 35 00" src="https://user-images.githubusercontent.com/1294206/107650380-569cf600-6c76-11eb-8c19-c32dad2f447d.png">

Note on the query above, we may want to restrict the change to foundation.mozilla.org, as it will match other Mozilla properties. I have `https://community.mozilla.org/en/` and `https://commonvoice.mozilla.org/en/` in mind, and in both cases our change will perfectly work and be beneficial, but there may be other domains that don’t have proper redirects.
We will also want to run this for `mozillafestival.org/en` I presume? That should be a much lower number of occurrences, though.
What about relative links starting with `/en/` or `en/`? That’s also probably not a lot…

**Comment by benhohner** [comment]
Need to find date to do this

**Comment by jamilasnell** [comment]
We have created tickets for the actions that need to take place. We are closing this ticket but the follow-up tickets should refer back to this original ticket.
