### ISSUE TITLE
#DearInternet - Wireframes

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#5650]
Create wireframe mockup based on chosen direction and finalize copy.

**Comment by sabrinang** [comment]
@Audreymofo please review what copy you want for the landing page, I iterated two options:

1 (copy from brief): https://share.goabstract.com/6b7dffe7-d1ef-48c6-a2b2-35488612074e?collectionLayerId=697f45b2-ad41-45c2-9801-421dccd0c2da&mode=design  _(goes more with the graphics we have for MVP site)_

2 (copy inspired by insta story): https://share.goabstract.com/6b7dffe7-d1ef-48c6-a2b2-35488612074e?collectionLayerId=a59bb443-a107-4610-befc-611220624c6c&mode=design _(goes more with the graphics we have for insta story)_

May be good to consider a heading before the letters section if we go option 1 and this will help determine what art I export for the top section of the page and layout. Let me know if you need more details. 

______________

/cc @mmmavis I updated the wireframes

**Comment by kristinashu** [comment]
Via Slack Audrey says she prefers Option 1 so we'll run with that! 

> I think option 1 is better, mainly because I think option 2 is too much scrolling (it is a great idea though and very beautiful!)
