### ISSUE TITLE
Add polish / effects to #DearInternet Page

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5659]
Because of the tight deadline, we should aim for getting the MVP version of #DearInternet Page built (#5616 ). If time allows, add polish and effects to the page to make it shine more.

More details to come once we have finalized design.

**Things we can polish ideas:**
- [x] Plane path: streamline start and end _(extend path?)_
   - update svg with a longer path (https://drive.google.com/open?id=1FJ5oEcUrMwVH68YStnpuRhv5wjiTRROo&authuser=sabrina%40mozillafoundation.org&usp=drive_fs)
- [x] Plane: scroll animation
  - similiar to what mavis has in the codepen 
- [x] adapt share buttons on mobile _(currently none)_
   - put them before the 3 envelopes in the CTA section
- [x] adjust heading/love letter graphic size on mobile _(to be a bit larger)_
  - enlarge them to full width on small mobile
- [x] h1 sizing on mobile
  - enlarge it a bit
- [x] adjust heart path top margin on larger desktop _(still a bit close to last letter)_
- [x] any accessibility improvements we can make?
  - 5th cloud (light-pink): change it to light-blue
  - very last cloud (light-blue): change it to white

**Comment by mmmavis** [comment]
@sabrinang can you help update the ticket description with things we wanna add polish on?

**Comment by sabrinang** [comment]
@mmmavis I updated description with ideas of things we can polish
