### ISSUE TITLE
Decide analytic events to add to #DearInternet page

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5660]
details to come later

---

implementation ticket #5661

**Comment by taisdesouzalessa** [comment]
@sabrinang please let me know how I can support/be your thinking partner on this :).

**Comment by sabrinang** [comment]
I began a doc for analytics here: https://docs.google.com/document/d/1wN5j-tfPjE7X9pRWfWow0ZSVW06kwn-uBye-uJsaGz4/edit?usp=sharing

@taisdesouzalessa It'd be great if you have any feedback on the notes and help me identify and think through what may be missing.

**Comment by taisdesouzalessa** [comment]
It looks great, Sabs. I like you added the goals on top so I can give feedback on the metrics with that frame as a reference. I added some notes in the doc and some suggestions.

**Comment by mmmavis** [comment]
Doc looks great! Left some comments in the doc but I think we should be able to track most things mentioned there. 👍

**Comment by sabrinang** [comment]
Thank you for all the input Tais and Mavis!
@taisdesouzalessa I'll need your assistance to translate these events to the [Analytics Site Events spreadsheet](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=873537793) but I added a "#DearInternet" tab.

**Comment by taisdesouzalessa** [comment]
@sabrinang good idea adding its own tab :). This is a good article that explains the difference between terms: https://support.google.com/analytics/answer/1033068?hl=en - they explain better than I would...haha. Let me know if you have any questions or how I can help, happy to support any way I can.

**Comment by sabrinang** [comment]
Reviewed and filled out the spreadsheet with Tais https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=873537793 to decided which events we want to track. Ready for implementation and I can schedule to meet with Mavis for #5661
