### ISSUE TITLE
Implement analytic events for #DearInternet page

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5661]
Implement analytic events decided in #5660

**Comment by sabrinang** [comment]
We decided which events we want for DearInternet, spreadsheet here: https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=873537793

@mmmavis We can schedule a call to go over it

**Comment by mmmavis** [comment]
This is more involved than expected. Gonna up the estimate to 4.

**Comment by mmmavis** [comment]
Events have been implemented. I've migrated events in the sheet from `#DearInternet` tab to the `Foundation Site Events` tab: https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=779058050
