### ISSUE TITLE
PNI images hosted on Cloudinary are intermitently disappearing on Firefox

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#5662]
Pretty much everything is in the title, Lindsay & I have been experiencing missing images since yesterday on PNI.

It doesn’t happen all the time, and a hard refresh doesn’t fix the issue. It doesn’t seem to happen in Chrome, though, only in Firefox as far as we can tell.

I’ve been able to reproduce on both Nightly and Release (83), and with a fresh profile.

![Screenshot_2020-11-17  confidentialité non incluse un guide d’achat pour les objets connectés](https://user-images.githubusercontent.com/1294206/99542063-830fe180-29a9-11eb-9619-6139348cda37.png)

@tomusher are you aware of any related Cloudinary issues?

**Comment by Pomax** [comment]
Are there any errors in the dev console when you see this happening?

**Comment by TheoChevalier** [comment]
Unfortunately no, I’m just seeing 0 Byte data transfer in the Network panel from the DevTools 
<img width="1352" alt="Capture d’écran 2020-11-18 à 17 16 10" src="https://user-images.githubusercontent.com/1294206/99556502-801ced00-29b9-11eb-9466-fd820867958e.png">

**Comment by jamilasnell** [comment]
Potential solution: we are removing cloudinary as Wagtail has it's own internal tools for imaging!

**Comment by kristinashu** [comment]
Is this good to close?

**Comment by Pomax** [comment]
Closing this as we'll be moving over to Cloudflare for caching purposes soon.
