### ISSUE TITLE
Review apps and dev/stage/prod do not build the mozfest site in the same way

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5674]
- dev/stage/prod create mozfest as a top level site, a sibling to the foundation homepage.
- Review apps create mozfest as a child of the main site homepage.

This causes problems when we need to test backend changes that affect mozfest, as we need to know whether things work with the mozfest page being a true site root. Most importantly, moving the mozfest page to be a top level page and then updating the `sites` setting to make the mozfest page the default site landing page causes the review app to crash.

We need to fix this so that review apps build the same tree structure as local dev/stage/prod, even if that means we still need to go in and manually "undefault" the `homepage` site, then mark the `mozfest` site as default

**Comment by Pomax** [comment]
This is still not building two sites, once for homepage, and one for mozfest, the same way local dev works.

**Comment by Pomax** [comment]
Right now the way to make this at least work is to:
1. go into `sites` and change the page from `Homepage` to `MozFest`
2. save the site update
3. in heroku, restart the review app dyno

![screenshot 669](https://user-images.githubusercontent.com/177243/101401353-150f5980-3887-11eb-873a-c28b5ec54302.png)


Once restarted, the review app will now be a normal mozfest app.

**Comment by KalobTaulien** [comment]
There's currently no way to build two sites on a single Heroku instance. Typically we use another hostname or port, but we're only given the one review app hostname and heroku doesn't allow for additional ports. 

@Pomax What are you thinking for next steps? Bring in Tom to check this out?

**Comment by jamilasnell** [comment]
Hey @tomusher, Happy New Year! Would you be willing to help out with this issue? It deals with Heroku and there are some elements that Kalob and Pomax need assistance with. 

Thank you in advance!

**Comment by tomusher** [comment]
If I'm reading this correctly, this covers the same ground as https://github.com/mozilla/foundation.mozilla.org/issues/5736#issuecomment-736627685. Do any of the options there sound like they'd help with this @Pomax @KalobTaulien?

**Comment by KalobTaulien** [comment]
Hey @tomusher 

Personally, I like option #2, but you're right it's more complicated — also more future proof. In my opinion, if we're going to do something we might as well do it right. But I won't speak on behalf of Mozilla — @Pomax what do you think about option 2 from [this comment](https://github.com/mozilla/foundation.mozilla.org/issues/5736#issuecomment-736627685)?

We also briefly spoke about looking for a tag in the branch that's deploying the review app. So if we tag a branch with "mozfest" it could change the site to be a mozfest site. Frankly I dont know enough about devops to tell if this is doable or not.

**Comment by Pomax** [comment]
yeah #2 is definitely the way to go

**Comment by Pomax** [comment]
Also, let me close this issue in favour of https://github.com/mozilla/foundation.mozilla.org/issues/5736 so there's one place for the discussion around this =)
