### ISSUE TITLE
Spike: investigate whether a 600 width cloudinary image is needed

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#5677]
In `network-api/networkapi/buyersguide/templates/buyersguide/catalog.html` line 90 there is:
```html
src="{% cloudinary_url product.cloudinary_image quality=50 fetch_format="auto" crop="fit" width=600 %}"
```

We need to investigate whether we actually need 600-width images here or if we can go lower.

**Comment by jamilasnell** [comment]
@kristinashu only input needed from you on this is knowing if 600 width is needed!

**Comment by kristinashu** [comment]
Does that mean 600 px wide? That does seem bigger than we need. Design saves product the images out at 400 x 400px and that is close to the what I think the biggest size is.

**Comment by Pomax** [comment]
They get constrained on the page itself, to 200x200 on desktop width, so based on that 400 should cover both regular and retina (2x) resolution.

**Comment by Pomax** [comment]
reassigning to @KalobTaulien (if you have no time this sprint, though, feel free to punt back)

**Comment by KalobTaulien** [comment]
The largest image is on tablet (just under 768px wide browsers) and the image is 359x359. SO having cloudinary set to 600 is still a good idea. 

But there's room for improvement here. We could use the `<picture>` element to give a source set and produce a smaller image for non retina, and a higher image for retina displays. 

Example:
```html
<picture>
 <source
   media="(min-width: 900px)"
   srcset="large-image_1x.jpeg 1x, large-image_retina.jpeg 2x"
   type="image/jpeg >
 <source
   media="(min-width: 601px)"
   srcset="medium-image_1x.webp 1x, medium-image_retina.jpeg 2x"
   type="image/jpeg" >
 <source
   media="(max-width: 600px)"
   srcset="small-image_1x.webp 1x, small-image_1x.jpeg 1x"
   type="image/jpeg" >
 <img
   src="large-image_1x.jpg"
   type="image/jpeg"
   alt="my image description">
</picture>
```

When we move PNI to Wagtail, we can also output .webp images for Chrome users. 

I'm going to open a new stretch ticket for this idea so we can serve the right images to the right devices without overspending the users bandwidth.
