### ISSUE TITLE
Create images for TAI Whitepaper

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5681]
Once all the content is in - Import AI Whitepaper with Publications Template #5536, we should add some of standard MoFo AI graphics to it.

**Comment by sabrinang** [comment]
Ready for review @kristinashu 
- Iterated on abstract background banner options and updated redpen: https://redpen.io/p/nqe11451b1e355f06b
- Some are placed in https://foundation.mozilla.org/en/insights/trustworthy-ai-whitepaper/ to test and can update as stakeholders continue to update content.
- Exported to google drive here: https://drive.google.com/open?id=1Eo8Gt7n0efRTBvitkyR5MRQOvJFUyZVc&authuser=sabrina%40mozillafoundation.org&usp=drive_fs

**Comment by kristinashu** [comment]
These look great Sabs! I actually like how the dark overlay makes it feel more serious, perfect for the audience.
