### ISSUE TITLE
[Publications] Design QA

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5682]
Once all the content has been entered in https://github.com/mozilla/foundation.mozilla.org/issues/5536. Design to do further QA, combine feedback with the ([existing feedback](https://github.com/mozilla/foundation.mozilla.org/issues/5312#issuecomment-715640663)), and open dev tickets for implementation.

**Comment by sabrinang** [comment]
**Things to revise:**
- Navigation: missing menu on viewports > 990px _(should be similar to blog nav)_
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/2492510/100813692-b7958b80-33f4-11eb-858a-7acacd15b92f.png">

- Publications heading subtitle: 20px/30px to be body-large size (currently 28px/36px)

- Footnotes: feel a bit too large especially when there are a few (suggested 14px/20px)

- Italics are in nunito light → nunito regular

**Feedback to consider:**
- should chapter/subchapter numbers be reflected on article pages?
- could footnotes be more user friendly? (wasn't as intuitive for user to use without guidance)
- numbered lists didn't copy and paste well (best to not copy/paste from pdf as it carries over some line breaks and omits some lists etc.)

These notes were taken from Jam and mine experience importing content: https://docs.google.com/document/d/1yM5DsKSeIUGktvx_x2G7S7EJe7pHDnEIkXMYtIMxj10/edit?usp=sharing

**Comment by sabrinang** [comment]
QA notes captured here and https://github.com/mozilla/foundation.mozilla.org/issues/5312#issuecomment-715640663. 
Ready for review and can meet Kalob on Monday to open tickets.

**Comment by sabrinang** [comment]
Reviewed this https://github.com/mozilla/foundation.mozilla.org/issues/5682#issuecomment-736926553 and previous https://github.com/mozilla/foundation.mozilla.org/issues/5312#issuecomment-715640663 with @KalobTaulien over zoom and he'll open up tickets based on those and get them into sprint planning tomorrow.
