### ISSUE TITLE
Zoom e2e Reportback 

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#5705]
### Describe the feature request
Concept and design featured here https://docs.google.com/document/d/1pLAHR1yDTLiIdkm6N9JHdoB7TLKq9Iv62PEhITgFFBw/edit

Would like this done by Nov. 25th but checking in with Audrey to see if that is still a goal of hers.

**Comment by jamilasnell** [comment]
Talked with Kaili and due date can actually be pushed back to end of sprint Dec. 7th

**Comment by kristinashu** [comment]
Opened a ticket in the design repo https://github.com/MozillaFoundation/Design/issues/707
