### ISSUE TITLE
[IA Refresh] Measuring success: part I

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5706]
**Background:**
According to our [Foundation Site Information Architecture](https://docs.google.com/presentation/d/19etCN1uGLcLmB50-uV-srsWKEAhlwlR_bc0dLE1uW1g/edit?usp=sharing) document, those were the 4 areas we want to focus to assess the success of our IA refresh initiative:

1. Reduce the bounce rate on our homepage by 20% through site updates based on user testing, analytics, and staff interviews
2. Qualitative testing finds that users’ understanding of Mozilla Foundation’s mission improves by 25% (conduct baseline/control test along with prototypes in April)
3. Qualitative testing finds that staff can more easily find the content they are looking for compared to initial IA audience report
4. Behaviour in Google Analytics shows users going to a diverse set of pages

**To do:**
- [x] First of all, we should take a look at Google Analytics and create a report to see if 1 and 4 were achieved and it not, why? [Report here →](https://docs.google.com/document/d/1qiZv-hmp4RLN5-rIfD5LR24yMCJHaOFWdgl78Y9ougU/edit?usp=sharing)
- [x] Confirm with Sarah W. if "Who we are" section is good to go as an MVP. [Copy here](https://docs.google.com/document/d/19Y5hNmEU4wix_gCoSvmhMKUk2F1Dht6Nwf1JQAu0lsg/edit?usp=sharing). 
- [x] If it is good to go, update the "Who we are page"  
- [x] Add Carys' picture to Leadership tab, requested by email on Nov 26 - @nancyt1 will do that, yay!
- [x] Put together a [list of key staff members](https://docs.google.com/document/d/1k7NtkJ2o3HfTn0x95PnAjfuMdIPN3eNr0czTYscJLB4/edit?usp=sharing) to interview about the new site
- [x] Start booking the interviews for next sprint. [Time slot sheet here](https://docs.google.com/spreadsheets/d/19wwKnffP0TN_0ut6EdslqKiWpGk3GugWMUXV1o-7J9w/edit?usp=sharing), booking as people add their names to it.

Part II is here: #5711

**Comment by taisdesouzalessa** [comment]
Started creating the report (draft stage-still very messy and I am trying to make sense of all data): [Report here](https://docs.google.com/document/d/1qiZv-hmp4RLN5-rIfD5LR24yMCJHaOFWdgl78Y9ougU/edit?usp=sharing)

Once I have a little more clarity/deep thinking on this report, I will share it with Nancy to hear her thoughts and discuss patterns.

**Comment by kristinashu** [comment]
Yay! @nancyt1 can now be assigned to issues in this repo!

**Comment by taisdesouzalessa** [comment]
@nancyt1 will add Carys picture to our site ([Leadership tab](https://foundation.mozilla.org/en/who-we-are/leadership/)).

**Picture:**

![carysheadshot](https://user-images.githubusercontent.com/22157921/100789876-e6e3d280-33cb-11eb-86d7-8d1d82599399.jpg)

**Full Name:** Carys Afoko.
**Tittle:** Director of Advocacy.

**Comment by nancyt1** [comment]
I added her to the page and also arranged the directors in alphabetical order!

**Comment by taisdesouzalessa** [comment]
So fast! Thank you so much, @nancyt1 :). Appreciate the help!

**Comment by taisdesouzalessa** [comment]
@kristinashu @sabrinang @natalieworth when you have some available time, can you give feedback on [this report](https://docs.google.com/document/d/1qiZv-hmp4RLN5-rIfD5LR24yMCJHaOFWdgl78Y9ougU/edit?usp=sharing)?
The goal was to look into Google Analytics and see if the items 1 and 4 of this ticket were achieved and if not, why. Feel free to add comments/questions/suggestions to the doc. Thank You!

**Comment by taisdesouzalessa** [comment]
All interviews scheduled (except for 1 that I will send a follow up message next week).
