### ISSUE TITLE
[MozFest] Add link to footer: Implementation ticket

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5737]
**To do:** 
- [ ] Add the "Become a Sponsor" link to MozFest site footer only (design ticket #5503)

**Resources:**
- [Here are the mockups](https://share.goabstract.com/5bea23cc-eee3-4a86-972c-d57c41891d2b?collectionLayerId=bc33fe87-ea1f-4378-b0f1-3ccd9c6e70e8&mode=design) on Abstract (second row - MozFest footers)
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/22157921/100681609-f6f6a600-3328-11eb-9519-1002f97d28ca.png">
- The new "Become a Sponsor" link will link to this page: 

**https://www.mozillafestival.org/sponsor/**

**Engineers: please let us know if there are any localization needs we should be aware of.**

tagging @jamilasnell for triage and assigning engineers

**Comment by jamilasnell** [comment]
@mmmavis Is this something that you can work on?

**Comment by mmmavis** [comment]
Yup!

**Comment by jamilasnell** [comment]
Thank you! Assigning this ticket to you!
