### ISSUE TITLE
[RCSC + Playbook] Delete old pages

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5763]
Redirects were done here:  #5710

I can't delete the hub "Responsible Computer Science Challenge". So I am creating this ticket to request engineers delete the page for me. < cc: @jamilasnell for triage

<img width="1441" alt="image" src="https://user-images.githubusercontent.com/22157921/101062034-fedf6180-3545-11eb-9b76-3c30b313f46b.png">

**Comment by Pomax** [comment]
Removed \o/
