### ISSUE TITLE
[What We Fund] Delete old pages

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5764]
What we Fund redirects were done here: #5197

**To do:**
- [x] Do QA of redirects: column F - [Spreadsheet here](https://docs.google.com/spreadsheets/d/1htYOLCDJgEXDmEArg0pliaTTcZY6yFzeSb7Kp6iDKjQ/edit?usp=sharing)
- [x] Delete old CMS pages (urls [here](https://docs.google.com/spreadsheets/d/1htYOLCDJgEXDmEArg0pliaTTcZY6yFzeSb7Kp6iDKjQ/edit?usp=sharing): column A, tab "What We Fund Redirects") - Hubs: Fellowships and Awards - they are "Unpublished" for now.
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/22157921/100942730-b75ac600-34b0-11eb-93e2-7968cb888f60.png">

@jamilasnell I don't have permission to delete things on Wagtail so can we assign this ticket to an engineer, please? It would also be good if they could do a quick QA before we delete the pages (I did one but always good to have another person to check since this is a project that will erase pages). It is non-urgent but good to have those pages deleted at some point before staff starts populating old pages we deprecated.

**Comment by Pomax** [comment]
The old CMS pages have been removed \o/
