### ISSUE TITLE
[Publications] Document How-to/Onboarding Notes

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#5765]
Capture onboarding/how-to notes that we can reuse and distribute to inform staff how to use the new page types. 

Instead of a doc, I'm thinking we can add a section to https://foundation.mozilla.org/en/docs/how-do-i-wagtail/. 

Some notes for reference are here https://docs.google.com/document/d/1yM5DsKSeIUGktvx_x2G7S7EJe7pHDnEIkXMYtIMxj10/edit

- [x] write content
- [x] review content
- [x] publish content

related issue #5581

**Comment by sabrinang** [comment]
@kristinashu R? I wrote content that is ready for review: https://docs.google.com/document/d/1aENkyXfaX_fGSmESd0SGk6VBzcDh62RA92t8b6uuTnU/edit?usp=sharing

A question I have is will these page types only be available on /insights? so I can include where staff can find and use it.

URL wise, I think this could live `/docs/how-do-i-wagtail/publications`

I can also include more imagery where helpful on the CMS page itself.

**Comment by sabrinang** [comment]
@jamilasnell Can you review this doc:  https://docs.google.com/document/d/1aENkyXfaX_fGSmESd0SGk6VBzcDh62RA92t8b6uuTnU/edit?usp=sharing

**Comment by kristinashu** [comment]
> A question I have is will these page types only be available on /insights? so I can include where staff can find and use it.

It's available to use in most places (not blogs but pretty much all the other urls e.g. /campaigns).

**Comment by jamilasnell** [comment]
Done with my review!

**Comment by sabrinang** [comment]
Content and images are published here: https://foundation.mozilla.org/en/docs/how-do-i-wagtail/publications/
