### ISSUE TITLE
[Publications] Onboarding the Insights Team

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#5766]
continuation of https://github.com/mozilla/foundation.mozilla.org/issues/5581

Get teams familiar with the new page types available for long-form content publishing, publication and article pages. This can be schedule call walkthroughs and sharing https://github.com/mozilla/foundation.mozilla.org/issues/5765 notes when ready.

**Teams**
- [ ] Insights team
- [ ] ~Design team~
- [ ] ~maybe MozFest book team~

**Comment by sabrinang** [comment]
@jamilasnell should we schedule these onboardings for next year as many of us will be out for holidays next week and we still have a few publication PRs being landed so it would be good to wrap those up first too. Any other timings we should consider and any thoughts?

**Comment by jamilasnell** [comment]
Yes, I think that we should move the onboarding meetings to next year. Considering the fact that we will have a month between when we come back in Jan to when PNI Valentines is launching, I would said that later in Jan makes the most sense to schedule the trainings out.

**Comment by kristinashu** [comment]
Gonna move this to next sprint and increase the time estimation.

**Comment by kristinashu** [comment]
I'm going to update this ticket so it's only about onboarding the Insights team. It's important that they can start uploading content to the Publications as soon as possible to allow time for QA and feedback before the actual launch of their publications. We will have limited capacity so QA and feedback will really have to be about critical issues, not nice-to-haves.

@jamilasnell could you please clarify the timeline for the Insights team's work related to this?

**Comment by jamilasnell** [comment]
Eeva and Kasia are meeting this Wednesday (1/13) to discuss the timeline of the onboarding process. I told them that with this late start, they should not expect to use the template immediately since we need time for QA process.

**Comment by kristinashu** [comment]
@jamilasnell thank you for the update! I would very much encourage them to use the templates as soon as possible. They have been QA'ed and there are no blockers to using it. The issue would be if they wanted a new special/unique feature, we wouldn't have time the design, implement, and QA that. But what we have now should be plenty for them to get started!

**Comment by jamilasnell** [comment]
Meeting has been set for Jan 21st!

**Comment by sabrinang** [comment]
I've onboarded Eeva, Laura and Tais to the publications templates and walked them through referencing https://foundation.mozilla.org/en/docs/how-do-i-wagtail/publications/ in our call today. 

@jamilasnell Is there anything else for this ticket or are we good to close?

**Comment by jamilasnell** [comment]
I think we are good to close!
