### ISSUE TITLE
[IA Refresh] Measuring success: part III (a)

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5775]
**Background:**
According to our [Foundation Site Information Architecture](https://docs.google.com/presentation/d/19etCN1uGLcLmB50-uV-srsWKEAhlwlR_bc0dLE1uW1g/edit?usp=sharing) document, those were the 4 areas we want to focus to assess the success of our IA refresh initiative:

1. Reduce the bounce rate on our homepage by 20% through site updates based on user testing, analytics, and staff interviews
2. Qualitative testing finds that users’ understanding of Mozilla Foundation’s mission improves by 25% (conduct baseline/control test along with prototypes in April)
3. Qualitative testing finds that staff can more easily find the content they are looking for compared to initial IA audience report
4. Behaviour in Google Analytics shows users going to a diverse set of pages

In part I (#5706) we took a look at the analytics, in part II (#5711) at the perception of internal stakeholders and in this part III we will collect users insights and compile all the results.

**To do:**

- [ ] Make sure to incorporate team's feedback from part II ( #5711)
- [x] Reach out to Raja for access.
- [x] Refine the script from usertesting.com and interview 12 members of our audience (define them with Anil/Kristina). We did [a script a while](https://docs.google.com/document/d/1xZqOWY9A6kUbQDm4FZmEs0VEYACwwSI9CGSlUyOxlTM/edit?usp=sharing) ago but it should be revised to make sure things are still true.
- [x] Analyze 5 mobile interviews
- [ ] Analyze 5 desktop interviews
- [ ] Find patterns and insights
- [ ] Produce a report of the findings, comparing it against the goals we set

cc: @kristinashu @jamilasnell for triage - if possible, could we aim to have this in the queue in January?

**Comment by jamilasnell** [comment]
Placed this in the Jan 18th Milestone!

**Comment by taisdesouzalessa** [comment]
@nancyt1 would you help me out by going through the videos and adding your observations as notes on Usertesting.com?
I already started the mobile ones but would love if you can go through the Desktop videos and take notes (here is a screenshot):
<img width="315" alt="image" src="https://user-images.githubusercontent.com/22157921/104792525-862e1080-5753-11eb-97e6-d1121c5ed5fe.png">

Happy to quickly hop in a call if you need some guidance on taking notes and how I am categorizing information on usertesting.com. Please ping me if you wanna chat on Monday (Jan 18). Thanks!

**Comment by taisdesouzalessa** [comment]
Mobile interviews are analyzed! Next step: desktop (with help from Nancy).

**Comment by taisdesouzalessa** [comment]
This ticket was 1/2 done in this sprint: interview script were written, interviews were launched and mobile analysis done - added a follow up ticket for next steps:  #6051
