### ISSUE TITLE
[IA Refresh] Measuring success: part IV

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5776]
**Background:**
This work started here: #6157

According to our [Foundation Site Information Architecture](https://docs.google.com/presentation/d/19etCN1uGLcLmB50-uV-srsWKEAhlwlR_bc0dLE1uW1g/edit?usp=sharing) document, those were the 4 areas we want to focus to assess the success of our IA refresh initiative:

1. Reduce the bounce rate on our homepage by 20% through site updates based on user testing, analytics, and staff interviews
2. Qualitative testing finds that users’ understanding of Mozilla Foundation’s mission improves by 25% (conduct baseline/control test along with prototypes in April)
3. Qualitative testing finds that staff can more easily find the content they are looking for compared to initial IA audience report
4. Behaviour in Google Analytics shows users going to a diverse set of pages

**To do:**
- [x] Add more items to the [table Nancy built](https://docs.google.com/document/d/12Lk9ObtT7robD76gPUDGiDW1LeFMtfM5zX6JnIlwfF0/edit?usp=sharing) summarizing the findings of this 3-part research (part I - #5706, partII - #5711 and part III - #5775 ).
- [x] Share the findings to immediate team and open for feedback
- [x] Incorporate team's feedback
- [x] Plan a way to share it across the org: via Slack message (all staff), a brown bag session, others?

**Comment by jamilasnell** [comment]
Placed this in the Jan 18th Milestone!

**Comment by taisdesouzalessa** [comment]
Added more items to this doc, I would say it is 65% done.

**Comment by taisdesouzalessa** [comment]
Nancy and I worked more on the document today and we will open to team feedback early next week. \0/.

**Comment by taisdesouzalessa** [comment]
This is ready for feedback: https://docs.google.com/document/d/12Lk9ObtT7robD76gPUDGiDW1LeFMtfM5zX6JnIlwfF0/edit?usp=sharing

@kristinashu @sabrinang @natalieworth - for context, this is a doc crossing the results of the 3 researches we did (staff, user testing, analytics) + recommendations of next steps. Nancy and I would love to hear your feedback + additional recommendations you can think of (if you can add/use the recommendations in the context of your working groups that would also be great).

**Comment by taisdesouzalessa** [comment]
This is done. Created a follow up ticket here for action items based on this report: #6276
