### ISSUE TITLE
Publication QA

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#5780]
We have Publication QA feedback from Sabrina ready for development work. 

All the feedback lives in these two tickets (in the comments) but I'm creating an epic and a series of tickets to help us keep track of all this. The two originating tickets can be found here:
* https://github.com/mozilla/foundation.mozilla.org/issues/5682#issuecomment-736926553
* https://github.com/mozilla/foundation.mozilla.org/issues/5312#issuecomment-715640663

I'll add additional context to all the tickets individually.

**Comment by mmmavis** [comment]
@KalobTaulien are we good to close this ticket?

**Comment by Pomax** [comment]
all tasks complete.
