### ISSUE TITLE
Footnotes text is too large 

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#5783]
Footnotes: feel a bit too large especially when there are a few (suggested 14px/20px)

How to create: Edit an Article Page (Factory will create these for you) and add footnotes. In production we have ~10 footnotes so it looks huge. Locally (image below) I only show 3, but _imagine_ there are 10. 

Target area:
![image.png](https://images.zenhubusercontent.com/5efb75cdc84745fe99550744/ed75eaa9-1a23-4cad-8a83-d0a6fbe673ab)

Criteria:
- [x] Font size 14px
- [x] Line height 20px

**Comment by mmmavis** [comment]
@sabrinang I see that on Sketch, footnote text is set to 16px/24px on mobile and 18px/27px on desktop. Just wanna double check with you that we wanna change footnote font size to 14px with 20px line-height for all screen sizes.

**Comment by sabrinang** [comment]
@mmmavis yeah 14px/20px is good for both mobile and desktop, I updated the sketch file now too
