### ISSUE TITLE
Align summary dropdown

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#5791]
Summary box drop down alignment (text align to the summary title and box width to column edges, margins are good)

Example: (Alignment should follow the pink area and be 4 columns wide)
![image.png](https://images.zenhubusercontent.com/5efb75cdc84745fe99550744/92c7fbe5-a17d-4e03-9087-23a7ecc21eeb)

Criteria:
- [ ] Summary box should be 4 columns wide
- [ ] Summary box should align with the rest of the page and the design (demonstrated in the image above)

**Comment by mmmavis** [comment]
Kalob's PR #5888 covers the fix for this ticket. Will close this one when that PR is merged.

**Comment by KalobTaulien** [comment]
Closing in favour of #5947
