### ISSUE TITLE
Summary bar location work

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#5792]
See the design [here](https://app.abstract.com/share/c5b5156f-9bb9-4147-a45d-0bf020c0c76b?collectionLayerId=de3fda23-a5b4-4e37-8906-554314afbd80&mode=design&sha=25903d8a620778784fb326db1e70a7951f5d4091)

Criteria:
- [ ] Summary bar needs to be visible on mobile 
- [ ] The "left" part of the summary bar can stay hidden, we just need the dropdown. 
- [ ] Make summary bar hidden until user scroll past summary box? (see example below) ![image.gif](https://user-images.githubusercontent.com/2492510/97209768-f68f4c00-1779-11eb-884a-e9af1fa486cf.gif)

**Comment by jamilasnell** [comment]
@Pomax will approve this as he has the **power**
