### ISSUE TITLE
[Mozfest] Become a Sponsor footer link: next steps

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5797]
Now that the "Become a Sponsor" link is implemented on the [live MozFest site](https://www.mozillafestival.org/en/) (ticket: https://github.com/mozilla/foundation.mozilla.org/issues/5503) we should:

- [x] Delete "Become a Sponsor" from the top nav
- [ ] UX Recommendation: to add a "Become a Sponsor" copy blurb on "Get Involved" page (at the end of it) because this seems a spot where people would look at if they want to sponsor the event.

@marcwalsh please let me know if you need any design help :). Assigning this ticket to you and you recommended via email.

cc: @jamilasnell 

Thanks!

**Comment by jamilasnell** [comment]
@marcwalsh is this still relevant? Please let us know the priority of this task.

**Comment by kristinashu** [comment]
I'm going to close this ticket. "Become a Sponsor" has been deleted from the top nav. It's up to @marcwalsh if he wants to add it to the Get Involved page or not.

**Comment by marcwalsh** [comment]
Thanks both - sorry I missed this before. We decided not to include it in the Get Involved as we're likely including more on that page as we get closer to the festival.
