### ISSUE TITLE
[Publications] Plan out work for ToC / Publication child pages UX

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#5800]
Placeholder issue to think through how we can better connect publication/article child pages so they are less disconnected from the rest of the content and improving the reading flow experience. Brainstorm UX/UI solutions. 

Note from @baricks: It would be nice to have some kind of navigation at the top of the page so that people can easily jump between the different parts of the paper. (For instance, policymakers may only want to read 2 challenges and 1 outcome that is relevant to them)

/cc @jamilasnell

**Comment by sabrinang** [comment]
Feedback via slack Sarah W. :

> Is it possible to have the sections list in the top summary box in one column rather than 2 (see attached photo).
> When you navigate via the arrows and arrive at pathways forward it looks like you're back on the main nav page. Not sure if there's a way to make it clearer that you have to click the arrow again to reach the content?

**Comment by jamilasnell** [comment]
We are waiting for content from the Insights team to be entered into the template

**Comment by Pomax** [comment]
@sabrinang assigning this to you mostly as a "you are probably the most familiar with this issue and known who should be working on this", feel free to reassign.

**Comment by sabrinang** [comment]
Refer to Nancy's QA notes when reviewing UX: https://docs.google.com/document/d/136l3IIV2HTdG3cJMxtAZLgRRA4lEdrpoe5mUbdIhT_Q/edit#
- some ux around publishing modes

**Comment by sabrinang** [comment]
Note: Deafult pages with publication page as children do not show up in the left side menu. For example, creating a demo publication page in wagtail how-to doesn't appear in the side menu.
<img width="963" alt="image" src="https://user-images.githubusercontent.com/2492510/108265117-39a46f00-711d-11eb-9779-12ef6b354361.png">

I assume it is because it is a publication page type and it doesn't have this navigation system on that page itself. Capturing if a default page has a publication child should that show up in the nav or not as it feels like a disconnected experience since all the other default child pages has the side nav still present but publications do not. This can be noted on the how-to page as well #774.

**Comment by kristinashu** [comment]
@sabrinang is there a way to break up this work into smaller tickets? 16 story points is probably too big for one ticket.

**Comment by kristinashu** [comment]
Moving this to Mar 15 milestone. The work for that milestone will be to break this up into smaller tickets. Reducing the estimate for it because it doesn't actually include the work anymore.

**Comment by sabrinang** [comment]
**Note:** I got some metrics from Tais when we worked on staff call presentaton so capturing it in this ticket for future reference as it relates to UX and flow of publications as well:

- /en/insights/ai-whitepaper" had around 44.5% pageviews coming from mobile (which is a big number and raises the need for a better mobile experience than PDF can provide)
![image](https://user-images.githubusercontent.com/2492510/109733538-20b3a900-7b74-11eb-9ca9-e97405eb0c9b.png)
- amount of button clicks to "download PDF" (you see it is way lower than the number of sessions, meaning not everybody who lands on that page wants to download the PDF, the majority of people consume the information right on the site because the barrier is lower)
![image](https://user-images.githubusercontent.com/2492510/109733674-6c665280-7b74-11eb-8fae-bbbc00cf8542.png)
- many people don't past the first page (this is more for us to look at internally and see how to solve in the future if desirable)
![image](https://user-images.githubusercontent.com/2492510/109733930-f7474d00-7b74-11eb-9678-37a7b31b1d12.png)

**Comment by sabrinang** [comment]
We've revised a few publication features since this issue has been filed, we've are revising summary link ordering https://github.com/mozilla/foundation.mozilla.org/issues/6327#issuecomment-799758807 and we've revised previous/next button linking https://github.com/mozilla/foundation.mozilla.org/issues/5784 that addresses https://github.com/mozilla/foundation.mozilla.org/issues/5800#issuecomment-744577728 and revised table of content thumbnail images/removed numbering.

For issue related to flow https://github.com/mozilla/foundation.mozilla.org/issues/5800#issue-759797367 and https://github.com/mozilla/foundation.mozilla.org/issues/5800#issuecomment-789327634, so I've filed #6411 to look into improvements in the future.

For h2 issue, we've filed https://github.com/mozilla/foundation.mozilla.org/issues/6326 to resolve making it more obvious that bold/italics will break the anchor as it is by design. Along the same lines, we will have h2 only be anchors by design (use other headings for non-anchored links) and if more use cases come up we don't want them anchored we can look into it and resolve.

Other feedback mentioned involves some wagtail publishing quirks, like sorting which is mentioned in https://foundation.mozilla.org/en/docs/how-do-i-wagtail/publications/ and others that are not publication specific _(like you can publish and set to private to see all the sections instead of draft)_.
