### ISSUE TITLE
[Publications] Remove ToC Numbering

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#5822]
@baricks is inputting content for the whitepaper and it has a very specific numbering structure that is integral to the content itself. Our table of content numbers are auto generated and can not be edited so it is clashing and misaligned with the paper's content.

Are we able to remove the table of content numbers since they are not editable? 

<img width="573" alt="image" src="https://user-images.githubusercontent.com/2492510/101699149-8427b200-3a2f-11eb-981e-7b1b9fc49e7c.png"> 

Are we able to upload imagery in the boxes?
<img width="583" alt="image" src="https://user-images.githubusercontent.com/2492510/101699263-b46f5080-3a2f-11eb-83e1-820566257bd4.png">

/cc @jamilasnell

**Comment by mmmavis** [comment]
> Are we able to remove the table of content numbers since they are not editable?
Yes, we can remove them.
I'm thinking mabye we can add a new toggle box in the CMS for editors to decide whether or not they want ToC numbering to autoshow. I'll file a ticket as this requires further discussion.

> Are we able to upload imagery in the boxes?
This will require backend changes so I'll file a follow-up ticket for this work. (The team is busy getting other backend heavy work for PNI to land so it's better that we don't introdue more backend changes for now)

**Comment by mmmavis** [comment]
Note: ToC appears not just on Publication Page but also on "chapter page" (publication page as child of another publication page)
