### ISSUE TITLE
[Publications] Long URLs extend beyond container

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#5825]
When there is a long URL present it is breaking outside of the column content body:

![image](https://user-images.githubusercontent.com/2492510/101700199-7e32d080-3a31-11eb-8a7b-e3d1d377fa9f.png)

https://foundation.mozilla.org/en/insights/trustworthy-ai-whitepaper/path-forward/building-new-tech-and-products/#footnote-5

![image](https://user-images.githubusercontent.com/2492510/101700456-e84b7580-3a31-11eb-8fd3-c5dfccb09c68.png)
https://foundation.mozilla.org/en/insights/trustworthy-ai-whitepaper/references/

/cc @baricks @jamilasnell

**Comment by mmmavis** [comment]
The footnote list should probably be implemented using `<ol>` instead of a list of `<div>`. Will have to rewrite the DOM + tweak styling a bit.
