### ISSUE TITLE
PNI footer has a misaligned icon in the footer

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5830]
It looks like the footer on PNI pages has a misaligned icon
![image](https://user-images.githubusercontent.com/177243/101807307-d4ebe900-3ac9-11eb-975a-6d30fa047cda.png)

**Comment by mmmavis** [comment]
This will be fixed once PR https://github.com/mozilla/foundation.mozilla.org/pull/5855 is pushed live.
