### ISSUE TITLE
MozFest signup petition campaign id does not make it into salesforce

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5839]
We updated the Mozfest signup petitions to take a Salesforce campaign id, https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/pagemodels/campaigns.py#L55-L70, with this id added to the basket payload when signups are processed, https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/campaign/views.py#L104-L120

however, @marcwalsh and @stephaniemcv are reporting that this campaign id is not making it into salesforce.

We should investigate whether:
1. the payload that basket gets includes this campaign_id, and if so,
2. what happens to it.

it's possible we're using the wrong field name so salesforce just ignores it, but it's using the same fieldname that we use for petitions, https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/campaign/views.py#L146-L154, which do get tied to salesforce correctly as far as I understand it (@stephaniemcv please correct me if I'm wrong on that)

**Comment by pmac** [comment]
I believe I see the issue. I see on [this line](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/campaign/views.py#L129) that the event type is `newsletter_signup_data`. The only event type that is setup on the basket side to record a `campaign_id` is `crm_petition_data`. This is also because there is no field on the contact record for a campaign ID, this is only on the `CampaignMember` object type in SalesForce.

**Comment by Pomax** [comment]
@pmac would it be possible to add this new event type and have it forward data to salesforce?

**Comment by pmac** [comment]
You say above that it should be coming in as a petition. If it was then I think this would work fine. It's currently just coming in as a newsletter subscription.

**Comment by Pomax** [comment]
hm, good point. @stephaniemcv @marcwalsh can you confirm which of the two this was supposed to be? As I recall this was indeed a newsletter signup, not a petition?

**Comment by Pomax** [comment]
After talking about this with staff it sounds like we're not doing landing-page segmentation for mozfest this year, so we can look at this again next year (but then a lot earlier) if we still need this then.
