### ISSUE TITLE
PNI: product page spacing

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5842]
I don't know when this happened but at some point a bunch of extra space was added below each criteria. It was good at launch but something changes at some point. @Pomax @mmmavis @KalobTaulien any idea when/how/why this happened? Can you please revert it back to how it was? cc @sabrinang 

Screen cap from prod https://foundation.mozilla.org/en/privacynotincluded/products/jabra-elite-85t/

<img width="884" alt="image" src="https://user-images.githubusercontent.com/1068783/101829066-471ef680-3ae7-11eb-9d34-e861c44468a3.png">

Comps https://share.goabstract.com/20c32e9d-5585-4bb2-b575-8d38ed754b81?mode=design&sha=de92d4a0b2cb2b1635ab097de5615415ee7e5b33

<img width="826" alt="image" src="https://user-images.githubusercontent.com/1068783/101829044-40907f00-3ae7-11eb-8dc8-624943c3cf32.png">

**Comment by sabrinang** [comment]
The [About the Guide](https://foundation.mozilla.org/en/privacynotincluded/about/why) pages are also looking spaced out after paragraphs:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/2492510/101842542-1f3a8d80-3afd-11eb-8219-2b4e1ad34290.png">

Comp: https://share.goabstract.com/38480f87-d9fb-4274-9e98-8848e9e1963a?mode=design&sha=fd854dc7dd2965d9ccb794b92e8c31a058d99b2c
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2492510/101842653-5f9a0b80-3afd-11eb-81ec-817a6bc6e9e0.png">

**Comment by kristinashu** [comment]
The plot thickens!

**Comment by mmmavis** [comment]
I think I found what's causing the issue. Looks like it's the CSS we added for the Content Rules page is also applied on other pages. I'll file a fix. Weird that Percy didn't catch this though. 🤔
