### ISSUE TITLE
Consider allowing editors to upload chapter image shown on Publication's ToC

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5847]
### Describe the feature request
Consider allowing editors to upload custom chapter image shown on Publication's ToC

### Additional context
#5822

/cc @sabrinang

**Comment by mmmavis** [comment]
@kristinashu @sabrinang I initially marked this ticket as "needs discussion" as this was a request from the Whitepaper stakeholders. Do you know who else we should loop in for discussion to make a decision?

**Comment by sabrinang** [comment]
I'm not to sure who but it'd be great if we can get this feature in this template. 

When we reviewed with TAI stakeholders they expressed their desire of wanting images previously and today Becca reached out saying a few people were asking when the coloured boxes will get replaced with designed assets so I think that is the expectation. 

@kristinashu is it possible to proceed with this ticket or do we need more feedback first?

**Comment by kristinashu** [comment]
Sounds like it would be a valuable feature and I don't see down-sided to add it, do you? Mavis, if you have the bandwidth to do it then I don't see why not!

**Comment by mmmavis** [comment]
No concern other than in the cases the background to foreground(text) contrast might not be a11y friendly. Should we add a filter to darken the background?

**Comment by sabrinang** [comment]
I think when images are present the numbers are still removed so I'd keep it simple and accessible to have image only.
No need for numbering right now as we have removed them based on it interfering with content that has an independent numbering system. 

We can think about it more in the #5800, it perhaps is an either number or image but not both situation but let's not let that block this issue.

**Comment by mmmavis** [comment]
Ah right. Totally forgot that we had the numbers removed lol 😂
