### ISSUE TITLE
Finesse ReactGA vs. Google Tag Manager

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5849]
With GTM added to the event code, we should have a look at seeing whether or not we want to keep GA events or do everything in GTM

**Comment by mmmavis** [comment]
Before we start doing the actual cleanup work, we should document how in GTM we target DOM elements to trigger events. We need to find a way to prevent things from "out of sync". For example, if in GTM we target DOM element by their id/class selector, once the selector name gets changed in code, the GTM event trigger will stop working **without** giving any notice or throw errors.

**Comment by Pomax** [comment]
yeah that's a very good point. @benhohner I don't supposed you already looked into whether there was any reporting around that kind of desync?

**Comment by benhohner** [comment]
@Pomax @mmmavis that's a good question. I don't think there's a well defined process for that.
I can only think of 2 solutions off the top of my head:
1) We probably don't change class names that often? before we do, check GTM to see if there's an associated class
2) Train the designers how to submit PRs in GitHub to add classes to elements they want to target using a special "gtm-*" class that we know not to touch.

**Comment by Pomax** [comment]
@benhohner do we still want to do this?

**Comment by Pomax** [comment]
closing this as "we have no one to do this work, nor an outstanding request for it at the moment".
