### ISSUE TITLE
PNI follow-up: clean up the tests

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5882]
several tests were marked as `@skip` as part of https://github.com/mozilla/foundation.mozilla.org/pull/5883, with some tests rewritten just enough for the wagtail version to pass - we should revisit these tests.

**Comment by KalobTaulien** [comment]
Update: This one is VERY tricky and requires a lot of time to explore and debug.

**Comment by Pomax** [comment]
closing as no longer required. The tests as they are in place now should be fine.
