### ISSUE TITLE
PNI follow-up: make categories aware of new products

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5886]
category functionality got rewritten, but the new code and templates still tap into some of the old logic. Specifically, [published_product_count()](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/buyersguide/pagemodels/product_category.py#L51-L53) checks for how many _original_ products are classified into this category, which determines whether or not a category shows up in the nav bar.

In order to clean this part up, we _probably_ want to switch to a new category class instead, house in `wagtailpages`, so we can start moving away from needing code from the `buyersguide` app.

We can have a look at https://stackoverflow.com/a/26472482 and see if that works with wagtail mixed in

**Comment by KalobTaulien** [comment]
Splitting this ticket into 2. 

Step 1. `published_product_count()` needs to count products by its ProductPage, not Product model (which is added in #6011) 
Step 2. Move `BuyersGuideProductCategory` model into the `wagtailpages` app. This requires a fair amount of work, and there's some trickiness around migrations involved in moving a model like that. New issue #6012 opened for this.
