### ISSUE TITLE
PNI follow-up: remove the buyersguide app

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5887]
- [ ] make sure all app files have already been disabled/deleted
- [ ] create a management command to
  - [ ] deal with the table rename for the product category
  - [ ] remove the buyersguide tables from the db using pure SQL
- [ ] update wagtail:
  - [ ] remove the buyersguide nav section

**Comment by Pomax** [comment]
marking as blocked until we have all the things we still rely on in the old app, moved over to the `wagtailpages` app

**Comment by KalobTaulien** [comment]
Dev note: Let's also ensure we remove the old templates that aren't being used. 2x check the views manually since there are duplicate templates that are now namespaced - we want to make sure we remove the _correct_ templates.
