### ISSUE TITLE
Wagtail: Improve Image Quality

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#5898]
Images have good resolution but when uploaded they are a bit blurry. See example below: [theory of change graphic](https://foundation.mozilla.org/en/insights/trustworthy-ai-whitepaper/path-forward/introduction-theory-change/)
<img width="787" alt="image" src="https://user-images.githubusercontent.com/2492510/102282595-af097e80-3ee5-11eb-9144-afe9539596e6.png">

Kalob mentioned in slack:
> We could improve this too by using a `<picture>` with multiple image sources, and providing a 2x image for retina screens.
> We should also add these settings to the site:
`WAGTAILIMAGES_JPEG_QUALITY = 100`
`WAGTAILIMAGES_WEBP_QUALITY = 100`

**Comment by KalobTaulien** [comment]
Ahh so this is in the `content` RichText stream block. I thought (for some reason) this was it's own stream block. 

So here we have very little control. It's set a width of 800 by default in the richtext area. All we can do, as far as I know, is set the JPEG and WEBP image qualities — which I'll open a PR for.
