### ISSUE TITLE
Get rid off all off-brand colours

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5906]
Related ticket: https://github.com/mozilla/foundation.mozilla.org/issues/6285#issuecomment-797052376

There are more and more one-off custom colours being used in the codebase. We should really stop adding those as they are violating our brand guide and making the codebase harder to maintain.

Let's clean them up by either replacing them with existing brand colours or turning them into official brand colours.

From a quick search in the codebase, there seem to be at least 6 one-off colours now, 5 in [article-page.scss](https://github.com/mozilla/foundation.mozilla.org/blob/e62d219a68e89ea5252439a32d4d2cb0866b8f51/source/sass/components/article-page.scss) and 1 in [publication-page.scss](https://github.com/mozilla/foundation.mozilla.org/blob/190935dc63194473ea3f96343bc1d678d8a33d1b/source/sass/components/publication-page.scss)  (search for `stylelint-disable`). Plus a new one is being added in #6285.

- [x] Step 1: engineers to list out all custom colours used in the codebase
- [x] Step 2: designers to suggest how we wanna update the colours
- [x] Step 3: engineers update code and add new brand colours (if any) to style guide page
- [x] Step 4: designers update Sketch file to reflect these colour changes

**Comment by Pomax** [comment]
@mmmavis who would be a good person on the design side to flag as assignee?

**Comment by mmmavis** [comment]
I think @sabrinang 

@sabrinang - we discovered this unmilestoned ticket during triage yesterday so we decided to put it in this milestone as a stretch goal so it doesn't get forgotten.

**Comment by kristinashu** [comment]
@sabrinang could you please estimate on how much work you think this is?

**Comment by mmmavis** [comment]
Self-assigned since I will most likely be the person working on this 😄

**Comment by mmmavis** [comment]
@sabrinang I've done the [audit](https://docs.google.com/document/d/117_bZOGq47TqVR7-FxHutcMuePl521jVRyAtwUY8FPs/edit#) and tagged you for issues that need design feedback.

**Comment by sabrinang** [comment]
Thanks for compiling all in the audit doc Mavis! I added my solutions and wanted to name and include lightest blue tint #e7e7fc in the brand colours. I'm thinking $lightest-blue but I know it isn't a very scalable convention the way it is going but thought to use it for time being — any thoughts or suggestions on this?

**Comment by mmmavis** [comment]
I think it's fine to just give it a name now so we can add it to the style guide. This will make our future design system cleanup work easier too (i.e., we only need to revise existing style guide colours vs going through the codebase and find all custom colours again)

**Comment by mmmavis** [comment]
Hi @sabrinang I've merged my PR. Once you have the Sketch file and other documentation updated, could you please tick off the last checkbox in this ticket and close this ticket? 😃

**Comment by sabrinang** [comment]
I added lightest-blue as a symbol in the sketch style guide library file and style guide page. Merged in Abstract.
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/2492510/112073068-802c2580-8b30-11eb-9965-4564381c1640.png">

Thanks @mmmavis — good to close!

**Comment by mmmavis** [comment]
Thank you @sabrinang 🎉
