### ISSUE TITLE
[Publications] Add event to Trustworthy AI download button

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5908]
With the launch of Creating Trustworthy AI Whitepaper we need to track how many clicks we get on the "Download Full PDF" button

<img width="366" alt="image" src="https://user-images.githubusercontent.com/22157921/102383961-fdb82680-3f80-11eb-990b-d038a3b541c0.png">

https://foundation.mozilla.org/en/insights/trustworthy-ai-whitepaper/

If possible, we should add this tracker sooner than later to capture the energy from launch.
Assigning @benhohner for triage

**Comment by taisdesouzalessa** [comment]
@benhohner I think I am not assigned as a reviewer because there is no "review requests" on my queue :).

Anyways, I took a look at it and it seems it is already implemented [in the live site](https://foundation.mozilla.org/en/insights/trustworthy-ai-whitepaper/), correct? Tested using the Inspector and it seems to be working \0/. 

Thanks!

<img width="701" alt="image" src="https://user-images.githubusercontent.com/22157921/104390418-7d8acf80-54f2-11eb-948b-f01be639de74.png">

**Comment by benhohner** [comment]
@taisdesouzalessa Because there was no pull request, I'm not sure I can create a "review request".

Yes, it's live on the site. Thanks for verifying! I'll show you the GTM debugger when we connect next :)

**Comment by taisdesouzalessa** [comment]
Mavis taught me how to use the GA debugger (this is what I have been using since then), curious to learn about the GTM one too. Thanks, Ben!

<img width="147" alt="image" src="https://user-images.githubusercontent.com/22157921/104489845-f5a1d580-5584-11eb-87e4-afd9b9bc08c7.png">
