### ISSUE TITLE
[Insights Hub] Nesting Insights projects inside Insights Hub

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5931]
@jamilasnell This is an issue that needs discussion between a designer (me) and one engineer. Tagging you for triage.

**Issue:**
We want to move the following projects: "[Privacy Included](https://foundation.mozilla.org/privacy-included/)" and "[Data Futures](https://foundation.mozilla.org/en/initiatives/data-futures/)" inside the newly created "[Insights](https://foundation.mozilla.org/en/insights/)" Hub - as per our [URL structure plan](https://docs.google.com/spreadsheets/d/184z7LnHIghXDp2NIns4T8zlpBDAdaRFuPMUDX7ijHYY/edit?usp=sharing)

The challenge we're having is that if we add a "Banner" type of page inside the major "Insights" (also a Banner type page) we end up with a behavior that is not the desired one. See below for reference:

**Page uses the top messaging + nav menu from Insights**

<img width="473" alt="image" src="https://user-images.githubusercontent.com/22157921/102558632-b74af080-4082-11eb-8b86-fbe4d46554ef.png">
---------------------------------------------------

**Desired behavior:** page is nested in URL (https://foundation.mozilla.org/insights/data-futures/) and in the CMS but keeps the same structure as it currently has:

<img width="581" alt="image" src="https://user-images.githubusercontent.com/22157921/102558756-02fd9a00-4083-11eb-8af0-c9eaed9a1be8.png">

Our "Initiatives" hub is a good example on how we would like it to work - the big hub allows other pages to have their own layout. Looking at the CMS, I see the type of page this hub is "Initiatives page" type

<img width="975" alt="image" src="https://user-images.githubusercontent.com/22157921/102558993-a64eaf00-4083-11eb-9426-777abfe3cfc1.png">

**To do:**
- [ ] Designer and Engineer to have a conversation on how to tackle this issue.
- [ ] Once we find a solution, implement it.
- [ ] Then we do the redirects [highlighted here](https://docs.google.com/spreadsheets/d/1cZL5ExYE0754budmYcTPyd2t5_RjZzHSnJuP0Shu9jM/edit?usp=sharing) (from row 12 on)

**Comment by jamilasnell** [comment]
@kristinashu you had planned to meet with these stakeholders right to discuss the URL mapping and why this may be a heavy/complicated lift?

**Comment by kristinashu** [comment]
No, I wasn't planning on it. The request comes more from us giving this recommendation than the stakeholders requesting it. The plan Tais has outlined in this ticket sounds good to me. I think devs will be able to update the template to allow for this.

**Comment by taisdesouzalessa** [comment]
I'll tag @benhohner to assign an Engineer to connect with me then so we can update the template (hopefully). Thanks all!

**Comment by kristinashu** [comment]
cc @Pomax who knows a lot about our templates :)

**Comment by benhohner** [comment]
> 
> I'll tag @benhohner to assign an Engineer to connect with me then so we can update the template (hopefully).
> Ben, could you assign an engineer to this ticket, please?
> 
> Thanks all!

@taisdesouzalessa I finally figured out GitHub notifications, should actually get these now! Sorry for the delay. Hopefully Pomax can help with this as Kristina tagged.

**Comment by Pomax** [comment]
self-assigned for the collab part =)

**Comment by taisdesouzalessa** [comment]
@Pomax is it possible to do the request I wrote in the ticket? I have some incoming projects from Data Futures and will need to sort out the URL structure in order to decide where they fit. Please let me know if the ticket is clear enough :). Thanks!

**Comment by Pomax** [comment]
As an engineering description, the request is to have banner pages that act as their own "mini site" (e.g. with a nav that has an overview + links for child pages) as children of the `insights` page, which is itself already a banner page with an overview page + child page nav.

In order to make this work, banner pages would need to become aware of whether or not they are a "root" page, with changes to the code that builds the banner page nav, so that for those pages it does not go all the way up to the highest possible banner page. 

If this is what we want to do, then I'd estimate that at probably be 1~2 days of work (engineering + testing).

**Comment by kristinashu** [comment]
Thank you Pomax! @taisdesouzalessa - you and I can chat about this tomorrow and open an implementation ticket if we want to move forward with this but based on our chat today I think we can _design around this_.

**Comment by taisdesouzalessa** [comment]
Alternatives if there is no Engineering resources to allocate to this project:
1. Rebuild: https://foundation.mozilla.org/en/privacy-included/ as a Default Page (inside /insights like the [RCSC example](https://foundation.mozilla.org/en/what-we-fund/awards/responsible-computer-science-challenge/)) or leave it as is (traffic to this page is very low) - 189 unique pageviews in the last 6 months.
2. We're already potentially planning moving [Data Futures](https://foundation.mozilla.org/en/initiatives/data-futures/) into the Publications template: this would mitigate this issue for now. If the whole page isn't moved to the Publications template (if only the PDFs become publications), we can rebuild that page as Default page (like [RCSC](https://foundation.mozilla.org/en/what-we-fund/awards/responsible-computer-science-challenge/))

@kristinashu let's connect tomorrow! Above there are the options for design work without need of Engineer time.

**Comment by taisdesouzalessa** [comment]
Talked to designers and we decided to:
1. Rebuild: https://foundation.mozilla.org/en/privacy-included/ as a Default Page Ticket here: #6108
2. Data Futures won't live under "Insights" anymore (it has its own hub) so we won't have this issue.

That eliminates the need for Engineer work at this time. < @Pomax fyi and thanks for brainstorming solutions with me!
