### ISSUE TITLE
[Insights hub] Email preferences page update

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5932]
**Background:**

This ticket is:
- [x] to get the progress status for the email preferences page update [as per this doc](https://docs.google.com/document/d/1cjvoU2fVqLnY7lGHNsBtrIBRTuiRZp8S3sXT6W2BPZg/edit?usp=sharing)
- [x] once it is updated, notify the Insights team 

cc: @jamilasnell this is more a reminder for us so this project doesn't get forgotten

**Comment by taisdesouzalessa** [comment]
**Update:** pinged Steph McV on Slack about it.

**Comment by taisdesouzalessa** [comment]
This is now updated! Wohoo! Here is a screenshot!
<img width="844" alt="image" src="https://user-images.githubusercontent.com/22157921/105733004-e6f0e200-5ee5-11eb-8aa9-ae3c5b51fc86.png">

@kristinashu I added a note on [this doc](https://docs.google.com/document/d/1cjvoU2fVqLnY7lGHNsBtrIBRTuiRZp8S3sXT6W2BPZg/edit?usp=sharing) tagging Kasia and Eeva to notify them this is now updated.

**Comment by kristinashu** [comment]
Amazing! Thank you Taís!
