### ISSUE TITLE
PNI: expand "what could go wrong" field in CMS

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5944]
CMS usability feedback from Jen:

- [x] Expand what could go wrong text box in the CMS so it’s like the blurb one and not all on one line (it’s hard to review when it’s all on one line)

Screen cap from prod:
<img width="710" alt="image" src="https://user-images.githubusercontent.com/1068783/102801617-4d746480-436a-11eb-9d03-3fc62e904410.png">

**Comment by mmmavis** [comment]
@KalobTaulien `blurb` is a text field. Is there a Wagtail config that we can get the field to show as textarea?
