### ISSUE TITLE
PNI: Add a text field for user-friendly privacy section

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5945]
Feedback from Jen:

- [x] Add an optional text field for user-friendly privacy section
- [x] Style it the same as the already existing fields

**Comment by mmmavis** [comment]
@kristinashu do you know what text field (name, type, possible values) we want to add and how we want it to appear on the page?

**Comment by kristinashu** [comment]
Same as the other help text fields. E.g. the "In April 2020..." text
<img width="889" alt="image" src="https://user-images.githubusercontent.com/1068783/104665377-fc644180-5685-11eb-93a0-26b5cbf47f13.png">


But @Pomax just opened this ticket which I think is a duplicate https://github.com/mozilla/foundation.mozilla.org/issues/6023 so could probably close this one.

**Comment by Pomax** [comment]
closing 6023 as the duplicate as this issue has acceptance criteria already. Text from that issue:
---
From @caltrider: "Add a text field for user-friendly privacy section (or move the help text section from the privacy line in the MSS up to be the help text for user-friendly privacy). Best case would be to move the text box that already exists (and the data in there already) from the existing MSS privacy policy text box and make that the text box for the User Friendly Privacy part."
