### ISSUE TITLE
[PNI] Change “Unknown” to “Can’t determine” for quad-state-fields

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5946]
Update the four-possible-values field from the current "Yes"/"No"/"Not Applicable"/"Unknown" to "Yes"/"No"/"Not Applicable"/"Can't Determine", to better 

- [x] Change the field definition from “Unknown” to “Can’t determine” 
- [x] Update the template tag for this field to use the new phrasing

Screen cap from prod:

<img width="564" alt="image" src="https://user-images.githubusercontent.com/1068783/102809833-8961f680-4377-11eb-896e-991166b4bbed.png">

**Comment by kristinashu** [comment]
This is more complicated than it appears... via @Pomax in slack

> It's tricky since it relies on the universal yes/no/unknown/na field. The fields don't get generated "one by one", they all use the same code to turn their CMS value into a readable string. So we could create special code just for those AI fields, but that does risk the code getting harder to maintain the more fields we decide need different things shown while being the same field type in the CMS.

> So I don't want to say we can't do it, just double check that we really want to do this because it'll require some careful coding to make sure we do that in a way that won't create hard to maintain fragmentation.

@caltrider how important is it that AI says “Can’t determine” instead of “Unknown”? Is it actually unique to AI or could all the  "Unknown" criteria become "Can't determine"?

**Comment by Pomax** [comment]
@kristinashu after talking to Jen, she would prefer if we simply change this field from "unknown" to "can't determine" across the board, which makes things quite a bit easier to implement and maintain - I've update the issue title and initial comment to reflect that but please let me know if you have any concerns!

**Comment by mmmavis** [comment]
Reminder: let Kalob know before merging the PR as it will affect the Airtable work.
