### ISSUE TITLE
Make the PNI homepage banner a CMS field

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5955]
The PNI homepage used to have to point to a static image asset because it was a plain Django app instead of being CMS managed, but now that it's a real Wagtail page, we should add a field for that banner so that staff can update it through the admin interface, rather than through github pull requests.

**Comment by kristinashu** [comment]
Screen cap from prod
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/1068783/103035707-bbf92400-451c-11eb-8009-25ce5c6c0059.png">

- [ ] Make the background image CMS editable (note: the Webby Awards badge should stay as hardcoded) 
- [ ] Make the heading text CMS editable 
- [ ] Make the intro text CMS editable
- [ ] Make sure it works with localization
- [ ] Make sure all styling stays the same

cc @TheoChevalier
