### ISSUE TITLE
PNI: evergreen graphics

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5969]
After Valentines day edition, we should update the homepage hero graphic as well as the share images.

**Comment by Pomax** [comment]
Now that the new PNI is wagtail-based, we should update the PNI homepage model to allow specifying the banner through the CMS, so that we can point to the new graphic using the CMS rather than having to upload it to github.

**Comment by kristinashu** [comment]
Yes! Here's a link to your ticket about implementing that https://github.com/mozilla/foundation.mozilla.org/issues/5955

**Comment by kristinashu** [comment]
Duplicated https://github.com/mozilla/foundation.mozilla.org/issues/6201
