### ISSUE TITLE
Add language negociation to English pages

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#5981]
Related to #5646, in a joint effort to make translated content easier to access, but this ticket is focusing on access from external sources (social media, press websites, partner websites, MoCo web properties…), rather than links stored in the DB.

CC @benhohner as we started chatting about this

# Observed situation
Even if staff are doing a great job promoting language-agnostic links to social media & press, we can’t prevent external sources from promoting links including `/en` to non-EN audiences, preventing language negotiation from happening and forcing English onto everyone accessing the link. 

# Proposed change
When someone explicitly access any URL containing `/en`, we should stop assuming they actually meant to get content in English. Instead of straight-up serving English, we should proceed with additional checks at this point. Here’s a pseudo-code algorithm of what I have in mind. This should be more or less what’s already happening when accessing a locale-agnostic URLs (e.g. https://foundation.mozilla.org/privacynotincluded)

```
if django_language cookie is set then
  if django_language equals 'en' then
    # Keep serving English
  else
    # Redirect to that locale
  end if
else
  if browser language preference is set and we support that language then
    # Redirect to that locale
  else
   # Keep serving English
  end if
end if
```

# Additional notes

- I don’t think we need to run similar code when accessing links with other locales hardcoded.

**Comment by Pomax** [comment]
URL resolution is handled by django/wagtail/wagtail-modeltranslation, so the "locale agnostic" behaviour you're seeing is something that's taken care of outside of our control. This might have to be something that slots into the modeltranslation - in the mean time we could try to effect this logic in the https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailcustomization/redirects/middleware.py file that we already have in place.

**Comment by benhohner** [comment]
Cc: @KalobTaulien thoughts on where it could fit within the wagtail ecosystem? Maybe connect with @Pomax and/or @TheoChevalier  to discuss?

**Comment by jamilasnell** [comment]
@TheoChevalier closing this ticket as the localization work that we are doing now makes this redundant

**Comment by TheoChevalier** [comment]
> @TheoChevalier closing this ticket as the localization work that we are doing now makes this redundant

@jamilasnell Hmm, AFAICT, this won’t be fixed with the work we’re doing around wagtail-localize, but maybe I did miss a discussion somewhere?

**Comment by TheoChevalier** [comment]
To @Pomax’s question whether this could be contributed upstream, unless it can be a behavior that is off by default, I don’t think this should be wagtail-localize’s default language negotiation algorithm

**Comment by Pomax** [comment]
In terms of resolution, I think the path forward here is staff education + doing the database mining to find all explicit `/en/` urls and turning them into unlocalized urls, but we shouldn't try to override how URL routing is supposed to work: if someone explicitly asks for an `/en/` URL, that's what they should get (URL responses should stay predictable).

**Comment by benhohner** [comment]
I think next steps for this would be figuring out the best way(s) to educate staff, doing the education, and seeing if the education is successful and how much it reduces localized URL usage. If the problem persists, we can create an Airtable ticket for getting the design team involved to do some user research and brainstorm possible technical solutions.
