### ISSUE TITLE
PNI - make sure factory generates fake product images

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5983]
Currently, none of the products have fake product image generated.

<img width="773" alt="image" src="https://user-images.githubusercontent.com/2896608/104059328-07146780-51aa-11eb-8187-78c5830adb98.png">

**Comment by Pomax** [comment]
Hm, I'm pretty sure before I left we landed a PR that generates fake product images, except the images were all "blue rectangles"?

**Comment by Pomax** [comment]
origin code for providing real images: https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/utility/faker/image_provider.py

**Comment by Pomax** [comment]
closing as duplicate of https://github.com/mozilla/foundation.mozilla.org/issues/5905
