### ISSUE TITLE
wagtail-localize: Upgrade to wagtail>=2.11.3

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#5990]
This work can be done on the master branch rather than only for the wagtail-localize branch

- [x] update wagtail from 2.10.2 to 2.11
- [x] further update wagtail to 2.11.1
- [x] further update wagtail to 2.11.2
- [ ] further update wagtail to 2.11.3

**Comment by Pomax** [comment]
bumping to 4 because errors are ruining this upgrade path...
