### ISSUE TITLE
wagtail-localize: set up a dedicated staging instance

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#5991]
In order to reupload all translations in a timely fashion once wagtail-localize is on prod, we will need to generate .po files from a staging instance with a prod DB dump. Without prod data, we won’t be able to upload the generated files.

This ticket is about:

- [x] Setting up a staging instance running on this branch: https://github.com/mozilla/foundation.mozilla.org/tree/wagtail-localize
- [ ] add the temporary staging app as valid callback URL for google auth, and make sure the `SOCIAL_AUTH_GOOGLE_OAUTH2_KEY` and `SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET` heroku env vars are set appropriately.
- [ ] figure out what the `TARGET_DOMAINS` value needs to be
- [ ] Set up cron to make copy of main staging DB
- [ ] Make sure Theo can access staging database data for foundation.mozilla.org
- [ ] Granting me admin permissions
- [ ] Setting up wagtail-localize with a dummy l10n repo (so we can hook up to Pontoon)

**Comment by Pomax** [comment]
@tomusher do you know how we can tie a heroku pipeline to a branch that isn't `master`? I believe cade documented this _somewhere_ but I don't remember where... =S

**Comment by Pomax** [comment]
@TheoChevalier do we need a distinct redis instance?

**Comment by Pomax** [comment]
I'm seeing the builld for the staging app breaking, but I'm not sure why:
```
-----> $ python network-api/manage.py collectstatic --noinput
       /app/.heroku/python/lib/python3.7/site-packages/environ/environ.py:630: UserWarning: /tmp/build_2f74b308_/network-api/networkapi/.env doesn't exist - if you're not configuring your environment separately, create one.
         "environment separately, create one." % env_file)
       Traceback (most recent call last):
         File "network-api/manage.py", line 34, in <module>
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
         File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
           self.execute(*args, **cmd_options)
         File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
           output = self.handle(*args, **options)
         File "/app/.heroku/python/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 188, in handle
           collected = self.collect()
         File "/app/.heroku/python/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 105, in collect
           for path, storage in finder.list(self.ignore_patterns):
         File "/app/.heroku/python/lib/python3.7/site-packages/django/contrib/staticfiles/finders.py", line 131, in list
           for path in utils.get_files(storage, ignore_patterns):
         File "/app/.heroku/python/lib/python3.7/site-packages/django/contrib/staticfiles/utils.py", line 23, in get_files
           directories, files = storage.listdir(location)
         File "/app/.heroku/python/lib/python3.7/site-packages/django/core/files/storage.py", line 315, in listdir
           for entry in os.scandir(path):
       FileNotFoundError: [Errno 2] No such file or directory: '/tmp/build_2f74b308_/network-api/networkapi/frontend'
 !     Error while running '$ python network-api/manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

@tomusher any idea why this might be (also if it's easier to throw this pipeline away and build a different one, that's fine!)

**Comment by TheoChevalier** [comment]
> @TheoChevalier do we need a distinct redis instance?

I’m a bit confused, do we already have a redis instance running? If so, then we should be able to use the same

**Comment by Pomax** [comment]
Foundation staging has a redis service attached, so I'm wondering if we need to create a copy of that, or whether we can make use of that (I've not dealt with redis before so I don't know if it can be shared between staging and the new pipeline or not)

**Comment by TheoChevalier** [comment]
ah, got it. I have no idea then… I had no idea what Redis was before working on this :)

**Comment by Pomax** [comment]
it looks like we're blocked on figuring out how to only build for PRs to the `wagtail-localize` branch - there might be a github action that we can use here, but we might have to self-host it, or get it cleared by MoCo for use on the mozilla org repos.

**Comment by TheoChevalier** [comment]
Hey @Pomax, do you think that sometime during the current sprint we could get that staging instance in a state where I could start using it to create migration .po files? At least I could start preparing .po files for old pages that we know are very unlikely to get updated on prod any time soon.

**Comment by Pomax** [comment]
closing the pontoon/github loop is part of my workload this sprint, so barring no further surprising around the other issues, I should be able to finally get this done.
