### ISSUE TITLE
wagtail-localize: migrate pt to pt-BR

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#5993]
With the move to wagtail-localize, we will need to formally move `pt` to `pt-BR`.

Code sites to update:

- [x] set up a permanent redirect for all `/pt/*` links to `/pt-BR/*` in `urls.py` (or the redirects file)
- [x] source/js/components/petition/locale-strings.jsx
- [x] https://github.com/mozilla/foundation.mozilla.org/blob/08801cdbf3b2f9ce388f2617bb768ab8ccfe24a0/network-api/networkapi/settings.py#L408
- [x] https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templatetags/localization.py#L20
- [x] https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/templates/fragments/canonical_url.html#L31-L34
- [x] https://github.com/mozilla/foundation.mozilla.org/blob/master/source/sass/buyers-guide/views/product.scss#L84
- [x] Make sure Salesforce keeps receiving `pt` when subscribing to the newsletter/signing a petition
- [x] Have `Portuguese` selected by default in sign up forms from `pt-BR` pages: https://github.com/mozilla/foundation.mozilla.org/blob/master/source/js/components/join/language-select.jsx#L20
<img width="574" alt="Capture d’écran 2021-02-15 à 11 27 54" src="https://user-images.githubusercontent.com/1294206/107934882-83a02000-6f78-11eb-9b6f-a773c254f586.png">

**Comment by Pomax** [comment]
Let's fold #5994 into this as well as it's effectively the urls.py part of the same work.

**Comment by mmmavis** [comment]
PR has been merged into `wagtail-localize` 🎉
