### ISSUE TITLE
wagtail-localize: set up redirect for pt URLs

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#5994]
We should set a permanent redirect for all `/pt/*` links to `/pt-BR/*`

This should work for any link on the main site, PNI, or MozFest.

**Comment by Pomax** [comment]
This will be be an update to `urls.py`

**Comment by Pomax** [comment]
folded into https://github.com/mozilla/foundation.mozilla.org/issues/5993
