### ISSUE TITLE
Strategize connection between CMS authored pages and network site

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#600]
As we gear up for more self-service use of CMS authored pages, we've discovered some room for improvement, particularly at the top of these pages to clean up connection to rest of the site. 

Use case A – a network page: If a visitor lands directly on a CMS authored pages, people would benefit from more context to guide them from that page to the rest of the site. Maybe we offer a sidebar for context and a link to home and about? Tracking this here: Capture organic traffic #540. 

Use case B – a mini-site: The Mozilla Information Trust Initiative needs a landing page or mini-site. In this case, we might want to offer authors more independence from the network site (though this is debatable). The top-level nav and signup button could be confusing to visitors. Do we want to hide this stuff and offer a more muted link to the network site? Or, can we clarify the relationship between initiative and the network without creating too much noise?

See mockups: https://redpen.io/wh681ba02d54215838

**Comment by xmatthewx** [comment]
@jessevondoom – I think we need guidance from you on Use case B. Do we want to enable fairly independent initiatives? How do we best connect them to larger site, network, and movement?

**Comment by kristinashu** [comment]
It has a name now and it's called Zen mode! Should be live very soon!
