### ISSUE TITLE
PNI to Airtable connection

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6008]
We want to push Wagtail-based PNI products to an Airtable sheet. We'll want to use the [wagtail-airtable](https://github.com/wagtail/wagtail-airtable) package. 

Some things we'll need to know:
- [ ] Is this a one-way or two-way data sync? As in, can we export data from Wagtail to Airtable and vice versa (two-way)? Or Only send data to Airtable from Wagtail (one-way)?
- [ ] What kind of data do we want to store in Airtable? We can add just about everything except images. We probably want an exact product URL, product name, product category or categories, and what else would the Airtable users be looking for? 
- [ ] It'll be easiest if I have Airtable access to I can setup the Airtable columns (for things like dropdowns, enums, checkboxes, etc). We will want to look into that. Though I can always walk someone through it if permissions are going to cause problems. 
- [ ] While we're adding Airtable support for PNI products, are there any other models or data types we want to automagically push to Airtable? (If there are, we should consider opening a small epic).

CC @benhohner

**Comment by benhohner** [comment]
> Some things we'll need to know:
> 
>     * [ ]  Is this a one-way or two-way data sync? As in, can we export data from Wagtail to Airtable and vice versa (two-way)? Or Only send data to Airtable from Wagtail (one-way)?
Dependent on how easy this is to achieve:

1 way, added items get updated or appended then removed from the Airtable spreadsheet, like a queue that triggers when you click "add"

OR

2 way
> 
>     * [ ]  What kind of data do we want to store in Airtable? We can add just about everything except images. We probably want an exact product URL, product name, product category or categories, and what else would the Airtable users be looking for?
> 
Everything except for image, privacy policy links section, updates section, and related products section

>     * [ ]  It'll be easiest if I have Airtable access to I can setup the Airtable columns (for things like dropdowns, enums, checkboxes, etc). We will want to look into that. Though I can always walk someone through it if permissions are going to cause problems.
> 
Invite sent

>     * [ ]  While we're adding Airtable support for PNI products, are there any other models or data types we want to automagically push to Airtable? (If there are, we should consider opening a small epic).
I don't think so at the moment.

@KalobTaulien
