### ISSUE TITLE
Explore a timeline or current events like feed

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#601]
For the end of the year, could be interesting to explore what a timeline could look like. Gathering highlights from projects, news, etc, calling out milestones in the year. 

[one precedent](http://mollywhite.net/wikimedia-timeline/) and  another [mofo specific precedent](https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1aypWtbAW4Z8v_PfHPx9JuJL4rJxBoz49Ry0mnFIHSxM&font=Default&lang=en&initial_zoom=2&height=650)

originally posted at https://github.com/mozilla/network-pulse/issues/55

**Comment by kristinashu** [comment]
EOY has come and gone! Closing this.
