### ISSUE TITLE
Move `BuyersGuideProductCategory` model to `wagtailpages` app

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6012]
Spin off from #5886

> we probably want to switch to a new category class instead, house in wagtailpages, so we can start moving away from needing code from the buyersguide app.
> 
> We can have a look at https://stackoverflow.com/a/26472482 and see if that works with wagtail mixed in

**Note**: My estimate of `4`is quite conservative. It could very well be an `8`. It's not a very straightforward task. There's also [this realpython](https://realpython.com/move-django-model/) article that could help shed some light on moving an entire model with ForeignKeys attached to it.

**Comment by Pomax** [comment]
I'm bumping this to 8 because I'd rather over estimate

**Comment by KalobTaulien** [comment]
Opened #6313 to remove old BuyersGuideProductCategory model code.
