### ISSUE TITLE
Update content security policy for Vimeo

### ISSUE THREAD

**Issue by benhohner** [mozilla/foundation.mozilla.org#6015]
### Describe the feature request
Add Content Security Policy: player.vimeo.com to (“frame-src”) to enable embedding Vimeo videos with the Wagtail video component.

### Additional context
The content team plans to use Vimeo videos more in the future.

**Comment by benhohner** [comment]
@kristinashu slated for this sprint!

**Comment by kristinashu** [comment]
Yay! cc @natalieworth since you mentioned Audrey was wanting this.

**Comment by natalieworth** [comment]
Yas! Amazing ty ty @benhohner and @kristinashu :D

**Comment by mmmavis** [comment]
Done. Added `https://player.vimeo.com` to `CSP_FRAME_SRC` whitelist.
