### ISSUE TITLE
Audit our redirects for permanent/temporary status

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6016]
while working on https://github.com/mozilla/foundation.mozilla.org/issues/5738 I found a lot of CMS redirects that should probably be permanent redirects rathe than temporary redirects, based on the SEO notion that anything that is intended to never host content again, or will not host content for at least a year, should be a permanent redirect, whereas urls that might go back to hosting real content within a year should be temporary redirects.

Let's audit our redirects to see which ones can be marked permanent, so that we know which are safe to remove in the future based on whether they're a year old or not.

**Comment by taisdesouzalessa** [comment]
Audit is here: https://docs.google.com/spreadsheets/d/1gKhZkm_-4nm8vW4iKAAPLhSnop_4hQqtjl4-AbyrDdI/edit?usp=sharing - work in progress

**Comment by taisdesouzalessa** [comment]
Audit completed. Redirects changed. From the 34 links we audited **we changed 32 from Temporary to Permanent**.

**Comment by taisdesouzalessa** [comment]
Thanks for pushing for this change @Pomax and for the additional context on parameters to consider when thinking about the redirects. Closing this ticket.
