### ISSUE TITLE
[Wagtail documentation] Image guidelines

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#6019]
**Background:**
To offer staff guidance on best export formats depending on type of image + encourage optimization to reduce file sizes.

From Pomax:

> 
> Encoding, exports recommended (PNG)
> JPG for “real” images (photos, natural blurs, etc)
> Usually these don’t need to be 100% quality to look good, 85% tends to still be virtually indistinguishable from 100%
> PNG for when crisp lines are important
> There are optimizing tools for reducing their file size after export that we can use. 

Tools to use: tinypng.com/tinyjpg.com, ImageOptim
https://sourceforge.net/projects/nikkhokkho/
https://imageoptim.com/versions.html 

**To do:**
- [x] add these guidelines here https://foundation.mozilla.org/en/docs/how-do-i-wagtail/photo-and-image-guidelines/  - Pomax to write the bulk of info/ Taís to support
- [x] Once guidelines are added, notify staff in #mofo-wagtail channel and other relevant channels, if any

**Comment by Pomax** [comment]
I've stubbed out the initial section over on https://foundation.mozilla.org/cms/pages/236/edit as `#4`, which is now live on https://foundation.mozilla.org/en/docs/how-do-i-wagtail/photo-and-image-guidelines/

I'm trying to think of how best to show a good example of JPG and PNG, and then what they look like using "the other format" to show why they are worse, would that make sense?

**Comment by taisdesouzalessa** [comment]
@Pomax I added some graphic elements on top of the images to really emphasize the advantaged of one format over other in each case. Let me know what you think?

First set of images:
<img width="891" alt="image" src="https://user-images.githubusercontent.com/22157921/105225489-817ea900-5b13-11eb-830b-9ffdfd51594e.png">


Second set of images:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/22157921/105225445-7166c980-5b13-11eb-8f0c-392f4dead7e6.png">

Can you give me a thumbs up here if it is all good to you? When I have a confirmation from you, we can post it in the Wagtail channel (I can do that if you want or let me know if you prefer to post it).

**Comment by Pomax** [comment]
love it - I've notified staff in the wagtail channel of the docs update.
