### ISSUE TITLE
[Analytics] Google Tag Manager: documentation and sharing

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#6022]
**Background:**
We implemented GTM in our Foundation site and MozFest site. More details here: #5935

**To do:**
- [ ] Taís: to learn about GTM - resource shared by Ben [in this doc](https://docs.google.com/document/d/1Qh08EbSSRVtno3cgHokilfcnXB7FnJaA-VNDk_u3whs/edit?usp=sharing)
- [ ] While learning, write a basic documentation to make it easier for other designers to onboard it.
- [ ] Schedule a brownbag session on creating our own tags

**Comment by kristinashu** [comment]
No longer needed.
