### ISSUE TITLE
[PNI] add a category-picker to the BuyersGuidePage (homepage) that is used to exclude products from the listing

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6025]
Have categories that purely organizational categories (e.g. not for showing the category nav) and can be used to exclude products from showing in `catalog.html` product sets.

Use case: have a "valentine's day" category that shows in the nav as well as a "sex toys" category that doesn't show in the nav, assign all the sex toys to both categories, and then be able to tell the homepage to exclude listing any product that has "sex toys" as (one of) its categories.

- [x] allow category creation in the CMS
- [x] allow categories to specify whether they show up in the nav menu
- [x] add an `excluded_categories` field and `snippetChooserPanel("excluded_categories")` to the BuyersGuidePage model, that can be populated with categories that should be excluded from the homepage. (e.g adding "sex toys" would remove all products in that category, even if those products are also in other categories, from the list on the PNI homepage, but not from PNI category pages)
- [x] update the queryset that gets used for `catalog.html` so that products that are in any of the categories in `excluded_categories` get filtered out before the template gets rendered

**Comment by Pomax** [comment]
@mmmavis this might be a nice issue for exploring the backend, I'd be happy to talk through what kind of code the functionality would need.

**Comment by mmmavis** [comment]
@Pomax 

> have an "exclude products from category..." picker on the BuyersGuidePage's CMS admin page

Could you clarify what you mean by "BuyersGuidePage's CMS admin page"?  Were you thinking about adding a new type of snippet? A new field in "Buyers Guide Product Categories" snippet? Or?

**Comment by Pomax** [comment]
@mmmavis I've updated the initial comment, is that clearer?

**Comment by mmmavis** [comment]
@Pomax`SnippetChooserPanel` seems to only allow singular selection. Do we wanna allow BuyersGuidePage to take more than one "exclude category"?

**Comment by mmmavis** [comment]
I've tried creating `excluded_categories` as `ParentalManyToManyField` and pairing it with `FieldPanel`, but `page.excluded_categories` would just return `wagtailpages.BuyersGuideProductCategory.None `

**Comment by Pomax** [comment]
We do, so the trick there is the same we use for blog authors: there is the [snippet itself](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/pagemodels/blog/blog.py#L60-L77), which we'd only be able to include one of, so instead we have a separate [orderable model](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/pagemodels/blog/blog.py#L80-L94) that "wraps" that snippet. That way, we can use the [InlinePanel](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/pagemodels/blog/blog.py#L117-L127) to get "more than one".
