### ISSUE TITLE
wagtail-localize: prepare MozFest site for wagtail-localize

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#6030]
<img width="943" alt="Capture d’écran 2021-01-15 à 11 52 15" src="https://user-images.githubusercontent.com/1294206/104716376-c70c3200-571f-11eb-8f98-29428a0fbaa1.png">

This issue happens when trying to translate the MozFest homepage with wagtail-localize ([this branch](https://github.com/mozilla/foundation.mozilla.org/tree/wagtail-2-11))

This may or may not be the same root cause as for #5953, which is still being investigated.

**Comment by KalobTaulien** [comment]
Found the problem for this issue. `wagtail-localize` is looking for `header`, which exists as a field, but is being stripped away and taken out of the conten`content_panels`. The trouble code is here:

https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/mozfest/models.py#L147-L168

Still looking into the issue for #5953

**Comment by KalobTaulien** [comment]
Opened an issue with wagtail-localize here https://github.com/wagtail/wagtail-localize/issues/306

**Comment by KalobTaulien** [comment]
Found the solution to this with @kaedroho's help. 

```python
from wagtail_localize.fields import TranslatableField, SynchronizedField

class MozfestHomepage(MozfestPrimaryPage):
    ....
    translatable_fields = [
        TranslatableField('title'),
        TranslatableField('slug'),
        TranslatableField('seo_title'),
        SynchronizedField('show_in_menus'),
        TranslatableField('search_description'),
        SynchronizedField('search_image'),
        # TranslatableField('header'), # <- This is removed from the list of `translatable_fields` because it's not being used on the Mozfest Home page
        SynchronizedField('banner'),
        TranslatableField('intro'),
        SynchronizedField('signup'),
        TranslatableField('body'),
        SynchronizedField('use_wide_template'),
        TranslatableField('cta_button_label'),
        TranslatableField('cta_button_destination'),
        TranslatableField('banner_heading'),
        TranslatableField('banner_guide_text'),
        SynchronizedField('banner_video_url'),
        SynchronizedField('footnotes'),
    ]
```
