### ISSUE TITLE
[Homepage hero image]

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#6034]
Xavier will add [this blog post](https://foundation.mozilla.org/en/blog/announcing-8-projects-examining-ais-relationship-with-racial-justice/) to our home page and needed a hero image for that.

**To do:**
- [x] Design hero image
- [x] Apply feedback (if any)

Proposal added to staging for approval - designers + Xavier

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/22157921/104785878-778a2e00-5740-11eb-813e-499e36582f9e.png">

**Comment by kristinashu** [comment]
I think this is done and good to close!

**Comment by taisdesouzalessa** [comment]
I sent it Xavier's way today but I don't think we will have any feedback in terms of image modification. Will check with him tomorrow morning before closing this issue.

**Comment by taisdesouzalessa** [comment]
Done and approved by all. Will open a follow up stretch ticket related to creating templates for the hero images. Ticket here:  #6050
