### ISSUE TITLE
PNI products don't show up in review apps

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6042]
Looking at the latest couple review apps, Ive noticed Product images dont show up. I had to manually overwrite one by logging into the admin. 

We need to find a way to copy PNI product images into review apps.

If this is a duplicate issue, please close this one.

**Comment by mmmavis** [comment]
Dupe of https://github.com/mozilla/foundation.mozilla.org/issues/5983 😉 . Closing.
