### ISSUE TITLE
Percy seems to not load a specific image half the time

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6043]
The "who we are" page seems to be missing its banner image half the time on Percy, let's figure out why.

**Comment by mmmavis** [comment]
Getting the same false positive flag but it's with the "Who we are" page. 
![image](https://user-images.githubusercontent.com/2896608/104961784-dc859400-598b-11eb-861d-3f1a486688f7.png)

**Comment by Pomax** [comment]
thanks, I think I just wrote the wrong page title. updated the issue.

**Comment by mmmavis** [comment]
My guess is that the default background image is too large (1.71 MB) so it takes long to load. Sometimes it doesn't get loaded in time and that causes Percy to flag it. I will try reducing the file size to see if it helps.

**Comment by mmmavis** [comment]
@Pomax @KalobTaulien I've landed the PR which made that banner image smaller in file size. Gonna keep this ticket open and close it towards the end of the sprint if none of us experience the Percy issue again.

**Comment by mmmavis** [comment]
I haven't encountered the same issue since so I'm gonna close this ticket.
