### ISSUE TITLE
[PNI] Apple Homepod image is broken

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#6049]
### Describe the bug

The Homepod image on https://foundation.mozilla.org/fr/privacynotincluded/apple-homepod/ can’t be displayed.

Opening the image directly in Firefox shows a message saying the image contains errors: https://res.cloudinary.com/mozilla-foundation/image/upload/v1604693714/foundationsite/buyersguide/Apple-Homepod_ddkmd2.jpg

The console logs are showing a 404 for this resource, it may have just been deleted by mistake?

![Screenshot_2021-01-19  confidentialité non incluse un guide d’achat pour les objets connectés](https://user-images.githubusercontent.com/1294206/105019951-9a695a80-5a3e-11eb-8646-b1db001722d2.png)

**Comment by kristinashu** [comment]
I've re-uploaded the image and it seems fine now. Let me know if you have any more issues with it.
