### ISSUE TITLE
[Foundation Website] Hero Image templates

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#6050]
**Background:**
From time to time we have to quickly build a hero image (for homepage and for "what we can do" page) for relevant Foundation initiatives. It would be very useful if we have templates we can quickly use depending on the situation so we can quickly swap images instead of reinventing the wheel over and over. Based on suggestion gave by @kristinashu via Slack.

**To do:**
- [x] Create an area on Figma displaying past examples of hero images (with dimensions).
- [x] Under each past example, find opportunities of reusing the style. For instance: the mosaic picture style can be used to highlight new Fellows, projects from Awardees or any other collection of projects or profile pictures. 
- [x] In this Figma doc, add the links to Photoshop source files so we can reuse them.
- [x] Create a small slide deck with ideas of quick "hacks" other companies do for image styling that we could adopt in the future. Then present to designers in our critique meeting.

@natalieworth @sabrinang @nancyt1 what do you think of this idea? If you have any suggestions of process/improvements, please edit the to do list :). Also if anybody wants to collaborate on this project, please assign yourself. 

**Reference:**
Take a look at this discussion too:  #5954

**Comment by kristinashu** [comment]
Add a note that the template should show where text will appear at different screen widths in order to make sure the text is legible and the graphic looks good.

**Comment by taisdesouzalessa** [comment]
Instead of doing a presentation, I added them all to Figma. It is currently under design review

https://www.figma.com/file/O4EsReprDAlTaW3ARqmJX5/Homepage-hero-images?node-id=0%3A1

**Comment by taisdesouzalessa** [comment]
This is done and we can now use it as a reference when designing our hero image for the homepage.
