### ISSUE TITLE
[IA Refresh] Measuring success: part III (b) 

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#6051]
**Background:**
According to our Foundation Site Information Architecture document, those were the 4 areas we want to focus to assess the success of our IA refresh initiative:

1.   Reduce the bounce rate on our homepage by 20% through site updates based on user testing, analytics, and staff interviews
2.   Qualitative testing finds that users’ understanding of Mozilla Foundation’s mission improves by 25% (conduct baseline/control test along with prototypes in April)
3.   Qualitative testing finds that staff can more easily find the content they are looking for compared to initial IA audience report
4.   Behaviour in Google Analytics shows users going to a diverse set of pages

In part I (#5706) we took a look at the analytics, in part II (#5711) at the perception of internal stakeholders and in the part III (a- #5775) and b (this one) we will collect users insights and compile all the results.

**To do:**
Continue work started on part III (a) - #5775
- [ ] Make sure to incorporate team's feedback from part II ( #5711)
- [x] Analyze 5 mobile interviews - done in part III (a)
- [x] Analyze 5 desktop interviews
- [x] Find patterns and insights (desktop + mobile)
- [x] Produce a report of the findings, comparing it against the goals we set

**Comment by taisdesouzalessa** [comment]
Nancy and I did a board with all the user testing noted in Figma: https://www.figma.com/file/IV1NZFuosASSFJPkcr3WiR/User-Testing-Analysis?node-id=0%3A1

Tomorrow we will meet to find patterns and make sense of the data.

**Comment by taisdesouzalessa** [comment]
Nancy and I started finding patterns today. Will have another session on Monday.

**Comment by taisdesouzalessa** [comment]
this is 80% done. Will finish it at the beginning of next sprint.

**Comment by taisdesouzalessa** [comment]
Report done! [Link here](https://docs.google.com/document/d/1_ozmuyj2m8so10yb-UcbC86JirfJFuKCbq8i8Hdkgak/edit?usp=sharing)
@nancyt1 can you please review it/add your thoughts before we share with other designers for feedback? Questions I had in mind, but feel free to consider other things as well:
• does it flow well? 
• Does the information displayed there seem true according to your experience? 
• Anything you would add/remove/change? 
This report is ours so feel free to suggest edits and critique!

**Comment by kristinashu** [comment]
@nancyt1 have you had a chance to review this yet?

**Comment by taisdesouzalessa** [comment]
Nancy reviewed this project and I updated the report with her recommendations! Thanks, @nancyt1 💯
