### ISSUE TITLE
wagtail-localize: Investigate whether syncing is on by default

### ISSUE THREAD

**Issue by benhohner** [mozilla/foundation.mozilla.org#6061]

**Comment by KalobTaulien** [comment]
If by auto-sync we mean when we change, lets say, a title from an English page — it will not auto update the other languages.

**Comment by KalobTaulien** [comment]
@pomax I've moved this to review before closing it so at least one other member on the team is aware of these findings. Or if I've misunderstood the goal of this ticket, please let me know and I'll move this back to "In Progress"

**Comment by Pomax** [comment]
I think we can close this, although it's something we'll have to educate staff on.
