### ISSUE TITLE
wagtail-localize: Audit code for _en

### ISSUE THREAD

**Issue by benhohner** [mozilla/foundation.mozilla.org#6062]

**Comment by KalobTaulien** [comment]
### Findings: 

There's a lot of migration data. Not sure if we want to update the migration files for consistency or let model-translation create a new migration to handle that. Probably the last option as that's likely easiest and leaves the migration history in tact. 

There's mention of `slug_en` in [buyersguide/tests.py:165-167](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/buyersguide/tests.py#L165-L167) (and one more on [line 153](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/buyersguide/tests.py#L153) of the same file). When we remove model-translation we need to remove those two lines. As well as `name_en` in from [pagemodels/product_category.py:66](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/buyersguide/pagemodels/product_category.py#L66) -  Both situations here are easy solutions. 

From what I can tell anywhere we find `_en` we can safely remove it, or set the value to its non-_en value (ie. self.title_en becomes self.title). And there are no signs of using other suffixes other than `fy-NL` in a single unit test. 

There are a couple of other places that use `title_en` or `slug_en`. 

When I removed or replaced the values of all of these locations the site worked perfectly fine (working off of Theo's 2.11 Wagtail branch) and tests were passing as expected. 👍 

Ticket #6063 addresses fixing the code and formally working with the code base. No PR required for this ticket.

**Comment by Pomax** [comment]
I think we want to leave existing migrations as is and instead add removal migrations on top. I started a dedicated "unhook wagtail-modeltranslation" PR over on #6085 (based mostly on Theo's 2.11 Wagtail branch, too) which we can use to address the `[...]_end` removal in code, too, including fixes to tests because this should be a PR in and of itself that can successfully pass CI =)
