### ISSUE TITLE
wagtail-localize: Test localized category reassignment (product/blog)

### ISSUE THREAD

**Issue by benhohner** [mozilla/foundation.mozilla.org#6064]
If we localize PNI categories, as well as blog categories, what happens to all the "other" locales? E.g. update a product category in the English locale, does that product still live in the "old" category for the French page instance?

(and the same for blog posts, but that's less pressing as we rarely, if ever, change categories for those)

**Comment by KalobTaulien** [comment]
I've been thinking about this.. 

The categories themselves are mostly meta data, and are managed in the wagtail admin in English. So we might not even need to translate things like category fields — we just need to translate the copy in the template so it looks translated. 

The one caveat about what I just said is... slugs. Slugs would always be in english. I'm not sure how we feel about that. On on hand if the category slugs are always in english, it keeps the codebase simple. But on the other hand, search engines operating in different languages might not pick up on exact queries. So there's a trade off here. 

@Pomax @benhohner thoughts on that?

**Comment by Pomax** [comment]
We generate the nav bar using "normal" template code, so we definitely use the snippet fields, not static strings:
```
{% for cat in categories %}
  {% if cat.published_product_page_count > 0 %}
    {% routablepageurl page 'category-view' cat.slug as cat_url %}
    <a class="multipage-link {% check_active_category current_category cat %}{% if cat.featured is True %} featured{% endif %}{% if category == cat.slug %} active{% endif %}" href="{{ cat_url }}" data-name="{{ cat.name }}">{{ cat.name }}</a>
  {% endif %}
{% endfor %}
```

https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/buyersguide/templates/buyersguide/bg_base.html#L88-L93

**Comment by KalobTaulien** [comment]
We're going to need to do some Locale searching to make PNI work properly. I created a category called "Kalob Test" and translated it into Spanish, called "Kalob Test (ES)". 

One product in "Kalob Test" and one product in "Kalob Test (ES)". 

Both translations show up in the category menu. We'll need to write some locale detection for that context data in the view (Page). 

Also products become duplicated. It shows the english and spanish versions (the image below doesn't capture this but one is spanish one is english). We will need to implement some locale detection in there as well so when we move to wagtail-localize we aren't looking at 17 duplicate products for 17 different languages. This shouldn't be too hard, but we'll likely want to add caching to PNI again. 

![image](https://user-images.githubusercontent.com/4743971/109680890-2b514c80-7b3a-11eb-8bd7-e42788214c11.png)


To get a translated object:
```python
from wagtail.core.models import Locale 
from networkapi.buyersguide.pagemodels.product_category import BuyersGuideProductCategory  

obj = BuyersGuideProductCategory.objects.get(pk=8)
obj_es = obj.get_translation(Locale.objects.get(language_code='es'))  # <- Will need access to the language code in the URL
```

@Pomax Let's talk this through next time we're both working on wagtail localize

**Comment by KalobTaulien** [comment]
I'm moving this ticket into `blocked` because we want to keep the work attached to it for the future, but we can't action on this until we re-do wagtail-localization with a less-divergent set of branches.

**Comment by jamilasnell** [comment]
Closing this ticket as we will have to re-do the work anyway.
