### ISSUE TITLE
wagtail-localize: Verify PNI search works

### ISSUE THREAD

**Issue by benhohner** [mozilla/foundation.mozilla.org#6065]
Of course, this is actually PNI result filtering, so should be entirely unaffected, but we should double check to make sure that localization does not somehow "break" search filtering.

important to check:
- [ ] ensure that `/en/` pages only list `en` product cards, `/fr/` only shows `fr` cards, etc.

**Comment by mmmavis** [comment]
I've verified it by

1. go to https://foundation.mozilla.org/fr/privacynotincluded/
2. search for `téléviseur`
3. only `Google Chromecast` shows up as a result
4. and then go to https://foundation.mozilla.org/en/privacynotincluded/
5. search for `téléviseur`
6. no result was found
