### ISSUE TITLE
wagtail-localize: Staff training and change management

### ISSUE THREAD

**Issue by benhohner** [mozilla/foundation.mozilla.org#6067]
Document how things will work now, as well as how this differs from before, and schedule time to either send out an email to all staff, or schedule a brown bag that can be attended and recorded for those who cannot attend.

**Comment by Pomax** [comment]
Estimate as 2 mostly because documentation is hard.

**Comment by Pomax** [comment]
@benhohner who would be best to assign this to? Or collab-mult-assign?

**Comment by benhohner** [comment]
@Pomax someone who was responsible for implementing the changes should probably do documentation. As for the training, anyone who understands how it works would be good; either yourself or kalob or mavis

**Comment by benhohner** [comment]
Need docs for 
- How to use page or snippet chooser without language

**Comment by bheasman** [comment]
Closing - can revisit if the requirement still stands
