### ISSUE TITLE
[Insights team: Data Futures Lab] Data Stewardship Ecosystem and Demand study

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#6073]
### Background:
This is the part II of the [research we already published on our site](https://foundation.mozilla.org/en/initiatives/data-futures/). 
The title of the research is "Data Stewardship Ecosystem and Demand study".

### To do:
SITE
- [x] Read the research and analyze if it would fit better as new tab items [here](https://foundation.mozilla.org/en/initiatives/data-futures/) or if it would be better to move them all to Publications template. Sabrina can help on this task since she is familiar with Publications. **Responsible:** Sabrina
- [x] While reading the research, make sure to mark content types: Airtable, tables, images - so we start forming an idea of structure and needed images. **Responsible:** Taís with Sabrina's help.
- [x] Once we have an idea/suggestions of structure, propose them to Insights team **Responsible:** Taís 
- [ ] After proposal, Insights team can populate their page with content **Responsible:** Insights team
- [ ] After content is populated, design can review site for usability improvements.  **Responsible:** Taís 

IMAGES
- [ ] Interactive images/visualizations. Insights team has a contractor (Christian Laesser) who will create them. The responsibility of our team is to make sure we can integrate those on Wagtail pages - as discussed via Slack, we will integrate them in our site as static images and have a link to go to the interactive site (ideally we can host the site within Mozilla) > @jamilasnell could you please check with Engineers if it is possible? **Responsible:** Taís / Jamila

PDF 
- [ ] Add content to Mozilla Foundation Doc template **Responsible:** Insights team 
- [ ] Do a design review, connect PDF with site **Responsible:** Taís 

### References:
**Airtable link:** https://airtable.com/tbljPmOCkK9JShaTS/viw9sdUJiIjCYpn0Y/rec0Abfjqo93TEU07?blocks=hide
**Draft copy:** https://docs.google.com/document/d/1D1nVFMC9WCWHq8nVyP3AbqGfde6U-z2JpL36_HRb1vY/edit#heading=h.t4ihadghehzo
**Epic ticket:**  #6047
**Design needs (doc prepared by Insights team)**: https://docs.google.com/document/d/1Bf9N7p5qvza7HFq7oUDUcdBtsVae6RVEDDsI6Fj-63c/edit?usp=sharing

**Comment by taisdesouzalessa** [comment]
@sabrinang since the thinking on adding content to Publications (if splitting them or all in one publication), I moved this ticket to this sprint - marking as in progress, cool?

cc: @kristinashu @jamilasnell

**Comment by sabrinang** [comment]
I've transferred the draft copy doc and used placeholder images on this page using publications template:
https://foundation.mozilla.org/en/data-futures-lab/data-stewardship-ecosystem-and-demand-study/

**Comment by taisdesouzalessa** [comment]
Sabrina and I split the follow-up tickets for this issue:
 #6132 for non-Publication related support
[ 751 on Design Repo](https://github.com/MozillaFoundation/Design/issues/751) for Publication-related suppport
