### ISSUE TITLE
[Insights team] Movement partnership landscape analysis

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#6074]
### Background:
This is for internal use only for now but I thought it would be great to put it on the website as password protected for easier use, especially because we will be visualizing the [mapping of AI and social movements](https://docs.google.com/spreadsheets/d/1lbYLUR40huRk_hs0NUK5Y3X5feizTj-Ew9I_UDSohU4/edit?usp=sharing) intersections and we'll need to embed it somewhere.

UPDATE: Jan 25th - it seems Insights team will have a contractor to do the graphics they need plus they will add this page to Publications so our role on this project is smaller than initially thought.

### To do:
- [x] Make sure the content is password-protected. Keep in mind this is for internal use only. **Responsible:** Taís
- [x] Sort out URLs. [Work being done on this ticket](#6076). **Responsible:** Taís 
URL: https://foundation.mozilla.org/en/insights/movement-partnerships-analysis/ - Password-protected
- [x] Connect Ben and Christian so they can talk about the possibility of having iframes on the Wagtail site
Opened a thread with them both and Kasia via Slack
- [ ] Do a design review once Insights team turn this research into a Publication.

### References:
**Airtable link:** https://airtable.com/tbljPmOCkK9JShaTS/viw9sdUJiIjCYpn0Y/recWsZuYmNKwdrMnT?blocks=hide
**Draft copy (to be shortened):** https://docs.google.com/document/d/1o6R-_Gpd0XOKn1GhsCJ4AxANtdKOfHTodY7f8LAkLXY/edit#heading=h.yive0zz6hsnc
**Epic ticket:** #6047
**Design needs (document created by Insights team)**: https://docs.google.com/document/d/1onTGvEOQaLw2UDoXdmLqOxw0wixgjF9QTpdUcXMu1tE/edit

**Comment by taisdesouzalessa** [comment]
@kristinashu I updated the ticket, please let me know if it is more accurate with the current plan. Feel free to change it if needed. Thanks!

**Comment by sabrinang** [comment]
From looking through the draft, some publication feedback things to consider are:
- “Quote” block component exists for regular cms pages but we don't have those on publications _(it looks like they want to highlight a few quotes throughout the doc but they may be able to just use what we have in content block?)_
- Call out boxes with styled text: currently we just have grey background behind unstyleable text (if publications can provide clear hierarchy with what we have we may not need it?)

Everything else seem straightforward but if insights team are putting in content then I can take a look again after when some stuff is in the cms.

**Comment by kristinashu** [comment]
To close this ticket
- [ ] @sabrinang to open ticket for next sprint to do a design review of the publication once Insights has added in all the content
- [ ] @sabrinang to add above possible feature request to the new epic ticket/doc
- [ ] @taisdesouzalessa to remind Insights of our doc template

**Comment by sabrinang** [comment]
issue filed here: https://github.com/mozilla/foundation.mozilla.org/issues/6118 Design Review of Movement partnership landscape analysis

**Comment by sabrinang** [comment]
issue for tracking publication feature requests here: https://github.com/mozilla/foundation.mozilla.org/issues/6119 [Publications] Feature Requests

**Comment by kristinashu** [comment]
@taisdesouzalessa up to you if you think they need reminding or not. But I think this is good to close!

**Comment by taisdesouzalessa** [comment]
Kasia and Eeva were notified via Slack about the Doc Template.
