### ISSUE TITLE
[Data Futures Lab] Microsite

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#6076]
______
🚫  **BLOCKED BY CONTENT: Mehan and team to populate with content the structure we created** 
_____
### Background:
The Data Futures Lab will need a microsite (initiative led by Mehan and Lindsey). This site will host the research the Insights team is doing and additional items.

### Wireframe:
Here is the wireframe the team put together: https://balsamiq.cloud/sj2hm38/paaw8qh/r2278

### To do:
As discussed with Mehan via Slack, this is the plan:
- [x] Think about how all the URLs structures will fit together (Data Futures microsite, Insights Projects, Insights Hub). **Responsible:** Taís, looping Kristina in
- [x] Do a sketch to present to Insights team: [Insights Hub](https://foundation.mozilla.org/en/insights/) will become a bigger hub with all things Insights (Data Futures Lab, Trustworthy AI research included) + include other people in "Meet the Team" (all people who do research at Mozilla)
- [x] Data Futures Lab (Mehan's project) will have tabs to encompass the work Insights team did (Research)
- [x] Do the wagtail structure, following the wireframe. **Responsible:** Taís
- [x] Mehan and team to populate it via CMS. **Responsible:** Mehan and team
- [ ] Do a design review at the end (to check usability issues, opportunities to add illustrations/icons). **Responsible:** Taís

### Deadline:
End of this sprint - Feb 1 for the "skeleton". Full site must be ready before MozFest (March 8th 2021)

[Airtable link here. ](https://airtable.com/tbljPmOCkK9JShaTS/viw9sdUJiIjCYpn0Y/recwcfpllJzWY84CE?blocks=hide) -

**Comment by taisdesouzalessa** [comment]
[URL and structure thinking here](https://www.figma.com/file/AABYnCVDRDfyMSyyTYiGAH/URL-plan-Mozilla-Research?node-id=0%3A1):
<img width="390" alt="image" src="https://user-images.githubusercontent.com/22157921/105562469-15e13b00-5ccf-11eb-8375-ce550f4ba6b1.png">

Next step: connect with @kristinashu to see what she thinks.

**Comment by taisdesouzalessa** [comment]
Connected with Kristina, will update the ticket with our plan (the first checkbox has some sub-items). will connect with Sabrina to figure out if we should move the "Data Futures Lab" Insights work into Publications.

**Comment by taisdesouzalessa** [comment]
Data Futures Hub here: https://foundation.mozilla.org/en/data-futures-lab/
Asked for design review before sending Mehan's way.

**Comment by taisdesouzalessa** [comment]
Design review done, site sent to Mehan. 
Highlighted those next steps to him via Slack:
• their team to populate this page
• then we can do a design/usability review once content is ready - please give Design some days to do this work before launch - ping me when it is done or if you need any design support through the process (like illustrations/pictures)
• Also asked him to fill out the Design Brief so I can have a better idea of their goals when doing the design review with all the site's content.

**Comment by kristinashu** [comment]
New tickets
- Tais: IA map to include [/learning tab](https://foundation.mozilla.org/en/data-futures-lab/learning/) with arrows linking the publication(s)
- Sabs: turning [existing data futures site](https://foundation.mozilla.org/en/initiatives/data-futures/) into a publication(s)

**Comment by sabrinang** [comment]
Issue for turning existing data future site report into publication here: https://github.com/mozilla/foundation.mozilla.org/issues/6120

**Comment by taisdesouzalessa** [comment]
Design review - ticket here: #6122
/learning tab work: Data Futures Hub and Insights Team work connections - ticket here:  #6123
