### ISSUE TITLE
Update factory boy and Faker

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6105]
factory boy/faker need to be bumped by (several) major versions, which also requires changing some of our code that relies both on apparently ancient APIs, but also on what appears to be entirely undocumented behaviour around data providers for Faker.

**Comment by tbrlpld** [comment]
Most work on this ticket has already happened. I only created a PR to bump Faker to the latest version (we currently use one that is 4 months old, so also pretty fresh still).

**Comment by tbrlpld** [comment]
@cdanfon This ticket is done already 👍

**Comment by cdanfon** [comment]
@tbrlpld How long did it take you? (story points)

**Comment by tbrlpld** [comment]
Maybe 1
