### ISSUE TITLE
wagtail-localize: ensure redirects work correctly with wagtail-localize

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6114]
There are some redirect oddities that we need to address: if I have a rule `/blogz` that goes to the `/blog` page instead, and it works for both unlocalized and localized URLs, the latter is a bit funny:

- ✔️ `/blogz` goes to `/en/blog` as expected,
- ✔️ `/en/blogz` also goes to `/en/blog` as expected
- ❌ a non-default locale code like `/fr/blogz` seems to remove the locale, apply the redirect, but forgets which locale the request was for, redirecting to `/en/blog` instead of `/fr/blog`
- ❌ even if I set my language preference to French with the language picker in our footer, `/blog/` correctly takes me to `/fr/blog`, but `/blogz` incorrectly redirects me to `/en/blog`

**Comment by KalobTaulien** [comment]
This seems to be working for me. I changed my Firefox browser language to Spanish, created a redirect from /blogz to /blog/  (I didnt select the page, I manually wrote in the redirect), and it detects my locale and sends to me to /es/blog/ as expected.

Likewise opening a new private window using Spanish and going to localhost:8000/blog/ sends me to localhost:8000/es/blog/

And if I open a new private window, select a different language from the footer, it redirects me to the correct place. 

So either this is fixed, or I'm testing this incorrectly. 

@Pomax pinging you for confirmation I'm testing this accurately.

**Comment by KalobTaulien** [comment]
Update: This works as expected if you write the final URL by hand. If you select a page using the PageChooser it goes to a very specific page. I've asked Karl if this is intended behaviour or if the redirect using the PageChooser should be locale-aware.

**Comment by Pomax** [comment]
if this is intended behaviour we'll probably need to put some redirect-changing code in place similar to what we have for wagtail-modeltranslation in `master`

**Comment by KalobTaulien** [comment]
I had a quick conversation with Karl and Phil about this today. Something might get added into wagtail core like a BooleanField that would check for redirects. I'm also going to explore this a bit more today and play with different middleware locations to see what we can do.

**Comment by jamilasnell** [comment]
2 hours already spent on this, 4 in total spent on this issue

**Comment by Pomax** [comment]
It looks like the new wagtail-localize work is not affected by this. redirects correctly reapply the locale code.
