### ISSUE TITLE
[Publications] Feature Requests

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#6119]
Creating this ticket to track incoming feature requests related to the publications template.

- [x] Create a running google doc list (example: add features we want as we go through insights/TAI pub content)

**Comment by sabrinang** [comment]
Started a google doc here: https://docs.google.com/document/d/1fbqNREI4dhKMoSWHTej-w8cOnwokg4NcZLxovH8ipkY/edit?usp=sharing

**Comment by kristinashu** [comment]
@sabrinang would it be helpful to turn this into an epic?

**Comment by sabrinang** [comment]
+1 an epic makes sense as I'll file issues from this

**Comment by sabrinang** [comment]
In addition the the four issues filed for this epic, I created three tickets that were more QA related and tagged the older publication QA epic https://github.com/mozilla/foundation.mozilla.org/issues/5780 _(if they should be here instead I can relabel to move)_

**Comment by sabrinang** [comment]
Filed four more issues related to this epic from #5827 demo QA review.

**Comment by kristinashu** [comment]
I think this should be good to close? Even if a few small tickets come up or are remaining, the bulk of the work is done!

**Comment by sabrinang** [comment]
Yup the bulk of the requests are done! In the future if they trickle in they are tagged with `publications` or named [Publications] so these tickets are easy to find whether this epic is open or closed — so I am good to close.
