### ISSUE TITLE
[Data Futures Lab] Microsite Design Review

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#6122]
**Deadline:** early March. Asked Mehan to ping us once copy is stable enough to do a design review.
**UPDATE: got a ping on March 1st saying placeholder copy is there.**

**Background:**
https://foundation.mozilla.org/en/data-futures-lab/ is structured in the CMS (logged in users only). Now Mehan and team will populate it with content. Previous ticket here: #6076

**To do:**
- [x] Do a design review once content is in place (to check usability issues, opportunities to add illustrations/icons). 
- [x] Don't forget to reference the [Design Brief](https://docs.google.com/document/d/1wSQhaoDtxsC_qFtuwa-9l5M-LpOA_-XI5g5yBobrJa8/edit?usp=sharing) to make sure their main goals are easy to achieve on the site (once content is in place)
- [x] Gather feedback from the team. 
- [ ] Tweak the site if needed.

### Deadline:
Full site must be ready before MozFest (March 8th 2021)

**Comment by kristinashu** [comment]
@taisdesouzalessa what's the new deadline for this? Should it be move to next sprint or next next sprint?

**Comment by taisdesouzalessa** [comment]
I asked Mehan for an estimate and he will talk to the person who is writing the copy. Not sure about the exact deadline (all I know that this should be done before MozFest).

**Comment by taisdesouzalessa** [comment]
Got the date! Early March. Moving this to next sprint then.

From Mehan:
"Alix [the person who is writing the content] says she'll have a draft by next Friday. So maybe early March?"

**Comment by jamilasnell** [comment]
Talked to Mehan and he said that they'll have draft content in there by the end of this week (2/26)

**Comment by kristinashu** [comment]
Did they get the draft content in?

**Comment by taisdesouzalessa** [comment]
Yep! Mehan pinged me today the placeholder content is there. Removing the tag "blocked" from this ticket.

**Comment by taisdesouzalessa** [comment]
Added comments to Figma file: https://www.figma.com/file/AABYnCVDRDfyMSyyTYiGAH/URL-plan-Mozilla-Research?node-id=141%3A3 - I have lots of suggestions to improve the UX so sent a note to Mehan if we can talk about my suggestions and see what he thinks.

**Comment by taisdesouzalessa** [comment]
This is done and I sent a note to Mehan highlighting the work done: https://foundation.mozilla.org/en/data-futures-lab/learning/

I'll leave this ticket open because we need to collect feedback from the team and do tweaks if needed.

**Comment by taisdesouzalessa** [comment]
Talked to Mehan and he thinks if there are tweaks required, it will mostly be stuff he can handle himself.
Closing this ticket then. Will open a new one if any work is required from us.
