### ISSUE TITLE
[Insights Team Research + Data Futures Lab] Work intersections: feedback from teams 

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#6128]
**Background:**
Work started here: #6123 and the goal of this project is to successfully to connect Insights Team Research + Data Futures Lab in our site in a user-friendly way.

**To do:**
- [x] Collect feedback from Mehan and Kasia and align if needed ([feedback sheet here](https://docs.google.com/document/d/1bzD4TlLp1EhdjjiBkCc4W7cKmQpI72-x3tP9hhH7wLc/edit?usp=sharing))
- [x] Act on feedback
- [x] Connect with Becca to see what she thinks about adding the IA whitepaper into the Insights hub.
- [x] Implement changes in our site to reflect the thinking we did

**Comment by taisdesouzalessa** [comment]
This is a summary of what came up from our async discussion:
• Overall the flow works for both Mehan and Kasia.
• DFL is too big to fit into any of the existing categories like ‘awards’ or ‘fellowships’ so it makes sense to add it to "What we do" (connect leaders area)
• It makes sense to place the individual research from Insights team inside the “Learning” tab of DFL. **Consideration: see how it flows with other elements there like "Lab Reflections" and others on that page once we have the final copy.** 
 •  Link “What is Mozilla Insights” to the central Research tab in DFL “Learning” instead of listing both research pieces as links. - DONE and updated on [Figma flow mockup](https://www.figma.com/file/AABYnCVDRDfyMSyyTYiGAH/URL-plan-Mozilla-Research?node-id=0%3A1)
 • Consider using the text from the ”[Introduction](https://foundation.mozilla.org/en/initiatives/data-futures/)” as the intro text on the Data Future Lab “Research” tab
• Insights team may want to shift some publications (e.g. the content moderation and the privacy included could be seen as special editions of the IHR but it is to Eeva and Solana to decide).
• We may need to publish research (Insights team) before the Data Futures Lab website is published. Because we don't want Google to index the placeholder of DFL, my recommendation for the teams was to have the Insights publication on the "/inights/[name-of-publication]" URL for now and redirect it later (once we have the DFL hub). @kristinashu let me know your thoughts on it.

**Comment by kristinashu** [comment]
Everything sounds good Tais - including publishing under Insights, for now. Thanks for tackling this complicated issue!

**Comment by kristinashu** [comment]
Do you think this is good to close? You could open up individual tickets for any additional implementation work needed.

**Comment by taisdesouzalessa** [comment]
Yes. Follow up tickets: #6194 (implementation ticket) and #6196 (discussion on how to integrate other researchers into Insights Hub)
