### ISSUE TITLE
Set up subdomains for MozFest book and event booking platform

### ISSUE THREAD

**Issue by benhohner** [mozilla/foundation.mozilla.org#6149]
2 subdomains needed with A or CNAME records.
Will get further details about IPs

- [x] schedule.mozillafestival.org 
- [x] book.mozillafestival.org 
- [ ] Add book to nav
- [ ] Create task to remove sites 90 days after MozFest is over

DNS for mozfest in AWS Route 53

** Due **
Online preview for design, Feb 10
Deploy to MOzilla 20-22 Feb

**Comment by benhohner** [comment]
Still waiting on DNS info from Newcastle.
No word from HeyHey

**Comment by benhohner** [comment]
Waiting on Marc to provide feedback on nav

**Comment by benhohner** [comment]
@marcwalsh @sabrinang Can you provide feedback on where you'd like the book to be linked? I believe it's almost done being proofed

**Comment by jamilasnell** [comment]
Closing this ticket as it seems that the book is being shared ad hoc and there doesn't seem to be a need to add it to the nav.
