### ISSUE TITLE
Triage Dependency Upgrades

### ISSUE THREAD

**Issue by benhohner** [mozilla/foundation.mozilla.org#6150]
- [x] Create project with dependabot PRs
- [x] Triage current dependabot major/breaking version upgrade PRs
- [x] Create tickets totaling ~2 days worth of major version upgrades

**Comment by Pomax** [comment]
I've created https://github.com/mozilla/foundation.mozilla.org/projects/21 to help with this.

**Comment by mmmavis** [comment]
A little confused about what I should do for this ticket. @Pomax has kindly created the project board and added dependabot PRs to it. How do we wanna triage major version update PRs? Do we create another column on the project board?

**Comment by mmmavis** [comment]
Done. I've merged all non-breaking dependabot PRs and created corresponding tickets for the rest (#6265 to #6269). Project board has been updated as well: https://github.com/mozilla/foundation.mozilla.org/projects/21
