### ISSUE TITLE
[Publications] Interactive Data Visualizations (wagtail embed)

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#6151]
Insights team would want to include interactive images/visualizations, figure out design needs how we can integrate those on Wagtail pages.

- also look into existing solutions (tableau)

**Comment by sabrinang** [comment]
**Custom data visualizations notes:**
- currently done by contractor Christian
- custom code included in wordpress; code to control front-end and .csv files for data input 
- dev team may need to be involved to resolve where data is hosted, figure out flexible html embed etc.
___________________
**Third-party data visualization service ideas:**
- Tableau _(https://dataviz.mozilla.org/ used by other MoCo teams)_
- Kumu.io _(https://kumu.io/JvanGeuns/decision-tree-2a58 seen data future insights team use this)_
- DataWrapper _(https://www.datawrapper.de/)_
- RAWGraphs _(https://rawgraphs.io/)_
___________________
**Embed design ideas:**
- publication pages: 
   - we can use similar images size on publication pages but the embeds should include attribution/citation or data source link option beneath it
   - the wide image (full view port width may be a bit too big proportionately if graph is tall)
- other wagtail pages (may be out of scope for this ticket): 
  - we can use similar image size on banner pages but the embeds should include attribution/citation or data source link option beneath it
  - we can introduce another size that is the same width as the content container to be a bit larger
<img width="927" alt="image" src="https://user-images.githubusercontent.com/2492510/106679535-be19be00-6571-11eb-81b8-f66d5eaf017b.png">

___________________

**Upcoming data visualizations examples**
- there is also a variety from network pie chart graph, lollipop chart, sunburst slice chart etc.
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/2492510/106681163-ccb5a480-6574-11eb-82f2-32956fcabfc9.png">
<img width="1441" alt="image" src="https://user-images.githubusercontent.com/2492510/106681130-bdcef200-6574-11eb-8057-8434ca4032db.png">
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/2492510/106681174-d63f0c80-6574-11eb-9b46-64bbb2afbbfe.png">

**Comment by kristinashu** [comment]
Thanks for this @sabrinang! One other upcoming use case is for a [series of blog posts via Jon](https://docs.google.com/document/d/1Dzb3Hw3TDL9gz_REfTzhHw7duc8AGA5QU-5QJkmOClw/edit). I think we should find something that works for publications, blogs, and our other standard wagtail templates. And a big +1 to making the component a wider width!

cc @mmmavis

**Comment by mmmavis** [comment]
Thanks for the detailed notes, @sabrinang .

Do we know what we want to allow CMS users to embed? Is it
- a component that allows users to drop in any script / code into CMS page?
- an embed of third party tool (where the data viz is hosted on that platform and Wagtail is only responsible of embedding it)?

**Comment by sabrinang** [comment]
@mmmavis My assumption is that staff would want to visualize data files _(like .csv from a spreadsheet)_ but I actually haven’t seen what the data sources they use. I think we want it to be as accessible for staff as possible so that we won’t need devs to hand hold them to create specific custom scripts/code in order to use data visualizations in the CMS each time. 

- If there is a component where staff can input their data file format and can create data visualizations from the CMS directly that would work but I assume their would be many limitations within wagtail as data visualizations are pretty specific
- Embedding a third party data viz platform _(where staff is responsible for creating their data viz outside of wagtail)_ I believe would give them tools to what they need to make the data viz themselves and yes Wagtail would only need to whitelist it and ensure it is embeddable.
- I'm also assuming that a third party platform won't require staff needing coding skills but sort of wysiwig customizable editor to manipulate their data to create a variety of data viz styles to suit their needs _(note: I have not personally used any of the third party services I mentioned)_

**Comment by kristinashu** [comment]
Can this be closed now that you have this ticket https://github.com/mozilla/foundation.mozilla.org/issues/6192?

**Comment by sabrinang** [comment]
👍 Yes, go to close — will continue on #6192's gdoc.
