### ISSUE TITLE
[IA Refresh] Measuring success: part IV-a

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#6157]
**Background:**
According to our [Foundation Site Information Architecture](https://docs.google.com/presentation/d/19etCN1uGLcLmB50-uV-srsWKEAhlwlR_bc0dLE1uW1g/edit?usp=sharing) document, those were the 4 areas we want to focus to assess the success of our IA refresh initiative:

1. Reduce the bounce rate on our homepage by 20% through site updates based on user testing, analytics, and staff interviews
2. Qualitative testing finds that users’ understanding of Mozilla Foundation’s mission improves by 25% (conduct baseline/control test along with prototypes in April)
3. Qualitative testing finds that staff can more easily find the content they are looking for compared to initial IA audience report
4. Behaviour in Google Analytics shows users going to a diverse set of pages

**To do:**
- [x] Update the part I - #5706 research with current analytics numbers and further insights if any, since we have collected more information about traffic at this point.
- [x] Do a table with "research question","answer" and "recommendations" (part I - #5706, partII - #5711 and part III - #5775 ), compiling the results of the 3 research materials into one. Focus on the 4 items above + any other relevant items we think it deserves our attention and action.

**Comment by nancyt1** [comment]
Started the [doc](https://docs.google.com/document/d/12Lk9ObtT7robD76gPUDGiDW1LeFMtfM5zX6JnIlwfF0/edit?usp=sharing) to compile the results of all our research.

**Comment by kristinashu** [comment]
Ooops! We missed this during sprint planning. @taisdesouzalessa can you please re-estimate on this?

**Comment by taisdesouzalessa** [comment]
done

**Comment by taisdesouzalessa** [comment]
Updated the part IV ticket to reflect what needs to be done still. Just finished reviewing the analytics so closing this ticket.
