### ISSUE TITLE
[PNI] update About page for valentine's day release

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6160]
Some changes to the "why we made this page" about page (`buyersguide/templates/about/why_we_made.html`) need to be made in preparation for the vday release of the buyers guide.

**Comment by caltrider** [comment]
@pomax The two graphs that need updating on the "Why We Made This Guide" page in the About section are highlighted in this doc https://docs.google.com/document/d/12ImD2VM53xww_S-zNNcd7tX9eFYsr-CERZ686njcL4k/edit
