### ISSUE TITLE
[Publications] Article Child Page Alignment on Table of Contents

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#6171]
Originally we had section numbers included in the table of contents but this conflicted with the numbering of the long-form content structure itself so we removed them. The spacing indent remained but this can be a cleaner visual line if we left aligned it with the publication parent heading.

For example:
<img width="893" alt="image" src="https://user-images.githubusercontent.com/2492510/106981752-73d24180-6717-11eb-9d61-300a9de74a01.png">

may be related to https://github.com/mozilla/foundation.mozilla.org/issues/5846

**Comment by mmmavis** [comment]
@sabrinang it seems like numbering shows up on smaller screen size. What should we do with it? 
<img width="443" alt="image" src="https://user-images.githubusercontent.com/2896608/108919632-32330900-75e8-11eb-9aab-440048d6a985.png">

**Comment by sabrinang** [comment]
Good catch @mmmavis remove numbers and align to edge
