### ISSUE TITLE
[What you can do] Hero banner for MozFest

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#6173]
Create a hero banner for MozFest since we plan to place it into the "What we can do" hero section advertising that tickets are on sale.

**Deadline:** Feb 9

**Comment by taisdesouzalessa** [comment]
Sent do design review for feedback. Copy is placeholder (from other initiative)
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/22157921/107101260-99208780-67cb-11eb-9812-4bbca69e97cf.png">

**Comment by kristinashu** [comment]
Did you get feedback on this?

**Comment by taisdesouzalessa** [comment]
oh yeah! done and launched. Sorry, forgot to close this ticket.
