### ISSUE TITLE
Find a permanent solution for wagtail-inventory

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6184]
We had to write some emergency code to deal with `wagtail-inventory` database records duplication over in https://github.com/mozilla/foundation.mozilla.org/issues/6162, where the solution was to create a temporary fork of `wagtail-inventory` with a code patch applied to its `helper.py`:

```python
def create_page_inventory(page):
    page_blocks = get_page_blocks(page)

    # return [
    #     PageBlock.objects.get_or_create(page=page, block=block)[0]
    #     for block in page_blocks
    # ]

    list = []

    for block in page_blocks:
        bindings = PageBlock.objects.filter(page=page, block=block)

        if bindings.count() > 0:
            list.append(bindings.first())
            for index, entry in enumerate(bindings):
                if index > 0:
                    entry.delete()
        else:
            result = PageBlock.objects.create(page=page, block=block)
            list.append(result)

    return list
```

However, we should find a long term solution for this patch because we don't want to be maintaining that code, ideally `wagtail-inventory` can detect and fix this problem itself in a next version so we can simply update our dependency to "at least that version".

**Comment by Pomax** [comment]
cross reference: https://github.com/cfpb/wagtail-inventory/issues/43

**Comment by benhohner** [comment]
File a PR upstream with fix, @KalobTaulien to ping wagtail core dev to accept PR

**Comment by KalobTaulien** [comment]
The PR to wagtail-inventory needs to pass CI first (https://github.com/cfpb/wagtail-inventory/pull/44). Once it passes CI, I'll ask Andy or Scott at CFPB to review it and maybe do a version bump soon. For now I'm going to put this ticket into blocked.

**Comment by Pomax** [comment]
blocked on CI apparently being broken over on wagtailinventory =(

**Comment by Scotchester** [comment]
Hey all, something seems to have gone bad with our connection to Coveralls. Will try to look at it soon!

**Comment by Pomax** [comment]
wagtail-inventory was updated with code and a migration that deduplicates duplicated entries, and adds a unique constraint to the table so that duplication (should be) impossible in the future. Closing this issue pending an update for wagtail inventory, https://github.com/mozilla/foundation.mozilla.org/issues/6624
