### ISSUE TITLE
PNI: Change intro header text to white/ create wagtail option to toggle header text color between white or black

### ISSUE THREAD

**Issue by natalieworth** [mozilla/foundation.mozilla.org#6185]
### Intro
Design was wanting to use a dark banner background ([example here](https://redpen.io/ae85ad031250988f84)) but currently the text is black in the banner area. We were wanting to update the text to white.

If it's also possible, adding a wagtail option for the header area text to black or white would be ideal (but let me know if you want me to open a separate ticket for that or if it's too much to do in this sprint since this is last minute).

cc @Pomax I estimated a 2 but let me know if that's too little. Thank you so much! :)

**Comment by Pomax** [comment]
nah, this will only take a few minutes =)
