### ISSUE TITLE
Update Video component hint text to include Vimeo

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#6191]
Now that we allow Vimeo embeds (as well as YouTube) we need to update the hint text so staff know which format the url embed needs to be.

Screen cap from PR
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/1068783/107418342-61675780-6acb-11eb-922f-8dd47487293a.png">

**Comment by mmmavis** [comment]
Was gonna work on this ticket but I realized I didn't have a sample Vimeo embed URL I could include in the help text. It seems like we don't have an official account on Vimeo. 🤔 Gonnna mark this ticket as blocked and will bring up this q on Slack for help when I'm back from PTO.

**Comment by jamilasnell** [comment]
Please put an estimate on this ticket when you can @mmmavis

**Comment by mmmavis** [comment]
I'm just gonna use the one Kristina put in the screencap: https://vimeo.com/9004979
