### ISSUE TITLE
Create Data Visualization Brief / Planning Doc

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#6192]
Let's capture context and findings so far in a centralized doc for reference. Create a google doc brief that can help with planning and that we can share with members of the team for their expertise and input (like Jackie, stakholders, dev etc.)

**Comment by sabrinang** [comment]
We will use a google doc https://docs.google.com/document/d/1ySaJMH4mWxgZLqt7PvdVeNdS-IHekfKBYLF-ZSI9Nk4/edit?usp=sharing for this brief and planning work

**Comment by sabrinang** [comment]
Mavis and I finished writing the data viz planning doc here: https://docs.google.com/document/d/1ySaJMH4mWxgZLqt7PvdVeNdS-IHekfKBYLF-ZSI9Nk4/edit?usp=sharing

@kristinashu @benhohner @Pomax please review the doc and leave any feedback for us.

**Comment by kristinashu** [comment]
Amazing doc! Also adding @KalobTaulien to this so he can review and add feedback.

**Comment by Pomax** [comment]
added us as assignee so we don't lose this issue =)

**Comment by benhohner** [comment]
Doc is amazing. Thanks everyone! Any recommendations for next steps @mmmavis @sabrinang ?

**Comment by jamilasnell** [comment]
We will discuss this when Mavis and Sabrina are back week of April 5th

**Comment by sabrinang** [comment]
Chatted with Mavis today and scheduled a quick discussion tomorrow (Ben/Kristina/Mavis) to finalize next steps to wrap up this planning ticket.

**Comment by sabrinang** [comment]
After our discussion today, I've filed two follow up issues to continue the work:
- [Data Visualization] Stakeholder Needs Assessment #6524
   - to better understand staff needs and demand to create data viz on the foundation site
- [Data Visualization] Document Guidelines for Custom Graphics #6525
   - to capture the custom graphic solution and best practices we use 

We'll continue to use the planning doc to capture notes and findings. Next week's planning meeting will help prioritize this along other foundation site work too.
