### ISSUE TITLE
[Insights Team Research + Data Futures Lab] Copy considerations and implementation

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#6194]
From the conversation on this ticket (#6128), those issues surfaced:

• It makes sense to place the individual research from Insights team inside the “Learning” tab of DFL. Consideration: see how it flows with other elements there like "Lab Reflections" and others on that page once we have the final copy. DEPENDENCY: DFL final copy
• Consider using the text from the ”Introduction” as the intro text on the Data Future Lab “Research” tab DEPENDENCY: DFL final copy

**To do:**
- [x] Once we have the final version of the DFL copy, make sure the considerations above are made
- [ ] Do the changes proposed on [this flow](https://www.figma.com/file/AABYnCVDRDfyMSyyTYiGAH/URL-plan-Mozilla-Research?node-id=0%3A1) in the live site

**Comment by jamilasnell** [comment]
"The Data Futures part will be moved this week (first part) so we can plug it into the Data futures Lab website that will be launched at Mozfest. And then the second part will be probably moved in the week of the 15th so we can launch on March 24."

**Comment by taisdesouzalessa** [comment]
@jamilasnell moving this one back to March 15th because this ticket isn't related to the Insights Team project we discussed. This is a ticket for the work with the Data Futures Lab :). Just 2 considerations so I don't forget.

**Comment by taisdesouzalessa** [comment]
Applied the following changes from the flow:
1. "[What we do](https://foundation.mozilla.org/en/what-we-do/)" page now has an entry point to DFL
2. "Creating Trustworthy AI" in inside [Mozilla Insights](https://foundation.mozilla.org/en/insights/)
3. "[Data for Empowerment](https://foundation.mozilla.org/en/data-futures-lab/data-for-empowerment/)" is inside Data Futures Lab Hub - URL: `https://foundation.mozilla.org/en/data-futures-lab/data-for-empowerment/`

We will have to figure out how to reference the DFL in the Insights Hub. It would be good to have their second research launched so we think about the flow considering those 2 researches. I'll add a note to the ticket  #6132 for now but it may become its own ticket later on.
