### ISSUE TITLE
[Insights Team] Hub expansion

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#6196]
**Background:**
From the conversation [in this doc ](https://docs.google.com/document/d/1bzD4TlLp1EhdjjiBkCc4W7cKmQpI72-x3tP9hhH7wLc/edit?usp=sharing)(and proposed flow) a challenge emerged: how might we expand the [Insights Hub](https://foundation.mozilla.org/en/insights/) to accommodate research of other teams? From the audience's perspective, it makes sense to host all research in one place. We want to add the "Trustworthy AI" whitepaper in the hub but having the tab "Meet the team" doesn't make sense since it includes only Insights Team members.

**Considerations and some ideas:**
From Insights Team: 
They do more than the IHR, and the IHR Hub is really hidden.They think the team deserves to be featured more prominently. How about adding other researches to their team and explaining in their Pulse bio that they are working for other teams?

We could add "The Insights team is part of Mozilla's Global Programs unit. Some research featured under "Publications" is done by researchers from other teams" and we add other researchers so they are represented.  They are open to other solutions but as long as this is still their Hub they think it makes sense for their team to be featured on the page.

From Design team: maybe move away from "Team" and categorize people as Contributors?

**To do:**
- [x] Come up with a plan/ sketches and present them to Kristina
- [x] Show Insights team and Becca (as representative of Trustworthy AI paper)

**Comment by taisdesouzalessa** [comment]
@kristinashu this is my proposal on staging:
https://foundation.mofostaging.net/en/insights/team/
Please let me know what you think.

This is a temporary solution until we have an internal alignment on what research means at Mozilla and how we display it in our properties (discussion happening between Becca and other researchers).

For now I propose we add:
1. a broad explanation of the current state of research at Mozilla (open to copy refinement): "At Mozilla, research is done by people from a variety of teams. Here we highlight all the individuals that have contributed to our original research."
2. Clarity on where the Insights team seat: "The Insights team is part of Mozilla's Global Programs unit."
3. Clarity on "Creating Trustworthy AI" white paper authors: Becca and Mark - **NOTE:** Becca has to update her Pulse profile and Mark has to create one.
4. Clarity on "Creating Trustworthy AI" white paper contributors (added at the end of the page).

**Comment by kristinashu** [comment]
Thanks @taisdesouzalessa! Yes, I think this works as a temporary solution.

**Comment by taisdesouzalessa** [comment]
Send a Slack message to Kasia and Becca seeking alignment. Once we are on the same page I can then open an implementation ticket.

**Comment by taisdesouzalessa** [comment]
We're almost there. Kasia and Becca are aligned and I am just waiting for Solana to update her Pulse profile so we can update these pages.

**Comment by kristinashu** [comment]
🙌

**Comment by taisdesouzalessa** [comment]
Pages are now updated!
• Trustworthy AI white paper is now in the [Overview page](https://foundation.mozilla.org/en/insights/) of the Insights Hub
• It is also in the [Publications page](https://foundation.mozilla.org/en/insights/publications/) of the Insights Hub
• Finally, we solved the "teams" issue by adding the team each member belong to in their Pulse profile - thanks for the suggestion, Kasia! See the "[Meet the team](https://foundation.mozilla.org/en/insights/team/)" page.
