### ISSUE TITLE
[PNI] Evergreen graphics

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#6201]
After our v-day push we will need to update the site graphics to be more evergreen.

Todo
- [x] Determine the art direction (with input from Jen, Audrey, Lindsay)
- [x] Create hero banner
- [x] General share image
- [ ] Bonus: custom share images for each category

**Comment by natalieworth** [comment]
Evergreen [graphic direction](https://redpen.io/p/zgc8e9d09d7a000638) is started here for 2021

**Comment by natalieworth** [comment]
I updated the final designs for the banner and the [share image using inspiration](https://redpen.io/p/zgc8e9d09d7a000638) from the contractor assets and Audrey, Jen, and Lindsay preferred the more simpler banner option with the purple gradient over the 3-D images.

[Final images and working files are in here](https://drive.google.com/open?id=13_UsKqX_3z629tM3sEE-zY13thQlpVOv&authuser=natalie%40mozillafoundation.org&usp=drive_fs)
