### ISSUE TITLE
SPIKE: allow wider image and iframe blocks on publications and blogs

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#6204]
A stakeholder mentioned the desire for wider but not full-width container to allow more readable/impactful images and interactive graphics. Let's chat and see if it's something we wanna support, and if so, how?

Publication template already supports this but the implementation wasn't ideal. I will drop in more info after I check out the code myself.

/cc @kristinashu @sabrinang

**Comment by mmmavis** [comment]
We'll schedule a meeting to chat about this once this ticket has been triaged.

**Comment by benhohner** [comment]
Related to #6275

**Comment by jamilasnell** [comment]
Mavis will talk to Kristina and Sabrina and make time for a chat

**Comment by mmmavis** [comment]
@kristinashu I'm wondering what the specs for this image block would be. i.e., how wide the image container should be? mockups? what CMS page types do we wanna enable this new block on ... etc.

**Comment by kristinashu** [comment]
What is the scope for this? It seems like at the very least we want this for the new data visualization component - the more refined specs might come out of https://github.com/mozilla/foundation.mozilla.org/issues/6192. My assumption is that the image container would either match the Publications version of "wide" or the version of "wide" used on all our other templates. Design would need time to mock this up.

If we're expanding this to a larger scope then ideally _make it full-width_ would be option for all our components (with the exception of the text component, for better legibility). Ideally design would have the time to mock this up as well before implementing.

@sabrinang feel free to chime in with your thoughts as well!

**Comment by mmmavis** [comment]
I'm unsure about the scope of this ticket. I think this was emerged from another convo (which I couldn't recall what now) so I created this placeholder ticket.

From implementation point of view, ideally we would want things to stay within the Bootstrap container so we don't have to come up with hacky way to make wide images to work (like the ones on Publication pages). I'm opposed to making most components available "full width" (breaking out of the Boostrap container) as 1) it requires quite a bit of rewrite and in most cases, with hacky solution 2) it defeats the purposes of using Bootstrap grid 😬

**Comment by kristinashu** [comment]
Sorry I think I used the wrong terminology. I wasn't proposing to break away from our existing grid. By "full width" I actually meant "full-width container". 

For example, right now we have the "Narrowed page content" checkbox. I'm assuming "full-width container" means the components would look as they do when that box is not checked.  

<img width="955" alt="image" src="https://user-images.githubusercontent.com/1068783/109857593-b51f1980-7c0f-11eb-90e3-69d98c6fb862.png">

Right now this narrow vs wide is only available at a page level i.e all the content is either narrow or wide. This is not ideal because we want body copy to be narrow so that is more legible. But then we want things like graphs and cards to be wide so we can have bigger visuals are a better use of space. So ideally, the narrow vs wide could be controlled at a component level rather than just the page level, as it is now.

Quick example:
<img width="813" alt="image" src="https://user-images.githubusercontent.com/1068783/109857498-9d479580-7c0f-11eb-8102-852210eead4e.png">

**Comment by mmmavis** [comment]
Got it. Thanks for the helpful annotated screenshot. Glad we are not hoping to break Bootstrap container on most pages 😂 

However, we'll still need to do a thorough audit on all blocks and page types as implementation can be different in each combined scenario. For example, for "narrow width page", we implemented it so that everything in the main body section is contained in a 8-column `div`. If we wanna make any block wider (like the Pulse directory block), we'll need to make it "break" the 8-column `div`, and therefore it will require a certain degree of code rewrite to the template and styling side of things, along with adding additional "wider block" field (checkbox) to those streamblocks.

Can we start by prioritizing what blocks and page types we wanna tackle first?

**Comment by kristinashu** [comment]
Thanks Mavis! Would you have time to create a spreadsheet to audit all the possible combinations of components and templates? Then we can do through it all together and decide the widths for each.

I think the priorities are the iFrame and future graph embed component. Followed by Recent blog entries and Profile by id.

Priority for templates would be Publications and Blog pages. Followed by Bannered and Default template.

**Comment by mmmavis** [comment]
Bumped up the estimate to 4 as this ticket requires research/audit + implementation.

**Comment by benhohner** [comment]
This ticket is now for the audit.

We need wider, but still within bootstrap's constraints on page types:
- publications
- blogs

content types needed:
- image
- iframe

**Comment by mmmavis** [comment]
I'm aiming to have a solution that doesn't require us to rewrite all our page/block template code.

### Blog page

We should be able to allow full-Bootstrap-container-width `image` and `iframe` with minor code changes to only the blog page template itself along with CSS code targeting elements on the blog page. One thing we'll have to compromise -- we won't be able to have sticky side share buttons anymore. We can still make them sit at page top but they won't be sticky. This is due to the template code changes.

Tech approach:
- make the blog main content wrapper full width (12-column) instead of 8-column
- use CSS to add `max-width: 66.7%` and `margin: 0 auto` to all streamblocks so they can only appear 8-column wide and center aligned (same as now)
- use CSS to allow **full-Bootstrap-container-width** `image` and `iframe` to have `max-width: 100%`
- (depending on what we wanna do with side share buttons) alter the code in template & CSS


### Publication page (I'm guessing we mean **Article Page** and not **Publication Pages**???)

The existing `iframe` block already shows up the same width as the "full width" `image`. If we are thinking about allowing the iframe to expand **full page wide**, we should just create a new streamblock (similar to what we did for the [`Article Page's WideImage`](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templates/wagtailpages/blocks/article_full_width_image_block.html), which shouldn't be tricky.

**Comment by mmmavis** [comment]
@kristinashu @benhohner ^^

**Comment by mmmavis** [comment]
Done. Closing.

Follow-up SPIKE ticket https://github.com/mozilla/foundation.mozilla.org/issues/6517
Relevant discussion: https://github.com/mozilla/foundation.mozilla.org/pull/6471
