### ISSUE TITLE
[Publications] Caption/Alt Text for Images in Content Component

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#6209]
For full width/hq, left-aligned, right-aligned images in the content component, can we include AltText, Caption and CaptionURL fields _(similarly to image component on default wagtail pages)_.

**Comment by KalobTaulien** [comment]
Alt text is already provided when you select an image to upload. 
![image](https://user-images.githubusercontent.com/4743971/109204981-3d5e7400-7763-11eb-9e24-2ca862354b31.png)

But captions are not supported. We'd need to overhaul our Image model and use a custom image model, which is a bit of a pain to do. And we'd need to overwrite the wagtail `|richtext` filter that works some magic to convert `<img>` to `<picture>` elements, with a caption in it. That cascades into some CSS work and database migrations as well. So unless this is a vital feature, we might want to stick with 2x or wide images. 

Alternatively, we could look into a "floating" or "full width" image block with a caption that you can place between two richtext sections. Let's talk about this one @sabrinang

**Comment by sabrinang** [comment]
Note: We chatted on slack and looks like we would create a new image block _(like full width/hq)_ that can have the caption option so we don't have to overwrite core features

**Comment by KalobTaulien** [comment]
Note: I asked the wagtail core team what they think and they agree that we should create a new image block instead of overwriting the images in the richtext field. I'm going to close this ticket in favour of #6275
