### ISSUE TITLE
[Analytics] Getting oriented with analytics as a team: activities

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#6211]
**Background:**
Now that [we have the major themes](https://docs.google.com/document/d/11HMrN2BOdy_IGy_93QczdBpwqSDfx-EYCqzssW2kpQw/edit?usp=sharing) based on Production team feedback, it is time to plan the activities we can do.

**To do:**
- [x] Taís, Ben and Jackie to add suggestions [to the document](https://docs.google.com/document/d/11HMrN2BOdy_IGy_93QczdBpwqSDfx-EYCqzssW2kpQw/edit?usp=sharing)
- [x] Implement activities

cc: @benhohner @kristinashu

**Comment by taisdesouzalessa** [comment]
Added suggestions based on themes I found. Pinged Jackie and Ben to the doc to brainstorm ideas together.

**Comment by jamilasnell** [comment]
Putting this as blocked as further action depends on Ben and Jackie's schedule

**Comment by benhohner** [comment]
Document looks great to me.

**Comment by taisdesouzalessa** [comment]
@benhohner next step is to do one initiative. My suggestion is we do:

**• A brown bag with the theme Google Analytics 101, using one of our initiatives as an example (maybe PNI)?**

Let's plan this together? I'll create a ticket for that.

**Comment by taisdesouzalessa** [comment]
Ticket for activity created: #6246

Closing this once since data analysis is done and next steps are suggested.
