### ISSUE TITLE
Interim interactive graphic host and embed in iframe

### ISSUE THREAD

**Issue by benhohner** [mozilla/foundation.mozilla.org#6223]
### Describe the feature request
Until we develop a permanent solution to embedding raw HTML, we'll need to host interactive graphics on our S3 and embed them as iframes.
We'll need to create the S3 bucket infrastructure anyway, in case we need to host additional files with the raw HTML embeds.

* [x] add an iframe component to the publications template - https://github.com/mozilla/foundation.mozilla.org/pull/6258
* [x] create a new private repo for user generated content: https://github.com/MozillaFoundation/mofo-infographics
* [x] create a bucket in S3 with a folder for each project (Tom)
* [x] validate files and upload files to repo
* [x] create github actions to publish files to S3
* [x] create bugzilla ticket for Rapid Risk Analysis (https://infosec.mozilla.org/guidelines/risk/rapid_risk_assessment) - https://bugzilla.mozilla.org/show_bug.cgi?id=1695019
* [x] look into vanity domain (Tom) (stretch goal) (Current URL: https://mofo-infographics.s3.amazonaws.com/  either make sure S3 role is secure or connect to cloudfront or connect vanity domain)
* [x] Link to files in S3 (may need to update CSP)
* [x] verify graphic is working correctly on desktop and mobile

### Additional context
* There will be 2 interactive graphics that will be launching on the 24th and March 1st, both developed by Christian Laesser, who we can bring in for a meeting if necessary.
* Inside the graphics there is JS code to detect the size of the graphic and resize the graphic to fill the available space.

**Comment by benhohner** [comment]
*beta* files to test system:

[https://app.zenhub.com/files/76596293/8b53185c-c0a2-4db5-868f-8e96f0890639/download](https://app.zenhub.com/files/76596293/8b53185c-c0a2-4db5-868f-8e96f0890639/download)

[https://app.zenhub.com/files/76596293/bbf5a8bc-dfec-4ae9-aed1-e8670f08ce23/download](https://app.zenhub.com/files/76596293/bbf5a8bc-dfec-4ae9-aed1-e8670f08ce23/download)

**Comment by Pomax** [comment]
Note: we will need to get the original source dir so _we_ can vet the code properly, and then run the build ourselves instead so that we can control the code that gets bundled in. We won't be able to accept pre-bundled/minified single .js files

**Comment by Pomax** [comment]
I've set up a test page over on https://foundation.mofostaging.net/en/insights/iframe-test-publication/iframe-article/ but it's currently simply pointing to the base bucket location, which means it's only serving the "you don't have access to this" page =)

Did we put any content up on AWS already for testing purposes? If so we can update the iframe URL on https://foundation.mofostaging.net/cms/pages/1937/edit/ and we should see things working.

**Comment by jamilasnell** [comment]
60% already done coming into March 15th sprint

**Comment by Pomax** [comment]
@benhohner turns out that we can't use the private repo for this: private repos are plan based, and we don't have a plan with github actions enabled. We could make the sync happen based on a dir in the foundation repo instead, with the github action set to monitor that particular dir for changes in order to kick off an s3 sync?

**Comment by benhohner** [comment]
Made repo public.

**Comment by Pomax** [comment]
@benhohner  in terms of `validate files`, do we want to run things through linters, too, to make sure that in addition to "safe" it's also "correct"?

**Comment by Pomax** [comment]
Test pages:

- https://foundation.mofostaging.net/en/insights/iframe-test-publication/iframe-article/
- https://foundation.mofostaging.net/en/insights/iframe-test-publication/iframe-article-graphics/

**Comment by Pomax** [comment]
For mobile views, the graphics code itself probably needs massaging, because even at full-device-width this would not look good:

![image](https://user-images.githubusercontent.com/177243/109862300-23b2a600-7c15-11eb-8d3f-c3c57da1a6e6.png)
