### ISSUE TITLE
[Analytics] Production team activity

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#6246]
From our [Production Team Survey](https://docs.google.com/document/d/11HMrN2BOdy_IGy_93QczdBpwqSDfx-EYCqzssW2kpQw/edit?usp=sharing) we learned that

The majority of people (6 or 7 out of 9) already:
• Understand Time on Page, Bounce Rate, Sessions, and Pageviews (7/9)
• Know how to figure out where our visitors are geographically located (7/9)
• Know how to check how many people visited a particular page (6/9)

The first step on getting oriented as a team is to have a **basic level analytics brown bag** to put everybody on the same level.

**To do:**
- [ ] Draft session
- [ ] Schedule a 30-45min call with Production team. Presenters: Taís/Ben/others?
- [ ] Have a feedback sheet post-session. Also ask participants what they would like to do next: working groups/ shared analytics resources?

@jamilasnell I put the milestone March 15 but maybe it fits into the following sprint due to MozFest?

**Comment by jamilasnell** [comment]
Moving to after MozFest

**Comment by taisdesouzalessa** [comment]
From Ben: "I can definitely be a resource for Analytics in the org, but I think once you're gone, the next best person to lead the initiative would be Jackie and her team. I already chatted with her about the possibility of getting some external experts in to give us presentations". Closing this ticket but tagging @benhohner so he has access to the survey results for future plans.
