### ISSUE TITLE
Advanced Publication Table Block

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6250]
We need a more advanced table block that can hold information such as:

- [x] Links 
- [x] Lists 
- [x] Centering text in a cell 
- [x] Bold 
- [x] Italics 

Other features it will need are:

- [ ] Merging cells left and right 
- [ ] Merge cells top and bottom
- [x] Heading styling (first row and left column)
- [ ] ~Accessibility title~ (same as below)
- [x] Optional table caption (richtext)

**Comment by jamilasnell** [comment]
@sabrinang is this something that needs to be done this sprint? Or can we push this back to the next one?

**Comment by sabrinang** [comment]
@jamilasnell  Some of the content that I’ve seen from data futures lab gdocs had tables originally has hyperlinks in them and the simple table https://foundation.mozilla.org/en/data-futures-lab/data-for-empowerment/alternative-data-governance-approaches-global-landscape-scan-and-analysis/preface/ currently doesn’t have them. That team hasn’t flagged this as I was the one that put the content in but I assume when they promote these docs it'd be good to have hyperlinks to be available but I don’t know how urgent it is as I haven’t heard back or reached out to that team regarding that publication in general.
