### ISSUE TITLE
Airtable Block Update

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#6256]
from discussion https://github.com/mozilla/foundation.mozilla.org/pull/6254

- include in help text that height is in pixels
- I also noticed the bottom margin may be a bit narrower and can give it a bit more to balance this out before next block starts

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/2492510/109196168-38dc9000-7750-11eb-97b7-7a452f42611b.png">

- [ ] add help text for block height field
-  [ ] add bottom margin to airtable block

**Comment by mmmavis** [comment]
@sabrinang can you provide copy for the help text and bottom margin for this block?

**Comment by sabrinang** [comment]
Help text: 
`The pixel height on desktop view, usually copied from the Airtable embed code`

Bottom margin:
I think typically there is a 24px bottom margin to give some separatioin

**Comment by benhohner** [comment]
@mmmavis to pair with Daniel on this
