### ISSUE TITLE
[Wagtail] Delete "Privacy Included: Rethinking the Smart Home" from the CMS

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#6264]
**Background:**
We created a new page for "Privacy Included: Rethinking the Smart Home" (see ticket #6108). 
This is the new URL: https://foundation.mozilla.org/insights/privacy-included/

**To do:**
- [x] Follow up with Tais' permissions
- [x] Delete the previous version of the same page (current in Wagtail). Page is already unpublished (and redirect is done) but I don't have the permission to delete it.

Path: Homepage > Privacy Included: Rethinking the Smart Home
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/22157921/109359828-fd6ac000-783a-11eb-99a3-cf6966b08091.png">

cc: @jamilasnell for triage

**Comment by benhohner** [comment]
@taisdesouzalessa I granted you admin permissions. Can you try deleting now?

**Comment by taisdesouzalessa** [comment]
Yes! Done. Thanks, Ben!
