### ISSUE TITLE
Bumps eslint-config-prettier from 7.2.0 to 8.1.0.

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#6265]
Dependabot PR: #6252

**Comment by lydell** [comment]
Alternatively, you might be able to remove eslint-config-prettier altogether. You seem to [_only_ extend `"prettier"`](https://github.com/mozilla/foundation.mozilla.org/blob/537c3514096942e75cba8fde29c5b5ad7cb892d2/.eslintrc.json#L3), so it doesn’t make a difference.

**Comment by mmmavis** [comment]
@lydell nice! Thanks for the helpful info!
