### ISSUE TITLE
Bump browserslist from 4.16.1 to 4.16.3

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#6268]
Dependabot PR: #6133

**Comment by mmmavis** [comment]
We need the PR to stay open due to [reasons](https://github.com/mozilla/foundation.mozilla.org/pull/6133#issue-565049881). 

Removing myself as assignee as there's no action for me to take. :)

**Comment by jamilasnell** [comment]
Closing this ticket per Mavis's comment above
