### ISSUE TITLE
Make the title in "Recent blog entries" component an optional field

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#6279]
Currently the title field is required but sometimes the blog posts are self explanatory and I title is not needed.

- [x] Make the "Title" field an optional field 

Screen cap from prod:
<img width="763" alt="image" src="https://user-images.githubusercontent.com/1068783/109539434-2c20aa80-7a76-11eb-8fe6-174e9ced2d54.png">

cc @benhohner

**Comment by benhohner** [comment]
@pomax to pair with Daniel on

**Comment by alihaiderrizvi** [comment]
I'd like to work on this issue. Could you give me some pointers on where to get started? Thanks!
