### ISSUE TITLE
Add Link to MozFest Schedule on Top Nav of MozFest Website

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/foundation.mozilla.org#6282]
Could the top nav of mozillafestival.org be updated to add a link to the MozFest Schedule?

The title should be 'Schedule' and links to schedule.mozillafestival.org

Thank you!

**Comment by benhohner** [comment]
@taisdesouzalessa @sabrinang Can either of you please reach out to Marc to discuss nav changes and validate before we implement?

**Comment by sabrinang** [comment]
I can help with this ticket — self-assigning so I can keep tack too

**Comment by sabrinang** [comment]
@marcwalsh 
What do you think about if `Schedule` link becomes the new CTA external link button? Tickets is already the second item in the navigation so it will save some horizontal space and the schedule links externally _(all the other nav links are within the site)_:
<img width="1566" alt="image" src="https://user-images.githubusercontent.com/2492510/109727240-d416a080-7b68-11eb-9d97-e7dc2ed488cc.png">

**Comment by sabrinang** [comment]
@marcwalsh would the book be linked from the primary nav as well or is that accessed elsewhere from the site?

**Comment by sabrinang** [comment]
@marcwalsh mentioned via slack they'll change this over to the schedule being the CTA on Monday. He can change the CTA in wagtail.

**Comment by sabrinang** [comment]
schedule has become the CTA on the website — closing issue.
