### ISSUE TITLE
Investigate Commenting solutions

### ISSUE THREAD

**Issue by benhohner** [mozilla/foundation.mozilla.org#6288]
- [x] Reach out to commento developer
- [x] Reach out to Coral hosted

**Comment by benhohner** [comment]
Waiting for commento response

**Comment by jamilasnell** [comment]
Seems like we should move to Coral.

**Comment by benhohner** [comment]
Coral provided their MSA, we need to take to legal

**Comment by benhohner** [comment]
Discussing with Anil
