### ISSUE TITLE
[IA Refresh] Action item - site improvements recommendations

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#6303]
**Background:**
Now that we have [compiled the results](https://docs.google.com/document/d/12Lk9ObtT7robD76gPUDGiDW1LeFMtfM5zX6JnIlwfF0/edit?usp=sharing) of our IA refresh (measuring success) it is time to take action: decide the improvements we want to make in our site based on our learnings.

**To do:**
- [ ] Take the recommendations we have from the report, label them into categories "design", "content" and so on. Set level of complexity for implementation and impact if done. Then decide with Kristina which ones we should prioritize.

cc: @jamilasnell for triage

**Comment by kristinashu** [comment]
@taisdesouzalessa is there any way to break this up into a slightly smaller tickets?

**Comment by taisdesouzalessa** [comment]
Assigned Sabrina and Nancy to this ticket, unassigned myself. In my [handoff list](https://docs.google.com/document/d/1NNEWLL-i0joq_2kjcKnYsLWPmU1GNaUM5jmBc7bIHuc/edit?usp=sharing) I added a task for them to read the research and ping me if any questions or if they need clarification on any item.

**Comment by sabrinang** [comment]
I've worked on taking the recommendations and grouping/labeling them in a google sheet: https://docs.google.com/spreadsheets/d/14XlcxPYT5qJFPnMUsPmDk512lMzTuLx0OJeSwGbmAQM/edit?usp=sharing

@kristinashu I left columns for complexity/impact/urgency empty as I'm not quite sure how to measure the pieces comparatively and if it needs to align with any roadmap stuff so any feedback here is appreciated. Do the 'areas of work' work as categories or did we have others in mind?

@taisdesouzalessa I wanted to get going on this before you leave, so any feedback you have is appreciated!

**Comment by kristinashu** [comment]
Wow nice spreadsheet!

**Comment by taisdesouzalessa** [comment]
This is a great spreadsheet, Sabs! The most beautiful I've ever seen. My only feedback is to link [this doc](https://docs.google.com/document/d/12Lk9ObtT7robD76gPUDGiDW1LeFMtfM5zX6JnIlwfF0/edit?usp=sharing) to the top of the spreadsheet (in case you easily need to go back for context on why those changes were requested) and also link the spreadsheet to the report (maybe in "next steps"?). So you can go back and forth easily and it somebody asks why we are doing some change you have the rationale right there!.

**Comment by sabrinang** [comment]
Thanks for the feedback @taisdesouzalessa! I've linked the original research doc at the top of the spreadsheet with the four labels beneath it and checked off for each item. I also added a README tab that links to all the report/research for additional context for the sheet. Great suggestion to connect these pieces more, I also added a line in the report that links back to this sheet.

@kristinashu this seems like it would be related to the fo-mo planning #6519 so we can discuss prioritization and the other columns then or separately? I'll also summarize the items on the planning list too.

**Comment by kristinashu** [comment]
Tomorrow's meeting will included these recommendations and well as a bunch of the other requests. So it will be slightly high-level but then after that we can dig into the details further.

**Comment by sabrinang** [comment]
The site recommendations were labelled and categorized and got Tais' feedback as she wrapped up her work. A follow up issue is filed here #6557 to divide up this work and continue it further.

@kristinashu is there anything left to review for this issue or are we good to close?

**Comment by kristinashu** [comment]
Looks good, thank you Sabs!
