### ISSUE TITLE
Remove ability to add sub-pages to blog posts

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#6310]
Noticed a staff member added a blog post as a sub-page of another blog post. It seems like it still worked normally but it made it hard to find that sub-post. I don't think blog pages should have the ability to have sub-pages.

- [ ] Remove ability to add sub-pages to blog posts

Screen cap from production showing how sub-pages are possible 
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/1068783/109853700-0d075180-7c0b-11eb-9c90-f84d6e400b60.png">

**Comment by kristinashu** [comment]
Note: clicking on Add Child Page shows **all** the options 😭 

<img width="431" alt="image" src="https://user-images.githubusercontent.com/1068783/109854732-3ecce800-7c0c-11eb-8735-2b060f070a0c.png">

**Comment by KalobTaulien** [comment]
Some documentation with a code example around this: https://docs.wagtail.io/en/stable/topics/pages.html#an-example-wagtail-page-model 

We're looking for `subpage_types` which is a list of page model types (either Classes or lazy-loading strings).

**Comment by danielfmiranda** [comment]
Thanks for linking the docs Kalob! Just submitted a PR :)
