### ISSUE TITLE
[Publications] Preface Text and Publisher's Note Options

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#6311]
Eeva has surfaced that previously when users arrive at the publication there the headline and an instant overview of what you clicked on: https://foundation.mozilla.org/en/initiatives/data-futures/what-could-go-wrong/

So for publication template, they would like to have the option for preface, explainer text after the heading and before the table of contents before jumping in.

I believe this usage was mentioned for the [TAI](https://foundation.mozilla.org/en/insights/trustworthy-ai-whitepaper/path-forward/) paper as well but the intro section was large enough to have it's own page and not ideal to have the ToC to be pushed so far down. 

----

- Consider what design options and layout could accommodate this need for more context as currently we have 'notes' but it may be too far down on the page
- Consider word limit so the ToC isn't pushed too far down
- Consider if the hero section or body options for the format of this content

**Comment by sabrinang** [comment]
@kristinashu R? and feedback?

I iterated on some options and included my annotations here: https://share.goabstract.com/ab0f3e48-fee0-449b-984c-96a66d71d9fd
<img width="1652" alt="image" src="https://user-images.githubusercontent.com/2492510/111831526-c1ac9e80-88ac-11eb-8864-c9a0e4da82ce.png">
 
I didn't include the deeper cutout option as the other pages also have the 48px height cutout that aligns so it didn't makes sense to have it change for when the intro copy is present. I'm leaning towards my last iteration _(relocation notes to appear above ToC as an option without divider and to have Table of Contents available as an option to include)_

Do you think we should include both options of including notes before/after ToC or include them both as different (optional) sections?

**Comment by kristinashu** [comment]
I also prefer your last two iterations. I'm not really familiar enough with the content to know how useful, or not, it is to have the two optional text fields - but I can't think of any harm in having both. I would suggest sharing your final mock-up with a couple stakeholders tho to let them know you're planning to make that update and to make sure they're happy with it.

**Comment by sabrinang** [comment]
I reached out to Eeva and she confirmed that they'd want both options as she mentioned various individual pieces would benefit from it. 

I finalized the design so both above/below Table of content sections can have optional notes: 
Publication page: https://share.goabstract.com/ab0f3e48-fee0-449b-984c-96a66d71d9fd?collectionLayerId=903ef120-e271-4dfc-892b-08ea9ec1623d&mode=design
Child publication page: https://share.goabstract.com/ab0f3e48-fee0-449b-984c-96a66d71d9fd?collectionLayerId=75597cfa-f09b-47f8-a472-b9280fff3bcf&mode=design
<img width="650" alt="image" src="https://user-images.githubusercontent.com/2492510/112070608-46a4eb80-8b2b-11eb-8c5b-499f55b26e2d.png">

The notes field that comes before the ToC can be the same style that contains bold, italic, h4, lists: 
![image](https://user-images.githubusercontent.com/2492510/112070469-f463ca80-8b2a-11eb-9c30-9c30cc2b5306.png)

We can call the new field `intro notes` to differentiate them in the cms.

**Comment by sabrinang** [comment]
I filed the implementation ticket here: https://github.com/mozilla/foundation.mozilla.org/issues/6419 — closing this issue and work continue there.

**Comment by kristinashu** [comment]
Sweet! Thanks for checking with Eeva!
