### ISSUE TITLE
[Insights team: Data Futures Lab] Publications images support

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#6319]
**Background:**
As the Insights Team populates the Publications templates, they will need design support for the images (hero background images and Publications square images). The current hero background images make legibility difficult and we need a system for the square images.

**Publication:**
(https://foundation.mozilla.org/en/data-futures-lab/data-for-empowerment/what-helps-the-ecosystem-for-needs-and-support/)

**To do:**
- [x] Revise/produce hero images for the report, considering past visuals that [were done here](https://foundation.mozilla.org/en/initiatives/data-futures/) + [Data Futures Lab](https://foundation.mozilla.org/en/data-futures-lab/) visual identity
- [x] Revise/produce square images for the template, considering past visuals that [were done here](https://foundation.mozilla.org/en/initiatives/data-futures/) + [Data Futures Lab](https://foundation.mozilla.org/en/data-futures-lab/) visual identity

**Deadline**
**Publication planned for March 30, we hope to have the text frozen by March 24**. 

cc: @kristinashu @jamilasnell for triage (feel free to edit milestone too if it makes sense). Not sure if you want to assign me or Sabrina for this task. Created this ticket so we don't forget about this type of support the Insights team will need from us.

**Comment by jamilasnell** [comment]
@taisdesouzalessa please estimate this issue when you get a chance!

**Comment by taisdesouzalessa** [comment]
@jamilasnell last time I spoke to Eeva she mentioned Solana was working on this and that the 2 researches may be consolidated together...do you know anything about it? I would like to produce the images only once we have the content stable so I don't create more images than needed. I'll put a label "blocked" until we have more information on this, cool?

**Comment by taisdesouzalessa** [comment]
Worked on the icons/hero image and asked for designers feedback. Once I have it, I'll send it to Kasia for review (Eeva will be out until next week).
1. Set of icons #1: [https://foundation.mofostaging.net/en/data-futures-lab/data-for-empowerment/](https://foundation.mofostaging.net/en/data-futures-lab/data-for-empowerment/)
2.Set of icons #2: [https://foundation.mofostaging.net/en/data-futures-lab/data-for-empowerment/what-could-go-wrong/](https://foundation.mofostaging.net/en/data-futures-lab/data-for-empowerment/what-could-go-wrong/)
3. Hero background image of [this page](https://foundation.mofostaging.net/en/data-futures-lab/data-for-empowerment/ ): (I treated the image to increase contrast and legibility of the copy above - you can see this page's hero (with untreated bkg) for comparison.

**Comment by taisdesouzalessa** [comment]
Sent updates to Insights Team - will act on feedback from them + Design team once I have them

**Comment by taisdesouzalessa** [comment]
This is done - @sabrinang I think Laura Vidal is the person responsible for adding all the content to Wagtail - you can ping her to ask when this will be ready for your Publications review.
