### ISSUE TITLE
[Publications] Add two new fields on Article Pages

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#6325]
For the collection of [Data for Empowerment](https://foundation.mozilla.org/en/data-futures-lab/data-for-empowerment/) reserach series, there are use cases and the request from Eeva/Solana to be able to add the publication date to the article page sections as well.

We should also include the "secondary subtitle" option where people can add additional information that goes with this date area too.

---

Add two new fields to Article Page
- [x] publication date (not the publication date of the wagtail page, but a text/date field that users can manually enter input)
- [x] secondary subtitle

For specs, just follow what we have for Publication Page.

**Comment by benhohner** [comment]
Please confirm if this still needs to be done. If not, close

**Comment by sabrinang** [comment]
@benhohner Yes, the stakeholders would like to add dates to their content

**Comment by jamilasnell** [comment]
"Where do these dates need to go?" - @sabrinang

**Comment by mmmavis** [comment]
@sabrinang can you clarify if this ticket is for adding two additional fields to Article Page?

1. publication date
2. secondary subtitle

**Comment by sabrinang** [comment]
@mmmavis Yes, please add those two fields to the article page _(similarly to the fields are seen on publication pages)_
<img width="1657" alt="image" src="https://user-images.githubusercontent.com/2492510/111392784-8889e980-8674-11eb-80a4-46c684e75229.png">

**Comment by mmmavis** [comment]
@sabrinang thanks for the screencaps. Could you provide mockup and styling specs as well? Or should I just refer to what we have on Publication Page?

**Comment by sabrinang** [comment]
@mmmavis Yes, please refer to what is live on the Publication Page

**Comment by mmmavis** [comment]
@sabrinang sounds good. Thanks!
