### ISSUE TITLE
[Publications] Summary Link Order

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#6327]
There's been feedback for adjusting the summary link order or format such as:

- [Data for Empowerment](https://foundation.mozilla.org/en/data-futures-lab/data-for-empowerment/) research series, they want to be able to change the two columns to be vertically ordered not horizontal
- [Trustworthy AI whitepaper](https://foundation.mozilla.org/en/insights/trustworthy-ai-whitepaper/), Sarah W wanted to be able to have one column for the summary content https://github.com/mozilla/foundation.mozilla.org/issues/5800#issuecomment-744577728

Are these possible options to provide?

--- 

Updates: according to this [comment](https://github.com/mozilla/foundation.mozilla.org/issues/6327#issuecomment-801531125)

> have one column when there are less than 5 links, and two columns when there is more

**Comment by benhohner** [comment]
@sabrinang Can you provide some more detail on what is requested/desired? We need a bit more information before we can recommend solutions

**Comment by sabrinang** [comment]
@benhohner Yes, I annotated some screencaps here to go along with the request

- Data for Empowerment research series, they want to be able to change the two columns to be vertically ordered not horizontal:
<img width="1599" alt="image" src="https://user-images.githubusercontent.com/2492510/111229173-b1da4500-85a2-11eb-824a-7e6770136bd2.png">

- Trustworthy AI whitepaper (_this is the executive summary section within it_) they wanted to be able to have one column for the summary content:
<img width="1569" alt="image" src="https://user-images.githubusercontent.com/2492510/111229283-e3531080-85a2-11eb-900b-1c8dfb368d84.png">

My concern with one column however is that when it has a lot of content in the summary it pushes the content quite down on desktop _(see below)_
<img width="1567" alt="image" src="https://user-images.githubusercontent.com/2492510/111229450-29a86f80-85a3-11eb-93f8-869b867df558.png">

**Comment by mmmavis** [comment]
We might wanna settle for just having one 2-column link order because from the users' perspective, having two different order options here and there are very confusing unless the links are explicitly numbered.

**Comment by mmmavis** [comment]
@sabrinang assigning this one to you as we need to finalize specs and mockup before we start implementation!

**Comment by sabrinang** [comment]
@mmmavis I agree that having both orderings would be confusing so I'm planning to go with just the vertical ordering. I was wondering is it possible to have one column when there are less than 5 links, and two columns when there is more?
<img width="1645" alt="image" src="https://user-images.githubusercontent.com/2492510/111556113-09191a80-8747-11eb-9da5-0b76719ff57d.png">

**Comment by mmmavis** [comment]
@sabrinang yup it should be possible.

**Comment by mmmavis** [comment]
I've updated the ticket description with the decision we made.

**Comment by mmmavis** [comment]
Thanks for tackling this @danielfmiranda !

@sabrinang is back from PTO and got the chance to test your solution out on prod. It seems like the PR has introduced some undesired side effects. I'm gonna re-open this ticket so you can work closely with Sabrina to get this to the perfect state! 😃 

### Issues:

1. Some pages split the links into 2+ columns. e.g., https://foundation.mozilla.org/en/data-futures-lab/data-for-empowerment/shifting-power-through-data-governance/
2. columns are not in equal width

**Comment by danielfmiranda** [comment]
Thanks for the catch @sabrinang  and thank you for the suggestion @mmmavis! 
Using the column-count instead of css grid worked great :D I have assigned a PR with the fix to this issue. 

Please let me know if you have any questions
