### ISSUE TITLE
Update the blog "featured post" cards to have a uniform height

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6348]
we're currently only restricting featured blog images to a width 540px but with an unspecified height, which can lead to a blog page that looks like this:

![image](https://user-images.githubusercontent.com/177243/110674454-c2e01c00-8186-11eb-8415-ed3a35af3613.png)

Let's:

- [ ] determine the appropriate max-height for featured post images 
- [ ] update https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/blog_index_feature.html#L12 to include this new value

**Comment by mmmavis** [comment]
Looking at the list of image transformation options that Wagtail provides, I'm not sure if we can find a solution that works for all images. Most images will either get cropped, scaled, or resized (may or may not be processed proportionally) depending on the final specs we set. 

Or we can combine both Wagtail image tag options + CSS, though I think for some cases the images are still gonna look funkier than others.

**Comment by Pomax** [comment]
could we maybe set a max-width/max-height (in percentages), with the image itself being a "crop-...x..." instruction in the wagtail template, with an updated CMS help text to explain that images should be some WxH pixels minimum? The same image also get used for opengraph/twitter cards/etc, as far as I can tell, so having something that universally "crops nicely" might be useful.

**Comment by natalieworth** [comment]
@Pomax if we have a max-width/height, is it possible to have an ellipsis or a 'read more' or some sort of indicator that the text continues if the first sentence doesn't fit within the new size?

**Comment by kristinashu** [comment]
@natalieworth I think this ticket is more about the images, not the text.

@Pomax the images were mocked up to have a 16:9 ratio. Not sure the best way to crop them is but hopefully we can utilize the "focal point" feature in wagtail to help make sure key elements in the graphic aren't cropped out.

![blog-w-featured-copy@2x](https://user-images.githubusercontent.com/1068783/112915219-b6c6ea80-90b2-11eb-8e37-246e3c68a247.jpg)

**Comment by natalieworth** [comment]
ohhh sorry I thought it was both! That makes more sense hah! :)

**Comment by kristinashu** [comment]
Un-assigning design from this.
