### ISSUE TITLE
`create_wagtail_image` function needs unit tests. 

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6350]
To ensure that `create_wagtail_image` always works the way we're expecting it to work in the future, we should write some unit tests. 

Namely, we need to test:
- [ ] Fetching an image from a URL and saving it as a Wagtail Image (but have this disabled so CI doesn't take longer and download an image on every run, but can be tested locally)
- [ ] Fetching an image from a local resource (local file) and saving it as a Wagtail Image 
- [ ] Test automatic creation of a new collection
- [ ] Test image generation without a collect (should be in the "Root" Collection)

**Comment by Pomax** [comment]
> (but have this disabled so CI doesn't take longer and download an image on every run, but can be tested locally)

we can create a gh-pages branch purely for test data that we need to pull from the internet, so that we can test against github.io URLs. As long as github is up, CI should be able to pull those super fast.
