### ISSUE TITLE
Address warnings in a migration file

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#6364]
Just spotted these warnings in Wagtail CI test:

<img width="886" alt="image" src="https://user-images.githubusercontent.com/2896608/111006245-4fced500-8341-11eb-8bdb-f14093cf23ef.png">

Link to migration file: https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/buyersguide/migrations/0002_auto_20200923_1817.py

**Comment by Pomax** [comment]
I think in this case we can back-substitute: the warning is correct, `is` is for primitive "identity" comparison (e.g. is the thing being compared actually the same universal data-at-memory-adress) whereas strings can only be compared for "equality" (e.g. is the _content_ of this memory address the same as the _content_ of this other memory address).

We should be able to safely change the code in these migration file, without having to reapply those changes.
