### ISSUE TITLE
Determine whether we still need Tags for our content, given what we use them for.

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6371]
In order to make the site more responsive, we need to tighten up our blog pages, including the tag code, but this raises questions about what we want to do with tags: we currently use them to decide what qualifies as "related content" for blog/campaigns/etc, but we don't surface those tags on the site in any way, so as far as users are concerned: tags don't exist.

If we're only using them to generate "related content" links, would it make more sense to let content editors explicitly set a number of related posts manually, on the admin side, similar to how PNI deals with related products?

**Comment by Pomax** [comment]
I looked into improving our performance for the codepath indicated by the Scout report, which is for caused by tag filtering being super inefficient, but it also looks like the only way we hit this is through the "recent blog entries" component, which can specify tags. We don't surface tags on blog/campaigns anywhere, so folks don't even know the `/tags` URL exists, acting more as an internal API route.

Looking at our blog dataset, there are currently 444 blog posts but 199 of those don't have any tags, and 128 of those 199 are from the last half year. Given that we don't surface tag routes explicitly, it feels like the right approach here is to remove all the old tag code, and then introduce new and better code for tagging when we want users to see tags again

(the way we originally implemented tags worked at the time, but isn't very expandable, so it seems like the perf. issues we're hitting now are the price of shortcuts taken a few years ago)

**Comment by Pomax** [comment]
@benhohner @kristinashu how do we feel about taking tags out entirely?

**Comment by Pomax** [comment]
As @kristinashu points out, we do still use tags to surface "related posts" on blog pages, but given the large number of posts without tags, it might make more sense to update that to tap into categories rather than tags.

**Comment by jamilasnell** [comment]
@Pomax - can you change the title of this ticket to be more accurate of the actions that need to take place? Thank you!

**Comment by Pomax** [comment]
@Pomax to schedule a call for this

**Comment by benhohner** [comment]
Pages currently using recent blogs component:
![image.png](https://images.zenhubusercontent.com/5fc93ac187345c0cf1d7ae58/2496e1ff-c8f6-411a-bb72-98bbf4d4ee95)

**Comment by Pomax** [comment]
Switching to true related posts:

- [ ] switch blog posts to use `related_posts` similar to PNI categories
  - [ ] write a migration that, for each blog post, performs the related posts search and saves those into the new `related_posts` relation

Moving away from tagfs for "recent blog entries":
- [ ] create a blog entries picker component
- [ ] replace all the above-mentioned "recent-blog-entries-by-tag" with the blog entries picker component instead, set to the same blog entries as the tag search yields, then:
- [ ] remove tag filtering from the "recent blog entries" component

**Comment by Pomax** [comment]
Of the above pages, only three list recent entries by tags:

- Campaigns > Election integrity and platform accountability, uses "platform policy tracker"
- Mozilla Insights > *Privacy Included: Rethinking the Smart Home, uses "privacy-included"
- Homepage > Privacy Included: Rethinking the Smart Home, uses "privacy-included"

And it looks a lot like those last two are the same page.

**Comment by benhohner** [comment]
@Pomax I like your outlined suggestions above, let's move forward with an Epic for this?
@kristinashu thoughts?

**Comment by kristinashu** [comment]
Everything sounds good to me. UX-wise for staff using the blog picker, I'd recommend showing the most recent first and also having search functionality. We have a lot of blog posts and sorting alphabetically would not be useful.

Also just want to confirm that the Recent Blog Entries Component by Category (not tags) will be completely unaffected by this work?

**Comment by benhohner** [comment]
@kristinashu I think we can confirm there will be a way to get recent blog entries by category, whether it be a feature in the new component we create or we decide to leave the recent blog entries component.

**Comment by Pomax** [comment]
https://github.com/mozilla/foundation.mozilla.org/issues/6751 has been filed as implementation epic.
