### ISSUE TITLE
PNI category names are not translated anymore

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#6380]
I just noticed the PNI category names were not translated anymore, this is a regression that occurred sometime between the Valentine’s Day release and now.

Glancing at recent commits, this looks like a solid candidate for this change https://github.com/mozilla/foundation.mozilla.org/pull/6317

Here’s the menu in French:
<img width="1131" alt="Capture d’écran 2021-03-16 à 13 11 07" src="https://user-images.githubusercontent.com/1294206/111306904-b3624680-8650-11eb-9047-981820484e89.png">

When I try to edit https://foundation.mozilla.org/cms/snippets/wagtailpages/buyersguideproductcategory/11/ for instance, I’m getting an error message stating I don’t have permissions to access this area

<img width="881" alt="Capture d’écran 2021-03-16 à 13 12 48" src="https://user-images.githubusercontent.com/1294206/111307179-fd4b2c80-8650-11eb-9786-6d759243f953.png">

**Comment by Pomax** [comment]
I think we forgot to add the category field to the `translation.py` file that we're still using
