### ISSUE TITLE
Follow up to implement wagtail-cache on the PNI home page

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6383]
This is a follow up ticket from the #6375 spike. 

Let's install wagtail-cache on localhost, and apply page caching to the PNI home page. The PNI home page has _a lot_ of database queries, so this should help speed up the page drastically. 

We might want to turn on django debug toolbar (and filebased caching on localhost) to test the performance before and after, and to see if it's worth globally caching all wagtail pages, or just a few page types. 

If things go well on localhost, open a PR to cache just the PNI homepage.

**Comment by jamilasnell** [comment]
We don't think this is still relevant as we are using CloudFlare and the loading time is *chef's kiss*
