### ISSUE TITLE
Investigate mismatched HTML tag issues on article pages

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#6386]
### Describe the bug
There are HTML validation errors around mismatched HTML tags on our sample article pages. I'm guessing the cause might be some block template are missing opening/closing tags.

### To Reproduce
1. Go to `/publication-page-with-chapter-pages/fixed-title-chapter-page/fixed-title-article-page/` locally or on review app.
2. View source code
3. Scroll through and look for highlighted mismatched HTML tag errors

### Expected behavior
No mismatched HTML tags

### Screenshots

<img width="405" alt="image" src="https://user-images.githubusercontent.com/2896608/111359242-7eea8c80-8648-11eb-97ab-f4637700b5c2.png">

<img width="528" alt="image" src="https://user-images.githubusercontent.com/2896608/111359266-8742c780-8648-11eb-8f2f-672abb6216e7.png">

**Comment by mmmavis** [comment]
@danielfmiranda would you like to take this one on?

**Comment by danielfmiranda** [comment]
Hi @mmmavis yes I would! Thank you :)
