### ISSUE TITLE
Download button on Publication Page is off-brand

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#6390]
### Describe the bug
Download button on Publication Page is off-brand. I didn't check Article Page but the button there might be off-brand as well.

### To Reproduce
1. Go to https://foundation.mozilla.org/en/insights/trustworthy-ai-whitepaper/
2. Inspect the "Download PDF" button (default state and hover state)
3. Button is in a different style than what we have in the [style guide](https://foundation.mozilla.org/en/style-guide/)

### Expected behavior
Button should follow style guide. Need to verify this with designers but I'm guessing the button should be in dark theme `.btn-primary` styling. e.g., we need to make sure on hover, the download icon is black instead of white.

### Screenshots
Default state
<img width="242" alt="image" src="https://user-images.githubusercontent.com/2896608/111500579-62f6f180-8701-11eb-8ff5-1d894172a409.png">
Hover state
<img width="236" alt="image" src="https://user-images.githubusercontent.com/2896608/111500629-6e4a1d00-8701-11eb-9976-fc9322a9e133.png">

**Comment by danielfmiranda** [comment]
Hi @mmmavis I have a quick question

It appears that the download icon rendered in the button is doing so with a white SVG in the CSS:
`  
download-button::before {
...
background-image: url(../_images/glyphs/download-file.svg);
} 
`

My first idea to resolve this, without needing a second SVG, is to use this in the CSS:
`.download-button:hover:before {
  filter: brightness(0);
}`

This then achieves the desired result on hover, 

![image.png](https://images.zenhubusercontent.com/6046b7f1bc36adc9ce95a16a/969acc2d-3c52-4eec-bb7a-103ef4651469)

Does this sound like a good solution?

Thanks!

**Comment by mmmavis** [comment]
Yup, that sounds like an awesome solution. We implemented `.btn-secondary` (external link's version) in the same way as well :)

**Comment by mmmavis** [comment]
@danielfmiranda don't forget to check with designers to see if we indeed wanna make the icon go black on hover.

**Comment by danielfmiranda** [comment]
Awesome! Thank you @mmmavis 

Hi @sabrinang I was wondering if you can confirm that the icon changing to black on hover is the desired, on-brand result? Thank you!

**Comment by sabrinang** [comment]
@mmmavis thanks for catching this!

@danielfmiranda Yes the icon should be black like the label too since it is using the dark theme primary button style 👍

**Comment by danielfmiranda** [comment]
@mmmavis @sabrinang Awesome! Just created a PR :) thank you
