### ISSUE TITLE
Enable Pages to pull in Projects and Profiles

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#641]
CMS authored pages would benefit from the ability to use Pulse tags to pull in projects and profiles (when they're available). 

Use cases: 
 - Gigabit cretes a page for 2017 grant initiatives, showing related projects and people
 - Global sprint creates a page to celebrate July's impact
 - Mozfest creates a page for Privacy session facilitators

MVP: 
 - Mezzaine page editor includes field to query pulse (can be raw `tag=mozfest&issue=decentralization` initially. could think about nicer ui later.)
 - frontend template displays card list below page content

**Comment by xmatthewx** [comment]
@alanmoo – following the current priorities, this might be one of the things we want to work on. It unlocks a lot for program staff. Given that we already have some pulse integration on the network site, how complicated would this be? (Just a quick guess, no need to jump deep into this now.)

**Comment by alanmoo** [comment]
Not quite sure what you're looking for here- is it basically a field in the admin page that adds the results of a pulse search?

**Comment by xmatthewx** [comment]
I'll do a quick mockup of admin and rendered page to help guide conversation.

**Comment by kristinashu** [comment]
w00t this is done!
