### ISSUE TITLE
[Publications] Test and improve flow between publication sections

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#6411]
Look into how we can help people navigate between different parts of a publication. 
- Test how users move from sections and see where the opportunities are for improvement  https://github.com/mozilla/foundation.mozilla.org/issues/5800#issue-759797367
- It was also mentioned that https://github.com/mozilla/foundation.mozilla.org/issues/5800#issuecomment-789327634 not many get past the first page so we can look into how to help move them along the publication
- Check if the mechanisms we have now are being utilized _(breadcrumb, previous.next, summar nav and bar, etc.)_

**Ideas**
- perhaps include a reading progress bar to show progression on page
- evaluate if breadcrumb can be improved

**Comment by kristinashu** [comment]
Closing this based on the work Rebecca just did by including all articles within a publications within the summary ToC as well as infinite scroll.
