### ISSUE TITLE
Factory should generate a valid PDF for Publication Page for "Publication PDF" button

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#6414]
STR:
1. Go to http://test.example.com:8000/en/publication-page-with-child-article-pages/
2. Hover over "Publication PDF"
3. Check file extension

**Comment by jamilasnell** [comment]
@KalobTaulien a little present for your return :)

**Comment by KalobTaulien** [comment]
This is proving harder than anticipated to make work with a _real_ .pdf file and some placeholder text like "Hello World", and it's a slow process to test everytime a change is made in the codebase. 

I'm going to shelf this for now. For future me (or anyone else who picks up this ticket) this is a good resource: https://factoryboy.readthedocs.io/en/stable/orms.html#extra-fields and it's working with the `DocumentFactory` class in `publication.py`
