### ISSUE TITLE
Remove duplicate `image_url_tag_urls.py`

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6423]
There are two `image_url_tag_urls.py` files.

We only need the one inside of the `wagtailcustomizations` directory. The other one can be removed.

**Comment by prsndp** [comment]
Hey, @KalobTaulien  I want to work on this issue, please assign me this task

**Comment by KalobTaulien** [comment]
Hi @prsndp — we'd love for you to pick up this ticket. I've assigned this to you. Please set me as the reviewer then you file a PR. 

Thanks!

**Comment by prsndp** [comment]
Yeah, @KalobTaulien  Thanks :)

**Comment by prsndp** [comment]
Hii, @KalobTaulien  there are two **files image_url_tag_urls.py**   but one is inside wagtailcustomizations directory and second one is outside of this directory so which one we need to remove from there? Please let me know..

**Comment by KalobTaulien** [comment]
We want to remove the one that's outside of the wagtailcustomization/ directory. It's currently unused IIRC.

**Comment by prsndp** [comment]
@KalobTaulien  okay thanks

**Comment by prsndp** [comment]
Hii, @KalobTaulien  Please review PR https://github.com/mozilla/foundation.mozilla.org/pull/6427
