### ISSUE TITLE
Make taggit tags case insensitive

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6430]
- [ ] set `TAGGIT_CASE_INSENSITIVE = True` in setting.py
- [ ] add a migration that case-collapes all our tags so we don't end up with "IoT" and "Iot" and "iot" crashing Taggit when it tries to `get(tag__name='iot')` (which expects zero or one result, not more than one).

**Comment by KalobTaulien** [comment]
Collapsing tags is going to be trickier than we expect. We have tags like `,AI` and `AI` which wouldn't get filtered out, they'd just be set to `,ai` and `ai` but still both would exist. 

We might want to go through production and clean up the strange tags we have. Then we can write a management command to turn them all into lowercase, clean up things like commas, and then turn on `TAGGIT_CASE_INSENSITIVE = True`.

For now, I'll work on a management command that at least turns all tags to lowercase and removes _exact_ lowercase text matched tags.

**Comment by jamilasnell** [comment]
@kristinashu may need design assistance here

**Comment by KalobTaulien** [comment]
I'm moving this to blocked until #6371 is figured out. If we end up ditching tags we won't need this ticket. Plus this ticket will need some human intervention to determine each use case and re-name tags appropriately and if we don't end up using tags that time will be wasted.

**Comment by KalobTaulien** [comment]
@Pomax Do you remember where we ended up in regards to using tags? If we're ditching tags, we probably don't need this ticket any more.

**Comment by Pomax** [comment]
I'm going to close this is not worth our effort given that once PNI has been covered, cleaning up the blog tag code is next. (for which there is still an epic)
