### ISSUE TITLE
Remove old `ExtendedYesNoField` from buyersguide app

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6437]
In #6435 we've copied over the ExtendedYesNoField class. 

In this issue, we need to remove the old one. The problem is the class is embedded in too many migration files. We should squash the migrations first before removing the old ExtendedYesNoField.

The old ExtendedYesNoField can be found in networkapi/buyersguide/fields.py

**Comment by KalobTaulien** [comment]
`buyersguide.ExtendedYesNoField` is used 15 times in the `0001_to_0049.py` migration and a few others in the buyersguide/migrations folder. We dont need this anymore so I'm proposing we tackle this ticket when we delete the entire buyersguide app, and scrub the database for old buyersguide table(s).

**Comment by Pomax** [comment]
closing as this will automatically be covered by https://github.com/mozilla/foundation.mozilla.org/issues/8038
