### ISSUE TITLE
Check if `generate_pni_report` command is still being used. 

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6438]
Check with Jen to see if the `generate_pni_report` command is still being used for a private dashboard they have. 

If it's not being used, we should remove the `generate_pni_report.py` file from the `buyersguide/` app. 
If it is still being used, please open a SPIKE ticket to determine what's needed to remove this feature, or to replace the report with a ProductPages instead of Product models.

**Comment by Pomax** [comment]
@caltrider do you know if this is something you still use?

**Comment by caltrider** [comment]
Sooooo....I know nothing about a  generate_pni_report command for a private dashboard. Given that, it's probably safe to say it's not used, at least not to my knowledge.

**Comment by Pomax** [comment]
@KalobTaulien let's removolate!
