### ISSUE TITLE
Remove buyersguide.validators after migrations are squashed.

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6441]
We currently have this file: buyersguide/validators.py

it needs to be removed once migrations are squashed so we can avoid doing migration surgery. This seems to be nested in quite a few migrations.

**Comment by KalobTaulien** [comment]
The`buyersguide.validators.ValueListValidator` class is being used in the `0001_to_0049.py` migration. I'm proposing we delete this all at the same time when we delete the buyersguide app. Could be merged in to #6437 as the same task. The ValueListValidator class isn't being used anywhere else, but it's needed for existing migrations. But if we don't need the migrations at some point, we won't need this class.

**Comment by Pomax** [comment]
closing as this will automatically be covered by https://github.com/mozilla/foundation.mozilla.org/issues/8038
