### ISSUE TITLE
SPIKE: Investigate why we have a DoubleClick cookie being registered on the what-we-fund page

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6458]
Investigate why we have a DoubleClick cookie on what-we-fund and if we can get rid of it to be inline with mozilla.org’s cookie usage.

Find out where it's coming from, and if we need to remove anything to prevent it from loading on the foundation site.

**Comment by Pomax** [comment]
Can we confirm this is still the case? Because I don't see one.

**Comment by jamilasnell** [comment]
We can't find it whelp closing it :)
