### ISSUE TITLE
Document the importance of not hardcoding the English locale when including links in content

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6461]
Followup to https://github.com/mozilla/foundation.mozilla.org/issues/5981

Add documentation to the "how do I wagtail" pages to explain that links should never include the `/en/` locale prefix.

**Comment by jamilasnell** [comment]
Related to #6457

**Comment by jamilasnell** [comment]
@TheoChevalier and @beccaklam Is this something that should still be completed?

**Comment by TheoChevalier** [comment]
I’ve just added a first version here: https://foundation.mozilla.org/en/docs/how-do-i-wagtail/adding-links/

Anyone should feel free to edit/improve :)
