### ISSUE TITLE
Add support for spaces in PNI categories back in 

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6464]
We took it out, so that resolution on slug is the only way to get to categories, but we're seeing request for the old format, e.g.:

```
Mar 29 00:47:24 foundation-mozilla-org heroku/router at=info method=GET path="/en/privacynotincluded/categories/Toys%20&%20Games/" host=foundation.mozilla.org request_id=f6e92e2c-4c76-42b7-8e0c-f4c1ea866a25 fwd="54.70.40.11,172.69.23.51" dyno=web.2 connect=1ms service=80ms status=500 bytes=1811 protocol=https
```

Alternatively, we could have that at least return the PNI homepage instead of a 500 server error?

**Comment by Pomax** [comment]
So, investigative results: `@route` decorators run through `wagtail.core.views.serve`, which itself only binds to [a very restricted pattern](https://github.com/wagtail/wagtail/blob/571b9e1918861bcbe64a9005a4dc65f3a1fe7a15/wagtail/core/urls.py#L9-L18) that does not kick in for "non-slug" patterns, meaning that anything with `%xx` values won't work.

This almost feels wagtail-bug worthy. Thoughts @KalobTaulien?

**Comment by KalobTaulien** [comment]
I agree we should open a Wagtail issue!

**Comment by Pomax** [comment]
We can probably also write a "shim" file that basically does what https://github.com/wagtail/wagtail/blob/571b9e1918861bcbe64a9005a4dc65f3a1fe7a15/wagtail/core/urls.py does, but then with a broader pattern, so that that, too, gets sent over to the wagtail.core.views.serve function
