### ISSUE TITLE
Wider iframe and wider images on blog and publications

### ISSUE THREAD

**Issue by benhohner** [mozilla/foundation.mozilla.org#6465]
We need to create slightly wider image format (col-12, currently uses col-8 on lg) to enable our content creators to increase engagement with their graphics, as they're currently quite small.

- [ ] wide iframe on blog
- [ ] wide image on blog
- [ ] wide iframe on publications
- [x] wide image on publications

**Comment by KalobTaulien** [comment]
Note: We're going to implement some of the design changes to get this ticket merged in as soon as possible before the agnostic blog/article streamblock refactor work.
