### ISSUE TITLE
[Miscelaneous] A place for all unplanned small tasks (Design team) during this sprint

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#6468]
This is a place where we can track unplanned small tasks that come up through the sprint. Please add your name in the thread, the tasks you worked on and duration of task.

cc: @jamilasnell feel free to edit this ticket as you see fit.

**Comment by taisdesouzalessa** [comment]
**Taís:**

- [ ] Slack request (from Kasia - Insights team): prepare an image for Insights team blog post - "I am thinking about the new nice icon you made with the hand and the plant but in an horizontal format so I can add it to the blogpost"
- [ ] Slack request (from Laura - Insights team)): fix spacing in 2 of the quotes [in the PDF](https://docs.google.com/document/d/1yPokbfI-3TEiUl6hcRvq3XGcopHfdML--IxSM6JklV4/edit?usp=sharing) (pages 19 and 36)

**Comment by sabrinang** [comment]
**Sabrina:**

- [x] Coordinating content card graphic (from MJ/Audrey): Intake request, relay between Nancy/MJ and update [/agency-assets](https://foundation.mozilla.org/en/docs/brand/agency-assets/) documentation with dimensions. **Time spent: 10 min** _(Mar 29/30)_

- [x] Meeting with Simply Secure (from Mehan/Jam): Discuss wagtail, publications, data viz and components for an upcoming collaboration. Follow up slack with Jam re: list of template and component types for reference on how to wagtail. **Time spent: 45 min** _(Mar 30)_

**Comment by natalieworth** [comment]
- [ ] Email from Stephanie Lowrey requesting envelop colour to change for donor fundraising envelopes **Time spent: 40 mins** (Mar 29)
- [ ] Slack request from Audrey for Converted the 'Mozilla Explains' bumper into a vertical size for Instagram Stories. **Time spent: 1 hour** (Mar 30)
- [ ] Slack request from Audrey for 2 options of a 1200 x 800 graphic for mozilla.org team of the first Mozilla Explains video for their homepage **Time spent: 30 mins** (Mar 30)
- [ ] Slack request from Audrey for a YT cover image for the 1st Mozilla Explains video **Time spent: mins** (April 1)

**Comment by kristinashu** [comment]
Thank you all for tracking this and for being willing to jump in and help out staff!

@jamilasnell looks like this ticket was moved over from the previous sprint - was that intentional? I assumed we'd close this at the end of the sprint it's in and open a new one for the new sprint https://github.com/mozilla/foundation.mozilla.org/issues/6520

**Comment by jamilasnell** [comment]
Did not mean to move this ticket to the current sprint! Will remove
