### ISSUE TITLE
[Wagtail Documentaion] Create List of Templates and Components

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#6472]
Document on https://foundation.mozilla.org/en/docs/how-do-i-wagtail/ what types of templates that we have available on the CMS for stakeholders as they are considering to publish their content on our foundation.mozilla.org site. For each template, list what components are available that correspond to each. Updating the sample page may be useful to showcase the components in use.

**Comment by kristinashu** [comment]
w00t! Rebecca did this https://foundation.mozilla.org/en/docs/how-do-i-wagtail/page-types/ & https://foundation.mozilla.org/en/docs/how-do-i-wagtail/streamfield-blocks/
