### ISSUE TITLE
Remove user-associated profiles when deleting a user

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#648]
@Pomax commented on [Tue Jul 18 2017](https://github.com/mozilla/network-api/issues/250)

right now deleting a user can lead to an error:
```
IntegrityError at /admin/auth/user/
Exception Value: update or delete on table "auth_user" violates foreign key constraint "userprofile_userprofile_user_id_59dda034_fk_auth_user_id" on table "userprofile_userprofile"
DETAIL:  Key (id)=(......) is still referenced from table "userprofile_userprofile".
```
so we need to update the user model(s) such that when a user gets deleted, the associated user profile gets removed as well.

**Comment by Pomax** [comment]
which of the two "user" headings in the navigation did you use to get this error?

**Comment by alanmoo** [comment]
¯\_(ツ)_/¯ You were the one to file this issue, I simply moved it from the network-api repo.

**Comment by kristinashu** [comment]
@Pomax is this still an issue with Wagtail?

**Comment by Pomax** [comment]
it is not. closing.
