### ISSUE TITLE
Determine whether we can use `sandbox` with our iframe

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6481]
We had `sandbox="allow-scripts"` but this was too restricted and prevented content from loading on https://foundation.mozilla.org/en/data-futures-lab/data-for-empowerment/what-helps-the-ecosystem-for-needs-and-support/#who-is-building-the-field

- [ ] determine if there is any combination of values for this attribute that will allow our content embeds to keep working.

**Comment by jamilasnell** [comment]
#Investigation!
