### ISSUE TITLE
make `highlight` app use wagtail for its images

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6482]
- [x] rewrite `networkapi/highlights` to use wagtail images instead of S3 file uploads
- [x] create a migration that turns all remote highlight images into wagtail images.
- [ ] change the highlights factory code so that it uses the same random wagtail image code that blogs etc. use

This will unblock https://github.com/mozilla/foundation.mozilla.org/issues/6102

I suspect this will be similar to our PNI image uplift, although nowhere near as likely to go completely wrong =)

**Comment by KalobTaulien** [comment]
@Pomax I'll take this ticket. Should be [hopefully] straight forward now that we have the create_wagtail_image() function.
