### ISSUE TITLE
[Spike] Audit which JS files need docs to explain what they do and how they're used

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#6506]
Add inline documentation describing what each JS file is for.

Audit result:

- [ ] social-share.jsx
- [ ] creepiness-labels.js
- [ ] inject-react/creep-vote.js
- [ ] homepage-c-slider.js (while it does have comments that explains what the code does, it might be a good idea to add a comment at the top to let the reader know that this logic has to do with the PNI creepometer face.
- [ ] pni-mobile-nav.js (pretty simple, however might still benefit from leaving comment at the top letting reader know what it does)
- [ ] product-tab.js
- [ ] Carousel.js
- [ ] Mozfest-hero-carousel.js
- [ ] mozfest/home-banner.js
- [ ] mozfest/tito.js
- [ ] youtube-regrets/regrets-reporter/cta-button.js (needs updated comment at top)
- [ ] youtube-regrets/regrets-reporter/share-buttons.js (this one can probably be moved to a new extension landing page directory)
- [ ] youtube-regrets/regrets-reporter/timeline.js
- [ ] youtube-regrets/regrets-reporter/utm-buttons.js (this one can probably be moved to a new extension landing page directory, and can also use an explanation at the top of the file.)
- [ ] callpower.js
- [ ] directory-listing-filters.js
- [ ] audio-player-handler.js
- [ ] blog-hero-video-handler.js
- [ ] looping-video-handler.js
- [ ] basket-signup.js
- [ ] donate-banner.js
- [ ] dropdowns.js
- [ ] nav-newsletter.js

**The following can probably be moved to their own subdirectory to show they belong to the YT regrets 2021 page. As well as adding a description to the top of the file.**
- [ ] youtube-regrets/accordion.js
- [ ] youtube-regrets/browser-extension.js
- [ ] youtube-regrets/carousel.js
- [ ] youtube-regrets/categories-bar-chart.js
- [ ] youtube-regrets/count-up.js
- [ ] youtube-regrets/intro-tunnel.js
- [ ] youtube-regrets/read-more-categories.js
- [ ] youtube-regrets/recommendation-pie-chart.js
- [ ] youtube-regrets/regret-rates-chart.js

**Comment by mmmavis** [comment]
Since we have so many JS files (60+), adding documentation to all JS files and functions in one go is unrealistic and draining 😂 . I'm gonna change this ticket to focus just adding documentation explaining what each file is for.

**Comment by Pomax** [comment]
@danielfmiranda let's morph  this into a spike: let's list every file we want to update, with a checkbox to mark whether or not we've done that, so that by the time they've all checked, FIVE YEARS FROM NOW, we know we're done

**Comment by danielfmiranda** [comment]
Audit complete, implementation issue can be found here! https://github.com/mozilla/foundation.mozilla.org/issues/8041
