### ISSUE TITLE
[Publications] Callout Box Styling

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#6509]
### Intro
This is a design ticket to look into how callout boxes could be improved or if something else is more useful _(i.g. a block quote component etc.)_

### Context
After doing the data for empowerment design review https://github.com/mozilla/foundation.mozilla.org/issues/6118, there was use cases and feedback from the insights team on the callout box.

- they were including breaks in the text but didn't understand why it wasn't showing
- they discovered is that the style changes when the text is longer but realized there is no way to change the style inside of the box
- they mentioned it looked awful without styling and wanted to add a title, bold to format etc. so I recommended for them to use the content component

Some examples of what they wanted to use it for:
- notes/acknowledgment, spotlight sections, block quotes:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/2492510/113903290-ab944e80-9785-11eb-856a-6e76d9de6b33.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/2492510/113903311-b2bb5c80-9785-11eb-8651-7b7712c88d66.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/2492510/113903341-b9e26a80-9785-11eb-9657-fd5cb5398d3f.png">

They ended up using callouts for block quotes only.

**Comment by kristinashu** [comment]
@sabrinang sorry, I forget, is this still needed? How is it related to the other call-out and quote tickets you recently worked on?

**Comment by sabrinang** [comment]
This was the original ticket for callout box styling improvements and captured some of the limitations and in https://github.com/MozillaFoundation/Design/issues/806 we've looked into it and due to it's infrequency of use it was a wontfix issue. If it is something we want to note to get to the future we can leave this issue open or if you think it is not valuable we can close since we closed the other one.

**Comment by kristinashu** [comment]
Thank you Sabs! Will close this and can open a new one if it starts to feel more needed.
