### ISSUE TITLE
Perform our outstanding migration/app surgery

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6510]
We've accrued a ton of migrations in mozfest and wagtailpages again, and the old buyersguide app is still hanging around, so let's perform our outstanding migration/app surgery:

- [ ] remove old buyersguide app rather than cleaning up its migrations
  - [ ] also remove cloudinary dependency, as the old bg app is the thing that's keeping that a required dependency
- [ ] squash mozfest
- [ ] squash wagtailpages
  - https://github.com/mozilla/foundation.mozilla.org/pull/8182

**Comment by Pomax** [comment]
I'm not sure if we can use `replaces` to replace "itself" (e.g. have `0001_initial` replace `[0001_initial, 0002_blah]`), but if that's possible, that would allow us to drop the subsequent noop migration entirely.

**Comment by bheasman** [comment]
Closing as covered by #8216
