### ISSUE TITLE
fo'mo planning

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#6519]
Plan out our next feature improvements on the site https://docs.google.com/document/d/1P8nLBsmYy0_tpnUdBSRMuHGKymEydiGM7Z2UqKghFWc/edit?usp=sharing

**Comment by kristinashu** [comment]
Still figuring out the best way to do this but I think we should try doing our meeting tomorrow using Miro. Kaili has an account and has created [a board](https://miro.com/app/board/o9J_lJgXt6M=/) for us to use. Before the meeting, please make sure you have access to it and can add post-its.

Once all the possibilities are in Miro, then we can move them to a spreadsheet similar to [this amazing one ](https://docs.google.com/spreadsheets/d/14XlcxPYT5qJFPnMUsPmDk512lMzTuLx0OJeSwGbmAQM/edit#gid=93481257)Sabrina created.

**Comment by benhohner** [comment]
Sounds like a great plan

**Comment by kristinashu** [comment]
After some fun Miro sessions, Jamila summarized and ordered the priorities here https://docs.google.com/document/d/1cYnRO6zWIxOK0CVhy2bRnLBCmSxG6e21aJioFaBK_R8/edit. We are aiming to complete the first 10 in that list within the next two months. Jamila has submitted the first 10 items to Airtable. Thank you all!
