### ISSUE TITLE
[Data Visualization] Document Guidelines for Custom Graphics

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#6525]
Create guidelines and best practices for custom data visualization graphics for staff and corresponding contractors/vendors/contributors they work with. 

Currently there has been an [interim implementation solution](https://github.com/mozilla/foundation.mozilla.org/issues/6223) so we can describe what the process looks like, what is required and expected from it.

### Reference
Planning document: https://docs.google.com/document/d/1ySaJMH4mWxgZLqt7PvdVeNdS-IHekfKBYLF-ZSI9Nk4/edit?usp=sharing
Planning issue: #6192

**Comment by mmmavis** [comment]
What I understood based on the [interim implementation solution ticket](https://github.com/mozilla/foundation.mozilla.org/issues/6223) -- Amazon S3 bucket for custom graphics has been set up and whitelisted by Foundation site. To include a new custom graphic, simply drop the script files in S3 bucket and embed the graphic using CMS's iframe block.

Note: the interim solution ticket mentioned a new public repo was set up. I'm not sure what it was referring to. Maybe things in that new repo get automatically uploaded to the S3 bucket? I will check with Pomax/Ben on this on Tuesday and update this comment accordingly.

**Comment by benhohner** [comment]
@sabrinang @Pomax Added contributing guidelines here: https://github.com/MozillaFoundation/mofo-infographics/blob/main/README.md Please review and make any changes you see fit

**Comment by sabrinang** [comment]
@benhohner The guideline looks good! For step two, we don’t have a set expanded palette for data viz colors but I can see a step being reaching out to the design team to give a design review _(to check that chosen expanded colors align and that overall the visual is on brand)_? and could we be reviewing it on github?

**Comment by benhohner** [comment]
@sabrinang I updated the copy to include a design review stage.
Why I mentioned an expanded colour palette was because I think that will be a common need and we'd want the developer to reach out to you to create one.

**Comment by sabrinang** [comment]
@benhohner +1 I think it would useful to have the extended palette for data viz too _(noting this need in the design library work so we can include it in the future_)
