### ISSUE TITLE
[SCSS] Clean up _forms.scss

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#6527]
[source/sass/mofo-bootstrap/overrides/_forms.scss](https://github.com/mozilla/foundation.mozilla.org/blob/master/source/sass/mofo-bootstrap/overrides/_forms.scss) has rulesets which were in v4 alpha but are no longer available in v4. e.g., `.has-danger` , `.form-control-feedback`, `.form-control-danger`... etc. 

### Approach 1 (simplest)
If these rulesets are still needed, we should move them out from the `mofo-bootstrap` directory and treat them as our custom SCSS for foundation site.

### Approach 2 (more desired but requires more effort)
Another approach is to utilize Bootstrap v4's [form validation classes](https://getbootstrap.com/docs/4.0/components/forms/#validation) instead of keeping the old alpha rulesets. Note that this approach will require updating DOM nodes / React components to a certain degree so they have the right class name attached for all scenarios.

**Comment by fessehaye** [comment]
Going to do approach one since we are transitioning to Tailwind!
