### ISSUE TITLE
add an indicator to the user admin to show which account is django vs. social auth

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#653]
@Pomax commented on [Thu Jul 20 2017](https://github.com/mozilla/network-api/issues/251)

social auth users cannot be deleted except through the social auth => users panel, so it will be good to highlight which user is of which type in the users => user panel

---

@arush0311 commented on [Fri Jul 21 2017](https://github.com/mozilla/network-api/issues/251#issuecomment-317104113)

can i take this?

**Comment by arush0311** [comment]
This requires monkey-patching mezzanine's UserModelAdmin but i am not sure where the code will belong

**Comment by Pomax** [comment]
I would like to suggest closing this in favour of a well-tasked epic around proper user deleting through python-social-auth's hooking mechanism/proper `ON_DELETE` settings

**Comment by Pomax** [comment]
no longer relevant due to wagtail
