### ISSUE TITLE
Investigate slowdown on edit pages starting Week of April 9th

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6536]
Scout has noticed a drastic slowdown this week. 

We need to explore _why_ this happening and what is causing the slow down. 

As far as we know it's just when editing a page. 

Places to check:
- [ ] save() methods
- [ ] Middleware 
- [ ] Wagtail hooks

**Comment by Pomax** [comment]
this is now too far in the past to look at, but we've performed a number of improvements that have lead to faster response times overall, and drastically faster response times in specific page instances.
