### ISSUE TITLE
[YouTube] RegretsReporter shareout landing page planning

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#6539]
Project from the AI & Content working group. 

Create an interactive landing page to share out this content https://docs.google.com/presentation/d/10ZNsVF6hOAGPy4i6Cgx9WiryOiSzX69bUm6MluS740w/edit#slide=id.p

Proposed deadline for project: end of May

### More links
- working group notes https://docs.google.com/document/d/102LP21bcOtiVAIwvbsp2hUl578gdi6ecFpWNfe7TyMg/edit
- Tais' scope notes https://docs.google.com/spreadsheets/d/13TCx3NFTRtKTQ6Nh8_TNitPSoWnDP9MovvEnkW0f3QE/edit?ts=606cd9fc#gid=0
- Project brief https://docs.google.com/document/d/19r7dIkYKe1IRLXV5hH1n0OkSNKkROkcirq2amoQ7-AU/edit

### For this sprint 
- [x] Read the docs (Nat & Nancy)
- [x] See if Audrey can help (Kristina)
- [x] See if [Christian](https://christianlaesser.com/) can help (Ben)
- [ ] Start content outline for landing page (Nat & Nancy)
- [ ] Determine technical direction for charts/graphs (Nat & Nancy)
- [ ] Bonus: start wireframing the page (Nat & Nancy)

**Comment by natalieworth** [comment]
Hey @kristinashu I know Taís started this a bit, but will this be custom-code or should we think about designing it for the parameters of our Wagtail blog pages?

**Comment by kristinashu** [comment]
This would be an example of a storytelling or narrative piece - maybe not a block but perhaps a campaign page. I wouldn't go too bluesky with this one. If there are new Wagtail components you think would be good for this as well as other narrative pieces then you should propose those e.g. full width image.

Note: Audrey will be chatting with Brandi about this tomorrow to onboard her to the project and content.

**Comment by natalieworth** [comment]
@nancyt1 and I have reviewed the notes for this. I have scheduled a meeting with Brandi and Audrey for Tuesday (April 27).

The possibility of the data wrapper doesn't seem feasible with this sprint—so likely going with Christian for custom graphs/charts would be easiest for now.

**Comment by natalieworth** [comment]
I've made a new ticket with updates and to-dos for the next sprint, so going to close this.

New updates are in #836
