### ISSUE TITLE
Redirects don’t keep URL parameters

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#6543]
URL parameters used to be kept during redirects, but it’s not the case anymore. This prevents us from generating performance reports on campaigns. Here’s an example below with a snippet campaign

### STR:
- Open https://foundation.mozilla.org/newsletter/?utm_source=desktop-snippet&utm_medium=snippet&utm_campaign=snipQ22021&utm_term=999999&utm_content=REL

### Current behavior:
Currently redirects me to: https://foundation.mozilla.org/fr/newsletter/

### Expected behavior:
Should be redirecting me to https://foundation.mozilla.org/fr/newsletter/?utm_source=desktop-snippet&utm_medium=snippet&utm_campaign=snipQ22021&utm_term=999999&utm_content=REL

This looks like a good candidate to add a test for as it’s not easy to notice it’s broken. Happy to file a separate ticket for this

**Comment by Pomax** [comment]
I suspect this is caused by https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailcustomization/redirects/middleware.py
