### ISSUE TITLE
List of CMS Page Types for Design Library Planning

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#6549]
To help inform designers what Figma templates we should create, please compile the list of the CMS page types that we currently have.

Please help correct the following list so it's up to date with what we have on CMS:

- Default Page
- Banner Page
- Publication page
- Blog index page
- Blog Page
- Primary Page
- Buyers Guide Page
- Participate page2
- Mini site name space
- Initiatives page
- Campaign index page
- Campaign page
- News page
- Styleguide
- Redirecting page
- Opportunity page
- Petition page

**Comment by KalobTaulien** [comment]
This might or might not be helpful, but here's a screenshot of all the available pages on the Foundation site and Mozfest site (combined) 

![image](https://user-images.githubusercontent.com/4743971/122826570-8e5d1f80-d2a0-11eb-9b53-973cd28c4f8f.png)

**Comment by KalobTaulien** [comment]
Note for devs: Follow up on what the page types are being used for. 

@sabrinang We need a little more context around this. Do you just need the list of pages, or the hierarchical connection between them? (Like how Article Pages are usually children of Publication Pages)

**Comment by jamilasnell** [comment]
Becca did complete this so I am closing!
