### ISSUE TITLE
Address "TODO:FIXME:" issues with our existing SCSS mixins

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#6550]
There are a few things we can improve with our existing SCSS mixins. I've put in inline notes in this [PR](https://github.com/mozilla/foundation.mozilla.org/pull/6542). To look for the notes, just search for `TODO:FIXME:` in the `.scss` files (there should be [4 instances specifically for mixin improvements](https://github.com/mozilla/foundation.mozilla.org/pull/6542/files)) and follow the inline notes.

To make PR review easier, I'd suggest creating individual PR for each issue mentioned or one PR with each commit addressed an individual issue.

**Comment by Pomax** [comment]
marking as 4 for now, we can adjust down as someone sits down to do this work.
