### ISSUE TITLE
Refactor blog authors template code so publication pages can use it

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#6554]
The majority of the code in this part of [publication_hero.html](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/publication_hero.html#L42-L73) is almost identical to [blog_authors.html](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/blog_authors.html).

Let's 

1. first check with the designers and see if the styling of both types should match
2. determine how much code we can extract from `blog_authors.html` (and SCSS) so publication pages can use it
3. refactor code and rename "blog_authors/blog-author" in code and file name to something more generic

**Comment by jamilasnell** [comment]
Power behind the Throne = Simon

**Comment by danielfmiranda** [comment]
Hi Everyone, after looking into this ticket, we found that the only similar portion between the two files would be the part that loops through the author pictures:
![image.png](https://images.zenhubusercontent.com/6046b7f1bc36adc9ce95a16a/ccef59ec-2b92-4b10-b1c6-86d564a88b83)
![image.png](https://images.zenhubusercontent.com/6046b7f1bc36adc9ce95a16a/66d9d263-489f-49ce-aff1-9dd0037c507a)

We can extract this section and move it to its own file, wanted to ask the teams thoughts before we proceed.
