### ISSUE TITLE
Remove chapter-page.scss

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#6555]
Code in [chapter-page.scss](https://github.com/mozilla/foundation.mozilla.org/blob/master/source/sass/components/chapter-page.scss) is either not being used or should be renamed and relocated.

- [ ] Verify if `chapter-number` is applied to any HTML node. If not, remove the entire SCSS ruleset
- [ ] Verify where `chapter-article-link` is being applied. From a quick check it seems like it's only used on `publication_table_of_contents.html` and therefore this selector should be renamed and the SCSS code should be moved to `publication-page.scss` instead.
- [ ] Remove `chapter-page.scss` if it contains no useful code after the previous cleanup steps

**Comment by jithenshriyan** [comment]
Hi, I'd love to work on this task! I'll go ahead and get started if no one else is working on it. Thanks!

**Comment by Pomax** [comment]
hi @jamilasnell can you review  your PR? it has merge conflicts that need to be resolved.

**Comment by Pomax** [comment]
hi @jithenshriyan, can you review  your PR? it has merge conflicts that need to be resolved.
