### ISSUE TITLE
Make sure we are loading italic font styles from Google & update /style-guide to include examples

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#6564]
One example:
https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/templates/pages/base.html#L33-L37
(Note that we also need to fix other templates as well. Search `https://fonts.googleapis.com` in the codebase to find more.)

- [x] It looks like we are only loading `300i` for both Nunito Sans and Zilla Slab. We should make sure italic styles are loaded for other font weights as well.
- [x] Work with designer and add examples to /style-guide page to demonstrate italic styles for body text. This can also help us capture regressions (via Percy) if italic style doesn't get loaded properly to the site. 

/cc @sabrinang @danielfmiranda

**Comment by jamilasnell** [comment]
Simon is going to be the real force behind this ticket

**Comment by sabrinang** [comment]
@fessehaye Here's more context on which italics should be loaded as users in wagtail can apply italics to the text in various templates _(looks like mainly 400i, 600i are missing but please check what is missing as well)_. Here is a screenshot of default template and highlighted issue areas in pink and what it should be:
![testing-type-screenshot@2x](https://user-images.githubusercontent.com/2492510/122441092-10bcab00-cf52-11eb-9a20-7690799abfe8.jpg)

- This should be added to the Paragraphs section as we have bold already
- We did not add bold and italics in headings deliberately as we won't want to encourage using them there to keep headings uniform and clean but the option is there for staff
