### ISSUE TITLE
Typeform Wrap Up

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#6593]
- [x] Get design input on what instructions need to look like
- [x] Update Wagtail Docs (https://foundation.mozilla.org/cms/pages/54/)
- [x] Determine Users of Typeform
- [x] Make sure all staff have 1Password set up (Ben can help with this)
- [x] Make Sure all staff have access to Typeform Login

**Comment by kristinashu** [comment]
cc @sabrinang since she is creating some Typeform templates https://github.com/MozillaFoundation/Design/issues/798 and is familiar with possible stakeholders. Also linking to some very [WIP guidelines](https://docs.google.com/document/d/1oWIrAk5k3Gd9ILYs-Sgrcalw7Yoyb11WjNcIXyfJfL0/edit) Anil has made.

**Comment by danielfmiranda** [comment]
Hi @benhohner! After reaching out to the design team they let me know the current typeform stakeholders include Kaili, Audrey, and Anil. 
I was wondering if you can help me with the 4th action item in this ticket, which are to make sure that they have 1password set up?

Thank you!

**Comment by benhohner** [comment]
@danielfmiranda definitely! I was expecting the list to be a bit bigger, but I checked and all the stakeholders have access. I'll ping them to verify they know how to access our Typeform. Thanks Daniel!

**Comment by danielfmiranda** [comment]
Thanks Ben! That would be very helpful as I believe once we confirm they also have access to typeform, we can check the 5th action item of this task as done.

**Comment by Pomax** [comment]
unassigning myself so it won't show up in my "todo" list, but of course feel free to reach out for any questions =)

**Comment by sabrinang** [comment]
Ben to give Daniel CMS permissions

**Comment by danielfmiranda** [comment]
Hi Everyone, using  [this](https://docs.google.com/document/d/1oWIrAk5k3Gd9ILYs-Sgrcalw7Yoyb11WjNcIXyfJfL0/edit) google doc for reference, I have filled out the docs on the Wagtail site to the best of my ability, below are the links to the draft/preview:

Link to CMS Draft: https://foundation.mozilla.org/cms/pages/2139/edit/
Link to Preview: https://foundation.mozilla.org/cms/pages/2139/edit/preview/

@benhohner @kristinashu I was wondering if I can get some feedback on this doc, and if you can point me to someone who can help me fill the "How to collect responses and sunset" and "Deleting any private data" sections as I am unfamiliar with that workflow. 

Thank you!

**Comment by benhohner** [comment]
@danielfmiranda I made a couple edits and saved the draft. Looks good to go!

**Comment by kristinashu** [comment]
Thank you Daniel! I left one comment in the doc.

I also don't know the answers to "How to collect responses and sunset" or "Deleting any private data". @anilkanji any ideas?

**Comment by benhohner** [comment]
@kristinashu I think everyone should have 1Password access now. Is there anything the design team would like to do as a follow up to make sure everyone has proper training?

**Comment by kristinashu** [comment]
If it's all set then I guess just announce it in the Wagtail channel and link to the resources. Perhaps with a specific FYI that Sabrina has added some design templates to our account.

**Comment by sabrinang** [comment]
I checked out the draft page too and it looks good! Not sure if this is wrapped up but I have some feedback that could help staff when referencing the page:
- a demo typeform embed on the page or link to a wagtail page with one
- screenshots could also help accompany instructions _(example: screenshot to go with “share” button at the top-centre of the screen etc.)_
- menu label could be just Typeform to simplify and match the others

**Comment by danielfmiranda** [comment]
Thanks Sabrina! I have changed the menu label to just be "Typeform" and have also added 2 screenshots for now. 
Since this ticket is wrapped up, I will create a new issue to create a demo typeform embed or to link a demo typeform as well!

**Comment by danielfmiranda** [comment]
@benhohner Was wondering if I was OK to push the article draft now before I mark this ticket as closed?

**Comment by danielfmiranda** [comment]
Pushed the documentation to live, marking this as closed!

**Comment by anilkanji** [comment]
Thank you so much for your work on this @danielfmiranda ! Two questions that I had slacked to Ben/Sabrina a while back - apologies if I missed a response:

1) We actually only pay for 2 users on typeform - if folks start signing into typeform with their own accounts to build surveys we'll start to incur costs for each additional user - @benhohner have you all discussed this and come to a solution? 

2) We had I believe set up Typeform to auto-delete responses after a while, which surprised some initial users - can we please add in some way for a user to retain data outside of the Typeform platform? @tomusher would have some context on this, and he should vet this process to add any feedback from his perspective (as he helped set up our initial surveys). 

@danielfmiranda can you please loop back with me on Slack and then we can document here what the resolution was?
