### ISSUE TITLE
Fo'mo Cinchy/CRM Migration Code Cleanup

### ISSUE THREAD

**Issue by benhohner** [mozilla/foundation.mozilla.org#6596]
Clean up code for migration on donate and foundation (do After production launch on May 25th)

 - [x] Look through code and environment variables changed on fo'mo because of migration
- [x] Update fo'mo to remove branching and method env variable

**Comment by Pomax** [comment]
@benhohner do you remember the specifics for this issue?

**Comment by jamilasnell** [comment]
@benhohner What work still needs to be done? Let @danielfmiranda know and he can finish up this work. Thank you!
