### ISSUE TITLE
Determine a timeline and roadmap for switching to an all-streamfields-are-rows rollout

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6597]
Once we're convinced we have a way forward for #6517, we need to plan out over what time period we update everything, and how we can make sure we land and communicate changes in a way that causes the least amount of friction.

**Comment by danielfmiranda** [comment]
Closing this issue as we have already taken care of the majority of the work for this rollout in the past two sprints (May 10- May 23 2021, May 24-Jun 6 2021).

This means that we have implemented the new templates for the streamfields are rows method, and we also updated some components to take advantage of the "full-width" functionality, this includes:

- Full Width Images
- Full Width Youtube Video Embeds
- Full Width Iframes
