### ISSUE TITLE
Add Next-> button to bottom of With Great Tech Comes Great Responsibility

### ISSUE THREAD

**Issue by CubeOfCheese** [mozilla/foundation.mozilla.org#6609]
### Describe the feature request
https://foundation.mozilla.org/es/initiatives/great-tech-great-responsibility/
When I reached the bottom of the intro for With Great Tech Comes Great Responsibility, I was confused because I expected there to be more content but it just ended. I then scrolled up and realized I had to click to the next page from the left side menu.
My request is for a "next" button to be added or a link to the next page in the series at the bottom of the article.
 
### Screenshots / mock-ups
<img width="1057" alt="Screen Shot 2021-04-29 at 12 57 45 AM" src="https://user-images.githubusercontent.com/16740469/116519143-f5a0b980-a885-11eb-93e4-86420316e21b.png">

**Comment by CubeOfCheese** [comment]
Yeah it does!

**Comment by Pomax** [comment]
closing as addressed.
