### ISSUE TITLE
Remove current pages from static build system

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#661]
Creating as a placeholder epic for visibility on the boards. No need to assign this to a specific milestone.

Current pages = "everything that's not managed by the Mezzanine 'pages' app" (not `/opportunity/`)

**Comment by Pomax** [comment]
can we elaborate on what "current pages" are?

**Comment by alanmoo** [comment]
Update original ticket

**Comment by gvn** [comment]
This is done I think?
