### ISSUE TITLE
[Data Visualization] Summarize Survey Findings

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#6645]
Summarize survey findings from the internal staff survey and share recommendations with dev and design team.

_______________________

This issue follows up on the results from issue: 
[Data Visualization] Stakeholder Needs Assessment https://github.com/mozilla/foundation.mozilla.org/issues/6524

**Comment by sabrinang** [comment]
**Update:** 
I'm wrapping up response collection and I DM'd 11 people _(Eeva, Lindsay, Amy, Mehan, Temi, Jen, Kathy, JesseW, Jon, Xavier, KristinaG)_ to ensure they are aware. One of them mentioned they will fill it out early next week and most I haven't heard back from most since it is Friday. I will leave the form open early next week.

We currently have 13 responses so far.

**Comment by sabrinang** [comment]
@kristinashu for review? The survey results are transferred to slides to be viewed more easier. Context, methodology and summary slides are included at the beginning: https://docs.google.com/presentation/d/1YOjMQ5vQf1-scF-bZvkOGVN6Tr5iOpABR_NAKuRiS9Y/edit?usp=sharing

Results on Google Forms: https://docs.google.com/forms/d/1rq4SMsFiKfj7kYrvguoKHTrIs1liSx_bONWeKAwadFg/viewanalytics

FYI — I'm not sure if the remaining few DM'd people will respond but the form is still technically open

**Comment by kristinashu** [comment]
This is great! Do you think the next step is to meet with Ben and Anil to make a final decision on whether or not to commit to Datawrapper?

**Comment by sabrinang** [comment]
Yes that next step makes sense to me. We will use these summary results to inform how we decide on if the Datawrapper service we'll provide staff is appropriate with their needs and wants.

**Comment by kristinashu** [comment]
Nope! I plan to share the results in the A&E slack channel as part of a sprint highlights post.
