### ISSUE TITLE
investigate whether wagtail images are a perf. bottleneck

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6669]
Most of our n+1 performance hits are from wagtail image renditions, and I'd like to understand whether we're using Wagtail images wrong, or whether other projects have this problem too and it's something that might be worth bringing up as seeking an alternative for.

This issue is for the discussion/investigation, with the outcome being "we know why it does what it does, and we have (several) ways forward that we can now look into".

/cc @KalobTaulien @benhohner @danielfmiranda

**Comment by Pomax** [comment]
Deprioritising this due to frontend caching, but we should still figure out what's up with this "eventually".

**Comment by KalobTaulien** [comment]
Ping me when this ticket is in progress. I have insight into why the images are bottlenecks and how to defer the rendition process.

**Comment by jamilasnell** [comment]
Let's look at Scout for this issue!

**Comment by jamilasnell** [comment]
Closing this as this issue is moot now. Create a new ticket if this issue pops up again
