### ISSUE TITLE
Investigate all Full-width blocks not displaying in fo’mo

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6672]
Publications and Blog should have a wide image and wide iframe setting. 

Look into why these aren't showing up the way we expect. 

**Note**: The wider image option is already on publication article pages.

**Comment by KalobTaulien** [comment]
## Findings:

#### Blog:
- [ ] Does not have a wide iframe setting. All iframes are "wide" by default. 
- [x] Has an image and wide image 

#### Article page:
- [ ] Does not have a wide iframe setting. 
- [x] Has an image and wide image (and an full-width image)

---

For the wide iframe setting, I'm not sure if this is worth doing now, or when we tackle the larger global streamblock issue at a later date. For efficiency it would be best to add that in during the streamfield template uplift, but if a normal vs wide iframe setting is _needed_ right now, we could work this in. 

@benhohner what are you thoughts on this? You might know something I don't regarding the above statement

**Comment by benhohner** [comment]
@KalobTaulien unless the generic streamblocks will be done by early June, we'll need a wide iframe on blog and article pages by the end of this sprint.

How much effort will it take to get the wide iframes added the temporary way?

**Comment by KalobTaulien** [comment]
Probs an hour or two, it's getting kind of messy in that template. I'll make us at ticket for this.

**Comment by KalobTaulien** [comment]
Ticket opened at #6714 — I'm going to close this ticket because it was just an investigation.
