### ISSUE TITLE
Storytelling Wagtail Component: Wide and Full-width Images

### ISSUE THREAD

**Issue by natalieworth** [mozilla/foundation.mozilla.org#6676]
### Intro
To allow for more compelling storytelling on the Wagtail blog pages, we want to implement a wide and full-width image option within the Wagtail blog template.

Full-width images should be 100% of the viewport width with no margin or padding on the x-axis
Wide images should be a boostrap 12-col width with the default bootstrap 15px padding on each side.

![Screen Shot 2021-05-09 at 10.01.59 PM.png](https://images.zenhubusercontent.com/57a10963e40e5714b16cdb3b/532193ef-e951-4a8c-8c01-5641dea65561)

---

###  Design -> Dev Handoff Checklist

- [x] Design has been finalized 
- [x] Link to original design ticket ([original design ticket is in #829](https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozillafoundation/design/829)
- [x] [Link to Redpen](https://redpen.io/p/wu5fe36cd1366a0cad)
- [x] [Link to Figma file](https://www.figma.com/file/OTFsYEpkuXcR6HgowgDlyO/Wagtail-Storytelling-Components?node-id=0%3A1)
- [x] Desktop, tablet, and mobile mockups are included

Please reach out to @natalieworth if you have any questions or need clarification! :)

---
Copied from Design ticket:
For the addition of full-width images (as seen in the image below), are we able to add a full-width image button underneath the wide image option?

![Screen Shot 2021-05-09 at 9.59.19 PM.png](https://images.zenhubusercontent.com/57a10963e40e5714b16cdb3b/b2722d7a-50be-4fb7-8901-9f2fb28b8154)

I have designed this to be within our 16:9 ratio for the full-width images. I believe a lot of the images on the site use that ratio instead of the 16:6, so is it possible to add/change the instructions at the top to 16:9 ratio OR have instructions beside the full-width image check-box? Something along the lines of 'Images must be 1600 x 900 aspect ratio and a minimum of 300dpi'

Here's an example of dribbble's guidelines:
![Screen Shot 2021-05-09 at 10.32.19 PM.png](https://images.zenhubusercontent.com/57a10963e40e5714b16cdb3b/32817f40-4c56-4e8a-a370-a6d24b288619)

And their error message:
![Screen Shot 2021-05-09 at 10.35.58 PM.png](https://images.zenhubusercontent.com/57a10963e40e5714b16cdb3b/a9b620a5-2209-45ab-a478-942e183ed745)

**Questions:**
- do we want to limit the size (e.g. 10MB max?)
- are we able to set a minimum dpi so people don't upload low-res files?
- I would also prefer that images are not cropped since it's difficult to control cropping and have it still look decent at full-width size

**Comment by natalieworth** [comment]
I included some considerations/ questions about how to implement this in the original design ticket: https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozillafoundation/design/829

**Comment by Pomax** [comment]
### Describe the feature request
At the moment we have normal width images, which will follow the column count of the rest of the page, and then we have wide images which break out of that and move to col-12 to be a little bit wider than the rest of the pages content.

We would like to have images that span from one edge of the page to the other. After we update the templates to use the streamfields as rows method, this should be a matter of doing the following: 
- Add a flag to images for "full-width", similar to how we have a flag for "wide"
- Add some logic in the templates to properly display full width images. 


Here is an image showing an example: 
![image](https://user-images.githubusercontent.com/18314510/122296051-ce8e5d80-ceae-11eb-8654-932c68d98825.png)
