### ISSUE TITLE
Link People and Projects

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#668]
First iteration is simply adding links to projects from People profiles.

Later iteration will involve building out infrastructure to have meaningful connections between people, projects, issues, etc. on the backend.

**Comment by xmatthewx** [comment]
I don't think we'll link projects to existing site profiles. Much easier to wait until we can pull in people from Pulse, and maintain the project-profile links there.

**Comment by alanmoo** [comment]
Added dependencies for clarity.

**Comment by techac** [comment]
Hello @alanmoo can you please elaborate...
I am new to this project and this might be a good start i guess..thanks..:)

**Comment by alanmoo** [comment]
Hi @techac, I'm not quite sure what I was referring to for this issue so I'm going to close it. We've addressed some of the things it was talking about anyway. But take a look at these two issues, they might be good ones to start with:

https://github.com/mozilla/foundation.mozilla.org/issues/1805
https://github.com/mozilla/foundation.mozilla.org/issues/1643
