### ISSUE TITLE
Create an AWS S3 bucket for visual regression testing

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6687]
We need a new bucket for visual regression testing, set to "entirely" public as it will be hosting files that need to be web-accessible. I would recommend something like `foundation-mozilla-org-visual-ci` so that it's nice and unique while also relatively concisely describing its role.

We'll also need to add an access key and secret to the repo secrets (`AWS_ACCESS_KEY_FOR_VISUAL_CI` and `AWS_ACCESS_SECRET_FOR_CI` should work) so that the visual CI task can correctly make use of the new bucket.

**Comment by tomusher** [comment]
This has been created. Details in Engagement Team 1password under 'foundation-mozilla-org-visual-ci S3 Bucket Owner'
