### ISSUE TITLE
Step 2. Add localization "staging" site (DevOps)

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6704]
## Acceptance criteria

- [ ] We need a dedicated pipeline for testing the work. @tomusher we'll need your help with this. 
  - [ ] Needs CI setup to help us merge the main review branch into master later with no problems.

**Comment by KalobTaulien** [comment]
@tomusher I made this branch: https://github.com/mozilla/foundation.mozilla.org/tree/wagtail-localize-2021 (wagtail-localize-2021). Could we use this for pipeline testing, as a pseudo-staging site for _only_ localization work?

**Comment by tomusher** [comment]
The `foundation-localize` app is now available in Heroku configured as discussed with Kalob. Let me know if any changes are needed!
