### ISSUE TITLE
Step 4. Add in wagtail-localize and enable it in our settings

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6706]
## Acceptance criteria

- [x] Add in wagtail-localize. Enable it in the settings, but don't do anything else with it yet. Let's take this in small steps. 
  - [x] Make sure tests pass. 
  - [x] Add in wagtail-localize into the requirement dependencies 
  - [x] Merge into review branch and let CI run for higher future-merge confidence

**Do not** do all the localization work. Let's just get this setup and running in a bare-bones manner at first.

**Comment by Pomax** [comment]
associated PR landed but didn't auto-close this issue
