### ISSUE TITLE
Step 5. List out which models and fields need translating

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6707]
## Acceptance criteria

- [ ] List which models need translating and which models don't. (including snippets, please)
- [ ] List out which fields should be TranslatableField and which fields should be SynchronizedField.

**Ideal scenario**:
If @TheoChevalier could create a Google Sheet listing which models need translating, and which fields in each model need to be a:
 * TranslatableField
 * SynchronizedField
 * Ignored

**Comment by TheoChevalier** [comment]
I’ll work on it this week :)

**Comment by TheoChevalier** [comment]
WIP here, but I’ll need to finish this on Tuesday, so keeping the ticket opened https://docs.google.com/spreadsheets/d/1AU7pxboZoBiVcbTpZO-VUMAhxZwx5mdEH_FBLfo2D-w/edit?usp=sharing
