### ISSUE TITLE
Step 8. Make the footer language picker work.

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6710]
This may or may not be a problem, I'm not entirely sure. 

I'm going to assume we're going to run into things we need to work on for this task. This task is largely unknown and could possibly _not_ be a problem, or may be a hard one to solve.

## Acceptance criteria

- [x] Change the language picker in the footer of the website to properly set the language of the site

**Comment by Pomax** [comment]
Initial testing shows that the URL gets updated correctly, but I can't seem to figure out how to manually make translations for a page kick in, so I can't solidly confirm this works quite yet.

**Comment by Pomax** [comment]
It looks like this will rely on getting the "unlocalized" URL for a page, which doesn't seem possible without writing a custom tage? Both `<p>{% pageurl page.localized %}</p>` and `<p>{% pageurl page %}</p>` will yield `/en/` for the homepage, for example.

**Comment by Pomax** [comment]
This may also fix https://github.com/mozilla/foundation.mozilla.org/issues/4290
