### ISSUE TITLE
Step 9. Pontoon integration

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6711]
I'm going to estimate this ticket to be a 16 because I remember this being difficult to implement. If I'm wrong, please feel free to correct it. 

**Note**: This may require Karl's help and some of his time. 

## Official pontoon integration docs

https://www.wagtail-localize.org/how-to/integrations/pontoon

## Acceptance criteria

- [x] Generate an SSH keypair for Wagtail Localize

```
+---[RSA 3072]----+
|       ...o.o=E+B|
|       ...o..oooo|
|        o. + .=oo|
|       . o  *..+=|
|        S. + oo=o|
|          =  o*.o|
|           o. oB.|
|            .oo.o|
|           .oo.. |
+----[SHA256]-----+
```

- [x] Create a git repository 
  - https://github.com/MozillaFoundation/wagtail-localize-foundation-l10n

- [x] add the public key (wagtail-localize-key.pub) that you created as a deploy key

![image](https://user-images.githubusercontent.com/177243/120682682-95d39a80-c451-11eb-923d-70064af2ba55.png)

- [x] Install the wagtail-localize-git plugin
  - added in PR commit https://github.com/mozilla/foundation.mozilla.org/pull/6794/commits/55bdd43402e10d698936d8469f2e7c141932f51e

- [x] Add the SSH private key as BASE64-encoded heroku env var

![image](https://user-images.githubusercontent.com/177243/120685846-2e1f4e80-c455-11eb-91ec-d3713680a19c.png)

- [x] Add the `.profile` file for Installing the SSH private key during deploy, see https://github.com/mozilla/foundation.mozilla.org/commit/bc9117b65d17482b57427ac5d6fcd22b33c5331d
  - added in PR commit https://github.com/mozilla/foundation.mozilla.org/pull/6794/commits/db2910a831193b77a6fc43484b5c16520da9408d

- [x] Configure the wagtail-localize-git plugin (see [docs](https://www.wagtail-localize.org/how-to/integrations/pontoon/#configure-the-wagtail-localize-git-plugin))

![image](https://user-images.githubusercontent.com/177243/120685210-70945b80-c454-11eb-9506-5c995a3ef529.png)

- [x] land PR https://github.com/mozilla/foundation.mozilla.org/pull/6794

- [x] explicitly deploy wagtail-localize-2021 on heroku

- [x] test pontoon integration using test content (i.e. a default install)

- [x] copy the prod db to the localization testing app, scrubbed the same way as for staging (https://github.com/mozilla/foundation.mozilla.org/issues/6827)

- [x] test pontoon integration on real data

**Comment by Pomax** [comment]
I've set up https://github.com/MozillaFoundation/wagtail-localize-foundation-l10n as repo for testing, but we're blocked on https://foundation-localize.herokuapp.com/cms/ apparently trying to fetch assets from foundation.mofostaging.net, rather than... you know... _itself_

**Comment by Pomax** [comment]
the heroku app has been fixed, so this work can now proceed

**Comment by Pomax** [comment]
@TheoChevalier let's test this integration on Monday?

**Comment by TheoChevalier** [comment]
I’ve been playing with a test page, and was able to confirm sync is working both ways! https://github.com/MozillaFoundation/wagtail-localize-foundation-l10n/commits/master

**Comment by Pomax** [comment]
pontoon integration works \o/
