### ISSUE TITLE
Step 10. Documentation

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6712]
## Acceptance criteria

- [ ] Documentation:
  - [ ] Write documentation on how to implement and support pontoon with any gotchas documented as well. Might be useful to put this in the wagtail-localize.org docs as well.
  - [ ] We said we'd write docs for moving away from wagtail-modeltranslation and contribute it back to wagtail-localize. Lets write documentation on how we moved away from wagtail-modeltranslation to wagtail-localize, and commit the changes [to the wagtail-localize docs](https://www.wagtail-localize.org/how-to/migrate/wagtail-modeltranslation/)

**Comment by KalobTaulien** [comment]
Adding Pomax to this ticket for Pontoon documentation.

**Comment by Pomax** [comment]
@TheoChevalier hopefully you don't mind if I assign this issue to you, since you have the deepest knowledge here.

**Comment by benhohner** [comment]
@TheoChevalier can you please put relevant wagtail-translate documentation into our new Notion engineering handbook? https://www.notion.so/mozilla-foundation-engineering/Backend-c2876a1a86e84b37b4e7d1d2e26feba8

**Comment by TheoChevalier** [comment]
Hey folks, sorry for the delay, I have added some MVP guides to Notion:
https://www.notion.so/mozilla-foundation-engineering/Wagtail-localization-a8313a879d0a4b9290350809cb7141a7

@benhohner Would this work?

**Comment by bheasman** [comment]
Closing off the back of previous comments.
