### ISSUE TITLE
Pregenerate the testing database whenever master updates

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6729]
We should generate a testing db based on master whenever code lands in master, and save that db to AWS, so that branches against master can pull down that prebuilt DB and only need to run `python manage.py migrate` rather than go through the entire migration chain and `load_fake_data` pass, both of which take a considerable amount of time to run. E.g.

- new workflow file looking at updates to the `networkapi` dir on the `main` branch
- kick off an action that builds the repo up to to point where we have run `load_fake_data`
- dump the pg database to file using `pg_dump`
- store that file as GH actions artifact for use by other workflows

Then:

- update the existing workflow action for PRs to look for that artifiact
- run `pg_restore` to "instantly" set up a fully functional database rather than running `load_fake_data`
- then run `inv migrate` to catch up the database to the PR's code.

**Comment by mtdenton** [comment]
Great idea, never got executed. Marking for purge.
