### ISSUE TITLE
[Publications] Single Article Page

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#6730]
Currently article pages exist only as child pages to a publication page that is created. There have been requests to use only an article page (without a parent publication page)

**Note: added:** Currently Article Pages _must_ live within a Publication Page. We need to enable them to live anywhere in the wagtail tree. 

## Criteria:
- [x] Need to unrestrict Article Pages 
- [x] May need to give pages the permission to have Article pages as a child page (`subpage_types = ['...', 'articlepage']`) 
- [x] Will need to "ignore" the parent page and next/prev pages and the buttons in the template associated with them since they wont have any real siblings and the parent page could be _any_ page type. 
  - [x] We want to ensure that Article Pages under Publication Pages still function as expected.

**Comment by kristinashu** [comment]
Note this is needed for the AI & Content working group YouTube Regrets Reporter shareout launching in June.

**Comment by Pomax** [comment]
is there a deadline date that we can add to the original comment? Because if it's before June 6th, we need to make sure it gets prioritised such that it happens in the first week of the May 24-June 6 sprint, rather than the second.

**Comment by kristinashu** [comment]
June 6 would be great! The project is launching at the end of June but need time to do other work on it like have Christian add in some data visualizations.

**Comment by kristinashu** [comment]
Or June 7. Stupid Github Sprint made it due on a Sunday!

**Comment by kristinashu** [comment]
Realizing the single article pages will also need the feature that the publications template has - an optional PDF download button. Please open a new ticket if this should be a separate but related issue.

**Comment by sabrinang** [comment]
@kristinashu The article pages were updated with optional download buttons and subtitle field features in the hero section here https://github.com/mozilla/foundation.mozilla.org/issues/6166. This was done to support the Data for Empowerment publication feature requests in February — live example here: https://foundation.mozilla.org/en/data-futures-lab/data-for-empowerment/shifting-power-through-data-governance/

**Comment by kristinashu** [comment]
Ah ok good! Thank you for pointing that out Sabs!
