### ISSUE TITLE
Investigate slow page load times on fo'mo

### ISSUE THREAD

**Issue by benhohner** [mozilla/foundation.mozilla.org#6750]
### Details

Requests on fo'mo take upwards of 20 seconds, sometimes timing out when you're logged in to Wagtail (because Cloudflare caching is disabled when logged in). We need to investigate what is slowing Wagtail down and fix it

### Implementation Checklist

- [ ]  Investigate what is slowing down fo'mo using Papertrail, Scout, django debug toolbar, memory profiling tools e.g. Pympler, etc.
- [ ] Implement a fix
- [ ] (optional) look into ways to load test
- [ ] (optional) port any fixes applicable to donate over to donate.

**Pre-Merge**:
- [ ] Code follows our code style guide [documentation WIP]
- [ ] Code is documented according to our documentation standards [Need to create]
- [ ] Unit Test Coverage [need to create coverage target and tooling]
- [ ] Integration Test Coverage [need to create guide]
- [ ] Any technical debt is documented (todo/fixme => needs an issue linked in comments)
- [ ] Any follow-up tasks are created before a PR is merged
- [ ] Code peer-reviewed by at least one other developer

**If the work had design-dev handoff, also signed off by a designer**:
- [ ] Code has error handling with clear error messages
- [ ] Incomplete features are hidden behind feature flags (for features without Update or Delete DB migrations)
- [ ] Secrets (github actions + heroku) are up to date for CI, review apps, and staging

**Post-Merge, Pre-Production Deploy**:
- [ ] Code is deployed to Staging
- [ ] Code is manually verified to work on staging (rare, but important)
- [ ] Test management commands that may need to be run
- [ ] Release scripts are up to date (rare, but important)

**Production Deploy**:
- [ ] Production deploy successful
- [ ] Notify Stakeholders

**Comment by Pomax** [comment]
Possible thing to investigate: see whether reducing the number of user groups reduces the time required to load (by cutting down DB joins on page permissions before determining whether a page can be served at all)

**Comment by Pomax** [comment]
time and a concerted SRE effort passed this issue by to a large enough degree that the original motivation behind this issue has been addressed since.
