### ISSUE TITLE
Step 6.5. Check that PNI localization works and adjust categories if needed.

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6760]
Epic: #6703 

After migrating snippets to be translatable, we want to make sure PNI products are still showing up as they normally do. 

I suspect multi-lingual categories based on URLs is going to cause us some trouble. I'm estimating a high 8 for this, but there's also a chance everything will "just work". 

### Acceptance criteria
- [x] Make sure all products that _are_ supposed to show up in the PNI home page continue to show up 
- [x] Make sure al products that _aren't_ support to show up in the PNI home page continue to be hidden (ie. non-published draft pages) 
- [x] Make sure the category views continue to work in English and products are being displayed
- [x] Make sure the category views show all the right products in English 
- [x] Make sure the category views work in other languages (ie. French) and products are being filtered
- [x] Make sure the category views work in other languages (ie. French) and that they display products in French
- [x] Make sure languages continue to filter all products properly and show what we expect them to show.

**Comment by Pomax** [comment]
I've confirmed all these things to be the case using a production database copy with the current wagtail-localize-2021 code (after running `inv catchup`).
