### ISSUE TITLE
[Epic] YouTube Regrets Reporter Landing

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#6789]
Epic for YouTube Regrets Reporter report share out landing page design

## Links
- [Copy doc](https://docs.google.com/document/d/1pn8CUywtNo2J3rIlgfIKqCyJor1UiiLGqziHzVi_muI/edit?ts=60b6266d#heading=h.6v1ik6cnpxi8)
- [Meeting notes doc](https://docs.google.com/document/d/1SPbtrGhQDs7aSWJt9qx1kqgagGCrouUuDSNUbV2LTrY/edit#)

## Rough Timeline (assuming 2 weeks for dev time)
- June 3: Present 3 rough sketches/wireframes to Brandi (get feedback during the meeting) https://github.com/mozillafoundation/design/issues/850
- June 7: Share final wireframe
- June 9: Present 3 moodboards for the metaphor and look & feel for the landing page https://github.com/MozillaFoundation/Design/issues/870 
- June 16: Present initial rough high-fidelity design mockups to Brandi and Torchbox for feedback [need ticket]
- June 21: Final mockup [need ticket] and prep for dev https://github.com/mozillafoundation/design/issues/868
- June 21: Dev starts [need ticket for design QA]
- July 5: Launch

**Comment by wilhitem** [comment]
Updated timeline:

    June 3: Present 3 rough sketches/wireframes to Brandi (get feedback during the meeting) MozillaFoundation/Design#850
    June 7: Share final wireframe
    June 9: Present 3 moodboards for the metaphor and look & feel for the landing page MozillaFoundation/Design#870
    June 16: Present initial rough high-fidelity design mockups to Brandi and Torchbox for feedback [need ticket]
    June 21: Final mockup [need ticket] and prep for dev MozillaFoundation/Design#868
    June 21: Dev starts [need ticket for design QA]
    June 25: Mozilla dependencies for Torchbox dev's implemented
    June 28th: Copy finalized (Need to check w/ Brandi)
    June 28th: Torchbox development begins
    July 5th: Dev implementation complete
    July 6th: QA complete (Need to double check with design team tomorrow)
    July 8th: Launch

**Comment by kristinashu** [comment]
It's live https://foundation.mozilla.org/campaigns/regrets-reporter/findings/ and is a masterpiece!
