### ISSUE TITLE
Copy the prod db to the localization testing instance (June 9 deadline)

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6827]
In order to close out #6711, let's copy the prod db over to the localization testing heroku instance, with the same PII scrubbing that we do for staging by June 9 so we can finish testing this week.

**Comment by Pomax** [comment]
@TheoChevalier I assigned you to this one as well so you can mark it as "good to go" when we're satisfied with the first pontoon integration testing pass.

**Comment by tomusher** [comment]
@TheoChevalier @Pomax Can you confirm if this is still required?

**Comment by Pomax** [comment]
we can close this issue, we've done this a few times now =)
