### ISSUE TITLE
Storytelling Wagtail Component: Wide and Full-width iframe

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6833]
(based on: https://github.com/mozilla/foundation.mozilla.org/issues/6676)

### Intro
To allow for more compelling storytelling on the Wagtail blog pages, we want to implement a wide and full-width iframe option within the Wagtail blog template.

Full-width iframes should be 100% of the viewport width with no margin or padding on the x-axis
Wide iframes should be a boostrap 12-col width with the default bootstrap 15px padding on each side.

![Screen Shot 2021-05-09 at 10.01.59 PM.png](https://images.zenhubusercontent.com/57a10963e40e5714b16cdb3b/532193ef-e951-4a8c-8c01-5641dea65561)

---

Copied from Design ticket:
For the addition of full-width images (as seen in the image below), are we able to add a full-width image button underneath the wide image option?

![Screen Shot 2021-05-09 at 9.59.19 PM.png](https://images.zenhubusercontent.com/57a10963e40e5714b16cdb3b/b2722d7a-50be-4fb7-8901-9f2fb28b8154)

**Comment by jamilasnell** [comment]
SIMON IS KING!
