### ISSUE TITLE
Storytelling Wagtail Component: Wide and Full-width Video With Looping Option

### ISSUE THREAD

**Issue by benhohner** [mozilla/foundation.mozilla.org#6834]
### Intro
To allow for more compelling storytelling on the Wagtail blog pages, we want to implement a wide and full-width video option within the Wagtail blog template, with the option to make the video autoplay with looping with minimal user controls.

Full-width videos should be 100% of the viewport width with no margin or padding on the x-axis
Wide videos should be a boostrap 12-col width with the default bootstrap 15px padding on each side.

![Screen Shot 2021-05-09 at 10.01.59 PM.png](https://images.zenhubusercontent.com/57a10963e40e5714b16cdb3b/532193ef-e951-4a8c-8c01-5641dea65561)

---

###  Design -> Dev Handoff Checklist

- [x] Design has been finalized 
- [x] Link to original design ticket ([original design ticket is in #829](https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozillafoundation/design/829)
- [x] [Link to Redpen](https://redpen.io/p/wu5fe36cd1366a0cad)
- [x] [Link to Figma file](https://www.figma.com/file/OTFsYEpkuXcR6HgowgDlyO/Wagtail-Storytelling-Components?node-id=0%3A1)
- [x] Desktop, tablet, and mobile mockups are included

Please reach out to @kristinashu if you have any questions or need clarification! :)

**Comment by danielfmiranda** [comment]
Hi Everyone have a quick question. 

I see that we have a video streamfield block already set up, which takes an embed url (the help text mentions youtube) and then renders the embedded player on the page. 

This is the item that I have added the functionality for wide and full-width too. But now I am questioning if that was the request, or, if the video is supposed to match the image above? 

If so, that should not be too difficult/time consuming to add, as I have already recreated the video player in the image above, in the "header image/hero video" ticket.
