### ISSUE TITLE
Update Readme to reflect unity changes

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#685]
Local dev instructions are no longer accurate. Not quite sure who would be best for this, tagging everyone for visibility.

**Comment by alanmoo** [comment]
@cadecairos Is this the last thing that we need to do re: unity? (I currently have no idea how deploy works...I think we're doing the 2 branch approach?)

**Comment by alanmoo** [comment]
Let's make this a priority, it's entirely unclear as to how deployments happen at this point in time.

**Comment by gvn** [comment]
@cadecairos If you can update the [deployment section](https://github.com/mozilla/network#deployment) I think I can update the rest.

**Comment by alanmoo** [comment]
Bumping into this milestone for visibility

**Comment by cadecairos** [comment]
I'll take this on today.

**Comment by gvn** [comment]
I feel like this is basically done...
