### ISSUE TITLE
Blog category snippet: add optional OG image and description 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#6870]
### Describe the feature request

Currently a blog category just shows the general /blog image and text. 

![image](https://user-images.githubusercontent.com/1068783/122265868-076a0a80-ce8e-11eb-9201-64ab5cd39ada.png)

It should show an image and text specific to the blog category. 

### Todo
- [x] Add optional field to upload an image
- [x] Add optional field to include description text (fall back text should be the category snippet text)

cc @Audreymofo

**Comment by Pomax** [comment]
I am moving this to the next sprint because this is going to collide with the localization work, and we want to get that landed before we do any snippet code revisions
