### ISSUE TITLE
Restore a deleted Wagtail page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#6871]
I mistakenly deleted this page https://foundation.mozilla.org/en/initiatives/artists-open-web and it's subpage several months ago.

Please restore it from our database so we can rebuild t. I believe if you go back 8 months you should see the content. 

cc @marcwalsh

**Comment by Pomax** [comment]
Unfortunately, we don't have backups going that far back, if it were 1 or 2 months we could probably still find it, but 8 is unfortunately lost to us.

**Comment by kristinashu** [comment]
Did you check the oldest possible back up for it? Small chance it's there.

**Comment by Pomax** [comment]
I have some offline copies of the db on my workstation that might go back a bit further, I'll try to dig them up and see if it has that page.

**Comment by kristinashu** [comment]
🤞

**Comment by Pomax** [comment]
I found _something_, does this look like the right page?

![image](https://user-images.githubusercontent.com/177243/123035024-7fa96200-d39f-11eb-90c0-5636b8e7233f.png)

**Comment by Pomax** [comment]
Ah, no, wait, there are sub pages, but they don't seem to have anything beyond a title heading:

![image](https://user-images.githubusercontent.com/177243/123035444-2ee63900-d3a0-11eb-9fa6-fff72e38d76e.png)

![image](https://user-images.githubusercontent.com/177243/123035458-3574b080-d3a0-11eb-95dc-a91f3d299a22.png)

![image](https://user-images.githubusercontent.com/177243/123035473-3b6a9180-d3a0-11eb-8328-a1eb1637e150.png)

**Comment by Pomax** [comment]
Rather than try to restore these pages as their original database record, given the content it might actually be easier to make new pages, since there's not a lot to each page.

**Comment by kristinashu** [comment]
Yay! Thank you Pomax! I can re-create them. Are you able to tell which Pulse criteria those pages are using?

**Comment by kristinashu** [comment]
Never mind, I think I got them https://www.mozillafestival.org/en/artists-open-web/
