### ISSUE TITLE
Step 1. Hero / banner 

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6878]
## Priority:
Accordion functionality should come first. See #6915  

## Design preview
![image](https://user-images.githubusercontent.com/1068783/123828895-cecb2780-d8b6-11eb-99e1-e7b367a633b8.png)

Links to Examples:
[Dynamic color gradient shift](https://book.mozillafestival.org/10-years-of-activism-community-and-collaboration) (the one from yellow to white)

## Acceptance criteria:
- [x] Title
- [x] Description 
- [x] Download link
- [x] Background image 
- [x] Start of the gradient background

**Comment by kristinashu** [comment]
Note: we're hoping that some of the elements will be animated but this could be done as a follow up ticket at the end

**Comment by kristinashu** [comment]
Link to the PDF is here https://github.com/mozilla/foundation.mozilla.org/issues/6890#issuecomment-874327960
