### ISSUE TITLE
Step 2. Introduction text

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6879]
## Design preview:
![image](https://user-images.githubusercontent.com/1068783/123829279-2cf80a80-d8b7-11eb-8090-6c1285780e00.png)

## Acceptance criteria:
- [ ] Spaced out content (with fade in transitions on scroll)
- [x] Formatted links
- [x] Lives inside the first gradient area
- [x] Text can be re-used in other areas of the page 
- [ ] Should use as many Bootstrap utility classes as possible before customizing the styling with SASS 
- [x] Illustration

**Comment by kristinashu** [comment]
Assuming this won't get animated.
