### ISSUE TITLE
Step 4. Offensive/Untrue/Bizarre section 

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6881]
## Design preview:
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/1068783/124321580-d1d24c00-db32-11eb-9ad0-5b0f269f2d92.png">

Same carousel functionality as section 04, users will click arrow to see the next slide.

## Acceptance criteria:
- [x] Title
- [x] Icon
- [x] Navigation arrows
- [x] Counter
- [x] Slides with:
   - [x] Title
   - [x] Intro
   - [x] Looping mp4 [(files are here)](https://drive.google.com/drive/folders/1aTcqi7hmNtaOXDA4H6F2aegmsh8cdKzA)
   - [x] Caption

**Comment by SimonDEvans** [comment]
MR [here](https://github.com/chris-lawton/foundation.mozilla.org/pull/10).
