### ISSUE TITLE
Step 6. Bar chart with lines

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6883]
## Design preview:
![image](https://user-images.githubusercontent.com/1068783/123829516-60d33000-d8b7-11eb-9351-6ad87aa9240b.png)
## Acceptance criteria:
- [x] Need a bar graph library
- [ ] Chart should be animated
- [x] Data matches these numbers ([spreadsheet](https://docs.google.com/spreadsheets/d/1a2wX3hR6fTmJwGY68HLE9TgSs_cRcpC29y3v3PtO1Hk/edit#gid=176035906))

## Unknowns:
- [x] Which chart library to use

**Comment by kristinashu** [comment]
Graph was made responsive here https://github.com/mozilla/foundation.mozilla.org/issues/7014

There was a error in the values and will be fixed in https://github.com/mozilla/foundation.mozilla.org/issues/7036

I'm going to assume it won't animate in.
