### ISSUE TITLE
Step 12. Primary (bottom) text section

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6889]
## Design preview:
![image](https://user-images.githubusercontent.com/1068783/123831292-089d2d80-d8b9-11eb-857e-0b633fadceb8.png)

## Acceptance criteria:
- [ ] Illustration
- [ ] Inverted bootstrap colors 
- [ ] Light text colors 
- [ ] Title 
- [ ] Subtext
- [ ] Lead text sections with horizontal rules 
- [ ] Final subtext at the very bottom

**Comment by SimonDEvans** [comment]
MR [here](https://github.com/chris-lawton/foundation.mozilla.org/pull/8).
