### ISSUE TITLE
Step 13. Download pdf / contributor section

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6890]
## Design preview:
<img width="656" alt="image" src="https://user-images.githubusercontent.com/1068783/122826582-302c3e80-d298-11eb-8ddc-95d32e15fee2.png">

## Acceptance criteria:
- [x] 2 columns 
  - [x] Download pdf section with title and link
  - [x] Download extension section with title and link (similar to the buttons on https://foundation.mozilla.org/en/campaigns/regrets-reporter/)

**Comment by kristinashu** [comment]
I've uploaded the PDFs to our Wagtail Documents folder so we can easily update it - https://foundation.mozilla.org/documents/214/YouTube_Regrets_Report.pdf
