### ISSUE TITLE
Create a wagtail page for the new YT Regrets template (backend)

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6891]
Need a backend dev to create a new URL with an empty template for frontend devs to work with to inject each of the sections into the template. 

This will help keep the page cleaner and more maintainable if each section is in an include file and simply included into the main template page. 

## Acceptance criteria
- [ ] URL pattern for the YouTube Regrets page ~(may conflict with the existing YouTube regrets URL and may require a Wagtail page redirect)~ https://foundation.mozilla.org/campaigns/regrets-reporter/findings
- [ ] Create an empty template for the frontend developers to start working with 
- [ ] Ensure this URL is added to our sitemap.xml 

## Unknowns: 
* ~Is this replacing the current youTube regrets page?~ No. ~If so, we can strip out the old fields from the page and re-use the original template. If we did that, the sitemap would auto-generate this URL for us and we wouldn't need to create a URL path.~

**Comment by kristinashu** [comment]
URL should be https://foundation.mozilla.org/campaigns/regrets-reporter/findings
