### ISSUE TITLE
Customize UI return

### ISSUE THREAD

**Issue by muffenme** [mozilla/foundation.mozilla.org#6894]
I currently don't like the clean looks of Firefox icons used.  They look like someone 2 minutes on these icons and then said, lets call it the day.  To me it looks lazy.  Let us as user decide how we want our browser to look like.

The image below is a UI that looks bad.  This is the new ui.
![now](https://user-images.githubusercontent.com/9914938/122592091-4046e280-d03a-11eb-85c9-c8cb2140e107.jpg)

Previous UI, that starting to look bad.
![older](https://user-images.githubusercontent.com/9914938/122592602-de3aad00-d03a-11eb-8b3f-a54deab12c09.jpg)

This is a much better UI from Firefox pass
![better look](https://user-images.githubusercontent.com/9914938/122592718-0c1ff180-d03b-11eb-8255-0caabcb2ce3c.jpg)

Let the user decide on which UI they want and not force only one that people would dislike.

**Comment by TheoChevalier** [comment]
Hi,
This repository is not about Firefox, you can submit constructive feedback on https://mozilla.crowdicity.com/
