### ISSUE TITLE
Google Search Console (GSC) verification

### ISSUE THREAD

**Issue by benhohner** [mozilla/foundation.mozilla.org#6911]
We need to add the Google provided HTML file to the root of the website to enable us to verify ownership of Google Search Console.

PM Ben for the HTML file as this ticket is public.

**Comment by Pomax** [comment]
unknown estimate, setting to 1 for now

**Comment by benhohner** [comment]
File name: googled2a9d510ca850787.html

Contents: 
```
google-site-verification: googled2a9d510ca850787.html
```
