### ISSUE TITLE
"Read more" functionality

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6917]
This needs to come first from the frontend. We basically want the "read more" functionality added to the page first, and then fill each of the accordion sections with their respective content. 

### Acceptance criteria:
- [ ] "Read more" needs to show more content in the gradient coloured part near the top of the page 
- [ ] "Read less" needs to show when the content is expanded

**Comment by kristinashu** [comment]
Should this also include "Read Less" criteria?

**Comment by KalobTaulien** [comment]
> Should this also include "Read Less" criteria?

Yep! I added that in, thanks for catching that @kristinashu!
