### ISSUE TITLE
Synchronize PNI page slug

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#6926]
The slug of [the buyersguide page](https://foundation-localize.herokuapp.com/cms/pages/1444/edit/) is [currently translatable ](https://github.com/MozillaFoundation/wagtail-localize-foundation-l10n/blob/master/templates/pages/homepage/privacynotincluded.pot#L12-L14), we should make it synchronized

**Comment by benhohner** [comment]
There's another issue for general page slugs
