### ISSUE TITLE
Add something about Web Monetization 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#6927]
Via https://airtable.com/tbljPmOCkK9JShaTS/viwpFvt3FxiVannif/reccv9dlPgNFaTdaS?blocks=hide

We'll be shortly enabling web monetization on the entire foundation site. One of our learnings from our original trial was that in order to increase adoption, we can't just rely on existing customers to discover Web Monetization, we need to promote it as well.

We need a way to display somewhere that we're supporting web monetization on the foundation website. We'll probably need design (in collaboration with eng) to think about the best way to do this. We'll also need to consider the ethical implications of directing support to Coil, which is currently the only monetization provider (There are multiple wallets, but only one provider. See below for more info on how it works).

### Links
- Web Monetization overview https://webmonetization.org/docs/explainer
- https://webmonetization.org/
- https://coil.com
- Contacts with the context: Janice Wait, Anil Kanji, Ben Hohner

### Recommended todos
- [x] Doing some background research and benchmarking around this
- [x] Meet with stakeholders to get their thoughts and sharing benchmarks for their input
- [x] Mock up a few options and gather feedback
- [x] Open implementation ticket(s)

**Comment by kristinashu** [comment]
We came across one example of this today!

![Screen Shot 2021-07-07 at 11 11 25 AM](https://user-images.githubusercontent.com/1068783/124830190-5efc1300-df2e-11eb-98cd-b77059a2c856.png)

**Comment by nancyt1** [comment]
Started a [design brief](https://docs.google.com/document/d/1UIs0-obwQfy_bTzBz-IdwLFVvRVcvHuOVrTMuVR_jzM/edit?usp=sharing) and started reaching out to Ben, Anil, and Janice for more context.

**Comment by nancyt1** [comment]
Created some mockups in [Figma](https://www.figma.com/file/r7XjTxEOBFzLO7o1kwbEro/Web-Monetization?node-id=6%3A2), gonna get feedback before narrowing down again.

**Comment by kristinashu** [comment]
These look great Nancy! It's nice to see the expansive exploration and lots of different options!

I am definitely curious to hear what the stakeholders think but I lean towards having it in the footer since it seems to make the most sense given the type of content and the level of priority of the cta (low). Bonus of footer direction is that we can also easily add it other sites like PNI.

I so also see value tho in creating a generic "inside content" component tho that staff can customize depending on the content (so the short text and link could be about donating, coil, newsletter signup, or a petition - whatever makes the most sense given the specific content). See https://github.com/mozilla/foundation.mozilla.org/issues/7112

**Comment by kristinashu** [comment]
Feedback from Anil:
- I am totally fine to put it as a footer link. We'll have to create a web monetization page - I'm unsure what kind of page type this should be, but I can provide the copy.
- In the Figma Nancy shared, she gave examples of the "along content" only (unless I don't know how to find the other stuff, which is entirely possible) - I find that a little too intrusive (for example, having that next to every blog) but like the idea of developing it out as an optional cta content creators could add
