### ISSUE TITLE
Make ExtendedYesNoField a subclass of ExtendedBoolean

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6929]
To avoid potential Django problems around changing a field's superclass, the ExtendedBoolean and ExtendedYesNoField are currently fully qualified, separate classes. However, one is basically "the other with a fourth value added to the choice list" so it would be nice to turn ExtendedYesNoField into `ExtendedYesNoField(ExtendedBoolean)`

**Comment by benhohner** [comment]
If we run into migration issues, don't do

**Comment by Pomax** [comment]
Closing, Daniel had an excellent idea concerning template/code extensions, and put that in place.
