### ISSUE TITLE
Convert ListBlock of Quotes to a Single Quote Block

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6934]
ListBlocks aren't supported in wagtail-localize yet. There's an RFC open in wagtail core to support ListBlocks by giving them a UUID, but it hasn't been worked on yet. 

Our ListBlock of Quotes accepts more than one quote (because its a ListBlock) but the template doesn't support more than one quote, so we can safely migrate the first quote in a ListBlock to a single quote.

## Acceptance criteria
- [ ] ListBlock needs to be removed
- [ ] A single quote block with the _first_ quote in the ListBlock needs to be created 
- [ ] A data migration should upload all ListBlock quotes automagically 
- [ ] Template needs to be updated (its currently a loop, but won't need to be anymore) 

## Ideas:
* Re-purpose the StructBlock that houses the ListBlock

**Comment by KalobTaulien** [comment]
Putting this ticket on the backburner. Most of the work is done, but it's going to add a level of complexity to the localization work that we aren't willing to jeopardize at the moment. So we'll tackle this in the future. 

PR #6936 for reference. 

Moving back to Backlog and updating the estimate to a 2.

**Comment by jamilasnell** [comment]
#ForRich?

**Comment by richbrennan** [comment]
New pull request: https://github.com/mozilla/foundation.mozilla.org/pull/7660
