### ISSUE TITLE
Related content section is pulling blog posts from all locales

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#6965]
Check the Related Content section at the bottom of https://foundation-localize.herokuapp.com/en/blog/lets-unfck-internet/
It’s now pulling content from all locales instead of the current one.

<img width="1209" alt="Capture d’écran 2021-07-01 à 17 12 35" src="https://user-images.githubusercontent.com/1294206/124148022-27e9b580-da87-11eb-93c5-81db79c243a2.png">

**Comment by Pomax** [comment]
This should no longer be the case when we switch to "real" related content (i.e. staff will pick related blog posts using a page chooser, see #https://github.com/mozilla/foundation.mozilla.org/issues/6753

**Comment by benhohner** [comment]
Do we need a temporary fix until we get #6753 completed so we can launch? Theo mentioned there's an issue with page choosers at the moment?

**Comment by TheoChevalier** [comment]
> Do we need a temporary fix until we get #6753 completed so we can launch? Theo mentioned there's an issue with page choosers at the moment?

Here’s the ticket about the page choosers https://github.com/mozilla/foundation.mozilla.org/issues/7034
