### ISSUE TITLE
404 page svg issue

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#698]
Our 404 page is currently not displaying the correct version of the svg illustration:

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/22157921/29723205-89c19a66-8978-11e7-8c2b-37feb97bff37.png">

**Comment by gvn** [comment]
Is this in Firefox?

**Comment by kristinashu** [comment]
Looks like this has been fixed https://foundation.mozilla.org/errors/404/ but please reopen if it is still an issue.
