### ISSUE TITLE
Page alias slugs are not kept in sync with the source page slug

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6982]
local tracking issue for the Wagtail https://github.com/wagtail/wagtail/issues/7168 issue

**Comment by Pomax** [comment]
(assignments mostly so either of us can update this if needed)

**Comment by KalobTaulien** [comment]
An idea is to register an after_page_publish Wagtail hook with code that's something like this:

```python
from wagtail.core.utils import find_available_slug

def on_page_publish():
    for alias in page.aliases.all():
        alias.slug = find_available_slug(alias.get_parent(), page.slug, ignore_page_id=alias.id)
        alias.save_revision().publish()
```

☝️ Credit goes to [Karl Hobley](https://github.com/kaedroho) for that snippet.
