### ISSUE TITLE
1 - Add color design tokens to tailwind

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#6984]
- remove redundant colours
- expand colour palette
  - Introducing data-viz colors that can work with our brand but accessible
  - possibly move to tailwind colour palette or slightly modify?

**Comment by sabrinang** [comment]
@fessehaye 
I worked on colors in https://github.com/mozillafoundation/design/issues/901 and giving you an update that our color tokens are now defined (see tokens.json https://github.com/MozillaFoundation/Design/blob/master/systems/tokens.json) and that our figma library is using figma tokens plugin to create styles in figma ready for use.
