### ISSUE TITLE
[YouTube QA] Regrets Rate by Country chart is cut off at narrow widths on Chrome/Safari

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7008]
"Regrets Rate by Country" graph in Chrome and Safari is cut off at narrow widths. Screen cap from staging:

![image](https://user-images.githubusercontent.com/1068783/124668230-673c4b80-de65-11eb-965e-338271f0d609.png)

Ideal the bars should before shorter. Screen cap from mockup:

![image](https://user-images.githubusercontent.com/1068783/124667948-00b72d80-de65-11eb-8f18-eb4365557fa9.png)

To do
- [ ] Update chart so it isn't cut off in Chrome and Safari

**Comment by helenb** [comment]
I can't assign myself but noting that I'll start with this one.

**Comment by helenb** [comment]
https://www.chartjs.org/docs/2.7.2/general/responsive.html#important-note explains about how to make the chart responsive. It's also important to disable the `maintainsAspectRatio` option.

As part of debugging this I added a custom event when the accordion drawer opens. Although I don't need this in the end, I have left it in place as it may be useful for sorting countup on the stats that are inside the accordion drawers.

See https://github.com/mozilla/foundation.mozilla.org/pull/7026
