### ISSUE TITLE
[YouTube QA] Updates to quote section

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7009]
- [x] Add nav arrows to narrow widths [high priority]
- [x] Images should all be landscape format (both desktop and mobile - currently 01 on mobile is portrait)[[Drive Folder](https://drive.google.com/drive/u/0/folders/1_QijhYuIMQfWSg-Ho-4asT6pgjVOV9EF)]
- [x] Quote text should be smaller font size (24 px) at narrow widths
- [ ] Spacing between bottom of quote and “Close” button should be smaller (is it possible to have the container change height depending on content?)

Screen cap from mock ups:
![image](https://user-images.githubusercontent.com/1068783/124668762-2bee4c80-de66-11eb-8c9b-b25746cdcd99.png)

**Comment by KalobTaulien** [comment]
For the last task in the list, we've opened #7110 to track that. I'm going to close this ticket as the rest of the work has been merged already
