### ISSUE TITLE
[YouTube QA] Swap background images for most recent illustrations

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7011]
Newest illustrations have more texture to them, please replace these for both desktop and mobile:
- [ ] Hero images 
- [ ] “What is a YouTube Regret?” background images
- [ ] Findings background images
- [ ] Update Regrets Icon 

All images are [here](https://drive.google.com/drive/folders/1tUDnYe0kXo5jb8i50fzQp4udVDzHj3sf?usp=sharing).

**Comment by helenb** [comment]
picking this one up.

**Comment by helenb** [comment]
PR: https://github.com/mozilla/foundation.mozilla.org/pull/7027
