### ISSUE TITLE
[YouTube QA] Accordion drawers improvements 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7015]
### Black background on hover
When hovering over Section 04 you see the black background behind it or something.

- [x] White background when hovering over Section 04

Screen cap from staging:
![image](https://user-images.githubusercontent.com/1068783/124671399-40ccdf00-de6a-11eb-9a95-0d7c3185cfcf.png)

### Animation
Seems like the accordions have an extra bounce which makes it feel more jarring and less smooth. The benchmark seems smoother https://ideasreport.com/2020/read/insight3/ 

- [ ] Remove extra animation bounce

**Comment by KalobTaulien** [comment]
It looks like the background (that gap when hovering) is fixed. I can't seem to find the PR for this though. 

The animation is a quirky one. We should consider getting a more frontend-y person to do this. I'm wondering if @danielfmiranda or @fessehaye would be able to pick this up?
