### ISSUE TITLE
[YouTube QA] Misc small styling updates

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7016]
- [x] “Our recommendation” Section: Title on desktop should be 52px
- [ ] Links on dark backgrounds should be light blue color: #B7B9FA
- [ ] Hero background gradient on mobile: gradient color should match desktop (blue/black and not grey)
- [ ] Tighten up some spacing to match the mockups (see two screen caps from staging below where it is too large)

<img width="445" alt="image" src="https://user-images.githubusercontent.com/1068783/124672325-ae2d3f80-de6b-11eb-992c-79dba293c1f9.png">

<img width="407" alt="image" src="https://user-images.githubusercontent.com/1068783/124672315-aa012200-de6b-11eb-84fb-c97f13d96b20.png">

**Comment by helenb** [comment]
PR: https://github.com/mozilla/foundation.mozilla.org/pull/7029
