### ISSUE TITLE
[YouTube QA] Copy updates 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7017]
Screen cap from staging:

- [x] Replace `5,234` with `3,362` (via @TheoChevalier - it needed to be updated in two places, updated the second one here https://github.com/mozilla/foundation.mozilla.org/pull/7013/commits/dd1f5ced6ffa3f014d85cb0acb5be43b6a068db7) (screen cap from mockup)
![image](https://user-images.githubusercontent.com/1068783/124673782-58a66200-de6e-11eb-9eb2-fb69777e6cdb.png)

- [x] Remove "Reported Videos" and "Other Videos" titles 
- [x] Capitalize "English" for consistency 
- [x] Capitalize all subtext in **all** black highlight boxes 
<img width="175" alt="image" src="https://user-images.githubusercontent.com/1068783/124673051-0add2a00-de6d-11eb-9ba6-ee398764e3c2.png">

- [x] Update "geographic discrimination" should read "geographic disparities"
![image](https://user-images.githubusercontent.com/1068783/124673258-63142c00-de6d-11eb-8272-1903039c4b14.png)

- [x] Update "accrued over 160 average days that the videos had been up at the time they were reported" to "accrued over an average of 5 months that the videos had been up at the time they were reported", and also change from "160 days" to "~5 months" on the black box below
![image](https://user-images.githubusercontent.com/1068783/124673337-89d26280-de6d-11eb-94ad-72b7ee0998d8.png)

- [x] Update headline to "non-English speakers are hit the hardest"
![image](https://user-images.githubusercontent.com/1068783/124673415-a66e9a80-de6d-11eb-8432-1d8dd586903b.png)

- [x] "data" should be all lowercase
![image](https://user-images.githubusercontent.com/1068783/124673575-e9c90900-de6d-11eb-85e1-3fe594506f81.png)

**Comment by wilhitem** [comment]
reviewed this in stage - the only one i'm unclear on is "Remove "Reported Videos" and "Other Videos" titles"

**Comment by kristinashu** [comment]
I all looks good! That reference was removed to you can't see it anymore (but it is still in one place - as it should be).
