### ISSUE TITLE
Page choosers are not linking to either page aliases or actual translations

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#7034]
The issue is mostly affecting the homepage, in particular the News, Highlights and Take action sections.

On https://foundation-localize.herokuapp.com/fr/, pages in these sections are linking to the English page, but here’s the expected behavior:
- While they’re not translated: they should link to the alias page.
- As soon as they are translated: they should link to the translated page.

https://foundation-localize.herokuapp.com/fr/blog/lets-unfck-internet/ for instance is translated, but it’s linking to https://foundation-localize.herokuapp.com/en/blog/lets-unfck-internet/
I’ve tried syncing the translations of the homepage after the Let’s unfck the Internet page got translated just in case it wasn’t automatic, but it didn’t change anything.

**Comment by jamilasnell** [comment]
It is currently blocked on PRs that are assigned to Kalob. Will move forward once Kalob returns!

**Comment by Pomax** [comment]
As far as I can tell this is now fixed in the localize branch:

![image](https://user-images.githubusercontent.com/177243/129639287-eb76b331-271d-450c-ae68-525419e1901e.png)
