### ISSUE TITLE
[YouTube QA] Add animations

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7051]
- [ ] All graphs should animate in
- [ ] All chunky numbers should count up
- [ ] Intro text fade in

Example of [pie chart](https://www.pinterest.ca/pin/277464027028208791/) animation and[ text fade in ](https://year-in-review.alltrails.com/c20b0523-ff1c-4566-9003-ce000c4629ad)but open to devs suggestions.

**Comment by benhohner** [comment]
@kristinashu do we still think it's worth it to implement these?

**Comment by kristinashu** [comment]
Nope, closing!
