### ISSUE TITLE
Make quote component available in Publications

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7057]
Fellowships & Awards and Simply Secure need this feature in order to publish their report

- [ ] Add quote component as an option in Publications template
- [ ] All styles and functionality of the component should be the same as on other pages

<img width="737" alt="image" src="https://user-images.githubusercontent.com/1068783/125137160-fe510f80-e0c0-11eb-8300-8bd2d447b30e.png">

cc @benhohner for triage

**Comment by KalobTaulien** [comment]
Let's create a new block for this, and not re-use the ListBlock (currently our Quote is a ListBlock but that's not localize-able)
