### ISSUE TITLE
"undefined" in header of admin site

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#707]
![2017-08-30 14_00_55-](https://user-images.githubusercontent.com/438003/29887517-b257ef86-8d8b-11e7-8d4f-c47862365795.png)

I'm not sure what this is or why it's there.

**Comment by kristinashu** [comment]
Is this still relevant now that we've moved to Wagtail?

**Comment by cadecairos** [comment]
Nope!
