### ISSUE TITLE
Follow-up for URL parameters support during redirects

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#7072]
This is a follow-up ticket from https://github.com/mozilla/foundation.mozilla.org/issues/6543

It looks like the issue has been partially fixed, now `subscribed=1` is kept, but UTM tags are still stripped.

Here are a couple URL examples:

https://foundation.mozilla.org/campaigns/apples-anti-tracking-plans-iphone/?subscribed=1&utm_source=email&utm_medium=email&utm_campaign=2020advocacy-fr&utm_content=appleidfathanks&utm_term=5382510
redirects me to https://foundation.mozilla.org/fr/campaigns/apples-anti-tracking-plans-iphone/?subscribed=1

https://foundation.mozilla.org/regrets?utm_campaign=youtuberegrets&utm_source=twitter&utm_medium=social&utm_content=1625741125%7C redirects me to https://foundation.mozilla.org/fr/campaigns/regrets-reporter/findings/

**Comment by Pomax** [comment]
Looking at the wagtail code, query arguments get stripped during the redirect middleware process in a way that the previous PR could not compensate for. I've filed https://github.com/wagtail/wagtail/issues/7339 on the wagtail side for this, with a PR incoming to patch this in our middleware override for now.
