### ISSUE TITLE
Audit terminology used in Wagtail

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/foundation.mozilla.org#7080]
When using the different content blocks in Wagtail I noticed the help text included reference to whitelisting domains. 

Specifically, I found this on the MozFest site editor when adding an iFrame content block.

MoCo are currently changing removing these terms from their products and codebase, are we able to do the same? Which may need a wider audit than just this example.

* [x] search through codebase for "blacklist" or "whitelist" and replace with "denylist" and "allowlist"
* [x] look through our main repositories (fo'mo, donate, network-pulse, etc.) and migrate from "master" branch to "main" branch

**Comment by danielfmiranda** [comment]
Hi @Pomax @KalobTaulien @fessehaye!

Wanted to hear what you all thought about the 2nd action item in this ticket which is to change the master branch name from "master" to "main"

I would imagine that a number of different CI tools are watching for any changes to the "master" branch, so I wanted to double check with the engineers on the team to see if there was anyone opposed to this change before I begin to audit/make changes.

Thanks!
