### ISSUE TITLE
Prevent CloudFlare from stripping UTM tags on prod

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#7107]
This ticket is a follow up from a follow up, here’s the recap:

#6543 was the initial attempt
#7072 fixed the issue on staging, but UTM tags are still stripped on prod, even though they are both running the same code.

✅ https://foundation.mofostaging.net/regrets?utm_campaign=youtuberegrets&utm_source=twitter&utm_medium=social&utm_content=1625741125

❌ https://foundation.mozilla.org/regrets?utm_campaign=youtuberegrets&utm_source=twitter&utm_medium=social&utm_content=1625741125

@KalobTaulien & I think CloudFlare could be stripping UTM tags too. So essentially, it was broken twice, and we addressed only one issue.

@tomusher does that ring a bell to you?

**Comment by TheoChevalier** [comment]
Actually, @benhohner would you be able to take a look while Tom is away?

**Comment by benhohner** [comment]
@TheoChevalier I'll take a look

**Comment by benhohner** [comment]
Looks like the cloudflare workers are stripping URL parameters:

```javascript
// NOTE: A 'Cache Level' page rule set to 'Cache Everything' will
// prevent private cookie cache skipping from working, as it is
// applied after this worker runs.
const PRIVATE_COOKIES = ["csrftoken", "sessionid"];
const STRIP_QUERYSTRING_KEYS = [
  "utm_source",
  "utm_campaign",
  "utm_medium",
  "utm_term",
  "utm_content",
  "gclid",
  "fbclid",
  "dm_i", // DotDigital
];
/**
 * List of cachable HTTP status codes comes from here:
 * https://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.4
 */
const CACHABLE_HTTP_STATUS_CODES = [200, 203, 206, 300, 301, 410];
addEventListener("fetch", (event) => {
  event.respondWith(main(event));
});
async function main(event) {
  const cache = caches.default;
  let request = event.request;
  request = stripIgnoredQuerystring(request);
  if (!requestIsCachable(request)) {
    return fetch(request);
  }
  let response = await cache.match(request);
  if (!response) {
    response = await fetch(request);
    if (responseIsCachable(response)) {
      event.waitUntil(cache.put(request, response.clone()));
    }
  }
  return response;
}
function stripIgnoredQuerystring(request) {
  // Return a request with specified querystring keys stripped out
  const url = new URL(request.url);
  const stripKeys = STRIP_QUERYSTRING_KEYS.filter((v) =>
    url.searchParams.has(v)
  );
  if (stripKeys.length) {
    stripKeys.forEach((v) => url.searchParams.delete(v));
    return new Request(url, request);
  }
  return request;
}
function requestIsCachable(request) {
  if (hasPrivateCookie(request)) {
    return false;
  }
  return true;
}
function hasPrivateCookie(request) {
  const cookieHeader = request.headers.get("Cookie");
  if (!cookieHeader) {
    return false;
  }
  const requestCookieNames = cookieHeader
    .split(";")
    .map((cookie) => cookie.split("=")[0].trim());
  // Check if the request includes any of the specified 'private' cookies
  return PRIVATE_COOKIES.some((privateCookieName) =>
    requestCookieNames.includes(privateCookieName)
  );
}
function responseIsCachable(response) {
  if (!CACHABLE_HTTP_STATUS_CODES.includes(response.status)) {
    return false;
  }
  return true;
}
```
I think what we need to do is record the stripped query strings and re-add them to the response after all the caching business is done.

**Comment by tomusher** [comment]
If we pass UTM values to the origin it will reduce the "cacheability" of the site as each different value will be a unique cache key.

Is there a particular reason we need the UTM values here? They're usually parsed client side, which will still have access to them even if they're stripped out in the request to the origin.

**Comment by TheoChevalier** [comment]
> If we pass UTM values to the origin it will reduce the "cacheability" of the site as each different value will be a unique cache key.

I believe Ben’s strategy above should address this if we’re first stripping the tags, delivering the cached page for the url **without** tags, then adding back the tags?
This seem to be the strategy adopted by this user in the CloudFlare forums, too https://community.cloudflare.com/t/help-with-workers-to-deliver-cached-pages-for-utm-tags/109975

> Is there a particular reason we need the UTM values here? They're usually parsed client side, which will still have access to them even if they're stripped out in the request to the origin.

It doesn’t seem to work without them unfortunately. I’ve used a custom tag on staging and was able to track it in GA, but the same didn’t work on prod

<img width="809" alt="Capture d’écran 2021-07-21 à 18 24 25" src="https://user-images.githubusercontent.com/1294206/126525174-2dc5b0ed-257e-4049-b864-d4febd5ef3ca.png">

**Comment by tomusher** [comment]
I've updated the worker to rewrite the 'location' header on redirects to include the originally stripped querystring keys.

**Comment by TheoChevalier** [comment]
Thanks @tomusher! Is this supposed to work on prod already?

**Comment by TheoChevalier** [comment]
Confirming it’s working, thanks again Tom!
