### ISSUE TITLE
[wagtail-localize] Image grid can’t be localized

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#7115]
Image grid on https://foundation-localize.herokuapp.com/fr/campaigns/eu-misinformation/resources/ can’t be localized. This is likely using ListBlocks and similar to #6934

**Comment by KalobTaulien** [comment]
This will hopefully be solved soon when Wagtail RFC 65 (https://github.com/wagtail/rfcs/pull/65) lands. It's in its last stage, minus the actual work. It's been approved, we just need someone like Karl to implement the RFC soon.

**Comment by Pomax** [comment]
Let's see if, with the PRs landed in Wagtail, this is now something we can solve with a simple wagtail bump.

**Comment by TheoChevalier** [comment]
I think we will need small changes in wagtail-localize first to use what’s landed in Wagtail core, but this is already planned for an upcoming sprint

**Comment by TheoChevalier** [comment]
Confirming the combination of both wagtail 2.16 & wagtail-localize 1.1 have fixed this
