### ISSUE TITLE
Recent blog entries block is timing out

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#7152]
Pages using the "Recent blog entries" block are timing out most of the time — for logged in users anyway, because otherwise people are getting the cached version and it works well.

What’s more annoying is that it’s timing out for **Previewing** the page as well

There’s an example here: https://foundation.mozilla.org/cms/pages/1935/edit/, neither Jon & I managed to get a preview

**Comment by Pomax** [comment]
closing: the "blog set" streamfield component fixed this.
