### ISSUE TITLE
Some blog post listing pages (/blog/tags/xxx) are throwing 5xx errors

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#7163]
Anna noticed a bunch of pages in GA where we’re having 5xx errors: https://docs.google.com/spreadsheets/d/1fgJ7kWroTtVYVhAN8Xtod5UEW5BBYWlTFKK5NL1jfPM/edit#gid=179377913

Some are timing out because it’s taking too long, but others are crashing, for example https://foundation.mozilla.org/en/blog/tags/mozfest-2021/

**Comment by Pomax** [comment]
tag filtering and routing are slated to be removed, so that problem will basically disppear all on its own. Rather than https://foundation.mozilla.org/en/blog/tags/mozfest-2021 folks will want to use https://foundation.mozilla.org/en/blog/category/mozilla-festival/

**Comment by Pomax** [comment]
closing this as effectively being fixed once https://github.com/mozilla/foundation.mozilla.org/issues/6757 closes
