### ISSUE TITLE
PNI product pages should show PNI OG image

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7165]
Product pages on PNI are showing the generic Mozilla OG image.

![image](https://user-images.githubusercontent.com/1068783/128047483-6e7b4662-8636-417c-945b-8025a9a5a561.png)

They should show the PNI OG image.
![image](https://user-images.githubusercontent.com/1068783/128047397-a7b9f14b-527c-4e2c-bac9-99803ecb0e2f.png)

Note: Category pages should show continue to show the custom category OG when one has been uploaded.

**Comment by Pomax** [comment]
It looks like the product page implements a `block social_image` but that block seems to have disappeared from the "higher up" templates. Let's find out when we lost it,

**Comment by kristinashu** [comment]
Thank you for clarifying Daniel! Categories have been done here https://github.com/mozilla/foundation.mozilla.org/issues/7441, just hasn't been merged to the main site yet.
