### ISSUE TITLE
[PNI Website] Benchmarking

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7179]
Todo
- [x] Review feature requests
- [x] Gather competitors and benchmarks 
- [x] Present to stakeholders for input

**Comment by kristinashu** [comment]
Not a great design reference but for a competitive analysis, the UK researcher mentioned this site https://www.which.co.uk/

**Comment by nancyt1** [comment]
Gathered a few [benchmarks](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/Privacy-Not-Included-Website?node-id=3%3A9) and categorized them into feature buckets that I simplified from the brief.
