### ISSUE TITLE
[PNI Website] Move files to Figma

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7180]
Todo
- [x] Review Sketch file to decide what to move over
- [ ] Create key PNI styles and components in Figma
- [ ] Build key pages in Figma
- [x] Archive old sketch file
- [ ] Clean up and consolidate colors
- [ ] Clean up and consolidate typography

**Comment by sabrinang** [comment]
Downloaded sketch files from Abstract which includes `Buyers Guide.sketch` and `zArchive.sketch` but only PNI related zArchive pages/symbols and moved them into google drive in Buyer's Guide / PNI > Archived Sketch Files folder hree: https://drive.google.com/open?id=1Skz1CFiEdXir56ilVnsrWKN8WhSZkrFl&authuser=sabrina%40mozillafoundation.org&usp=drive_fs

Filed ticket to split component creation work here #7289
