### ISSUE TITLE
Card Component Needs Narrow Width Update

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#7201]
Card components show 3 cards, but on narrow pages we might want it to show 2 cards so it looks less cluttered. 

We may be able to detect the page width (or maybe not) to auto-determine if we should show 2 or 3 cards.

**Comment by danielfmiranda** [comment]
Added design tag and the feedback from Kristina that prompted this ticket: 

"The cards are too narrow when the page is narrow width. Could the cards either be only 2 up at narrower widths or could the component break out of the narrow width and always be wide width (like you've done for wide width images)?"

@kristinashu Would it be possible for someone on the design team to mock up the two methods you mentioned above, and then we can see which route we would like to implement for the cards? Thanks in advance!

**Comment by kristinashu** [comment]
I'd love to get this done but this sprint is looking pretty busy for design - sorry but this ticket might have to be a stretch goal for us.

**Comment by danielfmiranda** [comment]
No problem @kristinashu! Going to move this ticket to stretch for the sprint

**Comment by jamilasnell** [comment]
Design to come up with mockup
