### ISSUE TITLE
[CI Report] word count & image specs

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7207]
This report will follow the same layout and structure as YouTube Findings site https://foundation.mozilla.org/en/campaigns/regrets-reporter/findings/

Design to work with Marni to create
- [x] a copy doc template with word counts for the writer
- [x] spec sheet for website assets for the designer to follow
- [x] copy template and update with Zilla to make it more generic

**Comment by nancyt1** [comment]
Started the [figma template](https://www.figma.com/file/7wEohUki46uKUd2BncB2Ke/Report-Findings-Template?node-id=0%3A1) and reviewed and updated Marni's [copy doc](https://docs.google.com/document/d/1Cs_8K5hWttNPxQwFheVTg-G2ADeDJtaoYaVMlAo1wSw/edit#)

**Comment by kristinashu** [comment]
Looking good. Thank you for jumping into this today!

**Comment by nancyt1** [comment]
Finished the [figma template](https://www.figma.com/file/7wEohUki46uKUd2BncB2Ke/Report-Findings-Template?node-id=0%3A1) and included asset specs on the side. Should a google doc be made with the asset specs as well or is figma enough?

**Comment by kristinashu** [comment]
Looks good! I think the specs you added to Marni's doc and the Figma file are enough!
