### ISSUE TITLE
Clean up "default local" code for PNI category snippets

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7217]
Follow-up to https://github.com/mozilla/foundation.mozilla.org/pull/7215, where we had to write some non-DRY code to get default_locale and default_locale_id from the database in a way that doesn't kick in "before the database is ready".

We tried using the AppConfig `ready()` function, but that still kicks in too early (you can get model classes from the db, but you can't get model _data_ from the db yet when that triggers).

The idea is that we somehow get these values into `settings`, between "db is up and ready for calls" and "regular code starts running", so that `settings.DEFAULT_LOCALE` and `settings.DEFAULT_LOCALE_ID` exist by the time any code tries to access it.

**Comment by richbrennan** [comment]
Closing following discussion with Pomax. The `get_supported_content_language_variant` function is being used in code already so action required.
