### ISSUE TITLE
Design review of MozFest work

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7266]
Torchbox will be doing a few updates to the mozfest site (ti.to embed, gallery, homepage hero) and we will need to review the wireframes.

**Comment by sabrinang** [comment]
Met this morning to go over Lindi's (from TorchBox) mockups and gave feedback.

**Comment by kristinashu** [comment]
I checked with Marni and we don't think Sabrina needs to do much more review since they were all aligned at the last check-in. Torchbox should share progress in the slack channel and we can flag any concerns there.
