### ISSUE TITLE
Language should not change when clicking on a blog post link

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7268]
### Describe the bug
Clicking on a blog post changes the language.

### To Reproduce
1. Go to https://foundation.mozilla.org/en/blog/ (note the /en)
2. Click on any blog post that isn't a feature post
3. Location changes to /es e.g. https://foundation.mozilla.org/es/blog/announcing-common-voices-kiswahili-community-event-this-august/

### Expected behavior
The language should stay the same.

I don't think this is device or browser specific.

**Comment by Pomax** [comment]
It looks like some of the other locale fixes we pushed through also fixed this issue, so I'm closing this one.
