### ISSUE TITLE
Missing publish date on alias blog pages

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#7282]
Page aliases for blog posts are currently showing `not published yet` while the original /en page is published. E.g:
- Page  alias: https://foundation.mozilla.org/es/blog/announcing-common-voices-kiswahili-community-event-this-august/ 
- Original: https://foundation.mozilla.org/en/blog/announcing-common-voices-kiswahili-community-event-this-august/

Wagtail is looking for the published date of the alias, we should make it look up the one from the /en page instead

**Comment by Pomax** [comment]
Hm, I'm having a hard time reproducing this, here's what I've done:

1. new DB
2. created a new locale for German, synced to English
3. ran `sync_locale_trees`
4. confirmed that there is a german alias for the english "test blog page": 
![image](https://user-images.githubusercontent.com/177243/132412842-4118b820-c8e7-4409-b4e0-78ce5655f5f7.png)
5. visted http://localhost:8000/en/blog/initial-test-blog-post-with-fixed-title/: 
![image](https://user-images.githubusercontent.com/177243/132412909-70614cab-b441-4dfa-91f8-9407526a9301.png)
6. visited http://localhost:8000/de/blog/initial-test-blog-post-with-fixed-title/: 
![image](https://user-images.githubusercontent.com/177243/132412956-0752d62d-530e-43a9-ba07-2014029741a8.png)

This shows a different date format, but it does show a date. Would you happen to have additional details that lets me reproduce this locally?

**Comment by TheoChevalier** [comment]
I played around, and indeed, we were missing a step and it’s the weirdest…

As step 3.5, translate the /blog (blog index) page in German. You don’t need actual translations, just starting the translation.

Now create and publish your test blog post in English, and the German blog post will show "not published yet" 🤷‍♂️🤷‍♂️🤷‍♂️

**Comment by Pomax** [comment]
I still can't seem to reproduce this - I run through steps 1 through 4, then for the blog index page:

![{14189427-8A14-48C1-89D5-FC6F9E8ACD3D}](https://user-images.githubusercontent.com/177243/132564426-3b47caf0-4a98-4b32-8654-4a6010e09688.png)

I click "translate this page", then:

![{40B2938F-1C63-4356-9275-213A35683C8B}](https://user-images.githubusercontent.com/177243/132564451-5549526a-8950-4ea0-bf0f-1970530d9ea6.png)

I click "submit", then try the german blog page:

![{6E325EDC-CDFE-4392-B6BE-A7EB79CBE9ED}](https://user-images.githubusercontent.com/177243/132564522-e9301fe3-c534-4c9a-aa63-163947a43792.png)

This still shows a real date...

**Comment by Pomax** [comment]
Confirmed: this happens for new EN blog posts _after_ setting up localisation, and I can reproduce:

![image](https://user-images.githubusercontent.com/177243/132564920-181e79a4-1e96-4ec6-8588-d977e8e703f3.png)

**Comment by Pomax** [comment]
test result: rerunning `sync_locale_trees` does not update this field, either.

**Comment by Pomax** [comment]
Filed https://github.com/wagtail/wagtail-localize/issues/449 because this is almost certainly a wagtail-localize incompletion.

**Comment by Pomax** [comment]
@TheoChevalier @benhohner @kaedroho I'm not sure writing patch code is going to be tractable, so this might require us to wait for wagtail-localize to fix this instead. 

If we create a template tag like `get_original_page` then we end up having to write templates that always start with "get the original page as well as the one we're templating for", which doesn't feel right, and if we create a mixin that ensures that pages have some `origial_page` property, then now we need to remember to add that superclass to every new class we write for something that should be handled automatically by wagtail-localize.

This feels like the kind of thing that would be fixed much more cleanly if pages had an `.original_page` and snippets had an `.original_snippet` property imparted on them by wagtail-localize, how much work would it be to make that a reality?

**Comment by TheoChevalier** [comment]
Note for ourselves once it’s fixed in wagtail-localize, we will want to check it fixes it on featured blog posts, too

<img width="580" alt="Capture d’écran 2021-09-16 à 11 08 52" src="https://user-images.githubusercontent.com/1294206/133584610-caa3c598-583b-44c3-9cfb-3d40cc4f8665.png">

**Comment by richbrennan** [comment]
I investigated this and found that when a page is created the translatable alias does not have certain fields, including `first_published_at` set, which could be related too this issue as they use the same mechanism to normal aliases: https://github.com/wagtail/wagtail/issues/7373

I wasn't able to pin down exactly where this is happening, however did find that these fields are missing from the first revision of a page even when going straight to publish, because the revision is created before the `first_published_at` etc are set on the page when the revision is subsequently published: the `first_published_at` in the revision `content_json` field is not updated with the page `first_published_at`. I'm not sure, however, that this is the necessarily the cause of the issue as the alias is created from the page object after the publishing logic has completed.

**Comment by Pomax** [comment]
@richbrennan  It sounds like this is something we might need to take to the wagtail team? If so, woudl you be willing to file an issue on the wagtail repo?

**Comment by richbrennan** [comment]
I've updated the existing Wagtail issue with the above, and will ask around to see if anyone is looking into it.

**Comment by richbrennan** [comment]
Fix in progress https://github.com/wagtail/wagtail/pull/7788

**Comment by Pomax** [comment]
Wagtail should have been updated at this point, let's see if we can put this in place?

**Comment by tbrlpld** [comment]
Currently in 2.16rc1: https://github.com/wagtail/wagtail/commit/731cc540b0f70527dc81cbc23e2f8f2cdaaf9df7

**Comment by TheoChevalier** [comment]
Here’s a management command to update existing alias pages https://gist.github.com/zerolab/75323b449efa28a5ea4031d97b6a2ff4

I’m not sure if I’m doing something wrong, but so far it doesn’t seem to fix old alias pages. I ran the command with Wagtail 2.16rc1 on the prod DB but they still show up as not yet published. Checking with Dan

**Comment by TheoChevalier** [comment]
Confirming this has now been fixed for all existing pages by running the command landed in https://github.com/mozilla/foundation.mozilla.org/pull/8277

Example link in the first comment isn’t showing up `Not published yet` anymore https://foundation.mozilla.org/es/blog/announcing-common-voices-kiswahili-community-event-this-august/
