### ISSUE TITLE
PNI menu is only matching browser language settings

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#7283]
With a browser set with French as the preferred language, opening PNI in any language will serve me the menu in French. Here’s an example with https://foundation.mozilla.org/de/privacynotincluded/ opened in a French Firefox:

<img width="1380" alt="Capture d’écran 2021-08-30 à 18 25 49" src="https://user-images.githubusercontent.com/1294206/131372410-a6e17e5d-d082-449a-8664-a701edbc5587.png">

Impact should be low (after all, we’re serving the language people said they preferred), but it does look confusing. It should be matching the current page locale instead

**Comment by Pomax** [comment]
The PRs for https://github.com/mozilla/foundation.mozilla.org/issues/7122 will address this issue, too.

**Comment by TheoChevalier** [comment]
Confirmed fixed
