### ISSUE TITLE
[Investigate] dyno load is abnormally high for the foundation site

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7286]
It looks like someone's hammering the Thimble artifact page again, which might be what's causing the huge spinup, but it's also possible there's more at play.

Let's investigate what might be possible causes. So far:

- [ ] a single IP seems to be hammering the Thimble Artifact page - we can ban that IP using cloudflare, and possibly unpublish the Thimble artifact page so that it's a 404 for a few weeks.

**Comment by jamilasnell** [comment]
@tomusher Hey! You've been co-assigned to this ticket just so we can keep an eye on the logs :)

**Comment by Pomax** [comment]
So it turns out https://github.com/mozilla/mofo-redirector/blob/master/config.py is probably to blame here, but indirectly: this is probably someone trying to proxy `thimble.webmaker.org` from yeeeeears ago, which we should seriously consider shutting down instead of just redirecting to our artifacts pages.

/cc @benhohner @anilkanji

**Comment by Pomax** [comment]
specifically: https://github.com/mozilla/mofo-redirector/blob/master/config.py#L201-L210

**Comment by Pomax** [comment]
So far, we've:
1. commented off the thimble.webmaker.org and thimble.mozilla.org redirects in mofo-redirector
2. removed the nameserver binding for thimble.webmaker.org

**Comment by Pomax** [comment]
we've been able to restore cloudflare, resolving this issue.
