### ISSUE TITLE
Version Upgrades

### ISSUE THREAD

**Issue by benhohner** [mozilla/foundation.mozilla.org#7288]
- [x] Fo'mo
- [x] Donate/Thunderbird

**Comment by jamilasnell** [comment]
Hey @richbrennan! Would you be willing to handle the wagtail version upgrades? Would be greatly appreciated! :)

**Comment by richbrennan** [comment]
- Update Wagtail to [2.15.1](https://docs.wagtail.io/en/stable/releases/2.15.html#upgrade-considerations)
- Dependabot PRs: Cypress has been basically impossible to use for local dev
- Make Cypress work for local dev

**Comment by richbrennan** [comment]
Hi @Pomax 

The Python-related Dependabot PR's are failing in CI due to incompatible requirements of `importlib-metadata`. It seems as though `flake8` has it [pinned](https://github.com/PyCQA/flake8/blob/6e5600f8ec3f98fd052bd532470297e0a360750e/setup.cfg#L45) to the older `<4.3` for Python < 3.8, whereas other packages are using a newer version.

- https://github.com/mozilla/foundation.mozilla.org/pull/7930
- https://github.com/mozilla/foundation.mozilla.org/pull/7911
- https://github.com/mozilla/foundation.mozilla.org/pull/7909

Is updating to a newer version of Python a viable option?

**Comment by richbrennan** [comment]
Cannot update to Wagtail 2.15.1 until `wagtail-localize-git` is updated: https://github.com/wagtail/wagtail-localize-git/blob/main/setup.py#L51

**Comment by richbrennan** [comment]
@Pomax 

Also, would you be able to confirm what `Donate/Thunderbird` in the first comment refers to please?

**Comment by Pomax** [comment]
"Donate/Thunderbird" refers to the https://github.com/mozilla/donate-wagtail repo and its dependencies.

**Comment by Pomax** [comment]
I've filed https://github.com/wagtail/wagtail-localize-git/issues/16 to hopefully get wagtail-localize version bumped, so we can uplilft that and then get wagtail onto 2.15

**Comment by Pomax** [comment]
@richbrennan it might be a good idea to see if we uplift our python versions to 3.10 for the foundation and donate repos. We don't have an issue filed for that atm, but if you want to tackle that feel free to create one.

**Comment by richbrennan** [comment]
> I've filed [wagtail/wagtail-localize-git#16](https://github.com/wagtail/wagtail-localize-git/issues/16) to hopefully get wagtail-localize version bumped, so we can uplilft that and then get wagtail onto 2.15

Thanks Pomax. I might see if I can create a PR for the change to the `wagtail-localize-git` repo

**Comment by richbrennan** [comment]
Draft PR for Donate to Wagtail 2.15.1: https://github.com/mozilla/donate-wagtail/pull/1591

Draft PR for foundation site to Wagtail 2.15.1: https://github.com/mozilla/foundation.mozilla.org/pull/7970

**Comment by richbrennan** [comment]
Blocked until a new version of `wagtail-localize-git` is released. I've updated it to support Wagtail 2.15 and Python 3.10, so just waiting on a new code release.

**Comment by richbrennan** [comment]
Dependabot updates dependent on: #7953

**Comment by richbrennan** [comment]
I've reviewed and tested the following Foundation site BE Dependabot PRs, they just need to be merged:

- https://github.com/mozilla/foundation.mozilla.org/pull/7952

- https://github.com/mozilla/foundation.mozilla.org/pull/7951

**Comment by richbrennan** [comment]
The BE Donate site Dependabot PRs are quite old and are flagging merge conflicts in requirements files.

Suggest we revisit them once the Donate site Wagtail update has been completed: https://github.com/mozilla/donate-wagtail/issues/1593

**Comment by Pomax** [comment]
Missed this question: I'd say let's close all Dependabot PRs and take it from there. It'll file new ones over the break that we can look at in the new year.

**Comment by richbrennan** [comment]
I've closed all but the ones tagged with Security in case they need attention early next year
