### ISSUE TITLE
PNI product images aren’t centered

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#7293]
Product images aren’t centered anymore, but visually left-aligned. I assume it’s not intended :)

Tested on Firefox & Chrome

<img width="1144" alt="Capture d’écran 2021-08-31 à 11 51 14" src="https://user-images.githubusercontent.com/1294206/131481835-dc476781-0e86-4680-85b0-93e95848b22e.png">

**Comment by Pomax** [comment]
This will require bisecting to find out which commit caused this change.

**Comment by Pomax** [comment]
Findings so far: after postcss runs, things are good. Once tailwind's compile has kicked in, it no longer looks right.

**Comment by Pomax** [comment]
```
aa6ae0a915896281af9940b886428021b4bf3da7 is the first bad commit
commit aa6ae0a915896281af9940b886428021b4bf3da7
Author: Simon Fessehaye <fessehay@ualberta.ca>
Date:   Wed Aug 11 16:09:15 2021 -0600

    7194 - PNI footer layout is broken (#7214)

    Co-authored-by: Daniel Miranda <manieldiranda@gmail.com>

 source/sass/buyers-guide/bg-main.scss | 4 ++++
 1 file changed, 4 insertions(+)
```

**Comment by Pomax** [comment]
Changes: https://github.com/mozilla/foundation.mozilla.org/commit/aa6ae0a915896281af9940b886428021b4bf3da7

**Comment by Pomax** [comment]
Manual check: dfb95851aa9d055f92c3469eedcf09b8f662183b has the correct layout, aa6ae0a915896281af9940b886428021b4bf3da7 no longer does.
