### ISSUE TITLE
[PNI Website] Determine which metrics to track

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7305]
Design to make a list of key things we would like to track and make sure they are properly tracked.

Links
- [2020 Holiday Wrap-up deck](https://docs.google.com/presentation/d/1_pclZ2KJjTvRAHgmmslBJuVuRM9Hb3om9nK73Jc6C4k/edit#slide=id.g8a4b8daaaa_0_3132)
- [2021 V-Day Wrap-up deck](https://docs.google.com/presentation/d/1EJYAGVPVco4VVWZQk2pEp0nyo99N572EgSwe07xWvVw/edit#slide=id.g8a4b8daaaa_0_3132)

To do
- [x] Write list of things to track
- [x] Have meeting with design and dev to discuss more ideas and how to track
- [x] Ask Ben about how to set this up
- [ ] Ask about UTMs
- [x] Open follow up ticket to create dashboard

**Comment by kristinashu** [comment]
Here's a link to the current dashboard https://datastudio.google.com/reporting/987f19db-fb13-481c-b2ea-7d2eddd7d24f

**Comment by nancyt1** [comment]
I started a [doc](https://docs.google.com/document/d/1lOYFRsftKUx4oBPo3gmqEAsLLGlDPjtgd4vJ11wBLW0/edit#) and brain dumped some metrics I was thinking of tracking. Feel free to add or comment anything!

**Comment by nancyt1** [comment]
Opened up new ticket https://github.com/mozilla/foundation.mozilla.org/issues/7782 to tag and turn into dashboard.

Thanks Ben for brownbag!
