### ISSUE TITLE
[PNI Website] Iterate on categories

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7313]
### Requirements for the page
- [x] Add ability to have more categories (done, decided more categories aren't needed)
- [x] Add ability to have sub-categories (initial draft is done)

### Steps
- [x] Explore different options and prototype them
- [x] Get feedback from Jen and devs
- [x] Work with devs to open their tickets (delayed by a week)

(not we will explore this more next year, for now we are looking for lower lift solutions)

**Comment by kristinashu** [comment]
Jen now has the real list of products, categories, and sub-categories https://docs.google.com/document/d/1Fft0fBwZnrZ896kcUp5KVpdaFKbuiMr-EeBLuYzqLk8/edit#

**Comment by kristinashu** [comment]
Gonna cc @sabrinang on this since she has also already done some wireframing on it and it will be good the get her input, ideas, and feedback!

**Comment by kristinashu** [comment]
Note from Pomax about drop-down options on mobile to keep in mind:
- Super easy: rename “all” to “all categories” and done.
- More-work option: Initially show “categories”. when users taps and menu is shown. show “all categories”
- Lot-of-work option: show “category” above “all”, but remove that option when the menu gets expanded.

**Comment by nancyt1** [comment]
I've been exploring designs in the [figma file](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/Privacy-Not-Included-Website?node-id=1173%3A101577) and set up a [presentation](https://www.figma.com/proto/GwdoUiY4fzVyeLfXsAJGPq/Privacy-Not-Included-Website?page-id=1173%3A101577&node-id=1246%3A108518&viewport=241%2C48%2C0.17&scaling=scale-down-width&starting-point-node-id=1246%3A108518) for the checkin on 10/5.
