### ISSUE TITLE
CMS: Opportunity Pages (enhancement) - WYSIWYG editor

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#732]
Could we make the typeface and spaces as we see in the published page? I know we can't replicate every single detail in the editor but currently is a bit challenging to foresee how the page will look like until we see the draft in the site

<img width="831" alt="image" src="https://user-images.githubusercontent.com/22157921/29835105-c8b9f8b4-8ca5-11e7-9787-fe9cda75d6de.png">

I wonder if we could make more like that (meaning what we see in the editor is very close to the published page):

<img width="595" alt="image" src="https://user-images.githubusercontent.com/22157921/29835067-aacced66-8ca5-11e7-86a4-fab60dd7e937.png">
I feel this change would make the creation of pages faster for editors.

**Comment by kristinashu** [comment]
Closing since this is for Mezzanine and we've moved to Wagtail now.
