### ISSUE TITLE
Blog social metadata is incorrect

### ISSUE THREAD

**Issue by anilkanji** [mozilla/foundation.mozilla.org#7350]
### Describe the bug
In Mozilla Slack channel #mofo-website-new-blogs, which pulls an RSS feed of MoFo blogs, the previews render boilerplate text. This only seems to show up in this channel, with the RSS feed -so likely not a huge priority to solve, just want to make sure it's not an issue that's showing up elsewhere.

### To Reproduce
1. Go to  #mofo-website-new-blogs
2. view content pulled in from RSS feed
3. See error

![image](https://user-images.githubusercontent.com/46638654/132763394-42b7fa25-6381-4a9e-9a8a-2f242fcb3a55.png)

**Comment by benhohner** [comment]
Technical details: Twitter and OG description are the page description instead of a summary of the post

**Comment by benhohner** [comment]
@danielfmiranda as discussed in stand, let's pull the first characters from the first paragraph if the meta description field is not filled in.
https://moz.com/learn/seo/meta-description (char lengths here)

**Comment by Pomax** [comment]
For the blog RSS work we discovered and used some functions that might be useful here:

https://github.com/mozilla/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/pagemodels/blog/blog.py#L4

https://github.com/mozilla/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/pagemodels/blog/blog.py#L17

**Comment by danielfmiranda** [comment]
Hi Everyone, I have tested this issue and it appears that the code that @Pomax linked above has resolved this. For example:

here is a screenshot of what the meta description looks like when I did not have anything set:
![MetaWithNoneSet.png](https://images.zenhubusercontent.com/6046b7f1bc36adc9ce95a16a/dc2bc072-a38d-4d99-b29c-ffda71ce9915)
