### ISSUE TITLE
[PNI] Product page - header updates: remove pricing

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7375]
- [x] Remove product price

Current page implementation:

![image](https://user-images.githubusercontent.com/177243/133164784-3f1df919-cf70-44fe-aa5a-c53250a9b7a3.png)

- [x] Add external link icon. SVG icon here: https://drive.google.com/open?id=1Tb1mypj_5pfzhrZ53Hg6ONIkhIp4JxU2&authuser=sabrina%40mozillafoundation.org&usp=drive_fs 

Relevant part of the updated product page comp:

![image](https://user-images.githubusercontent.com/177243/133164198-aced8a68-c170-4225-a029-95d0e2c6d7e5.png)

Comps on figma: https://www.figma.com/proto/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?page-id=548%3A72128&node-id=611%3A77813&viewport=283%2C48%2C0.08&scaling=min-zoom&starting-point-node-id=611%3A77813

**Comment by danielfmiranda** [comment]
Closing this issue as we have the solution merged in
