### ISSUE TITLE
[PNI] Product page - header updates: update date format

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7376]
- [ ] Change review date date formatting to `Month Day, Year`

We may be able to do this using the same Django template tag/filter that we're already using.

Relevant part of the updated product page comp:

![image](https://user-images.githubusercontent.com/177243/133164198-aced8a68-c170-4225-a029-95d0e2c6d7e5.png)

Comps on figma: https://www.figma.com/proto/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?page-id=548%3A72128&node-id=611%3A77813&viewport=283%2C48%2C0.08&scaling=min-zoom&starting-point-node-id=611%3A77813

**Comment by danielfmiranda** [comment]
Closing this issue as we have the solution merged in
