### ISSUE TITLE
[PNI] Product page - header updates: Mozilla Researched

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7377]
- Add a `Mozilla researched` entry to the Product page
  - [ ] add copy + template section for hours spent researching this product
  - [ ] link to `methodology` "about" page 
  - [ ] add a "time researched"` number field to the `ProductPage` backend model
  - [ ] add info circle. SVG icon here: https://drive.google.com/open?id=1TbEuGYvryqkcfticy1IdG0eRz7Nfs1mg&authuser=sabrina%40mozillafoundation.org&usp=drive_fs

Relevant part of the updated product page comp:

![image](https://user-images.githubusercontent.com/177243/133164198-aced8a68-c170-4225-a029-95d0e2c6d7e5.png)

Comps on figma: https://www.figma.com/proto/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?page-id=548%3A72128&node-id=611%3A77813&viewport=283%2C48%2C0.08&scaling=min-zoom&starting-point-node-id=611%3A77813

**Comment by danielfmiranda** [comment]
Hi @kristinashu! I have a quick question regarding this ticket and the medium-small breakpoints:

Currently, the new fields look good on both desktop and mobile breakpoints (The people voted section is just a placeholder for now):
Desktop:
<img width="1237" alt="Screen Shot 2021-09-27 at 12 18 11 PM" src="https://user-images.githubusercontent.com/18314510/134972075-b1d361b5-113a-42ce-9447-c4655db4f74d.png">
Mobile:
<img width="714" alt="Screen Shot 2021-09-27 at 12 21 06 PM" src="https://user-images.githubusercontent.com/18314510/134972137-864e6d20-691c-4060-a665-3117cccef620.png">


However, on the medium and small breakpoints, the text seems to get very squished or compact:
Medium:
<img width="1001" alt="Screen Shot 2021-09-27 at 12 18 31 PM" src="https://user-images.githubusercontent.com/18314510/134971912-96423804-acde-497a-aaf9-f9c14b9fde99.png">
Small:
<img width="792" alt="Screen Shot 2021-09-27 at 12 18 48 PM" src="https://user-images.githubusercontent.com/18314510/134971977-0b69d267-92bb-4945-8d7c-6b9e76e018d1.png">


I was wondering if there was a way the design team would like us to resolve this. At the moment, one solution I can think of would be to have the columns go from 4 on desktop, to 2 and 2 on medium-small, and then finally to 1 on 1 on 1 on 1 on mobile.

However I wanted to run this by the design team to see if there were any other preferred solutions for this, thanks!

**Comment by kristinashu** [comment]
Thanks for checking @danielfmiranda! I think your suggestion of "columns go from 4 on desktop, to 2 and 2 on medium-small, and then finally to 1 on 1 on 1 on 1 on mobile" sounds good but I would like @sabrinang's input.

**Comment by sabrinang** [comment]
+1 @danielfmiranda your suggestion sounds good to me and I can see it looking like this:
<img width="657" alt="image" src="https://user-images.githubusercontent.com/2492510/134995470-e926b974-a861-44b1-a6fd-497319d98109.png">
