### ISSUE TITLE
[PNI] Product page - header updates: add People Voted

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7379]
- Add "people voted"
  - [x] add ‘People voted’ copy, acting as anchor link to the creep-o-meter voting section
    -  we'll probably need a new `id`, as `#creep-vote` points to the `<form>` specifically, which cuts off the header if we navigate to that
  - [x] displaying creepiness percentage, rounded to the nearest integer
  - [x] display one of five face icons, similar to the ones used in the creep-vote results. SVG icons here: https://drive.google.com/open?id=1Tio1_tNLzuYprg_pwCjP2pbJdTyJWwtp&authuser=sabrina%40mozillafoundation.org&usp=drive_fs

Relevant part of the updated product page comp:

![image](https://user-images.githubusercontent.com/177243/133164198-aced8a68-c170-4225-a029-95d0e2c6d7e5.png)

Comps on figma: https://www.figma.com/proto/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?page-id=548%3A72128&node-id=611%3A77813&viewport=283%2C48%2C0.08&scaling=min-zoom&starting-point-node-id=611%3A77813

**Comment by danielfmiranda** [comment]
Hi @kristinashu @nancyt1 @sabrinang! 

Had a quick question about this ticket:

Should the people voted section always say "super creepy"? 
For example, if no one has voted that the product was super creepy, just have the section say "People voted 0% super creepy".

Or, do we need to display the creepiness level with the majority of votes. 
For example, if a majority of people have voted "Not Creepy" should the section say "people voted 76% not creepy" 

Thanks in advance!

**Comment by danielfmiranda** [comment]
Note for me or simon: we can access the creepiness data by using:
`        {{product.get_voting_json}}
`

**Comment by sabrinang** [comment]
@danielfmiranda 
The people voted section should not always say super creepy and display the corresponding creepiness level with the majourity of votes. So in this example with the highest votes it should display: "People voted 57% not creepy (with corresponding not creepy emoji face)"
![image](https://user-images.githubusercontent.com/2492510/133849620-7d4b9fc8-d41b-4451-b2d5-cec0137a8a61.png)
