### ISSUE TITLE
[PNI] Product page - disable "creep-o-meter" vote button until user interacted with slider

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7381]
- disable "creep-o-meter" vote button until user interacted with slider
  - [x] set `disabeld` attribute on the submit button
  - [x] have JS remove that disabled attribute once the user interacts with the slider element

There may be additional work for user feedback when the user tries to click the button anyway, this will be filed as followup if necessary

Relevant part of the updated product page comp:

![image](https://user-images.githubusercontent.com/177243/133167464-7a60758e-22e2-494f-a572-042e76886fb3.png)

In the larger voting content box:

![image](https://user-images.githubusercontent.com/177243/133167441-4e8c0f48-acd3-4a24-a9c9-9df13b8f5246.png)

Comps on figma: https://www.figma.com/proto/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?page-id=548%3A72128&node-id=611%3A77813&viewport=283%2C48%2C0.08&scaling=min-zoom&starting-point-node-id=611%3A77813

**Comment by sabrinang** [comment]
idea: when disabled button is clicked, the slider above can have an horizontal shake animation hint ([shake example](https://css-tricks.com/snippets/css/shake-css-keyframe-animation/ ))
