### ISSUE TITLE
[PNI] Product page - remove company contact information

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7384]
- [x] Remove the company contact information from the product page.
- [x] Hide fields in CMS app and interface (ask Jen whether or not the data needs to go away for old products)

Remove from current template:

![image](https://user-images.githubusercontent.com/177243/133168233-10d0d067-c472-4c56-9725-d94db3613344.png)

**Comment by danielfmiranda** [comment]
Closing this one as it is now merged
