### ISSUE TITLE
[PNI] Product page - reorder "end of page" sections

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7388]
- [ ] Reorder the "end of page" sections from the current ["updates", "comments", "related products"] to ["news", "related products", "comments"]

<img width="892" alt="image" src="https://user-images.githubusercontent.com/2492510/133516326-4b7f3df5-67e2-4c43-9b04-e4e318e29d9d.png">

Comps on figma: https://www.figma.com/proto/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?page-id=548%3A72128&node-id=611%3A77813&viewport=283%2C48%2C0.08&scaling=min-zoom&starting-point-node-id=611%3A77813

**Comment by danielfmiranda** [comment]
Closing this issue as we have the solution merged in
