### ISSUE TITLE
[PNI] Product page - add horizontal rules between "end of page" sections

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7389]
- [x] add horizontal rules between the "end of page" sections
  - note new styling on these hr

Relevant part of the updated product page comp:

![image](https://user-images.githubusercontent.com/177243/133169030-7dbedfaa-96fd-4368-a39c-325a4147cb16.png)

Comps on figma: https://www.figma.com/proto/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?page-id=548%3A72128&node-id=611%3A77813&viewport=283%2C48%2C0.08&scaling=min-zoom&starting-point-node-id=611%3A77813

**Comment by danielfmiranda** [comment]
Closing as this has been merged in
