### ISSUE TITLE
[PNI] Product page - comment section heading/lead-in changes

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7391]
- [x] Update the heading for comments (copy tbd)
- [x] Add a lead-in paragraph for the comment box (copy tbd)

No comps yet

**Comment by benhohner** [comment]
Waiting on copy from @caltrider @kristinashu

**Comment by danielfmiranda** [comment]
Copy for the comments title from @caltrider "Got A Comment? Let Us Hear It"

**Comment by danielfmiranda** [comment]
Hi @sabrinang @nancyt1 I have a quick question about this ticket:
I was wondering if you can let me know what part of the comment box is the "lead in paragraph"
<img width="865" alt="Screen Shot 2021-09-29 at 2 36 54 PM" src="https://user-images.githubusercontent.com/18314510/135352321-3b46f49e-125d-4e29-bf15-b0282180bbe1.png">

I know the heading is marked by #1 in the image above, however I am not sure if the lead in comment is marked by number #2 in the image, or, if it is a paragraph underneath the heading #1.

Thank you!

**Comment by sabrinang** [comment]
@danielfmiranda If we have lead-in copy, I think it's best as a paragraph underneath the heading

**Comment by danielfmiranda** [comment]
Hi @caltrider! 

I was wondering if you wanted us to replace the  heading that says "Comments", to the text you sent me which was "Got a comment? Let us hear it", or if you would like us to add that line underneath the "Comments" heading.

Thanks!

**Comment by caltrider** [comment]
Hey @danielfmiranda. I think what @sabrinang recommends is good. Make the lead in copy of "Got A Comment? Let Us Hear It." as a paragraph underneath the "Comments" heading.
