### ISSUE TITLE
[PNI] Product page - remove SoftwareProduct from the CMS

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7392]
13-27 September sprint:

- [x] Keep the model around, keep the data, but remove any mention of the SoftwareProduct in the CMS nav/permissible child pages, etc.

Later:

- [ ] clean up the model + data later, once folks have gone over all the old softare products and deemed them removable (if not removed by staff themselves already).

**Comment by Pomax** [comment]
part 1 is done, moving issue to backlog so it can be planned into a future sprint, with updated estimate.

**Comment by tbrlpld** [comment]
There is 14 `SoftwareProductPage` items left on product, but they are all in draft state and not live.

```
>>> from networkapi.wagtailpages.pagemodels.products import SoftwareProductPage
>>> SoftwareProductPage.objects.count()
14
>>> SoftwareProductPage.objects.live().count()
0
```
