### ISSUE TITLE
RSS Feed for Kiswahili Content

### ISSUE THREAD

**Issue by Witty-Kitty** [mozilla/foundation.mozilla.org#7396]
### Describe the feature request
An RSS feed of the MoFo blog that indexes posts writted in Kiswahili.

### Additional context
A couple of us fellows working on Kiswahili for CV started a column on the Mozilla blog, which we will update every 2 weeks.
Posts are in Kiswahili and I''ve been wondering about the discoverability of this content, thinking about a scenario where we go for an event and would like the audeinces we target to be able to access the backlog of available posts.
Would it be possible to create an RSS feed, or something, that indexes these posts?

**Comment by benhohner** [comment]
Our options are an explicit category or we can tap in to the language code. We'll triage this function in our next Engagement Team meeting.

**Comment by Witty-Kitty** [comment]
Are there any updates on this request? Is it still pending?

**Comment by Pomax** [comment]
It looks like this dropped off the radar, I've added it back to the upcoming sprint so we can determine what work is necessary here.

**Comment by Witty-Kitty** [comment]
1. Because we have funding to build a Kiswahili dataset on CV, the main intention of these posts is to help with outreach and community engagement of Kiswahili speakers. Since I put in this initial request, the MoFo website has since been localised to Kiswahili, and still we face the same challenge. If you navigate to https://foundation.mozilla.org/sw/blog/, it would be ideal to only view blogposts that have Kiswahili translations as opposed to having to comb through many more that don't, so by default appear in English.
2. Main reason I suggested an RSS feed is because it can act as a 'portfolio', when we reach out to organisations that have been building in the language. Our work shows that beyond collecting the data, we care about the language and a newsletter may not have the same effect.

I'm happy to keep chatting and charting the best way forward.

**Comment by anilkanji** [comment]
@kristinashu @nancyt1 - are any of the features you're tracking to develop for the blog relevant to this ticket? i.e. will we enable functionality to use search strings to serve up specifically-tagged blogs? So that we'd be able share a search link that would deliver up, for example, only Kiswahili posts?

**Comment by nancyt1** [comment]
Our initial thoughts are to broaden our current “Categories” to be rebranded as “Topics” where we can have more niche ones (going from the current 9 to say ~30 or so) and to allow for one blog post to be have 1-3 different Categories/Topics assigned to it. So for this example it could go under both Common Voice as well as a new Topic of Kiswahili. Each post would still have a its own landing page e.g. https://foundation.mozilla.org/blog/category/common-voice/ but for this case, there would be a new one for Kiswahili.

We were also considering having a shareable search and adding a language filter on the homepage for cases like this.

**Comment by Pomax** [comment]
@nancyt1 thinking in terms of RSS, would each topic have its own RSS feed?

**Comment by nancyt1** [comment]
It would be great to have a feed for each topic in addition to the master feed and if possible going the route of having one RSS url with filter arguments to closer align with how I imagine topics might be set up.

**Comment by anilkanji** [comment]
Although RSS has been raised as a potential solution, I'm not sure that's necessary in this case - @Witty-Kitty let me know if I'm wrong. I think you're looking for a way to direct people to a page that aggregates blog posts that have a particular tag.

**Comment by Witty-Kitty** [comment]
Yes, if a language tag is an option, then a page aggregating this would
work splendidly.

Kathleen S.

**Comment by bheasman** [comment]
Keeping this issue open until resolved by the blog improvements work

**Comment by kristinashu** [comment]
Nancy's proposal is here https://redpen.io/yxc54f2b2d1dc3b782 which includes Kiswahili.
