### ISSUE TITLE
FE - Mozfest Community Directory

### ISSUE THREAD

**Issue by wilhitem** [mozilla/foundation.mozilla.org#7417]
### Design team contact
 @sabrinang
Torchbox designers from project available via slack:
* Lindiwe (ux)
* Jeth (visual design)

### Final Designs

Figma - https://www.figma.com/file/2knnwWmmqCXuMyF6WPiOuG/MozFest-Additional-Features?node-id=30%3A317

### Details
Front end ticket for #7421 

Relates to the existing component - https://foundation.mozilla.org/en/what-we-fund/fellowships-and-awards-directory/
API - https://pulse.mozilla.org/api/index.html
Examples of wagtail currently - https://foundation.mozilla.org/en/docs/how-do-i-wagtail/profiles-from-pulse/

Duplicate existing component and make following changes:

- Admin can define the tabs to show from a list of Profile Types from Pulse (years to be removed)
- Add the the Space dropdown will list all spaces of people under current tab

For each card:
- list spaces

### Implementation Checklist

Acceptance Criteria
- [ ] Matches designFilter can be turned off by profile type (keep blank space where it was to avoid content jumping)
- [ ] Navigation is horizontally scrollable on mobile
- [ ] 2 Card grid on desktop
- [ ] 1 card grid on mobile
- [ ] Current tab is highlighted

**Comment by wilhitem** [comment]
@jamilasnell this one is assigned to @stevedya and was  estimated at 3 hours, so maybe mark as a 4?
Steven does appear to have access to the repo, i just can't assign it to him currently.

**Comment by marcwalsh** [comment]
Hey @stevedya - I can answer these.

- Yes, we'll use profile_type for filtering by Wranglers, Facilitators, etc. However, it's only a limited number of options that we want to be displayed.
- The spaces filter will be by program_type (as that is a field I can add options to)
- Currently this will only be for the MozFest site, but if it works well we can share it with the Fellows team to see if they would like to implement it.
- The blue links would be the program_type (space) - but they do not need to link.

**Comment by marcwalsh** [comment]
It's very unlikely we'll see profiles with more than one space. Wranglers are only in one space. Facilitators could be in more than one space, but we can ask them to pick the main space for MVP - alternatively create a duplicate profile if they really want to be listed in both.

**Comment by SharmaineLim** [comment]
Sounds good, thanks Marc!

**Comment by richbrennan** [comment]
Closing as both PRs related to this issue have been merged
