### ISSUE TITLE
BE: Mozfest Community Directory

### ISSUE THREAD

**Issue by wilhitem** [mozilla/foundation.mozilla.org#7422]
### Design team contact
@sabrinang 
Torchbox designers available via slack:
Lindiwe (ux)
Jeth (visual design)

### Final Designs

Figma - https://www.figma.com/file/2knnwWmmqCXuMyF6WPiOuG/MozFest-Additional-Features?node-id=30%3A317

### Details
Backend ticket supporting #7421 

Relates to the existing component - https://foundation.mozilla.org/en/what-we-fund/fellowships-and-awards-directory/

Duplicate existing component and make following changes:

Admin can define the tabs to show from a list of Profile Types from Pulse (years to be removed)
Add the the Space dropdown will list all spaces of people under current tab

For each card:
- list spaces

### Implementation Checklist

- [ ] Editor can add tabs of Profile Types
- [ ] Editor can add Profiles to the tabs
- [ ] Editor can choose to show 'Spaces Filter' for each tab
- [ ] User can filter profiles by space if filter is available

**Comment by wilhitem** [comment]
@jamilasnell - this should be assigned to https://github.com/b-ggs and is estimated at 5 hours

**Comment by richbrennan** [comment]
Closing as both PRs related to this issue have been merged
