### ISSUE TITLE
FE: Mozfest Session Slider

### ISSUE THREAD

**Issue by wilhitem** [mozilla/foundation.mozilla.org#7425]
### Design team contact
@sabrinang for internal feedback

Torchbox design team available via slack:
* Lindiwe
* Jeth

### Final Designs

Figma - https://www.figma.com/file/2knnwWmmqCXuMyF6WPiOuG/MozFest-Additional-Features?node-id=54%3A296

### Details
Front end ticket for epic #7423 

Help text says "recommend up to 5 items in the slider"
User can move through items using arrow buttons
The component has a heading.

Each item in slider contains:
- Heading *
- author subheading
- Image *
- Video - autoplays on hover (optional)
- rich text copy *
- link to an internal page or external url *

### Implementation Checklist

- [ ] Hovering over card plays video
- [ ] Matches design
- [ ] Whole card is a clickable link
- [ ] Bullet navigation shows on mobile
- [ ] Arrow navigation on desktop
- [ ] On mobile videos play when scrolling into view

**Comment by wilhitem** [comment]
@jamilasnell this is another one for @stevedya estimated at 4 hours

**Comment by kristinashu** [comment]
Is this good to close?

**Comment by stevedya** [comment]
Yep as far as I know this is merged and should be okay to close 😊

**Comment by kristinashu** [comment]
yay!
