### ISSUE TITLE
Epic: Mozfest Current Event Slider

### ISSUE THREAD

**Issue by wilhitem** [mozilla/foundation.mozilla.org#7429]
### Design team contact
@sabrinang for internal feedback

Torchbox design team available on slack:
* Lindiwe (ux)
* Jeth (visual design)

### Final Designs

Figma - https://www.figma.com/file/2knnwWmmqCXuMyF6WPiOuG/MozFest-Additional-Features?node-id=2%3A5746

### Details

Help text says "recommend up to 5 items in the slider"
User can move through items using arrow buttons
The component has a heading.

Each item in slider contains:
- Heading
- link
- image
- plain text copy
- 2 buttons each with options to either link to file (such as ical), internal page or external URL

**Comment by richbrennan** [comment]
Closing as this has been merged and deployed, and is in use
