### ISSUE TITLE
FE: Mozfest Current Events Slider

### ISSUE THREAD

**Issue by wilhitem** [mozilla/foundation.mozilla.org#7430]
### Design team contact
@sabrinang for internal feedback

Torchbox design team available via slack:
* Lindiwe
* Jeth

### Final Designs

https://www.figma.com/file/2knnwWmmqCXuMyF6WPiOuG/MozFest-Additional-Features?node-id=2%3A5746

### Details
Front end implementation for epic #7429 

Help text says "recommend up to 5 items in the slider"
User can move through items using arrow buttons
The component has a heading.

Each item in slider contains:
- Heading
- link
- image
- plain text copy
- 2 buttons each with options to either link to file (such as ical), internal page or external UR

### Implementation Checklist

- [ ] Matches design
- [ ] 1.5 Cards showing at a time on desktop
- [ ] Shows arrow navigation for desktop
- [ ] Bullet navigation for mobile
- [ ] 1 card showing at a time on mobile

**Comment by wilhitem** [comment]
@jamilasnell - assign to @stevedya. estimated at 4 hrs

**Comment by kristinashu** [comment]
Is this good to close?

**Comment by stevedya** [comment]
Yep as far as I know this is merged and should be okay to close 😊

**Comment by kristinashu** [comment]
ty!
