### ISSUE TITLE
BE: Mozfest Current Events Slider

### ISSUE THREAD

**Issue by wilhitem** [mozilla/foundation.mozilla.org#7431]
### Design team contact
@sabrinang for internal feedback

Torchbox design team available via slack:
* Lindiwe (ux)
* Jeth (visual design)

### Final Designs

Figma - https://www.figma.com/file/2knnwWmmqCXuMyF6WPiOuG/MozFest-Additional-Features?node-id=2%3A5746

### Details
Back end implementation task for epic #7429 

Help text says "recommend up to 5 items in the slider"
User can move through items using arrow buttons
The component has a heading.

Each item in slider contains:
- Heading
- link
- image
- plain text copy
- 2 buttons each with options to either link to file (such as ical), internal page or external URL

### Implementation Checklist

- [ ] Editor can add a heading (required)
- [ ] Editor can add items (unlimited)
- [ ] Editor is advised that no more than 5 items are added
- [ ] Editor can add a heading to an item (required)
- [ ] Editor can add a link to an item
- [ ] Editor can add a image to an item (required)
- [ ] Editor can add a plain text description to an item (required)
- [ ] Editor can add 2 buttons with either link to file (ical) external URL or internal page (1 required, 2nd optional)

**Comment by wilhitem** [comment]
@jamilasnell this is another for https://github.com/b-ggs. Estimated at 3 hrs so maybe mark as a 4?

**Comment by kristinashu** [comment]
Is this good to close?

**Comment by richbrennan** [comment]
Closing as this has been merged and deployed, and is in use
