### ISSUE TITLE
Epic: Mozfest Tito Ticket purchase embed

### ISSUE THREAD

**Issue by wilhitem** [mozilla/foundation.mozilla.org#7433]
### Design team contact
@sabrinang for internal feedback

Torchbox designers available via slack:
* Lindiwe
* Jeth

This issue needs some developer review for level of effort.

Issues: 
Audience attrition when tickets hosted on Tito Website(Mozfest 2021 18k ticket views, 14 K exits, 9.8K registrations)

User story: As a human interested in moz things, i want to purchase a ticket so that I may attend mozfest

Clicking on a particular ticket type sends you to the purcahse flow for that particular ticket type

Feature:
Tito widget embed to improve conversions. Check out is launched when the individual selects ticket type (e.g. “Become a Mozfest contributor”). Checkout completed in overlay. (e.g. https://ti.to/docs/checkout). The embed is not customizable in it's visual design, but you can specify the options availabe for each button

https://ti.to/docs/api/widget#/

Three ticket types
Individual Contribution (participant input ticket price and quantity)
Patron Contribution (€250)
Mozfest Benefactor (€1000+)
(Rec:) Summary copy should also be included in the overlay (to produce one direction flow from ticket selection to check-out 

Tickets page: https://www.figma.com/proto/2knnwWmmqCXuMyF6WPiOuG/MozFest-Additional-Features?page-id=0%3A1&node-id=23%3A37&viewport=288%2C48%2C0.27&scaling=min-zoom&starting-point-node-id=23%3A37&show-proto-sidebar=1

**Comment by richbrennan** [comment]
BE ticket: https://github.com/mozilla/foundation.mozilla.org/issues/7534

**Comment by kristinashu** [comment]
Is this good to close?

**Comment by richbrennan** [comment]
Yep, closing as the BE and FE work has been completed
