### ISSUE TITLE
Epic: Mozfest Event Structured Data

### ISSUE THREAD

**Issue by wilhitem** [mozilla/foundation.mozilla.org#7434]
### Describe the feature request
As a human interested in Mozfest, I want to google Mozfest and get the correct information about the event

### Screenshots / mock-ups
This is really more about how we structure the data for a google search. You can see ideally what this looks like
https://developers.google.com/search/docs/advanced/structured-data/event

### Additional context
Last year when people searched for Mozfest, a particular venue in the netherlands was listed as the location even though it was virtual. they would like if people search for mozfest this year for it to point to the correct information.

Currently Mozfest uses an events content type in the wagtail implementation so this should be relatively straight forward.

**Comment by phildexter** [comment]
Should be closed by #7568
