### ISSUE TITLE
Snippet chooser panel for blog categories should not show non-English entries

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#7437]
Translated categories are showing up in the category picker, we should only show the English ones

I believe filtering should happen here? https://github.com/mozilla/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/pagemodels/blog/blog_category.py#L55

<img width="462" alt="Capture d’écran 2021-09-21 à 11 32 57" src="https://user-images.githubusercontent.com/1294206/134201941-119a7fac-afa5-413d-a964-15331ee6bed5.png">

**Comment by benhohner** [comment]
Verify still the case after we update Wagtail to 2.14

**Comment by TheoChevalier** [comment]
Tested in 2.14 & checked with Karl, we actually need to use a Snippet chooser panel here (like we do for authors etc)
@Pomax Do you think we could do that?

**Comment by Pomax** [comment]
this should be doable, I'll put it in the current sprint, do we need this "right now" or do we need this "before content entry"? Because that makes a difference in terms of which branch we target.

**Comment by TheoChevalier** [comment]
> this should be doable, I'll put it in the current sprint, do we need this "right now" or do we need this "before content entry"? Because that makes a difference in terms of which branch we target.

I believe you’re thinking about PNI, but this is only about blog posts ;) There’s no concrete deadline, next sprint is fine, I’ll hold off translating more categories until then so that we don’t flood/confuse staff with translations

**Comment by Pomax** [comment]
ahh, my bad! In that case yes, let me put it in the next sprint.

**Comment by Pomax** [comment]
Wagtail and wagtail-localize got updated since the last comment, with some fixes around this issue (choosers should now have a locale dropdown as well). 

@TheoChevalier can you check and see if this is still a concern, or whether wagtail fixed this?

**Comment by TheoChevalier** [comment]
Yup, confirming the fix is available and we can move forward with this work.

Here’s an example with the donate snippet chooser:
<img width="891" alt="Capture d’écran 2022-04-18 à 16 52 23" src="https://user-images.githubusercontent.com/1294206/163826614-b5642ed2-4e55-4f4f-a8be-7c5ad0133884.png">

**Comment by TheoChevalier** [comment]
Closing in favor of https://github.com/mozilla/foundation.mozilla.org/issues/9187
