### ISSUE TITLE
Broken share buttons on article pages

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#7438]
Share buttons at the bottom of article pages are broken. It’s currently broken on https://foundation.mozilla.org/en/campaigns/tiktok-german-election-2021/ haven’t looked other article pages, but it’s not broken on blog pages.

<img width="777" alt="Capture d’écran 2021-09-21 à 18 39 44" src="https://user-images.githubusercontent.com/1294206/134211564-216bff59-44a0-43cc-888b-b54908527d2c.png">

They link to:
https://www.facebook.com/sharer/sharer.php?u=
https://twitter.com/intent/tweet?text=
mailto:?&body=

Interestingly, the small versions of those buttons on the same page (top left) are working:
<img width="62" alt="Capture d’écran 2021-09-21 à 18 41 17" src="https://user-images.githubusercontent.com/1294206/134211787-56730f18-ac78-4c56-b75c-62af53258a87.png">
…

**Comment by jamilasnell** [comment]
#ForRich ?
