### ISSUE TITLE
PNI voting seems to be broken for (some) products?

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7440]
Looking at the database, there are a bunch of products with zero-vote data:
```
wagtail=# select distinct(title) from (
    select
        page.id, page.title as title, product.page_ptr_id, votes.id
    from
        wagtailcore_page as page,
        wagtailpages_productpage as product,
        wagtailpages_productpagevotes as votes
    where
        votes.vote_bins='0,0,0,0,0'
        and product.votes_id = votes.id
        and page.id = product.page_ptr_id
) as subquery order by title;

                      title
--------------------------------------------------
 BlueJeans
 Discord
 Doxy.me
 Facebook Messenger (and Facebook Messenger Kids)
 FaceTime
 Google Duo/Google Hangouts/Google Meet
 GoToMeeting
 Houseparty
 Jitsi Meet
 Marco Polo
 Ring Indoor Cam
 Signal
 Skype
 Slack
 Teams
 Telegram
 Threema
 Viber
 Webex
 WeChat
 WhatsApp
 Zoom
(22 rows)
```

And we need to figure out why voting does not work for these products, specifically.

**Comment by kristinashu** [comment]
This seems to be product wide. I any testing this while logged into the CMS.

**Dating app: https://foundation.mozilla.org/en/privacynotincluded/hornet/**
Before voting: 151
<img width="881" alt="image" src="https://user-images.githubusercontent.com/1068783/134221812-94aef6a7-536b-4dbd-9d35-3e2fc005be72.png">
During vote: 152
<img width="872" alt="image" src="https://user-images.githubusercontent.com/1068783/134221875-edb5ec71-8ddf-4cd1-b46d-eb46e223f938.png">
After voting: 151
<img width="867" alt="image" src="https://user-images.githubusercontent.com/1068783/134221916-086d908c-f15e-4aa2-8461-8c86dd254eb3.png">

**Nintendo Switch: https://foundation.mozilla.org/en/privacynotincluded/nintendo-switch/**
Same thing, vote count is not increasing.

**Comment by Pomax** [comment]
Looking at the database, it does not seem that new votes are getting saved, with the vote bins showing `28,24,57,22,20`, which sums to 151 rather than some higher number based on additional test votes.

**Comment by Pomax** [comment]
running vote testing against our `load_fake_data` db shows no votes getting saved either, so it looks like there's a way to locally reproduce and figure out what's going on.

**Comment by Pomax** [comment]
Further investigation reveals:
```
backend_1             | 2021-09-21 18:00:15,388 [WARNING] Forbidden (CSRF token missing or incorrect.): /en/privacynotincluded/company-teacher-room-more-stay-cover/
backend_1             | 2021-09-21 18:00:15,391 [WARNING] "POST /en/privacynotincluded/company-teacher-room-more-stay-cover/ HTTP/1.1" 403 1249
backend_1             | 2021-09-21 18:00:15,391 [WARNING] "POST /en/privacynotincluded/company-teacher-room-more-stay-cover/ HTTP/1.1" 403 1249
```
Examining the product HTML path shows that the JSX tries to send a CSRF token, but that the JS that furnishes the JSX does not extract a CSRF token to us, and that the product page template does not contain a `{% csrf_token %}` tag, which would make it rather difficult to get CSRF clearance.
