### ISSUE TITLE
add PNI voting to the tests

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7443]
PNI product voting may not have been working for 10 months, and we didn't know. This needs a test that tries to submit a value out-of-band and then confirms the numbers didn't change, as well as submitting a value with proper CSRF values, and then confirms the numbers _did_ change, so we never have a repeat of this situation...

**Comment by benhohner** [comment]
Using Cypress for integration testing

**Comment by Pomax** [comment]
I think I added this, @pomax to confirm whether we still need this issue.

**Comment by Pomax** [comment]
this got added.
