### ISSUE TITLE
Add Mozfest figma files to Mozilla Foundation account

### ISSUE THREAD

**Issue by wilhitem** [mozilla/foundation.mozilla.org#7466]
We need to add the files from our work to the Mozilla Foundation account.
Here's an invite to the account: https://www.figma.com/team_invite/redeem/G1zg8Ufjf9D3pZIAzMQbxE

Tagging Phil - I assume this is something that Jeth or Lindiwe will take on but i haven't added them as assignees in Mozilla.

**Comment by sabrinang** [comment]
@wilhitem Do you approximately know when the figma files will get added to our team account? It'd be great to get edit access to them

**Comment by kristinashu** [comment]
Adding that the Figma files also need to be updated to reflect what was actually implement since some updates needed to be made to reflect real content, dev constraints, and different responsive states.

**Comment by kristinashu** [comment]
Can this please be done before the end of this year?

**Comment by richbrennan** [comment]
@wilhitem See above

**Comment by kristinashu** [comment]
Awesome, thank you!

**Comment by phildexter** [comment]
Hi @kristinashu this should be updated now to match live.

**Comment by kristinashu** [comment]
Thank you @phildexter!
