### ISSUE TITLE
[PNI] Nav - change "all" category on mobile to a more indicative text

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7473]
- [x] Mobile only: update the category label "all" to be more indicative of the fact that it's a category selector (input needed from @caltrider)

**Comment by kristinashu** [comment]
For now, let's keep this simple and update "All" to "All Categories" on mobile. 

<img width="380" alt="image" src="https://user-images.githubusercontent.com/1068783/135141985-55fb87ec-583e-4345-a9b8-19729b40bd9c.png">
