### ISSUE TITLE
Code reviews for TBX MozFest UX updates

### ISSUE THREAD

**Issue by benhohner** [mozilla/foundation.mozilla.org#7504]
Torchbox is implementing a number of MozFest code changes including
* 3 new slider StreamField blocks (to be trialed on Mozfest site first and then ported to fo'mo if successful)
* home page UI changes

We need a quick code review for each PR Torchbox submits:
Key criteria to look at:
* Does it adhere to our coding standards?
* Is the code maintainable?

**Comment by kristinashu** [comment]
Closing this ticket since it doesn't really seem like it's being used.
