### ISSUE TITLE
Wagtail Demo Page Content

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#7506]
Compile and write first draft of content that will populate pages that demo Wagtail's page types and components. Draft has been started [here](https://docs.google.com/document/d/1hY-clLhI0N56v8oWNN5Z1DaYovYK8E2yQsxObVrdK30/edit?usp=sharing).
- [x] Compile and write first draft of content
- [x] Gather feedback from stakeholders
- [x] Revise draft
~- [ ] Gather one more round of feedback from stakeholders before building out demo page MVP~

**Comment by beccaklam** [comment]
Compile and write first draft of content that will populate pages that demo Wagtail's page types and components
- [ ] Compile and write first draft of content
- [ ] Gather feedback from stakeholders 
- [ ] Revise first draft
- [ ] Gather one more round of feedback from stakeholders before building out demo page MVP

**Comment by kristinashu** [comment]
Yes to Ben, Pomax, and Sabrina. I'd also add Daniel since he's done some Wagtail documentation and features. For the pages in general, Kaili is a Wagtail power users and sometimes answers questions from staff so you could also get feedback some from her.

**Comment by beccaklam** [comment]
@kristinashu @benhohner @Pomax @danielfmiranda @sabrinang I have a first draft of the wagtail demo page content ready for review [here](https://docs.google.com/document/d/1hY-clLhI0N56v8oWNN5Z1DaYovYK8E2yQsxObVrdK30/edit?usp=sharing). I still need to gather examples for the streamfield blocks but I figure I could do that while I wait on your feedback. Please give it a read over let me know directly in the doc if anything needs reworking. If you have any good examples you know of that you don't see in the doc please add them in as well! Thanks!
