### ISSUE TITLE
Mock ups for new YT RegretsReporter Extension landing page

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#7511]
- [x] Mock up page at different screen widths
- [x] Mock up other example use cases of how the template/components could be used
~- [ ] Meet with devs to talk about feasibility~

**Comment by beccaklam** [comment]
Note: For the text block in the header can we do a paragraph block so we have multiple rich text options. This allows for more flexibility depending on the copy staff want to use (short headline vs long headline).

**Comment by beccaklam** [comment]
[Redpen](https://redpen.io/p/ho219b2c818dc8acbb) for YouTube extension landing page mockups and other example use cases @kristinashu @sabrinang @nancyt1 Would I be able to get a design review? Other example use cases were inspired by this [giving page](https://foundation.mozilla.org/en/giving/100-days-of-privacy/) and this MozFest [On-Demand page](https://www.mozillafestival.org/nl/on-demand/).

**Comment by kristinashu** [comment]
Looking good! I left a few comments in Redpen. 

More aspirational use case could be for the hero section of https://foundation.mozilla.org/en/campaigns/regrets-reporter/findings/
