### ISSUE TITLE
InlinePanel fields not kept in sync on translated pages

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#7517]
Turns out InlinePanel fields are not `synchronized` by default, so we need to explicitly add them to the `override_translation_fields` var.

**Comment by TheoChevalier** [comment]
Once merged & deployed, Théo to:

- [ ] Sync all French video call app products
- [ ] Sync /blog
- [ ] Sync https://foundation.mozilla.org/en/blog/how-opt-out-human-review-your-voice-assistant-recordings/

**Comment by TheoChevalier** [comment]
Keeping open just so that I don’t forget the post deploy steps

**Comment by Pomax** [comment]
@TheoChevalier are there still pending steps for this one?

**Comment by TheoChevalier** [comment]
Nope, all good, thanks!
