### ISSUE TITLE
Bug - Mini site: menu on top on mobile 

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#752]
Bug happens on Firefox and Safari - iPhone 7
It is not a major usability issue since it works, I think this is a "nice to have" fix if we have the time.
cc: @xmatthewx 

The anchor for rotation of the arrow seems to be located on the right- it doesn't happen on a desktop browser, only on the phone.
![arrow](https://user-images.githubusercontent.com/22157921/30348642-f5252e26-97c4-11e7-8b74-47419f163ec1.gif)

**Comment by lejara** [comment]
Hey! pretty new here, but do mind if I can work on this?

**Comment by gvn** [comment]
Go right ahead @lejara ! Thanks!

**Comment by lejara** [comment]
Thanks! Mind giving me tips on how to reproduce this?
I know the problem is on the phone.  It could be a CSS problem.
But do you know any specific area I should start looking at?

**Comment by lejara** [comment]
#935

**Comment by taisdesouzalessa** [comment]
It works great on staging. Ex: https://foundation.mofostaging.net/opportunity/net-neutrality-groups/

Thanks all!

**Comment by taisdesouzalessa** [comment]
Just for the record here, we have to fix the prod to make sure this menu becomes visible there: https://github.com/mozilla/foundation.mozilla.org/issues/830

Closing this ticket. Feel free to reopen if we need it for anything else.
