### ISSUE TITLE
Headings with Sublinks in publications ToC not clickable

### ISSUE THREAD

**Issue by benhohner** [mozilla/foundation.mozilla.org#7526]
### Describe the bug
On publication pages, headings with sublinks on a publication page aren't clickable

### To Reproduce
1. Go here: https://foundation.mozilla.org/en/data-futures-lab/data-for-empowerment/
2. See "What Could Go Wrong? | Failure Modes for Data Stewardship"
3. Title should be clickable and lead to first subsection

### Expected behavior
TBD

### Screenshots
Working link
![image.png](https://images.zenhubusercontent.com/5fc93ac187345c0cf1d7ae58/3a46e8ba-8e12-41f0-9ce1-75c31f340b8b)

Not working link
![image.png](https://images.zenhubusercontent.com/5fc93ac187345c0cf1d7ae58/111dbaa6-8b32-4b47-8fc3-53f8a0258f07)

### Additional context
Kasia needs this fix done quickly as there is a publications launch shortly

**Comment by Pomax** [comment]
It looks like this is a templating issue, where pages with grandchildren lead to the nested menu presentation such as this:

![image](https://user-images.githubusercontent.com/177243/135311598-a6fe7cff-763a-4a06-abea-be87645d0db0.png)

where the immediate child page is not linked, and only the grandchildren are linked. The current templating code for this in `network-api\networkapi\wagtailpages\templates\fragments\publication_table_of_contents.html` is:

```
...
              <div class="col-8 ml-sm-3{% if not child.get_children_count %} d-flex align-items-center{% endif %}">
                <h3 class="{% if child.get_children_count %}publication-chapter-title mb-4 {{% else %}m-0 {% endif %}">
                  {% if not child.get_children_count %}
                  <a href="{{ child.url }}" class="d-block {% if child.get_children_count %}mb-4{% endif %}">
                    {{ child.title }} {% if child.has_unpublished_changes %}🐣{% endif %}
                  </a>
                  {% else %}
                    {{ child.title }} {% if child.has_unpublished_changes %}🐣{% endif %}
                  {% endif %}
                </h3>
...
```

Which should be updated so that the `child.title` is always wrapped in a link, probably with a CSS classing fix for height-adjustment, because the chapter "icon" does not look properly aligned with the nav menu. That second part can be done in followup though, with design input.

**Comment by benhohner** [comment]
@pomax Thinking about the proper behaviour for this, I'm leaning toward:
If there's a Section page that exists, if it has no content, it should link to the first child page, if it has content, it should link to the Section page itself. 

The reason for this being, sometimes people create section pages with content explaining the section's theme, other times they're just used to contain subpages in a thematic category.

e.g.
- Section Page (no children) -> Section Page

---
- Section Page (no content) -> Subsection Page 1
  - Subsection Page 1 -> Subsection Page 1
---


- Section Page (has body content) -> Section Page
  - Subsection Page 1 -> Subsection Page 1

**Comment by Pomax** [comment]
As long as we can detect that a page is empty, then "linking if not empty" feels like an appropriate template update. Looking at the PublicationPage, the following fields might play a role in determining whether a publication page is "empty";

- `intro_notes`
- `notes`
- `contents_title`

**Comment by Pomax** [comment]
After runnign through the options, the concensus is that we want the heading to always be clickable, and point to "the page itself" if that page has content (based any of the abovementioned three fields having content), or link to the page's first child if the page itself does not have content.
