### ISSUE TITLE
BE: Mozfest Hero updates

### ISSUE THREAD

**Issue by b-ggs** [mozilla/foundation.mozilla.org#7531]
Epic: #7432

### Describe the feature request

Make the hero editable through Wagtail Admin.

Figma for quick reference: https://www.figma.com/proto/2knnwWmmqCXuMyF6WPiOuG/MozFest-Additional-Features?page-id=74%3A283&node-id=80%3A739&viewport=288%2C48%2C0.5&scaling=min-zoom&starting-point-node-id=74%3A289

### Implementation Checklist
- [ ] Editor can add a heading
- [ ] Editor can add a CTA label and link
- [ ] Editor can specify 3 (no more, no less) subheadings each with their own heading, plain-text copy, and associated image
- [ ] Editor can specify an embedded YouTube video OR video in Wagtail

**Comment by jamilasnell** [comment]
PR has been merged https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozilla/foundation.mozilla.org/7573 so I am closing this ticket
