### ISSUE TITLE
Add a second locale to both the Django unit test suite, and our load_fake_data factory code

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7559]
Follow-up to https://github.com/mozilla/foundation.mozilla.org/issues/7502

We need to add a secondary locale as part of the test framework before can write tests that can verify that changes are correct across locales. (For PNI specifically, we also want to know that votes on localized objects make it to the original object, etc).

**Comment by benhohner** [comment]
@richbrennan feel free to reach out to @pomax for any questions or further clarification on this one!

**Comment by jamilasnell** [comment]
Hey @richbrennan ! Is this still an 8? If not, can you please re-estimate? Thank you!

**Comment by richbrennan** [comment]
I've put this down to a `1` for this sprint as there should hopefully only be a small change needed, depending on answer to outstanding question on PR.
