### ISSUE TITLE
child pages of "Giving" don't show their own title

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7571]
STR:
- Go to https://foundation.mozilla.org/cms/pages/1437/edit/
- See the title and header text in the CMS
- See the title on the live page https://foundation.mozilla.org/en/giving/happy-holidays-mozilla/ that says "Giving"
- It should say "Happy Holidays from Mozilla"

Jesse W is trying to create a new page under /giving and is having this same issue. Page is launching next week.

**Comment by richbrennan** [comment]
The title/heading logic is contained in the `primary_heroguts.html` template. This is used by the following pages:

- Banner Page (BanneredCampaignPage model): bannered_campaign_page.html
- MozFest Homepage: mozfest_homepage.html
- Other MozFest pages: mozfest-base.html

- Homepage: homepage.html

- Primary Page: primary_page.html

**Comment by richbrennan** [comment]
@jamilasnell @Pomax @kristinashu 

Can we close this one if the page has been recreated using a different type?

**Comment by kristinashu** [comment]
Curious what @Pomax thinks? We solved for the original problem with a quick fix but do you think this will be a reoccurring issue we should fix - does this help clean up or complicate our code?

**Comment by Pomax** [comment]
I'd like to mull this over for a bit to see what work (if any) Rich's findings suggest might be worth doing.

**Comment by kristinashu** [comment]
@mtdenton there is valuable info in this ticket but the original request is no longer needed. Is it ok close?

**Comment by mtdenton** [comment]
Apologies, this comment fell through the cracks. Closing now.
