### ISSUE TITLE
Update the article page template to force small rectangular image "decoration"

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7579]
Right now the article template does not properly size headline images for headings on pages like https://foundation.mozilla.org/en/what-we-fund/research/impact/, which currently looks like:

![image](https://user-images.githubusercontent.com/177243/136431160-38491b76-b2e2-4c0f-885e-2d48778e6107.png)

This might require setting dimensions on the imagetext/textimage component (because it looks like the image is a `richtext-image leftrichtext-image left`)

For design: what dimensions should these images be at the various breakpoints?

**Comment by kristinashu** [comment]
Hi @danielfmiranda! As a quick fix we just deleted the images. But you can recreate the issue by:

1) Add a image to the Content block on an Article page

 <img width="1069" alt="image" src="https://user-images.githubusercontent.com/1068783/137561673-85d28ded-b5a7-4ca4-bc23-7987953af840.png">

2) For example, you can use key2.jpg as a testing image and set it to left-aligned.

<img width="1010" alt="Screen Shot 2021-10-15 at 3 38 27 PM" src="https://user-images.githubusercontent.com/1068783/137561634-cf86d540-014c-4daa-af70-43a30dea34c8.png">

3) It looks as expect on desktop.

<img width="956" alt="Screen Shot 2021-10-15 at 3 38 37 PM" src="https://user-images.githubusercontent.com/1068783/137561638-ea6fc7f7-d302-4c91-9007-734d31d34591.png">

4) But at narrower widths, it becomes very large.
<img width="439" alt="Screen Shot 2021-10-15 at 3 38 44 PM" src="https://user-images.githubusercontent.com/1068783/137561641-2b8b1578-8a37-4da5-a4ac-712bff27dd4e.png">

5) The image should scale down proportionally with the browser width. I don't have this mocked up could if needed.
