### ISSUE TITLE
[PNI] - Subcategories - implement subcategory client-side "url faking"

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7622]
- [ ] When a user clicks on a subcategory, the URL should "fake change" using [History.pushState](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState), replacing the main category name (e.g. https://foundation.mozilla.org/en/privacynotincluded/categories/wearables/) with the subcategory name (e.g. https://foundation.mozilla.org/en/privacynotincluded/categories/fitness-trackers/)
- [ ] When a user deselects a subcategory, the URL should "fake change" back to the parent category

**Comment by kristinashu** [comment]
Done!
