### ISSUE TITLE
[PNI] Show product share info

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7625]
Currently sharing a product page URL shows the general PNI info e.g https://foundation.mozilla.org/en/privacynotincluded/jabra-elite-85t/: 

<img width="579" alt="image" src="https://user-images.githubusercontent.com/1068783/137526247-df481805-49b7-4b14-a5ae-99f62951dfdf.png">

### Each product should show:
- [ ] Title `*Privacy Not Included review: [product name]`
- [ ] Description: `[product's intro blurb text]`
- [ ] Image [Product image]

**Comment by richbrennan** [comment]
Pull request https://github.com/mozilla/foundation.mozilla.org/pull/7773

**Comment by kristinashu** [comment]
Out of scope for this ticket but I'm curious if either of you have a sense of how much work it would be to auto-style the product share images. For example, if it pulled the product photo for the page (as you've done), but then puts it on a grey rectangular background, and adds a Mozilla *Privacy Not Included logo over top. 

Audrey from social media linked to this https://itsmereal.com/automated-open-graph-image-overlay-for-wordpress/, we get that is for Wordpress but are curious if it's possible in Wagtail?

**Comment by richbrennan** [comment]
Hi @kristinashu 

The simplest way would probably be to overlay one image on top of the other using the Python Pillow image library but this isn't something I've done before unfortunately. I'll try a spike to see if I can get something working, but please chip in @danielfmiranda if you have any other ideas!
