### ISSUE TITLE
Improve Promote tab on blog pages for better content entry

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7638]
Staff either aren't aware of the Promote tab or keep forgetting to add info to it. There also seems to be info that isn't necessary for blog pages.

Is it possible to:
- Move the info that is in the Promote tab to the bottom of the main Content tab?
- Remove the "Show in menus:" checkbox, does this actually do anything?
- Make "Meta description:" a required field?
- Update name of "Search image:" to "Share image:" (since this appears on /blog and in social media feeds)?
- Hide the "Tags" field since this doesn't do anything and staff are wasting time filling it in?

**Comment by kristinashu** [comment]
Education will help but I think there are UX fixes that can be done as well to improve this. Do you have any thoughts on the individual items listed?

**Comment by benhohner** [comment]
Yep, I can definitely expand on the details! After thinking about each item a bit more I think we can act on one or two of these.

---

> Move the info that is in the Promote tab to the bottom of the main Content tab?

I believe Pomax said that the "Promote tab" (and its naming of "Promote") is a core wagtail feature, that would take a large lift to override if it's even possible. @Pomax can you clarify?

>Remove the "Show in menus:" checkbox, does this actually do anything?

Apparently this decides whether the page is included in automatically generated menus. See https://www.accordbox.com/blog/wagtail-tutorial-12-how-create-and-manage-menus-wagtail-application/ (Search for show_in_menus). Not sure where we use this feature on the site.

>Make "Meta description:" a required field?

We've filed [a separate bug](https://github.com/mozilla/foundation.mozilla.org/issues/7350) which should pull the first paragraph of article content for the meta description if the field is not filled in. Based on my experience with SEO plugins from my last role, this field is usually optional to reduce barriers to content publishing, and to ensure only people that know about SEO best practices use it.

>Update name of "Search image:" to "Share image:" (since this appears on /blog and in social media feeds)?

If this is easily doable I'm all for it. It definitely is more of a Share image than a Search image.

>Hide the "Tags" field since this doesn't do anything and staff are wasting time filling it in?

Also good point! I afaik we need to do some more work to remove tagging, but it might be possible to hide this from users.

---
I think we could also offer more SEO guidance via help text for each field by linking off to SEO best practices articles.
Really, the meta description has some pretty strict rules we need to follow for best practices, ~155 characters max, good keyword research and usage, but no keyword stuffing, etc.

**Comment by Pomax** [comment]
What would be further steps require here?

**Comment by jamilasnell** [comment]
@kristinashu any guidance here?

**Comment by kristinashu** [comment]
Based on Ben's response, the things to move forward on are:

- [ ] Remove the "Show in menus:" checkbox from **blog page type** since it  doesn't actually do anything here
- [ ] Update name of "Search image:" to "Share image:" **on all page types** since this is a more accurate discretion 
- [ ] Hide the "Tags" field since this doesn't do anything and staff are wasting time filling it in

**Comment by kristinashu** [comment]
@tbrlpld are you referring to the tags? We aren't using them. They were added but never surfaced to users on the front-end.

**Comment by tbrlpld** [comment]
@kristinashu Thanks for finding these use cases. 

Does this mean we also want to keep the tags visible in the "Promote" tab?

**Comment by kristinashu** [comment]
Yeah I guess so. I'll remove it from the checklist above.

**Comment by kristinashu** [comment]
This ticket is getting messy and unclear. Closing this one and opened https://github.com/mozilla/foundation.mozilla.org/issues/9464
