### ISSUE TITLE
Mozfest hero video: Problem uploading MP4's

### ISSUE THREAD

**Issue by wilhitem** [mozilla/foundation.mozilla.org#7643]
Notes from Sabrina regarding issue encountered w/ uploading MP4's for the hero image updates in #7585:

I am unsure if the decision should be updating the text or supporting MP4's, but something should be done to address this use case. 

**Banner Carousel**

**Video**
- I’m getting a different type of error for CMS video:
<img width="1252" alt="Screen Shot 2021-10-14 at 5 45 34 PM" src="https://user-images.githubusercontent.com/2492510/137419472-8ffa6a01-8cf1-41b0-9d0e-1398834daf94.png">

- I’m using a .mp4 file but it isn't clear what video extensions are supported so that could be added to the help text as well _(I’ve tried adding thumbnail, changing size, duration etc.)_

_Originally posted by @sabrinang in https://github.com/mozilla/foundation.mozilla.org/pull/7585#pullrequestreview-780404995_

**Comment by bheasman** [comment]
@sabrinang are you able to confirm if this is still an issue please? Thanks!

**Comment by bheasman** [comment]
Slack thread for reference: https://mozilla.slack.com/archives/C0294BBL2DT/p1634668805012900

**Comment by sabrinang** [comment]
@bheasman This issue has been resolved in https://github.com/mozilla/foundation.mozilla.org/pull/7585#pullrequestreview-784794801 — cms video uploading and external videos work.
