### ISSUE TITLE
[PNI] - Subcategories - harden the subcategory form/save logic

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7644]
The initial subcategory code from #7641 allows for some things we may want to "lock down";

- categories can be nested infinitely deep
- categories can technically be linked up into a cycle

Let's harden that code a little so that at the very least that last option isn't possible anymore, and then possibly lock down the first option, too.

From @richbrennan: 
> In case it might be useful, I've been meaning to investigate this for nested categories: https://posts-by.lb.ee/building-a-configurable-taxonomy-in-wagtail-django-94ca1080fb28

**Comment by richbrennan** [comment]
@jamilasnell @Pomax 

One I might be able to pick up?

**Comment by richbrennan** [comment]
@jamilasnell @Pomax 

One I might be able to pick up?

**Comment by Pomax** [comment]
absolutely - this also combines well with the issue for not allowing categories to be saved if there is already a category with the same name.

**Comment by Pomax** [comment]
estimating this as a 4 (dev + review time) but feel free to adjust up or down.

**Comment by richbrennan** [comment]
Had planned to look at this today but have been assigned to MozFest work

**Comment by richbrennan** [comment]
@Pomax 

> categories can be nested infinitely deep

What would be a suitable limit to how deeply they can be nested?

**Comment by Pomax** [comment]
For now, given that we're only using single-parent, let's just go with one level deep and then if we need deeper in the future and everyone's signed off on that need, we can update this code.
