### ISSUE TITLE
Page elements below the "regrets" content cannot be clicked on https://foundation.mozilla.org/en/campaigns/regrets-reporter/

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7651]
### Describe the bug

The https://foundation.mozilla.org/en/campaigns/regrets-reporter/ page has a "donate now" button at the bottom, like most of our pages, that folks can click to donate to the Mozilla Foundation. However, hovering the mouse over the button does not show it as being active, and clicking does nothing. Some further testing shows that nothing below main page content is interactible. 

The reason for this is that there are invisible divs on top of it: both `intro-text-container` and `scene-container` divs are overlayed with a height:100% irrespective of scroll position, meaning they cover the donate button as well as our footer.

**Comment by kristinashu** [comment]
This page might be deprecated and replaced with https://github.com/mozilla/foundation.mozilla.org/issues/7791. @beccaklam can you please confirm that https://foundation.mozilla.org/campaigns/regrets-reporter/ will no longer exist?

**Comment by Pomax** [comment]
Per slack, it was confirmed that this page will be archive, so I am closing this issue as no longer relevant.
