### ISSUE TITLE
Spike | New page types are missing from the Campaigns index page on /campaigns

### ISSUE THREAD

**Issue by benhohner** [mozilla/foundation.mozilla.org#7662]
### Describe the bug
Currently CampaignPages and BannerPages are displayed on the https://foundation.mozilla.org/campaigns/ Campaigns Index Page.

New page types are missing:
* PublicationPage
* ArticlePage
* Youtube regrets page
* Youtube regrets reporter page
* Dear internet page

### Describe what should happen
All first-child page types except for DefaultPage should display in the index.

Need to verify the index page is pulling properties that are available on all page types, because it's currently set to pull page types from CampaignPages

**Comment by kristinashu** [comment]
This is under "Needs discussion" - is that still the case? If so then I can set up a time to chat about this next week.

**Comment by benhohner** [comment]
Yep, I think we need to discuss: 

>which pages are not being listed right now,
    whether we can move those pages there, instead, and if not,
    whether including them in the index overview even makes sense.

I set up a chat for us next week!

**Comment by jamilasnell** [comment]
Need to separate into two tickets: 1 for the investigation and the other for the implementation

**Comment by bheasman** [comment]
Agreed to close - will re-raise if surfaces as an issue moving forward.
