### ISSUE TITLE
Enable End of Year Fundraising top banner

### ISSUE THREAD

**Issue by benhohner** [mozilla/foundation.mozilla.org#7702]
* [ ] Dig up code from previous popup
* [ ] Convert to top anchored, collapsible, site-wide banner, similar to Wikipedia's

**Comment by benhohner** [comment]
CLose on Design/Dev handooff

**Comment by kristinashu** [comment]
### Via the design ticket

Figma [mockups](https://www.figma.com/file/2TK8tXeDIiLC67TMdbMIcO/?node-id=115%3A271) & [prototypes](https://www.figma.com/proto/2TK8tXeDIiLC67TMdbMIcO/Fundraising?page-id=115%3A271&node-id=116%3A386&viewport=241%2C48%2C0.11&scaling=scale-down&starting-point-node-id=116%3A386&show-proto-sidebar=1)

Banner images in google drive: [blue banner](https://drive.google.com/open?id=1VcBPsENRH-VcJT8IFPlPhzJ2xZpRb9xg&authuser=sabrina%40mozillafoundation.org&usp=drive_fs)

- Mockup jpg and banner exported in drive if needed: https://drive.google.com/open?id=1VdNWZdgWYyDxk9Ocyco9TeU-nrjYKQ0C&authuser=sabrina%40mozillafoundation.org&usp=drive_fs
- Used Giving Tuesday copy from 'No Testing' section for mockups here: https://docs.google.com/document/d/1r2Ft9tvEZLzgBPQE3HzECTUhCMBlNiSvWyFJCJOKsTQ/edit?usp=sharing


Timeline:
- Launch Giving Tuesday version on Nov 30
- Turn off Giving Tuesday Version on Wed 1

Functionality as discussed at kick-off
- Appears at the top of every foundation.mozilla.org/ page (not PNI, MozFest, Donate)
- Clicking on the 'x' dismisses the banner
- Clicking on a new page dismisses the banner
- Scroll moves the banner up and out of view, nav remains sticky

**Comment by kristinashu** [comment]
For reference, here's moco's ticket for enabling it on their site https://github.com/mozilla/bedrock/issues/10700

**Comment by kristinashu** [comment]
Meeting notes https://docs.google.com/document/d/11YhzpzW2mloaRuw5wlqzIa0hSHVrdePwtx2c9VSh4bY/edit# and @Pomax will open a ticket for this work.

**Comment by jamilasnell** [comment]
Separate ticket has been created and this has been shipped!
