### ISSUE TITLE
[PNI QA] Product Page — alignment, formatting & dividers

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#7703]
### Desktop

- [x] add more spacing above the category label
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/2492510/138958592-1fdbe9c2-c658-4277-a239-c9d8acfdb52b.png">

### Mobile
There are a few discrepancies on mobile:
- [x] Ding alignment
<img width="300" alt="image" src="https://user-images.githubusercontent.com/2492510/138957968-ab9a92ab-f717-4b83-83a5-ddd246c4cf50.png">

- [ ] Tab alignment (starts a bit too far in on mobile)
<img width="300" alt="image" src="https://user-images.githubusercontent.com/2492510/138957843-14df377d-a3e6-4ee3-a90a-d44e6b09afc0.png">

- [x] spacing & dividers missing from `Can it snoop on me?`, `What can be used to sign up?` & `What data does the company collect?` sections _(should be similar to formatting to what is currently live)_
<img width="300" alt="image" src="https://user-images.githubusercontent.com/2492510/138958106-b58bbf77-d851-45ff-9cfc-7158cda3797b.png">

- [x] text & icon formatting for `Does this product meet our Minimum Security Standards?` section
<img width="300" alt="image" src="https://user-images.githubusercontent.com/2492510/138957245-3a460f0f-d18f-4aff-a680-76c40c322b39.png">

**Comment by jamilasnell** [comment]
Seeing some similar issues related to alignment. This is only happening when I have my browser window fill half of my giant external screen (this isn't happening when my browser is fully expanded to full the external screen). 

It is affecting the info icon in "Does this product meet our Minimum Security Standards" section under the security tab. 

<img width="569" alt="Screen Shot 2021-11-09 at 4 23 27 PM" src="https://user-images.githubusercontent.com/70977386/141027347-1cd2117b-830f-4c4f-8957-2cfb0a2ad2e5.png">

Additionally, it is cutting off the Privacy Policy section as well.

<img width="566" alt="Screen Shot 2021-11-09 at 4 23 23 PM" src="https://user-images.githubusercontent.com/70977386/141027414-50a614d2-ace3-4bed-840c-4c62694a7dc2.png">

Here is what the full screenshot looks like: 
<img width="794" alt="Screen Shot 2021-11-09 at 4 23 19 PM" src="https://user-images.githubusercontent.com/70977386/141027595-47bb0e91-5ae2-4257-bec2-fed3f88aa19a.png">

**Comment by kristinashu** [comment]
Thank you Simon for grabbing this!
