### ISSUE TITLE
Get Involved Section

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#771]
**Description:**

- [ ] The left column bottom margin is too big. 

- [ ] We have an extra horizontal line in the right column.

<img width="809" alt="image" src="https://user-images.githubusercontent.com/22157921/30604313-53c9f060-9d1f-11e7-9b9d-1c1891872fc2.png">

It seems we have an extra div there:
<img width="656" alt="image" src="https://user-images.githubusercontent.com/22157921/30604398-98f87df0-9d1f-11e7-94b4-ff16d4f1a4dc.png">

**Comment by Rishabh04-02** [comment]
@taisdesouzalessa can you please provide the link to the page you've mentioned above.

**Comment by taisdesouzalessa** [comment]
Sorry for the delay here @Rishabh04-02...it seems those changes are already done now! Thanks :).

@gvn it is all good on staging. Closing this issue.
