### ISSUE TITLE
Replace Cypress with Playwright

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7711]
The combination of docker and cypress has led to a situation where we can run cypress in CI context, where node and python run side by side, but not easy in local dev context, where different docker containers run node and python codebases. We need to rewrite how the cypress tasks work for local testing so that they fire up the correct Docker containers for us to do visual/integration testing with.

### update

Given how much headaches cypress is giving, this issue was morphed into swapping Cypress out for Playwright

**Comment by jamilasnell** [comment]
@Pomax will drop some knowledge on this ticket

**Comment by Pomax** [comment]
Adding some details: in order to make sure that cypress doesn't automatically install when running `npm install` there is a separate command `npm run cypress:install` that installs cypress, with `npm run cypress` that's runs the server, waits for its port to be serviced, and then runs cypress's integration tests. However, this relied on being able to directly run `python manage runserver`, which now happens in docker... so we need to rejigger the run scripts so that we run the server using docker, while still running cypress outside of docker.

the fun parts of package.json: https://github.com/mozilla/foundation.mozilla.org/blob/main/package.json#L20-L31

**Comment by Pomax** [comment]
- [ ] investigate https://stackoverflow.com/questions/59514234/viewing-the-interactive-cypress-test-runner-in-docker-on-linux

**Comment by Pomax** [comment]
I was able to uplift all our cypress dependencies and rewrite the node scripts so that `npm run cypress` (after `npm run cypress:install` runs the manual cypress UI locally against docker, while keeping `cypress:ci` the task we invoke for github CI. It does mean that cypress still has to be installed manually, but it's at least better than "it doesn't work at all".

**Comment by Pomax** [comment]
Cypress has changed a lot between v6 and v8, so for local image testing I've added https://github.com/uktrade/cypress-image-diff as image diffing "backend".

**Comment by Pomax** [comment]
It looks like the screenshooting is based on "Scrolling the page" which is 100% useless in our case due to `sticky` and `fixed` CSS, so back to the drawing board...

**Comment by Pomax** [comment]
https://docs.cypress.io/plugins/directory#visual-testing
