### ISSUE TITLE
Clean up tw-text-[...] classes

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7714]
The new mozfest work uses `tw-text-[...]` in a few places, with explicit font sizes rather than using one of our styleguide classes for text sizing, so we should probably look at how many there are, and what we can turn those into to make sure it's all styleguide conformant.

**Comment by benhohner** [comment]
- @kristinashu can we take a look at the usage of these styles outside of our DS and figure out whether to remove the styles or add them to the DS?

**Comment by kristinashu** [comment]
Happy to chat about this. As is, I have no idea what it's about.

**Comment by Pomax** [comment]
A lot of the mozfest work ended up using text sizes based on point sizes written directly into CSS classes, instead of using our styleguide type classes. For example, the `session-card` HTML has:

```
<a class="tw-block tw-group tw-no-underline tw-p-5 tw-border tw-border-gray-60/20 tw-text-[22px]"
```

That last class is "use text at 22px sizing", and there are 24 instances of this being used in several places now. It would be good to say "let's not do this" and instead replace them with the appropriate type classes from our styleguide.

**Comment by kristinashu** [comment]
Right, I would agree that we should replace them with the closest equivalent from our styleguide. However, there is a **chance** that a few of them are edge cases that will need to have overrides. When this work happens, @sabrinang should review the PR.

**Comment by Pomax** [comment]
closing due to the ongoing active tailwind switchover work by @fessehaye
