### ISSUE TITLE
Always show the main nav on blog posts

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7717]
Implementing part of https://github.com/mozilla/foundation.mozilla.org/issues/2989 

Update the blog page type to always show the main nav instead of the Zen mode version
- [ ] Main nav appears on all blog posts

**Comment by Pomax** [comment]
Does this also include removing the "zen mode" option entirely?

**Comment by kristinashu** [comment]
In general, keep "zen mode" checkbox as is were it currently exists. 

Currently the checkbox doesn't exist for the blog page type so you can continue to not have it as an option.

**Comment by richbrennan** [comment]
@jamilasnell @Pomax 
This looks like one I could pick up
