### ISSUE TITLE
Add scripts for generating mock data

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#773]
Reframing #651

Let's generate mock data for testing purposes. It would help find edge cases and be more useful for local dev, as we (Or I, at least) occasionally have to nuke our local dbs and re-configure them, which takes time. (Also helps new contributors spinning up have an idea of how we use the project)

So the environments would look like this:

Local (mock data)
Review app (mock data)
Staging (staging db)
Production (prod db)

**Comment by gideonthomas** [comment]
This is done?
