### ISSUE TITLE
[PNI] QA - subcategories can disappear during back/forward navigation

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7746]
1. go to https://foundation-pni-q3-2021.herokuapp.com/en/privacynotincluded/categories/toys-games/
2. click on "gaming consoles" subcategory
3. use the browser back button, subcategory is there, just unselected
4. use the browser forward button, the subcategory will have suddenly disappeared.

**Comment by sabrinang** [comment]
@Pomax What you mention happens on Chrome. When I was testing on Firefox, when you click the browser back button the heading/sub category stays the same but the URL changes only. If you go forward it still remains as the URL changes.

**Comment by danielfmiranda** [comment]
After a discussion with Simon, we found that this issue if fixed in PR: [#7761](https://github.com/mozilla/foundation.mozilla.org/pull/7761)
