### ISSUE TITLE
[PNI] QA - "privacy not included" checkbox disspears on small breakpoint

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#7748]
Beyond the small breakpoint, we are able to see the "privacy not included" checkbox:
![image](https://user-images.githubusercontent.com/18314510/139950938-28e61418-a282-4c86-9bf3-d30c3e7534ed.png)

However, below the small breakpoint the checkbox seems to disappear: 
![image](https://user-images.githubusercontent.com/18314510/139951004-30aaabfd-7683-46b6-8b84-1288475829c7.png)

**Comment by benhohner** [comment]
P1

**Comment by fessehaye** [comment]
Checked on both firefox and chrome as well as local and production and the checkbox is visible in all
