### ISSUE TITLE
[PNI] Update copy on About pages: Part 2 - Deadline EOD Mon Nov 15

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7749]
Follow up from https://github.com/mozilla/foundation.mozilla.org/issues/7701

- [x] Update https://foundation.mozilla.org/privacynotincluded/about/why/ with this ([copy](https://docs.google.com/document/d/1piZASfmYtL0TNaysIbonwLBYgcedBkJMpkHwLLAOH5M/edit))
- [x] Update https://foundation.mozilla.org/privacynotincluded/about/press/ with this ([copy](https://docs.google.com/document/d/1RPUdGpB6BrdLykWfI92vZUrmI4ZV7EaL6BsD9M6dJdE/edit))

No updates needed:
- ~https://foundation.mozilla.org/privacynotincluded/about/~
- ~https://foundation.mozilla.org/privacynotincluded/about/contact/~

**Comment by benhohner** [comment]
@kristinashu just checking in. Is this still blocked?

**Comment by benhohner** [comment]
@kristinashu do we have updated copy yet?

**Comment by kristinashu** [comment]
We don't have copy yet so this is still blocked.

**Comment by kristinashu** [comment]
Content should be ready this Thurs or Friday and needs to be live by EOD Monday.

**Comment by kristinashu** [comment]
I've added copy from Jen for Press and Why. Still waiting for About and Contact.
