### ISSUE TITLE
[PNI] QA - "privacy not included" checkbox not functioning in firefox

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#7751]
On Firefox browsers, the checkbox doesn't filter:
![330GMvN97G](https://user-images.githubusercontent.com/2492510/139963135-f5ad7ffb-c799-4717-8838-faa04f97ffd8.gif)

However, it works on Chrome/Safari.

**Comment by kristinashu** [comment]
@sabrinang I checked this when you opened the ticket and I was also seeing this same issue. But I think Pomax just fixed a cashing issue and this seems to be working for me now (if I clear my cache). Can you please double check?

**Comment by kristinashu** [comment]
via Pomax: indeed, but fixing it for FF then broke something for Chrome so this last prod push should sort that all out

**Comment by danielfmiranda** [comment]
HI @sabrinang! it looks Kristinas comments were right, when I tried to recreate this issue on both Chrome and Firefox, the checkbox seemed to be working correctly. I was wondering if you could please take a look and confirm if this is no longer an issue? If so, I will close the ticket.

Thanks in advance!

**Comment by sabrinang** [comment]
Is this the latest I should check? https://foundation-pni-q3-2021.herokuapp.com/en/privacynotincluded/

Still having issues in Firefox:
https://user-images.githubusercontent.com/2492510/140436198-156f7194-7ce8-4b09-9707-6dff1f807696.mov

Works in Chrome/Safari still

**Comment by kristinashu** [comment]
Everything is live now so you can check on production at https://foundation.mozilla.org/en/privacynotincluded/. Also make sure to clear your cache lol!

**Comment by sabrinang** [comment]
Oh yes the live production is working for me in Firefox!

**Comment by kristinashu** [comment]
kk awesome! seems to be working on all browsers so I'm gonna close this.

**Comment by danielfmiranda** [comment]
Thank you both!
