### ISSUE TITLE
[PNI] - Investigate "|extended_yes_no" flag

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#7757]
In "product_page.html" we are sending a number of items with a "|extended_yes_no" flag. 

If you take a look at the file "bg_selector_tags.py", you will see that this is used to return a human readable string from the extended yes no choices. 

However, "product_criterion.html" the template we are sending these values to, is actually expecting one of the 4 original choices (CD/NA/YES/NO). 

We should update the template and or remove the flag from some instances of "product_criterion" so we can make sure that they display the values correctly.

**Comment by Pomax** [comment]
No? `extended_yes_no` works with four values, in https://github.com/mozilla/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/templatetags/bg_selector_tags.py#L28-L39:

```python
@register.filter
def extended_yes_no(value):
    """Converts quad-state to human readable string"""
    if value == 'CD':
        return gettext('Can’t Determine')
    if value == 'NA':
        return gettext('N/A')
    if value == 'Yes':
        return gettext('Yes')
    if value == 'No':
        return gettext('No')
    return value
```

**Comment by Pomax** [comment]
ohh wait I think I misread you. Are you saying we're forwarding the uninterpreted value? Because if so, wherever that value gets displayed (not used for template purposes) that's where it should get `|extended_yes_no`'d

**Comment by benhohner** [comment]
P3
