### ISSUE TITLE
PNI - add animations for categories and products

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#7768]
Animations related to the product search page. Including navigating the category header and the transitions for hiding and showing products.

**Comment by nancyt1** [comment]
Here are 2 examples related to page load when you first land or trigger something to refresh, it loads in one row at a time or from top left to bottom right:
[https://dribbble.com/shots/16645599-Justuno-is-Live](https://dribbble.com/shots/16645599-Justuno-is-Live)
[https://codepen.io/tjroberts086/pen/mngxF](https://codepen.io/tjroberts086/pen/mngxF)
