### ISSUE TITLE
RSS feed description should output meta description instead of encoded html

### ISSUE THREAD

**Issue by benhohner** [mozilla/foundation.mozilla.org#7778]
Currently the RSS feed outputs encoded page html instead of the page's meta description.
The RSS feed description fields should be the corresponding article's meta description.

See: https://foundation.mozilla.org/en/blog/rss/

The meta description behaviour should follow the existing meta description behaviour (if Meta Description is filled in on the promote tab, display that, otherwise display the first 153 characters of the article with an ellipsis at the end)

**Comment by richbrennan** [comment]
PR https://github.com/mozilla/foundation.mozilla.org/pull/7914
