### ISSUE TITLE
Link buttons on articles are misaligned

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#7788]
### Describe the bug
It appears that link buttons on article pages are appearing misaligned with the rest of the content: 
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/18314510/140447793-8fa473e8-938e-429b-82c4-b801246fb71c.png">

However after looking at the style guide to see what buttons should look like on a page, it appears to be centered.

We should reach out to the designers to see whether or not the button should be centered. If so, make the buttons centered in the middle of the content, if not, have it left aligned with the rest of the content

**Comment by danielfmiranda** [comment]
Hi @kristinashu! I was wondering if the link buttons are supposed to be left aligned with the rest of the page content, or centered in the middle similar to the button on the style-guide. 

Thanks in advance!

**Comment by kristinashu** [comment]
Hey, please make it left aligned since that's how it is on most of the site. Sorry, which style-guide has it in the center?
