### ISSUE TITLE
[PNI QA] AI-related fields not hidden on translated pages for products that don’t use AI

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#7790]
Example here:
https://foundation.mozilla.org/fr/privacynotincluded/sonos-one-sl/

This product doesn’t use an AI, and the AI related fields are hidden on the English page, but are still visible on the French page.

English:
<img width="802" alt="Capture d’écran 2021-11-05 à 13 30 19" src="https://user-images.githubusercontent.com/1294206/140510544-69878ad0-6587-45fe-8a2b-d9bc063ac8cb.png">

French:
<img width="791" alt="Capture d’écran 2021-11-05 à 13 29 58" src="https://user-images.githubusercontent.com/1294206/140510588-4b8860fe-3308-4d65-aad8-2f77e86610b0.png">

**Comment by benhohner** [comment]
P2
