### ISSUE TITLE
Youtube Regrets Extension Landing Page

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#7791]
This epic is related to the youtube regrets extension landing page which can be found here: https://www.figma.com/file/A0TYlvLzKxnQLZr3unohQy/YouTube-RegretsReporter---product-page-test?node-id=232%3A1216

**Comment by kristinashu** [comment]
This is done https://foundation.mozilla.org/en/youtube/regretsreporter/!!!
