### ISSUE TITLE
Create the top "half" of the landing page

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#7793]
Depends on #7792

This landing page has two main sections, the top half houses:

- [x] background image
- [x] embedded Video on the right side (need vimeo link)
- [x] text on the left side
- [x] Buttons (to be added in other ticket)
- [ ] Make sure content is wrapped in {% trans %} and {% blocktrans %} tags

Figma design can be found here: https://www.figma.com/file/A0TYlvLzKxnQLZr3unohQy/YouTube-RegretsReporter---product-page-test?node-id=232%3A1216
To see how this page should format in desktop/tablet/mobile breakpoints.

**Comment by benhohner** [comment]
Need to verify
- [ ] background image content
- [ ] video content
