### ISSUE TITLE
Add the browser-sensing buttons to the top half of the page

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#7795]
Depends on #7793 
In the top half of the page, there can be two or one buttons found depending on the window width.

However, we want to try and find a way to also make it so the page knows whether the user is viewing on a desktop or mobile browser. 

If viewing on desktop browser, have two buttons render which link to extension download page for firefox and chrome. 

If viewing on mobile browser, have one button render which would allow them to send an email reminder to download the extension. 

@Pomax mentioned the ability to be able to view what browser the user is using. It might be beneficial to reach out to him early this sprint to gather more details on how this can be achieved.

Figma design can be found here: https://www.figma.com/file/A0TYlvLzKxnQLZr3unohQy/YouTube-RegretsReporter---product-page-test?node-id=232%3A1216
To see how this page should format in desktop/tablet/mobile breakpoints.

**Comment by benhohner** [comment]
Kristina mentioned we might be doing something similar with a project related to Facebook?
