### ISSUE TITLE
Implement email sending for reminder button

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#7796]
Depends on #7795 
As mentioned in the previous ticket, if the user is not viewing on a browser that allows extension, we want to render a button that says "Send Reminder":
<img width="920" alt="image" src="https://user-images.githubusercontent.com/18314510/140569586-0f4d1201-3386-4557-98e6-0aeb39c45edd.png">

We need to: 

- [x] Reach out to design to get a copy of what the process should look like (user clicks -> form renders -> success message)
- [ ] Add the functionality for when the button is clicked on

**Comment by benhohner** [comment]
Blocked:
- waiting on form design and confirmation design from designers
- waiting on copy
- email design

Ben's comments: I think this feature needs to be fleshed out more before we move ahead, we may need to delay until designers are back

**Comment by kristinashu** [comment]
Rebecca mentioned in Slack that the button should work like the email share button on our blog posts e.g. https://foundation.mozilla.org/en/blog/how-to-curb-election-disinformation-on-social-media/

Clicking on the button should
- open the person's email 
- pre-populate the email with [title] [body text] (I have asked the Brandi/Audrey for this)

I don't think it needs a form with custom styling or anything like that. I also don't think the button copy needs to be updated.

Does that make sense?

**Comment by benhohner** [comment]
@danielfmiranda to further clarify from eng side, I was mistaken about the interaction. Just needs a `mailto:` link with the correct subject filled in, should be pretty straighforward and no additional screens or email sending.

**Comment by kristinashu** [comment]
Brandi has shared this copy for the email:

### Subject
> Reminder to download RegretsReporter on your desktop

### Body
> Mozilla built RegretsReporter to help you take back control of your YouTube recommendations and make YouTube better for everyone else. 

> [Add to Firefox](https://addons.mozilla.org/addon/regretsreporter/) | [Add to Chrome](https://chrome.google.com/webstore/detail/regretsreporter/obpoeflheeknapimliioeoefbfaakefn)

> [Visit our website to learn more.](https://foundation.mozilla.org/youtube/regretsreporter)

**Comment by benhohner** [comment]
Here are some docs on the mailto format @danielfmiranda https://css-tricks.com/snippets/html/mailto-links/
Not sure if we can include sub-links, but we can probably include URLs as text. e.g. `Add to Firefox: https://addons.mozilla.org/addon/regretsreporter/`

**Comment by danielfmiranda** [comment]
Thanks so much @benhohner for the reading material!! This will make it easier to implement. going to reduce the time necesssary for this ticket from 4 to 2! And also removing this from blocked
