### ISSUE TITLE
Implement localization for landing page content

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#7797]
Once the page is built and complete, we would like to have the page content be localized. 

I believe this may be able to be achieved by using a {% transblock %} but we will want to double check with @TheoChevalier for what else we may need to accomplish this! 

Based on conversations on slack however this doesnt sound like its going to be too large of a lift.

**Comment by TheoChevalier** [comment]
Heya @danielfmiranda I don’t think we need a specific ticket for this — the engineering work needed to support localization will/should happen during the page implementation.

Like for the rest of the website, it will involve:
- Using `{% trans %}` and `{% blocktrans %}` tags in templates
- Hooking the CMS fields with Wagtail-localize in models

Of course I’ll be here to answer questions/review PRs/check everything works

**Comment by benhohner** [comment]
Just keeping around as a reminder to make sure it's done. This should be done during initial implementation

**Comment by fessehaye** [comment]
Epic tasks are done, so I am considering this task done
