### ISSUE TITLE
PNI checkbox is cut-off in German on Desktop

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#7815]
The "* Privacy not included" checkbox is currently cut-off in German on Desktop, we should make it properly wrap in two lines (or give it more space, if possible)

<img width="463" alt="Capture d’écran 2021-11-09 à 16 44 01" src="https://user-images.githubusercontent.com/1294206/140956463-1231c025-bf33-4306-89b8-300be5a54a9e.png">

**Comment by fessehaye** [comment]
Looks like it is working properly on local and live
