### ISSUE TITLE
[PNI QA] Width is broken on mobile product pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7830]
### Describe the bug
Something is breaking the layout on mobile. The content shifts sideways and I see a black bar in some sections.

### To Reproduce
1. Go to any product page https://foundation.mozilla.org/en/privacynotincluded/threema/
3. Scroll down
4. See error: content will also scroll horizontally. 

### Expected behavior
Context should scroll vertically.

### Screenshots
<img width="602" alt="image" src="https://user-images.githubusercontent.com/1068783/141174721-485155f7-9de6-434d-8be9-04fac0a312aa.png">

### Smartphone
 - Device: iPhone 12 mini
 - OS: iOS 15.1
 - Browser: both Safari & Chrome

**Comment by arun-kushwaha04** [comment]
https://github.com/mozilla/foundation.mozilla.org.git

**Comment by arun-kushwaha04** [comment]
@kristinashu can I work on this issue ?

**Comment by kristinashu** [comment]
Thank @arun-kushwaha04 but given our timeline I think it will be better if this is done internally. @fessehaye any chance you would be able to take a look at this?
