### ISSUE TITLE
[PNI QA] A.I. section question and answer display

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#7834]
The question `Is the company transparent about how the AI works?` doesn't display but the answer appears with `Does the user have control over the AI features?` while that answer does not appear.

Content on the spreadsheet I want to show on the website but doesn't:
<img width="1414" alt="Screen Shot 2021-11-10 at 1 49 53 PM" src="https://user-images.githubusercontent.com/2492510/141199360-c33bebcc-d1c5-4eb1-bb13-119fc026a038.png">
What I have entered in the CMS:
<img width="707" alt="image" src="https://user-images.githubusercontent.com/2492510/141199729-f9663e79-a907-4f1d-9cee-921c37a48236.png">

**Comment by kristinashu** [comment]
Good catch @sabrinang! @danielfmiranda @fessehaye would one of you be able to fix this before EOD Monday?

**Comment by kristinashu** [comment]
Looks like this hasn't been fixed but should be a P1 since it is showing inaccurate information.
