### ISSUE TITLE
[PNI QA] Hide empty field subheadings (What data does the company collect?)

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#7843]
For the `What data does the company collect?` section, is it possible to hide the subheading when it is unaccompanied by an answer? It might look incomplete to the reader when all other sections are filled out with answers like _can't determine_ or _N/A_ in comparison:
<img width="1534" alt="image" src="https://user-images.githubusercontent.com/2492510/141599147-171a3856-c109-4b60-870b-24e03fff426f.png">

**Comment by mtdenton** [comment]
![Capture](https://user-images.githubusercontent.com/41487159/210602142-9a3f7486-3e39-40e2-9a0e-b55443fdef49.JPG)

WAVE doesn't see an issue here from an accessibility standpoint. We can reopen this issue later, but this one is over a year old.
