### ISSUE TITLE
[PNI] Add overlay to product share image

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7859]
Follow up to https://github.com/mozilla/foundation.mozilla.org/issues/7625

Is it possible to auto-style to a PNI product share image? We now pull the product photo for the page, but is it possible to  puts it on a grey rectangular background, and adds a Mozilla *Privacy Not Included logo over top?

Audrey from social media linked to this https://itsmereal.com/automated-open-graph-image-overlay-for-wordpress/, we get that is for Wordpress but are curious if it's possible in Wagtail?

Via @richbrennan 

> The simplest way would probably be to overlay one image on top of the other using the Python Pillow image library but this isn't something I've done before unfortunately. I'll try a spike to see if I can get something working, but please chip in @danielfmiranda if you have any other ideas!

**Comment by Pomax** [comment]
This would be quite a bit of involved work, because there's nothing built in for that. We'd be writing our own image processing scripts with wagtail integration to make sure the results end up managed by wagtail's image management. It's possible, but would be a heavy lift.

**Comment by bheasman** [comment]
Closing
