### ISSUE TITLE
[PNI] Hide the creepy-o-meter face when there aren't enough products

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7875]
Some of the sub-categories don't have very many products which means the creep-o-meter isn't very accurate. Would it be possible to hide it when there are less than ~12 products?

<img width="1314" alt="Screen Shot 2021-11-10 at 3 24 24 PM" src="https://user-images.githubusercontent.com/1068783/142045560-ecfe0cf9-4e38-4d29-9efa-5508f016f05c.png">

**Comment by jamilasnell** [comment]
Is for the current iteration or for the next one? @kristinashu

**Comment by kristinashu** [comment]
Later is fine! Although it does feel a little broken as is.

**Comment by kristinashu** [comment]
**Hold on** this since it might change with the redesign.

**Comment by fessehaye** [comment]
Looks like this was already done
