### ISSUE TITLE
SEO improvements

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7882]
1. hreflang `x-default` should probably point to `/en/` rather than `/` -> #8834
1. add a `crawl-delay` to robots.txt -> #8835
1. why is the `_util` URL visible to non-CMS-authed users (can we add this to deny) -> #8836 
1. sitemap URL looks to point to a lot of 4xx pages? -> #8837
1. sitemap
    - reports of localized PNI categories under the `/en/` locale, which should not be happening. -> #8838
    - may be impairing site checks, see https://github.com/mozilla/foundation.mozilla.org/issues/8162
1. put the "Mozilla Foundation" prefix in <title> at the end of the title -> #8839
1. blog and categories: adding summary text to each card would make for a better page -> Blog improvements are in the works #8682 
1. make sure that images use alt text -> #8840
1. make sure that images without alt text that shouldn't have alt text, have an `aria-role ` that helps? -> #8840
1. finish making CMS temp redirects permanent redirects where possible -> #8841
1. the django internationalisation `jsl18n` script is apparently (a) not minified, and (b) causing 404s? -> #8842

**Comment by tbrlpld** [comment]
1 -> https://github.com/mozilla/foundation.mozilla.org/issues/8834

**Comment by tbrlpld** [comment]
I have created individual tickets in the SEO epic #8441 for the above points.

**Comment by tbrlpld** [comment]
I believe we can close this issue.

**Comment by tbrlpld** [comment]
I believe we can close this issue.
