### ISSUE TITLE
mozfest nav button should always be editable in the CMS

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7883]
The recent video work for the mozfest homepage introduced some logic that hides certain fields that are not needed in the CMS edit view for the page, but it takes out too much. Let's:

- [x] restore "all panels" first (https://github.com/mozilla/foundation.mozilla.org/pull/7884/files)
- [x] redo the logic that decides which fields to keep for which view, with @marcwalsh to confirm

**Comment by richbrennan** [comment]
Hey @marcwalsh 

Are you able to advise which fields to keep for which view, see previous comment?

**Comment by marcwalsh** [comment]
I think it's only for the MozFest Homepage - we'd need to keep the following:

- Title
- Signup
- CTA Button Label
- CTA Button Destination
- Banner Heading
- Banner CTA Label
- Banner Carousel
- Banner Video (not Banner Video URL)
- Body
