### ISSUE TITLE
YouTube Marketing Graphics (cont'd)

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#7887]
Assets needed by EOD Nov 30th
- [ ] Localized versions of [these ads](https://redpen.io/p/wpcccce987c35da2e3)
- [ ] Banner, screen shot and GIF edits if needed

**Comment by beccaklam** [comment]
Link to video: https://www.dropbox.com/s/gdx2b0v4lo2q9w0/YT%20Mozilla%20Regrets%20Reporter%20-%2020211116%20V01.mp4?dl=0

**Comment by beccaklam** [comment]
First draft of GIF [here on the drive](https://drive.google.com/open?id=1BtIEyBQkzIfs-4zgd_tJm60XM_XX94Zd&authuser=rebeccal%40mozillafoundation.org&usp=drive_fs) and on [redpen](https://redpen.io/ch9b625f2a07895ff7) (look in chrome)

**Comment by beccaklam** [comment]
Updated GIF based on feedback from Audrey: https://redpen.io/ch9b625f2a07895ff7 Asset approved via slack.

**Comment by beccaklam** [comment]
Sent asset to alexander via slack thread.

**Comment by kristinashu** [comment]
I'm pretty sure you did these!
