### ISSUE TITLE
Research Hub MVP Torchbox design support

### ISSUE THREAD

**Issue by wilhitem** [mozilla/foundation.mozilla.org#7892]
To contact team members, everyone should be available on slack.

Research lead: Jonny Peacock (jonny.peacock@torchbox.com)
Sr Designer: Nick Lee (Nick.Lee@torchbox.com)
PM: Marni Wilhite (marni.wilhite@torchbox.com)

Mozilla Design Review: @beccaklam 

Support the research and design of a digital research hub to present an easy to find, well coordinated and coherent research “face” for funders, researchers, allies, builders and policy makers.

Documents:
[Research Hub doc from Kasia](https://docs.google.com/document/d/1kgDVt376T_O8EkwVwX3oJNgLIDLRRf9Y3CnMQd5XqQA/edit?usp=sharing)
[Torchbox Proposal](https://docs.google.com/document/d/1GtBnGQNj46ZctiCHX98V9BpB_Jz4P4nz9QNSifN7Q14/edit?usp=sharing)
[Project kick off deck](https://docs.google.com/presentation/d/1T_XsyKJ8F5KKsY3B_owxLYgBQ1CnuHQhE0F8ldq_RVY/edit?usp=sharing)

Daily work tracked in [miro](https://miro.com/app/board/o9J_lj3YpBI=/?invite_link_id=332203049163).

---

### Expected Deliverables

- [x] Designs complete in figma
- [x] Prioritized backlog for implementation

**Comment by bheasman** [comment]
@tbrlpld are you happy we close this one?

**Comment by tbrlpld** [comment]
Yea, from my end this is good. We have the dev epic now to track the implementation work.
