### ISSUE TITLE
[MozFest] Design support and review cont. V

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#7896]
Continuation https://github.com/mozilla/foundation.mozilla.org/issues/7781

- Website PR design review support for MozFest 2021 TBX Milestone: https://github.com/mozilla/foundation.mozilla.org/milestone/77
- MozFest Community Directory & TiTo Widget reviews some time last week of November
- Possibly sync with Lucie and new PM for coordinating design assets and maybe remaining feedback support for Bas?

**Comment by sabrinang** [comment]
- Lucie/Josine/Bas have reached out for review on style proposals for 2022, will review by early next week

**Comment by sabrinang** [comment]
- Gave feedback and review for style proposals via email to Lucie/Josine/Bas

**Comment by sabrinang** [comment]
- https://github.com/mozilla/foundation.mozilla.org/pull/7603 has inactive deployment issue so Daniel mentioned it will have to wait until Monday to get it resolved before I can review 
- reviewed app header image and icons [redpen](https://redpen.io/p/mjf473533ba14af434) for Lucie/Bas and replied via mozfest slack channel

**Comment by kristinashu** [comment]
Thanks Sabs! I see you opened a ticket for next sprint https://github.com/mozilla/foundation.mozilla.org/issues/7976, is this one good to close?

**Comment by sabrinang** [comment]
Yes, will continue in #7976 — closing!
