### ISSUE TITLE
Custom URL for RegretsReporter video to redirect to RegretsReporter Landing Page

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#7926]
Lindsay and team are asking for a custom URL: mozillafoundation.org/regretsreporter that will redirect to foundation.mozilla.org/youtube/regretsreporter. Work with engineers to see if we would be able to set that up for them. Lindsay also asked to make it so that even if someone types ‘RegretsReporter’ the link will still work.

**Comment by beccaklam** [comment]
Currently in a slack thread with Pomax and JenC to see if this work is possible. Waiting on Lindsay to see when the deadline for this work would be.

**Comment by Pomax** [comment]
see https://github.com/mozilla/foundation.mozilla.org/issues/7931

**Comment by beccaklam** [comment]
This was possible to do but in the end we decided not to go this route because we didn't want to set a precedent other than using our true URL which is foundation.mozilla.org.
