### ISSUE TITLE
[Due 12/6] Setting DNS Records for 2022 MozFest Plaza 

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#7928]
This is a request from Marc. 

"_Setting DNS records for the 2022 MozFest Plaza, ready for public sharing on Dec 8th. The subdomain is still TBC but should know by Nov 24, IP will be known in the next week or so._"

I unfortuntely don't have any further information than what he provided. However, I belileve that we did this for the MozFest team last year.

**Comment by marcwalsh** [comment]
Hello! :)

We're going to use [schedule.mozillafestival.org](schedule.mozillafestival.org) subdomain again this year for the Plaza website, I'll have the IP address to point to in a day or so.

Is this the right repo for this, or should I open a new issue in [MozillaFoundation/mofo-devops](https://github.com/MozillaFoundation/mofo-devops)?

**Comment by marcwalsh** [comment]
Thanks @tomusher the IP is `134.209.136.114`

Also just looping in @robb-j  the developer from Open Lab who is building the Plaza so he knows when it's complete.

**Comment by tomusher** [comment]
Great, I've updated that record.

**Comment by marcwalsh** [comment]
Thanks Tom, this seems to be working. I'll close this out for now
