### ISSUE TITLE
[YouTube Regrets] Update RRELP video once video is ready

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#7939]
Currently we have a placeholder video on the RRELP. Devs will need to replace that video once the actual video is ready.

**Comment by beccaklam** [comment]
Hi @danielfmiranda here is the link to the new youtube video for the YouTube RegretsReporter landing page. Note: The link won't go live until 4am EST on Dec 2nd but I think you can swap it in before then?

**Comment by danielfmiranda** [comment]
Merging this into staging so we can have it ready for the next prod push
