### ISSUE TITLE
Add share image and customized text to RRELP

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#7964]
Placeholder ticket to add share image and customized text to the new RegretsReporter landing page.

**Comment by beccaklam** [comment]
Will try the cms share image first, if it works remind @fessehaye that he may need to update localized versions.

**Comment by beccaklam** [comment]
For now I'm thinking we can use the share image and text that we used for the old extension. 
Image: https://assets.mofoprod.net/network/images/extension-icon.original.png
Text: The RegretsReporter browser extension, built by the nonprofit Mozilla, lets you flag regrettable recommendations on YouTube.
@fessehaye

**Comment by beccaklam** [comment]
@fessehaye Updated the text above based on Lindsay's comment in slack.

**Comment by fessehaye** [comment]
https://foundation.mozilla.org/en/youtube/regretsreporter/

**Comment by beccaklam** [comment]
Brandi updated the texrt this morning so we will need a dev to fix this.

**Comment by beccaklam** [comment]
Text should be: The RegretsReporter browser extension, built by the non-profit Mozilla, ~lets you block~ helps you reject harmful YouTube recommendations.

**Comment by beccaklam** [comment]
Updated the text via the CMS and Theo is syncing the translations!
