### ISSUE TITLE
Mozilla dinosaur mascot

### ISSUE THREAD

**Issue by natewrench** [mozilla/foundation.mozilla.org#7978]
Hi I was wondering if Mozilla foundation owns the original Mozilla mascot the dinosaur one from Netscape or has it been retired all together and replaced with the Firefox like logo I don't know if it still lives on in any capacity I even know if the mascot is at the Mozilla foundation anyway since it was brought over from Netscape I was just curious I just was wondering if if Mozilla ever changes their logo main foundation logo would go back to the dinosaur mascot and keep the Firefox logo separate I don't know something about its roots.

**Comment by Pomax** [comment]
Mozilla's branding with respects to its logo is documented over on https://mozilla.design/mozilla/logo-usage, the short version is that the current logo is the mozilla word mark.
