### ISSUE TITLE
Remove Signals for building using the Heroku Build API

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#798]
as per #749, and with #656 landed, the home page now pulls in content via XHR, not during the npm build step.

It should be safe to pull out this functionality now.

**Comment by jayyyin** [comment]
May I ask what functionality needs to be removed? I'd like to help with this, as I'm new to open source system I'm uncertain how to start contributing.

**Comment by cadecairos** [comment]
Hi @jayyyin! We're looking to remove the following files, among with anything depending on them: 

[network-api/app/networkapi/utility/build.py](https://github.com/mozilla/network/blob/87c7854d9aca01caa7ac35151ab53e61dfa72e97/network-api/app/networkapi/utility/build.py)
[network-api/app/networkapi/utility/decorators.py](https://github.com/mozilla/network/blob/87c7854d9aca01caa7ac35151ab53e61dfa72e97/network-api/app/networkapi/utility/decorators.py)

The signals are set up in the people and news apps using `signals.py`and `app.py`. We might need to modify `__init__.py`

**Comment by jayyyin** [comment]
oh ok sounds good, I'd like to claim this then =D

**Comment by jayyyin** [comment]
oh quick question, what version of python do I need to test this and how should I setup the testing env.

**Comment by cadecairos** [comment]
I'm actually working on updating our documentation right now (we recently merged two repos together),  but I haven't pushed the changes to GitHub get.  

At this time,  there's the README.md file in `network-api` that is still mostly relevant

**Comment by jayyyin** [comment]
ah ok I see @cadecairos

**Comment by jayyyin** [comment]
@cadecairos just for clarity for what needs to be done I've noticed that the "tests.py" imports 
```from networkapi.utility.decorators import debounce_and_throttle``` 
which is one of the files needing to be removed I'm guessing the "debounce and throttle" class is one to be removed? or would the whole file need to be removed?

**Comment by cadecairos** [comment]
@jayyyin yeah, we can probably just modify that file to something like:

```python
from django.test import TestCase


class TestUtilty(TestCase):
    pass

```

**Comment by jayyyin** [comment]
@cadecairos oh ok thanks for the reply.

**Comment by jayyyin** [comment]
@cadecairos what should I run to test if the changes work? or should I commit and have testing done by someone else?

**Comment by jayyyin** [comment]
@cadecairos also what is replacing the ```build_static_site``` in ```post_save.connect``` in the various ```signals.py```s

**Comment by cadecairos** [comment]
> what should I run to test if the changes work?

(from `network-api` folder)
`python app/manage.py test` should run any tests - but strangely, those tests aren't running on my machine.



> also what is replacing the build_static_site in post_save.connect in the various signals.py

We should just be removing those completely.

**Comment by jayyyin** [comment]
@cadecairos alright

**Comment by jayyyin** [comment]
@cadecairos yah I've been running ```python app/manage.py test``` and it shows 

```
Creating test database for alias 'default' ...

------------------------------
Ran 0 tests in 0.000s

OK
Destroying test database for alias 'default' ...
```

doing 

```python app/manage.py runserver'''
seems to show everything is fine and the server does indeed run, I'm just not familiar with the admin system so I don't know how to farther test if everything is working as it should.

**Comment by jayyyin** [comment]
@cadecairos also I just noticed that I've been working in the Master branch by accident, how should I proceed from here to make sure I don't break something.

**Comment by cadecairos** [comment]
@jayyyin you can checkout a new branch `git checkout -b <branch_name>` and it will bring over the commits you added on top of master.

to reset your master branch to upstream (or origin, depending on what you call it) you can run `git reset --hard origin/master`

If you open up a pull request, I'd be glad to have a look and confirm that you got everything.

**Comment by jayyyin** [comment]
@cadecairos alright thanks I'll see what I can do

**Comment by jayyyin** [comment]
@cadecairos  appear to be having issues getting the branch onto the site.... so I'm uncertain how to open a pull request

**Comment by jayyyin** [comment]
@cadecairos https://github.com/mozilla/network/pull/825
here's the pull request.

**Comment by cadecairos** [comment]
@jayyyin  unfortunately, our continuous integration tests won't pass unless the pull request is made from a branch on the origin repo (mozilla/network).. and to do this an account needs write permission on the repo. 

I'm going to bring this up with the team tomorrow and work out a plan so that our CI scripts don't block patches from contributors like yourself.

**Comment by jayyyin** [comment]
@cadecairos yah I guessed as much, I was having issues with permissions to make an extra branch on it, thanks, as I would like to contribute to this project more in the future.

**Comment by jayyyin** [comment]
@cadecairos so what's going on?
