### ISSUE TITLE
[PNI] Case study and summary of metrics

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7982]
[placeholder]

**Comment by nancyt1** [comment]
Started a [brain dump doc](https://docs.google.com/document/d/1DDwWOUbarpfvQ8nwuBKk8_GfsvVrWx9ZxgQjnQhix78/edit#) and outlined how a deck or blog post could be organized + all the changes we made for PNI this year.

**Comment by sabrinang** [comment]
Met with Nancy and made good progress on discussing scope and building out the outline

**Comment by nancyt1** [comment]
Started a [slide deck](https://docs.google.com/presentation/d/1Qd51XgZK4Sqs4GqN6ZHVFVf0WNfREH9dy7WkyFLjvUQ/edit?usp=sharing) and populated it with text from the outline

**Comment by kristinashu** [comment]
FYI the PNI retro won't be until next year, once we have more info on how the ads are doing (and I guess GMT info as well).

**Comment by sabrinang** [comment]
@kristinashu  @beccaklam R?
The 2021 PNI Website Case Study from @nancyt1 and I are on google slides and ready for review here: https://docs.google.com/presentation/d/1Qd51XgZK4Sqs4GqN6ZHVFVf0WNfREH9dy7WkyFLjvUQ/edit?usp=sharing 

We aim to have this ready by our PNI retro next Thursday. We also included some of this slide content into Lindsay's wrap up deck which we will share during this week's design crit.

**Comment by sabrinang** [comment]
Also sent out a calendar invite to review this with Jamila and Jen this Wednesday.

**Comment by sabrinang** [comment]
@nancyt1 I incorporated and resolved the comments/feedback in the slide deck and updated slide content. I believe most is consolidated but would like to go over the timeline slide (if we need to be more specific as noted in speaker notes) but overall I like how you combined it. I think we are pretty close but we can also sync on this when we go over #8106 before Thursday.

**Comment by sabrinang** [comment]
https://docs.google.com/presentation/d/1Qd51XgZK4Sqs4GqN6ZHVFVf0WNfREH9dy7WkyFLjvUQ/edit?usp=sharing

We've resolved the comments and cleaned up any speaker notes in the case study. It was also referenced in our [retro](https://miro.com/app/board/uXjVOUN8nhQ=/) call today.
