### ISSUE TITLE
Youtube RR Landing page share buttons

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#7985]
### Describe the feature request
We would like to add share buttons underneath the download or send email reminder buttons.

These are requested to animate from the side when the user clicks the "share" button. 

Since we are using GSAP for animations on pages such as youtube regrets 2021. Maybe we can use that here as well? Link to docs: https://greensock.com/docs/

### Screenshots / mock-ups
TODO: Reach out to @beccaklam for screenshots/figma

**Comment by kristinashu** [comment]
@beccaklam could you please update this ticket with the Shareprogress info/requirements?

**Comment by beccaklam** [comment]
These share buttons will need to use share progress codes. The content is [here](https://docs.google.com/document/d/1JhsK7pBIulWCkLtjZW_7hBh3EcZJB9wG8akSjYYS1yc/edit?usp=sharing). I'm working on logging into share progress so I can generate the codes.

**Comment by beccaklam** [comment]
Twitter share progress code: <div class='sp_221637 sp_tw_large' ></div>
Facebook share progress code: <div class='sp_221639 sp_fb_large' ></div>

**Comment by beccaklam** [comment]
@danielfmiranda I believe you need to add this code to the head section of the HTML of the RegretsReporter landing page in order for the share progress buttons to work?
![Screen Shot 2021-12-14 at 4 18 07 PM](https://user-images.githubusercontent.com/20977376/146099916-7d128626-77a6-4b0d-a69a-d12d55b203d9.png)
