### ISSUE TITLE
Autofilled related posts are picking translated pages

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#7991]
STR:
- Edit a blog post
- Make sure only one "related post" is picked, with two empty slots
- Hit save

→ Edit the page again, the two empty slots are now (likely) filled with translated pages.

![image(3)](https://user-images.githubusercontent.com/1294206/145008143-4a0c658c-5188-4929-b528-381b369ab864.png)

**Comment by tbrlpld** [comment]
@TheoChevalier From the help text for the related posts this seems like this intended behaviour. 
>  Pick three other posts that are related to this post. If you pick fewer than three (or none), saving will automatically bind some related posts based on tag matching.

What seems undesired is that this includes pages of other locales (especially when it picks the same article).

**Comment by tbrlpld** [comment]
Locally I currently have a case where the page itself gets added to the list of related posts.

**Comment by tbrlpld** [comment]
@TheoChevalier This is ready for testing on staging.

**Comment by tbrlpld** [comment]
@TheoChevalier This is not in production
