### ISSUE TITLE
Old EN RRELP not redirecting to new RRELP

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#7993]
### Describe the bug
When you go to https://foundation.mozilla.org/en/campaigns/regrets-reporter/ the redirect to https://foundation.mozilla.org/youtube/regretsreporter/ does not work. If you take out /en/ though, it does redirect. Any idea on why and how we can fix this?

### To Reproduce
1. Go to https://foundation.mozilla.org/en/campaigns/regrets-reporter/
2. See error
3. Remove the locale specific 'en' and '/'
4. See redirect

### Expected behavior
https://foundation.mozilla.org/en/campaigns/regrets-reporter/ should redirect to https://foundation.mozilla.org/youtube/regretsreporter/

### Desktop (please complete the following information):
 - OS: MacOS Monterey 12.0.1 
 - Browser: Firefox
 - Version 94.0.2 (Firefox)

**Comment by TheoChevalier** [comment]
Hm, it works here…
@beccaklam This may be cache related? Could you try in another browser maybe?

**Comment by beccaklam** [comment]
Hi @TheoChevalier, after I opened this ticket Kristina mentioned that I may need to unpublish the /campaigns page in order for the redirect to work. It seems like it is working now, so I will close this ticket!
