### ISSUE TITLE
Update layout of the homepage news you can use feature 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7998]
Flagged my Anna in slack.

> The design of the current 'News you can use' section of the homepage has 4 slots, with the top one being large and prominent. This is great, because I can give an important or recent piece more prominence. But unfortunately, the way the headline box is designed to overlap the image, means that faces often get obscured, especially if it's a profile piece of some kind. That means I have to bump that piece down to the lower row, and it doesn't get its moment in the more prominent spot. In the short term, I guess we adjust the images themselves where possible, but might be something we could think about tweaking on the homepage itself for 2022?

Note that the graphic is pulling from the OG image.

Examples for the issue:

![image](https://user-images.githubusercontent.com/1068783/145455949-46e81b10-ceb8-421b-a513-f4a74885e481.png)

![image](https://user-images.githubusercontent.com/1068783/145455967-7a028629-7ad2-4b52-b84f-b5f16079104a.png)

![image](https://user-images.githubusercontent.com/1068783/145455990-deed3f8b-abf1-4282-b63d-8541148f8b5f.png)

**Comment by kristinashu** [comment]
via crit:
- An issue in pulse as well
- Visually interesting but obscures images
- Anna curates homepage content 
- Image is pulled from share image

Layout ideas:
- Change proportion of cutout, not overlap image but color 
- Change alignment options (left, right etc so editors have a choice)
- Remove or reduce cutout (make it easier for editors, accessibility) +1
- Use cutout style elsewhere that doesn’t impede content
- Changing proportions could happen easy from dev perspective or alt pulling image
- Align image ratio for news you can use (not have cut off logos) +1

**Comment by navyagarwal** [comment]
Hey! Can I try to solve this issue, I am trying to start out with open source, and this looks like something I could do...I am not sure if this is the right protocol to follow tho...any insights are much appreciated

**Comment by kristinashu** [comment]
Hi @navyagarwal, thank you so much for your interest in helping us with this. This ticket will first need one of our designer to mock up the designs before any code can begin. Also, unfortunately, we currently don't have the capacity to onboard new people or to run them through the code and do PR reviews.

**Comment by navyagarwal** [comment]
Hi @kristinashu ! Thank you so much for the reply, I will look for some other projects :)
