### ISSUE TITLE
Changing Language on Donate Page

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#8011]
We have a request to change language on the donate page. "Bitcoin" is listed in the "in the other ways to give" section. 

That page links to a mana page and then eventually a form. We need to update the language on all these pages to show that we accept a diversity of crypto currencies through Bitpay (not just Bitcoins). Ideally, we'd simply add the BitPay button next to the PayPal button.

![image.png](https://images.zenhubusercontent.com/5f592fe47f30fa8d24d93d20/371e9435-8fe4-42cd-855e-0dd85d41faa9)

Listed it as high priority in order to get this done before code freeze.

**Comment by jessedward** [comment]
When we have more time, adding the bitpay payment mark (https://brand.bitpay.com/7b6hnbyxw/p/76b712-payment-mark/b/600f40), similar to PayPal, will be most helpful in securing more cryptocurrency donations. In the meantime, I'd like the text that says "Bitcoin" in the "other ways to give" section to say "bitpay (cryptocurrencies)". And instead of linking to the mana page, it should like directly to the bitpay payment form (https://bitpay.com/100257/donate). I also need some text updates to that payment form but tracking down who has access to that page.

**Comment by Pomax** [comment]
I'll form a PR to update that term and the link in the mean time.

**Comment by Pomax** [comment]
Note that there is also the "Bitcoin" section at the bottom on https://donate.mozilla.org/en-US/ways-to-give, and it looks like the FAQ page is a normal CMS page that staff can update themselves, mentioning bitcoin a several places.

**Comment by Pomax** [comment]
Issue moved to [mozilla/donate-wagtail #1603](https://github.com/mozilla/donate-wagtail/issues/1603) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Pomax** [comment]
I have moved this issue to the donate repository.

**Comment by jamilasnell** [comment]
Re-opening this ticket as we have decided to pause accepting cryptocurrencies for the time being. For reference, Marc's [slack thread](https://mozilla.slack.com/archives/G4TED39AS/p1641488157000600) and the [twitter conversation](https://twitter.com/mozilla/status/1479143340159422468). I think it would be good to remove the ability to do bitcoin donation on this page https://donate.mozilla.org/en-US/ways-to-give and @jessedward  can you please remove the reference to bitcoin on the [FAQ](https://donate.mozilla.org/en-US/ways-to-give/) page?

**Comment by jessedward** [comment]
Is that FAQ page a wagtail page that I can edit? Just making sure I have
access to it.

Jesse

**Comment by Pomax** [comment]
That is a request best made in the wagtail channel.

**Comment by danielfmiranda** [comment]
Hi Everyone, reclosing this ticket in place of https://github.com/mozilla/donate-wagtail/issues/1608 on the donate repo.
