### ISSUE TITLE
MozFest: Add support for multiple Tito events

### ISSUE THREAD

**Issue by richbrennan** [mozilla/foundation.mozilla.org#8013]
Each Tito event has its own webhook API key and newsletter sign-up question ID (currently set in environment variables `TITO_SECURITY_TOKEN` and `TITO_NEWSLETTER_QUESTION_ID`). As these are currently global in the Mozilla site only one Tito event can be supported at a time.

Suggest creating a new Event snippet to store the event slug (currently set on the Tito widget block), API key and newsletter sign-up question ID (keep 'releases' specific to the Tito widget block). The snippet can then be selected in the Tito widget block. Access to the event snippets in Wagtail can be restricted with Group permissions to help protect the event API keys, if required.

The webhook Django view will also need to be updated to find retrieve the API key and question ID based on the event received by the hook.

Update the `Mozilla Festival` section of the project README to reflect the changes.

**Comment by bheasman** [comment]
Hi @marcwalsh ! Nice to meet you (I've recently joined on the Torchbox team). As I understand it, this issue was raised off the back of a conversation where you indicated there might be an appetite to support multiple Tito events. Is this something the team would still like to do?

**Comment by cdanfon** [comment]
Issue assigned to Kalob (he doesn't have ZenHub access as yet)

**Comment by cdanfon** [comment]
Hi @marcwalsh Thanks for that! When would MozFest 2023 planning start?

**Comment by marcwalsh** [comment]
We're into the planning process now, I haven't got a date for ticket launches but it should be after the summer.

**Comment by tbrlpld** [comment]
@marcwalsh Can you confirm that the users should be signed up to the same Mozfest newletter?

**Comment by tbrlpld** [comment]
Current implementation see: https://github.com/mozilla/foundation.mozilla.org/commit/ce64714f0a1d6895e3cf2cdeb88600e9f3550fd0

**Comment by marcwalsh** [comment]
Hi @tbrlpld - yes that's correct - it should always add them to the MozFest list. Also I can confirm now that we're launching Early Bird tickets w/c December 6th.

**Comment by cdanfon** [comment]
@marcwalsh ready for you to test!

**Comment by danielfmiranda** [comment]
Tested this on staging and everything looks good to me 👍

**Comment by marcwalsh** [comment]
Currently the Tito registration portion of this is working, and I'm able to register for a Tito after setting the snippet. However I'm not currently receiving the double opt-in email that should be triggered when checking the newsletter sign up question. 

I'm confirming with Tito if there is a difference between the question slug (which is how I currently have the snippet set up) and ID, and if it is the slug vs ID that is causing the issue it would be good to add more detail on how to obtain this in the help text when creating the snippet.

**Comment by marcwalsh** [comment]
I switched over the numeric ID however I'm still not receiving the double opt-in.

**Comment by cdanfon** [comment]
@tomusher can you look into this for Marc please?

**Comment by tbrlpld** [comment]
Since this is working with rendering IDs to the template, I just wanted to raise awareness of the default localization of numbers that is applied to the templates: https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/stack.md#localiztion-of-numbers

**Comment by fessehaye** [comment]
pushed to prod
