### ISSUE TITLE
remove the venv activation from npm scripts

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#802]
We added npm scripts for activating the python virtualenv and then running mezzanine, but unfortunately this _only_ works on operating systems that understand the `source` command. This means that the npm scripts cannot run on windows (nothing exists that does what `source` does for bash, on windows), and so running everything with a convenient npm script cannot work (not even in theory).

We should remove the automatic venv activation and runserver command from the npm scripts, and find a way to make the commands necessary to run the mezzanine server the same irrespective of the OS used.

**Comment by gvn** [comment]
How about we add x-platform support instead of removing something currently useful for the majority of developers in the interim?

**Comment by cadecairos** [comment]
The only possible cross platform solution I know of right now is `virtualenvwrapper` (`virtualenvwrapper-win` for windows)

if we made it a requirement for development, we can put something like this in the setup:

```
Create a virtual environment with virtualenvwrapper: 
  - OSX/Linix `mkvirtualenv network -p python3`
  - Windows `mkvirtualenv network -p C:\Python36\python.exe`
```

Then, in an npm script we can run `workon network` and it will activate the virtual environment regardless of the platform.

**Comment by Pomax** [comment]
`pipenv` fixed this.
