### ISSUE TITLE
[MozFest] Progress bars on homepage hero displaying incorrectly

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/foundation.mozilla.org#8020]
The MozFest homepage hero should be showing three white progress bars above each headline. 

_Old staging screenshot:_
![Screen Shot 2021-10-08 at 8 24 55 AM](https://user-images.githubusercontent.com/30226684/146423222-c3bb2234-67f4-4b66-962f-99065def951a.png)

Currently, the white progress bars are appearing as blue dots.

![Screenshot 2021-12-16 at 17 48 42](https://user-images.githubusercontent.com/30226684/146422852-8d2ae8ad-e796-43a5-bef8-13d147a7c201.png)

Seems to be an issue across browsers, and only appeared recently.

**Comment by tbrlpld** [comment]
@marcwalsh It looks on staging like the slide indicators / progress bars are replaced by little circles. 

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/24797493/151049284-1712bc2a-2192-4abb-bf99-4a804a14410f.png">

The automatic transition still works and clicking the circles to change the slide (background image) also works. 

I presume that the slide/carousel library was updated. I'll dig.

**Comment by tbrlpld** [comment]
@marcwalsh This will be ready for testing on staging momentarily: https://github.com/mozilla/foundation.mozilla.org/actions/runs/1757749422

**Comment by tbrlpld** [comment]
https://mozillafestival.mofostaging.net/en/
