### ISSUE TITLE
Related blog post should reflect the designated order

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#8021]
via Anna in Slack 

> I just published a blog post, but the related posts at the bottom of the page are showing up in the wrong order. Any idea why/how I can fix? I think it might be defaulting to chronological order, rather than what I tell it in Wagtail..? Thanks in advance!

Screenshot of CMS vs live page https://foundation.mozilla.org/en/blog/why-facebook-snapchat-and-google-want-smart-glasses-to-be-a-thing/

![image](https://user-images.githubusercontent.com/1068783/146573522-df0581e9-85dc-4970-abc0-db99f739edf9.png)

**Comment by AnnaLCJay** [comment]
Wanted to add a new layer to this! I just noticed that if I 'save draft' on an unpublished blog post, it re-orders the related blog posts into chronological order in Wagtail, rather than keeping them as I'd arranged them. I assume that's probably the same underlying bug, but wanted to flag in case.

**Comment by tbrlpld** [comment]
I can not observe the issue with the admin and the frontend not showing in the same order, but I can reproduce that the order in the admin seems to be overridden on save.

**Comment by tbrlpld** [comment]
@kristinashu This is ready for testing on staging: https://foundation.mofostaging.net/en/blog/misinformation-and-disinformation-at-mozfest-2022/

**Comment by kristinashu** [comment]
Excellent, thank you! Looks like this is working well now.
