### ISSUE TITLE
Create monochromatic news glyphs

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#803]
We currently have lots of News glyphs missing, as Gavin mentioned [here](https://github.com/mozilla/network/issues/796#issuecomment-332898475). This ticket is to address that.

Task breakdown:
1. check the News that don't have glyphs (in prod site - staging has a different database so the News aren't updated there)
2. find the News logos online
3. make them monochromatic 
3. upload them to the CMS (prod admin)

cc: @xmatthewx

**Comment by xmatthewx** [comment]
Cool. Sounds tedious. You might rope in Kevin for collaboration. 

At the end of this work, let's also file a ticket to either show a placeholder (gray cirlce or dot?), or to align Publication title left.

**Comment by gvn** [comment]
Left align is the current behavior for missing glyphs, but a regression in the CMS code is causing missing glyphs to output as broken URLs instead of empty strings. It should be fixed in the next prod push...

**Comment by taisdesouzalessa** [comment]
Talking to Kevin about logos and featured images here: #812

@gvn you had mentioned something about automating the glyphs, maybe adding the grayscale in css? I'll file a ticket for future discussions, ok?

**Comment by taisdesouzalessa** [comment]
@Sydette please let me know if we have an editorial calendar for the news so we can work together in a workflow to collect the news glyphs in advance - maybe in a spreadsheet or something? Based on the discussion we had last week, it would be good to have the glyphs for most of the news, right?

@gvn I will do a test first to see how the page looks like with automatic grayscale glyphs first (currently we use a uniform shade of grey in the glyphs, so it is highly designed). I'll do that post-Mozfest and then file an implementation ticket when the need arises.

**Comment by kristinashu** [comment]
News glyphs have proven to be unrealistic to maintain and so we are no longer using them.
