### ISSUE TITLE
Use the same code for pulling pulse data

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#8033]
With https://github.com/mozilla/foundation.mozilla.org/pull/7603 landing, we now have two different files that use the same code to access pulse, which is a great source of future bugs. Let's make sure to turns this into "there is only one authoritative place where pulse results are fetched".

**Comment by eleensmathew** [comment]
Hi I am interested to work on this. Since this is my first project please guide me

**Comment by Pomax** [comment]
Hi @eleensmathew, unfrotunately we don't have the capacity to onboard contributors, we're using this label to triage an initial workload for a new hire.

**Comment by tbrlpld** [comment]
@Pomax I am not quite sure on how to tackle this one. I do see there are multiple points in the backend where we are pulling data from Pulse (these are differnt block types). But I have also noticed that some of these blocks implement a way pull form Pulse on the server and on the client side (I guess so there is already data in the template on first render). 

Which are the ways we want to merge here? Do we want to remove all the backend access? All the frontend access? Or just create some client that abstracts the Pulse API (for the differnt locations on the backend)?

**Comment by tbrlpld** [comment]
I think I am also blocked, because there are I get CORS errors from the Pulse API.

**Comment by tbrlpld** [comment]
@Pomax Now that we have the CORS issue figured out, I am wondering if this is still a worthy cause, since we discussed in Retro that the future of Pulse is unclear. 

The bug fixes are probably worth it still for the mean time, but a larger refactoring like this might be more questionable.

**Comment by Pomax** [comment]
Closing for now - if we want to invest effort here in the future based on a decision around pulse we can always revisit this.
