### ISSUE TITLE
Figure out why the pulse filters don't show up in the list of permissions

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#8034]
Pulse filters show up in the list of snippets:

![image](https://user-images.githubusercontent.com/177243/146805723-3155bf75-0b0d-4b90-a77e-bb87507bd030.png)

But they are nowhere to be found in the list of items that can be assigned permissions when creating/editing a group.

Code:

https://github.com/mozilla/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/pagemodels/pulse.py#L9

**Comment by richbrennan** [comment]
Findings so far:

- Pulse Filter shows in Group permissions locally with production DB backup, but not on staging or production

- Clearing the staging cache and then restarting the dynos doesn't help

This seems to be something to do with permissions not being present on staging/production. [This Group form code](https://github.com/wagtail/wagtail/blob/v2.15.1/wagtail/users/forms.py#L204) fetches the registered [permissions for snippets ](https://github.com/wagtail/wagtail/blob/v2.15.1/wagtail/snippets/wagtail_hooks.py#L39)when constructing the 'Object permissions' list on the Group admin page.

When recreating the call in the shell locally vs staging the list of permission objects is empty on staging:

Local:
```>>> from django.contrib.auth.models import Permission
>>> from django.contrib.contenttypes.models import ContentType
>>> from networkapi.wagtailpages.pagemodels.pulse import PulseFilter
>>> ct = ContentType.objects.get_for_model(PulseFilter)
>>> Permission.objects.filter(content_type=ct)
<QuerySet [<Permission: wagtailpages | pulse filter | Can add pulse filter>, <Permission: wagtailpages | pulse filter | Can change pulse filter>, <Permission: wagtailpages | pulse filter | Can delete pulse filter>, <Permission: wagtailpages | pulse filter | Can view pulse filter>]>
```

Staging:
```>>> from django.contrib.auth.models import Permission
>>> from django.contrib.contenttypes.models import ContentType
>>> from networkapi.wagtailpages.pagemodels.pulse import PulseFilter
>>> ct = ContentType.objects.get_for_model(PulseFilter)
>>> Permission.objects.filter(content_type=ct)
<QuerySet []>
```

So to progress we need to investigate why the permissions don't appear to be present on staging and production.

**Comment by Pomax** [comment]
This is starting to smell like a migration file got updated in-place, where stage/prod had the class, then later it got switched to a snippet, but the migration that created the class got updated, rather than landing a new migration that changed the data layout.

**Comment by bheasman** [comment]
Moving back to backlog as agreed in standup until we have a clear sense on Pulse strategy

**Comment by mtdenton** [comment]
Moving this up for Maintenance/bug issues

**Comment by tomusher** [comment]
In looking in to this, these permissions now seem to be present on both production and staging.

Looking at deployment logs, there was an error running migrations starting when these models were first added, meaning the full migration process (and `contrib.auth`s `post_migrate`) was not running. This seemed to be fixed by a change on Jan 11, which allowed the migrations to succeed and the permissions were correctly generated.

**Comment by tomusher** [comment]
Created #9547 to prevent similar issues by exiting out of the release pipeline when commands fail.

**Comment by tbrlpld** [comment]
Thanks for looking into this @tomusher. I left one question on the PR, but only for my own learning 😅

**Comment by tbrlpld** [comment]
Merged and deployed. All is well. Thanks for this @tomusher.
