### ISSUE TITLE
PNI has duplicate categories in the prod db

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#8092]
Running wagtailpages migration 0064 on the prod db crashes on this line:

```python
    BuyersGuideProductCategory = apps.get_model("wagtailpages", "BuyersGuideProductCategory")
    healthAndExercise = BuyersGuideProductCategory.objects.get(name="Health & Exercise") <--
```

because apparently more than one category has this name. Which should not be the case. It looks like wagtailpages/buyersguideproductcategory id:5 and wagtailpages/buyersguideproductcategory id:61 both have the "Health & Exercise" name, despite #61 supposedly being a Polish translation (and so shouldn't be the same string)

**Comment by TheoChevalier** [comment]
Hm, translation has been started for this snippet, but there’s currently no Polish translation here: https://pontoon.mozilla.org/pl/foundation-website-content/templates/snippets/wagtailpages.BuyersGuideProductCategory/5-health-exercise.pot/?string=230845

It’s not clear if we’re doing something wrong in our code or if it’s a wagtail-localize bug, but all I can say is this is a valid use case (translation of the page/snippet started, waiting for actual translation of the string)

**Comment by TheoChevalier** [comment]
FWIW, I’ve synced these snippets, it seems the share image was missing on translations, but I doubt it has anything to do with the error above

**Comment by Pomax** [comment]
I see, yes then that's probably a code issue - it uses `get` rather than `filter` so it's getting that alias atm without filtering for the english-locale-only objects.
