### ISSUE TITLE
[Design Ops] Look into naming conventions for design files

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#8099]
Look into best practices for naming design files both while we're working on something and when we hand off to stakeholders.

**Comment by beccaklam** [comment]
Some links:

- https://libguides.princeton.edu/c.php?g=102546&p=930626
- https://bootcamp.uxdesign.cc/file-naming-conventions-for-designers-c08f288b4d2a
- https://guides.lib.purdue.edu/c.php?g=353013&p=2378293
- https://www.oreilly.com/library/view/web-design-in/0596009879/ch04s03.html

**Comment by kristinashu** [comment]
Closing this and opened a broader ticket https://github.com/MozillaFoundation/Design/issues/1104
