### ISSUE TITLE
[Interactive Report PT] Summarize Stakeholder Interviews

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#8105]
Do a brief analysis of the stakeholder interview responses from ticket [insert number]. Share next steps based on responses.

**Comment by beccaklam** [comment]
Analysis started in this [doc](https://docs.google.com/document/d/1N2N_TJ1pUajytEGDA3mlp00ZyPDrYnn7sfHbcABqJP0/edit?usp=sharing)

**Comment by beccaklam** [comment]
Summary finalized in this [doc](https://docs.google.com/document/d/1N2N_TJ1pUajytEGDA3mlp00ZyPDrYnn7sfHbcABqJP0/edit?usp=sharing)

**Comment by kristinashu** [comment]
Amazing summary. It's nice to see stakeholders are all pretty aligned. With this info and the landscape analysis, I think you're ready to start designing!
