### ISSUE TITLE
Current Events Slider no longer full width on MozFest homepage

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/foundation.mozilla.org#8131]
The 'Current Events Slider' on mozillafestival.org is now constrained to the width of the content in the left column where previously it would be the full width of the page - even with the newsletter snippet on the page. This is across FF/Chrome/Safari on desktop. The mobile version is not affected.

## Current View:
<img width="1284" alt="Screenshot 2022-01-21 at 15 56 54" src="https://user-images.githubusercontent.com/30226684/150559784-a7794890-1817-464c-93db-38bbfe994e61.png">

## Previous View:
<img width="1282" alt="Screenshot 2021-11-04 at 17 44 39" src="https://user-images.githubusercontent.com/30226684/150561175-e77f3839-348c-41b8-aa06-a8f0f0e6d7a2.png">

**Comment by kristinashu** [comment]
@sabrinang please link to the PR related to this, ty!

**Comment by sabrinang** [comment]
original PR related to this here: https://github.com/mozilla/foundation.mozilla.org/pull/7457
