### ISSUE TITLE
Add YouTube icon/link to footer

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#8157]
Lindsay D has requested we add the YouTube icon and link https://www.youtube.com/user/Mozilla to the footer on fo’mo & PNI (see mozfest site for YouTube icon already in their footer).

- [x] Mock-up the footer, responsively
- [x] Open dev ticket, include the icon, mockups, url link, and where the icon should appear, note to let Lindsay know once it's live

[White Youtube Icon](https://drive.google.com/file/d/17J8K4AAegb-jp-Vbks_jBUJcw2P2BDt6/view)
[Figma File](https://www.figma.com/file/zTPKwhxfBiHIHEYFxryJbh/Footer-Update?node-id=0%3A1)

**Comment by nancyt1** [comment]
Opened the [dev ticket](https://github.com/mozilla/foundation.mozilla.org/issues/8212) and i'll let lindsay know when it's live

**Comment by kristinashu** [comment]
Looks good Nancy! I just added a few check boxes to the dev ticket to make sure it is super clear to devs.

<img width="271" alt="image" src="https://user-images.githubusercontent.com/1068783/153047018-160d0908-b588-4eed-a5e1-d14380ef8b84.png">
