### ISSUE TITLE
Donate: Inbound link broken - 404

### ISSUE THREAD

**Issue by anilkanji** [mozilla/foundation.mozilla.org#8161]
A [review ](https://datastudio.google.com/reporting/12b9f4b6-c354-4f1a-9d08-749a36d08789/page/qAvjC)of our website analytics flags that there is broken inbound donate link:

donate.mozilla.org/en-US/page/contribute/Give-Now/?source=mozillaorg_default_footer&ref=firefox_about&tm_source=firefox&tm_medium=referral

We can't find where this page was intended to go, and it's not a link type that we use. We also can't find the source (i.e. where this link is coming from).

It's a not-insignificant amount of traffic we should be directing to a real donate page

**Comment by Pomax** [comment]
Issue moved to [mozilla/donate-wagtail #1631](https://github.com/mozilla/donate-wagtail/issues/1631) via [**ZenHub**](https://www.zenhub.com/)
