### ISSUE TITLE
Investigate and potentially fix sitemap.xml

### ISSUE THREAD

**Issue by anilkanji** [mozilla/foundation.mozilla.org#8162]
Filing this issue on behalf of contracted agency Grassriots:

* Working on technical SEO evaluation for the Foundation
* In utilizing SEMrush, unable to complete full audit of pages, even after whitelisting
* Used another tool instead - screamingfromg - and determined SEMrush was somehow blocked/hindered by sitemap.xml
* Guessing there may be a misconfiguration in the sitemap.xml file 
[SLACK THREAD HERE](https://mozilla.slack.com/archives/C02G16GSQS1/p1642177455007600)

**Comment by Pomax** [comment]
Looking at both the local sitemap and the one on https://foundation.mozilla.org/sitemap.xml I don't see anything obviously wrong. We may be able to see if we redo the work based on https://www.mashandgravy.co.uk/blog/google-friendly-sitemaps-multilingual-wagtail-sites

**Comment by bheasman** [comment]
Anil following up with Grassriots for more info on the issue and how to move forward.

**Comment by bheasman** [comment]
Hi @anilkanji - any movement on this one from Grassriots?

**Comment by bheasman** [comment]
NB - this ticket just covers the initial call with Grassriots

**Comment by Pomax** [comment]
discussion scheduled for March 3rd

**Comment by anilkanji** [comment]
Talked to GR 7/3/2022:  - Still seeing incorrect content header type when using xml sitemap validators - can we try replicating this error and figure out what’s broken?

**Comment by Pomax** [comment]
_which_ incorrect header type, though? Because our server's sending `content-type: application/rss+xml; charset=utf-8` which is 100% the correct type for RSS feeds.

**Comment by anilkanji** [comment]
Hi @ryanbaillargeon - would love more clarity on this!

**Comment by Pomax** [comment]
I'm going to close this issue because as far as we can tell the XML is correct, without any further details that we can action on.
