### ISSUE TITLE
PNI product thumbnails are blank

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#8172]
PNI thumbnails appear broken on staging https://foundation.mofostaging.net/en/privacynotincluded/, prod is working fine so I suspect one of the latest changes broke this.

I’ve checked with both Chrome & Firefox.

You can see links are still there, it’s just text + image are missing

<img width="1257" alt="Capture d’écran 2022-01-31 à 15 16 08" src="https://user-images.githubusercontent.com/1294206/151809420-882db976-8c3a-4aaa-92a2-db860df9e135.png">

**Comment by Pomax** [comment]
temporarily reopening, seeing errors on staging:

**Comment by Pomax** [comment]
when I type `gsap` in the console, it looks like it's there, so it's possible the bg code doesn't timeout-wait for gsap to load in?
