### ISSUE TITLE
iFrame Customization   

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#8174]
According to comments below, the ask is to be able to add the "scrolling" flag to the iframe block, as in the requester's use case https://www.mozillafestival.org/en/on-demand/audio/, it appears that the iframe from anchor.fm (the place where we host the mozilla podcast episodes) seem to render a large whitespace underneath the media player, within the iframe itself.

Screenshot of audio player iframe on render:
<img width="937" alt="Screen Shot 2022-02-08 at 5 16 25 PM" src="https://user-images.githubusercontent.com/18314510/153103373-5537f33b-f4c2-41ec-9c35-c7a2f15a5a99.png">

Screenshot once scrolled down on the iframe:
<img width="937" alt="Screen Shot 2022-02-08 at 5 18 35 PM" src="https://user-images.githubusercontent.com/18314510/153103482-7dd1f675-a4f5-47ad-af5c-0ea53fff644f.png">

**Comment by danielfmiranda** [comment]
Hi @marcwalsh @anilkanji I was told you both might have more context regarding the "Iframe customization" task on Airtable. I was wondering if you could help me figure out what the ask of that ticket is so I can implement it?

Thanks in advance!

**Comment by marcwalsh** [comment]
Thanks @danielfmiranda 

So the iframe embed code we’re using for Anchor.FM looks like this:
`<iframe src="https://anchor.fm/letsgetlitical/embed/episodes/Is-the-Internet-a-human-right-featuring-Soledad-Magnone--Joseph-Thomas-e1dnj15" height="102px" width="400px" frameborder="0" scrolling="no"></iframe>`

The page that’s in the frame is long and has white space at the bottom, but setting the height and being able to add the `scrolling="no"` parameter would mean the user cannot scroll into the white space as it does currently on the [embed at the moment](http://mozillafestival.org/on-demand/audio)

Let me know if there's other details you need

**Comment by danielfmiranda** [comment]
Thank you for the details @marcwalsh! They are much appreciated

**Comment by danielfmiranda** [comment]
Though the original ask was to add a "scrollable" flag to the iframe block which would then add the scrollable='no' to the iframe element if checked, I first checked to see if I was able to produce the desired effect using just CSS as according to the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-scrolling) the "scrolling" flag has been deprecated.

Interestingly enough however, it does in fact seem to be the only thing that is able to achieve the desired results. 

Inspecting the anchor.fm iframe on my dev environment, I can see that the issue is caused by a:
`<main class="styles__appChildrenContainer___zRgNt" id="app-content">`

In which some CSS sets the min-height to 300px:

<img width="236" alt="Screen Shot 2022-02-08 at 5 55 51 PM" src="https://user-images.githubusercontent.com/18314510/153107165-86e5fb12-c250-431d-9906-2aa470dbb0e8.png">



However when trying to override the iframes CSS even using a new specific classname and !important, the original min-height seems to persist. 

Like mentioned, I have only found luck with actually using the scrollable='no' flag, which does seem easy enough to add as a checkbox in the iframe block/template, though I am hesitant due to its status on the MDN. 

So I wanted to check with the team what they think about adding this feature @Pomax @tbrlpld @fessehaye 

Thank you in advance!

**Comment by Pomax** [comment]
The real solution of course is to get anchor to remove their `min-height: 300px" CSS, but barring that, as far as I can tell setting an `overflow: hidden` on the iframe itself also removes the scrollbar _on some browsers_ with the `scrolling="no"` solution work in browsers where overflow does nothing. So we probably want to use both in this case.
