### ISSUE TITLE
Update wagtail-localize-git to 0.12.0

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#8185]
wagtail-localize-git just got [a new release](https://github.com/wagtail/wagtail-localize-git/releases/tag/v0.12.0) fixing issues for us, let’s update.

We just make sure to specify the l10n repo branch name and set it to `master`

**Comment by Pomax** [comment]
Given that we're working with branch names for this one, can we rename those main branches from `master` to `main`? Might as well clean that naming up before we hardcode "master" in even more places.

**Comment by TheoChevalier** [comment]
I think we should do this in two steps, in case we need to revert to 0.11. I’ve updated steps in the PR
