### ISSUE TITLE
Unable to "npm start" a fresh clone of repo.

### ISSUE THREAD

**Issue by flukeout** [mozilla/foundation.mozilla.org#819]
I followed the instructions in the repo, and I'm getting an error when running ``npm start``.

I'm running...
* Node 6.8.1
* npm 3.10.8
* Python 2.7.10

cc @gvn @alanmoo 

---

Here's the relevant part of my ``npm-debug.log``

```
17 error Darwin 15.4.0
18 error argv "/usr/local/Cellar/node/6.8.1/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.8.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error network@1.0.0 start: `npm i && npm run build-uncompressed && run-p server watch:**`
22 error Exit status 1
23 error Failed at the network@1.0.0 start script 'npm i && npm run build-uncompressed && run-p server watch:**'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the network package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm i && npm run build-uncompressed && run-p server watch:**
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs network
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls network
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by flukeout** [comment]
With the help of @patjouk we were able to get up and running. I'm going to leave this open until tomorrow, when I'll help @taisdesouzalessa get her environment up and running. I'll use that session to make notes and update the README.md files in both repos.

**Comment by alanmoo** [comment]
See also #685

**Comment by gvn** [comment]
I'd also definitely recommend updating Node. It's up to `8.6.0` now.

**Comment by flukeout** [comment]
---

In `network-api` folder

* virtualenv -p python3 venv
* source venv/bin/activate
* pip install -r ../requirements.txt
  * do this after you have the venv running?


In `network` folder

* cp env.default .env

In `network-api` folder

* python app/manage.py migrate
* python app/manage.py createsuperuser
  * Leave blank for mozilla
  * use your own email
  * make up a password
  
In `network` folder

* npm start

**Comment by flukeout** [comment]
cc @cadecairos @gideonthomas @gvn - the instructions above work on a Mac assuming all of the dependencies are installed. I've verified this by running through the process a few times my self and with @taisdesouzalessa

**Comment by alanmoo** [comment]
Thanks for documenting all that out, @flukeout!

**Comment by flukeout** [comment]
I'd also recommend adding install instructions for the main dependencies, as well as explanations of what they are.

**Comment by flukeout** [comment]
What i used...

* Brew to get python
  * `* $ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
* Use brew to get python
  * `brew install python`
* `sudo easy_install pip` to get PIP
* `pip install virtualenv` - PIP to install `virtualenv`

**Comment by Pomax** [comment]
fixed a while back.
