### ISSUE TITLE
Datawrapper: Read docs and training materials

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#8192]
Goals: 
* [x] Have an overview of possible charts that are going to be possible to do.
* [x] Create some basic documentation on how to implement them. 
* [x] Rough implementation outline. Have a look what we did for other embed blocks (Tightform, Airtable).

**Comment by fessehaye** [comment]
We are going to add documentation to #8190 at the same time we will be adding the new block to the style-guide
