### ISSUE TITLE
Figure out how to make blog categories dynamic, without streamfield migrations

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#8224]
In order for the `recent_blog_posts` component to do its job, it needs to present the user with a category picker, based on the categories currently available in the CMS. However, using code like:

```python
    category_filter = blocks.ChoiceBlock(
        label='Filter by Category',
        required=False,
        choices=BlogPageCategory.get_categories(),
        help_text='Test this filter at foundation.mozilla.org/blog/category/',
    )
```

with the `get_categories` implemented as

```python
        choices = []
        # This Try/Except block is used to avoid errors during tests/new-envs,
        # without this, it will return a ProgrammingError due to BlogPageCategories not yet existing.
        try:
            choices = [(cat.name, cat.name) for cat in BlogPageCategory.objects.all()]
            choices.sort(key=lambda c: c[1])
        except ProgrammingError:
            pass
        choices.insert(0, ('All', 'All'))
        return choices
```

Means that every time the categories change, Django sees a change to the streamfield content of anything that uses the "recent blog posts" component (which is three page types).

What we want is a way to have a dynamic picker in the admin, _without_ having to prebuild a list of options.

**Comment by Pomax** [comment]
@tbrlpld I would like to pair with you on this one, if that's okay with you.

**Comment by tbrlpld** [comment]
@Pomax happy to pair on it. At first glance I would think the removing the parenthesis from `choices=BlogPageCategory.get_categories()` should do the trick. 

With the parenthesis the choices attribute is filled at import time, e.g. when Django is checking for changed fields that need migrations. What we want is for the method to be evaluated lazily at run time (when the form is displayed). To get that, I think we only need to pass the method name without the parenthesis, since `ChoiceBlock` accepts `choices` to be a callable (as well as a list of options).

**Comment by Pomax** [comment]
this might be good to still pair on before April 15th

**Comment by tbrlpld** [comment]
@danielfmiranda Has this been QAed yet? If not, can you assign the responsible person? Should be Claudia or the designer who requested the work.

**Comment by cdanfon** [comment]
@danielfmiranda Please add QA instructions for @mtdenton to QA

**Comment by tbrlpld** [comment]
@danielfmiranda This is still missing QA instructions

**Comment by danielfmiranda** [comment]
Hi @tbrlpld apologies for the delay, I noticed a small bug that I am creating a PR for, will be up very shortly

**Comment by danielfmiranda** [comment]
Steps to test:

1. Visit a page that is using the "recent_blog_entries" block, such as https://foundation.mofostaging.net/cms/pages/19418/edit/
2. Scroll down to the recent_blog_entries block, and take a look at the choices for the blog topic filter:
<img width="1844" alt="Screenshot 2022-11-15 at 12 21 08 PM" src="https://user-images.githubusercontent.com/18314510/202017793-2423fc5c-c6ec-4432-83eb-46bfbaf1e91f.png">
3. Visit https://foundation.mofostaging.net/cms/snippets/wagtailpages/blogpagetopic/, and create a new topic
4. Take a look at the list of topics on https://foundation.mofostaging.net/cms/pages/19418 again, and the new topic should be part of the list
5. If everything is working as expected, testing is complete!

**Comment by tbrlpld** [comment]
@danielfmiranda I have tested and this seems to work.

**Comment by mtdenton** [comment]
Same, looks good from here.
