### ISSUE TITLE
[Interactive Report] Accordion component

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#8246]
Design and prototype component

**Comment by kristinashu** [comment]
Looks good!
- I don't think it should have a mandatory header  
- I like the minus (an x feels more final, like it's closed forever like a popup)
- Left a comment in redpen, but I would allow for more styling like adding url links, bold and italic text

**Comment by beccaklam** [comment]
[Updated the design](https://redpen.io/cte3cdc276478b8bc9) based on Kristina's comments. Adding in the following to include in the Accordion content cms:

- Bold
- Italic
- Numbered list
- Bulleted list
- Document link

@kristinashu Can I get another R+? Thank you!

**Comment by kristinashu** [comment]
Yes R+!

**Comment by beccaklam** [comment]
@kristinashu Thank you! Some thoughts this morning: wondering if we should add Image and perhaps Datawrapper to the Accordion content. I was looking at YouTube Regrets Findings which has that type of content in its accordions. Though, during discovery, the only comment I got from staff was that accordions were useful for glossaries. Another solution I was wondering about is if we could build the accordion component to be a div that can contain other blocks like the Content block or the Datawrapper block, leaving its contents to be very open ended? So for example, if someone wanted a traditional accordion, their layout might be: Accordion block + Content block. But if someone wanted something more substantial, their layout could be: Accordion block + Content block + Datawrapper block.

**Comment by kristinashu** [comment]
As discussed in slack, let's just stick with the basic accordions for now. 

Note: this block should be available on some of our other page types as well, not just articles.

**Comment by beccaklam** [comment]
As discussed on slack and above I've updated the designs to reflect a [basic accordion design](https://redpen.io/p/voffc50587b06bc101).

### Design to Dev Hand-off Checklist:
- [ ] Build Accordion Functionality
- [ ] Add Styling
- [ ] The body of the Accordion should include:
-  Bold
-  Italic
-  Link
-  Numbered list
-  Bulleted list
-  Document link
