### ISSUE TITLE
Remove @set-text-size mixin

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#8281]
All SASS files are using the `@set-text-size` mixin. 

Since the move to Tailwind, we would need that mixin anymore. 

Refactoring the sass files will be a lot easier if we do not have to think about how the mixin transforms even if it makes the sass files temporarily more dry code

**Comment by bheasman** [comment]
@fessehaye to flesh this out ahead of next sprint

**Comment by Pomax** [comment]
@fessehaye at the time this issue made sense, but without an actual comment I have no idea what the plan was =D

Can you either edit the first comment to add details, or just close it if no longer relevant?
