### ISSUE TITLE
Sidebar isn't visible on opportunity pages with children

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#830]
https://network.mozilla.org/opportunity/2017-tech-policy-fellows/

**Comment by gvn** [comment]
Ok, this is completely baffling me.

The sidebar shows up in Firefox but not in Chrome or via a `curl` request. I even tried creating a new parent and subpage to see if Firefox had a cached copy and the result is the same.

Since this is generated on the server the only thing I can think of is user agent causing variances in the rendered HTML...but I have no idea why that would be the case.

**Comment by alanmoo** [comment]
Can you spoof the UA in Chrome and see if it does anything?

**Comment by gvn** [comment]
Changing UA to Firefox in Safari and Chrome didn't render the sidebar. Not surprised...

Also, this doesn't repro when I run the site locally.

**Comment by gvn** [comment]
Sidebar is now showing up on staging. I can't see anything in the last 2 commits that might have fixed this, but maybe a prod push will take care of things...

**Comment by gvn** [comment]
Ok, this has to be an environment variance issue.

Staging and prod are running identical code now and still only prod has this issue.

See:
https://network.mozilla.org/opportunity/test-parent/
versus
https://network.mofostaging.net/opportunity/test-parent/

I also can't repro the issue locally.

**Comment by gvn** [comment]
@cadecairos Is there any way to generate a diff on `network-api/app/networkapi/templates/pages/landingpage.html` between our current production and staging builds?

**Comment by xmatthewx** [comment]
We going to have a few new users of this multipage feature soon-ish. So good to dig into this.

**Comment by alanmoo** [comment]
I...think it works now?

**Comment by taisdesouzalessa** [comment]
Hey @alanmoo, the menu is sill not displaying in prod site - iPhone 7 (Firefox and Safari) - not sure about other phones, though.

**Comment by alanmoo** [comment]
The plot thickens. On desktop I see the sidebar...unless private browsing is turned on.

**Comment by alanmoo** [comment]
AHA! It doesn't show in private browsing because you're not logged in. I tested across devices/browsers and is indeed the issue: The secondary menu only appears if you're logged in to the back-end of Mezzanine. Let's make that not happen, and we'll be good across all these cases.

**Comment by taisdesouzalessa** [comment]
Mystery solved then? That was a good one!

**Comment by Pomax** [comment]
Are there steps to ensure an opportunity page when starting with a fresh clone?

**Comment by alanmoo** [comment]
I believe the PR that just landed this week should do it. `python manage.py load_fake_data`

**Comment by alanmoo** [comment]
This has been resolved. Turns out it was the "published" vs "draft" status of the main `Opportunity` page causing problems. It has to be in `Published` mode.

**Comment by Pomax** [comment]
I am actually reopening this until we have issues filed to address where to find the information we uncovered, so this "never happens again" =)

**Comment by Pomax** [comment]
Follow up:

- implement something that highlights part of, or the entire chain of, pages are set to `draft`, which can cause the side menu to disappear. Tracked as https://github.com/mozilla/foundation.mozilla.org/issues/984
- add an entry to our editor guide over on https://mzl.la/cms-guide that explains this situation in a "troubleshooting" section for mini-sites. Tracked as https://github.com/mozilla/foundation.mozilla.org/issues/987
- add an entry to the developer guide, which is really just the README.md, that lets devs find the editor guide as well, as they will need to be able to find this guide when doing user testing during development or as part of debugging. Tracked as https://github.com/mozilla/foundation.mozilla.org/issues/988
