### ISSUE TITLE
ResearchHub MVP implementation

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#8306]
As part of this epic, we want to create an MVP implementation of the Research Hub section. 

I would propose to implement the MVP in a iterative fashion to allow the different tasks to be split between people and being able to show progress. 

[Designs](https://www.figma.com/file/6BXnlCvPcQrtIaxunvuBYc/Mozilla-Research%3A-Inspiration)

[Model list and page structure](https://docs.google.com/document/d/19WoZxJvisMsHnXqA4GDX3Te6t9JnqAI2NG5jE9J4LP4/edit?usp=sharing)

**Comment by tbrlpld** [comment]
@Pomax @bheasman @TheoChevalier One topic I think I have totally missed when mapping out this work is the internationalisation. Do we expect the "research hub" to be translated?

**Comment by TheoChevalier** [comment]
> @Pomax @bheasman @TheoChevalier One topic I think I have totally missed when mapping out this work is the internationalisation. Do we expect the "research hub" to be translated?

Yes, please. Generally speaking, we should always consider content will be localized at some point.

**Comment by tbrlpld** [comment]
Thanks @TheoChevalier. That makes sense.

**Comment by tbrlpld** [comment]
@bheasman I have added "must have" and "nice to have" labels to the tickets. I hope this helps tracking the "MVP" and further work.

**Comment by bheasman** [comment]
Thanks @tbrlpld - good flag. I've assigned @beccaklam to a few tickets for now. We'll just need to keep ahead of things by assigning a handful for Becca to review each sprint.

**Comment by beccaklam** [comment]
Overall this ticket and the Model list and page structure doc looks good. It will be good to confirm with Kasia on Friday what is MVP and what is not. I also just had two little questions I've put at the end of this comment:

## MVP or not?
**Landing page**
- "Meet the researchers" section
- About block - can this content be covered in the intro text with a link to a more robust About page?
- Research Newsletter doesn't exist, do we keep this as donate?

**Research Library**
- Load more or pagination for now?

**Research Detail**
- Overview section: do we need this or is the Intro text enough?
- Related news & events section (also, is this automated or not? right now the implementation looks like it's manually filled in?)

## Other questions:
**Research Detail**
- Region is listed in the model doc but I don't see a place for it in the design
- Why is the 'filter_year(year: int)' functionality needed?

**Comment by tbrlpld** [comment]
@bheasman @beccaklam @kristinashu Would it make sense for us to also also have each ticketed QAed by design? Or should we add another ticket for design sign-off/QA after the implementation tickets are done?

**Comment by kristinashu** [comment]
@tbrlpld typically the designer who created the designs would review all the tickets with the dev and review each front-end related PR. So ideally Nick would be doing this and then Rebecca can just have a few check-ins along the way and at the end. @bheasman mentioned Nick will be available to work on this towards the end of the month and early next month. Rebecca can help in the meantime but has pretty limited capacity and really isn't as familiar with all the design decisions as Nick would be.

**Comment by tbrlpld** [comment]
Thanks for the clarification of the process @kristinashu. 

@bheasman Do you think we can secure some of Nick's time for QA or the PRs? If we have to wait for the end of the month, the reviews are going to block a bunch of the work. 

I guess we would also have occasional reviews with him (e.g. once per sprint).

**Comment by bheasman** [comment]
@tbrlpld I've got some of Nick's time from the 25th April. It's gonna be tricky to get any before then. If @beccaklam is able to QA any tickets in the meantime to prevent a build up, that'd be amazing?
