### ISSUE TITLE
[RH] 2 - Research detail page - main fields

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#8310]
![image.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/52a39c99-c091-46ae-9593-18bd4b7340ce)

Add main fields to [research detail page](https://docs.google.com/document/d/19WoZxJvisMsHnXqA4GDX3Te6t9JnqAI2NG5jE9J4LP4/edit#heading=h.3hme6b9wqnh):
  - Original publication date
      - Date
      - Date the original work was published (not the page linking to the work)
      - We need this to be a proper date object for the filtering capabilities
  - Authors
      - [Inline panel](https://docs.wagtail.org/en/stable/topics/pages.html#inline-models)
      - Orderable through model
          - Parental key [Research detail page]
          - Snippet chooser [Profile]
      - Min 1
  - Topics
      - [Inline panel](https://docs.wagtail.org/en/stable/topics/pages.html#inline-models)
      - Orderable through model
          - Parental key [Research detail page]
          - Snippet chooser [Research topics]
      - Optional
  - Region
      - [Inline panel](https://docs.wagtail.org/en/stable/topics/pages.html#inline-models)
      - Through model
          - Parental key [Research detail page]
          - Snippet chooser [Research region]
      - Optional
  - Intro
      - Plain text
      - 300 characters
  - Links
      - [Inline panel](https://docs.wagtail.org/en/stable/topics/pages.html#inline-models)
      - Orderable inline model
          - Parental key [Research detail page]
          - External link or document link
          - Text
  - Overview 
      - Richtext field, maybe stream-field
  - Collaborators
      - Plain text
      - 500 characters

Implementing this page will also require that the related snippet models are created. 

- Research topics (snippet)
  - Fields
      - Title
      - Description
          - Plain text
          - Max 250 char
          - Used on the landing page

- Research regions (snippet)
  - Fields
      - Name

All of this is necessary to start developing the filtering capabilities of the library.

See also:
- [Research hub models](https://docs.google.com/document/d/19WoZxJvisMsHnXqA4GDX3Te6t9JnqAI2NG5jE9J4LP4/edit#)
- [Designs](https://www.figma.com/file/6BXnlCvPcQrtIaxunvuBYc/Mozilla-Research%3A-Inspiration)

***

**Acceptance criteria**

- [ ] All the above fields are added to the page type and are editable in the admin.
- [ ] The snippets models for research topic and research region exist and can be created and associated with the research detail page.
- [ ] Factories for the snippets exist.
- [ ] The page factory is adjusted to fill all the added fields.
- [ ] The page template is adjusted to display the above fields (in a basic manner).

**Comment by bheasman** [comment]
@tbrlpld to add detail around fake data for testing & also field spec from the doc into this ticket - thanks!

**Comment by bheasman** [comment]
@beccaklam please could you review this one from a design perspective? Thanks!

**Comment by beccaklam** [comment]
The ticket for this looks fine! It would be good to confirm with Kasia though that she is okay with the manual entering of all these fields?

**Comment by bheasman** [comment]
Thanks @beccaklam - will pick up with Kasia later.

**Comment by bheasman** [comment]
The overview section is optional - so as agreed we'll need some design time to review how this'll render if not populated. Nick will have time from the 4th May to look at this - so for the upcoming sprint I think we should assume the field will be populated and then revisit once we have the designs in. Sound ok @tbrlpld ?

**Comment by tbrlpld** [comment]
@bheasman Field exists already but is not enforced to be filled. I guess we are not going live before Nick had a chance to review the design. So I don't think we need to force editors to enter data, because they won't see it until we can handle having it empty visually.
