### ISSUE TITLE
[RH] 3 - Library page - basic search

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#8311]
![image.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/e1a76a99-3e89-4da3-a8b9-c423f9e76644)

Implement a simple search feature for the research hub on the "research library" page. We can start with a simple implementation that updates the search results with a full page load. 

See also:
- [Research hub models](https://docs.google.com/document/d/19WoZxJvisMsHnXqA4GDX3Te6t9JnqAI2NG5jE9J4LP4/edit#)
- [Designs](https://www.figma.com/file/6BXnlCvPcQrtIaxunvuBYc/Mozilla-Research%3A-Inspiration)

***

**Acceptance criteria**

- [x] List all "research detail pages" when loading page without search query
- [x] Allow sorting 
  - [x] newest first
  - [x] oldest first
  - [x] alphabetically (a-z) 
  - [x] alphabetically reversed (z-a)
- [ ] When a search keyword is entered into the search input box, the list of displayed "research detail pages" is filtered down to the pages that include the search term. 
- [x] Only pages of the same locale as the locale of the request (current locale) are displayed. This makes sure that the search results would also be accessible via browsing on the page. 
- [x] When search filter is used, show total number of results for the search term.

**Comment by bheasman** [comment]
@beccaklam please could you review this one from a design perspective? Thanks!

**Comment by beccaklam** [comment]
@tbrlpld Just curious for: 

> When a search keyword is entered into the search input box, the list of displayed "research detail pages" is filtered down to the pages that include the search term.

Is it if the term shows up in the title or anywhere in the report?

**Comment by tbrlpld** [comment]
@beccaklam They word has to be in any of the fields on the "research detail page". That would be "title", "introduction" or "overview". 

I have also added "collaborators" to the searchable fields, in case someone is search for names that are not the main authors.

**Comment by beccaklam** [comment]
This ticket looks good to me! ✅
