### ISSUE TITLE
[RH] 5 - Landing page - main section

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#8314]
![image.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/5c873024-07eb-4712-8c6f-1727c670a699)

See also:
- [Research hub models](https://docs.google.com/document/d/19WoZxJvisMsHnXqA4GDX3Te6t9JnqAI2NG5jE9J4LP4/edit#)
- [Designs](https://www.figma.com/file/6BXnlCvPcQrtIaxunvuBYc/Mozilla-Research%3A-Inspiration)

# Acceptance criteria

- [x] Add necessary fields and methods to create the main section of the [landing page](https://docs.google.com/document/d/19WoZxJvisMsHnXqA4GDX3Te6t9JnqAI2NG5jE9J4LP4/edit#heading=h.etsvp4r9p6tx)
- [x] Displayed and editable fields
  - Title
  - Intro
      - Plain text
      - Max 250 char
- [ ] Search field — submitting leads to keyword filtered listing page
- [x] “Browse all” links — link to unfiltered listing page
- [x] Latest research (3 items) automatically pulled
- [x] Topics in the "browse by topic" element can be selected by authors
- [ ] Topic links (one link per topic to the listing page filtered by the given topic)

**Comment by bheasman** [comment]
@beccaklam please could you review this one from a design perspective? Thanks!

**Comment by beccaklam** [comment]
This looks good to me! ✅

**Comment by danielfmiranda** [comment]
Hi @beccaklam! I am going to start working on this ticket pretty soon, but was wondering if it was possible to get a mock up of this section on tablet size please? 

<img width="697" alt="image" src="https://user-images.githubusercontent.com/18314510/163501120-6f1c5361-31b2-4738-9b38-fc87d9b9f68c.png">

I was thinking of having the "research" title cutout, "latest research" section, and "browse by topic" section all stack on top of one another like in the mobile rendition. However, I was wondering how wide you wanted these sections to span across the screen on tablet size.

Thank you in advance!

**Comment by tbrlpld** [comment]
@danielfmiranda I think it's a good question you are raising about the tablet design. But I think that is out of scope for this ticket. Styling (and I am counting the mobile and tablet arrangements for that) will be implemented as part of #8385 (because that one is still blocked). 

It should be ok for this ticket to apply only very basic styling.
