### ISSUE TITLE
[RH] 6 - Author detail "page"

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#8315]
![image.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/9e8cbcee-9a57-43c8-88da-0746e4df5649)

**Reconsidered in design-dev sync 2022-03-02:** Reuse "content author" snippet. Rename (e.g. People) and extend that snippet with extra fields. Make the author detail page be automated. 

*** 
This is not really a page, but a route on the author index.

Add a route to the "research author index page" that allows display of an "research author profile". A "research author profile" is a `Profile` snippet that is associated with a "research detail page". The association is created with an orderable through-model. 

One thing to figure out is how you can create slugs for the different profiles. E.g. you could take the name, but people can have the same name. So there needs to be something else.

It might make sense to list the "authors" on the index as part of this, to make QA testing a bit simpler.

**Acceptance criteria**

- [ ] You can open a research authors "detail page" at some slug below the "research author index page". E.g. `research-hub/browse-authors/jane-doe`.
- [ ] `Profile`s have unique slugs, even if they have the same name
- [ ] The page shows name, tagline (job description), intro and image from the `Profile`
- [ ] The page shows the last 3 (most recently published) research items (links to the research detail pages).

***

See also:
- [Research hub models](https://docs.google.com/document/d/19WoZxJvisMsHnXqA4GDX3Te6t9JnqAI2NG5jE9J4LP4/edit#)
- [Designs](https://www.figma.com/file/6BXnlCvPcQrtIaxunvuBYc/Mozilla-Research%3A-Inspiration)

**Comment by bheasman** [comment]
NB - will require fake data for testing (+ field spec in the ticket)

**Comment by bheasman** [comment]
Moving into stretch for this sprint the approach has changed significantly - we can pick up next sprint

**Comment by tbrlpld** [comment]
The listing of the authors research will require #8310 to be merged. I think I should be able to prepare the rest without.

**Comment by tbrlpld** [comment]
Waiting for #8448 to finish review and be merged

**Comment by bheasman** [comment]
@beccaklam please could you review this one from a design perspective? Thanks!

**Comment by tbrlpld** [comment]
@beccaklam I have created an example on staging. Should be visible until Monday. This is not styled yet!

https://foundation.mofostaging.net/en/research/authors/305/bartholemew-bellchambers/

**Comment by beccaklam** [comment]
Thanks for sharing @tbrlpld Nice to see this page coming together!
