### ISSUE TITLE
[RH] 3.1 - Library page - pagination

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#8316]
# Description

Add pagination to library page. 

The design contains a "load more" button, to dynamically extend the list of results. In the first pass, we are not going with that, but with standard pagination of the results and full page refreshes. There is #8532 to implement the dynamic "load more" functionality.

The design has been updated to reflect the desired pagination style. 

![image.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/7c5d1522-905d-46fa-aefb-14b710360766)

See also:
- [Research hub models](https://docs.google.com/document/d/19WoZxJvisMsHnXqA4GDX3Te6t9JnqAI2NG5jE9J4LP4/edit#)
- [Designs](https://www.figma.com/file/6BXnlCvPcQrtIaxunvuBYc/Mozilla-Research%3A-Inspiration)

# Acceptance criteria

- [ ] The library page does not show more than 10 results per page.
- [ ] A next an previous link are displayed to navigate to the respective page.
- [ ] On the first page the previous link is disabled.
- [ ] On the last page the next link is disabled.
- [ ] The page navigation is implemented with full page refresh (dynamic behavior can be added later/with a separate ticket). 
- [ ] Change the search filter will reset the page selection to 1.
- [ ] Changing the sorting will reset the page selection to 1.

# Dev tasks

- [x] Add page setting (not on the content panel) to define page size. Default 10. 
- [x] Update the factories to create more pages, to be able to test pagination.
- [x] Add test to check different pages of results can be requested via URL parameters. To make the test simpler to set up, it is helpful to set the page size to a lower value (e.g. 3). 
- [x] Add pagination to the results queryset/list in the `get_context` method. This should make the test pass. 
- [x] Add navigation links below the results list. 
- [x] Style the links according to the design.

**Comment by bheasman** [comment]
@beccaklam please could you review this one from a design perspective? Thanks!

**Comment by beccaklam** [comment]
@tbrlpld The designs show a "load more" functionality instead of pagination. Was this chosen instead because it's easier to implement? Sorry, I couldn't find the conversation in the design where this was decided so just wanting to understand how we got here!

**Comment by beccaklam** [comment]
That makes sense to me! Again, let's just make sure Kasia knows that we've made that decisions. This ticket looks good to me ✅

**Comment by tbrlpld** [comment]
This is ready for review and demo @danielfmiranda @nicklee
