### ISSUE TITLE
cleanup source\sass\views\regrets-reporter-landing-page.scss

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#8344]
We can remove the file and replace with tw-classes

Files affected:
* `network-api\networkapi\wagtailpages\templates\wagtailpages\pages\regrets-reporter-landing-page\*.html`

**Comment by danielfmiranda** [comment]
This ticket is taking a little longer than anticipated as I found another bug on the landing page where the share buttons are not rendering correctly. 

Going to trouble shoot this bug and then clean up the SCSS!
