### ISSUE TITLE
Thimble missing from Artifacts page

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/foundation.mozilla.org#8350]
Hi Mozilla friends!

I noticed that the link and content for Thimble has gone away from [https://foundation.mozilla.org/en/artifacts/](https://foundation.mozilla.org/en/artifacts/). I have a few places that link to it as a former Mozilla product (and it's a part of my portfolio as well). Was wondering if it moved somewhere else and if I could get a link to that please?

Thanks!

**Comment by Pomax** [comment]
I hasn't moved it was getting some 10k hits a day and nothing we did made whatever was polling it stop, so we unpublished the page. I'll see if we can put it up on a new slug (without setting up a redirect for it)

**Comment by Pomax** [comment]
I've restored the thimble page on a new URL, the sidebar on the artifacts should point to it.

**Comment by gideonthomas** [comment]
Thank you so much Pomax! Also, hi 👋

**Comment by Pomax** [comment]
howdo howdo 👋
