### ISSUE TITLE
Update logic to keep current entries at top of Upcoming page

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#838]
**Summary:**
In our [Upcoming](https://network.mozilla.org/programs/upcoming/) page, events that belong to our current month (October) are being displayed under "recent" instead of right after the Hero image.

**Additional details:**
I feel that events that don't have a day assigned to it should stay in the main area (after the hero). Like the NSF challenge is still open today (Oct 11th) and by being displayed under "recent" it seems it is not an actionable item anymore.

<img width="968" alt="image" src="https://user-images.githubusercontent.com/22157921/31472873-0c22516a-aea6-11e7-89b8-99eda49d4a0a.png">

**Comment by taisdesouzalessa** [comment]
@xmatthewx - opened this ticket so you can set the priority and we can also track the discussion here.

**Comment by xmatthewx** [comment]
I agree. Ideally, authors set the correct date, but we could be less aggressive to give them some wiggle room, since they might not know an exact date when they add the entry. 

For engineers: let's show current and future months in the top section, past months under recent. Let's ignore the day of the month.

**Comment by taisdesouzalessa** [comment]
@xmatthewx as far as I know, the Upcoming page can't be edited via CMS (I don't see it in the admin view) - is that correct @gvn?

**Comment by gvn** [comment]
They're in the CMS as "milestones", so on staging you can edit them at:

https://foundation.mofostaging.net/admin/milestones/milestone/

**Comment by taisdesouzalessa** [comment]
I have a "403 Forbidden" error on it. Maybe I don't have access to it?

**Comment by gvn** [comment]
That's odd. I just tried to give you permission, can you try again?

**Comment by taisdesouzalessa** [comment]
Working now, Gavin! Tks for your help.

**Comment by gvn** [comment]
No problem!

**Comment by taisdesouzalessa** [comment]
> @taisdesouzalessa - I also recommend that you make sure our documentation makes it clear that the date on entry is important.

@xmatthewx - good point. I added a step by step on adding milestones in the documentation. I will tag you there.

**Comment by taisdesouzalessa** [comment]
Tested on staging. It is working well now. Tks for fixing it, Gavin!
