### ISSUE TITLE
[RH] 7 - Research card component

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#8384]
# Description

Create a "research detail" card component. 

This component is used across the research hub to link to "research detail pages". 

**Desktop**
<img width="691" alt="image" src="https://user-images.githubusercontent.com/24797493/156829267-cb90c139-930f-4670-8dda-92fd3b1f797b.png">

**Mobile**
<img width="334" alt="image" src="https://user-images.githubusercontent.com/24797493/156829875-6bb71359-dcde-48b8-8b30-71aaf950a2f6.png">

[Designs](https://www.figma.com/file/6BXnlCvPcQrtIaxunvuBYc/Mozilla-Research%3A-Inspiration)

# Acceptance criteria

- [ ] Card displays the image, title, publication date, topics and authors of the research detail page. 
- [ ] The card links to the research detail page displayed. 
- [ ] The card does not have any border or background (to make it reusable in different context -- e.g. landing page, listing page, author detail, etc.).
- [ ] A parameter can be passed to the component that defines if the image is displayed in mobile view. (Needed because on the mobile library page there are no images used, but on the mobile landing page there is).

# Dev tasks

- [x] Add image to research detail page
- [x] Decide on a page where to implement the card first (e.g. the library page). 
- [x] Create a rough mobile style for that page so that the detail cards stack vertically without any other elements besides them
- [x] Implement the card for mobile as per design in the pages template (with image)
- [x] Extract the card to a separate template file and include it in the example page
- [x] Allow passing a variable to the card template to not display image (e.g.`hide_image_on_mobile=True`)
- [x] Show date in localized format
- [x] Avoid line wrapping of metadata
- [x] Use the right joiners on the metadata (comma for authors, slash for topics)
- [x] Create a rough page style for desktop. The main goal here would be to have a similar width of the cards as in the design. 
- [x] Debug the overflow bug on desktop. There is some issue with the nested flex rows.
- [x] Try to use [responsive images](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images) to only load the image at the appropriate resolution. 
- [x] Apply additional classes to display the card in the desktop variant. 
- [x] Allow heading level for the card title to be passed in. This is because the results can be `h2` on the library page, but will be `h3` on the other pages (landing, author detail). 
- [x] Use the card on the library, landing and author detail page. 
- [x] Library and landing page mobile only show author names
- [x] Author page mobile show the topic
- [ ] Receive design feedback on image rations and card border on lading page.

**Comment by cdanfon** [comment]
Hey @tbrlpld is this groomed and ready to be picked up? 

@bheasman
