### ISSUE TITLE
[RH] Research detail page - main section styling

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#8387]
# Description

<img width="686" alt="image" src="https://user-images.githubusercontent.com/24797493/156842122-5b9e7c61-bb3a-4b78-ba01-1c738dec5c49.png">

Implement styling of the main section of the "research detail page" 

# Acceptance criteria

- [ ] Editors can select a cover image
- [ ] The header image of the parent library page is used.
- [ ] The visual appearance of the "research detail page" is as close to the [designs](https://www.figma.com/file/6BXnlCvPcQrtIaxunvuBYc/Mozilla-Research%3A-Inspiration) as possible
- [ ] The names of the project leads are links to their respective "author detail" pages. 

# Dev tasks

- [ ] If none exists, create an author card component
- [ ] Split the layout into boxes
- [ ] Come up with a way to order the layout boxes for a mobile screen (because there is currently no design)
- [ ] Organize the template according to the layout boxes
- [ ] Implement the design of the boxes in mobile view
- [ ] Implement the design of the boxes in desktop view

**Comment by tbrlpld** [comment]
@KalobTaulien Is working on this one.

**Comment by cdanfon** [comment]
Kalob working on this issue - almost done

**Comment by cdanfon** [comment]
Kalob working on this issue - almost done
