### ISSUE TITLE
[RH] Author index page - styling

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#8389]
Implement styling of the author index page. 

The designs contain  a letter list that is hard to implement of different locales. We have also discussed using a simple search bar instead. This is still with design, so that feature can be skipped for now. 

We had also discussed to add pagination to this page, but that will be dealt with in a separate step (#8538).

<img width="416" alt="image" src="https://user-images.githubusercontent.com/24797493/162296282-2c2707e0-6897-4743-9a0e-51ecef91d5c6.png">

Note: Breadcrumbs are dealt with in #8498 

# Acceptance criteria

- [x] The visual appearance of the "author index page" matches the [designs](https://www.figma.com/file/6BXnlCvPcQrtIaxunvuBYc/Mozilla-Research%3A-Inspiration) as close as possible. (Note: ignore the letter filtering feature / search bar -- this is not part of MVP)
- [x] For each author: image, name and tagline/job description are displayed. 
- [x] Each author card links to the authors detail page. 
- [x] Editors have to select a header image for the author index.
- [x] Factories are updated to set a header image.
- [ ] Authors are listed alphabetically

# Dev tasks

- [ ] Create a author card component. 
- [ ] For each author profile listed on the index, render the respective author card.

**Comment by cdanfon** [comment]
Kalob will be picking up this ticket
