### ISSUE TITLE
Update copy that refers to Network

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#841]
As we prepare to shift the site URL and framing from Network to Foundation, Taís did a fab review of the content and noted copy we might want to update.  

@Sydette @jessevondoom - we'll leave this in your capable hands to assess references to the network and figure out what needs to be resolved. Nothing seems wildly stop-the-presses critical to me. 

https://public.etherpad-mozilla.org/p/foundation-site-url-updates

**Comment by taisdesouzalessa** [comment]
This issue also relates to this ticket Gavin opened: #892

**Comment by taisdesouzalessa** [comment]
@kristinashu not really...lol! Although the majority of the items are now updated (due to site updates), we still have lots of "Network" in our "Get Involved" page (see the Etherpad for mode details). Not a critical issue but a nice to have!

**Comment by taisdesouzalessa** [comment]
I'll leave up to @kristinashu and @xmatthewx to decide if we should to those changes on copy or not. I can clean up the list with things that are no longer relevant if you decide to proceed with this issue.

**Comment by xmatthewx** [comment]
thanks. This will be addresses with all the new content jesse and sydette are putting together. i don't think we need to fix it as a separate issues.
