### ISSUE TITLE
Change Email address from network@

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#842]
@jessevondoom - the site footer and nav include an email link to network@mofo. We should update that at some point as we shift framing. 

Do you know about our desk.com account? If it isn't already, we might hook this up with that.

**Comment by stephaniemcv** [comment]
Network@ is hooked up to Desk.com. We should chat, @xmatthewx, I'm the admin of that baby now. :-P

**Comment by xmatthewx** [comment]
Yikes. Yes, let's talk. Are other parts of the org actively using Desk? I don't think anyone on our team is triaging those messages.

**Comment by stephaniemcv** [comment]
Fundraising is actively using Desk to triage donation cases.
Email replybacks also land in Desk as more of a feedback collection tool.
Teachtheweb@ checks in every now and then but we should chat about possible decommissioning that and network@. I'll stalk your calendar for a meeting time.

**Comment by xmatthewx** [comment]
Thinking about this again... I think @jessevondoom and @Sydette or Lotta (rather than me) should decide if they want a contact email on the site for the them to monitor on Desk. Could be good for feedback and suggestions regarding content and editorial. Maybe we switch to something like hello@mo...fo...org.

**Comment by Pomax** [comment]
The footer is still `network@...`, is this still something we want to resolve @xmatthewx?

**Comment by anilkanji** [comment]
As per a Slack convo with Matthew, Will, Kevin, Steph and Sydette, we’ve decided to kill it.

**Comment by Pomax** [comment]
Do we want to file a new issue to remove the email option from the footer?

**Comment by anilkanji** [comment]
@xmatthewx ?

**Comment by xmatthewx** [comment]
Sure. Filed here:  
https://github.com/mozilla/foundation.mozilla.org/issues/2596
