### ISSUE TITLE
SEO | Correct hreflang links 

### ISSUE THREAD

**Issue by bheasman** [mozilla/foundation.mozilla.org#8439]
Off the back of the Grassriots site audit, it has been identified that there are a number of issues with incorrect hreflang links.

Detail from Grassriots
The x-default for most pages has a redirect to the /en version of the page. It is very important to make sure your hreflang links always refer to absolute URLs with HTTP 200 status codes, otherwise search engines will not be able to interpret them correctly and, as a result, will not show the correct language version of your pages to the relevant audience.

Link to the [audit](https://docs.google.com/spreadsheets/d/15HwgpxSYc4Zl809kcebAhLfLYXFuIk8ZP-Qvk3yVV8Q/edit?usp=sharing)

**Comment by tbrlpld** [comment]
@bheasman I am not clear on what the solution here is supposed to be. Are they saying we are using relative URLs (like `/en/some-page/`) but should use absolute URLs (like `https://foundation.mozilla.org/en/some-page/`)?

**Comment by bheasman** [comment]
Hi @tbrlpld, good question. My reading of it is that we shouldn't use the language specific version of the URL e.g. /en/ but a generic one (https://foundation.mozilla.org/advocacy/) so that search engines show the relevant language. I'll ask someone with a bit more SEO expertise though and get back to you!
