### ISSUE TITLE
SEO Site Audit remediation

### ISSUE THREAD

**Issue by bheasman** [mozilla/foundation.mozilla.org#8441]
Off the back of the recent Grassriots [SEO audit](https://docs.google.com/spreadsheets/d/15HwgpxSYc4Zl809kcebAhLfLYXFuIk8ZP-Qvk3yVV8Q/edit?usp=sharing), a number of issues have been raised that require resolution.

**Comment by bheasman** [comment]
It'd be good to review whether we still need #7882 off the back of this epic.

**Comment by tbrlpld** [comment]
@bheasman I have created additional tickets in the EPIC based on #7882. So I think we can close #7882

**Comment by cdanfon** [comment]
We're going to tackle this with the help of TBX, closing this ticket as it feels like we need to revisit the Audit in first instance and check what is still applicable
