### ISSUE TITLE
SEO | uncrawlable pages

### ISSUE THREAD

**Issue by bheasman** [mozilla/foundation.mozilla.org#8443]
Off the back of the Grassriots site audit, it has been identified that there are a number of issues with pages that can't be crawled

Detail from Grassriots:
Pages in this set are exclusibley /privacynotincluded pages - and may indicate slow server response times causing the crawler to fail. 

Link to the [audit](https://docs.google.com/spreadsheets/d/15HwgpxSYc4Zl809kcebAhLfLYXFuIk8ZP-Qvk3yVV8Q/edit#gid=627737737)

**Comment by cdanfon** [comment]
A moco colleague has given feedback on the grassriots recommendations (Adria Kyne), her comments are as follow:

> I didn't have any difficulty crawling these. I think this was due to the method they used to crawl the site, and not a site problem.

Which makes this ticket redundant.,

**Comment by cdanfon** [comment]
Hey @tbrlpld can you move this ticket to the 'Needs discussion' pipeline please? Thanks!

**Comment by cdanfon** [comment]
Closing this ticket as it has become redundant after Adria Kyne comments.
