### ISSUE TITLE
SEO | Duplicate title tags

### ISSUE THREAD

**Issue by bheasman** [mozilla/foundation.mozilla.org#8444]
Off the back of the Grassriots site audit, it has been identified that there are a number of issues with pages that have duplicate title tags.

Detail from Grassriots:
Pages in this set have duplicate / generalized title tags - in some case english language / non-translated. Duplicate <title> tags make it difficult for search engines to determine which of a website's pages is relevant for a specific search query, and which one should be prioritized in search results. Pages with duplicate titles have a lower chance of ranking well and are at risk of being banned. Moreover, identical <title> tags confuse users as to which webpage they should follow.

Link to the [audit](https://docs.google.com/spreadsheets/d/15HwgpxSYc4Zl809kcebAhLfLYXFuIk8ZP-Qvk3yVV8Q/edit#gid=627737737)

**Comment by cdanfon** [comment]
Further feedback from Adria Kyne on the grassriot audit: 

> This is a localization issue again--there are pages that have been published on localized URLs that have not yet been translated. That this creates duplicate titles is the least of the problem here--the larger problem is that we are publishing unlocalized pages.

Creating a ticket to tackle the main issue here: **Unlocalized pages being published** with higher priority than this one.

**Comment by cdanfon** [comment]
Hey @kristinashu Can you move this ticket to the 'Needs discussion' pipeline too please? Thanks!

**Comment by cdanfon** [comment]
@kristinashu Apologies, my comment was directed to @tbrlpld!
