### ISSUE TITLE
Design Fellowships Landing Page on the Foundation Site

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#845]
**Background:**
Currently, information about our Fellowship programs can be found across several web properties.
Our vision is to create a shared online home for all of our Fellows programs. This aligns with a programmatic effort to align the Fellowships in terms of timeline, application processes, benefits, etc.

**Audience**
The Fellowships landing page will serve as a one-stop shop for:
• Current and past fellows to showcase their projects
• People interested in applying for a Fellowship (entry point to apply)
• People interested in learning more about the Fellows and their impact (e.g. media, internet activists)

**Full Document here**
https://docs.google.com/a/mozilla.com/document/d/12poQEDuYPIGGHEOoZuwpGjpdGpzi_8EHD0U4vecu6v4/edit?usp=sharing

cc: @flukeout @hannahkane

**Comment by taisdesouzalessa** [comment]
Here is my suggestion of breakdown:
- [ ] 1. Research of current state of individual pages, ask questions in the doc and find benchmarks
- [ ] 2. User journey
- from hearing about Fellowships to being in one cohort
- from belonging to a Fellowship to updating projects and connecting to other Fellowship members
- from learning about the existence of Fellowships to getting educated about it in order to use the info learned (media or internet activists).
- [ ] 3. Wireframes (important: loop in Engineers to help shape the page)
- [ ] 4. Mockups

@hannahkane could you please take a look at this breakdown and see if you think it makes sense to you? Am I missing some step? 

Once we have an agreement on the breakdown, I can turn this issue into an epic and file individual tickets.

**Comment by hannahkane** [comment]
@taisdesouzalessa - this is great. I can't think of a step you're missing. 

cc @xmatthewx in case he wants to propose edits to this breakdown

**Comment by xmatthewx** [comment]
This looks good. I'm curious, how much time would you estimate on each step? A few thoughts below on how we might keep this nice and Lean. 

 1. Hannah – do you think there's strong understanding of the current pages, effectiveness of content, rationale behind prior choices? Or, can we look to them for content/inspiration and jump ahead to step 2. (We have mostly new stakeholders on the fellowships team.)
 2. I would keep this scoped to the page (with an understanding of how people get there). Let's leave things that happen before and after the visit to the fellowship team. Maybe we can collaborate on that with them later, after we've established a unified home.  
 3. Since we have strong UI patterns, wireframes don't seem essential, but maybe useful. 
 4. Yay

**Comment by taisdesouzalessa** [comment]
@xmatthewx and @hannahkane 

in terms of time, these are rough estimates:
1. a day or less
2. a day or less
3. 4-5 days
4. If using the elements we already have: 2-3 days. If we want to do something very different...maybe add 2-3 days to it.

If we need to do this task asap, we can establish the key components and priorities and do a very quick MVP as well, not sure what the needs are in terms of time here...

About item 2: I imagined the user journey not being a lengthy one but more a diagram so we can better connect what's happening online with the offline work. I feel that seeing it on a flow usually help stakeholders to see how the pieces fit together and we end up with a more cohesive experience. Also, it helps me to make better design decisions. It is ok if we don't want this step, I can remove if you feel it adds too much complexity.

About item 3: I think the wireframes are necessary in this case as a tool for building this page together with stakeholders (as they shape the copy) and focus on the flow of information rather than visuals. The turnaround time for a wireframe is pretty quick after revisions, which doesn't happen in a mockup.

**Comment by xmatthewx** [comment]
I think so. Could be helpful for both endeavors. Some fellows will be The Professional. Tech Policy are more System Changer.

**Comment by hannahkane** [comment]
Looks like @taisdesouzalessa has gotten a good start on the benchmarks doc (#855). 

I think very a very simple user journey diagram that illustrates how the site can support offline goals could be useful for syncing up with the programs team, but would be hesitant if it takes more than half a day for a first draft.

The wireframes were requested by the program team, and I think will be useful for helping them craft the right content and copy. We just need to indicate information flow and about how much content is appropriate for a web brochure.

**Comment by taisdesouzalessa** [comment]
This page is launched: https://foundation.mozilla.org/fellowships - closing this ticket
