### ISSUE TITLE
Research Google Analytics 4

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#8453]
We will need to update to [Google Analytics 4](https://blog.google/products/marketingplatform/analytics/prepare-for-future-with-google-analytics-4/) however I have no idea how much or little effort this will be.

- [ ] Get confirmation from from Jackie that it is ok to upgrade (I have pinged Jackie to see if it needs to go through privacy and legal review)
- [ ] Look into how it is done and what the effects are
- [ ] Open tickets to do the work
- [ ] Inform staff that we will be doing this

cc @bheasman in case you have more context!

**Comment by bheasman** [comment]
Thanks Kristina - this looks good. As per the chat with Phil M - our analytics team will be able to support/guide through the process as required!

**Comment by cdanfon** [comment]
This is currently being done by TBX
