### ISSUE TITLE
Build Accordion Block for Foundation Site

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#8474]
# Description

Accordion block to be implemented on the Foundation Site on all Page Types except for Publication.

---

###  Design -> Dev Handoff Checklist

Link to original design ticket: #8246
[Figma File](https://www.figma.com/file/P06Q7hWuILgc9g19AXcP39/Publications-template?node-id=580%3A26090)
[Redpen](https://redpen.io/p/voffc50587b06bc101)
Assets: 
![plus-circle.svg](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/4bbd4588-0346-4b9c-a203-d0c0e2822e78)
![minus-circle.svg](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/ac7ec8bf-8960-4036-a54e-89bd93fface8)

- [ ] Build Accordion Functionality
- [ ] Add Styling
- [ ] The body of the Accordion should include:
-  Bold
-  Italic
-  Link
-  Numbered list
-  Bulleted list
-  Document link
- [ ] Add block to all page types except Publication

# Acceptance criteria

- [x] Accordion block should be available via CMS for all pages besides publications
- [x] Accordion should have rich text field with the above markdown included

# Dev tasks

- [x] Create backend streamfield for accordion block
- [x]  Style block to match mockup provided on figma and redpen
- [x]  Add javascript to enable opening and closing the block
- [x]  Make sure the block is mobile-responsive

**Comment by beccaklam** [comment]
*Question: Is it possible to add streamfield blocks inside an accordion?

**Comment by cdanfon** [comment]
Hey @fessehaye If you complete all the work within sprint ahead of Monday this is a good candidate to be picked up please, thanks! 

@beccaklam @kristinashu fyi
