### ISSUE TITLE
Case Study for Publications and Article Page Type Updates

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#8505]
After we've had a few use cases for the updated Article and Publication page types, it would be good to write a case study showing how the updated features have affected metrics/how staff have used them.

- Reference [Landscape Analysis and Stakeholder Interviews](https://docs.google.com/document/d/1N2N_TJ1pUajytEGDA3mlp00ZyPDrYnn7sfHbcABqJP0/edit?usp=sharing)
- Reference #6411

**Comment by kristinashu** [comment]
Going to close this but let's open a new ticket in https://github.com/MozillaFoundation/Design/issues closer to when this work will begin.
