### ISSUE TITLE
[Interactive Report] Update Publication Landing Page

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#8527]
Update the Publication Landing Page for Continuous Scrolling.

## Design to Dev Handoff Check List
[Redpen](https://redpen.io/p/yo9a8acdd779e7a410)
[Figma File](https://www.figma.com/file/P06Q7hWuILgc9g19AXcP39/Publications-template?node-id=820%3A31337)

- [ ] Update Publication Landing Page to be similar to Sticky Nav Menu (style and accordion functionality, displays H2 headings as well as Article titles)
- [ ] Include functionality to show child Publications, similar to the Sticky Nav Menu
- [ ] Landing Page automatically scrolls to first Article in Publication without a transition, experience should be seamless 

@kristinashu Can I get a R+ for this design?

**Comment by kristinashu** [comment]
R+ looks good!
