### ISSUE TITLE
[Interactive Report] Documenation

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#8536]
Continuing work from #8446

### Update Publications "How to Wagtail" page
~- [ ] Check to see if the video needs updating~ (decided to remove for now)
- [x] Update features list

### Share Examples Pages
- [x] Full screen layout
- [x] Image Left
- [x] Image Right

**Potential reports to feature:** 
- [YouTube Regrets Findings](https://foundation.mozilla.org/en/youtube/findings/)
- [Tinder Campaign](https://foundation.mozilla.org/en/campaigns/personalised-pricing/)
- [Exporting Disinformation: How Foreign Groups Peddle Influence in Kenya through Twitter](https://foundation.mozilla.org/en/campaigns/exporting-disinformation-how-foreign-groups-peddle-influence-in-kenya-through-twitter/)

### Share with Staff
- [ ] Contact Stakeholders previously interviewed
- [ ] Beta test documentation with Ramy

**Comment by beccaklam** [comment]
### Update Publications "How to Wagtail" page
- [ ] Check to see if the video needs updating
- [ ] Update features list

### Share Examples Pages
- [ ] Full screen layout
- [ ] Image Left
- [ ] Image Right

**Potential reports to feature:** 
- [YouTube Regrets Findings](https://foundation.mozilla.org/en/youtube/findings/)
- [Tinder Campaign](https://foundation.mozilla.org/en/campaigns/personalised-pricing/)
- [Exporting Disinformation: How Foreign Groups Peddle Influence in Kenya through Twitter](https://foundation.mozilla.org/en/campaigns/exporting-disinformation-how-foreign-groups-peddle-influence-in-kenya-through-twitter/)

### Share with Staff
- [ ] Contact Stakeholders previously interviewed
- [ ] Beta test documentation with Ramy

**Comment by beccaklam** [comment]
Share this [deck](https://docs.google.com/presentation/d/1FKY3xTCi9LAN-Fg1MBTs3uWl_P-IyiuKia8zBXWHXy4/edit?usp=sharing) with staff on Monday, April 11

**Comment by beccaklam** [comment]
Last week:
- Started creating YouTube Regrets Findings example page
- Created Data Wrapper assets and laid out text 

This Week:
- [ ] Adjust illustrations for Wagtail
- [ ] Create video of subtle animations for the hero header?

Still need to create example pages for Full Screen and Image Right

**Comment by kristinashu** [comment]
Cross-linking this with https://github.com/MozillaFoundation/Design/issues/815

**Comment by beccaklam** [comment]
I've gotten the How To Wagtail page for Publications and Articles to a place where I think it's ready to be published! @kristinashu do you mind giving it a R+?

**Steps:**
1. Go to: https://foundation.mozilla.org/cms/pages/1436/edit/
2. Click preview to see the changes in draft mode (live is still the old page)
3. See page for review!

Thank you in advance!

**Comment by kristinashu** [comment]
Awesome! This feels very informative yet concise! R+

**Comment by beccaklam** [comment]
Great thank you @kristinashu I've added examples of different hero header layouts to the documentation as well, though I'm waiting on a server 500 error to be resolved for the full screen example. Wondering if I can send out what I currently have on Monday for now?

**Comment by beccaklam** [comment]
Sounds good!

**Comment by beccaklam** [comment]
Closing this for now and will create a follow up ticket for sharing documentation with stakeholders!
