### ISSUE TITLE
SEO | Create a sitemap index file

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#8550]
# Description 

Create a sitemap index file, which should be findable at https://foundation.mozilla.org/sitemap.xml. 

This index would link to the sitemaps for all of the languages that the website supports.

# Acceptance criteria

- [x] /sitemap.xml should be accessible on staging/production/and review apps
- [x]  sitemap should include all 10 languages included on foundation site translations

# Dev tasks

- [x] Generate Sitemap using wagtail [sitemap generator](https://docs.wagtail.org/en/stable/reference/contrib/sitemaps.html)

**Comment by cdanfon** [comment]
Hey @tbrlpld me again, can you add the following tags (maintain, engineering) and move the ticket to the backlog please? Thanks!

**Comment by fessehaye** [comment]
After a look at the repo it looks like sitemaps are already included for all languages:

https://foundation.mozilla.org/sitemap.xml
https://foundation.mozilla.org/es/sitemap.xml

**Comment by tbrlpld** [comment]
@fessehaye I believe the intent is that the default non-locale sitemaps only shows the localized sitemaps. The current one seems to list all pages.

**Comment by tbrlpld** [comment]
@cdanfon I might make sense to provide more background here. Why is this change necessary? Where is the requirement coming from?

**Comment by cdanfon** [comment]
Hey @fessehaye & @tbrlpld 

Grassriot provided some recommendations regarding SEO on this [audit](https://docs.google.com/spreadsheets/d/10vx_yWcS5a1GpWOCSvxnvN5efAFa_M5yHdNrts9CuIE/edit#gid=627737737).

A MoCo colleague had a look and challenged some of these. 

As part of her comments she advised we should include a sitemap index  file, which should be findable at [https://foundation.mozilla.org/sitemap.xml](https://www.google.com/url?q=https://foundation.mozilla.org/sitemap.xml&sa=D&source=editors&ust=1651165412759406&usg=AOvVaw2lsfaGdqjVV5treEaZGRdO). This index would link to the sitemaps for all of the languages that the website supports.

@fessehaye I've tagged you in her original comment - please let me know if you need more context. Thanks!
