### ISSUE TITLE
Incorrect sentence in Common Voice Language Rep

### ISSUE THREAD

**Issue by pedroldk** [mozilla/foundation.mozilla.org#8556]
### Describe the bug
Access https://foundation.mozilla.org/en/blog/could-you-be-the-next-common-voice-language-rep/ and the sentence "Increased my awareness of the value of language technologies for the revitalization of Minority Languaglanguageses" is wrong at the end.

### To Reproduce
1. Go to https://foundation.mozilla.org/en/blog/could-you-be-the-next-common-voice-language-rep/

### Expected behavior
"Increased my awareness of the value of language technologies for the revitalization of Minority Languages"

### Screenshots
![image](https://user-images.githubusercontent.com/480413/163191380-98e875a4-2b44-45b6-a133-f2ab9f1ac51e.png)

**Comment by pedroldk** [comment]
Related with https://bugzilla.mozilla.org/show_bug.cgi?id=1764526

**Comment by kristinashu** [comment]
Thank you for flagging! This was fixed a while ago now.
