### ISSUE TITLE
MozFest on Projects page

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#856]
MozFest should be featured prominently on the website over the next month. 

Question for @jessevondoom @Sydette: Should we add MozFest as the top item on the Projects page? 

![image](https://user-images.githubusercontent.com/53411/31619771-7d464692-b263-11e7-8e96-2a69824898ed.png)

**Comment by jessevondoom** [comment]
I like the idea of adding a "Projects seen at MozFest" or similar header for the next month or so. Could be a rad way to hit the IRL aspects of network projects...

**Comment by taisdesouzalessa** [comment]
I love this idea! Let me know if you need any assets/design work for that. 

Also, I was wondering if we could feature more speakers from "Dialogue and Debates" on our homepage (part of MozFest too) and add links to videos of their talks in the People's page. We would need to break the video in small chunks (on Air Mozilla they are full Sat and Sun videos) and publish them either on Air Mozilla or YouTube.

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/22157921/32457874-62484322-c2df-11e7-8b20-1454374ce9fb.png">

I am not sure about how this idea fits with other priorities @xmatthewx and @jessevondoom and if we can use the speakers' videos. If you think it is valuable and possible, let me know and I can create a GitHub ticket and work on that as well.

**Comment by xmatthewx** [comment]
Last year, Kevin and team cleaned up the videos before posting to Facebook. I think it took a couple of weeks. We posted links to each of those talks to Pulse.

@alanmoo - do you think Gavin has the bandwidth to add MozFest as a category on the Projects page? Just like the 5 issues, no different functionality.

**Comment by taisdesouzalessa** [comment]
Cool, tks for the context here Matthew! I'll ask Kevin if they are doing the same thing for this year and if so, to let me know when the cleaned up versions are ready. Then we could add the links to the Foundation site and also Pulse you think?

**Comment by alanmoo** [comment]
You can link directly to the timecode of the speakers on AirMo; Click on the speaker pictures on https://mozillafestival.org to see what I mean.

@xmatthewx Should be fine, though would we just end up seeing 2 Mozfest projects based on whatever was posted recently, before our most recent deploy?

**Comment by xmatthewx** [comment]
The project page section will help communicate that MozFest is a thing, that it's a way we surface and promote exciting activity from our peeps. Even if it isn't dynamic. 

Let's move discussion about speaker series videos to a new ticket if useful.

**Comment by kristinashu** [comment]
New [wireframes](https://docs.google.com/presentation/d/1Hl5Etpl-iTOCoJJ66ilszGLYFS2k-LqTRk7_fCTmySc/edit#slide=id.g2e15d82b60_0_64) should solve for this so I'm closing this ticket but @xmatthewx please reopen if you think we need it.
