### ISSUE TITLE
[Interactive Report] Add Hero Header to Publications

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#8584]
Right now, only Article pages feature the new Hero Header but we've decided to add feature to Publications as well! This is because Publications are usually bigger projects/reports that would require a unique landing page.

**Design files/mockups:**
[Figma File](https://www.figma.com/file/P06Q7hWuILgc9g19AXcP39/Publication-%26-Article-Page-Types?node-id=901%3A32335)
[Redpen](https://redpen.io/p/xwf84f72d83a40bd2b)

### Design to Dev Checklist:
- [ ] Add Hero Header to Publications

### Dev Tasks:
- [x] Add Hero Header fields to publication page
- [x] Make appropriate updates to front end template

@kristinashu Can I get a design review?

**Comment by kristinashu** [comment]
R+ assuming the Secondary subtitle and the Author profile pictures can still be there
