### ISSUE TITLE
Transitions/animation for the website

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#86]
If time allows, it would be nice to add a layer of polishing in the website with transitions and animations. @sabrinang and I had ideas for 4 items, playing with the diagonal shape that is characteristic of the new brand:

- [ ] Animation for hover state in the buttons
- [ ] Animation for click on the menu
- [ ] Animation for People's page (cards that allow users to see more details)
- [ ] Animation for "Join Us" (depends on issue #45 - we didn't think about this animation yet)

I think those are important for a welcoming user experience in the site. They are pieces of delight that definitely make a difference in how the audience perceives the site. 

In terms of strategy and timelines, I am not sure it those would fit in a V1 of the website, so I am looking for some input here.

@xmatthewx @hannahkane @gvn

**Comment by sabrinang** [comment]
Button transition and hover idea that it fills left to right on a diagonal:
<img width="919" alt="screen shot 2017-02-22 at 11 22 51 am" src="https://cloud.githubusercontent.com/assets/2492510/23228450/6534947c-f8f1-11e6-8d16-279c0a768d6c.png">

**Comment by taisdesouzalessa** [comment]
People's page animation (timing will be adjusted - will work with Gavin on that if we choose to implement it.):

![animation-people-v2](https://cloud.githubusercontent.com/assets/22157921/23230324/575ee90e-f8f8-11e6-96ec-86c4990002c1.gif)

**Comment by taisdesouzalessa** [comment]
Closing this ticket since we have a redesigned site now. We can rethink about animations on the new context and open a ticket by then.
