### ISSUE TITLE
[Interactive Report] Server 500 error when trying to publish specific article page

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#8600]
When attempting to publish this article page: https://foundation.mozilla.org/cms/pages/18069/edit/ I keep running into a server 500 error. This doesn't seem like a site-wide problem as other article pages are publishing fine. But it would be good to understand why this is happening so we can preemptively avoid this error.

~Not sure if this has any relation to #8599~

cc: @danielfmiranda

**Comment by beccaklam** [comment]
This isn't a high priority as long as it's not a site wide issue!

**Comment by kristinashu** [comment]
I quickly recreated the page with the same content and it seemed to work fine so I feel like this was just a odd one-off event. @beccaklam would it be ok to close this and just reopen it if it happens again?

**Comment by beccaklam** [comment]
Yes fine to close!
