### ISSUE TITLE
[PNI Editorial Updates] Finish Discovery

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#8631]
Finish [design brief](https://docs.google.com/document/d/1h4B8ca9ASgGeuwBMDkzncAjcaq4xcxKYtD1AD2VU5n4/edit#heading=h.e1hdva6khlbd) started in ticket [#8537](https://docs.google.com/document/d/1h4B8ca9ASgGeuwBMDkzncAjcaq4xcxKYtD1AD2VU5n4/edit?usp=sharing)

- [ ] Sign-off on brief
- [x] User stories
- [x] Roadmap
- [x] Metrics & Analysis

**Comment by kristinashu** [comment]
I think this is considered done!
