### ISSUE TITLE
[PNI Editorial Updates] Content & Content Strategy

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#8632]
Placeholder ticket to start asking Jen for content or example content

**Comment by beccaklam** [comment]
Pinged Jen and she replied with the following details below which I feel like is sufficient information for now:

> Heya Becca, the main types of content i’m imagining we’ll want to feature would be:
>1.  Blog post/articles we’ve written or contracted to write that expand what we learned from our product review research. For example, a blog post that compares the privacy/security of meditation apps head to head, or a deeper dive into where HIPAA laws end and our data economy begins, or a “Tips to protect your privacy when meeting with an online therapist” as examples of what we could features for our current mental health apps launch.
> 2. Advocacy campaign asks.
> 3. News articles written by journalistic or other sources that feature us or news relevant to our current product reviews.
> 4. Promos of things we’re doing: Like ways to announce/promote things like the Reddit AMA on mental health apps we’re doing tomorrow or our D&D coming up later this month.
> 5. An interactive section where people can send us questions/concerns/experiences they’ve had with this tech, etc.

@kristinashu do you think we need anything more specific?

**Comment by kristinashu** [comment]
Nope, this is great to know!
