### ISSUE TITLE
[PNI Editorial Updates] Start Exploration

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#8633]
Ideating, Concepting & Brainstorming

**Comment by kristinashu** [comment]
Work is here https://www.figma.com/file/uiH6Rp09pexbhJ2yKmQ6HT/PNI-Editorial-Updates-Benchmarking?node-id=0%3A1 

Follow up tickets to finish user flow https://github.com/mozilla/foundation.mozilla.org/issues/8845 and start wireframes have been opened
