### ISSUE TITLE
[Interactive Report] Supporting MAIT report

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#8635]
Supporting Ramy in this work of getting the report into our Publication template!

**Important Docs**

- [MAIT report design notes](https://docs.google.com/document/d/1Cq-Wt-coYFbTMEK_G8piqAmS4xkp9d8kB4vOFhoEcD0/edit?usp=sharing)
- [MAIT report draft](https://docs.google.com/document/d/18KyJzLZvIBq0TlHm59NZMbNVEhfprnWrYmreEb-rnbA/edit?usp=sharing)

**Create tickets for**
- [x] Read through [MAIT report draft](https://docs.google.com/document/d/18KyJzLZvIBq0TlHm59NZMbNVEhfprnWrYmreEb-rnbA/edit?usp=sharing) and work with Ramy on how to divide content and integrate Arafath's visuals [#9991]
- [x] Datawrapper graphs [#9989]
- [x] Support for high level landing page/blog post for broader audience (marketing to lead) [#9990]
~- [ ] Design support/review after content has been put into Wagtail~

**Comment by kristinashu** [comment]
@beccaklam is this still happening? I'm going to close this ticket but please open a new one in https://github.com/MozillaFoundation/Design/issues if needed
