### ISSUE TITLE
Blog improvements - Spec out the dev work

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#8646]
Define the dev work that will be involved and add tickets under the epic after the meeting with the design team on 16th of May

*[TIMEBOX 2 hours]*

**Comment by danielfmiranda** [comment]
Epic for this work can be found at https://github.com/mozilla/foundation.mozilla.org/issues/8682, though I would like to spend some more time  "componentizing" different parts of the pages.
