### ISSUE TITLE
[RH] Switch color of checkbox and radio from red to foundation blue

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#8658]
# Description

There was feedback on the color choice for the checkboxes and radio button in [this discussion](https://www.figma.com/file/6BXnlCvPcQrtIaxunvuBYc?node-id=21:275#193076250) in the design. 

This is the current situation:
![image.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/fc6e2631-f6b1-4aba-8bb5-4419d5257543)

We want the color of these to be "foundation blue" (`#595cf3`)

# Acceptance criteria

- [ ] Checkboxes in the library page filter section use the foundation blue as the accent color.
- [ ] Radio buttons in the library page filter section use the foundation blue as the accent color.

# Dev tasks

- [ ] Change checkboxes in the library page filter section to use the foundation blue as the accent color.
- [ ] Change radio buttons in the library page filter section to use the foundation blue as the accent color.

**Comment by nicklee** [comment]
Hi @tbrlpld, I've updated them to the blue-purple, which I have as "#4a17d4", @kristinashu can you confirm you're happy with this? The figma design is now using this colour.

**Comment by kristinashu** [comment]
Please make it our foundation Blue ($blue) #595cf3. Thank you!
