### ISSUE TITLE
[RH] Add standard donate CTA banner to all Research Hub pages

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#8659]
As per @kristinashu's [comment](https://www.figma.com/file/6BXnlCvPcQrtIaxunvuBYc?node-id=1166:2168#193857393) all pages should show the default donate CTA banner. 

I think this is just deactivated in the Research Hub base template. Should be simple to activate. 

This is the default "donate CTA banner":
<img src="https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/3feb0061-aaa3-49eb-94b0-2164f5a7480d" width="300"/>

This banner should be displayed on all research hub pages above the footer.

<img src="https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/3a27c91b-8113-41e9-b2b2-6af0994d9b67" width="300" />

# Acceptance criteria

- [ ] The donate CTA banner is displayed on the research landing page
- [ ] The donate CTA banner is displayed on the research library page
- [ ] The donate CTA banner is displayed on the research detail pages
- [ ] The donate CTA banner is displayed on the research author index page
- [ ] The donate CTA banner is displayed on the research author detail page

# Dev task

- [ ] Add the banner to the research hub base page template.
- [ ] Check that the banner is displayed correctly on all page types.

**Comment by tbrlpld** [comment]
@kristinashu Does the updated description fit your expectation?

**Comment by kristinashu** [comment]
Yes, that is correct. Thank you!
