### ISSUE TITLE
SEO | hreflang conflicts within page source code 

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#8679]
This set of pages have been flagged with having issues with the format of the HREFLANG source code. However, there is not a clear issue to correct for these pages and may be appearing error due to the URL parameters.. The issues is identifed by having one of the following issues: - Conflicting hreflang and rel=canonical URLs, Conflicting hreflang URLs, No self-referencing hreflang URLs

https://docs.google.com/spreadsheets/d/15HwgpxSYc4Zl809kcebAhLfLYXFuIk8ZP-Qvk3yVV8Q/edit#gid=1772715630

**Comment by tbrlpld** [comment]
@cdanfon There is no set of pages reference above. It only says "this set of pages". It's not clear what this is pointing to. Also, it is not clear to me what the issue is and how to fix it.
