### ISSUE TITLE
SEO | incorrect page found in sitemap.xml 

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#8681]
The Same [page identified](https://foundation.mozilla.org/en/blog/why-our-tech-community-is-most-excited-about-mozfest-2022/) with a 5XX code is listed here as well. However, using multiple sitemap validator tools, they were unable to validate the XML sitemap for the domain foundation.mozilla.org - additional attention should be paid to the output for the SITEMAP to ensure it follows the standard with all necessary XML structures.

**Comment by tbrlpld** [comment]
@cdanfon What XML validator was used? Would be good to have more info on this to be able to know what needs to be fixed.

**Comment by tbrlpld** [comment]
Also, it seems like this ticket is about multiple things. Would be good to split this up.
