### ISSUE TITLE
[Blog] - Landing Page - Featured Cutout Box

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#8683]
Design:

<img width="282" alt="image" src="https://user-images.githubusercontent.com/18314510/168687459-c2f8a62a-a86d-4369-b949-1ed8d4acf866.png">

This ticket is to create a template to house this new component that is going to live on the blog landing page.

It should have the following fields in the backend:
- [ ] Related Tag
- [ ] Icon
- [ ] Title
- [ ] Content? (At the moment it looks like rich text, and a audio component. Please check with Design what the user should be able to add in here.)
- [ ] CTA Button Text
- [ ] CTA Button Link URL

Dev Steps:

1. Create new template file for this component. Should probably live under /fragments.
2. Add the fields above to the blog page under the title "featured callout box"
4. Update template to render fields as designed

**Comment by danielfmiranda** [comment]
Hi @nancyt1!

I have a couple of questions I was hoping I could ask before we get started on this work:

1. Should we make the tag at the top selectable by the user?
2. I see we are displaying the audio player, is this always going to be the case? If not, what other blocks/fields should we make available to the user?

Thank you!

**Comment by nancyt1** [comment]
@danielfmiranda 
1. Yes the topic should be selectable and when clicked will take you to that topic's landing page. (We're officially calling the categories topics now lol)
2. I think this callout should be flexible so having the option to change the title, description, topic, and optional button or audio. Is it possible to do a form field here for newsletter signups?

**Comment by kristinashu** [comment]
@nancyt1 to mock up what a non-audio version should look like
