### ISSUE TITLE
[Blog] - [Landing] - Topic Callout Box

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#8688]
### Design:

<img width="392" alt="image" src="https://user-images.githubusercontent.com/1068783/169410017-a53fc11c-0b40-461b-8ad6-c397303d384d.png">

This ticket is to create the new "Related Topics" callout box fragment. Once this is created we can then add it to the "topic landing page" template.

Dev Tasks:
---
Backend:

- [x] Add a new relation to the blog index page, similar to the "FeaturedBlogPages" model in blog_index.py, called something like "featured_topics"
- [x] Make these new featured topics selectable by the user in the CMS. 

Once this is done, we can then move on to the front end:

Frontend:

- [x] Create a new template under fragments directory
- [x] This template should pull all of these "featured_topics" and render a badge that links to their respective "Topic Detail Page"

Acceptance Criteria:
---

- [x] Users can select topics to be displayed in this new component
- [ ] Once selected, they should render as designed in figma.

**Comment by danielfmiranda** [comment]
Hi @nancyt1! I was wondering how we should populate this box? Does this just display all other tags/categories, or do we need to implement a way to mark other tags as "related?"

**Comment by nancyt1** [comment]
@danielfmiranda Can this be manually curated? Like someone can edit or add topics into it in the CMS?

**Comment by danielfmiranda** [comment]
Hi @nancyt1! Yes these can, I will update the ticket to make the featured topics section manually curated :D
