### ISSUE TITLE
[Blog] - Topic Landing Page Styling

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#8689]
Once #8688 is complete, we can then create the "Topic Landing page" and style it.
We can make the following changes to the existing "categories" template to include the following:

This new page includes:

- [ ] Breadcrumbs (#8498)
- [ ] Search Bar (#8720)
- [ ] Title of Topic
- [ ] Description of Topic
- [ ] Grid with Tagged posts, and cutout "related topic" box (#8688)

**Comment by kristinashu** [comment]
Just want to make sure it is clear that these are updates to the already existing "category" (not "topic") pages e.g. https://foundation.mozilla.org/en/blog/category/common-voice/
