### ISSUE TITLE
[Blog] - Author Detail Page Social Media Section

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#8691]
Design:

<img width="766" alt="image" src="https://user-images.githubusercontent.com/1068783/169411262-0b6a7624-81b3-46cc-bf26-00d0057f997d.png">

The goal of this ticket is to update the Profile model that is related to BlogAuthors Model in order to include everything that is now needed on the Author detail page.

Based on the designs, it appears that the page needs the following: 

- [x] Name (Already exists)
- [x] Introduction (Already exists)
- [ ] Facebook Link
- [ ] Twitter Link
- [ ] Email

Once these are done, we can then create a new html file to house the component that renders the breadcrumbs, title, description, image, and the animated "Share buttons". 

Based on the design, the buttons appear to be quite similar to the animated buttons found on the regrets reporter landing page, so we can use those existing templates/js for reference!

**Comment by kristinashu** [comment]
Note @nancyt1  has updated the design slightly. These buttons won't be animated like on regrets reporter, they will always be present. The link icon is to a external url e.g. their portfolio site.
