### ISSUE TITLE
[Blog] - [Search] - Load More Results

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#8775]
<img width="569" alt="image" src="https://user-images.githubusercontent.com/18314510/169924551-13e625ae-ac2a-4335-a8f6-130a78be39a8.png">

After #8772 and #8843 are complete, the search page template will return the first 6 blog posts, filtered by a search query or not.

The goal of this ticket is to add a button at the bottom which reads  "Load more results" and when clicked, appends another 6 entries to the results.

Acceptance Criteria:
---

- [ ] If there are more than 6 entries in the list of results, the "load more" button should render
- [ ] When clicked, it should append 6 more results to the list

**Comment by tbrlpld** [comment]
@danielfmiranda @nancyt1 Is there a reason for the search results page to deviate from the usual page sizes? The basic index page (from which the blog index and the search page inherit their functionality) defines 4, 8, 12 and 24 as options for the page size (with 12 being the default). Would one of those options also be acceptable or do we need to introduce a new size?

**Comment by tbrlpld** [comment]
> @danielfmiranda @nancyt1 Is there a reason for the search results page to deviate from the usual page sizes? The basic index page (from which the blog index and the search page inherit their functionality) defines 4, 8, 12 and 24 as options for the page size (with 12 being the default). Would one of those options also be acceptable or do we need to introduce a new size? 

Confirmed on Slack: the default options work too. 6 was only used in the mock up.
