### ISSUE TITLE
[Blog] - [Landing] - Flexible Call Out Box

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#8783]
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/18314510/169931460-a350589d-73b1-40fa-ad9e-597144f9d91f.png">

This ticket is to create a template to house this new component that is going to live on the blog landing page.

It should have the following fields in the backend:
- [ ] Related Tag
- [ ] Show Icon (Boolean to show headphone icon)
- [ ] Title
- [ ] Content (Rich Text) (optional)
- [ ] Audio Player (optional)
- [ ] CTA Button Text (optional)
- [ ] CTA Button Link URL (optional)

Dev Steps:
---
1. Create new template file for this component. Should probably live under /fragments.
2. Add the fields above to the blog page under the title "featured callout box"
4. Update template to render fields as designed

Acceptance Criteria:
---

- [ ] Blog index page has a new section for the "featured call out box"
- [ ] Users can pick a related tag to display at the top of the box
- [ ] Users can choose whether or not to show headphone icon
- [ ] Users can enter a title
- [ ] Users can add optional rich text for the body
- [ ] Users can choose to add a audio player block to the component
- [ ] Users can choose to add a optional link button at the bottom of the component

**Comment by cdanfon** [comment]
Hey @danielfmiranda Thanks for your work on this issue! Do you mind updating the acceptance criteria if completed, please? That way we know for sure that everything has been achieved :)

Thanks a lot!

**Comment by cdanfon** [comment]
[timebox to 1 hour]
