### ISSUE TITLE
Transition Sentry from hosted to cloud - foundation.mozilla.org

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#8806]
# Description

We want to move the error tracking for the Foundation webstie from the [self-hosted Sentry](https://sentry.prod.mozaws.net) to the [Sentry cloud service](https://sentry.prod.mozaws.net). 

# Acceptance criteria

- [ ] Backend errors are reported to the Sentry cloud version
- [ ] Frontend errors are reported to the Sentry cloud version
- [ ] Errors from production environment are reported to Sentry and labeled with the correct environment
- [ ] Errors from staging environment are reported to Sentry and labeled with the correct environment
- [ ] Releases are tagged in Sentry
- [ ] Error are reported using the latest version of the Sentry SDK for backend errors
- [ ] Error are reported using the latest version of the Sentry SDK for frontend errors
- [ ] All devs on the project can view errors on Sentry
- [ ] Devs are notified about new and frequent errors

# Dev tasks

- [ ] Setup a project on the Sentry cloud service - @jzinner will complete this. 
- [ ] Update the Sentry backend SDK 
- [ ] Update the Sentry frontend SDK 
- [ ] Configure the staging environment to report errors to the cloud hosted Sentry project (this needs to happen after deployment to staging)
- [ ] Test that errors on staging are correctly reported
- [ ] Configure the production environment to report errors to the cloud hosted Sentry project (this needs to happen after deployment to staging)
- [ ] Test that errors on production are correctly reported

# SaaS Sentry upgrade mana page 
[SaaS Sentry team put together this mana page](https://mana.mozilla.org/wiki/pages/viewpage.action?spaceKey=SRE&title=SaaS+Sentry) to guide teams on how to upgrade their Sentry

**Comment by tbrlpld** [comment]
cc @cdanfon

**Comment by jzinner** [comment]
Sentry is now sending to new SaaS Sentry hosts.
