### ISSUE TITLE
[PNI Editorial] Wireframe homepage

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#8847]
- [x] Be generative: quickly create several different high-level wireframe options
- [x] Present to design, Jen, Simon then narrow down the options
- [x] Create more detailed wireframes for the selected direction(s)

**Comment by beccaklam** [comment]
[Wireframes](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=2303%3A126762) have been drafted and a meeting with Jen, Simon, Kristina and Nancy has been set for June 13th!

**Comment by beccaklam** [comment]
We will be proceeding with design 2 from the wire frame selections for the MVP!
