### ISSUE TITLE
[PNI Editorial] Wireframe category page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#8848]
Based on https://github.com/mozilla/foundation.mozilla.org/issues/8847 

- [x] Be generative: quickly create several different high-level wireframe options
- [ ] Share with design, Jen, Simon for feedback
- [x] Create more detailed wireframes for the selected direction(s)

**Comment by beccaklam** [comment]
First draft of wireframes available [here](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=2303%3A126762). Will share at huddle tomorrow for feedback!

**Comment by beccaklam** [comment]
[MVP designs](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=2303%3A126762) have been finished and will be shared with Jen, Simon and other stakeholders next sprint. Post-MVP designs are still underway.
