### ISSUE TITLE
[PNI Editorial] Wireframe blog landing page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#8849]
Based on https://github.com/mozilla/foundation.mozilla.org/issues/8847 

- [ ] Be generative: quickly create several different high-level wireframe options
- [ ] Share with design, Jen, Simon for feedback
- [ ] Create more detailed wireframes for the selected direction(s)

**Comment by nancyt1** [comment]
Landing on 1 [design](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=2448%3A14190) for the mvp and created a few more [options](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=2448%3A13752) for future evolutions
