### ISSUE TITLE
[PNI Editorial] Wireframe product page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#8850]
Based on https://github.com/mozilla/foundation.mozilla.org/issues/8847

- [x] Be generative: quickly create several different high-level wireframe options
- [ ] Share with design, Jen, Simon for feedback
- [x] Create more detailed wireframes for the selected direction(s)

**Comment by beccaklam** [comment]
[Wireframes](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=2303%3A126762) have been drafted and a meeting with Jen, Simon, Kristina and Nancy has been set for June 13th!

**Comment by beccaklam** [comment]
[MVP designs](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=2303%3A126762) have been finished and will be shared next sprint with Jen, Simon and other stakeholders.
