### ISSUE TITLE
[PNI Editorial] Wireframe prototype

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#8853]
- [x] Make a clickable prototype of all the created wireframe pages
- [x] Gather feedback from stakeholders based on clickable wireframe
- [x] Show wireframe prototype to devs in a design to dev hand-off to gather feedback and technical input

**Comment by beccaklam** [comment]
Here is the link to the [Desktop wireframe prototype](https://www.figma.com/proto/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?page-id=2303%3A126762&node-id=2349%3A127179&viewport=2473%2C3405%2C0.2&scaling=scale-down)! Can I get some feedback @kristinashu and @nancyt1 ?
