### ISSUE TITLE
Revision of the typographic system - Foundation Site

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#891]
Now that we've replaced Arvo with Zilla Slab on our Foundation site, we should get together to do an audit of the system we previously had, keeping in mind the unified guidelines proposed by @kristinashu.

One issue I noticed: because the x-height of Zilla Slab is smaller than its predecessor (Arvo) we have almost no contrast between h5 and body copy, for instance, which is not great for scannability.
<img width="864" alt="image" src="https://user-images.githubusercontent.com/22157921/32468878-f6a0e1bc-c304-11e7-8b60-c09c573c22d1.png">

Other things we could pay attention to in this audit:
- Internet or internet?
- Unify title treatment: Title Case vs Sentence case

Here is the style guide link: https://foundation.mofostaging.net/style-guide/

@xmatthewx I will assign this issue to you so you can prioritize it accordingly. Although an initial discussion would be necessary between Kristina and Sabrina and me, I feel after that, only 1 designer could take this task.

**Comment by kristinashu** [comment]
I agree with you @taisdesouzalessa that the h5 needs to be bigger. 

And then I also think these dividers should be using Zilla Highlight:
<img width="420" alt="screen shot 2017-11-08 at 3 35 53 pm" src="https://user-images.githubusercontent.com/1068783/32580550-a88d09fa-c49a-11e7-9d02-26bb70c20eff.png">

**Comment by taisdesouzalessa** [comment]
They use Zilla Slab in the site with a backgorund color block instead of Zilla Highlight. Not sure why...

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/22157921/32580975-d5ca4386-c49c-11e7-8e8d-e22780f86833.png">

**Comment by kristinashu** [comment]
Could be because Zilla Highlight was released later? I'm good with using Zilla Slab with a box but up to Gavin which way he prefers. Main issue is that the font should be some kind of Zilla and not Nunito.

**Comment by kristinashu** [comment]
@taisdesouzalessa I've put together a list of updates. Please let me know if you are good with them.

# Font updates
Screen caps are from [foundation.mozilla.org](https://foundation.mozilla.org/) and comps [here](https://redpen.io/p/rx51f171fd150ae1fc).

## h1
- remove highlight
- make text black
- increase font size from 48px to 56px

<img width="646" alt="screen shot 2017-11-15 at 10 45 45 am" src="https://user-images.githubusercontent.com/1068783/32854101-6536d2dc-c9f2-11e7-9893-fa8ed0f2459c.png">

## h2
- update from Nunito to Zilla (either Slab with block background or Zilla Highlight)

<img width="648" alt="screen shot 2017-11-15 at 10 45 35 am" src="https://user-images.githubusercontent.com/1068783/32854094-5fc01af2-c9f2-11e7-8cf6-d578bda41156.png">

## h5
- increase size from 18px to 20px
- increase font weight from 400 to 600 

<img width="646" alt="screen shot 2017-11-15 at 10 46 31 am" src="https://user-images.githubusercontent.com/1068783/32854111-6d2f656c-c9f2-11e7-8836-c109f71b540a.png">

# Style guide
Will open a separate ticket to clean up and streamline the style guide https://foundation.mofostaging.net/style-guide/

# Copy updates
Will open a separate ticket to tackle "Internet or internet?" and "Unify title treatment: Title Case vs Sentence case" in a separate ticket.

**Comment by taisdesouzalessa** [comment]
@kristinashu those changes are ok to me. Just 4 observations:

**h1**
- decrease line-height from 1.5 to 1.2 (the line height is too big when we remove the background)
- with the changes you suggested above + this change, "h1-home-white" will be exactly the same as "h1-white". So I guess we can remove one style from the style-guide...yay! We will just have to notify Gavin of that when sending the implementation ticket.

**h5**
- you mean increase size from 18px to 20px in mobile view, correct? I ask that because on desktop view it is already 20px. 
- if we do this change, my suggestion would be to also change the ".h2-headings-white" on mobile. From the current 18px to 20px, so the title balances better with the new h5 rules. 
<img width="686" alt="image" src="https://user-images.githubusercontent.com/22157921/32923181-fc507396-caea-11e7-986b-eb6e987835cc.png">

**Comment by kristinashu** [comment]
Thanks @taisdesouzalessa!

I've opened these follow up tickets:
- Font tweaks #913 
- Copy consistency #914
- Clean up font styles #915
