### ISSUE TITLE
Update node container

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#8933]
# Description

When running commands like `inv new-env` or `inv catch-up` the `package-lock.json` file keeps getting updated. 

I believe this might have something to do with the node version that is used in the Dockerfile (which is 14.13.1). 

I see errors like this: 
```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
```

We should probably update the node version that is used in the container. We also need to make sure that running `inv new-env` or `inv catch-up` can be run without changed to the `package-lock.json` file. 

We probably want to make sure that the development node and the live version also match. Production is currently on `19.2.0`. See also: https://devcenter.heroku.com/articles/nodejs-support
We can set this to something else too in the `package.json`. 
Considering the support table, using version `18.x` seems reasonable, LTS supported until 2025. 

# Acceptance criteria

- [ ] As a developer on my local setup, when I run `inv new-env` or `inv catchup` the `package-lock.json` file is not updated but stays the same as before I ran either command.
- [ ] The development container uses the `node` version as we do in production.

**Comment by tbrlpld** [comment]
@cdanfon This issue has just prevented a release to staging and now requires extra work to get `main` to a releasable state. Would be good for us to address this sooner rather than later.

**Comment by tbrlpld** [comment]
Could use some ACs I think

**Comment by cdanfon** [comment]
Are you OK to add some Tibor?

**Comment by tbrlpld** [comment]
I'll add it for the next grooming round

**Comment by tbrlpld** [comment]
Yea, happy to do this as part of grooming.

**Comment by tbrlpld** [comment]
Staging is running `18.13.0`.

**Comment by tbrlpld** [comment]
When creating a new environment with `inv new-env` we also get version `18.13.0`. This should also update to the latest minor and patch version based on the time of the environment generation.
