### ISSUE TITLE
give.thunderbird.net - remove charity marks

### ISSUE THREAD

**Issue by anilkanji** [mozilla/foundation.mozilla.org#8934]
As a Thunderbird staffmember, I want to avoid confusing our financial contributors as to our status as a charity. I'd like to remove the "Charity Navigator" and "Guidestar" logos from our give.thunderbird.net pages.

They currently don't appear on our main give page:
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/46638654/173129902-423c7efe-fed3-4509-84a4-157d2cf01de0.png">

However when I create a campaign page, they appear below the left hand copy:
https://give.thunderbird.net/en-US/2022-june-test/

<img width="836" alt="image" src="https://user-images.githubusercontent.com/46638654/173130218-1425caa3-bf16-40a0-bffc-f114f9a54c07.png">

**Comment by danielfmiranda** [comment]
Closing to create this bug in the Donate stack repo!
