### ISSUE TITLE
Archive Webmaker.org

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#896]
The site for Webmaker likely gets a bunch of legacy traffic. If so, we should update and archive  https://webmaker.org/

 - take a screenshot for documentation, then...
 - remove play store button
 - add notice
 - add "Find More" CTA, link to Pulse and Site
 - make the page static
 - file a ticket to add a page on the site to document the project, research, lessons, etc

**Comment by xmatthewx** [comment]
@taisdesouzalessa - if you have a quiet day, could you help with a quick mockup of this. Low priority. And let's timebox it to just a couple hours.

**Comment by taisdesouzalessa** [comment]
@xmatthewx do you know who has the editable files of this page? No worries if you don't. I could also do the changes straight to the page inspector and screenshot it for reference.

The link "Find More" will connect to a page that isn't built yet, is that correct?

**Comment by xmatthewx** [comment]
It'll be a sketch file created by Ricardo. In Design Assets > _Projects > Webmaker > [Webmaker-App-2015](https://drive.google.com/drive/u/2/folders/0ByIoeeW0a3R_blJYQ01pcnQ1Rjg) I see a file called Webmaker-Landing Page-UI

**Comment by Pomax** [comment]
This work is tracked in a different repo.
