### ISSUE TITLE
PNI Petition Page Comp

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#8985]
- [x] Create Petition page design comp ready for dev hand off

**Comment by beccaklam** [comment]
This has been done here in the [Figma file](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3679%3A48333). Can I get an R+ @nancyt1 @kristinashu

**Comment by kristinashu** [comment]
R+ but note to devs that the newsletter signup is post-MVP

**Comment by nancyt1** [comment]
R+!

**Comment by beccaklam** [comment]
Noted in a comment in the figma file, closing this ticket now :)
