### ISSUE TITLE
2x Image Component isn't showing images side by side

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9007]
How to reproduce:
Example: https://foundation.mozilla.org/en/insights/strengthening-data-ecosystems-for-education-in-india/appendix/
the images are shown on top of each other rather than side by side

**Comment by kristinashu** [comment]
Looking at the [Figma file](https://www.figma.com/file/P06Q7hWuILgc9g19AXcP39/Publication-%26-Article-Page-Types?node-id=0%3A1), this is how it should look:

<img width="913" alt="image" src="https://user-images.githubusercontent.com/1068783/175099929-8c9dcb77-6f0f-48ac-8ebd-72f36ec30eaa.png">

Whereas in Marc's example, the images are stacking:

<img width="982" alt="image" src="https://user-images.githubusercontent.com/1068783/175100077-9d5eb153-c0cc-44f6-aaa5-d06580bb5794.png">
