### ISSUE TITLE
Setup linting for Django templates

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#9034]
I ran across https://github.com/prettier/prettier/issues/5581#issuecomment-1169111071 and as I recall, there was no linting for the django code (yet), so some of the mentioned solutions might actually be good fits for the parts that currently left unlinted.

**Comment by tbrlpld** [comment]
I agree, it would be very valuable to setup linting for Django templates. One option is: https://djlint.com/

If we find the above too much, at the very least we should make sure our templates are indented correctly. That could be achieved with https://github.com/rtts/djhtml
