### ISSUE TITLE
[PNI] Finalize & get feedback and approval on homepage UI

### ISSUE THREAD

**Issue by nancyt1** [mozilla/foundation.mozilla.org#9037]

**Comment by beccaklam** [comment]
@nancyt1 For when you're back, this is where I'm at with the designs:

**Still to do**
- [ ] Finalize small PNI details
* Rounded corners
* Type
* Filters

**Mock up screens for**
- [ ] Expanded search on mobile and desktop
- [ ] Search results
- [ ] Dropdown for filters
- [ ] Tablet View
- [ ] Variations for Flexible PNI call out card
- [ ] See if product images need updates to make more cohesive with the rest design updates

cc: @kristinashu

**Comment by beccaklam** [comment]
Got a large portion of this work done but will wrap things up next sprint in ticket #9125.
