### ISSUE TITLE
Brainstorm names for PNI editorial content sections

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9039]
- [x] Create doc ahead of meeting for people to fill in async (send to larger group, include Anil)
- [x] Schedule brainstorm with Jen, Kristina (optional), Nancy and I
- [x] Pick names and finalize

**Comment by beccaklam** [comment]
Meeting has been set for July 18th and the [async doc is here](https://docs.google.com/document/d/1qw1HBD8qXvR4xYqJHicYrgaBQuCQf8bzSv5e-CCMx4k/edit?usp=sharing)

**Comment by kristinashu** [comment]
I believe this is done https://redpen.io/p/hmdcb0dd795e67119c!
