### ISSUE TITLE
SPIKE [CI/CD] - Work on bring back review apps for PRs

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9057]

**Comment by cdanfon** [comment]
[Timebox to 2 hours]

**Comment by fessehaye** [comment]
Google Doc was made with our collected founding!

It sounds like the two actionable things we can do going forward is:
1. Move this repro with a different organization with the help of cknowles
2. Creating some temp automation so staging gets updated when main gets pushed and relying on that for designers to review PRs.

**Comment by cdanfon** [comment]
Thanks for this @fessehaye, do you mind creating a ticket for action #2 please?
