### ISSUE TITLE
CommandError: No fixture named 'test_data' found.

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#906]
I followed instruction in README but got some errors back after running the command

```bash
(venv) mavisou:~/Development/foundation.mozilla.org/network-api[gh-771*]$ python ./manage.py loaddata network-api/networkapi/fixtures/test_data.json
CommandError: No fixture named 'test_data' found.
```

**Comment by mmmavis** [comment]
@gideonthomas I'm not sure how to fix this one.

**Comment by gideonthomas** [comment]
@mmmavis try: `python ./manage.py loaddata networkapi/fixtures/test_data.json`

**Comment by mmmavis** [comment]
Heh. Just realized I wasn't on the root dir. Closing this ticket now. There's nothing to fix here.
