### ISSUE TITLE
SUPPORT DUTY - Publication/Article pages not scrolling to next chapter

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#9078]
### Describe the bug
This bug is found on pages that use the "scroll to visit next chapter" feature. such as https://foundation.mozilla.org/en/campaigns/trained-for-deception-how-artificial-intelligence-fuels-online-disinformation/introduction/

### To Reproduce
1. Visit the page above
2. Scroll to the bottom of the page until you see "Keep scrolling to see..."
4. Note that this functionality works only sometimes

### Expected behavior
This behavior should work every time

### Desktop (please complete the following information):
This bug seems to only happen on non-chrome browsers.

**Comment by mtdenton** [comment]
Reopening this, there was another instance found of this issue:

https://foundation.mozilla.org/en/campaigns/tiktok-political-ads/recommendations/

**Comment by kristinashu** [comment]
I believe this has been fixed. @mtdenton to confirm.
