### ISSUE TITLE
Update social icons on from black to grey on People page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#908]
Please update the Twitter and LinkedIn icons on https://foundation.mozilla.org/people/ to match the grey used on https://foundation.mozilla.org/

[Update these icons:](https://foundation.mozilla.org/people/)
<img width="567" alt="screen shot 2017-11-15 at 12 25 04 pm" src="https://user-images.githubusercontent.com/1068783/32858359-1b58e1d8-ca00-11e7-8391-a0929185d695.png">

[To look like this:](https://foundation.mozilla.org/)
<img width="273" alt="screen shot 2017-11-15 at 12 24 38 pm" src="https://user-images.githubusercontent.com/1068783/32858358-1b422ef2-ca00-11e7-82ee-6c015bb1d76e.png">

**Comment by gvn** [comment]
Do you know what color value that grey is?

**Comment by kristinashu** [comment]
Looks like it's black with opacity 40% (thank you @taisdesouzalessa for figuring that one out!).

**Comment by kristinashu** [comment]
Perfect!
