### ISSUE TITLE
[PNI] [Devops] - Create Heroku PNI App and PNI branch

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9081]
Like last year, we should create a branch called `pni-2022` and use that as the base for all of TODO items so we do not have to include partial changes on production and staging. We should create a heroku app with the branch so people can test the new PNI additions. We will need to rebase `pni-2022` branch from main once a while so we do not deal with a lot of merge conflicts in the end once the milestone is done. 

** MUST BE DONE FIRST **
Dev Tasks:
* [x] Create `pni-2022` branch
* [x] Create heroku app based on that branch

Acceptance Criteria:
* [x] PNI branch exists
* [x] PNI Heroku App exists and link to preview app available

**Comment by fessehaye** [comment]
heroku app is working now

**Comment by jzinner** [comment]
As of Sept 9 the Heroku app: `foundation-pni-q3-2021` is deleted
