### ISSUE TITLE
[PNI] - Create Campaign Page Type for PNI [Backend]

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9082]
https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=2303%3A126762
This is mostly a copy of existing campaign or bannered campaign page. 

Create PNI Campaign Page Type for Privacynotincluded

CMS fields should include:
* Rich text field and same streamfields as blog
* Title Field

Acceptance Criteria:
* [x] PNI Campaign Page Type added for PNI site
* [x] Campaign Page Type can only be created within PNI content index page
* [x] Campaign pages are listed on the PNI content index page

Dev Tasks:
* [ ] Create backend page type

<img width="670" alt="image" src="https://user-images.githubusercontent.com/2374073/178842702-1b220cc6-a3e8-4723-9879-b335e2556716.png">

<img width="121" alt="image" src="https://user-images.githubusercontent.com/2374073/178845174-08619b30-28c3-4e35-b332-206e8b6662a6.png">

**Comment by cdanfon** [comment]
@kristinashu Can you please have a look at this as per Daniel's questions during the daily huddle ?

**Comment by kristinashu** [comment]
Thank you for tackling this @danielfmiranda! Everything on the page should function and look like a petition on the main site with the exception of the top nav. Ignore the donate CTA and the shapes in the background as those are post MVP. Please ping me if you have any questions, I'm happy to talk through it.

**Comment by tbrlpld** [comment]
@cdanfon This is ready for QA now: https://foundation-pni-2022.herokuapp.com/cms/pages/18831/add_subpage/

Thanks for pushing @fessehaye

**Comment by cdanfon** [comment]
I've tested this by creating https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/articles/campaign-page-1/

All AC's satisfied, but from the testing I've noticed that upon selecting a CTA you're presented with all the different options in various locales (however all of them have the exact same name), this makes using the back end as an editor difficult and is not a nice experience. I'll create a separate ticket about the way in which localize is applied to the Foundation site in general.

**Comment by cdanfon** [comment]
Marking this as completed @tbrlpld
