### ISSUE TITLE
[PNI] - Editorial Content “Index” Page [Backend] 

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9084]
https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=2303%3A126762

Similar to how the blog index page works!

Dev Tasks:
- [ ] Create backend page type
- [ ] Also create a "pni article page" type (#9083) that can only live below the "pni content index page". The details of that page are not important. Only that it can only live below the index. 
- [ ] Show all children content
- [ ] Add factors for new page type

Acceptance Criteria:
* [ ] Editorial Content “Index” Page Type added for PNI site
* [ ] Editorial Content “Index” Page Type can only be created within PNI
* [ ] Editorial Content “Index” Page Type shows all children content

<img width="395" alt="image" src="https://user-images.githubusercontent.com/2374073/178849708-bbbcbcde-8400-4ecc-a635-16cd91160181.png">

**Comment by beccaklam** [comment]
This ticket looks good to go! @nancyt1 can you give it quick look as well and unassign yourself?
