### ISSUE TITLE
[PNI] - New Navigation 

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9087]
[Homepage desktop comp](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3096%3A30793)
[Mobile comp](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3075%3A29691)
[Tablet comp](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3679%3A47858)

Desktop
![Screen Shot 2022-07-27 at 2.36.02 PM.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/0b9aa51b-e01e-4b7d-bef7-6015bb8d2fc6)
Mobile
![Screen Shot 2022-07-27 at 2.36.19 PM.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/725651ac-6eed-4c1f-91de-f476bd984b60)![Screen Shot 2022-07-27 at 2.36.35 PM.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/07c9d077-16cb-4084-97c0-88c0df8c9000)

Dev Tasks:
* [x] [Mobile only] Add Search Product to Navigation 
* [x] Remove old Hero
* [x] Change "About" link text
* [x] Include "Product Reviews" link that loads the home page without the editorial section at the `/reviews` route
* [x] Add "Articles" link to Article Index Page
* [x] Apply new PNI logo
* [x] Include Mobile styling
* [x] Include Desktop styling
* [x] Include [search styling for Mobile and Tablet nav](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3593%3A44399)

Acceptance Criteria:

- [x] New navbar should be present in all PNI pages
- [x] New nav includes all new menu items (Product Reviews and Articles) and old names are updated ("About the guide" changes to "About"
- [x] Mobile/Tablet nav now includes Product Search
- [x] Search icon expands when tapped in Mobile/Tablet nav
- [x] Old logo has been replaced by the new logo
- [x] Search bar for both mobile(on navbar) and desktop (on category list now) should have previous functionality and filter products when typed and cleared
- [x] mobile search bar when enter key is pressed should redirect you the product review with the text filtered if you are not already on the homepage or category pages

**Comment by fessehaye** [comment]
Design hasn't been finalized

separate navigation and mission statement as separate tickets @fessehaye

**Comment by beccaklam** [comment]
See if Simon can separate search from mobile navigation work.

**Comment by cdanfon** [comment]
Hey @fessehaye do you mind tagging me on adding a comment to the ticket when it's ready for QA review please? Thanks!

**Comment by cdanfon** [comment]
Hey @fessehaye I had a look at this ticket, none of the ACs seems to be satisfied apart from the first one. I am looking here, am I on the wrong page? 

https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/

 

- [ ]  New nav includes all new menu items (Product Reviews and Articles) and old names are updated ("About the guide" changes to "About"
- [ ]  Mobile/Tablet nav now includes Product Search
- [ ]  Search icon expands when tapped in Mobile/Tablet nav
- [ ]  Old logo has been replaced by the new logo

See attached what I can see at my end![Screenshot 2022-09-02 at 17.56.34.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/fbe5db4a-6046-4838-bcdf-540d8a5249c7).

**Comment by fessehaye** [comment]
https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/ @cdanfon 

![image](https://user-images.githubusercontent.com/2374073/188698164-a9ae6448-29a0-4254-9fe7-2925cc05e097.png)

**Comment by cdanfon** [comment]
Hey @fessehaye Thanks for this, looking great, the only thing to mention is that when using the search bar on mobile on the homepage the behaviour, even if it's satisfying all the ACs, is odd. See below screen recording: 

```
https://torchbox.zoom.us/rec/share/hUpnIfiDBSvKqz3jER3CVNbt_tH3zbSyJ4rExmKmkXmVl0GKhRMTXjjdpFRM7f6S.Yp6mmJOdzx0z2WMa?startTime=1662555315000
Passcode: vg@i61db
```

I would expect the product-filtered search to appear at the top upon clicking the 'search' or 'enter' button instead of having to scroll down to find my filtered search. 

@nancyt1  @beccaklam  fyi

**Comment by cdanfon** [comment]
@fessehaye 

Sorry, I've just noticed something else while doing QA for a different ticket. 

When the user is on the 'Articles' page (Article index page) the designs show a wavy underline in purple, when navigating to the Articles page on staging this underline is not present. See screenshots: 

**Figma files:** 
![Screenshot 2022-09-08 at 16.06.15.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/1f8a4800-d481-4a46-bc39-1fd3f63bce24)

**Staging site:** 
![Screenshot 2022-09-08 at 16.03.32.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/a2089a52-4454-4eec-a7ff-57274df2adcc)

**Comment by fessehaye** [comment]
![image](https://user-images.githubusercontent.com/2374073/189209934-64f542f9-b6cb-439e-bb83-8b7c5298c2bd.png)

@cdanfon this is working for me and the underline is showing on staging

**Comment by cdanfon** [comment]
Hey @fessehaye 

The underline shows in staging upon hovering the navigation label, however I believe if a user in on the page itself, no matter whether they're hovering the navigation item, the underline should show to indicate the page they're in. 

@beccaklam can you confirm the expected behaviour please?

Thanks both!

**Comment by beccaklam** [comment]
> Hey @fessehaye Thanks for this, looking great, the only thing to mention is that when using the search bar on mobile on the homepage the behaviour, even if it's satisfying all the ACs, is odd. See below screen recording:
> 
> > https://torchbox.zoom.us/rec/share/hUpnIfiDBSvKqz3jER3CVNbt_tH3zbSyJ4rExmKmkXmVl0GKhRMTXjjdpFRM7f6S.Yp6mmJOdzx0z2WMa?startTime=1662555315000
> > Passcode: vg@i61db
> 
> I would expect the product-filtered search to appear at the top upon clicking the 'search' or 'enter' button instead of having to scroll down to find my filtered search.
> 
> @nancyt1 @beccaklam fyi

Hi @fessehaye I agree with @cdanfon. I think we discussed that we would hide the editorial sections for the search results?

**Comment by beccaklam** [comment]
> Hey @fessehaye
> 
> The underline shows in staging upon hovering the navigation label, however I believe if a user in on the page itself, no matter whether they're hovering the navigation item, the underline should show to indicate the page they're in.
> 
> @beccaklam can you confirm the expected behaviour please?
> 
> Thanks both!

@fessehaye @cdanfon Yes this is the expected behavior though I see that it's not clear in the comps on the product review pages and the article pages. On the higher level pages )'Product Reviews', 'Articles', 'About' should all have underlines though. @nancyt1 @kristinashu Do you think we should also have it on product review pages and article pages?

**Comment by kristinashu** [comment]
Agree! Higher level pages in the main nav should show which page a user is on by showing the cute squiggly underline. 

@nancyt1 also agrees but can't comment in the ticket right now :)

**Comment by cdanfon** [comment]
Check on heroku app, @fessehaye please see @kristinashu's comment above: 

All higher level pages (Product Reviews, Articles, About) **and their sub-pages should show which page a user is on by showing the cute squiggly underline**. Like on our main site e.g. https://foundation.mozilla.org/en/blog/why-mozilla-is-scrutinizing-the-privacy-of-pregnancy-apps/

At the moment, when I navigate to a sub-page the squiggly is not present. See as example: https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/articles/in-post-roe-v-wade-era-mozilla-labels-18-of-25-popular-period-and-pregnancy-tracking-tech-with-privacy-not-included-warning/

**Comment by fessehaye** [comment]
Hi! TIbor and I looked into this remaining issue. PNI uses different tags then the main site for navigation highlighting. In order, for the underline to happen we would probably want to do some larger changes that would take significant more some time plus have small risks of effecting non-PNI pages. Since I think this request, is kind of a scope creep. I will create a new ticket for this issue.

@cdanfon since this covers the AC can we close this ticket or move it to blocking?

**Comment by fessehaye** [comment]
Ticket made https://github.com/mozilla/foundation.mozilla.org/issues/9420

**Comment by cdanfon** [comment]
Sounds good tom e @fessehaye
