### ISSUE TITLE
[PNI] - Add Parallax visuals with background Shapes

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9088]
https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3403%3A38681

Used in homepage,editorial and category page

Dev Tasks:
* [x] Add background shapes as SVG on main, category and editorial page
* [x] Work with designers to fine tune parallax effect for scrolling

Acceptance Criteria:

- [x]  As a user, I should be able to see at least 4-6 svg shapes on the background of the main page.
- [x]  As a user, I should be able to see at least 4-6 svg shapes on the background of the category page.
- [x]  As a user, I should be able to see at least 4-6 svg shapes on the background of the editorial page.
- [x]  As a user, I should be notice that the shapes slightly shifts in the background as you are scrolling down or up the page.
- [x]  As a user, I should see that the asterisk shapes are rotating as you scroll up and down the page.
- [x]  As a user, I should not see the background shapes on mobile viewports, tablet is fine.
- [x]  As a user, I should not notice any scroll-jacking issues or interfere with interacting existing PNI pages.

Ideas: 
* https://www.netlify.com/blog/fun-parallax-scrolling-css-for-matterday/#parallax-visuals
* https://loremipsum.io/
* https://locomotivemtl.github.io/locomotive-scroll/
* https://www.flowdough.nl/

**Comment by cdanfon** [comment]
@fessehaye Can you please give us a number of hours to timebox this issue?

**Comment by nancyt1** [comment]
@fessehaye Here's the [link](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=4575%3A58497) to the background shapes in figma

**Comment by cdanfon** [comment]
Hey @kristinashu @nancyt1 this is now on staging and ready for review.

@fessehaye do you mind tagging the reviewer in a comment for visibility? Otherwise it could be missed.Thanks!

**Comment by fessehaye** [comment]
@beccaklam can you review it since Nancy is away. I did review this with her before the PR was pushed for timings of the animations

**Comment by beccaklam** [comment]
This looks good to go! I found one thing: 
![image](https://user-images.githubusercontent.com/20977376/203850671-ec65b613-5da8-4006-9943-f86245df24e9.png)
but @fessehaye said it will be addressed in a separate PR!
