### ISSUE TITLE
[PNI] - Privacy Ding Visual changes

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9089]
https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=2573%3A15226

![image](https://user-images.githubusercontent.com/2374073/178896208-a5c83637-503f-4987-b363-e1e2c32ccc42.png)

Dev Tasks:
* [x] Move ding to subcategory container
* [x] Restyle checkbox

Acceptance Criteria: 
* [x] Old privacy checkbox is removed
* [x] New privacy ding button is working and styled correctly

**Comment by fessehaye** [comment]
Should be ready on the heroku app 
![image](https://user-images.githubusercontent.com/2374073/188737338-c13af678-552d-4f99-8f5d-a884ecabe70d.png)

**Comment by cdanfon** [comment]
Checked on https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/#product-review

Satisfies ACs, moving this to the 'Done' column
