### ISSUE TITLE
[PNI] - Sort By Creepiness Toggle

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9090]
[Desktop Figma link](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3595%3A44806)
[Mobile Figma link](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3595%3A45493)

![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/9cbf3b1d-20bf-41fe-939a-f10131014e24)

Dev Tasks:
* [x] Added Sort By Component to subcategory container
* [x] Add JS to sort by Lowest -> Highest Creepiness & Highest -> Lowest Creepiness & Alphabetical order
* [x] Add JS push state history changes similar to privacy ding checkbox

Acceptance Criteria:

- [x]  Should be able to sort visible products by Creepiness or Alphabetical order on Homepage and Category page
- [x] Each menu item has an emoji
- [x]  Should preserve history state when changing sort without adding to existing URL(Example: Refreshing should remember the existing sort type)

**Comment by fessehaye** [comment]
Need final feedback by design

**Comment by cdanfon** [comment]
Design is being updated.
AC's will need to be updated.

@beccaklam to update the ticket

**Comment by tbrlpld** [comment]
@cdanfon This is ready on the preview app https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/

**Comment by cdanfon** [comment]
Hey @tbrlpld I've checked this against ACs and looks good to me on desktop, however when navigating the page on a mobile version (Inspect tool - iPhone SE) the whole page seems to be off, including the 'Sort by creepiness toggle'.

I'm going to create a new ticket for the issue mentioned above and mark this as passed as the ACs are effectively satisfied.
