### ISSUE TITLE
[PNI] Homepage - Hero feature [backend]

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9091]
[Desktop comp](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3096%3A30793)
[Mobile comp](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3075%3A29691)

![Screen Shot 2022-07-27 at 2.15.50 PM.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/72634120-c204-4f0a-a6f5-bc50047bdf13)
Dev Tasks:
* [ ] Add Template to top of homepage
* [ ] Include Related Reading block

Acceptance Criteria:
* [x] As an editor, I can add a featured hero article to the homepage
* [x] As an editor, I can add supporting articles in the hero section
* [x] As an editor, I can change the heading for the supporting articles in the hero

**Comment by cdanfon** [comment]
As per the slack update I've included this issue in the current sprint @tbrlpld, would you mind giving it an estimate please? Thanks!

@mtdenton 'cc

**Comment by beccaklam** [comment]
This ticket looks fine @nancyt1 though we need to finalize the styling for 'Related Reading block' @tbrlpld

**Comment by beccaklam** [comment]
@beccaklam Update screen cap with correct 'Related Reading' styling

**Comment by tbrlpld** [comment]
@cdanfon This is now ready on the preview app for QA: https://foundation-pni-2022.herokuapp.com/cms/pages/1444/edit/

**Comment by cdanfon** [comment]
Preview doesn't work - is it page specific?

**Comment by tbrlpld** [comment]
@cdanfon Since we won't be releasing any of the PNI issue separately to production but as one big PNI release (by merging the integration branch) I believe we could close these tickets when they pass QA. Or do you think we should not diverge from the just recently set up QA process already, which I think would also be reasonable 😅?

**Comment by cdanfon** [comment]
Mmm, good shout, to be honest I'm finding not being able to close them a bit of a nuisance, I reckon we can create a ticket which is called something along the lines of _PNI push to prod_ so that we don't forget to push to production (one of the reasons why the process was put in place)

**Comment by tbrlpld** [comment]
@cdanfon I have created #9287 for the release
