### ISSUE TITLE
[PNI] - Advice / Ask Jen Section for Homepage - [Frontend]

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9092]
[Figma component](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3096%3A30793)

![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/f9863297-d3db-49ca-8e91-7d15365ebb88)

Dev Tasks:
* [ ] `Submit it Here` [Link](https://mozillafoundation.typeform.com/ask-jen) <-- this will be a typeform link
* [ ] `Read Full Answer` Link leads to Advice article
* [ ] Truncate Answer to 3 lines using tailwind clamp
* [ ] Mobile Styling - Stack Vertically instead of Horizontally 
* [ ] [Tablet](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3679%3A47858) Styling - Q+A will be stacked vertically like mobile but the layout will be side by side like desktop (the result is similar to a two column grid)
* [ ] Should be separated as a Wagtail component

Acceptance Criteria:
* [x] As a user I can see Ask Jen Section on the  Homepage
* [x] Ask Jen Section is styled correctly
* [x] Content is being pulled correctly 
* [x] As a user if I click on 'Read full answer' I get redirected to the full article page on the same tab 
* [ ] As a user if I click on 'Submit it here' on the right-hand side, I get redirected to the type form on a new tab

If done before Blog backend is done, links can be added later

**Comment by kristinashu** [comment]
MVP is to add an external link to the form https://mozillafoundation.typeform.com/ask-jen

However Typeform does allow for some different embed options which could be cool. Perhaps this is something we could explore in the future?
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/1068783/180864544-4ac4bb30-d74a-4616-8002-d9c994a893d0.png">

**Comment by cdanfon** [comment]
@fessehaye To add dev tasks to this ticket by Thursday the 11th

**Comment by cdanfon** [comment]
Hey @fessehaye further to our chat in sprint planning can you split this ticket into FE & BE please? Thanks!

**Comment by fessehaye** [comment]
Ready for testing!

**Comment by cdanfon** [comment]
Hey @fessehaye this looks great, the only ACs that's missing is:

- [ ] As a user, if I click on 'Submit it here' on the right-hand side, I get redirected to the type form on a new tab

Can we add the target=”_blank” attribute please? Thanks!

**Comment by cdanfon** [comment]
Tested on staging and happy with it! 
@fessehaye

**Comment by cdanfon** [comment]
Tested on staging and happy with it! 
@fessehaye
