### ISSUE TITLE
[PNI] - More Category Dropdown and Category Visual Changes

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9093]
https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=4136%3A57133
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/c328147a-2130-4d16-ad23-266dd9e16d52)
**Active State**
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/e4230ca9-e2b4-4aae-89a1-adf4ea7bd25d)
**Selecting State**
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/d661618a-2c51-4db6-9d2c-e8fe760f1b9a)
**Selected State**
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/43e42bb0-0031-4fb4-bbf6-47df07ef6108)

~Still Need Active State before estimating.~

Dev Tasks:
- [x] More Category Dropdown
- [x] Truncate categories down based on available space (including 'More' drop down button)
- [x] New Active/Hover States for visible Categories
- [x] Change `All` to `All Product Reviews`
- [x]  Mobile Categories do not change, use old dropdown
- [x] Add `Product Reviews` Heading instead of updated title with selected Category

Acceptance Criteria:
* [x] Should be able to access the remaining categories that are not visible via dropdown
* [x] Hovering over the Category links should have wavy underline on category links
* [x] Hovering over the dropdown links should have wavy underline on category links
* [x] When category in dropdown is selected, text on dropdown should be updated and have wavy underline
* [ ] Category Header on home page should have the text "All Product Reviews"

**Comment by cdanfon** [comment]
Design to be updated @beccaklam to include new design in ticket

**Comment by beccaklam** [comment]
Design has been updated.

**Comment by beccaklam** [comment]
Added the number of categories we should feature in the product reviews nav

**Comment by cdanfon** [comment]
To double check ACs against new design updates

**Comment by tbrlpld** [comment]
@fessehaye Can you add some more context on what the AC " Category header has correct text" means? I am not sure how to understand this.

**Comment by fessehaye** [comment]
@cdanfon this is ready on homepage

**Comment by tbrlpld** [comment]
https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/

**Comment by cdanfon** [comment]
Hey, tested on homepage, all looks good except for:

 _
- [ ] Category Header on home page should have the text "All Product Reviews"
_

If I click on a particular category and I open the link in a new tab the Category header updates to the category I've selected: 

<img width="1363" alt="Screenshot 2022-10-21 at 12 16 06" src="https://user-images.githubusercontent.com/102978346/197184050-8ee16a09-5a7f-4930-8545-105ca03a5aca.png">

From here even if I select 'All Reviews' (**not** opening the link on a new page) the header title doesn't change. 

<img width="1363" alt="Screenshot 2022-10-21 at 12 16 06" src="https://user-images.githubusercontent.com/102978346/197184506-64255261-244a-4983-958a-6f5c494c1393.png">


Also worth mentioning that all the other content on that page disappears (nothing neither above the reviews, see comparison below).

<img width="1363" alt="Screenshot 2022-10-21 at 12 16 06" src="https://user-images.githubusercontent.com/102978346/197184419-8bda338c-f151-46ba-8267-73ede88a6b42.png">
<img width="1363" alt="Screenshot 2022-10-21 at 12 20 30" src="https://user-images.githubusercontent.com/102978346/197184423-53394ce7-8aa6-4bb7-a3cb-a52e36661994.png">

**Comment by tbrlpld** [comment]
@cdanfon This was by design that when you open in a new tab (or share the link to the filtered list) you don't see the editorial content. You should also see that the URL expresses that filtering.

**Comment by cdanfon** [comment]
Hey @kristinashu based on @tbrlpld comment are you happy with this ticket to be completed?

**Comment by beccaklam** [comment]
@fessehaye this look good from a design perspective. I'm not sure if this is the time and place to do this but since we are amending the design, would now be the time to remove the wavy line and [reverse the change where "Product Reviews" replaced the selected category title](https://github.com/mozilla/foundation.mozilla.org/issues/9536)? Just not sure if it makes sense to merge changes we will then remove.

I'm also happy to go with the direction merging this ticket and then we will use the follow up tickets we've already created to implement the changes I've mentioned above. cc: @cdanfon @kristinashu

**Comment by tbrlpld** [comment]
Not sure what @fessehaye thinks about this, but I think there is a lot of code in here that will remain the same and it would be better to deal with the changes in a separate ticket.

**Comment by beccaklam** [comment]
I'm fine with that!

**Comment by fessehaye** [comment]
Since there are created issues for the remaining changes I will be closing this ticket
