### ISSUE TITLE
[PNI] - Product Page Aside Content (CTA & Related Articles)

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9094]
https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=2573%3A15226

![image](https://user-images.githubusercontent.com/2374073/189735296-d6c61e6a-97ef-49ed-8c0c-4b8c2150a233.png)

[Tablet link](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3753%3A52397)

**Tablet placement**
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/f62dfe77-700f-42d8-bad4-5e661d509e35)

![image](https://user-images.githubusercontent.com/2374073/178903645-8009c192-100a-4f64-ae37-570bb99a2961.png)

Dev Tasks:
* [ ] Add CTA Component to layout
* [ ] Add Related  Component to layout
* [ ]  Main Content Col 1-10 Aside Content 11-12
* [ ]  Aside Content will overflow from the 12-Col Grid
* [x] Still need medium/tablet mockup for aside content

**ACs**

- [x] As a user navigating a product page, I can see the CTA styled and in the same position as per Figma design
- [x] As a user navigating a product page I can see the related articles section styled and in the same position as per Figma design
- [x] As a user navigating a product page I can see both elements mentioned above (CTA & Related articles) styled properly for mobile and tablet following Figma design

**Comment by cdanfon** [comment]
@fessehaye to add AC's to description of the ticket

**Comment by cdanfon** [comment]
Design to be updated by @beccaklam

**Comment by beccaklam** [comment]
Design has been udpated

**Comment by tbrlpld** [comment]
This is blocked by #9188

**Comment by tbrlpld** [comment]
@kevinhowbrook @fessehaye This ticket is ready for review now 🙏

**Comment by tbrlpld** [comment]
@cdanfon This is ready for QA on the preview app: https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/threema/

cc @kristinashu

**Comment by cdanfon** [comment]
@tbrlpld Hey tibor, I've checked on desktop, mobile and tablet. Although looks fine on desktop it doesn't on tablet or mobile, see attached: 

![iPad air.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/df23819b-49e8-4e04-af38-f702ae40a014)
![iPhone SE.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/ec1a6979-776f-4dc4-b8a3-dfc9c3cdf782)
![ipad mini.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/a0c30f4d-9424-4cc9-878b-4162b85e385c)

**Comment by cdanfon** [comment]
Moving this back to 'In progress' and reassigning it to @tbrlpld

**Comment by tbrlpld** [comment]
Thanks for finding this @cdanfon. This has the same cause as the issue in #9169 I have found... I guess there must have been a bad merge or something that I did not see this locally (also, I did need to use Chrome to reproduce locally, so that was also a factor). 

This should be addressed in #9419

**Comment by tbrlpld** [comment]
@cdanfon The QA issues should now be fixed (too)

**Comment by cdanfon** [comment]
Thanks @tbrlpld !
