### ISSUE TITLE
[PNI] - Product Page Editorial Content

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9097]
https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3083%3A30133

![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/c8e88813-fd0d-4487-b337-854788bfcc7b)

Dev Tasks:
* [ ] Add Dive Deeper Component to layout
* [ ] What to read next Component to layout
* [ ]  Full Width Newsletter
* [ ]  Related Product Style changes

Acceptance Criteria: 
* [x] Editorial Content is visible on the bottom of any specific product page
* [x] Editorial content is styled correctly and has correct grid layout
* [x] Editorial content is styled correctly on mobile

**Comment by cdanfon** [comment]
@beccaklam to update design
@fessehaye update description

**Comment by beccaklam** [comment]
Design has been updated.

**Comment by tbrlpld** [comment]
@fessehaye I am not sure how to understand this AC "Editorial Content is visible on the bottom of any specific product page"

**Comment by tbrlpld** [comment]
@cdanfon This is ready for QA on the preview app: https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/threema/

**Comment by cdanfon** [comment]
Looks good to me @tbrlpld Closing this, thanks!
