### ISSUE TITLE
[PNI] - "In the Press" Component [Frontend]

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9098]
[Figma Component Link
](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3240%3A32961)

![image](https://user-images.githubusercontent.com/2374073/181871499-121b0f39-3899-4c12-8bc6-cf3d2f9cc76e.png)

In the Press Component will only be used for PNI Homepage with similar styling to dive deeper

Dev Tasks: 
* [x] Create Wagtail template for "In the press"
* [x] Allows max 3 "in the press" articles that leads to 

Acceptance Criteria:
* [x] Component is viewable on the PNI Homepage
* [x] "All Press" - leads to content index page with press filter or to editorial index page if 9107 is not done yet

Note: links won't work as expected in ACs until #9107 is completed

**Comment by cdanfon** [comment]
@beccaklam to update design, @fessehaye to follow up by updating Dev tasks & ACs

**Comment by fessehaye** [comment]
![image](https://user-images.githubusercontent.com/2374073/188737516-663ddc31-0062-4a55-8414-cb330054808d.png)

Ready to test

**Comment by cdanfon** [comment]
Thanks @fessehaye 

Tested and all looks good, the only caveat is that All Press" - leads to to editorial index page as 9107 is not done yet

Can we create a new ticket from the back of this to prevent this falling through the gaps please?

Moving to 'Ready for production' 

Thanks!
