### ISSUE TITLE
[PNI] - Newsletter component in product grid

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9099]
<img width="868" alt="Screen Shot 2022-08-09 at 9 39 21 AM" src="https://user-images.githubusercontent.com/74557207/183677738-8fdc6b2d-dd6d-49f8-ab7f-0a4e9ea875b8.png">

[Figma: Component States](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3231%3A33672)
[Figma: Design in Context](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3096%3A30793)

Dev Tasks: 
* [ ] Add newsletter block after 10 Products (2x width)
* [ ] Switch from using Flexbox -> CSS Grid

Acceptance Criteria:
* [ ] Newsletter is visible in product review grid

**Comment by cdanfon** [comment]
@beccaklam to update the design

**Comment by cdanfon** [comment]
@fessehaye to update description

**Comment by tbrlpld** [comment]
@cdanfon This is ready for testing on the preview app: https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/

**Comment by cdanfon** [comment]
Thanks @tbrlpld looks good to me
