### ISSUE TITLE
Update thumbnail images to 16:9

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#910]
Note: people profile images will remain square.

### Images on these pages should be updated:
- [Homepage Feature](https://foundation.mozilla.org/)
- [Get Involved](https://foundation.mozilla.org/get-involved/)
- [Upcoming](https://foundation.mozilla.org/programs/upcoming/) 

Once this is done, we might need to add more spacing between posts. [Here's the comp](https://redpen.io/p/rx51f171fd150ae1fc)

@taisdesouzalessa do you know how images are sized. Should I do them in Photoshop then upload via CMS or are the cropped automatically in the CMS?

**Comment by taisdesouzalessa** [comment]
Love the idea of keeping them all 16:9. 
If I am not mistaken, the images are limited by the system in the width (which means they occupy a certain % of the layout, depending on the number of columns) but the height scales automatically with the width variation (so images aren't distorted). As far as I know, the CMS doesn't crop the images. @gvn may be able to confirm that or correct me if I am wrong.

**Comment by gvn** [comment]
That's correct: there's no cropping done by the CMS. It's best to manually crop images to make sure they look good. Automating cropping tends not to work very well...

**Comment by kristinashu** [comment]
Ok thanks! Manual it is.
