### ISSUE TITLE
[PNI] - Editorial Content “Index” Page - Popular Article Section

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9105]
[Figma File: Final Designs](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3471%3A41810)
[Figma: Component States](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3240%3A32961)

Dev Tasks:
- [ ] Add Popular Articles Component to  Editorial Content “Index” Page as aside content

Acceptance Criteria:
* [ ] As an editor I can add popular articles 
* [ ] Popular Articles are viewable from Editorial Content “Index” Page Type
* [ ] Popular Articles are styled correctly

![Article Index Page - All](https://user-images.githubusercontent.com/74557207/183678102-9db26cc3-de61-4a45-9878-6f2a07e96b1c.jpg)

**Comment by tbrlpld** [comment]
@fessehaye This probably needs backend work too

**Comment by cdanfon** [comment]
Hey @tbrlpld Am I meant to be seeing the 'Popular articles' block underneath the CTA? 

In the preview app that section is empty, but I can see it on the Figma design. Attached both 

![PreviewApp](https://user-images.githubusercontent.com/102978346/196390794-bcc64b5d-52fb-46fe-b1e3-b02315b3abeb.png)


<img width="1080" alt="Figma" src="https://user-images.githubusercontent.com/102978346/196390780-512ca91e-7f71-4da8-8458-a59f53370ea1.png">

**Comment by cdanfon** [comment]
Re-checked it, looks good to me! @tbrlpld
