### ISSUE TITLE
[PNI] - Editorial Content “Index” Page - Newsletter Signup CTA

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9106]
https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3471%3A41810

Dev Tasks:
- [ ] Add Newsletter Signup CTA Component to  Editorial Content “Index” Page as aside content
- [ ] Add Newsletter Signup CTA Component to  Editorial Content “Index” Page above footer (full width)

Acceptance Criteria:
* [x] Newsletter Signup CTA are viewable from Editorial Content “Index” Page Type

Note: Newsletter only appears when "All" is selected.

![Article Index Page - All](https://user-images.githubusercontent.com/74557207/183943406-9955bd54-e784-4768-ac0c-d0bafae0a0aa.jpg)

**Comment by anilkanji** [comment]
Is it possible to have this signup associate to a specific campaign for segmenting purposes? We are currently able to do this with the campaign signup pages but not newsletter pages.

**Comment by kristinashu** [comment]
>Is it possible to have this signup associate to a specific campaign for segmenting purposes? We are currently able to do this with the campaign signup pages but not newsletter pages.

MVP is to use the current signup and we will plan and scope out the above request separately.

**Comment by mtdenton** [comment]
@cdanfon @fessehaye Possible candidate for this sprint for Simon, seems like it needs grooming? The second dev task is possibly already done, but it looks out of place though with the other footer CTA currently on staging, see image:

![fellowshipswidthbreak](https://user-images.githubusercontent.com/41487159/195173939-985bd958-2001-4dd4-8e96-4e7b56418e05.JPG)

**Comment by cdanfon** [comment]
Hey @fessehaye I'm assuming you're OK picking this ticket - do you mind adding an estimate please? Thanks!

**Comment by tbrlpld** [comment]
This needs clarification. Is this ticket about the Newsletter signup (the blue box) or about the CTA (the thing with the heart)?

The CTA is positioned correctly as part of #9105

**Comment by cdanfon** [comment]
@fessehaye I think you created the ticket, do you mind looking at @tbrlpld comment above please? Thanks!

**Comment by fessehaye** [comment]
@tbrlpld is correct, I just finished checking this PR and it does include a fix for this issue on staging. The PR is approved for those related issues so I will move them to internal review column

**Comment by tbrlpld** [comment]
This is ready on the preview app: https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/articles/

**Comment by cdanfon** [comment]
Checked on desktop and mobile, LGTM. 

Something worth mentioning: the preview app is missing the taxonomies section so I cannot test that the newsletter only appears when 'All' is selected but I'm assuming this is being covered in a different ticket? @tbrlpld @fessehaye 

<img width="189" alt="Screenshot 2022-10-14 at 11 01 53" src="https://user-images.githubusercontent.com/102978346/195820709-28088d0c-db1f-44d5-9f0e-7f96d80efc7d.png">
