### ISSUE TITLE
[PNI] - Editorial Content “Index” Page - Sort By Functionality

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9108]
https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=2303%3A126762

Dev Tasks:
- [ ] Add Sort By dropdown
- [ ] Sort by Newest and Alphabetical

Acceptance Criteria:
* [ ] Content on Editorial Content should be able to be sorted by Newest and Alphabetical
* [ ] Sort Dropdown should be styled correctly

<img width="395" alt="image" src="https://user-images.githubusercontent.com/2374073/178849708-bbbcbcde-8400-4ecc-a635-16cd91160181.png">

**Comment by tbrlpld** [comment]
Closing this for now then
