### ISSUE TITLE
[PNI] - Editorial Content “Index” Page [Frontend] 

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9109]
[Desktop comp](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3471%3A41810)
[Mobile comp](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3471%3A41500)
[Tablet comp](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3679%3A46178)

![image](https://user-images.githubusercontent.com/2374073/181865048-7a8fea49-2e73-4e9b-8729-142b71f376e4.png)

Editorial Content “Index” Page

Dev Tasks:
- [x] Create Grid Layout for Editorial Content “Index” Page 
- [x] Style article cards
- [x] include newsletter CTA block
- [ ] ~~include popular article blocks~~ (Ticket for this template pending)
- [ ] ~~nclude callout CTA~~ (Ticket for this template pending)
- [x] inlcude [mobile](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3471%3A41500) and [tablet](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3679%3A46178) styling

Acceptance Criteria:
* [ ] Editorial Content “Index” Page is styled properly
* [x] Editorial Content “Index” Page has mobile and tablet responsive styling
* [ ] ~~Newsletter CTA only appears on default page (All Articles)~~ (Ticket for this different page types pending)

**Comment by fessehaye** [comment]
Popular Articles are not as high priority as the rest!

**Comment by tbrlpld** [comment]
@beccaklam This is not in our sprint. So start with the next sprint (Aug 2) should be fine.

**Comment by cdanfon** [comment]
Hey @danielfmiranda I can see that this ticket has been in Internal review for 8 days, can I get an update on it please? Thanks!

**Comment by cdanfon** [comment]
He @danielfmiranda I had a look at this on staging. A couple of things:

- The background on the Figma file has some shapes that don't appear on the page - see attachment #1.

- The images appear to be stretched - see attachment #2.

- The title on the Figma file reads as 'All Articles', the title on staging read as 'Articles'

- Underneath the title we have some filtering options that are not present on the staging site - see attachment #3

Any questions let me know!

![attachment_1.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/a98e5b02-7919-4a02-84fe-8ca61c4a863d)
![attachment_2.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/f5a7994f-058b-4e24-8fe5-86276903ee9f)
![attachment_3.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/6e27b72e-4d17-4c7a-86d5-f447169e17a7)

**Comment by fessehaye** [comment]
Filters and background pattern are not apart of this ticket. Patterns are a p3 ticket and are probably last on the to-do list

**Comment by danielfmiranda** [comment]
Have created #9338 to solve the image issue!

**Comment by cdanfon** [comment]
Hey @fessehaye @danielfmiranda thanks for explaining. 

The Acceptance Criteria in this ticket created confusion as it was asking to check whether **_Editorial Content “Index” Page is styled properly_** 

Looking at the Figma files the ticket doesn't match the styling.

Now that you've explained makes sense, but let's try to write ACs as good as we can :)

**Comment by cdanfon** [comment]
Moving this ticket to "Closed" taking into account that the image issue will be fixed via #9338
