### ISSUE TITLE
[PNI] - Editorial Content “Index” Page - See More Results

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9110]
https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3471%3A41810

Dev Tasks:
- [ ] Create Load More Button on bottom of Editorial Content “Index” Page
- [ ] Create backend endpoint to retrieve additional articles 

Acceptance Criteria:
* [x] Editorial Content “Index” Page should only show first 10 articles
* [x] Editorial Content “Index” Page Type should be able to view all articles content by clicking more Load more button

![Article Index Page - All](https://user-images.githubusercontent.com/74557207/183677216-1858764d-5872-48b1-9fdb-8f1b5b67c8f4.jpg)

**Comment by cdanfon** [comment]
@nancyt1 Hey Nancy, could you confirm the number of articles to be shown on the index page please?

**Comment by nancyt1** [comment]
The mockup shows 10 articles but 8 is also good (since I think a page type has already been made with that amount)

**Comment by tbrlpld** [comment]
@cdanfon This is ready on the preview app: https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/articles/

If you want to also test the non-JS pagination, you need to deactivate JS in your browser. I use this browser extension: https://github.com/meetDeveloper/JavaScript-Switcher

**Comment by cdanfon** [comment]
Tested on the preview app - looks good to me. Closing this as passed @tbrlpld
