### ISSUE TITLE
[PNI] Create a BuyersGuideContentCategory snippet

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#9111]
# Description

Simple snippet to categorize the different kinds of articles. 

Fields:
* `title`: CharField
* `slug`: SlugField

# Acceptance criteria

 - [x] As a Wagtail editor, I can create content category snippets in Wagtail. 
 - [ ] As a translator, I can translate the content category title.
 - [ ] As a Wagtail editor, I can not create two categories with the same slug and in the same locale. (Bug #8918 preventing this)
 - [ ] As a Wagtail editor, I can create two categories with the same slug and different locale. (Bug #8918 preventing this)

**Comment by tbrlpld** [comment]
Since this is a PNI ticket, it won't go to staging. We can to QA once the PNI review app is ready.

**Comment by tbrlpld** [comment]
Note: A bug in Wagtail unfortunately prevents the option from constraining the slug uniqueness only per locale. See also: wagtail/wagtail#8918. Because of this issue, translators will have to manually set a unique slug if the translated title matches any other language.

**Comment by cdanfon** [comment]
tried to translate numerous snippets at once - it didn't translate
when trying to translate 1 snippet - 500 error
