### ISSUE TITLE
[PNI Editorial Updates] User Testing Part 1: Write Test

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9126]
### Description
Conduct a quick user test on usertesting.com to gain a sense of the following questions:
1. Can users discover editorial content easily? How do the editorial content updates affect how someone moves through our site?
2. Can users still discover product reviews easily?
3. Does the 'Sort by Creepiness' filter help with understanding the ordering of product reviews/creep-o-meter?

- [WIP Doc ](https://docs.google.com/document/d/1YcvLH8mEQlnwPLIw_yFUkrBpFEAerOGC38vcuCyR5yQ/edit?usp=sharing)

**Acceptance Criteria:**
- [x] Script is written to test the effectiveness of our Editorial and other miscellaneous updates 
- [x] [Prototype](https://www.figma.com/proto/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?page-id=3403%3A38681&node-id=3096%3A30793&viewport=5484%2C571%2C0.13&scaling=scale-down&starting-point-node-id=3096%3A30793&show-proto-sidebar=1) is updated to ensure flows are ready for user testing

**Relevant Links**
- [Jonny's research plan from last year](https://docs.google.com/document/d/13q9RqwMvGwJC4pYU1QZjlp-4DWEwyHqVZlidptiqUOo/edit?usp=sharing) (2021)
- [Jen's old 2021 User Research brief](https://docs.google.com/document/d/1E2I3Trxvtku8v8Q2vdEo7FOgaW8KYKnL5aCf5CC86f0/edit)
- [Draft of questions based on Jonny's Aug 2021 questions](https://docs.google.com/document/d/1ZIReqDcv84dCLv0pz4VCDAXMiWplh8KrhbXZP32YaqU/edit?usp=sharing)

**Comment by beccaklam** [comment]
I've began editing Jonny's old script to adapt it for this round of testing. The first iteration can be found in this [doc](https://docs.google.com/document/d/1ZIReqDcv84dCLv0pz4VCDAXMiWplh8KrhbXZP32YaqU/edit?usp=sharing). I've tagged @kristinashu for first round revisions!

**Comment by kristinashu** [comment]
The questions sound great! Small styling thing, could you please copy this over to a Mozilla branded doc?

**Comment by beccaklam** [comment]
@kristinashu Yup, the doc can be found [here](https://docs.google.com/document/d/1YcvLH8mEQlnwPLIw_yFUkrBpFEAerOGC38vcuCyR5yQ/edit?usp=sharing) and I've added the link in this ticket's description

**Comment by beccaklam** [comment]
I've gone over the [questions](https://docs.google.com/document/d/1YcvLH8mEQlnwPLIw_yFUkrBpFEAerOGC38vcuCyR5yQ/edit?usp=sharing) and [prototype](https://www.figma.com/proto/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?page-id=3403%3A38681&node-id=3096%3A30793&viewport=5484%2C571%2C0.13&scaling=scale-down&starting-point-node-id=3096%3A30793&show-proto-sidebar=1) and I think they're ready to go. Do you mind giving both a look over before I launch the test next sprint @kristinashu ?

**Comment by kristinashu** [comment]
The questions are great but I think the prototype needs a bit more work. A few things to consider:
- Having the designs within the laptop frame makes the text small and hard to read. It also makes it harder to navigate the site. Can the designs just be in the browser window? 
- By default the prototype shows all the flow options on the left hand side of the screen which might be confusing. Can the chosen prototype be isolated?
- The content should be a little more realistic and more things should be clickable. For the smartwatch question: I would like to either click on Wearables, on an editorial article about smartwatches, on a smatchwatch thumbnail, or use the search bar - none of these options seem clickable right now which might be frustrating to testers.

**Comment by beccaklam** [comment]
@kristinashu Okay I've tried to incorporate all the changes suggested above! This actually ended up taking the rest of my day, just noting that for future reference for estimating how long prototyping takes. Do you mind taking another look at the prototype to see if it's ready to go? The only thing I didn't do is take the screen out of the laptop frame because otherwise there is no "in browser" option and all other options show the entire page at once.

**Comment by kristinashu** [comment]
Thanks for noting the updated time estimation!

Looks like the prototype has "headphones" clickable but the script has "smartwatch" so maybe just update the script :)

I like the addition of the headphone articles on the category page but I think it should also be included on the homepage - hypothesis is that people who are looking for headphones in general (rather than a specific pair) might find an article giving an overview more helpful than clicking on the super detailed product page for several products.

I also think the homepage should include at least one headphone thumbnail people I could see some people being drawn to the photo.

By "in browser" in meant people will be seeing it in their browser (not a browser within Figma). I think it's good to show the full screen since that is how people will see in once it's live.

**Comment by beccaklam** [comment]
@kristinashu Thanks so much for the review! I've made the updates to incorporate more headphone images and updated the script. Also I think I finally figured out something for [an in browser view](https://www.figma.com/proto/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?page-id=3403%3A38681&node-id=3096%3A30793&viewport=19638%2C1513%2C0.5&scaling=scale-down-width&starting-point-node-id=3096%3A30793&hide-ui=1)! Does that look good?

**Comment by beccaklam** [comment]
Will circle back to this work next week, closing this ticket for now!

**Comment by kristinashu** [comment]
The in browser looks good! The links are also all good!
