### ISSUE TITLE
[PNI Editorial Updates] User Testing Part Two: Run and Review user tests

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9127]
### Description:
After test has been written, create the test in UserTesting.com and run the tests. After testing has been completed, the videos will need to be reviewed and notes taken on findings and possible changes for the report in ticket #9128

**Tasks:**
- [x] Create test in UserTesting.com
- [x] Run tests
- [x] Watch videos
- [ ] Take notes on findings and possible changes

**Comment by kristinashu** [comment]
Becca ran the test but people didn't understand the Figma prototype. Now the staging site https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/ is getting pretty close, perhaps we can test with that instead.

**Comment by beccaklam** [comment]
Closing this ticket, we will run new tests using the staging site.
