### ISSUE TITLE
[PNI Editorial Updates] User Testing Part Three: Recommendations based on tests

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9128]
### Description
After the UserTesting.com videos have been reviewed in ticket #9458 a report needs to be written with a summary of findings and recommendations for next steps

Tasks
- [x] Review findings in [google spreadsheet](https://docs.google.com/spreadsheets/d/1UCwj8xF8rs_3mOaNn51F8SnHGLV6duo5H9LYXx2iWh8/edit?usp=sharing)
- [x] Write summary report
- [x] Write recommendations

**Comment by beccaklam** [comment]
The first draft of this report has been written [here](https://docs.google.com/document/d/1mvxqtpAqvWchSlwfLBznD73ivNV18NP9exHU9thki7s/edit#). I may go back and gather some quotes.

**Comment by kristinashu** [comment]
Love how clear and concise the report is! Gathering some quotes sounds good. I've left some comments in the doc.

**Comment by beccaklam** [comment]
The [second draft ](https://docs.google.com/document/d/1C6_6p10iys-3O5VLG_gu5GaKGBvJWI-D_1Nx52YMTiU/edit?usp=sharing), complete with quotes and more context about limited editorial content testing, is now ready for review! @kristinashu

**Comment by kristinashu** [comment]
+R

**Comment by kristinashu** [comment]
This is done! @beccaklam when you can, please close this ticket and open a new one for the follow up "quick test" you ran. Thank you!
