### ISSUE TITLE
[PNI] Homepage route for "all reviews"

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#9143]
# Description

The hompage will show both, editorial content and reviews. The old homepage only showed review (because there was no editorial content). 
We there will be links to show only reviews (e.g. "Product reviews" in the main nav and "All" in the category nav). 
The means we want a specific route to be able to link to "homepage" variant that shows only the reviews. 
E.g. use the `reviews/` route for this.

**Comment by tbrlpld** [comment]
@fessehaye I am not sure how we are doing the routing going from the homepage to the "all reviews" page. This might also need some changes on the frontend (similar to whatever we do when going to the category page).

**Comment by cdanfon** [comment]
This ticket is related to #9087

**Comment by tbrlpld** [comment]
As I am working on this now, it seems like this ticket might not be necessary. The homepage and the category pages use different templates. The category page template would just not show the editorial content while the home page does. 

Clicking any of the links in the category nav on the home page only filters the already displayed list. 

When visiting a category page directly, the editorial content is not displayed. Clicking the "all" entry shows items from all categories (the editorial content will still not be shown). 

Clicking the PNI logo in the nav will navigate to the homepage. Here the editorial content is shown as before. 

I think this is how the navigation is supposed to work.
