### ISSUE TITLE
Remove Airtable integration

### ISSUE THREAD

**Issue by jzinner** [mozilla/foundation.mozilla.org#9147]
## Actions

This Issue is the code cleanup of the AIRTABLE integration. 

Which will be reversing this PR: https://github.com/mozilla/foundation.mozilla.org/pull/6046/files 

##  Background 

Since caltrider, the Product Manager, provided confirmation that PNI is not using the AIRTABLE integration on July 18, 2021.  See comments in [Investigate what to do with our wagtail_airtable integration for PNI #7730](https://github.com/mozilla/foundation.mozilla.org/issues/7730)

During a discussion, Anil indicated PNI was the only team interested in the AIRTABLE integration.  

On July 21, 2021 - I removed all 4 of the AIRTABLE config vars from our Heroku apps - see JIRA, MOFOET-20 for more info.

## Acceptance criteria

- [ ] All code relating to Airtable is removed from the code base.
- [ ] The removal is performed in a [backward compatible manner](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/workflow.md#remove-a-field-or-a-model).

**Comment by Pomax** [comment]
Also ping on @KalobTaulien because this removes the need for the airtable package, and if Moz was the only one using it, it might not be worth the maintenance cost of keeping it (implicitly) maintained.
