### ISSUE TITLE
Updating the 'form_submission' data layer change to only fire after ticking the privacy box in the newsletter signup form

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9149]
### Describe the bug
After doing some testing on the 'form_submission' data layer change - [#8956 ](https://github.com/mozilla/foundation.mozilla.org/issues/8956)
the GTM event will fire twice if the user first clicks sign up without ticking the checkbox (I'm okay with Mozilla handling my info as explained in this Privacy Notice), i.e it fires before the form is successfully submitted. This applies to each placement of the sign up form, eg header, footer, and the callout box.

I've attached two screenshots that show the tag firing before the form has been submitted (error message visible in red), and then again once the error is corrected and the form is successfully submitted. 

**Can we fix this so that the box must be ticked before an event is fired?**

### Screenshots 
![Screenshot 2022-07-20 at 11 07 02 (1)](https://user-images.githubusercontent.com/102978346/181248892-8b799b2c-a99f-4e83-b2dd-5f2f71d71596.png)

![Screenshot 2022-07-20 at 11 07 19](https://user-images.githubusercontent.com/102978346/181249030-696fc4b4-0d40-495c-9d6a-b68c47c32c64.png)

### Acceptance criteria
- [x] The privacy box must be ticked before firing the form_submission event in [foundation.mozilla.org](https://foundation.mozilla.org/)
- [x] The privacy box must be ticked before firing the form_submission event in [www.mozillafestival.org](https://www.mozillafestival.org/)
- [ ] The privacy box must be ticked before firing the form_submission event in [/mozillapulse.org](https://mozillapulse.org/)

**Comment by danielfmiranda** [comment]
Hi @cdanfon! Wanted to give you a heads up that the ask: 

- [ ] The privacy box must be ticked before firing the form_submission event in [/mozillapulse.org](https://mozillapulse.org/)

Is not quite needed, as it appears that we still need to add data layer to the pulse site: https://github.com/mozilla/network-pulse/issues/1656

However, I will be sure to only fire the dataLayer event once the checkbox has been selected when I implement that ticket. I have added it to my support duty ticket as well!

**Comment by cdanfon** [comment]
Thanks @danielfmiranda ! Noted :)

**Comment by danielfmiranda** [comment]
Closed with #9210 #9211
