### ISSUE TITLE
Capture form location when signup bar is on the right for www.mozillafestival.org

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9150]
### Describe the bug
After doing some testing on the 'form_submission' data layer change - [#8956 ](https://github.com/mozilla/foundation.mozilla.org/issues/8956)
we are not getting the form location when the signup block is on the right sidebar on Mozilla festival (screenshot below where form_location is 'null').

### Screenshots 

![Screenshot 2022-07-20 at 11.13.50.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/e0aee3ff-4bb4-460a-b31a-2bba4d79f898)

### Acceptance criteria
- [ ] Form location is captured under Tag Details in 'Event Parameters' on GA4 when the signup bar is on the right in https://www.mozillafestival.org/en/

**Comment by danielfmiranda** [comment]
Hi @cdanfon! I have the work needed for this ticket almost complete, however I was wondering what  the string for the "form_location" parameter should be set to? Thanks!

**Comment by cdanfon** [comment]
Hey @danielfmiranda Thanks for checking, can you use the parameter: `newsletter_signup_sidebar` please? Thanks!

**Comment by danielfmiranda** [comment]
Closed with #9210
