### ISSUE TITLE
[PNI] - Related / "What to read next" component - [backend]

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9151]
[Link to Figma Components](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3240%3A32961)

![image](https://user-images.githubusercontent.com/2374073/181867666-3d8e92d2-4876-492b-9dec-b1e96ee494ca.png)

![image](https://user-images.githubusercontent.com/2374073/181867683-c6a63f69-dafa-4eb8-bc7e-642477934541.png)

Related blocks/what to read next block will be included on:
* ~~Article Pages~~ Already implemented in #9083
* Product Pages
* Category Pages
* Editorial Content Index Page

Related Content block and what to read next block will both be using PNI articles for data

Dev Tasks:

- [x] Add CMS field for product specific pages to add related PNI articles, limit 5
- [x] Add CMS field for category pages to add related PNI articles, limit 6
- [x] Add CMS field for Editorial Content Index page to add related PNI articles, limit 3
- [x] ~~Add CMS field for article pages to add related PNI articles, limit 6~~ Already implemented in #9083
- [x] Update wagtail factories to included new CMS changes
- [x] Update wagtail test to check for articles

Acceptance criteria:
- [x] Should be able to add up to 5 articles via CMS for related content on product related pages
- [x] ~~Should be able to add up to 6 articles via CMS for related content on article pages~~ Already implemented in #9083
- [x] Should be able to add up to 6 articles via CMS for related content on Category pages
- [x] Should be able to add up to 3 articles via CMS for related content on Editorial Content Index page

**Comment by cdanfon** [comment]
Hey @danielfmiranda I can see that you've updated the title of #9240. Am I right to believe you'll cover the 'Related articles' section you mentioned above via #9240? Thanks

**Comment by tbrlpld** [comment]
@danielfmiranda @cdanfon I am confused about the status of this ticket. The PR is not reviewed but the acceptance criteria are ticket off. What needs to be done here?

**Comment by tbrlpld** [comment]
@cdanfon This is ready for QA on the preview app now. 

Editorial content index:  https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/articles/
Product category page: https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/categories/pets/
Product page: https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/petsafe-smart-feed/

**Comment by cdanfon** [comment]
Thanks for adding the links to the pages @tbrlpld , this is really helpful ♡

Tested and all looks good to me, moving to 'Ready for production' pipeline.

**Comment by tbrlpld** [comment]
@cdanfon You can close the ticket if QA passed since we release PNI in one go (otherwise the tickets will just sit in the "ready for production" column until then and cluttering it up and doing other releases you  always have to comb through what was actually released).

**Comment by cdanfon** [comment]
True we agreed on the following (see below) I'll mark move them to the 'Done' column 

_

> Mmm, good shout, to be honest I'm finding not being able to close them a bit of a nuisance, I reckon we can create a ticket which is called something along the lines of PNI push to prod so that we don't forget to push to production (one of the reasons why the process was put in place)

_
