### ISSUE TITLE
[PNI] - Mission Statement Section

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9156]
[Homepage comp](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3096%3A30793)

![image](https://user-images.githubusercontent.com/20977376/181381532-05c83126-ae3d-4a7b-9a80-38881cabd1e7.png)

Dev Tasks:

- [x]  Remove old hero banner
- [x]  Update Mission Statement
- [x]  Move Creepy face component to top
- [x]  Apply gradient on speech bubble

Acceptance Criteria:

- [x]  Old hero banner + mission statement to be removed
- [x]  Creepy Face is moved to the top of the new homepage instead of directly nearby product search
- [x]  Creepy Face is updated with the new mission statement text as default
- [x] Preserve previous Creepy Face functionality for the product review section

**Comment by beccaklam** [comment]
[Homepage comp](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3096%3A30793)

![image](https://user-images.githubusercontent.com/20977376/181381532-05c83126-ae3d-4a7b-9a80-38881cabd1e7.png)

**Comment by fessehaye** [comment]
![image](https://user-images.githubusercontent.com/2374073/188737388-f6109b57-9dac-4d39-86e3-1a35c94d0e86.png)

ready to test

**Comment by cdanfon** [comment]
Tested and looking good! 

Moving this to the 'Done' pipeline.
