### ISSUE TITLE
[PNI] - Newsletter CTA stylings

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9168]
[Desktop comp](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3406%3A38682)

Use existing newsletter CTA react component as a base! Does not require back end additions!

Dev Tasks:

- [x] Style Newsletter CTA block
- [x] SVG asterisk background
- [x] Gradient background
- [x] Rounded corners

Acceptance Criteria:
* [x] PNI Article Page Styled Correctly

![image](https://user-images.githubusercontent.com/2374073/181864801-8dc5f04f-2f56-4690-b6c3-24eea32e84a6.png)

**Comment by cdanfon** [comment]
Hi @fessehaye Thanks for adding this to the PNI milestone. Does this ticket have any dependencies? For example, does it makes sense to complete this one before other tickets in the PNI milestone or is it blocking anything?

@tbrlpld for reference

**Comment by cdanfon** [comment]
Hey @fessehaye Does this ACs refer to the ability to add a CTA to an PNI article page as a Wagtail user?

Sorry I'm a bit confused about what I need to do to be able to test is working!

**Comment by fessehaye** [comment]
https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/articles/this-is-a-test/

**Comment by cdanfon** [comment]
All good @fessehaye, thanks for adding the test link
