### ISSUE TITLE
[PNI] - What to read next component - [Frontend]

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9169]
[Link to Figma Components](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3240%3A32961)

![image](https://user-images.githubusercontent.com/2374073/181871237-6a9353b5-07b6-4d27-aeaf-3e44a6d986bd.png)

## Mobile:

![image](https://user-images.githubusercontent.com/2374073/181875104-1df372bd-d59c-4a87-a913-68829f946831.png)

What to read next blocks will be included on:
* Article Pages
* Product Pages
* Category Pages

What to read next block will both be using PNI articles for data

Dev Tasks: 
* [ ] Add wagtail template for What to read next block
* [ ] add `All Articles` link on top
* [ ] Uses 2 or 3 articles limit

Acceptance Criteria:
- [ ] Design to look as per Figma files
- [x] As an editor creating article, product or category pages I can see the read next blocks on each of them
- [x] "What to read next" have CTA links to content index page
- [x] All "What to read next" blocks have long squiggles
- [x] Include mobile specific stylings

**Comment by tbrlpld** [comment]
URLs for QA:

* Category page: https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/categories/mental-health-apps/
* Product page: https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/threema/
* Article page: https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/articles/calm-vs-headspace-which-is-best-for-your-privacy-security/

**Comment by tbrlpld** [comment]
@cdanfon Ready for QA on the preview app now. See the relevant URLs above 👆

**Comment by cdanfon** [comment]
@tbrlpld Thanks for including the links, they are really helpful :)

A few things I've noticed: 

1. On mobile view (using inspect tools), randomly one image in each page seems to be broken. See attachments 1, 2 and 3. 
![1.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/b5a8c1cc-33e4-4411-9707-bf802e0b23d7)
![2.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/631a9509-bcce-4ac1-a2a9-53342d98ebc7)
![3.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/94a00f8d-cff7-48f0-acb2-54b1e136c827)

2. On the article page, the image in the middle is not cropped to fit the space as per the other ones. See attachment 4. 

![4.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/469dade7-f78b-4f7a-898d-e094a13e1e01)

**Comment by tbrlpld** [comment]
@cdanfon 

1. Nice catch. Yea, looks like the mobile version uses the hero image, while the large version uses the meta image. Turns out that some articles don't have the hero set, but do have a meta image. This is the situation where they are missing on mobile. I will update the small version to also use the meta image. 

2. This is definitely an oversight. The images are requested in their original dimension instead of being cropped. I will fix this.

**Comment by tbrlpld** [comment]
There appears to be another issue on the product pages now... Weird I have not caught this before:

![image.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/45a845a6-7c47-46a7-a7eb-f410a0045c61)

**Comment by tbrlpld** [comment]
@cdanfon The QA issues should now be fixed

**Comment by cdanfon** [comment]
Thanks @tbrlpld looking good!
