### ISSUE TITLE
News media icons - convert from SVG to PNG

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#918]
**Description:**
For security reasons, Mezzanine doesn't allow SVGs to work properly in the media library, which has been a problem when we upload new media icons in our [News page](https://foundation.mozilla.org/news/)

**Solution:**
Use PNG instead of SVG and transform old SVGs into PNGs.

**Comment by taisdesouzalessa** [comment]
@alanmoo does this have to be done manually? If so, I think it will be a design task. If somehow there is a way to automate that, let me know.

Another question: does this scenario also applies to other SVGs in the site? Such as the examples below? From the design perspective they look better in svg so we don't have to worry about screen resolution. However it is understandable if we need to change them due to security.
<img width="419" alt="image" src="https://user-images.githubusercontent.com/22157921/32971578-b157700c-cba2-11e7-81cc-4af790f57231.png">
<img width="467" alt="image" src="https://user-images.githubusercontent.com/22157921/32971606-c9609d40-cba2-11e7-9e66-265a88c783e4.png">

**Comment by alanmoo** [comment]
Other SVGs are fine, only the ones uploaded through the Mezzanine interface need to be in PNG format. As such, I'm not sure there's much to do with this ticket?

**Comment by taisdesouzalessa** [comment]
Cool, thanks for the context here. The news page has SVGs (you have to scroll for a bit) and are uploaded through Mezzanine:
https://foundation.mozilla.org/news/

Should we update them to png?

**Comment by gvn** [comment]
I think if they're already in there they don't need to be converted. This probably just applies to future CMS managed images.
