### ISSUE TITLE
[PNI] Translate article page with related articles

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#9194]
# Describe the bug

When trying to translate a page of the new PNI article page type (#9083) which has related articles defined, the admin crashes. 

```
Traceback (most recent call last):
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/wagtail/admin/urls/__init__.py", line 125, in wrapper
    return view_func(request, *args, **kwargs)
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/wagtail/admin/auth.py", line 174, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/wagtail/admin/views/pages/edit.py", line 304, in dispatch
    response = self.run_hook('before_edit_page', self.request, self.page)
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/wagtail/admin/views/generic/hooks.py", line 16, in run_hook
    result = fn(*args, **kwargs)
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/wagtail_localize/wagtail_hooks.py", line 259, in before_edit_page
    return edit_translation.edit_translation(request, translation, page)
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/wagtail_localize/views/edit_translation.py", line 657, in edit_translation
    location_info = get_segment_location_info(
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/wagtail_localize/views/edit_translation.py", line 451, in get_segment_location_info
    "widget": widget_from_field(child_field) if widget else None,
  File "/app/dockerpythonvenv/lib/python3.9/site-packages/wagtail_localize/views/edit_translation.py", line 306, in widget_from_field
    for model in edit_handler.target_models()

Exception Type: AttributeError at /cms/pages/268/edit/
Exception Value: 'NoneType' object has no attribute 'target_models'
```

# To Reproduce

1. Run locally. 
2. Set `RANDOM_SEED=530910203` in your `.env` file
2. Create a new test database: `inv new-db`
2. Go to `http://localhost:8000/cms/pages/260/`
4. Try to translate one of the article pages 
7. See error 

# Expected behavior

Be able to translate the article page with Wagtail Localize. 

**Note:** This only happens when the orderable relation (through model) is to another page. If it is to a snippet it works fine.

**Comment by cdanfon** [comment]
Hey @tbrlpld can you add an estimate to this ticket please? danke!

**Comment by tbrlpld** [comment]
I have created a corresponding issue on the Wagtail Localize repo. Need to wait for feedback.

https://github.com/wagtail/wagtail-localize/issues/640

**Comment by tbrlpld** [comment]
On the blog we are using syncronized fields. @TheoChevalier Is this a pattern that we could repeat here to get around the issue? Is that even the more desirable modeling of the content relations? I guess we would need to make sure that we use the localized versions of the related pages when creating links.

**Comment by TheoChevalier** [comment]
> On the blog we are using syncronized fields. @TheoChevalier Is this a pattern that we could repeat here to get around the issue? Is that even the more desirable modeling of the content relations? 

Yup, we should use synchronized fields here, we don’t want to force translating all related articles

> I guess we would need to make sure that we use the localized versions of the related pages when creating links.

Yes, correct.

**Comment by tbrlpld** [comment]
Thanks @TheoChevalier for this clarification. Would you say that pattern would apply to all relations? In case of the article page this would be related authors and related categories: https://github.com/mozilla/foundation.mozilla.org/blob/pni-2022/network-api/networkapi/wagtailpages/pagemodels/buyersguide/article_page.py#L114-L185

For some reason I was under the assumption that the through models / orderables should be translated.

**Comment by TheoChevalier** [comment]
> Would you say that pattern would apply to all relations?

No, this should be a case by case decision. but here Categories and Authors should be translatable, yes.
To understand the thinking being it, I consider these are _almost_ UI elements, are generally short and reused in multiple places.

**Comment by tbrlpld** [comment]
@TheoChevalier Sorry, I am not sure I understand what you mean.

**Comment by tbrlpld** [comment]
@TheoChevalier @cdanfon This is ready for QA on the preview app now. Example article page with related articles: https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/articles/mental-health-apps-for-teens-what-sorts-of-privacy-protections-are-there/

You should be able to translate the page. The related articles won't show up for translation as they are synced. When you visit the page with a non-default locale then the links to the related articles should use that same non-default locale.

**Comment by TheoChevalier** [comment]
Hi @tbrlpld , thanks! Do you know where I can find the review app credentials? I could only find the ones from last year’s app on 1password.

Thanks!

**Comment by cdanfon** [comment]
Hey @TheoChevalier I'll slack you the credentials now

**Comment by TheoChevalier** [comment]
Thanks, I’m in!

**Comment by TheoChevalier** [comment]
> So if it's short and used in many places you want to translate it. If it's longer or single use you don't. Do I understand that correct?

Yup, that’s it. Also just to make sure we’re on the same page, when through models / orderables are synchronized, it doesn’t mean I won’t translate them, it just means they are not _automatically_ and _systematically_ translated. I can then pick the ones worth translating in the admin, manually, independently of the page where they are linked.

Hopefully this comment doesn’t add to the confusion, but this is a pretty important point

> Ah yea, can you file a bug for this? Can you translate categories correctly though? (Nope.. you mentioned that above).

Sure, filed https://github.com/mozilla/foundation.mozilla.org/issues/9551

**Comment by tbrlpld** [comment]
Thanks @TheoChevalier, that makes sense. 

And thanks for filing the bug report.

**Comment by tbrlpld** [comment]
Just to clarify @cdanfon @TheoChevalier do we consider this QA passed?

**Comment by cdanfon** [comment]
Looks good to me @tbrlpld, unless @TheoChevalier disagrees

**Comment by tbrlpld** [comment]
@TheoChevalier I am not sure we have. Can you file one please?

**Comment by cdanfon** [comment]
As per new process should we pass this onto the design team for testing? @tbrlpld @beccaklam @kristinashu

**Comment by tbrlpld** [comment]
I am not sure that is necessary, since @TheoChevalier is the stakeholder for this change and has tested personally.

**Comment by tbrlpld** [comment]
Thanks for filing the bug @TheoChevalier

**Comment by beccaklam** [comment]
Looking at the description of this ticket I agree that Theo is the correct stakeholder/tester for this! @cdanfon

**Comment by tbrlpld** [comment]
Since @TheoChevalier has filed the follow up ticket for the other discovered issues, I think we can consider this one done.
