### ISSUE TITLE
Language selector in the footer isn't working

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#9218]
### Describe the bug
The language picker at the bottom of the foundation site not working when selecting a new language, it should refresh the page and update the URL with the appropriate language code. 

### To Reproduce
1. Go to our footer on the foundation website
2. Select a different language
3. See that nothing changes

### Expected behavior
Page content updates to the selected language

**Comment by danielfmiranda** [comment]
Closed with #9219

**Comment by TheoChevalier** [comment]
Hey @danielfmiranda, looks like this is fixed locally, but is still broken on https://foundation.mofostaging.net
Are there some config vars to update?

**Comment by danielfmiranda** [comment]
Hi @TheoChevalier! Just made a minor update and pushed to staging, can you please take a look and see if this issue persists? Thanks!

**Comment by TheoChevalier** [comment]
Confirming it works now, thanks a lot @danielfmiranda !
