### ISSUE TITLE
PNI content entry link formatting bug

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9234]
### Describe the bug
Sometimes copy and pasting links into the PNI cms causes strange formatting like turning a single link into two links or not including some letters but including other letters that shouldn't be included. It isn't a big issued but does eat up a lot of time for people doing content entry because it can happen 100s of time. 

### To Reproduce
1. Go to the [research spreadsheet ](https://docs.google.com/spreadsheets/d/1pwA8WfzmzEKHN9ya2JP_lnnbCybmFUNptu4tWKCoU3g/edit#gid=1764292170)
2. Copy a cell of text that has links in it
3. Sometimes see the error

### Expected behavior
Links should appear the same in the cms as they do in the spreadsheet. 

### Screenshots
Example of copied cell in spreadsheet
<img width="552" alt="image" src="https://user-images.githubusercontent.com/1068783/184734190-bf889edc-e034-4a3f-a864-30a30bd1d648.png">

Example of re-formatting that happens
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/1068783/184734251-88c6db2d-d47e-41c7-8bb7-54898953c21e.png">

**Comment by kristinashu** [comment]
With @fessehaye prompt, I tested this on our main site as well and I am getting the same formatting error. 

![image](https://user-images.githubusercontent.com/1068783/184984698-d290c296-3d2b-4a18-a73e-28913565c131.png)

@cdanfon this could be a Wagtail issue. Are you able to flag this with the Wagtail team?

**Comment by cdanfon** [comment]
Thanks @kristinashu I've raised with the Wagtail team, will keep you posted

**Comment by cdanfon** [comment]
Hey @kristinashu I've heard back from the Wagtail team, see below their answer: 

> The link icons are a deliberate design feature, to show where individual link elements start. If the pasted content really does have links in those positions (i.e. there's one link on the "n" of "when", and another one that stops part way through the word "found") then Wagtail is working as designed - if not, then that could be a Wagtail bug where it's not getting the positions of links right.

I've gone ahead and cope the cell that you've mentioned above and pasted it into a Google docs, I think the issue might be to do with the links in the spreadsheet - see attached. 

<img width="763" alt="Screenshot 2022-08-17 at 17 48 22" src="https://user-images.githubusercontent.com/102978346/185196920-61006ebf-956e-4ea0-adba-ccdfa0422e3b.png">

**Comment by kristinashu** [comment]
Ah interesting! Thank you for figuring this out! I'll close this ticket. Thanks again!
