### ISSUE TITLE
PNI creepy vote results doesn't show selection when it's the first vote

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9235]
### Describe the bug
If I vote for a creepiness level that hasn't been voted on before then my selection doesn't show up as selected in the results. This isn't a big issue but it does mean that for every new product I spend a lot of time going and voting once for each level so that users don't notice the issue.

### To Reproduce
1. Go to a product that has not been voted on before 
<img width="759" alt="Screen Shot 2022-08-15 at 3 56 45 PM" src="https://user-images.githubusercontent.com/1068783/184734962-613fadb1-6a84-4000-8ac0-a7b30624ccac.png">
2. Vote 
<img width="759" alt="Screen Shot 2022-08-15 at 3 56 53 PM" src="https://user-images.githubusercontent.com/1068783/184734989-5d285d26-8620-4b3a-864e-ef71086c433a.png">
3. See error that it doesn't show you what you voted
<img width="762" alt="Screen Shot 2022-08-15 at 3 56 59 PM" src="https://user-images.githubusercontent.com/1068783/184735052-db655090-8542-4e80-b4c8-f7dae17b7f8b.png">

### Expected behavior
What you voted for should be highlighted in the results.
<img width="759" alt="Screen Shot 2022-08-15 at 3 58 10 PM" src="https://user-images.githubusercontent.com/1068783/184735105-f26dfac6-b3e6-40e6-a91d-95642ec5be0f.png">

**Comment by fessehaye** [comment]
@cdanfon this should probably be part of the support tasks this sprint right?

**Comment by kristinashu** [comment]
No rush on this! I'd say it should be done before the main holiday launch in Oct.

**Comment by cdanfon** [comment]
Hey @fessehaye 

I appreciate you doing this but the priority for this ticket was fairly low and would've been better to focus on p1 PNI work. 

Ideally the sprint commitment (tickets we will be working on) is something we negotiate as a team during our sprint planning meeting and is fixed for the duration of the sprint. No changes should be made to the sprint commitment (ie, removing tickets or adding tickets to the sprint) without the prior team agreement.

The reason being is that planning is made based on priorities. The goal for this sprint is to complete as many p1 PNI tickets as possible as we're a bit behind schedule. Working on that ticket interferes with the sprint goal.

I'd like to understand your reasoning though, do you feel you are likely to run out of tickets this sprint or is it confusion about what is expected from you when assigned to the 'Support duty' task? 

Thanks!
