### ISSUE TITLE
SUPPORT DUTY - Blog Landing page's "featured posts" images are stretching

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#9236]
### Describe the bug
At the large breakpoint, images for the 1st and 5th "featured post" stretch to fill the size of the containing div.
![Screen Shot 2022-08-11 at 5 01 32 PM](https://user-images.githubusercontent.com/18314510/184769957-17d7b81a-8cbe-4451-93be-e5b8f7e69937.png)

### To Reproduce
1. Go to https://foundation.mozilla.org/en/blog/
2. Resize window from XL to L
3. Note the stretching of the image

### Expected behavior
The image should instead keep its original ratio, even if that means a little more whitespace then usual:
<img width="908" alt="Screen Shot 2022-08-15 at 10 51 53 AM" src="https://user-images.githubusercontent.com/18314510/184781682-5c36c58f-8327-4f4b-90a8-3d33e349ef96.png">

**Comment by nancyt1** [comment]
Image is also stretching if the text on the left is really long, it would be great if it can keep the original ratio in this instance also.

<img width="1680" alt="Screen Shot 2022-08-17 at 3 33 29 PM" src="https://user-images.githubusercontent.com/74557207/185242328-35537f3e-9f9f-427a-9ec5-db8af8d2904b.png">

**Comment by cdanfon** [comment]
A MoFo colleague has posted in mofo-wagtail regarding this issue. Re-opening as it looks like it hasn't been fully sorted.

There's a new feature article where the image looks a bit squisehd. 

>  _The image in the featured blog post is pulling from the 1.91:1 OG image, but that isn’t the right dimensions for that spot. It looks a bit squished._

![image.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/8d50d611-30e2-45c7-ab49-8ef12b3b1184)


@mtdenton one for the Support triage call
