### ISSUE TITLE
Continuous scroll functionality not working 

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9244]
### Describe the bug
The continuous scroll functionality is broken on this tik tok publication landing page: [https://foundation.mozilla.org/en/campaigns/tiktok-political-ads/.](https://foundation.mozilla.org/en/campaigns/tiktok-political-ads/). 

It's also not working on https://foundation.mozilla.org/en/insights/trustworthy-ai-whitepaper/executive-summary/ which is a publication within a publication 

It seems to be working on this other publication though: https://foundation.mozilla.org/en/insights/trustworthy-ai-whitepaper/ so not quite sure what is going on.

### To Reproduce
1. Go to https://foundation.mozilla.org/en/campaigns/tiktok-political-ads/
2. Scroll down to the bottom of the page
3. See error - next publication doesn't appear

### Desktop 
 - OS
 - Browser Chrome
 - Version 104.0.5112.79

### Additional context
This issue seems to affect only certain pages (publications within publications). I wonder if the logic prevents continuous scroll unless the same page type comes after.

**Comment by cdanfon** [comment]
Hey @kristinashu I've raised a ticket for this and planned it for the upcoming sprint, under the 'Support duty' task.

**Comment by kristinashu** [comment]
Wonderful, thank you Claudia!

**Comment by cdanfon** [comment]
@danielfmiranda to pick this one up as part of the support duty

**Comment by kristinashu** [comment]
Please also look at this use case https://foundation.mozilla.org/en/research/library/user-controls/report/executive-summary/ as it also isn't loading for me.

This is important for this to be fixed for next week's YouTube launch.

**Comment by cdanfon** [comment]
Hey @danielfmiranda Further to @kristinashu comment about next week's YouTube launch, will this issue be completed by end of sprint (today)?
Thanks!

**Comment by danielfmiranda** [comment]
Hi @cdanfon I do not believe that this ticket is going to be completed by end of sprint

**Comment by cdanfon** [comment]
Thanks @danielfmiranda 

This would be an example of why requests like the ones Alexander had should've gone through the support process. 

We didn't have visibility of it and couldn't decide which one should've taken priority - hope that makes sense but happy to talk about the support process further if needed :)

**Comment by danielfmiranda** [comment]
Hi @cdanfon! Definitely makes sense, apologies for the confusion!
