### ISSUE TITLE
Personas draft: program staff review during All Hands

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#925]
We will have the personas printed in posters during All Hands in Austin. It is a good opportunity to get feedback on the ones that are ready to go and to have more info from staff on the ones that are still incomplete (not enough data).

We will also print the personas cards (letter size set of personas) so people can grab a set and bring to their team meetings if they wish. - **Taís will print some sets in Vancouver office and bring to Austin.**

I thought about printing a size close to A2:
<img width="719" alt="image" src="https://user-images.githubusercontent.com/22157921/33586726-99496968-d91f-11e7-937c-002687d45c8a.png">

Fedex prints mounted posters in 18" x 24" (45.72cm x 60.96cm), which is very close to A2 so I am using these measurements as a reference.

**DEADLINE: Taís to send all the artwork by EOD Wed (Dec 6th) so we have time to get those printed by Fedex.**

**Comment by taisdesouzalessa** [comment]
Hey @xmatthewx could you take a look at this poster template and let me know your thoughts on it? It had to be different than the cards because we just have 1 page to display all the info in this case.
https://redpen.io/p/an5fa1a49d3273f94e

I will use this layout as a reference to all posters we will print for All Hands.

**Comment by taisdesouzalessa** [comment]
Hey @xmatthewx here is the revised version of the poster. I like the fact those changes allowed the illustration to be bigger and more impactful:

https://redpen.io/p/an5fa1a49d3273f94e

**Comment by taisdesouzalessa** [comment]
@xmatthewx I was thinking if we should have another poster with some info for context to staff like:
1. Brief explanations of what personas are
2. Brief explanation about how those personas were built
3. How staff can help: we can ask them to think about their last interactions with their audience, could they fit the audience in one of those categories of personas? Is there anything we are missing or they feel it is incorrect on each board? Could they help us to complete or point out where we can find more info about the personas we are missing some information (Internet Enthusiast/Woke Internet User)?
4. QR code for feedback in a computer and we can also have stickies to get handwritten feedback.

It would be mainly a poster full of copy, kind of like those intros we have in art exhibitions that give some context, you know? I think it is valuable since there won't be anybody there to explain the personas and how they were built. What do you think?

**Comment by xmatthewx** [comment]
This all sounds good. Let's do this without full color design, so it feels more honest, direct, informal. 

I honestly don't think people are going to take time to fill out a form with all the chaos at all hands.  I would skip the energy to make the form. Could invite them to email us.

**Comment by taisdesouzalessa** [comment]
All the personas posters are in RedPen:
https://redpen.io/p/an5fa1a49d3273f94e

@xmatthewx can you please take a look at them? I'll be double checking the info we have there, comparing with the ones we have in the spreadsheet. 
I need help mainly in the empty state posters (is the writing there all good?) and in the Instructions posters (please let me know if there are any grammar mistakes or if anything could be better written). Thanks!

**Comment by xmatthewx** [comment]
I reviewed things. Everything is looking awesome!!

Final steps...
 - update instructions
 - update instructions on empty personas (redpen comment)
 - update related personas (in spreadsheet)
 - names on persona overview poster

Ship
 - posters unmounted
 - letter-size version (collated and staple)

**Comment by taisdesouzalessa** [comment]
@xmatthewx - "final steps" bullet points were applied to posters:
https://redpen.io/p/an5fa1a49d3273f94e

On Friday I'll work on applying the changes we did in the posters to the cards (letter-size) + I'll have some bandwidth to apply any revision to posters you may need.

Thanks!

**Comment by taisdesouzalessa** [comment]
This work is done, closing :)
