### ISSUE TITLE
YTR 2022  | Top hero intro section and moving stats upwards

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9253]
Link to design - https://www.figma.com/file/XtEAabujYbKaP5mLnCtvVS/YouTube-User-Control-Report-Landing-Page?node-id=0%3A1

ACs:

- [ ] Copy matches content in this [document](https://docs.google.com/document/d/1-QU-Yv17WjAa788tNFmAxWbTJT7NGY2snY5qPSEGlWk/edit)
- [x] Content is broken down as per the new design
- [x] Stats appear at the end of this section and continue to be animated and match the new colour
- [x] Two illustrations to appear on each side of the stats as per the new design 

**TO DO**: clarify the use of illustration on tablet & mobile

**Comment by cdanfon** [comment]
@beccaklam to confirm where the button should be getting the content (pdf) from.

**Comment by cdanfon** [comment]
@kristinashu This is now ready for MoFo to review, please note my comments on Content.

**Comment by cdanfon** [comment]
I can't satisfy AC #1 as the content has been changed since Steve completed this ticket. 

Content changes would need to be re-factored towards the estimate.

**Comment by kristinashu** [comment]
This looks amazing, thank you so much! And sorry for those last minute copy changes.

There was also a stakeholder request to make the subtitle stand out more. Nancy mocked it up (see screep cap from Figma below). Should this be done here or in a new ticket? 
<img width="709" alt="image" src="https://user-images.githubusercontent.com/1068783/188724300-4a31c191-36a0-450b-b1dc-d6217a80b2d2.png">

cc @nancyt1 in case you see anything else

**Comment by cdanfon** [comment]
NB Removed AC the following AC which will be done as part of a separate ticket: 

- [ ] Copy matches content in this [document](https://docs.google.com/document/d/1-QU-Yv17WjAa788tNFmAxWbTJT7NGY2snY5qPSEGlWk/edit)

**Comment by cdanfon** [comment]
Hey @kristinashu if it's a one-off change we can update it within this ticket, @siimonevans are you OK to pick up this small change request please? 

Thanks!
