### ISSUE TITLE
YTR 2022 | Recommendation section

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9254]
ACs:

- [ ] Content changes as per new copy 
- [ ] Design changes as per new design (desktop, tablet, mobile)
- [ ] Only 2 buttons displayed (remove current 3rd one)

**Design files:** 
https://www.figma.com/file/XtEAabujYbKaP5mLnCtvVS/YouTube-User-Control-Report-Landing-Page?node-id=155%3A176599

**Screenshot**
![Image](https://user-images.githubusercontent.com/25041665/187960366-aebbfd94-161a-494c-a69c-e6f027470bab.png)

**Copy**: 
https://docs.google.com/document/d/1-QU-Yv17WjAa788tNFmAxWbTJT7NGY2snY5qPSEGlWk/edit

**Comment by siimonevans** [comment]
MR ready for review here: https://github.com/mozilla/foundation.mozilla.org/pull/9324

**Comment by cdanfon** [comment]
@tbrlpld Can you code review this please? Thanks!
