### ISSUE TITLE
YTR 2022 | We found section - new layout

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9256]
ACs:

- [x] Looks as design on desktop, mobile, tablet

Design: 
https://www.figma.com/file/XtEAabujYbKaP5mLnCtvVS/YouTube-User-Control-Report-Landing-Page?node-id=155%3A176599

Copy: 
https://docs.google.com/document/d/1-QU-Yv17WjAa788tNFmAxWbTJT7NGY2snY5qPSEGlWk/edit

![Image](https://user-images.githubusercontent.com/102978346/188698033-7e30694a-31a0-4575-abab-d789f26044fb.png)

**Comment by cdanfon** [comment]
Copy has been updated since implementation, I cannot satisfy AC #1, other than that is ok for @kristinashu and the team to check :)

**Comment by kristinashu** [comment]
Looks good to me!

cc @nancyt1

**Comment by cdanfon** [comment]
NB Removing AC:

- [ ] Content reads as per provided copy 

This will be picked up in a different ticket
