### ISSUE TITLE
YTR | New layout of YouTube feedback area

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9257]
ACs:

- [x] Add title 
- [x] Add paragraph 1
- [x] Add paragraph 2
- [x] Add paragraph 3
- [x] To look as mobile, desktop, table design 

Design: 
https://www.figma.com/file/XtEAabujYbKaP5mLnCtvVS/YouTube-User-Control-Report-Landing-Page?node-id=0%3A1

Copy: 
https://docs.google.com/document/d/1-QU-Yv17WjAa788tNFmAxWbTJT7NGY2snY5qPSEGlWk/edit

![Image](https://user-images.githubusercontent.com/102978346/186948693-dfbcefc3-d0ec-453f-9728-a958f9e968f3.png)

**Comment by cdanfon** [comment]
I can't satisfy AC #1 due to changes to the copy since the implementation was done. 

@kristinashu This is ready for your review with the content caveat.

**Comment by cdanfon** [comment]
Updates to content will need to be done, to refactor this in the original time estimate

**Comment by kristinashu** [comment]
Looks good! Again, sorry about the copy edits.

cc @nancyt1

**Comment by cdanfon** [comment]
Hey @kristinashu thanks for reviewing! 

I'm going to create a new ticket to cover all the copy edits and mark this ticket as complete.

Depending on how much time we've got left after completing all the original tickets either TBX or a MoFo dev can pick up the copy changes as well as the illustration updates. Hope that sounds OK!

**Comment by cdanfon** [comment]
NB I've removed ACs - [ ] Content to use copy provided
from the list. This will be done in a separate ticket

**Comment by kristinashu** [comment]
A separate ticket for copy updates sounds good.
