### ISSUE TITLE
YTR 2022 | Remove read more clickable and swap by sign a petition

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9258]
- [x] Remove Read more expand/collapse functionality
- [x] Title added
- [x] Paragraph changes as per new design 
- [x] Remove 'YOUTUBE’S BLOG' text 
- [x] Button added 
- [x] CTA takes me to Sign petition landing page

**Comment by stevedya** [comment]
This is now ready for review here: https://github.com/mozilla/foundation.mozilla.org/pull/9297

**Comment by cdanfon** [comment]
@bheasman This is a test

**Comment by cdanfon** [comment]
All good except for the link on the CTA, which currently takes me to a 404:

https://foundation.mozilla.org/en/campaigns/youtube-user-controls/?_gl=1*1fvycg2*_ga*NTY4NDcxMTM3LjE2NTY0OTE2NzY.*_ga_4R07FEDXLC*MTY2MjQ4MzQyOS45LjEuMTY2MjQ4Mzg1OS4wLjAuMA..

@siimonevans this was done by @stevedya last week. Can you update the link once @kristinashu confirms where should we point that CTA to? 

Thanks!

**Comment by kristinashu** [comment]
This looks great! The page doesn't yet exist but the URL will be https://foundation.mozilla.org/campaigns/youtube-user-controls. 

cc @nancyt1

**Comment by cdanfon** [comment]
Thanks for confirming @kristinashu I've marked that AC as completed now :)
