### ISSUE TITLE
YTR 2022 | Remove drawer accordions

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9259]
ACs:

- [ ] As a user I cannot see the accordions

**Comment by cdanfon** [comment]
Hey @stevedya 

Can I check with you why this has been marked as done? We haven't gone through testing.

**Comment by stevedya** [comment]
@cdanfon Oops sorry for the confusion! Since we actually created a new template for this work, the accordions won't be in there by default so no need to remove them at all since they don't technically exist on this new page. If you'd like we could move this to  QA testing for now
