### ISSUE TITLE
Ideate Network Visualization

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#926]
Brainstorming doc: https://docs.google.com/presentation/d/1xokDoi88YUG7EGOic8T94vj-2WLEDENnY38aTLHEVzA/edit#slide=id.g1ea5ab4fd9_0_139

For a visualization of the network we need to determine what we want to communicate and what meaning we want to convey to our audience. This will help determine what visual direction we want to take.

We also should discuss the narrative and context of this visualization and where this will live.

**Comment by xmatthewx** [comment]
We can move this to https://github.com/mozilla/network-pulse/issues/883

**Comment by kristinashu** [comment]
Closing since it has been moved to mozilla/network-pulse#883
