### ISSUE TITLE
YTR 2022 | Change copy on stats numbers and content surrounding

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9261]
ACs:

- [x] Add title as per copy document 
- [x] Add introduction as per copy document 
- [ ] To look as design for mobile, tablet, desktop
- [x] Stats to be animated counting upwards

Copy:
https://docs.google.com/document/d/1-QU-Yv17WjAa788tNFmAxWbTJT7NGY2snY5qPSEGlWk/edit

Design: 
https://www.figma.com/file/XtEAabujYbKaP5mLnCtvVS/YouTube-User-Control-Report-Landing-Page?node-id=0%3A1

![Image](https://user-images.githubusercontent.com/102978346/186947345-3b57c1d4-ba87-4da2-8ef5-9a54cf1f7da5.png)

**Comment by stevedya** [comment]
This is now ready for review here: https://github.com/mozilla/foundation.mozilla.org/pull/9298

**Comment by cdanfon** [comment]
Hey @siimonevans a few amends to this ticket on the work that @stevedya has done. 

Mainly around view on figma file vs. staging site for desktop, mobile & tablet. 

I've added a few screenshots comparing:


**Desktop**

Figma design: 

![Image](https://user-images.githubusercontent.com/102978346/188699306-b79681c5-e711-4fec-9610-258eab1ba188.png)


Staging site:

![Image](https://user-images.githubusercontent.com/102978346/188699248-2e71d746-bc45-4df1-84c7-b54d5b2465c1.png)

**Main difference on the above is the size of the cards, they seems to be taller in the staging site.** 


**Tablet**

Figma design: 

![Image](https://user-images.githubusercontent.com/102978346/188699833-af8c28c3-aaf3-4e5e-9a55-205f4365efcd.png)


Staging site:

![Image](https://user-images.githubusercontent.com/102978346/188699832-695c9dcb-3c73-487a-b5d4-030697e8a3d6.png)

**Main difference on the above is the size of the cards and white space padding** 


**Phone**

Figma design: 

![Image](https://user-images.githubusercontent.com/102978346/188700058-553de86a-0ee4-477f-851e-d8ff1468c076.png)


Staging site:

![Image](https://user-images.githubusercontent.com/102978346/188700093-fa93ac45-a541-41b5-96f6-855a195d15aa.png)


**Main difference on the above is the size of the cards and white space padding**

**Comment by siimonevans** [comment]
PR open [here](https://github.com/mozilla/foundation.mozilla.org/pull/9329).
