### ISSUE TITLE
YTR 2022 | Integrate data wrap embed and content blurb below

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9262]
**ACs:**

- [ ] Update title 
- [ ] Update introduction 
- [ ] Include embed graph as per figma design 
- [ ] Include recommendation section using new copy 
- [ ] Include image on the left hand-side of the recommendation 

<img width="795" alt="image" src="https://user-images.githubusercontent.com/1068783/187966938-b99d47ec-5797-4ac6-bfb6-fcb405cb5292.png">

**Design**: 
https://www.figma.com/file/XtEAabujYbKaP5mLnCtvVS/YouTube-User-Control-Report-Landing-Page?node-id=0%3A1

**Copy**: 
https://docs.google.com/document/d/1-QU-Yv17WjAa788tNFmAxWbTJT7NGY2snY5qPSEGlWk/edit

**Comment by cdanfon** [comment]
Embed code below: 

`<iframe title="Bad Recommendation Rates" aria-label="Dot Plot" id="datawrapper-chart-vbiwl" src="[https://datawrapper.dwcdn.net/vbiwl/1/](https://www.figma.com/exit?url=https%3A%2F%2Fdatawrapper.dwcdn.net%2Fvbiwl%2F1%2F)" scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="626"></iframe><script type="text/javascript">!function(){"use strict";window.addEventListener("message",(function(e){if(void 0!==e.data["datawrapper-height"]){var t=document.querySelectorAll("iframe");for(var a in e.data["datawrapper-height"])for(var r=0;r<t.length;r++){if(t[r].contentWindow===e.source)t[r].style.height=e.data["datawrapper-height"][a]+"px"}}}))}();</script>`

**Comment by stevedya** [comment]
This is now ready for review here: https://github.com/mozilla/foundation.mozilla.org/pull/9298

**Comment by cdanfon** [comment]
**NB: there's been some discussion around the data wrapper embed and whether they automatically localize for different languages on the labels, or if we need to replace the url based on the locale.**

Link to slack conversation [here](https://mozilla.slack.com/archives/C03S8880GLC/p1662567042056669?thread_ts=1662477648.853219&cid=C03S8880GLC) 

### We will need to replace theURL based on the locale. Localised list of URLs for: 

French (fr): https://datawrapper.dwcdn.net/kl3jI/
German (de): https://datawrapper.dwcdn.net/iHxzV/
Spanish (es): https://datawrapper.dwcdn.net/QIjQb/
Dutch (nl): https://datawrapper.dwcdn.net/d8LI4/
Portuguese (pt-BR): https://datawrapper.dwcdn.net/KhNFD/

**Comment by siimonevans** [comment]
Confirmed via Slack that the `fr` code is actually `https://datawrapper.dwcdn.net/w8veu/`. Updating PR…

**Comment by kristinashu** [comment]
I think this is done!
