### ISSUE TITLE
YTR 2022 | Animated timeline section

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9263]
ACs:

- [ ] Include a floating 'Skip' link at the bottom 
- [ ] As you scroll through text and images take a parallax effect as per example https://theraelettes.com/
- [ ] To look as per the design on desktop, mobile and tablet
- [ ] Images start small and go bigger as you scroll

**Design**: 
https://www.figma.com/file/XtEAabujYbKaP5mLnCtvVS/YouTube-User-Control-Report-Landing-Page?node-id=155%3A176599

**NOTE**: What's the desired behaviour for user with prefers-reduced-motion turned on? _Becca: "We should support this if they we have time to do it but is not an MVP"_

**Comment by cdanfon** [comment]
We've decided during the stand-up that we're going to simplify the animation slightly for the MVP and focus on parallax images and if next week we've got time we will look into adding the text and year.

**Comment by stevedya** [comment]
Hey @siimonevans i have a draft of this work here. It still has a bit of outstanding work but might serve as a good starting point for this one. See here: https://github.com/mozilla/foundation.mozilla.org/pull/9303

**Comment by stevedya** [comment]
@siimonevans this is now ready for review here! https://github.com/mozilla/foundation.mozilla.org/pull/9303

**Comment by siimonevans** [comment]
Hey @stevedya I've reviewed this - great work!

I noted on the PR that I shared your accessibility concerns which you raised via Slack [in this thread](https://torchbox.slack.com/archives/C03S8880GLC/p1662682434446949).

It would be good to get that ironed out before merging, but otherwise I think we're good to go.
