### ISSUE TITLE
Enable search for profile snippets in snippet chooser dialogs

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9267]
## Description

It is very tedious to add a Profile as authors on blog posts, publications, and in research hub landing pages. The list appears as a long multi page list that is, I believe, in order they were added.

I am curious if Wagtail "out of the box" has a better UX for this already or if we can update ours to be in **alphabetical order** and with a search?

Screen cap from prod:

<img width="300" alt="Screen Shot 2022-08-24 at 3 12 05 PM" src="https://user-images.githubusercontent.com/1068783/186720110-1b6179e6-2268-454f-ac09-e42055bc9483.png">

## Dev notes

- Alphabetical ordering has been added before
- See https://docs.wagtail.org/en/v2.16.3/topics/snippets.html#making-snippets-searchable

## Acceptance criteria

- [ ] As an editor, when adding selecting profiles (e.g. to add them as author on a blog page like https://foundation.mozilla.org/cms/pages/21874/edit/) I can search the profiles by name.

**Comment by kristinashu** [comment]
Added that finding a profile in the snippet is also painful because staff have to click through 10 pages of names. A search and alphabetical order would be very helpful. Screen cap of CMS on prod:

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/1068783/189206097-160c3c1b-bf72-4c40-9cff-41a71b59d1c8.png">

**Comment by tbrlpld** [comment]
Thanks @kristinashu I need to double check, but I believe these are issues that have been addressed in the Wagtail v3 or v4 releases. If not, this is certainly something we can report to the core team.

**Comment by kristinashu** [comment]
Oooooh that would be very nice!

**Comment by tbrlpld** [comment]
Looks like I spoke too soon. I will carry these feature requests forward to the Wagtail team though.

**Comment by tbrlpld** [comment]
Until that feature lands, we should be able to create custom admin pages (snippets are really only a simple version of custom admin pages). 

This is an example for such a page:
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/24797493/191838358-2d903c3b-d6cb-43c9-8ca4-0dfd3539a5d5.png">


Btw, this is not dependent on Wagtail upgrades (this screenshot is only made on a newer version).

**Comment by tbrlpld** [comment]
I am just realizing... we can also make the profiles searchable 🤦‍♂️: https://docs.wagtail.org/en/stable/topics/snippets.html#wagtailsnippets-making-snippets-searchable

It does not really take much. Also, the sort order is definitely something we control.

Thanks for reporting this @kristinashu. This should be fixable pretty easily.

**Comment by kristinashu** [comment]
Amazing, thank you for looking into this Tibor!

Should this be two tickets? One for the original comment about selecting authors to add them to a page and then a different one for the [second comment](https://github.com/mozilla/foundation.mozilla.org/issues/9267#issuecomment-1241119987) about finding a profile within the snippet?

**Comment by tbrlpld** [comment]
@cdanfon Moving this into the sprint because I am stalled on #9881

**Comment by tbrlpld** [comment]
@kristinashu Profile search by name is on staging now: https://foundation.mofostaging.net/cms/pages/390/edit/

**Comment by kristinashu** [comment]
w00t search is there and working well!

My out-of-scope feedback that I don't expect to be actioned on is that it would be nice if "nancy" showed up while typing "nanc" since I feel this is more commonly how live search works. Maybe this is feedback for Wagtail. But anyways, the search is still very nice to have now!

<img width="398" alt="Screenshot 2023-02-02 at 3 57 06 PM" src="https://user-images.githubusercontent.com/1068783/216477965-ac05be85-4390-47ee-9f68-f04de1d8d0b9.png">

<img width="398" alt="Screenshot 2023-02-02 at 3 57 12 PM" src="https://user-images.githubusercontent.com/1068783/216477966-6e463b8a-406f-471e-a79b-8c70a00ae5cd.png">

**Comment by tbrlpld** [comment]
Thanks @kristinashu. Yea, this is something that I have been noticing too. It's quite confusing really. I will take that to the Wagtail team, but this might be something that will need more work. I did enable partial matching in the options I have, so I am not sure what I am missing.

**Comment by tbrlpld** [comment]
Looks like this will be fixed in 4.2: https://github.com/wagtail/wagtail/issues/772

**Comment by kristinashu** [comment]
That's great to hear!

**Comment by cdanfon** [comment]
Closing this issue as will be picked up in future versions of Wagtail

**Comment by kristinashu** [comment]
Sorry, I don't think this should be closed. The AC for the ticket have been met and the PR is on staging so I think we should keep this open and in the ready for production column.

**Comment by cdanfon** [comment]
Sorry, I misinterpreted Tibor's comment!

**Comment by kristinashu** [comment]
Actually, this is weird. I was just checking something else on staging and noticed the search is no longer working.

@danielfmiranda any idea if something changed?

Screen cap of the exact same search that was working on staging but is no longer working:

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/1068783/217113417-bbb2b883-7490-460a-8f69-74c3e02c9ae7.png">

**Comment by kristinashu** [comment]
Never mind, this is working again now. So weird.
