### ISSUE TITLE
[RegretsReporter] Create additional graphics for Publication template & PDF

### ISSUE THREAD

**Issue by nancyt1** [mozilla/foundation.mozilla.org#9279]
- [x] Meet with Becca to talk about what graphics are needed for the publications and pdf
- [x] Compile all the graphics needed 
- [x] Produce graphics
- [x] Send for feedback
- [x] Make updates

**Comment by nancyt1** [comment]
Started creating the graphics in [figma](https://www.figma.com/file/XtEAabujYbKaP5mLnCtvVS/YouTube-User-Control-Report-Landing-Page?node-id=562%3A1022), waiting on Becca to see where I should put it for feedback

**Comment by nancyt1** [comment]
Added the graphics into the draft doc and [drive](https://drive.google.com/drive/u/0/folders/1m3xRctsN4hWA-l0tA0tPNzm67eGHADgZ) and tagged Becca R to review

**Comment by kristinashu** [comment]
These are looking nice and clean! You could add the graphics to the main YT Redpen so it's easier for people to give feedback and so everyone can see them.

**Comment by nancyt1** [comment]
Added the graphics to [redpen](https://redpen.io/p/kwa5086c1432931f2f), still waiting on final approval for this [graphic](https://redpen.io/wd0890ec7f1521a697)

**Comment by nancyt1** [comment]
Finalized all graphics for PDF and added them into the publications template
