### ISSUE TITLE
[RegretsReporter] Landing page finishing touches

### ISSUE THREAD

**Issue by nancyt1** [mozilla/foundation.mozilla.org#9281]
Updating micell. things that come up

- [x] Update recommendations with new copy
- [x] Test different type styles to fit full hero title
- [x] Update designs with latest copy (Sep 6)
- [x] Export updated tablet and mobile to redpen

**Comment by kristinashu** [comment]
I think this is all done! Good to close?

**Comment by kristinashu** [comment]
Sorry, I guess you still need to update the mobile and tablet version in Redpen
