### ISSUE TITLE
[PNI] Release PNI 2022 editorial content work to production

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#9287]
# Description

Release the integration branch `pni-2022` to staging and production. 

# Acceptance criteria

- [x] We consider the state of PNI on staging ready for production

**Comment by tbrlpld** [comment]
Wow, how did we miss this in "planning"...

**Comment by tbrlpld** [comment]
@mtdenton @kristinashu @cdanfon @beccaklam @nancyt1 @fessehaye @danielfmiranda 

The PNI integration branch is now ready on staging (the normal staging -- not the preview app anymore) for QA. 

https://foundation.mofostaging.net/en/privacynotincluded/

This does not yet contain all the QA fixes. We can deploy those one by one. 

Until we are happy with QA on staging we should not push to prod though. So this is a release blocker for all other work.

**Comment by kristinashu** [comment]
This is live!!!

**Comment by tbrlpld** [comment]
Yup. This can be closed.
