### ISSUE TITLE
[PNI] Featured advice article for PNI homepage [Backend]

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9288]
[Figma component](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3096%3A30793)

![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/f9863297-d3db-49ca-8e91-7d15365ebb88)

Dev Tasks:
* [ ] Add CMS field for homepage to add related PNI articles, limit 1
* [ ] Update wagtail factories to included new CMS changes

Acceptance Criteria:
* [x] Should be able to add up to 1 article via CMS for related content on homepages

**Comment by cdanfon** [comment]
Hey @tbrlpld are you waiting on a review from either @fessehaye or @danielfmiranda ?

**Comment by tbrlpld** [comment]
@cdanfon No, @danielfmiranda did review yesterday. I forgot to deploy to staging. It's now available: https://foundation-pni-2022.herokuapp.com/cms/pages/1444/edit/

**Comment by cdanfon** [comment]
I checked this, and as I understand, the related content the AC above is referring to is the  _**Hero featured article:**_ in the backend. 

If so the ticket is ready to go.

@tbrlpld shout if not!

**Comment by tbrlpld** [comment]
@cdanfon No. It is **not** referring to the "hero featured article". It's about the "featured advice article".

**Comment by cdanfon** [comment]
Thanks @tbrlpld Just checked, looking fine - thanks for clarifying
