### ISSUE TITLE
Progressive Web Apps support project

### ISSUE THREAD

**Issue by RobertJGabriel** [mozilla/foundation.mozilla.org#929]
Hey,

Just said I would throw it out there in case there is any interest as I am looking for a way to helping Mozilla community and project to do.

I was looking at the website and thought I could spend my Xmas break in converting it have Progressive Web App support and service workers. If there is interest I would be more then happy to do the work and give back for all the help the community has given me.

**Comment by alanmoo** [comment]
I just saw this, as we've all been on break as well. Thanks for the offer, but I don't know that this is the best candidate for that tech stack. You might be interested in github.com/mozilla/network-pulse though, that's a bit more of a front-end web application that might benefit from some newer fanciness in the future.
