### ISSUE TITLE
YT | Insert new illustrations

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9299]
YTR | New layout of YouTube result area[#9257](https://github.com/mozilla/foundation.mozilla.org/issues/9257)
- [ ] Illustration changes as per new design

YTR 2022 | Top hero intro section and moving stats upwards[#9253](https://github.com/mozilla/foundation.mozilla.org/issues/9253)
- [ ] Top Illustration changes as per new design
- [ ] SIde illustrations change as per new design

YTR 2022 | Recommendation section[#9254](https://github.com/mozilla/foundation.mozilla.org/issues/9254)
- [ ] Illustration changes as per new design

YTR 2022 | Remove read more clickable and swap by sign a petition[#9258](https://github.com/mozilla/foundation.mozilla.org/issues/9258)
- [ ] Icon changes as per new design

**Comment by cdanfon** [comment]
This ticket is blocked until we receive confirmation that the illustrations have been completed and signed off. 

@sabrinang @kristinashu any updates on the above please?

**Comment by sabrinang** [comment]
BeccaR signed off on Slack. Illustrations exported in google drive:
- Desktop: https://drive.google.com/drive/folders/1-5BwU98HpFR4y1xix_V9h8gODxuFFWdV?usp=sharing
- Mobile: https://drive.google.com/drive/folders/12sx05afruAOT5pJcue7D2ZvFPRj02Cbg?usp=sharing
- Quote images for both: https://drive.google.com/drive/folders/10LmiUYk4HXzD4mus_Axa7X5ymOf-NbAT?usp=sharing

**Comment by siimonevans** [comment]
All changes have been pushed to [this PR](https://github.com/mozilla/foundation.mozilla.org/pull/9339), with the exception of the recommendation section - I'll handle that as part of #9524.
