### ISSUE TITLE
Enable CSP for Ask forms

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#930]
[This page](https://foundation.mozilla.org/opportunity/nsf-showcases/) (unpublished draft right now, you need to log in as admin) needs the embedded form to work. Please enable CSP so it does.

**Comment by alanmoo** [comment]
FYI: I tried enabling CSP locally for `https://ask.mofoprod.net` but it didn't work, I had to approve s3 completely.

**Comment by cadecairos** [comment]
This is working on staging and production.

``` shell
cade@cade-moz  ~  heroku config:get CSP_FRAME_SRC -a foundation-mozilla-org   
'self' https://www.youtube.com https://survey.mofoprod.net
 cade@cade-moz  ~  heroku config:get CSP_FRAME_SRC -a foundation-mofostaging-net
'self' https://www.youtube.com https://survey.mofoprod.net

```
