### ISSUE TITLE
[PNI] - Featured Article Homepage - [Frontend]

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9302]
[Desktop comp](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3096%3A30793)
[Mobile comp](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3075%3A29691)

![Screen Shot 2022-07-27 at 2.15.50 PM.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/72634120-c204-4f0a-a6f5-bc50047bdf13)

Dev Tasks:
* [x] Add Template to top of homepage
* [x] Include Related Reading block

Acceptance Criteria:
* [ ] Hero image is styled accordingly and works on mobile 
* [ ] Related Article Section is included and styled correctly

**Comment by cdanfon** [comment]
Hey @fessehaye 

I've been trying to test this, but the hero image doesn't seem to appear in any of my tests. 

This is how the back end looks like: 

![Screenshot 2022-09-09 at 10.23.05.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/1bdfd6d8-f7da-4619-a453-3d838204e71b)

This is how the frontend looks like:

![Screenshot 2022-09-09 at 10.22.55.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/6fe2e738-0394-452f-8bf2-9882dcae32fe)

I'd expect the image I'm using to appear on the homepage, but it isn't. Can I check with you if this is what's expected to happen? 

Thanks

**Comment by cdanfon** [comment]
Through testing other tickets I've noticed that the image is now showing on the homepage.

I'm assuming @fessehaye has fixed this. Marking this as QA passed and closing it
