### ISSUE TITLE
Add Fellowships section to site - Master ticket

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#933]
Let's use this ticket as a master placeholder for the Fellowship work on the Foundation site. We can track documents and such here, feel free to edit this comment

[Design ticket](https://github.com/mozilla/foundation.mozilla.org/issues/845)

UI DESKTOP - clickable prototype
- [UI Applications Open](https://invis.io/ZJ9YTAGEA#/276734814_v2-FellowshipsUI_-_Overview) 
- [UI Applications Closed](https://invis.io/ZJ9YTAGEA#/276734811_v2-FellowshipsUI_-_Overview_Applications_Closed) 

UI MOBILE  - clickable prototype - status: **outdated** (making sure the desktop changes are confirmed before moving to doing the changes in mobile but it is likely the structure on mobile won't change too much)

- [UI Applications Open](https://invis.io/Z4FGLVDEP3W#/275861761_MOBILE_-_FellowshipsUI_-_Overview) 
- [UI Application Closed](https://invis.io/Z4FGLVDEP3W#/275861758_MOBILE_-_FellowshipsUI_-_Overview_V2_Applications_Closed) 

[Site requirements Google doc](https://docs.google.com/document/d/1dVRxKDmSIkrJdKhPqxHzhrByJ6fFkf0eCsQgm12sckI/edit?ts=5a4fc694#heading=h.x80etj9gzt9u)
[Site Content](https://docs.google.com/document/d/1iiQ5lTFpAbEvRMYcNx9DqvaTmVjCE-AHwYh4PMtvveg/edit?usp=sharing)
[Spreadsheet with required info from Fellows (directory)](https://docs.google.com/spreadsheets/d/1fZXiQTn9BgGkWEDy7rSVabKHjbptbYDjUdKEMUygNt0/edit?usp=sharing)

**Comment by xmatthewx** [comment]
I think this is all taken care of elsewhere. Closing. cc @taisdesouzalessa
