### ISSUE TITLE
QA for Youtube user control study

### ISSUE THREAD

**Issue by nancyt1** [mozilla/foundation.mozilla.org#9354]
https://foundation.mofostaging.net/en/youtube/user-controls/

# P1 

**Copy Edits**
- [x] "Our work is the first-ever experimental audit of YouTube by independent researchers, powered by Mozilla’s RegretsReporter." ->  "Our work is the largest experimental audit of YouTube by independent researchers, powered by Mozilla’s RegretsReporter."
- [x] Under section: People take a trial-and-error approach to controlling their recommendations. 
     - Last sentence says "It rarely works. Said one user:" → "It doesn’t seem to work. Said one person:"
     - "When YouTube’s own controls fail, people take matters into their own hands, using tactics including VPNs, new devices, and altered behavior like not clicking on or hovering over videos." → "When YouTube’s own controls fail, people take matters into their own hands, relying on privacy tools or even changing how they watch videos on YouTube."
- [x] Under section: The result?
    - Update graph subtitle "among all video pairs assessed by our research assistants" → "among high-risk video pairs assessed by our research assistants"
- [x] Missing title before timeline: "Bad recommendations resurfaced over time."

# P2
**Timeline Functionality**

- [x] **Functionality of timeline is varying across devices:** 

**Timeline is working on**  ✅:
 _iPad OS 15.6.1_
      - Firefox 
      - Chrome 
      - Safari 
 _iOS 15.6.1_
       - Firefox  
       - Chrome 

**But not working on** ❌:
_iOS 15.6.1_
        - Safari

_Comments_
   - (Nancy) Weird lag happening on timeline in mobile? Sometimes it's just white until the images and text load in. And the pictures are really small but if you wait a while and scroll up and down, it will fade in like intended. Sometimes it stays blank.
    - (Nancy) Sometimes I run into this bug where I can't scroll up, I can only scroll down and it will jitter or lag. Scroll on tablet/mobile feels really sluggish in general, especially anything in the white section. Overall it doesn't seem responsive to touch, it takes a couple scrolls to feel like you're going somewhere.
 ![IMG_0371](https://user-images.githubusercontent.com/74557207/189696338-45670669-f1d2-4ab6-8766-723db276545b.PNG)
- [x] on tablet (iPadOS 15.7): timeline does not appear for Sabrina
- [x] on mobile (Android 11): timeline section feels like Sabrina has to scroll a lot for the page to move which makes it feel sluggish

# P3
**Design Edits**
- [x] The 2 illustrations are in the wrong order for "Our work is the largest experimental..." section. It should swap places
- [x] Illustration: use mobile version of [labyrinth for mobile](https://drive.google.com/open?id=12wGjK3xBcJwtNVo0i3jExPCG3Dt3zA38&authuser=sabrina%40mozillafoundation.org&usp=drive_fs)
- [x] Illustration: use updated, hi-res [quote images](https://drive.google.com/open?id=10LmiUYk4HXzD4mus_Axa7X5ymOf-NbAT&authuser=sabrina%40mozillafoundation.org&usp=drive_fs)
- [x] Illustration: use mobile version of [regrets for mobile](https://drive.google.com/open?id=14j55nIZMyt4IDXpK110lJllaFVVOfBtm&authuser=sabrina%40mozillafoundation.org&usp=drive_fs)
- [x] **Adding white background:** If there is time, can we add the white background styling for the timeline used for mobile and partially for tablet (seems like it only shows for the date and not other text) and apply it to desktop and all of tablet too? Tyler raised that bad contrast of text should ideally not happen no matter the state of the page
- [x] The hero image looks smaller compared to the figma designs and the previous youtube landing page as well as the font sizes. I'd prioritize the image size over the font.
<img width="732" alt="image" src="https://user-images.githubusercontent.com/74557207/189740029-ade208eb-859f-42cd-bc0b-856dec80e377.png">

- [x] Image is too big for "What is a bad recommendation" section, the max width should be around 25-30% for desktop.
- [x] Not a huge priority but for some reason the first quote on the timeline is cut off on mobile for me:

![IMG_0355](https://user-images.githubusercontent.com/20977376/189733596-9b594efa-f5f8-4ffc-84c7-f4b274504371.PNG)

**Comment by sabrinang** [comment]
- [ ] Illustration: use mobile version of [labyrinth for mobile](https://drive.google.com/open?id=12wGjK3xBcJwtNVo0i3jExPCG3Dt3zA38&authuser=sabrina%40mozillafoundation.org&usp=drive_fs)
- [ ] Illustration: use updated, hi-res [quote images](https://drive.google.com/open?id=10LmiUYk4HXzD4mus_Axa7X5ymOf-NbAT&authuser=sabrina%40mozillafoundation.org&usp=drive_fs)
- [ ] Illustration: use mobile version of [regrets for mobile](https://drive.google.com/open?id=14j55nIZMyt4IDXpK110lJllaFVVOfBtm&authuser=sabrina%40mozillafoundation.org&usp=drive_fs)

**Comment by siimonevans** [comment]
[This PR](https://github.com/mozilla/foundation.mozilla.org/pull/9359) addresses everything in P1 and P3 with the exception of the final point on P2.

**Comment by siimonevans** [comment]
[This PR](https://github.com/mozilla/foundation.mozilla.org/pull/9360) addresses P2, but needs testing with the original devices on which the performance degradation was observed.

**Comment by siimonevans** [comment]
Re:
>  The hero image looks smaller compared to the figma designs and the previous youtube landing page as well as the font sizes. I'd prioritize the image size over the font.

I've increased the hero image size and tweaked the positioning, so hopefully this is now closer to the designs. However, when I bump up the font size of the main heading we get a few layout/height issues - I've left it as it was previously as a result.

We could tweak it but I've ran out of time for now unfortunately - I don't want to start refactoring such important parts of the layout this late in the day without being able to test properly, sorry!

**Comment by beccaklam** [comment]
The timeline is working much better on iOS safari now, at least for me!
Something I've noticed:
- [ ] The initial quotation mark for the timeline is overlapping with some text at the beginning of the timeline (I've noticed this in chrome and firefox, will check safari later on my Mac (macOS Monterey 12.5.1):
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/20977376/189976430-596dd545-2ce9-4604-b7a2-f91d4aa09483.png">

- [ ] And then not as important (something I could live with at least) is this faint grey line at the end of the timeline:
![IMG_0364](https://user-images.githubusercontent.com/20977376/189976875-3547b42c-381f-4e14-be05-4834e893e801.PNG)

**Comment by sabrinang** [comment]
On narrow viewports _(MacOS 12.5.1 Firefox 104.0.1 & Safari 15.6.1)_ , 
- the card section doesn't lift enough to reveal the illustration
- the quote overlaps with the text above

https://user-images.githubusercontent.com/2492510/189978413-d181c1f5-744c-49ad-8b72-25b085878845.mov

**Comment by kristinashu** [comment]
Thank all for the QA and all the fixes!

@beccaklam the two you mentioned above are not ideal but I think they aren't not critical to fix.
> The initial quotation mark for the timeline is overlapping with some text at the beginning of the timeline (I've noticed this in chrome and firefox, will check safari later on my Mac (macOS Monterey 12.5.1):

> And then not as important (something I could live with at least) is this faint grey line at the end of the timeline:

@sabrinang what you mentioned does seem like an important bug to fix but I am unable to reproduce it. I have the same OS and browser versions that you mentioned. For me, at narrow widths, the card reveal animation doesn't happen so the illustration isn't hidden and then I'm not seeing the text overlap either. @beccaklam @nancyt1 could you please check this as well? Note, I'm using this url https://foundation.mofostaging.net/en/youtube/user-controls/

> the card section doesn't lift enough to reveal the illustration

> the quote overlaps with the text above

**Comment by nancyt1** [comment]
Hm I'm seeing @sabrinang's overlap issue when I inspect for mobile on my desktop window but not on ipad or my actual mobile device since the the card reveal animation does seem to be disabled for mobile devices.

**Comment by kristinashu** [comment]
I noticed the link url issue mentioned at the start of QA is still an issue. 
- [ ] Remove all extra charters that is being added to links

Steps to repeat:
- Click on a link like the Petition, Read the Full Report, RegretsReporter
- First time I click on it the url is fine
- Click on it again to see the issue
- E.g. 
   https://foundation.mozilla.org/research/library/user-controls/report/?_gl=1*w59eu2*_ga*MTQwMjY1ODQ5LjE2NjMxODAzNDY.*_ga_4R07FEDXLC*MTY2MzE4MDM0Ni4xLjEuMTY2MzE4MDQwOC4wLjAuMA..
   https://foundation.mozilla.org/en/campaigns/youtube-user-controls/?_gl=1*il0z03*_ga*MTQwMjY1ODQ5LjE2NjMxODAzNDY.*_ga_4R07FEDXLC*MTY2MzE4MDM0Ni4xLjEuMTY2MzE4MDM3NS4wLjAuMA..
   https://foundation.mozilla.org/en/youtube/regretsreporter/?_gl=1*lc92jp*_ga*MTQwMjY1ODQ5LjE2NjMxODAzNDY.*_ga_4R07FEDXLC*MTY2MzE4MDM0Ni4xLjEuMTY2MzE4MDM5NC4wLjAuMA..

**Comment by kristinashu** [comment]
Never mind, @mtdenton pointed out that:
> I think I see what's happening. Since you're traveling from the staging site to the production site using those links, it's adding all of that to the URL to keep track of your journey in GA, otherwise it can't track you from the staging domain to the prod domain. If that is in fact the case, then this won't happen in production since it's all going to be the [foundation.mozilla.org](http://foundation.mozilla.org/) domain pages in the user journey.

Confirmed that this is not happening on prod!

**Comment by kristinashu** [comment]
Unless anyone disagrees, I think the remaining bugs are minor and we are done!

**Comment by cdanfon** [comment]
Great, thanks for the update Kristina.
