### ISSUE TITLE
[PNI] - Integrates CTA on homepage | FE

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9357]
This ticket is to integrate the CTA in the homepage once the back end work has been completed.

Figma design: https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3403%3A38681

**ACs:**

- [ ] As a user I can see the CTA component in the homepage

**Comment by danielfmiranda** [comment]
Steps to test on QA:

- Visit PNI Home page https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/
- The call to action should be in line with the other items as shown in figma:
![image.png](https://images.zenhubusercontent.com/6046b7f1bc36adc9ce95a16a/f611b17c-dc34-4f50-a9bb-c2f82a78b9ed)

**Comment by cdanfon** [comment]
Checked the homepage on desktop, the CTA appears below the 'Popular' and 'In the Press' articles. See below:

![Screenshot 2022-09-22 at 10.56.56.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/922b9a1a-c8f8-463c-9f52-592fa69e04b8)

**Comment by cdanfon** [comment]
@fessehaye can you please update the PNI branch for me please?

**Comment by cdanfon** [comment]
@kristinashu Please ignore my above comment until @fessehaye has updated the PNI branch, it might just be down to that

**Comment by cdanfon** [comment]
Checked on staging, looking good now
