### ISSUE TITLE
[YouTube] Copy update to quotes in timeline

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9366]
- [ ] Add `(Participant 112)` at the end of the first timeline quote (see screen cap below)
- [ ] Add `(Participant 187)` at the end of the last timeline quote (see screen cap below)

<img width="718" alt="image" src="https://user-images.githubusercontent.com/1068783/190280974-91d1c540-19f4-471d-889f-165680f25ef0.png">

<img width="711" alt="image" src="https://user-images.githubusercontent.com/1068783/190281024-006ef034-375c-4f0e-b2b7-f013c00e9cd0.png">

**Comment by TheoChevalier** [comment]
Closing, done in https://github.com/mozilla/foundation.mozilla.org/pull/9367
