### ISSUE TITLE
Clean up Sketch file and Drive folder

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#938]
### To do:
- [x] Rename folder from "Mozilla Network Site" to "Foundation Site"
- [x] Archive and organize folders in Drive
- [ ] Update Sketch file to reflect what we see on http://foundation.mozilla.org/
- [ ] Add to Craft

@sabrinang @taisdesouzalessa could you help archive and organize the folder? I will start updating the Sketch file.

**Comment by taisdesouzalessa** [comment]
I can help organize the folders :).

**Comment by kristinashu** [comment]
Awesome thank you @taisdesouzalessa! Let me know when you're done or if you get stuck on anything.

**Comment by sabrinang** [comment]
I'll be organizing and syncing anything that I have worked of locally as well onto the drive

**Comment by kristinashu** [comment]
Sweet! 🙌

**Comment by sabrinang** [comment]
As we are sorting through our files are we following any sorting/naming conventions? There is this documentation on this topic was in the [/design repo wiki](https://github.com/MozillaFoundation/Design/wiki/Process#assets) that links to a [gdoc ](https://docs.google.com/document/d/1AZ_TrLkdWVnRT_fAxW-kFT3o2tDgMlg_f65AKKcrtJY/edit) and we may wish to update this too

**Comment by kristinashu** [comment]
For our folders, I've done the quick fix of moving all the Network files into a `z-Archive-Network` folder. We can just pull folders out of there as needed and please feel free to continue to organize the folders if you like!

<img width="957" alt="screen shot 2018-01-11 at 1 44 54 pm" src="https://user-images.githubusercontent.com/1068783/34849122-2bcd4628-f6d6-11e7-8012-53f10e82872d.png">
