### ISSUE TITLE
DFL 2022 | Landing Listing card

### ISSUE THREAD

**Issue by kevinhowbrook** [mozilla/foundation.mozilla.org#9393]
### Describe the feature request

We need to make a new listing card to be added on the landing section (see screenshot)

This should include:
- Image
- Title (text field)
- body (text field)
- optional page link (for title). (page chooser field)
- No footer/author. 

### Screenshots / mock-ups
![Screenshot(13)](https://user-images.githubusercontent.com/2128707/192488865-285d0567-6fa4-430a-8e8e-f4ffd6430eae.png)

### Additional context
Link to [designs](https://www.figma.com/file/goD9bRqPoedQAxi8OsInkR/Data-Futures-Lab%3A-Designs?node-id=626%3A9963)

---

**Dev Tasks:** 
* [ ] Create new listing card this will consist of title, body, optional metadata and optional page link
* [ ] Configure new text block template

**Acceptance Criteria:**
- [x] Design to look as per Figma files
- [x] As an editor creating a banner page I can add listing cards
- [x] Template stacks verticle on mobile
- [x] Title for cards to be black instead of blue as per outdated design

**Comment by kristinashu** [comment]
Design should follow existing styles and convention on the site i.e. the headline should be black not blue.

**Comment by kristinashu** [comment]
The listing card is working very well! 

The hover state for the heading doesn't seem to match our [style guide](https://foundation.mozilla.org/en/style-guide/#headers-links). 

Screen cap from staging (the underline looks blue and possibly too thin, it should be black and thicker)
<img width="395" alt="image" src="https://user-images.githubusercontent.com/1068783/195136063-ce5f17d4-3155-4ff8-8f9e-0ac2d067ea2f.png">

**Comment by cdanfon** [comment]
### Amend needed: 

- [ ]Hover state for the header to be thicker and black to match style guide as per Kristina's comment above

**Comment by cdanfon** [comment]
Steps for MoFo testing

1. Go to https://foundation.mofostaging.net/cms/pages/1769/add_subpage/
2. Create a new 'banner page'
3. Fill the 'title' field (this is compulsory and won't let you preview the page unless it's been filled out)
4. Add a 'listing' block in the body section (screenshot attached)
5. Check Acceptance criteria 2 & 3 (1 is part of the FE task)

NOTE: 
- To be tested alongside #9394 
- Hover state will be fixed as part of the FE work

**Comment by cdanfon** [comment]
**FE Amend needed:**

 - [ ] Hover state for the header to be thicker and black to match style guide as per Kristina's comment above
(moving ticket back to 'In progress column')

**Comment by cdanfon** [comment]
@stevedya Thanks! Moving forward, when there's a PR ready can you please let @tbrlpld know in the [slack](https://torchbox.slack.com/archives/C042N61EYTX) channel please?

**Comment by cdanfon** [comment]
@tbrlpld this is ready to deploy to staging please

**Comment by tbrlpld** [comment]
@cdanfon Deployed to staging now

**Comment by cdanfon** [comment]
@kristinashu Tagging you for reference

**Comment by cdanfon** [comment]
Hey @stevedya see above comment about the padding from Lisa: 

>the Figma page looks like it's divided into thirds (vertically) and the layout on staging looks like the card listing >takes up more than 2/3 of the page

**Comment by stevedya** [comment]
Hey @cdanfon I can adjust this today. It looks like we have it set to `3/4` for the left side and `1/4` for the right. So i'll update to be into thirds instead.

**Comment by stevedya** [comment]
I've now adjusted this as part of this PR https://github.com/mozilla/foundation.mozilla.org/pull/9538. 

This is now ready for you to look at @tbrlpld

**Comment by tbrlpld** [comment]
@stevedya Thanks for this. We are going to need some solution that is supported in Firefox.

**Comment by stevedya** [comment]
@tbrlpld No problemo, I've made some changes now, this is once again ready for review

**Comment by tbrlpld** [comment]
This is the same PR as #9432 and waiting for action.

**Comment by stevedya** [comment]
Hey @tbrlpld i've adjusted this PR as part of your feedback and its now ready for you to look at again 😄

**Comment by cdanfon** [comment]
Created #9602 to include URL field

**Comment by tbrlpld** [comment]
@cdanfon This is now on staging.

**Comment by cdanfon** [comment]
Looks good to me, over to you for testing @gutermul

**Comment by gutermul** [comment]
Looks great, signed off!

**Comment by cdanfon** [comment]
This is now on prod. Closing as completed
