### ISSUE TITLE
DFL 2022 | About - Profile card (individual profile)

### ISSUE THREAD

**Issue by kevinhowbrook** [mozilla/foundation.mozilla.org#9395]
### Describe the feature request
A new card needs to be defined for adding profiles, this should consist of:

- Profile snippet selector

### Screenshots / mock-ups
![Screenshot(3)](https://user-images.githubusercontent.com/2128707/191259738-94f17eeb-9662-46c1-a630-8a3f36f7f039.png)

### Additional context
Link to [designs](https://www.figma.com/file/goD9bRqPoedQAxi8OsInkR/Data-Futures-Lab%3A-Designs?node-id=626%3A9963)

---

**Dev Tasks:** 
* [ ] Create new profile card block consisting of image, name and bio fields
* [ ] Configure new text block template

**Acceptance Criteria:**
- [ ] Design to look as per Figma files
- [ ] As an editor creating a banner page I can add profile grid cards
- [ ] Template stacks vertically on mobile

**Comment by kristinashu** [comment]
Will this not pull info from our Profile snippet?

**Comment by cdanfon** [comment]
@tbrlpld Is there a particular reason why we're not going with a snippet selector? 

Thanks!

**Comment by tbrlpld** [comment]
@cdanfon I don't recall being part of the decision process here, maybe I am forgetting something though 😅 Seems like we could use a snippet chooser though.

**Comment by cdanfon** [comment]
Going ahead with a profile snippet selector

**Comment by kevinhowbrook** [comment]
This can be code reviewed here https://github.com/mozilla/foundation.mozilla.org/pull/9450

**Comment by tbrlpld** [comment]
@kevinhowbrook Looks good. I left a few questions regarding the template.

**Comment by cdanfon** [comment]
Hey @tbrlpld, 

Your questions have been addressed by @kevinhowbrook, can you double-check and move to _**Ready to deploy to staging**_ if it looks OK to you? Thanks

**Comment by tbrlpld** [comment]
@cdanfon @kevinhowbrook It does not look like the questions have been addressed yet. Maybe I am missing something.

**Comment by tbrlpld** [comment]
@cdanfon This is now on staging

**Comment by cdanfon** [comment]
Tested on https://foundation.mofostaging.net/ one deviation from the Figma design: 

### - The font of the profile text in the Figma and staging looks different: 

**FIGMA**: 
//styleName: Small/B2 - Body;
font-family: Nunito Sans;
_font-size: 16px;_
font-weight: 300;
line-height: 23px;
letter-spacing: 0em;
text-align: left;

**STAGING**: 
<img width="603" alt="Screenshot 2022-10-11 at 10 34 03" src="https://user-images.githubusercontent.com/102978346/195054332-92961baa-b6af-4c29-a23e-923666c6010a.png">

**Comment by cdanfon** [comment]
Steps for MoFo testing

NOTE: This will need to be tested alongside https://github.com/mozilla/foundation.mozilla.org/issues/9395 -  FE will be picked up next week by Steve, for now please test functionality 

Go to https://foundation.mofostaging.net/cms/pages/1769/add_subpage/

1. Create a new 'banner page'
2. Fill the 'title' field (this is compulsory and won't let you preview the page unless it's been filled out)
3. Add a 'profile' block in the body section (screenshot attached)
4. Check Acceptance criteria 2 & 3 (1 is part of the FE task)

**Comment by gutermul** [comment]
All good! the tw-body font-size is 18px rather than the 16px in the figma, but I imagine that's just to normalize with the rest of the mofo website. I sign off.

**Comment by cdanfon** [comment]
Hey @gutermul Thanks for that - the font size will be picked up by Steve as part of the FE work :)

**Comment by cdanfon** [comment]
Hey @kristinashu Could you confirm the size of the font on the profile text please?

The Figma file states 16px, but seems that we should be using 18px instead for consistency across the foundation website. 

Thanks!

**Comment by cdanfon** [comment]
This is now on prod. Closing as completed
