### ISSUE TITLE
DFL 2022 | Profile cards grid

### ISSUE THREAD

**Issue by kevinhowbrook** [mozilla/foundation.mozilla.org#9396]
### Describe the feature request
We'll need a card/block type to house the profile cards in a grid added in #9395

### Screenshots / mock-ups

![Screenshot(4)](https://user-images.githubusercontent.com/2128707/191264320-1eb64418-41b0-43bf-b5e3-6b4268674dc2.png)

### Additional context
Links to [design](https://www.figma.com/file/goD9bRqPoedQAxi8OsInkR/Data-Futures-Lab%3A-Designs?node-id=644%3A7618)

---

**Dev Tasks:** 
* [ ] Create new profile cards grid block to house individual profile cards
* [ ] Configure new text block template

**Acceptance Criteria:**
- [ ] Design to look as per Figma files
- [ ] As an editor creating a banner page I can add profile cards grid blocks
- [ ] Template stacks vertically on mobile

NOTE: This will need to be tested alongside #9395

**Comment by kevinhowbrook** [comment]
This can be code reviewed here https://github.com/mozilla/foundation.mozilla.org/pull/9450

**Comment by tbrlpld** [comment]
@cdanfon @kevinhowbrook This is the same PR, so I don't think the questions have been addressed yet.

**Comment by tbrlpld** [comment]
@cdanfon This is now on staging

**Comment by cdanfon** [comment]
Tested via #9395 LGTM, moving this one to ready for MoFo Staging but awaiting amends to be done to #9395

**Comment by cdanfon** [comment]
@kristinashu feel free to do a visual check

**Comment by kristinashu** [comment]
The grid looks good to me, thank you!

**Comment by cdanfon** [comment]
Steps for MoFo testing: 

1. Go to https://foundation.mofostaging.net/cms/pages/1769/add_subpage/
2. Create a new 'banner page'
3. Fill the 'title' field (this is compulsory and won't let you preview the page unless it's been filled out)
4. Add a 'profile' block in the body section (screenshot attached)
5. Check Acceptance criteria 


<img width="1196" alt="Screenshot 2022-10-19 at 16 49 17" src="https://user-images.githubusercontent.com/102978346/196741344-9199e324-c58f-46d2-8b4a-2361bf7689c6.png">

**Comment by gutermul** [comment]
I can add profiles that exist in the system, but I do not have permission to create or edit them- so my page currently looks like this: 
![grafik](https://user-images.githubusercontent.com/21171146/196942513-6328fb1d-e280-4060-9a8e-d96f40c2cab0.png)

**Comment by cdanfon** [comment]
Please note that in the ticket description there's a section for Acceptance Criteria, ideally if the 'acceptance criteria' it's been satisfied, the ticket would be marked as completed/signed off.

**Comment by gutermul** [comment]
Looks good. I sign off.

**Comment by cdanfon** [comment]
This is now on prod. Closing as completed
