### ISSUE TITLE
DFL 2022 | Events - Text only card

### ISSUE THREAD

**Issue by kevinhowbrook** [mozilla/foundation.mozilla.org#9398]
### Describe the feature request
We need a new `Text Only` card which will consist of:
- Heading (text) 
- Heading link (page chooser)
- Metadata (text)
- Text body (text)

### Screenshots / mock-ups
![Screenshot(6)](https://user-images.githubusercontent.com/2128707/191285748-db22a462-3b19-41ad-970b-0ddb0a466bf9.png)

### Additional context
Link to [designs](https://www.figma.com/file/goD9bRqPoedQAxi8OsInkR/Data-Futures-Lab%3A-Designs?node-id=644%3A7784)

---

**Dev Tasks:** 
* [ ] Create new text block consisting of title, link, metadata and text
* [ ] Configure new text block template

**Acceptance Criteria:**
- [ ] Design to look as per Figma files
- [ ] As an editor creating a banner page I can add text-only blocks
- [ ] Template stacks verticle on mobile

**Comment by cdanfon** [comment]
@kristinashu Can you confirm if this component should have blue or black as the colour for the title please? Thanks!

**Comment by kristinashu** [comment]
They should be black in order to align with [our style guide.](https://foundation.mozilla.org/en/style-guide/)

**Comment by kevinhowbrook** [comment]
This is ready for staging https://github.com/mozilla/foundation.mozilla.org/pull/9511

**Comment by kevinhowbrook** [comment]
Actually hold off on this. It's blocked by https://github.com/mozilla/foundation.mozilla.org/pull/9456 while the FE is done as it's based off that branch

**Comment by cdanfon** [comment]
Moving this back to the sprint backlog for Steve to pick up

**Comment by kevinhowbrook** [comment]
No this doesn't need front end work - it's just blocked by a PR that does

**Comment by kevinhowbrook** [comment]
This has been rebased and is ready to deploy to staging https://github.com/mozilla/foundation.mozilla.org/pull/9511

**Comment by cdanfon** [comment]
Hey @tbrlpld another one for you please :)

**Comment by cdanfon** [comment]
Hey @stevedya a couple of things:

- Underline should be black as per style [guide](https://foundation.mozilla.org/en/style-guide/#headers-links)
- Paragraph text to be grey as per style [guide](https://foundation.mozilla.org/en/style-guide/#paragraphs)

**Comment by tbrlpld** [comment]
Two small question for me @stevedya

**Comment by stevedya** [comment]
@tbrlpld I've replied and will pass these back to you now

**Comment by tbrlpld** [comment]
@cdanfon This is ready for testing on staging

**Comment by cdanfon** [comment]
Looks good to me thanks, @gutermul over to you for MoFo testing

**Comment by gutermul** [comment]
Looks good to me. The only thing I noticed was that the date was not forced all caps like in the figma, but from my perspective the flexibility is better. Attached is the Events page I recreated, for reference.



![Image](https://user-images.githubusercontent.com/21171146/198994098-d1d4b382-2d32-46df-bcc3-f3c845df9238.png)

**Comment by cdanfon** [comment]
Created #9601 to include URL field

**Comment by cdanfon** [comment]
This is now on prod. Closing as completed
