### ISSUE TITLE
Increase max line length allowed by flake8 to 120

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#940]
It's 2017, and we should be able to have lines longer than 80 characters (that rule isn't there for readability, but to ensure people with only 80 column text displays could edit your files).

I'm not entirely sure how to set it up, but there's gotta be documentation somewhere.

**Comment by medlin01GA** [comment]
Amed to that, the 80 character limit is an anachronism and forces you to write worse code in many situations.
