### ISSUE TITLE
DFL 2022 | Resources - Image teaser

### ISSUE THREAD

**Issue by kevinhowbrook** [mozilla/foundation.mozilla.org#9400]
### Describe the feature request
New block consisting of the following:
- Image (image chooser)
- Heading (text)
- Link (URL)
- Link title (for button rendering)
- Body (text)

### Screenshots / mock-ups
![Screenshot(8)](https://user-images.githubusercontent.com/2128707/191289718-04351b12-3e9f-4170-8fe7-0201f7332636.png)

### Additional context
Link to [designs](https://www.figma.com/file/goD9bRqPoedQAxi8OsInkR/Data-Futures-Lab%3A-Designs?node-id=644%3A7950)

---

**Dev Tasks:** 
* [ ] Create new image teaser block with image, heading, link and body fields
* [ ] Configure image teaser block template

**Acceptance Criteria:**
- [ ] Design to look as per Figma files
- [ ] As an editor creating a banner page I can add image teaser blocks
- [ ] Template stacks verticle on mobile

**Comment by kevinhowbrook** [comment]
@kristinashu I've updated this to support a URL link rendered as a button to match the re-use in https://github.com/mozilla/foundation.mozilla.org/issues/9504#issuecomment-1284292410

**Comment by kevinhowbrook** [comment]
@cdanfon and @stevedya this is ready for some FE attention with the stacking https://github.com/mozilla/foundation.mozilla.org/pull/9519

I've left it in draft until the FE is complete so tibor can review the whole thing

**Comment by stevedya** [comment]
@cdanfon @kevinhowbrook I've made the necessary front end changes to that PR now. I'll assign this to Kev for now to get reviewed once he's addressed the branches this is based off of.

**Comment by cdanfon** [comment]
Moving this to 'Code review' but is blocked by MR- 9398 text teaser

**Comment by stevedya** [comment]
Hey @tbrlpld since this is only blocked for merging right now only because of the merge order of the branches. Could we get this reviewed in the meantime. It's ready for a look here: #9519

**Comment by tbrlpld** [comment]
Already on my list @stevedya

**Comment by kevinhowbrook** [comment]
I've rebased this and cherry-picked the work back in

**Comment by stevedya** [comment]
@tbrlpld I've just pushed up some adjustments based on your questions. It's ready for another look now 🙂

**Comment by tbrlpld** [comment]
@stevedya One more micro suggestion

**Comment by tbrlpld** [comment]
@cdanfon Ready for testing on staging

**Comment by stevedya** [comment]
No problem, this is resolved now 😄

**Comment by tbrlpld** [comment]
Sorry, I don't follow. I think I already reviewed no?

**Comment by cdanfon** [comment]
Looks good to me, over to you @gutermul for testing

**Comment by gutermul** [comment]
Looks great. Signed off. Attached screenshot of the whole page I built to check all tickets related to this page.



![Image](https://user-images.githubusercontent.com/21171146/198824263-cbfccabd-6e48-4599-8ccd-6a97c9deac26.png)

**Comment by cdanfon** [comment]
This is now on prod. Closing as completed
