### ISSUE TITLE
DFL 2022 | Projects - Card list block

### ISSUE THREAD

**Issue by kevinhowbrook** [mozilla/foundation.mozilla.org#9403]
### Describe the feature request
Similar to card listing (from landing page). This could just be an option on the card listing to use horizontal cards and stack them.. (to include title eg 2022 cohort)

### Screenshots / mock-ups

![Screenshot(11)](https://user-images.githubusercontent.com/2128707/191305061-b6e4b4ef-7b31-4452-87d7-badaed4ec381.png)

### Additional context
Link to [designs](https://www.figma.com/file/goD9bRqPoedQAxi8OsInkR/Data-Futures-Lab%3A-Designs?node-id=644%3A8116)

---

**Dev Tasks:** 
* [ ] Create new card list block allowing editors to add a title (e.g 2022 cohort) and up to 4 cards
* [ ] Configure card list block template

**Acceptance Criteria:**
- [ ] Design to look as per Figma files
- [x] As an editor creating a banner page I can add up to 4 horizontal cards consisting of an image, metadata, heading, link, and body text and to include a block title text
- [x] Template stacks verticle on mobile

**Comment by kevinhowbrook** [comment]
This needs some FE attention for stacking on smaller screens https://github.com/mozilla/foundation.mozilla.org/pull/9539

**Comment by stevedya** [comment]
Hey @tbrlpld this one is now ready for review at #9539

**Comment by tbrlpld** [comment]
@stevedya Left some small questions on the PR

**Comment by stevedya** [comment]
@kevinhowbrook Just updating this ticket quick, that those questions @tbrlpld had were resolved and this can be added to the merging chain.

**Comment by tbrlpld** [comment]
@cdanfon Ready for testing on staging

**Comment by cdanfon** [comment]
Hey @stevedya looks good to me except for tablet, see attached
<img width="790" alt="Screenshot 2022-10-28 at 09 30 18" src="https://user-images.githubusercontent.com/102978346/198542149-a11d7b71-15ce-42eb-ad2d-2425070014c4.png">

**Comment by cdanfon** [comment]
@gutermul Over to you for testing, the card padding on tablet needs to be amended, but this ticket it for the cards as a block element.

**Comment by gutermul** [comment]
Small thing: I think the title should be H3 instead of H2. See attached page recreation and compare with figma.



![Image](https://user-images.githubusercontent.com/21171146/199001335-47347c2b-bb5f-41df-b750-4bf958d76d28.png)

**Comment by cdanfon** [comment]
You're right @gutermul thanks for raising

@stevedya can you please address the above? 

2022 COHORT should be using a H3 instead

**Comment by tbrlpld** [comment]
@cdanfon I believe I requested this change in code review, because we have no way (at the moment) to check if an `h2` has been used before this block. That could lead to in valid / non-semantic ordering of the headings. If you are only talking about the styling, that could be addressed without changing the semantics.

**Comment by cdanfon** [comment]
hey @tbrlpld yes, I'm talking about the styling here - @stevedya please note this is not a semantic change, only a visual one

**Comment by cdanfon** [comment]
@stevedya this is only a style change, no need to change the semantic

**Comment by stevedya** [comment]
Hey @tbrlpld I've posted a PR for this fix here: #9590 thats ready for review.

**Comment by tbrlpld** [comment]
@cdanfon This is ready for testing on staging.

**Comment by cdanfon** [comment]
Checked and looks good to me, over to @gutermul for MoFo testing please

**Comment by gutermul** [comment]
great! signed off

**Comment by cdanfon** [comment]
This is now on prod. Closing as completed
