### ISSUE TITLE
DFL 2022 | Projects Card

### ISSUE THREAD

**Issue by kevinhowbrook** [mozilla/foundation.mozilla.org#9404]
### Describe the feature request
Add option for the horizontal layout of the card to the template, the card listing block should pass in the flag to the individual card template that controls if laid out vertically or horizontally. 

### Screenshots / mock-ups
![Screenshot(12)](https://user-images.githubusercontent.com/2128707/191306845-618447cc-58fe-4b3d-a1bf-61e5cbb8ce34.png)

### Additional context
Link to [designs](https://www.figma.com/file/goD9bRqPoedQAxi8OsInkR/Data-Futures-Lab%3A-Designs?node-id=644%3A8116)

Metadata displayed above the title, similar again to the cards in the blog set: https://foundation.mofostaging.net/en/docs/how-do-i-wagtail/streamfield-blocks/#blog-set

Dev Tasks: 
* [ ] Create new card block with tex, image fields and link field
* [ ] Configure card template with horizontal layout (stacks on mobile)

Acceptance Criteria:
- [ ] Design to look as per Figma files
- [ ] As an editor creating a banner page I can add horizontal cards consisting of an image, metadata, heading, link, and body text
- [ ] Template stacks verticle on mobile

NOTE: To be tested with #9403

**Comment by kevinhowbrook** [comment]
This needs some FE attention for stacking on smaller screens https://github.com/mozilla/foundation.mozilla.org/pull/9539

**Comment by stevedya** [comment]
Fixed!

**Comment by tbrlpld** [comment]
@cdanfon Ready for testing on staging

**Comment by cdanfon** [comment]
As per comment on #9403 the padding on tablet needs to be fixed

**Comment by stevedya** [comment]
Hey @tbrlpld i've added a super small PR to fix this one here: https://github.com/mozilla/foundation.mozilla.org/pull/9572 and its now ready for review

**Comment by tbrlpld** [comment]
@cdanfon This is ready for testing on staging.

**Comment by cdanfon** [comment]
Thanks! Looks good to me, @gutermul over to you for MoFo testing

**Comment by gutermul** [comment]
Looks great! Signed off from my end.

**Comment by cdanfon** [comment]
This is now in production
