### ISSUE TITLE
Youtube Regrets 2022 timeline section is clipping into section header

### ISSUE THREAD

**Issue by mtdenton** [mozilla/foundation.mozilla.org#9410]
### Describe the bug

Present on the Youtube Regrets 2022 User Controls page:
https://foundation.mozilla.org/en/youtube/user-controls/

On various viewport sizes, the timeline section's parallax effect intersects with the header above that reads "Bad recommendations resurfaced over time". Example, iPhone 12/13 preset viewport in Firefox:

### To Reproduce
1. Go down to beginning of section on small and medium sized devices
2. Scroll/swipe downwards to activate parallax effect

### Expected behavior
The timeline section should avoid intersecting with the header, this might be done by calculating padding based on the timeline's position in the viewport but that's just a spitball idea

### Screenshots
<img width="1009" alt="Screen Shot 2022-09-21 at 9 24 45 AM" src="https://user-images.githubusercontent.com/41487159/191530940-8e3fc3ee-0a9b-45a2-8866-f09474bf70f3.png">

**Comment by kristinashu** [comment]
Closing this as Won't Fix
