### ISSUE TITLE
[PNI] - Can’t sync translations when the homepage has a Hero featured article 

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#9415]
Not sure if it’s too early to flag this, but setting a Hero featured article on the new PNI homepage fails when syncing with translated pages:

<img width="1306" alt="Capture d’écran 2022-09-22 à 17 17 02" src="https://user-images.githubusercontent.com/1294206/191786446-4622f5e7-5cfe-456d-b25d-4b82af357d19.png">

<img width="631" alt="Capture d’écran 2022-09-22 à 17 26 19" src="https://user-images.githubusercontent.com/1294206/191788930-48e87cb3-e1bf-4cc8-9239-ab656d6f0287.png">

With the prod DB, I’ve created a Buyer’s Guide article page named "Test PNI article page", added it to the English homepage, then hit "Sync translated pages", and it fails with the error below

`Cannot assign "<Page: Test PNI article page>": "BuyersGuidePage.hero_featured_article" must be a "BuyersGuideArticlePage" instance.`

**Comment by TheoChevalier** [comment]
Synced is good here too, I will translate the featured article on a case-by-case basis

**Comment by tbrlpld** [comment]
Pulling this into the sprint because of the high priority.

**Comment by tbrlpld** [comment]
Seems this is a known issue in `wagtail-localize`: https://github.com/wagtail/wagtail-localize/issues/430

Might be solved in a future release. For now we will need a work around.

**Comment by tbrlpld** [comment]
This is ready for testing on staging @TheoChevalier @cdanfon 


To test that the synchronization works:
1. Login to the admin
2. Navigate to the edit view of the **french** version of the buyer's guide homepage. 
3. Click the "translate this page" button.
4. Check the "french" locale tickbox and click the "submit" button.
1. Open the **french** version of the buyer's guide homepage: http://localhost:8000/fr/privacynotincluded/
4. See the titles of the different featured articles (hero, hero supporting, advice, popular)
5. Navigate to the edit view of the **english** version of the buyer's guide homepage. 
6. Pick different pages for the related links and publish the **english** page.
7. Synchronize the buyer's guide homepage translation (in the tree view click the "more" button)  <img width="200" alt="Screen Shot 2022-11-04 at 17 01 56" src="https://user-images.githubusercontent.com/24797493/200091345-eeda29b7-f8da-44b9-9ca9-ce0d7af684aa.png">7. 
8. Synchronize and publish the translations.8. 
9. Reload the **french** version of the buyer's guide homepage: http://localhost:8000/fr/privacynotincluded/
10. Observe that the featured articles should be updated according to the changes you have made.

Test that the localization works: 
1. Open the translated version of the buyer's guide homepage: http://localhost:8000/fr/privacynotincluded/
2. Follow the related articles links and notice that the active locale is still the translated one (you can notice this in the URL -- if you started with `http://localhost:8000/fr/privacynotincluded/` you should still see the `fr/` bit in the URL.

**Comment by kristinashu** [comment]
Sorry, I'm not familiar with this ticket but the fix should be live now. @TheoChevalier please confirm and then close this ticket, thank you!

**Comment by TheoChevalier** [comment]
Confirming this bug is now fixed, thanks everyone!
