### ISSUE TITLE
DFL 2022 | Aside block for card listing (all cards)

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9432]
Ticket for the creation of the aside block for https://github.com/mozilla/foundation.mozilla.org/issues/9394

### Describe the feature request

In #9393 a new block was introduced, on the designs, there is also an 'aside block'. This block is out of the flow of the main body content and sits in the right sidebar.

For this aside block we will need to do the following:

- Create a new 'aside' block consisting of title and text (link button block already exists)
- Create a new 'Aside' field on the Banner Page type where blocks can be added. (just the new block and the button link block)
- Configre the template so IF the new aside field is populated with blocks, the template is slimmer and the aside field shows on the right on desktop view and stacks at the TOP on mobile (shown in the screenshot s the purple outlined area). 

### Screenshots / mock-ups

![Image](https://user-images.githubusercontent.com/2128707/192495492-da8a985d-66ee-4874-bab7-eafe7fa89cf3.png)

### Additional context
Link to [designs](https://www.figma.com/file/goD9bRqPoedQAxi8OsInkR/Data-Futures-Lab%3A-Designs?node-id=626%3A9963)

---

**Dev Tasks:** 
* [ ] Create new aside block
* [ ] Configure new field for aside content
* [ ] Configure template logic for new aside area

**Acceptance Criteria:**
- [ ] Design to look as per Figma files
- [x] As an editor creating a banner page I can add link and text blocks to the aside area
- [x] If an aside block is not added, the template layout is full width

**Comment by cdanfon** [comment]
After discussing in stand up this is ready to be picked up

**Comment by kevinhowbrook** [comment]
Lisa to check if we can float the aside block to the top of the sidebar so we can re-work this to support mutiples

**Comment by kevinhowbrook** [comment]
I've re-worked the PR for this https://github.com/mozilla/foundation.mozilla.org/pull/9437
FE attention is needed because I can't fix whats going on with the link block in the aside area.

**Comment by tbrlpld** [comment]
@kevinhowbrook Left some small questions.

**Comment by tbrlpld** [comment]
@cdanfon This is now on staging

**Comment by cdanfon** [comment]
Hey @kevinhowbrook tested on stage, a couple of things on this one, although looks like Simon Evans will be picking this on up:

1) The aside section doesn't quite level as per design (don't know if this is a dev constrain)
2) The aside button in the design is left aligned, whilst in the staging site is centred 


See attached 
<img width="1294" alt="Screenshot 2022-10-10 at 18 27 27" src="https://user-images.githubusercontent.com/102978346/194922347-417592bf-ccdc-4b49-9cb0-06efc34fe144.png">
<img width="823" alt="Screenshot 2022-10-10 at 18 29 24" src="https://user-images.githubusercontent.com/102978346/194922407-8d8f2629-3cc3-4090-afc0-210a657c36d9.png">

**Comment by kevinhowbrook** [comment]
@cdanfon Those remaining issues are FE

**Comment by stevedya** [comment]
I've adjusted this as part of this PR https://github.com/mozilla/foundation.mozilla.org/pull/9538 

This is now ready to review @tbrlpld

**Comment by tbrlpld** [comment]
@stevedya Thanks for this. We are going to need some solution that is supported in Firefox.

**Comment by stevedya** [comment]
@tbrlpld I've made some changes now. This is once again ready for review

**Comment by tbrlpld** [comment]
@stevedya Thanks for these changes. I think there might be some question about what the desired functionality is here: https://github.com/mozilla/foundation.mozilla.org/pull/9538#pullrequestreview-1160812230

**Comment by tbrlpld** [comment]
@cdanfon It might be worth for you or @gutermul to take a look at the linked review comment. There is an open question about the desired functionality.

**Comment by cdanfon** [comment]
Hey @tbrlpld I posted a comment on the linked review - I'd suggest pushing to staging and checking for Kristina's opinion

**Comment by tbrlpld** [comment]
@cdanfon @stevedya There seems to be an unintended change to the body width that is caused by this PR. See  https://percy.io/Mozilla-Foundation/foundation.mozilla.org/builds/22591214/changed/1259054366?browser=chrome&browser_ids=30%2C31&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280

**Comment by cdanfon** [comment]
@stevedya @tbrlpld what's the latest on this ticket please? Did those unintended changes get fixed?

**Comment by stevedya** [comment]
@cdanfon Yep! These were fixed yesterday and I had pinged @tbrlpld on the PR already 👍

**Comment by tbrlpld** [comment]
@cdanfon This is now on staging.

**Comment by cdanfon** [comment]
Looks good to me, @gutermul over to you for testing. Please note that this block has changed names - is called 'block with aside' now

**Comment by gutermul** [comment]
Got it. Works well, but will definitely require good documentation once it goes into the "How-to Wagtail" guide. Screenshot fwiw:

![Image](https://user-images.githubusercontent.com/21171146/199723081-96155c34-0f61-4d0f-a02f-110169818de3.png)

**Comment by gutermul** [comment]
The only outstanding thing, which I'll discuss with @cdanfon and champika, is whether given how this has ended up, on mopbile I think the stacking of the aside might make more sense below the "block with aside" content, mainly because otherwise there's no good way to label the section given that the title needs to be part of a paragraph above and is not part of the "block with aside" component.


![Image](https://user-images.githubusercontent.com/21171146/199725112-af5328bb-19f3-4eeb-a1ce-97637b007859.png)

**Comment by gutermul** [comment]
Confirming that we'd like the aside to go below the "block with aside" in the mobile view. I confirmed with Champika.

**Comment by cdanfon** [comment]
Hey @stevedya please see above comment from Lisa, can place the aside block underneath the 'block with aside' please? So basically it would stack here (see red rectangle):

<img width="170" alt="Screenshot 2022-11-03 at 16 49 03" src="https://user-images.githubusercontent.com/102978346/199783850-a0d85891-c3e8-4d86-9dc8-94224ba0e463.png">

**Comment by stevedya** [comment]
Hey @tbrlpld i've posted a PR to fix this remaining issue here: #9618 and its now ready for your review :)

**Comment by tbrlpld** [comment]
@cdanfon This is now ready for test on staging.

**Comment by gutermul** [comment]
super! signed off. thanks

**Comment by cdanfon** [comment]
This is now on prod. Closing as completed
