### ISSUE TITLE
Personas draft: post All Hands feedback (staff) 

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#945]
**Context:**
After All Hands, Matthew sent an email to staff to asynchronously capture feedback related to personas in a doc (deadline - Jan 19, 2018). We will also have a meeting to capture feedback in real time. This issue is to track this stage.

- [PDF](https://drive.google.com/file/d/1hboEuUQCdyOSvaN-ejroBNLvoPJaFoJN/view?usp=sharing) with all personas
- [Feedback doc](https://docs.google.com/document/d/1iZKUbpEnrdT7TTjjv-yF61FvNTv9dZzGEU5rIGmjsws/edit?usp=sharing)

cc: @jessevondoom @xmatthewx

**Comment by kristinashu** [comment]
Assigning to @beccaklam to review (along with https://github.com/mozilla/foundation.mozilla.org/issues/566) then close and open a new summary ticket in the [Design repo](https://github.com/MozillaFoundation/Design/issues).

**Comment by beccaklam** [comment]
Closing this ticket for now. New summary ticket [here](https://github.com/MozillaFoundation/Design/issues/307).
