### ISSUE TITLE
Scrolljacking on "Does this button work?" article

### ISSUE THREAD

**Issue by yoasif** [mozilla/foundation.mozilla.org#9454]
## Description

There is a fake scrollbar on https://foundation.mozilla.org/en/youtube/user-controls/ that messes with normal scroll behavior. 

### Steps to reproduce

1. Navigate to https://foundation.mozilla.org/en/youtube/user-controls/
2. Scroll with touchpad or look for scrollbar

### Expected result

Normal scrolling, I should see a scrollbar. 

### Actual result

Scrolling is weird - doesn't follow normal Firefox scroll behavior. Also, the scrollbar is not present, but a fake one appears instead. 

### Environment

Firefox Nightly on Linux.

**Comment by tbrlpld** [comment]
@yoasif This is unfortunately necessary for the scroll animation at the bottom of the page.
