### ISSUE TITLE
Youtube User Controls Petition - Post-submit CTA buttons not working

### ISSUE THREAD

**Issue by mtdenton** [mozilla/foundation.mozilla.org#9457]
### Describe the bug

https://foundation.mozilla.org/en/campaigns/youtube-user-controls/

On the Youtube User Controls Petition page, a couple of the buttons that appear after the petition is signed are not working. Debated on splitting this into two issues but I'm betting they're very closely related.

The "Twitter" button just opens a small popup of this same page, it does not go to Twitter.

The "Email" button doesn't do anything at all.

### To Reproduce
1. Go to https://foundation.mozilla.org/en/campaigns/youtube-user-controls/
2. Submit the petition form.
3. Choose the "No" option at the bottom of the lightbox
4. Click on "Twitter" and "Email" buttons as shown in the image below.

### Expected behavior
The Twitter button should open a window that tweets the petition page. If this is unclear then we need to talk about it and grab details from the stakeholders.

The Email button should be an a tag with mailto, subject, and body. If this hasn't been provided by the stakeholders then we should reach out about this as well.

### Screenshots
<img width="1425" alt="Screen Shot 2022-10-04 at 12 24 35 PM" src="https://user-images.githubusercontent.com/41487159/193887318-a70a4321-c517-406b-84d0-13613a22492e.png">

**Comment by danielfmiranda** [comment]
Hi Everyone, it turns out that this error was being caused by one of the "share_..." fields missing a 0, once I updated that field, all the buttons work! Going to mark this as resolved
