### ISSUE TITLE
Upgrade Django to 3.2.16 

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#9459]
A security patch for Django was released fixing a critical issue on sites that use the translation framework. 

See also: https://www.djangoproject.com/weblog/2022/oct/04/security-releases/

**Comment by tbrlpld** [comment]
@cdanfon I don't think we can to more than a general functionality test here too. 

@TheoChevalier Also tagging you for QA because the fix is around localized URLs.

**Comment by cdanfon** [comment]
Unless @TheoChevalier has spotted anything that affects localized URLs I'm happy to mark this as complete.

**Comment by TheoChevalier** [comment]
Just tested this locally, and can confirm I haven’t found issues with language negotiation 👍
