### ISSUE TITLE
Hero title should fit on 2 lines in FF

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#946]
At medium width (e.g. 1000px), the hero title is on 3 lines when it should fit on 2. When the title is on 3 lines it pushes the rest of the content further down the page than needed. It does however look good in Chrome at the same width. 

FF top and Chrome bottom:
<img width="1049" alt="screen shot 2018-01-12 at 11 12 22 am" src="https://user-images.githubusercontent.com/1068783/34891225-9e07449c-f789-11e7-99f5-1c828b5e9b4e.png">

**Comment by gvn** [comment]
There's no guarantee that live text will render consistently in all environments. Users can change the size within their browser. We can tweak it, but it'll never render consistently 100% of the time.

**Comment by kristinashu** [comment]
This seems to have fixed itself!
