### ISSUE TITLE
Datawrapper is cut off on mobile

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#9466]
### Describe the bug

The datawrapper embed component is not showing all of the data on mobile screen sizes:

<img src="https://user-images.githubusercontent.com/18314510/194450036-9861e263-7ef0-44d8-9a8c-6a88b41f727d.png" width="250px"/>

### To Reproduce
How to reproduce:
1. View the production url at a narrow width
2. See bottom of table cut off on mobile
OR
1. Go to staging url https://foundation.mofostaging.net/en/research/library/user-controls/report/nothing-changed-a-qualitative-analysis-of-youtubes-user-controls/ (this has "mobile fallback" unchecked in datawrapper)
2. Table is not cut off on mobile but there is a large white space below the table at wider widths

### Expected behavior
The datawrapper component should be responsive.

**Comment by tbrlpld** [comment]
@cdanfon This is now on staging.

**Comment by cdanfon** [comment]
@danielfmiranda @tbrlpld 

Checked on staging, looks good to me - moving this to 'Ready for prod'
