### ISSUE TITLE
Smoother page load

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#947]
While a page is loading, the content jumps down. This makes the page look broken at times and is very jarring when it actually does finish loading. Seems like most sites now don't do this. Can we fix this so it is a smother experience for users?

<img width="1180" alt="screen shot 2018-01-12 at 11 44 08 am" src="https://user-images.githubusercontent.com/1068783/34892426-18fb243a-f78e-11e7-8134-ca29d005e282.png">

**Comment by gvn** [comment]
There's some measurement that has to occur via JS to properly align everything (our nav is fairly complex), so I don't think there's anything to prevent the jump unfortunately.

**Comment by kristinashu** [comment]
Even for the Member Spotlight content? I.e. have the footer lower down so it's out of view.

**Comment by gvn** [comment]
That content is brought in via XHR, and we don't know how much vertical space it will take up ahead of time.

We can optimize the XHR through caching to make the load snappier though...

**Comment by kristinashu** [comment]
What about setting a minimum height of say 1000px? Content will end up being more but doesn't matter to the user since at that point, it will be out of view anyways. 

E.g. [Thimble projects](https://thimble.mozilla.org/en-US/) seem to load nice and smoothly even though they are still loading.

**Comment by kristinashu** [comment]
This page doesn't exist anymore and Lucy's cloudinary work should help with this.
