### ISSUE TITLE
Topic blog index broken for non-default locales

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#9487]
Originally submitted by @TheoChevalier 

*** 

Looks like a recent code change broke the localized topic pages in all locales, except English.

I’ve had a quick look at recent changes, and think I’ve found what is causing it.
Reverting this commit locally fixes the issue: https://github.com/mozilla/foundation.mozilla.org/commit/d6e923a48a0863488381d0b28d518495a8182aae

Related PR: https://github.com/mozilla/foundation.mozilla.org/pull/9455

**Comment by tbrlpld** [comment]
@TheoChevalier @cdanfon This is ready for QA on staging now: https://foundation.mofostaging.net/fr/blog/topic/advocacy/

**Comment by cdanfon** [comment]
Hey @tbrlpld tested on staging and looks good to me, unless @TheoChevalier disagrees we can move this to 'Ready for production'.

**Comment by TheoChevalier** [comment]
Thanks @tbrlpld for the quick fix, looks good to me as well!
