### ISSUE TITLE
[PNI] Content index does not save "load more" pagination state

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#9491]
# Description

The PNI editorial content index page does not save the pagination state when navigation with the "load more" botton. 
This means when the page is refreshed it page starts only displaying the first page. 

This can lead to navigation issues for users. If for some reason (storage full, etc.) the pages are not cached properly, navigating back to the index might show a different state than the user left. E.g. navigating from the index (after clicking the "load more" button) to an article and back to the index would show only the first page of the index again. 

To avoid this, we should save the state of the pagination with the "load more" button. 

# Dev notes

* Updating the history and URL is possible with [`hx-push-state`](https://htmx.org/attributes/hx-push-url/). 
* We need to avoid this functionality from colliding with the "non-JS" pagination that is first loaded and only replaced with the "load more" functionality. E.g. when directly navigating to the index with `?page=2` it should still show only the second page of articles. We should be able to use a second query parameter, e.g. `expanded`, to signal that we should render all articles from all pages from the first to the requested one. E.g. `?page=2&expanded` shows all articles form the first page and all articles from the second page. The "non-JS" pagination would still go to a normal `?page=3` which would only show the articles of the third page. The "load more" button should add the articles from the thrid page to the current index (and update the active URL accordingly). 

# Acceptance criteria

- [x] As a user, when I visit the content index page, click the "load more" button I can see the URL now includes the page and expansion query parameters (`?page=2&expanded`).
- [x] As a user, when I visit the content index page, click the "load more" button and refresh the page, I find the index page in the same state (shows all the loaded articles) as before the refresh.

**Comment by kristinashu** [comment]
This is working very nicely! Ready for prod!
