### ISSUE TITLE
Build fellowships homepage template

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#950]
Build a static homepage based on the wireframes at https://projects.invisionapp.com/share/UQF78CYKM#/screens/271941410_It-4-Overview.

UI design to come, but this should be enough for a start of a scaffolding. No carousel.

**Comment by mmmavis** [comment]
I guess this is a good ticket to start. Assigning it to myself. 

@alanmoo is `/network-api/networkapi/fellows/templates/fellows_home.html` where I'm supposed to add the majority of HTML/template code to?

**Comment by alanmoo** [comment]
Yup!

**Comment by mmmavis** [comment]
Done and merged into `fellowships` branch.
