### ISSUE TITLE
Donate Stack - reset minimum recurring gift donation amount

### ISSUE THREAD

**Issue by anilkanji** [mozilla/foundation.mozilla.org#9505]
### Describe the feature request
Change the new minimum **monthly** gift amount on donate forms from £10 / $10 / €10 to £5 / $5 / €5

Change the text under the "one time" box to:

> To combat fraud, Mozilla Foundation has temporarily restricted one-time donations to a minimum of XXX

### Screenshots / mock-ups
<img width="822" alt="Screenshot 2022-11-08 at 15 02 06" src="https://user-images.githubusercontent.com/102978346/200599363-74bc462b-8a64-455a-93b5-b6619e1e66e3.png">

### Additional context
Note this is only for the 'monthly' gift amount. The 'one time' donation is to stay the same.

**Comment by cdanfon** [comment]
Needs to be moved to the donate repo, I can't seem to be able to move it

**Comment by cdanfon** [comment]
@mtdenton this is ready to be picked up in the next sprint. Adding it to the queue by assigning it the next sprint label 'Sprint: Nov 21 - Dec 4, 2022'

**Comment by tbrlpld** [comment]
This can not be moved, because the donate repo is in a different Org now.

**Comment by tbrlpld** [comment]
@anilkanji Does this change affect how the "other" minimum should be handled? Currently this value is the same for one-time and monthly (at 10). Can the "other" minimum be changed to 5 in both cases or do we need to split the logic and have 10 for one-time and 5 for monthly?

**Comment by mtdenton** [comment]
@tbrlpld I'm reaching out to Kevin as well for info here.

**Comment by mtdenton** [comment]
@tbrlpld via Kevin:

> I think we want to keep it the same, so $5 monthly, $10 one-time if possible.

I also updated the issue with the desired text changes

**Comment by tbrlpld** [comment]
@mtdenton If I understand correctly, we want a $5 minimum amount for the "other" option and text when monthly, but $10 minimum amount for the "other" option and text when one-time?

**Comment by tbrlpld** [comment]
Nudge @mtdenton

**Comment by cdanfon** [comment]
Hey @tbrlpld 

 _**Monthly**_ should be 5 minimum. This needs to change in 2 places see below: 

<img width="822" alt="monthly" src="https://user-images.githubusercontent.com/102978346/205636586-a45c8557-24f6-4d0d-af6d-f55436cd7019.png">

**_One time_** should be 10 minimum. No need to change anything here I believe: 


<img width="1395" alt="Screenshot 2022-12-05 at 12 19 47" src="https://user-images.githubusercontent.com/102978346/205636010-de696b0b-06e6-41e3-bc9d-e1a3805a057d.png">

**Comment by tbrlpld** [comment]
Thanks for the clarification @cdanfon. 

In that case, I think the estimate needs to be changed from 1 to 4. Currently there is only a single "minimum" amount (the one that creates the message under the "other" field) that is independent from the "presets" (which are used to create the buttons with the predefined amounts).

**Comment by tbrlpld** [comment]
@anilkanji @mtdenton This is ready for testing on staging now

**Comment by tbrlpld** [comment]
@mtdenton Pinging to get this QA'ed for deployment before code freeze

**Comment by danielfmiranda** [comment]
@tbrlpld just gave this a test, can confirm that the donation amounts are what they should be for the specified currencies, other currencies look as expected as well. Minimum amount validation is also working.

Ready for prod!
