### ISSUE TITLE
Build "fellowship type" template

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#951]
Based on https://projects.invisionapp.com/share/UQF78CYKM#/screens/271941399, build a static page with this structure. The content is less important than the structure, as we'll be using template tags to swap out the body text.

**Comment by mmmavis** [comment]
@taisdesouzalessa is https://projects.invisionapp.com/share/ZJ9YTAGEA#/screens/273603674 the WIP comps for this page type?

**Comment by taisdesouzalessa** [comment]
@mmmavis nope, this is the comp:
https://invis.io/ZJ9YTAGEA#/273312988_FellowshipsUI_-_Specific_Fellowship_Page

Also, for Open Web page, the only one who has host orgs), this is the model: 
https://invis.io/ZJ9YTAGEA#/273843963_FellowshipsUI_-_Specific_Fellowship_Page_With_Host_Orgs

**Comment by mmmavis** [comment]
Merged into `fellowships` branch!
