### ISSUE TITLE
[PNI] Add articles to production

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9512]
We will need to add articles to the site as soon as the site is pushed to prod.

### Steps
- Go to [this spreadsheet](https://docs.google.com/spreadsheets/d/1uHfnTP7cyU85qfh8AY8Nk7kuHIcPYjNBnw0aSpfLpvs/edit#gid=0)
- Add your name to as many articles as you can
- Add the articles
- Update the status in the spreadsheet

**Comment by nancyt1** [comment]
Looks like all the articles from the spreadsheet have been added!

**Comment by kristinashu** [comment]
Thank you so much Nancy & Becca! Sorry I wasn't able to help with this.
