### ISSUE TITLE
[PNI] Pre-launch QA

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9513]
Timeline:
- Nov 1: All dev tickets done
- Nov 2: QA on staging
- Nov 3: Push to prod
- Nov 4: End of “sprint 2”
- Small tweaks and fixes in “sprint 3”

### Design to QA
- [x] Staging

**Comment by beccaklam** [comment]
Using this [spreadsheet](https://docs.google.com/spreadsheets/d/1TYnQFGOZLSJrHGHvnLhJwBaZUcAyOmTbHNcu65WUv_4/edit?usp=sharing) to track what I've QA-ed.
