### ISSUE TITLE
YouTube Regrets Retro Prep

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9514]
Prepare materials for YouTube Regrets Retro:
- [x] Gather deliverables that we made

- [x] Website metrics (# of visits, time on page, conversion rates, etc)

- [x] Any learnings about the publications template (stretch)

**Comment by kristinashu** [comment]
[Here's Jam's retro planning doc](https://docs.google.com/document/d/1RftR0fyQyoilAous7BYUbU_rBk3JR0y3VP9YTM3MxRg/edit#)

**Comment by nancyt1** [comment]
Started compiling images in [here](https://docs.google.com/presentation/d/1hspGNKL1m2bH_6pGLCeIq7-0PvrvDe07AoHJkb3DzuY/edit?usp=sharing)! It's not really organized yet. @beccaklam

**Comment by kristinashu** [comment]
Looks like [this deck](https://docs.google.com/presentation/d/1j7jLEynNhMU0brurcOi8tW5OgHWfgZp7vOuG3awSVqo/edit#slide=id.p) has been added to the meeting invite so when you're ready you should move your selected slides over there!

**Comment by beccaklam** [comment]
This is done! Nancy added the slides and we presented this morning at the retro :)
