### ISSUE TITLE
Write PNI User Test #2 Report

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9517]
Following up from ticket #9510, write a report based on findings from that user test. Findings and notes documented in this [spreadsheet](https://docs.google.com/spreadsheets/d/1UCwj8xF8rs_3mOaNn51F8SnHGLV6duo5H9LYXx2iWh8/edit?usp=sharing).
- [x] Draft report
- [x] Get feedback from design
- [x] Share report

**Comment by beccaklam** [comment]
@kristinashu The [first draft of this report](https://docs.google.com/document/d/15f6Dz9RtzCgN3A7tBaLxl1EBZ0qjf9LXz2_mQUdK1Fc/edit?usp=sharing) is ready for review :)

**Comment by kristinashu** [comment]
Looks great, no feedback from me!

**Comment by beccaklam** [comment]
Shared report in the pni production channel :) Marking this done.
