### ISSUE TITLE
[PNI] Update Tagline

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9522]
**Links to comps:**
Homepage [desktop](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=4762%3A74534) and [mobile](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3075%3A29691)
Product Reviews [desktop](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3080%3A30591), [tablet](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3467%3A41084), and [mobile](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3083%3A29539)
Creep-o-meter face [mobile](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=4893%3A105021) example

### Goals:
- Update styling on homepage and Product Reviews pages
- Creep-o-meter face animation should always begin in the bottom right hand corner instead of transitioning there
- Make text editable in the CMS, design to provide guidance on character limit
- Question for Dev: This might introduce a new type style, do we have any existing styles that are similar? Will we have too many styles after this? (devs: yes)

### Acceptance criteria:
**Content**
- [x] New tagline should say: Make smart choices to protect your privacy.
Search for products. Read expert reviews. Get tips and tricks.

**Styling**

- [x] There should be a < br > between "Make smart choices to protect your privacy." and "Search for products..."
- [x] Remove previous creepy face styling, change to text only
- [x] Creep-o-meter face animation should now always begin in the bottom right hand corner instead of transitioning there
- [x] Desktop and Tablet text styling for tagline should be Zilla Slab, Light, size 36px (new style)
- [x] Mobile text styling should be Zilla Slab, Light, size 24px (new style, technically Mobile Heading 3 with an override on font weight from regular to light, but could just set this as a new PNI tagline style instead)
- [x] Text is centered
- [x] Desktop spacing: Padding top and bottom should be 48px
- [x] Tablet and mobile padding top and bottom should be 24px

**CMS**
~Make CMS editable (stretch)~

**Comment by kristinashu** [comment]
Note the CMS already shows this field it just doesn't seem to be connected to the front-end. 
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/1068783/197274876-41804f25-eb37-4729-8278-ef43b8d1253e.png">

**Comment by kristinashu** [comment]
Turns out that having the line break makes it more complicated to make this a CMS editable fields so we've removed that requirement.

**Comment by kristinashu** [comment]
Discuss with @beccaklam and she's decided the face doesn't need to "teleport". The Creep-o-meter face should always start in the lower right hand corner.

**Comment by beccaklam** [comment]
@fessehaye @tbrlpld I've included the creep-o-meter face decision in the acceptance criteria. Let me know if what I've written works!

**Comment by cdanfon** [comment]
@fessehaye Hey Simon are you working on this one at the moment? If so can you please update the status? Thanks! :)

**Comment by tbrlpld** [comment]
@cdanfon @beccaklam Looks like this is ready for QA on staging.

**Comment by kristinashu** [comment]
@beccaklam I don't think those are blockers for launch so could you please one a new ticket for those requests?

**Comment by beccaklam** [comment]
Follow up ticket created for the above requests: #9652
Should I close this ticket then @kristinashu ?

**Comment by kristinashu** [comment]
@beccaklam please check off the ACs that are done and move this to the "Ready for Prod" column and assign this back to Simon :)

**Comment by beccaklam** [comment]
@fessehaye One small thing, not a blocker so if it's hard to do let me know, but can the line-height for mobile be 1.75rem instead of 2rem. That's what it is in the comps but I didn't write it out in the ACs, sorry about that.

**Comment by kristinashu** [comment]
@beccaklam adding the line-height issue to https://github.com/mozilla/foundation.mozilla.org/issues/9652 so that we can close this one :)
