### ISSUE TITLE
[PNI] Adjust Nav Categories and Search Bar Positioning

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9523]
Move category nav and search bar so that it is consistently a part of the top page navigation (the same as how it currently is on the Product Reviews & Category pages)

![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/acfa9cea-e4f7-45ea-b2e2-05db80b92e27)![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/63dd5399-0771-434b-93b9-7c7a6427da69)

**Figma Links**
[Desktop](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=4762%3A74534), [tablet](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3467%3A41084) and [mobile](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3467%3A41084) examples

### Dev Tasks (needs refinement)
- [x] Move category nav and search bar to just under the current PNI primary nav
- [x] Make adjustments to the More dropdown 

### Acceptance Criteria
- [x] Category navigation and search bar are now just below the main nav 
- [x] Category navigation and search bar are now positioned the same on all PNI pages
- [x] Clicking on a category on the homepage brings a user to the Product Reviews page (with the selected filter, when applicable)
- [x] To simulate the above AC (user is brought to the Product Reviews page): "Product Reviews" is highlighted, the selected (if applicable) category is highlighted and the editorial section is hidden  
- [x] Submitting a search on the homepage brings a user to the Product Reviews page with the search results showing
- [x] "More" drop down shows additional categories that don't fit

**Comment by mtdenton** [comment]
Planning on splitting this issue into P1 and P2 based on dev tasks.

**Comment by kristinashu** [comment]
@beccaklam @fessehaye I've updated the ACs - please re-review them :)

**Comment by kristinashu** [comment]
I see this is on staging now! I had a quick look and it's looking really good except it doesn't seem to satisfy the ACs of:
- Clicking on a category on the homepage **brings a user to the Product Reviews page** (with the selected filter, when applicable)
- Submitting a search on the homepage brings a user to the Product Reviews page with the search results showing

**Comment by beccaklam** [comment]
I also get the same error where clicking the category nav doesn't bring me to the Product Reviews page but keeps me on the homepage still but with the new category selected? In case we're not being clear, that was the old expected behaviour but with the category nav moved up the expected behaviour is now that the user would be sent to the product reviews page.

https://user-images.githubusercontent.com/20977376/200925434-cf854469-6afb-4863-85e4-22a38af29716.mov

**Comment by beccaklam** [comment]
@fessehaye just added an AC that lays out what we talked about in the call with Kristina:
"To simulate the above AC (user is brought to the Product Reviews page): "Product Reviews" is highlighted, the selected (if applicable) category is highlighted and the editorial section is hidden"

**Comment by kristinashu** [comment]
Yay this is looking good to me!

**Comment by beccaklam** [comment]
This looks good to me too!
