### ISSUE TITLE
[PNI] Update PNI Ding Filter

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9524]
**Link** to [example](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=4762%3A74534)

Old:
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/b8cc4394-7e62-4b50-be4c-8f23b408f7e5)

New:
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/56d1a595-1e24-46b7-9e66-8967bf908751)

Add tooltip:
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/ed9e4c48-45fe-4031-ac6c-cf07f52c2055)

Example of existing tool tip for ding over a product:
<img width="297" alt="image" src="https://user-images.githubusercontent.com/1068783/197644292-27b38172-a9a9-4b58-989c-7ff37a38333b.png">

### Dev tasks
- [ ] Update text to "privacy not included"
- [ ] Add tooltip

### Acceptance Criteria
- [ ] Text has changed from "old" to "new" described above
- [ ] Text change doesn't adversely affect page responsiveness on any size
- [ ] A tooltip appears when hovering over the filter button
- [ ] The tooltip matches the existing tool tip that shows up when hovering over the "ding" on the product cards (also see above)

**Comment by kristinashu** [comment]
I've added the tool tip example above ^

**Comment by tbrlpld** [comment]
@beccaklam @kristinashu Are we sure the text of the tooltip on the button should be "*privacy not included with this product"? I would expect more something like "Filter for products with sever privacy concerns"... or something like that... since the hover is not on a prodcut.

**Comment by tbrlpld** [comment]
Or at least "*privacy not included with these products"

**Comment by tbrlpld** [comment]
@cdanfon @beccaklam This is now ready for testing on the preview app: https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/

**Comment by beccaklam** [comment]
> Or at least "*privacy not included with these products" (because it's more than one)

This is a good point, we can probably change it to at least this ^. Rewriting to something like "Filter for products with severe privacy concerns" would probably need a consult from Jen since there used to be concerns (I _think_, at a legal level) with us being _too_ opinionated.

**Comment by beccaklam** [comment]
@tbrlpld The wording has definitely been updated across all the screens I've checked!

I'm having trouble though seeing the tool tip consistently:

- I don't see it at all on Chrome. 

- On Safari it only shows up after 3-4 seconds and only when my cursor is directly above the word "privacy not included". 

- The tool tip does not seem to activate when hovering over the hazard icon directly for any browser I've checked (Firefox, Chrome, Safari)? 

I'm assuming the tool tip also only works on desktop, correct?

**Comment by tbrlpld** [comment]
Yes, tooltips don't work for mobile as there is no hovering.

**Comment by tbrlpld** [comment]
I guess it should be possible to show the tooltip for the whole button including the icon.

**Comment by tbrlpld** [comment]
For me it did show up in Chrome too.

**Comment by beccaklam** [comment]
@tbrlpld Oh strange, it's working for me now! I think we can go ahead with implementing what we have right now and make adjustments later?

**Comment by tbrlpld** [comment]
@beccaklam Sorry, I am not sure I follow. What do you suggest we implement now?

**Comment by beccaklam** [comment]
Oh, I meant what you have currently working on staging looks good to go for me. The adjustments to the wording/cursor placement can be debated later?

**Comment by tbrlpld** [comment]
@beccaklam Sure can. Would you mind creating a ticket for the further changes?

**Comment by beccaklam** [comment]
Done: #9575

**Comment by tbrlpld** [comment]
Thanks @beccaklam I mark this one as done. We can tackle the rest in the new ticket.
