### ISSUE TITLE
[PNI] Update homepage hero article layout

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9525]
**Links**
[Desktop](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=4762%3A74534), [mobile](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3075%3A29691) examples

### Goals
- Reduce the image dimensions 
- Increase hero title and related section width
- Reduce the title size to Heading 3 (28px)
- Update type style for title of “Related” block

### Acceptance Critera
- [ ] Reduce hero image to 7 columns
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/73fd7e52-b155-4b48-bef8-dc67448b8d36)
<br></br>
- [ ] Increase hero article title and related section to 5 columns
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/fa7b5e51-529f-4762-9b0d-f664fa47dc7b)
<br></br>
- [ ] Desktop/Tablet: Reduce text size of hero article title to Desktop Heading 3 (Zilla Slab, Regular, size 28px leading 36px)
- [ ] Mobile: Reduce text size of hero article title to Mobile Heading 4 (Zilla Slab, Regular, size 22px leading 28px)
- [ ] Update styling of "Related" text to Nunito Sans, Regular, size 16px leading 20px
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/b7ef0d7b-1ab9-40e3-9c35-edd7577887a9)

**Comment by tbrlpld** [comment]
@cdanfon @beccaklam This is ready for testing on the preview app: https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/

**Comment by beccaklam** [comment]
@tbrlpld Visually this is good to go!

**Comment by cdanfon** [comment]
All ACs were visual we can close this as completed
