### ISSUE TITLE
[PNI] Update "Submit a product" section

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9526]
**Links**
[Example](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=4762%3A74534)

### Goals

- Add link to search bar
- Turn button into just a text link

### Acceptance Criteria
- [x] Change text to say "Try search or let us know what product you would like reviewed in the guide. Submit a product here." below "Don’t see the product you’re looking for?"
- [x] Link "Try search" to search bar. Expected behavior: click link, page scrolls to area where search bar is
- [x] Change "Submit a product" from a button to a text link

Old:
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/86470e41-9456-4b38-983c-f5674315dee6)

New:
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/fa352680-665f-4ef0-a043-2305ce56f6d5)

**Comment by fessehaye** [comment]
ready on staging

**Comment by beccaklam** [comment]
This is good to go! ✅ Created a follow up design ticket: #9653 just as a reminder to myself for some progressive enhancement.
