### ISSUE TITLE
[PNI] Implement About page copy updates

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9527]
Based on https://github.com/mozilla/foundation.mozilla.org/issues/9483 

## ++++ Blocked until we have the finalized copy docs++++

Updates will only be copy updates, no functionality or layout changes.

### Acceptance Criteria
- [ ] Copy on https://foundation.mozilla.org/en/privacynotincluded/about/why/ matches the [copy doc needed]
- [ ] Copy on https://foundation.mozilla.org/en/privacynotincluded/about/ matches the [copy doc needed]
- [ ] Copy on https://foundation.mozilla.org/en/privacynotincluded/about/methodology/ matches the [copy doc needed]
- [ ] All external links open in a new tab

**Comment by cdanfon** [comment]
@kristinashu Can you confirm if the copy is available for this please?

**Comment by kristinashu** [comment]
We still don't have copy for this yet but it should come this sprint.

**Comment by kristinashu** [comment]
Note this is not a blocker for launch.

**Comment by kristinashu** [comment]
via Jen "probably won't have copy until after Thanksgiving"

**Comment by kristinashu** [comment]
Closing this since there won't be any updates this year
