### ISSUE TITLE
[PNI] Re-style Nav Categories and Search Bar

### ISSUE THREAD

**Issue by mtdenton** [mozilla/foundation.mozilla.org#9528]
There are some stylistic changes needed for the nav categories and search bar.

**Figma Links**
[Desktop](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=4762%3A74534), [tablet](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3467%3A41084) and [mobile](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3467%3A41084) examples

### Dev Tasks
 - [x] Remove squiggly line from underneath nav categories on mouseover
 - [x] Move the dividing line as described in the Figma comps
 - [x] Adjust padding of categories
 - [x] Adjust padding of search bar

### Acceptance Criteria
 - [ ] Layout matches Figma comps on all sizes

**Comment by beccaklam** [comment]
Hey @fessehaye this is looking really good! The search bar is actually supposed to be flush against the dividing line but I think having the space there is okay, esp if we want to implement making the category nav sticky in the future. One thing though:
- [ ] The drop down nav font-size is .875rem which equals to 14px I think (is the base rem 16px?). It would be nice if this could be updated to match the rest of the category nav font size which is 15px. Right now there is a slight difference between the two which looks a little odd.

**Comment by kristinashu** [comment]
@beccaklam please open a follow up ticket for the font size adjustment then close this one! Ty!
