### ISSUE TITLE
[PNI] Changing the category filter on the product reviews page does not update the title

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#9536]
# Description

There is a bug on the product review page when switching category filters. 

1. Visit the product review page: https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/categories/best-of/
2. Notice the title matching the selected category filter
3. Click a different category filter. 
4. See that the products change and the active category in the nav is highlighted, but the heading is still the previous category (the one that the page was loaded with). 

The title should update to the newly selected category. 

# Acceptance criteria

- [x] As a user, when I visit the product review page and switch between categories to filter, the title updates with the selected category title.

**Comment by tbrlpld** [comment]
@beccaklam Can you define what the desired behaviour is? Should we never update the heading to the category (meaning it should always say "Product reviews") or should it always update?

**Comment by beccaklam** [comment]
Thanks for making this ticket Tibor! We've decided that the title should update with the category title. So when a user selects a category, the product review title should match the selected category.
![image](https://user-images.githubusercontent.com/20977376/197647159-2f4f9173-9b67-4879-8eb9-5076757579ec.png)

**Comment by tbrlpld** [comment]
@beccaklam Just to clarify: The current ACs match the desired behavior?

**Comment by beccaklam** [comment]
@tbrlpld Yes it does!

**Comment by beccaklam** [comment]
This is good to go!
