### ISSUE TITLE
Build "fellowship applications closed" page

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#954]
https://projects.invisionapp.com/share/DQF7R82UA#/screens/272095069

**Comment by mmmavis** [comment]
@taisdesouzalessa what happens after user has successfully signed up the newsletter?

**Comment by alanmoo** [comment]
Is it clear where that form submits to as well? Is it the general `mozilla-foundation` newsletter?

**Comment by mmmavis** [comment]
Closing. PR just got merged into `fellowships` branch!
