### ISSUE TITLE
[PNI] Positioning of related articles on the category page

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#9540]
# Context: 

Current position does not match [design](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3080%3A30591). 

![image.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/487981be-812b-44cd-b221-a6c0c4d100f9)

# Acceptance Criteria: 

- [ ] The related article section on the categories page is placed inside the grid as per Figma design on desktop
- [x] The related article section on the categories page is placed inside the grid as per Figma design on mobile
- [ ] The related article section on the categories page is placed inside the grid as per Figma design on tablet

**Comment by beccaklam** [comment]
![IMG_EA8D905AE42A-1.jpeg](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/3a6a1cdd-89f8-42ed-92bc-abf51e4e8323)
Adding this screen shot to this bug. Not sure why it's saying "Primary Related Articles"?

**Comment by beccaklam** [comment]
The positioning of the related article also needs to be fixed. It should look like this:
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/85c0d65f-3867-4ebf-a0a3-705f171bb72b)
[Link to design](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3080%3A30591)

**Comment by kristinashu** [comment]
p3 since we can just hide (not add) articles for now

**Comment by tbrlpld** [comment]
@beccaklam This is ready for QA on staging.

**Comment by tbrlpld** [comment]
@beccaklam This is ready for QA on staging.

**Comment by tbrlpld** [comment]
@beccaklam To QA this, you will have to add related articles to the category you want to test and then load that categories page. 

The toggle between the categories does not work yet, meaning the related articles will remain the same when you switch categories. The articles should update with the category only on page refresh. The dynamic switching of the related articles is part of #9541.

**Comment by beccaklam** [comment]
Hi @tbrlpld this is working and looking mostly as expected! One small thing, can you increase the padding for desktop and mobile to 1.875rem? Currently it's 1rem but in the figma comp the padding is supposed to be 30px.

**Comment by tbrlpld** [comment]
@beccaklam Yea, we can update this. I was not sure where in Figma I could measure/find that padding. It seems to mix with the gap between the cards. 


Just wondering, should we make this 2rem (32px)? 1.875 rem does not seem to show up in the design system spacing scale: https://www.figma.com/file/JT9Dvdyc96AqQ3HJlnA9Qq/WIP-Mozilla-Foundation-Design-Style-Library?node-id=1737%3A1115&t=Wgszlt8rMDSwgAvy-1

**Comment by beccaklam** [comment]
@tbrlpld 2rem sounds good to me 👍 

Looks like you can find the padding if you go to the 'Inspect' panel in figma and select the component in question:

![Screenshot 2022-11-23 at 8 29 38 AM](https://user-images.githubusercontent.com/20977376/203599310-f938da29-4faa-40ba-90f8-8e5b874cf11e.png)

**Comment by tbrlpld** [comment]
Thanks @beccaklam 

I guess I must have been looking at the wrong instance of the component. 

<img width="300" alt="image" src="https://user-images.githubusercontent.com/24797493/203605731-76adb5a7-a7b0-49e6-8715-23d41ba7f4a6.png">

**Comment by tbrlpld** [comment]
Ah true. I guess I a was looking only vertical 🤦‍♂️

**Comment by tbrlpld** [comment]
@beccaklam The increased padding should be ready on staging.

**Comment by beccaklam** [comment]
This looks good to go!

**Comment by beccaklam** [comment]
I'll open a ticket for some other spacing issues but this is fine to go on prod.

**Comment by beccaklam** [comment]
Follow up ticket created here: #9761
