### ISSUE TITLE
[PNI] Switch related articles on category page when category changes

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#9541]
**Context:**
When switching between the categories, the related articles don't update unless the page is reloaded. 
https://user-images.githubusercontent.com/24797493/197841991-53d750ca-9185-4b5f-bc8a-567b1d647ad3.mov

**Acceptance Criteria:** 
- [x] As a user navigating the site, when I select a different category filter the 'Related articles' update to show related articles to that category
- [x] As a user navigating the site, when I select a category filter that doesn't have any articles, the 'Related articles' section doesn't show

NB: A prerequisite is that there are related articles created for that specific category

**Comment by beccaklam** [comment]
The positioning of the related article also needs to be fixed. It should look like this:
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/85c0d65f-3867-4ebf-a0a3-705f171bb72b)
[Link to design](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3080%3A30591)

**Comment by tbrlpld** [comment]
@beccaklam Thanks, there already is #9540. That seems more like what you are talking about. This issue here is a about the functionality of switching which articles are displayed, not the location.

**Comment by beccaklam** [comment]
@tbrlpld Oops thanks for catching that! I've moved my comment to the correct ticket.

**Comment by fessehaye** [comment]
@kristinashu You might need to create some related articles for the category on staging to test this

**Comment by kristinashu** [comment]
Sorry, asking @beccaklam to please review this! Ty!

**Comment by beccaklam** [comment]
This looks good to go! Thank you!
