### ISSUE TITLE
[PNI] Positioning of related articles on article page

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#9542]
Positioning of the related articles does not match the [design](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3406%3A38682). 

![image.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/f325f305-8459-4231-bb02-bd7623084118)

**Comment by beccaklam** [comment]
Adding this mobile screen shot to this bug.
![IMG_EA8D905AE42A-1.jpeg](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/3a6a1cdd-89f8-42ed-92bc-abf51e4e8323)
 Not sure why it's saying "Primary Related Articles"?

**Comment by tbrlpld** [comment]
@beccaklam That was just a marker for us in the template. I don't think we expected the frontend to be not being properly worked on for so long.

**Comment by beccaklam** [comment]
@fessehaye Hi Simon, thanks for working on this. I'm a bit confused about the placement of the related articles. The comp looks like this:
![image](https://user-images.githubusercontent.com/20977376/200921501-3f4d9265-c779-487d-b1fb-c17cbc7a6cf9.png)
But what I'm seeing on staging is this:
<img width="758" alt="Screenshot 2022-11-09 at 11 16 37 AM" src="https://user-images.githubusercontent.com/20977376/200921555-095068e2-6626-4982-b58d-45a817b30ec8.png">
I know that we had a conversation with Nancy where we decided we would have the related articles at the end of an article but _only_ in the niche situation you mentioned where there was very little content (e.g. one photo no paragraph block). Was there some kind of mix up or am I missing something?

**Comment by beccaklam** [comment]
We also would need more spacing between the email CTA box and the "What to read next" section:
![image](https://user-images.githubusercontent.com/20977376/200922135-3040912f-0179-483c-a5fe-3628412afea0.png)

**Comment by kristinashu** [comment]
Note that this is not a prod push blocker since we can just not add the related articles until this is done.

**Comment by beccaklam** [comment]
Follow up ticket in #9664. Closing this ticket!
