### ISSUE TITLE
[PNI] Product grid & cta layout is broken on mobile

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9543]
### Describe the bug
At narrow widths, the product grid is showing 4-up when it should be 2-up and the CTA box covers 2 "columns" when it should cover all 4 "columns." 

### To Reproduce
1. Go to https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/
2. View product grid it at a narrow width
3. See error

### Expected behavior
Screen cap from Figma
![image](https://user-images.githubusercontent.com/1068783/197868006-e1382b2e-a316-4941-9a78-fc0898fc46df.png)

### Screenshot from heroku
![image](https://user-images.githubusercontent.com/1068783/197867617-e0c15eb0-2559-4ebe-8a39-94a1ad674c37.png)

**Comment by tbrlpld** [comment]
Weird. Looks like I was the last to touch this. I must have forgotten to switch that mobile style back on after some experimenting.

**Comment by kristinashu** [comment]
Thanks for looking at this Tibor! I'm assuming it looked right at one time.

**Comment by tbrlpld** [comment]
@fessehaye This is ready for review.

**Comment by tbrlpld** [comment]
@kristinashu @cdanfon This is ready on the preview app now for QA: https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/

**Comment by kristinashu** [comment]
Yay looks good, thank you!
