### ISSUE TITLE
SPIKE [PNI] Improve performance of product grid load time

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#9545]
# Description

There is currently an issue where the PNI pages with the product grid (namely home page and the review/category pages) load extremely slowly for logged in users. 

I am guessing the template caching gets around this for the anonymous users.

```html+django
        {% if request.user.is_anonymous %}
          {# User is not logged in. Return cached results. 24 hour caching applied. #}
          {% cache 86400 pni_home_page template_cache_key_fragment %}
            {% for product in products %}
              {% product_in_category product category as matched %}
              {% include "fragments/buyersguide/item.html" with product=product.localized matched=matched %}
            {% endfor %}
          {% endcache %}
        {% else %}
          {# User is logged in. Don't cache their results so they can see live and draft products here. #}
          {% for product in products %}
            {% product_in_category product category as matched %}
            {% include "fragments/buyersguide/item.html" with product=product.localized matched=matched %}
          {% endfor %}
        {% endif %}
```
 
But it still affects logged in users very badly and makes development extremely painful. 

I am guessing the issue is related to the large queryset we are using and that we use 1+n queries to retrieve the localized version of each product (`product=product.localized`). 

We should investigate the root cause for the bad load times implement some performance improvements. Move the retrieval of the localized products into the view and make sure we only need 1 or 2 queries for this (anything below n would be good). Also, prefetch related items like the image on each product. That should also be possible to include in the above query.

**Comment by cdanfon** [comment]
**GOAL**: Create a performance analysis of the grid view and understand how we can improve the load time. Create a follow-up ticket with a list of steps/dev tasks.

**[TIMEBOX to 4 HOURS]**

**Comment by cdanfon** [comment]
@tbrlpld to publish outcomes and next steps (create tickets to address the issue)

**Comment by tbrlpld** [comment]
## Findings

I was not able to fully uncover the specific root cause of the slow load times, but, through adding integration tests for the page, I was able to confirm that loading the buyer's guide homepage (with the product grid) generates a huge amount of database queries. 

In my tests, serving the homepage with 50 products resulted in the need for 955 database queries. This is a particularly alarming result considering that the production page contains more than 400 products. Based on the approximated 15 queries per product, this would mean 6000 queries. 

It also turns out that the buyer's guide homepage  without any products present still requires the large number of 156 database queries to be rendered.

Comparing the full page rendering with calling the `get_context` method (the method meant for data retrieval) directly show that the templates trigger a large number of the database queries.

However, even the number of database queries triggered in the `get_context` method is very large, considering that it takes 4 times as many queries as there are products. Not that having `1+N` queries for `N` items is considered bad. This page currently needs `4 * N` queries. 

<img width="300" alt="image" src="https://user-images.githubusercontent.com/24797493/206011098-55d95904-e95d-4788-a00e-117f473a552c.png">

There are some question I have not been able to answer:

- What happens in the template that requires this many queries, when there are no products?
- Why does it take 5 queries for a single product in `get_context`?
- Why does it take 30 queries for a single product in the full page rendering? This is an extra 25 queries coming from the template. This should be using what is retrieved by `get_context`.

## Goals and next steps

Regardless of the still open questions I would like to propose the following goals and next steps (working towards these goals should also answer some of the above questions):

1. Template should not make extra requests for the products. All information should be retrieved in the view / `get_context`. This alone would be a huge win.
2. Reduce number of queries it takes the view /  `get_context`, or better a dedicated method to retrieve all the needed data for the products. 
    1. Soft target would be to need less than `N`. 
    2. Really, this should be waaaaaaay less than `N`.
3. Reduce the number of queries it takes the basic page without any products to render. This should be a performance boost for the entire site section.

The above steps are ordered based on the impact that I assume they will have on improving the performance of the buyer's guide homepage.
