### ISSUE TITLE
Fix CI deprecation warnings

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#9548]
We currently get a bunch of deprecation warnings for every GitHub action run. I think we need to fix this to make sure CI is not going to break. 

![image.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/827a01f9-fa5f-4ce1-8ac7-5c49929a25fe)

**Comment by mmmavis** [comment]
Fixed!

**Comment by mmmavis** [comment]
Fixed!
