### ISSUE TITLE
Build static fellowships directory page

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#955]
We're going to have a dynamic directory, but the work on that might take longer than it does to get to building this page. If that's the case, grab the JSON from the desired pulse profiles and use that to generate a static page.

**Comment by alanmoo** [comment]
@auremoser Can you or Amy (github handle?) build a list of the urls for pulse profiles of current fellows?

**Comment by auremoser** [comment]
Sure, Amy's handle is @community-impact. 

I sent the fellows a message to create profiles and we added an [issue in the moz-fellows repo for it](https://github.com/MozillaFoundation/mozfellows-2017/issues/3) but I am not sure all of them were able to 😢 . I'll remind them.

I think I'll need to request their profile links from them anyway, because the search doesn't seem to return for their names:
![screen shot 2018-01-16 at 1 06 26 pm](https://user-images.githubusercontent.com/1559703/34988185-28f1183a-fabe-11e7-93c7-8ef13675e6c4.png)

Even when they have a profile:
* Chris Hargerink: https://www.mozillapulse.org/profile/248

More soon @alanmoo !

**Comment by alanmoo** [comment]
Yup, that's expected and one of the things on our roadmap is improving the search.

As long as the have a google account, they should be able to log in with it on Pulse and that'll allow them to create a profile.

**Comment by auremoser** [comment]
FYI, updated the above comment to include more fellows' profiles.
Trying to get through that this week!

**Comment by xmatthewx** [comment]
Sharing a list of links to all the profiles.

**Comment by auremoser** [comment]
I added all the profiles as of today, including some alumni fellows (mostly OWF and Science because that's my focus area but I found some senior fellows too, so I add those.

**Comment by mmmavis** [comment]
@alanmoo What URLs do we wanna use for specific fellowship type pages under Directory?

I'm thinking

- /fellowships/directory/senior
- /fellowships/directory/science
- /fellowships/directory/open-web
- /fellowships/directory/tech-policy
- /fellowships/directory/media

Thoughts?

**Comment by auremoser** [comment]
I think these are logical @mmmavis ! I wonder if we would want to abbreviate to "dir" or something so the URL isn't quite so long. What would be the full URL breadcrumb here? Something like `foundation.mozilla.org/fellowships/directory/science/2016`?

It's probably too late to punt "directory" as a term, but I also like the following as options (they feel a bit warmer?, and echo community programs like [this directory example which includes but is not forever limited to fellows](https://source.opennews.org/people/))
* `/fellowships/index/` we could also do `fellowships/codex` though I'm not sure the "code" pun would come through 😢 
* `/fellowships/community/`
* `/fellowships/people/`

**Comment by xmatthewx** [comment]
Let's stick with `fellowships/directory`. I like people, but we use that for a top level view. That view will evolve this spring to stories about people (including fellows). It'll be warm and fuzzy. Community connotes something broader and feels ambiguous.

**Comment by mmmavis** [comment]
We have dynamic directory working already so I'm closing this ticket. 

See this review app: https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/directory/ 

Profiles are pulled from Pulse API directly. To make someone show on the directory page, make sure his/her Pulse profile has the following meta set (we can do this on Pulse backend's admin interface)

- `profile_type` is set to `fellow`
- `program_type` is properly set
- `program_year` is properly set

**Comment by auremoser** [comment]
Whoo, looks slick, what's the best way to add a person (I notice Joey K. Lee @joeyklee is not listed among [Science Fellows 2015](https://science.mozilla.org/programs/fellowships/fellows)) but I'm happy to add him. 
* Do I have access to the `profile_type`/`program_type` entries that @mmmavis mentions? 
* Should I just ask him to make a profile again?

What's the best way to do this from the above/other options?

Thank you!

**Comment by xmatthewx** [comment]
Yes, staff will have access to add and update profiles for fellows. As I mentioned in slack, there's a hiccup we're squashing now that will make it much simpler. More soon....

**Comment by joeyklee** [comment]
Thanks @auremoser! let me know if there's anything I can do to help.

**Comment by auremoser** [comment]
Yes @joeyklee , would you mind making a [Pulse Profile](https://www.mozillapulse.org/featured), we'll be using it in the spiffy new website which will feature a fellows' directory! I couldn't find your profile in my searches before, so I'm not sure we asked you to make one.
![screen shot 2018-03-05 at 11 52 07 am](https://user-images.githubusercontent.com/1559703/36988031-c1a1cc64-206b-11e8-8972-ac4b37e0334d.png)


Thanks

**Comment by joeyklee** [comment]
@auremoser oh whoops! I may have overlooked that mail. Anyhoo, you should find it under my email: josephkanglee@gmail.com
