### ISSUE TITLE
[PNI QA] Alignment of product review filters is broken on various screens

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9550]
## Describe the bug:
The privacy ding and sort by creepiness filter alignment needs some adjustment on tablet and mobile screens. 

**To reproduce:**
1. Go to https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/
2. Adjust to tablet view (810 x 1080) and mobile view (375 x 812)
3. See bug(s)

### Mobile:
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/64581644-56a8-44b5-95d6-77f497b6d218)

### Tablet:
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/b986b5e7-06d5-4a5a-9767-9a87aa78ef53)
[Link to design example](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3467%3A41084)

### Mobile:
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/c97ca679-11f1-4f98-9c28-2c276acf6092)
[Link to design](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3083%3A29539)

**Comment by beccaklam** [comment]
Adding that the 'sort by creepiness' filter appears squished when multiple tags appear for a category:
![Screen Shot 2022-10-26 at 2.35.18 PM.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/b25cf902-9e98-4b5c-937d-dce27b26aff0)

**Comment by kristinashu** [comment]
This might be a p2?

**Comment by beccaklam** [comment]
Yeah ... I would want this fixed before launch if possible. Just looks unpolished.

**Comment by beccaklam** [comment]
Adding that on tablet when the "sort by creepiness" filter gets squished the words also merge into the arrow (Firefox, iPad OS):
![image](https://user-images.githubusercontent.com/20977376/199588271-91a2e35c-8d39-401d-8334-11fffd67066a.png)

**Comment by beccaklam** [comment]
Also happens on Safari:![15915.jpg](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/64eebe94-4dd5-4754-a23f-301ccbc22075)
[](url)

**Comment by fessehaye** [comment]
Should be ready in staging in a few mins

**Comment by kristinashu** [comment]
This looks much better! Some design could be done to improve where the tag meets "Sort" but that should be a follow up!

<img width="969" alt="image" src="https://user-images.githubusercontent.com/1068783/200963660-f7746e74-94ec-47eb-912e-39d73617996e.png">

**Comment by beccaklam** [comment]
Agreed ☝️ ! Created a follow up ticket: #9659. This is good to go though.
