### ISSUE TITLE
[PNI QA] Search not working on product review pages

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9553]
On a product review page (not to be confused with the Product Reviews page), search is not working.

To replicate bug:
1. Go to https://foundation-pni-2022.herokuapp.com/privacynotincluded/ on any device (desktop, tablet, mobile)
2. Click on any product review like https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/threema/
3. Go to the search bar
4. Type something into the search bar and hit enter
5. See bug (nothing happens)

**Comment by mtdenton** [comment]
@fessehaye seems like javascript errors might be causing this and #9557: 
<img width="1723" alt="Screen Shot 2022-10-26 at 6 20 30 PM" src="https://user-images.githubusercontent.com/41487159/198157399-27b949bd-0216-4cb1-8246-f4c7fb7ca7f2.png">

**Comment by fessehaye** [comment]
I think Becca was referring to the desktop screen? But good to know that mobile isn't working either. This overlaps some of the nav stuff I am doing so I will grab this one. @mtdenton

**Comment by mtdenton** [comment]
It adjusted viewport size because I opened the dev tools, just trying to show that there are javascript errors that need addressed.

**Comment by beccaklam** [comment]
It's for all screens actually, I think @fessehaye

**Comment by tbrlpld** [comment]
Mobile (Desktop Firefox with small viewport) works for me. Desktop (Firefox) does not work.

**Comment by tbrlpld** [comment]
Works for me on iOS (Safari)

**Comment by tbrlpld** [comment]
I have tried cleaning this up, but it turns out to be more work than expected. Looks like a refactor has been needed for a while: https://github.com/mozilla/foundation.mozilla.org/issues/8015

I am moving forward with this as is, but would propose to follow up with #8015 as soon as possible.

**Comment by tbrlpld** [comment]
@beccaklam This is on staging ready for testing.

**Comment by beccaklam** [comment]
This looks good to me!
