### ISSUE TITLE
[PNI QA] 'Related products' squiggle on product review pages is too big in Chrome

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9554]
The 'Related products' squiggle on product review pages is too big:
![Screen Shot 2022-10-26 at 2.17.36 PM.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/75975e02-1162-461d-b72c-09b5fd347870)

It should look like this:
![Screen Shot 2022-10-26 at 2.18.12 PM.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/181e7c0b-e139-4fba-a51f-edd7cf28cdec)

To replicate bug:
1. Open Chrome
2. Go to https://foundation-pni-2022.herokuapp.com/privacynotincluded/
3. Click into any product review
4. Scroll to the bottom of the page and locate 'Related products'
5. See bug

**Comment by kristinashu** [comment]
Putting this as a p2 if it's a quick fix but if it's more than a `1` estimate, bump it down to a p3

**Comment by fessehaye** [comment]
Is this still happening? Checking on staging and looks fine?

**Comment by kristinashu** [comment]
I still see it in Chrome Version 106.0.5249.119 on macOS 12.6 when my browser is at a wide width (looks good a narrow width) 

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/1068783/199069150-cb5684be-1fec-4ca0-af16-6d9d9a510db0.png">


<img width="485" alt="image" src="https://user-images.githubusercontent.com/1068783/199069538-c8f9355b-d371-4a38-878b-51977aa1ec78.png">

**Comment by fessehaye** [comment]
ready on staging

**Comment by beccaklam** [comment]
This is fixed!
