### ISSUE TITLE
[PNI QA] Cannot select the category nav on a product review page (Mobile - any browser)

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9557]
The category nav drop down menu is not working on the product review page on mobile.

To replicate the bug:
1. Go to https://foundation-pni-2022.herokuapp.com/privacynotincluded/ on your mobile device
2. Click into any product review, such as https://foundation-pni-2022.herokuapp.com/privacynotincluded/amazon-echo-show/
3. Try to tap the drop down menu besides "All Categories" or even "All Categories" itself
4. See bug (nothing happens)

Note: This appears to work on Firefox desktop when you adjust the view width to a mobile size but not on a mobile device itself (at least on iOS)

**Comment by tbrlpld** [comment]
I can even reproduce on desktop Firefox with small viewport.

**Comment by cdanfon** [comment]
Currently with Tibor for code review

**Comment by fessehaye** [comment]
ready on staging

**Comment by beccaklam** [comment]
This is fixed! ✅
