### ISSUE TITLE
[PNI QA] Sign up button styling on product page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9558]
### To Reproduce
1. Go to a product page, for example https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/netatmo-smart-indoor-camera/
2. Scroll down to the Newsletter signup
3. See `Sign up` button text that has an underline (Expected behavior: should not have underline)
4. Hover over the `Sign up` and see the button text turn blue (Expected behavior: text should remain white and button color should change)

#### Screen cap of product page (bug)
<img width="760" alt="image" src="https://user-images.githubusercontent.com/1068783/198150132-b2022f19-a259-464f-97f2-f21f09a445f0.png">

#### Screen cap of homepage (expected behaviour) 
<img width="575" alt="image" src="https://user-images.githubusercontent.com/1068783/198150203-4ce31d0c-85a4-4b29-8d51-639e9e0b0eb3.png">

**Comment by cdanfon** [comment]
This is ready to be pushed to staging, but we're waiting to have a few more tickets in the same status to make the most of the push to staging instead of a push for a single ticket

**Comment by fessehaye** [comment]
ready on staging

**Comment by kristinashu** [comment]
Looks good, thank you!
