### ISSUE TITLE
[PNI QA] Email CTA showing up first in product review grid when using alphabetical and 'Creepiness: Most — Least' filters (safari - mobile)

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9559]
On mobile, when using the 'sort by' filter and selecting 'Alphabetical' and 'Creepiness: Most — Least', the email call out box shows up first. This is confusing because it kind of looks like nothing is happening/there are no results. Would it be possible to make sure it doesn't show up first in the grid? This is low priority.

**Comment by cdanfon** [comment]
Hey @beccaklam could you provide more info please?:

- What page are you on when experiencing this? 
- Could you please explain where the CTA box should go when there are only a few items?

Is it possible to make a video please? :)

**Comment by cdanfon** [comment]
Needs grooming

**Comment by cdanfon** [comment]
Hey @beccaklam Any thoughts on the above please?

**Comment by beccaklam** [comment]
Hmm, so I just looked at this again and I think it's related to loading because sometimes the email will appear first (I tried 'Toys & Games' but some time other products will load in. I'll close this for now because it's probably related to #9709.
