### ISSUE TITLE
Refine fellowships pages based on UI comps

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#956]
All of the fellowships pages are being built based on wireframes, so we'll need another round of polish on them once the comps are done.

This ticket can be closed when all pages have been updated to reflect as-of-yet unfinished comps.

**Comment by taisdesouzalessa** [comment]
I'll be posting the WIP in the design issue in the ticket #957 and once the feedback rounds about UI are done I will post the final version here. Sounds good?

**Comment by taisdesouzalessa** [comment]
Here are the comps, not 100% final but it has been through some feedback already. Still doing the tweaks and working on the mobile versions of the screens:

Applications Open: https://invis.io/ZJ9YTAGEA#/273312987_FellowshipsUI_-_Overview
Applications Closed: https://invis.io/ZJ9YTAGEA#/273603676_FellowshipsUI_-_Overview_V2_Applications_Closed

**Comment by taisdesouzalessa** [comment]
@mmmavis here are the Sketch files with the work in progress as per our conversation: https://drive.google.com/file/d/1ZqIVpHwzx9AWk9Ef4l22VD82FK4yYWoi/view?usp=sharing

**Comment by taisdesouzalessa** [comment]
@mmmavis comps are ready to go: https://drive.google.com/file/d/1ZqIVpHwzx9AWk9Ef4l22VD82FK4yYWoi/view?usp=sharing

This to consider: content still not 100% yet, we may have some few feedback pieces here and there - but styling and structure seems ok, I'll let you know if anything changes as soon as I know.

Next step: to work on assets.

**Comment by taisdesouzalessa** [comment]
@mmmavis I am starting to build the assets for the pages. Please note that some discussions are still happening, so what I did was to add notes on top of each page of the Sketch file and I'll update the notes as soon as we make the pending decisions. I am working from V2 now, cool? So I don't have to update V1 and V2.

Here is the Sketch file
https://drive.google.com/open?id=15st_Yd-GS4nAFgqqp-ci8QU1g4pWLdWr

[UI Applications Open ](https://invis.io/ZJ9YTAGEA#/276734814_v2-FellowshipsUI_-_Overview)
[UI Applications Closed](https://invis.io/ZJ9YTAGEA#/276734811_v2-FellowshipsUI_-_Overview_Applications_Closed)

**Comment by taisdesouzalessa** [comment]
Status: assets created and refined after a feedback round (thanks @sabrinang and @xmatthewx) - all icons/illustrations are placed in the comp now. Links are above (I kept the same link but updated the file).
Next step: finish pictures and export svgs to @mmmavis  \0/

**Comment by taisdesouzalessa** [comment]
Assets being tracked here: #1057
The work on the UI (structure) of this project is on hold until we have updated content info. Meanwhile I am working on the assets issue to make sure all the placeholders are gone.

**Comment by taisdesouzalessa** [comment]
Here are the mockups with the latest changes and assets in place:

DESKTOP:
[UI Applications Open ](https://invis.io/ZJ9YTAGEA#/276734814_v2-FellowshipsUI_-_Overview)
[UI Applications Closed](https://invis.io/ZJ9YTAGEA#/276734811_v2-FellowshipsUI_-_Overview_Applications_Closed) 

@alanmoo @jessevondoom @xmatthewx I went as I far as I could go with those, please take a look at the latest version and let me know if we will have any updates on copy (there are some missing) or changes of page structure.  cc: @mmmavis

**Comment by mmmavis** [comment]
Followup tickets have been filed and fixed to address issues in individual page/section.

Closing this ticket now.
