### ISSUE TITLE
GA4 Implementation

### ISSUE THREAD

**Issue by bheasman** [mozilla/foundation.mozilla.org#9561]
This issue is to track all work relating to the initial GA4 set up.

The work is nearly complete - here's a high level summary:
- [Fo.mo GA4 property](https://analytics.google.com/analytics/web/#/p321347134/reports/intelligenthome)
- [Donate GA4 property](https://analytics.google.com/analytics/web/#/p321328061/reports/intelligenthome)
- [Mozfest GA4 property](https://analytics.google.com/analytics/web/#/p321315318/reports/intelligenthome)
- [Pulse GA4 property](https://analytics.google.com/analytics/web/#/p323672401/reports/intelligenthome)
- [Common Voice GA4 property](https://analytics.google.com/analytics/web/#/p337278639/reports/intelligenthome) 
- [ Data studio dashboard](https://datastudio.google.com/u/0/reporting/4cb22021-3ab0-4feb-aa95-cdc6b06c0b81/page/QeI3C) 

The 2 areas needed to wrap up this ticket are:
- Investigate the CSP issue blocking some data flowing to GA4
- Test data layer that's been added to track donations

**Comment by kristinashu** [comment]
Moved this to our upcoming sprint since this is In Progress. Assigned to TBX to facilitate.

**Comment by bheasman** [comment]
Update - donation tracking unblocked - waiting on a prod push then this will be resolved. Then proposing to close this issue as the Pulse question is part of a wider discussion (as detailed in #9587 )

**Comment by bheasman** [comment]
Proposing to close this one for now as the donate tracking is in place. Any issues with that @kristinashu ?

**Comment by kristinashu** [comment]
Sounds good, thank you!
