### ISSUE TITLE
Cleanup of unused models' attributes

### ISSUE THREAD

**Issue by patjouk** [mozilla/foundation.mozilla.org#958]
While creating the fake data generator, @cadecairos and I ran into a few models' attributes that are not used anymore (list to be continued):

People:
- `bio` cf #359
- `featured` cf #721 

News:
- `featured`: cf #721

**Comment by Pomax** [comment]
#359 has been closed since, so I will close this issue in lieu of #721, which is still open and has more recent activity on the question of what to do with the featured field.
