### ISSUE TITLE
DFL - Article teaser block in Banner page to include further fields

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9585]
### Describe the feature request
From the back of the work done by TBX on #9401, tweaks are needed to incorporate: 

- Title
- Image (thumbnail)
- Image label
- URL link 

### Screenshots / mock-ups
The current option allows the editor to select from an 'article page chooser', whereas the use case is to allow for an external article to be rendered. 
<img width="930" alt="Screenshot 2022-10-31 at 10 37 18" src="https://user-images.githubusercontent.com/102978346/198989252-a40e85f9-c26d-4a2d-8288-5fd32512be7e.png">

<img width="930" alt="Screenshot 2022-10-31 at 10 38 36" src="https://user-images.githubusercontent.com/102978346/198989300-f4df30af-1ff4-4f22-846d-a52c540ac785.png">

**Comment by stevedya** [comment]
@cdanfon This looks like more of a BE change but i've put 3 hours on it as a rough estimate

**Comment by tbrlpld** [comment]
@cdanfon Where are these images and names coming from? Will this all be uploaded an a block basis? Or should this come from profile snippets? I guess we typically won't have these external sources as profiles.
