### ISSUE TITLE
[PNI] "Product Reviews" header link on homepage sends user too far down the page on Firefox

### ISSUE THREAD

**Issue by mtdenton** [mozilla/foundation.mozilla.org#9586]
### Describe the bug
On the PNI homepage, "Product Reviews" header link sends user too far down the page when it navigates to https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/#product-review

Seems to only happen on Firefox.

### To Reproduce
1. Go to https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/
2. Click on "Product Reviews" in the header
4. Page scrolls way too far

### Expected behavior
Clicking the link should show display the top of this view, starting with the page header reading "Make smart choices to protect your privacy. Search for products. Read expert reviews. Get tips and tricks."

### Screenshots
https://user-images.githubusercontent.com/41487159/199039457-53c86d69-73a8-4cb8-8d69-8453eb18b0d5.mp4

### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Firefox

**Comment by cdanfon** [comment]
closing this one as duplication #9552
