### ISSUE TITLE
[PNI] Does the nav need to be sticky?

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9589]
@fessehaye brought up that we may want to make the nav sticky (like how it used to be) given the length of some of our pages.

**Goals**
- [x] Benchmark solutions
- [x] Design to explore sticky solutions (should the it be just the category nav/search bar, or the upper main menu as well?)
- [x] Address #9698 
- [x] Gather feedback from design and devs
- [x] Create implementation ticket

cc: @kristinashu @nancyt1 If I have time this sprint I can tackle this? If not we can chat about what priority this is and if it will make it into the next sprint?

**Comment by beccaklam** [comment]
First draft of the designs can be found in this [redpen](https://redpen.io/p/wy75eeaf54e8ebcc04) @kristinashu @nancyt1 let me know your thoughts!

**Comment by beccaklam** [comment]
Updates based on crit this morning are now in the [redpen!](https://redpen.io/p/wy75eeaf54e8ebcc04) @kristinashu @nancyt1

**Comment by kristinashu** [comment]
@beccaklam desktop is looking good to me. Are there new mock-ups for mobile?

**Comment by nancyt1** [comment]
Desktop looks good to me too!

**Comment by beccaklam** [comment]
@kristinashu Just added the screens!

**Comment by kristinashu** [comment]
Looks good!

**Comment by beccaklam** [comment]
Created implementation ticket #9720. Plan is to gather feedback from the dev (probably @fessehaye?) before they begin implementation.
