### ISSUE TITLE
Add add 'image feature card' and 'image teaser' block to the Mozfest pages

### ISSUE THREAD

**Issue by bheasman** [mozilla/foundation.mozilla.org#9591]
### Describe the feature request
Add add 'image feature card' and 'image teaser' block to the `Mozfest_homepage `and `mozfest_primary_page`

These blocks are both available on the banner page. Here are the tickets in which they were delivered:
https://github.com/mozilla/foundation.mozilla.org/issues/9400
https://github.com/mozilla/foundation.mozilla.org/issues/9397

ACs
- [ ] as an editor, I can add an `image feature card` block to the body streamfield content in the `Mozfest_homepage `and `mozfest_primary_page`
- [ ] As an editor, I can add an `image teaser` block to the body streamfield content in the `Mozfest_homepage `and `mozfest_primary_page`

**Comment by tomusher** [comment]
It looks like these are already available on Mozfest pages as delivered in the original tickets.

Can you confirm @bheasman ?

**Comment by bheasman** [comment]
@tomusher - ah great, I wasn't aware that was the case. But yep, agree they're in there now. @marcwalsh - are you happy to test this please and check you're happy? 

CC @kristinashu @mtdenton

**Comment by kristinashu** [comment]
Yes, the blocks are showing up on the mozfest site and I'm assuming the dividing lines will show up there as well once https://github.com/mozilla/foundation.mozilla.org/issues/9535 is done. 

I didn't realize the `Body` text was going to be truncated so much in https://github.com/mozilla/foundation.mozilla.org/issues/9397 so I'll open a follow up ticket to increase the character count for that field. 

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/1068783/199624354-b795306d-0232-4dc7-8d35-f4beb090e6d7.png">

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/1068783/199624517-ffb96e70-7e37-438b-8630-db6334110506.png">

**Comment by marcwalsh** [comment]
This looks great for the Meet the Community / Community Spotlight section. +1 to @kristinashu's comment about allowing for longer body content. I think we might be pushing the limits a little with some of the quotes we're hoping to include.

**Comment by kristinashu** [comment]
I've opened the follow up ticket here https://github.com/mozilla/foundation.mozilla.org/issues/9619

**Comment by cdanfon** [comment]
Closing this as complete. Follow up ticket has been created _#9619_
