### ISSUE TITLE
[PNI] Menu shaking when product grid reaches top of screen

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#9595]
# Description

Visit the PNI page (http://localhost:8000/en/privacynotincluded/) and scroll down. 

Notice the shaking when the product grid reaches the top of the screen.

https://user-images.githubusercontent.com/24797493/199338503-0ef0cea9-9a63-4cd2-a0da-d8d280577a8b.mov

# Expected behaviour

Smooth scrolling. 

# Acceptance criteria

- [x] On the buyer's guide (home) page I can scroll down until the product grid scrolls smoothly out of view at the top of the screen.

**Comment by kristinashu** [comment]
I'm also seeing this sometimes. Seems really bad in FF and Chrome and less bad in Safari.

**Comment by cdanfon** [comment]
NB Once this ticket has been completed we can do a push to production

**Comment by fessehaye** [comment]
ready on staging @cdanfon

**Comment by cdanfon** [comment]
@kristinash assigning to you for testing!

**Comment by kristinashu** [comment]
@beccaklam could you please check, ty!

**Comment by kristinashu** [comment]
I've just check this and it looks good! I'll move this to the Ready for Production column
