### ISSUE TITLE
[PNI QA] Byline missing "and" between author names on homepage

### ISSUE THREAD

**Issue by nancyt1** [mozilla/foundation.mozilla.org#9600]
### Describe the bug
When there's more than 1 author, it should say "and" between the 2 names
<img width="1336" alt="Screen Shot 2022-11-02 at 11 00 15 AM" src="https://user-images.githubusercontent.com/74557207/199540708-b83515fa-e80a-4155-91c7-78eff24616e8.png">

### To Reproduce
Go to homepage (https://foundation.mofostaging.net/en/privacynotincluded/) and look at the featured article with 2 authors

### Expected behavior
Should say "by Mozilla and Anil" and look something like this
<img width="384" alt="Screen Shot 2022-11-02 at 11 02 26 AM" src="https://user-images.githubusercontent.com/74557207/199540661-f51d1249-0ea4-4d68-95b1-3847115b3958.png">

**Comment by tbrlpld** [comment]
@nancyt1 This is ready for testing on staging

**Comment by mtdenton** [comment]
@nancyt1 I'm QA'ing this so that we can (unfortunately) make a critical change in prod today.

@tbrlpld, I tested on both the homepage and the article page on various sizes, looks good to go. I couldn't find any other articles with dual authors.

**Comment by danielfmiranda** [comment]
Pushed to prod, closing!
