### ISSUE TITLE
DFL 2022 | Events - Text only card - URL field

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9601]
This ticket is to include a URL field to DFL 2022 | Events - Text only card #9398

Currently the _**heading link**_ comes from a page picker, we want to include an option for URL fields that opens in a new tab (as these are expected to be external links). 

The editor would have 2 options: 

- Page chooser
- URL field

**Dev tasks:** 

- Include a URL field
- Add some logic that prevents using both page picker & URL field at the same time
- Include some helper text: _'Please use one of the options below - either the internal page picker or the external URL field'_
- URL link to open in a new tab

Additional context https://github.com/mozilla/foundation.mozilla.org/issues/9398

**Comment by kevinhowbrook** [comment]
This is ready for code review here https://github.com/mozilla/foundation.mozilla.org/pull/9739

Thanks

**Comment by kevinhowbrook** [comment]
Thanks for the review @tbrlpld https://github.com/mozilla/foundation.mozilla.org/pull/9739 has been amended

**Comment by tbrlpld** [comment]
@cdanfon This is now on staging.

**Comment by cdanfon** [comment]
Thanks, looks good to me! 

@gutermul Over to you for testing

**Comment by danielfmiranda** [comment]
Pushed to prod, closing!
