### ISSUE TITLE
DFL 2022 | Landing listing card - URL field

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9602]
This ticket is to include a URL field to the streamfield created from [DFL 2022 | Landing Listing card#9393](https://github.com/mozilla/foundation.mozilla.org/issues/9393)

Currently the _**heading link**_ comes from a page picker, we want to include an option for URL fields that opens in a new tab (as these are expected to be external links). 

The editor would have 2 options: 

- Page chooser
- URL field

**Dev tasks:** 

- Include a URL field
- Add some logic that prevents using both page picker & URL field at the same time
- Include some helper text: _'Please use one of the options below - either the internal page picker or the external URL field'_
- URL link to open in new tab

Additional context https://github.com/mozilla/foundation.mozilla.org/issues/9393

**Comment by kevinhowbrook** [comment]
This is ready to code review here https://github.com/mozilla/foundation.mozilla.org/pull/9741

Thanks

**Comment by kevinhowbrook** [comment]
Thanks @tbrlpld - https://github.com/mozilla/foundation.mozilla.org/pull/9741 has been amended

**Comment by tbrlpld** [comment]
@cdanfon This is now on staging.

**Comment by cdanfon** [comment]
Thanks, LGTM 

@gutermul over to you for testing

**Comment by gutermul** [comment]
looks good to me. thanks.

**Comment by danielfmiranda** [comment]
Pushed to prod! Closing
