### ISSUE TITLE
[PNI QA] Hero article image should pull OG image

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9603]
Currently the hero image pulls the image from the Articles `Hero image` but it should pull from `Share Image`. 

Share image is better because
- It has an aspect ratio closer to what is used on the homepage and therefor it will look better
- Not all articles will have a `Hero Image`
- Our main site typically pulls from the `Share image`

Note: This work is related to related ticket https://github.com/mozilla/foundation.mozilla.org/issues/9606

### AC
- [ ] As a user, I see the `Share Image` on the homepage hero article when that article is features (for this to work the share image needs to be set on the article, which will be required in #9606). 

### Screen caps

Screen cap of homepage feature article
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/1068783/199552526-cd2a669d-f3ed-4c0d-8718-ab6df4102d13.png">

Screen cap of 'Hero image' field in CMS
<img width="625" alt="image" src="https://user-images.githubusercontent.com/1068783/199553696-92a65068-d03e-4bdb-afb3-30b6e9a88a81.png">

Screen cap of 'Share image' field (image that should be used in the homepage feature)
<img width="634" alt="image" src="https://user-images.githubusercontent.com/1068783/199555245-7ebd710d-37d2-4101-9422-172c391f874b.png">

**Comment by tbrlpld** [comment]
@kristinashu Is it more likely for an article to have a share image than a hero image? Would it make sense to fall back to the hero image if no share image is set? Do we need to need to warn editors when they are selecting the featured article and it does have neither share nor hero image?

**Comment by kristinashu** [comment]
Ah this raises something else... the Share Image and Meta Description were recently made required fields on our main blog site https://github.com/mozilla/foundation.mozilla.org/issues/9464 so they should also be required fields for PNI Articles. Should this request be a new ticket or added to this one?

<img width="721" alt="image" src="https://user-images.githubusercontent.com/1068783/199579716-b78e7aa3-6fff-4b00-8577-dcb54e85bf09.png">

**Comment by tbrlpld** [comment]
@kristinashu Though considering the questions this has raised before, maybe combine them here or have the "make required" ticket be blocking to this one here.

**Comment by kristinashu** [comment]
Ok, I've added a note to the first comment in this ticket - _Note: This work is related to related ticket https://github.com/mozilla/foundation.mozilla.org/issues/9606_

I don't think it's necessarily a blocker tho since currently the Hero Image isn't a required field and the hero image looks broken if no hero is set.

Screen caps from staging:
<img width="511" alt="image" src="https://user-images.githubusercontent.com/1068783/199588901-f9d7d3bd-0974-4cfd-a35f-611101121663.png">

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/1068783/199588982-40719c8b-00e2-4194-90aa-c86f26b44f21.png">

**Comment by tbrlpld** [comment]
Thanks @kristinashu. Yea, if that is acceptable we can move a head without it.

**Comment by mmmavis** [comment]
@kristinashu this is ready for QA on staging!

**Comment by kristinashu** [comment]
Thanks @mmmavis! This does meet the AC but I'm noticing a new bug on staging https://foundation.mofostaging.net/en/privacynotincluded/. Do you know it the bug is coming from this PR or from a different one? The issue is that clicking on the hero article on the homepage links to the homepage when it should be linking to the article. 

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/1068783/207119171-6e4fe099-57e6-4dfc-abb0-d95b385acb59.png">

**Comment by mmmavis** [comment]
@kristinashu thanks for catching that. It is indeed a bug my PR introduced. Will submit a fix now.

**Comment by danielfmiranda** [comment]
Just tested out #9836 on staging and can confirm that the bug is fixed. Ready for prod!

**Comment by mmmavis** [comment]
@danielfmiranda thank you!

**Comment by danielfmiranda** [comment]
Pushed to prod! Closing
