### ISSUE TITLE
[PNI QA] Dive deeper and related products sections look misaligned on product pages

### ISSUE THREAD

**Issue by nancyt1** [mozilla/foundation.mozilla.org#9604]
### Describe the bug
Dive deeper and related products sections (or "what to read next section" if visible) misaligned on product pages

<img width="1360" alt="Screen Shot 2022-11-02 at 12 18 31 PM" src="https://user-images.githubusercontent.com/74557207/199578718-c3738b52-1b14-4a32-ab2b-a41a70a82a6b.png">

### To Reproduce
Click on any PNI product and scroll to the bottom where related content are.

### Expected behavior
Squiggles should look like they're on the same line. (screencap from figma)

<img width="1065" alt="Screen Shot 2022-11-02 at 1 57 04 PM" src="https://user-images.githubusercontent.com/74557207/199578704-443a2ce0-c421-4911-ae4a-fc31831b5f37.png">

### Desktop:
Firefox Version 104.0.2

**Comment by tbrlpld** [comment]
@nancyt1 I agree that looks off. I guess in the design they are top aligned with the text, but not quite with the other line.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/24797493/199589423-c2e913a7-70f8-48ef-9498-89400ccd9cc2.png">

**Comment by nancyt1** [comment]
@tbrlpld ah yeah true, top aligned is the better descriptor. But yeah visually it should look like a straight line across the page, even if it technically isn't

**Comment by tbrlpld** [comment]
@nancyt1 This should now be ready for testing on staging.

**Comment by cdanfon** [comment]
@nancyt1 please QA this asap

**Comment by tbrlpld** [comment]
@nancyt1 Have you had a chance to look at this one?

**Comment by nancyt1** [comment]
yes, looks good to me! @danielfmiranda
