### ISSUE TITLE
[PNI] Make the `Share image:` and `Meta description:` required fields on PNI Article pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9606]
### Context:
Raised in https://github.com/mozilla/foundation.mozilla.org/issues/9603#issuecomment-1301100267 and related to https://github.com/mozilla/foundation.mozilla.org/issues/9464

Make the `Share image:` and `Meta description:` required fields on all PNI Article pages (similar to how it is on our main blog site pages)

### Acceptance Criteria:
- [x] As a user I can't publish a PNI Article until I have added a `Share image:` 
- [x] As a user I can't publish a PNI Article until I have added a `Meta description:`

**Comment by danielfmiranda** [comment]
Tested this on staging, can confirm that its working as expected!

**Comment by kristinashu** [comment]
Sorry I forgot about this! Yes, confirmed it's working properly. Thank you!
