### ISSUE TITLE
[PNI QA] Limit of 7 items for ‘News’/’Dive Deeper’ section

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9613]
There’s a limit of 7 items for the ‘News’/’Dive Deeper’ section. Can we remove that limitation? I don’t think it’s necessary because we already truncate the list and the user chooses whether or not to expand to see all related news articles.

![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/16d46654-0868-4b4c-844d-fd8c359a400b)

To replicate:
1. Make sure you're logged into the mofo staging cms
2. Go to: https://foundation.mofostaging.net/en/privacynotincluded/ring-video-doorbell/
3. Access the cms of this page (by clicking the bird in the lower left hand corner, etc)
4. Without changing anything, go to the bottom of the page select "Publish Page"
5. Go to "News Link" and see error

Note: This bug is kind of weird because there are currently products that have more than 7 new link/dive deeper items but you cannot a) add to these items and b) once you try to re-publish the page the error message shows up

# Acceptance criteria 

- [x] As an editor, I am able to publish a product with an unlimited number of news updates added to the "news updates" section. 
- [x] As a site visitor, when I visit a product page I can see only 3 news updates listed in the "dive deeper" section.
- [x] As a site visitor, when I visit a product page that has more than 3 news updates associated I can see and expand the "dive deeper" section with a click on the "show more" button to show all news update links.

**Comment by tbrlpld** [comment]
@beccaklam I think this was added to avoid the layout being weird with the expanded list of more than 7 entries.

**Comment by beccaklam** [comment]
It's going to affect updates to the page if we change any of the content though (for example, if we want to update any of the review content it's not going to let us publish unless we delete some news links). What looks weird with the layout?

**Comment by tbrlpld** [comment]
@beccaklam I think the long space was the reason. But if you think this is not an issue with users if users disclose this we can add remove the limitation. 

<img width="239" alt="Screen Shot 2022-11-07 at 06 53 26" src="https://user-images.githubusercontent.com/24797493/200340610-e162d638-8c12-46fa-b734-594f3d26dd4e.png">

<img width="381" alt="Screen Shot 2022-11-07 at 06 53 21" src="https://user-
images.githubusercontent.com/24797493/200340619-3051f15a-8835-41be-9549-78a19e4c97ad.png">


> It's going to affect updates to the page if we change any of the content though (for example, if we want to update any of the review content it's not going to let us publish unless we delete some news links).

Sorry, I don't understand. Can you add some context?

**Comment by kristinashu** [comment]
Increasing this to a P1 since it is blocking content entry. Currently some products on prod have more than 7 items so staff won't be able to re-publish existing pages.

**Comment by tbrlpld** [comment]
Is this a prod release blocker or could the fix be pushed later on?

**Comment by kristinashu** [comment]
If it's a quick fix then it's a prod release blocker since, as is, it would make content entry difficult.

**Comment by tbrlpld** [comment]
@beccaklam @kristinashu I have added some AC. Can you sanity check them and update if necessary please? Thank you.

**Comment by beccaklam** [comment]
@tbrlpld took a look at the ACs and made some small edits. Let me know if the edits work for you! cc: @kristinashu

**Comment by tbrlpld** [comment]
Thanks @beccaklam, I am not sure what changed, but it looks like my implementation should fit that. 

@danielfmiranda I have the PR ready for review if you have a moment 🙏

**Comment by beccaklam** [comment]
@tbrlpld Just wording! But nothing regarding the implementation 👍

**Comment by tbrlpld** [comment]
@beccaklam @cdanfon This is ready for testing on staging.

**Comment by cdanfon** [comment]
Hey @tbrlpld from now on anything that the design team has worked on will be tested by them.

**Comment by tbrlpld** [comment]
Ok, won't tag you on those anymore then.

**Comment by tbrlpld** [comment]
Thanks @beccaklam.

**Comment by tbrlpld** [comment]
@beccaklam If a ticket passes QA with no needed follow up you can move it forward to "ready for production". We'll close it when it is released.

**Comment by beccaklam** [comment]
Got it thanks!
