### ISSUE TITLE
[PNI] Finish setting up metrics

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9616]
Following up from #9515. Set up metric events once all tickets have been pushed to prod.
**Goals**
- [x] Set up events
   - [x] Featured article
   - [x] Related section to featured article
   - [x] Top “Related/Popular” block on product review, category, article index and article blog pages
   - [x] Bottom “What to read next” block on product review, category and article blog pages
   - [x] Newsletter CTA in product grid
   - [x] Wide Newsletter CTA
~- [ ] Check [dashboard](https://datastudio.google.com/reporting/868245f5-7732-4fa3-a7f3-dd8f39f6666a/page/y8efC)~
~- [ ] Get feedback from design~
~- [ ] Get feedback from stakeholders~
~- [ ] Share in pni production channel~

**Comment by beccaklam** [comment]
Added tags today, waiting for #9670 to be pushed to prod to check if we set up the metrics properly.

**Comment by nancyt1** [comment]
Most IDs are in staging, Daniel is still working on one of them, but the tags are now all published in GTM thanks to Tyler. So after the IDs are on prod the tags should all be working!

**Comment by beccaklam** [comment]
Created follow up ticket #9721 since the PNI IDs did not get pushed to prod in time for us to check the dashboard this sprint.
