### ISSUE TITLE
[PNI] Doing QA for PNI once all tickets land on production

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9617]
The design team will help with QA once all tickets for PNI have landed on production
- [x] Review PNI on production
- [x] Create tickets for any bugs
- [x] Prioritize bugs

**Comment by beccaklam** [comment]
Again, using this [spreadsheet](https://docs.google.com/spreadsheets/d/1TYnQFGOZLSJrHGHvnLhJwBaZUcAyOmTbHNcu65WUv_4/edit?usp=sharing) to track QA. Also added outstanding questions the [design dev notes doc](https://docs.google.com/document/d/1opBAnQH_VjG5eHEe7txpkw6QBTeu79S0MWNT5-m7WnE/edit?usp=sharing).

**Comment by kristinashu** [comment]
I _think_ this is done?
