### ISSUE TITLE
Mozfest | Reposition image in the "image teaser" block

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9621]
Ticket open from the back of #9535

The image doesn't centre vertically when longer text is posted. Attached example:

<img width="1213" alt="Screenshot 2022-11-03 at 15 55 42" src="https://user-images.githubusercontent.com/30226684/199810722-61e52112-b122-4bec-9a08-1ced7da87705.png">

The goal of this ticket is to reposition the image to align with the content in the "image teaser" block.

**Comment by cdanfon** [comment]
Note: Depending on how much content the user includes there's a call to use a vertical image instead of a horizontal one. (Ie add helper text: if more than x characters use 'horizontal' image, if less than x characters use 'vertical' image)

**Comment by cdanfon** [comment]
@tomusher Is this something that you could pick up as well next week please?

**Comment by cdanfon** [comment]
@marcwalsh @kristinashu 'cc

**Comment by tomusher** [comment]
@cdanfon Could you clarify your note? Should a vertical image be suggested used when there is long content, or short content? What character threshold? For reference there are 544 characters in the first paragraph of the attached screenshot.

**Comment by cdanfon** [comment]
Hi @tomusher thanks for checking. 

@marcwalsh this issue has been created from the back of your comment [here](https://github.com/mozilla/foundation.mozilla.org/issues/9535#issuecomment-1302543299). 

Could you confirm what the expected behaviour when using long text would be please?  Would it be something like in the below example? 

<img width="988" alt="Screenshot 2022-11-07 at 14 30 24" src="https://user-images.githubusercontent.com/102978346/200335828-8f0c4791-960f-4f1c-a75e-c209f2dc75b5.png">

We have a couple of options here: 

1. Centre the images in all instances (no matter how much content there is)
2. Recommend editors use vertical images when using more than 540 characters by adding helper text in the block.

**Comment by marcwalsh** [comment]
Thanks @cdanfon - I think I'd like to loop in @kristinashu on this one, as it's more of a design preference. 

Ideally for me it would either sit centre of or at the top of the paragraph text, leaving the title to stand alone.

**Comment by cdanfon** [comment]
Thanks @marcwalsh 

I'm going to adjust the requirement for this ticket with the following: 

1. Image to be in line with the top of the paragraph text (leaving title to stand-alone)
2. Add helper text for editors: If using more than 540 characters using a vertical image is recommended. 

@kristinashu shout if any issues please

@tomusher FYI

**Comment by kristinashu** [comment]
> 1. Image to be in line with the top of the paragraph text (leaving title to stand-alone)

My preference would be the center align all the text (and button) with the image.

I worry that aligning the top of the paragraph with the text looks a little broken for the Data Futures Lab scenario. Screen cap of how it would look:

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/1068783/201711630-ddfee249-6ef0-47bd-baa8-d343e181562e.png">


> 2. Add helper text for editors: If using more than 540 characters using a vertical image is recommended.

I believe images get auto-cropped so adding a vertical image would not help. Cropping is good because it helps keep the page looking structured even if staff upload a few images with different aspect ratios.

**Comment by tomusher** [comment]
Resolved by #9702

**Comment by cdanfon** [comment]
Thanks @tomusher Is this something you can push to staging to be tested by @marcwalsh or do you need a MoFo dev to deploy it?

**Comment by cdanfon** [comment]
Thanks Marc, @danielfmiranda @tbrlpld moving this to ready for production
