### ISSUE TITLE
[PNI] SPIKE | Create metrics tracking for PNI newsletter signup

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9637]
The goal of this ticket is to see if we can track email sign ups from PNI. Design and engineering should work together on this to identify what the user flow is for this process and where we can insert the appropriate metrics tracking technology.

Note from @mtdenton: Implementation will be in a follow-up ticket

**Goals**
- [x] Identify accurate user flow
- [x] Brainstorm possible ideas

**Comment by mtdenton** [comment]
@beccaklam happy to put in some thought work on this during this sprint, I'll give you a shout

**Comment by beccaklam** [comment]
@mtdenton That would be great, thank you!

**Comment by kristinashu** [comment]
Is this done or is more needed?

**Comment by beccaklam** [comment]
This is done!
