### ISSUE TITLE
[PNI] Search form / order by drop down menu are truncated

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#9640]
I noticed we have some truncations with some translations of the search placeholder and in the drop down menu.

### German
https://foundation.mofostaging.net/de/privacynotincluded/
<img width="467" alt="Capture d’écran 2022-11-08 à 18 07 47" src="https://user-images.githubusercontent.com/1294206/200630288-5e2bd092-db71-41db-8d5b-21604a0a9384.png">

### Spanish
https://foundation.mofostaging.net/es/privacynotincluded/
<img width="397" alt="Capture d’écran 2022-11-08 à 18 12 25" src="https://user-images.githubusercontent.com/1294206/200631986-c7343415-3c5d-4afd-bc0e-e05922e4b8a1.png">

### Portuguese
https://foundation.mofostaging.net/pt-BR/privacynotincluded/
<img width="423" alt="Capture d’écran 2022-11-08 à 18 11 52" src="https://user-images.githubusercontent.com/1294206/200631942-7a24fb27-7df8-4a1f-ae64-785408628a84.png">

### French
For French, I’ve made big trade-offs and truncated a word to make it fit, but more room will allow me to use better translations:

https://foundation.mofostaging.net/fr/privacynotincluded/
<img width="381" alt="Capture d’écran 2022-11-08 à 18 12 56" src="https://user-images.githubusercontent.com/1294206/200631249-66da8b4f-2311-41c7-87a0-fddbb2d8b28d.png">

Ideal translation for the placeholder would be "Rechercher parmi tous les produits"
For the drop down: "Du moins effrayant au plus effrayant"

**Comment by mtdenton** [comment]
Thanks @TheoChevalier . @kristinashu I don't know if we want any weigh-in from a design perspective but the obvious solution to me is to just make sure that the underlying white container fits the text regardless of length.

**Comment by kristinashu** [comment]
Yes, if that's possible then that sounds good. Ty!

**Comment by kristinashu** [comment]
Design will mock up an extreme edge case and then work closely with a dev to figure out the best approach.

**Comment by nancyt1** [comment]
Just realized that the creepometer face text also runs off page on mobile. Would be good to have the bubble expand upwards instead of outwards

![IMG_A9DE90A11D7C-1](https://user-images.githubusercontent.com/74557207/207979748-4093cd6d-afbd-4342-9e70-0f2aa480c681.jpeg)

**Comment by nancyt1** [comment]
So I have the [final mockups](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=5609%3A102175&t=vXLlDQxsrT5NRZZP-1) in figma but essentially we're thinking of keeping it simple and just expanding the container to fit any text for both the dropdown, search bar, and creepometer face. There's some additional padding and a fade in for the dropdown. And for mobile, it should break into 2 lines if it doesn't fit. 

@mtdenton I'm not sure which dev is gonna work on this but I'm wondering if you think this is all feasible and your thoughts on how we should break this up for implementation?

**Comment by nancyt1** [comment]
Created a dev ticket (#9870) for this work! Decided to split into multiple smaller tickets
