### ISSUE TITLE
Sign up snippets not syncing across translations

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#9642]
## Describe the bug
Signup snippet changes on mozfest pages are not being synchronized, even after clicking "sync translations".

**From Slack:**
The sign up snippet got removed from the updated English page https://www.mozillafestival.org/en/proposals/ in order to use the full width, but syncing translations doesn’t remove it from translated pages.

## Steps to reproduce

1. Visit https://www.mozillafestival.org/en/proposals/, note that there is no signup snippet set.
![Screenshot 2022-11-08 at 14-18-01 Submit your MozFest Session before December 16th](https://user-images.githubusercontent.com/18314510/200687907-e6ae8480-cb4f-4531-98c3-7529fe4b87eb.png)

2. Visit https://www.mozillafestival.org/fr/proposals/, and note that there is **still** a signup snippet on the page, even after clicking "sync translations".
![Screenshot 2022-11-08 at 14-18-24 Proposez votre session pour le MozFest avant le 16 décembre](https://user-images.githubusercontent.com/18314510/200688015-3c04798e-ee67-4132-a19a-bc9d8056eeee.png)

## Expected behavior

If a mozfest page removes/changes it's linked signup snippet, its localized versions should show the same change after clicking "sync translations".

**Comment by tbrlpld** [comment]
I think it would be good to describe the expected behaviour in a bit more detail. Are no changes carrying over?

**Comment by danielfmiranda** [comment]
Hi @cdanfon this is now on staging and ready to be tested!

# Acceptance Criteria

- [ ] As a user, if I navigate to a given page in a language (such as English), it should provide the same sign-up snippet on all  other localized versions.
EX:
[mozillafestival.mofostaging.net/en/proposals/](http://mozillafestival.mofostaging.net/en/proposals/) vs. [mozillafestival.mofostaging.net/fr/proposals/](http://mozillafestival.mofostaging.net/fr/proposals/)
- [ ] As a content editor, if I remove a sign-up snippet from a page in the dashboard, then it should be removed for all languages for a given page, after selecting "Sync translated pages -> Publish Immediately" in the CMS.  
- [ ] As a content editor, if I add a sign-up snippet to a page from the dashboard, then it should appear for all languages for a given page, after selecting "Sync translated pages -> Publish Immediately" in the CMS.  


# Steps to test:

1. Visit http://mozillafestival.mofostaging.net/en/proposals/ and note that there is no sign up snippet on the right side of the page.
2. Visit http://mozillafestival.mofostaging.net/fr/proposals/ and note that it is the same (no signup snippet set)
3. Edit the page in the CMS https://mozillafestival.mofostaging.net/cms/pages/421/edit/ and add a sign up snippet.
4. Once finished editing, select "sync translated pages" in the CMS, and then "publish immediately".
![Screenshot 2022-11-17 at 15-43-26 Wagtail - Exploring Mozilla Festival](https://user-images.githubusercontent.com/18314510/202583528-7bc0548b-2c2b-4641-aa51-2dbed174bef9.png)
![Screenshot 2022-11-17 at 15-44-06 Wagtail - Update existing translations Call For Proposals](https://user-images.githubusercontent.com/18314510/202583612-eb14d275-7799-43a3-b8ba-06f26b1b675d.png)
5. Visit http://mozillafestival.mofostaging.net/en/proposals/ again, and note the new sign up snippet on the right side
6. Visit the page in any other language, for example http://mozillafestival.mofostaging.net/fr/proposals/, and there should be a sign up snippet as well.

**Note:** If a localized version of the sign up snippet does not exist, it will render the English version


Thanks in advance!

**Comment by danielfmiranda** [comment]
Just tested this out myself and seems to be working as expected 👍

**Comment by cdanfon** [comment]
Looking good, nice one @danielfmiranda !
