### ISSUE TITLE
[PNI] Inconsistent black link hover styles in hero section

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#9650]
# Description

The hero section of the PNI homepage uses 4 different hover styles for links that use black text when not hovered. 

The section in question:
![Screen Shot 2022-11-09 at 06.51.56.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/8359c0e2-5dd0-4be5-b774-ec6cfdf7d8fe)

Menu link (blue with wavy blue underline, but the color of underline and text don't match): 
![Screen Shot 2022-11-09 at 06.52.02.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/5d16c980-319a-4e01-9d90-c73734b4dee7)

Hero article link (black w/ black  underline):
![Screen Shot 2022-11-09 at 06.52.07.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/e502087c-95c0-4ee9-9614-8c99ed932ce8)

Hero related article link (blue, no underline):
![Screen Shot 2022-11-09 at 06.52.12.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/a8b79a1e-5e48-4b95-a5b9-ba4cbfa0334f)

Heading link (different blue, no underline):
![Screen Shot 2022-11-09 at 06.52.17.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/cfc06853-85d8-4028-bde2-df0c3d026dd1)

# Expected behavior

Fewer hover link styles and color variations.

**Comment by kristinashu** [comment]
Design will audit and mock this up and then open a new ticket for dev implementation.

**Comment by ArshErgon** [comment]
well, I think for the `Menu link (blue with wavy blue underline, but the color of underline and text don't match):` this issue #9669 solves the issue.

**Comment by nancyt1** [comment]
Create a few hover state [prototypes](https://www.figma.com/proto/3WWDPe9rii2ZorAa4r9GFG/*Privacy-Not-Included-2023?page-id=5901%3A105881&node-id=5916%3A5765&viewport=585%2C280%2C0.05&scaling=min-zoom&starting-point-node-id=5916%3A5765&show-proto-sidebar=1) to be discuss during crit!

**Comment by nancyt1** [comment]
Opened an implementation [ticket](https://github.com/mozilla/foundation.mozilla.org/issues/10067) for this work
