### ISSUE TITLE
[PNI] Large white space in "related" section on product page on mobile

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#9651]
# Description

There are large amounts of white space in the related section of product pages. 

This is probably a side effect of trying to accommodate long lists of news updates / "dive deeper". A fix would need to account for that case too.

https://foundation.mofostaging.net/en/privacynotincluded/threema/

<img src="https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/cddbc242-7f0f-4361-b5dc-e0d6b57cf6d3" width=300>

# Expected bahvior

The sections size to fit their content and not more.

**Comment by tbrlpld** [comment]
@cdanfon @kristinashu This is ready for testing on staging. 

https://foundation.mofostaging.net/en/privacynotincluded/euki/

**Comment by kristinashu** [comment]
This looks much better! Ready for prod!

**Comment by fessehaye** [comment]
pushed to prod
