### ISSUE TITLE
Update creepy face to show on page load and show introductory text

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9652]
Follow up ticket from #9522

**Description:** Can the creepy face show immediately on page load? Currently it only loads after the user scrolls for a bit (see screen recording below). We are also missing the face that says, "_Scroll to see how creepy people find these products!_".

https://user-images.githubusercontent.com/20977376/200679723-109afff1-a699-46a0-9785-3fbd900f961e.mov

<br></br>
Example of creepy face on page load with the text "Scroll to see how creepy people find these products!"

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/20977376/200682825-5b6531b4-f784-4a86-8f30-1faef8bec635.png">

**Acceptance criteria:**
- [ ] Creepy face shows once the first row of the product grid is visible
- [x] Creepy face has speech bubble that says, "Scroll to see how creepy people find these products!"
- [x] Line-height for **tagline** on mobile should be 1.75rem (instead of 2rem)

**Comment by kristinashu** [comment]
Added this little tagline line-height adjustment mentioned in https://github.com/mozilla/foundation.mozilla.org/issues/9522#issuecomment-1309425116 to the ACs

**Comment by cdanfon** [comment]
@kristinashu One for QA please

**Comment by kristinashu** [comment]
@cdanfon I don't think this is on staging yet - it's just ready for staging.

**Comment by tbrlpld** [comment]
@beccaklam This should now be ready on staging for testing.

**Comment by cdanfon** [comment]
@beccaklam please QA asap please

**Comment by beccaklam** [comment]
Hi, this is looking good! The only thing that is missing is the first acceptance criteria:
"Creepy face shows once the first row of the product grid is visible". Right now the creepy face shows immediately on page load even when the product grid is not visible yet. I think it would be good to hide the face until the grid is visible otherwise it will be out of context. @tbrlpld @cdanfon

**Comment by tbrlpld** [comment]
@beccaklam Would you consider that a release blocker? Otherwise, can you create a follow up ticket?

**Comment by tbrlpld** [comment]
Yes please.
