### ISSUE TITLE
[PNI QA] Space between "Product Reviews" title and product reviews grid too big on homepage and Product Reviews page

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9654]
I'm seeing a space between the "Product Reviews" title and the product reviews grid. Looks like it might be the space where the creep-o-meter face used to be but we no longer need it?
![Screenshot 2022-11-09 at 12.54.02 PM.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/433610c7-ebf8-4e0e-8f3a-b8f49da66bcd)

**Comment by fessehaye** [comment]
being resolved in #9577 closing since this is a dub
