### ISSUE TITLE
[PNI] Improve spacing between tags and "sort by" filter

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9659]
Follow up ticket from #9550:

> This looks much better! Some design could be done to improve where the tag meets "Sort" but that should be a follow up!

<img width="969" alt="image" src="https://user-images.githubusercontent.com/1068783/200963660-f7746e74-94ec-47eb-912e-39d73617996e.png">

**Comment by beccaklam** [comment]
Adding that this still looks squished on tablet when the desktop design is in use:
![IMG_226DFC1A0631-1](https://user-images.githubusercontent.com/20977376/201831295-45b24b50-e4a1-40af-b081-2097b7485722.jpeg)

**Comment by kristinashu** [comment]
Design will mock this up and then open a new ticket for dev implementation.

**Comment by nancyt1** [comment]
I mocked this up in [figma](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=5609%3A102175&t=UCOqvUJixeY29Pqv-1) to go along with ticket #9640 and created a new implementation ticket (will add here)
