### ISSUE TITLE
[PNI] Category order in drop down should reflect desired order 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9691]
**Context:** 
Jen updated the order of the categories in the CMS. The order is properly reflected in the main nav however the order is reversed in the drop down menu. 

**Acceptance Criteria:**
- [ ] As an editor I can manually define a sort order in the back end for categories
- [ ] As a site visitor I can see the manually defined category order in the dropdown (more categories) nav menu

Screen cap of CMS on staging:
<img width="554" alt="image" src="https://user-images.githubusercontent.com/1068783/201714477-68ee6c02-c629-4536-a779-ae548a939bf9.png">

Screen cap of the nav on staging showing the wrong order in the nav:
<img width="882" alt="image" src="https://user-images.githubusercontent.com/1068783/201714538-9e30ca28-5fba-4df0-9d6a-1e4892a30088.png">

**Comment by mtdenton** [comment]
Looking to negotiate this into our current sprint, removing the label for now.

**Comment by tbrlpld** [comment]
@kristinashu This is on staging ready for testing.

**Comment by kristinashu** [comment]
This looks good on staging and is ready for prod!
