### ISSUE TITLE
[PNI QA] Search on about and article pages not working

### ISSUE THREAD

**Issue by nancyt1** [mozilla/foundation.mozilla.org#9693]
### Describe the bug
Search not working on article, article index, and about pages. Could be related to ticket #9553 

**Steps to reproduce the behavior:**
1. Go to [Articles](https://foundation.mozilla.org/en/privacynotincluded/articles/) or [About](https://foundation.mozilla.org/en/privacynotincluded/about/why/) 
2. Click and type in search bar
4. See error (which is nothing happening)

<img width="1680" alt="Screen Shot 2022-11-14 at 12 54 39 PM" src="https://user-images.githubusercontent.com/74557207/201779318-d74630cf-69e3-4dcc-a7fb-d80e7c3a4db9.png">

### Expected behavior
Change page to bring up grid of products or empty search results. 

If possible, for pages that aren't product reviews, it could be good to press "enter" to search and it brings them back to the product review pages so it's less confusing where they are and what happened to the content they were just viewing.

**Comment by beccaklam** [comment]
This appears to only affect about and article pages using the desktop search, if the page is using mobile search (the drop down blue bar), search appears to work?

**Comment by kristinashu** [comment]
I believe this was addressed in https://github.com/mozilla/foundation.mozilla.org/issues/9553 but there are still some issues so here's follow up ticket https://github.com/mozilla/foundation.mozilla.org/issues/9712

@nancyt1 @beccaklam please reopen this ticket if I'm wrong!
