### ISSUE TITLE
[PNI QA] Empty speech bubbles on category pages (chrome only)

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9694]
The speech bubble for the creepy face appears empty on category pages. This bug seems to only appear on chrome mobile (tested on iOS).
https://images.zenhubusercontent.com/76596293/889109d7-6999-407e-ae83-38362dff2dcf/screen_recording_2022_11_14_at_1_57_13_pm.mov

**Comment by fessehaye** [comment]
Looks resolved
