### ISSUE TITLE
[PNI QA] White space below "related products" on mobile (all browsers)

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9696]
There are two large areas of white space below the "dive deeper" and the "related products" section on mobile for product review pages. 

https://images.zenhubusercontent.com/76596293/1853e640-3c4f-496d-9f7f-c9b38e297976/screen_recording_2022_11_14_at_1_42_43_pm.mov

**Comment by mtdenton** [comment]
Duplicate of #9651 , closing
