### ISSUE TITLE
[PNI QA] Text flowing behind tabbed section of product review page

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9697]
This could be related to the removal of the previous sticky category nav but now you can see text flowing behind the tabbed section of the product review page on mobile. This may be solved once we find a solution for the nav from this ticket: #9589

https://images.zenhubusercontent.com/76596293/fdc3c38c-780a-461a-9a09-f8c650d72029/screen_recording_2022_11_14_at_1_41_09_pm.mov

**Comment by tbrlpld** [comment]
@beccaklam This is ready for QA on staging: https://foundation.mofostaging.net/en/privacynotincluded/garmin-epix/

**Comment by beccaklam** [comment]
This is good to go! Thank you @tbrlpld !
