### ISSUE TITLE
[PNI QA] Squiggly underline is missing on tablet (all browsers)

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9701]
The squiggly blue underline for the main nav's selected state is missing on tablet. Though, this only applies when the "desktop" views appears on tablet.

**Current:**
![IMG_1E0A1D800B2D-1.jpeg](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/e9cdc223-9dda-42ce-90a1-2f565addda1c)

**Comp:**
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/f4317ad3-db7b-4147-8039-aec8a08340c3)

**Comment by mmmavis** [comment]
Ah this seems to be a Safari bug. The cause of it is described [here](https://github.com/mozilla/foundation.mozilla.org/issues/9610#issuecomment-1349250171). I'm filing PR #10178 to address a few active nav related issues.

**Comment by beccaklam** [comment]
Closing this ticket as we are evolving the main nav/hover state in https://github.com/mozilla/foundation.mozilla.org/issues/10067 and those are the changes that should be implemented.
