### ISSUE TITLE
Creat a GitHub action to add 'needs grooming' label to any ticket added to the repo

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9708]
TASK: action being added to GitHub

The requirement is that every time a ticket gets added to the repo the label 'needs grooming' automatically gets added. 

**Context**: 

In the 'Backlog' column currently, there's no way of defining if the ticket has or has not been groomed. This would make tracking tickets that need to be groomed easier when looking at ZenHub. 

By automatically adding the label to any ticket that has been created we ensure that a manual action is required to mark the ticket as 'groomed' (by removing the label). 

The expectation is that a user (product owner, dev, designer, dm) would remove the label if the ticket has been groomed.

**Comment by tbrlpld** [comment]
@mtdenton Looks like some rule on the organization is preventing action created in #9730 from working. 

I guess we could fork the action to get that working.

**Comment by mmmavis** [comment]
Alternatively, we can update GitHub ticket templates in the repo to always include the `needs grooming` label. Though this is not as nice as having GitHub action set up.

**Comment by tbrlpld** [comment]
@mmmavis That actually sounds like the simpler solution 🤔 I think the only place this fails is when issues are created through the Zenhub interface. I am not sure that uses the GitHub issue templates.

**Comment by cdanfon** [comment]
That's a good point @tbrlpld I've just checked and it doesn't:

<img width="569" alt="Screenshot 2022-11-22 at 14 49 19" src="https://user-images.githubusercontent.com/102978346/203344545-9866d940-ba8e-43ec-a581-45e3bc2c4437.png">

**Comment by cdanfon** [comment]
I've gone ahead and created a follow up ticket from this one #9746

**Comment by tbrlpld** [comment]
I have remove the failing workflow in #9749
