### ISSUE TITLE
[PNI] SPIKE | Image Deferment

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9709]
Placeholder ticket to address slow loading on PNI. Some recorded pain points:

> From Nov 14 QA 
> [Rebecca] Loading category pages can sometimes take a long time, wondering if we have anything in the works to speed things up? 
    [Nancy] +1, especially when you click a category page from About or Articles. Usually loading is fine from the homepage or product reviews page +1

> [Rebecca] Not sure if anyone else is noticing this but when I use PNI on mobile touch seems delayed a lot of the time? I often have to click a filter, or the search icon, three times before something happens?
    [Kristina] I’m getting this really bad on my phone in Chrome

cc: @mtdenton

**Comment by kristinashu** [comment]
Could this be related to https://github.com/mozilla/foundation.mozilla.org/issues/9545?

**Comment by mtdenton** [comment]
> Could this be related to #9545?

Lack of deferment may be part of it, but @tbrlpld thinks the root cause is more likely to be inefficient database querying.

**Comment by tbrlpld** [comment]
@kristinashu #9545 was why I asked is the above issues were occurring in logged-in state, but @beccaklam had clarified that the issues described above happen when not-logged-in.

**Comment by tbrlpld** [comment]
This might get more tricky (so good thing it's a spike), because I just had a look and `loading="lazy"` is already defined. But, it also does not appear to be respected. When I load the page all images get loaded before the JS is loaded. Something is off here. 

<img width="2030" alt="Screen Shot 2022-11-17 at 07 06 40" src="https://user-images.githubusercontent.com/24797493/202482525-62191559-aee6-498e-b3c5-7440e624abfc.png">


There might also be an opportunity here by defining a few more source options for the browsers to decide which image to load. E.g. on mobile we display the image at 170x170, but load 600x600 or even 720x720 on retina displays. 

```html
<picture class="product-thumbnail">
<source srcset="https://assets.mofoprod.net/network/images/Euki.2e16d0ba.fill-360x360.png 1x, https://assets.mofoprod.net/network/images/Euki.2e16d0ba.fill-720x720.png 2x">
<img class="product-thumbnail" loading="lazy" src="https://assets.mofoprod.net/network/images/Euki.2e16d0ba.fill-600x600.png" alt="link to Euki">
</picture>
```

**Comment by beccaklam** [comment]
@tbrlpld Oh that makes sense. I do have a memory of our old back end devs implementing something that sounded like lazy loading so I was a bit confused about what happened to that work.

**Comment by cdanfon** [comment]
**[TIMEBOX TO 2 HOURS]**

**GOAL**: understand the reason why is not currently working and create a follow ticket with the steps to fix it.

**Comment by tbrlpld** [comment]
@fessehaye I came across this over the weekend: https://web.dev/browser-level-image-lazy-loading/#images-should-include-dimension-attributes

I think the missing size could be what is leading to all the images being immediately loaded although they are marked for lazy loading: https://web.dev/browser-level-image-lazy-loading/#images-should-include-dimension-attributes

**Comment by fessehaye** [comment]
Reported findings on https://github.com/mozilla/foundation.mozilla.org/pull/9792
