### ISSUE TITLE
[PNI QA] Fix hover state color in the Newsletter signup button after voting 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9710]
### Describe the bug
Hover state for both the "Sign up" and the "No thanks"  buttons are incorrect. 

### To Reproduce
1. Go to a product page https://foundation.mozilla.org/en/privacynotincluded/eufy-robovacs/
2. Vote on the creepiness of the product
3. See Newsletter sign up prompt (note that you will only see this is it's your first couple of times voting)
4. Hover over "Sign up" and "No thanks" to see the styling error

### Expected behavior
Text color should remain the same on hover while the button color changes, like the other sign up buttons

### Screenshots
Screen cap from production:

<img width="756" alt="Screen Shot 2022-11-16 at 6 40 20 AM" src="https://user-images.githubusercontent.com/1068783/202260632-eb5ce295-28dc-485d-b9a7-cb89c45a9b27.png">

**Comment by fessehaye** [comment]
@kristinashu can you check this on staging?

**Comment by kristinashu** [comment]
Looks good, ready for prod!
