### ISSUE TITLE
[PNI QA] Search is showing different results depending on where you search from

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9712]
Related to https://github.com/mozilla/foundation.mozilla.org/issues/9693 & https://github.com/mozilla/foundation.mozilla.org/issues/9553

### Describe the bug
Searching for `amazon` on the Product Reviews page shows:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/1068783/202784502-c8772176-e9c4-45c6-870e-7a33d3299fa4.png">

while searching for `amazon` on the Articles page shows less accurate results:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/1068783/202284099-42505ad3-a299-4a7f-ba36-499b08a2ec6f.png">

People have also noted that desktop and mobile can show different results.

### AC
- [ ] As a user, I see the same relevant search results no matter where on the site I search from or what my browser width is

@mtdenton putting this as a P1 since we know a high portion of users use search

**Comment by mtdenton** [comment]
@cdanfon @fessehaye Let's make sure we get this groomed up first thing Monday.

**Comment by tbrlpld** [comment]
@beccaklam I think something went wrong when uploading the example images, because the results look the same to me.

**Comment by mmmavis** [comment]
> As a user, I see the same relevant search results no matter where on the site I search from or what my browser width is

Hello @kristinashu @fessehaye  I'm reviewing Simon's PR and wondering what the expected order the search results should be in. How do we define relevance? I noticed that "relevance" isn't listed in the sorting dropdown. If we always show most relevant search results first, should `relevance` be part of the dropdown options?

**Comment by kristinashu** [comment]
You nailed it @mmmavis! Yes, `relevance` is `name` first, and then `company`, and then `blurb`

@fessehaye @beccaklam and I ended up talking about the dropdown sort order a bunch today and how it is confusing. We have some notes [here](https://docs.google.com/document/d/1opBAnQH_VjG5eHEe7txpkw6QBTeu79S0MWNT5-m7WnE/edit#heading=h.fs3gtczc7i18). For the scope of this ticket, we're just focusing on making things the same across all page. There will be follow up tickets to resolve the confusion caused by the sort order.

**Comment by mmmavis** [comment]
@kristinashu Thanks! Will check out the doc.

**Comment by fessehaye** [comment]
@kristinashu this is ready for staging

**Comment by kristinashu** [comment]
Looks good, ready for prod!
