### ISSUE TITLE
ReferenceError when visiting PNI Articles pages

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#9714]
### Describe the bug
ReferenceError when visiting PNI Articles pages

### To Reproduce
1. Open browser's dev tool
2. Visit https://foundation.mozilla.org/en/privacynotincluded/articles/
3. See `ReferenceError` in console

### Expected behavior
No ReferenceError

### Screenshots
<img width="712" alt="image" src="https://user-images.githubusercontent.com/2896608/202317098-5e951834-4f1c-40e8-bc20-eb88054e8250.png">

**Comment by mmmavis** [comment]
@mtdenton @cdanfon Apologies as I'm probably hijacking the usual ticket triage flow. I just created this ticket and self-assigned myself. I have the fix and will submit a PR once I figure out my GitHub SAML SSO setting. Please help apply the right Zenhub tags to this ticket. Thank you.

**Comment by cdanfon** [comment]
Hey @mmmavis thanks for this. 

I've assigned the sprint label and moved the ticket to 'in progress'

**Comment by mmmavis** [comment]
@fessehaye Could you help review this on staging, please?

**Comment by fessehaye** [comment]
Looks good ready for prod
