### ISSUE TITLE
[PNI] Create 'Reflections' Deck

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9717]
**Goal:**
Create PNI reflection/retro deck and perhaps create a template for retro/reflections based the deck previously created for the YouTube retro.
- [ ] Create deck based on YouTube deck
- [ ] Add as much content as possible for now
- [ ] Get feedback from design
- [ ] Share with larger team?

**Comment by nancyt1** [comment]
Opened [ticket](https://github.com/MozillaFoundation/Design/issues/1108) in other repo
