### ISSUE TITLE
[PNI] Implement sticky nav

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9720]
Implementation ticket for design ticket #9589

### Goal Description:
Implement sticky nav functionality for PNI's category nav

### Links
[Figma File](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=5171%3A93008&t=qIBGqUXhA8SnRb7n-1)
[Redpen](https://redpen.io/p/wy75eeaf54e8ebcc04)

### Acceptance Criteria:
- [ ] As a user I can see the full PNI nav on page load (see image 1)
- [ ] As a user when I start scrolling down the page on PNI, and the main nav is longer visible, I see that the category nav becomes sticky whereas the upper nav stays out of sight (see image 2)
- [ ] As a user when I start scrolling back up, before I am at the top of the page, the full nav appears again and is sticky (see image 3)
- [ ] As a user I see this behaviour on mobile, tablet and desktop screens

**Image 1**
![Menu on page load.jpg](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/9fd0d6cc-9cc0-4b3a-80de-25dee0cbe415)

**Image 2**
![Sticky Nav Scroll Down.jpg](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/da61f73e-9974-4dad-8c84-b2a99c23ec8f)

**Image 3**
![Sticky Nav Scroll Up.jpg](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/b4273e95-2994-49cd-a080-ca5defb4d964)

**Comment by ArshErgon** [comment]
Hey @beccaklam  I would like to work on this, can you please assign it to me?

**Comment by fessehaye** [comment]
@beccaklam can you check this on staging?

**Comment by beccaklam** [comment]
@fessehaye Hey Simon, this looks to be working well on desktop and tablet screen sizes, but on mobile or at the mobile screen size I can't seem to access the drop down menu?

https://user-images.githubusercontent.com/20977376/212381844-c4169f1c-7855-4012-82cb-0bb1352da622.mov

**Comment by fessehaye** [comment]
@beccaklam addressed feedback on staging

**Comment by beccaklam** [comment]
@fessehaye This appears to be fixed! :) Looks ready to go to me!
