### ISSUE TITLE
[PNI] Change 'Submit a product' link to new Typeform

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9722]
Out of an abundance of caution, the security team at Mozilla is recommending we review and turn off data collection on Google Forms because of a bug where old Google forms have leaked information submitted by form responders through their URL shorteners.

So we've created a Typeform to replace the google form "Submit a product" link that needs to be updated on the site.

![Screenshot 2022-11-18 at 12.21.39 PM.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/a7b7b030-56b7-4015-9cbf-ef0ccd117592)

**Assets**
Typeform link: https://mozillafoundation.typeform.com/to/oWfci8Ee

**Acceptance criteria:**
- [x] The updated 'Submit a product' links to the new [typeform](https://mozillafoundation.typeform.com/to/oWfci8Ee) and no longer to the [old google form](https://forms.gle/UefDgjEU85Xwcf8C8)
- [x] Typeform link opens in a new tab

**Comment by tbrlpld** [comment]
@beccaklam "Could this form be made into a lightbox so people don't end up leaving our site?" is not really an acceptance criterion and will increase the amount of work. 

Might be worth a separate ticket.

**Comment by beccaklam** [comment]
@tbrlpld Yup I made a follow up ticket here: #9724!

**Comment by mmmavis** [comment]
Changes are now on staging! https://foundation.mofostaging.net/en/privacynotincluded/

@cdanfon @beccaklam tagging you both as I don't know who normally should verify changes on staging.

**Comment by beccaklam** [comment]
This looks good to go from my end!

**Comment by kristinashu** [comment]
This is live! @mmmavis you can now close this ticket please!

**Comment by fessehaye** [comment]
pushed to prod
