### ISSUE TITLE
[FRU] Add Fundraise Up JavaScript snippet

### ISSUE THREAD

**Issue by mtdenton** [mozilla/foundation.mozilla.org#9726]
In order to test and utilize Fundraise Up capabilities, we'll need to add the following snippet globally into the `<head>` of our pages:

```
<!-- Fundraise Up: the new standard for online giving -->
<script>(function(w,d,s,n,a){if(!w[n]){var l='call,catch,on,once,set,then,track'
.split(','),i,o=function(n){return'function'==typeof n?o.l.push([arguments])&&o
:function(){return o.l.push([n,arguments])&&o}},t=d.getElementsByTagName(s)[0],
j=d.createElement(s);j.async=!0;j.src='https://cdn.fundraiseup.com/widget/'+a;
t.parentNode.insertBefore(j,t);o.s=Date.now();o.v=4;o.h=w.location.href;o.l=[];
for(i=0;i<7;i++)o[l[i]]=o(l[i]);w[n]=o}
})(window,document,'script','FundraiseUp','ADCYPWMX');</script>
<!-- End Fundraise Up -->
```
Our CSP directives will also have to be updated to allow these scripts to load on the page. Details can be found [here](https://help.fundraiseup.com/can-fundraise-up-be-used-on-a-site-with-a-csp)

A nonce attribute will need to be added to the opening `<script>` in the snippet above. Example:
`<script nonce="{{request.csp_nonce}}"`

### Dev Tasks
- [x] Add the above snippet to `base.html` or by other means to globally load the FRU snippet. Include the `nonce` attribute in the `script` tag.
- [x] Update the CSP configuration to allow for FRU assets to load in browsers on both the staging and production sites.

### Acceptance Criteria
- [ ] As a developer, I can see the Fundraise Up script load in browser developer tools site-wide.
- [ ] As a user, if I navigate to https://foundation.mozilla.org/en/?form=FUNWTEYJTEM, a lightbox pops up with a Fundraise Up donation form.

**Comment by danielfmiranda** [comment]
Hi @mtdenton! Have a quick question for when this gets merged:

On the link that you posted regarding the CSP updates, they list optional URLs that we can add alongside the required ones:

```
connect-src
  fndrsp.net
  fndrsp-checkout.net
  *.fundraiseup.com
  *.stripe.com
  *.paypal.com // optional, for PayPal payments
  *.plaid.com // optional, for US bank transfers or stock donations
  pay.google.com // optional, for Google Pay
  *.mastercard.com // optional, for Click To Pay
  *.checkout.visa.com // optional, for Click To Pay
  api.addressy.com // optional, for UK based accounts
```

I was wondering which of these optional payment processors we want enabled?

Thanks!

**Comment by mtdenton** [comment]
@danielfmiranda per Sam, let's enable all of them for now.

**Comment by danielfmiranda** [comment]
Thanks @mtdenton! 

Just updated the CSP variables and gave it a test on staging, looks good to me!:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/18314510/204612233-64d289c6-d535-4458-b0f4-40479fa66421.png">

**Comment by danielfmiranda** [comment]
# Steps to test:
1. Visit https://foundation.mozilla.org/en/?form=FUNWTEYJTEM
2. The Fundraise Up Modal from the screenshot above should load in correctly

**Comment by danielfmiranda** [comment]
It appears this has been pushed to prod already, I have tested both staging and prod and can confirm that this is working. Moving to the next lane
