### ISSUE TITLE
[PNI] Open external links in a new tab

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9743]
PNI has a lot of external links to provide our information sources and for further reading. Most of these links open within the same tab as PNI which makes it look like there's a higher bounce rate and lower time spent on the page even though it's actually a really good engagement if people want to learn more. Making external link open in a new tab will give more accurate analytics. 

### AC
- [x] As a user, if I click on a link under "Dive Deeper" on a product page then the link opens in a new tab
- [x] As a user, if I click on "Submit it here" in the **Ask Jen** section on the homepage then the Typeform link opens in a new tab
- [x] As a user, if I click a link under "In the press" on the homepage then link will open in a new tab
- [x] As a user, if I click on the "Privacy Notice" link in the newsletter sign up model then the link opens in a new tab

### Screen caps

Dive Deeper at the bottom of product pages https://foundation.mozilla.org/en/privacynotincluded/eufy-robovacs/
<img width="300" alt="image" src="https://user-images.githubusercontent.com/1068783/203143984-b836e440-ab36-4698-ac45-4e7914382849.png">

Homepage 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/1068783/203156614-71306d1c-01a3-4289-92f1-88f6d5c17a27.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/1068783/203156646-81bb129f-5b45-45b3-95bf-72bf1c8190ae.png">
<img width="584" alt="image" src="https://user-images.githubusercontent.com/1068783/203157531-8396d196-030f-486f-b08c-de3083d4e649.png">

### Note the list of known links
**Homepage & Category pages**
- Typeform link for Ask Jen 
- In the press links
- "Submit a product" is covered in https://github.com/mozilla/foundation.mozilla.org/issues/9722  
- Footer is out of scope
- CTA modal link (this will typically be a donate ask or a petition within the site - can external links to a new tab but internal be within the same tab?)
- Newsletter sign up model 

**Product detail page**
- Company link (done)
- Links within criteria (done)
- Dive Deeper links

**About pages**
- Will be done as part of https://github.com/mozilla/foundation.mozilla.org/issues/9527

**Comment by mtdenton** [comment]
@mmmavis considering this was unplanned, feel free to pull #9603 from your sprint if you feel that you have too much.

**Comment by fessehaye** [comment]
@kristinashu this is on staging

**Comment by kristinashu** [comment]
All good, thank you!
