### ISSUE TITLE
Update GitHub templates to include 'needs grooming' label by default

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9746]
This is a follow-up ticket from [Create a GitHub action to add 'needs grooming' label to any ticket added to the repo #9708
](https://github.com/mozilla/foundation.mozilla.org/issues/9708)

The requirement is to update the following GitHub templates to include the label 'needs grooming' by default: 

- Design to Dev Handoff
- Bug report
- Code cleanup
- Implementation issue
- Feature request
- Design to Dev Handoff
- Other issue

**Comment by mmmavis** [comment]
- Existing templates can be found  https://github.com/mozilla/foundation.mozilla.org/tree/main/.github/ISSUE_TEMPLATE
- GitHub regarding how to create issue template: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by mmmavis** [comment]
I don't remember if we have a different ticket for this -- it would be awesome if we could also audit through the existing ticket templates to make sure the templates are still valid and relevant.

**Comment by tbrlpld** [comment]
I wanted to flag that updating the issue templates does not work for issues created through Zenhub. 

Maybe there is something we can do with a Github Action to add the label to every new issue.

**Comment by tbrlpld** [comment]
Never mind.... https://github.com/mozilla/foundation.mozilla.org/issues/9708

**Comment by tbrlpld** [comment]
I don't think there is anything to QA on staging here though.

**Comment by tbrlpld** [comment]
I can confirm that the label is added when creating a new issue (with any of the templates) through GitHub.
