### ISSUE TITLE
[PNI] Increase padding at the bottom of 'What to read next' sections

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9761]
The margin bottom for 'What to read next' sections should be closer to 120px, currently it is only 3rem (48px).
![Screenshot 2022-11-24 at 10.48.44 AM.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/c05252ec-1ef1-4d42-9972-d11f7475d563)
This was found during QA of the category page but it should also be applied any where the 'What to read next' component is found.

Acceptance Criteria
- [ ] The bottom margin of the 'What to read next' component is closer to 120px or 7.5rem or whatever is the closest figma token.

**Comment by fessehaye** [comment]
@nancyt1 Would you be able to check this since Becca is away?

**Comment by fessehaye** [comment]
currently on staging

**Comment by nancyt1** [comment]
Bottom padding looks good! Per slack message, it'd be great to add 1 more rem to the top margin (3rem to 4rem) but other than that looks good!

**Comment by danielfmiranda** [comment]
Pushed to prod! Closing
