### ISSUE TITLE
MozFest sign up snippet in the footer appear untranslated

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#9767]
While the snippet used for the sign up block in the footer [is translated](https://foundation.mozilla.org/cms/snippets/wagtailpages/signup/edit/191/), it’s still showing up untranslated: https://www.mozillafestival.org/es

<img width="593" alt="Capture d’écran 2022-12-02 à 18 13 57" src="https://user-images.githubusercontent.com/1294206/205348765-877f3a69-bfb6-499a-894e-aa2a98340105.png">

**Comment by danielfmiranda** [comment]
Tested this on staging and can confirm that its working as expected:

### English:
<img width="788" alt="Screenshot 2022-12-07 at 3 53 08 PM" src="https://user-images.githubusercontent.com/18314510/206322572-8ed9f1a4-a5e8-4245-a939-952f97d11785.png">

### French:
<img width="788" alt="Screenshot 2022-12-07 at 3 53 20 PM" src="https://user-images.githubusercontent.com/18314510/206322574-03e42539-7181-4c76-93c1-7ffc19e12b90.png">



Ready for prod!
