### ISSUE TITLE
Opportunity pages > multi page-menu behaviour

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#977]
I was wondering if we could fix a behaviour we are currently having in the multi-page menu, since this model of menu will also be used on the Fellowship Pages. The issue is that, once user select a category on the menu, the category doesn't stay visible

Current behaviour (once I click "Video" I still see "Net Neutrality Groups"):
![current-behaviour](https://user-images.githubusercontent.com/22157921/35163036-35753256-fcfa-11e7-960a-0c41b0a4c4fe.gif)

It was designed to have the category replaced on top once users click on that.
![desired-behaviour-opt1](https://user-images.githubusercontent.com/22157921/35163107-7d1c8b22-fcfa-11e7-8988-8bdcdce0388f.gif)

If this is too complicated to do, we could just have the word "menu" on top, always visible and as users select their option, it is still highlighted, but hidden under menu. 
<img width="344" alt="image" src="https://user-images.githubusercontent.com/22157921/35163141-9961a826-fcfa-11e7-80ae-b15f64268a3f.png">

@alanmoo @xmatthewx I assigned this ticket to you both to : 1. get your opinion on this issue (if you think there is another solution I am not seeing) and 2. triage this ticket

**Comment by alanmoo** [comment]
As far as I can see, you're absolutely right, this is a bug and should show the current page. I think "Menu" would be too confusing.

Let's figure out #830 first, and then we can tackle this.

**Comment by xmatthewx** [comment]
I agree totally. 1) Let's attempt to show current selection. If that's impossible for some weird reason, Menu is our best fallback. 2) This is less important than 830, but still pretty important. Thanks @taisdesouzalessa for catching this.

**Comment by alanmoo** [comment]
I just poked at the code, I don't think it's too difficult to show, we just need the right mezzanine tag swapped out in one file.

**Comment by taisdesouzalessa** [comment]
@alanmoo I did some studies in how this top menu could behave and talked to @mmmavis about what could be the best behaviour for the users. We both agree that something like the example below would be a better user experience. Wondering if you think it costs lots of time to implement something like that. If so, we can go with original plan and do that later on, after MVP.

![mobile-menu-behaviour-small](https://user-images.githubusercontent.com/22157921/35364461-219820a8-0124-11e8-841c-fb3d437be68b.gif)

**Comment by alanmoo** [comment]
Seems reasonable, at first glance anyway.

**Comment by anweshknayak** [comment]
cannot get to this view. Can anyone help ?

**Comment by alanmoo** [comment]
The pages in screen shots don't specifically exist. https://foundation.mozilla.org/opportunity/miti/ is an example of that kind of page though.

**Comment by mmmavis** [comment]
[This PR](https://github.com/mozilla/foundation.mozilla.org/pull/1020) should address this mobile multi-page nav issue we are trying to fix here. Just a note that this fix is part of the WIP fellowships minisite work so the change won't be live until we are ready to launch the fellowship site.

**Comment by xmatthewx** [comment]
I checked the PR. The mobile nav in it works as expected. When that lands, we can double-check and then close this. 🎊

**Comment by kristinashu** [comment]
@mmmavis since Fellowship pages won't be launching as soon as expected, can this issue become a pull request separate from the fellowship work? This way it can fix the dropdown on the Opportunity pages asap.

**Comment by mmmavis** [comment]
@kristinashu yup, I'll have a PR by end of the week.

**Comment by kristinashu** [comment]
Yay! 🥇

**Comment by kristinashu** [comment]
Yay looks good to me @mmmavis but @taisdesouzalessa would know better!

**Comment by taisdesouzalessa** [comment]
It looks great on desktop, thanks, Mavis!!! :). The only issue we are having is that the menu disappears when we see it on the phone (not responsive mode viewport but in real devices). I remember this is an issue we had in the past with this menu disappearing.

**Comment by taisdesouzalessa** [comment]
True @kristinashu - I do see when it I am signed in on staging on my phone. If it is just staging maybe it doesn't need to be fixed, for now, I guess?

**Comment by kristinashu** [comment]
Yeah, let's keep this ticket focused on the menu name update. I believe there are separate tickets for the staging issue. 

So just need to fix the two lines of underline issue you spotted!

**Comment by mmmavis** [comment]
I just filed a PR to fix the multi-line text link bug!

**Comment by alanmoo** [comment]
Changing the pages to "published" on staging (at the bottom of the edit page view in the admin) should make the nav show up when you're logged out.

**Comment by mmmavis** [comment]
@taisdesouzalessa https://foundation.mofostaging.net/opportunity/mavis-test-a-long-title-page-hello-there/pudding-jelly-o-sugar-plum-wafer-powder/ ready for review again!

**Comment by taisdesouzalessa** [comment]
Looks good to me! Tks @mmmavis :). Closing this issue since we are focusing on highlight only here. Feel free to reopen it if needed.
