### ISSUE TITLE
Make sure GA4 / GTM are respecting browser's Do Not Track preference

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#9782]
We set up [our own check](https://github.com/mozilla/foundation.mozilla.org/blob/main/source/js/common/google-analytics.js#L7-L26) a while back to determine user's Do Not Track preference and conditionally fire GA script only if user's DNT was `false`.  We should do the same check for [GTM script in the codebase](https://github.com/mozilla/foundation.mozilla.org/blob/main/network-api/networkapi/templates/pages/base.html#L38-L42) (i.e., remove code snippet from `base.html` and update [this](https://github.com/mozilla/foundation.mozilla.org/blob/main/source/js/common/google-analytics.js#L49-L74) to include `nonce`). Or alternatively, we may be able to handle that by setting up the right config on GA4/GTM side so we don't have to write our own script to deal with this on every web property we own.

I don't know much about GTM but this post seems useful: https://www.analyticsmania.com/post/respect-do-not-track-parameter-google-tag-manager/

(Please feel free to update the following list)

If possible, please set up DNT config on GA4/GTM for
- Foundation site
- Pulse
- Common Voice

And provide instructions if there are changes need be made to the codebase.

**Comment by cdanfon** [comment]
Hey @mmmavis just checking with the TBX folks about this

**Comment by cdanfon** [comment]
Hey@mmmavis I've heard back from the TBX folks, this is certainly something we could support with.

@mtdenton @kristinashu 

I've gone ahead and checked what would be involved in Mavis's suggestion above: _**GA4 / GTM to respect browser's Do Not Track preference**_  

It is estimated to take between 1.5/2 days to be completed including: 

1. writing the datalayer push code snippet and sending over for a MoFo to implement
2. modifying the snippet as needed and adding it to all pages
3. setting up the right datalayer variable and triggers in GTM
4. configuring tags to fire (or not fire) on the appropriate DNT triggers
5. testing, etc

Let me know if this is something you'd like to go ahead and I can check the team availability and look to get this scheduled in the new year. 

@bheasman 'cc

**Comment by kristinashu** [comment]
Great catch Mavis! @mtdenton this seems pretty critical?

**Comment by ollyw1** [comment]
Hello Mozilla team!

I'm Olly, one of the analysts at Torchbox, and I have been sent to help. I have had a look at the doNotTrack issue and have hopefully come up with a slightly simpler solution to the problem (which wont require any dev work or dataLayer pushes).

I have setup 2 javascript variables for each of the domains mentioned above. 1 variable is for browsers that have the donNotTrack value in the navigator and the other is for a couple of older browsers that have it in the window (window.doNotTrack). These show a 1 if the user has set their browser to doNotTrack.

I have then set 2 triggers for all GA4 (and old GA) tags as exceptions, and if either of the doNotTrack variables shows a 1, then no tracking tags will be fired and the users wish to not be tracked will be adhered to.

How does that sound? I cannot publish the changes myself but if anyone would be keen to test it and then publish the changes if everyone is happy then I think it is ready to go.

Best

Olly

**Comment by bheasman** [comment]
Thanks @ollyw1 ! Wondering if @mmmavis you'd be up for testing this one? Thanks!

**Comment by mtdenton** [comment]
doNotTrack exceptions are published in foundation and donate, let's check that this fits our needs.

**Comment by mmmavis** [comment]
Verified that foundation site and donate site GTM tags are respecting users' DNT settings.

I'm not able to test for Pulse because GTM isn't working for Pulse yet ( See https://github.com/mozilla/foundation.mozilla.org/issues/9587 ).

**Comment by cdanfon** [comment]
Hey Mavis, are you OK to close this ticket and create a new one only for Pulse that has a dependency on #9587 please? Thanks!

**Comment by mmmavis** [comment]
Filed https://github.com/mozilla/foundation.mozilla.org/issues/10033

Closing this one.
