### ISSUE TITLE
TypeError when visiting /admin

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#979]
STR:

1. check out `master`
2. follow regular steps to start server
3. visit `/admin`
4. TypeError encountered (see screencap below). This can be reproduced on other routes under `/admin` as well.

![screenshot-2018-1-19 typeerror at admin](https://user-images.githubusercontent.com/2896608/35176074-db5796b0-fd2b-11e7-98bc-89569af05b0e.png)

Not sure if this is related to Django 1.11 but checking out to this commit https://github.com/mozilla/foundation.mozilla.org/commit/24c25674ab2c0e7200f0053df97d904a6b8dffe3 resolved the problem.

/cc @cadecairos @alanmoo

**Comment by cadecairos** [comment]
This might be your pip modules not being completely up to date. Can you try running `pip uninstall -r requirements.txt -y` and then run `pip uninstall -r requirements.txt`

We might be seeing the same issue on staging.

**Comment by alanmoo** [comment]
This should be fixed now by #980
