### ISSUE TITLE
MozFest: L10N for Tito widget

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/foundation.mozilla.org#9790]
### Describe the feature request
The Tito widget allows for localisation by adding a parameter in the widget code. Adding this will allow us to have the ticketing process in Spanish for MozFest 2023, where we are looking to fully support Spanish across all platforms.

Currently the widget code looks something like this:
`<tito-button event="Mozilla/mozilla-festival-2023" releases="test-ticket"</tito-button>`

Adding the locales that are supported from Tito like this:
`<tito-button event="Mozilla/mozilla-festival-2023" releases="test-ticket" locale="es"</tito-button>`

### Screenshots / mock-ups
UI localisation already exists for multiple languages, for MozFest 2023 we're supporting `en` and `es` across all platforms. ~If the locale isn't supported it falls back to English.~ (The widget only falls back to English, if the language is support but no translation is provided)

<img width="950" alt="Screenshot 2022-12-01 at 17 50 03" src="https://user-images.githubusercontent.com/30226684/205124612-e0825fb8-06a2-473e-a7bb-d6cc2f6c7acf.png">
<img width="851" alt="Screenshot 2022-12-01 at 17 49 54" src="https://user-images.githubusercontent.com/30226684/205124620-dad4e614-013d-4dbf-83bb-c87af92800c4.png">

### Additional context
I briefly talked to @TheoChevalier about this and how it could be implemented, he mentioned that he would prefer if the local was handled in the code rather than us having this set within the snippets on wagtail. However it could introduce complexities where how we handle language identifiers doesn't match Tito's.

I'm happy with either route (and ideally it would be whichever would be able to be implements quickest) - since the use of ticketing is fairly limited at the moment.

**Comment by cdanfon** [comment]
Hey @mtdenton Tom is happy to pick this ticket

**Comment by tomusher** [comment]
I've added support for this with #9818

**Comment by cdanfon** [comment]
@danielfmiranda @tbrlpld @fessehaye could one of you review this for Tom please?

**Comment by cdanfon** [comment]
Hey @marcwalsh this should be ready to be tested on staging

**Comment by marcwalsh** [comment]
Thanks @cdanfon - this is great - it's working for me on staging. Can we hold off pushing this to production as we're awaiting the human translations - currently it's only auto generated translations being used to test.

**Comment by cdanfon** [comment]
Hey Marc, thanks for confirming. 

I believe if it's on staging at the moment it would be pushed to prod as soon as the MoFo team make a prod deployment unfortunately, have you got a timeframe as to when the human translations would be in place?

 @mtdenton @danielfmiranda @mmmavis @tbrlpld @fessehaye for reference

**Comment by TheoChevalier** [comment]
Hi,

Translations should be ready on Thursday

**Comment by mtdenton** [comment]
@marcwalsh @TheoChevalier just a heads-up that our code freeze for winter break starts on Friday, so Thursday will be the drop-dead date to push this into production environments.

**Comment by TheoChevalier** [comment]
Thanks @mtdenton, dropping a note here that translations are done and now in Marc’s hands for publishing

**Comment by cdanfon** [comment]
@TheoChevalier @marcwalsh Can we mark this one as complete now?

**Comment by cdanfon** [comment]
Thanks @marcwalsh 

@danielfmiranda would you mind including this in the next prod deployment please? Thanks

**Comment by marcwalsh** [comment]
@fessehaye - has this been pushed to Production, I'm not sure I'm seeing this working currently on the http://www.mozillafestival.org/es/tickets page.

**Comment by mtdenton** [comment]
@marcwalsh Looks like we took an additional step to prevent this from appearing on prod until the translations are in place. @danielfmiranda provided that step, he'll follow up on removing it.

**Comment by mtdenton** [comment]
Reopening this so that we can track getting the functionality onto production.

**Comment by cdanfon** [comment]
@mtdenton Just to confirm the only task that's preventing us from closing this ticket is to remove/disable the additional step to prevent this from appearing on prod until the translations are in place?

**Comment by danielfmiranda** [comment]
Hi @marcwalsh! Thanks for your patience, this has been merged into staging and is ready to be tested. When you have a free moment, can you please visit https://mozillafestival.mofostaging.net/es/tickets/ and let us know if everything is looking as expected?

Thanks again!

**Comment by marcwalsh** [comment]
Hi @danielfmiranda @mtdenton - this is working for two letter language codes, however it's introduced a bug for language codes with four letters (like pt-br).

I this does totally break for a few languages on the website, so I wouldn't want this pushed to production. However we have an email scheduled for next Thursday to be sent in Spanish as our last email for Early Bird Tickets. Can this be looked into for a potential fix by next Wednesday.

**Comment by marcwalsh** [comment]
Actually sorry - it's languages that are not in use by Tito. So pt-BT, sw, fy-nl are currently not working - is there a way to make those default to en?

**Comment by mtdenton** [comment]
Hey @marcwalsh, confirming that we're seeing the same thing, Tito's widget doesn't account for defaulting to a language if the language code isn't supported and just breaks. We're going to hard code this to get it out the door, just a heads-up that we will need to go back and refactor this to something more robust if we decide to support more languages.

Just to verify, is `es` the only language code that should go to Spanish, all others go to English?

**Comment by mtdenton** [comment]
@danielfmiranda confirming that "English (USA)" and "Spanish" are the only two that we have checked on the Tito side:

![titolanguages](https://user-images.githubusercontent.com/41487159/214916336-5807b8bf-83ae-442f-adef-8c6bf938a199.JPG)

As we discussed, any languages passed into `locale=` outside of this list likely causes this error

**Comment by marcwalsh** [comment]
@mtdenton @danielfmiranda - if the language is on the list above, it falls back to en, if it's not listed it breaks. 

For now from the languages we support on the website the following languages work with Tito:

- en
- fr
- de
- es
- nl
- pl

If it can be hardcoded now, I'll go to Tito to find out if they can add i18n for the other languages we support - I think that would be best case scenario, as we'll need Kiswahili for when we're starting registration of MozFest House: Kenya (which won't be for a few months yet).

**Comment by mtdenton** [comment]
Sounds like a plan, target is to have a solution up and going on or before our Tuesday prod deployment @danielfmiranda.

**Comment by tbrlpld** [comment]
Adding our "deployment blocker" label for visibility. Can be removed when the fix is merged and QAed.

**Comment by danielfmiranda** [comment]
HI @mtdenton @marcwalsh, this has been merged into staging and is now ready for QA! 


I have given this a test on:

- https://mozillafestival.mofostaging.net/en/tickets/
- https://mozillafestival.mofostaging.net/es/tickets/
- https://mozillafestival.mofostaging.net/fy-NL/tickets/

And can confirm that the Tito widget is showing Spanish for /es/, and English for /en/ and /fy-Nl/.


Can you please take a look and let me know if everything is working as expected?

Thanks!

**Comment by marcwalsh** [comment]
Thanks @danielfmiranda - that's working for me!
