### ISSUE TITLE
Refactor `network-api/networkapi/tests/tests.py`

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#9791]
This module currently contains a huge list of unrelated tests. The tests should be moved into a structure that matches the source structure. If the units (e.g. classes or functions) that are being tested are in different modules, so should their tests be. That prevent test modules from getting unwieldy and the tests hard to find.

**Comment by danielfmiranda** [comment]
Hi @tbrlpld @cdanfon this is now ready on staging. 

However, I am not sure of the best way to test this, as this PR was simply a refactoring/re-arranging of test files and no backend/frontend changes.

**Comment by cdanfon** [comment]
I'm not sure how to proceed here so I'll leave it for @tbrlpld to pick up when he's back
