### ISSUE TITLE
Pictures are very blurry when we use the “Profiles” streamfield block in DFL banner pages 

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9804]
### Describe the feature request
TBX has developed some new streamfield blocks for Data Futures Lab. 

One of these components re-uses profile images, however, the pictures are very blurry. A similar fix was applied in [this](https://github.com/mozilla/foundation.mozilla.org/issues/9608) ticket. 

Hoping we can replicate the fix for this block

**Comment by cdanfon** [comment]
Needs to be repurposed to create fragments & groomed

**Comment by mtdenton** [comment]
@cdanfon this would be an excellent one for @kevinhowbrook

**Comment by cdanfon** [comment]
Hey @kevinhowbrook I know you're currently working on the Wagtail upgrade, but if you have some spare time would be good to have a look at this ticket this sprint. Thanks!

**Comment by kevinhowbrook** [comment]
PR https://github.com/mozilla/foundation.mozilla.org/pull/10054 for this can be reviewed.

I'm not sure what this means though:

> Needs to be repurposed to create fragments

**Comment by kevinhowbrook** [comment]
This has been merged and can be tested when staging is deployed (I don't have access to update the board)

**Comment by cdanfon** [comment]
Tested on staging, LGTM 

https://foundation.mofostaging.net/cms/pages/21203/edit/preview/
![Screenshot 2023-02-06 at 12.29.20.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/47ffce43-9bf0-4d91-91a3-569b9ac60f21)
