### ISSUE TITLE
[FRU] Re-add Fundraise Up JavaScript snippet

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#9820]
Related Issues: #9726

In ticket #9726, it was requested to add a JavaScript snippet from Fundraise Up globally to the `<head>` element, in order to be able to render the Fundraise Up donation modal whenever a user visited the URL (base url)/en/?form=FUNWTEYJTEM.
```javascript
<!-- Fundraise Up: the new standard for online giving -->
<script>(function(w,d,s,n,a){if(!w[n]){var l='call,catch,on,once,set,then,track'
.split(','),i,o=function(n){return'function'==typeof n?o.l.push([arguments])&&o
:function(){return o.l.push([n,arguments])&&o}},t=d.getElementsByTagName(s)[0],
j=d.createElement(s);j.async=!0;j.src='https://cdn.fundraiseup.com/widget/'+a;
t.parentNode.insertBefore(j,t);o.s=Date.now();o.v=4;o.h=w.location.href;o.l=[];
for(i=0;i<7;i++)o[l[i]]=o(l[i]);w[n]=o}
})(window,document,'script','FundraiseUp','ADCYPWMX');</script>
<!-- End Fundraise Up -->
```

It was then requested to temporarily remove this snippet from the codebase, which was carried out in ticket #9796

Now, we are ready to re-implement the snippet. 

### Dev Tasks
- [x] Add the above snippet to `base.html` or by other means to globally load the FRU snippet. Include the `nonce` attribute in the `script` tag.

### Acceptance Criteria
- [x] As a developer, I can see the Fundraise Up script load in browser developer tools site-wide.
- [x] As a user, if I navigate to (base url)/en/?form=FUNWTEYJTEM, a lightbox pops up with a Fundraise Up donation form.

**Comment by danielfmiranda** [comment]
Just tested this out on staging, looks ready for Prod on my end!

**Comment by mtdenton** [comment]
Good to go!
