### ISSUE TITLE
Update the link and background image on the Donate Banner CTA

### ISSUE THREAD

**Issue by mtdenton** [mozilla/foundation.mozilla.org#9824]
~~The CTA Link on the Donate Banner needs to be updated to the following~~

~~https://donate.mozilla.org/happy-holidays-from-mozilla/?utm_medium=website&utm_source=MoFo&utm_campaign=22-EOY&utm_content=widget~~

Update on above: superceded by FRU

If it doesn't cause a large increase in effort due to layout changes, we would also like to change the background image to match [this](https://www-demo4.allizom.org/en-US/)

The image can be found [here](https://www-demo4.allizom.org/media/img/banners/fundraising/giving.a3e5c7240b17.jpg)

IMPORTANT: We're not turning on the banner in production yet, just getting it ready for when Kevin wants to turn it on.

Acceptance Criteria
 - [ ] As a user, if I click on the "Support Mozilla" CTA in the donate banner, I'm taken to https://donate.mozilla.org/happy-holidays-from-mozilla/?utm_medium=website&utm_source=MoFo&utm_campaign=22-EOY&utm_content=widget

**Comment by kristinashu** [comment]
@mtdenton I believe the background image and copy also need to be updated to match https://github.com/mozilla/bedrock/issues/12373

**Comment by mtdenton** [comment]
I talked to Kevin earlier, he wanted the same text as [here](https://www-demo4.allizom.org/en-US/), which is what we have in staging right now. He didn't mention the image but I'll ask.

**Comment by mtdenton** [comment]
Talked to Kevin, he'd prefer the same background image as MoCo given the choice. Updating above to provide the image @danielfmiranda

**Comment by danielfmiranda** [comment]
Hi @mtdenton! I have a quick question regarding this ticket

While testing out the new background image, I found that on some screen sizes, the text that overlaps with the image can get a little hard to read:

![Screenshot 2022-12-12 at 14-28-28 Homepage](https://user-images.githubusercontent.com/18314510/207178871-8bb7b287-2228-458b-aeed-67a397019b63.png)

We can work around this by having all the text on the left side of the banner, similar to the banner on https://www-demo4.allizom.org/en-US/.

Here is what it would look like:
![Screenshot 2022-12-12 at 14-30-34 Homepage](https://user-images.githubusercontent.com/18314510/207180587-b14dacaf-c26a-4bda-ab49-e558ed7ed32d.png)

 

While this looks good on larger screen sizes, the same overlap issue persists on medium-small screens:


![Screenshot 2022-12-12 at 15-02-20 Homepage](https://user-images.githubusercontent.com/18314510/207180812-6677ac5f-0cff-4b7c-84ad-34e47f5f048c.png)



I noticed that https://www-demo4.allizom.org/en-US/ is working around this by implementing a sort of semi-transparent effect to the div that houses the text:

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/18314510/207181100-a46a6a0f-d00c-4f59-a1f4-a7cb3b6f6806.png">




My question is: should I implement the same on our banner?

Meaning that we:
- Move the text to the left
- Add the semi-transparent effect on medium-small screen sized


Thanks in advance!

**Comment by danielfmiranda** [comment]
Hi @kristinashu @mtdenton!

This update has been pushed to staging and is ready for review at https://foundation.mofostaging.net/en/

Thanks!

**Comment by kristinashu** [comment]
Thank you Daniel! This looks good to me!

**Comment by anilkanji** [comment]
So happy to see this!  Thanks team. 
* Can someone please confirm the banner timing? I've had a request to extend to be up for when our thank you email goes out, Jan 3
* Does the banner appear sitewide, or just the home page?

@danielfmiranda for visibility

**Comment by kristinashu** [comment]
Following up from the slack message. The dates are Dec 26 - Jan 3 and Tyler will turn it on and then off.

The banner is site wide and you can see it now on https://foundation.mofostaging.net/ but it isn't on PNI or mozfest site.
