### ISSUE TITLE
[PNI] - Buyers Guide Campaign Page frontend bugs

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#9825]
# Description
The following bugs have been found by design on Buyersguide Campaign pages:

- ~~"All Reviews" is showing a selected state, it should show its non-selected state since it isn't selected.~~
- The image is slightly indented, it should be left aligned with the text like it is on all our other pages on the website.

# Screenshots

### Screenshot of the bugs
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/1068783/197852066-87c9d5e7-6d39-4063-8285-89426e6db320.png">

### Screen cap of campaign page on our main site:
(Note how the image is left aligned with the text below it)
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/1068783/197853044-c41b3567-3ea6-4a97-8b75-9b4fe6cb835c.png">

# Acceptance Criteria

~~- [x] The category navigation bar should have no selection highlighted on Buyersguide Campaign pages.~~
- [ ] Image blocks for Buyersguide Campaign pages should be left aligned with their surrounding text..

**Comment by danielfmiranda** [comment]
Great, thanks @kristinashu! I have created PR #9822 with the fix for the padding issue

**Comment by danielfmiranda** [comment]
Hi @kristinashu! This has been merged into main and should be on staging now, I was wondering if you could please give this a test whenever you have a free moment? Thanks in advance!

**Comment by kristinashu** [comment]
Looks good, thank you Daniel!

**Comment by danielfmiranda** [comment]
Pushed to prod! Closing
