### ISSUE TITLE
DFL - Group listing block hyperlink issue

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9834]
On the Projects page, when using the "Group listing block," the description text is not highlightable/copyable. It is just part of one big hyperlink space:

**Example here:** 

https://foundation.mozilla.org/en/data-futures-lab/draftprojects/

Issue: a user is unable to highlight content as it all is part of a big block.

**Comment by cdanfon** [comment]
Hey @mtdentonm, same with this one. Is this something that can be look at anytime soon by one of the MoFo devs or would you like me to ask a TBX dev to look into this? 

@gutermul for reference

**Comment by mmmavis** [comment]
The entire project card is indeed grouped into a hyperlink block.

![image.png](https://images.zenhubusercontent.com/568fffb1638e718c995fe96d/7d4e141b-340b-4e8c-81b0-2c4424626af8)

We should make only the image and title hyperlinked and not the entire container box.

If this sounds good to you @cdanfon @mtdenton , I can file a PR.

**Comment by mmmavis** [comment]
Will do. Happy Holidays @cdanfon 🎉 🎉 🎉

**Comment by mmmavis** [comment]
Hi @cdanfon , this is ready for QA on staging: https://foundation.mofostaging.net/en/data-futures-lab/draftprojects/

**Comment by mmmavis** [comment]
Hi @cdanfon , this is ready for QA on staging: https://foundation.mofostaging.net/en/data-futures-lab/draftprojects/

**Comment by cdanfon** [comment]
Hey @mmmavis looks great thanks! Moving this to 'ready for prod'

@gutermul 'cc

**Comment by mmmavis** [comment]
Done. Closing.
