### ISSUE TITLE
[PNI] Switch visibility of featured CTA with category

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#9853]
## Description

This is similar to #9541. When using the category nav to switch between categories, the visibility of the featured CTA should be updated based on the selected category. 

The categories have the `show_cta` boolean that decides the visibility of the CTA. 

This is also a followup to #9555.

## Acceptance criteria

Given there are two buyer's guide product categories, one with `show_cta =  True` and one with `show_cta = False`, and a featured buyer's guide CTA is specified on the buyer's guide page:

- [x] As a site visitor, when I load the category page for the category with `show_cta = 
True` I see the featured CTA.
- [x] As a site visitor, when I load the category page for the category with `show_cta = False` I **do not** see the CTA.
- [x] As a site visitor, when first I load the category page for the category with `show_cta = False` I **do not see** the featured CTA, but when I switch the active category with the category nav then I **do see** the featured CTA.

**Comment by danielfmiranda** [comment]
This ticket is now in QA and ready to test:

## Steps to test 

**Testing between categories:**

1. Visit https://foundation.mofostaging.net/en/privacynotincluded/categories/smart-home/. The CTA should appear on the page, as this category has `show_cta` set to `True`.
2. Visit https://foundation.mofostaging.net/en/privacynotincluded/categories/entertainment/, this CTA should **not** be visible on this page, as this category has `show_cta` set to `False`.
3. From the navigation bar, select the "Smart Home" category, the CTA now be visible.
4. From the navigation bar, select the "Entertainment" category, the CTA should now **not** be visible.

**Testing between subcategories:**

1. Visit https://foundation.mofostaging.net/en/privacynotincluded/categories/security-cams/. The CTA should appear on the page, as this subcategory has `show_cta` set to `True`.
2. Visit https://foundation.mofostaging.net/en/privacynotincluded/categories/smart-display/, this CTA should **not** be visible on this page, as this subcategory has `show_cta` set to `False`.
3. From the subcategory navigation bar, select "Security Cams", the CTA should now be visible.
4. From the subcategory navigation bar, select "Smart Display", the CTA should now **not** be visible.

**Comment by tbrlpld** [comment]
@danielfmiranda This seems to work as expected when switching between the category pages. I think on case (that is also missed in the ACs) is when switching from the PNI landing page to a category page. In that case, the CTA does not show. 

E.g.: 
* Open https://foundation.mofostaging.net/en/privacynotincluded/
* Click "Smart Home" category
* See grid update, but CTA does not show. 


I guess this could be a separate follow-up ticket.

**Comment by tbrlpld** [comment]
I have created #10046 as a follow up.

**Comment by danielfmiranda** [comment]
Thank you very much @tbrlpld 🙌
