### ISSUE TITLE
[FRU] Switch links from donate.mozilla.org to FRU modal

### ISSUE THREAD

**Issue by mtdenton** [mozilla/foundation.mozilla.org#9856]
We're ready to swap over. Here are the links I've identified so far that we need to swap out. 

Below, I have identified the lines that I've found that need to be changed. We want to retain the UTM parameters for now on each of these lines.

On that note, Tibor's comment down below:

> Adding only the querysting in the href should be relative to the current page: `<a href="?test=true">Test</a>`
> [Test](https://github.com/mozilla/foundation.mozilla.org/issues/9856?test=true) 

Ideally, we would want these to be relative to the URL of the current page for user experience. So, for instance, if a user is on this page:
`https://foundation.mozilla.org/en/blog/meet-julie-ricard-building-a-better-social-media-platform/`
We would want the final URL of the donate link to be:
`https://foundation.mozilla.org/en/blog/meet-julie-ricard-building-a-better-social-media-platform/?form=donate&utm_xxx=yyy&etc=etc`

..and that will open the FRU modal with those UTM parameters.

These are the places that I've identified that we need to swap out links. If I missed any, update this list:

---
### Primary Nav
![headerdonate](https://user-images.githubusercontent.com/41487159/207894847-124f7591-ff5d-4608-930f-585e647887b7.JPG)
https://github.com/mozilla/foundation.mozilla.org/blob/a18ee568eea17149be325bf2556945365bd64e0b/network-api/networkapi/templates/partials/primary_nav.html#L66
  

---
### Top Footer
![topfooterdonate](https://user-images.githubusercontent.com/41487159/207895151-f492a792-b320-4cfa-a559-58db271ddb6f.JPG)
https://github.com/mozilla/foundation.mozilla.org/blob/a18ee568eea17149be325bf2556945365bd64e0b/network-api/networkapi/templates/partials/footer.html#L15
  

---
### Bottom Footer
![bottomfooterdonate](https://user-images.githubusercontent.com/41487159/207895338-14c17eac-8c43-4a89-b115-786d45958563.JPG)
https://github.com/mozilla/foundation.mozilla.org/blob/a18ee568eea17149be325bf2556945365bd64e0b/network-api/networkapi/templates/partials/footer.html#L52
  
---
### Donate Banner
![donatebanner](https://user-images.githubusercontent.com/41487159/207898758-bc3eef88-f3d4-4161-8162-2a28d598a14c.jpg)
https://github.com/mozilla/foundation.mozilla.org/blob/a18ee568eea17149be325bf2556945365bd64e0b/network-api/networkapi/templates/partials/banner.html#L46
  
---
### MozFest Footer
![mozfestfooter](https://user-images.githubusercontent.com/41487159/207898528-c7a1f027-80a1-46a1-baf9-74945a9f3533.jpeg)
https://github.com/mozilla/foundation.mozilla.org/blob/5e15e737f443934f7e22c5d36cff791c41205731/network-api/networkapi/mozfest/templates/partials/mozfest_footer.html#L35
  
---
### Maintenance Page
https://github.com/mozilla/foundation.mozilla.org/blob/a18ee568eea17149be325bf2556945365bd64e0b/network-api/networkapi/wagtailpages/templates/maintenance/maintenance.html#L78
  
---
### PNI Nav
![pni](https://user-images.githubusercontent.com/41487159/207899082-fb4da4e3-870a-4c2d-bc7f-5e7d9745e258.JPG)
https://github.com/mozilla/foundation.mozilla.org/blob/dbd92e543c45e3ca1f348765b82b12689b65187a/network-api/networkapi/templates/fragments/buyersguide/primary_nav.html#L59
  
---
### Dear Internet Page
![dearinternet](https://user-images.githubusercontent.com/41487159/207899497-d54d58ba-c303-4788-bbae-b0cf42a1bfef.JPG)
https://github.com/mozilla/foundation.mozilla.org/blob/e25670341bc97b2f65bb5d16251a78df66500097/network-api/networkapi/wagtailpages/factory/dear_internet_page.py#L26

## There's a few that are questionable, and we need to discuss:
  
---
### button.js
https://github.com/mozilla/foundation.mozilla.org/blob/a18ee568eea17149be325bf2556945365bd64e0b/tailwind-plugins/button.js#L107
https://github.com/mozilla/foundation.mozilla.org/blob/a18ee568eea17149be325bf2556945365bd64e0b/tailwind-plugins/button.js#L144

  
---
### donation-modal.jsx
https://github.com/mozilla/foundation.mozilla.org/blob/a18ee568eea17149be325bf2556945365bd64e0b/source/js/components/petition/donation-modal.jsx#L74
  
---
### why_we_made.html
https://github.com/mozilla/foundation.mozilla.org/blob/c3c5eeeced094e6a94b27e6d580631b25378d76a/network-api/networkapi/templates/pages/buyersguide/about/why_we_made.html#L156

### Acceptance Criteria
All of these open the Fundraise Up modal on the same page that the link was clicked:
- [x] Donate Banner CTA
- [x] Default Primary Navigation Donate Button
- [x] Top of the footer (purple section)
- [x] Bottom of the footer (black section)
- [x] Privacy Not Included Primary Navigation
- [x] Mozilla Festival Footer
- [x] Maintenance Page Donate CTA
- [ ] "Dear Internet" Donate CTA

**Comment by tbrlpld** [comment]
Adding only the querysting in the `href` should be relative to the current page: `<a href="?test=true">Test</a>`

<a href="?test=true">Test</a>
