### ISSUE TITLE
[PNI QA] Donate button is missing from nav on mobile

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9859]
The Donate button is missing at narrow browser widths. It should appear in the open hamburger menu.

@beccaklam @nancyt1 could you please add a screen cap of how it should look?

Dev AC
- [ ] As a user, I see the donate button when I open the main menu on my phone
- [ ] As a user, there is enough space between the nav items for my fat fingers (least 1.25rem between the links)

**Comment by kristinashu** [comment]
Thank you Nancy! Yes, I agree the spacing is tight so I'll add that to the ACs.

**Comment by mmmavis** [comment]
@kristinashu is this ready for review on staging https://foundation.mofostaging.net/privacynotincluded/

**Comment by kristinashu** [comment]
Looks good Mavis, thank you!
