### ISSUE TITLE
Add a troubleshoot entry to the editor guide for mini-sites/menu issues

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#987]
We recently ran into an issue with minisite menus not showing because the minisite "over-arching page" was set to `draft` mode rather than `published` mode. In order to make that problem situation easier to spot and resolve for editors (as well as developers acting as editors during testing/debugging) we should expand https://mzl.la/cms-guide with a troubleshooting section either specific to minisites, or a kind of troubleshooting "appendix" that contains at the very least the findings and solutions from https://github.com/mozilla/foundation.mozilla.org/issues/830

**Comment by xmatthewx** [comment]
I added a few warnings in the guide. I added a trouble shooting section. Sparse, but better than nothing. I'll fag Alan in the doc to add other things that come up.
