### ISSUE TITLE
[PNI] Add fade effect between "Sort By" dropdown and subcategories

### ISSUE THREAD

**Issue by nancyt1** [mozilla/foundation.mozilla.org#9871]
Follow up from ticket #9659
[Figma Designs](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=5609%3A102175&t=UCOqvUJixeY29Pqv-1)

<img width="1050" alt="Screen Shot 2022-12-20 at 3 34 30 PM" src="https://user-images.githubusercontent.com/74557207/208771260-9d9b8522-095c-4cc3-98d3-8a6fd384da03.png">

**Acceptance Criteria:**
- [ ] It should look like category tags are faded out before reaching sort by dropdown
- [ ] The last category tag of list should not be faded

**Comment by mmmavis** [comment]
@nancyt1  how do I make more tags to show up? Mine only shows the PNI tag

![image](https://user-images.githubusercontent.com/2896608/208781433-18ddbb97-dc8a-4464-9f6d-b9721f55e55e.png)

**Comment by danielfmiranda** [comment]
Hi @nancyt1!

I was wondering if you could please confirm my understanding of the last two points of the acceptance criteria?

- [ ] It should look like category tags are faded out before reaching sort by dropdown
- [ ] The last category tag of list should not be faded

If I am understanding this correctly, the categories should fade out before reaching the "Sort By" Dropdown if there are more categories to scroll through:

<img width="543" alt="Screenshot 2023-01-09 at 3 26 10 PM" src="https://user-images.githubusercontent.com/18314510/211428465-1857e5ea-b422-4a2d-9c61-772c1b2e9bcf.png">

However, if it is the last category in the list, there should be no "fade effect" like so:



<img width="1001" alt="211427590-faa34ca5-b21d-4eb1-a3aa-a9e89230e9e4" src="https://user-images.githubusercontent.com/18314510/211428080-4fd7a9fe-7867-470b-ac5f-097fcaf325b4.png">




Also had one more question about the scroll effect on the left side of the list. At the moment, categories just get cut off on the left side like so:

**Before Scroll:**

<img width="543" alt="211427838-dfec076e-c92e-4b46-b17c-981b6a6e5ef5" src="https://user-images.githubusercontent.com/18314510/211428129-d507f0e0-0c43-47e3-8d8e-64e39b5a5e4c.png">

**After Scroll:**

<img width="543" alt="211427916-5b28749c-c506-4b0b-af02-f9cd1f62e2ee" src="https://user-images.githubusercontent.com/18314510/211428197-28bd0ad3-2a44-41df-b8e9-99fcd168b670.png">



Is this OK with the design team?


Thanks!!

**Comment by nancyt1** [comment]
Hi @danielfmiranda, yes your understanding is correct for the fade effect and yes it's fine to just cut off on the left side. Thanks for confirming!

**Comment by danielfmiranda** [comment]
Hi @nancyt1! 

As the German translation for the sort by dropdown is quite long, I was wondering if you could please create a quick mockup with English so I can see the desired design when the text is of a shorter length?

Thanks in advance!

**Comment by nancyt1** [comment]
@danielfmiranda I was thinking everything would move proportionally. The padding around the text should be the same
![Uploading Screen Shot 2023-01-13 at 2.23.22 PM.png…]()

**Comment by danielfmiranda** [comment]
Simon and I are going to coordinate on this ticket and #10058 after a meeting we have scheduled for 1/31/23 at 1:30PM PST

**Comment by danielfmiranda** [comment]
After coordinating with Simon, Nancy and Mavis, I have renamed this ticket, and updated the acceptance criteria to the following:

**Acceptance Criteria:**
- [ ] It should look like category tags are faded out before reaching sort by dropdown
- [ ] The last category tag of list should not be faded

**Comment by danielfmiranda** [comment]
Hi @nancyt1! This has been merged into staging, and is now ready for QA at: https://foundation.mofostaging.net/en/privacynotincluded/categories/smart-home/

Can you please take a look whenever you have a free moment and let me know if it looks as expected? Thanks!

**Comment by nancyt1** [comment]
@danielfmiranda Everything looks good to me! Thank you!
