### ISSUE TITLE
[PNI] Expand creepometer speech bubble to fit any text length on mobile

### ISSUE THREAD

**Issue by nancyt1** [mozilla/foundation.mozilla.org#9872]
![IMG_A9DE90A11D7C-1.jpeg](https://images.zenhubusercontent.com/5fb2aa620446ae2c8ea94417/ebdbbd3d-6457-4238-b5af-38da3e1958c9)

Text is getting cut off on mobile, especially for longer languages like german. Perhaps the bubble can expand upwards instead of capping at 2 lines.

**Figma Mockup:**
- Bubble expands to fit text, staying centered with the emoji face
![DE Creep-o-meter](https://user-images.githubusercontent.com/74557207/211667983-65d0e690-94d0-46d4-9e17-91422733ba3a.png)

**Comment by mmmavis** [comment]
Agree that the bubble shouldn't have fixed height. It's currently set to `--sticky-height: 73px`.

**Comment by mmmavis** [comment]
@nancyt1 could you suggest how the speech bubble should look? A mockup would be great so we can be on the same page. Thanks!

**Comment by nancyt1** [comment]
@mmmavis Hi mavis! I added the mockup to the ticket description!

**Comment by mmmavis** [comment]
@nancyt1 this is on staging for QA: https://foundation.mofostaging.net/en/privacynotincluded/

**Comment by mmmavis** [comment]
@nancyt1 this is on staging for QA: https://foundation.mofostaging.net/en/privacynotincluded/

**Comment by nancyt1** [comment]
@mmmavis Is there a reason the line is breaking at "gruselig" instead of "die"? It seems like more text would fit in that gap. And can the text be center aligned?

<img width="365" alt="Screen Shot 2023-01-17 at 4 15 54 PM" src="https://user-images.githubusercontent.com/74557207/213024396-7a84acac-e6e3-426a-af33-b9e0fbb25aaa.png">

**Comment by mmmavis** [comment]
@nancyt1 Thanks for the QA. Will update you once I find out where the localized text is pulling from. I *think* some text came with line breaks already.

Bubble text not getting updated on small screen is a known issue :( Ticket can be found here. https://github.com/mozilla/foundation.mozilla.org/issues/9942

**Comment by mmmavis** [comment]
Hello @TheoChevalier Happy New Year 🎉 

We are thinking about removing the line break hardcoded in this [text](https://github.com/mozilla/foundation.mozilla.org/blob/main/network-api/networkapi/templates/pages/buyersguide/catalog.html#L63) and let the text auto wrap based on the bubble size. Could you remind me where the localized text is coming from for this text? Is it Pontoon? Is it sufficient enough if I just remove the `<br>` from this line?

**Comment by TheoChevalier** [comment]
Hi @mmmavis, happy new year!

Great catch for the link, I’ll fix it. Translations for PNI UI are located here: https://pontoon.mozilla.org/projects/privacy-not-included/
And yes, just removing the <br/> is enough, it will invalidate existing translations

**Comment by mmmavis** [comment]
@TheoChevalier thank you!

**Comment by mmmavis** [comment]
Styling changes are looking as expected on production. Note that since we changed the bubble text by removing the hardcoded line break `<br/>`, we invalidated the old localized strings. Once the “new” text is localized again via Pontoon they will be pulled into our site.

Closing!

**Comment by mmmavis** [comment]
Styling changes are looking as expected on production. Note that since we changed the bubble text by removing the hardcoded line break `<br/>`, we invalidated the old localized strings. Once the “new” text is localized again via Pontoon they will be pulled into our site.

Closing!
