### ISSUE TITLE
Add Mastodon profile link next to Twitter

### ISSUE THREAD

**Issue by shuuji3** [mozilla/foundation.mozilla.org#9879]
### Describe the feature request
Hello, now Mozilla has an official Mastodon account on mastodon.social (🙂 🎉 [Mozilla (@mozilla@mastodon.social)](https://mastodon.social/@mozilla)).  I'd like to propose adding a Mastodon icon anywhere next to the Twitter icon.

There was a previous proposal just for reference: #4933

### Screenshots / mock-ups

I'm already started working on the implementation to solve this issue. I'll create a new PR soon for review. Here are some screenshots:

![Screenshot 2022-12-21 at 19 42 37](https://user-images.githubusercontent.com/1425259/208886556-e5cda79c-38d7-47b9-935f-b0bd0c726a7f.png)
(Footer icon)

![Screenshot 2022-12-21 at 19 36 21](https://user-images.githubusercontent.com/1425259/208886562-94afa6bb-e38f-4957-9063-3112756f33fc.png)
(Hover state)

### Additional context
Thanks!

**Comment by tbrlpld** [comment]
Thanks for the contribution. We currently don't have the capacity to review external contributions.
