### ISSUE TITLE
PNI - homepage speech bubble content should be localized

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#9881]
### Describe the bug
On PNI homepage, speech bubble content should be localized

### To Reproduce
1. Go to PNI homepage foundation.mozilla.org/privacynotincluded/
2. Scroll down to page bottom to choose a non-English language
3. Wait for page to reload
4. Scroll down and pay attention to speed bubble content (`creepy`, `not creepy`, etc)

### Expected behavior
Speech bubble content should be localized

### Screenshots
https://user-images.githubusercontent.com/2896608/208976643-8ba0bbce-5781-4f8f-9443-857d2debf06b.mov

**Comment by tbrlpld** [comment]
This needs to wait as it is likely to clash with #10059

**Comment by tbrlpld** [comment]
I assumed when estimating on this that this would be as simple as adding a `trans` block somewhere in the template. 

Turns out, these strings are defined in JS. 
`source/js/buyers-guide/homepage-c-slider.js` get strings from `source/js/buyers-guide/components/creepiness-labels.js`

I don't know how we deal with string translation in JS. When searching for `locale` in the JS files I am finding hardcoded strings and custom switcher logic.
 E.g.: 

- `source/js/components/petition/locales.js`  switches `source/js/components/petition/locale-strings.jsx`
- `source/js/components/tabbed-profile-directory/locales.js` switches `source/js/components/tabbed-profile-directory/locale-strings.jsx`

This seems to be a third way to do translations in the code base. Is this something we should be doing? 

@TheoChevalier is this the desired way to do this? 

How ever we are going to solve this, I have basically used the planned time for researching this with no result. I guess this needs more discussion.

**Comment by tbrlpld** [comment]
cc @mtdenton @cdanfon for visibility

**Comment by tbrlpld** [comment]
Also, not sure how we would be able to QA this because the strings are not in the translation database / dataset yet.

**Comment by tbrlpld** [comment]
@fessehaye Mentioned that some locations use data attributes for this

**Comment by TheoChevalier** [comment]
Hey there,

So yes, there are two different cases here: strings in simple .js files, and strings in React components.

The `locale-strings.jsx` file is a very hacky way of localizing strings in React components, we need to implement a proper i18n solution for this.

I’ve done some exploratory work a while back (and ended up spending way too many hours on this):
- Extending Django’s gettext to React https://github.com/mozilla/foundation.mozilla.org/pull/3913/files → The main caveat was that it doesn’t support backticks in strings and JS string interpolation.
- Using LinguiJS https://github.com/mozilla/foundation.mozilla.org/pull/3984
- Using Fluent https://github.com/mozilla/foundation.mozilla.org/pull/4181


As for simple .js files we can use Django’s gettext, here are a couple live examples:
https://github.com/mozilla/foundation.mozilla.org/blob/main/source/js/multipage-nav.js#L12
https://github.com/mozilla/foundation.mozilla.org/blob/main/source/js/foundation/pages/youtube-regrets/regret-rates-chart.js#L11

I’ve done just that, the only issue is we’re concatenating the label with an exclamation mark, but this is more a separate issue.

**Comment by TheoChevalier** [comment]
PR: https://github.com/mozilla/foundation.mozilla.org/pull/10109

**Comment by tbrlpld** [comment]
Thanks for the explanation @TheoChevalier 🙏

**Comment by tbrlpld** [comment]
@TheoChevalier Did you have to update the translation files when testing locally? It does not seem to work on staging right now: https://foundation.mofostaging.net/fr/privacynotincluded/

**Comment by TheoChevalier** [comment]
Yes, I had to update the .po files locally.

The code landed only *allows* me to extract the strings for translation (which [I did this morning](https://github.com/mozilla-l10n/fomo-l10n/commit/3930d120f13075469fe38c07323400816b3b0cc7)). Translations started to flow back to the l10n repo and they will be picked up by the staging instance the next time it gets rebuilt (likely at the next code commit on the main branch)

**Comment by cdanfon** [comment]
Hey @tbrlpld is there anything left to do as part of this ticket? What are the next steps?

**Comment by TheoChevalier** [comment]
Hey @cdanfon @tbrlpld,

I’ve added a couple lines here https://github.com/mozilla/foundation.mozilla.org/pull/10115 to fully localize the final string seen in the UI (with the exclamation mark), not just the labels

**Comment by mmmavis** [comment]
Thanks @TheoChevalier . I R+'ed and merged the PR. I did have one small question regarding if we should include a hardcoded punctuation `!` though. Please see [comment in PR](https://github.com/mozilla/foundation.mozilla.org/pull/10115) for more details. Thanks!

**Comment by mmmavis** [comment]
Staging looks good! Moving this ticket to "ready for prod" column!

**Comment by mmmavis** [comment]
Staging looks good! Moving this ticket to "ready for prod" column!

**Comment by mmmavis** [comment]
Staging looks good! Moving this ticket to "ready for prod" column!
