### ISSUE TITLE
[Responsible Computing] Planning Ticket

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9898]
Plan on how to break up the Responsible Computing work, particularly how to divide tasks between the "Hub" deliverable and "Library" deliverable.

**Goals**
- [x] Develop a list of deliverables and tasks (fill out Figma slide)
- [x] Plan a rough timeline corresponding to deliverables and tasks
~- [ ] Get feedback from design, dev and stakeholders~
- [x] Refine and make a roadmap proposal
~- [ ] Gather ~second round of~ feedback from design, dev and stakeholders~
~- [ ] Put roadmap in Figma deck~

**Comment by beccaklam** [comment]
@tbrlpld Tagging you in here for visibility!

**Comment by tbrlpld** [comment]
@beccaklam Where does the verbiage of "hub" and "library" come from? Considering the similarity with the Research Hub, I wanted to highlight that there, the "library" lives below the "hub". 

In Research Hub:

* Hub landing page 
  * Library page
    * Article landing page
      * Article page (optional, article landing page could also link externally)
    * ...
  * Author index page
    * Author pages (generated from profiles)


We could to something similar for responsible computing
* Hub landing page (it does not have "hub" in the title") 
  * Library page
    * Article landing pages
      * Article page (optional, article landing page could also link externally)
    * ...
  * Author index page (if desired)
    * Author pages (generated from profiles)
    * ...
  * Community content index (this is for the stuff that is submitted by the audience)
    * Content / article page

**Comment by beccaklam** [comment]
I think the terms "hub" and "library" comes from the teams themselves but we can ask Jocelyn more at the stakeholder meeting. I'm not sure if those are org wide terms but I suppose it's becoming that way with this potential second build. What you laid out above looks good although I wonder if the RC team wants the community content also in the library page. That's something we can also clarify during the stakeholder meeting.

**Comment by tbrlpld** [comment]
Yea, I was wondering about the integration of the community content into the library. Since the library will have taxonomies to filter by, it would be easy enough to separate the curriculum/playbook and the community contributions.

**Comment by beccaklam** [comment]
I'm going to close this ticket now because most of the feedback for the planning/roadmap/delivery plan will be given in the design brief ticket. Once that is finalized I will finalize the roadmap in the Figma file.
