### ISSUE TITLE
Mobile view heading placement

### ISSUE THREAD

**Issue by anweshknayak** [mozilla/foundation.mozilla.org#990]
![screenshot from 2018-01-24 20 52 13](https://user-images.githubusercontent.com/8139783/35340685-cac4e39e-0149-11e8-96ac-9d8f7fa108d1.png)

In mobile view, I think **Get Connected** should be placed in center

**Comment by taisdesouzalessa** [comment]
Hi @anweshknayak, thanks for your feedback here! Our brand guidelines usually ask us to prioritize the alignment to the left whenever possible. I agree with you that this page looks a bit weird, I'll create a design ticket so we think about other solutions to make this page looks better, sounds good?

Thanks for catching this :).

**Comment by gvn** [comment]
Since there's now a design ticket I'm closing this as a dupe.
