### ISSUE TITLE
[Responsible Computing] Create Design Brief

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9900]
After completing the Discovery and Planning phase of this work, summarize findings and goals in a design brief and get sign off from stakeholders so everyone is on the same page for the project.

**Goals:**
- [x] Write draft of design brief
- [x] Gather feedback from design, devs and stakeholders
- [x] Refine design brief based on feedback
- [x] Get sign off from all stakeholders
- [x] Add roadmap to Figma slide deck

**Comment by beccaklam** [comment]
@tbrlpld Tagging you here for visibility!

**Comment by beccaklam** [comment]
[First draft ](https://docs.google.com/document/d/1EGD8p92eNTu0OXmgYgziWxATtWrcMbImfp8y6RRaZz0/edit?usp=sharing)of the brief has been finished. Asked for feedback from Kristina in our design slack channel.

**Comment by kristinashu** [comment]
Is this good to close?
