### ISSUE TITLE
Hero and card images appear grainy/blurry even with large file sizes 

### ISSUE THREAD

**Issue by nancyt1** [mozilla/foundation.mozilla.org#9901]
Creating this ticket based on this [ slack thread](https://mozilla.slack.com/archives/C98GW3P7X/p1671645941583009)
### Bug 
I was imputing images for [ADG playbook](https://foundation.mozilla.org/en/research/library/alternative-data-governance-playbook/adg-playbook/) in the publication article template and it looks badly compressed even though file sizes are pretty large. You can see it in the hero and in the cards under "Read the Reports". I've also tried both compressed and non-compressed images and got the same result. _PW for page if needed: adg2022_

### Acceptance Criteria:
Images should be sharp as original uploaded image

**Comment by kristinashu** [comment]
Noting that I am also seeing this on the `Card grid` block and this has been an issue for PNI author images as well so it might be worth looking into this more broadly.

**Comment by tbrlpld** [comment]
@kristinashu Daniel has submitted #9918 to look into the image quality more broadly. I think we will need to turn that into an epic given how many locations are using images. 

This issue will deal with the publication header and the cards for now.

**Comment by tbrlpld** [comment]
@nancyt1 This should be ready to QA on staging in a few minutes.

**Comment by tbrlpld** [comment]
@nancyt1 This should be ready to QA on staging in a few minutes.

**Comment by nancyt1** [comment]
@tbrlpld Looks a lot better now! Thanks Tibor!

**Comment by kristinashu** [comment]
I just looked on staging and wow soooo much better!

**Comment by tbrlpld** [comment]
Thanks for QAing @kristinashu @nancyt1
