### ISSUE TITLE
Unable to use anchor links for H2 text in Image Teaser Blocks on MozFest Website

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/foundation.mozilla.org#9902]
### Describe the bug
When creating Image Teaser Blocks they have heading and body text. In other blocks we're able to link to those headings as an anchor link. However these headings are missing fragment ID that we would normally use for anchor links. 

### To Reproduce
1. Go to '[https://www.mozillafestival.org/en/issues-and-spaces](https://www.mozillafestival.org/en/issues-and-spaces)'
2. Click on MoZone (which links to https://www.mozillafestival.org/en/issues-and-spaces/transparency#mozone)
3. Page does not scroll to MoZone heading as part of Image Teaser Block

### Expected behaviour
I'm able to create anchor links using the headings added to Image Teaser Blocks.

**Comment by mtdenton** [comment]
Hi March, also looking to get this in during Sprint 1.

Grabbing for discussion today.

**Comment by cdanfon** [comment]
Hey @mmmavis can you update this ticket please? Thanks

**Comment by tbrlpld** [comment]
@marcwalsh Can you provide a link to a page that contains blocks with linkable headings? 

Also, I am not sure what should happen when you click on "MoZone". The element seems to be just a simple paragraph and an image, so clicking usually does not have an effect.

**Comment by tbrlpld** [comment]
@marcwalsh Was the first link meant to go to: https://www.mozillafestival.org/en/issues-and-spaces/transparency/ instead of https://www.mozillafestival.org/en/issues-and-spaces/?

**Comment by tbrlpld** [comment]
## Prior art

`wagtailcustom_tags.py`

#7348
#6679
#5259
#2892

#2788


The styleguide does contain linkable headings, but these are all manually created in the template.

**Comment by marcwalsh** [comment]
Hi @tbrlpld - I forgot we removed the links from the images on the [Issues and Spaces page](https://www.mozillafestival.org/en/issues-and-spaces).

Under [MozFest 2023 Spaces on the Issues and Spaces page](https://www.mozillafestival.org/en/issues-and-spaces/#mozfest-2023-spaces), we would link from MoZone (as an example) to the MoZone section on the [Transparency page](https://www.mozillafestival.org/en/issues-and-spaces/transparency#mozone) - I've added a screenshot of where the anchor for MoZone should go to:

<img width="1182" alt="Screenshot 2023-01-13 at 16 41 53" src="https://user-images.githubusercontent.com/30226684/212372904-f8d68497-8109-4c11-a44f-742a54e8668e.png">

The MoZone header is h2 however I'm unable to link to it using an anchor link - this issue is across all the Image Teaser Blocks on the site.

**Comment by tbrlpld** [comment]
@marcwalsh Thanks for the additional information. 

It looks like the for linkable headings in the "image text" block is based on linkable headings in richtext, and that seems to be broken at the moment 🤔 I guess that would be a separate issue.  

How would you get to the anchor id? Would you use the "inspect element" / dev tools of the browser or would there be an option to click something to get the ID or the URL?

**Comment by tbrlpld** [comment]
@marcwalsh Does this look about right? 

<img width="1634" alt="image" src="https://user-images.githubusercontent.com/24797493/212385175-784dd35f-8816-4ac0-a740-6f7ede99c782.png">

**Comment by marcwalsh** [comment]
Yes that's right - it's a bit of a complex process.

**Comment by tbrlpld** [comment]
@marcwalsh I'll follow the existing pattern for now, but we can probably talk to design to maybe add a clickable element to the headings similar. 

Similar solution can be found e.g. on MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#try_it

cc @kristinashu

**Comment by tbrlpld** [comment]
@marcwalsh I'll follow the existing pattern for now, but we can probably talk to design to maybe add a clickable element to the headings similar. 

Similar solution can be found e.g. on MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#try_it

cc @kristinashu

**Comment by tbrlpld** [comment]
Hey @kevinhowbrook I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account.
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by tbrlpld** [comment]
@marcwalsh This should be ready to test on staging: https://mozillafestival.mofostaging.net/en/issues-and-spaces/transparency/#mozone

For now, the discovery of the id (like `#mozone`) will still need to be done through the dev tools (or you manually suggify the title of the block), but we have #10052 to improve the discoverablitiy and accessibility of the anchor links. 

In case of the block heading, I have opted to set the `id` on the section and use it as the `href` on the anchor. This to to scroll the whole section with the image into view instead of only the heading which would cut of the image above. 

Let me know if this implementation is ok by you or if any changes are needed (other than the ones planned to be dealt with in #10052).

**Comment by marcwalsh** [comment]
This works for me! Thanks @tbrlpld

**Comment by tbrlpld** [comment]
Awesome. Thanks for testing @marcwalsh. We will release this with the next production deployment.
