### ISSUE TITLE
Add Accordion block to more page types

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9903]
`Accordion` block is currently available on `Article` and `Blog` page types but it would be helpful to also have these on other page types. 

## AC
- [x] As a user, I can use the `Accordion` block on `Banner` and` Primary` and `Default` page types
- [x] As a user, the [Wagtail UX Audit spreadsheet](https://docs.google.com/spreadsheets/d/1AwLF6dw05Jn2WZu-xvxUgm8VQ4udriZW6d_NfdVI9ns/edit#gid=1064282995) is up to date (please update the check boxes in the spread sheet once this work is live)

**Comment by mtdenton** [comment]
@fessehaye is this actually in progress?? I see a PR associated here

**Comment by kristinashu** [comment]
Looks good on staging, thank you!
