### ISSUE TITLE
[Mozfest] - "More from this blog" button not working

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9906]
URL Affected:
https://www.mozillafestival.org/en/newsletter/

How to reproduce:
click on the "more from this blog" button on this page: https://www.mozillafestival.org/en/newsletter/

**Comment by mtdenton** [comment]
@fessehaye is this in progress?

**Comment by fessehaye** [comment]
@kristinashu https://mozillafestival.mofostaging.net/en/newsletter/ Can you please double check that  the button is working now?

**Comment by beccaklam** [comment]
Looks like the button is working now! @fessehaye

**Comment by kristinashu** [comment]
Thank you both!
