### ISSUE TITLE
GTM recording events on staging site

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#9933]
### Description

We have reports that GTM is tracking events on staging (https://foundation.mofostaging.net/), which can lead to innacurate results.

However this ticket needs further investigation/grooming. If I understand correctly, while we are able to test our tags on the staging site using the GTM preview mode, official GTM events are only being recorded on https://foundation.mozilla.org:

<img width="403" alt="Screenshot 2023-01-10 at 10 17 58 PM" src="https://user-images.githubusercontent.com/18314510/211731924-0f63cced-d2d7-45fb-9687-731ed501a27d.png">

**Comment by mtdenton** [comment]
There is now an exception trigger on each tag that prevents tags from firing on staging. If we want to refine this further, we could prevent the GTM snippet from rendering on staging by making it toggleable via an environment variable.
