### ISSUE TITLE
PNI - Speech bubble and creep-o-meter emoji don't update on small screens

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#9942]
### Describe the bug
PNI homepage - Speech bubble and creep-o-meter emoji don't update on small screens (width < 768px)

### To Reproduce
1. Go to https://foundation.mozilla.org/privacynotincluded/
2. See if speech bubble and emoji are updating as you scroll up and down the page
3. Repeat Step 1-2 on a narrower screen

### Expected behavior
Speech bubble and emoji should update as you scroll.

### Screenshots (taken with window width 767px)

https://user-images.githubusercontent.com/2896608/212439612-4b1e890d-3841-4096-922b-1fb9c15f3b1d.mov

**Comment by fessehaye** [comment]
@beccaklam can you check this on staging

**Comment by beccaklam** [comment]
Yes this appears to be resolved!
