### ISSUE TITLE
SPIKE | PNI Refactoring

### ISSUE THREAD

**Issue by mtdenton** [mozilla/foundation.mozilla.org#9948]
Let's identify where we can improve the readability and performance of PNI from a code standpoint. The goal of this ticket is to identify our largest problem areas concerning PNI. Later (not part of this ticket), we will take these problem areas and break them down into actionable tickets.

Schedule a meeting to talk about the approach concerning front-end vs. back-end functionality.

Timebox: 4 hours

**Comment by tbrlpld** [comment]
Related issues #9812 and #9813

**Comment by mmmavis** [comment]
Code readability for PNI is not good which makes understanding the codebase really challenging. After diving into the code in the past day or so, I’m still unable to fully understand all the JS code. I’ve been taking notes as I check out the code, but before I can continue drafting the actual refactoring/rewrite plan, I want to propose that we clean up the codebase by first doing some minimal-risk tasks.

1. Extract code dupes and turn them into functions. This will reduce the code by tens+ lines.
2. Use JSDoc style to document every functions and modules. We have quite a bit of functions with long implementation. Many functions look like they have gone through rounds of quick patches and now their function names don’t represent what they do anymore. Ideally, we would want to break the long implementation into smaller functions to make sure each function has one sole purpose. To do so, we will first need to know what the current functions do, which we can achieve by adding documentations to existing functions and modules.
3. Update function names. There are some functions with very similar names but have quite different purposes. We should update them to make them more distinguishable. 
    
If the above sounds like good first step, let me know then I will break each item down into subtasks.

**Comment by tbrlpld** [comment]
Thanks @mmmavis 🙏 I really like all these suggestions! These are all pain points I have noticed as well.

**Comment by mtdenton** [comment]
Perfect @mmmavis, thanks! Very happy for you to move forward into breaking these out

**Comment by mmmavis** [comment]
@cdanfon @mtdenton any preference on how I should file the tickets? I'm thinking to create an epic ticket to track PNI refactoring work, create task-based tickets, and link those tickets to the epic.

**Comment by mmmavis** [comment]
Tickets for stage 1 refactoring work have been filed. Please see [[EPIC] PNI Refactoring Stage 1](https://github.com/mozilla/foundation.mozilla.org/issues/10159).

**Comment by mmmavis** [comment]
Tickets for stage 1 refactoring work have been filed. Please see [[EPIC] PNI Refactoring Stage 1](https://github.com/mozilla/foundation.mozilla.org/issues/10159).
