### ISSUE TITLE
Get Connected - design improvement

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#995]
Related to the issue #990, instead of changing the alignment, we could design this page to look a bit better. More like little spacing tweaks and others.

![img_6608](https://user-images.githubusercontent.com/22157921/35347599-71f0e574-00ea-11e8-8025-0e8d60fc8449.jpg)

**Comment by anweshknayak** [comment]
@taisdesouzalessa can I do this? Could you elaborate on how to fix this?

**Comment by taisdesouzalessa** [comment]
@anweshknayak I need to discuss this issue with other designers to make sure we approach it as a system because the styles used on this page affect others as well. It may take a while because we are focused on more urgent issues at the moment but I'll keep you posted here as soon as we have a design solution for this ticket. Sounds good?

**Comment by anweshknayak** [comment]
Thanks  🎉

**Comment by kristinashu** [comment]
This icon and page are gone now so this is no longer relevant.
