### ISSUE TITLE
Order snippets alphabetically

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#9968]
## Description

Without a proper order for the snippets, staff end up creating duplicate items on accident.

We should prevent this by at least ordering all snippets alphabetically if no other natural / required order exists for them. 

See also:
* https://mozilla.slack.com/archives/C98GW3P7X/p1673970641783389?thread_ts=1673970641.565049&cid=C98GW3P7X

## Acceptance criteria 

- [x] Snippets are ordered alphabetically (if no other order is required)

**Comment by tbrlpld** [comment]
@kristinashu You had opened a related issue, would you mind giving this a quick check on staging? 

* https://foundation.mofostaging.net/cms/snippets/
* https://foundation.mofostaging.net/cms/snippets/wagtailpages/profile/

**Comment by tbrlpld** [comment]
@kristinashu All snippets that did not specify a different ordering before are sorted alphabetically now.

* Blog page topic
* Buyer's guide content category
* Buyer's guide product update
* Callpower
* Donation CTA
* Area of focus
* Profile
* Pulse filter
* Research region
* Research topic
* Signup
* Tito event

The menu position should not have changed. This is a most curious thing 😵‍💫

**Comment by tbrlpld** [comment]
I can reproduce the jumping menu position 😳 Though I have no hunch as to where this is coming from.

**Comment by kristinashu** [comment]
Nice, all those snippets are in alphabetical order!

I thought the menu moved depending on the page but it actually sometimes moves even if I refresh the same page!?

**Comment by tbrlpld** [comment]
Yea, i get the same havior on staging, but not locally... very weird. Tried FF and Safari and get the same result. Sometimes it's at the top sometimes at the bottom... 

Maybe we give it a little bit of time to out rule caching... cause right now I have no other idea where this is coming from.
