### ISSUE TITLE
[PNI] Add Related Articles to Product Review Pages

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9976]
We can now (actually, for some time now) add related articles to product review pages. The goal is to add related articles (3) to the top 15 most viewed product review pages in PNI. We can track progress in this [spreadsheet](https://docs.google.com/spreadsheets/d/1uHfnTP7cyU85qfh8AY8Nk7kuHIcPYjNBnw0aSpfLpvs/edit?usp=sharing).

**Goals**
- [x] Identify top 15 most viewed product review pages on PNI
- [x] Add page links to [spreadsheet](https://docs.google.com/spreadsheets/d/1uHfnTP7cyU85qfh8AY8Nk7kuHIcPYjNBnw0aSpfLpvs/edit?usp=sharing)
- [x] Add three related articles for each product

**Comment by beccaklam** [comment]
I've added articles for 15 product pages for now. There's still some product pages identified that we could add articles too in the spreadsheet but closing this ticket for now.

**Comment by kristinashu** [comment]
Thank you!!!
