### ISSUE TITLE
Fix missing news icons

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#998]
The news section was designed with very nice icons for each news source but in practice the number to news items as been too many to keep up with so icons are almost always missing.

#### Production:
<img width="1054" alt="screen shot 2018-01-25 at 11 03 04 am" src="https://user-images.githubusercontent.com/1068783/35407270-3d7f3ed6-01c0-11e8-867a-7968bce8dc79.png">

@taisdesouzalessa @sabrinang @gvn @xmatthewx how do you feel about removing the icons all together and putting Source, Author, and Date all on one line. This helps to clean up several different font styles and reduces vertical space.

#### Something along these lines:
<img width="962" alt="screen shot 2018-01-25 at 11 08 24 am" src="https://user-images.githubusercontent.com/1068783/35407272-3da6fbec-01c0-11e8-9dc2-6d9ed94e101c.png">

**Comment by gvn** [comment]
That seems great to me. The icons have definitely been a pain point...

**Comment by xmatthewx** [comment]
I'm unsure. 

Pro: It looks cleaner for sure. 

Con: Publication name at the top helps signal that these articles are elsewhere, not on the site. Publication name and icon (when present) lend legitimacy. 

I think Jesse has plans to evolve the homepage in the not too distant future. Let's consider this as part of that, rather than making a change sooner.

**Comment by taisdesouzalessa** [comment]
I agree with the Pros and Cons pointed above by Matthew. I remember talking to Kevin about those news items during a work week and if I am not mistaken, having those logos was a positive thing, from his point of view.

I do agree that, in practice, we are not being very good at maintaining the structure by uploading the logos, though.

**Comment by xmatthewx** [comment]
Might just require a bit more training for users.
