### ISSUE TITLE
Add more styling options to `Callout` block

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9987]
## Description

Currently the `Callout` block only allows for bold text but more styling options would be helpful.

At the very least, it would be the best to add:
- Bullet list
- Links

Nice to have would be:
- Different heading styles

Screen cap of `Callout` block:
<img width="1280" alt="Screenshot 2023-01-18 at 4 32 54 PM" src="https://user-images.githubusercontent.com/1068783/213328004-a33d4fff-b2ed-480e-b6d1-065e38fd8e13.png">

<img width="600" alt="Screenshot 2023-01-18 at 4 33 20 PM" src="https://user-images.githubusercontent.com/1068783/213328015-a7f39f04-e599-46e6-9577-3d7be4a49ab7.png">

@nancyt1 can you please review this, is this what is needed for the ADG playbook?

Before adding ACs, I would like input from a dev on what styling options make sense to add from their perspective.

## Acceptance criteria

- [ ] As an editor, I can add italic text to the callout block richtext
- [ ] As an editor, I can add links to the callout block richtext (using Wagtails link functionality similar to what is in Paragraph links - Internal link using page chooser, external link, Email link, Phone link, and Anchor link)
- [ ] As an editor, I can add numbered lists to the callout block richtext
- [ ] As an editor, I can add bulleted lists to the callout block richtext
- [ ] As an editor, I can add headings to the callout block richtext of levels H2 - H4
- [ ] As a page visitor, I see the callout block content render the same as other richtext on the site
- [ ] As an editor, I don't loose any functionality that is currently on production (i.e. can still use Bold text)
- [ ] As a page visitor, I don't loose any styling that is currently on production (i.e. grey background box and grid/width remain the same)

**Comment by nancyt1** [comment]
@kristinashu Yes I think that's all we need! Could be nice to have the bold be a little more bold? I'm noticing now there's not a lot of contrast.

**Comment by kristinashu** [comment]
True, although the boldness of body-large might be a bigger issue with our styles https://foundation.mozilla.org/style-guide/#paragraphs.

@mtdenton @cdanfon could this ticket be groomed at your next grooming meeting or is there a dev that could help scope it so it gets into next sprint?

**Comment by cdanfon** [comment]
Thanks @kristinashu 

@mtdenton Our next scheduled _Grooming_ session will be replaced by the _ACs workshop_ - are you OK to arrange a _Grooming_ session with the devs on a different day?

**Comment by kristinashu** [comment]
Note that the stakeholder for the project that needs this (the ADG playbook) will start adding content in on Feb 3 so it would be ideal to have this live on prod before then.

**Comment by cdanfon** [comment]
Hey @kristinashu the current sprint spans from Jan 23 - Feb 6. This didn't make the cut for planning as it wasn't groomed. If this is an urgent/deal-breaker request it would be the case of negotiating this to be included in the current sprint and removing one of the tickets we've committed to.

**Comment by kristinashu** [comment]
Thanks Claudia! I didn't realize we were so close to Feb already! It is not urgent. Content entry will begin then but it won't launch until later so next sprint works.

**Comment by tbrlpld** [comment]
@kristinashu Which heading levels should available in this richtext field? Only `h2`, `h2-h6` or a subset?

**Comment by tbrlpld** [comment]
@kristinashu We don't really have any context to answer "Before adding ACs, I would like input from a dev on what styling options make sense to add from their perspective." 

We can activate any of the standard richtext options. They should render like in any other richtext field.

**Comment by tbrlpld** [comment]
@kristinashu We have added AC during grooming session. Can you review them for sanity.

**Comment by kristinashu** [comment]
Thanks! If it's just about picking and choosing from the current Paragraph styles then I would say to add:
- Italic
- H2 - H4
- Numbered list
- Bullet list
- Links (using what is available in the Paragraph links - Internal link using page chooser, external link, Email link, Phone link, and Anchor link)

Should I update the ACs with this?

**Comment by tbrlpld** [comment]
@kristinashu Yes, that would be great.

**Comment by kristinashu** [comment]
ACs have been updated! I also added a couple to make sure we don't loose any of the existing styling or functionalit but let me know if that is overkill.

**Comment by kristinashu** [comment]
@cdanfon did this make it into the sprint?

**Comment by cdanfon** [comment]
Hey @kristinashu we prioritised this ticket to include it in the sprint, but after consulting with the developers we decided to hold and include it in the sprint after (20th Feb - 6th Mar) as the work for it would involve mainly BE work. 

With the Wagtail upgrade we've limited the amount of BE we're committing to during this sprint as this couldn't be started until the upgrade has been completed.

**Comment by cdanfon** [comment]
Agree during planning that @danielfmiranda will be picking up this ticket today with the aim to do a prod push tomorrow.

**Comment by kristinashu** [comment]
Thank you @danielfmiranda @mmmavis! I see this on staging now and it looks great!
