### ISSUE TITLE
[MAIT report] Datawrapper graphs: Part I

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9989]
The Meaningful AI Transparency (MAIT) report needs support creating datawrapper graphs. Ramy has provided the csv files and will tag in this draft which graphs need to be integrated with datawrapper. Ramy has also expressed that she would appreciate some variety and creativity in the format of the graphs.

**Assets**
[csv file](https://drive.google.com/file/d/1OaC9w5NgaPbxDw724lpJN0WXo6Ih4eMf/view?usp=share_link)
[MAIT draft with current graphs](https://docs.google.com/document/d/18KyJzLZvIBq0TlHm59NZMbNVEhfprnWrYmreEb-rnbA/edit?usp=sharing)

**Goals:**
- [x] Finalize what graphs Ramy needs recreated in Datawrapper
- [x] Import data in Datawrapper
- [x] Create first draft of graphs
- [ ] Gather feedback from design and Ramy

Next ticket
- Finalize graphs
- Test in Publication
- Finalize in Publication

**Comment by kristinashu** [comment]
Is this part one good to close?

**Comment by nancyt1** [comment]
Yes, closing!
