### ISSUE TITLE
[MAIT report] Start laying out report in Publication

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9991]
Most of the content for the MAIT report is final and so we can begin laying it out in the publication. Ramy is still deciding on how to divvy up the content but we can start exploring graphic placement, etc. 

**Assets**
[MAIT report draft](https://docs.google.com/document/d/18KyJzLZvIBq0TlHm59NZMbNVEhfprnWrYmreEb-rnbA/edit?usp=sharing) (content ready from "1. Key Findings" onwards
[Illustrations](https://drive.google.com/drive/folders/1mWs2SFu3eHZb6aZuuhJ8rKOHS1Q2VRHD?usp=sharing)

**Goals:**
- [x] Start planning how content could be divided in Publication
- [x] Create Publication and layout one Article page (to show Ramy how it is looking)
- [ ] Add Illustrations
- [ ] Explore how we can add a more "accessible section" to the publication potentially using assets created from #9990

**Comment by nancyt1** [comment]
Started laying out draft into [publications](https://foundation.mozilla.org/en/research/library/ai-transparency-in-practice/ai-transparency-in-practice/)

**Comment by nancyt1** [comment]
Started laying out report but Ramy said there's gonna be more changes in the sections now so I just set up the structure and will get feedback before moving forward.
